### ISSUE TITLE
Framework dependency extracts -I in addition to framework, leading to endless include recursion

### ISSUE THREAD

**Issue by anarazel** [mesonbuild/meson#10002]
Hi,

On macOS, building a project using the system ldap as a dependency fails to compile. Appears to be a more generic issue that manifests badly in this case.

```shell
$ meson --version
0.61.1
```

meson.build:
```meson
project('repro', ['c'])

ldap = dependency('ldap', required: true, method: 'auto')

static_library('repro',
  sources: ['uses_ldap.c'],
  dependencies: [ldap],
)
```
uses_ldap.c:
```C
#include <ldap.h>
```

invocation:
```
$ meson setup build
The Meson build system
Version: 0.61.1
Source dir: /Users/andres/src/repro
Build dir: /Users/andres/src/repro/build
Build type: native build
Project name: repro
Project version: undefined
C compiler for the host machine: ccache cc (clang 13.0.0 "Apple clang version 13.0.0 (clang-1300.0.29.30)")
C linker for the host machine: cc ld64 711
Host machine cpu family: aarch64
Host machine cpu: arm64
Found pkg-config: /opt/homebrew/bin/pkg-config (0.29.2)
Run-time dependency ldap found: YES (/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/LDAP.framework)
Build targets in project: 1

Found ninja-1.10.2 at /opt/homebrew/bin/ninja

```shell
m1-dev:repro andres$ ninja -C build -v
ninja: Entering directory `build'
[1/2] ccache cc -Ilibrepro.a.p -I. -I.. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/LDAP.framework/Headers -fcolor-diagnostics -Wall -Winvalid-pch -O0 -g -F/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/LDAP.framework -MD -MQ librepro.a.p/uses_ldap.c.o -MF librepro.a.p/uses_ldap.c.o.d -o librepro.a.p/uses_ldap.c.o -c ../uses_ldap.c
FAILED: librepro.a.p/uses_ldap.c.o 
ccache cc -Ilibrepro.a.p -I. -I.. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/LDAP.framework/Headers -fcolor-diagnostics -Wall -Winvalid-pch -O0 -g -F/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/LDAP.framework -MD -MQ librepro.a.p/uses_ldap.c.o -MF librepro.a.p/uses_ldap.c.o.d -o librepro.a.p/uses_ldap.c.o -c ../uses_ldap.c
In file included from ../uses_ldap.c:1:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/LDAP.framework/Headers/ldap.h:1:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/LDAP.framework/Headers/ldap.h:1:
[~200 repetitions omitted]
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/LDAP.framework/Headers/ldap.h:1:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/LDAP.framework/Headers/ldap.h:1:10: error: #include nested too deeply
#include <ldap.h>
         ^
1 error generated.
ninja: build stopped: subcommand failed.
```

The problem is that -I was extracted in addition to the -F.

Failing build step:
```
ccache cc -Ilibrepro.a.p -I. -I.. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/LDAP.framework/Headers -fcolor-diagnostics -Wall -Winvalid-pch -O0 -g -F/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/LDAP.framework -MD -MQ librepro.a.p/uses_ldap.c.o -MF librepro.a.p/uses_ldap.c.o.d -o librepro.a.p/uses_ldap.c.o -c ../uses_ldap.c
```
manually corrected build step:
```
ccache cc -Ilibrepro.a.p -I. -I.. -fcolor-diagnostics -Wall -Winvalid-pch -O0 -g -F/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/LDAP.framework -MD -MQ librepro.a.p/uses_ldap.c.o -MF librepro.a.p/uses_ldap.c.o.d -o librepro.a.p/uses_ldap.c.o -c ../uses_ldap.c
```

Regards,

Andres

**Comment by nirbheek** [comment]
Yeah, we shouldn't add `-I` there. That's not how a framework is supposed to work. However, some frameworks do rely on that (particularly those that are simply aggregates of separate projects), so maybe we should make it opt-in.

**Comment by anarazel** [comment]
> However, some frameworks do rely on that (particularly those that are simply aggregates of separate projects), so maybe we should make it opt-in.

Do you happen to know an example of such a framework? Would be useful to see why those aren't a problem with several buildsystems etc.

**Comment by nirbheek** [comment]
The gstreamer framework does that: https://gstreamer.freedesktop.org/download/#macos, and the reason is that frameworks are kind of the only way to distribute libraries / SDKs on macOS. It treats `/Library/Frameworks/GStreamer.framework/Headers` as `/usr/include`, and expects people to do `#include <gst/gst.h>`, but when using a framework you're supposed to do `#include <GStreamer/gst/gst.h>`.

But that won't work, because gstreamer headers depend on a bunch of other projects like glib which expect `#include <glib.h>` et al but they should *also* be `#include <GStreamer/glib.h>` etc, which is not what the gstreamer headers do (or other projects like pango, cairo, etc). So the only way out is to add `-I/Library/Frameworks/GStreamer.framework/Headers`. 

Now it seems that this breaks projects like LDAP, so the `add -I` behaviour should be opt-in, or maybe we could autodetect it somehow.

**Comment by anarazel** [comment]
Hm. It looks like a solution to this issue could be to add framework headers using -idirafter, so that system headers would continue to "preempt" the framework headers? I don't know how invasive that'd be.

**Comment by tristan957** [comment]
I found the code for this at https://github.com/mesonbuild/meson/blob/master/mesonbuild/dependencies/framework.py#L73-L79. I will put it on my list of things to get to for 1.3.0. I will add a kwarg, but it seems like it should default to false. Otherwise you might break existing builds?

**Comment by tristan957** [comment]
This is now prioritized for me. Stay tuned for a PR very soon, though I won't be able to test it except through CI. No Apple hardware :)

**Comment by tristan957** [comment]
Would appreciate if you could test the PR when you get a chance.
