### ISSUE TITLE
add alias both_library for both_libraries

### ISSUE THREAD

**Issue by milahu** [mesonbuild/meson#10057]
for consistency (and for typos)

```
static_library
shared_library
both_libraries
both_library # expected error message: did you mean "both_libraries"?
```

actual error message is

```
ERROR: Unknown function "both_library".
```

**Comment by eli-schwartz** [comment]
I do not believe it is advisable to add multiple spellings of a function.

Especially as a mechanism of solving the issue where it tells you the function doesn't exist, but you wanted it to advise you about functions with similar names you might have meant. If such a feature is desirable, it could be added without making multiple function names work... also it would work with a much wider variety of possible misspellings.

**Comment by xclaesse** [comment]
Sounds like something an IDE could help with autocomplete suggestions.
