### ISSUE TITLE
WARNING: Unknown CPU family 'loongarch64'

### ISSUE THREAD

**Issue by choumin** [mesonbuild/meson#10062]
LoongArch is a new CPU architecture. Please add support in meson. Thank you very much.

loongson@loongson-pc:~$ uname -a
Linux loongson-pc 4.19.0-14-loongson-3 #1 SMP Fri Oct 29 01:36:47 UTC 2021 loongarch64 loongarch64 loongarch64 GNU/Linux

loongson@loongson-pc:~$ cat /proc/cpuinfo 
system type		: generic-loongson-machine
processor		: 0
package			: 0
core			: 0
cpu family		: Loongson-64bit
model name		: Loongson-3A5000LL
CPU Revision		: 0x10
FPU Revision		: 0x00
CPU MHz			: 2300.00
BogoMIPS		: 4600.00
TLB entries		: 2112
Address sizes		: 48 bits physical, 48 bits virtual
isa			: loongarch32 loongarch64
features		: cpucfg lam ual fpu lsx lasx complex crypto lvz lbt_x86 lbt_arm lbt_mips
hardware watchpoint	: yes, iwatch count: 8, dwatch count: 8

processor		: 1
package			: 0
core			: 1
cpu family		: Loongson-64bit
model name		: Loongson-3A5000LL
CPU Revision		: 0x10
FPU Revision		: 0x00
CPU MHz			: 2300.00
BogoMIPS		: 4600.00
TLB entries		: 2112
Address sizes		: 48 bits physical, 48 bits virtual
isa			: loongarch32 loongarch64
features		: cpucfg lam ual fpu lsx lasx complex crypto lvz lbt_x86 lbt_arm lbt_mips
hardware watchpoint	: yes, iwatch count: 8, dwatch count: 8

processor		: 2
package			: 0
core			: 2
cpu family		: Loongson-64bit
model name		: Loongson-3A5000LL
CPU Revision		: 0x10
FPU Revision		: 0x00
CPU MHz			: 2300.00
BogoMIPS		: 4600.00
TLB entries		: 2112
Address sizes		: 48 bits physical, 48 bits virtual
isa			: loongarch32 loongarch64
features		: cpucfg lam ual fpu lsx lasx complex crypto lvz lbt_x86 lbt_arm lbt_mips
hardware watchpoint	: yes, iwatch count: 8, dwatch count: 8

processor		: 3
package			: 0
core			: 3
cpu family		: Loongson-64bit
model name		: Loongson-3A5000LL
CPU Revision		: 0x10
FPU Revision		: 0x00
CPU MHz			: 2300.00
BogoMIPS		: 4600.00
TLB entries		: 2112
Address sizes		: 48 bits physical, 48 bits virtual
isa			: loongarch32 loongarch64
features		: cpucfg lam ual fpu lsx lasx complex crypto lvz lbt_x86 lbt_arm lbt_mips
hardware watchpoint	: yes, iwatch count: 8, dwatch count: 8

**Comment by eli-schwartz** [comment]
Which version of Meson are you using? This was added in #8300 (released in Meson 0.57.0) and reported again in #9405.

This is the third ticket about it, so maybe a common distro for people to work on loongarch64 is still stuck on an older Meson version?

If it's based on Debian 11 (bullseye) then there is a backports version of Meson 0.61.1 so please make sure you have those enabled.

**Comment by choumin** [comment]
> Which version of Meson are you using? This was added in #8300 (released in Meson 0.57.0) and reported again in #9405.
> 
> This is the third ticket about it, so maybe a common distro for people to work on loongarch64 is still stuck on an older Meson version?
> 
> If it's based on Debian 11 (bullseye) then there is a backports version of Meson 0.61.1 so please make sure you have those enabled.

Thanks for your reply. The version of meson I used is 0.56.2. Now I know I need to upgrade its version.
