### ISSUE TITLE
Cannot compile libclang even as a submodule.

### ISSUE THREAD

**Issue by Makogan** [mesonbuild/meson#10097]
**Describe the bug**
I am trying to use libclang as a dependency for my project. i have tried 3 different approaches.

Approach n1, as a regular dependency:

I tried:
```
dependency('clang') 
dependency('libclang') 
dependency('libclang-dev') 
dependency('libclang-cpp-dev')
```

None of them are found

Approach n2, compile from source using the cmake module:
```
cmake = import('cmake')
cmake_opts = cmake.subproject_options()
cmake_opts.add_cmake_defines({'CMAKE_POSITION_INDEPENDENT_CODE': true})
sub_proj = cmake.subproject('clang', options : cmake_opts)
clang = sub_proj.dependency('clang')
```

Meson terminates with this error:
`../subprojects/clang/meson.build:0:0: ERROR: Can't link non-PIC static library 'clangBasic' into shared library 'clang_cpp'. Use the 'pic' option to static_library to build with PIC.`

No such error is emitted if compiling directly (i.e. inside the directory).

Approach n3, manually loading from system files:

```
libclang = declare_dependency(
    dependencies: cpp.find_library('libclang', dirs : '/usr/lib/llvm-13/lib/'),
    include_directories: include_directories('/usr/lib/llvm-13/include/'),
)
```

if used as a dependency causes the following linker error:
```
/usr/bin/ld: TestExample.p/Examples_main.cpp.o: undefined reference to symbol '_ZN6NECore7Gallery14GetGpuMeshDataERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'
/usr/bin/ld: /home/makogan/neverengine_personal/Source/build-clang/Modules/Core/libne_core.so: error adding symbols: DSO missing from command line
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[2/2] Linking target Modules/Peripherals/libne_peripherals.so
```

Is it possible to link clang in any way?

**To Reproduce**
Try any of the above in a project using clang.

**Expected behavior**
A project with the header `#include "clang-c/Index.h"` Should compile.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
no
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
Ubuntu 21,04
* what Python version are you using e.g. 3.8.0
3.9.7
* what `ninja --version` if it's a Ninja build
1.10.1
* Meson version
0.61.1

**Comment by tristan957** [comment]
> dependency('clang') 

should be 

> find_library('clang')

Doesn't look like clang ships a pkg-config file.

For approach number 2, it is hard to say what is wrong without seeing your project. What is clangBasic for instance? Did you try doing what the error message said and setting `pic: true` on your library?

**Comment by dcbaker** [comment]
Because cmake this has to be `dependency('Clang', method : 'cmake', modules : ['clangBasic', ...])` The capitalization matters, and you have to pass modules. Alternatively you have to do some painful wrapping like:
```meson
dep_clang = null_dep
llvm_libdir = dep_llvm.get_variable(cmake : 'LLVM_LIBRARY_DIR', configtool: 'libdir')

clang_modules = [
  'clangBasic', 'clangAST', 'clangCodeGen', 'clangLex',
  'clangDriver', 'clangFrontend', 'clangFrontendTool',
  'clangHandleCXX', 'clangHandleLLVM', 'clangSerialization',
  'clangSema', 'clangParse', 'clangEdit', 'clangAnalysis'
]

dep_clang = []
foreach m : clang_modules
  dep_clang += cpp.find_library(m, dirs : llvm_libdir, required : true)
endforeach
```
(from mesa, which is MIT licensed)

**Comment by tristan957** [comment]
Thanks for adding on to my comment. I thought there was something custom around this functionality, but I was too lazy to look at the docs myself! In addition, here is the documentation that refers to what @dcbaker just wrote: https://mesonbuild.com/Dependencies.html#llvm

**Comment by Makogan** [comment]
Sorry I am still a little lost, based on teh feedback and reading the documentation I tried doing this:

```
llvm_dep = dependency('llvm', version : '>= 4.0', modules : [])
llvm_link = find_program(llvm_dep.get_variable(configtool: 'bindir') / 'clang-cpp')
```

And then when compiling the executable:

```

dependencies = [
    core_dep,
    gtest,
    glfw,
    stb_image,
    shaderc,
    vk_memory_allocation,
    vulkan,
    eigen,
    cereal,
    llvm_dep,

    profiler_dep
]

renderer_lib = shared_library(
    'ne_renderer',
    sources : renderer_sources,
    link_with : [],
    include_directories : [],
    dependencies : dependencies)
 ```
 
 It seems this does not include the right headers, I get the following when compiling:
 
 ```
 ../Modules/Renderer/ShaderProgram.hpp:6:10: fatal error: 'clang-c/Index.h' file not found
#include "clang-c/Index.h"
```

How do you specify the include directories?

**Comment by eli-schwartz** [comment]
> Sorry I am still a little lost, based on teh feedback and reading the documentation I tried doing this:
> 
> ```
> llvm_dep = dependency('llvm', version : '>= 4.0', modules : [])
> llvm_link = find_program(llvm_dep.get_variable(configtool: 'bindir') / 'clang-cpp')
> ```

Why are you following unrelated instructions from the docs on "how to find the llvm-link program as a find_program() external program"?

Why are you finding clang-cpp the program instead, but naming it a meson variable "llvm-link"?

@dcbaker suggested a good way to achieve your goal, and I suspect the simplest solution would be to use:

> Because cmake this has to be `dependency('Clang', method : 'cmake', modules : ['clangBasic', ...])` The capitalization matters, and you have to pass modules.

**Comment by tristan957** [comment]
I did not understand that `clangBasic` came from clang itself. I think you need to add the `pic: true` to shared_library(), although I don't really understand if `pic` applies to shared libraries. `link_with` can be removed from your shared_library() call as can the empty include directories kwarg. I also recommend using `library()` over `shared_library()`.

On my Fedora 35 machine, clang-c/Index.h is located in /usr/include, but I had to install llvm-devel.

**Comment by tristan957** [comment]
Here is an example which uses LLVM: https://github.com/mesonbuild/meson/blob/master/test%20cases/frameworks/15%20llvm/meson.build

**Comment by haoyu234** [comment]
On my fedora36 system, I use `libclang = dependency('Clang', modules: ['libclang'])` to link libclang library, but don't know why it's Clang and not clang. other requirements:
```bash
sudo yum install clang-devel
sudo yum install llvm-devel
```

**Comment by tristan957** [comment]
^ I don't think that is right. If something like that were to work, it would need to be dependency('llvm', modules: ['libclang']). `Clang` isn't a thing in https://mesonbuild.com/Dependencies.html#dependencies-with-custom-lookup-functionality

**Comment by haoyu234** [comment]
but it does work 
![use Clang](https://user-images.githubusercontent.com/19519128/192672087-39668132-ee6f-43ec-a33c-aa82ba8b04be.png)

**Comment by tristan957** [comment]
Can you point out where in the code base you are finding this support because it isn't documented?
