### ISSUE TITLE
Improve asm support

### ISSUE THREAD

**Issue by xclaesse** [mesonbuild/meson#10101]
Assembly is a can of worms that Meson is not touching. Every project do their own tricks with custom_target() and generator(). I'm opening this issue to collect what are the actual use-cases and discuss what Meson could do to help.

- `.asm` -> nasm 

This is pretty easy to support by adding the `nasm` language that will compile every `.asm` file with nasm.

=> Done: https://github.com/mesonbuild/meson/pull/9379.

- `.asm` -> yasm

yasm seems pretty much compatible with nasm and could be used as fallback when nasm program is not found. However it does not support generating depfile at the same time as compiling the file, so it requires a small wrapper script that we can easily add into Meson: [run_yasm.py](https://chromium.googlesource.com/chromium/src/third_party/yasm/+/530de22e88b9b90d6e0711ea6cfcd13e6eae7e7f/run_yasm.py)

I don't think we should add a dedicated `yasm` language, but simply fallback to the wrapper script when adding `nasm` language and the `nasm` program is not found. ok?

=> Done: https://github.com/mesonbuild/meson/pull/9379.

- `.s` -> gcc 

This has always been supported by Meson, but depfile is broken: https://github.com/mesonbuild/meson/issues/9849.

=> We need to use gcc for preprocessing and then compile using gas directly.

- `.s` -> clang

Meson already build `.s` files with clang, but unfortunately it seems clang does not support the same preprocessing for `.s` files as gcc. There is a [gas-preprocessor.pl](https://github.com/libav/gas-preprocessor/blob/master/gas-preprocessor.pl) that people uses to do the preprocessing.

If we translate that script to python and include it in Meson, we could wrap clang and compile `.s` files with both gcc and clang transparently.

- `.s` -> msvc

With MSVC `.s` files needs to be first preprocessed using `cl /P` and the compiled with `ml`, `ml64`, `armasm`, or `armasm64`. See https://github.com/mesonbuild/meson/issues/9889.

Question: Is that the same dialect as gcc `.s` ?

**Comment by bonzini** [comment]
> Question: Is that the same dialect as gcc .s ?

For ARM I don't know. For x86 the only portable way is nasm/yasm.

**Comment by dcbaker** [comment]
> This has always been working out of the box with Meson, but I saw @dcbaker complaining there are issues with depfile? Is there something we can do here?

https://github.com/mesonbuild/meson/issues/9849

Basically the only way to make this work reliably is to *not* use gcc/clang, but to invoke gas directly. The downside is that we have to run gcc/clang for preprocessing .S files into .s files

**Comment by xclaesse** [comment]
> The downside is that we have to run gcc/clang for preprocessing .S files into .s files

It's not that bad actually, because that's exactly what we need to do for MSVC too. They all can share the same workflow.

**Comment by xclaesse** [comment]
> For ARM I don't know. For x86 the only portable way is nasm/yasm.

Question is, on windows with MSVC, is it safe to assume that `.s` files are compiled with cl/ml and `.asm` files with nasm?

**Comment by bonzini** [comment]
> Question is, on windows with MSVC, is it safe to assume that .s files are compiled with cl/ml and .asm files with nasm?

No, on Windows they would likely use `.asm` for cl (masm syntax) and `.nasm` for nasm/yasm. I think for now we should only cover x86+nasm/yasm, and stick with the `.nasm` extension on either Windows or Linux systems. For legacy reasons `.s` can be supported with gcc only (not clang or MSVC).

Figuring out a portable solution for clang and MSVC could be done when looking at ARM.

**Comment by xclaesse** [comment]
> No, on Windows they would likely use `.asm` for cl (masm syntax) and `.nasm` for nasm/yasm.

I'm trying to collect real world examples, in the case of libffi they have `.S` files that gets preprocessed by cl and compiled by ml64.exe (that's MASM I guess).

https://gitlab.freedesktop.org/gstreamer/meson-ports/libffi/-/blob/5330111d527dd5671a31e586d579c29f12c345e4/src/meson.build#L23-69

Do you have counter examples? I think ultimately we'll have to make it configurable because I'm pretty sure that's completely inconsistent across all projects.

**Comment by dcbaker** [comment]
@bonzini do you mean no .s with clang in general, or only on windows? We use .s files with clang in mesa, but I don't think we use them on windows.
