### ISSUE TITLE
how to write meson.build when crosscompiling with emscripten

### ISSUE THREAD

**Issue by Cartman0** [mesonbuild/meson#10102]
hi!
i want example codes how to write `meson.build` when crosscompiling with emscripten.

I tried follow code, then can run at least.
but will compile in 2-step.
if i want 1step comple such as `emcc -c hello.c -o hello.js -s WASM=1`, how can control?

```
$ meson setup build_to_wasm/build build_to_wasm  --cross-file wasm.ini
$ cd build_to_wasm/build
$ meson compile --verbose

[1/2] emcc -Ihello.js.js.p -I. -I.. -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O0 -g -MD -MQ hello.js.js.p/.._hello.c.o -MF hello.js.js.p/.._hello.c.o.d -o hello.js.js.p/.._hello.c.o -c ../../hello.c
[2/2] emcc  -o hello.js.js hello.js.js.p/.._hello.c.o -s ERROR_ON_UNDEFINED_SYMBOLS=1 -s EXPORT_ALL=1 -s WASM=1
```

`meson.build`:

```.build
project('c2wasm', 'c')

src = '../hello.c'
executable('hello.js', src, link_args: [
    '-s','WASM=1'
])
```

`wasm.ini`: 

```.ini
# ref: https://github.com/mesonbuild/meson/blob/master/cross/wasm.txt
[binaries]
c = 'emcc'
cpp = 'em++'
ar = 'emar'
wasm = '/wabt/bin/wasm2wat'
wat = '/wabt/bin/wat2wasm'

[built-in options]
c_args = []
c_link_args = ['-s','EXPORT_ALL=1']
cpp_args = []
cpp_link_args = ['-s', 'EXPORT_ALL=1']

[properties]
c_args = []
c_link_args = []
cpp_args = []
cpp_link_args = []

static_library_suffix = 'la'
shared_library_suffix = 'js'
shared_module_suffix = 'js'

[host_machine]
system = 'emscripten'
cpu_family = 'wasm'
cpu = 'wasm'
endian = 'little'
```

dir :

```
- Project/
  - wasm.ini
  - hello.c
  - build_to_wasm/
    - meson.build
    - build/
```

**Comment by Cartman0** [comment]
And, how to set options to output only `.wasm` file such as `emcc -c hello.c -o hello.wasm` ?

follow codes can run : 

```.build
project('c2wasm', 'c')

src = '../hello.c'
executable('hello.js', src, link_args: [
    '-s','WASM=1',
    '-o', 'hello.wasm'
])
```

but "-o" option are set in duplicate. how to solve it?

```
$ meson compile --verbose
[1/2] emcc -Ihello.js.js.p -I. -I.. -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O0 -g -MD -MQ hello.js.js.p/.._hello.c.o -MF hello.js.js.p/.._hello.c.o.d -o hello.js.js.p/.._hello.c.o -c ../../hello.c
[2/2] emcc  -o hello.js.js hello.js.js.p/.._hello.c.o -s ERROR_ON_UNDEFINED_SYMBOLS=1 -s EXPORT_ALL=1 -s WASM=1 -o hello.wasm
```

**Comment by Cartman0** [comment]
Third, how to crosscompile-chain from `emcc .c` to `wasm2wat .wasm`, and finally build to `.wat`?

**Comment by tristan957** [comment]
Usually best to ask these types of questions in the matrix/irc channel. More people watch that channel than do github issue.

**Comment by Cartman0** [comment]
@tristan957 thx for rep. i joined to matrix channel, will ask it. but i want example patterns.

**Comment by tristan957** [comment]
https://github.com/taisei-project/taisei/tree/master

Is an example that you could follow

**Comment by tristan957** [comment]
PRs are welcome. None of the people that I know who contribute to this project work with emscripten. I am sure @jpakkane would love to add an emscripten document on the website for documentation purposes.

**Comment by Cartman0** [comment]
@tristan957 ok. if i'm used to how to use meson, try to write in doc. i want to add because i want diagrams drawn with such as mermaid..
