### ISSUE TITLE
generate_gir doesn't pick up internally-available dependency .gir files

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#1012]
First reported at https://bugzilla.gnome.org/show_bug.cgi?id=774044

Steps to reproduce:

1. Remove gstreamer1-devel (or move the .gir files away)
2. Build gst-build which will build `Gst-1.0.gir` inside the `gstreamer` subproject, and then use it to build `GstBase-1.0.gir` inside the `gst-plugins-base` subproject.

`FAILED: subprojects/gstreamer/libs/gst/base/GstBase-1.0.gir`
`Couldn't find include 'Gst-1.0.gir' (search path: '['/home/nirbheek/projects/repositories/gst/gst-build/build/subprojects/gstreamer/.', '/home/nirbheek/projects/repositories/gst/gst-build/subprojects/gstreamer/.', '/home/nirbheek/projects/repositories/gst/gst-build/build/subprojects/gstreamer/libs', '/home/nirbheek/projects/repositories/gst/gst-build/subprojects/gstreamer/libs', u'gir-1.0', u'/usr/share/gir-1.0', u'/usr/share/gir-1.0', u'/usr/share/gir-1.0']')`

`Gst-1.0.gir` is in `build/subprojects/gstreamer/gst/Gst-1.0.gir`, which is also where the `declare_dependency` for `libgstreamer-1.0` is, so it should have been picked up. Somewhere we're not passing the right library search path to `g-ir-scanner`.

**Comment by tp-m** [comment]
Just one minor correction: there is no `gst-plugins-base` involved here. It's all in the same source module, which is `gstreamer`. It's just that we have various helper libraries in `gstreamer/libs/xyz/` which depend on the GStreamer core library in `gstreamer/gst/`.

**Comment by nirbheek** [comment]
Sorry, sleepy bug reporting. :)

**Comment by nirbheek** [comment]
The problem was using `link_with` to the shared library instead of `dependencies` which also contains the path to the gir file. Not a Meson bug, but the way we use girs is still a bit of a hack (different bug though).
