### ISSUE TITLE
Installed components (gtk4, desktop-file-utils) not detected by Meson

### ISSUE THREAD

**Issue by Ricky-Tigg** [mesonbuild/meson#10139]
**Describe the bug**
Installed components (gtk4, desktop-file-utils) not detected by Meson
```
$ dnf -q --installed list gtk4 desktop-file-utils | sed 1d
desktop-file-utils.x86_64                0.26-5.fc35                 @System
gtk4.x86_64                              4.4.2-1.fc35                @System
```

**To Reproduce**
```
$ meson --reconfigure builddir
The Meson build system
Version: 0.61.3
Source dir: /home/user/Downloads/Flatseal
Build dir: /home/user/Downloads/Flatseal/builddir
Build type: native build
Project name: flatseal
Project version: 1.7.5
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program desktop-file-validate found: YES (/usr/bin/desktop-file-validate)
Program appstream-util found: YES (/usr/bin/appstream-util)
Program glib-compile-schemas found: YES (/usr/bin/glib-compile-schemas)
Found pkg-config: /usr/bin/pkg-config (1.8.0)
Program glib-compile-resources found: YES (/usr/bin/glib-compile-resources)
Program glib-compile-resources found: YES (/usr/bin/glib-compile-resources)
Program gjs found: YES (/usr/bin/gjs)
Configuring com.github.tchx84.Flatseal using configuration
Program jasmine found: NO
Dependency gio-2.0 found: YES 2.70.4 (cached)
Program glib-compile-schemas found: YES (/usr/bin/glib-compile-schemas)
Found CMake: /usr/bin/cmake (3.22.2)
Build-time dependency gtk4 found: NO (tried pkgconfig and cmake)
Program gtk4-update-icon-cache found: YES (/usr/bin/gtk4-update-icon-cache)
Build-time dependency desktop-file-utils found: NO (tried pkgconfig and cmake)
Program update-desktop-database found: YES (/usr/bin/update-desktop-database)
Build targets in project: 22

Found ninja-1.10.2 at /usr/bin/ninja
```

**Expected behavior**
Installed components to be detected by Meson

**system parameters**
cross build: ?; plain native build: ?
(in plain English) build via 
```
$ git clone https://github.com/mesonbuild/meson.git`
$ meson builddir
```
**OS:** Fedora
```
$ pip3 -V
pip 21.2.3 from /usr/lib/python3.10/site-packages/pip (python 3.10)
```

**Comment by eli-schwartz** [comment]
> Build-time dependency gtk4 found: NO (tried pkgconfig and cmake)

It tries to look up the gtk4-devel pkg-config file, but it is wrong anyway. I actually tried testing this locally, and the problem is worse if you install the gtk4 devel package. You get a
```
WARNING: pkgconfig variable 'gtk4_update_icon_cache' not defined for dependency gtk4.
```

and with --fatal-meson-warnings the build just errors out.

> Build-time dependency desktop-file-utils found: NO (tried pkgconfig and cmake)

This is a Meson bug, there is no such dependency and never has been.

**Comment by Ricky-Tigg** [comment]
That's thanks to one of your previous comments elsewhere that i could determine it was an issue.

**Comment by e-lunev** [comment]
WARNING: CMake Toolchain: Failed to determine CMake compilers state
Run-time dependency gtk4 found: NO (tried pkgconfig and cmake)

src/meson.build:6:0: ERROR: Dependency "gtk4" not found, tried pkgconfig and cmake

5.18.0-kali5-amd64

**Comment by xclaesse** [comment]
@e-lunev do you have gtk4 devel package installed? `pkg-config --modversion gtk4` should tell if you have the gtk4.pc file.
