### ISSUE TITLE
dependency search method 'system' does not find winsock2 library

### ISSUE THREAD

**Issue by lb90** [mesonbuild/meson#10133]
**Describe the bug**
If I use the `dependency`'s search `method: system` on MSYS2 to get winsock2, Meson fails with the following error message:

    ws2_dep = dependency ('ws2_32', method: 'system')

    Run-time dependency ws2_32 found: NO
    ../Project/meson.build:5:0: ERROR: Dependency "ws2_32" not found

If instead I use

    meson.get_compiler('cpp').find_library('ws2_32')`

it is found.

**To Reproduce**

```meson
project ('MyProject', 'cpp', version: '1.0.0')

ws2_dep = dependency ('ws2_32', method: 'system')

# This works:
# cxx = meson.get_compiler('cpp')
# ws2_dep = cxx.find_library('ws2_32')
```

**Expected behavior**
The Winsock2 library should be found

**system parameters**
* Native build
* MSYS2 on Windows 10 x64
* Python 3.9.10
* Meson 0.61.2
* Ninja build 1.10.2

**Comment by eli-schwartz** [comment]
> If I use the `dependency`'s search `method: system` on MSYS2 to get winsock2

Unless it is documented as a custom dependency at https://mesonbuild.com/Dependencies.html#dependencies-with-custom-lookup-functionality this will not find anything.

`dependency()` is not and never has been `find_library()`, do not try to use them the same. :)

Custom dependencies are handpicked and manually implemented, and their purpose is to cover cases where `find_library()` isn't good enough. For example, the ***main*** use case of them is cases where a pkg-config dependency might not have a .pc file on BSD, and we want to be able to search for it anyway without coding a bunch of `required: false` and various fallbacks. Or in cases like intl and iconv, where you want to find a library, but the library might not be needed *iff* you use glibc as that is built in there and cannot be found. And also you want to know whether "either a library or a built-in symbol" is found.

The general rule of thumb is that unless a dependency has at least two methods of finding it (possible types include built-in, system, pkg-config, config-tool and cmake) or else the only method is config-tool which "screw that", there isn't going to be a custom dependency.
