### ISSUE TITLE
test's is_parallel argument default is not consistent with documentation

### ISSUE THREAD

**Issue by matshch** [mesonbuild/meson#10155]
**Describe the bug**
[Documentation](https://mesonbuild.com/Reference-manual_functions.html#test) states that default for `is_parallel` argument of `test()` is `false`. In practice, `meson` sets this argument to `true` by default.

**To Reproduce**
Create any project with `test()` without `is_parallel` specified, eg. call `meson init -l cpp` or use next example:
* `meson.build`:
```meson
project('cpp', 'cpp')
exe = executable('cpp', 'cpp.cpp')
test('basic', exe)
```

* `cpp.cpp`:
```cpp
int main() {
    return 0;
}
```

Then create build directory (`meson setup builddir`) and check introspection files:
```
$ jq .[0].is_parallel builddir/meson-info/intro-tests.json
true
```

**Expected behavior**
https://github.com/mesonbuild/meson/blob/a0cade8f1d1470cf3203baae16d181eb4df8e9fe/docs/yaml/functions/test.yaml#L53
[Documentation](https://mesonbuild.com/Reference-manual_functions.html#test) states that result should be `false`, so either documentation or implementation should be fixed.

**system parameters**
* native build
* Debian 11
* Python 3.9.2
* meson 0.61.1 (however I also checked meson 0.56.2 and 0.61.3 and got the same result)
* ninja 1.10.1

**Comment by eli-schwartz** [comment]
This has been the case since the original implementation, for the same reason that ninja is parallel by default.

During the port to the RefMan 2.0, this old documentation:
> `is_parallel`: when false, specifies that no other test must be running at the same time as this test

got changed to:

> ```
> default: false
> description: |
>     when false, specifies that no other test must be running at the same time as this test
> ```
