### ISSUE TITLE
Feature Request: Specify the name of scan-build executable with an environment variable

### ISSUE THREAD

**Issue by lantw44** [mesonbuild/meson#1015]
FreeBSD doesn't have a command called `scan-build`. Packages in ports use versioned names, such as `scan-build37`, `scan-build38`, `scan-build39`, because there is no default version and installing multiple versions is supported. It will be nice to allow specifying the name of scan-build with an environment variable, so we don't have to create a symlink and modify `PATH` to use the `scan-build` target.

**Comment by jpakkane** [comment]
Can you test if #1016 does what you'd expect?

**Comment by lantw44** [comment]
Yes, thanks for the patch.

**Comment by amitdo** [comment]
What about documenting this?
