### ISSUE TITLE
Cross Compilation uses the build machine's PKG_CONFIG_PATH instead of cross file's pkg_config_libdir

### ISSUE THREAD

**Issue by eitkin-nvidia** [mesonbuild/meson#10157]
**Describe the bug**
Cross compilation uses both PKG_CONFIG_LIBDIR **and** PKG_CONFIG_PATH, while the latter can't be set/modified through the cross file. While non-native dependencies won't be searched in the build system's directories, they will still be resolved using the PKG_CONFIG_PATH environment variable of the **build** machine **before** reverting to use PKG_CONFIG_LIBDIR as configured in the cross file.

This behavior is caused due to the fix of #7062.

**To Reproduce**
Files attached as an archive:
[reproduce.tar.gz](https://github.com/mesonbuild/meson/files/8316789/reproduce.tar.gz)

**meson.build:**
```
project('native/cross dep pkgconfig reproduce')

dep_native = dependency('json-c', native: true)
dep_cross  = dependency('json-c', native: false)

dep_version = dep_native.version()
assert(dep_version != '20', 'Expected 10 or the system\'s default version')

dep_version = dep_cross.version()
assert(dep_version == '20', 'Expected 20')
```

**Cross File:**
```
[binaries]
pkgconfig = 'pkg-config'

[properties]
pkg_config_libdir = '/root/workdir/cross_pkgconfig'
```

**Error build:** An example of incorrectly using the system's PKG_CONFIG_PATH by the cross build.
```
# PKG_CONFIG_PATH=/root/workdir/native_pkgconfig meson cross-build1 --cross-file=cross_file
The Meson build system
Version: 0.61.2
Source dir: /root/workdir
Build dir: /root/workdir/cross-build1
Build type: cross build
Project name: native/cross dep pkgconfig reproduce
Project version: undefined
Build machine cpu family: aarch64
Build machine cpu: aarch64
Host machine cpu family: aarch64
Host machine cpu: aarch64
Target machine cpu family: aarch64
Target machine cpu: aarch64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Build-time dependency json-c found: YES 0.13.1
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency json-c found: YES 10

meson.build:10:0: ERROR: Assert failed: Expected 20

A full log can be found at /root/workdir/cross-build1/meson-logs/meson-log.txt
```

**Successful build:** Ignoring the PKG_CONFIG_PATH so only the cross file is the one that matters.
```
# PKG_CONFIG_PATH= meson cross-build2 --cross-file=cross_file
The Meson build system
Version: 0.61.2
Source dir: /root/workdir
Build dir: /root/workdir/cross-build2
Build type: cross build
Project name: native/cross dep pkgconfig reproduce
Project version: undefined
Build machine cpu family: aarch64
Build machine cpu: aarch64
Host machine cpu family: aarch64
Host machine cpu: aarch64
Target machine cpu family: aarch64
Target machine cpu: aarch64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Build-time dependency json-c found: YES 0.13.1
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency json-c found: YES 20
Build targets in project: 0

native/cross dep pkgconfig reproduce undefined

  User defined options
    Cross files: cross_file

Found ninja-1.10.0 at /usr/bin/ninja
WARNING: Cross file does not specify strip binary, result will not be stripped.
WARNING: Cross file does not specify strip binary, result will not be stripped.
```

**Expected behavior**
The expected behavior is that both cases above will give the same output, which is the one used in the successful case. That is, the build machine's PKG_CONFIG_PATH should be ignored by non-native dependencies during a cross compilation. One can see that the system's directory is ignored (json-c 0.13.1 isn't the one found) but PKG_CONFIG_PATH is still used.

An additional option is to allow the cross file to override PKG_CONFIG_PATH, but the only reason I see to use it if pkg_config_libdir is defined is to just reset the system's value, which is the recommended fix altogether.

**system parameters**
* Cross Compilation
* Ubuntu 20.04
* Python version: 3.8.10
* Meson version: 0.61.2 (Happens in all versions >= 0.54.2)
* Example reproduce is from an aarch64 server, but it obviously reproduced to us on an x86_64 server and on other distributions as well.

**Comment by dcbaker** [comment]
This may seem odd, but I think this is working as expected.

You can combine PKG_CONFIG_PATH and PKG_CONFIG_LIBDIR, and there are absolutely reasons to want to do this (say because you have a cross root in /mnt/cross and you've built a dependency in ~/source/foo/install. The way our resolution works is that PKG_CONFIG_PATH is checked if the cross/native file doesn't set pkg_config_path, which is checked if -Dpkg_config_path isn't set. And, on top of that, there are people who would absolutely want to be able to use a cross file to set the libdir, then add additional paths with PKG_CONFIG_PATH.

**Comment by eli-schwartz** [comment]
> Cross compilation uses both PKG_CONFIG_LIBDIR **and** PKG_CONFIG_PATH, while the latter can't be set/modified through the cross file.

This is incorrect, because both `-Dpkg_config_path=...` and `-Dbuild.pkg_config_path=...` exist as settings.

Defining that in the cross file rather than the command line is documented at https://mesonbuild.com/Machine-files.html#meson-builtin-options and even mentions pkg_config_path in its "incomplete list of options".

**Comment by eitkin-nvidia** [comment]
Thanks @eli-schwartz. I missed the builtin-options section for the cross-file, as I tried to use "pkg_config_path" under "properties" the same way as "pkg_config_libdir" was declared in the cross file, and obviously it didn't work for me.

Thanks for the fast reply.
