### ISSUE TITLE
LINK-style link args passed to Windows clang even when cross-compiling for Unix-like

### ISSUE THREAD

**Issue by fghzxm** [mesonbuild/meson#10183]
**Describe the bug**
When trying to cross-compile from Windows to a Unix-like host, using a build of clang that defaults to the Windows target (but passing the correct `--target` and `--sysroot` arguments), Meson incorrectly generates linking invocations that passes LINK-style arguments to clang rather than the expected ld-style ones.

**To Reproduce**
I use cross-compiling for WASI as an example.
1. Install LLVM 13 for Windows to `C:\Program Files\LLVM` using the official installer.  Verify that it defaults to targeting Windows:
   ```
   > "C:\Program Files\LLVM\bin\clang.exe" --version
   clang version 13.0.0
   Target: x86_64-pc-windows-msvc
   Thread model: posix
   InstalledDir: C:\Program Files\LLVM\bin
   ```
2. Download [libclang_rt.builtins-wasm32-wasi-14.0.tar.gz](/WebAssembly/wasi-sdk/releases/download/wasi-sdk-14/libclang_rt.builtins-wasm32-wasi-14.0.tar.gz) and extract it under `C:\Program Files\LLVM\lib\clang\13.0.0\`:
   ```cmd
   :: in an elevated command prompt:
   curl -fSL https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-14/libclang_rt.builtins-wasm32-wasi-14.0.tar.gz | tar -C "C:\Program Files\LLVM\lib\clang\13.0.0" -xzf -
   dir "C:\Program Files\LLVM\lib\clang\13.0.0\lib\wasi"
   ```
3. Download [wasi-sysroot-14.0.tar.gz](https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-14/wasi-sysroot-14.0.tar.gz) and extract it under `C:\`:
   ```cmd
   curl -fSL https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-14/wasi-sysroot-14.0.tar.gz | tar -C C:\ -xzf -
   dir C:\wasi-sysroot
   ```
4. Create a Meson project containing:
   - `hello.c`:
     ```c
     int main() { return 0; }
     ```
   - `meson.build`:
     ```meson
     project('hello', 'c')
     executable('hello', 'hello.c')
     ```
   - `cross.ini`:
     ```ini
     [constants]
     sysroot = 'C:\\wasi-sysroot'
     args = ['--target=wasm32-wasi', '--sysroot=' + sysroot]

     [host_machine]
     system = 'wasi'
     cpu_family = 'wasm32'
     cpu = 'unknown'
     endian = 'little'

     [binaries]
     c = 'C:\\Program Files\\LLVM\\bin\\clang.exe'
     c_ld = 'lld'

     [properties]
     sys_root = sysroot

     [built-in options]
     c_args = args
     c_link_args = args
     ```
5. Generate and try to build the project:
   ```cmd
   > meson builddir --cross-file cross.ini
   > ninja -C builddir
   ninja: Entering directory `builddir'
   [2/2] Linking target hello
   FAILED: hello hello.pdb
   "C:\Program Files\LLVM\bin\clang.exe"  -Wl,/OUT:hello hello.p/hello.c.o "-Wl,/nologo" "-fuse-ld=lld" "-Wl,/DEBUG" "-Wl,/PDB:hello.pdb" "--target=wasm32-wasi" "--sysroot=C:\wasi-sysroot"
   wasm-ld: error: cannot open /OUT:hello: no such file or directory
   wasm-ld: error: cannot open /nologo: no such file or directory
   wasm-ld: error: cannot open /DEBUG: no such file or directory
   wasm-ld: error: cannot open /PDB:hello.pdb: no such file or directory
   clang: error: linker command failed with exit code 1 (use -v to see invocation)
   ninja: build stopped: subcommand failed.
   ```
6. Verify that linking is successful if clang is passed the correct arguments:
   ```cmd
   cd builddir
   "C:\Program Files\LLVM\bin\clang.exe" -o hello.wasm hello.p/hello.c.o -fuse-ld=lld -g --target=wasm32-wasi --sysroot=C:\wasi-sysroot
   "C:\Program Files\LLVM\bin\llvm-objdump.exe" -h hello.wasm
   ```

**Expected behavior**
1. It would be nice if Meson could generate the correct linking invocation in the first place in some easy scenarios (e. g. when the `system` property of the `[host_machine]` section points to a well-known Unix-like target like Linux).
2. Meson should provide a switch that overrides Meson's heuristics about the linker's command line argument style.

**system parameters**
Windows: 10.0.22572.1
Python: 3.11.0a6
Meson: 0.62.0
Ninja: 1.10.2

**Comment by eli-schwartz** [comment]
Does it help if you move the constant args to append it to the c/cpp binaries entries as an array in order to define $CC as inherently being that executable with specific arguments? As opposed to the current approach which passes it as c_args and isn't part of the compiler definition itself.

**Comment by fghzxm** [comment]
@eli-schwartz Thanks, that resolved the bulk of the issue (though the specific example with WebAssembly still doesn't work, because the linker is `wasm-ld` and Meson has yet to know about clang's ability to compile to WASM; I'll open a separate issue for that).
