### ISSUE TITLE
run_target() cannot depend on run_tgt

### ISSUE THREAD

**Issue by ManuelAtWork** [mesonbuild/meson#10198]
**Describe the bug**
Two run_targets must be executed in a particular order. Naturally, I made the second depend on the first one:
```
    rt1 = run_target('rt1', command : [...])
    rt2 = run_target('rt2', command : [...], depends : rt1)
```
However, Meson says that run_target() may only depend on BuildTarget or CustomTarget:
`ERROR: run_target keyword argument 'depends' was of type 'list' but should have been list[BuildTarget,CustomTarget]`

**Expected behavior**
The documentation does not narrow the subtypes of `tgt` to be used with run_target(). It should be possible to chain multiple run_targets, so that they are guaranteed to execute in sequential order.

**system parameters**
meson v60.3

**Comment by eli-schwartz** [comment]
Is it not possible to make the rt2 command inherently perform both tasks?

**Comment by ManuelAtWork** [comment]
Tried to wrap the `run_tgt` in a `custom_tgt`, but the `custom_target()` function has the same issue:
```
rt1 = run_target('rt1', command : [...])
ct1 = custom_target('ct1', [...], depends : rt1)
```
gives
`ERROR: custom_target keyword argument 'depends' was of type 'list' but should have been list[BuildTarget,CustomTarget]`

The [documentation](https://mesonbuild.com/Reference-manual_functions.html#custom_target) of `custom_target()` does not limit the dependencies:
![image](https://user-images.githubusercontent.com/79627623/160551993-a92e8f6e-7804-433a-8896-bf5817c6acc6.png)
