### ISSUE TITLE
Run Unit tests for each module

### ISSUE THREAD

**Issue by sittim** [mesonbuild/meson#1021]
I am trying to find an automated way to run module specific unit tests in VIM
using using a shortcut, have the following directory layout:

```
my_project/-+-src/-+-module1.h
            |      |
            |      +-module1.cpp
            |      |
            |      +-module2.h
            |      |
            |      +-module2.cpp
            |
            +-test/-+-build/
                    |
                    +-module1_test.cpp
                    |
                    +-module2_test.cpp
                    |
                    +-meson.build

```

Is it possible to use **command line to specify which source files to build**, for example
`module1_test.cpp` and run the test for just that executable?

**Comment by nirbheek** [comment]
This is not implemented yet, but is planned. See: #730 and #708 

Closing this for now.
