### ISSUE TITLE
Improve subproject target qualification

### ISSUE THREAD

**Issue by ManuelAtWork** [mesonbuild/meson#10221]
Let us assume the following setup:

- In `meson.build`, there is a target `t1`.
- There also is a subproject `subprojectA` which also has a target `t1`.

When you call `meson compile t1`, then an error will be reported:

`ERROR: Can't invoke target /db: ambiguous name. Add target type and/or path: PATH/NAME:TYPE`

**1. Suggestion: Improve error message**
Now I know that I must provide some path. But is it the path to the `meson.build`? The builddir? Name of some namespace?
Better:

```
ERROR: Can't invoke target /db: ambiguous name. Add target type and/or path: PATH/NAME:TYPE
Possible choices:
        pathA/db:typeA
        pathB/db:typeB
```
With the list of possible choices, I can quickly fix the problem.

**2. Suggestion: Change behaviour**
Targets in the subprojects should be shadowed by equal-named targets in the main project. (Because the main project is the closest scope.)
- If there is a name conflict among targets in the main project and subprojects, then the main project should have precedence.
- Targets in subprojects can be referenced with the path/namespace mechanism.

**Comment by eli-schwartz** [comment]
I don't know how `meson compile` works, but this already works fine with `ninja`.

There are anyways things you cannot (by design) do with the former, and it will always just immediately run ninja anyway...

**Comment by xclaesse** [comment]
@ManuelAtWork It would be great to print all targets that match, yes. Could you propose a patch for that please?

@eli-schwartz I don't think ninja does anything about that, if you don't give the full path it just says the target is unknown and won't try to suggest anything.

**Comment by xclaesse** [comment]
One thing I've been wanting for a while is typing "meson compile foo.c.o" and it just build it whatever subdir it's in, or print all paths if there are more than one foo.c file.

**Comment by eli-schwartz** [comment]
Yay, more completely randomized behavior.

**Comment by ManuelAtWork** [comment]
> @ManuelAtWork It would be great to print all targets that match, yes. Could you propose a patch for that please?

I would love to, but my knowledge of Python is near-zero. (Not every gourmet is a chef. ... Unfortunately. ;-) )
(Maybe I can hire a Python dev next year. If so, I'll allocate some of his time to meson.)

However, assuming that the error message is generated by meson, it is probably issued in the context of an index (hashmap?) search. This search yields multiple results, exception thrown. Maybe at this point, all of the ambiguous seach results can be used to extend the exception's text.

**Comment by ManuelAtWork** [comment]
> 



> One thing I've been wanting for a while is typing "meson compile foo.c.o" and it just build it whatever subdir it's in, or print all paths if there are more than one foo.c file.

That might be a differnt topic: `foo.c.o` sound like an _output_, not a _target_ to meson. 
Unless you do something like `custom_target('foo.c.o', ...)`.

**Comment by xclaesse** [comment]
> That might be a differnt topic: `foo.c.o` sound like an _output_, not a _target_ to meson.

For ninja outputs are targets.
