### ISSUE TITLE
Existing file not detected by Meson

### ISSUE THREAD

**Issue by Ricky-Tigg** [mesonbuild/meson#10226]
**Describe the bug**
Existing file not detected by Meson

**To Reproduce**
```
$ pip3 install --user meson && type meson
meson is /home/yk/.local/bin/meson
# dnf install -y cmake gtk4 ninja-build libhandy-devel
$ git clone https://github.com/tchx84/Flatseal.git
$  cd Flatseal; meson _translate
(...))
po/meson.build:1:5: ERROR: File fi.po does not exist.
```
[meson-log.txt](https://github.com/mesonbuild/meson/files/8398237/meson-log.txt)
```
$ touch fi.po: ls -o fi.po
-rw-rw-r--. 1 yk 0  1. 4. 16:55 fi.po
$ meson _translate
```
_Same error_
```
$ meson --reconfigure _translate
Directory does not contain a valid build tree:
/home/yk/Lataukset/Flatseal/_translate
```
**Expected behavior**
Existing file to be detected by Meson

**system parameters**
* native build
* Fedora Linux
* Python 3.10.4
* [meson](https://pypi.python.org/pypi/meson) version: 0.62.0`

**Comment by eli-schwartz** [comment]
I'm not sure I understand the problem. At first it did not exist, then after you created it you tried to run `meson --reconfigure` on an entirely different directory that isn't `_translate`. And meson errors out that `builddir` isn't a directory you previously ran meson on.

**Comment by Ricky-Tigg** [comment]
"`builddir`" | I did not pay attention to that term; that was an error.

**Comment by Ricky-Tigg** [comment]
Since that file does exist and is not detected, then i had to conclude that it must be at a wrong location which meson is missing to report. At last i found by analogy a valid location for it. Now no error message but a non found component.
```
$ meson _translate
(...)
Program jasmine found: NO
(...)
Build targets in project: 23

Found ninja-1.10.2 at /usr/bin/ninja
```

**Comment by eli-schwartz** [comment]
Okay, so does that mean the problem is solved?

**Comment by Ricky-Tigg** [comment]
It does. Though there is place for improvement. While paying attention to the error message, i notice now for the first time `po/` as part of it. Is that mention meant to indicate a **relative path**, for instance the one of the directory expected to contain that file? If so, its meaning is hidden due to a non-explicit syntax which is at the very source of the present report. Instead a self-explicit syntax would be welcome, such as:

`meson.build:1:5: ERROR: file fi.po does not exist at po/.`

**Comment by eli-schwartz** [comment]
The file `fi.po` was expected as an input by the build definition at `po/meson.build:1:5:`, i.e. line 1, column 5 of `po/meson.build` --  source files listed in any given `meson.build` are expected to be relative to that `meson.build`. If the input filename as given was `../fi.po` then that is how the error message would format it, although gettext specifically expects a list of languages corresponding to message catalogs in the same directory. You do get input filenames with directory components, in `custom_target()` or `executable()` fairly often.

This seems like explicit syntax to me.
