### ISSUE TITLE
How do I build Intel binary on M1 Mac using Meson?

### ISSUE THREAD

**Issue by zajo** [mesonbuild/meson#10245]
I tried adding `-arch` using `add_global_arguments`, but it did not work. What's the correct way to do this?

**Comment by anadon** [comment]
Can you please post your `meson.build` file, as well as your invocation?

**Comment by zajo** [comment]
I apologize, the reason why I was getting an error is that I had forgotten to add `-arch` to the `add_global_arguments` for `language:'c'`. So, to answer my question, the solution is:

```
add_global_link_arguments(
	['-arch', 'x86_64'],
	language:'cpp' )

add_global_arguments(
	['-arch', 'x86_64'],
	language:'cpp' )

add_global_arguments(
	['-arch', 'x86_64']
	language:'c' )
```

Closing this issue now. Thanks!
