### ISSUE TITLE
'Format strings' don't format when passed as keyword argument

### ISSUE THREAD

**Issue by perigoso** [mesonbuild/meson#10264]
**Describe the bug**
when using `Format strings` instead of `.format()` inside keyword arguments, the string is not formated

**To Reproduce**
produces the expected `Test.elf` file
```
out_name = 'Test'
exe = executable('@0@.elf'.format(out_name))
```
produces a `@out_name@.elf` file
```
out_name = 'Test'
exe = executable('@out_name@.elf')
```
same applies to input/output files in `custom_target`

**Expected behavior**
Both options should produce the same result

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? **cross**
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) **Windows 10**
* what Python version are you using e.g. 3.8.0 **python 3.10**
* what `meson --version` **0.62.0**
* what `ninja --version` if it's a Ninja build **1.10.2**

**Comment by xclaesse** [comment]
> exe = executable('@out_name@.elf')

The string needs to be prefixed with f: `f'@out_name@.elf'`. Like in python syntax.

**Comment by perigoso** [comment]
oh dam, sorry, i missed that looking at the docs...
