### ISSUE TITLE
-Dbuildtype=release fails on CompCert

### ISSUE THREAD

**Issue by guijan** [mesonbuild/meson#10267]
**Describe the bug**
Building with CompCert on release mode fails. 
The error message is as follows:
```
ccomp: error: Unknown option `-03'
```
Note that this unknown option is "dash zero three" and not "dash O three". Maybe someone accidentally typed a zero where they wanted a letter "O"?

**To Reproduce**
The bug seems to trigger with any program.
Download this Meson "Hello, world!" program: [meson-compcert.zip](https://github.com/mesonbuild/meson/files/8468156/meson-compcert.zip).
Try to build it with:
```console
$ CC=ccomp meson setup -Dbuildtype=release build && meson compile -C build
```

**Expected behavior**
A successful build.

**system parameters**
I'm running Meson 0.62 from PyPi and my CompCert is the binary package of version 3.9 from the OpenBSD ports system.
My ninja is version 1.10.2 and my python is version 3.8.12.

**Comment by eli-schwartz** [comment]
Seems to be a simple typo, present since original implementation. Can you try my PR above?

**Comment by guijan** [comment]
Yes, that fixes it.
