### ISSUE TITLE
How to get Project Version in meson.build ?

### ISSUE THREAD

**Issue by Tanishq-Banyal** [mesonbuild/meson#10279]
I want to name my executable According to project version, like `myapp_v4.5`

I have meson.build like :-
```py
project('myapp', version: '4.5' ...)
...
ver = #what here ?
executable('myapp_v'+ver, 'main.cpp' ...)
```

How do i acess the version of project ?

**Comment by lazka** [comment]
https://mesonbuild.com/Reference-manual_builtin_meson.html#mesonproject_version

**Comment by Tanishq-Banyal** [comment]
Oh thanks!
