### ISSUE TITLE
compiler.has_argument doesn't work with clang-cl for warning flags

### ISSUE THREAD

**Issue by kazarmy** [mesonbuild/meson#10283]
**Describe the bug**

The option `-Wimplicit-fallthrough=3` is unknown to clang-cl 12.0.1, and yet the `has_argument('-Wimplicit-fallthrough=3')` check passes, as can be seen [here](https://ci.appveyor.com/project/rizinorg/rizin/builds/43245228/job/x5rjqvh9bwub2a0k?fullLog=true#L62):

![fallthrough-check-passes](https://user-images.githubusercontent.com/12002672/163571080-31dcc693-817d-4dbc-a294-fb514e4ef81f.PNG)

and [here](https://ci.appveyor.com/project/rizinorg/rizin/builds/43245228/job/x5rjqvh9bwub2a0k?fullLog=true#L34051):

![fallthrough-warning](https://user-images.githubusercontent.com/12002672/163571452-65bb676a-f323-4ebf-96c9-1f6385c8a60e.PNG)

The relevant `meson-log.txt` lines appear to be:
```
Compiler stdout:
 
Compiler stderr:
 warning: unknown warning option '-Wimplicit-fallthrough=3'; did you mean '-Wimplicit-fallthrough'? [-Wunknown-warning-option]
1 warning generated.

Compiler for C supports arguments -Wimplicit-fallthrough=3: YES 
```

so the issue appears to be the same as for #755 except that the compiler involved is now clang-cl.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?

native build

* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)

Windows Server 2019

* what Python version are you using e.g. 3.8.0

Python 3.8

* what `meson --version`

0.62.0

* what `ninja --version` if it's a Ninja build

1.10.2

**Comment by tristan957** [comment]
Seems like Meson needs to be passing `-Werror=unknown-warning-option` when it calls self.compiles() with your arguments.

**Comment by kazarmy** [comment]
Right, okay #10287 ... Thanks for the assist!
