### ISSUE TITLE
`add_test_setup(exclude_suites:)` is not being listified.

### ISSUE THREAD

**Issue by tristan957** [mesonbuild/meson#10293]
`add_test_setup(exclude_suites:)` is not being listified.

I am assuming this function just needs to be brought into the 21st century typed_kwargs/posargs.

cc @dcbaker @eli-schwartz 

If neither of you currently has a patch for this, I can go ahead and submit one.

**Comment by eli-schwartz** [comment]
It already uses typed_kwargs and gets stored as a list in `build.TestSetup`, can you clarify what went wrong and how?

**Comment by tristan957** [comment]
Oh whoops. Thought I was using 0.62, but I was back on 0.59.4. Closing.
