### ISSUE TITLE
FileNotFoundError in devenv

### ISSUE THREAD

**Issue by punytroll** [mesonbuild/meson#10310]
**Describe the bug**

```
$> cd build
$> meson devenv unknownexe
Traceback (most recent call last):
  File "/home/hmoebius/.local/lib/python3.9/site-packages/mesonbuild/mesonmain.py", line 153, in run
    return options.run_func(options)
  File "/home/hmoebius/.local/lib/python3.9/site-packages/mesonbuild/mdevenv.py", line 163, in run
    return subprocess.call(args, close_fds=False,
  File "/usr/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'unknownexe'

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

**To Reproduce**

meson.build
```
project('test', 'cpp')
executable('main', sources: 'main.cpp', install: true)
```

**Expected behavior**

An error message is preferable to a Python stacktrace.

I can provide a fix, but I want to be sure that a fix is wanted. There are various side cases, that need addressing as well:
* install: false
* install_dir: ''

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
native
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
Ubuntu Hirsute
* what Python version are you using e.g. 3.8.0
3.9.5
* what `meson --version`
0.62.1
* what `ninja --version` if it's a Ninja build
1.10.1

**Comment by tristan957** [comment]
cc @xclaesse 

@punytroll generally fixes like this are wanted. Meson should catch this error and report to the user the no devenv has been defined with that name.

**Comment by eli-schwartz** [comment]
> report to the user the no devenv has been defined with that name.

Well, that no executable exists by that name inside the devenv. :)

> An error message is preferable to a Python stacktrace.

Yes, agreed -- that's why in general we catch all tracebacks and append "This is a Meson bug and should be reported!" to them. :) Thanks for the report.

> I can provide a fix, but I want to be sure that a fix is wanted. There are various side cases, that need addressing as well:
> 
>     * install: false
> 
>     * install_dir: ''

It's not clear to me what any of these have to do with devenv?

**Comment by punytroll** [comment]
Nevermind, I hadn't checked for other PRs. :/ I closed my PR.
The other issues still stand.
