### ISSUE TITLE
[Notice] meson 0.61.x works better for compiling gnome-related apps than meson 0.62.x

### ISSUE THREAD

**Issue by rubyFeedback** [mesonbuild/meson#10315]
This is just a notification, you meson folks probably are aware of that already.

Meson 0.61.x branch: https://files.pythonhosted.org/packages/21/79/1afcc906894007b181e25bf64f7afeee8089da203e06ae364efa2ad3bf9e/meson-0.61.4.tar.gz

works better for me than meson 0.62.x.

In fact when I try to compile many gnome-based programs lately they complain about
a gtk_doc issue. There are probably easy workarounds, but I am lazy and just follow
LFS/BLFS (linux from scratch) instructions, so for the time being I will remain on meson
0.61.x

What is the point of this issue request, then, you may ask? Well, I assume I may not be
the only one, so I just let you guys know about this. Any other conclusion based on that
is for others to make, not me - my main purpose for this issue request was really only
to just state that 0.61.x **currently** works better for me in regards to compiling from
source, the rest is up to others to decide, if anything has to be decided upon that is.

**Comment by eli-schwartz** [comment]
> What is the point of this issue request, then, you may ask? Well, I assume I may not be
> the only one, so I just let you guys know about this.

Unfortunately, you failed to let us know what "a gtk_doc issue" is, so we don't know about it.
