### ISSUE TITLE
[Feature Request] Support ThinLTO cache

### ISSUE THREAD

**Issue by ishitatsuyuki** [mesonbuild/meson#10311]
ThinLTO accepts a cache directory as linker plugin option. When cache is enabled, it's able to perform incremental optimization, accelerating iteration times for small source changes. We should make it easy to enable cache in Meson.

The options are documented at: https://clang.llvm.org/docs/ThinLTO.html#incremental

The most relevant option is `--thinlto-cache-dir`, but there are also other options to control cache pruning behavior.

Other notes:
- The way to configure cache differs between linker, so we need to detect and adapt in Meson.
- This is useful for developers but not much when you just want to get an one-off build (distro packaging etc), so it should be opt-in.

**Comment by tristan957** [comment]
@ishitatsuyuki wouldn't this work better just passed as `-D<lang>_args` or `-D<lang>_link_args`?

**Comment by ishitatsuyuki** [comment]
> This doesn't sound like a concept which exists in other compilers. At least I have never heard of such a thing in GCC

Yes, ThinLTO is LLVM/Clang only. But we already have `-Db_lto=thin` in Meson. It can be substituted with `-flto=thin` in `{C,CXX,LD}FLAGS`, but maybe Meson's option is worth the convenience.

The reason you would want it, is that the cache is somewhat tied to the build directory (it's rare for the emitted bitcode to be common across build configurations, let alone different code bases). Specify `-Dlang_args` with a directory different for each build would be rather annoying as a personal setup. It's also different per linker - handling this within a utility would be nicer than doing it manually.

**Comment by tristan957** [comment]
I see, maybe Meson could check if -Db_lto is this and then set the cache dir to somewhere is Meson's private target directory. I don't think a PR would be very hard for that if you want to look into it.

**Comment by ishitatsuyuki** [comment]
I did not mean that it should be a user function --- I meant Meson as the "command-line utility". A b_ option is likely good for this.

**Comment by tristan957** [comment]
I mistyped....should be option

**Comment by ishitatsuyuki** [comment]
We just need an option so that it can be opt-in --- Meson is also called from packaging routines where you only fire off the build once and the cache would be just waste of space.

**Comment by tristan957** [comment]
good point! Sounds like a PR would be warranted then if you would like to submit one. I don't think it would be too difficult to create this.
