### ISSUE TITLE
`meson dist` complains about "Repository has uncommitted changes" for a clean repo in container

### ISSUE THREAD

**Issue by martinpitt** [mesonbuild/meson#10329]
**Describe the bug**

[umockdev's regular unit tests](https://github.com/martinpitt/umockdev/actions) started to fail on Debian testing started to fail 3 days ago, which coincides with Debian testing updating [meson from 0.61.2 to 0.62.1](https://tracker.debian.org/pkg/meson). [The failure](https://github.com/martinpitt/umockdev/runs/6151646365?check_suite_focus=true#step:3:1902) says:

```
+ meson dist --no-test
ERROR: Repository has uncommitted changes that will not be included in the dist tarball
Use --allow-dirty to ignore the warning and proceed anyway
```

**To Reproduce**
This apparently only fails in a container (with a bind mount), I am not seeing this bug on my host system:
```sh
git clone https://github.com/martinpitt/umockdev
podman run -it --rm -v ./umockdev:/source:ro docker.io/amd64/debian:testing
```
Inside the container, install minimal build deps and configure a tree:
```sh
apt update
apt install -y --no-install-recommends meson git-core gcc pkg-config valac libglib2.0-dev libudev-dev libpcap-dev
cd /source
meson /tmp/build
```

Now the bug happens with `dist`:
```
meson dist -C /tmp/build
```

fails with
```
ERROR: Repository has uncommitted changes that will not be included in the dist tarball
Use --allow-dirty to ignore the warning and proceed anyway
```

However, this is not true:
```
# git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

**Expected behavior**
`meson dist` should continue to work with a read-only/bind mount in a clean tree without `--allow-dirty`.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? No.
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) Debian testing
* what Python version are you using: 3.10.4
* what `meson --version`: 0.62.1
* what `ninja --version` if it's a Ninja build: 1.10.1

**Comment by martinpitt** [comment]
This is actually rather awkward to work around, as even 0.61 [does not know about `--allow-dirty`](https://github.com/martinpitt/umockdev/actions/runs/2238862391). I'll add some version check then.

**Comment by eli-schwartz** [comment]
https://github.com/mesonbuild/meson/blob/157d43883515507f42618b065a64fb26501734a0/mesonbuild/mdist.py#L147-L150

You say that git status reports it is clean. In that case, git diff-index should not be reporting that it is dirty!

If it is, somehow, reporting that it is dirty... but only inside a container! then it sounds like the container itself is broken. Does git status report that it is clean in your shell, or in the container? It's not actually clear from your report.

By the way, there's a recent git update containing a badly designed security fix (it stops people from creating malicious `git init` with dangerous read-write githooks by... Refusing to work at all in read-only contexts that cross ownership boundaries *including sudo which breaks their own Makefile*) and that fit update would be my first guess to why a container bund mount might now be considered broken when it didn't used to be.

It is the meson project's expectation that read-only access to a project source tree owned by a different user should be fine. Build systems are often used that way, in fact.

Apparently it's no longer the git project's expectation that that should be the case, and unfortunately there's nothing we can do about that.

**Comment by martinpitt** [comment]
I just noticed that with 0.61.2, meson dist [also already warns about this](https://github.com/martinpitt/umockdev/runs/6123205288?check_suite_focus=true#step:3:1587):
```
+ meson dist --no-test
WARNING: Repository has uncommitted changes that will not be included in the dist tarball
Created /tmp/dbg/meson-dist/umockdev-0.17.9.tar.xz
```
So this is not quite a regression, as the underlying dirty check already failed before. I agree to failing on this and making it explicit. Retitling accordingly.

> Does git status report that it is clean in your shell, or in the container?

I ran it in the container, but it's clean on the host as well.

Indeed your hint about `git diff-index` is exactly right, thanks! On the host:
```
❱❱❱ git diff-index HEAD; echo $?
0
``
In the container:
```
# git diff-index HEAD; echo $?
:100644 100644 397632e1a8d475775ee7dc7710c6fda9c1b0d06d 0000000000000000000000000000000000000000 M	.github/workflows/release.yml
[... and all other files ...]
0
```
i.e. the command still succeeds, but I figure meson looks at the output.

This happens with git 2.34.1 (Ubuntu 22.04) and 2.35.1 (Debian testing).

**Comment by eli-schwartz** [comment]
From the git manpage:
```
--exit-code
Make the program exit with codes similar to diff(1). That is, it exits with 1 if there were differences and 0 means no differences.

--quiet
Disable all output of the program. Implies --exit-code.
```

Meson uses the latter, so there's no output but it does return an error.

**Comment by martinpitt** [comment]
Thanks for the right pointers! [Setting the `safe.directory` option](https://github.com/martinpitt/umockdev/commit/093b401b0ab73c5aaa4f0023f624d996487bee21) and [using the `--allow-dirty` option](https://github.com/martinpitt/umockdev/commit/c0c505bda1cfcb55bdb6a2691752b49f615f393c) make things [work](https://github.com/martinpitt/umockdev/actions/runs/2257734644) again.
