### ISSUE TITLE
Option to preprocess sources, but not compile

### ISSUE THREAD

**Issue by X547** [mesonbuild/meson#10334]
I have various DSL (domain-specific languages) that use C preprocessor. So `cc -E` need to be called before running DSL compiler. Is there an option to run C preprocessor only? It is possible to run `cc -E` with `custom_target`, but it will not properly handle `#include <...>` dependencies in source files.

**Comment by willwray** [comment]
compiler.preprocess() was added in 0.64
https://mesonbuild.com/Reference-manual_returned_compiler.html#compilerpreprocess

(I'm trying to use it in a similar sounding use case, hoping to replace a custom_target that doesn't handle include paths properly)
