### ISSUE TITLE
EFI Application Windows Subsystem

### ISSUE THREAD

**Issue by LensPlaysGames** [mesonbuild/meson#10366]
For some reason only two of the many windows subsystems are allowed through. This disallows me from building a UEFI bootloader application using meson, as it FORCES either console or windows subsystem when attempting to use a MinGW compiler to generate UEFI-compatible PE32+ executables.

https://github.com/mesonbuild/meson/blob/c16fdaeecafe94461d6048b90bd337a04c25ad3c/mesonbuild/linkers/linkers.py#L702-L712

---

### Simple fix

```python
elif 'efi_application' in value: 
         args = ['--subsystem,10'] 
```

---

### Non-simple fix

https://github.com/mesonbuild/meson/blob/ca77adea89b3f102ca3e62465f651811516071f5/mesonbuild/build.py#L1260-L1264

The regexp above could take into account straight subsystem numbers, although that would definitely allow for things to break (which seems fine if you are messing with the windows subsystem, imo).

---

I'll probably end up making a pull request once I figure out how to build/use meson from source.

**Comment by Tachi107** [comment]
> build/use meson from source

It should be as easy as editing the source files and running running [`path/to/meson.py`](https://github.com/mesonbuild/meson/blob/master/meson.py)

**Comment by eli-schwartz** [comment]
https://mesonbuild.com/Getting-meson.html#downloading-meson

We document that running from source in the manner @Tachi107 described shall work, and it's tested in CI too (in addition to being the primary way I run meson myself).
