### ISSUE TITLE
needs_exe_wrapper = true seems not to work with override_find_program

### ISSUE THREAD

**Issue by hughsie** [mesonbuild/meson#10374]
**Describe the bug**

I have a subproject that defines a binary:

    gcab = executable(
      'gcab',
      install : true,
      ...
    )
    meson.override_find_program('gcab', gcab)

and defines it in the `gcab.wrap` file:

    [provide]
    program_names = gcab

and then a toplevel project (fwupd, but unimportant) that wants to use that binary:

    gcab = find_program('gcab')

...which is used like this:

    custom_target('foo',
      input : [
        'firmware.bin',
      ],
      output : 'colorhug-als-3.0.2.cab',
      command : [
        gcab, '--create', '--nopath', '@OUTPUT@', '@INPUT@',
      ],
    )

...I'm also then using a cross build file, with needs_exe_wrapper = true:

    [binaries]
    c = '/usr/bin/x86_64-w64-mingw32-gcc'
    cpp = '/usr/bin/x86_64-w64-mingw32-g++'
    fortran = '/usr/bin/x86_64-w64-mingw32-gfortran'
    rust = ['rustc', '--target', 'x86_64-pc-windows-msvc', '-C', 'linker=/usr/bin/x86_64-w64-mingw32-gcc']
    ar = '/usr/bin/x86_64-w64-mingw32-ar'
    pkgconfig = '/usr/bin/x86_64-w64-mingw32-pkg-config'
    ranlib = '/usr/bin/x86_64-w64-mingw32-ranlib'
    strip = '/usr/bin/x86_64-w64-mingw32-strip'
    glib-mkenums = '/usr/x86_64-w64-mingw32/sys-root/mingw/bin/glib-mkenums'

    [properties]
    root = '/usr/x86_64-w64-mingw32/sys-root/mingw'
    needs_exe_wrapper = true

    [host_machine]
    system = 'windows'
    cpu_family = 'x86_64'
    cpu = 'x86_64'
    endian = 'little'

..this gives:

    ERROR: An exe_wrapper is needed but was not found. Please define one in cross file and check the command and/or add it to PATH.

**Expected behavior**

I expected the exe wrapper to be automatically used on the overriden subproject executable.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?

Yes, a w64 cross build.

* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)

Fedora 36.

* what Python version are you using e.g. 3.8.0

3.10.4

* what `meson --version`

0.60.3, although it also happens with git master too.

* what `ninja --version` if it's a Ninja build

1.10.2

**Comment by eli-schwartz** [comment]
Where is your exe_wrapper defined?

**Comment by xclaesse** [comment]
> @xclaesse the commit message there seems to be incorrect :p it doesn't just affect devenv.

AFAIK it only affects devenv, what else does it change?

**Comment by xclaesse** [comment]
Oh, checking how it works for custom_target(), I discover that meson_exe.py already sets WINEPATH using  `mesonlib.get_wine_shortpath()`. I did not know we already had that code and re-implemented it in mdevenv.py.

**Comment by xclaesse** [comment]
@hughsie maybe something is broken, but meson is supposed to setup WINEPATH for your custom_target() already. One big limitation is the WINEPATH value must be less than 1024 chars (and not 2048 as mesonlib.get_wine_shortpath pretends). When having libs all across your builddir, you get above that very easily.

**Comment by hughsie** [comment]
@xclaesse Is there a way I dump the current WINEPATH without patching meson?

**Comment by xclaesse** [comment]
Meson does not seems to log that currently, you can either add a print there: https://github.com/mesonbuild/meson/blob/master/mesonbuild/scripts/meson_exe.py#L49

Or write your own "wine.sh" wrapper script that dump that env before calling the real wine.

**Comment by eli-schwartz** [comment]
@xclaesse

```diff
-if mesonlib.is_windows() or mesonlib.is_cygwin():
+if host_machine.is_windows() or host_machine.is_cygwin():
```
This made it cross friendly, which is how wine compilation works anyway.

You also made it set the per-exe environment to WINEPATH in a cross build instead of hardcoding native windows "PATH".

**Comment by hughsie** [comment]
> You also made it set the per-exe environment to WINEPATH in a cross build instead of hardcoding native windows "PATH".

Do you want me to open a new issue for this?

**Comment by eli-schwartz** [comment]
A new issue for what?

**Comment by hughsie** [comment]
@eli-schwartz that `PATH` is set with all the `/usr/x86_64-w64-mingw32/sys-root/mingw/bin` paths, and `WINEPATH` is empty...

**Comment by eli-schwartz** [comment]
But my comment said that the devenv PR *fixed* that as a side effect...

**Comment by hughsie** [comment]
> PR....

My https://github.com/mesonbuild/meson/pull/10291 says that it was merged to master 4 days ago; and I'm testing with master...

**Comment by eli-schwartz** [comment]
Well, that PR is definitely supposed to set WINEPATH whenever host_machine.system() is windows... is need_wine not true there?

**Comment by hughsie** [comment]
I don't think this is talking about `mesonbuild/backend/backends.py:get_devenv()`, the PATH is being set for me in `mesonbuild/scripts/meson_exe.py:def run_exe()`

**Comment by xclaesse** [comment]
> @xclaesse
> 
> ```diff
> -if mesonlib.is_windows() or mesonlib.is_cygwin():
> +if host_machine.is_windows() or host_machine.is_cygwin():
> ```
> 
> This made it cross friendly, which is how wine compilation works anyway.
> 
> You also made it set the per-exe environment to WINEPATH in a cross build instead of hardcoding native windows "PATH".

That code path is only used for devenv, not custom_target(). My PR is totally unrelated AFAIK.

**Comment by eli-schwartz** [comment]
@xclaesse ah, I guess I misread that. I saw code in backends.py that handled this, and for some reason thought it was setting it on the build target itself.

**Comment by eli-schwartz** [comment]
> Ha, interesting. I don't seem to have one. I've added
> 
> ```
> [binaries]
> exe_wrapper = '/usr/bin/wine'
>```
> ...and of course this bug is invalid, sorry for the noise. I guess those two lines also belong in /usr/share/mingw/toolchain-mingw64.meson as shipped in Fedora.
> 
> One bonus question, actually running wine is tricky [...]

Alright, so this issue can be closed then.
