### ISSUE TITLE
Meson >=0.59.0 Not able to find Threads with CMake in Yocto SDK

### ISSUE THREAD

**Issue by tlammi** [mesonbuild/meson#10384]
**Describe the bug**
Meson >= 0.59.0 fails to find Threads dependency with CMake when using Yocto generated SDK.
Meson <= 0.58.2 and plain CMake work fine.

The breaking change is likely https://github.com/mesonbuild/meson/pull/8812.

I hit this issue when cross compiling a meson project depending on https://github.com/aws/aws-iot-device-sdk-cpp-v2 which uses CMake for configuration and internally depends on Threads.

**To Reproduce**
1. Install Yocto generated SDK with Meson, CMake and libpthread (unfortunately I did not find any downloads for this and my own SDK is proprietary)
2. Source the environment setup script from the SDK
3. Compile the project below

meson.build
```
project('hello', 'cpp')

thread_dep = dependency('Threads', method: 'cmake', modules: ['Threads::Threads'])

hello = executable('hello', 'main.cpp', dependencies: thread_dep)
```

main.cpp
```
#include <iostream>
#include <thread>

int main() {
    std::thread t{[]() { std::cerr << "hello\n"; }};
    t.join();
}
```

**Expected behavior**
The project should compile with the SDK

**system parameters**
* Is this a cross build: Yes
* OS:
    * Host: Manjaro 21.2.6
    * SDK: Yocto Poky Kirkstone
* Python: 3.10.4
* what `meson --version`
    * Worked with 0.58.2
    * Did not work with 0.59.0, 0.61.3 or 0.62.1
* what `ninja --version` if it's a Ninja build
    * 1.10.2

**Comment by tlammi** [comment]
[cmake_trace.0.58.2.txt](https://github.com/mesonbuild/meson/files/8676940/cmake_trace.0.58.2.txt)
[cmake_trace.0.61.3.txt](https://github.com/mesonbuild/meson/files/8676942/cmake_trace.0.61.3.txt)

Here are modified CMake traces for the two cases (named as `cmake_trace.<meson-version>.txt`).
I ran the traces through `sed` to remove some information, like company name.

**Comment by tlammi** [comment]
I dug into this issue a bit more and found this in CMake logs:
```
Determining if the include file pthread.h exists failed with the following output:
Change Dir: /home/user/code/hello/meson-build/meson-private/cmake_Threads/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make -f Makefile cmTC_4fe43/fast && make[1]: Entering directory '/home/user/code/hello/meson-build/meson-private/cmake_Threads/CMakeFiles/CMakeTmp'
/usr/bin/make  -f CMakeFiles/cmTC_4fe43.dir/build.make CMakeFiles/cmTC_4fe43.dir/build
make[2]: Entering directory '/home/user/code/hello/meson-build/meson-private/cmake_Threads/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_4fe43.dir/CheckIncludeFile.cxx.o
"/opt/foo-linux/0.4.1/sysroots/x86_64-barsdk-linux/usr/bin/aarch64-foo-linux/aarch64-foo-linux-g++;-mcpu=cortex-a53;-march=armv8-a+crc+crypto;-fstack-protector-strong;-O2;-D_FORTIFY_SOURCE=2;-Wformat;-Wformat-security;-Werror=format-security;--sysroot=/opt/foo-linux/0.4.1/sysroots/cortexa53-crypto-foo-linux" -mcpu=cortex-a53 -march=armv8-a+crc+crypto -fstack-protector-strong -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/opt/foo-linux/0.4.1/sysroots/cortexa53-crypto-foo-linux --sysroot=/opt/foo-linux/0.4.1/sysroots/cortexa53-crypto-foo-linux   -O2 -pipe -g -feliminate-unused-debug-types   -o CMakeFiles/cmTC_4fe43.dir/CheckIncludeFile.cxx.o -c /home/user/code/hello/meson-build/meson-private/cmake_Threads/CMakeFiles/CMakeTmp/CheckIncludeFile.cxx
/bin/sh: line 1: /opt/foo-linux/0.4.1/sysroots/x86_64-barsdk-linux/usr/bin/aarch64-foo-linux/aarch64-foo-linux-g++;-mcpu=cortex-a53;-march=armv8-a+crc+crypto;-fstack-protector-strong;-O2;-D_FORTIFY_SOURCE=2;-Wformat;-Wformat-security;-Werror=format-security;--sysroot=/opt/foo-linux/0.4.1/sysroots/cortexa53-crypto-foo-linux: No such file or directory
make[2]: *** [CMakeFiles/cmTC_4fe43.dir/build.make:78: CMakeFiles/cmTC_4fe43.dir/CheckIncludeFile.cxx.o] Error 127
make[2]: Leaving directory '/home/user/code/hello/meson-build/meson-private/cmake_Threads/CMakeFiles/CMakeTmp'
make[1]: *** [Makefile:127: cmTC_4fe43/fast] Error 2
make[1]: Leaving directory '/home/user/code/hello/meson-build/meson-private/cmake_Threads/CMakeFiles/CMakeTmp'
```

The issue then seems to be that some compiler settings are joined with ";" instead of " ".

The settings here come from meson.cross file:
```
<snip>
[binaries]
cpp = ['aarch64-foo-linux-g++', '-mcpu=cortex-a53', '-march=armv8-a+crc+crypto', '-fstack-protector-strong', '-O2', '-D_FORTIFY_SOURCE=2', '-Wformat', '-Wformat-security', '-Werror=format-security', '--sysroot=/opt/foo-linux/0.4.1/sysroots/cortexa53-crypto-foo-linux']
</snip>
```

**Comment by eli-schwartz** [comment]
Well, this seems to be classic cmake at least. Randomly interpreting lists as `;`-delimited strings, and then not actually handling them as lists at all in contexts where they should be.

I would say "can't you just use Meson's own threads dependency" but I'm sure this must also be broken for other dependencies too.

**Comment by tlammi** [comment]
This was a strange bug but I managed to fix it.

Yocto SDK has multiple cmake toolchain files and I pointed to a wrong one which did not set `CMAKE_CXX_COMPILER`
which then for some reason caused the strange string behavior. What is strange is that everything worked fine before 0.59.0.

I'll close this issue now as I found a fix and I wouldn't call this a bug in meson.
