### ISSUE TITLE
Elevated pip3 install fails

### ISSUE THREAD

**Issue by ReznicencuBogdan** [mesonbuild/meson#10389]
**Describe the bug**
Installing `meson` as root ( i.e `sudo pip3 install meson` ) fails with the general error: 
> ERROR: Could not install packages due to an EnvironmentError: [Errno 20] Not a directory: '/usr/local/share/man/man1/meson.1'

**Expected behavior**
Install shouldn't fail.

**System parameters**
* Os: Linux Mint 20.3
* Python 3.8.10

**Comment by eli-schwartz** [comment]
I think this isn't really something Meson can solve.

pip usually installs to /usr and not /usr/local, but this weird on Debian. And /usr/local/share/man/man1 is the local equivalent of /usr/share/man/man1 which in the latter case should almost certainly exist. I am curious however, why pip does not create the former directory for you?

At any rate, pip is doing all the installation work, so any issue here is a pip issue.

...

In the future, it *would* be nice for Meson to be able to install itself by running `./meson.py setup builddir && ninja -C builddir install` but that would be a feature for the future. It would mean we no longer depend on pip to do things correctly, which is a nice thought...

Note as well that https://mesonbuild.com/Getting-meson.html describes several different ways of installing Meson. One of them is with pip, but you may find one of the other methods to be more satisfying. (I myself do use pip.)

**Comment by eli-schwartz** [comment]
Wait, hmm....


> Not a directory: '/usr/local/share/man/man1/meson.1'

Is pip trying to handle the destination filepath as the containing directory? I have no idea what this means.

Do you have that file already on your system? Do you have /usr/local/share/man/man1/ on your system?

**Comment by ReznicencuBogdan** [comment]
> Do you have that file already on your system? Do you have /usr/local/share/man/man1/ on your system?
Yes. The path however leads to a file, not a directory. 
```sh
file /usr/local/share/man/man1 /*gives*/ /usr/local/share/man/man1: troff or preprocessor input, ASCII text, with very long lines
```

> Note as well that https://mesonbuild.com/Getting-meson.html describes several different ways of installing Meson. One of them is with pip, but you may find one of the other methods to be more satisfying. (I myself do use pip.)
The pip version will not allow me to do a meson install - that requires root and it won't do (as noted in the docs). On the other hand, the distro's version is deemed too old for some projects that I need to compile/install. I guess all that's is building it myself. Than `man` issue is weird tho.

**Comment by eli-schwartz** [comment]
Oops, the `/usr/local/share/man/man1` path should definitely not be a file as that's invalid and breaks programs expecting it to be a directory. It is probably a man page -- what does `man /usr/local/share/man/man1` show the man page for?



> I guess all that's left is building it myself.

For which you do have several options :) the zipapp support in particular is pretty nifty.

**Comment by ReznicencuBogdan** [comment]
> what does man /usr/local/share/man/man1 show the man page for?

Ha! This one is funny. It is for the `dhex` - hex editor tool. Probably broke it while trying to install its docs?? I renamed the file and created the `man1` directory manually. The installation then succeded. :+1:  Not that much of a pain after all. I hope I didn't break something else. Thanks for the help.

**Comment by eli-schwartz** [comment]
Yeah, I found a github copy of the dhex source code:
https://github.com/cxd4/dhex/blob/515962fe20669e0235aa7ecfea972cefa42f04e1/Makefile#L29-L35

This should not assume that needed directories already exist, but it just `cp`s every file into place without first using `mkdir -p` and may very well put various stuff in the wrong place.
