### ISSUE TITLE
Wrap-db subprojects don't register the existence of a meson.build in them

### ISSUE THREAD

**Issue by michael-gene-brockus** [mesonbuild/meson#10395]
**Describe the bug**
I was trying to switch out an old test framework I was using for a long while for GTest, it downloaded files, but the `meson.build` wasn't found even though it's in the subproject, I had tested this with other test frameworks, UnitTest++ and Catch2 and same problem.

**To Reproduce**
This is the general project structure, I had to move back to the old test framework till this is resolved: https://github.com/michael-gene-brockus/cpp_meson_program

**Expected behavior**
Use a non-git-wrap file-based subproject and not see that it can't find a build file in the subproject even though there is clearly one in the dependency.

**system parameters**
* Is this a plain native build on my system and running on dummy host systems in CI/CD?
* running on Chromebook
* using `python 3.7.3`
* using `meson 0.62.0`
* using `ninja 1.10.0`

**Comment by eli-schwartz** [comment]
This works for me (and for lots of other people). The meson.build is provided by the patch_file, which is extracted before checking for the existence of the subproject build files. If you have already created the `subprojects/<some_subproject>/` directory, then Meson assumes the subproject is already downloaded and extracted, so it does neither one for you.
