### ISSUE TITLE
Separator arg warning with meson version >= 0.62.0

### ISSUE THREAD

**Issue by danielcjacobs** [mesonbuild/meson#10402]
**Describe the bug**
For a long time, I have used the `separator` kwarg when setting an environment variable in meson. Now, [v0.62.0](https://mesonbuild.com/Release-notes-for-0-62-0.html#new-method-and-separator-kwargs-on-environment-and-mesonadd_devenv) says this is a new feature...

A meson.build file that I've been using since before meson version 0.58.0 includes the line:
```
env.append('BAR', '0', separator: ':')
```

This has worked fine before, but after upgrading my meson version to 0.62.1, I now get this warning after running `meson build`:
```
meson.build:4: WARNING: Project targeting '>=0.58.0' but tried to use feature introduced in '0.62.0': separator arg in environment.append.
```

**To Reproduce**
1. With meson >= 0.62.0 installed, take the following meson.build:
```
project('foo', 'c', meson_version: '>=0.58.0')

env = environment()
env.append('BAR', '0', separator: ':')
```

2. Run `meson build`
3. See the warning

This warning doesn't occur with meson < 0.62.0

**Expected behavior**
I would not expect to receive a warning for a "new" feature that works with older meson versions.

**Comment by eli-schwartz** [comment]
This is incorrect and a regression from #10023
