### ISSUE TITLE
Subprojects not being deticted despite having a meson build file in [wrap-file] vs a [git-wrap]

### ISSUE THREAD

**Issue by michael-gene-brockus** [mesonbuild/meson#10425]
**Describe the bug**
Won't let me use a none git wrap as a subproject. Testing this on the Gtest framework and doesn't seem to be working.

![image](https://user-images.githubusercontent.com/55331536/170209913-6331e1a6-ed2c-4404-8488-9f7c76995571.jpeg)

**To Reproduce**
This is what I'm working with.

https://github.com/michael-gene-brockus/troglobyte-construct-cpp

**Expected behavior**
Ability to use a subproject like GTest.

**system parameters**
* Native build
* using Chromebook
* using `python 3.9.0`
* using `meson 62`
* using `ninja 1.10`

**Comment by xclaesse** [comment]
You're using a very old gtest.wrap, if you update to latest one from WrapDB it will work: `meson wrap update gtest`.

For the context, I think that would fix it:
```diff
-directory = gtest
+directory = googletest-release-1.8.1
```

**Comment by xclaesse** [comment]
Closing, let me know if that did not work.
