### ISSUE TITLE
Pybind11 extension module cannot be imported on windows when compiling with GCC

### ISSUE THREAD

**Issue by atw1020** [mesonbuild/meson#10454]
**Describe the bug**
When tiring to compile a test project that uses PyBind11 on a Windows computer using G++, meson is able to compile the program. However, if you try to import the resulting module in python, the program will error out with a DLL error:

```
>>> import adder
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed while importing adder: The specified module could not be found.
```

**To Reproduce**
1. On a windows machine install GCC (I used [MSYS2](https://www.msys2.org/))
2. Ensure that G++ is in the system path
2. Create a project directory with 2 files and an empty subprojects directory. The two files should be named "meson.build" and "module.cpp" (see below)

C:.
└───subprojects
└───meson.build
└───module.cpp

Contents of meson.build:

```meson
project('adder', 'cpp',
        default_options: ['cpp_std=c++17'], version: '0.0.1')

# ===========================================================
# Python 3
# ===========================================================

# python 3 import for extension_module
python_module = import('python')
inst = python_module.find_installation('python')

# ===========================================================
# PyBind11
# ===========================================================

# pybind11 dependency
pybind11_dep = dependency('pybind11')

inst.extension_module('adder', 'module.cpp',
                      dependencies: [pybind11_dep, inst.dependency()])

```

Contents of module.cpp:
```cpp
#include <pybind11/pybind11.h>

int add(int a, int b){
    return a + b;
}

PYBIND11_MODULE(adder, module){

    module.doc() = "this is an example";

    module.def("add", &add);

}
```

4. install pybind11 using `meson wrap install pybind11`
4. run `meson setup build` to create a build directory
5. examine the setup log and ensure that meson has detected the G++ compiler
> pybind11| C++ compiler for the host machine: c++ (gcc 11.3.0 "c++ (Rev1, Built by MSYS2 project) 11.3.0")
7. run `meson compile -C build` to compile the project
7. `cd build` into the build directory
8. run `python` to open an interactive shell.
9. try to import the module "adder" using `import adder`

**Expected behavior**
Python imports the `adder` module successfully and a python shell user is able to call the `add` function provided by the library

**system parameters**
Build: Native
Operating System: Windows 11
Python version: 3.9.7
Meson version: 0.62.1
Ninja version: 1.10.2.git.kitware.jobserver-1

**Other notes & Workarounds**

- Using MSVC instead of GCC fixes the issue.
- The issue appears to be related to the linking of DLL libraries, examining the .pyd file that is created with [dependency walker](https://github.com/lucasg/Dependencies) shows a few missing DLL files, but I have been unable to find these files on the internet

**Comment by atw1020** [comment]
Further research has led me to discover that this happens because the windows version of Python is built with MSVC, and therefore can't link anything compiled with GCC, which is not a bug.

**Comment by jeandet** [comment]
@atw1020,  for the record, this is not totally exact, you can build python packages on windows with Gcc but you might want to static link gcc provided libs as much as possible like here:
https://github.com/SciQLop/CDFpp/blob/master/meson.build#L38-L47
This is distributed on PyPi and built with Gcc on windows. Note also that you might only be able to build in release mode :/.
For such issues, [Dependency Walker](https://www.dependencywalker.com/) is a good friend.

**Comment by atw1020** [comment]
I tried release mode to try to get it to link statically but it still gives the DLL error, using static linking flags could also help though, thanks for the example!
