### ISSUE TITLE
Fails to find the compiler for cpp, even when using environment variable

### ISSUE THREAD

**Issue by Baileymnm1999** [mesonbuild/meson#10466]
**Describe the bug**
I have the following top level meson.build file for compiling my project.
```meson
project('gst-template', 'c', version : '1.19.0.1', license : 'LGPL')

plugins_install_dir = join_paths(get_option('libdir'), 'gstreamer-1.0')

cc = meson.get_compiler('c')
cxx = meson.get_compiler('cpp')

gst_version = meson.project_version()

api_version = '1.0'

gst_dep = dependency('gstreamer-1.0', version : '>=1.19',
    required : true, fallback : ['gstreamer', 'gst_dep'])
gstbase_dep = dependency('gstreamer-base-1.0', version : '>=1.19',
  fallback : ['gstreamer', 'gst_base_dep'])

subdir('gst-app')
subdir('gst-plugin')
```
Whenever I run it, regardless if I specify environment variable as follows `CXX=/usr/bin/g++ meson build` I get the following error.

```
meson.build:6:0: ERROR: Tried to access compiler for language "cpp", not specified for host machine.
```

**To Reproduce**
Try and build the above meson.build file with a standard cpp file. Empty method should work.

**Expected behavior**
CXX compiler to be found and used.

**system parameters**
* Native build on linux vm (Linux 5.15.0-1007-azure 8-Ubuntu SMP Wed May 18 18:12:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux)
* Python 3.10.4
* meson 0.61.2
* ninja 1.10.1

**Comment by Baileymnm1999** [comment]
So many hours wasted... thanks!

**Comment by dcbaker** [comment]
No problem! we could probably provide a better error message for that though
