### ISSUE TITLE
Warnings generated when installing JAR

### ISSUE THREAD

**Issue by tristan957** [mesonbuild/meson#10491]
**Describe the bug**

The MANIFEST generated by Meson's JAR is incorrectly formatted and produces warnings.

```
WARNING: Duplicate name in Manifest: Manifest-Version.
Ensure that the manifest does not have duplicate entries, and
that blank lines separate individual sections in both your
manifest and in the META-INF/MANIFEST.MF entry in the jar file.

WARNING: Duplicate name in Manifest: Created-By.
Ensure that the manifest does not have duplicate entries, and
that blank lines separate individual sections in both your
manifest and in the META-INF/MANIFEST.MF entry in the jar file.
```

**To Reproduce**
Create a JAR file and then try to install it. https://github.com/hse-project/hse-java/blob/master/meson.build#L73=

**Expected behavior**
Produce no warnings

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? No
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) fc36
* what Python version are you using 3.10.4
* what `meson --version` 0.62.1
* what `ninja --version` 1.10.2

**Comment by tristan957** [comment]
Meson isn't the one generating this file, so I don't think it is Meson's fault.

**Comment by bgilbert** [comment]
This is indeed a Meson bug.  Fix in https://github.com/mesonbuild/meson/pull/11174.
