### ISSUE TITLE
meson doesn't warn about include_type requiring 0.52.0 if required meson_version is too low

### ISSUE THREAD

**Issue by jeremyhu** [mesonbuild/meson#10529]
**Describe the bug**

Discussed in https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/913#note_1440794

I had meson_version set to 0.47.0 and made this change to our meson.build:

    -    rpc_dep = dependency('libtirpc', required: false)
    +    rpc_dep = dependency('libtirpc', required: false, include_type: 'system')

According to https://mesonbuild.com/Reference-manual_functions.html#arguments17, this should require meson 0.52.0, so I expected to get a nice warning from mesa about the issue like I do for others, eg:

> WARNING: Project specifies a minimum meson_version '>= 0.47.0' but uses features which were added in newer versions:

However, there was no such warning reported when I ran meson 0.62.1

**Comment by eli-schwartz** [comment]
It's correctly tagged as an `@FeatureNewKwargs` decorator in the original implementation of the feature: https://github.com/mesonbuild/meson/pull/5953/files#diff-e78ea7c334479feadcf670a4f9d33ff4479cfc539e100892ccdb9d2c56691d6dR3072

```
$ cat t/meson.build
project('test', 'c', 'cpp', version: '1', meson_version: '>=0.51.0', )

rpc_dep = dependency('libtirpc', required: false, include_type: 'system')
$ ./meson.py setup t/ t/builddir/
The Meson build system
Version: 0.63.0.rc1
Source dir: /home/eschwartz/git/meson/t
Build dir: /home/eschwartz/git/meson/t/builddir
Build type: native build
Project name: test
Project version: 1
C compiler for the host machine: ccache cc (gcc 11.1.0 "cc (GCC) 11.1.0")
C linker for the host machine: cc ld.bfd 2.36.1
C++ compiler for the host machine: ccache c++ (gcc 11.1.0 "c++ (GCC) 11.1.0")
C++ linker for the host machine: c++ ld.bfd 2.36.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
../t/meson.build:3: WARNING: Project targets '>=0.51.0' but uses feature introduced in '0.52.0': include_type arg in dependency.
Found pkg-config: /usr/bin/pkg-config (1.8.0)
Run-time dependency libtirpc found: YES 1.3.2
Build targets in project: 4
WARNING: Project specifies a minimum meson_version '>=0.51.0' but uses features which were added in newer versions:
 * 0.52.0: {'include_type arg in dependency'}
```

 Based on the xserver MR link and discussion, it seems you actually did specify 0.52.0 in meson.build...
