### ISSUE TITLE
0.36.0 test regression test cases/frameworks/13 yelp

### ISSUE THREAD

**Issue by anthraxx** [mesonbuild/meson#1052]
Hi, after trying to package the new 0.36.0 version i have noticed a test regression in ```test cases/frameworks/13 yelp```. I have used ```MESON_PRINT_TEST_OUTPUT=1``` but not quote sure what the problem is:

```
Failed test: test cases/frameworks/13 yelp
Reason: Running install failed.
The Meson build system
Version: 0.36.0
Source dir: /build/meson/src/meson-0.36.0/test cases/frameworks/13 yelp
Build dir: /build/meson/src/meson-0.36.0/b 9cu54r21
Build type: native build
Project name: yelp
Native c compiler: cc (gcc 6.2.1)
Appending CFLAGS from environment: '-march=i686 -mtune=generic -O2 -pipe -fstack-protector-strong'
Appending LDFLAGS from environment: '-Wl,-O1,--sort-common,--as-needed,-z,relro'
Appending CPPFLAGS from environment: '-D_FORTIFY_SOURCE=2'
Build machine cpu family: x86
Build machine cpu: i686
Build targets in project: 2
ninja: no work to do.
No tests defined.
No benchmarks defined.
[0/1] Installing files.
Running custom install script /usr/bin/python3
Failed to run install script: /usr/bin/python3 /build/meson/src/meson-0.36.0/meson.py --internal yelphelper install --subdir=help --id=meson --installdir=share/help --sources=index.page --media=media/test.txt --langs=de@@es
FAILED: install 
'/usr/bin/python3' '/build/meson/src/meson-0.36.0/meson.py' '--internal' 'install' '/build/meson/src/meson-0.36.0/b 9cu54r21/meson-private/install.dat'
ninja: build stopped: subcommand failed.
```

**Comment by anthraxx** [comment]
Actually it seems to be because of missing ```itstool```, when installing it into the clean chroot before building it passes. Shouldn't this be skipped in case something is missing?

**Comment by QuLogic** [comment]
It looks like the yelp helper doesn't really check for any of its required executables at all.

**Comment by TingPing** [comment]
Neither the i18n or gnome module check for the tools they just fail. Was on my todo list to clean up the error messages.

**Comment by tp-m** [comment]
See #821 for the i18n check issue.

**Comment by snsmac** [comment]
This seems to be fixed with: 
https://github.com/mesonbuild/meson/pull/3060
https://github.com/mesonbuild/meson/commit/d78f88160a9ee1cc8d75274599d6c45c7e678d9a

See also:
https://github.com/mesonbuild/meson/issues/2325

But in my opinion it would be better if the gnome.yelp module would check for the required dependencies so that its not needed to manually check for them every time
