### ISSUE TITLE
has_function fails to detect missing dependencies with CFLAGS=-O1

### ISSUE THREAD

**Issue by lantw44** [mesonbuild/meson#1053]
GStreamer uses `cc.has_function('backtrace', prefix : '#include <execinfo.h>')` to check whether it can use backtrace-related functions. Using these functions doesn't require linking extra libraries on GNU/Linux, but it is required to link with `-lexecinfo` on FreeBSD. Therefore, I have to write a meson alternative to autoconf `AC_SEARCH_LIBS` macro.

I implemented it with this patch: https://bugzilla-attachments.gnome.org/attachment.cgi?id=339827
However, this only worked with `CFLAGS=-O0`:
```
Has header "execinfo.h": YES
Checking for function "backtrace": NO    # without -lexecinfo
Library execinfo found: YES
Checking for function "backtrace": YES   # with -lexecinfo
```

If I set `CFLAGS=-O1` in the environment, the first `has_function` test didn't fail and caused undefined reference error when linking `libgstreamer-1.0.so`:
```
Has header "execinfo.h": YES
Checking for function "backtrace": YES   # without -lexecinfo
...
[99/442] Linking target gst/libgstreamer-1.0.so.0.1100.0
FAILED: gst/libgstreamer-1.0.so.0.1100.0 
gst/gstreamer-1.0@sha/gstinfo.c.o: In function `generate_backtrace_trace':
gst/gstinfo.c:2707: undefined reference to `backtrace_symbols'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

I tested it on FreeBSD 11.0 with clang 3.8.0 and binutils 2.27.

**Comment by jpakkane** [comment]
Can you test if #1066 fixes the issue for you?

**Comment by lantw44** [comment]
Yes, it works for me.
