### ISSUE TITLE
Unsupported Visual Studio target machine: Win32

### ISSUE THREAD

**Issue by yyc12345** [mesonbuild/meson#10539]
**Describe the bug**
meson throw exception `Unsupported Visual Studio target machine: Win32`

**To Reproduce**
This problem was happened on my build work of glib. There are the steps to reproduce this issue.

* Download glib with tag [v2.72.1](https://gitlab.gnome.org/GNOME/glib/-/tags/2.72.1).  
* Open **x86 Native** Tools Command Prompt for VS 2019. Btw, my machine is on x64 platform.  
* Use following command to execute meson:  
```
cd /d root_of_glib
mkdir _buildprj
cd _buildprj
meson .. --buildtype=release --prefix=D:/CppLib/GLib/Win32 --backend=vs2019
```

The build of glib for x64 platform was perfect. But when I was trying building this for Win32 platform. It threw this exception.

**Expected behavior**
meson should generate correct Visual Studio project files, rather than throwing exception.

I have done some work with my view. I traced this exception and I noticed this line: https://github.com/mesonbuild/meson/blob/5f8b0487abf501a09c51387791b578a148c973e2/mesonbuild/backend/vs2010backend.py#L1315  
It was pretty weird according to my understanding, so I changed it to `targetplatform = platform.lower()`. Then, everything work as my expect. I don't know whether this modification is suit for this project, so I open an issue rather than opening a PR.

**System parameters**
* Maybe this is a cross build. Because I try building an x86 project in a x64 computer.  
* OS: Windows 10 (21H1)
* Visual Studio version: Visual Studio Community 2019 (16.11.3)
* Python version : 3.9.0
* Meson version: 0.62.2
* Machine Platform: x64

**Comment by eli-schwartz** [comment]
> I don't know whether this modification is suit for this project, so I open an issue rather than opening a PR.

It seems reasonable to me, feel free to open a PR.

**Comment by yyc12345** [comment]
Thanks for you acknowledge. I have opened a PR. (and sorry for opening a PR in the wrong place at first)  
I am not familiar with meson. I didn't even use meson 1 day ago until I built glib. Furthermore, I don't know whether my modification can affect the build of any other architectures. This is the reason why I open a issue,
