### ISSUE TITLE
testlog.txt etc don't contain output of tap tests anymore

### ISSUE THREAD

**Issue by anarazel** [mesonbuild/meson#10563]
Starting with 702f3fe15 meson-logs/testlog.txt don't contain output from tap test failures anymore. And not just when the test succeed, even when the tap test failed. @trhd I assume this was not intentional?

Reproducer:
```
project('repro', ['c'])

test('ex', find_program('echo'),
     args: ['ok 1 - frak
# diag
not ok 2 - blarg
1..2
'],
     protocol: 'tap',
    )
```
with 0.62 that'll include 
```
----------------------------------- output -----------------------------------
ok 1 - frak
# diag
not ok 2 - blarg
1..2
```
in the log, but with 702f3fe15 that's not included anymore.

Obviously testlog.txt (etc) need to include the test output...

**Comment by eli-schwartz** [comment]
> Seems to have slipped in when #9930's commits were reordered for partial merging.

It could equally be said that it slipped in when 702f3fe15f767692928073a60bde8b699fdd445e and 89f4666590dc770b1ebbc634586548d2cc77f37a were originally committed as one commit that broke functionality and another commit that then fixed it, such that neither commit was standalone...

Anyway @bonzini opinions?
