### ISSUE TITLE
OSError: [Errno 26] Text file busy Mint VM (virtualBox)

### ISSUE THREAD

**Issue by RafaelRMachado** [mesonbuild/meson#10567]
**Describe the bug**
Fail to build a project https://github.com/rizinorg/rizin on a Linux Mint (linuxmint-20.3-xfce-64bit) virtualbox vm

**To Reproduce**

Rizin project instructions are:
$ git clone https://github.com/rizinorg/rizin
$ meson build
$ ninja -C build
$ sudo ninja -C build install

When running meson build, the following error happens:

The Meson build system
Version: 0.63.0
Source dir: /mnt/VBoxShare/rizin
Build dir: /mnt/VBoxShare/rizin/build
Build type: native build
Project name: rizin
Project version: v0.4.0
C compiler for the host machine: cc (gcc 9.4.0 "cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0")
C linker for the host machine: cc ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program python3 found: YES (/usr/bin/python3)
Program git found: YES (/usr/bin/git)
Message: rizin lib version: 0.4
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/mesonbuild/mesonlib/universal.py", line 1684, in cleanup
    super().cleanup()
  File "/usr/lib/python3.8/tempfile.py", line 970, in cleanup
    self._rmtree(self.name)
  File "/usr/lib/python3.8/tempfile.py", line 952, in _rmtree
    _rmtree(name, onerror=onerror)
  File "/usr/lib/python3.8/shutil.py", line 722, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib/python3.8/shutil.py", line 720, in rmtree
    os.rmdir(path)
OSError: [Errno 26] Text file busy: '/mnt/VBoxShare/rizin/build/meson-private/tmprr0_s2so'

**Expected behavior**
Build should work correctly so the next step would be performed (ninja -C build)

* what `meson --version`
0.63.0

* what `ninja --version` if it's a Ninja build
1.10.0

**Comment by eli-schwartz** [comment]
I don't see how this is a Meson bug? Your VBoxShare appears to be stopping Meson from deleting a file or something?

**Comment by RafaelRMachado** [comment]
Well, meson told it was its fault:

OSError: [Errno 26] Text file busy: '/mnt/VBoxShare/rizin/build/meson-private/tmprr0_s2so'

meson.build:96:0: ERROR: Unhandled python exception

    This is a Meson bug and should be reported!

**Comment by dcbaker** [comment]
We could return a nicer error message and/or throw a MesonException instead of allowing the builtin exception to propogate up. Either of these changes would be fairly trivial, and a good easy fix for someone wanting to get their feet wet

**Comment by duckflyer** [comment]
Hi @eli-schwartz  and @dcbaker, we opened a new pull request #10646, that gives a nicer error message.

Shay & Omer

**Comment by theyashl** [comment]
Hi @eli-schwartz and @dcbaker , as @duckflyer 's PR has been merged for the fix, can we please close this issue?
