### ISSUE TITLE
GJS tests get stuck since Meson 0.63.0

### ISSUE THREAD

**Issue by heftig** [mesonbuild/meson#10577]
**Describe the bug**

Some of GJS 1.72.1's tests time out since Meson 0.63.0. Meson 0.62.2 is fine.
GJS issue report at https://gitlab.gnome.org/GNOME/gjs/-/issues/490.

Stderr is no longer properly consumed for TAP tests, so the test gets stuck when the pipe is full. It seems #10471 broke this. 

**To Reproduce**
```
git clone https://gitlab.gnome.org/GNOME/gjs.git
cd gjs
git checkout 1.72.1
meson . b
meson compile -C b
meson test -C b --print-errorlogs
```

**Expected behavior**
Tests pass.

**system parameters**
* Native build
* Arch Linux
* Python 3.10.5
* Meson 0.63.0
* Ninja 1.11.0

**Comment by eli-schwartz** [comment]
This was also reported to @jpakkane in Debian as https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1014417
