### ISSUE TITLE
`meson help foo` KeyError

### ISSUE THREAD

**Issue by baedert** [mesonbuild/meson#10584]
**Describe the bug**
`meson help <arg>` needs an existing command as `<arg>`. Passing anything else leads to a `KeyError` instead of a nice error message.

**To Reproduce**
```
~ ❯ meson --version
0.62.2
~ ❯ meson help foo
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/mesonbuild/mesonmain.py", line 153, in run
    return options.run_func(options)
  File "/usr/lib/python3.10/site-packages/mesonbuild/mesonmain.py", line 118, in run_help_command
    self.commands[options.command].print_help()
KeyError: 'foo'

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!

```

**Expected behavior**
Some error message like "unknown command 'foo'" would be better, and/or list the available valid `<arg>` values.

**Comment by theyashl** [comment]
Hi, I want to work on this issue.
I have the modified code ready with me in which if unknown command is passed to help module, meson will just print the basic meson usage help. If any other approach is needed, I'm ready to modify it.

**Comment by dcbaker** [comment]
The best way to get code review is to open a merge request :)

**Comment by theyashl** [comment]
Just opened a MR! Hope it does the expected work. Thank you! :)
