### ISSUE TITLE
Qt6 module documentation is really Qt5

### ISSUE THREAD

**Issue by punytroll** [mesonbuild/meson#10581]
**Describe the problem**

The documentation for the Qt6 module (https://mesonbuild.com/Qt6-module.html) is still very much a Qt5 documentation. This is confusing for people starting out using the Qt6 module.

**Expected behavior**

- At least the introductory explanation should refer to Qt6.
- Also, the examples should reference the Qt6 module, not the Qt5 module.
- Functionality on the page refers to the meson version it was introduced in, but a lot of those versions are earlier (0.44, 0.48, 0.49, 0.54, 0.56) than the version that the Qt6 module was added (0.57).

**Comment by tristan957** [comment]
Can you submit a PR if you have a chance?

**Comment by punytroll** [comment]
Hi. I would ... but for two problems:
1. I was, and still am, somewhat confused about the correct usage of the qt6 module. So my attempt at fixing the problems in the documentation might be prone to errors. But that's up for comments, once I'm done writing.
2. I don't know how to deal with the modularized documentation. The page about qt6 only has once sentence (which I should fix) and then imports another general document. So, in order to really fix the issues, I would need to copy the documentation and make qt6-specific changes. Is that wanted?

Regards, ...

**Comment by tristan957** [comment]
@punytroll re 2 I think that would be correct.

**Comment by AHSauge** [comment]
So my assumption, knowing little about how this is implemented, is that Qt5 and Qt6 modules work pretty much the same. At least I hit no trouble based on that. If there is a difference, then indeed that certainly should be documented.

Second to that, since I can only assume people will start to begin transitioning from Q5 to Q6 these days; what is the best way to compile against Q6 if available and fall back to Qt5? With that in mind I would certainly argue that the difference between how they are handled in meson (from a user/builder perspective) should be minimal and ideally none. 

Right now for the fall back I'm doing this which seems to work, but I'm not sure if there's a more elegant way of doing this. Sadly `force_qt5` is needed in my case as there are bugs in the Qt6 code path for some platforms
```
#First checking for Qt6 unless we want to force Qt5
if get_option('force_qt5')
    qt = disabler()
    qt_dep = disabler()
else
    qt = import('qt6', required: false)
    qt_dep = dependency('qt6', modules: ['Core', 'Gui', 'Widgets'], private_headers: true, required: false)
endif

#Requiring Qt5 if Qt6 isn't found 
if not qt.found() or not qt_dep.found() 
    qt = import('qt5')
    qt_dep = dependency('qt5', modules: ['Core', 'Gui', 'Widgets'], private_headers: true)
endif
```

**Comment by tristan957** [comment]
```meson
if get_option('qt5')
  qt_pkg = 'qt5'
else
  qt_pkg = 'qt6'
endif

qt = import(qt_pkg)
qt_dep = dependency(qt_pkg, modules: ['Core', 'Gui', 'Widgets'], private_headers: true)
```

That probably looks a little bit better. Though I am sure there aren't too many projects using both qt5 and qt6

**Comment by AHSauge** [comment]
> ```meson
> if get_option('qt5')
>   qt_pkg = 'qt5'
> else
>   qt_pkg = 'qt6'
> endif
> 
> qt = import(qt_pkg)
> qt_dep = dependency(qt_pkg, modules: ['Core', 'Gui', 'Widgets'], private_headers: true)
> ```
> 
> That probably looks a little bit better. Though I am sure there aren't too many projects using both qt5 and qt6, and without reviewing docs, I am not sure how feasible this is.

Yeah, but that still misses the fall back. It does give full control over what to compile against, so I suppose it's better that away.

With regards to supporting both: Given that Qt state Qt6 is as source compatible with Qt5(.15) as feasible, my guess is that there will be more projects supporting both than we've seen with for instance 4 to 5. At least from a library perspective and in a transition period it makes sense to me. If you don't use anything deprecated in Qt5.15, then from what I understand moving to Qt6.2 is usually fairly straightforward. You just end up using deprecated stuff in Qt6 instead.

**Comment by tristan957** [comment]
```meson
qt_dep = dependency('qt6', 'qt5', modules: ['Core', 'Gui', 'Widgets'], private_headers: true)
qt = import('qt@0@'.format(qt_dep.version().split('.')[0])
```

Might try something like that instead. Add `force_qt5` as you see fit.

**Comment by AHSauge** [comment]
> ```meson
> qt_dep = dependency('qt6', 'qt5', modules: ['Core', 'Gui', 'Widgets'], private_headers: true)
> qt = import('qt@0@'.format(qt_dep.version().split('.')[0])
> ```
> 
> Might try something like that instead. Add `force_qt5` as you see fit.

That turned things a lot cleaner for me. I didn't realise `dependency` could be used that way, but that's exactly what I was looking for. Thanks!
