### ISSUE TITLE
vk-bootstrap - Sandbox violation error

### ISSUE THREAD

**Issue by Utfnid** [mesonbuild/meson#10596]
(Sorry for bad English)
Hello, i tried to use vk-bootstrap in my meson project, but it doesn't compile due to the error "Sandbox violation: Tried to grab file context.c outside current (sub)project."

**To Reproduce**
I created the subprojects dir inside the root (where meson.build is placed). I initialized there a git repo by using VS Code default Source Control, then moved to subprojects, and then entered the command "git submodule add https://github.com/charles-lunarg/vk-bootstrap". In the root folder i have meson.build and main.cpp [Test.zip](https://github.com/mesonbuild/meson/files/9096011/Test.zip), and the only command i entered is "meson build"

**Expected behavior**
I expected that it works just like the other libraries i use (glfw, VulkanMemoryAllocator, volk etc).

**system parameters**
* This isn't a cross build
* Windows 10 21H2
* Python 3.10.5
* meson version 0.63.0
* ninja version 1.10.2.git.kitware.jobserver-1
* vk-bootstrap [this commit](https://github.com/charles-lunarg/vk-bootstrap/tree/d4dba531197bd452ac51441d2d37c6605745e003)

**Log file**
[meson-log.txt](https://github.com/mesonbuild/meson/files/9095964/meson-log.txt)

**Comment by eli-schwartz** [comment]
Incidentally, this project is trying to unconditionally download and use a copy of glfw, and the sandbox violation occurs inside glfw.
