### ISSUE TITLE
Is llvm with CMake is always static and nothing changed from 0.51x?

### ISSUE THREAD

**Issue by rilian-la-te** [mesonbuild/meson#10592]
**Describe the bug**
I want to cross-compile with CMake-based LLVM detection (without LLVM-config). LLVM should be dynamic lib (at best, it should find libLLVM.so) with CMake. We cannot use llvm-config from cross-file due to qemu requirement (to run mipsel binaries on amd64), so, I do not provide it in cross file.

**To Reproduce**
Make native mipsel debian chroot via debootstrap
Try to compile some llvm-dependent package with sysroot of this chroot. Non-llvm dependent library works fine.

**Expected behavior**
LLVM should be found without using qemy bu CMake usage.

**system parameters**
* Cross build, Ubuntu 20.04 -> debian bullseye mipsel
* 3.8.10
* 0.63.0
* 1.10.0
Cross-file:

```
[constants]
fs = '/mnt/chroot/debian'
common_flags = ['--sysroot=' + fs ]

[host_machine]
system = 'linux'
cpu_family = 'mips'
cpu = 'mips32'
endian = 'little'

[properties]
sizeof_int = 4
sizeof_wchar_t = 4
sizeof_void* = 4

alignment_char = 1
alignment_void* = 4
alignment_double = 4

has_function_printf = true

sys_root = fs
pkg_config_libdir = [fs + '/usr/lib/mipsel-linux-gnu/pkgconfig', fs + '/usr/share/pkgconfig']

c_args = common_flags + ['-I' + fs + '/usr/include', '-L' + fs + '/usr/lib/mipsel-linux-gnu']

[binaries]
c = 'mipsel-linux-gnu-gcc'
cpp = 'mipsel-linux-gnu-g++'
strip = 'mipsel-linux-gnu-strip'
pkgconfig = 'pkg-config'
```

**Comment by eli-schwartz** [comment]
My understanding is that this is a flaw in llvm's own cmake files.

At any rate, this has not changed in meson git master.

**Comment by rilian-la-te** [comment]
@eli-schwartz I tried to fix it in my PR, but it certainly has bug. How I can unittest it? How LLVM dependency handling is unit tested at all?

**Comment by eli-schwartz** [comment]
In the `test cases/` directory there should be some cmake tests. Trying to run a project test with `method: 'cmake'` should get you more or less what you want.

But I'll leave meaningful responses to the person that actually understands our cmake support (I've assigned the PR already).
