### ISSUE TITLE
`install_plan` metadata has full path in destination instead of being based on a placeholder

### ISSUE THREAD

**Issue by FFY00** [mesonbuild/meson#10601]
**Describe the bug**

Introduced in 0.63.0.

Discovered in https://github.com/FFY00/meson-python/issues/95.

**To Reproduce**

Package: https://github.com/FFY00/meson-python/tree/main/tests/packages/purelib-and-platlib
Generated metadata:
```json
{
  "targets": {
    "/home/anubis/git/mesonpy/tests/packages/purelib-and-platlib/builddir/plat.cpython-310-x86_64-linux-gnu.so": {
      "destination": "/usr/lib/python3.10/site-packages/plat.cpython-310-x86_64-linux-gnu.so",
      "tag": "runtime"
    }
  },
  "python": {
    "/home/anubis/git/mesonpy/tests/packages/purelib-and-platlib/pure.py": {
      "destination": "{py_purelib}/pure.py",
      "tag": "runtime"
    }
  }
}
```

**Expected behavior**
It should generate the following metadata instead
```json
{
  "targets": {
    "/home/anubis/git/mesonpy/tests/packages/purelib-and-platlib/builddir/plat.cpython-310-x86_64-linux-gnu.so": {
      "destination": "{moduledir_shared}/plat.cpython-310-x86_64-linux-gnu.so",
      "tag": "runtime"
    }
  },
  "python": {
    "/home/anubis/git/mesonpy/tests/packages/purelib-and-platlib/pure.py": {
      "destination": "{py_purelib}/pure.py",
      "tag": "runtime"
    }
  }
}
```

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? No
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.): Reproduced on many Linux distros at least
* what Python version are you using e.g. 3.8.0: 3.10.5
* what `meson --version`: 0.63.0
* what `ninja --version` if it's a Ninja build: 1.10.2.git.kitware.jobserver-1

**Comment by eli-schwartz** [comment]
I realize that when I first drafted #9478 I actually commented on this.
> Still, it is a start at the correct solution. I think the remaining factor here will be either:
> 
>   * subclassing SharedModule to PythonSharedModule and teaching it a better constructor
> 
>   * teaching Target to accept an arbitrary override, like build.Data does, which contains a better value

**Comment by eli-schwartz** [comment]
So the problem is that 0.62.0 generated, for `import mod.submod`, the following install plan:

```
"destination": "{moduledir_shared}/submod.cpython-310-x86_64-linux-gnu.so",
```

What we actually *want* is:
```
"destination": "{moduledir_shared}/mod/submod.cpython-310-x86_64-linux-gnu.so",
```

What 0.63.0 gave us:
```
"destination": "/usr/lib/python3.10/site-packages/mod/submod.cpython-310-x86_64-linux-gnu.so",
```
