### ISSUE TITLE
Header-only library

### ISSUE THREAD

**Issue by Fingolfin1196** [mesonbuild/meson#10605]
I am trying to create a `meson.build` file for a header-only library (analogously to a CMake `INTERFACE` target), but even after a lot of searching, I cannot find a way to do that. I have found [this file](https://github.com/mesonbuild/meson/blob/0703ee0aef68e235c1e22d6448b79dfbbb5c8039/mesonbuild/cmake/interpreter.py#L87), which shows that the CMake interpreter supports `INTERFACE` targets, but I cannot find a way to use this directly in Meson. I have tried using `library`, but that generates a bogus `.so` file when compiling.

**Comment by dcbaker** [comment]
Generally you just need a declare_dependency() object with the proper include_directories set. There are some examples of this in the wrapdb

**Comment by Fingolfin1196** [comment]
I’ve experimented with `declare_dependency` today and understand the concepts used by Meson better now, coming from CMake and having only used Meson for executables before this. Thanks a lot for the hint!

**Comment by eli-schwartz** [comment]
> coming from CMake and having only used Meson for executables before this

Yeah, cmake calls these a type of library even though the interface that they look like is the same as a `pkg_check_modules()` or a `find_package()` (under the hood both of them create "libraries" anyway, but that's not their visible interface). Meson just calls them dependencies no matter where they come from and lets you create them out of a union of e.g. a library and a header include (and/or compiler flags).
