### ISSUE TITLE
Windows .msi release missing

### ISSUE THREAD

**Issue by tech189** [mesonbuild/meson#10615]
Since [0.62.2](https://github.com/mesonbuild/meson/releases/tag/0.62.2), the last 3 versions of Meson don't have a Windows .msi release in the Assets section. The last release to include it was [0.62.1](https://github.com/mesonbuild/meson/releases/tag/0.62.1) - https://github.com/mesonbuild/meson/releases/download/0.62.1/meson-0.62.1-64.msi

**Comment by eli-schwartz** [comment]
This is a known issue, see e.g. https://github.com/mesonbuild/meson/discussions/10467

**Comment by tech189** [comment]
Ah apologies, I didn't think to check the discussions tab, glad to see it's almost fixed

**Comment by tech189** [comment]
All fixed now, thank you!
