### ISSUE TITLE
Multiple producers for Ninja target error on meson v0.45.1-v0.53.2 workaround?

### ISSUE THREAD

**Issue by dwsteele** [mesonbuild/meson#10626]
**Describe the bug**

Getting `ERROR: Multiple producers for Ninja target "test-unit@exe/buffer.c.o". Please rename your targets.` with the following meson.build:
[meson.build.txt](https://github.com/mesonbuild/meson/files/9173986/meson.build.txt)

This is a generated build for a unit test. It works fine on 0.61.2.

**To Reproduce**
See above (looks similar to #3797). The weird thing is having the same file name seems to work just fine in the regular build: https://github.com/pgbackrest/pgbackrest/blob/main/src/meson.build

**Expected behavior**
It works fine in newer versions but I was wondering if there is a workaround for older versions.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? plain native
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) 
Ubuntu 18.04/20.04
* what Python version are you using e.g. 3.8.0
3.6 (Ubuntu 18.04) 3.8 (Ubuntu 20.04)
* what `meson --version`
0.45.1 (Ubuntu 18.04) 0.53.1 (Ubuntu 20.04)
* what `ninja --version` if it's a Ninja build
1.8.2 (Ubuntu 18.04) 1.10.0 (Ubuntu 20.04)

**Comment by eli-schwartz** [comment]
Hmm, is there a reason these are using absolute filepaths?

**Comment by dwsteele** [comment]
Yes. The project being built here is a unit test (meson.build is automatically generated). It needs to reference source from the original code repo, which could be located anywhere. On a Unix host this can always be expressed as a relative path, but on Windows that might not be possible based on where the test path is vs the code repo path.

So, it just seemed easier to use absolute paths. This also makes debugging quite a bit easier and works well with our coverage reporting tool.

That said, I switched to relative paths and that solved the issue for older meson versions. It's not ideal, but supporting older meson versions is critical for us to roll out meson support. 18.04 will be EOL in a year or so but 20.04 will be active for three more years. That's a long time to wait and requiring a specific version of meson for Debian packaging, at least, is an issue.

**Comment by eli-schwartz** [comment]
Hmm, but the unit tests aren't part of the same meson project that is being tested? :)

> That said, I switched to relative paths and that solved the issue for older meson versions. It's not ideal, but supporting older meson versions is critical for us to roll out meson support.

Good to hear my stab in the dark helped. :) I do agree that needing to support older systems is a valid critical requirement.

If I had to guess what's happening, the older versions of Meson don't define the output name based on the full path with sanitized slashes, but only based on the last component, only when given an absolute path? I don't know why that would be, but I haven't tried to bisect or trace this issue and I'm pretty sure at least newer versions of Meson do sanitize and use the entire path used as a meson.build input name.

**Comment by dwsteele** [comment]
> Hmm, but the unit tests aren't part of the same meson project that is being tested? :)

Currently, no. It *may* be possible for meson to handle our unit tests, but we aren't there yet.

> I'm pretty sure at least newer versions of Meson do sanitize and use the entire path used as a meson.build input name

Yes, they do. It happened somewhere after 0.53 and 0.61. I haven't bisected, either, just working with the versions that are available on various distros we use for testing.
