### ISSUE TITLE
ninja: build stopped: 'some/path.o' not mentioned in its dyndep file 'some/path/depscan.dd'

### ISSUE THREAD

**Issue by Volker-Weissmann** [mesonbuild/meson#10629]
**Describe the bug**
The follow error messages appears in my project.
```
ninja: build stopped: 'libscotchDecomp.so.p/plusplus.C.o' not mentioned in its dyndep file 'libscotchDecomp.so.p/depscan.dd'
```
Weirdly, it dissappears if I replace `project('SCOTCH', ['c', 'fortran'])` with `project('SCOTCH', ['c'])`, even though Fortran is never used in the example.

It would be nice if you could either fix the bug, or point me in the right direction to fix it.

Interestingly, this bug only appears if the C++ file ends with .C, not with .cpp. Feel free to say "told you so", as I'm the guy who wrote https://github.com/mesonbuild/meson/pull/8747.

**To Reproduce**
[withFortran.zip](https://github.com/mesonbuild/meson/files/9184433/withFortran.zip)

```
$ cd withFortran
$ meson setup build
$ ninja -C build/ libscotchDecomp.so.p/plusplus.C.o
ninja: Entering directory `build/'
[1/2] Module scanner.
ninja: build stopped: 'libscotchDecomp.so.p/plusplus.C.o' not mentioned in its dyndep file 'libscotchDecomp.so.p/depscan.dd'.
```

**Expected behavior**
`ninja -C build/ libscotchDecomp.so.p/plusplus.C.o` should run without errors, `ninja -C build` should error out.

**system parameters**
* Native Build
* Arch Linux
* Python 3.10.5
* meson 0.63.0
* ninja 1.11.0

**Comment by eli-schwartz** [comment]
There are two weird things. First, fortran uses the depscanner (dyndeps because modules), but no actual fortran code is being built or linked here. So why is the presence of it in languages causing dyndeps to be triggered on a C++ file? Moreover, why only... if there's a generated header in sources? Because .h is "can_compile" for gfortran.

Second, this only happens for C++ files named as .C, not ones which are named with better extensions such as .cc or .cpp;  this happens because we compare suffixes case insensitively and don't realize that `plusplus.C` is one of the files we tried to scan, here.

**Comment by eli-schwartz** [comment]
> Interestingly, this bug only appears if the C++ file ends with .C, not with .cpp. Feel free to say "told you so", as I'm the guy who wrote #8747.

Ah yes, nice edit, we discovered the same thing. I didn't want to say anything, but, you're quite correct there...

**Comment by Volker-Weissmann** [comment]
> There are two weird things. First, fortran uses the depscanner (dyndeps because modules), but no actual fortran code is being built or linked here. So why is the presence of it in languages causing dyndeps to be triggered on a C++ file? Moreover, why only... if there's a generated header in sources? Because .h is "can_compile" for gfortran.
> 
> Second, this only happens for C++ files named as .C, not ones which are named with better extensions such as .cc or .cpp; this happens because we compare suffixes case insensitively and don't realize that `plusplus.C` is one of the files we tried to scan, here, so it's not listed in the json file.
> 
> If I fix that in the ninjabackend, then depscan errors out with `Can not scan files with suffix .c.`
> 
> After removing two calls to `.lower()`, this works for me, albeit wastefully running a fortran module scanner on a C++ file that doesn't use C++20 modules.

You're a wizard. Figuring this out would take me thirty hours, not thirty minutes.

**Comment by eli-schwartz** [comment]
PR submitted.

**Comment by Volker-Weissmann** [comment]
> PR submitted.

Thank you.
