### ISSUE TITLE
cc1: error,  Compiler riscv64-unknown-elf-gcc can not compile programs

### ISSUE THREAD

**Issue by jaycbhsn** [mesonbuild/meson#10625]
**Describe the bug**
When attempting to build for a Nexys Video board using Linux on LiteX, it claims that this compiler cannot cross-compile for the specified board. This also happens with LiteX simulations.

**To Reproduce**
[build.zip](https://github.com/mesonbuild/meson/files/9172163/build.zip)

The Error according to the logs:
Sanity check compile stdout:

-----
Sanity check compile stderr:
cc1: error: -march=rv32i2p0_ma: unsupported ISA substring '2p0_ma'

-----

../../../../../pythondata-software-picolibc/pythondata_software_picolibc/data/meson.build:35:0: ERROR: Compiler riscv64-unknown-elf-gcc can not compile programs.

**Expected behavior**
I would expect that it would run without encountering this error.

**system parameters**
* This is for a cross build (riscv64-unknown-elf-gcc-8.1.0-2019.01.0-x86_64-linux-ubuntu14)
* Ubuntu 20.04.4
* 3.8.10
* 0.62.2
* 1.10.2.git.kitware.jobserver-1

**Comment by jpakkane** [comment]
These kinds of errors typically indicate something wrong with your toolchain setup. If you try to compile some simple C file with

    riscv64-unknown-elf-gcc -c -o /dev/null -march=rv32i2p0_ma -mabi=ilp32 somefile.c

does it work?

Unrelated to that your cross file has a _lot_ of things in it that really should not be there, like ´-Os` that should be set with the buildtype and `-MD` and `-MP` that you should not have at all, Meson will take care of those automatically

**Comment by eli-schwartz** [comment]
> Sanity check compile stderr:
> cc1: error: -march=rv32i2p0_ma: unsupported ISA substring '2p0_ma'

This is a GCC error. It comes from a flag in your cross file: `c_args      = [ '-Os', '-march=rv32i2p0_ma', '-mabi=ilp32',  ......`

> I would expect that it would run without encountering this error.

Why? You told Meson to invoke the compiler like this, and the compiler claims that it *cannot* be invoked like this. What should Meson do to allow it to run?

**Comment by jaycbhsn** [comment]
Thanks, it was an issue with my toolchain. I didn't have a certain package installed

**Comment by Ifoufou** [comment]
In my case, the package `gcc-riscv64-unknown-elf` was missing.

**Comment by xlgforever** [comment]
> In my case, the package `gcc-riscv64-unknown-elf` was missing.
i am use ubuntu18, and i also have the same error, and i can't find a way to install gcc-riscv64-unknown-elf by using apt.

**Comment by Ifoufou** [comment]
If you prefer to not build it from source, you can use the prebuilt toolchain provided by SiFive. Few lines below to guide you:
```
wget -O riscv64-unknown-elf-gcc.tar.gz https://static.dev.sifive.com/dev-tools/riscv64-unknown-elf-gcc-8.3.0-2019.08.0-x86_64-linux-ubuntu14.tar.gz
tar -xzvf riscv64-unknown-elf-gcc.tar.gz
sudo mv ./riscv64-unknown-elf-gcc-8.3.0-2019.08.0-x86_64-linux-ubuntu14/ /opt/riscv
echo 'export PATH=/opt/riscv/bin:$PATH' >> ~/.bashrc
source ~/.bashrc
```
