### ISSUE TITLE
Backend sometimes ends up in the `User defined options` section of the configure output when not specified by user

### ISSUE THREAD

**Issue by tristan957** [mesonbuild/meson#10632]
**Describe the bug**
`backend` will show up even if I never set it as an option.
```
  User defined options
    backend       : ninja
    buildtype     : debug
```

**To Reproduce**
I think it only occurs after Meson reconfigures.

**Expected behavior**
Not show up in the output.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) fc36
* what Python version are you using 3.10.5
* what `meson --version` 0.62.2
* what `ninja --version` if it's a Ninja build 1.10.2

**Comment by eli-schwartz** [comment]
I think this happens because for some reason the backend is specially set in the saved options which are used by a reconfigure, whether the backend was specified or not.

I'm not sure why it's special cased though.
