### ISSUE TITLE
compiling vala app on mingw64 on windows apply suplied linker arguments before of the defaults

### ISSUE THREAD

**Issue by tudo75** [mesonbuild/meson#10643]
**Describe the bug**
I'm starting to explore programming Vala on Windows 11 with MSYS2/MinGW64
I have this test code ([https://github.com/tudo75/TestBuilderGtk4Vala/tree/windows](https://github.com/tudo75/TestBuilderGtk4Vala/tree/windows)) that I'm able to compile but I cannot overwrite the `-Wl,--subsystem,console` option for linker with `-Wl,--subsystem,windows` because the latter is applied before the default one.
If I run the create-exe.bat after a ninja build it create a correct version of the exe

**To Reproduce**
Clone the repository, and enter the directory
```
meson setup build
ninja -v -C build
```
execute
`build/src/testbuildergtk4vala.exe` 
and you'll notice that exe is opened through a console 
if you then execute
`create-exe.bat`
and retry 
`build/src/testbuildergtk4vala.exe` 
console disappear and PE is applied to exe correctly for a gui app

**Expected behavior**
my `link_args` options must overwrite default ones

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? 
  plain
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) 
  Windows 11
* what Python version are you using e.g. 3.8.0
  3.10.5-2
* what `meson --version`
  0.63.0
* what `ninja --version` if it's a Ninja build
  1.11.0

**Comment by dcbaker** [comment]
How are you setting the subsystem? Are you using the win_subsystem keyword or are you passing it manually?

**Comment by tudo75** [comment]
I use the default config of the msys2/mingw64 packages and they add the `-Wl,--subsystem,console` automatically so I tried to overwrite them passin the `-Wl,--subsystem,windows` trough the `link_args` parameter in executable in the `meson.build`

**Comment by dcbaker** [comment]
Meson injects the subsystem based on the value of the win_subsystem keyword argument. It sings like that needs to be changed to 'windows'. What does the actual `executable()` call look like?

**Comment by tudo75** [comment]
`./meson.build`:

```
project('testbuildergtk4vala', ['c', 'vala'],
          version: '0.1.0',
    meson_version: '>= 0.59.0',
  default_options: [ 'warning_level=2',
                     'werror=false',
                   ],
)

i18n = import('i18n')

gnome = import('gnome')

subdir('data')
subdir('src')
subdir('po')

gnome.post_install(
  glib_compile_schemas: true,
  gtk_update_icon_cache: true,
  update_desktop_database: true,
)
```

`./src/meson.build`:

```
testbuildergtk4vala_sources = [
  'main.vala',
  'window.vala',
  'application.vala',
]

testbuildergtk4vala_deps = [
  dependency('gtk4'),
  dependency('libadwaita-1'),
]

gnome = import('gnome')

testbuildergtk4vala_sources += gnome.compile_resources(
  'testbuildergtk4vala-resources',
  'testbuildergtk4vala.gresource.xml',
  c_name: 'testbuildergtk4vala'
)

executable(
  'testbuildergtk4vala', 
  testbuildergtk4vala_sources,
  vala_args: '--target-glib=2.50',
  link_args: '-Wl,--subsystem,windows',
  dependencies: testbuildergtk4vala_deps,
  install: true,
)
```

**Comment by eli-schwartz** [comment]
```
  link_args: '-Wl,--subsystem,windows',
```

This seems very wrong.

**Comment by tudo75** [comment]
done as you suggested and using ```win_subsystem: 'windows'``` work all as expected.
Thank you so much for your help
By the way prior to fill the bug I haven't found anything about win_subsystem arg googling

**Comment by eli-schwartz** [comment]
It's listed at https://mesonbuild.com/Reference-manual_functions.html#executable CTRL+F spots it. :)

Unfortunately, it's very bad info to try to google, because all results lead to Windows Subsystem for Linux...
