### ISSUE TITLE
[Question] Is there a equivalent keyword for `diff_files` before version 0.63.0

### ISSUE THREAD

**Issue by MichaelJeiShen** [mesonbuild/meson#10659]
Hi all,

I am trying to apply a diff file on my `subprojects`.
I know that on 0.63.0 there is a new feature [diff_files](https://mesonbuild.com/Wrap-dependency-system-manual.html#diff-files) can achive what I said.

However I need to stick with **0.61.3** for some reasons.
Is there a way to fulfill my needs in **0.61.3**?

Thanks,
Michael

**Comment by eli-schwartz** [comment]
You can directly fork the subproject, and use the fork instead.
