### ISSUE TITLE
How to print stdout to stderr when caputre: true for custom_target and failed

### ISSUE THREAD

**Issue by lygstate** [mesonbuild/meson#10651]
**Describe the bug**
```
undefsym = find_program('scripts/undefsym.py')
block_syms = custom_target('block.syms', output: 'block.syms',
                             input: [libqemuutil, block_mods],
                             capture: true,
                             command: [undefsym, nm, '@INPUT@'])
```
when block_syms  failed, we wanna see the stdout/stdout of  undefsym, but now we have nothing

**Comment by eli-schwartz** [comment]
I'd probably suggest accepting an `@OUTPUT@` argument, and having the script write directly to that file. Then Meson's executable wrapper won't step on the output itself.

That being said, Meson explicitly prints stderr if the script exited with failure, which is where information about the error should be going to anyway.
