### ISSUE TITLE
python module: python_installation needs custom installation path setter

### ISSUE THREAD

**Issue by marcusmueller** [mesonbuild/meson#10667]
**Describe the bug**

As shown in #10459 (and #8739, and potentially a few other), it's sometimes impossible for meson to know the "strangeness" of the local system in terms of python installation directories; not even specifying [--prefix helps](https://github.com/mesonbuild/meson/issues/10459#issuecomment-1207407876). My experience from 10 years of GNU Radio (which is a medium-to-large C++-with-a-lot-of-Python-wrapper-code project) is that you cannot preempt all upcoming distro changes (and bugs, see #10459's related [Fedora bug](https://bugzilla.redhat.com/show_bug.cgi?id=2097183#)), possibly, and sometimes also your users just "need" strange paths.

In that case, current python_installation object's `install_sources`, and `get_install_dir` completely use their value. Since the `subdir` is not available in the usual installation functions, this means that in a project that's not supposed to be uninstallable once in a while when some distro, python prefix manager or distro builder (yocto/openembedded, buildroot…) has a special requirement for python paths, you cannot use `python` module to handle installations, at all, even if you have a way to specify a custom python path in some option. The lack of user functions means that it's impossible to build a wrapper function, either. 

**To Reproduce**

*This is just a use case example*.
using Fedora 36, `meson setup --prefix=/tmp/foobar`
```meson
project('mvre-meson-prefix', 'cpp',
        version : '0.0.0-preview0')
py3_inst = import('python').find_installation('python3')
py3_inst_dir = py3_inst.get_install_dir()
message(py3_inst_dir)
py3_inst.install_sources('file.py', subdir : 'mvre-meson-prefix')
```

shows that it installs to /tmp/foobar/local/lib/python3.10/site-packages, which simply isn't sensible.

No, I could have something like 
```meson
py3_inst = import('python').find_installation('python3')
if get_option('custom_python_install_path') == ''
  py_inst_path = py3_inst.get_install_dir() / $SUPER_MODULE_NAME
else
  py_inst_path = get_option('custom_python_install_path') / $SUPER_MODULE_NAME
endif
```

and on every point where I (throughout a subdirectory-heavy tree, as dictated by the usually hierarchical nature of the python packaging system reflecting in my Pybind11-wrapped C++ code) need to install a single python file, do something like
```meson
install_data('__init__.py', py_inst_path / $SUB_MODULE_NAME)
```
but this doesn't propagate to subprojects, it requires maintainers to have scripting or vigilance to detect and reject changes that want to use the intuitively useful `python_installation.install_sources()` function. 

Especially the aspect of *needing to propagate to subprojects* means that this needs to be centrally solved. I guess that means we need to make the `python` module somehow sensitive to either an explicit call that sets a custom inst prefix, which then propagates to subprojects. Alternatively, make it sensitive to an option(?).

**Expected behavior**

Being able to tell the `python` module an explicit, --prefix-relative path, in case what meson usually calls *heuristics* for detection of the correct python installation path fails.

**system parameters**

* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? Already necessary for self-hosted builds, but *especially* necessary for cross-builds, as depending on, say, fedora's or debian's python config to figure out what your openembedded build wants as python installation directory cannot work 
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) – N/A (all)
* what Python version are you using e.g. 3.8.0 – N/A (all) 
* what `meson --version` 0.62.2
* what `ninja --version` if it's a Ninja build – N/A (all)

**Comment by eli-schwartz** [comment]
> it's sometimes impossible for meson to know the "strangeness" of the local system in terms of python installation directories

Of course it would be great if we could detect this by default, though that's covered by the other tickets.

> My experience from 10 years of GNU Radio (which is a medium-to-large C++-with-a-lot-of-Python-wrapper-code project) is that you cannot preempt all upcoming distro changes (and bugs, see #10459's related [Fedora bug](https://bugzilla.redhat.com/show_bug.cgi?id=2097183#)), possibly, and sometimes also your users just "need" strange paths.

... but I quite agree with this, and the option you request already exists and is documented at https://mesonbuild.com/Builtin-options.html#python-module

**Comment by marcusmueller** [comment]
'doh! Somehow, this slipped by me multiple times. Thank you for the nice reply, and sorry for the noise!
