### ISSUE TITLE
Flake8 errors in code base

### ISSUE THREAD

**Issue by AHSauge** [mesonbuild/meson#10672]
The contribution description mentions running flake8 in the [Python coding style](https://mesonbuild.com/Contributing.html#python-coding-style) section. Is this still valid? If so, then I'm getting a fair bit of errors (See: [flake8.log](https://github.com/mesonbuild/meson/files/9294929/flake8.log)). This is based on just running flake8 as-is without any input arguments. 

I'm more than happy to clean this up, but some guidance on what's desired here would be very appreciated.

Some questions I have:
1. Are the input arguments missing that would impact the result here? If so, then lets update the documentation to reflect that
2. Should some of these errors be ignored? If so, which ones?

**Comment by eli-schwartz** [comment]
If you grep commit message summaries for "flake8" you'll see I periodically clean up some of them.

I think most of the remaining issues come from lingering anti-patterns in the cmake support code.

...

In general I'd like to be flake8-clean, yes.

**Comment by eli-schwartz** [comment]
I should also mention that I don't usually bother to lint anything other than `mesonbuild/`, and in particular the use of star/unused imports in the unittest gathering is likely correct and probably should be suppressed.

**Comment by AHSauge** [comment]
Thanks, that was going to be my next question. 

If you want me to, I can at least clean up `mesonbuild/` tomorrow (hopefully).

**Comment by eli-schwartz** [comment]
That sounds fine with me.

If there's any non-whitespace changes I would have them in a second commit in the same PR as that's easier to categorize and review.
