### ISSUE TITLE
ERROR: Dependency "gtk4" not found, tried pkgconfig and cmake

### ISSUE THREAD

**Issue by e-lunev** [mesonbuild/meson#10688]
WARNING: CMake Toolchain: Failed to determine CMake compilers state
Run-time dependency gtk4 found: NO (tried pkgconfig and cmake)

src/meson.build:6:0: ERROR: Dependency "gtk4" not found, tried pkgconfig and cmake

OS: Kali GNU/Linux Rolling x86_64
Kernel: 5.18.0-kali5-amd64

**Comment by eli-schwartz** [comment]
So the obvious question to ask is, do you have the gtk4 development package installed? :)

**Comment by tristan957** [comment]
@eli-schwartz closeable

**Comment by eli-schwartz** [comment]
Closing due to no response... but I assume the problem was solved by installing the dependency that the project was asking for. ;)

**Comment by pedropaulosuzuki** [comment]
> Closing due to no response... but I assume the problem was solved by installing the dependency that the project was asking for. ;)

Probably not. The message says 'Dependency "gtk4" not found'. User probably tried 'sudo dnf install gtk4' (or similar), got 'gtk4 is already installed bro' and just gave up. Would be more helpful to indicate the dependency missing is 'gtk4-devel', and not 'gtk4', so the issue is valid because the error message is not descriptive.

**Comment by eli-schwartz** [comment]
That sounds wrong. I'm pretty sure the name of the package was `gui-libs/gtk:4`, not `gtk4-devel`. At least that's what my Gentoo Linux system says. :)

The original reporter was using Kali Linux, which I don't think has a "dnf" program, what is "dnf" and where does it get the name of the packages from?

Note also on Adelie Linux there's a "gtk4-dev" package. Not "devel". Alpine has a "gtk4.0-dev" package, I'm not sure why as it doesn't provide version 4.0 of Gtk, it provides version 4.18. Solus has a "libgtk-4-devel" which is a bit closer to what you suggested. Debian, of course (and hence Kali) uses "apt install libgtk-4-dev".

...

Also that would just be #2292. I'd love to hear suggestions about how to robustly implement this, but please keep the discussion in one ticket. :)

**Comment by pedropaulosuzuki** [comment]
> That sounds wrong. I'm pretty sure the name of the package was `gui-libs/gtk:4`, not `gtk4-devel`. At least that's what my Gentoo Linux system says. :)
> 
> The original reporter was using Kali Linux, which I don't think has a "dnf" program, what is "dnf" and where does it get the name of the packages from?
> 
> Note also on Adelie Linux there's a "gtk4-dev" package. Not "devel". Alpine has a "gtk4.0-dev" package, I'm not sure why as it doesn't provide version 4.0 of Gtk, it provides version 4.18. Solus has a "libgtk-4-devel" which is a bit closer to what you suggested. Debian, of course (and hence Kali) uses "apt install libgtk-4-dev".

`dnf` is Fedora's package manager, I thought it was a well known fact. I just experienced that, so that's why I gave the example. Then I quickly found I had to append "-devel" after most packages, so I don't know if it's a Fedora only issue, but definitely an issue, as the 'gtk4' package was already installed and the error was non-descriptive, and some users might not find that so quickly.

> Also that would just be [#2292](https://github.com/mesonbuild/meson/issues/2292). I'd love to hear suggestions about how to robustly implement this, but please keep the discussion in one ticket. :)

I'd suggest adding a link to docs showing common names to famous packages in various distributions, to not pollute the codebase. Ubuntu, Fedora and Arch instructions being the ones which would probably help more users.

**Comment by pedropaulosuzuki** [comment]
> > Also that would just be [#2292](https://github.com/mesonbuild/meson/issues/2292). I'd love to hear suggestions about how to robustly implement this, but please keep the discussion in one ticket. :)
> 
> I'd suggest adding a link to docs showing common names to famous packages in various distributions, to not pollute the codebase. Ubuntu, Fedora and Arch instructions being the ones which would probably help more users.

Actually you have a point, maybe it's up for the developers to give build instructions to their projects. Still, if there is a way to get more meaningful error messages, that'd be great.

**Comment by eli-schwartz** [comment]
> `dnf` is Fedora's package manager, I thought it was a well known fact.

Sorry, that was a bit of an apparently "clear as mud" joke. :) If you look at the referenced ticket I talk about dnf there. But put yourself in the shoes of a Kali Linux user, who likely doesn't know what `dnf` is despite knowing lots about `apt`, being told "get it by running this dnf command".

> Then I quickly found I had to append "-devel" after most packages, so I don't know if it's a Fedora only issue, but definitely an issue, as the 'gtk4' package was already installed and the error was non-descriptive, and some users might not find that so quickly.

Some distros use "-devel" (Fedora), some use "-dev" (Debian), some don't require a separate package at all (Arch, Gentoo). Beyond that, there are many styles for naming the base package -- in very very many, "gtk4" is not the package that has `libgtk-4.so`, it may be "gtk-4", "libgtk-4", "gtk4.0", etc. :(

All we (Meson) know is the pkg-config name.

**Comment by pedropaulosuzuki** [comment]
> > Then I quickly found I had to append "-devel" after most packages, so I don't know if it's a Fedora only issue, but definitely an issue, as the 'gtk4' package was already installed and the error was non-descriptive, and some users might not find that so quickly.
> 
> Some distros use "-devel" (Fedora), some use "-dev" (Debian), some don't require a separate package at all (Arch, Gentoo). Beyond that, there are many styles for naming the base package -- in very very many, "gtk4" is not the package that has `libgtk-4.so`, it may be "gtk-4", "libgtk-4", "gtk4.0", etc. :(
> 
> All we (Meson) know is the pkg-config name.

Maybe there's a way of indicating that it's `*-dev` (or similar) that's needed, and not regular `gtk4`. For distros where it's the same package they can guess `gtk4` is enough, which is easier than to see `gtk4` to find 'oh, I need some *-dev, *-devel or similar. While surely not as robust as #2292, it's certainly more discoverable.
