### ISSUE TITLE
0.63.1 breaks D builds with LDC when external linker flags are set

### ISSUE THREAD

**Issue by ximion** [mesonbuild/meson#10693]
Hi!
At the moment all D packages that use Meson (which is quite a bunch!) fail to build in Debian with the upgrade to Meson 0.63.1 (0.63.0 was fine). Debian sets the `LDFLAGS` env var to set specific linker flags, which Meson passes through to the *compiler* in verbatim. The LDC D compiler can't understand GNU linker flags on its own though, they need to be preprocessed as done in the D compiler backend of Meson: https://github.com/mesonbuild/meson/blob/master/mesonbuild/compilers/d.py#L286

The commit that highly likely broke this is https://github.com/mesonbuild/meson/commit/0ec039d2597526c670f7e0478a7b5008e14ff474, see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1017087 for the Debian bugreport.

**To Reproduce**
Just set `LDFLAGS=-Wl,-z,relro` and try to build the D examples from the testsuite.

**Expected behavior**
To determine the linker, Meson should either not pass through all linker flags from the environment, or (probably better), if they are sent to the compiler give the compiler backend the chance to sanitize them into a form that the compiler can actually understand.

Cheers,
    Matthias

**Comment by eli-schwartz** [comment]
> or (probably better), if they are sent to the compiler give the compiler backend the chance to sanitize them into a form that the compiler can actually understand.

Something like this, hopefully: eli-schwartz@c4c492a8911aac816527cee488a166b2099440c7

**Comment by ximion** [comment]
This looks like it would do the trick :-)

**Comment by eli-schwartz** [comment]
Maybe a bit more polished: eli-schwartz@729d4131affc0c55daf52ce232bc02bd59e75aeb

**Comment by eli-schwartz** [comment]
BTW I'm assuming here that at least for gdc, it makes sense to pass -fuse-ld on and allow gdc to select the right linker.

**Comment by ximion** [comment]
Yes, gdc follows the same command-line syntax as gcc. LDC however has `--gcc=` to pass in a C compiler for linking, or `--linker=` to set a specific linker. AFAIK with recent releases, LDC will pass `-fuse-ld` to the C compiler on its own unless instructed not to do so.

**Comment by ximion** [comment]
Thank you for the quick fix :-)
