### ISSUE TITLE
cross-file use breaks declare_dependency() ?

### ISSUE THREAD

**Issue by darkshade9** [mesonbuild/meson#10694]
**Describe the bug**
I'm building an ANSI C application that uses a variety of build methods and architectures:
```
mingw i686 (Win)
mingw x86_64 (Win)
msvc x86 (Win)
msvc x64 (Win)
gcc x64 (Linux)
clang x64 (Linux)
gcc arm64 (Linux)
```

Only the mingw builds have the following complaint:

```
meson.build:340:4: ERROR: Entries in "link_with" may only be self-built targets,
external dependencies (including libraries) must go to "dependencies".
```

**Added 8/17:**
This may be due to the use of cross-files, not necessarily because of the mingw compiler, it doesn't even get that far.  See notes below
**end**

**To Reproduce**

Relevant `meson.build` snippet, `external/discord/lib` contains all Discord SDK libraries needed for linking:

```
if get_option('discord-sdk')
  if host_machine.cpu_family() == 'aarch64' # I am Linux ARM 64-bit
    # Discord does not have an SDK for this platform yet, setting USE_DISCORD to false
    config.set10('USE_DISCORD', false)
  else
    config.set10('USE_DISCORD', true)
    discord_dep_path = join_paths(meson.current_source_dir(), 'extern/discord/lib/', host_machine.cpu_family())
    discord_dep = cc.find_library('discord', dirs : discord_dep_path)
    dis_inc = include_directories('extern/discord/lib/')
    discord_dep_dec = declare_dependency(link_with : discord_dep, include_directories : dis_inc)

    client_deps += discord_dep

    endif
endif
```

**Expected behavior**

All compilers should either have similar behavior or have explicitly stated resolutions for when a defined setup isn't compatible with it.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? cross build
* what operating system: `ubuntu-22.04`
* what Python version are you using: `3.8.0`
* what `meson --version`: `0.61.2`

**Comment by eli-schwartz** [comment]
Can you clarify why you think this is specific to the mingw compiler?

I'm pretty sure this should be the case regardless of compiler type. The return value of `.find_library()` (and also of `dependency()`) is an "external prebuilt resource", the return value of `library()` is an internally compiled resource.

The link_with keyword argument does special handling for build rules that you are compiling yourself as part of your project, which doesn't generalize to external packages or SDKs.

**Comment by darkshade9** [comment]
That's the thing, I am not sure why it's tied to the mingw build type, but of all of the different types of builds listed, they are the only ones that have an issue regarding `link_with`.  These are external prebuilt libraries I'm referencing, which exist outside of the Meson system.  All gcc/clang/msvc builds compile without issue, but the mingw ones won't get past this initial check.

**Comment by darkshade9** [comment]
I will also note, the mingw builds are the only ones I am also using a `cross-file` with, if that matters

**Comment by darkshade9** [comment]
I am closing this issue, I was overcomplicating my meson file.  I appear to only need to reference the existing library files using find_library() and add that to the executable() dependencies and include_directories lists

**Comment by eli-schwartz** [comment]
Indeed, like the error message said it should go in "dependencies" (this is the case for declare_dependency and for executable).

The only thing that originally confused me was that you said there were cases that it wasn't an error.
