### ISSUE TITLE
meson-0.63.1-64.msi fails with error code 2503

### ISSUE THREAD

**Issue by mrboojum** [mesonbuild/meson#10697]
**Describe the bug**
Installation with msi failed due to error code 2503. Installation succeeds when msi is invoked from cmd as Administrator.

**To Reproduce**

**Expected behavior**
Request for elevation or an error message stating that the user doesn't have sufficient privileges.

**system parameters**
Windows 10.0.19043

**Comment by eli-schwartz** [comment]
Meson isn't responsible for permissions or error dialogs. We just use an MSI bundle and Microsoft's own installer service is what opens it.

**Comment by eli-schwartz** [comment]
After googling around, I saw some claims that error code 2503 is returned by Microsoft's installer service, if the permissions on your `C:\Temp` folder are broken.

Maybe that can help you solve the issue?

**Comment by mrboojum** [comment]
Thanks, for your advice, I've changed the permissions on the folder.
