### ISSUE TITLE
weird soname handling

### ISSUE THREAD

**Issue by ignatenkobrain** [mesonbuild/meson#1072]
# VERSION vs SOVERSION

## cmake
```cmake
set_target_properties (libfoo PROPERTIES VERSION "2.31.0")
```
results into `  SONAME               libangelscript.so.2.31.0`

## meson
```meson
library ('libfoo', srcs, version : '2.31.0')
```
results into `  SONAME               libangelscript.so.2`

# SOVERSION with multiple digits / dots

## cmake
```cmake
set_target_properties (libfoo PROPERTIES SOVERSION "2.31.0")
```
results into `  SONAME               libangelscript.so.2.31.0`

## meson
```meson
library ('libfoo', srcs, soversion : '2.31.0')
```
results into `Shared library soversion must be a valid integer`

**Comment by nirbheek** [comment]
This is fixed with #1102
