### ISSUE TITLE
Must invoke mesonconf to set directory options (e.g. prefix)

### ISSUE THREAD

**Issue by martin-ejdestig** [mesonbuild/meson#1073]
While setting other options, e.g. b_ndebug, works when invoking meson. Example:

```shell
$ mkdir build
$ meson --buildtype release -Db_ndebug=true -Dprefix=$HOME/usr build
...
$ mesonconf build/ | grep prefix
  prefix     Installation prefix.          /usr/local    
$ mesonconf build/ | grep ndebug
  b_ndebug    Disable asserts                                true
$ mesonconf -Dprefix=$HOME/usr build
$ mesonconf build/ | grep prefix
  prefix     Installation prefix.          /home/martin/usr
```

**Comment by martin-ejdestig** [comment]
Ah, thank you. Did not know about --prefix.

**Comment by TingPing** [comment]
Related to #969

**Comment by jpakkane** [comment]
`meson -h` gives a list of command line switches.

**Comment by martin-ejdestig** [comment]
Right. Have not installed many packages with Meson and just assumed that -D should work for all options listed by mesonconf.

**Comment by fooishbar** [comment]
It is definitely very odd that all the path configurations (prefix, libdir, etc) are --this with meson and -Dthat with mesonconf.

**Comment by nioncode** [comment]
Seems to be working fine (possibly after merging #969?). Should be closed.
