### ISSUE TITLE
libircclient not found

### ISSUE THREAD

**Issue by andy5995** [mesonbuild/meson#10738]
On Ubuntu 22.04 and Manjaro, meson can't find [libircclient](https://sourceforge.net/projects/libircclient/) using dependency() (The libircclient upstream project doesn't include a '.pc' file). Here's my (amateur) code to workaround this:

```meson
inc_ircclient = []
dep_irclient = []
dep_ircclient = dependency('libircclient', required: false)
if not dep_ircclient.found()
  dep_ircclient = cc.find_library('libircclient', has_headers: 'libircclient.h', required: false)
  if not dep_ircclient.found()
    inc_ircclient = '/usr/include/libircclient'
    dep_ircclient = cc.find_library(
      'libircclient',
      has_headers: 'libircclient.h',
      header_include_directories: include_directories(inc_ircclient)
    )
  endif
endif
```

On Manjaro, the headers are in '/usr/include/libircclient' and Ubuntu they are in '/usr/include'.

@astavale maybe this affects you, too. I saw you're using libirc... in https://github.com/mesonbuild/meson/issues/4702 

When I used only find_package() for libircclient on Manjaro the header wasn't found until I added the extra code (above)

**Comment by astavale** [comment]
I use Fedora and the header is in `/usr/include/`. I didn't get too far with the binding, but my `meson.build` file was:

```
project( 'vala binding to libircclient tests', 'vala', 'c' )

vapi_dir = join_paths( meson.current_source_dir (), 'vapi' )

add_project_arguments(['--vapidir', vapi_dir], language: 'vala')

dependencies = [
	dependency( 'glib-2.0' ),
	dependency( 'gobject-2.0' ),
	meson.get_compiler( 'c' ).find_library( 'libircclient' ),
	meson.get_compiler( 'vala' ).find_library( 'libircclient', dirs: vapi_dir ),
]

get_version = executable( 'get_version', files( 'tests/get_version.gs' ), dependencies: dependencies )

test( 'libircclient version should be found', get_version )
```

I'm not sure what heuristics Meson build uses for finding system wide headers, but you could try dropping `has_headers: 'libircclient.h'`. This works fine for me:

`meson.get_compiler( 'c' ).find_library( 'libircclient' )`

**Comment by eli-schwartz** [comment]
The upstream source code installs headers to /usr/include and not /usr/include/libircclient -- that is the only thing you should care about.

Some distros patch things in broken ways that simply don't work, which is just bad QA. I wouldn't worry about them. You could add a meson wrap for libircclient, it seems simple enough, and use that as a fallback for users building on those distros.

**Comment by andy5995** [comment]
> You could add a meson wrap for libircclient, it seems simple enough, and use that as a fallback for users building on those distros.

@eli-schwartz Pardon my ignorance, but do you mean as a PR for the meson project (and if so, could you provide a link to a commit for an example), or do you mean to suggest I include the wrap with the project I'm working on?

> I'm not sure what heuristics Meson build uses for finding system wide headers, but you could try dropping `has_headers: 'libircclient.h'`. This works fine for me:
> 
> `meson.get_compiler( 'c' ).find_library( 'libircclient' )`

@astavale That works for meson configure, but the build fails on some distros because the includes can't be found (like when there in /usr/include/libircclient).

**Comment by eli-schwartz** [comment]
> Pardon my ignorance, but do you mean as a PR for the meson project (and if so, could you provide a link to a commit for an example), or do you mean to suggest I include the wrap with the project I'm working on?

You can include the wrap with the project you're working on, and add the `meson.build` file for the libircclient subproject to `subprojects/packagefiles/libircclient/meson.build`.

**Comment by tristan957** [comment]
@eli-schwartz closeable

**Comment by eli-schwartz** [comment]
This is a project issue, not a meson one.
