### ISSUE TITLE
Meson's check for `--allow-shlib-undefined` with lld linker is broken

### ISSUE THREAD

**Issue by godvino** [mesonbuild/meson#10763]
**Describe the bug**
Meson checks whether the lld linker supports the `--allow-shlib-undefined` flag [here](https://github.com/mesonbuild/meson/blob/master/mesonbuild/linkers/linkers.py#L858). However it doesn't pass the `c_link_args` flags to the linker while checking it. This causes the `lld: error: unknown argument: --allow-shlib-undefined` error while cross compiling using clang because lld supports the flag on the host system but not on the target system (which is launched with `-target x86_64-w64-windows-gnu` as it is part of `c_link_args`).

**Expected behavior**
Meson correctly passes `c_link_args` while performing the check which will cause it to add the `--allow-shlib-undefined` only if it is supported.

Cross file:
```
[[binaries]
c = 'clang'
cpp = 'clang++'
strip = 'llvm-strip'
c_ld = 'lld'
objc = 'clang'
rust = 'rustc'
windres = 'llvm-windres'

[built-in options]
c_args = ['--start-no-unused-arguments', '--sysroot', '/var/home/godvino/Downloads/llvm-mingw-20220323-ucrt-ubuntu-18.04-x86_64', '-target', 'x86_64-w64-windows-gnu', '-resource-dir=/var/home/godvino/Downloads/llvm-mingw-20220323-ucrt-ubuntu-18.04-x86_64/lib/clang/14.0.0/', '-rtlib=compiler-rt', '-unwindlib=libunwind', '--end-no-unused-arguments']
c_link_args = ['--start-no-unused-arguments', '--sysroot', '/var/home/godvino/Downloads/llvm-mingw-20220323-ucrt-ubuntu-18.04-x86_64', '-target', 'x86_64-w64-windows-gnu', '-resource-dir=/var/home/godvino/Downloads/llvm-mingw-20220323-ucrt-ubuntu-18.04-x86_64/lib/clang/14.0.0/', '-rtlib=compiler-rt', '-unwindlib=libunwind', '--end-no-unused-arguments']
cpp_args = ['--start-no-unused-arguments', '--sysroot', '/var/home/godvino/Downloads/llvm-mingw-20220323-ucrt-ubuntu-18.04-x86_64', '-target', 'x86_64-w64-windows-gnu', '-resource-dir=/var/home/godvino/Downloads/llvm-mingw-20220323-ucrt-ubuntu-18.04-x86_64/lib/clang/14.0.0/', '-rtlib=compiler-rt', '-unwindlib=libunwind', '--end-no-unused-arguments']
cpp_link_args = ['--start-no-unused-arguments', '--sysroot', '/var/home/godvino/Downloads/llvm-mingw-20220323-ucrt-ubuntu-18.04-x86_64', '-target', 'x86_64-w64-windows-gnu', '-resource-dir=/var/home/godvino/Downloads/llvm-mingw-20220323-ucrt-ubuntu-18.04-x86_64/lib/clang/14.0.0/', '-rtlib=compiler-rt', '-unwindlib=libunwind', '--end-no-unused-arguments']
c_winlibs = ['-lkernel32', '-luser32', '-lgdi32', '-lwinspool', '-lshell32', '-lole32', '-loleaut32', '-luuid', '-lcomdlg32', '-ladvapi32', '-lws2_32', '-luserenv', '-lbcrypt']
cpp_winlibs = ['-lkernel32', '-luser32', '-lgdi32', '-lwinspool', '-lshell32', '-lole32', '-loleaut32', '-luuid', '-lcomdlg32', '-ladvapi32', '-lws2_32', '-luserenv', '-lbcrypt']

[properties]
sys_root = '/var/home/godvino/Downloads/llvm-mingw-20220323-ucrt-ubuntu-18.04-x86_64/x86_64-w64-mingw32/'

[host_machine]
system = 'windows'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'
```

**System parameters**
* Cross build
* Fedora Linux 36
* python3 3.10.4
* meson from master
* ninja 1.10.2

**Comment by tristan957** [comment]
Sounds like you know the fix. Can you submit a PR?

**Comment by dcbaker** [comment]
I think as a work around you can add target to the compiler binary definition instead of the args c = [clang, -target, …]

Sorry for the formatting, I’m on my phone

**Comment by tristan957** [comment]
Can you post an example of what the correct compiler/linker arguments would look like?

**Comment by medhefgo** [comment]
The correct way to detect this with lld (when targeting PE) is to pass the emulation arg with the right value for the build target (`thumb2pe` (arm), `arm64pe`, `i386pe` (x86), `i386pep` (x86_64).
```sh
$ ld.lld -version --allow-shlib-undefined -m i386pep
lld: error: unknown argument: --allow-shlib-undefined
```

**Comment by medhefgo** [comment]
> @medhefgo could you submit a PR?

Was already on it: https://github.com/mesonbuild/meson/pull/11263

Took me a while to find out that meson is actually probing bfd. Though, this still requires `-target` to be part of the binary instead of in c_args. Though, judging from https://github.com/mesonbuild/meson/pull/11262, that's the proper way to do it anyways.

**Comment by tristan957** [comment]
Thanks for your contribution :).
