### ISSUE TITLE
MSVC __cplusplus fix used Visual Studio version rather than Visual C++ Compiler version

### ISSUE THREAD

**Issue by CorrodedCoder** [mesonbuild/meson#10787]
**Describe the bug**
A change was made to meson to specify /Zc:__cplusplus which makes MSVC correctly define __cplusplus to a meaningful value (see https://docs.microsoft.com/en-us/cpp/build/reference/zc-cplusplus?view=msvc-160), but the meson check whether to include it or not seems to be comparing against a Visual Studio version number rather than a Visual C++ compiler version number. See commit https://github.com/mesonbuild/meson/commit/04c728a126cc484cda21d21d672630d298cae9b8

```
        if version_compare(self.version, '>= 15.7') and '/Zc:__cplusplus' not in args:
            return args + ['/Zc:__cplusplus']
        return args
```
The comparison should be something like the following, according to the version on this website https://walbourn.github.io/vs-2017-15-7-update
```
        if version_compare(self.version, '>= 19.14.26428') and '/Zc:__cplusplus' not in args:
            return args + ['/Zc:__cplusplus']
        return args
```
Visual Studio 2012 version is emitting the following complaint with each compilation unit:
cl : Command line warning D9002 : ignoring unknown option '/Zc:__cplusplus'

**To Reproduce**
Any C++ project targeting Visual Studio 2012 exhibits the above behaviour.

**Expected behavior**
No warnings when building with versions of Visual Studio/C++ which don't support this.

**system parameters**
* Native
* Windows 10
* Python 3.10.1
* `meson --version`: 0.63.0
* `ninja --version`: 1.10.2.git.kitware.jobserver-1

**Comment by tristan957** [comment]
Could you submit a PR? cc @dcbaker @eli-schwartz @xclaesse since y'all had a hand in the original commit.

**Comment by eli-schwartz** [comment]
> the meson check whether to include it or not seems to be comparing against a Visual Studio version number rather than a Visual C++ compiler version number

Thank you, your analysis makes sense. My apologies. :(

**Comment by CorrodedCoder** [comment]
Thanks! I've tested the change on fully patched VS2012, VS2015, VS2017, VS2019 and VS2022 - so I think you're good!
I used this snippet:
```
#include <iostream>

int main(void)
{
	std::cout
		<< "_MSC_VER: " << _MSC_VER << "\n"
		<< "_MSC_FULL_VER: " << _MSC_FULL_VER << "\n"
		<< "_MSVC_LANG: " <<
#if defined(_MSVC_LANG)
			_MSVC_LANG
#else
			"<NOT_DEFINED>"
#endif
		<< "\n"
		<< "__cplusplus: " << __cplusplus << "\n"
		;
}
```
The output for each release was correct, at least according to my expectations:

vs2012\test_a.exe
_MSC_VER: 1700
_MSC_FULL_VER: 170061030
_MSVC_LANG: <NOT_DEFINED>
__cplusplus: 199711

vs2015\test_a.exe
_MSC_VER: 1900
_MSC_FULL_VER: 190024245
_MSVC_LANG: 201402
__cplusplus: 199711

vs2017\test_a.exe
_MSC_VER: 1916
_MSC_FULL_VER: 191627048
_MSVC_LANG: 201402
__cplusplus: 201402

vs2019\test_a.exe
_MSC_VER: 1929
_MSC_FULL_VER: 192930146
_MSVC_LANG: 201402
__cplusplus: 201402

vs2022\test_a.exe
_MSC_VER: 1933
_MSC_FULL_VER: 193331629
_MSVC_LANG: 201402
__cplusplus: 201402
