### ISSUE TITLE
[Question]How do I build universal library(x86_64 and arm64) for macOS M1?

### ISSUE THREAD

**Issue by diuming** [mesonbuild/meson#10780]
How do I build universal library(x86_64 and arm64) for macOS?
Could you give me an example?
thanks

**Comment by xclaesse** [comment]
I think you need a different build directory per arch.

**Comment by diuming** [comment]
you mean cross compile one for arm64 another one for x86_64 and then use cpio to make fat library? right
if so, can i say that meson cannot support CFLAGS="-arch arm64 -arch x86_64"?
thanks

**Comment by xclaesse** [comment]
> if so, can i say that meson cannot support CFLAGS="-arch arm64 -arch x86_64"?

I did not know it is possible to give more than one arch in CFLAGS. I guess it could work to give those cflags to meson, not sure.

> you mean cross compile one for arm64 another one for x86_64 and then use cpio to make fat library?

You mean `lipo`? That's what I would do, yes.

**Comment by diuming** [comment]
@xclaesse typo cpio, lipo is correct.
OK I get it and thanks.
