### ISSUE TITLE
Meson fails to build if regional format is set to anything other than english

### ISSUE THREAD

**Issue by mafiosnik777** [mesonbuild/meson#10799]
**Describe the bug**

Meson fails to build on Windows if regional format is set to anything other than english.

![C9MNfto29u 1](https://user-images.githubusercontent.com/108760201/189345697-2b468bfa-f8d8-4e33-a683-7af201570685.png)

**To Reproduce**

![K7CrdMgq9M 1](https://user-images.githubusercontent.com/108760201/189345830-ca31b8fc-47da-40e2-9d58-66fecf0c19d6.png)

Set this setting in Windows settings to Russian or German and refresh your terminal session and try to build.

**Expected behavior**

Meson successes in building.

**system parameters**

OS
* Windows 11

Python version
* 3.10.6

`meson --version`
* 0.63.1

**Comment by xclaesse** [comment]
It could help to post the full python backtrace, the screenshot here does not show where it comes from.

**Comment by xclaesse** [comment]
oh, I think the cut top line is `bat_info = json.loads(bat_json)` which is in _setup_vsenv(). That means `vswhere.exe` returns non-utf8 json file...

**Comment by xclaesse** [comment]
Could be a vswhere bug: https://github.com/microsoft/vswhere/issues/262

**Comment by eli-schwartz** [comment]
Please don't post screenshots of terminal output. Post the (entire) traceback as text, preferably inside triple backticks as a code block.

Posting screenshots is an excellent way to confuse people so they cannot understand your issue, and then you have to post the text version anyway, so you might as well do so from the start.

**Comment by mafiosnik777** [comment]
It was indeed a bug in vswhere. Updating it from 3.0.1 to 3.0.3 fixed the issue.
