### ISSUE TITLE
Qt6 on Windows -> QtEntryPoint

### ISSUE THREAD

**Issue by punytroll** [mesonbuild/meson#10792]
**Describe the bug**

A very simple Qt 6 executable in the windows subsystem requires a WinMain function. Previously, this was provided by the static qtmain.lib, but, it seems, in Qt 6 it is provided by the new QtEntryPoint library. This is not heeded by the "main" keyword of the qt dependency().

**To Reproduce**
Trivial main.cpp
```
#include <QApplication>
#include <QPushButton>

auto main(int argc, char * argv[]) -> int
{
    auto Application = QApplication{argc, argv};
    auto Button = QPushButton{"Exit"};
    QObject::connect(&Button, &QAbstractButton::clicked, []() { QApplication::quit(); });
    Button.show();
    return Application.exec();
}
```

Trivial meson.build:
```
project('bug', 'cpp', default_options: ['cpp_std=c++17'])
qt_dep = dependency('qt6', modules: ['Core', 'Widgets'], main: true)
app = executable('app', 'main.cpp', dependencies: [qt_dep], win_subsystem: 'windows')
```

**Expected behavior**

This should compile successfully.

There are two options to solve this:
1. rely on the programmer to supply the 'EntryPoint' module in the dependency, and remove the 'main' argument for qt6
   I.e. this works: `qt_dep = dependency('qt6', modules: ['Core', 'EntryPoint', 'Widgets'])`
2. leave the interface as is and improve the Qt6 dependency handling to map from `'main': true` to the 'EntryPoint' module

It should be noted, that QtEntryPoint is not available on at least Ubuntu 22.04. So, the second options seems to be more portable, as it doesn't need OS-specific handling in the meson.build file.

**system parameters**
* no cross-compile
* OS: Windows, MSVC and Qt 6.3.2, run inside MSYS2
* meson --version: 0.63.2
* ninja --version: 1.11.1

**Comment by tristan957** [comment]
It seems like we should deprecate `main: true` and rely on the user to supply `'EntryPoint'`.

**Comment by eli-schwartz** [comment]
Why should it be deprecated? I'm not sure I understand the rationale.

It makes a lot more sense as a kwarg than as a distinct dependency lookup, because:
- it works the same on Qt5 and Qt6
- it automatically handles being a no-op for non-Windows platforms
- it is compatible with existing builds

What is the argument in favor of deprecating it?

**Comment by punytroll** [comment]
In essence I have to agree with @eli-schwartz. I've implemented that solution, but if deprecating 'main' gains favour, I'm not opposed to implementing that as well.
