### ISSUE TITLE
ERROR: <ExternalLibrary libcrypto: True> is not a target.

### ISSUE THREAD

**Issue by punytroll** [mesonbuild/meson#10813]
**Describe the bug**

I get the error `ERROR: <ExternalLibrary libcrypto: True> is not a target.` when trying to setup the build directory for this simple project.

**To Reproduce**

meson.build
```
project('p', 'cpp')
compiler = meson.get_compiler('cpp')
libcrypto_dep = declare_dependency(
  include_directories: ['C:\Qt\Tools\OpenSSL\Win_x64\include'],
  link_with: compiler.find_library('libcrypto', dirs: 'C:\Qt\Tools\OpenSSL\Win_x64\lib'))
executable('app', 'main.cpp', dependencies: [libcrypto_dep])
```

main.cpp contains only an empty main() function.

**Expected behavior**

I think this should setup just fine, but maybe I am misunderstanding the declare_dependency() documentation or the error message?!

**system parameters**
* Native
* Windows inside MSYS2
* Python: 3.10.6
* Meson: 0.63.1
* Ninja: 1.11.1

**Comment by dcbaker** [comment]
the output of `compiler.find_library()` is a dependency, not a target. so you want to replace `link_with` with `dependencies`, like so:
```meson
project('p', 'cpp')
compiler = meson.get_compiler('cpp')
libcrypto_dep = declare_dependency(
  include_directories: ['C:\Qt\Tools\OpenSSL\Win_x64\include'],
  dependencies: compiler.find_library('libcrypto', dirs: 'C:\Qt\Tools\OpenSSL\Win_x64\lib'))
executable('app', 'main.cpp', dependencies: [libcrypto_dep])
```

**Comment by punytroll** [comment]
Thank you so much, that solved the problem nicely! :)

I guess, `link_with` can only be used for libraries built with `library()` within the current project?

I like to think I could have found that solution myself, but for the fact, that the error message came from line 6. So I was trying to fix something in the `executable()` call. Shouldn't the error message apply to line 5? Or maybe line 3 for the start of the `declare_dependency()` call? As far as I can see in the documentation, the types of `dependencies` is `list[dep]` whereas the type of `link_with` is `list[lib]`. Would it be possible to catch that error, where it's initiated, not where it is used?

**Comment by eli-schwartz** [comment]
It's supposed to error out with:
```
meson.build:3:0: ERROR: declare_dependency keyword argument "link_with" can only be self-built targets, external dependencies (including libraries) must go in "dependencies".
```

But the check was broken.

**Comment by punytroll** [comment]
Yeah, that error message would have been much more helpful! :)

So it was a valid ticket after all. *phew* Thanks a lot for the quick fix!
