### ISSUE TITLE
Meson devenv still fails

### ISSUE THREAD

**Issue by mkaes** [mesonbuild/meson#10820]
meson --version  0.63.2
Installed from the MSI installer.

```
meson devenv
Traceback (most recent call last):
  File "mesonbuild\mesonmain.py", line 153, in run
  File "mesonbuild\mdevenv.py", line 147, in run
  File "mesonbuild\mdevenv.py", line 28, in get_windows_shell
  File "subprocess.py", line 420, in check_output
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['powershell.exe', '-noprofile', '-executionpolicy', 'bypass', '-file', 'C:\\Program Files\\Meson\\mesonbuild\\scripts\\cmd_or_ps.ps1']' returned non-zero exit status 5.

ERROR: Unhandled python exception
This is a Meson bug and should be reported!
```
The issue looks similar to #9872 but the file `C:\Program Files\Meson\mesonbuild\scripts\cmd_or_ps.ps1` exists so the installer is fixed but still it is not working as expected.

**Comment by eli-schwartz** [comment]
What happens if you try to run that command by hand?

**Comment by mkaes** [comment]
I am getting the following error when I execute it from a powershell:
```
Get-Process : Cannot find a process with the process identifier 6132.
At C:\Program Files\Meson\mesonbuild\scripts\cmd_or_ps.ps1:20 char:11
+   $pname=(Get-Process -id $ppid).Name
+           ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (6132:Int32) [Get-Process], ProcessCommandException
    + FullyQualifiedErrorId : NoProcessFoundForGivenId,Microsoft.PowerShell.Commands.GetProcessCommand

Get-Process : Cannot bind argument to parameter 'Id' because it is null.
In C:\Program Files\Meson\mesonbuild\scripts\cmd_or_ps.ps1:20 Zeichen:27
+   $pname=(Get-Process -id $ppid).Name
+                           ~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-Process], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.GetProcessC
   ommand
```

And I see this error when I execute it from a pwsh from VS code:
```
gwmi: C:\Program Files\Meson\mesonbuild\scripts\cmd_or_ps.ps1:5:8
Line |
   5 |  $ppid=(gwmi win32_process -Filter "processid='$pid'").parentprocessid
     |         ~~~~
     | The term 'gwmi' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

Which is something I would expect since Get-WmiObject is no longer supported in the powershell core.

**Comment by xclaesse** [comment]
CC @seungha-yang who wrote that script.

**Comment by eli-schwartz** [comment]
> And I see this error when I execute it from a pwsh from VS code:

Just to make sure... My suggestion was to run the command

```
powershell.exe -noprofile -executionpolicy bypass -file C:\\Program Files\\Meson\\mesonbuild\\scripts\\cmd_or_ps.ps1
```

Running powershell.exe from pwsh shouldn't make the script run under pwsh, are you executing the script itself instead of emulating the actual process model that meson is using?

**Comment by xclaesse** [comment]
The problem is `gwmi` does not exist any more in pwsh7:
```
(gwmi win32_process -Filter "processid='$pid'").parentprocessid
gwmi: The term 'gwmi' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

Looks like we should be using `CIM`: https://github.com/PowerShell/PowerShell/issues/4766

**Comment by xclaesse** [comment]
@mkaes could you please test the suggested fix there: https://github.com/mesonbuild/meson/pull/10825

**Comment by xclaesse** [comment]
@mkaes If I understanad correctly, you would get this error when powershell.exe is in fact powershell7, which should be named pwsh.exe. Does that happen with newer Windows or something?

**Comment by mkaes** [comment]
@xclaesse I get the error when I am using a powershell(5.1.19041.1682)
But I can confirm that your change fixes the issue with the pwsh(7,2,4)
With your change both behave the same way and show the same error.

**Comment by mkaes** [comment]
@eli-schwartz Depending on how I execute the script I get different errors. 
But after some debugging I assume that it is the virus scanner of my company that is blocking the script execution. I will try and investigate this a little more but I do not expect this to be a bug in meson. So I think we can close this one.

**Comment by eli-schwartz** [comment]
Well, again, the purpose of the script was to run only a specific way, which Meson enforces. So running "from a pwsh" doesn't say much.

Since they both error out, I don't think there's anything to fix for pwsh specifically, and I guess the virus scanner is the likely explanation anyway.

**Comment by xclaesse** [comment]
There is one thing we can do, catch the exception and fallback to a default shell. Or at least catch the exception to print better error message than a backtrace. I updated my PR for that.

**Comment by mkaes** [comment]
I can confirm that my original bug came from the virus scanner blocking the script.
Adding the script to the exclusion list fixed the issue for powershell.
The changes from @xclaesse fixes also the problems with pwsh. With those changes both powershell and pwsh behave the same.
