### ISSUE TITLE
Support LLVM Flang

### ISSUE THREAD

**Issue by MehdiChinoune** [mesonbuild/meson#10839]
LLVM Flang (https://github.com/llvm/llvm-project/tree/main/flang) is an LLVM
Fortran compiler that shares the same name as Flang (also known as Classic
Flang).

CMake now supports it https://gitlab.kitware.com/cmake/cmake/-/merge_requests/7246

**Comment by tristan957** [comment]
Shouldn't be too hard if you look at the logic for the GNU fortran compiler.

**Comment by tristan957** [comment]
@MehdiChinoune was the work actually done?

**Comment by MehdiChinoune** [comment]
No, It seems that no interested in doing it.

**Comment by eli-schwartz** [comment]
As is common in FOSS, patches are eagerly welcomed. If patches are not offered, then maintainers may do so as time allows, but then they may be focused on other things instead, so...

**Comment by MehdiChinoune** [comment]
> As is common in FOSS, patches are eagerly welcomed. If patches are not offered, then maintainers may do so as time allows, but then they may be focused on other things instead, so...

I know that. so I have just closed it. so what's the problem with that?

**Comment by eli-schwartz** [comment]
There's no problem as far as I'm concerned. :)

Just noting for any future readers that if they are interested they should feel encouraged to submit such work.

**Comment by tristan957** [comment]
Only reason I asked originally was because the reason for the issue being closed was that the work had been completed. Seems like the issue could reopened just so some future person could see it.

**Comment by h-vetinari** [comment]
I've opened up a follow-up issue in #12306

**Comment by eli-schwartz** [comment]
Duplicate of #12306
