### ISSUE TITLE
"meson dist" failure doesn't detect missing git command

### ISSUE THREAD

**Issue by hadess** [mesonbuild/meson#10866]
**Describe the bug**

I spent an hour trying to find why `meson dist` wasn't working in my CI:
```
$ ls -la
total 88
drwxrwxrwx 5 root root  4096 Sep 28 12:27 .
drwxrwxrwx 4 root root  4096 Sep 28 11:41 ..
drwxrwxrwx 6 root root  4096 Sep 28 12:27 .git
-rw-rw-rw- 1 root root   920 Sep 28 12:27 .gitlab-ci.yml
-rw-rw-rw- 1 root root    41 Sep 28 11:41 AUTHORS
-rw-rw-rw- 1 root root 26436 Sep 28 11:41 COPYING
-rw-rw-rw- 1 root root  9427 Sep 28 11:41 HACKING
-rw-rw-rw- 1 root root  3677 Sep 28 11:41 NEWS
-rw-rw-rw- 1 root root  1577 Sep 28 11:41 README
drwxr-xr-x 7 root root  4096 Sep 28 12:27 _build
drwxrwxrwx 4 root root  4096 Sep 28 11:41 libuhttpmock
-rw-rw-rw- 1 root root  1492 Sep 28 11:41 meson.build
-rw-rw-rw- 1 root root   393 Sep 28 11:41 meson_options.txt
-rw-rw-rw- 1 root root  1071 Sep 28 11:41 uhttpmock.doap
$ meson dist -C _build
Dist currently only works with Git or Mercurial repos
```

**To Reproduce**

1. Clone a git repo
2. Build in the usual way
3. Remove git package
4. Run `meson dist`

**Expected behavior**

Dist works, or complains about missing `git` command, rather than complaining about "Dist only working with Git repos".

The problem is a lack of error reporting as `is_git()` doesn't check why the `git ls-files` call failed.

`meson_0.63.2-1_all.deb`

**Comment by eli-schwartz** [comment]
Is removing the git package *really* something that people actually do? Why? What exactly is a git repo without the git program to interact with it?

**Comment by hadess** [comment]
> Is removing the git package _really_ something that people actually do? Why? What exactly is a git repo without the git program to interact with it?

It happens on CIs, as mentioned in the original comment. The CI doesn't require git to be installed manually because it's not used, that is until you want to run `meson dist` and can decypher the error message.

**Comment by eli-schwartz** [comment]
I simply don't understand the point of:
> Clone, build, *remove git package*, run dist

Why would you intentionally uninstall git just to see this error message?

Which is a correct error message, but I digress.

**Comment by hadess** [comment]
> I simply don't understand the point of:

It's how you can reproduce the bug on your machine, not how I encountered the bug.

**Comment by hadess** [comment]
> Which is a correct error message, but I digress.

It's an accurate statement, as an error message, it's neither "correct", nor useful.

**Comment by xclaesse** [comment]
> Why would you intentionally uninstall git just to see this error message?

@eli-schwartz at least with gitlab, the git repo of your project is cloned inside a docker image provided by gitlab which always have git and a few tools to prepare the job, but then the actual job is ran in your own docker that could not have git.

**Comment by dvdhrm** [comment]
This is quite hard to track down, and the error message is not helping me. I just triggered this on github-actions, since the `git ls-files` command used internally by `meson dist` failed with:

```
fatal: detected dubious ownership in repository at '/__w/<repo>/<repo>'
To add an exception for this directory, call:

	git config --global --add safe.directory /__w/<repo>/<repo>
```

Note that this happened because github-actions caches checkouts on the worker-machine, but then shares it into containers running individual steps. Yes, this is a misconfiguration on my side, but it was quite annoying trying to get the git error message out of meson.

**Comment by eli-schwartz** [comment]
It is actually a misconfiguration on the side of the git developers. :)

**Comment by mbridon** [comment]
I think I'm getting a similar issue (or maybe the same?) in Gitlab CI: https://gitlab.freedesktop.org/cangjie/libcangjie/-/pipelines/1003752

That error message is incredibly confusing because **I'm using Gitlab, so of course this is a Git repo**.

What can be done about this issue ? Did someone ever found an ugly workaround? :confused:

**Comment by mbridon** [comment]
Ok, turns out explicitly installing git in my CI lets it pass, but there's no real reason why it should be an actual dependency... :disappointed:

**Comment by eli-schwartz** [comment]
Possible fix for the ugly error message: https://github.com/eli-schwartz/meson/commit/283b4a66d04d5633937a7c088da37d89f3a43cdd

I'm not sure how much I like this.

**Comment by eli-schwartz** [comment]
That part of the message is specifically keyed on seeing "GITLAB_CI" in the environment variables, which I believe should be entirely unique to running on a gitlab-runner deployment.

**Comment by dvdhrm** [comment]
Working on git-checkouts without git installed sounds legitimate to me. Many situations where this can happen, especially when remote-mounting or otherwise sharing file systems. I would not necessarily call this a `bug`.

How about just:

```python
    if quiet_git(['ls-files', '--error-unmatch', 'meson.build'], src_root)[0]:
        return True

    if os.path.exists(os.path.join(src_root, '.git')):
        msg = 'Source tree is a git checkout, '
        if not GIT:
            msg += 'but git is not installed.'
        else:
            msg += 'but execution of git failed.'
        mlog.warning(msg)
    return False
```

**Comment by eli-schwartz** [comment]
> Working on git-checkouts without git installed sounds legitimate to me. Many situations where this can happen, especially when remote-mounting or otherwise sharing file systems. I would not necessarily call this a `bug`.

If you reread my patch, you'll notice it's only referred to as a bug when gitlab runners are detected...

**Comment by eli-schwartz** [comment]
Posted my patch as a PR.
