### ISSUE TITLE
JNI system dependency does not include FreeBSD

### ISSUE THREAD

**Issue by asiekierka** [mesonbuild/meson#10883]
**Describe the bug**

When trying to use the JNI system dependency on FreeBSD, the following error appears: `Could not find a JDK platform include directory for your OS, please open an issue or provide a pull request.`

This is related to the following list being limited to only Windows, Linux, Darwin and Solaris: https://github.com/mesonbuild/meson/blob/master/mesonbuild/dependencies/dev.py#L606-L622

**To Reproduce**

As per code examination, merely trying to pull in the JNI system dependency should be a sufficient reproduction.

**Expected behavior**

Detecting the platform-dependent include directory on FreeBSD, whose name is  `freebsd`.

**system parameters**

* FreeBSD 13.1
* Python 3.9.14
* Meson 0.62.2

**Comment by eli-schwartz** [comment]
@tristan957

**Comment by tristan957** [comment]
If anyone knows what netbsd and openbsd would be, I can fix those too. I could guess, but I would rather not

**Comment by asiekierka** [comment]
NetBSD: `netbsd`, as per http://cdn.netbsd.org/pub/pkgsrc/packages/NetBSD/x86_64/9.0_current/All/openjdk8-1.8.332.tgz:

```
java/openjdk8/include/jni_md.h
java/openjdk8/include/netbsd/jni_md.h
```

(interestingly, NetBSD copies `jni_md.h` to the directory below too?...)

OpenBSD: `openbsd`, as perhttps://cdn.openbsd.org/pub/OpenBSD/7.2/packages/i386/jdk-17.0.4.8.1v0.tgz:

```
jdk-17/include/openbsd/jni_md.h
```

**Comment by tristan957** [comment]
If any haiku lovers wanna give me the answer...
