### ISSUE TITLE
Feature request: allow reading the build options line from inside meson.build

### ISSUE THREAD

**Issue by amyspark** [mesonbuild/meson#10898]
Hey!

I'm working on some enhancements to a wrap, and one of the missing features is storing the configuration line inside the config.h header. Meson already saves this information in the build log, so currently I'm using a hack to extract this information at setup time:

```python

import re
import os

if __name__ == '__main__':
     with open(f'{os.environ["MESON_BUILD_ROOT"]}/meson-logs/meson-log.txt', encoding="utf-8", mode='r') as f:
        lines = [line for line in f if 'Build Options' in line]

        options = re.match(r'Build Options:\s+(.+)$', lines[-1])

        if options is not None:
            print(options.group(1))
```

And then in meson.build:
```meson
extractor = find_program('capture_build_options.py', required: true)
configuration = run_command(extractor)
assert(configuration.returncode() == 0, 'Could not extract configuration string from meson!')

final_conf = configuration_data()
final_conf.set_quoted('CONFIGURATION', configuration.stdout().strip())
configure_file(
  output: 'config.h',
  configuration: final_conf,
)
```

Would it be possible to add a read-only variable, perhaps to the `meson` object, to access this information?

**Comment by MathieuDuponchelle** [comment]
:+1: from me, I think it is fairly common for command-line tools to display the options they were built with when running, the context here is GStreamer's FFmpeg meson port for what it's worth.

**Comment by QuLogic** [comment]
We do this with a [post conf script](https://keep.imfreedom.org/pidgin/pidgin/file/tip/mkmesonconf.py) that calls `meson introspect` I'm not sure how robust that is, but it seems to work.

**Comment by xclaesse** [comment]
@QuLogic note that there is a difference between both solutions, the former only shows user defined otions, not default options. If we add an explicit function for this, I guess we would need an argument specifying if you want to include defaults or not.

**Comment by amyspark** [comment]
> We do this with a [post conf script](https://keep.imfreedom.org/pidgin/pidgin/file/tip/mkmesonconf.py) that calls `meson introspect` I'm not sure how robust that is, but it seems to work.

This approach works well, if you can generate the header during the build process.

Apart from that restriction, its weakness that it doesn't scale with the number of options; in our case it'll generate over *2000* option entries, most of which depend on the value of`-Dauto_features=<default>` anyway.

**Comment by nirbheek** [comment]
So as I understand it, this is about documenting what options [a project like ffmpeg](https://gitlab.freedesktop.org/gstreamer/meson-ports/ffmpeg/-/merge_requests/71) was built with? Is the purpose of that purely to document the project-specific options that were used? Why does it go into the header?

Trying to understand the precise use-case here, so we can solve it better.

**Comment by eli-schwartz** [comment]
It's typically emitted as part of the --version text of some programs.

**Comment by nirbheek** [comment]
That's not a purpose, that's just another chain in the implementation. What is the purpose of putting it in the version text? So that when users come to you for support you know how the app was built?

Do you want just the project-specific options there or also, for example, the optimization args? What about options from cross files and native files? What about env vars such as CFLAGS / LDFLAGS? Do you want to serialize the entire build state and put it in a header?
