### ISSUE TITLE
need to override search path for find_library

### ISSUE THREAD

**Issue by anordal** [mesonbuild/meson#109]
For my employer's cross compilation purposes, we need to link with libraries of the target architecture, and we would like to avoid accidentally finding the build host's own libraries. We compile a whole OS image, so we need to install and package the whole directory tree strictly separate from directories belonging to the build host.

Is this is something worth adding to meson?

Initially, we thought it was a good idea to extend the syntax for 'find_library', to allow specifying custom search paths, similar to cmake. However, we think it's generally a bad idea for the application to encode the whereabouts of its dependencies. Secondly, it could be useful to specify the install directory from the command line (for development purposes).

Given that we want to use command line options to override the search path of find_library, an acceptable solution we might try as a hack, is to modify the semantics of the --cross-file option, so that invoking meson, e.g., using:
```
meson --prefix=/tmp/temp-package-dir --libdir=lib --cross-file ~/cross_file_ppc.txt
```
would replace the default search paths used by 'find_library' (e.g., '/usr/lib' and '/usr/local/lib' for Linux) with the path obtained by concatenating the value of --prefix with that of --libdir (so in our case '/tmp/temp-package-dir/lib'). Therefore, the mere presence of the --cross-file option disables calling the 'get_library_dirs' function in 'mesonlib.py', and instead leads to the new custom search path being used. The assumtion is that nobody that uses the --cross-file option would like to find system libraries.

**Comment by jpakkane** [comment]
If you look at the sample cross files, they define a property called root. This means root of the filesystem in the target. I have been planning to change find_library so it is no longer a freestanding function but a method of the compiler object. This would allow you to do library detection both for the system and cross compilers.

As an example, doing this:

    meson.get_compiler('c', cross : true).find_library('foo')

would find <tt>/usr/i686-w64-mingw32/lib/libfoo.so</tt> whereas

    meson.get_compiler('c', cross : false).find_library('foo')

would find <tt>/usr/lib/libfoo.so</tt>.

Does this seem like a working solution for you?

**Comment by anordal** [comment]
It would have worked, but we would need it to be a disposable directory, like
```
root = '/tmp/install_branch-xyz_build-123'
```

This directory would always equal the install prefix (`meson --prefix=`), so the most direct fix would be a `--find-libraries-only-from-prefix` option. I admit, that need has really nothing to do with cross compiling, but more that we are building a whole OS.

If we had target libraries installed on the build host, then it would make sense to encode that in the cross-file. I guess that's an orthogonal need.

I like that meson.build files are cross compilation agnostic. Would your proposed change change that?

**Comment by anordal** [comment]
May I suggest a combination:
* `meson --add-library-search-path=/tmp/install_branch-xyz_build-123`
* The `root` parameter in the cross file would disable the standard host search paths (and of course enable the given path instead, which would not be required to exist).

**Comment by jpakkane** [comment]
Disabling host paths is not something we can do, Meson needs to provide for finding libraries in both of them at the same time. The use case for this is that if you have a project that first builds a code generator tool and then generates code that is cross compiled. We might need to find a library to build the codegen tool and then find a library from the machine prefix to link the resulting code.

**Comment by jpakkane** [comment]
As a first step find_library now has the <tt>dirs</tt> keyword to specify custom search directories. This is something we need in any case. You can use it in your use case too. The automatic cross-compilation case is a bit more difficult and requires more thought.

**Comment by anordal** [comment]
Okay I suppose we have all that's needed, I've just been too busy lately. Will test in a few days, and hopefully close this issue.

Thanks again! Your efforts are highly appreciated.

**Comment by jpakkane** [comment]
Did you have time to test?

**Comment by jpakkane** [comment]
Assuming this one closed due to inactivity. If the issue still happens, please file a new bug.

**Comment by JackLiar** [comment]
I'm a newb from CMake, could we add arbitray search path **ahead** of default search path through command line parameter now?

Just like [CMAKE_PREFIX_PATH](https://cmake.org/cmake/help/latest/variable/CMAKE_PREFIX_PATH.html)?

I haven't looked into meson deeply, I believe this could be done by modifying meson.build file.

But for a third party library, it is too hacky to modify its meson.bulid file to implement this function.

**Comment by mensinda** [comment]
You should be able to do this with `meson configure -Dcmake_prefix_path=<Path1> -Dpkg_config_path=<Path1>`
