### ISSUE TITLE
cannot open output file "??????" in containers

### ISSUE THREAD

**Issue by www-cat** [mesonbuild/meson#10908]
**Describe the bug**
compile error:
```
src/meson.build:58:0: ERROR: C shared or static library 'm' not found

Command line:  gcc /home/user/Код/gnome-text-editor/build/meson-private/tmpcif1iwkm/testfile.c -o /home/user/Код/gnome-text-editor/build/meson-private/tmpcif1iwkm/output.exe -D_FILE_OFFSET_BITS=64 -O0 -Wl,--start-group -lm -Wl,--end-group -Wl,--allow-shlib-undefined 

Code:
 int main(void) { return 0; }

Compiler stdout:
 
Compiler stderr:
 ld: cannot open output file /home/user/??????/gnome-text-editor/build/meson-private/tmpcif1iwkm/output.exe: No such file or directory
collect2: error: ld returned 1 exit status


src/meson.build:58:0: ERROR: C shared or static library 'm' not found
```
see "??????" in the Compiler stderr line

**To Reproduce**
build anything with libm
small file to reproduce:
```
project('example', 'c')
cc = meson.get_compiler('c')
executable('example', [], dependencies: cc.find_library('m'))
```

**Expected behavior**
no error

**system parameters**
* GNU Guix shell on Debian GNU/Linux bookworm/sid
* container packages: meson ninja coreutils glibc-locales gcc-toolchain
* what Python version are you using: 3.9.9
* what `meson --version`: 0.63.2
* what `ninja --version`: 1.10.2

**Comment by xclaesse** [comment]
@www-cat is your file system UTF-8? Maybe a bug in Debian sid binutils? Works fine for me on Ubuntu 22.04 when trying your example in a folder named `Код`.

**Comment by www-cat** [comment]
> @www-cat is your file system UTF-8? Maybe a bug in Debian sid binutils? Works fine for me on Ubuntu 22.04 when trying your example in a folder named `Код`.

my locale is utf-8, so it must be
no debian packages are in $PATH

**Comment by www-cat** [comment]
thank you for mentioning "binutils" btw! i included it in the container and the meson build was successful! mysterious... i'll ask guix why isn't it imported this way in guix shell --development

**Comment by xclaesse** [comment]
Weird, where does ld comes from then? At least on my Ubuntu /usr/bin/ld comes from binutils. But I don't know for guix.

**Comment by www-cat** [comment]
> Weird, where does ld comes from then? At least on my Ubuntu /usr/bin/ld comes from binutils. But I don't know for guix.

some "ld wrapper"
```
$ readlink $(guix shell --container which binutils -- which ld)
/gnu/store/zyqimpkmpffc24nwwqp46cicj8ss85y5-binutils-2.37/bin/ld
$ readlink $(guix shell --container which --development hello -- which ld)
/gnu/store/s2pg5k98fl2g2szg9dykxyd9zl3xihv9-ld-wrapper-0/bin/ld
$ 
```
