### ISSUE TITLE
test cases/rust/13 external c dependencies fails on Solaris due to lack of static zlib

### ISSUE THREAD

**Issue by alanc** [mesonbuild/meson#10906]
**Describe the bug**
When running the tests on Solaris 11.4, the runs of `test cases/rust/13 external c dependencies` with `-Dstatic=true` incorrectly report that libz.a is found, and then fail when ninja calls gcc for the linking step because Solaris only packages libz.so, and not libz.a.

**To Reproduce**
(in a checked out copy of this repo on Solaris 11.4)
```
cd test\ cases/rust/13\ external\ c\ dependencies/
env PKG_CONFIG_PATH=/usr/lib/64/pkgconfig python3 ../../../meson.py setup --wipe builddir -Dmethod=system -Dstatic=true
cd builddir/
ninja
```
or with `-Dmethod` set to `pkg-config` instead of `system`

When using `-Dmethod=pkg-config` it even correctly output a warning that this wouldn't work, but continued to try anyway:
```
WARNING: Static library 'z' not found for dependency 'zlib', may not be statically linked
```

**Expected behavior**
I expected the `if not dep_zlib.found()` clause in [meson.build](https://github.com/mesonbuild/meson/blob/0.63.3/test%20cases/rust/13%20external%20c%20dependencies/meson.build#L8) to trigger the `'MESON_SKIP_TEST: Could not find a @0@ zlib'.format(get_option('static') ? 'static' : 'shared')` message and exit.

**system parameters**
* native build
* Oracle Solaris 11.4
* Python 3.7.13
* meson 0.63.3
* 1.11.0

**Comment by tristan957** [comment]
@alanc seems like the best course of action is to skip the test on Solaris. Care to submit a PR? grep for `MESON_SKIP_TEST` I believe for other usages

**Comment by alanc** [comment]
We could do that, though the test passes for much of the matrix - in our Solaris package, we've only disabled the static linking portion of the test matrix, though in a way that isn't suitable for upstream:
https://github.com/mesonbuild/meson/blob/master/mesonbuild/linkers/linkers.py#L210

But it seems that's just ignoring an actual bug in meson in which `dependency('zlib', static : true, ...)` is  claiming the static library is available when it's not, but I don't know where in meson to fix that.

**Comment by dcbaker** [comment]
@alanc you should be able to look at the $builddir/meson-log/meson-log.txt and see more detailed debug information on why meson thinks it can find a static zlib. But this seems to be a common problem

**Comment by alanc** [comment]
Using the classic method of "grep and copy" programming, without actually understanding the source code, this small change to `ZlibSystemDependency` seems to fix it:

```
--- a/mesonbuild/dependencies/dev.py
+++ b/mesonbuild/dependencies/dev.py
@@ -509,7 +509,7 @@ class ZlibSystemDependency(SystemDependency):
             else:
                 libs = ['z']
             for lib in libs:
-                l = self.clib_compiler.find_library(lib, environment, [])
+                l = self.clib_compiler.find_library(lib, environment, [], self.libtype)
                 h = self.clib_compiler.has_header('zlib.h', '', environment, dependencies=[self])
                 if l and h[0]:
                     self.is_found = True
```

With that, running `../../../meson.py setup builddir -Dstatic=true -Dmethod=system` results in:
```
Run-time dependency zlib found: NO (tried system)

meson.build:9:2: ERROR: Problem encountered: MESON_SKIP_TEST: Could not find a static zlib
```
while it still completes setup & build successfully with `-Dstatic=false`.

**Comment by alanc** [comment]
Since no one said my fix looked wrong or made a better suggestion in the past 4 months I submitted pull request #11569 for this change.

On Solaris 11.4.57, this changes the results of that rust test case from:
```
 [SUCCESS]   rust: 13 external c dependencies    (static=False method=cmake)
 [SUCCESS]   rust: 13 external c dependencies    (static=False method=pkg-config)
 [SUCCESS]   rust: 13 external c dependencies    (static=False method=system)
 [SUCCESS]   rust: 13 external c dependencies    (static=True method=cmake)
  [ERROR]    rust: 13 external c dependencies    (static=True method=system)
During: build
Reason: Compiling source code failed.
```
to
```
 [SUCCESS]   rust: 13 external c dependencies    (static=False method=cmake)
 [SUCCESS]   rust: 13 external c dependencies    (static=False method=pkg-config)
 [SUCCESS]   rust: 13 external c dependencies    (static=False method=system)
 [SUCCESS]   rust: 13 external c dependencies    (static=True method=cmake)
 [SKIPPED]   rust: 13 external c dependencies    (static=True method=system)
Reason: Could not find a static zlib
```
