### ISSUE TITLE
glib: same object file included twice in static archive

### ISSUE THREAD

**Issue by rawoul** [mesonbuild/meson#10907]
Starting with glib 2.74, which bundles gvdb as a subproject, I get a broken static archive when configuring with `default_library = both`:

```
$ meson.py setup . build --default-library both
...
$ ninja -C build
...
$ ar t ./build/gio/libgio-2.0.a | grep gvdb
.._subprojects_gvdb_gvdb_gvdb-builder.c.o
.._subprojects_gvdb_gvdb_gvdb-reader.c.o
.._subprojects_gvdb_gvdb_gvdb-builder.c.o
.._subprojects_gvdb_gvdb_gvdb-reader.c.o
```

I wonder if this is because the gvdb dependency is not declared as a library but instead exposes its sources directly ?

**Comment by xclaesse** [comment]
I think it's the same as https://github.com/mesonbuild/meson/pull/10843. Can you check if that fix it for you please?

**Comment by rawoul** [comment]
It does ! Thank you. FYI having the same object twice in a static archive is not harmless, it will trigger linker errors because the same symbols are defined twice.

**Comment by tristan957** [comment]
So should this be closed now?
