### ISSUE TITLE
Test using `custom_target` as executable

### ISSUE THREAD

**Issue by wm-noble** [mesonbuild/meson#10915]
I'd like to pass a `custom_tgt` object, as returned by `custom_target()`, as the 'executable' argument to a [`test()`][1] target, which currently only takes a `jar`, `exe`, `external_program`, or `file`.

The executable I need for the test is an interpreted script that is generated by a generator. It would appear that this is currently impossible to use as the test executable, because a `generated_list` must be passed to a `custom_target()` or `build_target()` rule. A `custom_target()` *could* be passed to an `executable()`, which could then be used in the `test()`, however `executable()` seems to require compilation / linking, and since this is an interpreted script, compilation is not possible.

[1]: https://mesonbuild.com/Reference-manual_functions.html#test

**Comment by dcbaker** [comment]
Generators are badly named, what they really are is "custom compilers" the design is really "I have a tool that batch processes files and outputs a 1:1 set of files. Say you have a custom test definition language that that outputs C files.

On to your other question, what I'm assuming is that you have something like:
```meson
script = custom_target(
  'script.rb',
  output : 'script.rb',
  ...
)
test('generated script test', script)
```meson
In that case what you want to do is find the interpreter as an external program, and pass the script as an input argument to the interpreter:
```
script = ...
test('generated script test', find_program('ruby'), args : [script])
```

**Comment by wm-noble** [comment]
Ah, I didn't realize there was type inheritance for `tgt` > `custom_tgt`. Your example is a good solution for me. Thanks.
