### ISSUE TITLE
Windows: missing note regarding environment path in "the absolute beginner's guide"

### ISSUE THREAD

**Issue by Ryder17z** [mesonbuild/meson#10913]
**Describe the bug**
The guide doesn't mention that a restart may be required before "meson args" will work.

**To Reproduce**
Just run the MSI installer. Meson path may or may not be visible before a reboot. 

**Expected behavior**
N/A

**system parameters**
Not relevant

**Comment by eli-schwartz** [comment]
This sounds like a quirk of Windows, not Meson, but it seems odd that Windows itself would require a restart just to change the path via an API that is supposed to change the path for all newly opened command prompts.

If you installed Meson via an existing python installation using `pip install` then the path that python set up will contain Meson too -- hence certainly no restart needed. https://mesonbuild.com/Quick-guide.html doesn't mention the MSI, just pip or Debian apt, but https://mesonbuild.com/SimpleStart.html#windows1 does...

**Comment by Ryder17z** [comment]
it's indeed a windows issue, but a beginner may not be aware of it. Hence it would be good to point it out in the guide.

It's possible that it's just the msi installer is contributing, I don't know much about that format.

**Comment by eli-schwartz** [comment]
Right, I am just trying to understand exactly when the issue comes up myself, since I'm actually not very familiar with Windows.

As I hinted above... is this actually a reboot issue? I have no idea. I'd be fascinated to know if e.g. logging out and then back in works.

**Comment by QuLogic** [comment]
Are you sure it's a restart, or just re-opening the command prompts you already had open (which is true everywhere, environment variables are not propagated to already-running programs)?

**Comment by Ryder17z** [comment]
> Are you sure it's a restart, or just re-opening the command prompts you already had open (which is true everywhere, environment variables are not propagated to already-running programs)?

needs further testing to be relevant.

Probably irrelevant:
On some systems, reopening cmd did not help. But that's something which had been encountered a very long time ago.

**Comment by Ryder17z** [comment]
i'm assuming error on my machine, hence closing this
