### ISSUE TITLE
-I. -I.. default include dirs

### ISSUE THREAD

**Issue by OlafvdSpek** [mesonbuild/meson#10923]
Meson appears to add `.` and `..` to the include path by default without being asked to do so. Where does this come from, where is it documented and how do I disable this?
Should this be opt-in rather than opt-out?

**Expected behavior**
No `.` and `..` in include path.

```
$ meson --version
0.63.3
```

**Comment by jpakkane** [comment]
`implicit_include_directories`

https://mesonbuild.com/Reference-manual_functions.html

> Should this be opt-in rather than opt-out?

It's this way because in practice it is way more common of the two.

**Comment by OlafvdSpek** [comment]
> It's this way because in practice it is way more common of the two.

Is there a reference for that?

**Comment by jpakkane** [comment]
Other than "based on the tons of CMake files et al that I crawled through before deciding this and seeing how it has been used since [1]", no.

[1] It is _shockingly_ common how many projects do something like `include_directories: include_directories('.')` even though that has _never_ been needed.

**Comment by OlafvdSpek** [comment]
> Other than "based on the tons of CMake files et al that I crawled through before deciding this and seeing how it has been used since [1]", no.
> 
> [1] It is _shockingly_ common how many projects do something like `include_directories: include_directories('.')` even though that has _never_ been needed.

At https://mesonbuild.com/Wrap-best-practices-and-tips.html I read:
> Many projects keep their config.h in the top level directory that has no other source files in it. In that case you don't need to move it but can just do this instead:
```
internal_inc = include_directories('.') # At top level meson.build
```

That shouldn't be necessary then right?

**Comment by jpakkane** [comment]
That is defining a include object, not building a target.

The point is that you can then use `internal_inc` in any target in any subdirectory and it will get expanded to the correct `-I` flags.

**Comment by dotnwat** [comment]
@jpakkane 

is there a way to opt-out of this globally for a project? it is a very real issue for some projects. for us, in particular, we find that with the default setting of including these implicit directories that we frequently have includes in dependencies (e.g. some project using `limits.h`) that will resolve to the incorrect path, usually some `limits.h` file in our project rather than the system header that the dependency intended. the inverse of this also happens.

**Comment by OlafvdSpek** [comment]
> usually some `limits.h` file in our project rather than the system header that the dependency intended. the inverse of this also happens.

I'd like to see an opt out too.
But a tip: put include files in a sub dir. And perhaps use `#include <climits>

**Comment by dotnwat** [comment]
@OlafvdSpek 

yep, thanks for the tip. the primary issue is that we don't want to move around 1000s of files in a massive project to use a different layout to avoid the problem. but point taken :)
