### ISSUE TITLE
Allow passing BuildTargets as arguments to a test run with test()

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#1094]
Sometimes you want to get the path to a helper executable that will be run as part of the test. Passing a `BuildTarget` as an argument should supply the full path to it.

You can already do this with `BuildTarget.full_path()`, but that won't provide us metadata to add a dependency to it. This is not important right now, but it will become important if/when we start adding more granular dependencies to individual `test` targets instead of requiring that `all` be built first.

**Comment by nirbheek** [comment]
This is possible now, but we don't set dependencies properly; see #1704.

**Comment by bonzini** [comment]
This is implemented now, see for example the docs for test introspection:

```
The `depends` entry *(since 0.56.0)* contains target ids; they can be
looked up in the targets introspection data.  The executable
pointed to by `cmd` is also included in the entry, as are any
arguments to the test that are build products.
```
