### ISSUE TITLE
Mixed LTO/non-LTO builds

### ISSUE THREAD

**Issue by LunarLambda** [mesonbuild/meson#10944]
An embedded project I would like to contribute meson build files for mixes LTO and non-LTO code in a static library. This is due to some files "miscompiling" with LTO with regards to certain inlining/linker section requirements being broken by it.

I'm not the author of the project, so significant file rewrites are probably out of the question. However, LTO in meson is a global option, it cannot be overriden per-target (i.e. my initial idea was bundling the non-LTO code into a static library and linking it into the final library)

What are the options? I could look into contributing fixes for the relevant files, but that has only a dubious chance of working, and otherwise, I could emit a warning/error when an LTO build is detected?

As far as I know, GCC and Clang have zero gripes about mixing LTO and non-LTO code (they have to allow it, right, so non-LTO library dependencies still work?), don't know how it looks for MSVC but I'd expect similar.

Could this be allowed in the future? (In the meantime, I might see if adding `-fno-lto` to `*_args` might be enough, since the project only targets embedded GCC anyhow)

**Comment by eli-schwartz** [comment]
> However, LTO in meson is a global option, it cannot be overriden per-target (i.e. my initial idea was bundling the non-LTO code into a static library and linking it into the final library)

Is this really true? That sounds like a bug if so -- you should be able to override any compiler options by specifying `override_options: [...]` as a kwarg to a build target.

**Comment by LunarLambda** [comment]
Oh geez, I had totally missed `override_options` in the documentation. Thank you very much 😅
