### ISSUE TITLE
The extract_objects() method warns unconditionally

### ISSUE THREAD

**Issue by ebassi** [mesonbuild/meson#1097]
Starting from 0.36.0, this code:

    solver_objects = libemeus.extract_objects(solver_sources)

where `solver_sources` is an array with a subset of sources used by a library, generates a warning when running Meson:

````
Single object files can not be extracted in Unity builds. You can only extract all the object files at once.
````

This happens regardless of whether I pass `--unity` or not, and even if I wrap the `extract_objects()` call under a:

    if not meson.is_unity()
    ...
    endif

This does not happen with Meson < 0.36.0, and being able to extract a subset of objects is useful when writing tests for a specific internal API.

**Comment by nirbheek** [comment]
It causes a warning, and not an exception? Could you show us the code that's causing this? There's a test for exactly this, so it should work: https://github.com/mesonbuild/meson/blob/master/test%20cases/common/25%20object%20extraction/meson.build#L9

**Comment by ebassi** [comment]
Sorry, I wasn't being accurate. Running meson I get:

```
Meson encountered an error in file src/meson.build, line 96, column 0:
Single object files can not be extracted in Unity builds. You can only extract all the object files at once.
```

and the execution terminates.

The code that causes the issue is in Emeus, prior to this commit: https://github.com/ebassi/emeus/commit/868265038e5461dff8ccf23ae377c3751d857a8a

I had to switch to an internal static library in order to keep working on it.

**Comment by nirbheek** [comment]
I see the problem now. The test case is faulty. I'll fix this and we should get the fix into a 0.36.1 release.

**Comment by nirbheek** [comment]
Could you please try the patch from #1098? It should work with that.

**Comment by ebassi** [comment]
@nirbheek The patch in #1098 indeed fixes the issue for me.
