### ISSUE TITLE
[Feature Improvement]  Use f-string by default

### ISSUE THREAD

**Issue by afm0901x** [mesonbuild/meson#10998]
As in version 0.63.3, user need to put 'f' explicitly to use f-string:
```
my_name = 'joe'
message(f'My name is @my_name@')
```
Output: `Message: My name is joe`

Suggested improvement:
```
my_name = 'joe'
message('My name is @my_name@')
```
Output: `Message: My name is @my_name@`
Expected output: `Message: My name is joe`

**Comment by eli-schwartz** [comment]
And what would be the syntax for outputting the literal string `'@my_name@'`?

**Comment by eli-schwartz** [comment]
> ```
> # this new syntax for f-string without 'f'
> message('%my_name%')
> message('${my_name}') # or shell-like syntax
> message('{my_name}') # or python-like syntax
> ```

And what would be the literal string syntax to print an actual `%my_name%`?

Or a literal `${my_name}`?

Or a literal `{my_name}`?

For the second case, comparing to shell, shell specifically handles this by distinguishing between single quotes, which are for literal strings, and double quotes, which are for formatted/interpolated strings.

For the third case, python is a fantastic example! Meson was inspired by python's f-strings to implement a similar feature ourselves. We even copied the name. And the really interesting thing about python is that it requires the f before the string.

**Comment by xclaesse** [comment]
I agree with @eli-schwartz, adding a 1 letter to prefix strings is a small price to pay compared to introduce escaping nightmares. Closing this as won't fix.
