### ISSUE TITLE
Incorrect cmakedefine implementation

### ISSUE THREAD

**Issue by Jan200101** [mesonbuild/meson#11006]
**Describe the bug**
the current cmakedefine implementation assumes that the definition name and value have to be the same
e.g.
`#cmakedefine VAR @VAR@`

**To Reproduce**
simply have any cmakedefine usage where the name and value mismatch
e.g.
`#cmakedefine const @HAVE_CONST@` (taken from SDL2 https://github.com/libsdl-org/SDL/blob/9d1dbd2ad86805c316cf4f2ee8ab2b361be18f4d/include/SDL_config.h.cmake#L34-L37)

**Expected behavior**
the value should be any definition value accepted by C 

This issue also affects muon, which is stricter about this and errors out.
Muon issue report: https://todo.sr.ht/~lattis/muon/77

**Comment by eli-schwartz** [comment]
This is a known issue, which mainly boils down to "cmakedefine is incredibly complicated in the confusing way".

It works for a subset of well-designed cmakedefine templates. I talked about this a bit at https://github.com/mesonbuild/wrapdb/issues/708#issuecomment-1286498712

You can see my personal policy on fixing this, there. :D

**Comment by eli-schwartz** [comment]
(My personal feeling on the matter is to use handwritten mesondefine templates.)

**Comment by Jan200101** [comment]
I've gone ahead and made a small test repo for this to test edge cases against cmake and meson
https://github.com/Jan200101/cmakedefine-test

The issues it catches thus far are:
- unimplemented cmakedefine01 (cmakedefine01 treated as cmakedefine)
- incorrect variable substitution 
- incorrect whitespace handling (like with `#define`, the hash (#) and `cmakedefine` keyword can be seperated by whitespace)

I'll find some more edge cases to fix and later implement tests for them in the unittests
