### ISSUE TITLE
ERROR: Unhandled python exception

### ISSUE THREAD

**Issue by Mculover666** [mesonbuild/meson#11009]
**Describe the bug**
the error has occured When I install mesa after build in rk3399 board.

```bash
mculover@eaidk:~/develop/mesa/mesa$ sudo ninja -C build install
ninja: Entering directory `build'
[1/2] Installing files.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 146, in run
    return options.run_func(options)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 811, in run
    installer.do_install(datafilename)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 564, in do_install
    d = self.check_installdata(pickle.load(ifile))
AttributeError: Can't get attribute 'OptionString' on <module 'mesonbuild.interpreter.primitives.string' from '/usr/lib/python3/dist-packages/mesonbuild/interpreter/primitives/string.py'>

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
FAILED: meson-internal__install 
/usr/local/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.

``` 

**To Reproduce**

**Expected behavior**

**system parameters**
* it is on arm64 rk3399 board
* ubuntu 22.04.1 LTS
* Python 3.10.4
* meson 0.64.0
* ninja 1.10.1

**Comment by gohv** [comment]
I was working on something else, but got exactly the same exception.

Hey @nirbheek any idea how we can push this forward? Just randomly saw you are a contributor, are you able to forward to someone else?

**Comment by Mculover666** [comment]
The problem has been solved, uninstall the version installed using apt-get.

Because meson is already installed on my system using apt-get,  I used pip to install it again.

**Comment by eli-schwartz** [comment]
Closing for the same reason as:
#8425
#8695
#8887
#10448 
#11650 
#11651
#12073
