### ISSUE TITLE
Meson 0.64 broke python3 dependency lookup on Windows when python path is specified via native-file

### ISSUE THREAD

**Issue by dnicolodi** [mesonbuild/meson#11017]
Something in the 0.64.0 release broke the python3 dependency lookup on Windows when the path to the python executable is specified via a native-file. This method of specifying the path of the python interpreter is used by `meson-python` the effect is that `meson-python` is broken on Windows when using Meson 0.64.0.

This is output from the `meson-python` tests run in the CI:
```
meson setup --native-file=D:\a\meson-python\meson-python\tests\packages\purelib-and-platlib\.mesonpy-native-file.ini -Ddebug=false -Doptimization=2 --prefix=C:\hostedtoolcache\windows\Python\3.8.10\x64 D:\a\meson-python\meson-python\tests\packages\purelib-and-platlib D:\a\meson-python\meson-python\tests\packages\purelib-and-platlib\.mesonpy-c5iteen7\build
The Meson build system
Version: 0.64.0
Source dir: D:\a\meson-python\meson-python\tests\packages\purelib-and-platlib
Build dir: D:\a\meson-python\meson-python\tests\packages\purelib-and-platlib\.mesonpy-c5iteen7\build
Build type: native build
Project name: purelib-and-platlib
Project version: 1.0.0
C compiler for the host machine: ccache gcc (gcc 11.2.0 "gcc.exe (MinGW-W64 x86_64-posix-seh, built by Brecht Sanders) 11.2.0")
C linker for the host machine: gcc ld.bfd 2.37
Host machine cpu family: x86_64
Host machine cpu: x86_64
found pkg-config 'C:\\Strawberry\\perl\\bin\\pkg-config.BAT' but it is Strawberry Perl and thus broken. Ignoring...
Found Pkg-config: NO
Could not find Python3 library 'D:\\a\\meson-python\\meson-python\\.nox\\test-3-8\\python38.dll'
Run-time dependency python3 found: NO (tried sysconfig)

..\..\meson.build:6:0: ERROR: Dependency lookup for python3 with method 'pkgconfig' failed: Pkg-config binary for machine 1 not found. Giving up.

A full log can be found at D:\a\meson-python\meson-python\tests\packages\purelib-and-platlib\.mesonpy-c5iteen7\build\meson-logs\meson-log.txt
```

**Comment by eli-schwartz** [comment]
> Something in the 0.64.0 release broke the python3 dependency lookup on Windows when the path to the python executable is specified via a native-file. This method of specifying the path of the python interpreter is used by `meson-python` the effect is that `meson-python` is broken on Windows when using Meson 0.64.0.

The python3 dependency lookup has never even looked at the native file to begin with. I don't know why this is only failing tests with Meson 0.64.0, because it should always have been broken.

It's actually an extremely primitive lookup, a bit like the deprecated `import('python3')` module -- it simply calls into Meson's own sysconfig and builds for that. You are generally advised to use the python module's `find_installation().dependency()` instead.

**Comment by dnicolodi** [comment]
Oh, you are right. I just assumed the `meson-python` tests did nothing stupid, but they do. I'll fix the tests. Sorry for the noise.

**Comment by eli-schwartz** [comment]
Yeah, looking at the meson-python tests they were linking to the headers and libraries of the default python, while using the sysconfigdata for naming and install paths of the selected python. Occasionally those were even the same python. :D
