### ISSUE TITLE
feature request: support ninja job pool to limit concurrent link jobs

### ISSUE THREAD

**Issue by zhaoweny** [mesonbuild/meson#11010]
Hi,

I'm using meson+ninja to compile qemu with ThinLTO enabled. Currently there is no control for limiting concurrent link jobs, which leads to launching `N` concurrent `lld` process, which in turn spawns `N` concurrent thread for LTO.

I think ninja's job pool is great for: 
* limit memory requirement for linking huge binaries
* avoid launching too many link jobs (which may use LTO threads) to slow down compilation because of kernel scheduling
* ~~feature matching with cmake~~

I think meson could also consider that using job pool to control concurrent compile jobs, which might help user to reserve part of system resource for other tasks.

**Comment by eli-schwartz** [comment]
I think you probably just want https://mesonbuild.com/Build-options.html#max-links
