### ISSUE TITLE
glib-2.74.0/meson.build:2087:0: ERROR: Unhandled python exception

### ISSUE THREAD

**Issue by 1582130940** [mesonbuild/meson#11040]
**Describe the bug**
Downloading zlib patch from https://wrapdb.mesonbuild.com/v2/zlib_1.2.11-6/get_patch
Traceback (most recent call last):
http.client.RemoteDisconnected: Remote end closed connection without response
../../../../build_dir/hostpkg/glib-2.74.0/meson.build:2087:0: ERROR: Unhandled python exception

    This is a Meson bug and should be reported!

**To Reproduce**
This is part of openwrt and it's not clear to me why this is happening.
https://github.com/1582130940/OpenWrt-Packages/tree/master/libs/glib2

**system parameters**
* ERROR: package/feeds/packages/glib2 [host] failed to build.
* Ubuntu 22.04.1 LTS
* Python 3.10.6
* meson 0.61.2

**Comment by eli-schwartz** [comment]
This is missing a full output log, but seems like for some reason:
- you need zlib
- you don't *have* zlib
- meson tries to download a copy of zlib on demand and fails with a networking error


Since Meson 0.62.0 it should actually try several times (exponential backoff) to retrieve the file, so it should be a lot harder to get any errors there.

**Comment by 1582130940** [comment]
> This is missing a full output log, but seems like for some reason:
> 
> * you need zlib
> * you don't _have_ zlib
> * meson tries to download a copy of zlib on demand and fails with a networking error
> 
> Since Meson 0.62.0 it should actually try several times (exponential backoff) to retrieve the file, so it should be a lot harder to get any errors there. Can you reproduce the issue using the latest version of Meson?

The version of meson is based on the upstream of openwrt, and openwrt has reverted the new version update.
Based on the problems mentioned in issues, I put the corresponding zlib patch in the OpenWrt-Lean-AMD64/build_dir/hostpkg/glib-2.74.0/subprojects directory (this problem may be related to my network), but put it in and then compile it (make V=s -j1) ERROR: Subproject exists but has no meson.build file.

**Comment by eli-schwartz** [comment]
The full build log might indicate why it didn't find OpenWrt's own copy of zlib...
