### ISSUE TITLE
meson crash: mesonbuild.mesonlib is not a package.

### ISSUE THREAD

**Issue by jralls** [mesonbuild/meson#11051]
The command ` meson configure . -Doptimization=0` crashes with a python stack trace:
```
Traceback (most recent call last):
  File "/Users/john/.local/share/virtualenvs/etc-vauAPygS/lib/python3.10/site-packages/mesonbuild/mesonmain.py", line 194, in run
    return options.run_func(options)
  File "/Users/john/.local/share/virtualenvs/etc-vauAPygS/lib/python3.10/site-packages/mesonbuild/mconf.py", line 300, in run
    c = Conf(builddir)
  File "/Users/john/.local/share/virtualenvs/etc-vauAPygS/lib/python3.10/site-packages/mesonbuild/mconf.py", line 72, in __init__
    self.build = build.load(self.build_dir)
  File "/Users/john/.local/share/virtualenvs/etc-vauAPygS/lib/python3.10/site-packages/mesonbuild/build.py", line 2907, in load
    obj = pickle.load(f)
ModuleNotFoundError: No module named 'mesonbuild.mesonlib.universal'; 'mesonbuild.mesonlib' is not a package

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

Source is [cairo](https://gitlab.freedesktop.org/cairo/cairo/) at [commit 6dc5df6](https://gitlab.freedesktop.org/cairo/cairo/-/commit/c6dc5df61264be1bec2e622355b97c6c45d236fc).

Native compilation on macOS 13.1beta with Xcode 14.1's toolchain. Python is a locally-compiled 3.10 in a pyenv-controlled virtenv, and meson-0.64.0 was just pulled from pypi with pip3.

**Comment by tristan957** [comment]
your system sounds broken

**Comment by jralls** [comment]
@tristan957 OK, but that's not very helpful. What is broken about it?

**Comment by tristan957** [comment]
Usually when I have seen this error it is because Meson was installed with a different version of Python than what it is being executed with.

**Comment by eli-schwartz** [comment]
But this happened in meson configure, when configuring an existing build directory.

The actual problem is that Meson requires you to re-setup when you update to a new major version.

Usually you'd get an "error: you configured with meson 0.63 which is an older version, pls redo everything, kthxbai", more or less.

In this case it failed before the error message could be generated so you got a stacktrace instead. This is a.UX bug, I know why it happened and I will PR the fix shortly.

**Comment by jralls** [comment]
Hmm. It turns out that @tristan957 was almost right: There are in fact two python builds accessible to meson though they're both v3.10.0. Meson was installed in the virtenv, but $PYTHON pointed to another instance of python3.10 and that python's sys.path doesn't include meson's modules.

However, it's also correct that once I did `rm -rf * && meson ../../src/cairo` with the new meson version `meson configure . -Doptimization=0` no longer crashes.

**Comment by tristan957** [comment]
Glad a PR could come out of it and your problem fixed :).
