### ISSUE TITLE
mesontest: Allow passing extra data to test runner to run, for example inside GDB or valgrind

### ISSUE THREAD

**Issue by thiblahute** [mesonbuild/meson#1105]
The conversation started here: https://github.com/mesonbuild/meson/pull/1087

Basically in GStreamer we need to set several env variable so the test can run in GDB:

For gdb:
 * `CK_FORK=no`

For Valgrind:
 * `CK_DEFAULT_TIMEOUT=360`
 * `G_SLICE=always-malloc`

We do not want to need our users to know about that as it is not intuitive and even myself that I am very aware of that forgot and got weird results making me loose time for nothing.

My approach in the previously linked pull request is to allow extra data in the `test` target to be consume at later time in the `mesontest` tool or possibly in other specific tool from meson users.

I implemented it with `gdb_env` as an extra argument known by the `mesontest` tool and we would need to add at least `valgrind_env` in there too.

**Comment by nirbheek** [comment]
This is fixed with #1106 being merged.
