### ISSUE TITLE
"Unhandled python exception" error when building a project with MSYS

### ISSUE THREAD

**Issue by Kr1eg3** [mesonbuild/meson#11069]
**Describe the bug**
Hello. I tried to build a new version of netflix vmaf according to their [guide](https://github.com/Netflix/vmaf/blob/master/resource/doc/windows.md) through MSYS and at the build step of the project I encountered a problem. I attached a screenshot of the error message  

![изображение](https://user-images.githubusercontent.com/50653532/202485705-1fdb4070-1666-406c-9730-25fd6132750b.png)

**To Reproduce**
I include my `meson.build` file below. I didn't do anything special this time. So I think you need to follow the guide to reproduce the error.

**Expected behavior**
I've already built a netflix project on other systems. So this time I expected the same behavior.

**system parameters**
*  Windows 11 Pro
* I used MSYS, so all questions below are answered: those which are in MSYS

[meson.zip](https://github.com/mesonbuild/meson/files/10032893/meson.zip)

**Comment by eli-schwartz** [comment]
I think this is just another way to encounter #11051

You originally configured the project with a different major.minor version of Meson (patchlevel versions are compatible) and Meson is *supposed* to catch ModuleNotFoundError when loading internal data files, and print a warning that you used a different version of Meson and you need to reconfigure. There's a pending PR to fix it.

**Comment by eli-schwartz** [comment]
The fix is merged in git master, so you should get better error messages for this soon.
