### ISSUE TITLE
Meson configure fails when setting compiler options for unused languages

### ISSUE THREAD

**Issue by hwti** [mesonbuild/meson#11060]
**Describe the bug**
On a project which only enables C :
 - `meson setup -Dcpp_args='-DFOO' build` succeeds (without even a warning)
 - `meson configure -Dcpp_args='-DFOO'` fails with `ERROR: Unknown options: "cpp_args"`

With an empty project, it also happens with `c_args`.

This happens when meson is integrated in a buildsystem which sets `c_args`, `c_link_args`, `cpp_args`, `cpp_link_args`.
Note that the options are given on the command line since it allows changes to apply (as long as it doesn't affect configuration), while changes in cross or native files only apply after a full wipe (despite the `Regenerating build files`, ie `meson --internal regenerate`).

**To Reproduce**
```
project('foo')
```
`meson setup -Dc_args='-DFOO' build` => OK
`meson configure -Dc_args='-DFOO' build` => `ERROR: Unknown options: "c_args"`

**Expected behavior**
`meson configure` should silently ignore compiler options for unused languages, like `meson setup`. 

**system parameters**
* Issue happens both with native and cross build.
* Meson 0.64.0 or master

**Comment by hwti** [comment]
This is in fact fatal since dbf2ace6ca1ce39aa01497f815b65856079cc581.

`meson setup` uses `set_default_options` which filters out `OptionType.COMPILER, OptionType.BACKEND, OptionType.BASE`, before calling `set_options`.

So maybe :
```diff
             elif k in self.options:
                 self.set_option(k, v)
-            elif k.machine != MachineChoice.BUILD:
+            elif k.machine != MachineChoice.BUILD and k.type != OptionType.COMPILER:
                 unknown_options.append(k)
```
`OptionType.BASE` could be excluded too, but this would only happen when setting compiler-specific options like `b_bitcode` or `b_vscrt` on the wrong compiler (maybe this should even be a failure for `meson setup`).

Btw, it seems the `k.machine != MachineChoice.BUILD` check is only there for the `test_cross_file_dirs` / `test_cross_file_dirs_overridden` / `test_cross_file_dirs_chain` tests, which use a native file with paths.
`build.binddir` and others do not exist, which makes sense since Meson refuses to install a native target in a cross build.
So maybe it could be removed, with https://mesonbuild.com/Machine-files.html#paths-and-directories updated to make it explicit that paths can only be specified in cross files when cross compiling, and in native files otherwise.

**Comment by dcbaker** [comment]
The paths and directories section is deprecated in favor of the built-in arguments section anyway. I'm not super in favor of erroring on them in cross build because it means that I'd have to split more native files and pass more arguments around when cross compiling vs not cross complining, whereas right now meson just helpfully ignores them and I get to use one file.

I'd be fine wtih `meson configure` just doing what `meson setup` does and ignoring options for compilers that we're not using.

**Comment by hwti** [comment]
> The paths and directories section is deprecated in favor of the built-in arguments section anyway. I'm not super in favor of erroring on them in cross build because it means that I'd have to split more native files and pass more arguments around when cross compiling vs not cross complining, whereas right now meson just helpfully ignores them and I get to use one file.

This is the same for `[built-in options]`.
This is the `k.machine != MachineChoice.BUILD` check which avoids failures with :
 - `bindir` in a native file on a cross build for `meson setup`
 - `-Dbuild.bindir` for `meson setup` and `meson build`

> I'd be fine wtih `meson configure` just doing what `meson setup` does and ignoring options for compilers that we're not using.

Do you mean `k.type != OptionType.COMPILER` (allowing `cpp_args` and others), or `k.type not in {OptionType.COMPILER, OptionType.BASE}` (also allowing `b_bitcode`, `b_vscrt`) ?

**Comment by dcbaker** [comment]
For sure `k.type != OptionType.COMPILER`, I'd have to thik more about b_bitcode and b_vscrt... which we should deprecated b_bitcode because apple has deprecated it
