### ISSUE TITLE
Meson 0.64.0 configure output broken when $PAGER is set.

### ISSUE THREAD

**Issue by philj56** [mesonbuild/meson#11075]
**Describe the bug**

In Meson 0.64.0, `meson configure` uses `$PAGER` to display its output with colours. If `$PAGER` is set to e.g. `less`, without `-R`, this leads to broken output containing colour escape sequences.

**To Reproduce**

```sh
export PAGER=less
meson configure
```

**Expected behavior**

Other tools handle this by setting the appropriate environment variables or arguments. For example,

- git sets `LESS=FRX` in [CMakeLists.txt#L235](https://github.com/git/git/blob/a0789512c5a4ae7da935cd2e419f253cb3cb4ce7/contrib/buildsystems/CMakeLists.txt#L235), then uses it in [pager.c](https://github.com/git/git/blob/36f8e7ed7d72d2ac73743c3c2226cceb29b32156/pager.c#L72-L97).
- [bat](https://github.com/sharkdp/bat) checks if `less` is the pager, and appends the appropriate arguments in [output.rs#L76-L93](https://github.com/sharkdp/bat/blob/7c847d84b0c3c97df6badfbb39d153ad93aec74e/src/output.rs#L76-L93).

**Comment by tristan957** [comment]
@xclaesse

**Comment by xclaesse** [comment]
To be fair, I got mixed feelings, on one hand I personally think `PAGER=less` means user wants to use bare less (otherwise why setting PAGER at all), but on the other hand since that's what git does I guess that's the defacto standard way... Want to open a PR?

**Comment by philj56** [comment]
Sure, I've opened #11144. For me, the reason to set `PAGER=less` over not setting it at all is because otherwise it normally defaults to `more` (though that might be outdated knowledge from when I started on Ubuntu years ago). But yeah, I can totally see your side of the argument - I guess it's a case of "do exactly what I say" vs. "do what I probably expected to happen".

**Comment by philj56** [comment]
Thanks for the responses and getting the change merged!
