### ISSUE TITLE
-Wnon-virtual-dtor is a dumb option, don't use it

### ISSUE THREAD

**Issue by jwakely** [mesonbuild/meson#11096]
The default warnings for C++ (and Obj-C++) appear to include `-Wnon-virtual-dtor`. This is a very strange choice. That warning is pretty much broken by design, and doesn't warn about the right thing anyway. Why is it enabled by default?

https://github.com/mesonbuild/meson/blob/master/mesonbuild/compilers/cpp.py#L359

I added `-Wdelete-non-virtual-dtor` to GCC in [2011](https://gcc.gnu.org/g:014ab419efc12a59efebd2720d79e1c055675c85), copying it from Clang which has had it for even longer. That warns when you try to `delete` a polymorphic object with a non-virtual destructor, which is the real problem case that matters. Simply *having* a non-virtual dtor is not  bug (and GCC has numerous false positives where it warns even if the dtor is protected, or deleted, or otherwise unable to lead to the problems the warning tries to prevent).

The `-Wdelete-non-virtual-dtor` has no false positives, it only warns about code that actually has a problem, not about classes that might have a potential problem.

**Comment by eli-schwartz** [comment]
I submitted #10339 to remove it. I got the response:
> The reason I added it was that it is actually very useful as opposed to the rest of `-Weffc++`, which are inconvenient. IMHO it should be in `-Wall` but sadly isn't. There are a bunch of other such flags like `-Wshadow` but I did not add those at the time because I did not know that they existed.

I continue to think merging that PR is the correct choice.

**Comment by eli-schwartz** [comment]
> If using a slightly different option instead is a suitable compromise I'll be happy to update my PR

Scratch that, the alternative option is already part of `-Wall`. :D

**Comment by jwakely** [comment]
Yes, the alternative is in `-Wall` because it's actually useful, without false positives. And there are good reasons `-Wnon-virtual-dtor` is not in `-Wall`: it has too many false positives, and is about style, not correctness (there's no problem with non-virtual dtors if you never delete through a pointer to the base class). The correctness aspect is covered by the newer warning, so `-Wnon-virtual-dtor` is now just about coding style.

If somebody wants to use it in their own code, or their employer's codebase, that's fine. But forcing it on all users of meson as a default policy is ... well I don't have anything polite to say about that. It's not a good policy.

A build system should not be dictating C++ coding style by automatically enabling warnings that are about coding style, not about correctness.
