### ISSUE TITLE
`python.extension_module()` linking with libpython when it should not

### ISSUE THREAD

**Issue by dnicolodi** [mesonbuild/meson#11097]
Since version 0.63.0 Meson automatically adds a dependency on libpython when needed compiling extension modules. To determine whether to link to libpython Meson consults `distutils`. On Python 3.7 on Linux, `distutils` says that libpython should not be linked:
```python
>>> import distutils.core
>>> cmd = distutils.core.Distribution().get_command_obj('build_ext')
>>> cmd.ensure_finalized()
>>> cmd.get_libraries(distutils.core.Extension('dummy', []))
[]
```
However, the `pkg-config` file for python contains these linker arguments
```
$ pkg-config python3 --libs
-L/opt/_internal/cpython-3.7.15/lib -lpython3.7m
```
This code https://github.com/mesonbuild/meson/blob/fd43842041e8ca83b1baee94f053c814e144f98b/mesonbuild/modules/python.py#L524-L543
deals with adding the libpython dependency as need. In the case the libpython dependency is explicitly requested, only the compile arguments are used, however, in the case when it is not explicitly requested, all the arguments are added, including the link arguments found via `pkg-config`. I think that only the compile arguments should be included in this case too when the extension module should not be linked with libpython.

I'll prepare a PR, but I would like to check with @eli-schwartz if he agrees on the diagnosis.

**Comment by eli-schwartz** [comment]
This diagnosis confusesme since we specifically check for link_libpython and remove the link arguments (keeping only the compile ones).

However, on 3.7 you are supposed to link to libpython, except on Debian...

**Comment by eli-schwartz** [comment]
Oh, I think I see it now.

**Comment by dnicolodi** [comment]
I think the patch makes it clearer. I actually encountered the issue on the manylinux docker images, which are based on AlmaLinux. I suspect Debian may be patching the pkg-condig too.

**Comment by eli-schwartz** [comment]
The thing is that the patch is exactly what I thought you meant, and I don't see how that's possible to be a problem.

The internal dependency is `embed: false`.

**Comment by dnicolodi** [comment]
I stepped through the thing with a `pdb` and the linker flags are added. I'm afraid I don't know enough of the surrounding code to understand exactly why. However, I just verified that this solves the issue on Linux and a segfault on macOS.

The pkg-config definition oh the system looks like this:
```
# cat /opt/_internal/cpython-3.7.15/lib/pkgconfig/python3.pc
# See: man pkg-config
prefix=/opt/_internal/cpython-3.7.15
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: Python
Description: Python library
Requires:
Version: 3.7
Libs.private: -lcrypt -lpthread -ldl  -lutil
Libs: -L${libdir} -lpython3.7m
Cflags: -I${includedir}/python3.7m
```
Let me know if there is anything else that may be useful to better understand the root cause.

**Comment by dnicolodi** [comment]
I think the bug is most likely in the discrepancy between `distutils` and `pkg-config` for Python 3.7. But fixing it may be a bit late. I think that dealing with it in Meson is the only option.

**Comment by dnicolodi** [comment]
Also note that the distinction from `python3.pc` and `python3-embed.c` comes only starting with Python 3.8, so as long as Meson supports Python 3.7, we need to filter out the link flags.

**Comment by dnicolodi** [comment]
> The internal dependency is `embed: false`.

I had a closer look at the Meson python module code and I understood better what you mean with the above sentence. When the dependency is looked up with `embed=False` the `python3.pc` is looked up and when `embed=True` the `python3-embed.pc` is used instead. As I was writing above, up to Python 3.7 there is no `python3-embed.pc` thus this does not have the effect of removing the linking to libpython as per the `python3.pc` reported above.

**Comment by eli-schwartz** [comment]
> The internal dependency is `embed: false`. If you provide one we don't know what it is so we partial it.

So for clarity, I looked at this last night, and I apologize, because what I said was incredibly bogus and clueless. I double and triple checked, and actually `py.dependency()` itself is broken with pkg-config, then crudely hacked around inside extension_module using partial_dependency.

The correct fix is: https://github.com/eli-schwartz/meson/commit/889f9131596cd1a5677c90b0953164286bafb917

**Comment by dnicolodi** [comment]
Thanks @eli-schwartz Your fix looks good to me, FWIW.

**Comment by eli-schwartz** [comment]
Alright, PR'ed.
