### ISSUE TITLE
Compilers specified as full paths with spaces are botched on meson setup

### ISSUE THREAD

**Issue by amyspark** [mesonbuild/meson#11128]
**Describe the bug**

On Windows, it is possible to have paths with spaces if these are kept inside single or double quotation marks.

If these are fed to Meson through `CC` or `CXX`, or maybe through a native or cross file, `compilers.detect._get_compilers` will wrongly split the path on the first space with `BinaryTable.parse_entry`, take the first component as a "wrapper" (ccache) and the rest as the "path" to the compiler. A similar botched escape will take place for the linker.

This breaks CMake setup later, as this will get fed as a toolchain file:

```cmake
set(CMAKE_SIZEOF_VOID_P "8")
set(CMAKE_C_COMPILER_LAUNCHER "C:/Program")
set(CMAKE_C_COMPILER "Files/Microsoft" "Visual" "Studio/2022/Preview/VC/Tools/Llvm/x64/bin/clang-cl.exe")
set(CMAKE_LINKER "c:/Program" "Files/Microsoft" "Visual" "Studio/2022/Preview/VC/Tools/MSVC/14.35.32019/bin/Hostx64/x64/link.exe")
```

triggering this on the log:

```
Found CMake: C:\Program Files\CMake\bin\cmake.EXE (3.23.1)
WARNING: CMake Toolchain: Failed to determine CMake compilers state
```

`WARNING: CMake Toolchain: Failed to determine CMake compilers state` repeats once per failed `dependency()` lookup.

**To Reproduce**

Install the Clang tools from the Visual Studio Installer (here I'm using 2022 Preview), then try to set up the following environment:

```powershell
$env:CC="C:\\Program Files\\Microsoft Visual Studio\\2022\\Preview\\VC\\Tools\\Llvm\\x64\\bin\\clang-cl.exe"
$env:CXX = "c:/Program Files/Microsoft Visual Studio/2022/Preview/VC/Tools/MSVC/14.35.32019/bin/Hostx64/x64/link.exe"
meson setup build
```

meson.build:

```meson
project('test', 'c')

dep = dependency('theoradec', required: false)
```

**Expected behavior**

Meson should not escape paths to compilers unless it could clearly differentiate a path from a command list.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? **no**
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) **Windows 10 21H2**
* what Python version are you using e.g. 3.8.0 **3.10.1**
* what `meson --version` **0.64.0**
* what `ninja --version` if it's a Ninja build **1.10.2**

**Comment by eli-schwartz** [comment]
> If these are fed to Meson through `CC` or `CXX`, or maybe through a native or cross file, `compilers.detect._get_compilers` will wrongly split the path on the first space with `BinaryTable.parse_entry`, take the first component as a "wrapper" (ccache) and the rest as the "path" to the compiler. A similar botched escape will take place for the linker.

That's actually completely untrue, the general issue is that the CC and CXX environment variables are defined by convention (as in, the convention that such a variable exists and is meaningful) as a shell string that undergoes shell splitting.

It may contain prefixes, like `CC="ccache cc"`, or suffixes such as `CC="gcc -m32"`, or a variety of other things.

It is parsed by `Environment._set_default_binaries_from_env()`, which in turn runs `mesonlib.split_args(cmd)`.

**Comment by Neumann-A** [comment]
No problem passing those paths via cross/native files. vcpkg does it all the time in the form of:
`c = ['C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe']`

resulting into:
```
# Variables from meson
set(CMAKE_SIZEOF_VOID_P "8")
set(CMAKE_C_COMPILER "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe")
set(CMAKE_CXX_COMPILER "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe")
```

**Comment by kiwixz** [comment]
I faced the same issue, and could work around it by adding double quotes to the path inside the variable.  This behavior and the workaround are probably worth mentioning in the docs.

**Comment by eli-schwartz** [comment]
A documentation PR would be lovely. :)
