### ISSUE TITLE
Include osx loadable modules support (-bundle)

### ISSUE THREAD

**Issue by panitaxx** [mesonbuild/meson#1112]
Please include a loadable module target (-bundle flag  without -shared and -install_name flag) for OS X (mac os)

**Comment by jpakkane** [comment]
Can you test #1126 to see if it works for you?

**Comment by panitaxx** [comment]
It works fine  except that in OS X usually the shared modules (bundles) has .so  or .bundle extension and this one has a .dylib extension.
