### ISSUE TITLE
Meson does not detect a changed prefix

### ISSUE THREAD

**Issue by hughsie** [mesonbuild/meson#1113]
I get this:

    $ meson ../ && ninja-build install
    ...
    PermissionError: [Errno 13] Permission denied: '/usr/local/share/glib-2.0'
    $ meson ../ --prefix=/home/hughsie/.root && ninja-build install
    Error during basic setup:
    Trying to run Meson on a build directory that has already been configured.
    If you want to build it, just run your build command (e.g. ninja) inside the
    build directory. Meson will autodetect any changes in your setup and regenerate
    itself as required.

Surely meson should detect that the prefix is different and re-run the config (and rebuild all the files) accordingly? It seems a little odd to have to nuke my entire build directory manually (rm -rf) for this common case.

**Comment by tp-m** [comment]
At the very least it should mention `mesonconf` for changing options.

**Comment by TingPing** [comment]
Yes you would do `mesonconf -Dprefix=/home/hugsie/.root`

**Comment by jpakkane** [comment]
Error message updated to tell about `mesonconf`.
