### ISSUE TITLE
Meson 0.64 ERROR: Unknown variable "fs" when calling fs.copyfile(...)

### ISSUE THREAD

**Issue by Ryder17z** [mesonbuild/meson#11136]
**Describe the bug**
In some scenarios, a build process includes copying files to a directory that is not the build directory, but is instead a subdir inside the project directory.
But this doesn't seem to be working in meson and the error message is weird.

**To Reproduce**
```
project('tutorial', 'c')
executable('demo', ['src/source.c'])

import('fs')
copy = fs.copyfile('src/from.txt', 'data/to.txt')
install(copy)

# ERROR: Unknown variable "fs".
```

**Expected behavior**
Build the project and copy the indicated file post-build. (Assuming destination folder exists)

If there is a better method to copy a file like this, I have not found it.

**system parameters**
* `Is this a cross build`  yes (or Not Applicable)
* `operating system`  Manjaro Linux 22.0.0
* `Python version`  3.10.8
* `meson --version`  0.64
* `ninja --version`  N/A

**Comment by eli-schwartz** [comment]
You must assign the import to a variable.

**Comment by Ryder17z** [comment]
Right. Fixed that part, but then above example complains that "Destination path may not have path separators" so it doesn't help much.

**Comment by eli-schwartz** [comment]
What is the purpose of copying files

> to a directory that is not the build directory, but is instead a subdir inside the project directory.

If you're copying files from the source directory, to the source directory -- why not simply check that source file into git? What should be done when the source tree is mounted read-only? What should be done when multiple build directories are configured, and each one tries to copy that file to the source directory?

**Comment by Ryder17z** [comment]
> What should be done when the source tree is mounted read-only?

This has no effect. Unless your implying that the project root directory is the same as the "source tree" directory.

> If you're copying files from the source directory, to the source directory

Not necessarily, if `meson setup /home/user/absolute/path/builddir` is a valid command.
Then the target path for copyfile should be resolved to `/home/user/absolute/path/data`

It is quite common to have a project directory structure like this:

```
myapp
/bin/myapp
/data/resource.1
/data/resource.2
/data/resource.3
...
```
This directory may or may not also include the source directory

**Comment by eli-schwartz** [comment]
> This has no effect. Unless your implying that the project root directory is the same as the "source tree" directory.

I'm not implying it -- they are two phrases that mean the same thing. A project root directory is the root of the source tree which constitutes the project.



> Then the target path for copyfile should be resolved to `/home/user/absolute/path/data`

???

Output paths for build targets are always resolved relative to the build directory, not the source directory.

> It is quite common to have a project directory structure like this:
> [...]
> This directory may or may not also include the source directory

I'm not entirely sure what this means -- the project directory structure is, again, the source code director(ies)

It is distinctive from build artifacts -- files created by a build system, which git might report as untracked files unless they are in a `.gitignore` file.
