### ISSUE TITLE
Meson i18n.gettext does not support globbing languages

### ISSUE THREAD

**Issue by hughsie** [mesonbuild/meson#1115]
In GNOME we use a m4 snippet called AS_ALL_LINGUAS which is normally copy-pasted around projects: https://git.gnome.org/browse/gnome-software/tree/m4/as-linguas.m4

What this allows is a glob of all *.po files in po/ which avoids listing them all like:

    langs = [
      'af',
      'ar',
      'as',
      'ast',
      'be',
      'be@latin',
      'bg',
      'bn',
      'bn_IN',
      'bs',
      'ca',
      'ca@valencia',
      'cs',
      'cy',
      'da',
      'de',
      'dz',
      'el',
      'en_CA',
      'en_GB',
      'en@shaw',
      'eo',
      'es',
      'et',
      'eu',
      'fa',
      'fi',
      'fr',
      'ga',
      'gd',
      'gl',
      'gu',
      'he',
      'hi',
      'hr',
      'hu',
      'id',
      'is',
      'it',
      'ja',
      'ka',
      'km',
      'kn',
      'ko',
      'ku',
      'lt',
      'lv',
      'mai',
      'mg',
      'mk',
      'ml',
      'mr',
      'my',
      'nb',
      'nl',
      'nn',
      'oc',
      'or',
      'pa',
      'pl',
      'pt',
      'pt_BR',
      'ro',
      'ru',
      'si',
      'sk',
      'sl',
      'sr',
      'sr@latin',
      'sv',
      'ta',
      'te',
      'tg',
      'th',
      'tr',
      'ug ',
      'uk',
      'vi',
      'zh_CN',
      'zh_HK',
      'zh_TW
      ]

langs in GNOME modules are frequently 80+ items in size, and translators typically only create the .po file and automatically upload the file, meaning it never actually gets used unless the maintainer somehow notices the .gmo file isn't installed.

I know meson and globbing are not friends, but I wondered if this was functionality that could somehow be added so there's not a regression when porting away from automake. Ideas welcome!

**Comment by hughsie** [comment]
Note, this is the workaround: https://github.com/ebassi/emeus/blob/vfl-editor/po/README.i18n

**Comment by TingPing** [comment]
I've always thought we should reuse the `po/LANGS` file as the translators maintain that, no reason to duplicate it in the build files.

**Comment by hughsie** [comment]
You mean `LINGUAS`, right?

**Comment by hughsie** [comment]
I think if it exists, it makes sense to use it. Could we also generate LINGUAS using a glob perhaps?

**Comment by TingPing** [comment]
I'll work on a patch to read from LINGUAS but I think globing files part of the build system go against Meson's design which is to be fairly explicit. You can't glob source files or data files to install for example which I believe is a conscious decision.

**Comment by hughsie** [comment]
This works great, thanks!
