### ISSUE TITLE
Setup fails if you use fs.copyfile and enable installing to a subdirectory

### ISSUE THREAD

**Issue by sycc90** [mesonbuild/meson#11157]
**Describe the bug**
I have a file (script, text file, whatever) that needs to be copied during build (to be able to test and develop without installing) and also needs to be installed during the installation process.  If you copy it with fs.copyfile and specify an install_dir that is a subdirectory, you get an error such as:
```
ERROR: Target 'file.txt' has 1 outputs: ['file.txt'], but only 9 "install_dir"s were found.
Pass 'false' for outputs that should not be installed and 'true' for
using the default installation directory for an output.
```
The error happens during meson setup.

**To Reproduce**
This is a minimal meson.build to reproduce the issue:
```meson
project('MyProject', 'cpp')
executable(
  'myproject',
  'myproject.cpp',
  install : true,
  install_dir : 'something',
)
import('fs').copyfile(
  'file.txt',
  install : true,
  install_dir : 'something',
)
```
If I replace 'something' in the copyfile install_dir with '.' it succeeds.

**Expected behavior**
meson setup should succeed and the file should be copied to the specified subdirectory during installation.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
  Native build.
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)?
  Windows 10
* what Python version are you using e.g. 3.8.0
  Python 3.10.0
* what `meson --version`
  0.64.1
* what `ninja --version` if it's a Ninja build
  1.10.2

**Comment by tristan957** [comment]
@eli-schwartz which version of Meson has this fix?

**Comment by eli-schwartz** [comment]
It was milestoned for 0.64.2 but we never released such a bugfix release in the end. So it's part of 1.0

**Comment by tristan957** [comment]
Perfect. Thanks for the information.
