### ISSUE TITLE
devenv not setting path in windows

### ISSUE THREAD

**Issue by sycc90** [mesonbuild/meson#11158]
**Describe the bug**
Building an application with a dll library in a subdirectory and trying to run it from within the builddir by using devenv, however, it's not setting the path so the executable cannot find the dll.

**To Reproduce**
You can reproduce with this minimal example, this is the directory structure:
```
MyProject
  |-- myproject.cpp
  |-- meson.build
  \-- lib
       |-- meson.build
       |-- lib.cpp
       \-- lib.h
```
And these are the two meson files:
```meson
# meson.build
project('MyProject', 'cpp')
subdir('lib')
executable(
  'myproject',
  'myproject.cpp',
  dependencies : lib_dep,
)

# lib/meson.build
lib = shared_library(
  'lib',
  'lib.cpp',
)
lib_dep = declare_dependency(
  link_with : lib,
  include_directories : '.',
)
```
Then I build everything in pwsh (PowerShell 7.3.0) as such:
```
> meson setup builddir
> meson compile -C builddir
> meson devenv -C builddir --dump
PKG_CONFIG_PATH=/path/to/MyProject/builddir/meson-uninstalled
export PKG_CONFIG_PATH      
MESON_PROJECT_NAME=MyProject
export MESON_PROJECT_NAME   
MESON_DEVENV=1
export MESON_DEVENV
```
Of course, if I don't use the `--dump` option so that it actually opens the shell, if I then try to run the myproject.exe then it fails with error 0xc0000135.

**Expected behavior**
The path is set to point to builddir/lib so that myproject.exe can find the correct dll.  I can set the path manually with `$env:Path += '/path/to/MyProject/builddir/lib` and then the executable works.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
  Native build.
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)?
  Windows 10
* what Python version are you using e.g. 3.8.0
  Python 3.10.0
* what `meson --version`
  0.64.1
* what `ninja --version` if it's a Ninja build
  1.10.2

**Comment by xclaesse** [comment]
I only set PATH for installable DLLs and executables, any reason you did not have `install: true` on those targets?

**Comment by sycc90** [comment]
I was trying to remove as much as possible from the minimal example, but you're right that that should be there.  After double checking that, it turns out that it's a bit more weird.
If I add `install : true` to them, then it works correctly.  However, if I _also_ add `install_dir : 'some_subdir'` to **all** of them, then it stops working again.  So it seems that there needs to be at least one target that has install without install_dir.

For example, try with this one:
```meson
# meson.build
project('MyProject', 'cpp')
subdir('lib')
executable(
  'myproject',
  'myproject.cpp',
  dependencies : lib_dep,
  install : true,
  install_dir : 'myexe',
)

# lib/meson.build
lib = shared_library(
  'lib',
  'lib.cpp',
  install : true,
  install_dir : 'mylib',
)
lib_dep = declare_dependency(
  link_with : lib,
  include_directories : '.',
)
```
Then comment out one of the `install_dir` options and it'll start working.

PS:  by the way, why does it only work with installable targets?  It's quite common for us to have things that are only compiled for developers to aid development but are not meant to be installed, so we have no way of linking against them other than installing everything and then manually (via custom script) removing what's unnecessary.

**Comment by eli-schwartz** [comment]
The original intention of devenv was to expose a way to take some installable software and then run it without doing the actual installation part. For example this is useful when crossing project boundaries and you want to compile one against the other, but not mess with the version installed as root to /usr.

I suppose the assumption was that non-installed targets are not really useful except internally by custom_targets, rather than as a public build product.

**Comment by xclaesse** [comment]
> If I add `install : true` to them, then it works correctly. However, if I _also_ add `install_dir : 'some_subdir'` to **all** of them, then it stops working again. So it seems that there needs to be at least one target that has install without install_dir.

This is expected and documented: https://mesonbuild.com/Commands.html#devenv

> PATH includes every directory where there is an executable that would be installed into bindir. 

As @eli-schwartz said, the assumption for devenv is to reproduce an env that would work as if you actually did the install. So you can run executables installed into /usr/bin but not those installed into /usr/bin/foo. 

That said, I'm not against extending the initial use-case, I'm just a bit scared that if we include all tools and internal libraries, PATH will become huge and exceed the limit. Maybe that should be an option.

**Comment by sycc90** [comment]
> As @eli-schwartz said, the assumption for devenv is to reproduce an env that would work as if you actually did the install. So you can run executables installed into /usr/bin but not those installed into /usr/bin/foo.

I'm a bit confused by this, if I specify an install_dir, my installation would place everything inside that subdirectory, why would this prevent the devenv from working?
I probably over-complicated it by using different directories, but let's say I have `install_dir : 'myproject'` for both targets (the exe and the dll lib).  After installing, both would end up in the same output directory and windows will be able to run that without issues because it searches for dlls in the same path.  However, if I want to test without installing by using the devenv, meson won't set the PATH and it won't work.

Maybe the documentation is not clear enough?  It says (emphasis by me):

> "PATH includes every directory where there is an executable that would be installed into bindir. **On windows it also includes every directory where there is a DLL needed to run those executables**."

It says it **also** includes every directory with a necessary DLL.

**Comment by xclaesse** [comment]
> > "PATH includes every directory where there is an executable that would be installed into bindir. **On windows it also includes every directory where there is a DLL needed to run those executables**."
> 
> It says it **also** includes every directory with a necessary DLL.

It will include path of DLLs needed for executables installed into `<prefix>/<bindir>`, not for executables installed elsewhere. For example tools being installed into `/usr/libexe/` are not taken into account. I'm not against relaxing that limitation, but that's the current rational.

**Comment by sycc90** [comment]
Oh I see, I get it now!  Sorry for the misunderstanding.
In that case, while I do think it would be really useful for this feature to include all executables/dlls and not just those installed in <bindir>, this is definitely not a bug and I will be closing it.
Thank you very much for your patience, you've been very helpful!
