### ISSUE TITLE
Meson does not support creating a ChangeLog automatically

### ISSUE THREAD

**Issue by hughsie** [mesonbuild/meson#1116]
In lots of GNOME projects we support creating the ChangeLog file automatically from the git history, like this: https://git.gnome.org/browse/gnome-software/tree/Makefile.am#n57

I don't think this feature is available in Meson, but it probably belongs in the meson GNOME module.

**Comment by ignatenkobrain** [comment]
Well, I think you should define custom target for this.

**Comment by hughsie** [comment]
Or, as lots of other people said: just drop generation of ChangeLog files. :)
