### ISSUE TITLE
Meson does not support creating a NEWS file automatically

### ISSUE THREAD

**Issue by hughsie** [mesonbuild/meson#1117]
In lots of GNOME projects we support creating the NEWS file automatically from AppData files, like this: https://git.gnome.org/browse/gnome-software/tree/Makefile.am#n71

I don't think this feature is available in Meson, but it probably belongs in the meson GNOME module. The GNOME infrastructure requires a NEWS file to be updated for each tarball release, so this is probably more important than issue #1116.

Note, in this file we have a glob for multiple appdata files, but typically we only have one file, and in some cases maybe two or three (but not hundreds).

**Comment by ignatenkobrain** [comment]
I think this should be also done through custom target.

**Comment by hughsie** [comment]
The slight snag here is that "appstream-util appdata-to-news" just outputs the resulting data to the console, and I don't see any way to redirect that output to a file in Meson.

**Comment by TingPing** [comment]
`custom_target` has the `capture` kwarg to redirect stdout.

**Comment by hughsie** [comment]
Okay, that's good enough for me, thanks!
