### ISSUE TITLE
compiler.preprocess() should have an include_directories kwarg

### ISSUE THREAD

**Issue by LunarLambda** [mesonbuild/meson#11202]
Basically every single compiler method that deals with code has an `include_directories` kwarg, including compiles, run, and the preprocessor-specific has_header, check_header, has_header_symbol, and get_define.

It's a strange inconsistency, even if it can be worked around using the compile_args kwarg, *assuming* you're not using `include_directories()` objects, which are not iterable and do not have automatic to-compiler-argument conversion when passed in *_args kwargs.

On that note, we also have no equivalent of add_(global|project)_* for include directories, even though all build targets support it as a kwarg, and it's used just as commonly if not more commonly than the depends kwarg, which does have such functions.

**Comment by xclaesse** [comment]
It is actually already there, but missing from documentation: https://github.com/mesonbuild/meson/pull/11203.

> On that note, we also have no equivalent of add_(global|project)_* for include directories, even though all build targets support it as a kwarg, and it's used just as commonly if not more commonly than the depends kwarg, which does have such functions.

There is a trick for that:
```
dep = declare_dependency(include_directories: 'foo')
add_project_dependencies(dep)
```

**Comment by LunarLambda** [comment]
I see, thank you!
