### ISSUE TITLE
i18n module doesn't help when merging back translations

### ISSUE THREAD

**Issue by hughsie** [mesonbuild/meson#1120]
At the moment we have to do:

    custom_target('desktop-file',
                  input: 'org.gnome.PowerStats.desktop.in',
                  output: 'org.gnome.PowerStats.desktop',
                  install: true,
                  install_dir: join_paths(get_option('datadir'), 'applications'),
                  command: [
                    msgfmt, '--desktop', '--template', '@INPUT@', '-d', podir, '-o', '@OUTPUT@'
                  ])

Which is pretty horrific for something that's going to be super common for desktop applications. It's also the same issue for AppData files, GSettings schema and lots of other file types.

**Comment by TingPing** [comment]
So just an idea for the API if anybody has some thoughts:

```
i18n.merge_file('org.gnome.PowerStats.desktop.in', # Should we care about output, or just drop .in?
    type: 'desktop', # or 'xml',
    po_dir: '../po', # bit ugly
    install: true,
    install_dir: get_option('datadir'),
)

**Comment by hughsie** [comment]
I think that is nearly perfect, but I think we do need input and output. Some people are going to be shipping meson and autotools build systems alongside each other for some time, and so the input file might actually be org.gnome.PowerStats.desktop.in.in. Or, it might be that the input file is called app.desktop (which is itself built from something else) and converted to com.mycompany.myapp.desktop when merging translations.

**Comment by TingPing** [comment]
Seems reasonable.

**Comment by hughsie** [comment]
Works perfectly, thanks!
