### ISSUE TITLE
nvcc fatal: Unknown option '-Wl,-O2'

### ISSUE THREAD

**Issue by rongcuid** [mesonbuild/meson#11234]
**Describe the bug**
Meson generates compile flags which NVCC does not recognize:

```
nvcc fatal   : Unknown option '-Wl,-O2'
ninja: build stopped: subcommand failed.
```

**To Reproduce**
`meson.build`:

```
project('test-cuda', 'cpp', 'cuda')

cuda_dep = dependency('cuda', version: '>=10')

src = files(
    'main.cpp',
)

executable('main', src, 
    dependencies: [cuda_dep])
```

`main.cpp`:

```c++
int main() { return 0; }
```

**Expected behavior**
Successful compile

**system parameters**
* Native build
* CentOS stream
* Python 3.9.15
* Meson 0.60.1
* Ninja 1.10.2

**Comment by rongcuid** [comment]
You need `-Xlinker` for specifying linker options in NVCC.

**Comment by eli-schwartz** [comment]
@obilaniu @SoapGentoo

**Comment by lucifer1004** [comment]
I think the linker prefix is correctly set at https://github.com/mesonbuild/meson/blob/3c0de471228420c333bb98be35a28705d0ec063d/mesonbuild/compilers/cuda.py#L56
but when trying to build a simple CUDA program, meson still uses `-Wl,` at the linking stage, even if I manually set `link_language` to `cuda`. I just wonder why.
