### ISSUE TITLE
No such build data file as ".../meson-private/build.dat" when running `meson test`

### ISSUE THREAD

**Issue by B4mbus** [mesonbuild/meson#11233]
**Describe the bug**
I'm toying with catch2 and meson. Everything compiles and links fine, but when I try to do `meson test`  I get:
```
ERROR: No such build data file as '/mnt/data/prv/dev/projects/repro/meson-private/build.dat'.
```

**To Reproduce**
Here's a simple repro https://github.com/B4mbus/repro

**Expected behavior**
I expect the tests to run

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
Plain native for   the same computer
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
Fedora Workstation 37
* what Python version are you using e.g. 3.8.0
3.11.1
* what `meson --version`
1.0.0
* what `ninja --version` if it's a Ninja build
1.11.1

**Comment by eli-schwartz** [comment]
Did you run `meson test` in the same directory you ran `ninja` in? Or else, pass the same `-C builddir/` argument to both `ninja` and `meson test`?

Because based on the name `projects/repro/meson-private/build.dat` it sounds like meson test is trying to run in the source directory.

**Comment by B4mbus** [comment]
> Did you run `meson test` in the same directory you ran `ninja` in? Or else, pass the same `-C builddir/` argument to both `ninja` and `meson test`?
> 
> Because based on the name `projects/repro/meson-private/build.dat` it sounds like meson test is trying to run in the source directory.

I ran `meson setup build`, then `meson compile -C build` and `meson test` from the root of the project which in this case is `repro`

**Comment by eli-schwartz** [comment]
Right, so then you should also run `meson test -C build/`.
