### ISSUE TITLE
Which python to use ?

### ISSUE THREAD

**Issue by kif** [mesonbuild/meson#11248]
**Describe the bug**
I wonder how to specify the `python`  to use when calling `meson setup` ? The wrong one is picked in my case.

**To Reproduce**
in a debian unstable chroot where both python 3.10 and 3.11 are installed inside the system. 
The current python is from a venv. so does meson and ninja.

**Expected behavior**
I would expect the one from the venv to be chosen, not a different one.

**system parameters**
```
(py310) /tmp/pyFAI$ which python
/tmp/pyFAI/py310/bin/python
(py310) /tmp/pyFAI$ python --version
Python 3.10.9
(py310) /tmp/pyFAI$ meson buildtest
The Meson build system
Version: 1.0.0
Source dir: /tmp/pyFAI
Build dir: /tmp/pyFAI/buildtest
Build type: native build
Project name: pyFAI
Project version: 2023.1.0a0
C compiler for the host machine: cc (gcc 12.2.0 "cc (Debian 12.2.0-13) 12.2.0")
C linker for the host machine: cc ld.bfd 2.39.90.20230104
Cython compiler for the host machine: cython (cython 0.29.32)
Host machine cpu family: x86
Host machine cpu: i686
Program cython found: YES (/usr/bin/cython)
Library m found: YES
Program python3 found: YES (/usr/bin/python3)
Found pkg-config: /usr/bin/pkg-config (1.8.0)
Run-time dependency OpenMP found: YES 4.5
C++ compiler for the host machine: c++ (gcc 12.2.0 "c++ (Debian 12.2.0-13) 12.2.0")
C++ linker for the host machine: c++ ld.bfd 2.39.90.20230104
```

* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
This is a 32-bit chroot on a 64 bit computer ... but it should not matter.

* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
Debian unstable

* what Python version are you using e.g. 3.8.0
Meson is installed into the venv, thus running python 3.10

* what `meson --version`
1.0

* what `ninja --version` if it's a Ninja build
1.11.1

**Comment by dnicolodi** [comment]
You can either install meson in the virtual environment, or use the `--native-file` meson option to pass a file containing the path to the Python interpreter you want to compile for, or you can use `meson-python` that handles all this for you.

**Comment by tristan957** [comment]
@eli-schwartz closeable?

**Comment by eli-schwartz** [comment]
Yes, this seems reasonable. If you're using a virtualenv you're probably either installing meson as a build-requires or using meson-python.
