### ISSUE TITLE
[UWP] Could not determine vs dep dependency prefix string

### ISSUE THREAD

**Issue by Neumann-A** [mesonbuild/meson#11257]
**Describe the bug**
thorvg fails to configure with: 
`ERROR: Could not determine vs dep dependency prefix string. output: b"Microsoft (R) C/C++ Optimizing Compiler Version 19.34.31937 for x64\r\nCopyright (C) Microsoft Corporation.  All rights reserved.\r\n\r\ncl : Command line error D8048 : cannot compile C file 'incdetect.c' with the /ZW option\r\n" b''`

cross file:
[meson-x64-uwp-dbg.log](https://github.com/mesonbuild/meson/files/10368128/meson-x64-uwp-dbg.log)
(due to #11143 all flags are passed via the compiler)
configure log:
[config-x64-uwp-dbg-out.log](https://github.com/mesonbuild/meson/files/10368132/config-x64-uwp-dbg-out.log)
meson log:
[config-x64-uwp-dbg-meson-log.txt.log](https://github.com/mesonbuild/meson/files/10368133/config-x64-uwp-dbg-meson-log.txt.log)

pixman for example works fine with the cross file so what is going on here?

**Comment by Neumann-A** [comment]
Ok what is going on here is that meson is using the wrong compiler flags to compile a `.c` file. It uses cxx instead of c .....

**Comment by Neumann-A** [comment]
To give more detail. The project thorvg is defined as a cpp project so meson uses the cpp flags for the detection but MSVC sees the `*.c` ending of the file and compiles it as a C file which won't work with the `/ZW` flag. As such meson should add `/TC` or `/TP` flag to inform MSVC how the file should be compiled or change the file ending according to the language it actually checks.

**Comment by eli-schwartz** [comment]
1) this is true and Meson does the same thing for GCC, passing `-x{lang}`
2) > (due to #11143 all flags are passed via the compiler)

    That's not what was said there. You should only put flags that are intrinsic to the compiler correctly identifying as the correct compiler -- instead you copied *all* c_args over, including stuff like `-W3 -DDEBUG -DWIN32` which do not contribute to making the compiler correctly identify as itself? For a GCC comparison, you would never define `CC='gcc -Wall -O3 -DDEBUG'` but you would keep `-specs /usr/lib/musl/lib/musl-gcc.specs` there, or `-m32` (for telling a multilib GCC on x86_64 to operate as an i686 compiler)


...

Aside: you do not need to add either /nologo or /utf-8 since Meson always adds both of those (you can stop Meson from using /utf-8 only by passing your own competing /source-charset).

**Comment by eli-schwartz** [comment]
I have posted a PR which should fix this. It checks the compiler language and ends up using incdetect.cpp instead of incdetect.c

**Comment by Neumann-A** [comment]
@eli-schwartz: To be clear: The flags are coming from CMake and the native/cross files are generated with the flags from CMake. From the description in https://www.reddit.com/r/cpp/comments/ztsabe/comment/j1jw013/?context=3 which is related to https://github.com/mesonbuild/meson/issues/11143 I need to pass all flags via the compiler to force them and not make the project overwrite them (furthermore I am not going to filter them just to make meson happy .... ). 
My current workaround is to hardcode `/TC|/TP` into `CMAKE_C|CXX_FLAGS` in the cmake toolchain and hopefully be done with it in meson. 

Be aware that I also applied:
```
--- a/meson.build
+++ b/meson.build
@@ -1,6 +1,6 @@
 project('thorvg',
         'cpp',
-        default_options : ['buildtype=debugoptimized', 'b_sanitize=none', 'werror=false', 'optimization=s', 'cpp_std=c++14'],
+        default_options : ['cpp_std=c++14'],
         version : '0.8.3',
         license : 'MIT')
```
to make thorvg even compile. Somehow the default_options 'buildtype=debugoptimized' (and maybe 'optimization=s' )took precedence over what vcpkg passes on the command line/native file, resulting in `/O1` being passed alongside with `/RTC` in debug builds which are incompatible.

**Comment by eli-schwartz** [comment]
You might be interested in always passing `-Dbuildtype=plain -Ddebug=false -Doptimization=plain` on the command line, to override any specified default options and suppress Meson adding any buildtype flags itself. This may be useful as a standard template for Meson projects, in fact.

> From the description in https://www.reddit.com/r/cpp/comments/ztsabe/comment/j1jw013/?context=3 which is related to #11143 I need to pass all flags via the compiler to force them and not make the project overwrite them

The project should not be overwriting cpp_args, but the native/cross files have less precedence compared to passing `-Dc_args=...` as a command-line option to `meson setup`.

Anyway, I am not overly concerned with where you define them :D but I do notice they seem to be getting passed twice, for the most part?

**Comment by eli-schwartz** [comment]
At any rate, if you have time to give #11259 a test run and see if that solves the problem for you, that would be neat. :)

**Comment by Neumann-A** [comment]
> `-Dbuildtype=plain -Ddebug=false -Doptimization=plain`

does `-Dbuildtype=plain -Ddebug=<somevalue>` not imply `-Doptimization=plain` ? I assumed so due to:
`WARNING: Recommend using either -Dbuildtype or -Doptimization + -Ddebug. Using both is redundant since they override each other. See: https://mesonbuild.com/Builtin-options.html#build-type-options`

> At any rate, if you have time to give https://github.com/mesonbuild/meson/pull/11259 a test run and see if that solves the problem for you, that would be neat. :)

Seems to work. Will add it as a patch to `vcpkg-tool-meson`. Still adding /TC, /TP in the toolchain because it might fix issues in other build scripts unrelated to meson.
