### ISSUE TITLE
exe_wrapper isn't used when passing a built executable as a generator

### ISSUE THREAD

**Issue by Kazade** [mesonbuild/meson#11264]
**Describe the bug**

I'm attempting to cross compile an application from Linux -> Windows. The cross compile config specifies that the build needs an exe_wrapper (wine). 

To build the project, meson first builds a number of small executable programs which then in turn generate source files, which are then compiled into the final program. In meson.build I achieve this by defining each executable, then using that executable in a generator(), before calling generator.process(). This works fine natively.

However, when cross-compiling the executables (which are Windows .exe files) are not being run with the exe_wrapper (wine) - they are attempting to run natively (which appears to try to use mono). 

**To Reproduce**

This is an example from my meson.build:

```
gendec = executable(
    'gendec',
    files('src/tools/gendec.c', 'src/tools/insparse.c', 'src/tools/actparse.c'),
    dependencies: glib_dep,
    include_directories: include_dirs
)
gen = generator(
    gendec,
    arguments: ['@CURRENT_SOURCE_DIR@/src/sh4/sh4.def', '@INPUT@', '--output=@OUTPUT@'], output: '@BASENAME@.c',
)

sources += gen.process(
    'src/sh4/sh4core.in',
    'src/sh4/sh4dasm.in',
    'src/sh4/sh4x86.in',
    'src/sh4/sh4stat.in',
    preserve_path_from: meson.current_source_dir()
)
```

The call to process() fails as meson attempts to run the executable as a native binary rather than through the exe_wrapper.

**Expected behavior**

If the build has an exe_wrapper, it should be used to run the executable through a generator.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?

Cross-build

* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)

Fedora 37

* what Python version are you using e.g. 3.8.0
3.11.1
* what `meson --version`
0.63.3
* what `ninja --version` if it's a Ninja build
1.10.2

**Comment by dcbaker** [comment]
I have a reproducing test case
