### ISSUE TITLE
Meson missing "build" help menu item

### ISSUE THREAD

**Issue by kuwv** [mesonbuild/meson#11272]
**Describe the bug**
The build subcommand is missing from both `meson --help` and `meson help build`. Other subcommands seem to function normally. The `meson build --help` also succeeds.

**To Reproduce**
`meson help build`

**Expected behavior**
Meson help menu should have all subcommands.

**system parameters**
* Help message
* MacOS
* Python 3.11.0
* Meson 0.64.1
* Ninja 1.11.1.git.kitware.jobserver-1

**Comment by dcbaker** [comment]
`build` isn't a command, when you type `meson build` what you're actually running is `meson setup build`, but for backwards compatibility reasons if your run `meson foo` and `foo` isn't a recognized subcommand, it's passed to `meson setup` as the first argument. That behavior is deprecated, and in the future if `foo` isn't a subcommand it will be an error.
