### ISSUE TITLE
Unity build documention could be improved

### ISSUE THREAD

**Issue by bruchar1** [mesonbuild/meson#11284]
I think the documentation page about "Unity builds" could be improved:

> Meson has built-in support for unity builds. To enable them, just pass --unity on on the command line or enable unity builds with the GUI.

- What is the GUI? Why not simply mention project options?
- In the "Built-in options" page, it says `unity` option can take the values `on`, `off`, `subprojects`. What is the meaning of `subprojects` for that option?
- `unity_size` option should be mentioned as well
- Although this is not specific to unity build, it could worth mentionning that the option can be overrided by target using `override_options`.

**Comment by eli-schwartz** [comment]
Meson doesn't even have a GUI, so this might have been referring to some unofficial and non-explained third-party project? Very confused myself.
