### ISSUE TITLE
Testcase 'common/51 pkgconfig-gen' fail on Fedora 23

### ISSUE THREAD

**Issue by arteymix** [mesonbuild/meson#1129]
https://copr-be.cloud.fedoraproject.org/results/arteymix/valum-framework/fedora-23-x86_64/00484246-meson/build.log.gz

I'll probably try to run it off Docker to see the actual error.

**Comment by ignatenkobrain** [comment]
wondering why people are building something for F23 since it will be EOL in 2 weeks.

**Comment by arteymix** [comment]
I guess it's better if I drop it then. Is is still worth investigating?

**Comment by jpakkane** [comment]
If it can't be reproduced on a newer Fedora, probably not.

**Comment by arteymix** [comment]
Closing this then. In the meantime, I'll try to target EPEL 7 ;)

**Comment by nirbheek** [comment]
I would like to see what failed and decide whether we should fix it or not. F23 might be exposing a bug that is valid elsewhere too. We can't know till we investigate the cause. Could you please try to get me a log anyway? I'll do the figuring out if you don't want to. :)

**Comment by arteymix** [comment]
@nirbheek Sure, I'm currently debugging EPEL 7 at this moment and I think that the testcase fail there as well.

**Comment by nirbheek** [comment]
Great, thank you!

**Comment by arteymix** [comment]
It's missing the `--validate` flag for `pkg-config`. It was introduced in `0.29` and Fedora 23 ships `0.28`. The same apply for EPEL 7.

**Comment by nirbheek** [comment]
So the fix is to do a `run_command` on `pkg-config`, check the version, and to not run the validate part of the test if it's too old.
