### ISSUE TITLE
Objective-c fails with: Compiler cc can not compile programs.

### ISSUE THREAD

**Issue by darkoverlordofdata** [mesonbuild/meson#11319]
**Describe the bug**
Objective-c fails with: Compiler cc can not compile programs.

**To Reproduce**
```
mkdir helloobjc
cd helloobjc
meson init --language=objc --name=helloobjc --version=0.1 --build
```

**Expected behavior**
I expect it to build and compile the project, ending with the line  This is the behavior when I substitute 'c' for 'objc'

Instead I get 
```
meson.build:1:0: ERROR: Compiler cc can not compile programs.
```

**system parameters**
just a plain native build (for the same computer)

* Ubuntu 22.04
* Python version 3.10.6
* meson --version 0.61.2
* ninja version  1.10.1-1
* GNUstep version 2.1
* clang version 14.0.0

When I use the GNUmakefile, it compiles with no errors.

**Comment by dcbaker** [comment]
Do you have gcc installed without objc support, by chance?

**Comment by darkoverlordofdata** [comment]
Thank you, that works. I was trying CC=clang and getting nowhere :)
