### ISSUE TITLE
gcc option -Werror=format-security not handled correctly

### ISSUE THREAD

**Issue by yt87** [mesonbuild/meson#11329]
**Describe the bug**

Meson setup falsely labels ``-Werror=format-security`` as unhandled by gcc.

**To Reproduce**
The compiler recognises the option correctly:
```
$ cat foo.c 
#include <stdio.h>

int main(int ac, char **av)
{
    char c = 'a';
    printf(&c);
    return 0;
}
$ cc -Wformat -Werror=format-security foo.c 
foo.c: In function 'main':
foo.c:7:12: error: format not a string literal and no format arguments [-Werror=format-security]
    7 |     printf(&c);
      |            ^~
cc1: some warnings being treated as errors
```
Meson build file:
```
$  cat meson.build
project('foo', 'c', version: '0.0.0', default_options: ['warning_level=0'])

cc = meson.get_compiler('c')
_global_c_args = cc.get_supported_arguments(
  '-Wformat',
  '-Werror=format-security',
)
add_project_arguments(_global_c_args, language: 'c')

executable('foo', 'foo.c')
```
The output
```
$ meson setup --wipe bar
The Meson build system
Version: 1.0.0
Source dir: /tmp
Build dir: /tmp/bar
Build type: native build
Project name: foo
Project version: 0.0.0
C compiler for the host machine: cc (gcc 12.2.0 "cc (conda-forge gcc 12.2.0-19) 12.2.0")
C linker for the host machine: cc ld.bfd 2.39
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -Wformat: YES 
Compiler for C supports arguments -Werror=format-security: NO 
Build targets in project: 1

Found ninja-1.11.0 at /mnt/sdb1/home/george/miniforge3/envs/py310/bin/ninja

$  meson compile -v -C bar
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /mnt/sdb1/home/george/miniforge3/envs/py310/bin/ninja -C /tmp/bar -v
ninja: Entering directory `/tmp/bar'
[1/2] cc -Ifoo.p -I. -I.. -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -O0 -g -Wformat -MD -MQ foo.p/foo.c.o -MF foo.p/foo.c.o.d -o foo.p/foo.c.o -c ../foo.c
[2/2] cc  -o foo foo.p/foo.c.o -Wl,--as-needed -Wl,--no-undefined
```
I also tried this, maybe it will provide a hint:
```
$ cc -Werror=format-security foo.c
cc1: error: '-Wformat-security' ignored without '-Wformat' [-Werror=format-security]
cc1: some warnings being treated as errors
$ echo $?
1
```

**Comment by eli-schwartz** [comment]
> Returns an array containing only the arguments supported by the compiler, as if [compiler.has_argument()](https://mesonbuild.com/Reference-manual_returned_compiler.html#compilerhas_argument) were called on them individually.

In this case, however, to correctly check whether this compiler argument is supported you cannot use has_argument. You need to use this:

> **[compiler.has_multi_arguments()](https://mesonbuild.com/Reference-manual_returned_compiler.html#compilerhas_multi_arguments)**
>
> the same as [compiler.has_argument()](https://mesonbuild.com/Reference-manual_returned_compiler.html#compilerhas_argument) but takes multiple arguments and uses them all in a single compiler invocation.

**Comment by eli-schwartz** [comment]
> I also tried this, maybe it will provide a hint:

Note: there is a debug log in `bar/meson-logs/meson-log.txt` which includes reporting on the exact tests used to determine whether "Compiler for C supports arguments".

It should confirm your test.

**Comment by yt87** [comment]
Thanks, I tried 
```
_global_c_args = cc.has_multi_arguments('-Wformat', '-Werror=format-security',)
```
The log shows arguments are supported, now I have to figure out how to write an equivalent ``get_supported_arguments``:
```
Compiler for C supports arguments -Wformat -Werror=format-security: YES 

meson.build:10:0: ERROR: add_project_arguments argument 1 was of type "bool" but should have been "str"
```
A combination of ``foreach`` and ``if`` statements, or there is a better way? I am new to meson.
