### ISSUE TITLE
`test cases/failing/111 empty fallback` fails if cmake is not available

### ISSUE THREAD

**Issue by NickCao** [mesonbuild/meson#11320]
**Describe the bug**
Despite that meson allows running `run_project_tests.py` without cmake, `test cases/failing/111 empty fallback` specifically fails if cmake is not available, as it expects the string `tried pkgconfig and cmake` to be in stdout.

**To Reproduce**
Test meson with `run_project_tests.py` as normal, only that ensuring cmake is not available to meson.

**Expected behavior**
Tests pass, the cmake related tests are skipped.

**system parameters**
* what `meson --version` 1.0.0

**Comment by eli-schwartz** [comment]
Thanks for the report -- our CI tests obviously install cmake for full test coverage so we neglected to notice this...

The test definitions allow specifying an expected string with regular expressions, so this is easy to fix. See my linked PR.
