### ISSUE TITLE
can we we have macOS packages  for 1.0 (none since 0.63.1)

### ISSUE THREAD

**Issue by fduncanh** [mesonbuild/meson#11339]
the meson .pkg file for macOS stopped being in Releases after 0.63.1

other methods (pip3 etc) dont work properly on macOS, so it would be very
good to have these .pkg here,

I'm going to have to use 0.63.1  instead of 1.00   :(

**Comment by jpakkane** [comment]
The problem here is that I no longer have an Intel mac, so producing the installer is tricky (most macs are still Intel and that binary should work on aarch64, too). But I'll try to get it done somehow.

**Comment by fduncanh** [comment]
Thank you!
