### ISSUE TITLE
Can't use zig c or c++ compilers

### ISSUE THREAD

**Issue by ThatNerdUKnow** [mesonbuild/meson#11340]
**Describe the bug**
I am trying to write a wrapper library around two other libraries. Let's say libfoo and libbar.  
Let's say libfoo doesn't compile using msvc but does compile with gcc and g++
and let's say libbar doesn't compile using gcc and g++ but doesn't compile with msvc.
Being able to compile for multiple platforms is a concern of mine.

I thought, why not use the zig compiler as a cross platform compiler?

the problem is that I can't use `zig cc` or `zig c++` as compiler backends for meson

**To Reproduce**
native file:
```ini
[binaries]
c = 'zig cc'
cpp = 'zig c++'
```

output:
```
  meson.build:1:0: ERROR: Unknown compiler(s): [['zig cc']]
  The following exception(s) were encountered:
  Running "zig cc --version" gave "[WinError 2] The system cannot find the file specified"
```
**Expected behavior**
I would expect that zig cc would be executed as its own command?
Like typing `zig cc --version` manually emits the following: 
```
clang version 15.0.7 (https://github.com/ziglang/zig-bootstrap a3a6e85f9ec95b1772f5ace363e46df2f336c6b8)
Target: x86_64-unknown-windows-gnu
Thread model: posix
InstalledDir: C:/msys64/mingw64/bin
```
but zig cc --version within meson yields the results above

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? no
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) windows 10
* what Python version are you using 3.10.5
* what `meson --version` 0.62.1
* what `ninja --version` if it's a Ninja build 1.10.2

here's the meson.build file of the library I depend on and am attempting to build from source:
```meson
project('libvmaf', ['c', 'cpp'],
    version : '2.3.1',
    default_options : ['c_std=c11',
                       'cpp_std=c++11',
                       'warning_level=2',
                       'buildtype=release',
                       'default_library=both',
                      ],
    meson_version: '>= 0.47.0')

vmaf_soname_version       = '1.1.3'
vmaf_api_version_array    = vmaf_soname_version.split('.')
vmaf_api_version_major    = vmaf_api_version_array[0]
vmaf_api_version_minor    = vmaf_api_version_array[1]
vmaf_api_version_revision = vmaf_api_version_array[2]

libvmaf_src_root = meson.current_source_dir()
cc = meson.get_compiler('c')
libvmaf_inc = include_directories(['include'])

# Arguments in test_args will be used even on feature tests
test_args = []
if host_machine.system() == 'linux'
    test_args += '-D_GNU_SOURCE'
    add_project_arguments('-D_GNU_SOURCE', language: 'c')
elif host_machine.system() == 'darwin'
    test_args += '-D_DARWIN_C_SOURCE'
    add_project_arguments('-D_DARWIN_C_SOURCE', language: 'c')
else
    test_args += '-D_POSIX_C_SOURCE=200112L'
    add_project_arguments('-D_POSIX_C_SOURCE=200112L', language: 'c')
endif

# Header checks
stdatomic_dependency = []
if not cc.check_header('stdatomic.h')
    if cc.get_id() == 'msvc'
        # we have a custom replacement for MSVC
        stdatomic_dependency = declare_dependency(
            include_directories : include_directories('src/compat/msvc'),
        )
    elif cc.compiles('''int main() { int v = 0; return __atomic_fetch_add(&v, 1, __ATOMIC_SEQ_CST); }''',
                     name : 'GCC-style atomics', args : test_args)
        stdatomic_dependency = declare_dependency(
            include_directories : include_directories('src/compat/gcc'),
        )
    else
        error('Atomics not supported')
    endif
endif

subdir('include')
subdir('src')
subdir('tools')
subdir('doc')
subdir('test')
```

**Comment by eli-schwartz** [comment]
> the problem is that I can't use `zig cc` or `zig c++` as compiler backends for meson

The immediately apparent problem is that in your machine file, you specified the binary for c as a string containing two words. The native file supports arrays, and defining program binaries takes advantage of that for reliability -- is a space inside a single string supposed to be two shell words, or is it supposed to be a single command that has a space in it? On Windows, for example, it is common that it's a single command with a space in it.

So:
```ini
[binaries]
c = ['zig', 'cc']
```

is the correct way to define this.

For the traditional environment variable `$CC`, we assume it's intended as an array, and split on whitespace, because there is no way to distinguish between the two and it is most commonly intended as an array of arguments.

**Comment by eli-schwartz** [comment]
Note: I have not tested zig cc to see if it works, but the above advice may get it to work. I think it probably should work, because `zig cc --version` identifies as a variant of clang and we definitely support that.

**Comment by ThatNerdUKnow** [comment]
Let me give that a whack, I've only really given a cursory glance at the meson documentation as it's not the build system of my project per se but the library I want to use isn't distributed anywhere and the only way to use it is to compile from source but I digress

I'll make those changes, and share what comes out of it

**Comment by ThatNerdUKnow** [comment]
I ended up with lots of warnings and a few errors:
```
fatal error: 'pthread.h' file not found
  #include <pthread.h>
           ^~~~~~~~~~~
```

At this point I don't think this is so much of a meson problem than it is a zig problem. I really appreciate your help though! I never would have figured that out

**Comment by eli-schwartz** [comment]
Absolutely, happy to help! (That is why we are here, after all.)

And good to know that zig cc works in principle.
