### ISSUE TITLE
QEMU 7.2.0 - make install fail

### ISSUE THREAD

**Issue by CliveBaker32** [mesonbuild/meson#11347]
QEMU 7.2.0 - make install fail

**Host environment**

    Operating system: CentOS Stream 8
    OS/kernel version: 4.18.0-448.el8.x86_64
    Architecture: x86_64
    QEMU flavor: source code from https://www.qemu.org/download/#source
    QEMU version:  7.2.0
    QEMU command line:  make install

**Description of problem**

`[10055/10057] Generating docs/QEMU manual with a custom command [10056/10057] Generating docs/QEMU man pages with a custom command [10056/10057] Installing files. Traceback (most recent call last): File "/home/clive/.local/bin/meson", line 5, in <module> from mesonbuild.mesonmain import main ModuleNotFoundError: No module named 'mesonbuild' FAILED: meson-internal__install  /home/clive/.local/bin/meson install --no-rebuild ninja: build stopped: subcommand failed. make: *** [Makefile:165: run-ninja] Error 1 [clive@localhost build]$  
`

**Steps to reproduce**

    as user in shell
    wget https://download.qemu.org/qemu-7.2.0.tar.xz
    tar xvJf qemu-7.2.0.tar.xz
    cd qemu-7.2.0
    ./configure
    make install

**Additional information**

installed meson via **pip3 --user**

`pip3 --list` Output **meson version 1.0.0**

**Using** - python version 3.11.1

**ninja-build** installed via package manager `dnf`

**Using** - ninja-build version 1.8.2

Used `dnf builddep` on `ninja-build`, `meson`, and `qemu-kvm` before and after installation confirming I have dependencies.

**File "/home/clive/.local/bin/meson" contains**

```
#!/usr/local/bin/python3.11
# -*- coding: utf-8 -*-
import re
import sys
from mesonbuild.mesonmain import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())


```

**Comment by eli-schwartz** [comment]
> installed meson via **pip3 --user**

https://mesonbuild.com/Getting-meson.html#installing-meson-with-pip

The problem here is that pip with the `--user` flag installs software that only runs as the "user". Meson is an example of software that is frequently run as something other than the user -- i.e. the install stage usually has to run as root, and root did not install Meson.

Note: qemu tries to solve this by version-checking for Meson and using an internal copy, so this may work for you instead.

**Comment by CliveBaker32** [comment]
@eli-schwartz Thank you!
I fix this with what you said and linked. For future references here is what I did. Uninstall meson as it was installed by user. reinstall meson as root. Delete build directory as make install won't work as make install would look for something that's not there and sudo make install wouldn't work at all. I made build directory, reconfigured , and used make then sudo make install. 
```
pip3 uninstall meson
sudo pip3 install meson
rm -vfr build
mkdir build 
../configure
make 
sudo make install
```

**Comment by Elmootez-Belleh** [comment]
This link will help you to solve your problem:
https://zhuanlan.zhihu.com/p/642830339

**Comment by Elmootez-Belleh** [comment]
This will resolve the issue : 
Make shure you have already installed:
`
sudo apt-get install libglib2.0-0 libglib2.0-dev
sudo apt install libpixman-1-0 libpixman-1-dev
sudo apt install flex
sudo apt install bison

cd qemu/build/
sudo ../configure
`
you will probably face this error :  cannot find ninja
in this case : 
download this package maually : git clone git://github.com/ninja-build/ninja.git
`
unzip ninja-master.zip
cd ninja-master
./configure.py --bootstrap
cp ninja /usr/bin/
cd ~/qemu/build/
sudo make -j3
sudo make install
`

**Comment by eli-schwartz** [comment]
Please refrain from posting ChatGPT output on old, closed tickets.
