### ISSUE TITLE
`python.extension_module()` doesn't accept `.pyx` custom targets

### ISSUE THREAD

**Issue by tristan957** [mesonbuild/meson#11351]
**Describe the bug**

```
../subprojects/hse-python/hse3/meson.build:155:4: Exception: No host machine compiler for 'hse.pyx'
```

**To Reproduce**

https://github.com/hse-project/hse-python

**Expected behavior**

Accept custom targets ending in `.pyx`.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? Native build
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) Fedora 37
* what Python version are you using 3.11
* what `meson --version` 0.63.3
* what `ninja --version` if it's a Ninja build 1.10.2

**Comment by tristan957** [comment]
Also tried on master.

**Comment by dnicolodi** [comment]
Are you sure? This https://github.com/dnicolodi/python-siphash24/blob/master/meson.build works for me.

**Comment by tristan957** [comment]
Oh. I think this is because I only add Cython for the build machine and not the host machine. Let's see if I depend on Meson >= 0.64

**Comment by tristan957** [comment]
Yeah that works. @dcbaker since you reviewed my Cython+Vala always use the build machine PR, do you think there is anything to do here? Otherwise it could probably be closed.
