### ISSUE TITLE
ERROR: cmd was a built executable but not found in overrides table

### ISSUE THREAD

**Issue by igo95862** [mesonbuild/meson#11382]
**Describe the bug**
While trying to use `configure_file` using the `executable` as command I recieved the following error:

```
Configuring namespace_constants.json with command

src/namespaces_constants/meson.build:11:0: ERROR: cmd was a built executable but not found in overrides table

    This is a Meson bug and should be reported!
```

**To Reproduce**

I pushed the code that causes the bug to a separate branch:

https://github.com/igo95862/bubblejail/tree/meson-bug

This is the exact file that causes the bug:

https://github.com/igo95862/bubblejail/blob/meson-bug/src/namespaces_constants/meson.build

**Expected behavior**

Configuring file from an executable would not cause the bug.

**system parameters**
* Native build
* Arch Linux
* Python 3.10.9
* Meson 1.0.0
* Ninja 1.11.1

**Comment by xclaesse** [comment]
This is expected, configure_file() needs to execute the command at configure time, before your executable has been compiled. If you want to run the command at build time, use custom_target() instead.

**Comment by igo95862** [comment]
> This is expected, configure_file() needs to execute the command at configure time, before your executable has been compiled. If you want to run the command at build time, use custom_target() instead.

Maybe it shouldn't say `This is a Meson bug and should be reported!`

but rather say `configure_file() needs to execute the command at configure time`

**Comment by xclaesse** [comment]
> Maybe it shouldn't say `This is a Meson bug and should be reported!`

Oh, you're totally right!

**Comment by jscott0** [comment]
I got bit by this bug and can reproduce it like this:
```
project('test')
run_command(executable('Test', 'meson.build'))
```

I will try the proposed fix, but does anyone know of a workaround in the meantime?
