### ISSUE TITLE
type UserFeatureOption does not support the bool() operator

### ISSUE THREAD

**Issue by milahu** [mesonbuild/meson#11381]
this works

```meson
some_dep = dependency('some_name', required: get_option('some_option'))
```

this fails

```meson
some_dep = dependency('some_name', required: false)
if get_option('some_option') and not some_dep.found()
#  ^ error
  error('please install some_name from some_where')
endif
```

> ```meson.build:287:3: ERROR: Object <[FeatureOptionHolder] holds [UserFeatureOption]: <mesonbuild.coredata.UserFeatureOption object at 0x7ffff5eb3760>> of type UserFeatureOption does not support the `bool()` operator.```

considering that the `required` keyword accepts type `bool | feature`
there should be a cast from feature to bool

## workaround

check if the option is enabled

```meson
if get_option('some_option').auto()
  error('option "some_option" cannot be "auto", must be either "enabled" or "disabled"')
endif
some_dep = dependency('some_name', required: false)
if get_option('some_option').enabled() and not some_dep.found()
  error('please install some_name from some_where')
endif
```

## alternatives

try/catch to enrich the error

```meson
try
  some_dep = dependency('some_name', required: get_option('some_option'))
catch(e)
  error(e + '\n' + 'please install some_name from some_where')
endtry
```

## sources

https://github.com/mesonbuild/meson/blob/7186279ffaf8b5827d5ba4eedbe9249bc48f82c7/docs/yaml/functions/dependency.yaml#L157-L158

```
$ find . -name "*.yaml" | xargs -d '\n' grep -Hn -A3 "required" | grep -F -B1 'type: bool | feature'
./docs/yaml/functions/subproject.yaml:60:  required:
./docs/yaml/functions/subproject.yaml-61-    type: bool | feature
--
./docs/yaml/functions/find_program.yaml:66:  required:
./docs/yaml/functions/find_program.yaml-67-    type: bool | feature
--
./docs/yaml/functions/import.yaml:20:  required:
./docs/yaml/functions/import.yaml-21-    type: bool | feature
--
./docs/yaml/functions/dependency.yaml:157:  required:
./docs/yaml/functions/dependency.yaml-158-    type: bool | feature
--
./docs/yaml/objects/compiler.yaml:136:    required:
./docs/yaml/objects/compiler.yaml-137-      type: bool | feature
--
./docs/yaml/objects/compiler.yaml:366:    required:
./docs/yaml/objects/compiler.yaml-367-      type: bool | feature
```

**Comment by milahu** [comment]
problem: the `auto` value does not map to bool

https://github.com/mesonbuild/meson/blob/7186279ffaf8b5827d5ba4eedbe9249bc48f82c7/mesonbuild/coredata.py#L286-L301

**Comment by xclaesse** [comment]
3 states cannot be casted to 2 states. I'm not sure what you are trying to achieve here. If you want to report the error for missing dep yourself, do it like that:

```meson
if not get_option('some_option').disabled()
  some_dep = dependency('some_name', required: false)
  if get_option('some_option').enabled() and not some_dep.found()
    error()
  endif
endif
```

But best is just to let Meson report the error: `some_dep = dependency('some_name', required: get_option('some_option'))`

**Comment by milahu** [comment]
> If you want to report the error for missing dep yourself

yes, that was my idea

would be interesting how all these functions handle `get_option('some_option').auto()` ...
but for now im happy with the workaround &rarr; closing

**Comment by eli-schwartz** [comment]
The entire point of feature options is to allow some functions to accept them directly and handle ***all*** the logic involved, including required/optional/disabled and error message generation.


Maybe you want

```meson
dependency('some_name', required: get_option('some_option'), not_found_message: 'please install some_name from some_where')
```

If not, then you need to use custom handling of all three potential values of this tristate option. This isn't a "workaround", just the unfortunate nature of not having built-in support for whatever you're trying to do.

**Comment by milahu** [comment]
> not_found_message

aah! sorry im blind .__.

note to future: read the [manual](https://mesonbuild.com/Reference-manual_functions.html#dependency)
