### ISSUE TITLE
Issues following Tutorial

### ISSUE THREAD

**Issue by Adobe-Android** [mesonbuild/meson#1138]
I'm having issues with the gtk+ dep on Fedora 25. Yes, I did install gtk+.
Output:
Native dependency gtk+-3.0 not found.
FAILED: build.ninja
'/usr/bin/python3' '/usr/bin/meson' --internal regenerate '/home/vm/Projects/hello_world' '/home/vm/Projects/hello_world/buil
d' --backend ninja
ninja: error: rebuilding 'build.ninja': subcommand failed

Also to note: You use ninja-build now instead of just the ninja command.

**Comment by QuLogic** [comment]
> Yes, I did install gtk+.

But did you install `gtk3-devel`?

**Comment by TingPing** [comment]
Protip: `dnf install 'pkgconfig(gtk+-3.0)'`, since meson relies upon `pkg-config` for its deps that should work for everything.

**Comment by Adobe-Android** [comment]
Thanks for the tips from the both of you! Pkg-config was already installed so it was the -devel package I forgot about.

**Comment by a-eid** [comment]
how to resolve this issue on ubuntu ?

**Comment by TingPing** [comment]
@a-eid `libgtk-3-dev`
