### ISSUE TITLE
add try/catch block

### ISSUE THREAD

**Issue by milahu** [mesonbuild/meson#11394]
try/catch blocks are useful to make failing tests faster, by putting more tests in one meson.build file
see also https://github.com/mesonbuild/meson/pull/11375#issuecomment-1428239591

```meson
print('test: dependency should throw')
try
  some_dep = dependency('some_name')
  assert(false)
catch(e)
  assert(e.message == 'the dependency "some_name" was not found')
endtry
```

try/catch blocks could replace the `not_found_message` keyword
see also #11381 

```meson
try
  some_dep = dependency('some_name', required: get_option('some_option'))
catch(e)
  error(e.message + '\n' + 'please install some_name from some_where')
endtry
```

generally, a language with exceptions should have try/catch blocks, because not all exceptions are fatal

question is, how "simple" should meson be?

**Comment by bilhox** [comment]
Hi I'm passing here because I was looking if try catch statement exist in meson. I can see this issue is closed but how was it implemented then ?

**Comment by eli-schwartz** [comment]
You can do `testcase expect_error('XXXX')` but it's only for writing meson's own internal unittests, where we want to determine whether meson sometimes fails.

If you are building a project, you should just use `required: false` for situations where you want to find a dependency or something and a missing dependency should not be fatal.

**Comment by bilhox** [comment]
It was actually for printing a more elaborated error message.

**Comment by dcbaker** [comment]
@bilhox: what about:
```meson
dep_foo = dependency('foo', required : false)
if not dep_foo.found()
    error('Here is my more comprehensive message about what to do if `foo` is not found')
endif
```
