### ISSUE TITLE
Allow passing GeneratedList to generator.process

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#1141]
Sometimes you want to chain two generators one after the other; for instance while building assembly with MSVC, you need to use `ml.exe` but it doesn't do pre-processing, so you need to call `cl.exe /EP /P /Fi@OUTPUT@ @INPUT@` to do the pre-processing, and then pass it to `ml.exe /Fo @OUTPUT@ /c @INPUT@` to get compiled object code which can be added as sources to an `executable` or `library`.

This is not trivial to do (I tried) but shouldn't be too difficult. Also implementing it on the Visual Studio backend has the same problem that is causing the `113 generatorcustom` test to fail there.

This is needed for building libffi with Meson without resorting to a wrapper script.

**Comment by msink** [comment]
File objects too - if generator is defined in submodule - paths are relative to that submodule.

`bin2c.process('../../hello.zip')` - works

`bin2c.process(files('hello.zip'))` - syntax error

**Comment by randy408** [comment]
Any updates on this? Wrapper scripts are not trivial to write when e.g. subproject executables are involved in a compilation chain.

**Comment by quackersan** [comment]
Same here. I needed to preprocess some ASM files which include C headers, then pass the generated ASM sources to the ASM generator. Now it doesn't work. Could be done with custom_targets but not clean.

**Comment by Volker-Weissmann** [comment]
Same here. I'm using gnu m4 and  [lemon](https://en.wikipedia.org/wiki/Lemon_(parser_generator)). Unfortuantely

`lemongen.process(m4gen.process('myfile'))`

fails with

`ERROR: Generator arguments must be strings or files not <GeneratedListHolder: ['myfile']>.`

**Comment by vinipsmaker** [comment]
I stumbled upon this issue while trying to consume the output of `gperf` as input for `re2c` before finally using the generated sources to build an executable.

**Comment by vinipsmaker** [comment]
What I wanted to do:

```
gperf_gen.process(re2c_gen.process(re2c_src))
```

What I had to do thanks to Meson's limitation regarding non-chainable generators:

```
pp_state = custom_target(
    'bc2_state.cpp',
    output : 'bc2_state.cpp',
    input : re2c_gen.process('src/state.ypp'),
    command : [
        emilua_gperf,
        '--assign', 'GPERF_BIN=' + find_program('gperf').full_path(),
        '@INPUT@', '@OUTPUT@',
    ],
)
```

Full example: https://gitlab.com/emilua/emilua/-/blob/39a7b1299335ca84260f6fae7613b804d087a141/meson.build
