### ISSUE TITLE
`exclude_files` argument to `install_subdir()` should be recorded in `intro-install_plan.json`

### ISSUE THREAD

**Issue by dnicolodi** [mesonbuild/meson#11426]
The expectation is that `intro-install_plan.json` maps source or build artifacts file paths to installation paths containing destination path placeholders. When `install_subdir()` is used without the `exclude_files` or `exclude_dirs` arguments, the files are copied from the source tree to the installation path, thus `intro-install_plan.json` should contain an entry for the subdirectory path in the source tree. However, when either `exclude_files` or `exclude_dirs` are used, a copy of the subdirectory minus the excluded items is created in the build directory and the installation proceeds from there. Therefore, intro-install_plan.json` should contain an entry for the subdirectory path in the build directory.

EDIT: my understanding was very wrong. I updated the issue's title to point to what is really missing. See below for details.

**Comment by eli-schwartz** [comment]
That doesn't sound right at all. excludes are passed down to the installdata and evaluated by `meson install` directly. The entire point of install_subdir is that it's very loose and just does "whatever" at install time. We certainly cannot evaluate the pattern at configure time and copy files to the build directory, because if so those would go out of date.

**Comment by dnicolodi** [comment]
You are right. I was confused by the statements in this bug report https://github.com/mesonbuild/meson-python/issues/317

**Comment by dnicolodi** [comment]
is there a way to get a list of the excluded files via introspection ans without running `meson install` and comparing the source tree with the installed tree?

**Comment by FFY00** [comment]
@eli-schwartz how easy would it be to extract the matching logic? If it's not very hard, we could add a ninja target to update the affected metadata? Not sure how much of an overkill that'd be, though.

Actually, I am a bit confused at how this is implemented, as `ninja` would be the one doing the installation, and AFAIK it does not provide any way to implement matching logic like this.

**Comment by dnicolodi** [comment]
@FFY00 `ninja install` just calls `meson install --no-rebuild`

**Comment by eli-schwartz** [comment]
> @eli-schwartz how easy would it be to extract the matching logic? If it's not very hard, we could add a ninja target to update the affected metadata? Not sure how much of an overkill that'd be, though.

The install_plan is generated in `mesonbuild/mintro.py` by looping over the members of a `backends.InstallData`:
```
    for key, data_list in {
        'data': installdata.data,
        'man': installdata.man,
        'headers': installdata.headers,
        'install_subdirs': installdata.install_subdirs
    }.items():
```

installdata.install_subdirs is a `backends.SubdirInstallData` instance.

`minstall.Installer` does the same thing, except that SubdirInstallData is parsed by `Installer.install_subdirs` and processes the `SubdirInstallData.exclude` attribute in do_copydir().

**Comment by dnicolodi** [comment]
Would it make sense and be possible to record the excluded files and dirs in an "exclude" attribute attached to the entry in `intro-install_plan.json`?

**Comment by eli-schwartz** [comment]
PRs welcome :) the install_plan.json primarily exists to do what meson-python wants/needs it to do, so I'll probably usually defer to your judgment in that regard and mostly just review it based on code correctness and CI conformance rather than what I think it's supposed to look like.

**Comment by FFY00** [comment]
Sorry, I still don't understand properly. Could you clarify where the matching logic happens, and if its result is stored anywhere?

**Comment by dnicolodi** [comment]
First, there is no matching AFAIK, `exclude_files` and `exclude_dirs` take path arguments, not patterns, at least accordingly to the documentation https://mesonbuild.com/Reference-manual_functions.html#install_subdir The code that does the copying is responsible for skipping over the excluded files or directories. The items to skip are stored along the other information needed to install the project in `$build/meson-private/install.dat`.

**Comment by eli-schwartz** [comment]
Right, if you want to read the pickled install.dat internals then you are welcome to do so but you also get to keep both pieces when that gets refactored out from under you someday. :) The json files should generally be preferred.
