### ISSUE TITLE
suggestion for some rust cfg handling in meson

### ISSUE THREAD

**Issue by karolherbst** [mesonbuild/meson#11438]
At the moment meson doesn't add any cfg entries itself. Generally I think this is the right approach, but meson does have `b_ndebug` as a core options which can fundamentally affect APIs.

To have it better integrated with `bindgen` + rust targets I'd say meson should add a `--cfg ndebug` (or NDEBUG to match C more closely) on its own, so project do not have to deal with this themselves, because let's face it, checking if `NDEBUG` gets set or not isn't done with a trivial if clause in meson as far as I know.

The main reason for this being important is, that projects might flip some symbols between being a proper function or a simple `static inline` stub, so projects might want to gate certain rust code behind a `#[cfg(not(ndebug))]` so they do not have to deal with the `static inline` `bindgen` situation for those symbols.

**Comment by eli-schwartz** [comment]
Semantically this seems like a reasonable match, because this core option is implemented in C/C++ as a macro toggle but for rust the general system for that is cfg. There aren't a lot of options where this sort of thing is applicable.. it's probably okay to limit it to ndebug.

**Comment by eli-schwartz** [comment]
@dcbaker, this is solved by #11441?

**Comment by dcbaker** [comment]
No, I noticed that while looking at this. Rust has a `debug_assertion!()` that's more like C's `assert()`, and we should toggle that. I have a followup for this issue

**Comment by dcbaker** [comment]
@karolherbst just to be clear, this is an option you want for a rust target that includes or links with a bindgen target, right?

**Comment by karolherbst** [comment]
@dcbaker it probably makes sense to enable it for all targets, but yeah, that was my intention at least.

**Comment by karolherbst** [comment]
I'm now wondering if #11441 is indeed enough for this use case. If I can successfully enable/disable the code via `cfg!(debug_assertions)` or `#[cfg(debug_assertions)]` that would be good enough. Just needs proper documentation on mesons side so developers are aware of this I guess.

**Comment by karolherbst** [comment]
@dcbaker I can confirm that #11441 would be enough to solve the situation if meson makes sure that `debug_assertions` and `NDEBUG` are always enabled at the same time, which seems to be the case.

It's unfortunate the name doesn't match, but I think adjusting the documentation and what `meson configure` prints should be good enough here.

**Comment by karolherbst** [comment]
Oh, one thing which need to change is to pass `-DNDEBUG` to bindgen targets.

**Comment by dcbaker** [comment]
I updated 11441 to add -DNDEBUG to bindgen targs in the C args (I already had that patch). I'd kinda like to replace `b_ndebug` with `b_asserts` or `b_debug_asserts` or similiar. I think we have the mechanisms in place to make that work pretty easily now, actually.

**Comment by karolherbst** [comment]
@dcbaker looks like it all just works with your current branch :) Was able to drop my meson.build patch entirely now.
