### ISSUE TITLE
In-Depth Tutorial Clarification

### ISSUE THREAD

**Issue by Adobe-Android** [mesonbuild/meson#1146]
Needs further description to understand what you are supposed to be doing and to what file. Is there a good place I can ask these questions other than here? Everything makes sense until. 
_____________________________________________________________________
The first subdirectory we go into is include. In it we have a a header file for the library that we want to install. This requires one line.

install_headers('foolib.h')

**Comment by Adobe-Android** [comment]
Once I figure this stuff out, I'd like to make YouTube tutorials following them to help those in the future.

**Comment by TingPing** [comment]
>  Is there a good place I can ask these questions other than here? 

ircs://chat.freenode.net/mesonbuild

**Comment by Adobe-Android** [comment]
Thanks @TingPing
