### ISSUE TITLE
Property `patch_filename` with `wrap-git` for local patches

### ISSUE THREAD

**Issue by mtribiere** [mesonbuild/meson#11480]
Currently the `patch_filename` property to specify a local patch is only available for `wrap-file`. It would be nice to have it available with `wrap-git` as well.

**Comment by xclaesse** [comment]
I'm pretty sure it work with wrap-git too. Which version of meson are you using and what error do you get?

**Comment by xclaesse** [comment]
If you mean apllying  .patch files, you should use diff_files.

**Comment by mtribiere** [comment]
Here is an example of my wrap file:

```
[wrap-git]
url = http://example.com/myrepo.git
revision = 0000333_PROD
depth = 1

patch_filename = myLocalPatch.zip
```

With this configuration, the patch should be pulled from the local filesystem rather than online. It does work with ``[wrap-file]``, however with ``[wrap-git]`` the patch parameter just gets ignored. 

I'm using Meson 1.0.1.

**Comment by xclaesse** [comment]
I'm pretty sure it works, please double check:
- myLocalPatch.zip must be in subprojects/packagefiles/
- myLocalPatch.zip should contain as root dir "myrepo"

**Comment by mtribiere** [comment]
Just understood what was going on, Meson extract patches in the subproject folder directly. It's a little confusing considering you're trying to apply a patch for a specific subproject. 

To me it would make more sense to extract it in the subproject folder because like this, any patch made for a project could pollute another subprojects.

**Comment by xclaesse** [comment]
I would not recommend using `patch_filename` and `patch_url`, they are really made for WrapDB. Better use `patch_directory` or `diff_files`.
