### ISSUE TITLE
`declare_dependency()` is missing `objects` argument

### ISSUE THREAD

**Issue by mtribiere** [mesonbuild/meson#11490]
**Describe the bug**
The `declare_dependency` function does not accepts the `objects` argument and gives the following error:
```
 ERROR: declare_dependency got unknown keyword arguments "objects"
```

**To Reproduce**
A sample Meson.build file of a subproject:
```
project('mySubProject','c')

mySubDep_dep = declare_dependency(objects:
    [
       'a/a.o',
        'b/b.o',
        'c/c.o'
    ]
)
```

**Expected behavior**
Should generate Ninja without errors

**System parameters**

- Cross Compilation setup
- Meson 1.0.1 - Release
- Windows

**Comment by xclaesse** [comment]
It is already fixed in master, will be in 1.1.0 https://mesonbuild.com/Release-notes-for-1-1-0.html#new-declare_dependencyobjects-argument
