### ISSUE TITLE
meson pkg-config OpenCV on windows

### ISSUE THREAD

**Issue by RoyAmoyal** [mesonbuild/meson#11498]
Hey, when I build OpenCV from  source in Windows using Visual Studio, even with the ```OPENCV_GENERATE_PKGCONFIG``` flag it doesn't create the opencv.pc file.

Meson is using the pkg-config to find it, but it can't and I get the next error when using ```pkg-config --cflags --libs opencv``` or ```pkg-config --cflags --libs opencv4```.

```
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
```

What should I do to fix it?

**Comment by eli-schwartz** [comment]
https://github.com/opencv/opencv/blob/0052d46b8e33c7bfe0e1450e4bff28b88f455570/cmake/OpenCVGenPkgconfig.cmake#L1

This is an upstream opencv issue.
