### ISSUE TITLE
I have build llvm and clang with source,  set llvm-config path to environment variable,  but when i tried to build mesa, it cant detect llvm subModule

### ISSUE THREAD

**Issue by xusw-cs** [mesonbuild/meson#11503]
I have build llvm and clang with source,  set llvm-config path to environment variable,  but when i tried to build mesa, it cant detect llvm subModule

compile log is 

Library dl found: YES
Checking for function "dladdr" with dependency -ldl: YES 
Checking for function "dl_iterate_phdr" : YES 
Checking for function "clock_gettime" : YES 
Run-time dependency zlib found: YES 1.2.11
Run-time dependency libzstd found: NO (tried pkgconfig and cmake)
Run-time dependency threads found: YES
Checking for function "pthread_setaffinity_np" with dependency threads: YES 
Run-time dependency expat found: YES 2.2.9
Library m found: YES
Message: libdrm 2.4.102 needed because nouveau has the highest requirement
Run-time dependency libdrm_intel found: YES 2.4.107
Run-time dependency libdrm_amdgpu found: YES 2.4.107
Run-time dependency libdrm_radeon found: YES 2.4.107
Run-time dependency libdrm_nouveau found: YES 2.4.107
Run-time dependency libdrm found: YES 2.4.107
llvm-config found: YES (/home/xsw/llvm-tidy/out/bin/llvm-config) 15.0.5
Run-time dependency LLVM (modules: all-targets, amdgpu, bitreader, bitwriter, core, coverage, engine, executionengine, instcombine, instrumentation, ipo, irreader, linker, lto, mcdisassembler, mcjit, native, objcarcopts, option, profiledata, scalaropts, transformutils, coroutines) found: NO (tried config-tool)
Looking for a fallback subproject for the dependency llvm

meson.build:1503:2: ERROR: Subproject directory not found and llvm.wrap file not found

A full log can be found at /home/xsw/mesa_llvm_src/build/meson-logs/meson-log.txt

I have tried to set CMAKE_PREFIX_PATH or  pkg_config_path, but  it doesnt work , how meson to detect llvm submodule?

**Comment by xusw-cs** [comment]
meson --version
0.53.2

error happens here: it cant detect llvm modules
dep_llvm = dependency(
    'llvm',
    version : _llvm_version,
    modules : llvm_modules,
    optional_modules : llvm_optional_modules,
    required : (
      with_amd_vk or with_gallium_radeonsi or with_gallium_swr or
      with_gallium_opencl or _llvm == 'enabled'
    ),
    static : not _shared_llvm,
    method : _llvm_method,
    fallback : ['llvm', 'dep_llvm'],
  )

**Comment by dcbaker** [comment]
LLVM_CONFIG isn’t supported that far back. You need a native file; basically an ini file with a [binaries] section with an llvm-config entry

**Comment by xusw-cs** [comment]
I  build this project on ubuntu, when i use apt intstall command to install the llvm packages, then the mesa can detect it ,but i cant find any *.ini files or *.pc  files related to llvm , i dont understand the difference between the  source build with released package

**Comment by xusw-cs** [comment]
i tried to  touch a custom-llvm.ini, this is its content
[binaries]
llvm-config = '/usr/local/bin/llvm-config'

and then i execute meson command: 
meson --native-file custom-llvm.ini  -D .....  build

but it still doesnt work

**Comment by xusw-cs** [comment]
thanks , i finally find the problem in this command: 
dep_llvm = dependency(
'llvm',
version : _llvm_version,
modules : llvm_modules,
optional_modules : llvm_optional_modules,
required : (
with_amd_vk or with_gallium_radeonsi or with_gallium_swr or
with_gallium_opencl or _llvm == 'enabled'
),
static : not _shared_llvm,
method : _llvm_method,
fallback : ['llvm', 'dep_llvm'],
)

the static key is set to  false,  because i dont  set the variable shared-llvm , the default value is true , so the llvm-config will find the dynamic library libLLVM*.so, but i build the llvm with static mode, when i set the static to true ,it succeed to detect the  llvm dependency

**Comment by RobbieTheK** [comment]
the static key is set to false, because i dont set the variable shared-llvm , the default value is true , so the llvm-config will find the dynamic library libLLVM*.so, but i build the llvm with static mode, when i set the static to true ,it succeed to detect the llvm dependency


> the static key is set to false, because i dont set the variable shared-llvm , the default value is true , so the llvm-config will find the dynamic library libLLVM*.so, but i build the llvm with static mode, when i set the static to true ,it succeed to detect the llvm dependency

What option with `meson setup` does this?

**Comment by Forchapeatl** [comment]
Hi , please did anyone resolve this  problem ?

**Comment by Mohammad-Abdul-Hadi** [comment]
> What option with `meson setup` does this?

Could not find any meson setup option.
Dumb Solution: manually changed `static : not _shared_llvm` to `static : _shared_llvm` and all the Run-time dependency LLVM was found.

`Run-time dependency LLVM (modules: amdgpu, asmparser, bitreader, bitwriter, core, engine, executionengine, instcombine, ipo, mcdisassembler, mcjit, native, scalaropts, transformutils, coroutines) found: YES`

**Comment by dcbaker** [comment]
@Mohammad-Abdul-Hadi `meson setup $builddir -Dshared_llvm=false`

**Comment by dcbaker** [comment]
I'm going to close this as the original issue was resolved.

**Comment by Mohammad-Abdul-Hadi** [comment]
> @Mohammad-Abdul-Hadi `meson setup $builddir -Dshared_llvm=false`

`meson.build: ERROR: Unknown Options: "shared_llvm" `

**Comment by dcbaker** [comment]
Oops, sorry it's `-Dshared-llvm=false` with a `-` not `_`

**Comment by SomePersonSomeWhereInTheWorld** [comment]
No luck for me:
```
llvm| NOTICE: Future-deprecated features used:
llvm| * 0.55.0: {'meson.has_exe_wrapper'}
llvm| * 0.56.0: {'gui_app arg in executable', 'meson.build_root'}
llvm| * 0.62.0: {'pkgconfig.generate variable for builtin directories'}
llvm| * 0.64.0: {'copy arg in configure_file'}
llvm| WARNING: Broken features used:
llvm| * 1.3.0: {'str.format: Value other than strings, integers, bools, options, dictionaries and lists thereof.'}
llvm| Subproject llvm finished.

WARNING: Variable 'dep_llvm' in the subproject 'subprojects/llvm' is not found
Dependency llvm (modules: bitwriter, engine, mcdisassembler, mcjit, core, executionengine, scalaropts, transformutils, instcombine, amdgpu, bitreader, ipo, asmparser, native) from subproject subprojects/llvm found: NO

meson.build:1680:13: ERROR: Dependency 'llvm (modules: bitwriter, engine, mcdisassembler, mcjit, core, executionengine, scalaropts, transformutils, instcombine, amdgpu, bitreader, ipo, asmparser, native)' is required but not found.

```

**Comment by dcbaker** [comment]
@SomePersonSomeWhereInTheWorld, the LLVM you're using doesn't have amdgpu support built in. You'll either need an LLVM built with amdgpu support (if you care about radesonsi or radv) or you need to disable those drivers by passing an explicit list of OpenGL and Vulkan drivers via the `-Dgallium-drivers=...` and `-Dvulkan-drivers=...`

**Comment by SomePersonSomeWhereInTheWorld** [comment]
> You'll either need an LLVM built with amdgpu support (if you care about radesonsi or radv) or you need to disable those drivers by passing an explicit list of OpenGL and Vulkan drivers via the `-Dgallium-drivers=...` and `-Dvulkan-drivers=...`

OK I don't care about AMD, how do I disable those drivers?
