### ISSUE TITLE
depscan.dd is not found with Fortran preprocessing

### ISSUE THREAD

**Issue by amontoison** [mesonbuild/meson#11504]
**Describe the bug**
I have an error if I use Fortran prepropressing with Meson.
```
meson compile -C builddir4
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /usr/bin/ninja -C /home/alexis/Bureau/git/hsl/juliahsl/builddir4
ninja: Entering directory `/home/alexis/Bureau/git/hsl/juliahsl/builddir4'
ninja: error: loading 'preprocessor.p/depscan.dd': No such file or directory
```

**To Reproduce**
```
fc = meson.get_compiler('fortran')
libhsl_src = []
libhsl_src += files(file1.f, file2.f, file3.f90)
pp_libhsl_src = fc.preprocess(libhsl_src,
                              compile_args : ['-Dmetis_nodend=juliahsl_metis', '-DMETIS_NODEND=juliahsl_metis'],
                              output: '@PLAINNAME@')
```

**Expected behavior**
I expect to not have an error. it's working fine with `cc.preprocess(...)` where `cc=meson.get_compiler('c')`.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
No

* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
Ubuntu 22.04

* what Python version are you using e.g. 3.8.0 
3.10

* what `meson --version`
1.0.1

* what `ninja --version` if it's a Ninja build
1.10.1.

**Comment by tristan957** [comment]
cc @xclaesse

**Comment by amontoison** [comment]
@eli-schwartz 
I did an dummy example to reproduce the error: https://github.com/mesonbuild/meson/compare/master...amontoison:meson:fortran_preprocess

I hope that it will help to the solve the issue :crossed_fingers:

**Comment by amontoison** [comment]
@Volker-Weissmann
You fixed a few things recently for Fortran compilers.
Do you have an idea how to solve this issue?

**Comment by Volker-Weissmann** [comment]
> Thanks a lot @Volker-Weissmann! I found a [workaround](https://github.com/ralna/GALAHAD/pull/118) this morning with `generator` because `fc.preprocess` was not working but it's a great news that you fixed it! We will use it as soon as possible. It will avoid to adapt the generators for each different Fortran compiler...
> 
> I checked #11549 and by chance we only have some `include "*.h"` in our Fortran files.

include *.h has the same problem. If yout touch the .h file, ninja will not rebuild your code even though it shoud rebuild.

**Comment by amontoison** [comment]
Oh, you're right.
Ok, so we need to be careful if we modify our header files.

**Comment by amontoison** [comment]
@Volker-Weissmann @xclaesse
I encountered a similar issue today with `ifort` on Windows.
Do you have an idea?
```
[215/2920] Module scanner.
FAILED: galahad_single.dll.p/depscan.dd 
"C:\hostedtoolcache\windows\Python\3.11.5\x64\Scripts\meson" "--internal" "depscan" "galahad_single.dll.p/galahad_single.dat" galahad_single.dll.p/depscan.dd D:/a/GALAHAD/GALAHAD/builddir/galahad_single.dll.p/galahad_single-deps.json
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\hostedtoolcache\windows\Python\3.11.5\x64\Scripts\meson.exe\__main__.py", line 7, in <module>
  File "C:\hostedtoolcache\windows\Python\3.11.5\x64\Lib\site-packages\mesonbuild\mesonmain.py", line 294, in main
    return run(sys.argv[1:], launcher)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.11.5\x64\Lib\site-packages\mesonbuild\mesonmain.py", line 282, in run
    return run_script_command(args[1], args[2:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.11.5\x64\Lib\site-packages\mesonbuild\mesonmain.py", line 223, in run_script_command
    return module.run(script_args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.11.5\x64\Lib\site-packages\mesonbuild\scripts\depscan.py", line 208, in run
    return scanner.scan()
           ^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.11.5\x64\Lib\site-packages\mesonbuild\scripts\depscan.py", line 158, in scan
    self.scan_file(s)
  File "C:\hostedtoolcache\windows\Python\3.11.5\x64\Lib\site-packages\mesonbuild\scripts\depscan.py", line 58, in scan_file
    self.scan_fortran_file(fname)
  File "C:\hostedtoolcache\windows\Python\3.11.5\x64\Lib\site-packages\mesonbuild\scripts\depscan.py", line 67, in scan_fortran_file
    for line in fpath.read_text(encoding='utf-8', errors='ignore').split('\n'):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.11.5\x64\Lib\pathlib.py", line 1058, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.11.5\x64\Lib\pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by Volker-Weissmann** [comment]
> @Volker-Weissmann @xclaesse I encountered a similar issue today with `ifort` on Windows. Do you have an idea of where is the problem?
> 
> ```
> [215/2920] Module scanner.
> FAILED: galahad_single.dll.p/depscan.dd 
> "C:\hostedtoolcache\windows\Python\3.11.5\x64\Scripts\meson" "--internal" "depscan" "galahad_single.dll.p/galahad_single.dat" galahad_single.dll.p/depscan.dd D:/a/GALAHAD/GALAHAD/builddir/galahad_single.dll.p/galahad_single-deps.json
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "C:\hostedtoolcache\windows\Python\3.11.5\x64\Scripts\meson.exe\__main__.py", line 7, in <module>
>   File "C:\hostedtoolcache\windows\Python\3.11.5\x64\Lib\site-packages\mesonbuild\mesonmain.py", line 294, in main
>     return run(sys.argv[1:], launcher)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\hostedtoolcache\windows\Python\3.11.5\x64\Lib\site-packages\mesonbuild\mesonmain.py", line 282, in run
>     return run_script_command(args[1], args[2:])
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\hostedtoolcache\windows\Python\3.11.5\x64\Lib\site-packages\mesonbuild\mesonmain.py", line 223, in run_script_command
>     return module.run(script_args)
>            ^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\hostedtoolcache\windows\Python\3.11.5\x64\Lib\site-packages\mesonbuild\scripts\depscan.py", line 208, in run
>     return scanner.scan()
>            ^^^^^^^^^^^^^^
>   File "C:\hostedtoolcache\windows\Python\3.11.5\x64\Lib\site-packages\mesonbuild\scripts\depscan.py", line 158, in scan
>     self.scan_file(s)
>   File "C:\hostedtoolcache\windows\Python\3.11.5\x64\Lib\site-packages\mesonbuild\scripts\depscan.py", line 58, in scan_file
>     self.scan_fortran_file(fname)
>   File "C:\hostedtoolcache\windows\Python\3.11.5\x64\Lib\site-packages\mesonbuild\scripts\depscan.py", line 67, in scan_fortran_file
>     for line in fpath.read_text(encoding='utf-8', errors='ignore').split('\n'):
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\hostedtoolcache\windows\Python\3.11.5\x64\Lib\pathlib.py", line 1058, in read_text
>     with self.open(mode='r', encoding=encoding, errors=errors) as f:
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\hostedtoolcache\windows\Python\3.11.5\x64\Lib\pathlib.py", line 1044, in open
>     return io.open(self, mode, buffering, encoding, errors, newline)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ```

No, Sorry.

**Comment by Volker-Weissmann** [comment]
No, Sorry, I'm not good with Windows.
