### ISSUE TITLE
Support for ```depends``` kargs in ```configure_file``` ?

### ISSUE THREAD

**Issue by mtribiere** [mesonbuild/meson#11526]
There is some instances where you want to configure files after, for example, a code generation take place.
Therefore would adding ```depends``` kargs in ```configure_file``` be an option?

**Comment by eli-schwartz** [comment]
I can't see how that's practical. configure_file is only ever run by the `meson setup` stage, and codegen is performed by the build stage, via ninja.

Note also that configure_file does have depfile support, but it will cause a forced reconfigure.

Why are you using configure_file? If you use it with a `configuration:` kwarg it will only deal with statically known configure-time information, so you can't inject codegen values. If you use it with a `command:` kwarg then the fact that you depend on another built output means you should just use the same command with a custom_target.

**Comment by mtribiere** [comment]
Alright my bad, here is my situation: 
I'm trying to write```#include "macro_default.h"``` in a new file ```macro.h``` (for some stubbing reasons). But this operation needs to happen **after** the generation of some sources done with ```custom_target```. 

I was trying to use ```configure_file ``` for this purpose but perhaps it's not the right way to do it ?

**Comment by eli-schwartz** [comment]
If the file contents are fully static then why do you need to create it at build time at all? Why not check it into git?

But yes, if it has to occur after a custom_target then it too needs to be a custom_target.

**Comment by mtribiere** [comment]
Here is the solution I found, hope it can be usefull for someone:
```
# Create the macro.h file
custom_target('macro.h',
    output : 'macro.h',
    capture: true,
    depends: myOtherCustomTarget,
    command: [
        'echo',
        '#include "macro_default.h"',
    ],
    build_by_default: true
)
```

**Comment by eli-schwartz** [comment]
That would probably be the way I'd do it, too.
