### ISSUE TITLE
Use ${} expansion in "meson devenv --dump"

### ISSUE THREAD

**Issue by chergert** [mesonbuild/meson#11533]
**Describe the bug**

Currently `meson devenv --dump` uses `$PATH` type variable expansion instead of `${PATH}` style variable expansion. It would be nice if `${PATH}` was used instead because it allows using it with `env -S ` to set the environment.

Such use is needed when plumbing chains of operations through containers into development environs such as we do in GNOME Builder.

**To Reproduce**
`meson devenv --dump`

```
GI_TYPELIB_PATH="/home/christian/Projects/gnome-builder/build/src:$GI_TYPELIB_PATH"
export GI_TYPELIB_PATH
PKG_CONFIG_PATH="/home/christian/.jhbuild/lib64/pkgconfig:/home/christian/.jhbuild/lib/pkgconfig:/home/christian/.jhbuild/share/pkgconfig:/usr/lib64/pkgconfig:/usr/share/pkgconfig:/home/christian/Projects/gnome-builder/build/meson-uninstalled"
export PKG_CONFIG_PATH
MESON_PROJECT_NAME="gnome-builder"
export MESON_PROJECT_NAME
MESON_DEVENV="1"
export MESON_DEVENV
PATH="/home/christian/Projects/gnome-builder/build/src:$PATH"
export PATH
```

**Expected behavior**
```
GI_TYPELIB_PATH="/home/christian/Projects/gnome-builder/build/src:${GI_TYPELIB_PATH}"
export GI_TYPELIB_PATH
PATH="/home/christian/Projects/gnome-builder/build/src:${PATH}"
export PATH
```

**system parameters**
meson 1.0.1
ninja 1.11.1

Thanks!

**Comment by eli-schwartz** [comment]
> because it allows using it with env -S to set the environment.

I'm not entirely sure what you mean by this.

**Comment by chergert** [comment]
```sh
[christian@xps13 ~]$ env -S 'PATH=foo:$PATH' ps 
env: only ${VARNAME} expansion is supported, error at: $PATH

[christian@xps13 ~]$ env -S 'PATH=foo:${PATH}' ps 
    PID TTY          TIME CMD
 144926 pts/4    00:00:00 bash
 146594 pts/4    00:00:00 ps
[christian@xps13 ~]$ 
```

**Comment by eli-schwartz** [comment]
```
  -S, --split-string=S  process and split S into separate arguments;
                        used to pass multiple arguments on shebang lines
```

Not clear to me what that's even supposed to do in this context.

**Comment by chergert** [comment]
In practice you can use it to expand shell variables without having to run a full shell. That is particularly useful when developers have a bad habit putting random `echo` in their `.bashrc` (or equivalent) without checking if `stdout` is a TTY with `if [ -t 0 ];` or equivalent even when interactive-mode has not been enabled (such as `bash -i`).

Because of that, `meson devenv` is only useful for hacking on projects inside your terminal. There is no way to automate it without running a full blown shell between the editor and build tooling (such as LSPs, syntax formatters, linters, etc) many of which use `stdin` and `stdout` as their only IPC mechanism. For LSPs, that is problematic because it breaks the wire protocol.

Another option could be for `meson devenv --dump`  (or another suitable parameter) to expand the variables rather than try to export a script which then exports the variables.

**Comment by eli-schwartz** [comment]
Does `meson devenv build-tooling-program` work?

**Comment by chergert** [comment]
It does here locally for me, and according to `pstree` it doesn't have any parent processes between it and `meson` so I would have expected it to work.

But as soon as I made changes in Builder to do that, I started getting bug reports about failures. I don't know if perhaps it's possible that any sort of internal logging/etc leaked into `stdout` at some point, but it made me immediately go about looking for ways to have some certainty on how things execute.

The whole thing is rather complex because Builder may create a chain of commands to run based on how we need to poke ourselves out of a sandbox, then into various layers of containers (or remote systems), only to further go through shells for expansion, build system tooling, etc.

**Comment by eli-schwartz** [comment]
It's even more complex because you are not actually using the sh format that we currently emit. :D You are parsing a shell init file, dropping lines such as "export" which you don't want.

> only to further go through shells for expansion, build system tooling, etc.

No idea how this all works, but if you're going through a shell anyway is it possible to have that shell execute `. path/to/dumped/devenv`? The introduction of a "source" command shouldn't cause bashrc to be re-loaded if it wasn't previously doing so (only starting an interactive shell should do that).

**Comment by chergert** [comment]
The problem here is that people put stuff in their `.bash_profile` too. So pretty much any way we try to run things, we end up breaking on *some* setup, with some shell, etc.

This is a patch removing the special handling, which would be my preference, if it worked. https://gitlab.gnome.org/GNOME/gnome-builder/-/commit/8fd8e0769a67ffada585df238eb25a545f11ae3d (it doesn't actually work on my local machine either when trying to start pylsp).

**Comment by eli-schwartz** [comment]
> The problem here is that people put stuff in their `.bash_profile` too. So pretty much any way we try to run things, we end up breaking on _some_ setup, with some shell, etc.

That really, really, really, should not be the case. If you run a bash process, it doesn't load any configuration files at all. If you load a bash interactive shell, it does. If you execute a script file, or an inline script in a `bash -c` argument, then it operates in script mode, not "interactive terminal" mode.

```
bash -c '. path/to/devenv.env; build-tooling-program --args'
```

will not load bash_profile or bashrc, no more than `/usr/bin/myimportantscript.sh` loads it.

**Comment by chergert** [comment]
I don't remember the details but I think maybe it had something to do with needing to get the user's environment applied which won't happen automatically for us when poking out of a sandbox.

**Comment by eli-schwartz** [comment]
What about the environment? It's inherited by the bash process, and left unmodified (other than processing the devenv.env file). Unless you tell it to parse the user's bashrc environment, in which case that happens regardless of meson.

**Comment by xclaesse** [comment]
I guess if you run gnome-builder from a terminal it inherit stuff from bashrc. I think vscode avoids that by making the "code" cli invoke it outside of the current terminal env somehow.

@chergert btw, meson master supports `meson devenv --dump <path>` to write it into a file that you can source. It is faster than regenerating the env every time you want to start a command in devenv. meson-vscode plugin (will) use that, and it regenerate the env file only when it detects that build.ninja file changed. See https://github.com/mesonbuild/vscode-meson/pull/107.

But back to original issue, I've got nothing against using `${}`, are there any downside? Like some shell might not support that syntax? It could require having a different `--dump-format`?

**Comment by eli-schwartz** [comment]
The downside is that I think it fundamentally speaks to trying to do wrong things, fragilely.

It also won't be portable between versions. It's also not portable even if you guarantee the version of meson, because many systems -- including many Linux systems!!! don't have `env -S` whether it documents this bizarre string splitting that isn't string splitting or not.

It's still not obvious to me that manually parsing `devenv --dump` instead of sourcing it is a good idea. If the conclusion is to not manually parse it, then modifying how it works (and adding two useless bytes to every line) is just code churn for the sake of code churn.

So, I'm trying to better understand why "execute a bash process and source the shell assignments file" isn't a good approach. So far the answer seems to be "we can't do that because bash will mess with the bashrc" but I've already explained why that's not true.

**Comment by chergert** [comment]
We already had the `meson devenv --dump` output, so I managed to get the `/bin/sh -c ''` method working and wrapping the upper "layers" of our run context stack.

https://gitlab.gnome.org/GNOME/gnome-builder/-/commit/3aad6548e1a5093a0b67cd7b53e663c89ee36eb5

I think it's fine to close this.

Thanks everyone!

**Comment by chergert** [comment]
We don't officially support Alpine as it is as we use coroutines with `ucontext_t` unsupported on MUSL.
