### ISSUE TITLE
sanitycheckcpp: meson.build:16:0: ERROR: Argument is of an unacceptable type 'str'.

### ISSUE THREAD

**Issue by roninracer** [mesonbuild/meson#11545]
Hi, 
We currently use Meson version 0.63 invoked from Conan.
Recently, we started getting errors from the sanitycheckcpp stage.
Our container has not changed nor has the compiler or the Meson version.

It's possible that it's something we introduced, but since the error happens so early in the build I am hoping someone here will know what the potential issue may be.
I have attached the build log for reference. 
[sanitycheckcpp-issue-meson-log.txt](https://github.com/mesonbuild/meson/files/11005975/sanitycheckcpp-issue-meson-log.txt)

**Comment by jpakkane** [comment]
The sanity check is fine, the actual problem is further down:

```
../meson.build:16:0: ERROR: Argument is of an unacceptable type 'str'.
Must be either an external dependency (returned by find_library() or dependency()) or an internal dependency (returned by declare_dependency()).
```

**Comment by roninracer** [comment]
Thank you for looking.
Umm that file doesn't exist in the directory structure (../meson.build:16:0 from the meson-private dir) that I could find.
We have several meson.build files so I had examined all the ones we had but the error did not seem to match the line it references.
I've attached them for your perusal. 
Since I thought it was related to the sanitycheck, I expected the path to be in the meson-private in my build directory. But if it's an error in the other files then I guess that makes sense. 

Our source tree is something like this:
\
\src
\include
\test
\build

[meson(top).build.txt](https://github.com/mesonbuild/meson/files/11006281/meson.top.build.txt)
[meson(src).build.txt](https://github.com/mesonbuild/meson/files/11006283/meson.src.build.txt)
[meson(include).build.txt](https://github.com/mesonbuild/meson/files/11006285/meson.include.build.txt)
[meson(test).build.txt](https://github.com/mesonbuild/meson/files/11006288/meson.test.build.txt)

**Comment by jpakkane** [comment]
The error messages are relative to the source root directori. In any case the problem you have is in the src subdir

    project_dependencies = ('fruit')

You are setting this to a string. I'm not sure what `fruit` here is or what you were trying to do, but if you wanted to look up a dependency called "fruit" via pkg-config, then you'd do `project_dependencies = dependency('fruit')`.

**Comment by roninracer** [comment]
thank you, I will try that and report back.

**Comment by roninracer** [comment]
That addition did the trick. I have to deal with the fact pkgconfig can't find fruit (even though conan installs it) but solving that issue is much more clearer than what I was seeing before.

Thank you ever so much!
