### ISSUE TITLE
Add ability to install generator output

### ISSUE THREAD

**Issue by TingPing** [mesonbuild/meson#1158]
My example use case is a lot of man pages being generated. Using a dozen custom targets is very redundant.

**Comment by nirbheek** [comment]
Yeah, I was thinking that either we can let `install_data` accept `GeneratedList`s or we can add a `install_dir :` kwarg to `generator.process()`.

**Comment by TingPing** [comment]
For my needs `install_dir` would be good.

**Comment by nirbheek** [comment]
The general consensus now is that we *don't* want to extend `generator`s, but instead everyone should use `custom_target`s, and we will improve the verbosity of those (#1364). Closing.
