### ISSUE TITLE
Version Incompatibilities with `cfg_data.get` Return Value

### ISSUE THREAD

**Issue by AntumDeluge** [mesonbuild/meson#11581]
```
OS: Windows 10 64-bit
Environment: MSYS2/MinGW-w64
Meson version: 1.0.1
```

**Describe the bug**

I have come across an issue building [Geany](https://github.com/geany/geany) with their Meson build script. On my system using Meson v1.0.1, configuration fails at [line 440](https://github.com/geany/geany/blob/f0e3ee273e/meson.build#L440) where the comparison `cdata.get('HAVE_FNMATCH') == 1` is made. The error reported is ``meson.build:440:9: ERROR: The `==` operator of bool does not accept objects of type int (1)``.

The problem is fixed by removing `== 1` from the line, but doing so appears to break backwards compatibility. On the [workflow build runner](https://github.com/geany/geany/actions/runs/4498275848/jobs/7914723494#step:7:94), running on Ubuntu `20.04` with Meson version `0.53.2`, it then reports the error `meson.build:440:9: ERROR: If clause 1 does not evaluate to true or false`. Thinking the problem was compatibility with versions `<0.60`, I [configured the workflow](https://github.com/geany/geany/actions/runs/4507085679/jobs/7934550222#step:7:96) to run on Ubuntu `22.04`, which uses Meson version `0.61.2`. But now there is a new error: ``meson.build:440:9: ERROR: Object <[IntegerHolder] holds [int]: 1> of type int does not support the `bool()` operator.``

So updating the build script to work for `1.0` breaks building on any currently available Ubuntu distribution, as the latest version that Ubuntu provides is `0.64` (if I remember correctly). It appears `cfg_data.get('HAVE_FNMATCH')` is incompatible between Meson versions `<1.0` and `>=1.0`. In order to not break compatibility the check(s) will somehow need to be guarded with `version_compare`, if I understand the documentation correctly.

I am not yet too familiar with Meson's syntax. Am I correct in that in versions older than `1.0` it returns an integer and in `1.0` it returns a boolean?

Geany GitHub issue: https://github.com/geany/geany/issues/3435

**Comment by AntumDeluge** [comment]
I think I have figured it out using the following:

```meson
meson_legacy = meson.version().version_compare('<1.0')

...

have_fnmatch = false
if meson_legacy
	have_fnmatch = cdata.get('HAVE_FNMATCH') == 1
else
	have_fnmatch = cdata.get('HAVE_FNMATCH')
endif

if have_fnmatch

...
```

I will close this issue shortly, unless there is some feedback about my solution.

**Comment by eli-schwartz** [comment]
I've answered on the geany ticket.
