### ISSUE TITLE
Feature options: true as enabled, false as disabled

### ISSUE THREAD

**Issue by lb90** [mesonbuild/meson#11588]
Sometimes projects switch from boolean user options to feature options; other times people don't remember exactly an option type and just pass `enabled`, `true`, whatever...

It would be good to consider `true` as `enabled` and `false` as `disabled`, maybe print a message like `INFO: Option ___ is a feature: true was promoted to enabled` and then proceed, as there's no harm

See for example https://gitlab.freedesktop.org/mesa/mesa/-/blob/mesa-23.0.1/meson.build#L110

**Comment by xclaesse** [comment]
False is ambiguous, it can mean disabled or auto. But we can do the opposite, accept enabled/disabled for booleans.

**Comment by eli-schwartz** [comment]
This has been discussed before, and my answer is still "absolutely not" (in both directions).

> Sometimes projects switch from boolean user options to feature options

This is why @xclaesse added support for "deprecated" options, a project can switch from booleans to features and explicitly map the values "true" and "false" as acceptable values for that feature option, describing the project-specific nature of what it should be interpreted as *and* emitting a warning telling you that the option has changed.
