### ISSUE TITLE
python dependency causes warnings when compiling with msvc

### ISSUE THREAD

**Issue by anarazel** [mesonbuild/meson#11592]
Hi,

When compiling with msvc on windows, the python dependency emits a warning about a macro redefinition, starting with 1.0.2:
https://cirrus-ci.com/task/6721555284099072?logs=build#L1512
```
[04:38:28.590] [1498/2168] Compiling C object src/pl/plpython/plpython3.dll.p/plpy_elog.c.obj
[04:38:28.590] C:\python\Include\pyconfig.h(117): warning C4005: 'MS_WIN64': macro redefinition
[04:38:28.590] src/pl/plpython/plpython3.dll.p/meson_pch-c.c: note: see previous definition of 'MS_WIN64'
```

This is due to 91c336449561a68f5624692d3c894f2345e466a2 / 81a8c488f007e842e83aa16ba941877250430a15 (in the 1.0 branch). 

Even before 3.12 pyconfig.h defined MS_WIN64, just only when using msvc:
https://github.com/python/cpython/blob/aae91fa63c65745c4118eafca0088447d87e65b0/PC/pyconfig.h#L104-L114

Seems that either this needs to be restricted to !msvc, or needs to check if MS_WIN64 is defined by pyconfig.h?

CC: @eli-schwartz 

Regards,

Andres

**Comment by eli-schwartz** [comment]
IMO the easiest fix is to just define it as `=` rather than letting it default to `=1`, this should mean the definition is compatible and does not warn.

I tried checking if the compiler is msvc, but the line is already quite long and it felt like none of the options there were elegant.

**Comment by anarazel** [comment]
Thanks!
