### ISSUE TITLE
sdl2 does not build with the "vs" backend

### ISSUE THREAD

**Issue by pobrn** [mesonbuild/meson#11630]
SDL2 fails to build with the following error
```
> meson compile -C build
INFO: autodetecting backend as vs2022
INFO: calculating backend command to run: msbuild "ABC\build\ABC.sln" -maxCpuCount -verbosity:minimal
MSBuild version 17.5.0+6f08c67f3 for .NET Framework

  SDL_windows_main.c
ABC\subprojects\SDL2-2.26.0\include\SDL_config.h(58,1): fatal  error C1189: #error:  Wrong SDL_config.h, check your include path? [ABC\build\subprojects\SDL2-2.26.0\5f2ac02@@sdl2main@sta.vcxproj]
```
when the `vs` backend is used. It compiles fine with the `ninja` backend.

As far as I can tell the reason is that the include directories are passed to the compiler in different order:

* with `vs`: `..\..\..\subprojects\SDL2-2.26.0\include;include;`
* with `ninja`: `"-Isubprojects\SDL2-2.26.0\include" "-I..\subprojects\SDL2-2.26.0\include"`

(I think it's a bit hard to understand what's going on because they are different relative paths, but the order is swapped.)

So the `SDL_config.h` that has the `#error` is found first with the `vs` backend. Removing or renaming the file makes it build OK (as far as I have tested).

Could this be a `meson` issue?

**Comment by jpakkane** [comment]
Originally it did it the other way around so we fixed it. Apparently not in vs backend then...

**Comment by eli-schwartz** [comment]
Yes, that seems extremely reasonable to me.

**Comment by eli-schwartz** [comment]
Thanks! 

> It also added a test, but unfortunately the `vs` backend still passed (passes) it.

Looking at the test, this is because the main part of the test occurs in unittests rather than project tests, which means it requires running some python code to poke and prod at the test build. Specifically, it checks for a compdb and parses the contents of that -- and also raises a SkipTest for everything other than ninja.

Your test actually verifies it by trying to build it.
