### ISSUE TITLE
Syntax issues are confusingly attributed to the start of the clause rather than the offending atom's position

### ISSUE THREAD

**Issue by amyspark** [mesonbuild/meson#11643]
**Describe the bug**

When a syntax issue occurs, the parser is currently billing the start of a semantic structure, instead of the offending atom's position.

This causes, for instance, mismatched `elif`s to be billed to the start of the `if` clause instead of the position of the actual broken `elif`.

**To Reproduce**

meson.build:

```meson
project('test', 'c')

CMDLINE_SELECT = [
    'help',
    'apple',
]

IGNORE_MESON_BUILTINS = [
    'help',
]

MESON_OPTIONS = [

]

foreach flag: CMDLINE_SELECT
	if IGNORE_MESON_BUILTINS.contains(flag)
		continue
	elif MESON_OPTIONS.contains(flag)
		value = get_option(flag)
		if value != 'unset'
			features.set(flag, value)
		endif
	elif
		error('Unhandled option @0@'.format(flag))
	endif
endforeach

```

**Expected behavior**

Compilation will fail, but it should bill line 24 and not 17:

```
meson.build:17:26: ERROR: Unknown statement.
```

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? **Native**
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) **Windows 10 21H2**
* what Python version are you using e.g. 3.8.0 **3.10.7**
* what `meson --version`  **1.0.1**
* what `ninja --version` if it's a Ninja build **1.10.2.git.kitware.jobserver-1**

**Comment by eli-schwartz** [comment]
I have a fix. The problem was that we sometimes update the node we are processing, but the error handler wasn't updated too. I now get:
```
meson.build:24:5: ERROR: Unknown statement.
```
