### ISSUE TITLE
https://mesonbuild.com/Getting-meson.html is outdated

### ISSUE THREAD

**Issue by edwardont** [mesonbuild/meson#11664]
the page states:
"Meson releases can be downloaded from the [GitHub release page](https://github.com/mesonbuild/meson/releases), and you can run ./meson.py from inside a release or the git repository itself without doing anything special."

running:
/meson-1.1.0$ sudo ./meson.py

ERROR: Must specify at least one directory name.
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.

this should be updated
Thanks and sorry if im being noob

**Comment by eli-schwartz** [comment]
The instructions are correct -- you can run Meson itself using ./meson.py without doing anything special, and it is equivalent to installing meson and then running via /usr/bin/meson.

The error message is the same, if  you run `meson` without arguments you get the same error -- but if you run `meson --help` or `./meson.py --help` you also get the same results (in that case, instructions for using meson).

**Comment by edwardont** [comment]
ok thanks ill go have a word with myslef
