### ISSUE TITLE
C++ ".tpp" file. ERROR: No specified compiler can handle file

### ISSUE THREAD

**Issue by MurathanGoktas** [mesonbuild/meson#11697]
When building my project using Meson, I encountered an error stating "ERROR: No specified compiler can handle file /projects/btl/tgoktas/cc_btllib/btllib/src/btllib/counting_bloom_filter.tpp". The build works well when the file extension is changed to ".cpp", but not with the ".tpp" extension.

I have included my meson.build file in this issue. You may need to create simple source code files to reproduce the error (don't include private/proprietary code).

I expected Meson to compile the ".tpp" files without any issues, just like it does with ".cpp" files.

System parameters:

Built from conda.
Operating system: CentOS 7
Python version: Python 3.10.8
meson --version: 1.1.0
ninja --version: 1.11.0

`meson.build` [link](https://github.com/bcgsc/btllib/blob/code-coverage/meson.build)
```
btllib_include = [ include_directories('include'), include_directories('.') ]
btllib_sources = run_command('scripts/get-files', 'src').stdout().strip().split()

btllib_lib = static_library('btllib',
                           btllib_sources,
                           include_directories : btllib_include,
                           dependencies : deps,
                           install : true,
                           install_dir : 'lib')

btllib_dep = declare_dependency(
  link_with : btllib_lib,
  include_directories : btllib_include
)

subdir('include')
subdir('wrappers')
subdir('recipes')
if get_option('buildtype') != 'release'
  subdir('tests')
endif
```

**Comment by jpakkane** [comment]
Tpp is not supported because I have never even heard of such an extension. It seems to be nonstandard and based on a quick search, [.tpp files should not be compiled, only included in other source files](https://stackoverflow.com/questions/44774036/why-use-a-tpp-file-when-implementing-templated-functions-and-classes-defined-i).

**Comment by MurathanGoktas** [comment]
OK thanks for help I moved them from the `src` directory.
