### ISSUE TITLE
link_depends does not work with files()

### ISSUE THREAD

**Issue by dvdhrm** [mesonbuild/meson#1172]
Hey

The `link_depends:` argument to executables and libraries does not work with `File` objects so far. It requires strings. See this example:

```
project('foobar', 'c')                                                           
bar = shared_library('bar', ['foo.c'], link_depends: files(['A','B']))
```

It fails with:

```
Link_depends arguments must be strings.
```

I circumvent this by using `join_paths(meson.current_source_dir(), 'my_file')` instead of `files()`, but I guess that's no the suggested solution?

Furthermore, the reference-manual in the wiki does not explain the `File` object, but the documentation of `files()` mentions it.

Thanks
David

**Comment by dvdhrm** [comment]
Same for `install_headers()`. I guess there are a bunch more. Maybe `files()` is not supposed to used with those functions, but the wiki gives the impression that `files()` should work with anything that accepts paths. Or am I wrong here?

**Comment by nirbheek** [comment]
This is a bug. Generally, everything that accepts files as strings should also accept them as `File` objects. The reason that some things do not is because almost everyone uses strings and `File` objects were not there in the very beginning of the project when most of these functions were added.

**Comment by doraskayo** [comment]
It seems that [`generator.process()`](https://github.com/mesonbuild/meson/wiki/Reference%20manual#generator-object) also doesn't accept `file_array` (which is the output of `files()`.) I'm getting the following error:
```
Arguments must be strings.
```

@nirbheek, would you rather I open a new issue about it?

**Comment by nirbheek** [comment]
That was merged a few days ago in https://github.com/mesonbuild/meson/pull/1257.

**Comment by nirbheek** [comment]
For other people reading this bug report, you almost never need to use `meson.current_source_dir()` when passing files as strings to functions. Strings are implicitly assume to be relative to the current source dir. The only time you want to use that is when you want to get the absolute path for some custom reasons.
