### ISSUE TITLE
Setting `b_vscrt` via `meson setup --reconfigure` has no effect on the generated `build.ninja`

### ISSUE THREAD

**Issue by dnicolodi** [mesonbuild/meson#11732]
Reconfiguring with a different value of `b_vscrt` does not result in changes to `build.ninja`.

Running `meson setup` with `-Db_vscrt=mdd` results in the correct flag being passed to the compiler:
```
$ meson setup build --vsenv -Db_vscrt=mdd
...
  User defined options
    vsenv        : True
    b_vscrt      : mdd
...
$ grep '/MD' build/build.ninja
 ARGS = ... "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W2" "/std:c11" "/O2" "/Zi" ...
...
```
edited to remove unrelated output. However, reconfiguring with `-Db_vscrt=md` has no effect:
```
$ meson setup build --vsenv -Db_vscrt=md --reconfigure
...
  User defined options
    vsenv        : True
    b_vscrt      : md
...
$ grep '/MD' build/build.ninja
 ARGS = ... "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W2" "/std:c11" "/O2" "/Zi" ...
...
```
also edited to remove unrelated output. I would have expected the `/MDd` flag to be turned into `/MD`.

This is Windows with VS 17.5.3, Python 3.10, meson 1.1.0 and ninja 1.10.2.

**Comment by bruchar1** [comment]
This seems to be true for all base options. For instance, `b_ndebug` faces the same problem.
