### ISSUE TITLE
test-valgrind don't show errors

### ISSUE THREAD

**Issue by charlesvdv** [mesonbuild/meson#1175]
Hello,

When I execute ``` ninja test-valgrind ``` and there is some memleaks or invalid read/write in my C program, the test summary still shows an *OK* for this test. I find this a little counter intuitive.

One possible solution could be adding ``` --error-exitcode=1 ``` to valgrind to detect when there is errors but I don't know if it should be the default settings.

Thanks!

**Comment by jpakkane** [comment]
In current trunk we have changed the way test targets work. We no longer have a `test-valgrind` target but instead provide a testing tool that provides a lot more stuff (such as running each test X number of times, running them under gdb, etc).

**Comment by charlesvdv** [comment]
Is there any documentation about it ? I'm quite interrested in this and [your wiki](https://github.com/mesonbuild/meson/wiki/Unit-tests) don't say anything about it.

**Comment by jpakkane** [comment]
Not yet. It has not been released yet and I've been lazy. :smile: The program does have command line help, though.

**Comment by charlesvdv** [comment]
OK great ! Thanks a lot for your work and your help !
