### ISSUE TITLE
NASM support conflicts with vs2010backend.py language detection

### ISSUE THREAD

**Issue by ArthurHeymans** [mesonbuild/meson#11766]
**Describe the bug**
When combining nasm code with the suffix .asm and msvc C compiler the following warning is thrown
"ERROR: Could not guess language from source file xxx.asm."

**To Reproduce**
Add add 'nasm' to languages in meson.build and include an emtpy '.asm' file

**Expected behavior**
MSVC does not try to compile .asm files

**system parameters**
meson version 1.0.1

**Comment by xclaesse** [comment]
The vs backend only support c/c++ languages. You need the ninja backend to use nasm currently.

**Comment by ArthurHeymans** [comment]
Oh I see. Thanks for clarifying!
