### ISSUE TITLE
Missing dependencies for building docs

### ISSUE THREAD

**Issue by prasannavl** [mesonbuild/meson#11772]
## Missing deps

Just leaving this issue here to be documented / fixed, as the expectation that being a build system, building this should cleanly have the pre-req documented or catch it during the build process. 

- On a fresh install of Ubuntu 23.04: 
- Clone meson
- Build docs as per the documentation
  - `hotdoc`
    - This itself requires undocumented deps: 
      - Solution: `sudo apt install libjson-glib-dev`
    - `pipx install hotdoc`
  - `cd docs; meson setup build; meson compile -C build`
    - Missing: `strictyaml`, `chevron`
    - Need to do a `pip3 install --user <dep> --break` or install them on a venv.

**Comment by eli-schwartz** [comment]
chevron and strictyaml are documented at https://mesonbuild.com/Yaml-RefMan.html although granted this could be checked by meson.build as well.
