### ISSUE TITLE
EPEL 7 lacks RPM macros for ninja

### ISSUE THREAD

**Issue by arteymix** [mesonbuild/meson#1177]
Igor recently added Meson to this [Copr repository](https://copr.fedorainfracloud.org/coprs/ignatenkobrain/meson-el7/) and it works excellently. However, with Ninja's RPM macros lacking, the current macros for Meson are not working.

I think it would be great to repackage ninja-build in the Copr.

**Comment by ignatenkobrain** [comment]
* http://koji.fedoraproject.org/koji/buildinfo?buildID=822474
* https://bodhi.fedoraproject.org/updates/ninja-build-1.7.2-2.el7
* https://copr.fedorainfracloud.org/coprs/ignatenkobrain/meson-el7/package/ninja-build/
