### ISSUE TITLE
rust: `b_ndebug` enables both debug assertions and overflow checks

### ISSUE THREAD

**Issue by sdroege** [mesonbuild/meson#11785]
Since recently, `b_ndebug` passes `-C debug-assertions=on` to `rustc`. This is somewhat inconsistent with what cargo does. When setting `debug-assertions = true` in `Cargo.toml`, cargo (for release builds at least) passes `-C debug-assertions=on -C overflow-checks=off`. Only if also `overflow-checks = true` is configured in `Cargo.toml` it will also enable those.

I'd suggest handling this the same way as cargo does and maybe also add an easy configuration for overflow checks.

The effect of this is currently that a simple `staticlib` that exports a `fn add(a: i32, b: i32) -> i32 { a + b }` adds 5MB (instead of single-digit kB) to any executable or shared library it is linked into.

CC @dcbaker

**Comment by sdroege** [comment]
Implementing it like this would require checking if the user provided any of those `-C` flags themselves, and if so don't set them automatically based on the generic build configuration. That seems a bit fragile but seems like the only way forward.

**Comment by xclaesse** [comment]
There are already some cflags we warn when setting them manually because they are controlled by an option, e.g.`-Werror`. I guess this would be similar.

What you suggest is adding `rust_overflow_checks` compiler option, right?
- `-Db_ndebug=true` -> `-C debug-assertions=on -C overflow-checks=off`
- `-Drust_overflow_checks=true` -> `-C debug-assertions=on -C overflow-checks=on`
- `-Db_ndebug=false -Drust_overflow_checks=true` ->  `-C debug-assertions=off -C overflow-checks=on` ?

**Comment by sdroege** [comment]
That would be one option, yes. I wouldn't have added a `rust_overflow_checks` compiler option but that would work.

There are a lot of `-C` flags to `rustc` that a user might want to set, so I'm not sure we want to expose them all.

**Comment by dcbaker** [comment]
I can't replicate this by hacking up the test cases/rust/2 staticlib case, the outputs with `-C overflow-checks` is the same both on and off in both the static libs and in the resulting bin. Is there something more that needs to be done here? I hacked this by explicitly adding the overflow-checks flag in the rustc `get_assert_args()` method.

**Comment by sdroege** [comment]
I'll look at providing a complete testcase some time later. But maybe something changed in the meantime and it's not that much of a problem anymore?

**Comment by sdroege** [comment]
Here it is, with latest `master` of meson.

### meson.build

```meson
project('test', 'rust', 'c')

l1 = static_library('l1', 'l.rs', rust_crate_type : 'staticlib')
l2 = static_library('l2', 'l.rs', rust_crate_type : 'staticlib', rust_args : ['-C', 'overflow-checks=off'])

e1 = executable('e1', 'e.c', link_with : l1)
e2 = executable('e2', 'e.c', link_with : l2)
```

### l.rs

```rust
#[no_mangle]
pub extern "C" fn add(a: i32, b: i32) -> i32 {
    a + b
}
```

### e.c

```cpp
#include <stdio.h>

extern int add(int a, int b);

int main(int argc, char **argv) {
  printf("%d\n", add(1, 2));
  return 0;
}
```

### Results

```console
$ ls -alh e1 e2
.rwxr-xr-x. slomo slomo 5.2 MB Thu Jul 13 08:32:35 2023 e1
.rwxr-xr-x. slomo slomo  25 KB Thu Jul 13 08:32:35 2023 e2
```

**Comment by dcbaker** [comment]
Okay, yeah. I can see that reproducing now. Since rustc does the normal thing here and just takes the last value of a given `-C` argument passed to it, adding `-C overflow-checks=off` to the default arguments seems reasonable. If someone wants them on they can always set `-Drust_args="-C overflow-checks=on"`, or if there's a ton of interest we can add a builtin. I'll send a patch

**Comment by LingMan** [comment]
Cargo has two built-in profiles, `release` and `dev` (frequently referred to as `debug`). It is widely documented that overflow checks are by default active in `dev` builds and inactive in `release` builds. Same for debug asserts, but they are independent toggles.
How would that map to meson? Intuitively I'd expect:

* `--buildtype debug` implies `-Ddebug=true -Doptimization=0 -Db_ndebug=false -Drust_args="-C overflow-checks=on"`
* `--buildtype release` implies `-Ddebug=false -Doptimization=3 -Db_ndebug=true -Drust_args="-C overflow-checks=off"`

Would that make sense or is there some other high level profile concept I didn't find yet?

**Comment by sdroege** [comment]
Yeah it would probably be useful to map the different build types / profiles closer to what cargo does. This here was mostly to get the regression out of the way as a first step.

@LingMan Do you want to make a proposal what the different meson build types should map to and how that matches cargo? In a separate issue or PR
