### ISSUE TITLE
Revert #1060 for release if gobject-introspection upstream hasn't ack-ed the solution by then

### ISSUE THREAD

**Issue by tp-m** [mesonbuild/meson#1180]
#1060 calls `g-ir-scanner` with a new `--extra-library` option that currently does not exist yet, but only exists in a proposed patch in bugzilla: https://bugzilla.gnome.org/show_bug.cgi?id=774625

We should not ship this before we have any indication from g-i upstream that this will land in some form like that in future, with this option.

Hence milestoneing for 0.37

**Comment by thiblahute** [comment]
> #1060 calls g-ir-scanner with a new --extra-library option that currently does not exist yet, but only exists in a proposed patch in bugzilla: https://bugzilla.gnome.org/show_bug.cgi?id=774625

It does call that only if availaible, but still we need an answer from upstream before using it.

**Comment by thiblahute** [comment]
The patch has been merged: https://git.gnome.org/browse/gobject-introspection/commit/?id=eea2447c4e4c1c98fda3ba212a9a9bbcc8655c90

**Comment by thiblahute** [comment]
I guess we can just close that one?

**Comment by tp-m** [comment]
Yep, thanks!
