### ISSUE TITLE
`run_command` returncode is still 0 even when python returns error code

### ISSUE THREAD

**Issue by danielcjacobs** [mesonbuild/meson#11800]
**Describe the bug**
calling `run_command([python, '-c', '"import sys; sys.exit(1)"'], check: false).returncode()` returns 0, even though I would expect it to be 1.

**To Reproduce**
meson.build:
```meson
project('test', 'cpp')

python = import('python').find_installation('python3')
error_code = run_command([python, '-c', '"import sys; sys.exit(1)"'], check: false)
message(error_code.returncode())
```

**Expected behavior**
The message printed should be `Message: 1`, but it's `Message: 0`.

**system parameters**
* plain native build
* OS: Fedora 37
* Python version: 3.11.3
* `meson --version`: 1.1.0
* `ninja --version`: N/A

**Comment by eli-schwartz** [comment]
> calling `run_command([python, '-c', '"import sys; sys.exit(1)"'], check: false).returncode()` returns 0, even though I would expect it to be 1.

You're running `python -c` on a buffer that is equivalent to this python script:
```
#!/usr/bin/python3

"import sys; sys.exit(1)"
```

This is a str object that isn't assigned anywhere, so basically a docstring.

**Comment by danielcjacobs** [comment]
ah, thanks :facepalm:
