### ISSUE TITLE
Can't specify target for bindgen in machine file

### ISSUE THREAD

**Issue by alyssais** [mesonbuild/meson#11805]
**Describe the bug**
I'm trying to cross compile mesa, including rusticl.  For that to work, bindgen needs to be run for the right target.  This means that it needs to pass `-target x86_64-unknown-linux-gnu` to clang.  Putting `bindgen = ['bindgen', '-target', 'x86_64-unknown-linux-gnu']` in my cross file doesn't work, because bindgen interprets options that come before the positional header argument as arguments for itself, and arguments that come after the header argument as arguments for clang.  So the `-target` option needs to come at the _end_ of the bindgen command line.

I can create a bindgen wrapper that appends the appropriate `-target` option, but it feels like there should be a more Meson-y way to handle this.

**To Reproduce**
Try to cross compile Mesa with `-Dgallium-rusticl=true`.

**Expected behavior**
Mesa cross compiles successfully.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? <ins>yes</ins>
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) <ins>NixOS</ins>
* what Python version are you using e.g. 3.8.0 <ins>3.10.11</ins>
* what `meson --version` <ins>1.1.0</ins>
* what `ninja --version` if it's a Ninja build <ins>1.11.1</ins>

**Comment by dcbaker** [comment]
Yeah... that is an issue. We could probably put this in the `[properties]` section, but that feels really hacky. It's not a particularly hard problem to solve, but I'm not sure what the most elegant way to solve it would be
