### ISSUE TITLE
gnome.post_install() for gtk-update-icon-cache assumes hicolor cache

### ISSUE THREAD

**Issue by danyeaw** [mesonbuild/meson#11824]
**Describe the bug**
Hi all, while adding a meson build for [adwaita-icon-theme](https://gitlab.gnome.org/GNOME/adwaita-icon-theme), we realized that meson is hard coded to update the hicolor icon cache only. With GTK, each icon theme contains a separate cache.

```
gnome.post_install(gtk_update_icon_cache : true)

Running custom install script '/usr/bin/gtk4-update-icon-cache -q -t -f /home/dan/Projects/adwaita-icon-theme/dist/usr/share/icons/hicolor'
--- stdout ---

--- stderr ---
gtk4-update-icon-cache: Failed to open file /home/dan/Projects/adwaita-icon-theme/dist/usr/share/icons/hicolor/.icon-theme.cache : No such file or directory
```

**To Reproduce**

meson.build:
```
project('adwaita-icon-theme', 'c', version : '44.0')
gnome = import('gnome')
gnome.post_install(gtk_update_icon_cache : true)
```

```
> meson setup --prefix=/home/dan/Projects/adwaita-icon-theme/dist/usr builddir
> cd builddir
> meson install
```

**Expected behavior**
gnome.post_install allows us to install update other icon caches. Maybe hicolor is default, but allows for passing in Adwaita or another directory.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? Native
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.): openSUSE MicroOS
* what Python version are you using e.g. 3.8.0: 3.11.3
* what `meson --version` : 1.1.1
* what `ninja --version` if it's a Ninja build: 1.11.1

**Comment by xclaesse** [comment]
I think the rational here is, correct me if I'm wrong, each app install their icons into hicolor, so that's very common use-case. Only icons theme project needs to run gtk-update-icon-cache in a different directory, there are only a handful of them and they can use meson.post_install_script() pretty easily.

I guess we could add `gnome.post_install(gtk_update_icon_cache : 'Adwaita')` and `true` would be alias for `hicolor`, just not sure it's worth it?

**Comment by danyeaw** [comment]
I think you are right, I forgot that other apps install their icons as hicolor icons as well. In that case, it sounds like it is only really needed for adwaita-icon-theme and for that a custom install script is fine. Thanks!
