### ISSUE TITLE
Internal dependencies cannot provide a value for get_variable

### ISSUE THREAD

**Issue by bonzini** [mesonbuild/meson#11821]
**Describe the bug**
Variables are passed to the pkgconfig module, not to declare_dependency. This means that get_variable cannot be used on dependencies overridden by a subproject.

Instead, a `variables` argument should be added to declare_dependency and deprecated from pkgconfig.generate.

**To Reproduce**
```
project('test', 'c', meson_version : '>= 0.58')
glib = dependency('glib-2.0')
summary({'bindir': glib.get_variable('bindir')})
```

Now build using glib as a subproject:

```
mkdir subprojects
meson wrap install glib
meson setup --force-fallback glib build
```

Meson fails:

```
Dependency glib-2.0 found: YES 2.76.1 (overridden)
meson.build:3:0: ERROR: Could not get an internal variable and no default provided for <InternalDependency null: True>
```

**Expected behavior**
The minimal meson.build works both with system glib and with wrapdb-based glib

**system parameters**
Native build on Linux, meson 1.1.0

**Comment by bonzini** [comment]
Oh, so it's a glib bug.

> Why do you need bindir?

Building a Windows installer package requires the full path to the glib DLLs, which can be found in the glib bindir.

**Comment by xclaesse** [comment]
> Oh, so it's a glib bug.

Not sure it's really a bug, we don't usually have `bindir` in `declare_dependency()`.

> Building a Windows installer package requires the full path to the glib DLLs, which can be found in the glib bindir.

But when glib is a subproject, why do you need its bindir? It's going to be the same as main project's bindir. You can do: `glib_dep.get_variable('bindir', default_value: get_option('bindir'))`.

**Comment by bonzini** [comment]
> Not sure it's really a bug, we don't usually have bindir in declare_dependency(variables: {...}).

It's not commonly in .pc files either; glib has it as the basis for other variables such as `glib_genmarshal=${bindir}/glib-genmarshal`. If glib wants to be used as a wrap, they're the ones that need to make the dep file consistent with the .pc file (alternatively this has to be a feature request for Meson, but they're pretty conservative in adopting new versions).

> But when glib is a subproject, why do you need its bindir? It's going to be the same as main project's bindir. You can do: glib_dep.get_variable('bindir', default_value: get_option('bindir')).

More precisely it's `get_option('prefix') / get_option('bindir')`. Yes, it's going to be the same as the main project's bindir but I was testing a build with wraps that are obtained automatically from `meson wrap update-db`. So in this case my project does not know at all that a glib wrap is involved.
