### ISSUE TITLE
Meson cannot detect the correct windres executable for MSVS's stock Clang

### ISSUE THREAD

**Issue by amyspark** [mesonbuild/meson#11845]
**Describe the bug**

Meson believes that `windres` is the only available Windows resource compiler when GCC or Clang are the active compiler.

https://github.com/mesonbuild/meson/blob/e20717ed8f9f746a233e2bd2b3018997a3f73799/mesonbuild/modules/windows.py#L85-L92

This is almost correct, except that it's *not* for the Clang that Microsoft Visual Studio ships. It's unique in that it does not ship windres, but rather relies on MSVC's `rc` executable that comes with the stock compiler.

Basically, the check above needs to e.g. validate if `_MSC_VER` is present in the compiler before bailing over to finding `windres`. Just relying on the compiler ID is not reliable to determine the ABI.

**To Reproduce**

In a Windows box with Visual Studio 2022 and LLVM installed,

![imagen](https://github.com/mesonbuild/meson/assets/13498015/9807f77d-00e8-4515-9170-b284c0422ae5)

ensure that in your environment or native file, the `CC` and `CXX` variables are set to `clang` . Then try to build https://github.com/bad-alloc-heavy-industries/substrate:

```
git clone https://github.com/bad-alloc-heavy-industries/substrate
cd substrate
meson setup build --buildtype debugoptimized
```

**Expected behavior**

It will fail out of the box with:

```
impl\meson.build:177:29: ERROR: Could not find Windows resource compiler
```

This can be worked around with setting the `WINDRES` environment variable to `rc`.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
  * Native build
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
  * Windows 10 22H2
* what Python version are you using e.g. 3.8.0
  * Python 3.10.7
* what `meson --version`
  * 1.1.0
* what `ninja --version` if it's a Ninja build
  * 1.10.2

**Comment by tristan957** [comment]
@amyspark can you submit a PR for this? Should be easy. Plus you have a system which can easily test the changes.

**Comment by amyspark** [comment]
@tristan957 Sure, though I'm not sure yet if Meson's internals allow compiler ABI reflection.
