### ISSUE TITLE
crontab meson command not found

### ISSUE THREAD

**Issue by that-is-not-great** [mesonbuild/meson#11846]
I have an issue where the meson command cannot be found only when executing from a crontab

`pip install meson ninja`

```
meson --version
1.0.0
```

```
which meson
/home/xxx/.local/bin/meson
```

```
echo "$PATH"
/home/xxx/.local/bin:..........
```

server was rebooted

crontab script:

```
#!/bin/bash
meson --version; # cmd not found
pip --version; 
/home/xxx/.local/bin/meson --version;
```

crontab script output:

```
/home/xxx/build.sh: line 2: meson: command not found
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
1.0.0
```

why can the crontab script not find `meson` ?

**Comment by eli-schwartz** [comment]
> why can the crontab script not find `meson`? 

Because a crontab does not read files such as bashrc, and therefore does not have the same `$PATH` as when you are logged in.
