### ISSUE TITLE
Compilation error when using include_directories() object in subdirectory

### ISSUE THREAD

**Issue by adel-mamin** [mesonbuild/meson#1185]
In the setup, which uses '-Wmissing-include-dirs' together with '-Werror' treating all warnings as errors gcc compiler returns an error. Here is the simplified example:
git@bitbucket.org:adel-mamin/meson-test.git
If I compile it with gcc I get the following error:
> ninja
[1/5] Compiling c object 'subdir/liba@sha/a.c.o'
FAILED: subdir/liba@sha/a.c.o
cc  '-Isubdir/liba@sha' '-Isubdir' '-I../subdir' '-Iinclude' '-I../include' '-pipe' '-Wall' '-Winvalid-pch' '-Wmissing-include-dirs' '-Werror' '-O0' '-g' '-fPIC' '-MMD' '-MQ' 'subdir/liba@sha/a.c.o' '-MF' 'subdir/liba@sha/a.c.o.d' -o 'subdir/liba@sha/a.c.o' -c ../subdir/a.c
cc1: error: include: No such file or directory [-Werror]
cc1: all warnings being treated as errors
[2/5] Compiling c object 'mytest@exe/main.c.o'
ninja: build stopped: subcommand failed.

**Comment by ignatenkobrain** [comment]
actually this is because there is no such dir in builddir: `include`

**Comment by ignatenkobrain** [comment]
I think fix would be something to not add $builddir/dir if it's not subdir()'ed.

**Comment by jpakkane** [comment]
Can you test if #1186 fixes it for you?

**Comment by adel-mamin** [comment]
I have tested the commit b7fa5a8 "Only add build dir inlude directives if the corresponding dir exists. Closes #1185." and confirm that the issue is fixed.
