### ISSUE TITLE
armar compatibility broken

### ISSUE THREAD

**Issue by tolnaisz** [mesonbuild/meson#11887]
With commit b4d9b2551c32288754a3008d14895c6fe53f48e2 the armar compatibility was broken.

I have armar specified as static linker in my cross file. Meson setup now gives me the following error:
ERROR: Unknown linker(s): [['armar']]

The issue is that in detect_static_linker the '-?' parameter is passed into armar which causes it to print an error, the standard help and exit with exit code 1. It should either be called without any parameters or with the '--version' parameter.

**Comment by xclaesse** [comment]
CC @mon

**Comment by mon** [comment]
Cheers for the ping. Seems like just using binary names is fragile after all, and we need to use something similar to the compiler detection where version flags are tried if some fail. I'll try and hurry through #11421 (it's been stalled waiting for changes from me) and then make a fix.

**Comment by lavrinovu4** [comment]
@mon looks like this issues appears again after the commit: https://github.com/mesonbuild/meson/commit/eb74bb8dbf74ac22a02e369b6622ee0ef8b5d6a3

Can you look?

**Comment by mon** [comment]
@lavrinovu4 I thought I fixed this in  #11421, which was merged after that commit was made. Is the error identical to before?

The correct approach here would be to add regression tests using a docker image with TI's compilers, but I've pinned a working version in my builds so it wasn't really needed

**Comment by lavrinovu4** [comment]
@mon the issue is with non-TI armclang and is the same as in the comment https://github.com/mesonbuild/meson/pull/11942#issuecomment-1621496065.
I can't share the docker because compiler is not free. Meson version 1.4.2 is the last working version with my armclang.

**Comment by mon** [comment]
Oh I see, this was only *merged* in March. It [re-introduced](https://github.com/mesonbuild/meson/pull/12246/files#diff-d03e76a1b248e2587d914d0a686f7328cbc483988e5f2ee37b65d476f1d0e988R200-R203) the buggy detection that used linker names that I specifically fixed in #11421.

In theory it should be easy to fix, in reality the place I was working that was using TI compilers went into administration in March, so I left. I don't really have the bandwidth to install them on my personal machine and debug this. You'll have to give it a go yourself.

**Comment by eli-schwartz** [comment]
I am confused because #12246 was opened September 2023 and merged on March 12, 2024, and the PR from @mon was opened in *February* 2023, much earlier, but was merged 2 months later on May 15, 2024.

So the former shouldn't reintroduce an issue fixed in the latter. But also, the latter contains commit https://github.com/mesonbuild/meson/commit/456d879ff42624a5c67512022ab700518d869b21 which states:

> When C6000 support was added in https://github.com/mesonbuild/meson/pull/12246, TI compilers were given the correct version argument. This broke the previous check which relied on an error being thrown by the compiler.

So in theory it fixed... whatever was wrong?

Is there an additional regression then?

**Comment by lavrinovu4** [comment]
so looks like the commit https://github.com/mesonbuild/meson/commit/456d879ff42624a5c67512022ab700518d869b21 breaks non-TI armclang again.

**Comment by mon** [comment]
Thanks for the corrected timeline @eli-schwartz - in which case, the initial C6000 PR broke non-TI armar (by adding filename checks in `detect_static_linker`), and my PR _didn't_ fix it because I only tested against the TI armar.

**Comment by esolosh** [comment]
Here is what returned by ARM's `armar` probed by `Popen_safe_logged()`
```
p=<Popen: returncode: 1 args: ['armar', '?']> out="Product: Hardware Success Kit (Standard)\nComponent: Arm Compiler for Embedded 6.22\nTool: armar [5ee90200]\n\nArchive creation and maintenance tool\n\nCommand format:\n\narmar options archive [ file_list ]\n\nWildcards '?' and '*' may be used in file_list\n\nOptions:-\n\n -r         Insert files in <file_list>, replace existing members of the same name.\n -d         Delete the members in <file_list>.\n -x         Extract members in <file_list> placing in files of the same name.\n -m         Move files in <file_list>.\n -p         Print files to stdout.\n -a pos     Insert/move files after file named <pos>.\n -b pos     Insert/move files before file named <pos>.\n -u         Update older files only, used with -r.\n\n -n         Do not add a symbol table to an object archive.\n -s         Force regeneration of archive symbol table.\n -t         Print table of contents of archive.\n--zs        Show the symbol table.\n--zt        Summarize the archive contents (sizes + entries).\n -c         Suppress warning when a new archive is created.\n -C         Do not overwrite existing files when extracting.\n -T         Truncate file names to system maximum length.\n -v         Give verbose output.\n--create    Force creation of a new archive.\n--via file  Take additional arguments from via file.\n--sizes     List the size of each member and the library total.\n--entries   List sections containing ENTRY points.\n--vsn       Print the current Armar Version. \n--help      Print this message. \n\nExamples:-\n\n        armar -r  mylib.a obj1 obj2 obj3...\n        armar -x  mylib.a ?sort*\n        armar -d  mylib.a hash.o\n        armar -tv ansilib.a\n\n" err='Error: L6839E: One of the actions -[dmpqrtx] must be specified\n'
```

The `linker_name` is `armar`, but `returncode` is 1. Hence, it falls to `_handle_exceptions()` handler.
