### ISSUE TITLE
add remaining --sbindir & Co.

### ISSUE THREAD

**Issue by ignatenkobrain** [mesonbuild/meson#1190]
I think we still miss:
* sbindir (/usr/sbin)
* sharedstatedir (/var/lib)
* infodir (/usr/share/info)

**Comment by nirbheek** [comment]
I didn't even know that. I think no distro or package in the entire world uses `$prefix/com`.

**Comment by ignatenkobrain** [comment]
I think also will be useful to add runstatedir (which is $localstatedir/run, i.e. /var/run)

**Comment by QuLogic** [comment]
`docdir` too please (#825).

**Comment by ignatenkobrain** [comment]
@QuLogic for $docdir hopefully we will have something like `--nodocs` or something like this. Because when upstream thinks that they know which docs to install, it's usually not true.

But yeah, will add it.

**Comment by ignatenkobrain** [comment]
$runstatedir is a bit more complicated as its prefix is $localstatedir, not the $prefix. @jpakkane any suggestions how to handle this?

**Comment by jpakkane** [comment]
Will it be like the others where it is always set from the outside by the package builder?

**Comment by ignatenkobrain** [comment]
@jpakkane No, it's mostly never be touched. localstatedir is $prefix/com which will be overridden and this option should be $localstatedir/run

**Comment by jpakkane** [comment]
I'm fine with having some default value and then having the package builder set it manually and not doing any magic where we try to expand runstatedir automagically from localstatedir. That is, users will need to do something like:

    meson -Dlocalstatedir=/var -Drunstatedir=/var/run [other args]
