### ISSUE TITLE
`install_data()` default destination directory in subprojects

### ISSUE THREAD

**Issue by dnicolodi** [mesonbuild/meson#11910]
The default `install_dir` for `install_data()` is documented to be `{datadir}/{projectname}` thus I would expect the following calls to install in the same directory:
```
install_data('foo')
install_data('bar', install_dir: get_option('datadir') / meson.project_name())
```
However, when the following snippet appears in a Meson project installed as subproject, they do not. The default `install_dir` is derived from the parent project name.

I've verified this with the current git master.

**Comment by eli-schwartz** [comment]
I would expect the same thing. This is bad because a project that uses install_data with a default install_dir will behave normally by default, but behave incorrectly when used as a wrapped subproject.

**Comment by jpakkane** [comment]
Yes, definitely a bug.

**Comment by dnicolodi** [comment]
I found another issue:
```meson
install_data('foo/bar.txt', preserve_path: true)
```
installs `{datadir}/foo/bar.txt` but I would expect it to install `{datadir}/{projectname}/foo/bar.txt`.
