### ISSUE TITLE
compiler.preprocess does not generate rules for header files.

### ISSUE THREAD

**Issue by jeandudey** [mesonbuild/meson#11936]
**Describe the bug**

Currently I need to use `compiler.preprocess` to pass the resulting files to another tool to generate headers.

However, the code that needs to be pre-processed itself depends on other generated headers, and `compiler.preprocess` doesn't process header files, even if passed as a dependency instead of a source file, making it impossible to have a rule that the input .c sources depend on the header file that is generated.

This also happens with static (i.e. non-generated) headers as demonstrated in the `meson.build` present here.

**To Reproduce**

<details>
<summary>meson.build</summary>

```meson
project('bug', 'c')

python3 = find_program('python3')
cc = meson.get_compiler('c')

custom_target(
  'generated.h',
  input : cc.preprocess('header.h', output : '@PLAINNAME@.p'),
  output : 'generated.h',
  command : [python3, '-c', 'printf("output")'],
  capture : true,
  build_by_default : true,
)
```
</details>

<details>
<summary>Command-line reproduction</summary>

```
$ touch header.h
$ meson setup build
The Meson build system
Version: 1.1.1
Source dir: meson-bug
Build dir: meson-bug/build
Build type: native build
Project name: bug
Project version: undefined
C compiler for the host machine: gcc (gcc 12.3.0 "gcc (GCC) 12.3.0")
C linker for the host machine: gcc ld.bfd 2.38
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program python3 found: YES (/gnu/store/v2zydxzb0nmh295cqmda32ilmali98pr-profile/bin/python3)
Build targets in project: 2

Found ninja-1.11.1 at /gnu/store/v2zydxzb0nmh295cqmda32ilmali98pr-profile/bin/ninja
$ ninja -C build
ninja: Entering directory `build'
ninja: error: 'preprocessor_0.p/header.h.p', needed by 'generated.h', missing and no known rule to make it
```
</details>

**Expected behavior**

That `compiler.preprocess` processes header files, and/or accept dependencies that have generated header files.

**system parameters**
* GNU Guix.
* Python 3.10.7.
* Meson 1.1.1.
* Ninja 1.11.1.

**Comment by xclaesse** [comment]
I believe this is already fixed by https://github.com/mesonbuild/meson/pull/11424. Can you try Meson 1.1.2 or 1.2.0 please?

**Comment by jeandudey** [comment]
@xclaesse I didn't found a tag for v1.1.2 but I tested with latest master commit c34ee374a77fb2dffff90364506ac0cbbb1f00de and the error doesn't happen anymore.

**Comment by xclaesse** [comment]
> I didn't found a tag for v1.1.2

Ah right we stopped at 1.1.1 indeed. Maybe @nirbheek will make that point release later, dunno what are his plans. Thanks for confirming it's already fixed :)
