### ISSUE TITLE
Add ability to selectively install and refer to outputs of custom_targets

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#1193]
Currently, the `install` and `install_dir:` kwargs to `custom_target` install all the outputs into the specified directory. This is not always desired, for instance sometimes a single command generates sources to be compiled and headers to be installed.

**Comment by nirbheek** [comment]
We also need the ability to select subsets of the outputs of `custom_target`s. For instance, in libepoxy we have a script that generates headers and sources that are to be compiled. These headers are needed for anything that uses libepoxy itself (such as tests).

Normally, you'd just add the headers to the list of sources for each test or you'd add it to the `sources:` kwarg in `declare_dependency` for libepoxy. However we can't do that here because the `custom_target`s that build the headers also generate C sources and adding them to either of those will result in a bad outcome.

If we could filter out the outputs that we're using, we could still do this. Something like:

```
gensrc = custom_target(...)

executable('some-test', 'test.c', gensrc.out('*.h'))
```

`gensrc.out()` would return all the outputs as a list.

**Comment by jpakkane** [comment]
Let's not do wildcards if at all possible. Since we know the list of files a custom target outputs, maybe we can do something like this instead:

    custom_target(..., #outputs foo.c, foo.h and internal.h that needs to go to a subdir
      install : true,
      install_dir : ['', 'include', 'include/somesubdir'], # The .c file is not installed.
    )

**Comment by nirbheek** [comment]
That covers installation, but doesn't cover adding it to some other build target as sources (for generated headers). The wildcard is just convenience really; just implementing `gensrc.out()` which is a list of all outputs in the order in which they're listed is enough.

**Comment by ditsuke** [comment]
> We also need the ability to select subsets of the outputs of `custom_target`s. For instance, in libepoxy we have a script that generates headers and sources that are to be compiled. These headers are needed for anything that uses libepoxy itself (such as tests).
> 
> Normally, you'd just add the headers to the list of sources for each test or you'd add it to the `sources:` kwarg in `declare_dependency` for libepoxy. However we can't do that here because the `custom_target`s that build the headers also generate C sources and adding them to either of those will result in a bad outcome.
> 
> If we could filter out the outputs that we're using, we could still do this. Something like:
> 
> ```
> gensrc = custom_target(...)
> 
> executable('some-test', 'test.c', gensrc.out('*.h'))
> ```
> 
> `gensrc.out()` would return all the outputs as a list.

Hi, I found this issue while looking into expressing header-only dependencies from a set that includes source files. How would we accomplish this in meson 1.2.x?

**Comment by eli-schwartz** [comment]
I'm a bit confused since I thought you could already just use the indexes of the return value, as directly associated with the order of `output: [...]` items.

**Comment by dcbaker** [comment]
This is solved by indexing the outputs of the custom_target

```meson
x = custom_target(..., outputs : ['1.h', '1.c', '2.h'])
executable('some-test', 'test.c', x[0], x[2])
```

**Comment by ditsuke** [comment]
@eli-schwartz @dcbaker I moved on from this issue for a while due to a shift of priorities. Looking back, thank you for the help! Indexing into the outputs certainly works, though I can't help but feel that it's not very ergonomic.

**Comment by dcbaker** [comment]
It's not, but the usual way to handle this is to use declare dependency:
```meson
ct = custom_target(..., outputs : ['1.h', '1.c', 2.h'])
dep_ct = declare_dependency(sources : [ct[0], ct[2]])
exe = executable(..., dependencies : dep_ct)
```
This is also useful if you generate a static library from the `1.c`)
```meson
ct = custom_target(..., outputs : ['1.h', '1.c', 2.h'])
lib1 = static_library('lib1', ct)
dep_ct = declare_dependency(sources : [ct[0], ct[2]], link_with : lib1)
exe = executable(..., dependencies : dep_ct)
```

**Comment by ditsuke** [comment]
I really like the `declare_dependency` idiom! Dare I say it could be even nicer if we could filter targets besides indexing:
```meson
ct = custom_target(..., outputs : ['1.h', '1.c', 2.h'])
dep_ct = declare_dependency(sources : ct.out('*.h'))
exe = executable(..., dependencies : dep_ct)
```
