### ISSUE TITLE
Meson won't generate header dependency files for CUDA source files.

### ISSUE THREAD

**Issue by MiroPalmu** [mesonbuild/meson#11969]
**Describe the bug**
When building CUDA executable header dependency files are not generated using nvcc, so updating headers won't trigger rebuild.

In the generated build.ninja file we can see that there is no compiler flags for nvcc to generate the dependency files:

```
# Rules for compiling.

rule cuda_COMPILER
 command = nvcc $ARGS -o $out -c $in
 deps = gcc
 depfile = $DEPFILE_UNQUOTED
 description = Compiling Cuda object $out
```

even if the targets specifies these non-generated dependency files: 

```
# Build rules for targets

build FOO.p/main.cu.o: cuda_COMPILER ../main.cu
 DEPFILE = FOO.p/main.cu.o.d
 DEPFILE_UNQUOTED = FOO.p/main.cu.o.d
 ARGS = -IFOO.p -Xcompiler=-Minform=inform -g -G -g -I../include -I.. -I. -IFOO.p
```

**To Reproduce**
Folder with following structure:

main.cu
include/Foo.hpp
meson.cpp

where main.cu is:

```
#include "Foo.hpp"

int main() {
	Foo();
}
```

include/Foo.hpp is:

```
#include <iostream>

void Foo() {
	std::cout << "Hello from Foo\n";
}
```

meson.build is:

```
project('example', 'cuda')

executable('FOO', 'main.cu', include_directories : ['include'])
```

To initialize build folder:
```
meson setup build
```

**Expected behavior**
Meson to specify compiler flags for nvcc to generate the dependency files so modifying headers would trigger recompilations.
 
https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#generate-dependencies-m

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
native

* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
Red Hat Enterprise Linux 8.6 (Ootpa)

* what Python version are you using e.g. 3.8.0
Python 3.10.12

* what `meson --version`
1.1.1

* what `ninja --version` if it's a Ninja build
1.12.0.git

**Comment by eli-schwartz** [comment]
Unfortunately, it does not work. See some prior attempts to fix this:
#4991
#10993
#11229

Discussion from the original cuda support issue: https://github.com/mesonbuild/meson/issues/1003#issuecomment-259103463

**Comment by steef435** [comment]
This does not seem to work yet. Is this not planned for a 1.3.x?

If it is not going to land soon, might it be worth it to note this somewhere visible, maybe in the docs of the CUDA module? It took me some time to realize what was going wrong, and to find this issue.

**Comment by eli-schwartz** [comment]
The linked ticket is not tagged for backporting.

Note that 1.4.0 is in the works.

**Comment by steef435** [comment]
Ah, good to know. Then I won't bother you with a docs PR, haha. Thank you!
