### ISSUE TITLE
Multi-level generators seem broken

### ISSUE THREAD

**Issue by mortie** [mesonbuild/meson#11966]
**Describe the bug**

From the documentation, it seems like the intention is that `generator(...).process()` should be able to take a generator_list. However, this seems broken. In my testing, Meson accepts a generator_list as a parameter to process(), but then generates an invalid build.ninja file.

**To Reproduce**

Create two generators, where you call process() on the second with the generator_list from the first, like this:

```
generated_protos = generator(
  find_program('sh'),
  output: ['@BASENAME@_modified.proto'],
  arguments: [
    '-c',
    'sed "s/package internal/package whatever/" "$0" > "$1"',
    '@INPUT@', '@OUTPUT@'
  ],
).process([
  'proto/bar/bar.proto',
  'proto/foo/foo.proto',
])

proto_srcs = generator(
  find_program('cp'),
  output: ['@PLAINNAME@.cc'],
  arguments: ['@INPUT@', '@OUTPUT@'],
).process(generated_protos)
```

Alternatively, clone this test repo I created: https://github.com/mortie/meson-bug

    git clone https://github.com/mortie/meson-bug.git
    cd meson-bug
    meson setup build
    ninja -C build

The `meson setup build` will succeed, but the `ninja -C build` will fail with:

    ninja: error: 'bar_modified.proto', needed by 'hello.txt.p/bar_modified.proto.cc',
    missing and no known rule to make it

**Expected behavior**

Meson should generate a build.ninja which causes ninja to first run the first generator on the source files, then run the second generator on the output of the first generator.

Alternatively, if this shouldn't work or can't be made to work, the docs should be updated to make it clear that `generator().process()` can't take a generator_list, and meson should complain about a broken meson.build.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
  * Native build
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
  * macOS Ventura 13.4.1
* what Python version are you using e.g. 3.8.0
  * 3.11.4
* what `meson --version`
  * 1.1.1
* what `ninja --version` if it's a Ninja build
  * 1.11.1

**Comment by tristan957** [comment]
@mortie do the first set of generated files even exist on your system after calling build? Trying to determine if this is just a path issue within meson or a build dependency issue.

**Comment by tristan957** [comment]
Are you able to work around this with custom_targets?

**Comment by Volker-Weissmann** [comment]
This was fixed by https://github.com/mesonbuild/meson/pull/11654

**Comment by dcbaker** [comment]
I’m going close then, if this is still an issue with 1.2.0 please reopen

**Comment by mortie** [comment]
I can confirm that this is fixed in the master branch.
