### ISSUE TITLE
Clock skew only on encrypted HDD/SSD (Windows)

### ISSUE THREAD

**Issue by Extevious** [mesonbuild/meson#11991]
**Describe the bug**
Similar issue: #7275

`ERROR: Clock skew detected. File \.build\win32\meson-private/coredata.dat has a time stamp 0.7551s in the future.`

I have multiple projects that use Meson and they all suffer from this clock skew issue. I've done some testing, and from what I've found is it only happens on an encrypted storage drive, regardless if it's externally or internally mounted. The only exception is if I call Meson on a project that is on the same drive as the OS.

Clock skew ranges from anywhere between 0.01s to 2.5s.

I do not have this issue with Linux using VeraCrypt, only on windows using BitLocker or VeraCrypt.

**To Reproduce**
```meson
project('testproj', 'Cpp')

executable('testproj', 'main.cpp')
```

```cpp
#include <cstdio>

int main()
{
    std::printf("Hello world!");

    return 0;
}
```

**Expected behavior**
No clock skew error.

**system parameters**
- Native build
- Windows 11 Pro 64-bit 10.0.22621 Build 22621 (BitLocker encrypted)
- Python 3.11.4
- Meson 1.1.1
- Ninja 1.11.1
- msvc 19.36.32537
- Clang 16.0.0

**Comment by Kagetsuki** [comment]
I have a strong suspicion this isn't the fault of Meson but rather the fault of whatever abstraction is going on in Windows on encrypted volumes. If you haven't already you may want to post about this issue on some Windows/VeraCrypt related forums.

I hesitate to say this is not Meson related, but the file you pointed out `meson-private/coredata.dat` is a file generated by Meson. Just to clarify though, does this occur with any other generated file? And have you seen anything similar with other software?

**Comment by Extevious** [comment]
> I have a strong suspicion this isn't the fault of Meson but rather the fault of whatever abstraction is going on in Windows on encrypted volumes. If you haven't already you may want to post about this issue on some Windows/VeraCrypt related forums.
> 
> I hesitate to say this is not Meson related, but the file you pointed out `meson-private/coredata.dat` is a file generated by Meson. Just to clarify though, does this occur with any other generated file? And have you seen anything similar with other software?

Sorry for the late reply, but I'm only getting the error with the `meson-private/coredata.dat` file, and I don't have any similar issue(s) with other software. I'll look into seeing if the Windows forums can shed some light on this issue.
