### ISSUE TITLE
Fails to install via pip3 on Ubuntu 23.04

### ISSUE THREAD

**Issue by ChaseKnowlden** [mesonbuild/meson#12002]
**Describe the bug**
When I run `python3 -m pip install meson` it throws an error saying externally-managed-environment

**To Reproduce**
`python3 -m pip install meson`

**Expected behavior**
It should install meson without issues.

**system parameters**
* Plain Native build
* Ubuntu 23.04
* Python 3.11.4
* Meson 1.1.1
* Ninja 1.11.1

**Comment by eli-schwartz** [comment]
> When I run `python3 -m pip install meson` it throws an error saying externally-managed-environment

An externally-managed-environment means that pip has encouraged Ubuntu to declare a policy that Ubuntu will not allow users to install software with pip. Please submit a bug report to:
- Ubuntu
- pip

Also please note that this happens for ALL uses of pip, it has nothing to do with meson specifically. There is nothing we can do, other than hope that Ubuntu/pip changes its mind in the future.

I'm sorry. :(
