### ISSUE TITLE
When building a python c-extension using the limited_api, windows should link with python3.lib

### ISSUE THREAD

**Issue by mattip** [mesonbuild/meson#12008]
**Describe the bug**
In `dependencies/python.py:PythonSystemDependency::get_windows_link_args()`, the [link library](https://github.com/mesonbuild/meson/blob/9d88d0d5cc92de04cb33cac4ddaedff622b65c40/mesonbuild/dependencies/python.py#L280) will always be `pythonxy.lib` where `xy` is `311`. But when building a c-extension using the limited api (i.e. `-DPy_LIMITED_API=0x03060000`) the name should be `python3.lib`

**To Reproduce**
This is from PR numpy/numpy#24206 where I am converting an existing test that uses setup.py to meson.

```
project('limited_api', 'c', 'cython')

py_mod = import('python')
py3 = py_mod.find_installation(pure: false)

cc = meson.get_compiler('c')

npy_include_path = run_command(py3, ['-c',
               'import os; os.chdir(".."); import numpy; print(os.path.abspath(numpy.get_include()))'],
                         check: true).stdout().strip()

py3.extension_module(
    'limited_api',
    'limited_api.c',
    install: false,
    c_args: [
      '-DNPY_NO_DEPRECATED_API=0',  # Cython still uses old NumPy C API
      '-DPy_LIMITED_API=0x03060000',
    ],
    include_directories: [npy_include_path],
)
```

**Expected behavior**
There should be a way to tell meson to build limited_api c-extensions.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? __native build__
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) __windows__
* what Python version are you using e.g. 3.8.0 __3.11__
* what `meson --version` __latest__
* what `ninja --version` if it's a Ninja build __from PyPI__

**Comment by eli-schwartz** [comment]
This exact feature is being prototyped by @amcn in #11745, please provide feedback.

**Comment by mattip** [comment]
thanks. I searched the issues but not the PRs.
