### ISSUE TITLE
Python: Limited C API support

### ISSUE THREAD

**Issue by igo95862** [mesonbuild/meson#12029]
Python documentation describing the limited API: https://docs.python.org/3/c-api/stable.html#stable-application-binary-interface

Basically this will allow the Python C extension to be forward compatible. This requires the `Py_LIMITED_API` macro to be set and the extension have the `.abi3.so` suffix. 

I tried using the `name_suffix` but it is disabled for `extension_module`.

```meson
sd_bus_internals_module = python.extension_module(
    'sd_bus_internals',
    sd_bus_internals_sources,
    dependencies : libsystemd_dep,
    c_args : ['-DPy_LIMITED_API=0x03070000'],
    install : true,
    subdir : 'sdbus',
    name_suffix : 'abi3'
)
```

Maybe it is worth support it in python module? For example, a new option `limited_api : '3.7'` would set the limited api to python 3.7 and put the `abi3.so` suffix.

**Comment by igo95862** [comment]
I found a merge request that implements this: https://github.com/mesonbuild/meson/pull/11745

**Comment by eli-schwartz** [comment]
Also #12008
