### ISSUE TITLE
Add_languages is not working for Vala

### ISSUE THREAD

**Issue by tintou** [mesonbuild/meson#12046]
**Describe the bug**

After using `add_languages`, I'm unable to 

**To Reproduce**
Here is a simple meson.build to reproduce it:
```
project('test', 'c')

add_languages('vala', native: true)

executable('test',
    'testapp.vala'
)
```

**Expected behavior**
testapp.vala is being built

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
 Native build
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
Ubuntu 22.04
* what Python version are you using e.g. 3.8.0
3.10.6
* what `meson --version`
1.2.0
* what `ninja --version` if it's a Ninja build
1.10.1

The output I'm getting:
```
The Meson build system
Version: 1.2.0
Source dir: /home/tintou/Projects/test
Build dir: /home/tintou/Projects/test/build
Build type: native build
Project name: test
Project version: undefined
C compiler for the host machine: cc (gcc 11.3.0 "cc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0")
C linker for the host machine: cc ld.bfd 2.38
Host machine cpu family: x86_64
Host machine cpu: x86_64

meson.build:5:0: ERROR: No host machine compiler for 'testapp.vala'
```

**Comment by tintou** [comment]
Removing `native: true` works though

**Comment by tintou** [comment]
Okay that was it, don't mind me…

**Comment by dcbaker** [comment]
Yeah, in this case you're adding a compiler for the build machine, but then defining a target for the host machine. It might be worth adding an extra error message like "No vala compiler for host machine, but there is one for the build machine, do you have mismatched `native : ` arguments?" on our end to help debug this.
