### ISSUE TITLE
pkgconfig: accept another PkgConfigDependency as requires argument

### ISSUE THREAD

**Issue by ignatenkobrain** [mesonbuild/meson#1204]
Something like:
```meson
pkgg = import('pkgconfig')
openssl = dependency('openssl')
foo_pc = pkgg.generate(name : 'foo', requires : openssl)
bar_pc = pkgg.generate(name : 'bar', requires: foo_pc)
```

Which would create `foo.pc` with `Requires: openssl` and `bar.pc` with `Requires: foo`.

**Comment by nirbheek** [comment]
Ideally this should be done automatically. The current API for generating a pkg-config file is suboptimal as it forces you to duplicate the list of libraries needed by the module. We should be able to auto-generate the `Libs:`, `Requires:`, and `Libs.private:` fields from a `declare_dependency()` object.
