### ISSUE TITLE
Compile .hpp files into objects

### ISSUE THREAD

**Issue by r-devulap** [mesonbuild/meson#12061]
On the command line, I can compile a `.hpp` file into an object with: 

`g++ -c -x c++ -fpic myheader.hpp -o myheader.o`

How do I get meson to do this? I couldn't get `static_library` or `shared_library` to work.

**Comment by r-devulap** [comment]
Work around I am using now is to create a `temp.cpp` with just 1 line: `#include "myheader.hpp"` and compile this into a `static_library`. This obviously needs creating a new unnecessary file and I would like to avoid it.

**Comment by eli-schwartz** [comment]
If you have to pass `-x c++` doesn't that mean that the file is incorrectly named and it's not a header, and shouldn't be named `.hpp`?

What was the original motivation to name it that instead of `.cpp`?

**Comment by r-devulap** [comment]
These we originally meant to be just header files to be included and built within other libraries. But I would like build a shared library out of all the header files.

**Comment by sammyj85** [comment]
But then other source files which include the headers will get the full definitions of all the entities, so linking with the shared library will be useless. The headers are written incorrectly if you want to create a shared library.

**Comment by r-devulap** [comment]
I am not sure I understand your concern. Including a header file and linking to shared library built using those header files are two separate ways to consume a library. I need a way to build a shared library out of the header files in meson.

**Comment by eli-schwartz** [comment]
It's not a header file.

It's a somewhat odd example of https://mesonbuild.com/Unity-builds.html

You can just go:
```
mv myheader.hpp mylibrary.cpp
g++ -c -fpic mylibrary.cpp -o mylibrary.o
````

You can also update your other files that currently include myheader.hpp, to have them do this instead:
```c
#include "mylibrary.cpp"
```

This is the standard way to do unity builds, not naming your source files *.hpp

**Comment by r-devulap** [comment]
Thanks.
