### ISSUE TITLE
rust.bindgen doesn't respect project wide default options

### ISSUE THREAD

**Issue by karolherbst** [mesonbuild/meson#12065]
**Describe the bug**
Meson projects generally set the C/C++ std via default project options. When invoking `rust.bindgen` those options aren't respected which might lead to compilation errors, when e.g. headers requiring C++17, but the default version of clang is something lower.

**To Reproduce**
https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/24386/diffs?commit_id=b6df9b6ee1933fb78245b260f54e7d28f6979f6b

**Expected behavior**
rust.bindgen should add the relevant `c_args` and `cpp_args` default options (depending on input file) to clang.

**system parameters**
meson 1.2.0

**Comment by tristan957** [comment]
Adding it to the 1.2.1 milestone for now, but it might get shifted to 1.3.0 depending on if others agree this would be a bugfix. I am sure dcbaker can take a look when he is back at work next week.

**Comment by eli-schwartz** [comment]
> When invoking rust.bindgen those options aren't respected which might lead to compilation errors, when e.g. headers requiring C++17, but the default version of clang is something lower.

This appears to be the wrong solution entirely, unless we can actually guarantee that bindgen accepts all arguments that the C++ compiler accepts, no ifs ands or buts.

Even then it seems to be an... overly broad solution. Bindgen doesn't compile anything IIRC, so we do not want most arguments, only a limited number of arguments that come directly from the project definitions (so definitely no environment *FLAGS), and I'd expect those to be directly copied over as arguments to the bindgen function.

Apparently we cannot guarantee any such thing, because this did not fix building mesa, it broke building mesa: https://bugs.gentoo.org/914989

**Comment by karolherbst** [comment]
> > When invoking rust.bindgen those options aren't respected which might lead to compilation errors, when e.g. headers requiring C++17, but the default version of clang is something lower.
> 
> This appears to be the wrong solution entirely, unless we can actually guarantee that bindgen accepts all arguments that the C++ compiler accepts, no ifs ands or buts.
> 
> Even then it seems to be an... overly broad solution. Bindgen doesn't compile anything IIRC, so we do not want most arguments, only a limited number of arguments that come directly from the project definitions (so definitely no environment *FLAGS), and I'd expect those to be directly copied over as arguments to the bindgen function.
> 
> Apparently we cannot guarantee any such thing, because this did not fix building mesa, it broke building mesa: https://bugs.gentoo.org/914989

yeah, I already pinged @dcbaker on this on IRC: 

```
mhhh.. so https://github.com/mesonbuild/meson/commit/36210f64f22dc10d324db76bb1a7988c9cd5b14e added some very annoying behavior. The build system generally checks through meson if certain compiler flags are recognized, and if they assume they have gcc/msvc/whatever, they'll simply add those even globally, but that screws around with clang :')
[11:32] <karolherbst> the question is reather, as it's causing a regression, do we have to opt in on the bindgen callside instead? like add a "inherit-c-flags": ["global"|"project"|"cli"], and then projects can manage what they'll want inherited by themselfs
[11:32] <karolherbst> in mesa it's causing issues with `-mtls-dialect=gnu2` and some warnings we disabled, though only the former is causing errors
```

**Comment by dcbaker** [comment]
I was thinking about this this morning. It probably makes sense to limit this just to a handful of arguments, maybe -D and -I arguments?

> Even then it seems to be an... overly broad solution. Bindgen doesn't compile anything IIRC, so we do not want most arguments, only a limited number of arguments that come directly from the project definitions (so definitely no environment *FLAGS), and I'd expect those to be directly copied over as arguments to the bindgen function.
 
I think that having CFLAGS though is essential in this case, if a user passes -I or -D options that affect the way C uses a given header and bindgen doesn't take that into account we could end up with broken bindings.

**Comment by karolherbst** [comment]
> I was thinking about this this morning. It probably makes sense to limit this just to a handful of argument types, maybe -D and -I arguments, plus the relevant C standard.
> 
> > Even then it seems to be an... overly broad solution. Bindgen doesn't compile anything IIRC, so we do not want most arguments, only a limited number of arguments that come directly from the project definitions (so definitely no environment *FLAGS), and I'd expect those to be directly copied over as arguments to the bindgen function.
> 
> I think that having CFLAGS though is essential in this case, if a user passes -I or -D options that affect the way C uses a given header and bindgen doesn't take that into account we could end up with broken bindings.

yeah, I guess limiting this to any flags which matter on a preprocessor level is probably enough. For C++ headers it might also be relevant to pass in any ABI or symbol mangling related flags in case STL types are part of the API or something.
