### ISSUE TITLE
`dependency('vulkan', version: ['>=1.X.X'])` fails on Windows

### ISSUE THREAD

**Issue by LDAP** [mesonbuild/meson#12072]
**Describe the bug**
`dependency('vulkan',  version: ['>=1.3.0'])` fails on Windows if a version is specified.
The Vulkan SDK is installed, and the environment variable (`VULKAN_SDK=C:\VulkanSDK\1.3.250.1`) is set.

Edit: The same does work on Linux.

**To Reproduce**
Install a recent Vulkan SDK (>= 1.3.0) and use this meson.build:
```python
project('test-project', 'cpp')

# this does not work
vulkan = dependency('vulkan', version: ['>=1.3.0'])
# this does work
# vulkan = dependency('vulkan')

executable('test-project', ['main.cpp'], dependencies : [vulkan])
```

**Expected behavior**
Vulkan is detected correctly.

**system parameters**
* native build
* Windows 11
* Python 3.9.13
* Meson 1.2.0
* Ninja 1.11.0

**Comment by eli-schwartz** [comment]
https://github.com/mesonbuild/meson/blob/cdef6741698d98453142cb2a0b65c72676dbb259/mesonbuild/dependencies/ui.py#L239-L240

I suppose that that never got implemented... AFAIK there's no actual SDK version inside of a header somewhere, right?

**Comment by LDAP** [comment]
There is, but it would have to be extracted from multiple defines: https://github.com/KhronosGroup/Vulkan-Headers/blob/a3b683653e6a498514ef8a1865594810e91c594c/include/vulkan/vulkan_core.h#L75

I would prefer meson would warn that the version could not be determined instead of failing.

**Comment by tristan957** [comment]
@LDAP Meson has `compiler.get_define()`, which we could use on all platforms, and fallback to file path if not found. Wanna submit a PR?

**Comment by LDAP** [comment]
Is there a way to do this as part of a meson setup?

**Comment by tristan957** [comment]
Yes if you do a cc.compiles()

**Comment by LDAP** [comment]
I am looking into this.
