### ISSUE TITLE
Ability to configure project without a language

### ISSUE THREAD

**Issue by TingPing** [mesonbuild/meson#1208]
The use case would be something like a Gnome application written purely in a scripting language such as Python. As such it never needs a C compiler to build any libraries but it is still far more useful than setuptools because you have easy access to building GResource files, configuring desktop files, handling translations, and it isn't setuptools which is awful.

**Comment by ignatenkobrain** [comment]
wanted to file this issue long time ago ;) It's useful for wayland projects as well, since it's only XMLs are processed there.

**Comment by freddy77** [comment]
Just tried with 0.53.1, does not work, still try to find gcc.
