### ISSUE TITLE
buildtype does not get deduced from debug and optimization options

### ISSUE THREAD

**Issue by kiwixz** [mesonbuild/meson#12096]
**Describe the bug**
The doc says there is a two-way binding but in practice this doesn't work.  It's a big problem with some modules relying on the `buildtype` to guess what to do.  For example, CMake will happily use the debug libraries when you specified `-Ddebug=false --optimization=3` because `buildtype` still defaults to `debug`...

Edit: it looks like meson also use the `debug` option to guess sometimes!

Please also make it clear in the doc that some modules depend on the buildtype.

**To Reproduce**
With any meson.build, example:
```
project('')
```

- Configure with `meson setup build -Ddebug=false --optimization=3`, `buildtype` will be `debug` instead of `release`.
- Configure with `meson setup build --optimization=2`, `buildtype` will be `debug` instead of `debugoptimized`.

You can inspect it with `meson configure build`.

**System parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?  Plain
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)?  Debian 12
* what Python version are you using e.g. 3.8.0?  3.11.2
* what `meson --version`?  I tested 1.0.1 and master.

**Comment by bruchar1** [comment]
Duplicates #11645
