### ISSUE TITLE
Totally silent inside `meson.add_install_script`

### ISSUE THREAD

**Issue by goulf-3m** [mesonbuild/meson#12102]
Unless there's error exit, nothing in the script is shown (stdout/stderr). Nothing saved somehow neither.

Very annoying if the script exits with 0, but there is a bug inside.
Especially in some complex environment where it is not easy to directly call the script.

Throw away ordinary output is OK. But do not discard error message by default!

(Not just by default. Seems no way to get the output without modifying meson.)

**Comment by kiwixz** [comment]
Please use the issue template...  Output is actually printed on latest meson.
