### ISSUE TITLE
Additional warning flags are added to compile my own code when adding SDL2 dependency

### ISSUE THREAD

**Issue by Lisible** [mesonbuild/meson#12118]
Hello, 
I'm trying out Meson and when I add SDL2 as a dependency to my project, it adds additional warning flags when compiling my own code, such as -Wdeclaration-after-statement, is there a way to not inherit these warning flags?

This was done based on https://mesonbuild.com/GuiTutorial.html

My project directory structure is the following one
```
proj/builddir/
proj/subprojects/
proj/meson.build
proj/sample-app/meson.build
proj/sample-app/main.c
```

project/meson.build
```
project('proj', 'c', default_options: ['c_std=c17'])
sdl2_dep = dependency('sdl2')
subdir('sample-app')

```

project/sample-app/meson.build
```
executable('sample-app', 'main.c', win_subsystem: 'windows', dependencies: sdl2_dep)

```

proj/builddir/build.ninja
```
[...]
build sample-app/sample-app.p/main.c.o: c_COMPILER ../sample-app/main.c
 DEPFILE = sample-app/sample-app.p/main.c.o.d
 DEPFILE_UNQUOTED = sample-app/sample-app.p/main.c.o.d
 ARGS = -Isample-app/sample-app.p -Isample-app -I../sample-app -Isubprojects/SDL2-2.28.1/include -I../subprojects/SDL2-2.28.1/include -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/ibus-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/lib64/libffi/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/pipewire-0.3 -I/usr/include/spa-0.2 -I/usr/include/libusb-1.0 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c17 -O0 -g -D_REENTRANT -pthread -msse3 -Wno-deprecated-declarations -Wdeclaration-after-statement -Wshadow -fno-strict-aliasing
[...]
```

I'm using meson 1.2.0, I have the same issue with older versions.

**Comment by eli-schwartz** [comment]
proj/builddir/meson-logs/meson-log.txt will have enhanced debugging info about the configure run. My suspicion is that sdl2 lists this flag as one of the flags that are "required" for compiling against the sdl2 headers.

**Comment by Lisible** [comment]
Thank you for the quick reply, you seem to be right. 

The sdl2_dep is declared with these flags as compile_flags in SDL2's meson.build.

**Comment by tristan957** [comment]
Are we good to close this since it is an SDL2 issue?

**Comment by Lisible** [comment]
Yes. I think we are good.
