### ISSUE TITLE
meson does not find boost modules provided by conan on MSVC in debug configuration

### ISSUE THREAD

**Issue by domin144** [mesonbuild/meson#12117]
**Describe the bug**
When trying to build a project with dependency to boost and boost modules requiring linking,
meson is not able to find any libraries.

**To Reproduce**
meson.build
```
project('boost_test ', 'cpp')

boost_dep = dependency('boost', version : '>=1.73', modules : ['filesystem'])

executable(
    'boost_test',
    'main.cpp',
    dependencies : [boost_dep],
    install: true)
```
conanfile.py
```
from conan import ConanFile
from conan.tools.meson import MesonToolchain, Meson
from conan.tools.gnu import PkgConfigDeps


class boost_testConan(ConanFile):
    name = "boost_test"
    version = "1.0"
    package_type = "application"

    # Binary configuration
    settings = "os", "compiler", "build_type", "arch"

    # Sources are located in the same place as this recipe, copy them to the recipe
    exports_sources = "meson.build", "src/*"

    requires = ["boost/[>=1.73]"]
    tool_requires = ["meson/[>=1.1.0]", "pkgconf/[>=1.9]"]

    def layout(self):
        self.folders.build = "build"

    def generate(self):
        deps = PkgConfigDeps(self)
        deps.generate()
        tc = MesonToolchain(self)
        tc.generate()

    def build(self):
        meson = Meson(self)
        meson.configure()
        meson.build()

    def package(self):
        meson = Meson(self)
        meson.install()
```
main.cpp
```
#include <iostream>
#include <boost/filesystem.hpp>

int main() {
    if (boost::filesystem::exists("test.txt"))
        std::cout << "file exists\n";
    else
        std::cout << "file does not exist\n";

    return 0;
}
```

The following command will fail on Windows, where visual studio is configured as default profile.
```
conan build . --output-folder builddir_debug --settings build_type=Debug
```
Error message is:
```
Run-time dependency Boost (missing: filesystem) found: NO (tried system)
..\..\meson.build:3:12: ERROR: Dependency "boost" not found, tried system
```

No issue is observed in release build type:
```
conan build . --output-folder builddir
```

**Expected behavior**
Meson should find the library files and the example should compile.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
native
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
Windows 10
* what Python version are you using e.g. 3.8.0
Python 3.11.4
* what `meson --version`
1.2.0
* what `ninja --version` if it's a Ninja build
1.11.1

**Comment by eli-schwartz** [comment]
Boost is complicated since upstream doesn't seem much interested in providing sane dependency lookups. I believe you have to set the boost_root environment variable to get anything useful out of it.

**Comment by domin144** [comment]
I compared the debug and release runs and found, that the libraries get filtered out in the debug configuration by this line in `mesonbuild\dependencies\boost.py`:
```
        libs = [x for x in libs if x.vscrt_matches(vscrt)]
```
Conan does not use any tags in library names, e.g. filesystem library is named `libboost_filesystem.lib`. As a result `runtime_debug` is not set. This works nice for release build, but for debug, this check in `vscrt_matches` fails:
```
return not self.runtime_static and self.runtime_debug
```

**Comment by domin144** [comment]
I think boost root directory is successfully recovered from `prefix` variable in `.pc` file generated by conan. I saw some report on this on github. This part seems to be working as expected.

**Comment by eli-schwartz** [comment]
Maybe @mensinda knows more about this...

**Comment by domin144** [comment]
When the check is overridden, the project compiles and runs fine, so I think conan provides correct library, but just without tags in the name.

**Comment by kiwixz** [comment]
Did you try playing with the [`layout`](https://github.com/conan-io/conan-center-index/blob/499445e03d9ddc8b9587e6ac6642617c12d39c97/recipes/boost/all/conanfile.py#L84C10-L84C16) option of the conan package ?

Boost's manual does expect you to have abi tags in libraries name (see [here](https://www.boost.org/doc/libs/1_83_0/more/getting_started/windows.html#library-naming)), so I think it's reasonable for meson to look for them.

**Comment by bruchar1** [comment]
See #11487. This is supposed to be fixed on conan side (https://github.com/conan-io/conan/issues/14049).

**Comment by bruchar1** [comment]
Oh, I didn't realized it was about `debug` libs... In that case, there is probably something to improve on meson side...

**Comment by domin144** [comment]
@kiwixz No, I have not tried the layout options. Thanks for suggestion. I will try this out and report back.
@bruchar1 Yes, this is a different issue. The prefix variable is recovered correctly here.

**Comment by domin144** [comment]
@kiwixz Adding:
```
[options]
boost*:layout=tagged
```
to the conanfile.txt solves the issue. The lib files get proper tags in names and meson happily accepts them.

The issue is solved, at least for me.
Anybody using the boost + conan + meson + windows configuration will have to do the same.
