### ISSUE TITLE
Implement install_script() and allow setting ownership + permission bits

### ISSUE THREAD

**Issue by ignatenkobrain** [mesonbuild/meson#1212]
basically it should be same as install_data(), but also set executable bit.

**Comment by ignatenkobrain** [comment]
1. implementation of install_data() removes executable bit somehow even if original file has it
2. it is useful for installing configure_file()'d, because usually *-config wrappers are coming with *-config.in

**Comment by TingPing** [comment]
I'd also want this exposed in `mesonintrospect --installed` in some form so Builder can tell the difference between data and scripts. On a related note `install_script()` might be a better name.

**Comment by nirbheek** [comment]
`install_script()` does sound like a better name because you're installing a script, not a binary.

**Comment by nirbheek** [comment]
One more thing: `configure_file()` has an `install:` kwarg, and it preserves the permissions of the input file to the output file, so for `*-config` files, that is how you do the installation.

**Comment by jpakkane** [comment]
If install_data removes executable bits, that is a bug that needs fixing. It should always preserve state bits.

**Comment by ignatenkobrain** [comment]
> If install_data removes executable bits, that is a bug that needs fixing. It should always preserve state bits.

Just realized that it's my fault.

**Comment by nirbheek** [comment]
We also need a mechanism to set at least ownership and permissions bits (if not more such as extended attributes) on installed data and scripts.

This is needed for setuid programs, because setting ownership on the source data is not possible, and setting permissions is sometimes not possible (file was checked in from Windows).

**Comment by nirbheek** [comment]
I think that with the new `install_mode:` kwarg to `install_data()`, we don't really need this anymore.
