### ISSUE TITLE
Document that dictionaries support [] indexing

### ISSUE THREAD

**Issue by bmerry** [mesonbuild/meson#12147]
**Describe the bug**
By experimentation I've determined that dicts can be indexed in the "usual" way of most programming languages (`d[key]`), but https://mesonbuild.com/Syntax.html#dictionaries never mentions this, nor does it show it in the examples.

**To Reproduce**
```
project('foo')
x = {'key': 'value'}
message(x['key'])
```

**Expected behavior**
Behaviour is as I "expect", but it's undocumented.

**system parameters**
* Not a cross build
* Ubuntu 22.04
* Python 3.10
* Meson 1.2.1

**Comment by xclaesse** [comment]
Indeed, PR welcome :)

**Comment by bmerry** [comment]
I feel like it should rather be documented by someone who knows what the intended/supported semantics are, instead of me trying to reverse engineer what's implemented. e.g. is it restricted to literal keys (as dictionary literals apparently used to be), what happens if the key doesn't exist, if you use a non-string key (including a disabler) etc, have any of these changed from previous versions etc.

**Comment by xclaesse** [comment]
Dictionary keys can only be strings, and `d['k']` has always been supported.
