### ISSUE TITLE
'clean' target fails when custom_target's output is a directory 

### ISSUE THREAD

**Issue by fatih-asici** [mesonbuild/meson#1220]
I can reproduce it with this test case: `test cases/common/131 custom target directory install`

It gives the following error:
```
[1/1] 'Cleaning'
FAILED: clean 
'ninja' '-t' 'clean'
ninja: error: remove(html): Directory not empty
Cleaning... 0 files.
ninja: build stopped: subcommand failed.
```

**Comment by nirbheek** [comment]
This is a Ninja thing apparently; on Linux it only removes empty directories on clean (https://github.com/ninja-build/ninja/issues/828). We will have to add our own tool that maintains a list of directories and deletes them.

We should also enable cleaning in the CI so we don't break this again.
