### ISSUE TITLE
meson.build:2030:22: ERROR: Expecting eol got eol_cont if build_tests[0] and ^

### ISSUE THREAD

**Issue by Marietto2008** [mesonbuild/meson#12200]
### Discussed in https://github.com/mesonbuild/meson/discussions/12199

<div type='discussions-op-text'>

<sup>Originally posted by **Marietto2008** September  2, 2023</sup>

I'm trying to configure and build libvirt from source on Debian Buster on top of my ARM Chromebook,but I've got an error that I'm not able to fix :

```
# git clone https://github.com/libvirt/libvirt.git
Cloning into 'libvirt'...

# cd libvirt

# meson setup build

The Meson build system 
Version: 0.49.2 
Source dir: /home/marietto/Dati/virt/libvirt 
Build dir: /home/marietto/Dati/virt/libvirt/build 
Build type: native build

meson.build:2030:22: ERROR:  Expecting eol got eol_cont. 
if build_tests[0] and ^
```

Someone can help ? thanks.</div>

**Comment by eli-schwartz** [comment]
No need to open both a bug report and a Q&A discussion.
