### ISSUE TITLE
Superproject polluting subprojects' build options inconsistently

### ISSUE THREAD

**Issue by amyspark** [mesonbuild/meson#12202]
**Describe the bug**

Meson propagates default options from the root project down superprojects. However, this is not respected when it comes to (at least) compiler options. These are correctly expressed at configuration time, but at build time they're taken from **the subprojects' `default_options`**.

**To Reproduce**

Try building https://github.com/amyspark/meson-bug-subprojects-cppstd .

**Expected behavior**

Build should not error out with 

```
FAILED: subprojects/x/libx.a.p/x.cpp.obj
"cl" "-Isubprojects\x\libx.a.p" "-Isubprojects\x" "-I..\subprojects\x" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/Zc:__cplusplus" "/W2" "/EHsc" "/std:c++14" "/permissive-" "/Od" "/Zi" "/Fdsubprojects\x\libx.a.p\x.cpp.pdb" /Fosubprojects/x/libx.a.p/x.cpp.obj "/c" ../subprojects/x/x.cpp
../subprojects/x/x.cpp(2): fatal error C1189: #error:  "You should not see this"
ninja: build stopped: subcommand failed.
```

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? Native build
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) Windows 10 22H2
* what Python version are you using e.g. 3.8.0 3.10.7
* what `meson --version` 1.2.0
* what `ninja --version` if it's a Ninja build 1.11.1

**Comment by amyspark** [comment]
https://github.com/mesonbuild/meson/blob/156a9baab5f8b62d6a54f26fd361b493d1ddad4c/mesonbuild/backend/backends.py#L996-L998

should read

```python
        # Add compile args for c_* or cpp_* build options set on the
        # command-line, inherited from superproject, or default_options inside
        # project().
        commands += compiler.get_option_compile_args(self.environment.coredata.options)
```

The latter is the source of truth for compiler checks -- see https://github.com/mesonbuild/meson/blob/master/mesonbuild/interpreter/compiler.py#L264.

**Comment by xclaesse** [comment]
> Try building https://github.com/amyspark/meson-bug-subprojects-cppstd .

Not sure what that example is supposed to show, both main project and subproject have `cpp_std=c++14`.

**Comment by xclaesse** [comment]
> at build time they're taken from **the subprojects' `default_options`**.

cpp_std is per subproject, it is expected to that the value from subproject's default_options.

**Comment by dragonmux** [comment]
if one sets up to build it with `meson setup build -Dstd=c++17`, then the main project will go into C++17 mode correctly and all will be good.. but the subproject will be configured as-if C++17 but the Ninja build configuration generated as-if C++14, resulting in extremely broken.

**Comment by xclaesse** [comment]
Oh, I see, adding `assert(not cxx.compiles(files('x.cpp')))` in the subproject is supposed to fail when doing `meson setup -Dcpp_std=c++17 builddir`. It is expected in this case that subproject is built as c++14 and not c++17, but there is indeed an inconsistency.

**Comment by xclaesse** [comment]
Please give a try to https://github.com/mesonbuild/meson/pull/12209
