### ISSUE TITLE
include_directories check for in-tree absolute paths gives false positives

### ISSUE THREAD

**Issue by bmerry** [mesonbuild/meson#12217]
**Describe the bug**
If the source directory is /bar/foo, and `include_directories` is called with an absolute path like `/bar/football/include`, then Meson incorrect reports `ERROR: Tried to form an absolute path to a dir in the source tree.`

**To Reproduce**
```meson
project('foo')
incdir = meson.current_source_dir() + 'xyz/include'
message(incdir)
include_directories(incdir)
```
(meson.current_source_dir is used just for this example; when I actually ran into this it was due to a Python virtual environment created in a sibling directory of the root).

**Expected behavior**
Meson should use functions appropriate for checking nesting of paths, rather than a [string test](https://github.com/mesonbuild/meson/blob/fe9af72684f85d709ce45096534aa51854a6da9b/mesonbuild/interpreter/interpreter.py#L2787).

Incidentally, it looks like there is a similar bug [here](https://github.com/mesonbuild/meson/blob/fe9af72684f85d709ce45096534aa51854a6da9b/mesonbuild/interpreter/interpreter.py#L556).

**system parameters**
- Not a cross build
- Ubuntu 22.04
- Python 3.10.12
- Meson 1.2.1

**Comment by bruchar1** [comment]
A related issue is that the check actually does not work on Windows, because of mismatch on path separators.
