### ISSUE TITLE
Cannot convert file objects to string since cec3edc08a6cd6a89761c49292ba6a3bace8b3c1

### ISSUE THREAD

**Issue by medhefgo** [mesonbuild/meson#12259]
cec3edc08a6cd6a89761c49292ba6a3bace8b3c1 will break systemd once released and it's even failing on your own test cases (which is pretty much what systemd is doing). It seems that CI tests are either not working properly or results are not checked before committing.

```
(master =) $ ./meson.py setup --fatal-meson-warnings --wipe test\ cases/linuxlike/3\ linker\ script/ /tmp/meson-bug
The Meson build system
Version: 1.2.99
Source dir: /home/medhefgo/meson/test cases/linuxlike/3 linker script
Build dir: /tmp/meson-bug
Build type: native build
Project name: linker script
Project version: undefined
C compiler for the host machine: sccache cc (gcc 13.2.1 "cc (GCC) 13.2.1 20230801")
C linker for the host machine: cc ld.bfd 2.41.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Configuring bob-conf.map using configuration
test cases/linuxlike/3 linker script/meson.build:25: DEPRECATION: Project uses feature that was always broken, and is now deprecated since '1.3.0': str.format: Value other than strings, integers, bools, options, dictionaries and lists thereof..

test cases/linuxlike/3 linker script/meson.build:25:35: ERROR: Fatal warnings enabled, aborting

A full log can be found at /tmp/meson-bug/meson-logs/meson-log.txt
```

**Comment by tristan957** [comment]
We don't run the CI with --fatal-meson-warnings

**Comment by dcbaker** [comment]
I'm assuming that what systemd is doing is something like:
```meson
build_target(
  ...
  link_args : ['--linker-script=', '@0@'.format(files('foo.sym')[0])],
)
```
This was a misfeature, and doesn't work reliably. It won't break unless you're running with fatal warnings. But we should have a solution for this, which we've been discussing anyway.

**Comment by eli-schwartz** [comment]
> even failing on your own test cases (which is pretty much what systemd is doing)

Good, because our own test cases are incorrect and broken and what they suggest to do does not work. People who think to copy our test case are in for worlds of pain if they actually try to use it.
