### ISSUE TITLE
Unable to build on Solaris 5.10 with meson 1.2.1

### ISSUE THREAD

**Issue by CorrodedCoder** [mesonbuild/meson#12257]
**Describe the bug**
Unable to build on Solaris 5.10 with meson 1.2.1

**To Reproduce**
meson init
meson setup builddir
meson compile -C builddir
ERROR: Failed to run "/usr/bin/uname -o"

**Expected behavior**
Per meson 1.1.1 it should not fail with that error.

**system parameters**
* Plain native build for the same computer.
* Solaris: SunOS 5.10 sun4v sparc sun4v
* what Python version are you using: 3.9.17
* what `meson --version`: 1.2.1 (running from source)
* what `ninja --version`: 1.11.1

It looks like it was added as part of this commit relating to "separate illumos and Solaris kernels in Machines" https://github.com/mesonbuild/meson/commit/42c68291c4c2512de04de31a90cb1c408d75a277

"uname -o" responds with:
uname: illegal option -- o
usage:  uname [-snrvmapiX]
        uname [-S system_name]

I accept that it is an old version of Solaris but I'm afraid it's the one I'm currently stuck with.

Thanks for any help!

**Comment by eli-schwartz** [comment]
Perhaps @alanc @jclulow have ideas about the topic.

It may be enough to simply log a warning and return None, if that's an expected situation and we just want to defer issues until someone actually attempts to access the kernel value from meson.build.

**Comment by CorrodedCoder** [comment]
I locally modified mine to check for return code one from uname and it then enabled me to build and run tests again, (I'm not proposing that as the solution):

`def detect_kernel(system: str) -> T.Optional[str]:
    if system == 'sunos':
        # This needs to be /usr/bin/uname because gnu-uname could be installed and
        # won't provide the necessary information
        p, out, _ = Popen_safe(['/usr/bin/uname', '-o'])
        if **p.returncode == 1:
            out = 'solaris'
        elif** p.returncode != 0:
            raise MesonException('Failed to run "/usr/bin/uname -o"')
        out = out.lower().strip()
        if out not in {'illumos', 'solaris'}:
            mlog.warning(f'Got an unexpected value for kernel on a SunOS derived platform, expcted either "illumos" or "solaris", but g
ot "{out}".'
                         "Please open a Meson issue with the OS you're running and the value detected for your kernel.")
            return None
        return out
    return KERNEL_MAPPINGS.get(system, None)`

**Comment by jclulow** [comment]
If Solaris 10 support is needed, I would look at the `release` member of the `utsname` structure.  If it's `5.10` then it's **Solaris 10**, and you don't need to check anything else: from inception, **illumos** has had a `release` version of `5.11` like **Oracle Solaris 11**.

**Comment by alanc** [comment]
Right, the code to run `uname -o` should only be called when the `utsname` release is 5.11, for any other value it should just return `solaris` directly.

**Comment by CorrodedCoder** [comment]
Thanks - I'll try that out on Monday and let you know how I get on.

**Comment by CorrodedCoder** [comment]
The change above appeared to work for Solaris 5.10 (I have no way to test on Illumos or later Solaris). In my github naivety I accidentally created a pull request here - but I suppose you can at least see the diff 😃, so feel free to disregard it: https://github.com/mesonbuild/meson/pull/12269
