### ISSUE TITLE
Specifying additional source file dependencies for generators

### ISSUE THREAD

**Issue by gabeblack** [mesonbuild/meson#12256]
I have hundreds of input files that are used to generate source files. I use a generator to do that. However, the generator essentially has two inputs:

1. Specific file that is used as the template for the generator. 
2. A list of files that the generator uses to help generate the file

Basically, I'd like to be able to tell the generator to rerun if any of those files change.

1. The input file passed to the generator (e.g. the argument to gen.process())
2. A list of files that are passed to the generator (e.g., via its `depends` argument <- but that currently doesn't work).

I tried putting the list of files in a `declare_dependency` and giving that dependency object to `depends`, but meson gave the error: "ERROR: Depends entries must be build targets."

Anyway to accomplish what I want to do in meson? I really don't want to write hundreds of custom_targets.

**Comment by bruchar1** [comment]
You can probably use a `foreach` loop to create `custom_target` for each input file . On ninja side, this will be equivalent to using a generator.

**Comment by gabeblack** [comment]
I actually was giving that a try right after posting. Thanks! I think that will do what I need.
