### ISSUE TITLE
How can I use CCACHE_PREFIX with meson (specifically distcc with meson)?

### ISSUE THREAD

**Issue by gabeblack** [mesonbuild/meson#12275]
I've been trying to convert a project over to using meson for its build, and the existing project uses distcc and ccache (along with dmucs).

I've been trying all sorts of different ways to be able to use distcc along with ccache in meson (preferably also using dmucs). ccache/distcc documentation indicate to use CCACHE_PREFIX to combine distcc with ccache and there are also workarounds of using wrapper scripts. However, every attempt to do something similar in meson has resulted in meson giving varying errors of the form `meson.build:1:1: ERROR: Unknown compiler(s): [[...]]"` If I use a crossfile to use a wrapper script, it will say my wrapper script is the compiler in the "Unknown compiler" error message. If I set CCACHE_PREFIX environment variable, then it will say that 'cc', 'gcc', etc are the unknown compilers.

My current wrapper incarnation looks like the following:

```
#!/bin/sh
compiler=$(basename $1)
shift
exec /usr/bin/dmucs_gethost distcc "$compiler" "$@"
```

Invoking meson setup like so:
`CCACHE_PREFIX=/path/to/distcc_wrapper.sh meson setup --debug build`

I've also tried various forms of a crossfile that look like:
```
[binaries]
c = '/path/to/distcc_wrapper.sh'
cpp = '/path/to/distcc_wrapper.sh'
```

Any ideas of what I need to do to get distcc and cacche to play together in the meson sandbox?

**Comment by eli-schwartz** [comment]
It should print out the path to the setup logs, which have a debug dump of precisely what meson thought it saw that made it think it had no idea what the compiler was.

**Comment by gabeblack** [comment]
It doesn't really display anything else additional:
```
> cat /path/to/myproject/build/meson-logs/meson-log.txt
Build started at 2023-09-20T16:26:55.925244
Main binary: /usr/libexec/platform-python
Build Options: -Ddebug=True
Python system: Linux
The Meson build system
Version: 0.55.3
Source dir: /path/to/myproject
Build dir: /path/to/myproject/build
Build type: native build
Program cat found: YES
Running command: /usr/bin/cat /path/to/myproject/VERSION
--- stdout ---
9.4
--- stderr ---


None of 'PKG_CONFIG_PATH' are defined in the environment, not changing global flags.
None of 'PKG_CONFIG_PATH' are defined in the environment, not changing global flags.
Project name: SBC
Project version: 9.4
None of 'CC' are defined in the environment, not changing global flags.

meson.build:1:0: ERROR: Unknown compiler(s): ['cc', 'gcc', 'clang', 'pgcc', 'icc']
The follow exceptions were encountered:
Running "clang --version" gave "[Errno 2] No such file or directory: 'clang': 'clang'"
Running "pgcc --version" gave "[Errno 2] No such file or directory: 'pgcc': 'pgcc'"
Running "icc --version" gave "[Errno 2] No such file or directory: 'icc': 'icc'"
```

**Comment by gabeblack** [comment]
So it happens that our dmucs server happened to be having issues at the same time. Years it's been running, but decides to have issues right when I try and do the port... sigh. Sorry for wasting your time.
