### ISSUE TITLE
find_program does not follow documented search order on Windows

### ISSUE THREAD

**Issue by dvrogozh** [mesonbuild/meson#12297]
As documented in https://mesonbuild.com/Reference-manual_functions.html#find_program, `find_program` should first look into `dirs` kwarg if provided, then into `PATH` environment variable. This is not true however at least for meson on Windows (I did not try Linux). Consider the following example to replicate:
```
$ cp /c/Windows/System32/whoami.exe /c/temp/
$ cat meson.build
project('test', 'c')
whoami = find_program('whoami', dirs : 'C:\\temp')

$ meson --version
1.1.1

$ meson setup _build
The Meson build system
Version: 1.2.99
Source dir: C:/local/git/meson-bug/find_program
Build dir: C:/local/git/meson-bug/find_program/_build
Build type: native build
Project name: test
Project version: undefined
C compiler for the host machine: cc (gcc 13.1.0 "cc (Rev7, Built by MSYS2 project) 13.1.0")
C linker for the host machine: cc ld.bfd 2.40
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program whoami found: YES (C:\msys64\usr\bin/whoami.EXE)
Build targets in project: 0

Found ninja-1.11.1 at C:\msys64\mingw64\bin/ninja.EXE
```

Above is run with msys2 meson of version `1.1.1`. I did check that latest meson master https://github.com/mesonbuild/meson/commit/5ff59f2fb515f47ed61598fed7749982fb20e49f has the same issue. And if run meson installed on Windows under MSVC command prompt (under cmd.exe, not msys2) - same issue:
```
> meson setup _build
The Meson build system
Version: 1.1.1
Source dir: C:\local\git\meson-bug\find_program
Build dir: C:\local\git\meson-bug\find_program\_build1
Build type: native build
Project name: test
Project version: undefined
C compiler for the host machine: cl (msvc 19.35.32217.1 "Microsoft (R) C/C++ Optimizing Compiler Version 19.35.32217.1 for x64")
C linker for the host machine: link link 14.35.32217.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program whoami found: YES (C:\WINDOWS\system32\whoami.EXE)
Build targets in project: 0

Found ninja-1.11.1 at "C:\Program Files\Meson\ninja.EXE"
```

**Comment by Habbie** [comment]
I can reproduce this on Linux with meson 1.0.1, but not with 1.6.1

**Comment by Habbie** [comment]
> I can reproduce this on Linux with meson 1.0.1 and 1.5.1, but not with 1.6.0 or 1.6.1

bisected to 0f914b75fe39d924ff93d9651eba79c32c597365

**Comment by eli-schwartz** [comment]
Aha, yeah, that makes sense. That commit refactored `ExternalProgram._search` to batch all search directories and do a single search that internally checks all paths; that also means it does so before giving up and doing `shutil.which`.

Previously, if the first search dir (usually None) didn't find it, it would fall back to PATH, and then try again with the next search dir, fall back to PATH *again*, etc.
