### ISSUE TITLE
Meson generates potentially invalid response files for MSVC's Linker (link.exe)

### ISSUE THREAD

**Issue by yretenai** [mesonbuild/meson#12329]
**Describe the bug**

When linking an absurd amount of object files (in my case around 4,000) a response file gets made, which is expected.

This file has one single line, which ends up invoking error LNK1170 in the MSVC Linker because the entire line is longer than 128KB. 

By replacing one variable in the build.ninja file post-configure this will work.

**Workaround**

Letting it configure, and changing

```
rule cpp_LINKER_RSP
 command = "link" @$out.rsp
 rspfile = $out.rsp
 rspfile_content = $ARGS /MACHINE:x64 /OUT:$out $in $LINK_ARGS
 description = Linking target $out
```

to this:

```
rule cpp_LINKER_RSP
 command = "link" @$out.rsp
 rspfile = $out.rsp
 rspfile_content = $ARGS /MACHINE:x64 /OUT:$out $in_newline $LINK_ARGS
 description = Linking target $out
 ```

in the build.ninja file. The build will work correctly (and is also what the [ninja docs say](https://ninja-build.org/manual.html))

>  in_newline: the same as $in except that multiple inputs are separated by newlines rather than spaces. (For use with $rspfile_content; this works around a bug in the MSVC linker where it uses a fixed-size buffer for processing input.) 

TL;DR change $in to $in_newline for _RSP rules when rsp file syntax is RSPFileSyntax.MSVC.

I initially considered making a pull request for this but I am not experienced enough with both python and the meson code-base to feel comfortable enough making this change without it looking like found VHS footage.

**To Reproduce**

- Have a project with a lot of paths or a few very long paths resulting in a single line .rsp file over 128KB
- Build and link a shared library using MSVC as the target toolchain.

**Expected behavior**

Shared library gets made.

**system parameters**
* no cross compiling.
* Windows 11 
* Python 3.11.6
* Meson 1.2.1
* Ninja 1.11.1

**Comment by tristan957** [comment]
Seems like a potentially easy fix if you have a moment :)

**Comment by eli-schwartz** [comment]
> I initially considered making a pull request for this but I am not experienced enough with both python and the meson code-base to feel comfortable enough making this change without it looking like found VHS footage.

Your change looks pretty decent to me, by the way. :)
