### ISSUE TITLE
Extension to properly handle doxygen

### ISSUE THREAD

**Issue by robtaylor** [mesonbuild/meson#12335]
I have a project with *a lot* of relatively complex doxygen. I'm considering writing a tool or module to make including doxygen easier in a meson build.

As I understand it, we at least need a tool that will read a doxyfile and return the set of input files. I think I've figured out how to do this.  Do I also need to figure out the output files, or can this be done by running the tool?

Any recommendations on the correct approach?

**Comment by QuLogic** [comment]
There is an example of using Doxygen in [the tests here](https://github.com/mesonbuild/meson/tree/master/test%20cases/frameworks/14%20doxygen).

**Comment by robtaylor** [comment]
Ah cool, I’ll give that a try in my project, thanks!

**Comment by robtaylor** [comment]
Hmm, it seems non of the files from my docs folder or the headers are making into meson.project_source_root(). What may I be doing wrong?

**Comment by robtaylor** [comment]
PEBKAC, this works well, thank you!
