### ISSUE TITLE
meson/1.2.2 regression on windows using glib-compile-resources

### ISSUE THREAD

**Issue by weatherhead99** [mesonbuild/meson#12348]
**Describe the bug**
Hello all, apologies I am not an expert meson user. When trying to build packages for the conan package manager (which is invoking meson on this particular package), on windows, (https://github.com/conan-io/conan-center-index/pull/20354) when we build using meson 1.2.2 (and ninja 1.11.1) we see the following error:

```
[vcvarsall.bat] Environment initialized for: 'x64'
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: C:\Users\dpw244\.conan2\p\ninjae2ad385cd85df\p\bin\ninja.EXE -j 8
ninja: error: 'C:/Users/dpw244/.conan2/p/glibe293253e8b225/p/bin/glib-compile-resources', needed by 'src/arvresources.c', missing and no known rule to make it
```

when using meson 1.2.1 we see no such error. It is probably related to the fact that the actual file on disk is C:/Users/dpw244/.conan2/p/glibe293253e8b225/p/bin/glib-compile-resources.exe (i.e. with the .exe extension, and not without)
 

**To Reproduce**

(on windows)
```
pip install conan
git clone https://github.com/weatherhead99/conan-center-index aravis_bump_version_windows_broken
cd conan-center-index/recipes/aravis/all
conan source . --version=0.8.20
conan build . --version=0.8.20 --build=missing
```

above error is emitted early in build process when attempting to generate GLIB resources files.

**Expected behavior**
Build succeeds  (e.g. to reproduce)

```
rmdir /S src 
rmdir /S build-release
conan remove meson/*
conan source . --version=0.8.20
conan build . --version=0.8.20 -obreak_windows=False

```
will build this package with meson 1.2.1 and this runs to completion. Apologies I have no time at the moment to make a MWE. I am no expert at meson itself either.

**system parameters**
* native build
* Windows 10
* python 3.10.12
* meson version 1.2.22
* ninja version 1.11.1

**Comment by dcbaker** [comment]
This looks similar to https://github.com/mesonbuild/meson/issues/12271, there is a fix in the main branch for that issue already. Would it be possible to try this with main and see if that resolves the issue?

**Comment by eli-schwartz** [comment]
This should already be fixed in git master IIRC.

**Comment by weatherhead99** [comment]
ok, it's quite a pain to try master really in that environment but I will wait until 1.2.3 is out and then try this build again.
Thanks for all the help

**Comment by eli-schwartz** [comment]
You should be able to trivially backport commit d7b25662ce5c7f9831b003581054e174b97c4865 as a patch file applied to the `meson` package without messing around with unstable development releases of meson.
