### ISSUE TITLE
request for setting reserved options like includedir in meson_options.txt or meson.build

### ISSUE THREAD

**Issue by Crazyokd** [mesonbuild/meson#12365]
In project we maybe will use some options, include custom options and system options like includedir.
so meson friendly offer a `meson_options.txt` file for us.

but today i reference a third part library and when i execute the `meson install` command, i found the third part library will be installed to my system directory through console output.

but i don't want to do like that.
i want to the project install file can be install to local workdir and i implement it with `prefix = run_command('sh', '-c', 'echo $PWD').stdout().strip() / 'install'` command.
and further i view the meson.build of third part library under subprojects. and i found it install to `get_option('includedir')` dir.
so i want to set this option in my meson_options.txt  and i failed because it hint me "ERROR: Option name includedir is reserved."

definitely i know i can set this options with `meson configure -Dincludedir=xxx`, but i use `meson install` frequently so i don't want to do like that.

so i request for you can offer a method to set the "reserved option".
> I am not a native English speaker.

**Comment by eli-schwartz** [comment]
> i want to the project install file can be install to local workdir and i implement it with `prefix = run_command('sh', '-c', 'echo $PWD').stdout().strip() / 'install'` command.

You cannot use run_command() in a meson_options.txt file anyway.

However, meson does support setting the values of builtin options. Not using meson_options.txt, but rather, like this:

```meson
project('my-project', 'c',
    version: '1.2.3',
    meson_version: '>=0.61.0',
    default_options: ['includedir=' + run_command('sh', '-c', 'echo $PWD').stdout().strip() / 'install'],
)
```

The default_options is the important thing here. Please note that I do NOT encourage setting the prefix via run_command plus $HOME, but it is technically possible.

My preferred option would be to use https://mesonbuild.com/Machine-files.html

```
meson setup builddir --native-file home.txt
```

You can set builtin options via a machine file.



> definitely i know i can set this options with `meson configure -Dincludedir=xxx`, but i use `meson install` frequently so i don't want to do like that.

It should only be necessary to run `meson configure` once per build directory -- running `meson install` multiple times in the same directory does not mess up the current settings.

**Comment by Crazyokd** [comment]
Thank you for your detailed reply!
> However, meson does support setting the values of builtin options. Not using meson_options.txt, but rather, like this:
> 
> ```meson
> project('my-project', 'c',
>     version: '1.2.3',
>     meson_version: '>=0.61.0',
>     default_options: ['includedir=' + run_command('sh', '-c', 'echo $PWD').stdout().strip() / 'install'],
> )
> ```

I used the following command in `meson.build` in the past:
```
prefix = run_command('sh', '-c', 'echo $PWD').stdout().strip() / 'install'
bindir = join_paths(prefix, get_option('bindir'))
libdir = join_paths(prefix, get_option('libdir'))

executable('xxx', 'main.cpp',
    include_directories : [comm_inc],
    install_rpath: libdir,
    install_dir : bindir,
    install : true)
```
and if i use this method(set `default_options`) to solve the issue, i can't use variable like prefix because meson first statement MUST be a call to project(), however i probable need to set multiple options, such as includedir、bindir etc. so this method will make the code more redundant.

> My preferred option would be to use https://mesonbuild.com/Machine-files.html
> 
> ```
> meson setup builddir --native-file home.txt
> ```
> 
> You can set builtin options via a machine file.

this method works well to me. Thank you again.
I use below configuration to solve my problem:
```
[built-in options]
includedir = './install/include'
```

**Comment by eli-schwartz** [comment]
> I used the following command in `meson.build` in the past:
> ```
> prefix = run_command('sh', '-c', 'echo $PWD').stdout().strip() / 'install'
> bindir = join_paths(prefix, get_option('bindir'))
> libdir = join_paths(prefix, get_option('libdir'))
> 
> executable('xxx', 'main.cpp',
>     include_directories : [comm_inc],
>     install_rpath: libdir,
>     install_dir : bindir,
>     install : true)
> ```
> and if i use this method(set `default_options`) to solve the issue, i can't use variable like prefix because meson first statement MUST be a call to project(), however i probable need to set multiple options, such as includedir、bindir etc. so this method will make the code more redundant.


Note that by default the value of bindir is "bin", not "/usr/local/bin", and specifying a relative path   will cause it to be calculated relative to "prefix" for e.g. "install_dir".
