### ISSUE TITLE
How do I override project options?

### ISSUE THREAD

**Issue by jakubby2** [mesonbuild/meson#12376]
**Describe the bug**
I want to enable specific compilation options depending on the binary I want to produce.

**To Reproduce**
[meson.build](https://github.com/mesonbuild/meson/files/12910459/meson.build.txt)

**Expected behavior**
A simple way to override c_args project() option on a executable() library() level.

**system parameters**
* 2 Native builds (amd64/aarch64)
* openSuse Tumblweed
* Python 3.11.5
* meson 1.2.2
* ninja if it's a Ninja build 1.11.1

**Comment by jakubby2** [comment]
```bash
$ meson compile -C build --clean
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /usr/bin/ninja -C /home/jakubby/bakedPie/build clean
ninja: Entering directory `/home/jakubby/bakedPie/build'
[1/1] Cleaning
Cleaning... 0 files.
$ meson compile -C build
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /usr/bin/ninja -C /home/jakubby/bakedPie/build
ninja: Entering directory `/home/jakubby/bakedPie/build'
[5/23] Compiling C object bakePie.p/src_cpuBurners_RGBtoYCbCr.c.o
../src/cpuBurners/RGBtoYCbCr.c: In function ‘RGBtoYCbCr’:
../src/cpuBurners/RGBtoYCbCr.c:7: warning: ignoring ‘#pragma omp simd’ [-Wunknown-pragmas]
    7 |         #pragma omp simd
      | 
[23/23] Linking target bakedPie
```
I really don't know how to override `c_args=`.
If I put `-fopenmp` into the build it will work fine.

**Comment by jakubby2** [comment]
I asked google bard thinking that wouldn't work seeing how much shitty code it can hallucinate.
```
else
executable('bakePie',
			bakePieFiles,
			install : true,
			dependencies: bakePieDeps,
			c_args: ['-fopenmp', '-Wno-unused-but-set-variable'],
			install_dir: 'share/bakedPie/ovens')
endif
```

**Comment by dcbaker** [comment]
It would be better in this case to use `dependency('openmp')`, which is portable across different compilers.

**Comment by jakubby2** [comment]
Unless `dependency('openmp')` is a special case meson has.
Then it's not going to work.
openmp has no pkg-config/pkgconf profile in the filesystem(at least not by default) so invoking `pkg-config openmp --cflags` and `pkg-config openmp --libs` won't do anything.
