### ISSUE TITLE
Can't enable profiling without overriding c_args for the project or specific executable() targets.

### ISSUE THREAD

**Issue by jakubby2** [mesonbuild/meson#12379]
**Describe the bug**
I don't think it's currently possible to enable profiling for a single compilation session.

**To Reproduce**
```
# I don't want to edit the meson.build just to enable profiling, nor do I want to override all C args.
# I want to enable profiling from the cmdline.
# Nor do I want to build a profile target all the time.
project('helloWorld', 'c',
	version : '0.1.4',
	default_options : ['warning_level=1',
		'buildtype=release',
		'optimization=2',
		'b_lto=true',
		'b_lto_mode=thin',
		'c_std=gnu11',
	],
)
executable('helloWorld', 'hello.c')
```

**Expected behavior**
meson configure --profile [enables '-pg' flag on gcc, and whichever flags there are for msvc and what not].

**system parameters**
* No
* opensuse Tumbleweed
* Python 3.11.5
* meson: 1.2.2
* ninja: 1.11.1

**Comment by tristan957** [comment]
@jakubby2 you can do this with the following:

```
meson setup build -Db_lto=true -Db_lto_mode=thin ...
```

OR

```
meson configure build -Db_lto=true -Db_lto_mode=thin ...
```

I don't understand your question

**Comment by jakubby2** [comment]
> @jakubby2 you can do this with the following:
> 
> ```
> meson setup build -Db_lto=true -Db_lto_mode=thin ...
> ```
> 
> OR
> 
> ```
> meson configure build -Db_lto=true -Db_lto_mode=thin ...
> ```
> 
> I don't understand your question

GCC has a "gprof" "gnuprofiler" option the way it works is you add `-pg` flag to your gcc invocation and it makes every function invocation print out the enter and exit time of a function, it makes it so your program saves this information to a file.

I don't want it enabled for default/release build, but I still want to make use of it.

**Comment by tristan957** [comment]
So why not use it with `-Dc_args="-pg"`

**Comment by jakubby2** [comment]
I see, had no idea it is a thing.
Something in me was registering it as a `-D` flag like it works in gcc and clang.
Basically setting define.

**Comment by tristan957** [comment]
Glad I could help you. Other languages have similar options, `rust_args`, `cpp_args`, etc... Also setting CFLAGS would work, but you have to be careful with environment variables.
