### ISSUE TITLE
Vim syntax highlighting files are applied to all filetypes

### ISSUE THREAD

**Issue by eli-schwartz** [mesonbuild/meson#1241]
In #868 syntax, ftdetect, and indentation files for Vim were added, and the meson package for Arch Linux now installs these files globally.

Shortly after doing a sysupgrade which included meson, I discovered that my Vim settings were being stomped on, and I tracked it down to plugin/meson.vim which is, according to the commit message and the file itself, an indent file not a plugin.

Installing it as a plugin unfortunately means that it is loaded when Vim starts, as opposed to when a file of filetype=meson is read. As a result, it applies to ALL files, of every filetype whatsoever, where it proceeds to use set instead of setlocal to override shiftwidth and softtabstop.
See: http://learnvimscriptthehardway.stevelosh.com/chapters/42.html

Please move the indent file from plugin/ to indent/ (to prevent it from being loaded before meson files are edited) and use setlocal instead of set (to prevent it spreading into other buffers whenever meson files **are** edited).

**Comment by jpakkane** [comment]
Can you check if #1245 does the right thing (I don't use Vim so can't really tell)?

**Comment by anthraxx** [comment]
@jpakkane i'm not fully sure, but shouldn't that also apply to:
https://github.com/mesonbuild/meson/blob/master/syntax-highlighting/vim/syntax/meson.vim#L30

**Comment by eli-schwartz** [comment]
Yes, thanks.

(It's the same fix the Arch packager hotfixed.)
