### ISSUE TITLE
custom_target: target name ignored

### ISSUE THREAD

**Issue by d4ilyrun** [mesonbuild/meson#12440]
**Describe the bug**

According to the documentation, the `name` parameter is optional and should *default* to the basename of the first output.

But after testing, the target's name appears to be ignored and **always** set according to the output file.

**To Reproduce**

```python
custom_target('iso',
  output: ['kernel.iso', 'kernel.sym'],
  command: [ 'scripts/generate_iso.sh', kernel, '@OUTPUT@' ],
  depends: kernel
)
```

This custom targets does not produce a ninja target named `iso`.

**Expected behavior**

The given example should produce a target named `iso`

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
```ini
[target_machine]
cpu = 'i686'
cpu_family = 'x86'
endian = 'little'
system = 'none'
```

* OS: `linux x86_64 - 5.15.75`
* meson: `1.1.0`
* ninja: `1.11.1`

**Comment by eli-schwartz** [comment]
Ninja rules will map input filenames to output filenames. The custom_target name is only written to the ninja file as part of the description field (which ninja will show as the user-friendly version of the status line, if you don't invoke it with the "verbose" option).

This has a lot to do with why we now have it be optional, actually.

**Comment by eli-schwartz** [comment]
If you want a short target name to run as `ninja iso` then check out alias_target() -- you can make arbitrary groupings of outputs that get built with your choice of shortcut names.

**Comment by d4ilyrun** [comment]
Oh ok my bad then sorry ! I'm closing this issue then 👍🏻 

> If you want a short target name to run as `ninja iso` then check out alias_target() -- you can make arbitrary groupings of outputs that get built with your choice of shortcut names.

Yes, that's the solution I came up with eventually

**Comment by eli-schwartz** [comment]
It's definitely a bit confusing... :)
