### ISSUE TITLE
Meson builds?......what?

### ISSUE THREAD

**Issue by AnonymousRonin** [mesonbuild/meson#12441]
Meson doesn't build shit because lazy project maintaines, coders and/or developers either can't follow or don't know the build rules.  That's the second project I've given up on because of lazy dev teams.  Mesa was already borderline as far as usefulness, now the projects used to supplement them can't even be built by your average person.  This should have a disclaimer that unless your a software engineer familiar with meson or other similar programs that it's a fruitless venture.  I really enjoyed wasting my time trying to fix someone else's errors.

The Meson build system
Version: 1.2.1
Source dir: /home/ghost/Downloads/glu-9.0.2/src
Build dir: /home/ghost/Downloads/glu-9.0.2/src/gbuild
Build type: native build

ERROR: Invalid source tree: first statement must be a call to project()

A full log can be found at /home/ghost/Downloads/glu-9.0.2/src/gbuild/meson-logs/meson-log.txt

ghost@skynet:~/Downloads/glu-9.0.2/src$ meson gbuild/
The Meson build system
Version: 1.2.1
Source dir: /home/ghost/Downloads/glu-9.0.2/src
Build dir: /home/ghost/Downloads/glu-9.0.2/src/gbuild
Build type: native build

ERROR: Invalid source tree: first statement must be a call to project()

A full log can be found at /home/ghost/Downloads/glu-9.0.2/src/gbuild/meson-logs/meson-log.txt
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.

The Meson build system
Version: 1.2.1
Source dir: /home/ghost/Downloads/glu-9.0.2/src
Build dir: /home/ghost/Downloads/glu-9.0.2/src/gbuild
Build type: native build

meson.build:1:12: ERROR: Expecting eof got comma.
project_name, libfuck
            ^

A full log can be found at /home/ghost/Downloads/glu-9.0.2/src/gbuild/meson-logs/meson-log.txt

ghost@skynet:~/Downloads/glu-9.0.2/src$ sudo nano meson.build

ghost@skynet:~/Downloads/glu-9.0.2/src$ meson setup gbuild/
The Meson build system
Version: 1.2.1
Source dir: /home/ghost/Downloads/glu-9.0.2/src
Build dir: /home/ghost/Downloads/glu-9.0.2/src/gbuild
Build type: native build

ERROR: Invalid source tree: first statement must be a call to project()

A full log can be found at /home/ghost/Downloads/glu-9.0.2/src/gbuild/meson-logs/meson-log.txt

ghost@skynet:~/Downloads/glu-9.0.2/src$ sudo nano meson.build

ghost@skynet:~/Downloads/glu-9.0.2/src$ meson setup gbuild/
The Meson build system
Version: 1.2.1
Source dir: /home/ghost/Downloads/glu-9.0.2/src
Build dir: /home/ghost/Downloads/glu-9.0.2/src/gbuild
Build type: native build

meson.build:1:13: ERROR: Expecting eof got id.
project_name libfuck
             ^

A full log can be found at /home/ghost/Downloads/glu-9.0.2/src/gbuild/meson-logs/meson-log.txt

ghost@skynet:~/Downloads/glu-9.0.2/src$ sudo nano meson.build

ghost@skynet:~/Downloads/glu-9.0.2/src$ meson setup gbuild/
The Meson build system
Version: 1.2.1
Source dir: /home/ghost/Downloads/glu-9.0.2/src
Build dir: /home/ghost/Downloads/glu-9.0.2/src/gbuild
Build type: native build

meson.build:1:12: ERROR: Expecting eof got colon.
project_name: libfuck
            ^

A full log can be found at /home/ghost/Downloads/glu-9.0.2/src/gbuild/meson-logs/meson-log.txt

ghost@skynet:~/Downloads/glu-9.0.2/src$ sudo nano meson.build

ghost@skynet:~/Downloads/glu-9.0.2/src$ meson setup gbuild/
The Meson build system
Version: 1.2.1
Source dir: /home/ghost/Downloads/glu-9.0.2/src
Build dir: /home/ghost/Downloads/glu-9.0.2/src/gbuild
Build type: native build

ERROR: Invalid source tree: first statement must be a call to project()

A full log can be found at /home/ghost/Downloads/glu-9.0.2/src/gbuild/meson-logs/meson-log.txt

ghost@skynet:~/Downloads/glu-9.0.2/src$ sudo nano meson.build

ghost@skynet:~/Downloads/glu-9.0.2/src$ meson setup gbuild/
The Meson build system
Version: 1.2.1
Source dir: /home/ghost/Downloads/glu-9.0.2/src
Build dir: /home/ghost/Downloads/glu-9.0.2/src/gbuild
Build type: native build

ERROR: Invalid source tree: first statement must be a call to project()

A full log can be found at /home/ghost/Downloads/glu-9.0.2/src/gbuild/meson-logs/meson-log.txt

ghost@skynet:~/Downloads/glu-9.0.2/src$ sudo nano meson.build

ghost@skynet:~/Downloads/glu-9.0.2/src$ meson setup gbuild/
The Meson build system
Version: 1.2.1
Source dir: /home/ghost/Downloads/glu-9.0.2/src
Build dir: /home/ghost/Downloads/glu-9.0.2/src/gbuild
Build type: native build
Project name: fglu
Project version: undefined
Host machine cpu family: x86_64
Host machine cpu: x86_64

meson.build:107:4: ERROR: Unknown variable "inc_include".

A full log can be found at /home/ghost/Downloads/glu-9.0.2/src/gbuild/meson-logs/meson-log.txt

ghost@skynet:~/Downloads/glu-9.0.2/src$ sudo nano meson.build

ghost@skynet:~/Downloads/glu-9.0.2/src$ meson setup gbuild/
The Meson build system
Version: 1.2.1
Source dir: /home/ghost/Downloads/glu-9.0.2/src
Build dir: /home/ghost/Downloads/glu-9.0.2/src/gbuild
Build type: native build
meson.build:107: WARNING: Newline character in a string detected, use ''' (three single quotes) for multiline strings instead.
This will become a hard error in a future Meson release.
    'inc_include,
    ^

meson.build:107:50: ERROR: Expecting rbracket got id.
    'inc_include,
                                                  ^
For a block that started at 102,24
  include_directories : [
                        ^

A full log can be found at /home/ghost/Downloads/glu-9.0.2/src/gbuild/meson-logs/meson-log.txt

ghost@skynet:~/Downloads/glu-9.0.2/src$ sudo nano meson.build

ghost@skynet:~/Downloads/glu-9.0.2/src$ meson setup gbuild/
The Meson build system
Version: 1.2.1
Source dir: /home/ghost/Downloads/glu-9.0.2/src
Build dir: /home/ghost/Downloads/glu-9.0.2/src/gbuild
Build type: native build
Project name: fglu
Project version: undefined
Host machine cpu family: x86_64
Host machine cpu: x86_64

meson.build:110:18: ERROR: Unknown variable "dep_gl".

A full log can be found at /home/ghost/Downloads/glu-9.0.2/src/gbuild/meson-logs/meson-log.txt

ghost@skynet:~/Downloads/glu-9.0.2/src$ sudo nano meson.build

ghost@skynet:~/Downloads/glu-9.0.2/src$ meson setup gbuild/
The Meson build system
Version: 1.2.1
Source dir: /home/ghost/Downloads/glu-9.0.2/src
Build dir: /home/ghost/Downloads/glu-9.0.2/src/gbuild
Build type: native build
Project name: fglu
Project version: undefined
Host machine cpu family: x86_64
Host machine cpu: x86_64

meson.build:110:18: ERROR: Unknown variable "dep_gl".

A full log can be found at /home/ghost/Downloads/glu-9.0.2/src/gbuild/meson-logs/meson-log.txt

ghost@skynet:~/Downloads/glu-9.0.2/src$ sudo nano meson.build

ghost@skynet:~/Downloads/glu-9.0.2/src$ meson setup gbuild/
The Meson build system
Version: 1.2.1
Source dir: /home/ghost/Downloads/glu-9.0.2/src
Build dir: /home/ghost/Downloads/glu-9.0.2/src/gbuild
Build type: native build
Project name: fglu
Project version: undefined
Host machine cpu family: x86_64
Host machine cpu: x86_64

meson.build:7:9: ERROR: Include dir inc_include does not exist.

A full log can be found at /home/ghost/Downloads/glu-9.0.2/src/gbuild/meson-logs/meson-log.txt

**Comment by eli-schwartz** [comment]
> Meson doesn't build shit because lazy project maintaines, coders and/or developers either can't follow or don't know the build rules. That's the second project I've given up on because of lazy dev teams. Mesa was already borderline as far as usefulness, now the projects used to supplement them can't even be built by your average person. This should have a disclaimer that unless your a software engineer familiar with meson or other similar programs that it's a fruitless venture. I really enjoyed wasting my time trying to fix someone else's errors.

My apologies, you are right.

We regret everything and will close down shop immediately. :)
