### ISSUE TITLE
rust: Proc macros end up in library dependencies

### ISSUE THREAD

**Issue by gfxstrand** [mesonbuild/meson#12459]
This is somewhat related to https://github.com/mesonbuild/meson/issues/11702 but different. When you set up a project with a proc macro, you do something like
```meson
libnak_ir_proc = rust.proc_macro(
  'nak_ir_proc',
  files('nak_ir_proc.rs'),
  dependencies : [dep_syn],
)
```
and then, when you want to use it
```meson
_libnak_rs = static_library(
  ...
  rust_abi : 'c',
  link_with: [..., libnak_ir_proc],
)
```
This works fine. The problem comes when `_libnak_rs` is linked into some C code.  Meson is smart enough to not try to link `libnak_ir_proc` in directly but it still ends up in the dependency chain and the C linker tries to link it as part of linking `_libnak_rs` into the C library.  This is pointless but harmless on native builds.  For cross builds, however, this causes the C link to fail because it's trying to link libraries with different target architectures.

**Comment by gfxstrand** [comment]
Cc @dcbaker @xclaesse

**Comment by xclaesse** [comment]
Could you give a try to https://github.com/mesonbuild/meson/pull/12460 please?
