### ISSUE TITLE
meson compile doesn't respect -C arg

### ISSUE THREAD

**Issue by srobertjames** [mesonbuild/meson#12465]
**Describe the bug**
meson compile doesn't respect -C arg

**To Reproduce**
```
$  meson configure -C build
```
**Expected behavior**

Meson should switch to `build` dir and configure, similar to `meson compile`.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
Cross build
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
`Ubuntu 22.04.3 LTS`
* what Python version are you using e.g. 3.8.0
`Python 3.10.12`
* what `meson --version`
`1.2.2`
* what `ninja --version` if it's a Ninja build

**Comment by eli-schwartz** [comment]
```
$ meson configure --help

[...]

positional arguments:
  builddir
```

It is not a -C argument, it is the "primary purpose" argument.

(Note that meson compile is the inconsistent one. It was added relatively very recently, and basically serves no purpose other than to forward arguments to ninja -- which, ninja takes a -C argument, so meson compile wraps that argument.)

**Comment by srobertjames** [comment]
What is the reason that some meson commands take builddir as positional and some as `-C`?

It seems to me that meson should be consistent: either express `builddir` as a positional or express it as `-C` arg for all commands.  Both `configure` and `compile` are equally dependent on your choice of `builddir`.

The fact that `meson compile` forwards to ninja is internal to meson. It's an implementation aspect which doesn't seem to be otherwise a feature of writing a `meson.build` or using meson.

**Comment by eli-schwartz** [comment]
> The fact that `meson compile` forwards to ninja is internal to meson. It's an implementation aspect which doesn't seem to be otherwise a feature of writing a `meson.build` or using meson.

`meson compile` should generally not be used. There's no reason to use it. It's a duplicate of `ninja`.

> It seems to me that meson should be consistent: either express `builddir` as a positional or express it as `-C` arg for all commands. Both `configure` and `compile` are equally dependent on your choice of `builddir`.

It is consistent in that commands which modify the build options itself accept an action name of the directory to act on, as well as -D options, while commands that are the internal representation of classic Makefile -- or ninja file in this case -- targets, accept the classic make/ninja `-C workdir/` argument.

meson compile -> ninja
meson test -> ninja test
meson install -> ninja install

Running these via ninja is the top-level UX and will actually pick the correct "default" options for you. In most cases, they are already using positional arguments for incompatible meanings.
