### ISSUE TITLE
How to build subprojects in order

### ISSUE THREAD

**Issue by fukanchik** [mesonbuild/meson#12490]
I'm trying to compile and link a mix of C and golang subprojects. 

I'm attaching a minimal project where I am stuck. It consists of: a root meson.build, sources dir `src` and two subprojects - a and b.

Main project sources are in `src` and it uses a library from subproject `a`. Works ok if I disable golang project.

Subproject a is a c shared library which is used both by the main project and subproject b.

Subproject b is a golang binary (built via custom_target()) which uses C library a.

Problem is - I see no way to connect b to a and build a before b and then either consume it via `#cgo pkg-config:` (my case) or `LDFLAGS` . In the second case even if I somehow manage to enforce build order I can't guess the value of linkdir (-L).

What is the proper way to make b dependent on a and obtain compiler/linker flags for a within b?

**Comment by fukanchik** [comment]
[sample.tar.gz](https://github.com/mesonbuild/meson/files/13283599/sample.tar.gz)

**Comment by mitchgrout** [comment]
I might be misunderstanding, but this would ensure a sequencing of `a` always-before `b`?

```meson
// subprojects/a/meson.build
project('a', ..., meson_version: '>= 0.54')
dep = declare_dependency(...)
meson.override_dependency('a', dep)

// subprojects/b/meson.build
project('b', ...)
a = dependency('a') # Will force 'subprojects/a/meson.build' to be evaluated
b = declare_dependency(...)
meson.override_dependency('b', b)
```

**Comment by fukanchik** [comment]
>> a = dependency('a') # Will force 'subprojects/a/meson.build' to be evaluated
Thanks, this I think works. 
What about the second problem - setting the proper linker search directory in a golang project?

**Comment by mitchgrout** [comment]
Ah hold on a second, I think I see the problem you have. You need to force a build of the library from project `a` before you can build `b`. I'm just spitballing this but you might be able to get away with something like...

```meson
# subprojects/a/meson.build
project('a', ...)

lib = library(...)
dep = declare_dependency(...)
meson.override_dependency('a', dep)

# subprojects/b/meson.build
project('b', ...)

a_lib = subproject('a').get_variable('lib'), # may be able to use dependency('a').get_variable('lib') also 
go_mod = custom_target(
  output: 'go.mod.out',
  depends: a_lib,
  command: [some_command_that_makes_the_output, a_lib.full_path(), '@OUTPUT@'],
)

# use 'go_mod' as part of your sources
```

**Comment by fukanchik** [comment]
Thanks, that worked fine on my attached sample project however on a real world project with a big C library it only works with `meson compile -j 1`. In parallel builds C library starts to build and then somewhere in the middle meson tries to link golang project against yet unfinished C library.

**Comment by mitchgrout** [comment]
Hm, might need to dig into a more complete example; could you reduce your current example to a working MVP that you could share? This would need to include all scripts that you intend to use. It would also be helpful to look at your `build.ninja` file if possible

**Comment by fukanchik** [comment]
I tried to modify the attached sample project but it woks as expected no matter what I do. 

I will try to play with the big project a bit more and see if I can either solve the build order or as a final measure I'll anonymize `build.ninja` and attach it here.

**Comment by fukanchik** [comment]
Problem might be somehow related to this:
```
subprojects/golang_api/meson.build:20:0: ERROR: custom_target keyword argument 'depends' was of type array[InternalDependency] but should have been array[BuildTarget | CustomTarget]
```

Can this somehow make golang binary not to wait until c++ library finishes compilation?

For example, `depends` of `benchmark` explicitly says the target will be built:
```
Those targets are built before test is executed even if they have build_by_default : false.
```

but the doc for `depends` of `custom_target` does not mention "building":
```
Specifies that this target depends on the specified target(s), even though it does not take any of them as a command line argument. This is meant for cases where you have a tool that e.g. does globbing internally. Usually you should just put the generated sources as inputs and Meson will set up all dependencies automatically.
```

**Comment by fukanchik** [comment]
This was probably caused by 
`depends: a_lib,`
instead of
`depends: [a_lib],`
