### ISSUE TITLE
b_pch=false option doesn't work correctly on 'Developer Powershell for VS' shell with Meson v.1.2.0 and after

### ISSUE THREAD

**Issue by nbyavuz** [mesonbuild/meson#12494]
**Describe the bug**

There is an issue while building Postgres with Meson on Windows.

When `b_pch=false` option is used on `Developer Powershell for VS` shell, build fails with:
`ninja: error: 'src/backend/postgres_lib.a.p/meson_pch-c.obj', needed by 'src/backend/postgres.exe', missing and no known rule to make it.` 

Please note that, this failure occurs with Meson v.1.2.0 and after, v1.1.0 and before work correctly.

If the `b_pch=true` option or the default powershell is used, Postgres gets built successfully with Meson v.1.20 and after.

**To Reproduce**
I couldn't reproduce that on minimal repository. Sorry for that. 

Steps to reproduce that on Postgres repository:
1- Clone [Postgres](https://github.com/postgres/postgres)
2- Install Meson v.1.2.0 or newer (I installed it with pip)
3- Open Developer Powershell for VS
4- Build project with: `meson setup -Db_pch=false build` then `meson compile -C build`
6- You should see: `ninja: error: 'src/backend/postgres_lib.a.p/meson_pch-c.obj', needed by 'src/backend/postgres.exe', missing and no known rule to make it.` error.

**Expected behavior**
Project gets built successfully when b_pch=false is used.

**system parameters**
* Build: Native build
* OS: Windows 11 - Developer Powershell for VS
* Python version: 3.11.5
* Meson version: v1.1.0 and before works correctly, v.1.2.0 and after does not (including upstream Meson)
* Ninja version: 1.11.5

**Comment by tristan957** [comment]
@nbyavuz can you do a bisect to see what commit introduced the regression?

**Comment by nbyavuz** [comment]
@tristan957 it looks like d391e5281c982899e17c7a5ceeca30262f1640ea introduced the regression.

**Comment by xclaesse** [comment]
@nbyavuz Could you please try that fix? https://github.com/mesonbuild/meson/pull/12498.

**Comment by nbyavuz** [comment]
@xclaesse, https://github.com/mesonbuild/meson/pull/12498 fixed the issue, thanks!
