### ISSUE TITLE
meson does not support many compiler and this makes all projects using meson unusable

### ISSUE THREAD

**Issue by winspool** [mesonbuild/meson#12501]
**User experience: unusable build system**
I tried a project, which depends on "meson", 
and my user experience is: "unusable build system"

**Describe the bug**
All projects using meson are broken,
when the project user tries to use a compiler different from the few compilers supported by meson.

Examples for my tries using the "criterion" project, which depends on "meson":
```
CC=tcc  CFLAGS="-v"  meson  setup

../meson.build:1:0: ERROR: Unknown compiler(s): [['tcc']]
```

Next try:
```
CC=owcc  CFLAGS="-v -blinux -I$WATCOM/lh"  meson  setup

../meson.build:1:0: ERROR: Unknown compiler(s): [['owcc']]
```

See also:  https://github.com/Snaipe/Criterion/issues/514

**To Reproduce**
* checkout criterion from https://github.com/Snaipe/Criterion
* create a build dir
* cd into the build dir
* first try: `CC=tcc CFLAGS="-v" meson setup`
* second try: `CC=owcc CFLAGS="-v -blinux -I$WATCOM/lh" meson setup`

**Expected behavior**
A build system has to work

**system parameters**
* native build, x86_64
* ubuntu 2304 (lunar)
* python 3.11.4
* meson 1.0.1
* ninja 1.11.1

-- 
Regards ... Detlef

**Comment by thesamesam** [comment]
See https://github.com/mesonbuild/meson/issues/5406.

**Comment by xclaesse** [comment]
Closing as dup.
