### ISSUE TITLE
Invalid foreach behaviour on Windows

### ISSUE THREAD

**Issue by jgmdev** [mesonbuild/meson#12512]
**Description**
The foreach seems to iterate a list|array recursively on windows

**Sample code**

Extract from: https://github.com/pragtical/pragtical/pull/43/commits/cad343a8b48c186212cfeca5509afe39c5a643c5#diff-56cf0736c609eb4cddae5937c3eff06c3b4592de7ad88fb1406cf6e72b2d4362

```meson
hpre = '#include "@0@/../lj_arch.h"'.format(meson.current_source_dir())

checkdefs = [
    ['LJ_LE', '1', ['-D', 'ENDIAN_LE']],
    ['LJ_ARCH_BITS', '64', ['-D', 'P64']],
    ['LJ_HASJIT', '1', ['-D', 'JIT']],
    ['LJ_HASFFI', '1', ['-D', 'FFI']],
    ['LJ_DUALNUM', '1', ['-D', 'DUALNUM']],
    ['LJ_ARCH_HASFPU', '1', ['-D', 'FPU']],
    ['LJ_ABI_SOFTFP', '0', ['-D', 'HFABI']],
    ['LJ_NO_UNWIND', '1', ['-D', 'NO_UNWIND']],
    ['LJ_ABI_PAUTH', '1', ['-D', 'PAUTH']],
]

foreach def: checkdefs
    if cc.get_define(def[0], prefix: hpre) == def[1]
        dasm += def[2]
    endif
endforeach
```

The above produces the error:
> ERROR: Could not get define '1'

If I change the foreach loop to:

```meson
foreach def: checkdefs
    if def[0] != '1' and cc.get_define(def[0], prefix: hpre) == def[1]
        dasm += def[2]
    endif
endforeach
```

The error is:
> ERROR: Could not get define '-D'

So to workaround the recursive foreach bug had to:

```meson
foreach def: checkdefs
    def_valid = def[0].contains('LJ_')
    if def_valid and cc.get_define(def[0], prefix: hpre) == def[1]
        dasm += def[2]
    endif
endforeach
```

This happened while copying the LuaJIT meson wrap from this [Aegisub project fork](https://github.com/arch1t3cht/Aegisub/tree/feature/subprojects/packagefiles/luajit) and doing a PR https://github.com/pragtical/pragtical/pull/43 into the Pragtical editor which has a CI check that triggers msys2 and msvc builds. 

* [Build Log #1](https://github.com/pragtical/pragtical/actions/runs/6881771799)
* [Build Log #2](https://github.com/pragtical/pragtical/actions/runs/6881860762)

**System**
* Build type: native, github workflow on windows-2019 (msys2 and msvc) 
* OS: Windows
* Meson: 1.2.3

**Comment by eli-schwartz** [comment]
I cannot foresee a reason why this would be operating system specific. But looking at your example there seems to be more going on here:

```
if host_machine.cpu_family() == 'x86'
    checkdefs += ['__SSE2__', '1', ['-D', 'SSE']]
endif
```

Maybe Windows just happens to be the only x86 operating systems you are testing? :)

```
project('print defs', 'c')

checkdefs = [
    ['LJ_LE', '1', ['-D', 'ENDIAN_LE']],
    ['LJ_ARCH_BITS', '64', ['-D', 'P64']],
    ['LJ_HASJIT', '1', ['-D', 'JIT']],
    ['LJ_HASFFI', '1', ['-D', 'FFI']],
    ['LJ_DUALNUM', '1', ['-D', 'DUALNUM']],
    ['LJ_ARCH_HASFPU', '1', ['-D', 'FPU']],
    ['LJ_ABI_SOFTFP', '0', ['-D', 'HFABI']],
    ['LJ_NO_UNWIND', '1', ['-D', 'NO_UNWIND']],
    ['LJ_ABI_PAUTH', '1', ['-D', 'PAUTH']],
]

if host_machine.cpu_family() == 'x86'
    checkdefs += ['__SSE2__', '1', ['-D', 'SSE']]
endif

message(checkdefs)
```


```
$ CC='gcc -m32' meson setup builddir-32
[...]

Host machine cpu family: x86
Host machine cpu: i686
Message: [['LJ_LE', '1', ['-D', 'ENDIAN_LE']], ['LJ_ARCH_BITS', '64', ['-D', 'P64']], ['LJ_HASJIT', '1', ['-D', 'JIT']], ['LJ_HASFFI', '1', ['-D', 'FFI']], ['LJ_DUALNUM', '1', ['-D', 'DUALNUM']], ['LJ_ARCH_HASFPU', '1', ['-D', 'FPU']], ['LJ_ABI_SOFTFP', '0', ['-D', 'HFABI']], ['LJ_NO_UNWIND', '1', ['-D', 'NO_UNWIND']], ['LJ_ABI_PAUTH', '1', ['-D', 'PAUTH']], '__SSE2__', '1', ['-D', 'SSE']]
```

Notice how the last checkdefs has taken an array and added its contents at the end. The actual array itself has these elements:
- `['LJ_LE', '1', ['-D', 'ENDIAN_LE']]`
- `['LJ_ARCH_BITS', '64', ['-D', 'P64']]`
- `['LJ_HASJIT', '1', ['-D', 'JIT']]`
- `['LJ_HASFFI', '1', ['-D', 'FFI']]`
- `['LJ_DUALNUM', '1', ['-D', 'DUALNUM']]`
- `['LJ_ARCH_HASFPU', '1', ['-D', 'FPU']]`
- `['LJ_ABI_SOFTFP', '0', ['-D', 'HFABI']]`
- `['LJ_NO_UNWIND', '1', ['-D', 'NO_UNWIND']]`
- `['LJ_ABI_PAUTH', '1', ['-D', 'PAUTH']]`
- `'__SSE2__'`
- `'1'`
- `['-D', 'SSE']`


The += operator expects to receive an array of "things to add", but also accepts a single non-array and just adds that one thing. This is not the single most joyous aspect of the meson.build DSL to me, personally, but it is what was eventually settled on... the choices, in terms of DSL design, are:
- accept `+= [....]` and extend the array with `...`, but utterly reject `+= 'string'`
- ditto, but accept `+= 'string'` and extend the array with `'string'`
- accept += [...] and extend the array with `[...]`, accept `+= 'string'` and extend the array with `'string'`

The first case would be the least ambiguous, but also potentially annoy people in a "simple common case of adding one string to the array".
The third case makes it impossible to extend the array with multiple items at the same time.

**Comment by QuLogic** [comment]
> The += operator expects to receive an array of "things to add", but also accepts a single non-array and just adds that one thing.

While this is all true, I'm not sure it's too important here, as everything is an array here. It is currently doing the equivalent of:
```
[[1, 2], [3, 4]] + [5, 6] -> [[1, 2], [3, 4], 5, 6]
```

All that's needed is another level:
```meson
project('print defs', 'c')

checkdefs = [
    ['LJ_LE', '1', ['-D', 'ENDIAN_LE']],
    ['LJ_ARCH_BITS', '64', ['-D', 'P64']],
    ['LJ_HASJIT', '1', ['-D', 'JIT']],
    ['LJ_HASFFI', '1', ['-D', 'FFI']],
    ['LJ_DUALNUM', '1', ['-D', 'DUALNUM']],
    ['LJ_ARCH_HASFPU', '1', ['-D', 'FPU']],
    ['LJ_ABI_SOFTFP', '0', ['-D', 'HFABI']],
    ['LJ_NO_UNWIND', '1', ['-D', 'NO_UNWIND']],
    ['LJ_ABI_PAUTH', '1', ['-D', 'PAUTH']],
]

if host_machine.cpu_family() == 'x86'
    checkdefs += [
      ['__SSE2__', '1', ['-D', 'SSE']]
    ]
endif

message(checkdefs)
```
```
Message: [['LJ_LE', '1', ['-D', 'ENDIAN_LE']], ['LJ_ARCH_BITS', '64', ['-D', 'P64']], ['LJ_HASJIT', '1', ['-D', 'JIT']], ['LJ_HASFFI', '1', ['-D', 'FFI']], ['LJ_DUALNUM', '1', ['-D', 'DUALNUM']], ['LJ_ARCH_HASFPU', '1', ['-D', 'FPU']], ['LJ_ABI_SOFTFP', '0', ['-D', 'HFABI']], ['LJ_NO_UNWIND', '1', ['-D', 'NO_UNWIND']], ['LJ_ABI_PAUTH', '1', ['-D', 'PAUTH']], ['__SSE2__', '1', ['-D', 'SSE']]]
```

**Comment by eli-schwartz** [comment]
> While this is all true, I'm not sure it's too important here, as everything is an array here. It is currently doing the equivalent of:
> [...]
> All that's needed is another level:

Yes, sorry if I wasn't clear -- that's exactly what I meant by what I said. ;)

In other words:

> It's very important that everything is an array here, since that means that you're appending the contents of the array, rather than the array itself.

The implication is that `+= [ [...] ]` would append the *contents* of the array, that being... `[...]` (also an array).

I neglected to specifically spell this out.

**Comment by jgmdev** [comment]
> All that's needed is another level:

> The implication is that `+= [ [...] ]` would append the _contents_ of the array, that being... `[...]` (also an array).

Ah! Didn't saw this, sorry for the noise, will also notify the AegiSub fork maintainer about the array concatenation mistake. Thanks a lot!

**Comment by eli-schwartz** [comment]
I don't know that I would go so far as to call it noise. It's a pitfall that, while reliably defined, is not necessarily intuitive and may not be obvious from reading the docs. It's very plausible to say this is a still-valid bug report that should be fixed by making it clearer in the documentation.
