### ISSUE TITLE
Add a `fallback` argument for `find_program`

### ISSUE THREAD

**Issue by gerion0** [mesonbuild/meson#12529]
Not a bug but a (possible) enhancement.

`dependency` has a `fallback` argument which adds some syntactic sugar for subprojects:
```meson
my_dep = dependency('libfoo', fallback: ['libfoo-project', 'libfoo_dep'])
# vs.
my_dep = dependency('libfoo')
if not my_dep.found()
  libfoo_proj = subproject('libfoo-project')
  my_dep = libfoo_proj.get_variable('libfoo_dep')
endif
```
This is basically for the case where you need subprojects to provide code to link against.
However, sometimes (at least I use them for that) subprojects also provide code/binaries that need to be executed in the build process.

Currently, the following Meson code achieves this:
```meson
my_prog = find_program('foo', required: false)
if not my_prog.found()
  foo_proj = subproject('foo-project')
  my_prog = foo_proj.get_variable('foo_prog')
endif
```
What do you think of providing (analogous to `dependency`)?:
```meson
my_prog = find_program('foo', fallback: ['foo-project', 'foo_prog'])
```

**Comment by xclaesse** [comment]
You can add `[provide] programs = foo` in your subproject wrap file. `find_program('foo')` will then automatically use that subproject. Note that the subproject must use `meson.override_find_program()`.

- https://mesonbuild.com/Wrap-dependency-system-manual.html#provide-section
- https://mesonbuild.com/Reference-manual_builtin_meson.html#mesonoverride_find_program

**Comment by gerion0** [comment]
But the logic is different here, isn't it? When I understand it correctly, in my case the system program is used when found, while with the provide section the subproject is preferred.

**Comment by xclaesse** [comment]
No, it's a fallback when not found on system in both cases.

**Comment by gerion0** [comment]
Ok, I was especially referring to this part of the documentation (highlight by me):
> `meson.override_find_program()`
specifies that whenever `find_program()` is used to find a program named `progname`, **_Meson should not look it up on the system but instead return program_**, which may either be the result of `find_program()`, `configure_file()` or `executable()`.

Anyway, thank you. Maybe you want to consider a `fallback` argument regardless because currently two different ways exist to address the same problem: `dependency()` has a `fallback` argument _and_ the provide section, `find_program` has only the latter.

**Comment by xclaesse** [comment]
That's to be called in the subproject, I'm that case it all the already did the fallback.

**Comment by gerion0** [comment]
Ok, thanks for the clarification.
