### ISSUE TITLE
/WHOLEARCHIVE creation can use \ vs. / slash, causing compilation failures

### ISSUE THREAD

**Issue by pokowaka** [mesonbuild/meson#12534]
**Describe the bug**

We are porting the QEMU build system to run natively on Windows using clang-cl. The meson generator with the ninja backend will eventually produce a snippet like this:

(Note this is layed out for readability and just a partial snippet)
```
   LINK_ARGS = "-Wl,/nologo" "-Wl,/DEBUG"
   "-Wl,/PDB:qemu-system-x86_64.pdb" "-Wl,/WHOLEARCHIVE:libhwcore.fa"
   "-Wl,/WHOLEARCHIVE:libqom.fa" "-Wl,/WHOLEARCHIVE:libevent-loop-base.a"
   "-Wl,/WHOLEARCHIVE:gdbstub\libgdb_softmmu.fa"  <--- BACKSLASH!
  "-Wl,/WHOLEARCHIVE:libio.fa" "-Wl,/WHOLEARCHIVE:libcrypto.fa"
 ```

**To Reproduce**

Non trivial, you will need to obtain all the sources from https://android.googlesource.com/platform/external/qemu.git/+/refs/heads/emu-dev

**Expected behavior**

The MSVC backend accept both forward and backward slash:

see: https://learn.microsoft.com/en-us/cpp/build/reference/cl-filename-syntax?view=msvc-170

So throughout the codebase it is probably safe to use '/' vs. whatever the OS suggests.

The culprit is possibly here in `get_target_filename_for_linking`: https://github.com/mesonbuild/meson/blob/dfd8cfbd8d9ce03473cb17a722400cb4a8d1b67e/mesonbuild/backend/backends.py#L351

where paths are constructed that can use `\` in windows.

**Comment by bruchar1** [comment]
Fixed by #12564
