### ISSUE TITLE
Swift: `static_library()` ignores `swift_args`

### ISSUE THREAD

**Issue by noscript** [mesonbuild/meson#12533]
**Describe the bug**

I'm trying to enable interoperability with C++ by passing `-cxx-interoperability-mode=default` to `swiftc` but   `static_library()` ignores `swift_args`.

**To Reproduce**

```
project('swift_lib', 'swift')

br_inc = include_directories('Sources/CppBridge')

lib = static_library(
  'MyLib',
  'Sources/MyLib/MyLib.swift',
  swift_args: ['-cxx-interoperability-mode=default'],
  include_directories: br_inc
)

dep = declare_dependency(
  include_directories: [
    include_directories('.'),
    br_inc
  ],
  link_with: lib
)
 ```

The logs show that `swift_args` flags are not passed to `swiftc`:

```
/usr/bin/meson --internal dirchanger ~/proj/subprojects/swift/libMyLib.a.p swiftc -c -O \
  -module-name MyLib \
  -I~/proj/subprojects/swift/Sources/CppBridge \
  ~/proj/subprojects/swift/Sources/MyLib/MyLib.swift
```

**Expected behavior**

The flags listed in `swift_args` are passed to `swiftc`.

**system parameters**
> Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?

native

> what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)

Debian 12

> what Python version are you using e.g. 3.8.0

3.11.2

> what `meson --version`

1.0.1

> what `ninja --version` if it's a Ninja build

1.11.1

**Comment by tristan957** [comment]
We don't have any Swift contributors to my knowledge. Would you be interested in sending a PR

**Comment by dcbaker** [comment]
If you're interested, the place to start is in `backend/ninjabackend.py` and the function is either `generate_swift_compile` or `generate_swift_target` (can't remember off the top of my head). Pretty sure rust used to have the same issue, so if you look through the git log for `rust_args` you'll probably find something helpful

**Comment by noscript** [comment]
Sure, I will to make a PR.
