### ISSUE TITLE
 ERROR: Unknown compiler(s)

### ISSUE THREAD

**Issue by voss01** [mesonbuild/meson#12594]
**Describe the bug**

I am triyng to install https://github.com/Mesa3D/mesa for this I **need meson**.
like this:
```
$ mkdir build
$ cd build
$ meson ..
$ sudo ninja install
```
The problem is that when I am in the build folder and do
` meson ..`
 it gives this error:

```
../meson.build:21:0: ERROR: Unknown compiler(s): [['cc'], ['gcc'], ['clang'], ['nvc'], ['pgcc'], ['icc'], ['icx']]
The following exception(s) were encountered:
Running `pgcc --version` gave "[Errno 2] No such file or directory: 'pgcc'"
Running `icc --version` gave "[Errno 2] No such file or directory: 'icc'"
Running `icx --version` gave "[Errno 2] No such file or directory: 'icx'"

```
**To Reproduce**

```
The Meson build system
Version: 1.2.2
Source dir: /Users/gabrielvoss/Downloads/mesa-23.3.0
Build dir: /Users/gabrielvoss/Downloads/mesa-23.3.0/build
Build type: native build
Project name: mesa
Project version: 23.3.0
```

**Expected behavior**
Should build the project from MESA3D

**system parameters**
INTEL CHIP MAC, RUNNING ON MAC OS VENTURA 13.6.

**Comment by eli-schwartz** [comment]
Meson seems to be saying you don't have a compiler installed.

**Comment by voss01** [comment]
> Meson seems to be saying you don't have a compiler installed.

I have Xcode installed and launched the GUI app, as said in the meson guide.
