### ISSUE TITLE
"native: false" in add_global_arguments applies arguments to a native build

### ISSUE THREAD

**Issue by intractabilis** [mesonbuild/meson#12639]
# System info
Meson 1.3.0
Python 3.11.6
Manjaro Linux 23.1.0

# Description
I have the following call in my `meson.build`
```meson
add_global_arguments(
    '--specs=nano.specs',
    '-mcpu=cortex-m7',
    '-mthumb',
    language: ['cpp'],
    native: false)
```
If I read the documentation correctly, since I used `native: false`, these arguments should only apply to a cross-build. However, this is not the case. Meson tries to use these arguments in a native compilation.

# To Reproduce
Here is `meson.build`:
```meson
project(
    'test-native',
    ['cpp'],
    version : '0.1',
    default_options: ['cpp_std=gnu++17'])

add_global_arguments(
    '--specs=nano.specs',
    '-mcpu=cortex-m7',
    '-mthumb',
    language: ['cpp'],
    native: false)

executable('test-native', 'test-native.cpp')
```
`test-native.cpp`:
```cpp
int main(int argc, char *argv[]) {}
```
Then
```
$ meson setup --buildtype debug build/debug
The Meson build system
Version: 1.3.0
Source dir: /somedir/test-native
Build dir: /somedir/test-native/build/debug
Build type: native build
Project name: test-native
Project version: 0.1
C compiler for the host machine: cc (gcc 13.2.1 "cc (GCC) 13.2.1 20230801")
C linker for the host machine: cc ld.bfd 2.41.0
C++ compiler for the host machine: c++ (gcc 13.2.1 "c++ (GCC) 13.2.1 20230801")
C++ linker for the host machine: c++ ld.bfd 2.41.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Build targets in project: 1

test-native 0.1

  User defined options
    buildtype: debug

Found ninja-1.11.1 at /usr/bin/ninja
$ meson compile -C build/debug
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /usr/bin/ninja -C /somedir/test-native/build/debug
ninja: Entering directory `/somedir/test-native/build/debug'
[1/2] Compiling C++ object test-native.p/test-native.cpp.o
FAILED: test-native.p/test-native.cpp.o
c++ -Itest-native.p -I. -I../.. -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu++17 -O0 -g --specs=nano.specs -mcpu=cortex-m7 -mthumb -MD -MQ test-native.p/test-native.cpp.o -MF test-native.p/test-native.cpp.o.d -o test-native.p/test-native.cpp.o -c ../../test-native.cpp
c++: warning: ‘-mcpu=’ is deprecated; use ‘-mtune=’ or ‘-march=’ instead
c++: fatal error: cannot read spec file ‘nano.specs’: No such file or directory
compilation terminated.
ninja: build stopped: subcommand failed.
```
Surely I can use `native: true` in the `executable` call. However, in the real project, I have libraries that are compiled both in cross and native compilations.

**Comment by QuLogic** [comment]
> ```meson
> executable('test-native', 'test-native.cpp')
> ```

The [default for `native`](https://mesonbuild.com/Reference-manual_functions.html#executable_native) is `false`, meaning this _isn't_ a native executable. You also didn't pass `--cross-file`, so `host_machine` == `build_machine`, and this would have failed for native or cross.

**Comment by intractabilis** [comment]
> The [default for `native`](https://mesonbuild.com/Reference-manual_functions.html#executable_native) is `false`, meaning this _isn't_ a native executable. You also didn't pass `--cross-file`, so `host_machine` == `build_machine`, and this would have failed for native or cross.

Look at the output of the Meson in the initial post:
```
Build type: native build
```

**Comment by dcbaker** [comment]
This option is really badly named. It should really be machine : build|host. In a host == build configuration (native) setting the native keyword does nothing, since all binaries are for both the host and the build machine at the same time

**Comment by intractabilis** [comment]
Are you saying I can build a native executable while starting Meson with a `--cross-file` option?

**Comment by intractabilis** [comment]
Closing since it seems like I misunderstood the documentation.
