### ISSUE TITLE
b_sanitize=address is not handled when used on add_project_arguments

### ISSUE THREAD

**Issue by marcosps** [mesonbuild/meson#12651]
**Describe the bug**
We would like to set -fsanitize=address only when doing debug build. For purpose we have the following rule:

```
buildtype = get_option('buildtype')                                                                                                  
if buildtype == 'debug' or buildtype == 'debugoptimized'                                                                             
  add_project_arguments(['-g3', '-fsanitize=address']                                                                                
                        , language : 'cpp')                                                                                          
  add_project_link_arguments(['-fsanitize=address']                                                                                  
                        , language : 'cpp')                                                                                          
endif  
```
But when running the setup phase, we see

```
meson.build:19: WARNING: Consider using the built-in option for sanitizers instead of using "-fsanitize=address".
meson.build:21: WARNING: Consider using the built-in option for sanitizers instead of using "-fsanitize=address".
```

When changing the '-fsanitize=address' to 'b_sanitize=address', the compilation fails with

```
...
FAILED: libcextract/libcextract.a.p/ArgvParser.cpp.o 
clang++ ... -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -std=c++20 -O0 -g -Wno-unused-parameter -Wno-vla-extension -g3 b_sanitize=address -fPIC -MD -MQ ...
clang-16.0: error: no such file or directory: 'b_sanitize=address'
```

So it does not convert the b_sanitize option to -fsanitize=address, as it was implied.

**To Reproduce**
Described earlier.

**Expected behavior**
To be working :)

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
native build
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
openSUSE Tumbleweed
* what Python version are you using e.g. 3.8.0
python 3.11.5
* what `meson --version`
1.2.1
* what `ninja --version` if it's a Ninja build
1.11.1

**Comment by eli-schwartz** [comment]
Meson told you that b_sanitize is a *builtin* option, not a compiler option. When you use it (passed on the command line via `meson setup -Db_sanitize=address` or via the project() function default_options) meson can provide consistent and advanced handling for it.

**Comment by marcosps** [comment]
> Meson told you that b_sanitize is a _builtin_ option, not a compiler option. When you use it (passed on the command line via `meson setup -Db_sanitize=address` or via the project() function default_options) meson can provide consistent and advanced handling for it.

So in this, shouldn't meson stop complaining about it? I mean, if this is a compiler feature, and it's only meant to be used when a specific build type is passed, shouldn't meson to respect it?

**Comment by eli-schwartz** [comment]
Meson sometimes offers a suggestion that you should use its builtin options instead of compiler features, this isn't too out of the ordinary.

The only thing that's special here is that you essentially want the value of -Db_sanitize= to depend on the value of -Ddebug= which I actually find a bit odd. What if people want to build production binaries that have debug sections -- maybe even splitdebug? How do they turn sanitizers off?

**Comment by eli-schwartz** [comment]
If you want a development profile with a common collection of options to automatically set, then --native-file might be able to help you, since a native file e.g. `profiles/dev.ini` can contain settings for builtin options.
