### ISSUE TITLE
Race condition in project reconfiguration.

### ISSUE THREAD

**Issue by trhd** [mesonbuild/meson#1267]
Have

meson.build:
```
project('sct', 'c')
ARGS = []
if get_option('NO_FAIL')
        ARGS += [ '-DNOFAIL=1' ]
endif
bin = executable('sct', 'main.c', c_args : ARGS)
```

main.c:
```
#ifndef NOFAIL
#error No fail not defined.
#endif

int main() {
        return 0;
}
```

meson_options.txt:
```
option('NO_FAIL',
        type : 'boolean',
        value : 'false',
        description : 'foobar')
```

and observe as the command

`rm -rf b ; ../meson.py b &&../mesonconf.py -DNO_FAIL=true b && ninja -C b`

(I had these in a subfolder in meson's source directory.)

fails randomly.

By introducing a delay (as seen below) the problem more or less disappears.

`rm -rf b ; ../meson.py b && sleep 1 && ../mesonconf.py -DNO_FAIL=true b && ninja -C b`

**Comment by nirbheek** [comment]
This is sadly a known bug in Ninja: https://github.com/ninja-build/ninja/issues/371

**Comment by trhd** [comment]
Meh. Wish I knew that an hour ago.

Should I close this then?

**Comment by nirbheek** [comment]
Sorry for the time wasted. If you are familiar with C++, would you be interested in fixing it in Ninja? Apparently it's not a very difficult feature to add, but the last time I looked at it, I got discouraged very quickly because of the codebase 😅

**Comment by nirbheek** [comment]
FWIW, you can also set `-DNO_FAIL=true` while running `meson` itself. There is hardly ever a good reason to run mesonconf immediately after running meson except in automated builds/testing. Still annoying though!

**Comment by trhd** [comment]
I don't have a real use case for that. Just happened to notice that while working on other things. I'm afraid though, that others might run into that as well and depending on the situation it could cause serious problems.

Unfortunately I don't think I currently have the time to look into ninja, but you never know...

**Comment by QuLogic** [comment]
ninja-build/ninja#1219

**Comment by nirbheek** [comment]
@QuLogic Very nice! I'm really glad you looked into that :)

**Comment by nirbheek** [comment]
I'm going to close this since it's not a Meson bug and we have an upstream bug to track it.
