### ISSUE TITLE
BUG: `/Zc:__cplusplus` not set for clang-cl

### ISSUE THREAD

**Issue by h-vetinari** [mesonbuild/meson#12670]
**Describe the bug**
MSVC has a broken `__cplusplus` define as described here:

https://github.com/mesonbuild/meson/blob/f1035e0cd0c888bc7aa18fc6e5d92c93e9e96a83/mesonbuild/compilers/cpp.py#L754-L758

However, clang-cl (emulating MSVC's behaviour) tries to mimic that, and ends up needing the same define to work properly. Encountered with [scipy](https://github.com/scipy/scipy/issues/19726) while working around another bug.

**To Reproduce**
Use
```
#if __cplusplus >= 201703L
# include <cstdlib>
#else
# error __cplusplus not set correctly
#endif
int* p = static_cast<int*>(std::aligned_alloc(1024, 1024));
```
on windows and compile with clang-cl. I'd godbolt it but clang-cl [isn't supported](https://github.com/compiler-explorer/compiler-explorer/issues/5834) yet.

**Expected behavior**
Compilation on windows with clang-cl using C++17 features and standard macros should work.

**Comment by h-vetinari** [comment]
I think I feel prey to the multiple different ways that MSVC is non-compliant (and how well clang-cl tries to mimic it) and ended up misdiagnosing this. I'll close this for now, apologies for the noise.

**Comment by eli-schwartz** [comment]
So does that mean that clang-cl has the accurate `__cplusplus` or doesn't it?

If it doesn't, then I guess we should still fix *that*.

**Comment by h-vetinari** [comment]
> So does that mean that clang-cl has the accurate `__cplusplus` or doesn't it?

From what I can tell, it _does_ have the right `__cplusplus` value, otherwise we wouldn't enter the `# if` branch where the error occurs. It's possible that it's still a good idea to insert `/Zc:__cplusplus` explicitly also for clang-cl.
