### ISSUE TITLE
Error while installing glib

### ISSUE THREAD

**Issue by ttsiakir** [mesonbuild/meson#12729]
Encontered this bug while trying to setup glib ([link](https://gitlab.gnome.org/GNOME/glib/-/blob/main/INSTALL.md?ref_type=heads)):

*user@pc_id**:~/gitlab/glib$ sudo meson install -C _build
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 146, in run
    return options.run_func(options)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 797, in run
    b = build.load(opts.wd)
  File "/usr/lib/python3/dist-packages/mesonbuild/build.py", line 2868, in load
    obj = pickle.load(f)
ModuleNotFoundError: No module named 'mesonbuild.utils'

ERROR: Unhandled python exception

    **This is a Meson bug and should be reported!**

**Comment by phdye** [comment]
I'm seeing the same error attempting to build/install libdrm-2.4.120 on Ubuntu 22.04.4 LTS in WSL2.

**Comment by tristan957** [comment]
This is an issue where the Python interpreter being used to run Meson is not the same as the one that installed meson.
