### ISSUE TITLE
Subprojects update fails for all Git wraps with revision = 'head'

### ISSUE THREAD

**Issue by amyspark** [mesonbuild/meson#12730]
**Describe the bug**

As per https://mesonbuild.com/Wrap-dependency-system-manual.html#specific-to-vcsbased-wraps, we can use `head` to tell Meson to always use the latest commit when checking a subproject out:

>  revision - name of the revision to checkout. Must be either: a valid value (such as a git tag) for the VCS's checkout command, or (for git) head to track upstream's default branch. Required.

However, if one issues a `meson subprojects update` after a build,

https://github.com/mesonbuild/meson/blob/ae857e841b0a6b9b595583e74f5e21676bb83f9d/mesonbuild/msubprojects.py#L375-L377

this block will instead cause all updates to fail with the following error:

```
Updating faac...
  -> Could not fetch revision head in deps/faac
fatal: couldn't find remote ref head
Git command failed: ['C:\\Program Files\\Git\\cmd\\git.EXE', 'fetch', '--refmap', '+refs/heads/*:refs/remotes/origin/*', '--refmap', '+refs/tags/*:refs/tags/*', 'origin', 'head']
(repeats for all the below deps...)
WARNING: Please check logs above as command failed in some subprojects which could have been left in conflict state: faac, faad2, flac, lame, libid3tag, libmad, libmpc, libopusenc, mp4v2, ogg, optimfrog-win-x64, opus, substrate, vorbis, wavpack, zlib
```

This is really simple to fix: just uppercase `revision` if `head` prior to issuing the Git call above:

```python
                heads_refmap = '+refs/heads/*:refs/remotes/origin/*'
                tags_refmap = '+refs/tags/*:refs/tags/*'
                if revision == 'head':
                    revision = revision.upper()
                self.git_output(['fetch', '--refmap', heads_refmap, '--refmap', tags_refmap, 'origin', revision])
```

**To Reproduce**

Clone and initialise https://github.com/dragonCodecs/libAudio, then manually switch any of the above deps to an older commit.

**Expected behavior**

Meson should be able to update these wraps.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? No
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) Windows 10 22H2
* what Python version are you using e.g. 3.8.0 3.10.7
* what `meson --version` 1.3.1
* what `ninja --version` if it's a Ninja build 1.10.2

**Comment by bruchar1** [comment]
Isn't it rather a documentation issue? Shouldn't revision in the wrap file be HEAD instead?

**Comment by amyspark** [comment]
@bruchar1 Tests also use the same convention (Git revision value in lowercase), they don't show up as broken because updating is not tested:

https://github.com/mesonbuild/meson/blob/ae857e841b0a6b9b595583e74f5e21676bb83f9d/manual%20tests/3%20git%20wrap/subprojects/samplesubproject.wrap#L4

**Comment by bruchar1** [comment]
That's a good point. I have no strong opinion about which approach is the best. I will let meson developers decide of this.

**Comment by andy5995** [comment]
I've opened https://github.com/mesonbuild/meson/pull/13840 to fix this.

Because git is case-sensitive about HEAD, my opinion is that the meson code should not convert the case, and the docs should use "HEAD" not "head".
