### ISSUE TITLE
mesontest: tests should be namespaced by subproject

### ISSUE THREAD

**Issue by gdesmott** [mesonbuild/meson#1273]
When running `mesontest` in a top project, it would be good if tests were automatically namespaced by subproject. This would make things clearer for users as they would know right away which component is to blame if a test is failing (without having to dig in logs).
It would also prevent naming clashes. At the moment, if two subproject have tests with the same name, running `mesontest $TEST-NAME` will run all of these and it's impossible to pick the one we actually care about.

We are hitting those two issues in GStreamer: https://bugzilla.gnome.org/show_bug.cgi?id=776718

**Comment by gdesmott** [comment]
Actually when running all test, they are displayed with the subproject name:

```
101/290 gstreamer / libs/gstlibscpp             OK       0.03 s
102/290 gst-plugins-base / gst/typefindfunctions  OK       0.10 s
```

So what we need here is:
-  Namespace them when running `mesontest --list` as well
-  Allow to pass the full name to `mesontest` to run a specific test

**Comment by jpakkane** [comment]
Something like this is ongoing in #1252.
