### ISSUE TITLE
Windows: meson doesnt detect gcc despite being available in PATH on MSVC dev console

### ISSUE THREAD

**Issue by aurabindo** [mesonbuild/meson#12731]
**Describe the bug**
GCC is not detected even though its not available on PATH when running under visual studio developer console

**To Reproduce**
1. Install gcc somehow (I installed Strawberry Perl which came with gcc)
2. Install Microsoft Visual Studio community edition (not VSCode)
3. Create a C/C++ project and open "Tools -> Command Line -> Developer Command Prompt"
4. Verify that gcc is available on `%PATH%` by running `where gcc`
5. Go to ninja C project with std `gnu11` so that it needs gcc, and run `meson setup b`
6. Fails with the following error:
```
The Meson build system
Version: 1.3.0
Source dir: C:\Users\aaurabin\code\dal\dc\dml2\dml21\build\win
Build dir: C:\Users\aaurabin\code\dal\dc\dml2\dml21\build\win\b
Build type: native build
Project name: dml2_1
Project version: 0.1
DEPRECATION: None of the values ['gnu11'] are supported by the c compiler.
However, the deprecated gnu11 std currently falls back to c11.
This will be an error in the future.
If the project supports both GNU and MSVC compilers, a value such as
"c_std=gnu11,c11" specifies that GNU is prefered but it can safely fallback to plain c11.

meson.build:1:0: ERROR: Compiler cl cannot compile programs.
```

**Expected behavior**
Meson finds and uses the gcc thats available on the PATH

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? native dll
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)Windows 11
* what Python version  3.12.1
* what `meson --version` 1.3
* what `ninja --version` if it's a Ninja build 1.11.1

**Comment by eli-schwartz** [comment]
This is expected behavior. Meson can be instructed to use whichever compiler you wish, using the standardized `$CC` etc. environment variables. If you don't specify a compiler, meson searches for one using a prioritized list of possible compiler names -- and for Windows, the `cl.exe` compiler comes before GCC, because it is the platform default.

(If you run meson from outside of a MSVC dev console, then it will not find that compiler, and it will move on to GCC and find that instead.)

**Comment by eli-schwartz** [comment]
The internal search order is implemented at:

https://github.com/mesonbuild/meson/blob/ae857e841b0a6b9b595583e74f5e21676bb83f9d/mesonbuild/compilers/detect.py#L39-L66
