### ISSUE TITLE
build_by_default isnt respected when install is true during compilation

### ISSUE THREAD

**Issue by apache-hb** [mesonbuild/meson#12751]
**Describe the bug**
When a build target has both `build_by_default : false` and `install : true` running `meson compile -C build` builds the target.

**To Reproduce**
```py
project('temp', 'c')

lib = library('temp', 'temp.c',
  install : true,
  build_by_default : false
)
```
```c
// temp.c
int hello(int i) {
    return i * 10;
}
```
```sh
meson setup build
meson compile -C build # ninja -C build has the same issue
```
**Expected behavior**
`temp` should only be built during installation

**system parameters**
* windows 11 pro build 22621
* meson 1.3.1
* ninja 1.11.1
* python 3.11.7

**Comment by eli-schwartz** [comment]
> When a build target has both `build_by_default : false` and `install : true` running `meson compile -C build` builds the target.

And previously, it crashed at install time.
