### ISSUE TITLE
rust: Unable to use subproject to make use of pest_derive create

### ISSUE THREAD

**Issue by austriancoder** [mesonbuild/meson#12758]
**Describe the bug**
proc_macro is not found. It looks like meson does not add add --extern proc_macro like cargo.

**To Reproduce**
Reproducer can be found here: https://github.com/austriancoder/meson-proc-macro

**Expected behavior**
Building works like with cargo.

**system parameters**
This is a native build under Fedora 39.
python: 3.12.1
meson: 1.3.1
ninja: 1.11.1

**Comment by dcbaker** [comment]
Interestingly, we add this manually in the cargo -> Meson code, so if you have a Cargo.toml that defines a proc_macro we'll add this. I think it makes sense to add this in the core Meson code, and not in the cargo translation layer

**Comment by austriancoder** [comment]
I have updated the example with the cvs example from pest docs and added a Cargo.toml.

cargo:

 `Running /home/christian/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/bin/rustc --crate-name pest_derive --edition=2021 /home/christian/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pest_derive-2.7.6/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=140 --crate-type proc-macro --emit=dep-info,link -C prefer-dynamic -C embed-bitcode=no --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=32cbfa6c317e029f -C extra-filename=-32cbfa6c317e029f --out-dir /home/christian/projects/meson-proc-macro/target/debug/deps -L dependency=/home/christian/projects/meson-proc-macro/target/debug/deps --extern pest=/home/christian/projects/meson-proc-macro/target/debug/deps/libpest-e55adae96a5156e9.rlib --extern pest_generator=/home/christian/projects/meson-proc-macro/target/debug/deps/libpest_generator-f61c55eb3afa5df6.rlib --extern proc_macro --cap-lints allow`


meson:

`FAILED: subprojects/pest_derive-2.7.6/libpest_derive.so rustc -C linker=cc --color=always -C debug-assertions=yes -C overflow-checks=no --crate-type proc-macro -g --crate-name pest_derive --emit dep-info=subprojects/pest_derive-2.7.6/pest_derive.d --emit link=subprojects/pest_derive-2.7.6/libpest_derive.so --out-dir subprojects/pest_derive-2.7.6/libpest_derive.so.p -C metadata=a7312f0@@pest_derive@sha --extern pest=subprojects/pest-2.7.6/libpest.rlib --extern pest_generator=subprojects/pest_generator-2.7.6/libpest_generator.rlib -Lsubprojects/pest-2.7.6 -Lsubprojects/ucd-trie-0.1.6 -Lsubprojects/pest_generator-2.7.6 -Lsubprojects/pest_meta-2.7.6 -Lsubprojects/once_cell-1.8.0 -Lsubprojects/proc-macro2-1.0.70 -Lsubprojects/unicode-ident-1.0.12 -Lsubprojects/quote-1.0.33 -Lsubprojects/syn-2.0.39 -C prefer-dynamic ../subprojects/pest_derive-2.7.6/src/lib.rs error[E0432]: unresolved import proc_macro --> ../subprojects/pest_derive-2.7.6/src/lib.rs:318:5 | 318 | use proc_macro::TokenStream; | ^^^^^^^^^^ maybe a missing crate proc_macro? | = help: consider adding extern crate proc_macro to use the proc_macro crate`

**Comment by dcbaker** [comment]
I had to set the edition of peat_derive to match the one in cargo to get your example to compile. I should have mentioned that

**Comment by austriancoder** [comment]
> I had to set the edition of pest_derive to match the one in cargo to get your example to compile. I should have mentioned that

But your patch is still needed - or?


```
diff --git a/subprojects/packagefiles/pest_derive/meson.build b/subprojects/packagefiles/pest_derive/meson.build
index 7e352b4..d2ef6c3 100644
--- a/subprojects/packagefiles/pest_derive/meson.build
+++ b/subprojects/packagefiles/pest_derive/meson.build
@@ -13,6 +13,7 @@ rust = import('unstable-rust')
 lib = rust.proc_macro(
   'pest_derive',
   'src/lib.rs',
+  override_options : ['rust_std=2021', 'build.rust_std=2021'],
   link_with : [pest, pest_generator],
 )
```

```
[1/3] Compiling Rust source ../subprojects/pest_derive-2.7.6/src/lib.rs
FAILED: subprojects/pest_derive-2.7.6/libpest_derive.so 
rustc -C linker=cc --color=always -C debug-assertions=yes -C overflow-checks=no --crate-type proc-macro -g --crate-name pest_derive --emit dep-info=subprojects/pest_derive-2.7.6/pest_derive.d --emit link=subprojects/pest_derive-2.7.6/libpest_derive.so --out-dir subprojects/pest_derive-2.7.6/libpest_derive.so.p -C metadata=a7312f0@@pest_derive@sha --extern pest=subprojects/pest-2.7.6/libpest.rlib --extern pest_generator=subprojects/pest_generator-2.7.6/libpest_generator.rlib -Lsubprojects/pest-2.7.6 -Lsubprojects/ucd-trie-0.1.6 -Lsubprojects/pest_generator-2.7.6 -Lsubprojects/pest_meta-2.7.6 -Lsubprojects/once_cell-1.8.0 -Lsubprojects/proc-macro2-1.0.70 -Lsubprojects/unicode-ident-1.0.12 -Lsubprojects/quote-1.0.33 -Lsubprojects/syn-2.0.39 -C prefer-dynamic ../subprojects/pest_derive-2.7.6/src/lib.rs
error[E0432]: unresolved import `proc_macro`
   --> ../subprojects/pest_derive-2.7.6/src/lib.rs:318:5
    |
318 | use proc_macro::TokenStream;
    |     ^^^^^^^^^^ maybe a missing crate `proc_macro`?
    |
    = help: consider adding `extern crate proc_macro` to use the `proc_macro` crate

error: aborting due to previous error
```

**Comment by dcbaker** [comment]
```patch
diff --git a/subprojects/packagefiles/pest_derive/meson.build b/subprojects/packagefiles/pest_derive/meson.build
index 7e352b4..ce92ef1 100644
--- a/subprojects/packagefiles/pest_derive/meson.build
+++ b/subprojects/packagefiles/pest_derive/meson.build
@@ -3,6 +3,7 @@ project(
   'rust',
   version : '2.7.6',
   license :'MIT OR Apache-2.0',
+  default_options : ['rust_std=2021'],
 )
 
 pest = subproject('pest').get_variable('lib')
-- 
2.42.0
```

With setup and build after applying the patch works for me with my PR with both rustc 1.75 and 1.77 nightly

**Comment by austriancoder** [comment]
Yeah.. pest_derive builds now.
