### ISSUE TITLE
Meson error under windows10

### ISSUE THREAD

**Issue by jsemeda** [mesonbuild/meson#12787]
I am unable to run Meson at al. I am running windows10 and every time I try to use it I get the same error .. here is the error from the log

Sanity testing C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\bin\Hostx64\x64\cl.exe
Is cross compiler: False.
Sanity check compiler command line: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\bin\Hostx64\x64\cl.exe sanitycheckc.c /Fesanitycheckc.exe /MD /nologo /showIncludes /utf-8 /link
Sanity check compile stdout:
sanitycheckc.c
LINK : error LNK2001: unresolved external symbol mainCRTStartup
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\lib\x86\MSVCRT.lib : warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64'
sanitycheckc.exe : fatal error LNK1120: 1 unresolved externals

-----
Sanity check compile stderr:

-----

meson.build:1:0: ERROR: Compiler C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\bin\Hostx64\x64\cl.exe cannot compile programs.

**Comment by gregsskyles** [comment]
I'd suspect your environment is not set up correctly as it is finding the x86 C runtime library when you are running the x64 compiler. Did you use one of the developer command prompt shortcuts from `Start | Visual Studio 2022` and if so which one? Or did you run `vcvarsall.bat` and with what arguments?

**Comment by jsemeda** [comment]
I just downloaded the msi file and installed it. The instructions did not say anything about a setup. I just followed these directions
https://mesonbuild.com/SimpleStart.html

**Comment by gregsskyles** [comment]
Those instructions say
`You can verify that your installation is working by running the Visual Studio developer tools command prompt that can be found in the start menu.`
This is what I was asking about. Did you run Meson from that prompt?
And, what was in your `meson.build` file?
