### ISSUE TITLE
Copy a file to the build directory at configure time without warnings

### ISSUE THREAD

**Issue by amezin** [mesonbuild/meson#12792]
**Describe the bug**
I want to make eslint ignore the build directory - just like Meson itself generates `.gitignore`.

However, `configure_file(copy: true)` emits a deprecation warning, and `fs.copyfile()` copies the file at build time, not configure time - so the directory won't be excluded until the project is built.

**To Reproduce**
```
project('testproj', meson_version : '>= 1.0.0')

configure_file(
  input: 'lint/eslintrc.build.yml.in',
  output: '.eslintrc.yml',
  copy: true,
)
```

**Expected behavior**
A way to copy/write a file to the build directory at configure time, without warnings.

**system parameters**
* plain native build
* Arch Linux
* Python 3.11.6
* meson 1.3.1
* ninja 1.11.1

**Comment by amezin** [comment]
In other words: please undeprecate `copy: true`, or provide a replacement. `fs.copyfile` is not a complete replacement.

**Comment by mcdurdin** [comment]
I second this. I'd add also that the documentation for `configure_file` does not say that `copy` is deprecated.
