### ISSUE TITLE
Provide meson.build language support for emacs

### ISSUE THREAD

**Issue by Nikratio** [mesonbuild/meson#1280]
For the sake of being able to use the Python mode of various editors to edit Meson file, would it be feasible to add an alternate syntax for function calls that uses `=` instead of `:` for keyword arguments?

**Comment by TingPing** [comment]
It differs from Python in other areas so that doesn't really solve the problem. Just add a real syntax highlighting support for Meson for your editor of choice, it is a fairly small language and you can probably use the Python definitions as a starting point.

**Comment by Nikratio** [comment]
It doesn't solve the problem, but it nevertheless makes editing simple build files much easier. And its one less difference to keep in mind when writing Meson files..

**Comment by nirbheek** [comment]
There's a lot more changes to keep in mind besides the kwarg syntax; for instance the string formatting is different, there are no dictionaries, and so on. I don't think we should try to converge to the Python syntax most importantly because people will start expecting more Python-specific behaviour. 

@jpakkane what do you think?

**Comment by nirbheek** [comment]
fwiw, we already have [syntax highlighting files for Vim](https://github.com/mesonbuild/meson/tree/master/syntax-highlighting/vim) and for GtkSourceView (merged upstream), and they were both derived from the Python ones. Which editor do you use?

**Comment by Nikratio** [comment]
I'm using Emacs.

**Comment by Nikratio** [comment]
Having gathered some more experience with Meson, I realize that making it more Python-like wouldn't help much with editor support. So I'm re-titling this bug :-).

**Comment by jpakkane** [comment]
[Now here](https://github.com/wentasah/meson-mode).

**Comment by nirbheek** [comment]
In MELPA now: https://melpa.org/#/meson-mode
