### ISSUE TITLE
generated headers are not added as dependencies when passed to a target from private_dir_include

### ISSUE THREAD

**Issue by apache-hb** [mesonbuild/meson#12817]
**Describe the bug**
When including a header generated from `generator.process` in a different target where dependencies are passed via `extract_all_objects(true|false)` dependencies are not generated in the proper order.

**To Reproduce**
* `meson.build`
```meson
project('buggy', 'c')
gen = generator(find_program('header.py'),
  output : [ '@BASENAME@.generated.h', '@BASENAME@.generated.c' ],
  arguments : [ '@OUTPUT0@', '@OUTPUT1@', '@INPUT@' ]
)
src = [ gen.process('lib.c'), 'lib.c' ]
lib = shared_library('bug', src)
executable('hello', 'hello.c',
  objects : lib.extract_all_objects(recursive : true),
  include_directories : lib.private_dir_include()
)
```
* `header.py`
```py
#!/usr/bin/env python
import time, sys
time.sleep(1)

with open(sys.argv[1], 'w') as f:
    f.write('#define HELLO 1\n')

with open(sys.argv[2], 'w') as f:
    f.write(f'#include "{sys.argv[1]}.h"\n')
    f.write('// i am a source file\n')
```
* `lib.c`
```c
int empty = 5;
```
* `hello.c`
```c
#include "lib.generated.h"
int main() { return HELLO * 10; }
```
* shell
```sh
meson setup build
ninja -C build
```
* error output
```
ninja: Entering directory `build'
[1/6] Compiling C object hello.exe.p/hello.c.obj
FAILED: hello.exe.p/hello.c.obj
"cl" "-Ihello.exe.p" "-I." "-I.." "-Ibug.dll.p" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W2" "/Od" "/Zi" "/Fdhello.exe.p\hello.c.pdb" /Fohello.exe.p/hello.c.obj "/c" ../hello.c
../hello.c(1): fatal error C1083: Cannot open include file: 'lib.generated.h': No such file or directory
[2/6] Generating from 'lib.c'
ninja: build stopped: subcommand failed.
```

* relevant ninja build rule
```
build hello.exe.p/hello.c.obj: c_COMPILER ../hello.c
 DEPFILE = "hello.exe.p\hello.c.obj.d"
 DEPFILE_UNQUOTED = hello.exe.p\hello.c.obj.d
 ARGS = "-Ihello.exe.p" "-I." "-I.." "-Ibug.dll.p" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W2" "/Od" "/Zi" "/Fdhello.exe.p\hello.c.pdb"
```

**Expected behavior**
meson should apply `|| bug.dll.p/lib.generated.h` to the build rule for `hello.c`

**system parameters**
* meson 1.3.1
* ninja 1.11.1
* python 3.11.7
* windows 11 build 22621

**Comment by eli-schwartz** [comment]
This is really just https://mesonbuild.com/FAQ.html#how-do-i-tell-meson-that-my-sources-use-generated-headers

As far as meson has been told this *is* the correct order already. Depending on a library doesn't have any guarantee that you need its headers. Usually we want this added as an additional source to deal with that.

The catch here is that for generators it is complicated because they are generated into the private dir once actually used. One possibility is to have a generator for the header and include that generator in both targets, which will generate it twice. Another possibility is to use custom_target instead of generator.

Accessing lib.private_dir_include() is IMO badly defined. And there's no really good way to attach additional sources to an include_directories object, either (which isn't actually the answer as there could be many targets generated there and you might only want one of them).

**Comment by apache-hb** [comment]
In my real-world use case the generator produces both a header and a source file 
```meson
lex = generator(flex,
    output : [ '@BASENAME@_flex.c', '@BASENAME@_flex.h' ],
    arguments : [
        '--outfile=@OUTPUT0@',
        '--header-file=@OUTPUT1@',
        '@INPUT@'
    ]
)
```
which is then linked into both a static library and shared module
```meson
src = [
    'src/scan.c',
    'src/ast.c',
    'src/sema.c',
    lex.process('src/pl0.l'),
    parse.process('src/pl0.y')
]

pl0_lang = shared_library('pl0_lang', src)

if module_loader.contains('static')
    # depends on pl0_flex.h and pl0_bison.h
    pl0_static = static_library('pl0_static', 'src/main_static.c',
        objects : pl0_lang.extract_all_objects(recursive : true),
        include_directories : pl0_lang.private_dir_include()
    )
endif

if module_loader.contains('shared')
    # depends on pl0_flex.h and pl0_bison.h
    pl0_shared = shared_module('pl0_shared', 'src/main_shared.c',
        objects : pl0_lang.extract_all_objects(recursive : true),
        include_directories : pl0_lang.private_dir_include()
    )
endif
```
While it would be possible to build the entire source set as both a shared module and a static library it feels like a very hacky solution. Is there a solution I may be missing to avoid beyond writing extra code to wrap access to those headers to break the header dependency?

**Comment by apache-hb** [comment]
I now realize this behaviour can be done by passing the library into `link_with` which ensures the headers are built first. Terribly sorry about this...

**Comment by lf-** [comment]
IMO this is not fixed, since `link_with` is equivalent to simply building the entire lib first, which is ... pretty much exactly what this report is describing as a problem.
