### ISSUE TITLE
`compile_commands.json` does not use absolute paths for the compiler

### ISSUE THREAD

**Issue by deribaucourt** [mesonbuild/meson#12834]
**Describe the bug**
The generated `compile_commands.json` copies the name of the compiler as it can be found in the `$PATH`. According to the [LLVM specification](https://clang.llvm.org/docs/JSONCompilationDatabase.html): *"All paths specified in the command or file fields must be either absolute or relative to this directory"*. Because the command relies on `$PATH`, it is not possible to replay the compilation database if a different environment is used. I encountered this limitation when working with an external cross-compilation SDK. The meson workspace was configured inside the SDK environment and I'd like to replay the compilation in an IDE that doesn't source the SDK environment. I need absolute paths for this.

**To Reproduce**
I used the [gtk-doc test-case](https://github.com/mesonbuild/meson/tree/master/test%20cases/frameworks/10%20gtk-doc) as an example. I ran meson and ninja to produce `compile_commands.json` inside the build directory. The `command` field references the compiler without an absolute path:
```
[{ "directory": "/home/deribaucourt/Workspace/yocto-vscode/meson/test cases/frameworks/10 gtk-doc/builddir",
    "command": "cc -Ilibfoo.so.p -I. -I.. -Iinclude -I../include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -g -fPIC -MD -MQ libfoo.so.p/foo.c.o -MF libfoo.so.p/foo.c.o.d -o libfoo.so.p/foo.c.o -c ../foo.c",
    "file": "../foo.c",
    "output": "libfoo.so.p/foo.c.o" }]
```

**Expected behavior**
`compile_commands.json` should contain the absolute compiler path instead of relying on `$PATH` to improve portability and respect the specification from LLVM:
`"command": "cc` => `"command": "/usr/bin/cc`

I had a look at the Meson and Ninja code myself to try to find a solution, but I need some pointers from the maintainers. My guess is that we need to resolve the compiler path before passing it to ninja. A less obtrusive way would be to only edit the .json file as a post processing phase.

**system parameters**
* The issue is noticeable when cross-compiling mostly, but can be easily reproduced on native builds (by looking at the command field)
* Ubuntu 22.04
* Python 3.10.12
* Meson 0.61.2
* Ninja 1.10.1

**Comment by bruchar1** [comment]
My understanding is that compdb is generated by ninja. I think if there is a bug here, it is probably more on the ninja side.

**Comment by deribaucourt** [comment]
That was my first thought as well, but Ninja only orchestrates the commands right? Meson is the tool that has knowledge of the compiler and should forward it's absolute path to ninja?
I'll also post this issue on the Ninja GitHub, have more opinions on which tool is concerned.
