### ISSUE TITLE
Windows: MSYS/MSYS2: should scripts install without .py suffix?

### ISSUE THREAD

**Issue by achadwick** [mesonbuild/meson#1283]
On Windows, _setup.py_ installs the Meson tests with `.py` suffixes. That makes sense on Windows installs which use official Windows Python and (I guess) WSH. However this is inconvenient for users on MSYS2, which normally uses bash or some other POSIX-style shell that understands `#!`. All the install docs out there from meson-built projects that I've seen say "run `meson ..`" or similar, and the need to type the unnecessary additional extension can cause confusion.

Should Meson install without the suffix on MSYS/MSYS2, or should downstream MSYS2's _PKGBUILD_ create convenience launchers? The latter seems like only a partial solution to me.

If it should be done in Meson's installer, a suitable test would be to check for the presence of the `MSYSTEM` environment variable in _setup.py_. If it is set on (`sys.platform == 'win32'`), you are on a system that normally uses bash. The MSYS2 values are `MINGW64`, `MINGW32`, and `MSYS` if you want to be more explicit.

I would be happy to test this out or create a patch.

**Comment by achadwick** [comment]
Data point: Meson's users seem to want it to be called "meson" in MSYS2: https://github.com/ebassi/graphene/pull/93#discussion_r94460954

(I assume there's an implicit "if it's being called from bash in an environment that looks Exceedingly Like Unix" in there... @TingPing?)

**Comment by jpakkane** [comment]
File extensions on Python scripts gives me a massive headache. Every single platform does it differently and some even have "helpful" scripts to mandate their way. It is absolutely terrible.

That said, if someone submits a patch that makes MSYS work without changing behaviour on any other platform we could merge that.

**Comment by nirbheek** [comment]
A workaround is to keep around symlinks in the git tree that point to the `.py` versions, but that might mess up Windows even more. :)

**Comment by msink** [comment]
I've upgrade python to 3.6 64-bit (runninng on Win7-64) - and now `pip install meson`  installed into `Python36\Scripts\meson.py`

Any other pip packages, like flake8, isort, and pip itself - installed .exe wrappers like `Python36\Scripts\flake8.exe`

And now I have to run `meson.py`, not `meson`.
Before that it was just `meson` (python was 3.5 32-bit)

**Comment by lazka** [comment]
I think this can be closed.

Meson now installs a meson.exe using autotools and I've dropped the related patches in msys2.
