### ISSUE TITLE
Inject a dependency in to a subproject

### ISSUE THREAD

**Issue by gabeblack** [mesonbuild/meson#12844]
The simplest contrived example is the following:

Suppose I have project `Foo` that has subproject `Bar`. Is there a way for `Foo` to tell `Bar` about a dependency that `Bar` needs to depend on?

If it were all in the same package, you could do it:
```
package('Foo')

foo_dep = # some dependency that Foo builds

bar_sources = []
bar_deps = []

bar_deps += foo_dep
bar_exe = executable('bar', sources, dependencies: bar_deps)
```

However, if bar_exe is put in it's own subproject, how can `foo_dep` be injected as a dependency of `bar_exe`? 

For example:

```
package('Foo')

foo_dep = # some dependency that Foo builds

bar_proj = subproject('Bar')  # not sure how I can pass 'foo_dep" to subproject 'Bar'
```
```
package('Bar')
sources = # sources
bar_deps = # dependencies

bar_exe = executable('bar', sources, dependencies: bar_deps)

```

Is this possible? If so, how? There are intriguing attributes of `custom_target` that return a `custom_idx` that seems like they can be used to modify dependencies, however, the `dep` object from `declare_dependency` doesn't appear to have something like that. Anyway, is anything like that possible?

**Comment by eli-schwartz** [comment]
> Suppose I have project `Foo` that has subproject `Bar`. Is there a way for `Foo` to tell `Bar` about a dependency that `Bar` needs to depend on?

Try using `meson.override_dependency('foo', foo_dep)` in the Foo project to globally register an override, then use `dependency('foo') in the Bar subproject to retrieve it.

Note that meson can't solve a truly cyclical dependency, but that shouldn't be a problem here.

**Comment by gabeblack** [comment]
Thank you for the prompt reply... What if `bar_exe` is not a `build_tgt` but rather a `custom_target`, can a dependency in the form of a `custom_target` be passed to it still? I don't think `custom_target` can take a dependency object in the 'depends' list so I don't think one would be able to `override_dependency`.
