### ISSUE TITLE
coverage genhtml does not use .lcovrc

### ISSUE THREAD

**Issue by wakeofluna** [mesonbuild/meson#12863]
**Describe the bug**
When generating an HTML coverage report, the final call to genhtml does not use the .lcovrc config file. This causes genhtml-specific options to not be respected, such as the dark mode theme or css settings.

**To Reproduce**
1. Setup a build root with coverage support for a C++ project
    `meson setup build -Db_coverage=True`
2. Add a .lcovrc file at source root containing at least the following:
    `genhtml_dark_mode = 1`
3. Create an html coverage report using `ninja coverage-html`

**Expected behavior**
The generated HTML report has the dark theme.

**System parameters**
* No cross build
* OS: Gentoo Linux
* Python 3.12.0
* Meson 1.3.2
* Ninja 1.11.1

**Suggested fix**
```diff
--- a/mesonbuild/scripts/coverage.py    2024-02-15 16:51:46.193390219 +0100
+++ b/mesonbuild/scripts/coverage.py    2024-02-15 16:49:38.011725455 +0100
@@ -155,7 +155,7 @@
                                    '--legend',
                                    '--show-details',
                                    '--branch-coverage',
-                                   covinfo])
+                                   covinfo] + lcov_config)
             outfiles.append(('Html', pathlib.Path(htmloutdir, 'index.html')))
         elif gcovr_exe and mesonlib.version_compare(gcovr_version, '>=3.3'):
             htmloutdir = os.path.join(log_dir, 'coveragereport')
```

**Comment by eli-schwartz** [comment]
That sounds pretty reasonable. Can you submit the change as a pull request?
