### ISSUE TITLE
Impossibility to reconfigure a subproject

### ISSUE THREAD

**Issue by Jehan** [mesonbuild/meson#12898]
**Describe the bug**

When configuring a submodule with `default_options`, the default values are stored and cannot ever be changed (as far as I could find), except by wiping the whole build directory.

**To Reproduce**

1. In a meson file, have:

```
gimpdatadir='TEST'
gimp_data = subproject('gimp-data', default_options: [  'gimpdatadir=' + gimpdatadir ])
```

In your submodule:

meson_options.txt contains:

```
option('gimpdatadir', type: 'string',  value: '',     description: 'This must be set by GIMP')
```

and `meson.build` of the submodule contains:

```
gimpdatadir = get_option('gimpdatadir')
warning('XXXXXXXX ' + gimpdatadir)
```

2. Now configure your main project, then check `meson-logs/meson-log.txt`:

```
Project name: gimp-data
Project version: 2.99.19
../../../../../../../dev/src/gimp/subprojects/gimp-data/meson.build:29: WARNING: XXXXXXXX TEST
```

So far, so good.

3. Now edit the parent `meson.build`: with `gimpdatadir=HELLO WORLD`
4. Run `ninja reconfigure`
5. Check again `meson-logs/meson-log.txt`:

```
Project name: gimp-data
Project version: 2.99.19
../../../../../../../dev/src/gimp/subprojects/gimp-data/meson.build:29: WARNING: XXXXXXXX TEST
```

**Expected behavior**

In the second run, after having changed the contents of `default_options` list, I would expect the new configure to re-configure `gimp-data` subproject. It doesn't, or in fact even worse: even when meson reconfigures `gimp-data`, it uses the old `default_options` values.

For instance, if `gimp-data` has updates (so I run `meson subprojects update`), or even if I manually delete `subprojects/gimp-data` folder, it will still configure with the old option value `gimpdatadir=TEST` even though this value doesn't exist anymore in the parent meson.build. It's cached and I could not get rid of this value.

In fact, even `meson configure --clearcache` can't get rid of this `TEST` value! So it's more cached than other type of cache! 😰

The only solution I found so far is to simply delete the whole build folder and start from scratch (which is obviously not a solution at all!).

The goal is obviously to pass some settings from a module to a submodule and that's the only way I found. The other thing I found is using `yield` options, but this is not a case where I want to sync an option of the parent module. Rather I want to pass some constructed data over to the child module. We can't ask contributors to wipe their whole build every few days to make sure they don't have issues.

**system parameters**

* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? native build
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) Debian 11.7
* what Python version are you using e.g. 3.8.0: Python 3.9.2
* what `meson --version`: 0.63.0
* what `ninja --version` if it's a Ninja build: 1.10.1

**Comment by gabeblack** [comment]
I believe there is an FAQ that addresses your question:

https://mesonbuild.com/FAQ.html#why-are-changes-to-default-project-options-ignored

Long story short, you need to delete the build folder or run `meson configure` to have your new default values take effect.

**Comment by eli-schwartz** [comment]
> In fact, even `meson configure --clearcache` can't get rid of this TEST value! So it's more cached than other type of cache! 😰

The cache clearing setting is for clearing the cache of detected dependencies. If you want to clear *everything* then of course the best way to do that is --wipe (or rm -rf).

Overall the issue here is that defaults are, well, defaults, not mandatories. If you manually set a value on the command line to the same value as a default_options we must not change that behind your back under any circumstances. Currently this information isn't tracked in any way.

**Comment by eli-schwartz** [comment]
Closing in favor of the FAQ entry.

**Comment by Jehan** [comment]
Ok I can see the reason for defaults not being easily changeable. In fact, I think my problem is something else: clearly I have been misusing the `default_options` argument to override what looks like the inability to configure the subproject.

In other words, in my example above, what I wanted to do is not changing the defaults of `gimpdatadir` option, but instead to configure the subproject with `-Dgimpdatadir=something`.

And obviously if the parent project gets reconfigured, the subproject might have to be reconfigured (or not, i.e. maybe the option values would change or not).

The wiping of directory absolutely doesn't suit us because:

1. I could only have it worked by wiping the parent build directory (so that means a lot of time wasted to rebuild everything). Just wiping `subprojects/gimp-data/` in the build directory (this folder doesn't have any meson build files that I can see anyway; no idea where subproject meson files are stored). Unless you tell me there is a way to only wipe the subproject.
2. It is a build debugging hell because when I was changing something in the main project configuration which should have triggered a different configuration for the subproject, it was not happening. For a while I thought it was a bug somewhere in the build rules until I realized the problem mentioned here.

So conclusion:

* Is there an option not to change the default options but just to set options for configuring a subproject? Your [doc](https://mesonbuild.com/Reference-manual_functions.html#subproject) doesn't indicate such an option.
* If there is no such option right now, I'd like to make a feature request. Could this report be reopened and repurposed?

**Comment by eli-schwartz** [comment]
If the gimp datadir is exported as a variable in a pkg-config file, you could do `dependency('gimp').get_variable('gimpdatadir')` in the subproject.

**Comment by Jehan** [comment]
In other words, what I want is to be able to call:

```
gimp_data = subproject('gimp-data', options: [  'gimpdatadir=' + gimpdatadir ])
```

Note the change: `s/default_options/options/`. I don't want to change the default options of the subproject (which cannot be changed, cf. the fact). I just want to be able to tweak how the subproject is configured (not call it with everything default). And this subproject configuration may change when the parent project is reconfigured too.

**Comment by Jehan** [comment]
> If the gimp datadir is exported as a variable in a pkg-config file, you could do `dependency('gimp').get_variable('gimpdatadir')` in the subproject.

This variable is not exported in a pkg-config file and in any case, `libgimp` pkg-config was not built yet, not `libgimp` itself as we "build" data first.

But yeah basically what we want is to pass data from the parent project to the subproject. I thought of using subproject meson options, but other means are welcome.

> I assume you'd need something like this anyways in order to use the subproject standalone against a previously installed gimp (not sure how important that use case is for you though).

No, we just want to pass data for the to-be-installed GIMP. For instance, the gimpdatadir which is computed in the main meson.

Now in fact, this data could be absolutely recomputed in the subproject. But that means code duplication and possible diverging bug (i.e. if we change how `gimpdatadir` is computed in the future and forgot we duplicated this code in `gimp-data` repository, then we'd have installation bugs). That's why we want to keep the code in one place and just pass the finale info.

Note also that this `gimpdatadir` is just one example. I had a bunch of other similar issues. For instance, there were part of the build which only happen according to certain condition, e.g.: `enable_some_code = get_option('this-option') and get_option('that-option')`

Now I could again recompute `enable_some_code` if I add both `this-option` and `that-option` in `meson_options.txt` with `yield=true`. But again, it would be creating duplication hence a possibility of code divergence in the future (if we change the rule of `enable_some_code` computation in the main repo.

> (not sure how important that use case is for you though)

Very, as we are splitting our data to a separate repository, but right now because of this feature absence (at least that I could find), I'm hesitating of merging this change. Because I know that we'll soon get reports of broken builds and we'll have to tell people "update the submodule and wipe the build directory regularly" which is not something I want to tell people (well the "update" part, sure, the "wipe" part, not so much).

**Comment by eli-schwartz** [comment]
Okay so let's take a step back and ask, in an ideal world how would someone use the subproject on its own and tell it where to find the datadir?

**Comment by Jehan** [comment]
It's not made to be used on its own. It's a split data repository which is only meant to be used for GIMP (well it's FLOSS, people are welcome to use how they want, but we don't intend to make this a package, it's core data).

I even start the top `meson.build` with:

```
if not meson.is_subproject()
  error('''
    gimp-data is meant to be run as a subproject of GIMP source repository only:
    https://gitlab.gnome.org/GNOME/gimp/
  ''')
endif
```
