### ISSUE TITLE
Using a compiler different from MSVC on Windows

### ISSUE THREAD

**Issue by lem0nify** [mesonbuild/meson#12900]
I'm trying to configure a build for simple pure-C helloworld program of one file (`main.c`) with Meson in Windows. The only caveat is that I want tcc (Tiny C Compiler) to be used instead of MSVC.

Here is my `meson.build`:
```meson
project('helloworld', 'c')
executable('hello', 'main.c')
```

When I type `cmd /V /C set "CC=tcc" ^& meson setup meson-build`, here is what I see:
```
The Meson build system
Version: 1.3.2
Source dir: C:\Users\lem0nify\code\c\hw
Build dir: C:\Users\lem0nify\code\c\hw\meson-build
Build type: native build
Project name: helloworld
Project version: undefined
Activating VS 17.6.5

meson.build:1:0: ERROR: Unknown compiler(s): [['tcc']]
```

There are two problems here:
1. It does not recognize `tcc` as a valid compiler.
2. It still activates MS Build Tools environment, which is not needed when using compiler different from MSVC.

I've also tried using `--cross-file`, adding `.exe` extension to `tcc` and even specifying its full path – result is the same.

I can easily do it with CMake: command `cmd /V /C set "CC=tcc" ^& cmake -G Ninja ..` does the thing. But I'd like to use Meson instead. Is it possible to force it to ignore MS Build Tools and use compilers with unix-style CLI in Windows?

**Comment by eli-schwartz** [comment]
> There are two problems here:
> 
> - It does not recognize `tcc` as a valid compiler.
> - It still activates MS Build Tools environment, which is not needed when using compiler different from MSVC.


Regarding the second point you are correct, which is also why we don't activate it.

... when we detect a supported compiler different from MSVC, anyway. :)
