### ISSUE TITLE
In a wrap, using 'head' for revision fails on Slackware 15.0

### ISSUE THREAD

**Issue by andy5995** [mesonbuild/meson#12924]
https://github.com/mesonbuild/meson/blob/95e31b756f67f72939dd1587dccca9f497e09a18/docs/markdown/Wrap-dependency-system-manual.md?plain=1#L69

Not a meson problem, that I know of. At a minimum, maybe the doc needs changing?

Locally in a [Slackware 15.0 docker container](https://github.com/andy5995/docker-slackware-build-essential), and in a GitHub runner (using the same container), I got this when revision is set to "head":

```
Cloning into 'canfigger'...
warning: Could not find remote branch HEAD to clone.
fatal: Remote branch HEAD not found in upstream origin
```

Changing the revision value in the wrap to the main branch fixed the problem. https://github.com/theimpossibleastronaut/rmw/commit/16be20376de3b9c51741ca3bf3132326e3aa4e7a#diff-9f59ad650d378ee152f72361a28fc881b2b688c44647d3e6b8f64adbfd669e08R7

**Comment by eli-schwartz** [comment]
Can't reproduce. If it's too hard to update meson on Slackware, try using a different distro.

**Comment by andy5995** [comment]
@eli-schwartz I've asked about this in a Slackware forum: https://www.linuxquestions.org/questions/showthread.php?p=6537505

Do you happen to know which version of meson changed from using the --branch argument? My error seems to be from trying to clone HEAD as a branch (using meson 0.59.4):

```
meson.build:67:0: ERROR: Git command failed: ['/usr/bin/git', 'clone', '--depth', '1', '--branch', 'HEAD', 'https://github.com/andy5995/canfigger.git', 'canfigger']
```

If you happen to know the meson version that would fix that, I can suggest upgrading Meson  to a specific version.

**Comment by andy5995** [comment]
Disregard. I think I'm a little "slow" lately after overloading myself for the last month. There's enough workarounds for this that it's a non-issue.

**Comment by eli-schwartz** [comment]
Probably #10931
