### ISSUE TITLE
Cargo wraps assume dependencies are Cargo wraps

### ISSUE THREAD

**Issue by alyssais** [mesonbuild/meson#12921]
**Describe the bug**

A Cargo wrap can incorrectly assume its dependencies are Cargo wraps, which causes build failures if they don't e.g. provide features that it's looking for.  One use case where one might encounter this is when gradually converting a large number of Rust subprojects into Cargo wraps.

**To Reproduce**

Convert the existing Cargo wrap test into this situation:

```diff
diff --git c/test cases/rust/22 cargo subproject/subprojects/bar-rs.wrap i/test cases/rust/22 cargo subproject/subprojects/bar-rs.wrap
deleted file mode 100644
index 99686e90e..000000000
--- c/test cases/rust/22 cargo subproject/subprojects/bar-rs.wrap	
+++ /dev/null
@@ -1,2 +0,0 @@
-[wrap-file]
-method = cargo
diff --git c/test cases/rust/22 cargo subproject/subprojects/bar-rs/Cargo.toml i/test cases/rust/22 cargo subproject/subprojects/bar-rs/Cargo.toml
deleted file mode 100644
index d60a5d8f1..000000000
--- c/test cases/rust/22 cargo subproject/subprojects/bar-rs/Cargo.toml	
+++ /dev/null
@@ -1,14 +0,0 @@
-[package]
-name = "bar"
-version = "0.1"
-
-# This dependency does not exist, it is required by default but this subproject
-# is called with default-features=false.
-[dependencies.notfound]
-optional = true
-version = "1.0"
-
-[features]
-default = ["f2"]
-f1 = []
-f2 = ["notfound"]
diff --git c/test cases/rust/22 cargo subproject/subprojects/bar-rs/meson.build i/test cases/rust/22 cargo subproject/subprojects/bar-rs/meson.build
new file mode 100644
index 000000000..8323d0894
--- /dev/null
+++ i/test cases/rust/22 cargo subproject/subprojects/bar-rs/meson.build	
@@ -0,0 +1,7 @@
+project('bar', 'rust')
+
+bar = static_library('bar', 'src/lib.rs', rust_crate_type : 'rlib')
+
+bar_dep = declare_dependency(link_with : bar)
+
+meson.override_dependency('bar-rs', bar_dep)
diff --git c/test cases/rust/22 cargo subproject/subprojects/foo-rs/Cargo.toml i/test cases/rust/22 cargo subproject/subprojects/foo-rs/Cargo.toml
index 796548d63..ddd63b71d 100644
--- c/test cases/rust/22 cargo subproject/subprojects/foo-rs/Cargo.toml	
+++ i/test cases/rust/22 cargo subproject/subprojects/foo-rs/Cargo.toml	
@@ -17,11 +17,11 @@ optional = true
 version = "1.0"
 
 [dependencies]
-mybar = { version = "0.1", package = "bar", default-features = false }
+mybar = { version = "0.1", package = "bar" }
 
 [features]
 default = ["f1"]
 f1 = ["f2", "f3"]
 f2 = ["f1"]
-f3 = ["mybar/f1", "dep:extra-dep", "notfound?/invalid"]
+f3 = ["mybar", "dep:extra-dep", "notfound?/invalid"]
 f4 = ["dep:notfound"]
```

Output:

```
subprojects/bar-rs/meson.build:1:0: ERROR: In subproject bar-rs: Unknown options: "bar-rs:feature-default"
```

**Expected behavior**

It might be desirable to make Cargo subprojects handle non-Cargo dependencies better.  On the other hand, maybe it's fine for the answer just to be "wait for Cargo subprojects to be mature enough that you can convert all at once", and not to bother with supporting non-Cargo dependencies.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? <ins>native</ins>
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) <ins>NixOS 24.05pre-git</ins>
* what Python version are you using e.g. 3.8.0 <ins>Python 3.11.8</ins>
* what `meson --version`  <ins>1.3.99</ins>
* what `ninja --version` if it's a Ninja build <ins>1.11.1</ins>

**Comment by alyssais** [comment]
Okay, do we close this as a Meson issue then?

**Comment by xclaesse** [comment]
it's not something I'm planning to work on at least. We can revisit later if the need persists.
