### ISSUE TITLE
 viewer/data/meson.build:11:0: ERROR: Function does not take positional arguments.

### ISSUE THREAD

**Issue by PeiyuQuan** [mesonbuild/meson#12927]
Hello
I found a new issue during install the latest aravis:

viewer/data/meson.build:11:0: ERROR: Function does not take positional arguments.
Could you help me fix it?
Thank you

root@PC93372:/usr/local/aravis/build# ninja-build
ninja-build: command not found
root@PC93372:/usr/local/aravis/build# cd ..
root@PC93372:/usr/local/aravis# meson build
The Meson build system
Version: 0.61.2
Source dir: /usr/local/aravis
Build dir: /usr/local/aravis/build
Build type: native build
Project name: aravis
Project version: 0.8.9
C compiler for the host machine: cc (gcc 11.4.0 "cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
C linker for the host machine: cc ld.bfd 2.38
C++ compiler for the host machine: c++ (gcc 11.4.0 "c++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
C++ linker for the host machine: c++ ld.bfd 2.38
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -Wduplicated-branches: YES 
Compiler for C supports arguments -Wimplicit-fallthrough: YES 
Compiler for C supports arguments -Wmisleading-indentation: YES 
Compiler for C supports arguments -Wstrict-prototypes: YES 
Compiler for C supports arguments -Wunused: YES 
Compiler for C supports arguments -Wdeclaration-after-statement: YES 
Compiler for C supports arguments -Wformat=2: YES 
Compiler for C supports arguments -Wimplicit-function-declaration: YES 
Compiler for C supports arguments -Winit-self: YES 
Compiler for C supports arguments -Wmissing-include-dirs: YES 
Compiler for C supports arguments -Wmissing-prototypes: YES 
Compiler for C supports arguments -Wpointer-arith: YES 
Compiler for C supports arguments -Wformat-nonliteral: YES 
Compiler for C supports arguments -Wenum-conversion: YES 
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Run-time dependency glib-2.0 found: YES 2.72.4
Run-time dependency gobject-2.0 found: YES 2.72.4
Run-time dependency gio-2.0 found: YES 2.72.4
Run-time dependency libxml-2.0 found: YES 2.9.13
Run-time dependency zlib found: YES 1.2.12
Run-time dependency libusb-1.0 found: YES 1.0.25
Library m found: YES
Has header "linux/if_packet.h" : YES 
Program glib-mkenums found: YES (/usr/bin/glib-mkenums)
Program glib-mkenums found: YES (/usr/bin/glib-mkenums)
Program glib-mkenums found: YES (/usr/bin/glib-mkenums)
Program glib-mkenums found: YES (/usr/bin/glib-mkenums)
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Program glib-compile-resources found: YES (/usr/bin/glib-compile-resources)
Configuring arvfeatures.h using configuration
Configuring arvversion.h using configuration
Program g-ir-scanner found: YES (/usr/bin/g-ir-scanner)
Run-time dependency gobject-introspection-1.0 found: YES 1.72.0
Dependency gobject-introspection-1.0 found: YES 1.72.0 (cached)
Dependency gobject-introspection-1.0 found: YES 1.72.0 (cached)
Program g-ir-scanner found: YES (/usr/bin/g-ir-scanner)
Dependency gobject-introspection-1.0 found: YES 1.72.0 (cached)
Program g-ir-compiler found: YES (/usr/bin/g-ir-compiler)
Program python3 found: YES (/usr/bin/python3)
WARNING: Python files installed by Meson might not be found by python interpreter.
 This warning can be avoided by setting "python.platlibdir" option.
WARNING: Python files installed by Meson might not be found by python interpreter.
 This warning can be avoided by setting "python.purelibdir" option.
Configuring pylaunch using configuration
Configuring pylaunch-dbg using configuration
Configuring jslaunch using configuration
Configuring jslaunch-dbg using configuration
Run-time dependency gtk+-3.0 found: YES 3.24.33
Run-time dependency gstreamer-base-1.0 found: YES 1.20.3
Run-time dependency gstreamer-app-1.0 found: YES 1.20.1
Run-time dependency gstreamer-video-1.0 found: YES 1.20.1
Run-time dependency libnotify found: YES 0.7.9
Program glib-compile-resources found: YES (/usr/bin/glib-compile-resources)
Configuring arv-viewer-0.8.appdata.xml using configuration
Configuring arv-viewer.desktop.in using configuration

viewer/data/meson.build:11:0: ERROR: Function does not take positional arguments.

A full log can be found at /usr/local/aravis/build/meson-logs/meson-log.txt

**Comment by gregsskyles** [comment]
1. The error messsage directs you to line 11 of viewer/data/meson.build - what is that line? Or for that matter, can you share the entire meson.build file?
2. Version 0.61.2 of Meson is quite old; can you retry with a more modern verison? 1.3.2 is the current release. My guess, without the above information, is that your meson.build is written for a newer version of Meson.
3. The full log as mentioned at the end could be useful to see.
