### ISSUE TITLE
Wildcards and Notification-based Dependency Tracking

### ISSUE THREAD

**Issue by nordlow** [mesonbuild/meson#1293]
If Meson were to add support for notification-based dependency management like [Tup ](http://gittup.org/tup/) does on Linux, the restriction on wildcards

https://github.com/mesonbuild/meson/wiki/FAQ#why-cant-i-specify-target-files-with-a-wildcard

could be lifted for that case.

Are there any plans on adding such support?

**Comment by jpakkane** [comment]
No. Supporting something like inotify is a lot of work. Adding that would require that someone provide measurements that it works noticeably faster than Ninja. Thus far no-one has.

And this still does not change the fact that other backends could not use inotify so the wildcard limitation would need to remain.

**Comment by nordlow** [comment]
Ok, thanks anyway.
