### ISSUE TITLE
need --dry-run for compile

### ISSUE THREAD

**Issue by duanev** [mesonbuild/meson#12930]
meson needs to tell us a lot more about what it _will_ do.  Perhaps this is already present in introspect?  If so I can't get it to run:

$ meson introspect
Please specify a valid build dir ... (why? should work without one)

$ meson setup /tmp/foobar
(some error)
$ meson introspect /tmp/foobar
No command specified                  (???)

$ meson introspect --backend none /tmp/foobar
meson introspect: error: argument --backend: invalid choice: 'none'
                     (so https://mesonbuild.com/Commands.html is wrong)

$ meson ???

**Comment by eli-schwartz** [comment]
> meson needs to tell us a lot more about what it _will_ do. Perhaps this is already present in introspect? If so I can't get it to run:
> 
> $ meson introspect
> Please specify a valid build dir ... (why? should work without one)

It's impossible to work without one, since introspection provides information about configured builds which cannot be gotten from the source directory without fully evaluating the source directory.

> $ meson setup /tmp/foobar
> (some error)
> $ meson introspect /tmp/foobar
> No command specified (???)

- What was the error?
- "introspect" expects you to ask for introspection about something specific, such as "--ast" or "--buildoptions" or "--targets" etc.


> $ meson introspect --backend none /tmp/foobar
> meson introspect: error: argument --backend: invalid choice: 'none'
> (so https://mesonbuild.com/Commands.html is wrong)

I cannot reproduce this.

> $ meson ???

ninja -n, maybe?

```
$ ninja -h
[...]
  -n       dry run (don't run commands but act like they succeeded)
```

**Comment by duanev** [comment]
I see, so introspect is not what I'm looking for, maybe `ninja -n -v`, thanks.  And it makes sense that the setup must succeed before ninja will run.  The error was 'Unknown variable'; basically a broken subproject meson.build file with a faux 'project' statement ... (very much wish subprojects could standalone instead of 'first statement must be a call to project()').

Just trying to snip a bit of an open source repo, but the more layers of build system, the more opaque what is actually going to run.  :/
