### ISSUE TITLE
Conserve Valac coloration?

### ISSUE THREAD

**Issue by bagage** [mesonbuild/meson#1294]
As of today, `meson` loses `valac` coloration when building vala files. For instance in `test cases/vala/1 basic`, meson output will look like:
![capture d ecran de 2017-01-09 17-14-41](https://cloud.githubusercontent.com/assets/1451988/21773737/73404d82-d690-11e6-8c17-26bdfe36e3ca.png)
While using valac directly, it looks like:
![capture d ecran de 2017-01-09 17-14-52](https://cloud.githubusercontent.com/assets/1451988/21773740/78001244-d690-11e6-9480-21c80f136e97.png)
This happens because of how `meson` is piping `stderr` for `valac`, eg this issue can be easily reproduced using the simple `test.py` file below:

```
import subprocess
p = subprocess.Popen("/usr/bin/valac prog.vala".split(" "), stdout=subprocess.PIPE, stderr=subprocess.PIPE)
o, e = p.communicate(None)
print(o)
print(e)
```

Removing `stderr=subprocess.PIPE` makes `valac` errors colored obviously.

I don't know if any solution exist for such issue (except of reimplementing a valac logs colorer within meson…), but it would ease vala development a lot!

(ps: this is not specific to Vala, but any precompiler actually)

**Comment by ignatenkobrain** [comment]
GCC has flag to enforce colors. Vala doesn't, so we should implement it in Vala first.

**Comment by jpakkane** [comment]
Meson is not invoking the compiler, Ninja is. This needs to be fixed either by having Ninja not buffer compiler output (which is not a good idea because that leads to Make's intermixing of different compiler invocations) or adding a flag to valac to force output colorization. We can't really do anything about this.
