### ISSUE TITLE
ERROR: New value 20 is more than maximum value 6.

### ISSUE THREAD

**Issue by Aritra-BITS** [mesonbuild/meson#12946]
Firstly I am very new to this, I an trying to build PLDM from https://github.com/openbmc/pldm/, in my system. But I am getting the error

`ERROR: New value 20 is more than maximum value 6.`

I am using yocto bitbake recipes to build. What could be the issue?

**Comment by QuLogic** [comment]
There is no such string in Meson; it seems like a PLDM issue.

**Comment by dcbaker** [comment]
That error is from an integer option with a maximum value. I swear we had updated that to have the name in the option

**Comment by QuLogic** [comment]
Oh, I found it; don't know why GitHub's search is useless
https://github.com/mesonbuild/meson/blob/0cd74c96f1b58fe89ef9565ab40905d04538d7ed/mesonbuild/coredata.py#L196
No mention of the name yet unfortunately.

**Comment by bruchar1** [comment]
I guess that this PR could help for that case: #12728

**Comment by Aritra-BITS** [comment]
Okay that helped all i had to do was change the value [here](https://github.com/openbmc/pldm/blob/71c01e9bdee2fd656071c7e04a5a1bfbef3954b6/meson.options#L115C5-L115C8)
