### ISSUE TITLE
cannot use precompiled headers in static libraries when using clang-cl

### ISSUE THREAD

**Issue by apache-hb** [mesonbuild/meson#12954]
**Describe the bug**
When using precompiled headers, clang-cl, and llvm-ar. builds fail with the error `llvm-ar.exe: error: unable to load '..\pch/stdafx.obj': file too small to be an archive`

**To Reproduce**
```py
# meson.build
project('temp', 'cpp',
  version : '0.1',
  default_options : [
    'warning_level=3',
    'cpp_std=c++latest',
  ]
)

cpp = meson.get_compiler('cpp')

static_library('example', 'main.cpp',
  include_directories : ['pch'],
  cpp_pch : ['pch/stdafx.hpp', 'pch/stdafx.cpp']
)
```
clang-cl.ini
```ini
[binaries]
c = 'clang-cl'
cpp = 'clang-cl'
ar = 'llvm-ar'
ld = 'lld-link'
strip = 'llvm-strip'

[constants]
common_args = [ '-fcolor-diagnostics' ]

[built-in options]
c_args = common_args
cpp_args = common_args
c_ld_args = common_args
cpp_ld_args = common_args
```
```cpp
// main.cpp
#include "stdafx.hpp"

int do_thing() {
    std::cout << "Hello, World!" << std::endl;
}
```
```cpp
// pch/stdafx.hpp
#pragma once

#include <iostream>
#include <string>
#include <vector>
#include <map>
#include <set>
```
```cpp
// pch/stdafx.cpp
#include "stdafx.hpp"
```
`meson setup build --native-file clang-cl.ini`
`ninja -C build`

**Expected behavior**
The build is successful

**system parameters**
* Windows 11 build 22621
* meson 1.3.2
* ninja 1.11.1
* python 3.11.8
* clang-cl 19.0.0git
* llvm-ar 19.0.0git

**Comment by dcbaker** [comment]
Your main.cpp looks off. That should be:
```cpp
#include <string>
#include <iostream>

int do_thing() {
    std::cout << "Hello, World!" << std::endl;
}
```
Does that fix the compilcation errors?

Also noe that modern versions of Meson don't need the precompiled .cpp file, it will generate one automatically if it's needed

**Comment by apache-hb** [comment]
neither removing the `stdafx.hpp` include, nor removing `stdafx.cpp` and using the autogenerated one fixed the issue. this appears to be because llvm-ar only accepts .a archives, and meson attempts to give it the pch .obj file without putting it into an archive first.

**Comment by apache-hb** [comment]
Tested locally and meson shouldn't be giving the .obj file to lld-link for the final link, will see if i can put a patch together
