### ISSUE TITLE
Meson vs SCons

### ISSUE THREAD

**Issue by nordlow** [mesonbuild/meson#1296]
What are the pros (and cons if any) to using Meson compared to SCons?

Specifically benchmarks on incremental compilation performance?

**Comment by ignatenkobrain** [comment]
Given that SCons is slower than CMake... And CMake is slower than Meson...

**Comment by jpakkane** [comment]
[We have a page with comparison information](https://github.com/mesonbuild/meson/wiki/Comparisons). It has links to measurements.

**Comment by nordlow** [comment]
Thanks.

**Comment by nordlow** [comment]
I'm missing a comparison with Google Bazel.

**Comment by jpakkane** [comment]
I have not used it much but updated the page with what I know.

**Comment by abitrolly** [comment]
Pages moved.

* Pros/Cons - https://mesonbuild.com/Comparisons.html#scons
* https://mesonbuild.com/Simple-comparison.html
* https://mesonbuild.com/ARM-performance-test.html

**Comment by anohren** [comment]
> We have a page with comparison information

Would it be inappropriate to mention that SCons is 80% cons?

**Comment by abitrolly** [comment]
@anohren would be appropriate to give side by side syntax comparison.
