### ISSUE TITLE
1.4.0 - MSI release asset for Windows?

### ISSUE THREAD

**Issue by gregsskyles** [mesonbuild/meson#12966]
Hope I'm not just being blind, but I don't see the MSI file in the release assets for 1.4.0. Is it a manual step that gets missed?

**Comment by jpakkane** [comment]
It is being delayed by [https://github.com/orgs/wixtoolset/discussions/6516](this issue in WiX).

**Comment by jpakkane** [comment]
Added now.

**Comment by gregsskyles** [comment]
Thanks!

**Comment by gregsskyles** [comment]
OK, now seeing the same issue for 1.5.0...
