### ISSUE TITLE
Fails to find LLVM-18 and { LLVM-17 in c-only project }

### ISSUE THREAD

**Issue by MehdiChinoune** [mesonbuild/meson#12961]
**Describe the bug**
meson Fails to find LLVM-18.
```
WARNING: The LLVM dependency was not found via CMake since both a C and C++ compiler are required.
llvm-config found: YES (D:\Programs\msys64_test\clang64\bin/llvm-config.EXE) 18.1.0
Run-time dependency LLVM found: NO (tried cmake)

meson.build:5:11: ERROR: Dependency "llvm" not found, tried cmake

A full log can be found at D:/dev/Bugs/cmake_code/build/clang/meson-logs/meson-log.txt
```
The project is cpp only!

It also fails to find llvm-17 with c-only project
```
WARNING: The LLVM dependency was not found via CMake since both a C and C++ compiler are required.
Run-time dependency LLVM found: NO (tried cmake)

meson.build:5:11: ERROR: Dependency "llvm" not found, tried cmake

A full log can be found at D:/dev/Bugs/cmake_code/build/clang-17/meson-logs/meson-log.txt
```

**To Reproduce**
- Install llvm-18
- run meson
```meson

project('simple', 'cpp')
executable('test_exe', 'main.cpp')

dep_llvm = dependency(
    'llvm',
    method : 'auto',
    version : '>= 17',
    modules : ['core'],
    required : true,
  )
```
- Install LLVM-7
- run meson
```meson

project('simple', 'c')
executable('test_exe', 'main.c')

dep_llvm = dependency(
    'llvm',
    method : 'auto',
    version : '>= 17',
    modules : ['core'],
    required : true,
  )
```

**Expected behavior**
To find llvm

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
native
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
Windows 10 MSYS2/MinGW-w64
* what Python version are you using e.g. 3.8.0
3.11.8
* what `meson --version`
1.3.2
* what `ninja --version` if it's a Ninja build
1.11.1

**Comment by dcbaker** [comment]
I think that error message is misleading, I think what it actually means is "I need a C and a C++ compiler use CMake to find LLVM", even though it looks like it's saying "I can't use CMake to find LLVM because you have both C and C++"

**Comment by thesamesam** [comment]
Is your Clang binary called `clang-18.1`?
