### ISSUE TITLE
wayland module doesn't allow version number for stable protocols

### ISSUE THREAD

**Issue by bilelmoussaoui** [mesonbuild/meson#12968]
**Describe the bug**

When trying to port Mutter to use the wayland module, it seems you can't specify a version for a stable protocol and would fail with "The file doesn't exists"

For example, the linux-dmabuf protocol is versioned despite being stable. e.g 
`/usr/share/wayland-protocols/stable/linux-dmabuf/linux-dmabuf-v1.xml`

**To Reproduce**
Please include your `meson.build` files, preferably as a minimal toy example showing the issue.
You may need to create simple source code files (don't include private/proprietary code).

```
wl_mod = import('unstable-wayland')

wl_mod.find_protocol(
  'linux-dmabuf',
  state: 'stable'
  version: '1'
)
```

**Expected behavior**

The above should work out of the box otherwise one can't use the wayland module.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? native build
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) Fedora rawhide 
* what Python version are you using: 3.12.2
* what `meson --version`  1.3.2
* what `ninja --version` if it's a Ninja build 1.11.1

**Comment by xclaesse** [comment]
@bilelmoussaoui can you give a try to https://github.com/mesonbuild/meson/pull/12969 please?
