### ISSUE TITLE
meson doesn't find libarchive on macOS

### ISSUE THREAD

**Issue by hughsie** [mesonbuild/meson#12980]
**Describe the bug**

	% brew info libarchive
	[...]
	==> Caveats
	libarchive is keg-only, which means it was not symlinked into /opt/homebrew,
	because macOS already provides this software and installing another version in
	parallel can cause all kinds of trouble.

	If you need to have libarchive first in your PATH, run:
	  echo 'export PATH="/opt/homebrew/opt/libarchive/bin:$PATH"' >> ~/.zshrc

	For compilers to find libarchive you may need to set:
	  export LDFLAGS="-L/opt/homebrew/opt/libarchive/lib"
	  export CPPFLAGS="-I/opt/homebrew/opt/libarchive/include"

	For pkg-config to find libarchive you may need to set:
	  export PKG_CONFIG_PATH="/opt/homebrew/opt/libarchive/lib/pkgconfig"

**To Reproduce**

    # install macOS
    # brew install libarchive
    libarchive = dependency('libarchive')

**Expected behavior**

I'm guessing meson needs to special-case using pkgconfig with libarchive on macOS. I didn't see any way to pass in a hardcoded PKG_CONFIG_PATH for just that one `dependency()` and it feels like a hack to do that.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?

No.

* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)

MacOS Sonoma 14.4

* what Python version are you using e.g. 3.8.0

3.12.0

* what `meson --version`

1.4.0

* what `ninja --version` if it's a Ninja build

1.11.1

Thanks!

**Comment by eli-schwartz** [comment]
> I'm guessing meson needs to special-case using pkgconfig with libarchive on macOS. I didn't see any way to pass in a hardcoded PKG_CONFIG_PATH for just that one `dependency()` and it feels like a hack to do that.

There is nothing hacky about exporting PKG_CONFIG_PATH with an additive list of additional locations to search for software. It's how pkg-config was designed to work in the first place.

The homebrew keg is, by design, only providing that one package, so by doing so you won't even end up adding "too many packages" and detecting something other than libarchive from there.

**Comment by hughsie** [comment]
> There is nothing hacky about exporting PKG_CONFIG_PATH with an additive list of additional locations to search for software

So I have to set PKG_CONFIG_PATH before calling meson? Or use `-Dpkg_config_path=/opt/homebrew/opt/libarchive/lib/pkgconfig` -- I mean -- the latter works, but it seems weird to call `meson setup -D/opt/homebrew/opt/libarchive/lib/pkgconfig` on macOS and `meson setup` on all the other platforms.  Is there a way to set the list of *extra* `pkg_config_path`s in the `meson.build` file? That's going to be much easier to use.

**Comment by eli-schwartz** [comment]
You can set it in a machine file e.g. `meson setup builddir/ --native-file=profiles/macos.ini`.

Homebrew is apparently suggesting you put it in your shell config file...
