### ISSUE TITLE
meson dist is confused

### ISSUE THREAD

**Issue by matthiasclasen** [mesonbuild/meson#12985]
**Describe the bug**
meson dist refuses to operate, claiming that the repository contains uncommitted changes, when that is not the case.

**To Reproduce**

```
$ meson dist -C release_build/
ERROR: Repository has uncommitted changes that will not be included in the dist tarball
Use --allow-dirty to ignore the warning and proceed anyway
$ git diff
$ 
```

**Expected behavior**

meson dist should work. 

If there is actually something 'dirty' about my checkout, then meson should not be so tight-lipped and tell me what it is.

**system parameters**

This is meson 1.3.2 on Fedora 40

**Comment by eli-schwartz** [comment]
```python
def have_dirty_index(self) -> bool:
    '''Check whether there are uncommitted changes in git'''
    ret = subprocess.call(['git', '-C', self.src_root, 'diff-index', '--quiet', 'HEAD'])
    return ret == 1
```

I don't think this is being particularly tight-lipped. I actually have no clue what the difference is, and we didn't expect there to be one, so it didn't seem like something that needed to be reported...

**Comment by eli-schwartz** [comment]
What's the output of `git status`? Do you have staged-but-not-committed changes?

**Comment by bgilbert** [comment]
This can be reproduced by `touch`ing a tracked file in the repo before running `meson dist`.  Unlike `git status` and `git diff`, `git diff-index` doesn't refresh the index before comparing, so stat changes are assumed to imply content changes.  I'm currently working around this in some automation by manually updating the index with `git update-index -q --refresh` before running `meson dist`.

**Comment by tristan957** [comment]
@bgilbert have time to submit a patch?

**Comment by bgilbert** [comment]
Sure, PR in https://github.com/mesonbuild/meson/pull/13152.
