### ISSUE TITLE
Return value of get_option('xxxdir') is inconsistent

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#1299]
Since we started allowing passing absolute paths to `xxxdir` such as `--libdir`, it is difficult to know whether `get_option('libdir')` will return the full path to `libdir` or just the path relative to `prefix`.

Normally this is not a problem because people will use `join_paths([get_option('prefix'), get_option('libdir')])` which will do the right thing when `get_option('libdir')` returns an absolute path. However, there are use-cases where people want to just fetch the value of `libdir` relative to `prefix`.

For instance, Gentoo's init system OpenRC installs libraries in `/usr/lib64` and some of its binaries and scripts (which are not accessible to the user) into `/lib64/rc/bin`, `/lib64/rc/sbin`, `/lib64/rc/sbin`, etc. Gentoo does not use a unified `/usr`, so `/usr/lib64` is not the same as `/lib64`. I can imagine that lots of other 'system-level' projects for distros that don't have a unified `/usr` will face this issue.

There are examples in GStreamer as well besides "non-unified /usr"; just search for `grep --include=meson.build -re 'get_option.*libdir'` inside [gst-build](https://cgit.freedesktop.org/gstreamer/gst-build/) with the subprojects cloned. Perhaps many of those can be 'fixed' or changed, but people will keep writing build files with these issues.

I propose that if `xxxdir` is an absolute path and a subdir of `prefix`, `get_option('xxxdir')` should return the path **relative to `prefix`**. If it is not, only then must it return the absolute path.

**Comment by nirbheek** [comment]
Related: #1081

**Comment by jpakkane** [comment]
This is a bit abstract and the real issue is hard to decipher. Could you write a single file example describing:

 - where a file should be installed
 - how people would write the install today
 - how it goes wrong
 - what should happen instead
 - how does the proposed change fix this

Thanks,

**Comment by nirbheek** [comment]
I don't understand the confusion, but I'll try to rephrase the issue and maybe that will help.

For simplicity, I will give the specific example of `libdir`, but this applies to almost all `xxxdir` options.

Let's say the default value of `libdir` if unspecified is `lib64`. You can override it in three ways:

1. `meson --libdir=lib32`
2. `project(..., default_options : ['libdir=lib32'])`
3. `mesonconf -Dlibdir=lib32`

Regardless of how you set it, inside a build file, `get_option('libdir')` will return `lib32`, and it is your job to do a `join_paths()` with `get_option('prefix')` to get the full path.

However, now we allow setting `libdir` to absolute paths as well. This means that if you do `meson --libdir=/usr/lib32` (or set it via either (2) or (3) from above), in a build file `get_option('libdir')` will return `/usr/lib32` which includes the `prefix`. **This is the inconsistency.**

This hasn't broken much yet because only rpm-based distros seem to be passing absolute paths, and most projects want the full path to the libdir in the build files anyway and do `join_paths([prefix, libdir])` which is going to see that `libdir` is an absolute path and just return that directly.

However, the semantics of `libdir` in Meson is that it is relative to the `prefix`, so people will always expect `get_option('libdir')` to return a relative path, and in many cases it breaks things to return an absolute path there. For example:

1. Setting the `libdir` variable in pkg-config files:

```
pkgconf.set('libdir', '${prefix}/@0@'.format(get_option('libdir')))
```

2. The OpenRC example I gave above

And in general this is crappy API design because the format of the return value depends on user configuration. To be absolutely sure that they will get a relative path for `libdir`, people will have to do something like the following in their build files:

```
libdir = get_option('libdir')
prefix = get_option('prefix')
# Extract the libdir path relative to the prefix
if libdir.startswith('/')
  prefix_paths = prefix.split('/')
  libdir_paths = libdir.split('/')
  ii = 0
  found = false
  foreach p : prefix_paths
    if p == libdir_paths.get(ii)
      ii += 1
    endif
  endforeach
  libdirs = []
  jj = 0
  foreach p : libdir_paths
    if jj >= ii
      libdirs += [libdir_paths.get(jj)]
    endif
    jj += 1
  endforeach
  libdir = '/'.join(libdirs)
endif
```

I wrote that piece of code to demonstrate how crappy it is to do simple string and array manipulation in build files, and that we should not expect users to ever do that. We must give definite guarantees with our API.

Hence, we must always return relative paths in `get_option('xxxdir')`. #1308 implements this by requiring that if you set the an `xxxdir` option to an absolute path, that path must be a subdir of `prefix`. Once that requirement is in place, it is easy to transform an absolute path set by any of the three methods listed above to a path relative to `prefix. That's also what #1308 does.

Hope that makes it clear. We should fix this soon or it will be impossible to fix later.
