### ISSUE TITLE
Found python for x86-64 rather than for x86 on Windows

### ISSUE THREAD

**Issue by doadin** [mesonbuild/meson#13008]
using github actions + actions/setup-python@v4 with: update-environment: true

I am using https://github.com/wingtk/gvsbuild to build https://github.com/pygobject/pycairo/blob/main/meson.build which has 

```meson
pymod = import('python')
python = pymod.find_installation(get_option('python'), pure: false)
```

in the build error I get:
 "Need python for x86, but found x86_64"

if I delete all other python folder from the action runner in a step before the build process I get:
 Program python3 found: NO
meson.build:16:15: ERROR: python3 not found

full action log can be found here:
first error
https://github.com/doadin/gvsbuild-release/actions/runs/8443809356/job/23128136908
second error
https://github.com/doadin/gvsbuild-release/actions/runs/8446242953/job/23134712079

in the log for the first error you can see in the trace that x86 python is what is executing the command yet meson says "Need python for x86, but found x86_64". This seems to be a meson issue? however im not familiar with meson build system if this is a build file issue sorry.

**Comment by doadin** [comment]
https://github.com/doadin/gvsbuild-release/actions/runs/8461761735/workflow

it seems to find x64 python just fine, however does not find x86 for some reason.

**Comment by rgommers** [comment]
There's a lot more discussion on https://github.com/mesonbuild/meson-python/issues/610 about this (@doadin if you open a second issue, please cross-link to or close the first one).

**Comment by rgommers** [comment]
Could you update the title to something like: _Found `python` for x86-64 rather than for x86 on Windows_?

**Comment by doadin** [comment]
@rgommers sure.

**Comment by doadin** [comment]
@rgommers also, im not sure how much I can help, but I will add, I was able to work around this issue. The programs I was having issues compileing have a "messon option" to specify a python exe which gets passed to find_installation via get_option. And what is done in gvsbuild I add 

```
py_dir = Path(sys.executable).parent
Meson.build(self, meson_params=f'-Dpython="{py_dir}\\python.exe"')
```

And it just uses that to setup the params when meson is called to build that project.

Which I thought that essentially the same thing was, at least supposed to? happen https://github.com/mesonbuild/meson/blob/2d010c693b97694a82458ba89d4da569e21c60aa/mesonbuild/modules/python.py#L504C41-L504C53

I don't really know what the solution here is, again I was able to work around it because the program I was working with happen to have that param setup in messon.build, had it not though would have been stuck. So I don't know if something like Path(sys.executable).parent could be used as a failover or something. I hafve no clue, I would think a simple 

python = Path(sys.executable).parent\python.exe or arg1 
type of think would be enough to cover all needs for find_installation, but obviously its way more complicated, thats why im not sure I could really help.

**Comment by rgommers** [comment]
Thanks @doadin. I think your expectation of what is supposed to happen is reasonable, but unfortunately that is not how it works. `find_installation` isn't very tightly coupled to the Python installation that `meson` itself is installed in (primarily because nothing in Meson by design is Python-specific). Meson is going to prefer trying to find a 64-bit Python install on 64-bit Windows first, even if the `meson` Python package is installed in a 32-bit Python env.

`meson-python` handles this automatically, telling `meson` to prefer the `python` for which `meson-python` itself is installed via a native file. Which in a way is the same as what you're doing here, using a build option.

I think the design won't change, but the error message can be made more informative and the docs should cover this situation.

**Comment by doadin** [comment]
> Thanks @doadin. I think your expectation of what is supposed to happen is reasonable, but unfortunately that is not how it works. `find_installation` isn't very tightly coupled to the Python installation that `meson` itself is installed in (primarily because nothing in Meson by design is Python-specific). Meson is going to prefer trying to find a 64-bit Python install on 64-bit Windows first, even if the `meson` Python package is installed in a 32-bit Python env.
> 
> `meson-python` handles this automatically, telling `meson` to prefer the `python` for which `meson-python` itself is installed via a native file. Which in a way is the same as what you're doing here, using a build option.
> 
> I think the design won't change, but the error message can be made more informative and the docs should cover this situation.

I get that meson is not specific to python and its more they are just made in a way to work to gether I guess(idk if thats any better description or w.e.), however again me really not knowing the inner working of meson. It just seems backwards to me that meson would potentially asume something that is not true(as a default). I would think one of a few things should be a priority

1. The user wants to use the python that is currently running the meson python script(this does not necisarily mean where meson/python was installed), simply the exe that is running the script. If its running the script then its likely the user set their env up so that would be the case. (I would think there would be few reasons to use one python to call a build that then calls another python, that just seems a bit backwards to me again, what do I know though, not sarcasm)
2. The user wants to use the python setup via for example %PATH% on windows. 

#2 I think in a lot of cases it is likely the same as #1. And if I setup a python on my path I would think its reasonble to think that any use of python would use what I set on %PATH% (fairly certain that how most applications work, at least on windows).

Again I have no clue of the inner workings or anything and certainly don't speak for anyone but my self but I would think instead of assuming the python versions a priority like the following might be a good idea.

1. If the user set an option use that.(if an arg was supplied to find_installation)
2. check what python is currently running the script that looks for python.(I would think this would be the correct versions again because of the whole I put it on my path whats on my path is what gets used etc etc.)
3. if 1 or 2 did not work look for at least what version of python was used (3.8, 3.9, 3.12)(and maybe could still match the windows version bitness)
4. then maybe look for installs in the registry(for windows obviosuly) and look for one that maybe the meson.build specified eg. if it says look for python 3 look for 3 not 2, but match any minor version found.(and verify what is found in the registry actually exists)

And again maybe I have no clue what I am talking about I leave it to you guys to do what you think its best your the devs not me, just some thoughts as an amature, with very little coding knoledge.
