### ISSUE TITLE
compiler.has_argument() does not support gcc -Wno-attributes=

### ISSUE THREAD

**Issue by Jannik2099** [mesonbuild/meson#13022]
Meson expands a `-Wno-foo` test into `-Wfoo -Wno-foo` due to gcc behaviour, see https://github.com/mesonbuild/meson/blob/master/mesonbuild/compilers/mixins/clike.py#L1255

However, it turns out this breaks gccs `-Wno-attributes=foo` https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wno-attributes

```meson
project('attribute-test', 'cpp')
cpp = meson.get_compiler('cpp')
if cpp.get_id() == 'gcc'
    assert(cpp.has_argument('-Wno-attributes=foo'))
endif
```

yields the following gcc invocation:
`g++ /home/jannik/temp/argtest/build/meson-private/tmpwllkb_fp/testfile.cpp -o /home/jannik/temp/argtest/build/meson-private/tmpwllkb_fp/output.obj -c -D_FILE_OFFSET_BITS=64 -O0 -fpermissive -Wattributes=foo -Wno-attributes=foo`
and the following error
`cc1plus: error: arguments ignored for '-Wattributes='; use '-Wno-attributes=' instead`

Maybe just hardcode around it? I can't recall any other gcc argument with this behaviour.

Meson version 1.3.2

**Comment by thesamesam** [comment]
It looks like indeed `-Wattributes` is a special-case here from grepping gcc.
