### ISSUE TITLE
Unity builds should allow excluding files from units

### ISSUE THREAD

**Issue by ptomato** [mesonbuild/meson#13031]
In the documentation for [unity builds](https://mesonbuild.com/Unity-builds.html), it says

> There may also be some bugs in the source that need to be fixed before Unity compiles work.

This is not always possible when the source that needs to be fixed is generated by Meson.

The specific bug I'm dealing with, as far as I've tracked down an explanation: I have `#define _GNU_SOURCE 1` in my `config.h` file, which in glibc causes a whole bunch of other macros to be defined, which expose certain features in glibc header files. I include `config.h` everywhere in my sources. I also use `gnome.compile_resources()` which generates a `resource.c` file that does not include `config.h`. In a unity build, my generated `resource.c` is included first, and `resource.c` includes some other header file that includes `<locale.h>`. Several symbols are [skipped in `<locale.h>` unless `__USE_XOPEN2K8` is defined](https://codebrowser.dev/glibc/glibc/locale/locale.h.html#128), which is one of the macros enabled by `_GNU_SOURCE`, and so these types are permanently not available in files that come after `resource.c` in the smushed unity file, because `<locale.h>` can only be included once.

If the offending file wasn't generated, I'd easily be able to fix this.

I can think of a few possible solutions, but allowing the exclusion of certain files, or generated files only, from compilation units, seems like the most useful one to me.

**Comment by eli-schwartz** [comment]
The simplest way to do this is to compile your resource.c inside of a dedicated target:
```meson
res = gnome.compile_resources(...)
res_lib = static_library('unityproof-resources', res, override_options: ['unity=off'])
mainprog = executable('myprog', 'foo.c', link_with: res_lib)
```

**Comment by ptomato** [comment]
That'll work as a workaround for now, I guess! Thanks.

Is there any chance Meson would gain a more straightforward way to do this? I hadn't heard of the `override_options` argument before and probably would never have thought of this.

**Comment by eli-schwartz** [comment]
I don't know. I'm not sure what a more straightforward way would look like -- perhaps mainly because I do not often think about unity builds. :)

**Comment by ptomato** [comment]
Yeah, maybe there isn't a more straightforward way. Maybe a paragraph in the [cookbook](https://mesonbuild.com/howtox.html)?

**Comment by eli-schwartz** [comment]
Sounds like an excellent idea. Can you submit a patch to the docs?

**Comment by ptomato** [comment]
Added a howto section in #13076.
