### ISSUE TITLE
Feature request: initialize env object from another env

### ISSUE THREAD

**Issue by Jehan** [mesonbuild/meson#13045]
**Feature description**

It would be useful to have the ability to an `env` object initialized as the copy of another `env` object.
Typically I could imagine that [`environment()`](https://mesonbuild.com/Reference-manual_functions.html#environment) could take another `env` object as argument for initialization:

```
env2 = environment(env1)
```

This way, we could create slightly different environments from a similar base. This is a use case I encountered today and which would be useful.

**Comment by xclaesse** [comment]
I believe that's what `env2=env1` does.

**Comment by Jehan** [comment]
Oh ok! So `env2` doesn't point to the same env object, it makes a copy?

**Comment by xclaesse** [comment]
The doc is completely missing for this behaviour and it is inconsistent with how configuration_data() works. Made a PR to fix that: https://github.com/mesonbuild/meson/pull/13047.

> Oh ok! So `env2` doesn't point to the same env object, it makes a copy?

Assignment does a deepcopy, yes. https://github.com/mesonbuild/meson/blob/master/mesonbuild/interpreterbase/interpreterbase.py#L635
