### ISSUE TITLE
Was this documentation deleted by mistake?

### ISSUE THREAD

**Issue by doraskayo** [mesonbuild/meson#1305]
I was using the [Reference manual](https://github.com/mesonbuild/meson/wiki/Reference-manual) wiki page for development, and when I refreshed the page quite a few important lines disappeared. It appears they were deleted by mistake. See [this](https://github.com/mesonbuild/meson/wiki/Reference-manual/_compare/772ab6db7a382caade2ccefe15c831cfecdb58b0...47e3c971d45602c13212cfdb1ebc7f06fb8a7228) revision comparison.

If it wasn't intentional, it would be nice to get it fixed. Thanks!

@nirbheek

**Comment by jpakkane** [comment]
Reverted. Thanks for the report.

**Comment by nirbheek** [comment]
Whoa, no idea how that happened! Sorry and thanks for reporting and fixing :)
