### ISSUE TITLE
How to uninstall it？

### ISSUE THREAD

**Issue by Pathsis** [mesonbuild/meson#13069]
Hello, I installed meson using

```shell 
meson setup build sudo meson install -C build 
``` 
to install it, so how do I **UNINSTALL** it?

**Comment by dreamer-coding-555** [comment]
Did you try `python -m pip uninstall meson`?

**Comment by eli-schwartz** [comment]
> Hello, I installed meson using

That looks like you installed another project, using meson as the build system. ;)

You can uninstall using `ninja uninstall`.
