### ISSUE TITLE
Wrong detection of x86_64 in Windows 10

### ISSUE THREAD

**Issue by doraskayo** [mesonbuild/meson#1306]
Meson detects my 64-bit Windows 10 (build 1607) operating system as x86 instead of x86_64. When I run Meson from the "Developer Command Prompt for Visual Studio 2015", I get the following:
```
C:\Users\User\Desktop\project\build>meson.py .. --backend vs2015
The Meson build system
Version: 0.37.1
Source dir: C:\Users\User\Desktop\project
Build dir: C:\Users\User\Desktop\project\build
Build type: native build
Project name: project
Native cpp compiler: cl (msvc 19.00.24215.1)
Build machine cpu family: x86
Build machine cpu: x86
Build targets in project: 1
```
Running the following command in the same command prompt clearly states that my OS is 64-bit:
```
C:\Users\User\Desktop\project\build>wmic os get osarchitecture
OSArchitecture
64-bit
```
I currently don't have access to another Windows installation, so I can't tell if it's related to a specific configuration of my system or whether it's reproducible in other Windows environments. However, I'd be happy to run any test on this machine, just let me know.

**Comment by nirbheek** [comment]
This is not a bug, you're building with the 32-bit Visual Studio toolchain and SDK, which means your output binary will also be for x86 and will run on your 64-bit Windows via [WoW64](https://en.wikipedia.org/wiki/WoW64).

To build with the 64-bit toolchain, look for the x86_64/amd64 "Developer Command Prompt", or run `vcvarsall.bat` with `amd64` as the architecture.

**Comment by doraskayo** [comment]
You're right. I ran "VS2015 x64 Native Tools Command Prompt" instead, and it used the 64-bit toolchain as expected.

Thanks, and sorry for the trouble. Closing this issue...
