### ISSUE TITLE
Can't install a package due to FileNotFoundError causing problem in mesonbuild

### ISSUE THREAD

**Issue by pavelkomarov** [mesonbuild/meson#13068]
Here's a longer description of the issue. https://github.com/clawpack/clawpack/issues/249 I'm not sure whether this is a `ninja` problem (although they don't seem to think so: https://github.com/ninja-build/ninja/issues/2409), a `meson` problem, or a problem with how they're getting used by `clawpack`.

It appears there are some auto-generated files that aren't getting properly generated, resulting in `FileNotFoundError`s and a build failure. If anyone here has any further ideas, I'd appreciate it.

**Comment by eli-schwartz** [comment]
Please upload the full logs, e.g. as a text file attachment. No need to trim it in that case.

**Comment by pavelkomarov** [comment]
[error.txt](https://github.com/mesonbuild/meson/files/14939215/error.txt)

**Comment by eli-schwartz** [comment]
My analysis is that this is not a meson bug. I left a comment on the clawpack bug report instead -- let's discuss it there for now.
