### ISSUE TITLE
How to pass a configuration data or a dict to a subproject

### ISSUE THREAD

**Issue by ZZH-Finalize** [mesonbuild/meson#13077]
I'm using the `subproject()` function to add a library to my main project, but the subproject uses the "sourceset" module to control which source files should be compiled. So, how can I pass a dictionary to this subproject without directly referencing the variable in the subproject?

subproject meson.build:
![image](https://github.com/mesonbuild/meson/assets/33342565/bdb6f204-ea4c-4415-a113-8b165417ddf6)
![image](https://github.com/mesonbuild/meson/assets/33342565/11a390b1-ea3b-4535-9808-cbbc52f19f98)

**Comment by tristan957** [comment]
This is not possible
