### ISSUE TITLE
`project('tutorial', 'cpp')` works, but `add_languages('cpp')` fails with MSVC

### ISSUE THREAD

**Issue by 13lackade** [mesonbuild/meson#13085]
**Describe the bug**
When I use MSVC as C++ compiler, `project('tutorial', 'cpp')` works, but `add_languages('cpp')` fails with this output.
```
$ meson setup build
The Meson build system
Version: 1.4.99
Source dir: C:\Test
Build dir: C:\Test\build
Build type: native build
Project name: tutorial
Project version: undefined
Host machine cpu family: x86_64
Host machine cpu: x86_64

meson.build:3:0: ERROR: Compiler cl cannot compile programs.

A full log can be found at C:\Test\build\meson-logs\meson-log.txt
```
[meson-log.txt](https://github.com/mesonbuild/meson/files/14967828/meson-log.txt)
[meson-info.json](https://github.com/mesonbuild/meson/files/14967829/meson-info.json)

**To Reproduce**
1. This is the content of `meson.build`
```meson
project('tutorial')
add_languages('cpp')
executable('demo', 'main.cpp')
```

2. On `x64 Native Tools Command Prompt for VS 2022`, run `meson setup build`.

**Expected behavior**
Works as well as when I use `project('tutorial', 'cpp')`.

**system parameters**
* MSVC version : `Microsoft (R) C/C++ Optimizing Compiler Version 19.39.33523 for x64`
* Native build
* Operating system : Windows11 23H2
* `python --version` : `Python 3.13.0a2`
* `meson --version` : `1.4.99`
* `ninja --version` : `1.11.0`

**Comment by amcn** [comment]
I've been trying to reproduce this locally but I haven't been able to so far, which suggests to me the environment in which meson is running is playing a role in the behaviour that you have witnessed.

The only difference that I can see in the code between adding languages in `project` versus `add_languages` is that the order in which compilers are added is changed. In `project` it's [MachineChoice.HOST first](https://github.com/mesonbuild/meson/blob/f83dca32fe340727ada08b46d70bfc6dbba52d84/mesonbuild/interpreter/interpreter.py#L1320-L1321), whereas in `add_languages` it's [MachineChoice.BUILD first](https://github.com/mesonbuild/meson/blob/f83dca32fe340727ada08b46d70bfc6dbba52d84/mesonbuild/interpreter/interpreter.py#L1348-L1349).

It's not clear to me why this order should be switched. Could any Meson maintainers advise?

**Comment by 13lackade** [comment]
Sorry, I found out that my antivirus software was causing the problem. Closing.

**Comment by amcn** [comment]
Thanks for the update, I'm glad you were able to find a solution.

Searching for antivirus on GitHub Issues has brought #7486 to my attention in which @scivision noted that they had encountered a similar sounding problem and in which they suggest a potential solution in meson that could be attempted.
