### ISSUE TITLE
Support for other archive compression formats (bz2, zstd) in `meson dist`

### ISSUE THREAD

**Issue by kelnos** [mesonbuild/meson#13088]
The xz format [is unsafe, brittle, and needlessly complex, and is not suitable for long-term archving](https://www.nongnu.org/lzip/xz_inadequate.html).  I see that meson supports gz as well.  gz is a nice "everything in the world will support this" format to fall back on, but compression-wise it's not great compared to better, modern alternatives.  I think zstd would be the most forward-looking, but bz2 would also be an improvement over gz, while still being supported by _nearly_ everything in the world.

[We](https://xfce.org/) currently use bz2, but would like to use something with better compression.  xz does offer better compression, but with other significant downsides.  gz would be a step back for us.  We're a volunteer project with many of our resources donated, so we try to keep hosting/bandwidth costs down when possible.  Certainly we can uncompress whichever format `meson dist` and re-compress, but would rather not have to add post-processing to our builds where possible.

**Comment by eli-schwartz** [comment]
> The xz format [is unsafe, brittle, and needlessly complex, and is not suitable for long-term archving](https://www.nongnu.org/lzip/xz_inadequate.html). I see that meson supports gz as well. gz is a nice "everything in the world will support this" format to fall back on, but compression-wise it's not great compared to better, modern alternatives. I think zstd would be the most forward-looking, but bz2 would also be an improvement over gz, while still being supported by _nearly_ everything in the world.

The lzip page is a bad meme...

zstd is not an option because it is not available in the python stdlib. bzip2 is absolutely on the table, however.

I'm actually not sure why we don't already support it but probably whoever initially coded the mdist logic defaulted to assuming everyone would use xz if they wanted better than gzip. This isn't actually a reason to not support additional user choices such as bz2, when we can guarantee its availability and there are no downsides to the additional user choice.

If you want zstd you'll have to convince the CPython developers to add it to the stdlib. Meson is not going to depend on a third-party library.

**Comment by kelnos** [comment]
> The lzip page is a bad meme...

🤷🏻‍♂️ 

> zstd is not an option because it is not available in the python stdlib. [...] If you want zstd you'll have to convince the CPython developers to add it to the stdlib. Meson is not going to depend on a third-party library.

Makes sense, that's totally fair.

>  bzip2 is absolutely on the table, however.

Excellent.  So is this... uh, all it takes?  Looks like the format just gets passed to `shutil.make_archive()` without any need for format-depdendent code?  If so, I'll whip up a PR:

```patch
diff --git a/mesonbuild/mdist.py b/mesonbuild/mdist.py
index faaf1bfdd..875d751f7 100644
--- a/mesonbuild/mdist.py
+++ b/mesonbuild/mdist.py
@@ -33,9 +33,10 @@ if T.TYPE_CHECKING:
     from ._typing import ImmutableListProtocol
     from .mesonlib import ExecutableSerialisation
 
-archive_choices = ['gztar', 'xztar', 'zip']
+archive_choices = ['gztar', 'bztar', 'xztar', 'zip']
 
 archive_extension = {'gztar': '.tar.gz',
+                     'bztar': '.tar.bz2',
                      'xztar': '.tar.xz',
                      'zip': '.zip'}
 
```

**Comment by eli-schwartz** [comment]
Check out HgDist.create_dist too.

**Comment by eli-schwartz** [comment]
> > The lzip page is a bad meme...
> 
> 🤷🏻‍♂️

I'm not sure how worth it it is to get into the nitty gritty details. But the *author" of lzip is the kind of author that means that I'd simply refuse to implement lzip support specifically, on moral grounds. I don't care if CPython has stdlib support for it, I don't care whether there are "no technical downsides" to adding the option. It would make me deeply uncomfortable to touch the project with a ten foot pole.

**Comment by kelnos** [comment]
> Check out HgDist.create_dist too.

Ah, right, missed that.  Pushed  #13090.
