### ISSUE TITLE
Broken packaging for Windows through pip

### ISSUE THREAD

**Issue by doraskayo** [mesonbuild/meson#1310]
The current pip distribution turns makes Meson's Python scripts unable to run in Windows.

**Reproduction steps:**

- Get Windows. (I use Windows 10, version 1607)
- Install Python 3.x (I currently have v3.6.0:41df79263a11) and make sure you tick the "Add to PATH" checkbox.
- Open the command prompt (cmd.exe) and run `pip3 install meson`
- When it finishes installing, try to run `meson.py -h`

\* You may have to restart at some point in the process, Windows is weird like that.

**Expected results:**
Meson should run and show its syntax.

**Actual results:**
You get the following error:
```
Unable to create process using 'c:\users\my user\appdata\local\programs\python\python36\python.exe "C:\Users\My User\AppData\Local\Programs\Python\Python36\Scripts\meson.py"  -h'
```

**The reason:**
If I look at the installed Meson Python scripts, I see that the shebang line is the following:
```
#!c:\users\my user\appdata\local\programs\python\python36\python.exe
```
While it should be:
```
#!/usr/bin/env python3
```
Changing this value back fixes the problem and allows me to run "meson.py -h" without any issue.

### EDIT:
Apparently the issue actually comes from the fact that there is a space in the path to python.exe. Adding quotations around the path is another way to fix it, like so:
```
#"!c:\users\my user\appdata\local\programs\python\python36\python.exe"
```

**Comment by nirbheek** [comment]
We don't have any special requirements, so ideally we should be able to look at some other project that is using pip on Windows successfully and do what they're doing.

**Comment by doraskayo** [comment]
I investigated this issue a bit further, and it seems the problem comes from the space in the shebang. (see my edit for more information)

Apparently the issue (or a similar issue) was reported (pypa/setuptools#398) and closed without resolution by pointing to a new issue (pypa/pip#2783). At some point later a pull request landed (pypa/setuptools#616) and was documented to be part of [setuptools 24.3.1](https://github.com/pypa/setuptools/blob/master/CHANGES.rst#v2431) even though it actually landed in [setuptools 25.1.2](https://github.com/pypa/setuptools/commit/6547430bf289c7285498303ea77eef56702c3a95), at the same time as the release notes for 24.3.1 [were updated](https://github.com/pypa/setuptools/commit/3c9a71fa4e161500d45b64590274007871303280). Weird so far. Anyway, this pull request claimed to have fixed the original reported issue (pypa/setuptools#398), yet didn't actually mention the new issue that was opened. As long as it's fixed, I guess.

So then I checked my setuptools version:
```
C:\Users\My User\Desktop>pip3 show setuptools
Name: setuptools
Version: 28.8.0
```
`28.8.0 > 25.1.2 > 24.3.1`, right? Yet... I can still reproduce the bug.

So I ran `pip3 install -U setuptools` and now I got:
```
C:\Users\My User\Desktop>pip3 show setuptools
Name: setuptools
Version: 33.1.0
```
`33.1.0 > 28.8.0 > 25.1.2 > 24.3.1`, right? Well, it still happens.

The weirdest part? [These guys](https://github.com/semio/ddf_utils/issues/38#issuecomment-262681310) claim it works for them! I honestly have no idea at this point. Can someone else confirm that they can reproduce it?

**Comment by doraskayo** [comment]
Another update, I can't reproduce the bug anymore when I install with this:
```
pip3 install git+https://github.com/mesonbuild/meson.git@0.37.1
```

And I can still reproduce it with this:
```
pip3 install meson
```

@jpakkane, it's probably the version of setuptools that you use for packaging.

**Comment by scivision** [comment]
I'm not sure when this was fixed, but I have been `pip install meson` on Windows and other platforms for many months without an issue, including using as `install_requires = meson` from other packages. I think this was fixed by setuptools et al some time in the past.
