### ISSUE TITLE
Issue with Building pandas 2.2.2

### ISSUE THREAD

**Issue by SSSavii** [mesonbuild/meson#13156]
Describe the bug
During the installation of pandas version 2.2.2, the preparation of metadata (pyproject.toml) fails with a UnicodeDecodeError. The error occurs when running a subprocess within the build process, specifically when setting up Meson.

To Reproduce
The issue occurred when attempting to install pandas using pip with the following command:
shell

pip install pandas==2.2.2
Unfortunately, I do not have a meson.build file to provide as this is a standard installation process using pip.

Expected behavior
I expected pandas to install without any errors. Instead, the process failed during the preparation of metadata with a Unicode decoding error.

System parameters
- This is a native build on a Windows system.
- Operating System: Windows 10
- Python Version: 3.12.32 (32-bit)
- Meson Version: (not provided, as the error occurs before Meson setup completion)
- Ninja Version: (not applicable, as the error occurs before Meson setup completion)

The error log is as follows:
Preparing metadata (pyproject.toml): finished with status 'error'
error: subprocess-exited-with-error

Preparing metadata (pyproject.toml) did not run successfully.
exit code: 2

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 46: invalid continuation byte

ERROR: Unhandled python exception

This is a Meson bug and should be reported!

Additional context
The error message suggests that this is a Meson-related issue and not a problem with pip itself. The error originates from a subprocess, indicating that it might be a bug in the Meson build system.

**Comment by thesamesam** [comment]
I wonder if this is the same as https://github.com/mesonbuild/meson/issues/13154.

**Comment by SSSavii** [comment]
> I wonder if this is the same as #13154.

Most likely yes
