### ISSUE TITLE
Meson fails to link Boost::Regex

### ISSUE THREAD

**Issue by furkanusta** [mesonbuild/meson#1316]
My build file is 

```
project('file_matcher', 'cpp')
lib = shared_library('lib/file_matcher', 'src/file_matcher.cpp')
boost = dependency('boost', modules : ['regex'])
executable('match_test', 'src/main.cpp', link_with : lib, dependencies : boost)
```
This generates

`c++    -o liblib/file_matcher.so 'lib/file_matcher@sha/src_file_matcher.cpp.o' '-Wl,--no-undefined' '-Wl,--as-needed' '-shared' '-fPIC' '-Wl,-soname,liblib/file_matcher.so' '-Wl,-rpath,/home/eksi/Projects/52Weeks/1_test_build/2/build/' `

Which results in lots of linker errors regarding boost::regex functions.

If I have copy the above command and append -lboost_regex at the end it works.

**Comment by nirbheek** [comment]
I investigated this, and it's not a bug. The actual file using `boost::regex` is  `src/file_matcher.cpp`, so you need to add the boost dependency there too:

```
project('file_matcher', 'cpp')
boost = dependency('boost', modules : ['regex'])
lib = shared_library('lib/file_matcher', 'src/file_matcher.cpp', dependencies : boost)
executable('match_test', 'src/main.cpp', link_with : lib, dependencies : boost)
```

You only need to add `dependencies : boost` to `executable()` too if you are using Boost there too.

**Comment by nirbheek** [comment]
Of course if you were building a static library you wouldn't need to add boost to the dependencies, but since you're building a shared library it needs to know what to link against.

**Comment by furkanusta** [comment]
Thanks that one worked. I thought I would need to link the whole executable file.
