### ISSUE TITLE
Objective-C doesn't recognize C2x or C18

### ISSUE THREAD

**Issue by dreamer-coding-555** [mesonbuild/meson#13202]
**Describe the bug**
Seems Objective-C doesn't recognize C2x or C18 standards, and it works when I set the standard to C17 but this doesn't seem to help with my libraries which use C2x by default.

**To Reproduce**
```meson
project('objc test', 'objc', default_options: ['c_std=c2x'])

executable('pizza', 'main.m')
```

**Expected behavior**
I expect it to compile even with this new standard of C, assuming Objective-C is still an extinction of C after all of the years it's been around.

**system parameters**
* It was a `CI build`?
* operating systems (MacOS latest, Windows latest, Windows 2022, Ubuntu latest)
* python `3.13.0`
* meson `1.2.0`, `1.3.0`, `1.4.0` <- versions used in CI test run
* ninja `1.11.1`

**Comment by dreamer-coding-555** [comment]
Already have a working solution, and seems it is possible to configure subprojects to use a different standard.

**Comment by theoparis** [comment]
+1 for this issue, why does meson not support gnu2x when clang does? Can this be reopened?

**Comment by bonzini** [comment]
For the record this is now fixed.
