### ISSUE TITLE
Setting `fortran_args = ['']` will cause `meson compile` to fail

### ISSUE THREAD

**Issue by zoziha** [mesonbuild/meson#13215]
**Describe the bug**
In `meson 1.3.0rc1` and later, setting `fortran_args = ['']` will cause `meson compile` to fail, and the build command in the `build.ninja` will appear `""` for example:

```text
 build libtest1.a.p/src_acx_kinds.F90.obj: fortran_COMPILER ../src/acx_kinds.F90 || libtest1.a.p/depscan.dd
 DEPFILE = "libtest1.a.p\src_acx_kinds.F90.obj.d"
 DEPFILE_UNQUOTED = libtest1.a.p\src_acx_kinds.F90.obj.d
 ARGS = "-Ilibtest1.a.p" "-I." "-I.." "-fdiagnostics-color=always" "-D_FILE_OFFSET_BITS=64" "-Wall" "-O0" "-g" "" "-Jlibtest1.a.p"
 dyndep = libtest1.a.p\depscan.dd
```

The `"` is the main reason for the build failure. Query the source code of `meson`, I believe it is related to the following code: https://github.com/mesonbuild/meson/blob/bfb9ca04529aea96c1c997a8d881ddc7df7d6c84/mesonbuild/backend/ninjabackend.py#L2894

A simple patch can solve this problem (I don't know much about `meson` code, just for reference.):
```diff
diff --git a/mesonbuild/backend/ninjabackend.py b/mesonbuild/backend/ninjabackend.py
index 28f5d532f..9d1d3bbf7 100644
--- a/mesonbuild/backend/ninjabackend.py
+++ b/mesonbuild/backend/ninjabackend.py
@@ -2891,7 +2891,9 @@ https://gcc.gnu.org/bugzilla/show_bug.cgi?id=47485'''))
                 commands += compiler.get_include_args(d, i.is_system)
         # Add per-target compile args, f.ex, `c_args : ['-DFOO']`. We set these
         # near the end since these are supposed to override everything else.
-        commands += self.escape_extra_args(target.get_extra_args(compiler.get_language()))
+        extra_args = self.escape_extra_args(target.get_extra_args(compiler.get_language()))
+        if extra_args != ['']:
+            commands += extra_args
 
         # D specific additional flags
         if compiler.language == 'd':
```

**To Reproduce**
This is a toy example for a bug report for `meson`: [zoziha/meson-bug-report](https://github.com/zoziha/meson-bug-report).

**Expected behavior**
`meson compile` executes normally, and the compilation is not interrupted normally.

**system parameters**
* A plain native build (for the same computer).
* Windows 11.
* Python 3.11.9.
* Meson 1.4.0.
* Ninja 1.12.1.

**Comment by eli-schwartz** [comment]
This is expected behavior since you told the compiler to use an actual argument with zero length.

An array of length one, content `''` is not the same as an array of length zero, no content. There are valid use cases for both, e.g. the value to a flag can be set to empty and this produces different results compared to not passing the flag at all.

Is there a reason you wanted to pass a blank string as a positive component of the compiler command line?

**Comment by zoziha** [comment]
@eli-schwartz, thanks for the reply, I thought that the behavior of `meson` will automatically remove the quotes, and then pass it to the compiler. There is a deviation between my understanding and the `meson` feature.

But in retrospect, this incident surprised me. My original `meson.build` was to use `meson_options.txt` to control the macro definition `-DC2`: [diff-1 (bad)](https://github.com/zoziha/meson-bug-report/commit/91056260cae2a7deeb7aa481a86cc8bc9e7c6842#diff-30d8f6be6320feeacf686be94f48c70869b52630e01ea625f0f15adc0d57c3e4).
```diff
 project('test', 'fortran')

-test_lib = static_library('test1', 'src/kinds.F90', fortran_args: [''])  # This is the problem: `fortran_args: ['']`
+C2 = get_option('C2')
+if C2
+    C2_macro = '-DC2'
+else
+    C2_macro = ''
+endif
+
+test_lib = static_library('test1', 'src/kinds.F90', fortran_args: [C2_macro])  # This is the problem: `fortran_args: ['']`

 exe = executable('test2', 'src/main.f90',
    link_with: [test_lib])
```
```diff
+option('C2', type: 'boolean', value: false, description: 'use C2 macros')
+option('C4', type: 'boolean', value: true, description: 'use C4 macros')
```
I didn't mean to pass the empty string `[""]` to the compiler, when `C2 == False`, I just pass the compiler parameter `[]`. _`meson <=1.2.3`, my meson project works fine, and after updating the version to `1.4.0`, the project failed to build_, **which surprised me**, but no hints.

---

Now I know I should define macros like this [diff-2 (good)](https://github.com/zoziha/meson-bug-report/commit/a0c3d16df45e90c1d7800d53a525e1b9ac4024d7#diff-30d8f6be6320feeacf686be94f48c70869b52630e01ea625f0f15adc0d57c3e4):
```diff
diff --git a/meson.build b/meson.build
index b594880..b3a3783 100644
--- a/meson.build
+++ b/meson.build
@@ -1,13 +1,11 @@
 project('test', 'fortran')
 
-C2 = get_option('C2')
-if C2
-    C2_macro = '-DC2'
-else
-    C2_macro = ''
+fortran_args = []
+if get_option('C2')
+    fortran_args += '-DC2'
 endif
 
-test_lib = static_library('test1', 'src/kinds.F90', fortran_args: [C2_macro])  # This is the problem: `fortran_args: ['']`
+test_lib = static_library('test1', 'src/kinds.F90', fortran_args: [fortran_args])

 exe = executable('test2', 'src/main.f90',
     link_with: [test_lib])
```
Crude idea, maybe `meson` can detect the existence of `""`, after all, `""` will cause the compilation to fail, and the user side is not easy to find the root reason, because there is no obvious hint; or maybe it is not necessary to do this, because at least the latest `meson 1.4.0` will throw a compilation error (this is a **expected behavior**, compared to `meson <=1.2.3`), but the user like me may not be good to detect the cause of failure.

```diff
diff --git a/mesonbuild/backend/ninjabackend.py b/mesonbuild/backend/ninjabackend.py
index 28f5d532f..6684a9697 100644
--- a/mesonbuild/backend/ninjabackend.py
+++ b/mesonbuild/backend/ninjabackend.py
@@ -2891,7 +2891,13 @@ https://gcc.gnu.org/bugzilla/show_bug.cgi?id=47485'''))
                 commands += compiler.get_include_args(d, i.is_system)
         # Add per-target compile args, f.ex, `c_args : ['-DFOO']`. We set these
         # near the end since these are supposed to override everything else.
-        commands += self.escape_extra_args(target.get_extra_args(compiler.get_language()))
+        commands += [
+            s
+            for s in self.escape_extra_args(
+                target.get_extra_args(compiler.get_language())
+            )
+            if s != ""
+        ]
 
         # D specific additional flags
         if compiler.language == 'd':
```

**Comment by eli-schwartz** [comment]
> @eli-schwartz, thanks for the reply, I thought that the behavior of `meson` will automatically remove the quotes, and then pass it to the compiler. There is a deviation between my understanding and the `meson` feature.

Meson doesn't remove quotes. Quotes are syntax, not data. `''` isn't a pair of empty quotes, it is a meson array containing one string. It gets forwarded to the compiler using bash, and bash also uses quotes as syntax to denote strings (in this case, not always. Bash requires quotes for ambiguous cases that cannot be word-split obviously otherwise, and a blank string is one of those cases where bash needs those quotes.)

> I didn't mean to pass the empty string `[""]` to the compiler, when `C2 == False`, I just pass the compiler parameter `[]`. _`meson <=1.2.3`, my meson project works fine, and after updating the version to `1.4.0`, the project failed to build_, **which surprised me**, but no hints.

In my testing, both meson 1.2.3 and meson 1.4.0 fail in the same way. You would need to use `[]` in both cases.
