### ISSUE TITLE
Does meson discourage outside contributors?

### ISSUE THREAD

**Issue by gabeblack** [mesonbuild/meson#13210]
I took time to contribute this feature: https://github.com/mesonbuild/meson/pull/13035 which had indication in other threads of being something that might be desired.

However, the radio silence has turned me off to making further contributions. The general Q/A forum here seems to get responses which I am very appreciative -- however, I'm surprised that those that want to contribute back are ignored.

Did I miss a procedure when trying to contribute back? Or are outside contributors discouraged from contributing? Or something else?

**Comment by gabeblack** [comment]
I did ping a couple of times. No matter though -- because I didn't know that waiting more than a month for a response is normal. I do have a day-job and a family, so trying to keep that thread/fork alive and up-to-date over the period of multiple months is probably not something I'm willing to do and maintain. I do appreciate the project and was hoping to contribute when I can. However, I don't think my current work/life balance allows for such a long dev/contribution cycle. No biggie. Again, I appreciate your reply to my inquiry and I appreciate the meson project in general.

I'll close this issue as well as my PR request as to not clutter your issues/merge requests forum. Again thank you.

**Comment by thesamesam** [comment]
I understand. It's not always easy to page in all the context from months ago and so on. I agree the review situation could be a lot better..

**Comment by mid-kid** [comment]
You don't need to "maintain" a fork - if the changes are approved, it can be updated then for the sake of merging.
