### ISSUE TITLE
Error: Un-handled python exception while installing through vcpkg

### ISSUE THREAD

**Issue by amad-haseeb** [mesonbuild/meson#13295]
**Python version:** ```3.7.5```
**OS:** ```Ubuntu bionic```

I am statically compiling some packages through vcpkg, the content of vcpkg is as followed
```
{
    "dependencies": [
        "librdkafka",
	"libconfig",
        "glib"
    ]
}
```

**Error thrown on std::out**

```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /usr/bin/python3 -I /root/kafka/vcpkg/downloads/tools/meson-1.3.2-aa4767/meson.py setup -Dselinux=disabled -Dlibmount=disabled -Dgtk_doc=false -Dinstalled_tests=false -Dlibelf=disabled -Dman=false -Dtests=false -Dxattr=false --backend ninja --wrap-mode nodownload -Doptimization=plain --libdir lib --native /root/kafka/vcpkg/buildtrees/glib/meson-x64-linux-dbg.log -Ddebug=true --prefix /root/kafka/vcpkg/packages/glib_x64-linux/debug --includedir ../include -Dcmake_prefix_path=['/root/kafka/libs/vcpkg_installed/x64-linux/debug','/root/kafka/libs/vcpkg_installed/x64-linux'] /root/kafka/vcpkg/buildtrees/glib/src/glib-2-322e03f702.clean
    Working Directory: /root/kafka/vcpkg/buildtrees/glib/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /root/kafka/vcpkg/buildtrees/glib/config-x64-linux-dbg-meson-log.txt.log
      /root/kafka/vcpkg/buildtrees/glib/config-x64-linux-dbg-out.log

Call Stack (most recent call first):
  /root/kafka/libs/vcpkg_installed/x64-linux/share/vcpkg-tool-meson/vcpkg_configure_meson.cmake:436 (vcpkg_execute_required_process)
  ports/glib/portfile.cmake:42 (vcpkg_configure_meson)
  scripts/ports.cmake:175 (include)

```

**Error in /root/kafka/vcpkg/buildtrees/glib/config-x64-linux-dbg-meson-log.txt.log**

```
Traceback (most recent call last):
  File "/root/kafka/vcpkg/downloads/tools/meson-1.3.2-aa4767/mesonbuild/scripts/python_info.py", line 64, in <module>
    paths, install_paths = get_install_paths()
  File "/root/kafka/vcpkg/downloads/tools/meson-1.3.2-aa4767/mesonbuild/scripts/python_info.py", line 53, in get_install_paths
    import distutils.command.install
ModuleNotFoundError: No module named 'distutils.command'


../src/glib-2-322e03f702.clean/meson.build:2330:26: ERROR: <PythonExternalProgram 'python3' -> ['/usr/bin/python3']> is not a valid python or it is missing distutils

```
**Error in meson-logs.txt**
```

Build started at 2024-06-05T06:57:42.708336
Main binary: /usr/bin/python3
Build Options: -Dselinux=disabled -Dlibmount=disabled -Dgtk_doc=false -Dinstalled_tests=false -Dlibelf=disabled -Dman=false -Dtests=false -Dxattr=false -Doptimization=plain -Ddebug=true '-Dcmake_prefix_path=[/root/kafka/libs/vcpkg_installed/x64-linux/debug,/root/kafka/libs/vcpkg_installed/x64-linux]' -Dprefix=/root/kafka/vcpkg/packages/glib_x64-linux/debug -Dincludedir=../include -Dlibdir=lib -Dbackend=ninja -Dwrap_mode=nodownload --native-file=/root/kafka/vcpkg/buildtrees/glib/meson-x64-linux-dbg.log
Python system: Linux
The Meson build system
Version: 1.3.2
Source dir: /root/kafka/vcpkg/buildtrees/glib/src/glib-2-322e03f702.clean
Build dir: /root/kafka/libs
Build type: native build

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!

```

**PS:** I have executed the following command to verify if the python library is importable, but it got executed successfully 

```python3 -c "import distutils"```

**Comment by eli-schwartz** [comment]
@amitdo,

Actually Ubuntu bionic provides backports of 3.7 and 3.8

@amad-haseeb,

Ubuntu mutilates their python package and only half of it is installed by default. You need to get the other half with `apt install python3-distutils` IIRC (plus another couple of packages for the other missing bits).

**Comment by amad-haseeb** [comment]
@amitdo,
The system alternative were updated to point to python 3.7 instead of 3.6, so python3 was pointing to `3.7.5.`

:

@eli-schwartz: Thanks mate, I was missing the one you mentioned, rest were installed,  
those other packages are `python3.x-dev` and `python3.x `itself.

**PS:** It compiled successfully after installing `python3-distutils`

**Comment by eli-schwartz** [comment]
The other packages I'm referring to are things like "venv" (important but not specifically for meson). There's also tkinter but to be fair lots of distros make that optional.

**Comment by amad-haseeb** [comment]
Okay, But I was already building these packages inside a container so it was already a contained environment.

**Comment by amitdo** [comment]
Me:

>In Ubuntu 18.04, python3 points to python 3.6 which is not supported in meson 1.3.

@eli-schwartz 

> @amitdo,
> 
> Actually Ubuntu bionic provides backports of 3.7 and 3.8

Yes, I know, but this does not invalidates what I said. python3 will still point to the default python version in the distro, which is python 3.6, after installing python 3.7/3.8.

**Comment by eli-schwartz** [comment]
As the OP noted, Ubuntu itself was configured to select the backported 3.7 as /usr/bin/python3 using standard dpkg technologies.

Meson CI does the same thing, as it happens, on our single runner for Ubuntu Bionic.
