### ISSUE TITLE
[REGRESSION] since 'Better error message when using = rather than : for defining keywords.'

### ISSUE THREAD

**Issue by thiblahute** [mesonbuild/meson#1331]
Since 8ec9b0a71ffa1043b17a11e594219971c9288600 I am getting:

```
Meson encountered an error in file subprojects/gst-plugins-base/tests/check/meson.build, line 135, column 8:
Tried to assign values inside an argument list.
To specify a keyword argument, use : instead of =.
```

But [this](https://phabricator.freedesktop.org/diffusion/GSTBASE/browse/master/tests/check/meson.build;f9d110f596e3a81722e8af1586fea633f8d6741c$135) is the code:
```
    env.set('GST_PLUGIN_LOADING_WHITELIST', 'gstreamer',
        'gst-plugins-base@' + meson.build_root(), separator=':')
```

which is correct afaict

**Comment by jpakkane** [comment]
Why do you assume it is correct? Set is a regular method and its kwargs should be specified with a colon, so `separator : ':'`.

**Comment by thiblahute** [comment]
Because I am being blind, sorry about that :)
