### ISSUE TITLE
Dependency-related regression in 1.5.0rc1

### ISSUE THREAD

**Issue by thierryreding** [mesonbuild/meson#13352]
**Describe the bug**
When trying to build libepoxy with the latest meson 1.5.0rc1, I see issues with some of the test programs not linking properly against libX11. libepoxy doesn't seem to be the problem here, since meson 1.4.0 works fine.

I was able to bisect this to commit 6d713e40f815 ("dependency: define equality and hash operators for Dependency"). Reverting that commit fixes the regression.

**To Reproduce**
Download the latest [libepoxy](https://github.com/anholt/libepoxy/archive/refs/tags/1.5.10.tar.gz), extract and build using:

    $ mkdir libepoxy-1.5.0/build && cd libepoxy-1.5.0/build
    $ meson setup ..
    $ ninja

And see it fail to link various GLX, GLES tests.

**Expected behavior**
libepoxy should build without any errors.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
  Happens with both native and cross builds.
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
  Arch Linux, but I expect it to be distribution agnostic.
* what Python version are you using e.g. 3.8.0
  Python 3.12.3
* what `meson --version`
  meson 1.5.0.rc1
* what `ninja --version` if it's a Ninja build
  ninja 1.12.1

**Comment by eli-schwartz** [comment]
See also https://bugs.gentoo.org/935443
