### ISSUE TITLE
meson setup fails with "Module "features" does not exist

### ISSUE THREAD

**Issue by ozhang3** [mesonbuild/meson#13364]
Encountered this error while manually building numpy-2.0.0 with meson 1.4.1 on Ubuntu 20.04

Here's the error verbatim:
meson_cpu/x86/meson.build:2:15: ERROR: Module "features" does not exist

Here's the relevant portions of the meson.build file:

source_root = meson.project_source_root()
mod_features = import('features')

SSE = mod_features.new(
  'SSE', 1,  args: '-msse',
  test_code: files(source_root + '/numpy/distutils/checks/cpu_sse.c')[0]
)
SSE2 = mod_features.new(
  'SSE2', 2, implies: SSE,
  args: '-msse2',
  test_code: files(source_root + '/numpy/distutils/checks/cpu_sse2.c')[0]
)

P.S. I manually built and installed meson 1.4.1 on my system.

Any ideas?

**Comment by QuLogic** [comment]
NumPy requires its bundled copy of Meson; see #11307.
