### ISSUE TITLE
Compile of pulseaudio with meson 1.5.0rc1 errors with - Can not modify object after it has been used.

### ISSUE THREAD

**Issue by heitbaum** [mesonbuild/meson#13372]
**Describe the bug**

Compile of pulseaudio with meson 1.5.0rc1 errors with - Can not modify object after it has been used.

../src/pulsecore/meson.build:206:8: ERROR: Can not modify object after it has been used.

https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/blob/master/src/pulsecore/meson.build?ref_type=heads#L206

**To Reproduce**
Please include your `meson.build` files, preferably as a minimal toy example showing the issue.
You may need to create simple source code files (don't include private/proprietary code).

as per the meson.build - https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/blob/master/src/pulsecore/meson.build?ref_type=heads#L206

**Expected behavior**

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? 
  * Yes
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) 
  * Ubuntu 24.04 for LibreELEC target.
* what Python version are you using e.g. 3.8.0 
  * 3.11.9
* what `meson --version`
  * 1.5.0rc1
* what `ninja --version` if it's a Ninja build

**Comment by eli-schwartz** [comment]
@thesamesam found a similar problem with libvirt.

**Comment by thesamesam** [comment]
Bisecting.

**Comment by thesamesam** [comment]
9f02d0a3e5a5ffc82256391c244b1af38e41ef78 is the first bad commit
commit 9f02d0a3e5a5ffc82256391c244b1af38e41ef78
Author: Xavier Claessens <xavier.claessens@collabora.com>
Date:   Fri Apr 5 08:55:20 2024 -0700

    Clarify mutable objects usage

    Only Environment and ConfigurationData are mutable. However, only
    ConfigurationData becomes immutable after first use which is
    inconsistent.

    This deprecates modification after first use of Environment object and
    clarify documentation.

cc @xclaesse

**Comment by eli-schwartz** [comment]
It's a breaking change because we now mark it as used in many cases we didn't used to (every single unholder??? *wow*).

It's also an inconsistent change because there are still other cases we assign the `.used` attribute directly and the commit in question didn't seem to make any effort to look at existing use cases.

In retrospect that was an obvious red flag that the PR was incorrect.
