### ISSUE TITLE
want array.get() with fallback

### ISSUE THREAD

**Issue by tp-m** [mesonbuild/meson#1337]
I often find myself doing arrays of things like e.g. unit tests or exes or such which are then processed in a foreach loop. Sometimes each array element is an array in itself, so that 'extra' things like extra source files, extra deps and such can be added. This means that inside the array one has to have lots of 
```
extra_foo = []
if element.length() > N
  extra_foo = element.get(N)
endif
```

It would be nicer if we could just do:
```
extra_foo = element.get_with_fallback(N, [])
```
and ideally it would default to returning `[]` if no fallback is specified.

**Comment by tp-m** [comment]
Or maybe we can tweak the existing `get()` somehow, like if it gets passed a second argument that would be the fallback.

**Comment by nirbheek** [comment]
Python does exactly that with `.get()`, so we could do it too.
