### ISSUE TITLE
meson: Not able to install systemd unitdir files

### ISSUE THREAD

**Issue by BadganchiP1234** [mesonbuild/meson#13393]
**meson verion: 1.3.1
ninja version: 1.11.1**

Build is getting failed during during do_configure task for lxc component.
As we are trying to install systemd service files.
**PACKAGECONFIG[systemd] = "--with-systemdsystemunitdir=${sysconfdir}/systemd/system/,--without-systemdsystemunitdir,systemd,"**

Could you please check?

**ERROR:**

`| NOTE: Installed into sysroot: []
| NOTE: Skipping as already exists in sysroot: ['audit', 'libselinux', 'libsemanage', 'libsepol', 'openssl', 'base-files', 'base-passwd', 'expat', 'gettext-minimal-native', 'glibc', 'libxcrypt', 'libxml2', 'ncurses', 'systemd-systemctl-native', 'systemd', 'util-linux-libuuid', 'util-linux', 'zlib', 'binutils-cross-x86_64', 'cmake-native', 'gcc-cross-x86_64', 'gcc-runtime', 'libgcc', 'libedit', 'libtool-cross', 'libtool-native', 'm4-native', 'opkg-utils', 'python3', 'qemu-native', 'quilt-native', 'bzip2', 'libnsl2', 'libtirpc', 'shadow-sysroot', 'shadow', 'tcp-wrappers', 'texinfo-dummy-native', 'xz', 'kmod', 'linux-libc-headers', 'acl', 'attr', 'bash-completion', 'gdbm', 'libcap-ng', 'libcap', 'libffi', 'libpcre2', 'libseccomp', 'sqlite3', 'openssl-native', 'coreutils-native', 'expat-native', 'gettext-native', 'glib-2.0-native', 'ncurses-native', 'util-linux-libuuid-native', 'util-linux-native', 'zlib-native', 'autoconf-native', 'automake-native', 'flex-native', 'gnu-config-native', 'intltool-native', 'libedit-native', 'make-native', 'meson-native', 'ninja-native', 'patch-native', 'libxml-parser-perl-native', 'perl-native', 'pkgconfig-native', 'pseudo-native', 'python3-build-native', 'python3-flit-core-native', 'python3-installer-native', 'python3-jinja2-native', 'python3-markupsafe-native', 'python3-packaging-native', 'python3-pyproject-hooks-native', 'python3-setuptools-native', 'python3-wheel-native', 'python3-native', 'swig-native', 'bzip2-native', 'gperf-native', 'libnsl2-native', 'libtirpc-native', 'shadow-native', 'unzip-native', 'xz-native', 'zstd-native', 'gtk-doc-native', 'attr-native', 'gdbm-native', 'gmp-native', 'libbsd-native', 'libcap-ng-native', 'libffi-native', 'libmd-native', 'libmpc-native', 'libpcre2-native', 'mpfr-native', 're2c-native', 'sqlite3-native']
| DEBUG: Python function extend_recipe_sysroot finished
| DEBUG: Executing shell function do_configure
| NOTE: Executing meson -Dtests=true -Ddistrosysconfdir=/etc/default -Dapparmor=false -Dman=false -Dseccomp=true -Dselinux=true --with-systemdsystemunitdir=/etc/systemd/system/...
| usage: meson [-h]
|              {setup,configure,dist,install,introspect,init,test,wrap,subprojects,rewrite,compile,devenv,env2mfile,help}
|              ...
| meson: error: unrecognized arguments: --with-systemdsystemunitdir=/etc/systemd/system/
| ERROR: meson failed
| WARNING: exit code 1 from a shell command.
ERROR: Task (/home/builder/src/base/node0/meta-virtualization/recipes-containers/lxc/lxc_git.bb:do_configure) failed with exit code '1'`

**Comment by tristan957** [comment]
Please read the error message. It tells you exactly what is wrong.

**Comment by eli-schwartz** [comment]
Your error post was faulty. I've updated it to use triple backticks (code fences) rather than single backticks (inlin code).

The error message is now able to be read -- it makes it clear what the actual error is.
