### ISSUE TITLE
gpl v3 license in https://github.com/mesonbuild/meson/blob/master/test%20cases/format/2%20muon/crazy_comments.meson

### ISSUE THREAD

**Issue by vchhasatia** [mesonbuild/meson#13442]
Hello meson Team,

I was confused to see GPL v3 licensed file https://github.com/mesonbuild/meson/blob/master/test%20cases/format/2%20muon/crazy_comments.meson.

I was wondering if you plan to relicense it under Apache 2.0. 

Thank you for your time.

**Comment by eli-schwartz** [comment]
@bruchar1 @annacrombie

**Comment by bruchar1** [comment]
Oups! I took that file from muon test cases: https://git.sr.ht/~lattis/muon/tree/master/item/tests/fmt/crazy_comments.meson

Having a licence on that test file doesn't really make sense imho. Not sure what I should do about that. Should I just modify it enough so it doesn't look like a license violation?

**Comment by eli-schwartz** [comment]
> Hi, muon is using https://reuse.software/ which requires that every file in the repo has a license and copyright. I'm not really sure on the legality of this but I give my consent to just remove the copyright in meson's version 😄.

If you are the sole author of the file then your consent to have it be licensed under the meson (Apache) license is all it takes.

**Comment by eli-schwartz** [comment]
"we have permission" is perhaps a bit less precise than 
```
# SPDX-License-Identifier: GPL-3.0-only OR Apache-2.0
```

Which would indicate it has been relicensed with permission for use by meson, rather than "permission granted to use it anyway".

**Comment by dcbaker** [comment]
I like @eli-schwartz's suggestion.
