### ISSUE TITLE
'prefix' doesn't appear to be working anymore (default_options)

### ISSUE THREAD

**Issue by rhd** [mesonbuild/meson#1349]
```
00:12 $ ./meson/meson.py --version
0.38.0
```

I have this in my `meson.conf`

```python
project('ECS', ['cpp', 'c'],
    default_options : ['buildtype=debugoptimized',
                       'cpp_std=c++11',
                       'errorlogs=true',
                       'prefix=@0@/dist'.format(meson.current_source_dir())]
)
```

`mesonconf.py` returns this

```
  prefix         Installation prefix.                     /usr/local    
```

If I specify the `prefix` on the meson command line it works as expected.

This worked in .37.1

Thoughts?

Edit:
I expect it to say:
```
  prefix         Installation prefix.                     /path/to/proj/dist 
```

**Comment by nirbheek** [comment]
Looks like a regression. I'll look into this since I probably broke it in the first place. The fix will go into a point release next week.

**Comment by nirbheek** [comment]
I've added a commit to #1342 that fixes this. Can you test that it works for you?

**Comment by rhd** [comment]
I'm not exactly sure hot to pull down the PR directly, but I manually made the change from #1342 and it worked!

**Comment by nirbheek** [comment]
Thanks for testing! For future reference, you can look underneath the PR subject where it says `into mesonbuild:master from centricular:commonpath-py34`, the remote is [`centricular`](https://github.com/centricular/meson) and the branch is `commonpath-py34`. So if `git remote add` and `git checkout` and you're done. :)

**Comment by QuLogic** [comment]
If it's a PR, which this is, then it's even easier: `git fetch upstream pull/1349/head:temporary-branch-to-test`.

**Comment by nirbheek** [comment]
Ah, didn't know you could do that, thanks :)

**Comment by dzhang-b** [comment]
```
# meson --version
0.54.0
```
`meson configure --prefix=$(pwd)` or `meson --reconfigure build --prefix=$(pwd)` no longer works.

In the meson configure output, it does not show new prefix value. The `meson.build` is basically empty, generate from `meson init`.
