### ISSUE TITLE
Make it possible to refer to the compilation database directly

### ISSUE THREAD

**Issue by lf-** [mesonbuild/meson#13500]
Yes, this request is absurd and bad, and I am well aware of that. My use case is absolutely evil. What I am doing is, since it turns out that Nix's cc-wrapper is very broken and it is extremely nontrivial to get the *correct* compile args to be able to load a PCH built by Clang (stuff like stack protector args are injected at runtime. it's awful. I can't even wrap clang-tidy the same way since the cc-wrapper is tightly coupled to pointing it at an actual compiler called cc), I need to generate a modified compilation database with the problems caused by the cc-wrapper fixed up.

I am doing this with a `custom_target`. To do this, I need to get a reference to the `compile_commands.json` in the global build directory.

The code looks something like so:

```meson
pchless_compdb = custom_target(
  command : [
    python,
    meson.current_source_dir() / 'clean_compdb.py',
    '@INPUT@',
    '@OUTPUT@',
  ],
  capture : false,
  build_by_default : false,
  input : meson.global_build_root() / 'compile_commands.json',
  output : 'pchless_compdb.json',
)

if lix_clang_tidy_so_found
  run_target(
    'clang-tidy',
    command : [
      run_clang_tidy,
      '-load',
      lix_clang_tidy_so,
      '-p',
      pchless_compdb,
    ]
  )
endif
```

Related: https://github.com/mesonbuild/meson/issues/4481, #8635

**Comment by eli-schwartz** [comment]
compile_commands.json is only created once, at the end of configuring.

Maybe instead you could just use [`meson.add_postconf_script(clean_compdb_py)`](https://mesonbuild.com/Reference-manual_builtin_meson.html#mesonadd_postconf_script)

**Comment by lf-** [comment]
Ah, yep, that *does* work. I think that's probably a more correct approach for this use case. Thanks!!

**Comment by dcbaker** [comment]
@lf- If you're using a nix-shell environment (ie, not building nix derivations), adding `hardeningDisable = ['all']` will fix some of that

**Comment by lf-** [comment]
I'm doing both, so that's inapplicable. The "correct" solution is to wrap clang-tidy, but the solution I actually implemented was to delete the pch arguments from the compilation database. i suppose i could also reimplement the hardening options logic but i was not a fan of the idea.
