### ISSUE TITLE
Fix UnicodeEncodeError in AIX due to recent commit.

### ISSUE THREAD

**Issue by KamathForAIX** [mesonbuild/meson#13519]
**Describe the bug**
A recent commit at https://github.com/mesonbuild/meson/commit/3587786a3cf5dd06aa4cab2b6abb36bfd7c7eca0 caused build breaks for all AIX CI projects due to a unicode error. 

The error is as follows:

```
File "/home/buildusr/jenkins/workspace/meson/meson/meson_install/opt/freeware/lib/python3.11/site-packages/mesonbuild/minstall.py", line 445, in do_symlink
    self.log(f'Installing symlink: {link} \u2192 {target}')
  File "/home/buildusr/jenkins/workspace/meson/meson/meson_install/opt/freeware/lib/python3.11/site-packages/mesonbuild/minstall.py", line 380, in log
    print(msg)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2192' in position 111: ordinal not in range(256)
```

This happens only when we run meson install in AIX.

**To Reproduce**
Build any project like glib2 on AIX that requires symlinks during installation and run meson install post the build process.

**system parameters**
AIX - 7.1 or higher.
Master branch of Meson.

To fix this problem I propose to use the following change that gets the build back to normal.

```
# diff -u ./mesonbuild/minstall.py_orig ./mesonbuild/minstall.py     
--- ./mesonbuild/minstall.py_orig       2024-08-06 00:19:16.464691659 -0500
+++ ./mesonbuild/minstall.py    2024-08-06 00:20:18.704690962 -0500
@@ -442,7 +442,7 @@
                 raise MesonException(f'Destination {link!r} already exists and is not a symlink')
             self.remove(link)
         if not self.printed_symlink_error:
-            self.log(f'Installing symlink: {link} → {target}')
+            self.log(f'Installing symlink: {link} ->  {target}')
         try:
             self.symlink(target, link, target_is_directory=os.path.isdir(abs_target))
         except (NotImplementedError, OSError):
```

If the community is okay, then I would like to raise a PR with this fix and close it. Kindly let me know if this is okay for all of us. @jpakkane @eli-schwartz

**Comment by eli-schwartz** [comment]
Fixed, thanks for the report.

**Comment by KamathForAIX** [comment]
Thank you @eli-schwartz
