### ISSUE TITLE
Handling meson project setup with name "meson" more gracefully. 

### ISSUE THREAD

**Issue by KunalSin9h** [mesonbuild/meson#13527]
**Describe the bug**
When creating meson project, with name `meson` in `meson.build` file, the process crash with error "ried to overwrite internal variable "meson"". It is hard at first glance to comprehend the cause of failure. 

**To Reproduce**
create `meson.build` as: 

> The project name is `meson`, same as tool name. 

```js
project('meson', 'cpp',
        version : '1.0.0',
        default_options : ['warning_level=3', 'cpp_std=c++20'])

meson = executable('meson', 'main.cpp', install : true)

test('test', meson)
```

**Expected behavior**
The expected error message should be "Dont create project name same as meson", or something like that. 

**system parameters**
meson version: 1.5.1
C++ compiler for the host machine: c++ (gcc 13.2.0 "c++ (Ubuntu 13.2.0-23ubuntu4) 13.2.0")
C++ linker for the host machine: c++ ld.bfd 2.42
Host machine cpu family: x86_64
Host machine cpu: x86_64
Build targets in project: 1

**Comment by LDAP** [comment]
I believe the issue is this line `meson = executable('meson', 'main.cpp', install : true)` where you "tried to overwrite internal variable "meson""

**Comment by eli-schwartz** [comment]
> When creating meson project, with name `meson` in `meson.build` file, the process crash with error "ried to overwrite internal variable "meson"". It is hard at first glance to comprehend the cause of failure.

It's not a crash.

```
The Meson build system
Version: 1.5.1
Source dir: /tmp/test
Build dir: /tmp/test/builddir
Build type: native build
Project name: meson
Project version: 1.0.0
C++ compiler for the host machine: ccache c++ (gcc 13.3.1 "c++ (Gentoo 13.3.1_p20240614 p17) 13.3.1 20240614")
C++ linker for the host machine: c++ ld.bfd 2.42
Host machine cpu family: x86_64
Host machine cpu: x86_64

meson.build:5:8: ERROR: Tried to overwrite internal variable "meson"

A full log can be found at /tmp/test/builddir/meson-logs/meson-log.txt
```

It tells you exactly where the error is! Line 5 (column 8), not line 1. The issue is that there is an internal variable meson, as in, you can do this:

```meson
meson.add_install_script('foo.sh')

top_srcdir = meson.project_source_root()
```

etc. See https://mesonbuild.com/Reference-manual_builtin_meson.html

You cannot create a variable named "meson" since it overwrites the internally defined variable.  You can of course do something like:

```meson
project('meson', 'cpp',
        version : '1.0.0',
        default_options : ['warning_level=3', 'cpp_std=c++20'])

meson_exe = executable('meson', 'main.cpp', install : true)

test('test', meson_exe)
```
This works fine as far as meson is concerned, but creating an executable called "meson" seems... interesting given mesonbuild also installs a "meson" executable. :D

**Comment by eli-schwartz** [comment]
Note that e.g. syntax highlighting would mark the `meson = ` part to show "meson" as a builtin name, an indicator you shouldn't be assigning to it.

**Comment by KunalSin9h** [comment]
@eli-schwartz i got that, we should not create executable with meson name. But when someone does, like me accidentally. The error message should be easy to fix the issue. _

> This works fine as far as meson is concerned, but creating an executable called "meson" seems... interesting given mesonbuild also installs a "meson" executable. :D

**Comment by eli-schwartz** [comment]
Again, this has nothing to do with the executable name. The error message says that the *variable* name "meson" is reserved.

**Comment by KunalSin9h** [comment]
@eli-schwartz got it.
