### ISSUE TITLE
Is there a way to generate multiple executables

### ISSUE THREAD

**Issue by agauniyal** [mesonbuild/meson#1352]
Like taking input of an array of individual source files and generating corresponding executables for them..

**Comment by TingPing** [comment]
`foreach` loop over the sources?

**Comment by agauniyal** [comment]
@TingPing could you provide an example or guide me to relevant wiki section :)

**Comment by nirbheek** [comment]
This is the exact example given on the wiki: https://github.com/mesonbuild/meson/wiki/Syntax#foreach-statements

**Comment by agauniyal** [comment]
Thank you!
