### ISSUE TITLE
ld: unknown option: -export_dynamic

### ISSUE THREAD

**Issue by ryandesign** [mesonbuild/meson#13543]
**Describe the bug**
Some software building with meson now fails to build on Mac OS X 10.6 and earlier because meson now uses the linker flag `-export_dynamic` which the linker on Mac OS X 10.6 and earlier does not understand. See https://trac.macports.org/ticket/70386 and https://trac.macports.org/ticket/70496. This is a regression. This was caused by #13291 to fix #13290. The addition of this flag is suspect to me since all software that has ever built using meson on Mac OS X 10.6 prior to this change did so successfully without this flag. We are now reverting this change in MacPorts on Mac OS X 10.6 and earlier. Cc @barracuda156 

**To Reproduce**
Build e.g. glib2 with meson on Mac OS X 10.6.

**Expected behavior**
Successful build

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? plain native build
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.): Mac OS X 10.6
* what Python version are you using e.g. 3.8.0: 3.12.5
* what `meson --version`: 1.5.1
* what `ninja --version` if it's a Ninja build: 1.12.1

**Comment by thesamesam** [comment]
cc @wolfgangwalther
