### ISSUE TITLE
Why does Meson require g++ or clang when it has Ninja?

### ISSUE THREAD

**Issue by Universal-Flare** [mesonbuild/meson#13558]
I am newly setting up Meson with VSCode and I want to keep a minimal install for coding. Meson dosen't seem to check for ninja while checking for g++ or any other compiler. After Installed another compiler, it detects  Ninja and works.

My question is that, why does it require any other compiler when it already has Ninja and could work with it?

Does Ninja require the other compilers?

**Comment by eli-schwartz** [comment]
I'm not entirely sure what the question is.

Meson requires a compiler, if you specify that your project has C/C++ code to compile. It also requires ninja as a "makefile" backend.

Ninja isn't a compiler.

**Comment by Universal-Flare** [comment]
OK sorry, I was confused
