### ISSUE TITLE
Static library may contain stale object files

### ISSUE THREAD

**Issue by codido** [mesonbuild/meson#1355]
If a meson build script removes files from a static library, they may still reside in the resulting library after rebuilding.

For example, if the following is built:
```
project('test', 'c')

lib = static_library('foo', 'file1.c')

executable('a.out', 'main.c', link_with: lib)
```

libfoo.a will include file1.c.o. However, if meson.build is changed so file2.c is used instead, libfoo.a will include both file1.c.o and file2.c.o:
```
$ nm libfoo.a 

file1.c.o:
...

file2.c.o:
...
```

At least on gcc, linking the final executable will link in file1.o (most likely because it precedes file2.o), which would result in a broken executable if at all.

**Comment by nirbheek** [comment]
This is a consequence of how `ar` works. It will either create the specified static library, or if it already exists, it will append to it. There is no option to `ar` that will make it overwrite an existing static library.

I think we need to always delete the static library first and then create it.
