### ISSUE TITLE
Quoting of "<" breaks my custom command

### ISSUE THREAD

**Issue by exposedcranium** [mesonbuild/meson#13561]
**Describe the bug**

I use `</dev/null` at the end of some custom commands. For some reason, this gets quoted in the `build.ninja`, which results in the command (in my case GCC) treating this parameter literally (as a file) instead of treating it as a file redirection, which it is.

**To Reproduce**

Use the `<` character somewhere in your custom target's command kwarg.

**Expected behavior**

No quoting.

**Comment by eli-schwartz** [comment]
The `command:` kwarg for custom targets accepts an execvp-compatible array of arguments representing the command to run -- that is why it doesn't accept a single string.

If you want to include posix shell arguments you should be able to do that by specifying the command as "sh" and the args as `'-c', 'command string goes here </dev/null'`.

Aside: what is the context behind asking GCC to read devnull as the input? It doesn't sound like you're compiling an input file... are you scraping for information? This may be possible to do with meson's built-in compiler methods.

**Comment by eli-schwartz** [comment]
For general purpose receiving the input/output files as stdin/stdout of the custom target command there are the kwargs "feed" and "capture". Not really applicable to devnull I guess. :/
