### ISSUE TITLE
meson format: how to handle unknown keys in `meson.format`

### ISSUE THREAD

**Issue by dcbaker** [mesonbuild/meson#13569]
Right now we ignore unknown keys, and this seems like the worse possible solution. This makes a typo into infuriating behavior of trying to figure out "why isn't it doing what I told it to?"

The larger question to me is one of, do we make it a warning or an error?

I'm kinda leaning to error, since we could realistically have new keys for new behaviors, and a project could well expect that those new behaviors are used, and running an older `meson format` might not handle things the way the project wants.

**Comment by bruchar1** [comment]
I think it should be an error
