### ISSUE TITLE
Cannot run_target() from a subproject: unknown target type

### ISSUE THREAD

**Issue by lorcap** [mesonbuild/meson#13607]
**Describe the bug**
A `run_target()` in a subproject is not accessible.

**To Reproduce**
1. Create the following two `meson.build` scripts:
```sh
cat > meson.build <<END
project('main')
A_prj = subproject('A')
run_target('hello_main', command: ['/usr/bin/echo', 'hello_main'])
END

mkdir -p subprojects/A
cat > subprojects/A/meson.build <<END
project('A')
run_target('hello_A', command: ['/usr/bin/echo', 'hello_A'])
END
```
2. Run `meson setup build`.
3. The command `meson compile -C build hello_main` prints `hello_main` as expected.
4. Command `meson compile -C build A:hello_A` fails with:
```
ERROR: Can't invoke target `A:hello_A`: unknown target type: `hello_A`
```
5. Command `meson compile -C build hello_A` fails with:
```
INFO: calculating backend command to run: /usr/bin/ninja -C /home/lorcap/meson-test/build hello_A
ninja: Entering directory `/home/lorcap/meson-test/build'
ninja: error: unknown target 'hello_A', did you mean 'A@@hello_A'?
```
6. Command `meson compile -C build A@@hello_A` fails with:
```
ERROR: Can't invoke target `A@@hello_A`: target not found
```

**Expected behavior**
Command `meson compile -C build A:hello_A` should run successfully and print `hello_A`.

**System parameters**
* plain native build
* Linux 6.10.6-arch1-1
* Python 3.12.4
* meson 1.5.1
* ninja 1.12.1

**Comment by lorcap** [comment]
I respond to myself.

`:` are used when two targets have the same name but different types, e.g., when both executable and application library have the same name:

```sh
meson compile -C build main:executable # for main
meson compile -C build main:static_library # for libmain.a
```

In order to compile a subproject's target, prepend `subprojects/<project_name>/` to the target and specify the type if needed:

```sh
meson compile -C build subprojects/A/hello_A:executable
```

**Comment by julianneswinoga** [comment]
This bug was incorrectly closed. It's still possible to reproduce the original `run_target()`-in-subproject issue, at least with the `ninja` backend.

**Comment by eli-schwartz** [comment]
Please specify which of the several different approaches you are referring to by "the original issue".

**Comment by julianneswinoga** [comment]
Following the original reproduction steps, trying the "solution" of prepending `subprojects/<project_name>/` with the `run_target()`:
```
$ meson compile -C build subprojects/A/hello_A
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /usr/bin/ninja -C /tmp/meson_repro/build hello_A
ninja: Entering directory `/tmp/meson_repro/build'
ninja: error: unknown target 'hello_A', did you mean 'A@@hello_A'?
```

**Comment by eli-schwartz** [comment]
So to be clear, it does work with the ninja backend command when invoked as `A@@hello_A`?

In general, `ninja` allows you to do many things `meson compile` doesn't. The latter always desugars to "calculating backend command to run" anyway -- there is no "meson compile backend".

**Comment by julianneswinoga** [comment]
That is correct, using `ninja` directly works
```
$ ninja -C build/ A@@hello_A
ninja: Entering directory `build/'
[0/1] Running external command hello_A (wrapped by meson to set env)
hello_A
```

**Comment by julianneswinoga** [comment]
Interestingly it seems like the `@@` target syntax is only for `run_target`s and created by meson (i.e. it's not a `ninja`ism) and was introduced by https://github.com/mesonbuild/meson/pull/2286

**Comment by eli-schwartz** [comment]
> Interestingly it seems like the `@@` target syntax is only for `run_target`s and created by meson (i.e. it's not a `ninja`ism)

Ninja doesn't create *any* target names.

run_target doesn't produce a file output, it is a ".PHONY" target which means that the target name can be and is different from one that was chosen by meson (again) via the `output:` parameter of some mesonn.build file.
