### ISSUE TITLE
How to create build sub-directory

### ISSUE THREAD

**Issue by samwise** [mesonbuild/meson#1361]
I am trying to move a C++ project that uses Protocol Buffers to meson. I used the example in the meson project to get started:
```

project('protocol buffer test', 'cpp')

protoc = find_program('protoc')
dep = dependency('protobuf')

gen = generator(protoc, \
  output    : ['@BASENAME@.pb.cc', '@BASENAME@.pb.h'],
  arguments : ['--proto_path=@SOURCE_DIR@', '--cpp_out=@BUILD_DIR@', '@INPUT@'])

generated = gen.process('defs.proto')
e = executable('prog', 'main.cpp', generated, dependencies : dep)
test('prototest', e	)
```

The first issue I came across is that I want my generated files to go into @BUILD_DIR@/gen, but the protoc compiler will not create the output directory automatically and I could not find a way to instruct meson to create this 'gen' sub directory. 

Any suggestions?

**Comment by nirbheek** [comment]
Did you close this issue because you've solved the issue for yourself or was it by accident?
