### ISSUE TITLE
Incorrect host architecture with x86 clang-cl

### ISSUE THREAD

**Issue by vid512** [mesonbuild/meson#13643]
When using x86 Visual Studio clang-cl, Meson reports the host architecture as x86_64. 

**Reproduce:**
run.bat
```
<...VS path...>\vcvarsall.bat x86
set CXX=clang-cl
meson setup 
```

The meson.build can be anything that builds
```
project('test', 'cpp')
executable('a', ['a.cpp'])
```

a.cpp:
```
int main() {
	return 0;
}
```

You will get:
```
Host machine cpu: x86_64
```

This is different from what you get with either cl.exe, or clang.exe from same dev environment. Here is a full log showcasing the same situation with cl.exe, clang.exe and clang-cl.exe. Notice that only with clang-cl meson considers host to be x86_64. 

```
d:\dev\_testbed\meson\simple>call "c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" x86
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.11.2
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x86'

d:\dev\_testbed\meson\simple>set platform
Platform=x86

d:\dev\_testbed\meson\simple>where cl
c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\Hostx86\x86\cl.exe

d:\dev\_testbed\meson\simple>meson setup --wipe build_cl   | findstr "Host machine"
C++ compiler for the host machine: cl (msvc 19.41.34120 "Microsoft (R) C/C++ Optimizing Compiler Version 19.41.34120 for x86")
C++ linker for the host machine: link link 14.41.34120.0
Host machine cpu family: x86
Host machine cpu: x86

d:\dev\_testbed\meson\simple>findstr "link"   0<build_cl\build.ninja
# Rules for linking.
 command = "link" $ARGS /MACHINE:x86 /OUT:$out $in $LINK_ARGS

d:\dev\_testbed\meson\simple>set CXX=clang

d:\dev\_testbed\meson\simple>where clang
c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\bin\clang.exe

d:\dev\_testbed\meson\simple>dumpbin /headers "c:\Program Files\Microsoft Visual Studio\2022\Community\\VC\Tools\Llvm\bin\clang.exe"   | findstr "magic"
             10B magic # (PE32)

d:\dev\_testbed\meson\simple>meson setup --wipe build_clang   | findstr "Host machine"
C++ compiler for the host machine: clang (clang 17.0.3 "clang version 17.0.3")
C++ linker for the host machine: clang link 14.41.34120.0
Host machine cpu family: x86
Host machine cpu: i686

d:\dev\_testbed\meson\simple>findstr "link"   0<build_cl\build.ninja
# Rules for linking.
 command = "link" $ARGS /MACHINE:x86 /OUT:$out $in $LINK_ARGS

d:\dev\_testbed\meson\simple>set CXX=clang-cl

d:\dev\_testbed\meson\simple>where clang-cl
c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\bin\clang-cl.exe

d:\dev\_testbed\meson\simple>dumpbin /headers "c:\Program Files\Microsoft Visual Studio\2022\Community\\VC\Tools\Llvm\bin\clang-cl.exe"   | findstr "magic"
             10B magic # (PE32)

d:\dev\_testbed\meson\simple>meson setup --wipe build_clang_cl   | findstr "Host machine"
C++ compiler for the host machine: clang-cl (clang-cl 17.0.3)
C++ linker for the host machine: lld-link lld-link 17.0.3
Host machine cpu family: x86_64
Host machine cpu: x86_64

d:\dev\_testbed\meson\simple>findstr "link"   0<build_cl\build.ninja
# Rules for linking.
 command = "link" $ARGS /MACHINE:x86 /OUT:$out $in $LINK_ARGS
```

**system parameters**
- Meson 1.5.1
- Visual Studio 2022 17.11.2
- Python 3.11.5

**Comment by dcbaker** [comment]
I'm not sure what's going on here, you can look at `environment.py`, in the `detect_cpu_family`, and see if you can figure out where we're going wrong. It's unfortunately going to be really difficult to diagnose without a windows machine in front of me

**Comment by vid512** [comment]
`detect_cpu_family` is called three times prior to meson displaying Host architecture. First time with `len(compilers)==0`. Second and third time are identical, now with `compilers['cpp']` set. Problem is that `compiler.target` is already `i686` here. No idea where that gets set.

**Comment by vid512** [comment]
I thought 'i686' was a wrong value, that was my mistake. The problem must be somewhere later.

'i686' gets set here: https://github.com/mesonbuild/meson/blob/53e11488d9ce01b14c2b280d66c3efeda1c60abc/mesonbuild/compilers/detect.py#L425C2-L425C40

32-bit `clang-cl --version` displays: `Target: i686-pc-windows-msvc`
64-bit `clang-cl --version` displays: `Target: x86_64-pc-windows-msvc`

**Comment by vid512** [comment]
So, the problem is detect_windows_arch: https://github.com/mesonbuild/meson/blob/53e11488d9ce01b14c2b280d66c3efeda1c60abc/mesonbuild/environment.py#L278

The value tested against should be 'i686', not 'x86', at least with my version of MSVC clang. Not sure if 'x86' is used somewhere else.
