### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by spaette** [mesonbuild/meson#13652]
This shell script is authorised for use and/or modification by the repository Maintainers.

```
$ cat typos.sh
#!/bin/sh

sed -i "s/Dependndency/Dependency/g" meson/mesonbuild/cargo/interpreter.py
sed -i "s/Its/It's/g" meson/mesonbuild/dependencies/boost.py
sed -i "s/Its/It\\\'s/g" meson/unittests/internaltests.py
sed -i "s/Informations/Information/g" meson/docs/markdown/Release-notes-for-1.2.0.md
sed -i "s/actally/actually/g" meson/mesonbuild/msetup.py
sed -i "s/ammount/amount/g" "meson/test cases/rust/5 polyglot static/meson.build"
sed -i "s/commiting/committing/g" "meson/test cases/format/5 transform/genexpected.cmd"
sed -i "s/complaning/complaining/g" meson/mesonbuild/compilers/detect.py
sed -i "s/compraison/comparison/g" meson/mesonbuild/cargo/builder.py
sed -i "s/dependecy/dependency/g" meson/docs/markdown/Builtin-options.md
sed -i "s/destinatin/destination/g" meson/unittests/baseplatformtests.py
sed -i "s/directores/directories/g" meson/mesonbuild/backend/vs2010backend.py
sed -i "s/dont/don't/g" meson/mesonbuild/modules/__init__.py
sed -i "s/expcted/expected/g" meson/mesonbuild/environment.py
sed -i "s/explict/explicit/g" meson/mesonbuild/interpreter/interpreter.py
sed -i "s/expresion/expression/g" meson/data/shell-completions/bash/meson
sed -i "s/extention/extension/g" meson/mesonbuild/backend/vs2010backend.py
sed -i "s/fundementally/fundamentally/g" meson/docs/yaml/functions/build_target.yaml
sed -i "s/intentinally/intentionally/g" "meson/test cases/rust/9 unit tests/test3.rs"
sed -i "s/lets/let's/g" meson/docs/markdown/Release-notes-for-1.0.0.md
sed -i "s/lets/let's/g" meson/unittests/machinefiletests.py
sed -i "s/locaiton/location/g" meson/unittests/baseplatformtests.py
sed -i "s/microsofts/Microsoft's/g" meson/mesonbuild/compilers/detect.py
sed -i "s/microsoft's/Microsoft's/g" meson/mesonbuild/compilers/detect.py
sed -i "s/occurence/occurrence/g" meson/mesonbuild/backend/backends.py
sed -i "s/palaceholder/placeholder/g" meson/docs/refman/generatormd.py
sed -i "s/paramater/parameter/g" meson/docs/markdown/Release-notes-for-1.3.0.md
sed -i "s/reproducability/reproducibility/g" meson/mesonbuild/cargo/interpreter.py
sed -i "s/responsability/responsibility/g" meson/docs/markdown/Wrap-dependency-system-manual.md
sed -i "s/sentinal/sentinel/g" meson/unittests/machinefiletests.py
sed -i "s/shoulfail/shouldfail/g" meson/docs/markdown/Release-notes-for-0.51.0.md
sed -i "s/simplicety/simplicity/g" meson/mesonbuild/cmake/generator.py
sed -i "s/sinec/since/g" meson/docs/yaml/objects/compiler.yaml
sed -i "s/skipps/skips/g" meson/mesonbuild/cmake/interpreter.py
sed -i "s/somesuch/some such/g" meson/mesonbuild/environment.py
sed -i "s/stoo/too/g" meson/mesonbuild/backend/ninjabackend.py
sed -i "s/tos ave/to save/g" meson/mesonbuild/options.py
sed -i "s/uncompatible/incompatible/g" meson/docs/markdown/Wrap-dependency-system-manual.md
sed -i "s/uncompatible/incompatible/g" meson/docs/markdown/Release-notes-for-1.5.0.md
sed -i "s/untill/until/g" meson/docs/yaml/functions/install_data.yaml
sed -i "s/usualy/usually/g" meson/mesonbuild/backend/ninjabackend.py
$ 
```

manually fix these

```
$ grep -n dont meson/unittests/internaltests.py
1352:                      deprecated='2.0', deprecated_message='Its terrible, dont use it')
1364:            self.assertNotRegex(out.getvalue(), r'WARNING:.*deprecated.*input arg in testfunc. Its terrible, dont use it')
1378:            self.assertRegex(out.getvalue(), r'WARNING:.*deprecated.*input arg in testfunc. Its terrible, dont use it')
1411:            KwargInfo('output', ContainerTypeInfo(dict, str), default={}, deprecated_values={'foo': '0.9', 'foo2': ('0.9', 'dont use it')}, since_values={'bar': '1.1', 'bar2': ('1.1', 'use this')}),
1446:            self.assertRegex(out.getvalue(), r"""WARNING:.Project targets '1.0'.*deprecated since '0.9': "testfunc" keyword argument "output" value "foo2" in dict keys. dont use it.*""")
$ 
```

<hr>

Perhaps the grepped for strings are typos.

```
$ grep -nr sentinal meson
meson/unittests/machinefiletests.py:637:            'properties': {'bindgen_clang_arguments': 'sentinal'}
meson/unittests/machinefiletests.py:645:                self.assertIn('sentinal', args, msg="Did not find machine file value")
meson/unittests/machinefiletests.py:647:                sent_arg = args.index('sentinal')
meson/unittests/machinefiletests.py:648:                self.assertLess(cargs_start, sent_arg, msg='sentinal argument does not come after "--"')
$ grep -nr shoulfail meson
meson/docs/markdown/Release-notes-for-0.51.0.md:146:test('shoulfail', exe, should_fail: true)
$
```

**Comment by QuLogic** [comment]
Why 'donate' a shell script instead of opening a PR?

**Comment by spaette** [comment]
_cf_: `#11902` (merged Jun 27, 2023)

unittests/machinefiletests.py

@dcbaker 

Was use of `sentinal`  the intention in that file?

**Comment by dcbaker** [comment]
I consistently typo `sentinel` as `sentinal`, so no, not intentional

**Comment by spaette** [comment]
I'm adverse to open pull requests in repositories which utilise .mailmap files.

This is a one-off contribution to the code; if interested a Member can run the script on a fork's clone.

**Comment by dcbaker** [comment]
@spaette I can apply a patch if you want to just send a patch, you're welcome to set your email to `spaette@example.com` or whatever in said patch. It also looks like our mailmap is *horrifically* out of date, and only has a few developers in it, and we have no requirement to put an email address in the mailmap file.

**Comment by eli-schwartz** [comment]
Mailmap files are, by their very definition, a purely optional thing which users may self-nominate to add themselves to in the event that they have used multiple emails addresses in the past and prefer to credit all contributions to a single identity.

Not only is the fundamental git purpose an intrinsically optional and unforced thing, it's also... impossible to enforce?

What exactly would you enforce? Mailmap files can be used to replace a previous pseudonym with a new real name, or to replace a previous real name with a new pseudonym! They can be used to fix typos for invalid email addresses that were accidentally committed, too. But if you don't want to make such a change, don't mention it and no one will ever know?

Mailmap files CANNOT be used to enforce "legal name" policies, since by definition the use of a mailmap means the patches were originally committed using something else; as a basic matter of logic, projects with "legal name" policies would consider the original submission to be a violation, and would not use mailmap to fix it when they could instead just not merge the change.

As for meson -- meson's contributing guidelines make no mention of either "legal name" policies nor of mailmap files, so both are irrelevant.

**Comment by dcbaker** [comment]
Indeed, and I have been convinced elsewhere that a "legal name" policy is generally not a good one. So I would not be in favor of supporting that kind of policy.

**Comment by spaette** [comment]
They may be indexed by search engines.

**Comment by eli-schwartz** [comment]
If you wish for a convenient fake email address that will be automatically associated with your github account, but nothing else, then you can follow the instructions at https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address to set up an "@users.noreply.github.com" email address.

**Comment by eli-schwartz** [comment]
> They may be indexed by search engines.

If this is about spam prevention then I suspect those people / automated processes are already dumping git commit metadata even when it's not inside a displayed file, so the "noreply" email address is probably your best bet anyway.

**Comment by spaette** [comment]
absent any response to the contrary I'll add this line to the changes to be implemented

```
sed -i "s/shoulfail/shouldfail/g" meson/docs/markdown/Release-notes-for-0.51.0.md
```
