### ISSUE TITLE
illumos: Assert failed: FILE structure is defined in stdio.h, not stdlib.h

### ISSUE THREAD

**Issue by mtelka** [mesonbuild/meson#13688]
**Describe the bug**
I run tests on illumos and I found that the `common: 103 has header symbol` test fails with this error:
```
test cases/common/103 has header symbol/meson.build:19:2: ERROR: Assert failed: FILE structure is defined in stdio.h, not stdlib.h
```

**To Reproduce**
Run tests on illumos.

**Expected behavior**
The test pass.

**system parameters**
* cross/native: native
* operating system: OpenIndiana
* Python version: 3.9.20
* meson version: 1.5.1
* ninja version: 1.11.1

**Comment by mtelka** [comment]
I found that POSIX specifies the `FILE` to be found in [stdio.h](https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/stdio.h.html) and not in [stdlib.h](https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/stdlib.h.html).  I do not understand why `meson` expects the opposite.

**Comment by mtelka** [comment]
Actually, this assert message is confusing a bit because it tries to say that the `FILE` was found in `stdlib.h` and this was unexpected (and not the opposite as I thought before).

Anyway, the problem is that `-fpermissive` makes the compilation to pass without error on OpenIndiana:
```
$ cat test.c 
#include <stdlib.h>
int main(void) {
        FILE;
        return 0;
}
$ g++ -c -m64 -O3 -O0 -std=c++14 test.c 
test.c: In function 'int main()':
test.c:3:9: error: declaration does not declare anything [-fpermissive]
    3 |         FILE;
      |         ^~~~
$ g++ -c -m64 -O3 -O0 -fpermissive -std=c++14 test.c 
test.c: In function 'int main()':
test.c:3:9: warning: declaration does not declare anything [-fpermissive]
    3 |         FILE;
      |         ^~~~
$
```
This looks like a bug in gcc on OpenIndiana.  I tested GCC 7,10,11,12,13,14 and all of them behave same there.

**Comment by mtelka** [comment]
The problem is with illumos headers, not gcc itself: https://www.illumos.org/issues/16793

**Comment by alanc** [comment]
I don't see this problem on the Solaris side - your test case fails with both gcc & g++.

**Comment by mtelka** [comment]
@alanc, maybe the `/usr/include/stdio_tag.h` file got fixed on Solaris?

**Comment by eli-schwartz** [comment]
> Actually, this assert message is confusing a bit because it tries to say that the `FILE` was found in `stdlib.h` and this was unexpected (and not the opposite as I thought before).

The test case could be modified to have the assert say "is supposed to be defined in", rather than just "is defined in".

**Comment by alanc** [comment]
> @alanc, maybe the `/usr/include/stdio_tag.h` file got fixed on Solaris?

The only change we've made to `stdio_tag.h` itself since OpenSolaris was removing the CDDL & the SCCS ident tag - other than the license, ours appears to be identical to yours.

**Comment by mtelka** [comment]
Ah, right. The problem is not in the `stdio_tag.h` file, but in illumos' `/usr/include/floatingpoint.h`.  This file was added to illumos-gate in 2014, so it is not in Solaris and so the problem is illumos specific.

**Comment by alanc** [comment]
The Solaris copy of `/usr/include/floatingpoint.h` also has:
```
#ifdef __STDC__
#include <stdio_tag.h>
```
(it's part of the libm sources which are not in ON, but got merged into illumos instead of maintaining a separate consolidation for them as Solaris does for historical org-chart reasons).

And when I run `g++ -H test.c` on Solaris it does show that it includes `floatingpoint.h` and then `stdio_tag.h` from it.

If I use `g++ -E test.c` I can see that the results of processing `stdio_tag.h` are:
```
# 38 "/usr/include/floatingpoint.h" 3 4
# 1 "/usr/include/stdio_tag.h" 1 3 4
# 9 "/usr/include/stdio_tag.h" 3 4
extern "C" {
# 18 "/usr/include/stdio_tag.h" 3 4
typedef struct __FILE __FILE;


}
# 39 "/usr/include/floatingpoint.h" 2 3 4

namespace std {



typedef __FILE FILE;


}

````

and that appears to be the difference - our `floatingpoint.h` wraps the typedef inside `namespace std`, which I don't see in yours at https://github.com/illumos/illumos-gate/blob/master/usr/src/head/floatingpoint.h - that change went into ours back in 2007 under https://illumos.org/opensolaris/bugdb/bug.html#!6551534 and https://illumos.org/opensolaris/bugdb/bug.html#!6557863 so I don't know why it's not in yours.

**Comment by mtelka** [comment]
Thanks for the detailed analysis.  I updated the [illumos bug](https://www.illumos.org/issues/16793) to point to your comment.
