### ISSUE TITLE
add_global_arguments('-include foo.h' ....) does not work correctly for gcc compilers

### ISSUE THREAD

**Issue by B-B-Kuhn** [mesonbuild/meson#1375]
When I add the global argument '-include ...' for gcc tool chain I got the following error.

meson .. --buildtype=release
The Meson build system
Version: 0.39.0.dev1
Source dir: /mnt/hdd2/Data/err_example_include_arg
Build dir: /mnt/hdd2/Data/err_example_include_arg/build
Build type: native build
Project name: Err_Example_Include_Arg
Native cpp compiler: c++ (gcc 4.8.4)
Native c compiler: cc (gcc 4.8.4)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Build targets in project: 2
ubuntu@WE512699_U1809:/mnt/hdd2/Data/err_example_include_arg/build$ ninja
[1/4] Compiling c object 'example_c_exe@exe/examplec.c.o'
FAILED: example_c_exe@exe/examplec.c.o 
cc  '-Iexample_c_exe@exe' '-I.' '-I..' '-I /mnt/hdd2/Data/temp' '-pipe' '-Wall' '-Winvalid-pch' '-O3' '-include exampleinc.h' '-MMD' '-MQ' 'example_c_exe@exe/examplec.c.o' '-MF' 'example_c_exe@exe/examplec.c.o.d' -o 'example_c_exe@exe/examplec.c.o' -c ../examplec.c
In file included from <command-line>:0:0:
/usr/include/stdc-predef.h:59:1: fatal error:  exampleinc.h: No such file or directory
 #endif
 ^
compilation terminated.
[2/4] Compiling cpp object 'example_cpp_exe@exe/examplecpp.cc.o'
FAILED: example_cpp_exe@exe/examplecpp.cc.o 
c++  '-Iexample_cpp_exe@exe' '-I.' '-I..' '-I /mnt/hdd2/Data/temp' '-pipe' '-Wall' '-Winvalid-pch' '-Wnon-virtual-dtor' '-O3' '-include exampleinc.h' '-MMD' '-MQ' 'example_cpp_exe@exe/examplecpp.cc.o' '-MF' 'example_cpp_exe@exe/examplecpp.cc.o.d' -o 'example_cpp_exe@exe/examplecpp.cc.o' -c ../examplecpp.cc
In file included from <command-line>:0:0:
/usr/include/stdc-predef.h:59:1: fatal error:  exampleinc.h: No such file or directory
 #endif
 ^
compilation terminated.
ninja: build stopped: subcommand failed.
ubuntu@WE512699_U1809:/mnt/hdd2/Data/err_example_include_arg/build$ c++  '-Iexample_cpp_exe@exe' '-I.' '-I..' '-I /mnt/hdd2/Data/temp' '-pipe' '-Wall' '-Winvalid-pch' '-Wnon-virtual-dtor' '-O3' -include exampleinc.h '-MMD' '-MQ' 'example_cpp_exe@exe/examplecpp.cc.o' '-MF' 'example_cpp_exe@exe/examplecpp.cc.o.d' -o 'example_cpp_exe@exe/examplecpp.cc.o' -c ../examplecpp.cc
ubuntu@WE512699_U1809:/mnt/hdd2/Data/err_example_include_arg/build$ cc  '-Iexample_c_exe@exe' '-I.' '-I..' '-I /mnt/hdd2/Data/temp' '-pipe' '-Wall' '-Winvalid-pch' '-O3' -include exampleinc.h '-MMD' '-MQ' 'example_c_exe@exe/examplec.c.o' '-MF' 'example_c_exe@exe/examplec.c.o.d' -o 'example_c_exe@exe/examplec.c.o' -c ../examplec.c

When i remove the inverted comma arraound the -include argument on the command line then the error is gone.

Under the link below you will find a complete example with my workaround in the meson.build file.

[err_example_include_arg.tar.gz](https://github.com/mesonbuild/meson/files/766168/err_example_include_arg.tar.gz)

**Comment by nirbheek** [comment]
You are using it incorrectly; you must pass arguments as arrays, not strings everywhere in Meson. This will work:
```
add_global_arguments('-include', 'foo.h', language : 'c')
```

**Comment by nirbheek** [comment]
I've updated the documentation to explicitly say this. Closing.
