### ISSUE TITLE
Remove the `subprojects/` directory limitation

### ISSUE THREAD

**Issue by sardemff7** [mesonbuild/meson#1378]
I was advised on #1376 to use `subproject()` for a git submodule of mine. However, I have more than enough subdirectories already, and my submodules are in `src/` (with other non-submodule files) so the limitation to `subprojects/` is rather annoying to me.

Could it be possible to make this subdirectory a kwarg of the `subproject()` function? It sounds quite sad that my build system would enforce a layout on my repository.

**Comment by tp-m** [comment]
I would like to see this restriction lifted as well :)

**Comment by jpakkane** [comment]
You can set it in a kwarg to the [project() function](https://github.com/mesonbuild/meson/wiki/Reference%20manual#project). However it is recommended that you use the default value. By convention all Meson projects use the same dir, which makes it easier for people to move between projects. They always know where subprojects are and how to handle them. We admit this is slightly inconvenient for some projects that have uncommon directory layouts but it makes things a lot easier for the other >95% of projects that do not.

Note though that your subproject directory may only house subprojects. It can not have a mixture of subprojects and regular subdirs. Mixing the two is very confusing and unreliable so it is forbidden.

**Comment by sardemff7** [comment]
Too bad, Meson will not make it for me then.

**Comment by phillipjohnston** [comment]
I'm glad there is an argument to override the location. But the logic behind this limitation is silly.

Including your source files inside a `src/` directory is not an "uncommon layout".

**Comment by furkanmustafa** [comment]
Having a default is understandable, but forcing to use same directory name is extremely limiting.

I decide where to put my subprojects. And they are not always the same category. Could be `src/modules/something`, could be `vendor/libraresomething`..

**Comment by Tanishq-Banyal** [comment]
> I'm glad there is an argument to override the location. But the logic behind this limitation is silly.

Can you please share what argument did you use, couldn't find anything in documentation.

**Comment by ilg-ul** [comment]
I am also affected by this restriction, I cannot use `subproject()` in my builds, and I'm forced to use `subdir()`, which has its own share of limitations.

In my use case the sub-projects are all source libraries, brought into the project via a project manager which handles dependencies. The download folder is not unique, there are project wide dependencies, installed in an `xpacks` folder in the project root, and build configuration dependencies, installed in `xpacks` folders in the build folders, so it is absolutely no way to hack the the project hierarchy with symlinks to bring everything into a single folder called `subprojects`.

Given those limitations, using meson in multi-platform bare-metal embedded projects is not a very attractive solution, which is a pity.

https://github.com/mesonbuild/meson/discussions/9892

**Comment by Tanishq-Banyal** [comment]
You can change the subproject directory by passing `subproject_dir` option to your project()

**Comment by ilg-ul** [comment]
> passing subproject_dir option to your project()

Unfortunately this is not enough, the `subproject_dir` option allows to configure only one folder, while I need to pass multiple folders. Plus that the exactly which ones to use is known only at run-time, after parsing an option that defines the platform. :-(

So the really flexible solution would be to allow the parameter of `subproject()` to be an absolute path, anywhere in the filesystem. The second choice would be to allow to define a PATH like sequence of paths, at run-time.
