### ISSUE TITLE
meson.build:26:0: ERROR: Unknown options while I'm trying to build Mesa on FreeBSD.

### ISSUE THREAD

**Issue by Marietto2008** [mesonbuild/meson#13786]
Hello.

I'm running FreeBSD 14.1 right now and I suspect that the Mesa libs that I have installed on the system are bugged or maybe I have some misconfiguration,because when I do :

`# glxinfo | grep Mesa`

I get the error that you see on the title and smplayer/mpv/vlc doesn't work at all. Anyway,this is the context in which the error happens :

I have 3 GPUS :

```
1)

00:02.0 VGA compatible controller: Intel Corporation CoffeeLake-S GT2 [UHD Graphics 630]

01:00.0 VGA compatible controller: NVIDIA Corporation GP106 [GeForce GTX 1060 3GB]
01:00.1 Audio device: NVIDIA Corporation GP106 High Definition Audio Controller

02:00.0 VGA compatible controller: NVIDIA Corporation TU102 [GeForce RTX 2080 Ti]
02:00.1 Audio device: NVIDIA Corporation TU102 High Definition Audio Controller
02:00.2 USB controller: NVIDIA Corporation TU102 USB 3.1 Host Controller
02:00.3 Serial bus controller: NVIDIA Corporation TU102 USB Type-C UCSI Controller

I'm not using any xorg.conf.

nano /etc/rc.conf :

kld_list="nvidia-modeset nvidia-drm linux i915kms ext2fs"

nano /boot/loader.conf :

pptdevs="1/0/0 1/0/1 2/0/0 2/0/1 2/0/2 2/0/3 4/0/0"
hw.nvidiadrm.modeset=1
```

This is where the problem is :

```
[marietto@marietto ~]==> glxinfo | grep Mesa

X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  50
  Current serial number in output stream:  51
```

I've installed the following packages :

`# pkg install xf86-video-intel nvidia-drm-kmod drm-kmod nvidia-driver`

I've also tried to check if I had the same error by removing the xf86-video-intel and using the i915kms driver with Xorg :

```
# pkg remove xf86-video-intel
# nano /etc/X11/xorg.conf

Section "Device"
  Identifier  "Intel Graphics"
  Driver      "i915kms"
EndSection
```

But I've got the same error. Maybe it is a Mesa bug.

What's one consequence of this "bug" ? this one :

```
==> scrcpy --tcpip=192.168.1.3:5555

scrcpy 2.7 <https://github.com/Genymobile/scrcpy>
INFO: Connecting to 192.168.1.3:5555...
INFO: Connected to 192.168.1.3:5555
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 34.1 MB/s (71200 bytes in 0.002s)
[server] INFO: Device: [samsung] samsung SM-N9005 (Android 9)
[server] WARN: Audio disabled: it is not supported before Android 11

X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  147
  Current serial number in output stream:  148

```
What to do to fix that error ? 

Surfing the net,I found this tutorial,that maybe will help me :

https://eleni.mutantstargoat.com/hikiko/mesa-on-freebsd/

Unfortunately I've frozen myself trying to setup meson :

```
[marietto@marietto /usr/home/marietto/code/mesastuff/code/drm]==> meson setup ~/code/mesastuff/code/drm/build -Dplatforms=x11,drm -Ddri-drivers=i965,swrast -Dgallium-drivers=swrast,i965 -Dbuildtype=debug -Dvulkan-drivers=intel -Dglvnd=true -Dgles1=true -Dgles2=true -Degl=true -Dgallium-extra-hud=true -Dgallium-nine=true -Dtexture-float=true -Dgallium-vdpau=true -Dgallium-va=true -Dgallium-omx=auto

The Meson build system
Version: 1.5.2
Source dir: /usr/home/marietto/code/mesastuff/code/drm
Build dir: /usr/home/marietto/code/mesastuff/code/drm/build
Build type: native build

meson.build:26:0: ERROR: Unknown options: "dri-drivers, egl, gallium-drivers, gallium-extra-hud, gallium-nine, gallium-omx, gallium-va, gallium-vdpau, gles1, gles2, glvnd, platforms, texture-float, vulkan-drivers"
```

can someone explain to me how to fix that ? thanks.

**Comment by eli-schwartz** [comment]
> misconfiguration,because when I do :
> 
> ```
> # glxinfo | grep Mesa
> ```
> I get the error that you see on the title and smplayer/mpv/vlc doesn't work at all.

You cannot possibly get this error when running the installed `glxinfo` program.

> Unfortunately I've frozen myself trying to setup meson :
> 
> can someone explain to me how to fix that ? thanks.

You can check the output of `meson configure` to see what options actually exist for the current project.  Most likely you followed some directions for building one project, inside the source code for an entirely different project that doesn't have any of those options.

**Comment by Marietto2008** [comment]
-> You cannot possibly get this error when running the installed glxinfo program.

Can you elaborate more this sentence ?

**Comment by eli-schwartz** [comment]
You said that you get the error "you see in the title" when you run glxinfo.

The title contains "meson.build:26:0: ERROR"

**Comment by Marietto2008** [comment]
You are rigjt. Sorry,I have used another title. The original one,that's the error that I want to fix,is this one :

X Error of failed request:  BadValue (integer parameter out of range for operation)

**Comment by eli-schwartz** [comment]
Again:

Meson is saying the instructions you followed are totally wrong and that the project you are trying to build doesn't contain the options the instructions you followed say to use.

Ask the author of the tutorial, or use `meson configure` to see which options are supported. Builtin meson options are at the top, project options are at the bottom -- you want to know about project options.

**Comment by Marietto2008** [comment]
```
marietto@marietto /usr/home/marietto/code/mesastuff/code/mesa]==> meson setup build             
The Meson build system
Version: 1.5.2
Source dir: /usr/home/marietto/code/mesastuff/code/mesa
Build dir: /usr/home/marietto/code/mesastuff/code/mesa/build
Build type: native build
Project name: mesa
Project version: 24.3.0-devel
C compiler for the host machine: gcc (gcc 13.3.0 "gcc (FreeBSD Ports Collection) 13.3.0")
C linker for the host machine: gcc ld.bfd 2.43.1
C++ compiler for the host machine: g++ (gcc 13.3.0 "g++ (FreeBSD Ports Collection) 13.3.0")
C++ linker for the host machine: g++ ld.bfd 2.43.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Checking for size of "void*" : 8 
Checking if "-mtls-dialect=gnu2" runs: YES
Checking if "split TLSDESC" : links: YES 
Found pkg-config: YES (/usr/local/bin/pkg-config) 2.3.0
Run-time dependency libglvnd found: YES 1.7.0
Run-time dependency vdpau found: YES 1.5
Program glslangValidator found: YES (/usr/local/bin/glslangValidator)
Run-time dependency libva found: YES 1.22.0
Header "va/va.h" has symbol "VASurfaceAttribDRMFormatModifiers" with dependency libva: YES 
meson.build:782: WARNING: add_languages is missing native:, assuming languages are wanted for both host and build.
Rust compiler for the host machine: rustc -C linker=gcc (rustc 1.81.0)
Rust linker for the host machine: rustc -C linker=gcc ld.bfd 2.43.1
Program bindgen found: YES (/usr/local/bin/bindgen)
Found CMake: /usr/local/bin/cmake (3.30.4)
WARNING: CMake Toolchain: Failed to determine CMake compilers state
Run-time dependency libclc found: NO (tried pkgconfig and cmake)

meson.build:809:12: ERROR: Dependency "libclc" not found, tried pkgconfig and cmake

```

**Comment by Marietto2008** [comment]
Bro,it's different because in the while I've read more documentation to try to finish the tutorial.

**Comment by dcbaker** [comment]
If you're planning to use Mesa and Nvidia in parallel, you'll need to use glvnd, just a heads up. 

You may want to look at what the mesa port says it needs when you run `make all-depends-list` (I think that was the name, it's been a long time since I used FreeBSD)
