### ISSUE TITLE
Using vs as the backend to compile a  static library,but got a "*.a"

### ISSUE THREAD

**Issue by AdaSong697** [mesonbuild/meson#13797]
**Describe the bug**
I I was compiling a static library with meson, using vs as the back end, and I expected a *.lib that would work under windows, but I got a *.a instead

**To Reproduce**
meson.build:
project('test_msvc','c')
static_library('test_msvc',['module.c','module.h'])

module.c:
#include"module.h"
int add(int a,int b)
{
   return a+b;
}

module.h:
#include<stdio.h>

int add(int a,int b);

##
meson setup --backup vs build
##
**Expected behavior**
I expect to get a *.lib after compiling through the soultion project generated by meson

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?  --NO,it's native.
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)--windows 10
* what Python version are you using e.g. 3.8.0---3.12.2
* what `meson --version`--1.5.1
* what `ninja --version` if it's a Ninja build

**Comment by AdaSong697** [comment]
backend version is vs 2019

**Comment by eli-schwartz** [comment]
https://mesonbuild.com/FAQ.html#why-does-building-my-project-with-msvc-output-static-libraries-called-libfooa

**Comment by AdaSong697** [comment]
> This is an intentional, but understandably confusing choice by Meson. Microsoft decided to call a static archive a `.lib`, also interface libraries are called `.lib`. Interface libraries _must_ be called `.lib`, they don't work otherwise. static archives are, in fact, the exact same thing as a Unix `.a`, but with a different file extension, and the Microsoft tools don't have any problem with this.
> 
> Because Meson has the concept of a "both library", which will generate a `.dll` and `.a` from the same sources in the same directory, we cannot call both the import library and the static archive `.lib`, so we chose to call all static archives always `.a`.

thanks for your kindly reply.got it
