### ISSUE TITLE
Meson test fails on unordered TAP results

### ISSUE THREAD

**Issue by airtower-luna** [mesonbuild/meson#13802]
Meson requires TAP drivers to report test results in order:

https://github.com/mesonbuild/meson/blob/5cc511b1e6ff031f9257e11584c79e50370d9a4c/mesonbuild/mtest.py#L419-L420

However, the [TAP 14 specification states](https://testanything.org/tap-version-14-specification.html#test-point-id) that results may be reported in any order:

> Test Points *may* be output in any order, but any Test Point ID provided *must* be within the range described by the Plan.
> 
> This is valid TAP and a successful test run:
> ```
> TAP version 14
> 1..3
> ok 2
> ok 3
> ok 1
> ```

Oddly the specification also requires the harness to maintain an internal counter for unnumbered results, but I guess a test driver writing test IDs only for *some* results is unlikely.

Specification compliance aside, accepting unordered results would simplify concurrent test setups. Thanks for your attention! :smiley_cat:

**Comment by dcbaker** [comment]
TAP 12 doesn't allow this, so this would need to be based on the version of TAP used.

**Comment by airtower-luna** [comment]
I'm not sure that's actually necessary, in [the TAP 12 spec](https://testanything.org/tap-specification.html#the-test-line) I don't see any statement on whether test numbers have to be in order:

> TAP expects the ok or not ok to be followed by a test point number. If there is no number the harness must maintain its own counter until the script supplies test numbers again.

This is pretty much all it says about numbering, so I think if the counter considers possibly already reported results (and skips over them when counting up) it'd be compliant.
