### ISSUE TITLE
pkgconfig.relocatable in subproject default_options fails in parent project setup

### ISSUE THREAD

**Issue by seingierf** [mesonbuild/meson#13847]
**Describe the bug**
When setting up a parent project that includes a subproject with `pkgconfig.relocatable=true` in its `default_options`, meson setup fails in the parent project with the error:
```
subprojects/mysubprj/meson.build:1:0: ERROR: In subproject mysubprj: Unknown options: "mysubprj:pkgconfig.relocatable"
```

However, running meson setup directly within the subproject works without issue.
This change in behavior started with the following commit:
```
commit 6e200222957063819a00e3bf767ce28b7489c31f
Author: Jussi Pakkanen <jpakkane@gmail.com>
Date:   Sun Jul 14 19:33:41 2024 +0300

    Remove module type from OptionKey.
```

**To Reproduce**
In the parent project `meson.build`:
```
project('test', version : '1.0')
subproject('mysubprj')
```

In the subproject `meson.build`:
```
project('mysubprj', version : '1.0', default_options: ['pkgconfig.relocatable=true'])
```

Command-line steps:
```sh
cd test
meson setup build
# Error as shown above
cd test/subprojects/mysubprj
meson setup build
# Success
```

**Expected behavior**
The meson setup command in the parent project should successfully handle `pkgconfig.relocatable=true` in subproject `default_options` as it did in previous versions.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
native
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
Ubuntu 24.04
* what Python version are you using e.g. 3.8.0
3.12.3
* what `meson --version`
1.6.0

**Comment by amyspark** [comment]
Can confirm when using [librsvg](https://gitlab.gnome.org/gnome/librsvg) as a wrap from within the GStreamer repository.
