### ISSUE TITLE
gnome: mkenums: add support for generic template

### ISSUE THREAD

**Issue by tp-m** [mesonbuild/meson#1384]
It would be nice if `gnome.mkenums()` could be told to just do the right thing based on the same generic templating that is used by 99% of all enum file generation things.

The only thing that differs between the `.c.template` files is the prefix/includes at the beginning, and the only thing that differs between the `.h.template` files is the `#ifndef FOO_BAR_ENUMS_INCLUDED` guard.

**Comment by tp-m** [comment]
I've done some comparisons of template files in gtk+, GStreamer and json-glib to see how they differ. 

From that I find that following requirements for such a `mkenum_from_standard_template()` function:

- naming of include guard - could also just be replaced by #pragma once though (as done in config.h)
- one or multiple header includes for .c file
- optionally prefix `_get_type()` functions with underscore (from `gtkprivatetypebuiltins.[ch]`)
- optional direct include guard for header file, e.g.:
```
   #if !defined (__GTK_H_INSIDE__) && !defined (GTK_COMPILATION)
   #error "Only <gtk/gtk.h> can be included directly."
   #endif
```
- optional decorator for function declarations such as `GDK_AVAILABLE_IN_ALL` (slightly dubious though, since clearly enums are added later sometimes and you won't be able to differentiate on a per-include basis, but not our problem I suppose)
- some templates use `G_GNUC_CONST` for the declarations in the header file, others not. It's not correct though so we should not use it.
- some templates don't use `g_once_init_enter()` and friends to make the `_get_type()` functions thread-safe. We should simply always use this, and can always add a kwarg to not do it if someone really cares.

**Comment by mcatanzaro** [comment]
Isn't this fixed by mkenums_simple?
