### ISSUE TITLE
Need a way for scripts to know the path to mesonintrospect

### ISSUE THREAD

**Issue by tp-m** [mesonbuild/meson#1385]
Some custom target scripts may need to call other meson utilities such as `mesonintrospect` to get a list of targets, directories or such.

Case in point: gst-build's `uninstalled` target.

These scripts need to be able to call the *right* meson tool from the right directory, so that if I configured the build directory with `~/Devel/meson/meson.py` they can find `~/Devel/meson/mesonintrospect.py` instead of finding it in `PATH` and then have something like this happen:
```
[0/1] 'Running external command uninstalled.'
Traceback (most recent call last):
  File "/usr/bin/mesonintrospect", line 20, in <module>
    sys.exit(mintro.run(sys.argv[1:]))
  File "/usr/share/meson/mesonbuild/mintro.py", line 224, in run
    builddata = pickle.load(f)
AttributeError: Can't get attribute 'MachineInfo' on <module 'mesonbuild.environment' from '/usr/share/meson/mesonbuild/environment.py'>
FAILED: uninstalled 
'/usr/bin/python3' '/home/tpm/Devel/meson/meson.py' '--internal' 'commandrunner' '/home/tpm/Devel/gst-build' '/home/tpm/Devel/gst-build/build' '' '/home/tpm/Devel/gst-build/gst-uninstalled.py' '--builddir=/home/tpm/Devel/gst-build/build' '--gst-version=master'
```

I believe meson is supposed to be runnable from a git checkout without adding that to `PATH`?

**Comment by nirbheek** [comment]
Let's do this on a per-case basis? Let's start with `MESON_INTROSPECT` that points to the full path to `mesonintrospect`?

**Comment by tp-m** [comment]
Or that. There was some talk about possibly unifying all the different meson utils under a single `meson foo` interface like `git` does, so I thought the path to meson itself would be more future-proof, but I guess it doesn't matter.

**Comment by nirbheek** [comment]
I was just thinking that it would be almost impossible to debug or support someone running `meson` or `mesonconf` from inside a `meson` invocation or a `ninja` invocation, so explicitly exposing that would be asking for trouble.

**Comment by tp-m** [comment]
That's a good point.
