### ISSUE TITLE
Add a way to skip submodule tests

### ISSUE THREAD

**Issue by matthiasclasen** [mesonbuild/meson#13869]
My project builds with a bunch of submodules, but that doesn't mean that I need or want to run all
the subprojects' tests every time I run meson test.

Specifying all my subprojects testsuites in --no-suite arguments is entirely impractical.

**Comment by eli-schwartz** [comment]
The obvious way to do this would be to somehow specify the primary project as the suite. I can't recall off the top of my head if this works but can you try specifying the project name as the suite? It may work even though it's not a *sub*project.

**Comment by matthiasclasen** [comment]
Ah, that seems to work, thanks.
