### ISSUE TITLE
Linking step refers to the incorrect paths when dual booting.

### ISSUE THREAD

**Issue by gagero** [mesonbuild/meson#13898]
I dual boot Guix and Fedora. Compiling on Guix, Meson tries to link shared dependencies using Fedora's .so (in this case `/usr/lib64/libreadline.so` and vice versa (`/gnu/store/dl3665ynrp41ynyw2ay5kfqix93myj5d-readline-8.1.2/lib/libreadline.so`).

meson.build:
```
project(
  'example',
  'cpp',
)

readline_dep = dependency('readline')

executable(
  'simpledb',
	'src/main.cpp',
  dependencies: [
    readline_dep
  ]
)
```

**Expected behavior**
Meson uses the correct library paths.

Native build
Guix commit 4c56d0cccdc44e12484b26332715f54768738c5f/Fedora 41
Python 3.13.0 on Fedora, 3.10.7 on Guix
Meson 1.5.1 on both Fedora and Guix
ninja 1.12.1 on Fedora, 1.11.1 on Guix

**Comment by eli-schwartz** [comment]
This report doesn't actually explain what the issue is.

**Comment by eli-schwartz** [comment]
Are you saying that the LIBRARY_PATH produced by Guix is being sourced as an environment variable on your Fedora system?

And that your Guix compiler is configured to search in /usr/lib64?

**Comment by eli-schwartz** [comment]
Which one is it?
- is LIBRARY_PATH defined by Guix being sourced as an environment variable on Fedora
- is LIBRARY_PATH empty on Fedora

**Comment by eli-schwartz** [comment]
Maybe you could share logs of running meson and getting bad results, so we can better visualize the problem you're having?

**Comment by eli-schwartz** [comment]
Please post *complete* logs, starting with `meson setup`.

**Comment by dnicolodi** [comment]
I suspect that what is happening is that the same build directory is used to build the project on two different systems. Meson does not have a way to detect that the world changed under his feet and thus happily tries to compile the project on one system with the project configuration computed on the other. I think that the easy answer is: do not do that. Sharing the same building directory between different systems is not supported.
