### ISSUE TITLE
Unable to use Meson due to Kaspersky antivirus.

### ISSUE THREAD

**Issue by yukraya** [mesonbuild/meson#13893]
**Issue**
“sanitycheckcpp.exe” is detected as malware by Kaspersky Antivirus.

(note that I use CLion IDE)

**To Reproduce**
- Launch CLion IDE
- Create a C++ Meson project

**System parameters**
* Windows 11
* Python 3.13.0
* Meson 1.6.0

(I don't know if Clion uses an embedded version of Python and Meson)

**Screenshots**

![Capture d’écran 2024-11-11 111313](https://github.com/user-attachments/assets/40530841-6cd3-4c66-a111-6c42fca9682e)

![Capture d’écran 2024-11-11 111335](https://github.com/user-attachments/assets/ed1d8092-007d-418e-83b8-19ff1f0d30f7)

![Capture d’écran 2024-11-11 111456](https://github.com/user-attachments/assets/750e0581-04dc-43e8-af1a-b479b127ce62)

**Comment by dnicolodi** [comment]
I'm quite sure this is a Kaspersky Antivirus issue and not a Meson issue.

**Comment by yukraya** [comment]
@dnicolodi 

I think so too. However, after some research, it seems that sanitycheckcpp is regularly detected as malware by antiviruses. We should report that massively.

**Comment by eli-schwartz** [comment]
https://github.com/mesonbuild/meson/blob/b3f9b9dc06fcd6c0a3070380b42e0ab5fd6c1226/mesonbuild/compilers/cpp.py#L89-L91

https://github.com/mesonbuild/meson/blob/b3f9b9dc06fcd6c0a3070380b42e0ab5fd6c1226/mesonbuild/compilers/detect.py#L104-L111

We generate this source file snippet in the build directory, inside meson-private/

Antiviruses are often known for being on a hair-trigger with regard to executables that appear in say `%TEMP%` and this is why we create them inside the current working directory instead. I don't know what Kaspersky is freaking out about. Presumably adding an exclusion for your current coding directory would help though -- one is generally quite confident that a git clone of some open source codebase which may even be self-written, doesn't have malware...


> I think so too. However, after some research, it seems that sanitycheckcpp is regularly detected as malware by antiviruses. We should report that massively.

This is best reported by an antivirus customer. I've never gotten that erroneous malware detection on Linux :) and I don't think they would accept a report from me based on hearsay.

**Comment by bonzini** [comment]
This seems to be a very common false positive, see for example https://forum.kaspersky.com/topic/c-code-generates-vhotrojanwin32convagentgen-30460/. There's not much that meson developers can do.
