### ISSUE TITLE
Add support for Visual Studio 2017

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#1390]
We should also add auto-detection of the backend when you pass `--backend=vs` instead of always requiring the full name, such as `--backend=vs2015`, etc.

**Comment by nioncode** [comment]
I wonder how to detect which Visual Studio version is installed.
Do you have any pointers for that? Seems like they changed some stuff regarding easy detection through registry keys for vs2017: https://developercommunity.visualstudio.com/content/problem/2813/cant-find-registry-entries-for-visual-studio-2017.html

In my opinion, people usually know which version they want to compile for, so autodetection is not necessary. We might be able to parse the version number from the output of `cl.exe`, but I don't know if this can easily be mapped to a VS version.

**Comment by nirbheek** [comment]
Starting from at least VS 2015[1], the `VisualStudioVersion` environment variable should be a good way to figure that out. For VS 2010, we can require `--backend=vs2010`[2]. We already require users to setup the environment before calling `meson`, so we can rely on this.

1.  No idea about 2013 and we don't have a backend for it anyway
2.  ... or we could check for the presence of `VS100COMNTOOLS` and `VSINSTALLDIR` and the absence of `VisualStudioVersion`, but I say screw that because it's been 7+ years since VS2010 came out
