### ISSUE TITLE
meson build files generated from crates cannot be sufficiently customized

### ISSUE THREAD

**Issue by inklesspen** [mesonbuild/meson#13922]
I'm trying to get a barebones Rust-based Python extension module to build with meson. (I can of course build it with cargo, and therefore with maturin or setuptools-rust, but I prefer using meson-python when possible.)

Currently I'm stuck on configuring the build for a transitive dependency, [target-lexicon](https://crates.io/crates/target-lexicon/0.12.16), which is used by [pyo3](https://crates.io/crates/pyo3). This is one of the many crates which uses a `build.rs` file; in this crate, the build.rs file generates a source file, and optionally outputs an extra feature flag to enable. The logic to generate this source file is sufficiently complicated that it seemed to me that the simplest thing to do here would be to actually compile and run the `build.rs` file.

I'm running the unreleased dev version of meson (current commit is 33376efc4c1daf53c5509ea5fa7611b18d10416a).

The autogenerated meson.build file for this dependency looks like this:

```meson
project(
  'target-lexicon',
  'rust',
  version : '0.12.16',
  meson_version : '>= 1.7.0',
  default_options : ['rust_std=2018'],
  license : 'Apache-2.0 WITH LLVM-exception'
)
rust = import('rust')
message(
  'Enabled features:',
  ['default']
)
system_deps_args = []
extra_args = []
extra_deps = []
fs = import('fs')
if fs.is_dir('meson')
  subdir('meson')
endif
features_args = ['--cfg', 'feature="default"']
lib = static_library(
  'target_lexicon',
  'src/lib.rs',
  dependencies : [extra_deps],
  rust_dependency_map : {},
  rust_args : [features_args, extra_args, system_deps_args]
)
dep = declare_dependency(
  link_with : lib,
  variables : {'features' : 'default'}
)
meson.override_dependency('target-lexicon-0.12-rs', dep)
```

So I added a `subprojects/target-lexicon-0.12.16/meson/meson.build` file, with these contents:

```meson
rustc = find_program('rustc')
rustc_info = run_command(rustc, '-vV', check: true).stdout().splitlines()
target_triple = ''
foreach info_line : rustc_info
    if info_line.startswith('host')
        target_triple = info_line.split(':')[1].strip()
        break
    endif
endforeach
build_rs = executable(
    'build_script_build',
    [
        '../build.rs',
        '../src/data_model.rs',
        '../src/triple.rs',
        '../src/targets.rs',
    ],
)
build_output = custom_target(
    'host.rs',
    command: [build_rs],
    output: 'host.rs',
    env: {
        'OUT_DIR': meson.current_build_dir(),
        'TARGET': target_triple,
        'RUSTC': rustc.full_path(),
    },
)
```

This does build a `host.rs` file with the same contents that cargo would. However, I can't figure out any means to add the custom_tgt as a source file in the `lib` target. Additionally, since `features_args` is defined after the `subdir('meson')` call, I cannot augment it with the `'feature="rust_1_40"'` which the build script will normally define.

Perhaps in a scenario like this, the best thing to do would be to actually copy the generated meson.build file into the subprojects directory, create a cargo wrap, and make the meson.build do the right thing there. However, I have been unable to find any command to do this, or any guidance on doing it manually.

Advice more than welcome.

**Comment by eli-schwartz** [comment]
> This does build a `host.rs` file with the same contents that cargo would. However, I can't figure out any means to add the custom_tgt as a source file in the `lib` target.

This certainly looks like interesting functionality which would make sense to provide.

> Additionally, since `features_args` is defined after the `subdir('meson')` call, I cannot augment it with the `'feature="rust_1_40"'` which the build script will normally define.

I seem to recall this was the reason why `extra_args` was provided for extensibility though. Right?

> Perhaps in a scenario like this, the best thing to do would be to actually copy the generated meson.build file into the subprojects directory, create a cargo wrap, and make the meson.build do the right thing there. However, I have been unable to find any command to do this, or any guidance on doing it manually.

Generically speaking: https://mesonbuild.com/Wrap-dependency-system-manual.html

You would create a wrap-file which specifies the url to the crate as a source_url, and you would use the `patch_directory` key to define where, in subprojects/packagefiles/, your overridden meson.build is stored.

The cargo endpoint to download `target-lexicon-0.12.16.tar.gz` is: https://crates.io/api/v1/crates/target-lexicon/0.12.16/download

So:
```
[wrap-file]
directory = target-lexicon-0.12.16
source_url = https://crates.io/api/v1/crates/target-lexicon/0.12.16/download
source_filename = target-lexicon-0.12.16.tar.gz
source_hash = 0123deadbeef0123
patch_directory = target-lexicon

[provide]
dependency_names = target-lexicon-0.12-rs
```

IIRC it is considered desirable by the maintainers of our rust support to add a `meson wrap` command capable of stubbing in crates.io wrap-file entries for you (and creating an initial meson.build that you can tweak).

**Comment by inklesspen** [comment]
True, I could put the feature arg in extra_args, or indeed in system_deps_args. But it feels a bit hacky to do so.

On the subject of "interesting functionality it would make sense to provide", it would be neat if there were some way to obtain the ["target tuple"](https://doc.rust-lang.org/stable/rustc/platform-support.html) (such as `aarch64-apple-darwin`, `x86_64-unknown-linux-gnu`) either from the rust compiler object or (more ideally) from the target_machine object.

**Comment by inklesspen** [comment]
Well, I managed to get the wrap file working, and a fully hand-massaged meson.build file for the library, but unfortunately have run up against the #10030 issue. I guess this just isn't going to work unless either meson allows configuring env variables for rust targets or rust implements https://github.com/rust-lang/rfcs/pull/2794.
