### ISSUE TITLE
Cannot find HDF5 on Linux

### ISSUE THREAD

**Issue by subhacom** [mesonbuild/meson#13985]
**Describe the bug**
`meson setup` fails on Ubuntu/conda environment when there is a dependency on HDF5.
```
...
h5c++ found: YES (/home/subha/micromamba/envs/moose/bin/h5c++) 1.14.4
Run-time dependency HDF5 for cpp found: YES 1.14.4
...
... ERROR: Could not get config-tool variable and no default provided for <HDF5ConfigToolDependency hdf5: True>
```

**To Reproduce**
Relevant section of `meson.build`:
```
use_hdf5 = get_option('use_hdf5')
if use_hdf5
  hdf5_dep = dependency('hdf5', version: '>=1.8')
  add_global_arguments('-DUSE_HDF5', language: ['c', 'cpp'])
  add_global_arguments('-DH5_BUILT_AS_DYNAMIC_LIB', language: ['c', 'cpp'])  # to fix this issue: https://github.com/conda-forge/hdf5-feedstock/issues/58
else
  hdf5_dep = []
endif
```
Full build log here: https://github.com/subhacom/moose-core/actions/runs/12210096794/job/34065761090

Similar issues have been reported before, but are either open or the solutions do not work in this case:
1. https://github.com/mesonbuild/meson/issues/10859: this went away with cmake >=3.4 but I have cmake version 3.31.1
3. If `method: 'cmake'` argument is passed to `dependency('hdf5', version: '>=1.8')`, then meson complains about `cmake`:
    `ERROR: Unsupported detection method: cmake, allowed methods are auto, config-tool and pkg-config`
4. If `method: 'pkg-config'` argument is passed to `dependency('hdf5', version: '>=1.8')` it throws a different error:
    ```
    Run-time dependency HDF5 found: NO (tried pkgconfig and pkgconfig)

    ... ERROR: Dependency "hdf5" not found, tried pkgconfig and pkgconfig
   ```
5. This occurs when using micromamba/conda env with HDF5 installed from conda-forge, as well as with system-wide installation using `sudo apt-get install libhdf5-dev`.

**Expected behavior**
It should create the configuration without error. The same build works on Windows and MacOSX.

**system parameters**
- Python 3.12.7
- Meson Version: 1.6.0
- Build type: native build
- C compiler for the host machine: cc (gcc 11.4.0 "cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
- C linker for the host machine: cc ld.bfd 2.38
- C++ compiler for the host machine: c++ (gcc 11.4.0 "c++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
- C++ linker for the host machine: c++ ld.bfd 2.38
- Host machine cpu family: x86_64
- Host machine cpu: x86_64
- Found pkg-config: YES
- h5cc found: YES (/usr/bin/h5cc) 1.10.7
- Run-time dependency HDF5 found: YES 1.10.7

**Comment by eli-schwartz** [comment]
> **Describe the bug** `meson setup` fails on Ubuntu/conda environment when there is a dependency on HDF5.
> 
> ```
> ...
> h5c++ found: YES (/home/subha/micromamba/envs/moose/bin/h5c++) 1.14.4
> Run-time dependency HDF5 for cpp found: YES 1.14.4
> ...
> ... ERROR: Could not get config-tool variable and no default provided for <HDF5ConfigToolDependency hdf5: True>
> ```

Missing the line number before the word "ERROR".


> **To Reproduce** Relevant section of `meson.build`:
> 
> ```
> use_hdf5 = get_option('use_hdf5')
> if use_hdf5
>   hdf5_dep = dependency('hdf5', version: '>=1.8')
>   add_global_arguments('-DUSE_HDF5', language: ['c', 'cpp'])
>   add_global_arguments('-DH5_BUILT_AS_DYNAMIC_LIB', language: ['c', 'cpp'])  # to fix this issue: https://github.com/conda-forge/hdf5-feedstock/issues/58
> else
>   hdf5_dep = []
> endif
> ```


The relevant section is actually pointed to by the line number: https://github.com/subhacom/moose-core/blob/fd6cb7fe759dd6a709294366e34fbf905eb83530/builtins/meson.build#L35

```meson
if use_hdf5
  include_directories += hdf5_dep.get_variable(pkgconfig: 'includedir')
endif
```

dep.get_variable() has been told how to retrieve the includedir for a pkg-config dependency, but not how to retrieve the includedir when using h5cc.

**Comment by eli-schwartz** [comment]
```meson
include_directories = ['../external/fmt/include']
if use_hdf5
  include_directories += hdf5_dep.get_variable(pkgconfig: 'includedir')
endif
builtins_lib = static_library('builtins', builtins_src, include_directories: include_directories)
```

Just as a matter of curiosity... Why are you trying to get this variable at all? It seems like a much better idea to simply add hdf5_dep as as a dependency to this static library.

It's a static library and it uses hdf5. Static libraries don't and can't link to dynamic libraries -- adding a dependency means that ***when linking to*** the static library you also need to link to its recursive dependencies, namely hdf5.

The one place you use builtins_lib already depends on hdf5_dep for its own reasons, the dependency graph then merges both together. It will be linked to regardless, in other words.

Why manually reimplement the dependency interface via `get_variable(pkgconfig: 'includedir')`?

**Comment by subhacom** [comment]
Thank you! That fixed it. I think when I first switched from cmake to meson, there were compiler errors on HDF5 includes. I had just added the include directories as the next step.

**Comment by eli-schwartz** [comment]
Ok great, happy to help. :)

Note that if for some reason you find yourself in the future needing to only compile but not link (such as for a dependency that provides both a library and header inlines and you're only using inline functionality) you can use `dep.partial_dependency()` to grab just the compile args and includes in a tidy interface without the link parts. This is better than grabbing at private variables (but still inapplicable to most use cases).
