### ISSUE TITLE
DEF file not passed properly to Clang + LLD-LINK for MSVC targets

### ISSUE THREAD

**Issue by lhmouse** [mesonbuild/meson#13988]
### Describe the bug

For quite some time, with Visual Studio Installer, it is possible to install a Clang which targets MSVC. This Clang invokes LINK (the Microsoft linker) by default, which can be changed to LLD-LINK by passing `-fuse-ld=lld`. This setup allows building something with Unix-ish command-line options, but to produce libraries that are to be used with the Microsoft linker.

However, I ran into an issue about DEF files today: https://github.com/lhmouse/mcfgthread/actions/runs/12235206293/job/34126005390#step:5:136

Conventionally, when GCC or Clang with a MinGW target is used, DEF files are directly passed to the linker, which doesn't work in this setup. For LINK and LLD-LINK, DEF files should by passed with the `/DEF:` option.

I actually had a talk with @mstorsjo who is a maintainer of llvm-project. My opinion was that this is a Clang bug; because Clang is invoking a linker that expects MSVC-style options, then as a compiler driver it should translate the DEF file argument accordingly. His opinion was that the DEF file should be passed with `-Wl,/DEF:`.

### To Reproduce

meson.build
```meson
project('my', 'c')
shared_library('my',
    sources: [ 'my.c' ],
    vs_module_defs: 'my.def')
```

meson.native.clang
```ini
[binaries]
c = 'clang'
c_ld = 'lld'
```

my.c
```c
int foo(int a) { return a + 1; }
```

my.def
```def
EXPORTS
foo
```

In an _x64 Native Tools Command Prompt for VS2022_, this can be configured and built with
```text
meson setup --native-file meson.native.clang build
cd build
ninja
```
which fails with an error
```text
[1/1] Linking target my.dll
FAILED: my.dll my.pdb
"clang"  -Wl,/OUT:my.dll my.dll.p/my.c.obj "-Wl,/nologo" "-fuse-ld=lld" "-Wl,/DEBUG" "-Wl,/PDB:my.pdb" "-Wl,/DLL" "..\my.def" "-Wl,/IMPLIB:my.lib" "-lkernel32" "-luser32" "-lgdi32" "-lwinspool" "-lshell32" "-lole32" "-loleaut32" "-luuid" "-lcomdlg32" "-ladvapi32"
lld-link: error: ..\my.def: unknown file type
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

### Expected behavior

_my.def_ should be passed like `"-Wl,/DEF:..\my.def"`.

### system parameters

* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
    Negative.
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
    Windows 11 24H2
* what Python version are you using e.g. 3.8.0
    3.12.7
* what `meson --version`
    1.6.0
* what `ninja --version` if it's a Ninja build
    1.12.1

**Comment by mstorsjo** [comment]
> I actually had a talk with @mstorsjo who is a maintainer of llvm-project. My opinion was that this is a Clang bug; because Clang is invoking a linker that expects MSVC-style options, then as a compiler driver it should translate the DEF file argument accordingly. His opinion was that the DEF file should be passed with `-Wl,/DEF:`.

To add some nuance to this opinion here; I guess one could argue that Clang could do this handling as well - such a patch to Clang probably would be welcome too. There are many sharp corners around running Clang in MSVC mode via the GNU style `clang` interface, in particular with respect to linking.

But the fact that Meson already is invoking Clang with options like `-Wl,/OUT:my.dll` indicates that Meson is fully aware that there's a MS link.exe style linker being invoked - so that should extend to how `.def` files are handled as well.

**Comment by dcbaker** [comment]
> There are many sharp corners around running Clang in MSVC mode via the GNU style clang interface, in particular with respect to linking. 

This applies to Meson as well. We don't regularly test using the GNU compatible interface on Windows, and no one has (to my knowledge) ever done a ton of work to make it happen, as we generally expect that you'll use clang-cl. 

Looking more closely at what's going on here, it looks like when I split the compilers and linkers into two separate classes that are composed the def file coverage got left in the compiler instead of moving to the linker, so we special case having an MSVC compatible linker in the clang compiler. That should be fixed.

I don't have a Windows machine handy, but I'd be happy to review patches.

**Comment by lhmouse** [comment]
> > There are many sharp corners around running Clang in MSVC mode via the GNU style clang interface, in particular with respect to linking.
> 
> This applies to Meson as well. We don't regularly test using the GNU compatible interface on Windows, and no one has (to my knowledge) ever done a ton of work to make it happen, as we generally expect that you'll use clang-cl.

The reason for invoking _clang_ instead of _clang-cl_ is that there are a lot of options that are not supported by clang-cl:

```meson
    cc.get_supported_arguments(
      '-masm=intel', '-msse2', '-mfpmath=sse', '-mcmodel=small',
      '-fno-stack-protector', '-fstrict-aliasing', '-ffast-math', '-fno-ident',
      '-fno-omit-frame-pointer', '-fmerge-all-constants',
      '-Werror=conversion', '-Werror=sign-compare', '-Werror=sign-conversion',
      '-Werror=write-strings', '-Werror=return-type', '-Werror=double-promotion',
      '-Wmissing-declarations', '-Wswitch-enum', '-Wmissing-field-initializers',
      '-Wsuggest-attribute=noreturn', '-Wshadow', '-Wunused-function',
      '-Wunused-label', '-Wunused-local-typedefs', '-Wunused-but-set-variable',
      '-Wunused-but-set-parameter', '-Wunused-const-variable',
      '-Wno-unused-command-line-argument', '-Wno-dll-attribute-on-redeclaration',
      '-Wno-dynamic-exception-spec'),
```

And the reason for invoking _lld-link_ instead of _link_ is that the Microsoft linker does not support `-kill-at`.

> Looking more closely at what's going on here, it looks like when I split the compilers and linkers into two separate classes that are composed the def file coverage got left in the compiler instead of moving to the linker, so we special case having an MSVC compatible linker in the clang compiler. That should be fixed.
> 
> I don't have a Windows machine handy, but I'd be happy to review patches.

For this setup, it seems that `meson.get_compiler('c').get_linker_id()` returns `"link"`...?

I think relevant code is around https://github.com/mesonbuild/meson/blob/8578a995ae45ff737e25b8ff9d8ab0abe8d3b64c/mesonbuild/compilers/mixins/clang.py#L138 but certainly this needs some debugging.

**Comment by dcbaker** [comment]
That `isinstance` is wrong, now that I look at it again. It should be looking for a `VisualStudioLikeLinkerMixin`, or it needs to look for both `MSVCDynamicLinker` and `ClangCLDynamicLinker` (yeah, the name of that one is weird)

**Comment by lhmouse** [comment]
> That `isinstance` is wrong, now that I look at it again. It should be looking for a `VisualStudioLikeLinkerMixin`, or it needs to look for both `MSVCDynamicLinker` and `ClangCLDynamicLinker` (yeah, the name of that one is weird). Otherwise it only checks for link, and not lld-link

Thanks, both work for me.

```diff
diff --git a/mesonbuild/compilers/mixins/clang.py b/mesonbuild/compilers/mixins/clang.py
index a0d3d5ffb..41b35c041 100644
--- a/mesonbuild/compilers/mixins/clang.py
+++ b/mesonbuild/compilers/mixins/clang.py
@@ -135,7 +135,7 @@ class ClangCompiler(GnuLikeCompiler):
             return []
 
     def gen_vs_module_defs_args(self, defsfile: str) -> T.List[str]:
-        if isinstance(self.linker, (MSVCDynamicLinker)):
+        if isinstance(self.linker, (ClangClDynamicLinker, MSVCDynamicLinker)):
             # With MSVC, DLLs only export symbols that are explicitly exported,
             # so if a module defs file is specified, we use that to export symbols
             return ['-Wl,/DEF:' + defsfile]
```
