### ISSUE TITLE
[RFE] command to list all dependencies

### ISSUE THREAD

**Issue by solomoncyj** [mesonbuild/meson#14000]
**Describe the bug**
ommand to list all dependencies

**To Reproduce**

**Expected behavior**
the command will list all dependencies and version constrains, if applicable

**Comment by eli-schwartz** [comment]
#9541 
#985

In the first linked bug, this is discussed:
```
meson introspect --dependencies meson.build
```

**Comment by eli-schwartz** [comment]
Duplicate of #9541
