### ISSUE TITLE
Query run target in build file

### ISSUE THREAD

**Issue by sammyj85** [mesonbuild/meson#14042]
Is there a way to query which run target is being used from inside the build file?

https://mesonbuild.com/Run-targets.html

The run target is set up with the `run_target()` function with a name (possibly with multiple run targets). **Is there a way to create an if condition to check which target is being run?**

`run_target()` also does allow environment variables which are set to be passed in, which may have been an alternative way to do the same thing, but the there seems to be no way for Meson to query what environment variables are set (https://github.com/mesonbuild/meson/issues/9).

**Comment by eli-schwartz** [comment]
I don't really understand what you're asking to do. `meson setup` doesn't run `run_target()`, it just creates a ninja rule.

There's nothing to check and no location from which to check it. When you run `ninja foo-target`, the command that is run is whatever command was defined for foo-target, not the one defined for bar-target.

**Comment by sammyj85** [comment]
Thanks, quite right... with being several layers deep in meson calling a shell script which calls meson (etc), under the confusion it turns out this is a non-issue. Closing.
