### ISSUE TITLE
fs.name('@OUTPUT@') doesn't work

### ISSUE THREAD

**Issue by stsp** [mesonbuild/meson#14055]
**Describe the bug**

`fs.name('@OUTPUT@')` in custom_target()
results in full path, instead of just the name.
It seems, the expansion of `@OUTPUT@`
happens too late. So `fs.name()` first returns
`@OUTPUT@` as is, and only then the expansion
happens.

Is there work-around to strip the dir from
`@OUTPUT@`?

**Comment by eli-schwartz** [comment]
The `@OUTPUT@` is a parameter to "fs.name", and fs.name is a parameter to custom_target.

Hence fs.name canno know internal details of custom_target.

You can simply write the same string in `output: ...` and in wherever you wanted to use `@OUTPUT@`. In some cases, the `output:` kwarg contains e.g. `@PLAINNAME@` or `@BASENAME@`, which should work in both places already.
