### ISSUE TITLE
Don't strip rpaths set by user

### ISSUE THREAD

**Issue by TingPing** [mesonbuild/meson#1411]
Various projects can install libraries into a private directory and use rpath yet these are stripped.

**Comment by nirbheek** [comment]
Specifically, this is a common pattern in GNOME:

```console
$ readelf -a `which gnome-calculator` | grep -e PATH
 0x000000000000000f (RPATH)              Library rpath: [/usr/lib64/gnome-calculator]
$ readelf -a `which gnome-builder` | grep -e PATH
 0x000000000000000f (RPATH)              Library rpath: [/usr/lib64/gnome-builder:/usr/lib64/gnome-builder/]
$ readelf -a `which evolution` | grep -e PATH
 0x000000000000000f (RPATH)              Library rpath: [/usr/lib64/evolution]
```

And so on. Basically almost every GNOME application uses this.

**Comment by nirbheek** [comment]
During install in the `depfixer.py` script, we should only strip rpaths that lead to our build directory. I think this is doable.

**Comment by nirbheek** [comment]
Nvm, people can just use the `install_rpath:` keyword argument.

**Comment by dankegel** [comment]
Probably want to reopen this issue.  install_rpath is not helpful when consuming .pc files that need to specify an rpath.
