### ISSUE TITLE
libstatic.a is generated instead of static.lib on vs2015 (tested on current master)

### ISSUE THREAD

**Issue by dyu** [mesonbuild/meson#1412]
To reproduce:
https://github.com/dyu/cpp-build-example

Works on linux but fails in windows.

The ```call``` is from meson's appveyor, which is the same environment I have on my other laptop.
```
git clone https://github.com/dyu/cpp-build-example.git
call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64
mkdir build
cd build
meson ..
ninja
```

**Comment by nirbheek** [comment]
This is on purpose. Pasting the reasoning here [from the source](https://github.com/mesonbuild/meson/blob/master/mesonbuild/build.py#L1019):

> By default a static library is named `libfoo.a` even on Windows because MSVC does not have a consistent convention for what static libraries are called. The MSVC CRT uses `libfoo.lib` syntax but nothing else uses it and GCC only looks for static libraries called `foo.lib` and `libfoo.a`. However, we cannot use `foo.lib` because that's the same as the import library. Using `libfoo.a` is ok because people using MSVC always pass the library filename while linking anyway.

If you really need the static library to be named `static.lib`, you can set the `name_suffix:` and `name_prefix:` keyword arguments like so:

```
static_library('name', 'source1.c', 'source2.c', ...,
  ...,
  name_prefix : '',
  name_suffix : 'lib')
```

But beware that you cannot have a shared library with the same name in that case.

**Comment by dyu** [comment]
@nirbheek Ok.  I assumed that was what caused the build to fail.  So I guess it is something else.

Here's my output from win 8.1:
```
[7/13] Static linking library libstatic.a
LINK : warning LNK4044: unrecognized option '/DEBUG'; ignored
LINK : warning LNK4044: unrecognized option '/PDB:libstatic.pdb'; ignored
[8/13] Linking target executable.exe
FAILED: executable.exe
link @executable.exe.rsp
LINK : fatal error LNK1104: cannot open file 'shared.lib'
[11/13] Compiling cpp object gtest@sta/src_gtest-all.cc.obj
ninja: build stopped: subcommand failed.
```

**Comment by nirbheek** [comment]
You are not exporting any symbols in your shared library with [`__declspec(dllexport)`](https://msdn.microsoft.com/en-us/library/aa271769(v=vs.60).aspx) in the prototype or the `vs_module_defs:` keyword argument.

As a result, the DLL has no symbols and MSVC does not create an import library (`shared.lib`) for it so you can't link to it.

**Comment by dyu** [comment]
I updated the repo and converted it to to static (https://github.com/dyu/cpp-build-example/commit/628106eb532c2179df58481e13ea3f4e56f6c652)

Recompiled on linux, it works fine.

On windows here's the new error:
```
[6/13] Static linking library libstatic.a
LINK : warning LNK4044: unrecognized option '/DEBUG'; ignored
LINK : warning LNK4044: unrecognized option '/PDB:libstatic.pdb'; ignored
[8/13] Linking target executable.exe
FAILED: executable.exe
link @executable.exe.rsp
LINK : fatal error LNK1104: cannot open file 'static.lib'
[11/13] Compiling cpp object gtest@sta/src_gtest-all.cc.obj
ninja: build stopped: subcommand failed.
```

**Comment by dyu** [comment]
Ignore the last post (commit fail)
Here it is https://github.com/dyu/cpp-build-example/commit/f4b10831b4c48e25d1d0dae00c55f6501a33a9d1

I'm not able to get executable.exe but it errors when run on windows (as usual works on linux).

**Comment by nirbheek** [comment]
What's the error?

**Comment by dyu** [comment]
Launching the executable, a popup comes out.
```
The application was unable to start correctly (0xc000007b)
```

Looks like an invalid executable being generated.

I've tried the same example with [bfg9000](https://github.com/jimporter/bfg9000) (also a cross-platform python-based ninja generator)
```
project('hello', '1.0')

static_inc = header_directory('src/static/main', include='*.h')
shared_inc = header_directory('src/shared/main', include='*.h')

static_lib = static_library('static', files=['src/static/main/greeting.cpp'])
shared_lib = static_library('shared', files=['src/shared/main/add.cpp', 'src/shared/main/multiply.cpp'])

executable = executable('executable', 
                        files=['src/executable/main/main.cpp'],
                        includes=[static_inc, shared_inc],
                        libs=[static_lib, shared_lib])

default(executable)
```
With bfg9000, the binaries run fine under windows and linux.

**Comment by dyu** [comment]
Runs fine on windows with:
```
meson .. --buildtype release
```
