### ISSUE TITLE
Add configuration.setif() method

### ISSUE THREAD

**Issue by ssssam** [mesonbuild/meson#1424]
Currently a configuration_data object allows me to set a variable to a value in various useful ways. What it doesn't allow is for me to set the variable conditionally.

Currently I have to do this sort of thing ...

```
if exempi.found() conf.set('HAVE_EXEMPI', 1) endif
if unicode_library_name == 'unistring' conf.set('HAVE_LIBUNISTRING', 1) endif
```

... or this ...

```
if exempi.found()
    conf.set('HAVE_EXEMPI', 1)
endif
if unicode_library_name == 'unistring'
    conf.set('HAVE_LIBUNISTRING', 1)
endif
```

One is ugly and the other is verbose. This project has 20 or so flags that are used with #ifdef so having a prettier syntax would make quite a difference.

How about adding conf.setif() so I can do this ...

```
conf.setif('HAVE_LIBUNISTRING', unicode_library_name == 'unistring')
```

The value should be set to 1, as these defines all used with #if or #ifdef.

Maybe it's a little weird to have the condition as the second parameter, but it helps alignment a lot to have the variable name as the 1st parameter.

**Comment by nirbheek** [comment]
Doesn't this already do what you need?

```meson
conf.set('HAVE_EXEMPI', exempi.found())
```

This will create `#define HAVE_EXEMPI` if it is found, and not define it at all if it wasn't found. You should always be doing `#ifdef` for macro checks instead of `#if`.

**Comment by ssssam** [comment]
Aha, maybe the problem is there are a couple of uses of #if that are breaking things .. will test

**Comment by ssssam** [comment]
OK, there are a lot of places where #if is used where #ifdef should be used instead. I guess that's why I thought this was a missing feature. I'm happy to convert them all to #ifdef rather than adding a new function though if that's the established convention.

**Comment by tp-m** [comment]
I think .set() behaves as you requested, but there's also a set10() that will `#define FOO 0` in the case of `false` instead of leaving it undefined.

**Comment by nirbheek** [comment]
@ssssam Your changes in https://github.com/GNOME/tracker/commit/47adc7cdedf2fcfbd42ffc9b4dd13062617a1d19 are incorrect/incomplete. `configure.ac` sets those variables to `0` if not found and `1` if found. It's probably best to just use `set10()` here for compatibility with the existing build system.

**Comment by ssssam** [comment]
Right. This is pretty tricky to solve because some variables use #ifdef (thus we need to use `set`) and others use #if (thus they need use `set10`), and there's no single place where you can get a list of which ones are which!

I guess you're right that what I did yesterday will break things for the Autotools build instructions though. I'll try reverting that commit and setting specifically the variables that are used with `#if` with `set10`. Of course the others must still use `set` because they are tested for using #ifdef.

**Comment by nirbheek** [comment]
Codebases should never mix #if and #ifdef for feature-existence checks. This might be a good time to do a cleanup if you want, but I would do it in two separate commits: one that adds meson support, the other that makes #if vs #ifdef more consistent. Otherwise the reason why it's done will get misconstrued. :)

**Comment by ssssam** [comment]
Is that convention documented somewhere? It seems logical but nice if there's somewhere I can link to. And I guess part of this is C's fault for not providing #elifdef :-)

**Comment by nirbheek** [comment]
There's no documented convention. It's just bad practice to mix them because you then have to remember which macro will be not-found when it's `0` vs being not-found when it's not defined.

**Comment by tp-m** [comment]
Note that
```
#if FOO_BAR
#endif
```
will work fine if `FOO_BAR` is not defined, it will be assumed that `FOO_BAR` is 0 in that case. There's some compiler warning you can enable to catch these things.
