### ISSUE TITLE
When using link_with, transitive pthread dependency is ignored

### ISSUE THREAD

**Issue by johnjwang** [mesonbuild/meson#1426]
I'm building a common library which depends on math and thread libraries. Linking this library with an executable using `link_with : [common_lib]` should pick up both these transitive dependencies. However, the thread dependency is not picked up.

I'm using meson 0.38.1. A snippet of my meson.build file is reproduced below, with filenames replaced by "..." for clarity.

```meson
cc = meson.get_compiler('c')
m_dep = cc.find_library('m', required : false)
thread_dep = dependency('threads')

inc = include_directories(...)

common_src = [...]
common_lib = static_library('common',
    common_src,
    include_directories : inc,
    dependencies : [m_dep, thread_dep])

executable('foo',
    [...],
    include_directories: inc,
    link_with : [common_lib],
    install : true)
```

The resulting compile command contains `-lm` but not `-pthread`.

**Comment by TingPing** [comment]
You probably want:

```meson
cc = meson.get_compiler('c')
m_dep = cc.find_library('m', required : false)
thread_dep = dependency('threads')

inc = include_directories(...)

common_src = [...]
common_lib = static_library('common',
    common_src,
    include_directories : inc,
    dependencies : [m_dep, thread_dep]);

common_dep = declare_dependency(
  include_directories: inc,
  dependencies: [m_dep, thread_dep],
  link_with: common_lib)

executable('foo',
    [...],
    dependencies: common_dep,
    install : true)
```

**Comment by johnjwang** [comment]
This does work, but why doesn't the other form work? It does seem to be a bug because the behavior of `dependency('threads')` is inconsistent with other dependencies.

**Comment by nirbheek** [comment]
This is a known bug. The way we handle transitive dependencies isn't consistent right now. You should use the `declare_dependency()` format for now.

**Comment by nirbheek** [comment]
Fixed with https://github.com/mesonbuild/meson/pull/3895.
