### ISSUE TITLE
has_header should accept internal dependencies

### ISSUE THREAD

**Issue by TingPing** [mesonbuild/meson#1430]
```meson
clang_include = include_directories(run_command(llvm_config, '--includedir').stdout().strip())

clang_dep = declare_dependency(
  include_directories: clang_include,
)

if not cc.has_header('clang-c/Index.h', dependencies: clang_dep)
  error('clang: Failed to find headers')
endif
```

```sh
Dependencies must be external dependencies
```

EDIT: Ok in this specific case `prefix` does work, but It still seems less clean.

**Comment by nirbheek** [comment]
How would that work? Internal dependencies are only available at build time and compiler checks are run at configure time.

**Comment by nirbheek** [comment]
In this particular case, you're actually misusing internal dependencies to refer to external headers aren't you?
