### ISSUE TITLE
on 64 bit host, cross compilation install libraries in "lib64" instead of  "lib"

### ISSUE THREAD

**Issue by fabio-porcedda** [mesonbuild/meson#1433]
I use a x86_64 machine to cross compile for a 32bit mips platform.

My "cross_file.txt" is:

```ini
c = '/opt/br_mips-2013.11/usr/bin/mips-linux-gcc'
cpp = '/opt/br_mips-2013.11/usr/bin/mips-linux-g++'
ar = '/opt/br_mips-2013.11/usr/bin/mips-linux-ar'
strip = '/opt/br_mips-2013.11/usr/bin/mips-linux-strip'

[host_machine]
system = 'linux'
cpu_family = 'mips'
cpu = 'mips'
endian = 'big'
```

Unfortunately when i run the "ninja install" target the libraries are installed in the "lib64" directory instead of the "lib" directory.

I've checked the "meson_install.py" script but i didn't found any reference to the lib directory, what is the correct source file to check?

Thanks

**Comment by TingPing** [comment]
The problem is we check here: https://github.com/mesonbuild/meson/blob/98af711ca6f166bacf2b9c6e697026f5b323827a/mesonbuild/mesonlib.py#L315-L316

I have also encountered this issue when installing into jhbuild. So we need to look for `lib64` in the correct prefix.

**Comment by fabio-porcedda** [comment]
You are right, thanks for pointing it out, maybe we just need to check if is a cross_compile or not.

**Comment by fabio-porcedda** [comment]
In the meantime i will use a workaround using the "meson --libdir=lib" option.
