### ISSUE TITLE
Compd should have command lines for all the compilers

### ISSUE THREAD

**Issue by chergert** [mesonbuild/meson#1439]
I didn't see another bug that quite matched this request, so hopefully it's not a dup :)

What we need in Builder to improve our Vala support while running with the Meson build system is to get the compiler flags for `valac`. In particular, we're looking for those `--pkg gtk+-3.0 --pkg gio-2.0` type compiler flags.

We need these to prime `libvala` so that we can get relevant auto-completion results.

**Comment by jpakkane** [comment]
Ideally we should export those in the compdb automatically. If you go to a build dir with Vala code and do:

    ninja -t compdb vala_COMPILER

Does the output contain everything you need?

**Comment by chergert** [comment]
Most excellent, I think I can parse the flags out of that just fine!

**Comment by jpakkane** [comment]
Reopening, because the bug here is that we should generate that by default.
