### ISSUE TITLE
Recipes does not build on Windows

### ISSUE THREAD

**Issue by nacho** [mesonbuild/meson#1441]
Here is what I get when I try to build it:

```
C:\gtk-build\build\Win32\release\recipes\build>\gtk-build\tools\meson-0.38.1\meson.py ..
The Meson build system
Version: 0.38.1
Source dir: C:\gtk-build\build\Win32\release\recipes
Build dir: C:\gtk-build\build\Win32\release\recipes\build
Build type: native build
Project name: gnome-recipes
Native c compiler: cl (msvc 18.00.40629)
Build machine cpu family: x86
Build machine cpu: x86

Executing subproject libgd.

Project name: libgd
Native c compiler: cl (msvc 18.00.40629)
Found pkg-config: \gtk-build\gtk\Win32\release\bin\pkg-config.EXE (0.29.1)
Native dependency gtk+-3.0 found: YES 3.22.8
Library m found: YES
Native dependency glib-2.0 found: YES 2.51.4
WARNING: GLib compiled dependencies do not work reliably with
the current version of GLib. See the following upstream issue: https://bugzilla.gnome.org/show_bug.cgi?id=774368
Build targets in project: 3

Subproject libgd finished.
Dependency gnome-autoar-0 found: NO
Dependency gspell-1 found: NO
Dependency libcanberra found: NO
Native dependency gmodule-export-2.0 found: YES 2.51.4
Program list_to_c.py found: YES (C:\Python34\python.exe C:\gtk-build\build\Win32\release\recipes\src\list_to_c.py)
Program glib-mkenums found: YES (@PERL_PATH@ \gtk-build\gtk\Win32\release\bin\glib-mkenums)
Program gdbus-codegen found: YES (@PYTHON@ \gtk-build\gtk\Win32\release\bin\gdbus-codegen)
Program msgfmt found: YES (\gtk-build\gtk\Win32\release\bin\msgfmt.EXE)
Program tools/meson_post_install.py found: YES (C:\Python34\python.exe C:\gtk-build\build\Win32\release\recipes\tools/meson_post_install.py)
Build targets in project: 29

C:\gtk-build\build\Win32\release\recipes\build>ninja
[3/88] "Generating types.h with a meson_exe.py custom command."
FAILED: src/types.h
"C:\\Python34\\python.exe" "C:\\gtk-build\\tools\\meson-0.38.1\\meson.py" "--internal" "exe" "C:\\gtk-build\\build\\Win32\\release\\recipes\\build\\meson-private\\meson_exe_@PERL_PATH@_94f985194a9edbd2d462094ccc08fb2792b0afb6.dat"
Traceback (most recent call last):
  File "C:\\gtk-build\\tools\\meson-0.38.1\\meson.py", line 37, in <module>
    sys.exit(main())
  File "C:\\gtk-build\\tools\\meson-0.38.1\\meson.py", line 34, in main
    return mesonmain.run(launcher, sys.argv[1:])
  File "C:\gtk-build\tools\meson-0.38.1\mesonbuild\mesonmain.py", line 248, in run
    sys.exit(run_script_command(args[1:]))
  File "C:\gtk-build\tools\meson-0.38.1\mesonbuild\mesonmain.py", line 236, in run_script_command
    return cmdfunc(cmdargs)
  File "C:\gtk-build\tools\meson-0.38.1\mesonbuild\scripts\meson_exe.py", line 72, in run
    return run_exe(exe)
  File "C:\gtk-build\tools\meson-0.38.1\mesonbuild\scripts\meson_exe.py", line 55, in run_exe
    p, stdout, stderr = Popen_safe(cmd + exe.cmd_args, env=child_env, cwd=exe.workdir)
  File "C:\gtk-build\tools\meson-0.38.1\mesonbuild\mesonlib.py", line 496, in Popen_safe
    stderr=stderr, **kwargs)
  File "C:\Python34\lib\subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "C:\Python34\lib\subprocess.py", line 1114, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
[5/88] "Generating resources_ui_c with a custom command."
ninja: build stopped: subcommand failed.
```

**Comment by nacho** [comment]
Actually this seems the fault of the glib visual studio projects for not setting @PERL_PATH@ and @PYTHON@

**Comment by nacho** [comment]
This is the following problem I am encountering, any idea what this is about? I guess I need something special for gettext?

C:\gtk-build\build\Win32\release\recipes\build>ninja
[4/88] "Generating appdata with a custom command."
FAILED: data/org.gnome.Recipes.appdata.xml
"/gtk-build/gtk/Win32/release/bin/msgfmt.EXE" "--xml" "-d" "../po" "--template" "../data/appdata/org.gnome.Recipes.appdata.xml.in" "-o" "data/org.gnome.Recipes.appdata.xml"
/gtk-build/gtk/Win32/release/bin/msgfmt.EXE: cannot locate ITS rules for ../data/appdata/org.gnome.Recipes.appdata.xml.in
[6/88] "Generating types.h with a meson_exe.py custom command."
ninja: build stopped: subcommand failed.

**Comment by nacho** [comment]
Adding @fanc999 about the PERL_PATH and PYTHON issues.

**Comment by nacho** [comment]
For the its stuff I fixed it copying those files from the new gettext

**Comment by nacho** [comment]
Next topic, the include file is there but for some reason meson is not adding the include folder?

[1/79] Compiling c object tests/number@exe/number.c.obj
FAILED: tests/number@exe/number.c.obj
cl @tests/number@exe/number.c.obj.rsp
c:\gtk-build\gtk\win32\release\include\glib-2.0\glib\gi18n.h(23) : fatal error C1083: Cannot open include file: 'libintl.h': No such file or directory
[2/79] Compiling c object tests/ingredients@exe/ingredients-test.c.obj
FAILED: tests/ingredients@exe/ingredients-test.c.obj
cl @tests/ingredients@exe/ingredients-test.c.obj.rsp
c:\gtk-build\gtk\win32\release\include\glib-2.0\glib\gi18n.h(23) : fatal error C1083: Cannot open include file: 'libintl.h': No such file or directory
[3/79] Compiling c object tests/ids@exe/ids.c.obj
FAILED: tests/ids@exe/ids.c.obj
cl @tests/ids@exe/ids.c.obj.rsp
c:\gtk-build\gtk\win32\release\include\glib-2.0\glib\gi18n.h(23) : fatal error C1083: Cannot open include file: 'libintl.h': No such file or directory
ninja: build stopped: subcommand failed.

**Comment by TingPing** [comment]
I encountered that too, @nirbheek mentioned `INCLUDE` should be set the root include directory.

**Comment by nacho** [comment]
Bugs were reported to the specific modules. I am closing this.
