### ISSUE TITLE
cc.has_header('linux/foo.h') does not work with gcc

### ISSUE THREAD

**Issue by tp-m** [mesonbuild/meson#1458]
Meson checks for the existance of headers with something like (simplified):

```
#ifdef __has_include
 #if !__has_include(<linux/memfd.h>)
  #error "Header 'linux/memfd.h' could not be found"
 #endif
#endif
```

Problem is, that (unlike clang) current gcc/cpp versions expand the `linux` part here because `#define linux `, so they look for the header `1/memfd.h` and don't find it.

This is a [gcc/cpp bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80005) of course, but it stands to reason that knowing about this limitation with current version of gcc on Linux Meson should not check for the existance of headers differently in these cases, or work around it, e.g. by doing `#undef linux` (which will not fully work around the general issue of course, just one of the most common occurances).

**Comment by jpakkane** [comment]
Let's see what GCC devs say. This is serious enough that it might even make it into a distro patch.

**Comment by nirbheek** [comment]
Using the `__has_include("linux/memfd.h")` form doesn't trigger this bug, so maybe we could use that instead. The downside is that it will find that header if it's relative to the current directory and those listed with `-iquote` too.

Maybe we could use that form only with specific GCC versions that we know are buggy (which is all GCC versions right now).

**Comment by nirbheek** [comment]
Actually, it doesn't matter if we use the `<>` or `""` form because our compiler checks are run from a temporary directory anyway. It cannot find any headers in the source or builddir. Will open a PR to fix this.
