### ISSUE TITLE
Incorrect line/column numbers for certain types of parse errors

### ISSUE THREAD

**Issue by nelliezh** [mesonbuild/meson#1459]
With just the following in a meson.build file:

```meson
project('test', 'c')
executable('exe', 'test.c', foo:='bar')
```

Running meson reports the following output:
`Meson encountered an error in file meson.build, line 0, column 0:`
`Assignment target must be an id.`

Assignment target must be an id is right, but the line number and column number are wrong.

**Comment by nirbheek** [comment]
This is fixed with https://github.com/mesonbuild/meson/pull/1460.
