### ISSUE TITLE
Cannot build D unittests

### ISSUE THREAD

**Issue by russel** [mesonbuild/meson#1462]
D has mechanisms for putting unit tests in the code being tested, with there being two builds for any file, one for the application one for the tests. Given a single function factorial.d in a project, ignoring building it as a library, focussing only on building the test, I came up with the Meson file:
```
project('D Factorial', 'd')

factorial_test = executable('factorial_test', 'factorial.d', d_args: ['-unittest', '--main'])
test('test_factorial', factorial_test)
```
Sadly on executing the build I get:
```
|> ninja
[1/2] Compiling d object 'factorial_test@exe/factorial.d.o'
FAILED: factorial_test@exe/factorial.d.o 
ldc2  '-Ifactorial_test@exe' '-I.' '-I..' '-enable-color' '-wi' '-g' '-O0' '-unittest' '--main'  -of 'factorial_test@exe/factorial.d.o' -c ../factorial.d
Error: Output file 'factorial_test@exe/factorial.d.o' for module '__main' collides with previous module 'factorial'. See the -oq option
ninja: build stopped: subcommand failed.
```
I'm afraid I have no idea where to go with this. I am trying to transform a working SCons build to Meson.

**Comment by jpakkane** [comment]
If you run that compilation command manually, does it work? If not, what command line does work?

**Comment by russel** [comment]
Poster fail, sorry.

--main is a linker arg not a compiler arg, write a correct meson.build file and it all works.

The problem was the conflict between the "compile to create an object and then link to create an executable", versus the "compile and link in one go". I invariably use the latter when doing things manually and so the --main linker option is on the command line. It is though definitely a linker argument not a compiler argument so with -unittest in the d_args and --main in the link_args, all works fine.

Sorry for the noise.
