### ISSUE TITLE
Unable to use custom Qt

### ISSUE THREAD

**Issue by absmall** [mesonbuild/meson#1472]
According to a post on the mailing list:
https://groups.google.com/forum/#!topic/mesonbuild/7u4pYlzQj5A
It should:be possible to use a custom Qt by setting PKG_CONFIG_PATH and PATH

> The common approach is to set up multiple build directories, where each is configured to a specific qt installation. Like this:
> 
> mkdir qt51; cd qt51; PATH=/path/to/qt51/bin:$PATH meson .. <args>; cd ..
>mkdir qt52; cd qt52; PATH=/path/to/qt52/bin:$PATH meson .. <args>; cd ..
>mkdir qt53; cd qt53; PATH=/path/to/qt53/bin:$PATH meson .. <args>; cd ..
> 
> Then you can test any installation simply by running Ninja in the corresponding build dir.
> 
> This is a bit of work but you only need to set it up once per project. If that does not work, then please file a bug.

However I have Qt installed on my system, which provides .pc files, and a custom Qt that I want to use for this build which does not.

When the build is configured, it first tries pkg-config, and detects the system Qt module for all of the modules needed in the build that have a system version as well. I can't override pkg-config since I don't have any other .pc files to use. If I could, the fallback to qmake works correctly, but I can't get to that fallback.

**Comment by jpakkane** [comment]
If your Qt would ship with .pc files then it should work if you point PKG_CONFIG_PATH to those, they are scanned before system libraries.

If this is not the case the we should probably add some sort of way to override which dependency provider to use.

**Comment by nirbheek** [comment]
Related: https://github.com/mesonbuild/meson/issues/711.

However, as Jussi said, in your case you just need to set `PKG_CONFIG_PATH` to point to the directory containing your .pc files.

**Comment by absmall** [comment]
There are no .pc files in the Qt build. I'm not sure why, I can try to debug it sometime, but it's not just to stress-test meson, it's always been that way for this particular build.

We used qmake in the past (and still use qmake, but I'm hoping to switch to meson) so we didn't need .pc files. Possibly they were disabled on purpose at some point. But in any case, there do exist Qt builds like this.

The kwargs option mentioned in #711 sounds perfect for me.

**Comment by nirbheek** [comment]
For that use-case, you might want to set `PKG_CONFIG_PATH` to point to some empty directory and set `PATH` to point to the bin directory with `qmake` in it.

And yes, it would be good to fix #711 too. Would you like to work on a patch for that?

**Comment by absmall** [comment]
PKG_CONFIG_PATH just adds to the places to look for .pc files, it doesn't replace the default locations, and my system Qt ( which is a working Qt that I use for other projects, but not the one I want to use for this project) does provide .pc files in one of the default locations. So the build picks up those and uses the wrong Qt.

Yes, I can't say exactly when I'll have time to work on #711, but I will work on it sometime.

**Comment by nirbheek** [comment]
Ah, right. You need to set `PKG_CONFIG_LIBDIR` instead.
