### ISSUE TITLE
Errors out with 'Fallback variable xyz_dep does not exist in subproject' even though dep is optional

### ISSUE THREAD

**Issue by tp-m** [mesonbuild/meson#1474]
gstreamer-vaapi's `meson.build` has this snippet:
```
gstgl_dep = dependency('gstreamer-gl-1.0', version : gst_req,
  fallback : ['gst-plugins-bad', 'gstgl_dep'], required: false)
```

Now in the gst-plugins-bad module the variable `gstgl_dep` is not defined, since no opengl support was detected. As a result, we error out with:

```
Meson encountered an error in file subprojects/gstreamer-vaapi/meson.build, line 37, column 0:
Fallback variable 'gstgl_dep' in the subproject 'gst-plugins-bad' does not exist
```

How should this scenario work?

Is this a bug in Meson, and we should simply continue with 'not found' for this optional dependency in this case?

Or should gst-plugins-bad always set the variable, and indicate that it's not available with an empty array? (Will that be interpreted correctly as not found then?)

Something else?

**Comment by nirbheek** [comment]
I think this is a bug in Meson and we should simply continue with 'not found' since it's `required: false`. We should only error out if the subproject itself errors out (or there's a parser error in the subproject), not if the subproject wasn't found or if a variable inside it wasn't found.
