### ISSUE TITLE
configure_file: make input kwarg optional if command is specified?

### ISSUE THREAD

**Issue by tp-m** [mesonbuild/meson#1476]
I'm using configure_file() in the Gtk+ meson build to generate gresource.xml files based on a bunch of input filenames. This is done by calling a python script and passing the output filename and the input files to it.

I wonder if configure_file() really needs to insist on an input kwarg for this case, where `command:` is used?

**Comment by nirbheek** [comment]
Hmm, I thought I fixed that. Yes, there is no reason to require an input file.

**Comment by tp-m** [comment]
Updated.
