### ISSUE TITLE
Lexer error when using composite conditions including contains()

### ISSUE THREAD

**Issue by codido** [mesonbuild/meson#1477]
The following snippet results in a lexer error:
```
project('example', 'c')

v = 1
if ['foo'].contains('foo') && v == 1
	message('Works')
endif
```

If the '&& v == 1' is omitted, everything seems to work as expected.

**Comment by QuLogic** [comment]
Logical operations use [full words](https://github.com/mesonbuild/meson/wiki/Syntax#logical-operations), not symbols. I'm not sure why it doesn't raise an error.

**Comment by codido** [comment]
@QuLogic oops, my bad, thanks.
