### ISSUE TITLE
want install_data() variant that allows installing file under a different name

### ISSUE THREAD

**Issue by tp-m** [mesonbuild/meson#1487]
Sometimes one needs to install a file (data), but under a different name than it exists in the source tree, e.g. install `foo.bar.win32` as `foo.bar`.

We can currently hack around that with `configure_file()` and an empty configuration, but would be nice if there was an official way too.

**Comment by inigomartinez** [comment]
As stated in the last notification, tp-m has pointed me to this thread in #860. I'm facing a similar problem where some images have to be copied with their name changed. The case is exactly like this:

The files paths are as follow:

* data/icons/hicolor_apps_16x16.png
* data/icons/hicolor_apps_24x24.png
* data/icons/hicolor_apps_48x48.png
*  ...

These files should be installed like this:

* icons/hicolor/16x16/apps/note.png
* icons/hicolor/24x24/apps/note.png
* icons/hicolor/48x48/apps/note.png
* ...

The configuration workaround has two problems here.

1. It will parse the binary file, while it's unnecessary.
2. I'm not able to rename.

It would be nice if something like a copy_file function where source file name and destination file name could be stated exists.

**Comment by inigomartinez** [comment]
I did a workaround where I modified the files by using an install script, so the files were renamed properly. You can find a real example here[0], where a _very similar_ script is as follows:

`
name_pattern = re.compile('hicolor_(?:apps|actions)_(?:\d+x\d+|scalable)_(.*)')
search_pattern = '/**/hicolor_*'

actions_icon_dir = os.path.join(os.environ['MESON_INSTALL_PREFIX'], 'share', 'bijiben', 'icons', 'hicolor')
[os.rename(file, os.path.join(os.path.dirname(file), name_pattern.search(file).group(1)))
 for file in glob.glob(actions_icon_dir + search_pattern, recursive=True)]

apps_icon_dir = os.path.join(os.environ['MESON_INSTALL_PREFIX'], 'share', 'icons', 'hicolor')
[os.rename(file, os.path.join(os.path.dirname(file), name_pattern.search(file).group(1)))
`

I used some regex _black magic_ to parse the original file name, by getting the fields I need that were going to be used in the final name. It worked fine, although the files were properly renamed by an install script, meson is not able to figure out the final name on uninstall, so actually the command doesn't work properly. Despite the fact that this seems correct, it confirms that the workaround is just a hack and a rename option should exist somewhere.

I was also thinking about a _symetric_ add_uninstall_script, but it doesn't some like a good solution.

[0] https://git.gnome.org/browse/bijiben/tree/data/icons/meson_post_install.py?h=wip/inigomartinez/meson

**Comment by t-chaik** [comment]
Exact same problem here, for GHex. Nautilus is doing it another way [1], by arranging icons in subdirectories in the source tree and then calling install_subdir().

Still, it would be nice to be able to rename files at install time. What about an 'install_name' named argument one would pass to install_data()? Think it would cover at least the simple use-cases, wouldn't it?

[1] https://git.gnome.org/browse/nautilus/tree/data/icons
