### ISSUE TITLE
Objects of files() may be ambiguous

### ISSUE THREAD

**Issue by codido** [mesonbuild/meson#1494]
When files are specified using files(), their subdirectories aren't added as a prefix to their object file names, and all are output to the same output directory. As a result, if two different subdirectories have files with the same name, a conflict will follow.

For example, the following fails with `Multiple producers for Ninja target "a.out@exe/file.c.o". Please rename your targets.`:
```sh
#!/bin/sh

mkdir -p dir1 dir2

echo "int main() { return 0; }" > dir1/file.c
echo "sources += files('file.c')" > dir1/meson.build

touch dir2/file.c
echo "sources += files('file.c')" > dir2/meson.build

cat >meson.build <<EOF
project('proj', 'c')

sources = []
subdir('dir1')
subdir('dir2')
executable('a.out', sources: sources)
EOF

meson build
```

**Comment by nirbheek** [comment]
The fix for this is to use not the filename for deriving the object name, but the relative path to the current directory. The fix will have to also keep into account object extraction.

**Comment by codido** [comment]
@nirbheek Semi-related to this, perhaps extract_objects() should be able to receive files() as arguments?

**Comment by nirbheek** [comment]
Yes, that makes sense too!

**Comment by kaimast** [comment]
Is there a way to hack around this in earlier versions of meson?

**Comment by nirbheek** [comment]
If you can't rename the files, you can hack around it by 'copying' the files into the build directory with [`configure_file()`](http://mesonbuild.com/Reference-manual.html#configure_file):

```meson
copied_file = configure_file(input : 'source-file.c',
  output : 'renamed-file.c',
  configuration : configuration_data())
```

Then use the `copied_file` variable instead of `'source-file.c'` everywhere.
