### ISSUE TITLE
[REGRESSION] Order of include paths for internal dependencies is not maintained

### ISSUE THREAD

**Issue by thiblahute** [mesonbuild/meson#1495]
Since commit:

```
commit 2bb58c909fd80cc8ce053b5f1b6565bd28a416d2
Author: Nirbheek Chauhan <nirbheek@centricular.com>
Date:   Sat Jan 21 12:05:38 2017 +0530

    Use CompilerArgs for generation of compile commands
    
    At the same time, also fix the order in which compile arguments are
    added. Detailed comments have been added concerning the priority and
    order of the arguments.
    
    Also adds a unit test and an integration test for the same.
```

using [gst-build](https://phabricator.freedesktop.org/diffusion/GSTBUILD) to build GES as a subproject where we use an internal  ["declare_dependency"](https://phabricator.freedesktop.org/diffusion/GES/browse/master/ges/meson.build;dd8dacdfdee901c2ef2b1b839e6edb1a39434af5$192) which properly declares the include paths to build `ges-launch` [(build def)](https://phabricator.freedesktop.org/diffusion/GES/browse/master/tools/meson.build;dd8dacdfdee901c2ef2b1b839e6edb1a39434af5$1) we can see that the include path (which should include `-Isubprojects/gst-editing-services/`) is not present:

`[1/2] cc  '-Isubprojects/gst-editing-services/tools/ges-launch-1.0@exe' '-Isubprojects/gst-editing-services/tools' '-Isubprojects/gst-editing-services/ges' '-Isubprojects/gstreamer/gst' '-Isubprojects/gstreamer/libs/gst/base' '-Isubprojects/gst-plugins-base/gst-libs/gst/video' '-Isubprojects/gst-plugins-base/gst-libs/gst/pbutils' '-Isubprojects/gst-plugins-base/gst-libs/gst/audio' '-Isubprojects/gst-plugins-base/gst-libs/gst/tag' '-Isubprojects/gstreamer/libs/gst/controller' '-Isubprojects/gst-devtools/validate/gst/validate' '-I../subprojects/gst-editing-services/tools' '-Isubprojects/gstreamer' '-I../subprojects/gstreamer' '-Isubprojects/gstreamer/libs' '-I../subprojects/gstreamer/libs' '-Isubprojects/gst-plugins-base/gst-libs' '-I../subprojects/gst-plugins-base/gst-libs' '-Isubprojects/gst-devtools/validate' '-I../subprojects/gst-devtools/validate' '-Isubprojects/gst-editing-services' '-I../subprojects/gst-editing-services' '-I/usr/include/glib-2.0' '-I/usr/lib/glib-2.0/include' '-I/usr/include/orc-0.4' '-I/usr/include/libxml2' '-fdiagnostics-color=always' '-pipe' '-D_FILE_OFFSET_BITS=64' '-Wall' '-Winvalid-pch' '-Werror' '-O0' '-g' '-pthread' '-pthread' '-pthread' '-pthread' '-pthread' '-pthread' '-pthread' '-pthread' '-pthread' '-pthread' '-pthread' '-pthread' '-pthread' '-pthread' '-pthread' '-pthread' '-pthread' '-pthread' '-pthread' '-pthread' '-pthread' '-pthread' '-pthread' '-pthread' '-pthread' '-pthread' '-pthread' '-pthread' '-DHAVE_CONFIG_H' '-DGST_USE_UNSTABLE_API' '-MMD' '-MQ' 'subprojects/gst-editing-services/tools/ges-launch-1.0@exe/ges-launcher.c.o' '-MF' 'subprojects/gst-editing-services/tools/ges-launch-1.0@exe/ges-launcher.c.o.d' -o 'subprojects/gst-editing-services/tools/ges-launch-1.0@exe/ges-launcher.c.o' -c ../subprojects/gst-editing-services/tools/ges-launcher.c`

Before that commit it used to look like:
`[314/315] cc  '-Isubprojects/gst-editing-services/tools/ges-launch-1.0@exe' '-fdiagnostics-color=always' '-Isubprojects/gst-editing-services/tools' '-I../subprojects/gst-editing-services/tools' '-Isubprojects/gst-editing-services/.' '-I../subprojects/gst-editing-services/.' '-Isubprojects/gstreamer/.' '-I../subprojects/gstreamer/.' '-Isubprojects/gstreamer/libs' '-I../subprojects/gstreamer/libs' '-Isubprojects/gst-plugins-base/gst-libs' '-I../subprojects/gst-plugins-base/gst-libs' '-Isubprojects/gst-devtools/validate/.' '-I../subprojects/gst-devtools/validate/.' '-pipe' '-Wall' '-Winvalid-pch' '-DHAVE_CONFIG_H' '-DGST_USE_UNSTABLE_API' '-O0' '-g' '-Werror' '-I/usr/include/glib-2.0' '-I/usr/lib/glib-2.0/include' '-pthread' '-I/usr/include/orc-0.4' '-pthread' '-I/usr/include/libxml2' '-pthread' '-Isubprojects/gst-editing-services/ges' '-Isubprojects/gstreamer/gst' '-Isubprojects/gstreamer/libs/gst/base' '-Isubprojects/gst-plugins-base/gst-libs/gst/video' '-Isubprojects/gst-plugins-base/gst-libs/gst/pbutils' '-Isubprojects/gst-plugins-base/gst-libs/gst/audio' '-Isubprojects/gst-plugins-base/gst-libs/gst/tag' '-Isubprojects/gstreamer/libs/gst/controller' '-Isubprojects/gst-devtools/validate/gst/validate' '-MMD' '-MQ' 'subprojects/gst-editing-services/tools/ges-launch-1.0@exe/ges-launcher.c.o' '-MF' 'subprojects/gst-editing-services/tools/ges-launch-1.0@exe/ges-launcher.c.o.d' -o 'subprojects/gst-editing-services/tools/ges-launch-1.0@exe/ges-launcher.c.o' -c ../subprojects/gst-editing-services/tools/ges-launcher.c`

In the end, this means that when we [`#include "config.h"`](https://phabricator.freedesktop.org/diffusion/GES/browse/master/tools/ges-launcher.c;dd8dacdfdee901c2ef2b1b839e6edb1a39434af5$21) we end up including the include file from `-Isubprojects/gstreamer` which is plain wrong (and in the end it is built without `gst-validate` support).

**Comment by nirbheek** [comment]
So, `-Isubprojects/gst-editing-services` is still there, but the order is wrong:

before:
```
'-Isubprojects/gst-editing-services/tools/ges-launch-1.0@exe'
'-Isubprojects/gst-editing-services/tools'
'-I../subprojects/gst-editing-services/tools'
'-Isubprojects/gst-editing-services/.'
'-I../subprojects/gst-editing-services/.'
'-Isubprojects/gstreamer/.'
'-I../subprojects/gstreamer/.'
'-Isubprojects/gstreamer/libs'
'-I../subprojects/gstreamer/libs'
'-Isubprojects/gst-plugins-base/gst-libs'
'-I../subprojects/gst-plugins-base/gst-libs'
'-Isubprojects/gst-devtools/validate/.'
'-I../subprojects/gst-devtools/validate/.'
'-I/usr/include/glib-2.0'
'-I/usr/lib/glib-2.0/include'
'-I/usr/include/orc-0.4'
'-I/usr/include/libxml2'
'-Isubprojects/gst-editing-services/ges'
'-Isubprojects/gstreamer/gst'
'-Isubprojects/gstreamer/libs/gst/base'
'-Isubprojects/gst-plugins-base/gst-libs/gst/video'
'-Isubprojects/gst-plugins-base/gst-libs/gst/pbutils'
'-Isubprojects/gst-plugins-base/gst-libs/gst/audio'
'-Isubprojects/gst-plugins-base/gst-libs/gst/tag'
'-Isubprojects/gstreamer/libs/gst/controller'
'-Isubprojects/gst-devtools/validate/gst/validate'
```

after:
```
'-Isubprojects/gst-editing-services/tools/ges-launch-1.0@exe'
'-Isubprojects/gst-editing-services/tools'
'-Isubprojects/gst-editing-services/ges'
'-Isubprojects/gstreamer/gst'
'-Isubprojects/gstreamer/libs/gst/base'
'-Isubprojects/gst-plugins-base/gst-libs/gst/video'
'-Isubprojects/gst-plugins-base/gst-libs/gst/pbutils'
'-Isubprojects/gst-plugins-base/gst-libs/gst/audio'
'-Isubprojects/gst-plugins-base/gst-libs/gst/tag'
'-Isubprojects/gstreamer/libs/gst/controller'
'-Isubprojects/gst-devtools/validate/gst/validate'
'-I../subprojects/gst-editing-services/tools'
'-Isubprojects/gstreamer'
'-I../subprojects/gstreamer'
'-Isubprojects/gstreamer/libs'
'-I../subprojects/gstreamer/libs'
'-Isubprojects/gst-plugins-base/gst-libs'
'-I../subprojects/gst-plugins-base/gst-libs'
'-Isubprojects/gst-devtools/validate'
'-I../subprojects/gst-devtools/validate'
'-Isubprojects/gst-editing-services'
'-I../subprojects/gst-editing-services'
'-I/usr/include/glib-2.0'
'-I/usr/lib/glib-2.0/include'
'-I/usr/include/orc-0.4'
'-I/usr/include/libxml2'
```

The problem is not the `CompilerArgs` class, but the order in which we append includes to it. Will write up a patch for this.
