### ISSUE TITLE
Depending on generated linker files

### ISSUE THREAD

**Issue by codido** [mesonbuild/meson#1501]
I might be missing something, but there doesn't seem to be an easy/possible way to use link_depends for depending on generated files (e.g. dynamic generated linker script).

Such files are always assumed to be in the source directory, and adding the build directory as a prefix breaks the dependencies.

**Comment by nirbheek** [comment]
What exactly are you trying to do?

**Comment by codido** [comment]
I'm referring to a bare-metal target in which the linker script is auto generated based on a few dynamic constraints.

In other words, the linker script itself is generated using a custom target based on other files in the tree, and the final executable uses that when linking.

**Comment by nirbheek** [comment]
That is a `link_depends:` kwarg for that exact purpose, does it not work for you?

**Comment by codido** [comment]
Afraid not. Unless I'm missing something link_depends assumes the files are located in the source directory. And even if meson.current_build_dir() is added, the targets don't quite match the custom target..

**Comment by nirbheek** [comment]
I see now that it won't work because it must be a string (which is a bit broken; it can also be a file object, but that's a separate issue).

What is the linker script called? Usually you can just add the return value of `custom_target()` to the sources of a target and Meson will do the right thing -- if it's a source file, it will be compiled, if it's an object, it will be linked, if none of the above, it will be ignored, etc.

**Comment by codido** [comment]
Seems that if it is added to the source list, meson will add it to the dependencies (so it will be generated), but will not actually use it. This can be worked around by also adding the actual file to link_args, but I find that a bit counter-intuitive ;)

Shouldn't link_depends do all that, at least in theory (assuming it can be assigned a dependency, which it currently cannot)?

**Comment by nirbheek** [comment]
`link_depends:` is for files in the source tree that are used at link-time, but aren't source files. It adds a dependency in the build files so that if you change it in the source tree, the target(s) are re-linked (but not re-compiled). You still have to add it manually to your linker argument list if it is supposed to be consumed there. Meson can't know how you want to use it.

How exactly do you use this linker script in your linker arguments?

**Comment by codido** [comment]
With the above workaround, I just added custom_target result to the list of sources, and the actual file name to link_args (this particular linker doesn't have any special flags for specifying linker scripts).
I guess that if there's no real way of knowing how to feed the linker with its script, there's no way around specifying it twice. But perhaps it would have been nicer if link_depends could get a custom_target result as well instead of specifying it in the sources (which technically it isn't)?

In any case, if that's the intended behavior, I think we can close this, thanks!

**Comment by nirbheek** [comment]
What's the behaviour if that `custom_target()` is regenerated? Is the target only re-linked or also re-compiled?

**Comment by codido** [comment]
Only re-linked (it's basically a linker script)

**Comment by nirbheek** [comment]
No, I mean did you check that when the `custom_target()` is regenerated, the target where it's used is just re-linked or is it also re-compiled?

**Comment by codido** [comment]
When the lds is added to the list of sources? Just re-linked.

**Comment by nirbheek** [comment]
Okay. In that case there is no benefit to allowing `link_depends:` to also accept generated files. I'll close this. Thanks!

**Comment by codido** [comment]
@nirbheek My test might have been broken (or code changed since), but I'm noticing two things:

- Regenerating the lds doesn't seem to trigger a new link
- If the lds is the only argument in sources (in the case of linking previously built objects), it will not be generated.

I believe that both of these are caused by the fact that the dependency is set to order dependencies for the rest of the files and not the target. Since lds wouldn't be picked up by the make deps, it wont be converted to an implicit dependency (which is actually good, or otherwise it would trigger a re-compilation).
