### ISSUE TITLE
error checking math (m) library on windows

### ISSUE THREAD

**Issue by guruDanny67** [mesonbuild/meson#1509]
I'm on Visual studio 2015 and I'm trying to build emeus on windows and the meson.buildit use the reccomended way to check for the need of th em library:

    # Required dependencies
    mathlib_dep = cc.find_library('m', required: false)

but it finds the library, even if on windows is not necessary.

It's not a big problem if you want to build the emeus library without gobject-introspection (the build is fine).

But with the gobject stuff you got an error of library m not found.

I take a look at what happens and, without giving some libdir parameter, the meson check is made building a small executable with the required lib: the 19.x vs cl compiler simply ignores the added parameter (-lm.lib or something similar) so the check passes but if you need to use it on the link phase you've got an error (library not found).

I know this is more a Visual Studio C compiler issue (why in the earth you should ignore wrong parameters, if I make an error I would like to know it as soon as possible ...) 

BTW I'm using meson 0.39.0 

One solution would be to put a null dependencie if you are on windows with the vs compiler (if cc.get_id() == 'msvc') but I'm arguing if there an easy way to put a dependencies that doesn't do anything without writing something like:

no_dep_lib = cc.find_library('hope_you_will_not_find_this_library,please', required: false)

thanks in advance

**Comment by nirbheek** [comment]
This is strange though. We do the exact same thing as a link command while doing a `find_library()` check. So it should fail (or succeed) in the same way in both places.

Could you send us the link commands used in `cc.find_library()` (see `build/meson-logs/meson-log.txt`) and the build command (`ninja -d keeprsp`, then look at the `.rsp` file)?

**Comment by guruDanny67** [comment]
I make a little test, with a simple C snippet that uses sin()/cos():
File test.C:
#include <stdio.h>
#include <math.h>

int main(int argc, char * argv[])
{
    int     i;

    for(i = 0; i < 360; i += 30) {
        double  rad;
        double  sa;
        double  ca;

        rad = (i * 3.14) / 180.0;
        sa = sin(rad);
        ca = cos(rad);
        printf("%3u %10.7f %10.7f - %10.7f\n", i, sa, ca, sa * sa + ca * ca);
    }
    return 0;

}

I then make a simple meson.build file:
project('test', 'c')

cc = meson.get_compiler('c')
m_dep = cc.find_library('m', required : false)

executable('test_app', 'test.c',
            dependencies : m_dep)

And tested it in windows (vs2015) and linux (ubuntu gnome 17.04) and everything is working good in the sense that the executable is correct and give the expected result (if I don't put the math dependencies the program don't run on linux, for example) and the only strange thing is that, on windows, the math library is found.

Taking a look at the meson-log.txt the test is made with:
Running compile:
Working directory:  c:\temp\meBak\tmpnni0e1mx
Command line:  cl c:\temp\meBak\tmpnni0e1mx\testfile.c /MDd /Od /nologo /showIncludes /Fec:\temp\meBak\tmpnni0e1mx\output.exe 

Code:
 int main(int argc, char **argv) {
    return 0;
}
        
Compiler stdout:
 testfile.c

Compiler stderr:
 
Library m found: YES

If I try to llok for another lib, say x.lib, the same command is:
Running compile:
Working directory:  c:\temp\meBak\tmpmp7d_0gv
Command line:  cl c:\temp\meBak\tmpmp7d_0gv\testfile.c /MDd /Od x.lib /nologo /showIncludes /Fec:\temp\meBak\tmpmp7d_0gv\output.exe 

Code:
 int main(int argc, char **argv) {
    return 0;
}
        
Compiler stdout:
 testfile.c
LINK : fatal error LNK1181: impossibile aprire il file di input 'x.lib'

Compiler stderr:
 
Library x found: NO

(impossibile aprire il file di input 'x.lib' means 'Impossible to open the input file 'x.lib', I use the italian version of vs 2015).

I take a look at the meson code and, in compilers.py there is a check on some libraries:

                if name in ('m', 'c', 'pthread'):
                    # With MSVC, these are provided by the C runtime which is
                    # linked in by default
                    continue
           
It seems that if you're trying to use the m lib with msvcis simply dropped from the command line: when you use the compiler directly there is no problem (apart from the fact that you see that the m library is needed) but when you use custom commands (the g_ir_scanner, in my case) you may have problems.

Dropping the 'm' from the test in compilers.py gives the expected result (the library is tested and not found so it's not linked to the program) but I don't know if it's the correct solution.

Hope this help, thanks in advance.

**Comment by jpakkane** [comment]
Does `g_ir_scanner` fully support Visual Studio syntax? In any case it should not need the `m` library anyway, any test it compiles should have it by default. Can you list a concrete example of a failing case?

**Comment by guruDanny67** [comment]
I'm trying to put gobject-introspection support on the wingtk/gtk-win32 github project and up to gtk3 everywhing is okay because there are some nmake makefile that take cares of building the gir/typelib.

I'm adding emeus that instead uses meson to build and, if I disable the gobject introspection part all is fine, if I don't disable it I get an error when, using the gnome meson object, the g_ir_scanner is called:

In particular the part with the error is:

[29/30] "Generating Emeus-1.0.gir with a custom command."
FAILED: src/Emeus-1.0.gir
"python" "C:/gtk-build/gtk/win32/release/bin/g-ir-scanner" "../emeus/src/emeus-constraint.h" "../emeus/src/emeus-constraint-layout.h" "../emeus/src/emeus-version-macros.h" "../emeus/src/emeus-types.h" "../emeus/src/emeus-utils.h" "../emeus/src/emeus-constraint.c" "../emeus/src/emeus-constraint-layout.c" "../emeus/src/emeus-types.c" "-IC:/gtk-build/gtk/win32/release/include/gobject-introspection-1.0" "-IC:/gtk-build/gtk/win32/release/include/glib-2.0" "-IC:/gtk-build/gtk/win32/release/lib/glib-2.0/include" "--no-libtool" "--namespace=Emeus" "--nsversion=1.0" "--warn-all" "--output" "src/Emeus-1.0.gir" "--c-include=emeus.h" "-DEMEUS_COMPILATION" "-IC:/gtk-build/build/Win32/release/emeus/src" "-IC:/gtk-build/build/Win32/release/emeus-go/src" "--include=Gtk-3.0" "--symbol-prefix=emeus" "--identifier-prefix=Emeus" "--pkg-export=emeus-1.0" "-IC:/gtk-build/gtk/win32/release/lib/glib-2.0/include" "-IC:/gtk-build/gtk/win32/release/include/gdk-pixbuf-2.0""-IC:/gtk-build/gtk/win32/release/include/gtk-3.0" "-IC:/gtk-build/gtk/win32/release/include/glib-2.0" "-IC:/gtk-build/gtk/win32/release/include/atk-1.0" "-IC:/gtk-build/gtk/win32/release/include/pango-1.0" "-IC:/gtk-build/gtk/win32/release/include/cairo" "-LC:/gtk-build/build/Win32/release/emeus-go/src" "-lpangowin32-1.0" "-lcairo" "-lgdi32" "-lgdk-3.0" "-lglib-2.0" "-lpango-1.0" "-lwinmm" "-lole32" "-lgtk-3.0" "-lgobject-2.0" "-lm" "-lintl" "-lshell32" "-lzlib1" "-limm32" "-lgdk_pixbuf-2.0" "-lcairo-gobject" "-lws2_32" "-lgio-2.0" "-lgmodule-2.0" "-lusp10" "-latk-1.0" "-lpangocairo-1.0" "-liconv" "-LC:/gtk-build/gtk/win32/release/lib" "-ldwmapi" "--library" "emeus-1.0"

Microsoft (R) C/C++ Optimizing Compiler versione 19.00.24215.1 per x86
Copyright (C) Microsoft Corporation. Tutti i diritti  sono riservati.

g-ir-cpp-ht2cx46j.c
' at '__pragma'C\INCLUDE\vcruntime.h:81: syntax error, unexpected identifier in '__pragma(pack(push, 8))

.... A lots of errors like this previous one, also active when building with the makefile ...
... and at the end

LINK : fatal error LNK1181: impossibile aprire il file di input 'm.lib'
Traceback (most recent call last):
  File "c:\dev\py35\Lib\distutils\msvc9compiler.py", line 642, in link
    self.spawn([self.linker] + ld_args)
  File "c:\dev\py35\Lib\distutils\ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "c:\dev\py35\Lib\distutils\spawn.py", line 38, in spawn
    _spawn_nt(cmd, search_path, dry_run=dry_run)
  File "c:\dev\py35\Lib\distutils\spawn.py", line 81, in _spawn_nt
    "command %r failed with exit status %d" % (cmd, rc))
distutils.errors.DistutilsExecError: command 'C:\\dev\\vs2015\\VC\\BIN\\link.exe' failed with exit status 1181

If I change the meson.build file to avoid to find the m lib dependency with this ugly hack:

if cc.get_id() == 'msvc'
    mathlib_dep = cc.find_library('_hope_I_dont_find_this', required: false)
else
    mathlib_dep = cc.find_library('m', required: false)
endif

then the g_ir_scanner program gives some warning but the .gir/.typelib will be build correctly.

Thanks

**Comment by nirbheek** [comment]
Yes, I see the bug now, thanks for investigating. Will have a patch soon.

**Comment by fanc999** [comment]
Hi,

Just wondering, since the latest unstable gobject-introspection (which will become 1.54) does filter out the m.lib/-lm on Visual Studio during the scan (since I did the patch for it), does this issue still affect you?

With blessings, and cheers!

**Comment by guruDanny67** [comment]
I should make a test to see what happen. I can't find the patch (I look in gnome/gobject-introspection on github ...) but if you drop the '-lm' option then should work: on other places (when making an executable, for example) is meson that drops that part.

**Comment by fanc999** [comment]
Hi @guruDanny67,

This is the commit that contains the change, as it was part of another change to improve/fix g-ir-scanner...

https://github.com/GNOME/gobject-introspection/commit/5d4cd25292b8ed2c7a821ebe19fc5ab5d447db1a

With blessings, and cheers!

**Comment by guruDanny67** [comment]
Ok, I try to apply the patch but I have a lot of errors so I get the
giscanner dir from the master branch of gobject-introspection and run the
program to build the gir for emeus that gave me the error: with the new
version the .gir & .typelib are build so I think the patch is useful also
to resolve this issue.

Obviously, the m library stuff should be resolved by meson in my opinion
(when it's fixed there is no need to have special cases on msvc).

When will be out the new (1.54.x) release ?

Actually the gi part on my side is made with a couple of batch (and works
only with gtk 3.22.6, with the new version there are some errors, don't
know if caused by the VC runtime or Gtk) but will be a good think (tm) if
is present directly in the gvsbuild project.

I'm working right now to have all the gtkmm stuff working on gvsbuild
(using meson to build evertthing) but the gobject-introspection project is
one of the requested one (this can give you the gtk3 stuff working on the
new python 3.5/3.6).

Thanks for all the good work you're doing on the gtk,

With best regards

    Daniele Forghieri



2017-07-21 4:41 GMT+02:00 fanc999 <notifications@github.com>:

**Comment by nirbheek** [comment]
> Obviously, the m library stuff should be resolved by meson in my opinion (when it's fixed there is no need to have special cases on msvc).

Agreed, and there's a PR for it that I'm working on right now. However, gobject-introspection also needed to filter it out because Meson is not the only way to build using gobject-introspection.
