### ISSUE TITLE
Check keyword list

### ISSUE THREAD

**Issue by kitterion** [mesonbuild/meson#151]
In meson many functions don't even throw a warning when they see an unknown keyword, for instance:

```
find_library('pthread', useless_keyword : 'is useless')
```

Functions should check the keyword list they are invoked with.

**Comment by jpakkane** [comment]
Yes. This needs a keyword checking decorator and applying it liberally in interpreter.

**Comment by nirbheek** [comment]
This is fixed now. A keyword checking decorator was added several releases ago.
