### ISSUE TITLE
Building static libraries fails on Windows

### ISSUE THREAD

**Issue by peterh** [mesonbuild/meson#1517]
Starting with meson 0.39, building a library in a subdir fails on Windows.

Meson creates a build.ninja file containing a shell-out to a `del` command that only accepts \ as a path separator, but with a path that uses / as the path separator. This results in a build failure on Windows when `del` treats / as the switchchar and fails because it does not recognize the switch.

The build works fine in 0.37.x and 0.38.x.

Command output:
```
C:\Users\peterh\src\microbench>meson.py --buildtype debugoptimized build
The Meson build system
Version: 0.39.0
Source dir: C:\Users\peterh\src\microbench
Build dir: C:\Users\peterh\src\microbench\mingw
Build type: native build
Project name: microbench
Native c compiler: gcc (gcc 6.3.0)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Build targets in project: 2

C:\Users\peterh\src\microbench>ninja -Cbuild
ninja: Entering directory `build'
[2/4] Static linking library lib/libmbc.a
FAILED: lib/libmbc.a
cmd /c del /f /s /q lib/libmbc.a && ar @lib/libmbc.a.rsp
Invalid switch - "libmbc.a".
[3/4] Compiling c object polypt/polypt@exe/polypt.c.obj
ninja: build stopped: subcommand failed.
```

The meson.build files are trivial. Just in case:

meson.build:
```
project('microbench', 'c')

mbc_inc = include_directories('lib')
subdir('lib')
subdir('polypt')
```
lib\meson.build:
```
mbclib = static_library('mbc', 'mbc.c')
```
polypt\meson.build:
```
polypt_src = ['polypt.c']
polyptexe = executable('polypt', polypt_src,
        include_directories:mbc_inc,
        link_with:mbclib)
```

**Comment by nirbheek** [comment]
Ouch. This wasn't noticed because of insufficient test coverage.

**Comment by nirbheek** [comment]
Can you test if https://github.com/mesonbuild/meson/pull/1527 fixes it for you?

**Comment by peterh** [comment]
Yes, that fixes it for me. Thanks!
