### ISSUE TITLE
Missing shared library links in flat layout

### ISSUE THREAD

**Issue by sardemff7** [mesonbuild/meson#1521]
I have a project with a few libraries built with `version` (`0.0.0` in this case, but it doesn’t matter) and plugins. I use the flat layout so I can set the build dir as a plugin dir and load them all for tests.
Recently I added some API in one of the library, and my (manual) test suddenly failed due to a missing symbol.

It appears that Meson, with the flat layout, doesn’t create the `liblib.so.0 -> liblib.so.0.0.0` symlink in the build dir. Removing my system installed package confirms this is the issue.

**Comment by nirbheek** [comment]
Btw, you don't need to set a flat layout to get access to your plugindir. You can set an environment variable that points to it. That's how most projects do it.

**Comment by sardemff7** [comment]
When you have a variable pointing to one directory and multiple plugins in their own dir, you can’t. :-)
I had to add a PATH-like variable and fill it in a wrapper script when testing (manual testing).

**Comment by nirbheek** [comment]
Yes, you can. Meson explicitly supports that use-case, and GStreamer even uses it. See: https://cgit.freedesktop.org/gstreamer/gst-plugins-base/tree/tests/check/meson.build#n154

We already have a wrapper script that can run individual tests for you with those settings: `mesontest`.

**Comment by sardemff7** [comment]
No, I mean my application didn’t have a PATH-like variable I could set, but only a variable to set *one* path to search in.
Setting the env var is not the problem here.
