### ISSUE TITLE
Absolute-path requirement for include_directories() breaks existing projects

### ISSUE THREAD

**Issue by ximion** [mesonbuild/meson#1535]
Hi!

The [Vibe.d project](https://github.com/rejectedsoftware/vibe.d) uses Meson for building. It has a couple of external dependencies, which, if found in the system, are used from there. Otherwise, the Meson script will invoke Git to clone the 3rd-party projects from their repos and add them as includes.
This is messy, but needed because the dependencies themselves don't have Meson files and Meson forcing the use of a toplevel directory named "subprojects" along with its very specific wrap requirements make it very annoying to use this feature.
However, just calling the right commands makes things "just work".

Recently, Meson was changed so `include_directories()` doesn't allow absolute paths anymore. Since the additional files are downloaded into the build directory, their include path is constructed like:
`include_directories (meson.build_root() + '/subprojects' + '/xyz')`

Unfortunately since `meson.build_root()` gives an absolute path, this expression fails now. I assume others are hit by this issue as well, since someone might generate files in a separate directory in `build_root` and want to include them as well (not everyone has the more exotic case of downloading dependencies on-demand).

So, could you either:
 * Revert the change to make `include_directories()` require a relative path
 * Make  `meson.build_root()` return a relative path
 * Add a native function to convert a relative to an absolute path, or specify whether the output of  `meson.build_root()` should be relative / absolute.

At time the problem is solved by spawning a Python interpreter to make the directory relative, which is a really nasty hack that I would like to get rid of.

[1]: https://github.com/rejectedsoftware/vibe.d

**Comment by TingPing** [comment]
> include_directories (meson.build_root() + '/subprojects' + '/xyz')

Does `include_directories('subprojects/xyz')` not work?

**Comment by ximion** [comment]
@TingPing It doesn't, since the directory is in `build_root` which we don't know yet until the build is configured...

**Comment by nirbheek** [comment]
Include directories are always relative to the build root, which is why we started to forbid absolute include dirs. There is no need to use an absolute path.

**Comment by ximion** [comment]
@nirbheek True, but if I want to reference stuff in the build-root directory, I have no way to get a relative path to that directory.

**Comment by nirbheek** [comment]
All include directories evaluate to two directories: one relative to the build root and another relative to the source root. i.e., `include_directories('some-dir')` will become `-I@BUILD_ROOT@/some-dir -I@SOURCE_ROOT@/some-dir`.

**Comment by ximion** [comment]
@nirbheek Ah, interesting - I wonder if there ever will be a case where one wants to include one directory but not the other...

**Comment by ximion** [comment]
@nirbheek This is working really well - I think with the clarification that's in the Wiki now, it's safe to close this issue.
Thank you for your help! :-)
