### ISSUE TITLE
Cannot install internal shared library to work on both Windows and UNIXes

### ISSUE THREAD

**Issue by sardemff7** [mesonbuild/meson#1546]
Or rather, I cannot do it with sensible code, I have to duplicate my target.

Excerpt from [my project](https://github.com/sardemff7/eventd/blob/master/server/libeventd-helpers/meson.build):
```meson
libeventd_helpers_lib = library('eventd-helpers', [
        config_h,
        'src/reconnect.c',
        'src/config.c',
        'include/libeventd-helpers-dirs.h',
    ],
    c_args: [
        '-DG_LOG_DOMAIN="libeventd-helpers"',
    ],
    dependencies: [ libnkutils, libeventd_helpers_dep ],
    include_directories: libeventd_helpers_inc,
    install: true,
    install_dir: join_paths(get_option('libdir'), meson.project_name()),
)
```
On Windows, it installs my `.dll` in `lib/eventd`, which doesn’t work because all DLLs must be in the same directory as the executable.

If I change it to
`install_dir: is_windows ? get_option('libdir') : join_paths(get_option('libdir'), meson.project_name()),`
or
`install_dir: is_windows ? get_option('bindir') : join_paths(get_option('libdir'), meson.project_name()),`
It doesn’t work fully either, only the `.dll` is installed, the `.dll.a` is nowhere to be found, because it doesn’t pick the default dir.

I tried using a variable set to `''` or nothing or `None`, even tried a clever trick:
```meson
if is_windows
ins_dir = []
else
ins_dir = [ install_dir: join_paths(get_option('libdir'), meson.project_name()), ]
endif
libeventd_helpers_lib = library('eventd-helpers', [
        config_h,
        'src/reconnect.c',
        'src/config.c',
        'include/libeventd-helpers-dirs.h',
    ],
    ins_dir,
    c_args: [
        '-DG_LOG_DOMAIN="libeventd-helpers"',
    ],
    dependencies: [ libnkutils, libeventd_helpers_dep ],
    include_directories: libeventd_helpers_inc,
    install: true,
)
```
but no luck.

**Comment by nirbheek** [comment]
The problem with the `.dll.a` is fixed in #1469. In that PR, the import library is installed with the DLL if the DLL is installed in a custom location.

Is that enough for you? If not, what else would you like to see?

**Comment by sardemff7** [comment]
On Windows, custom location cannot work, all DLLs must be in the same directory as my executable. What I’d like is to be able to install in a custom directory on UNIXes, and in the default location on Windows, by nullifying the kwarg somehow.
I think #1469 allows that by passing either `[join_path(…)]` or `[]` (which makes `outputs[0] = None`), or `[true]`, right?

**Comment by nirbheek** [comment]
`[true]` should work, yes. `[]` won't work because you need to specify at least one `install_dir:` if `install: true`.

**Comment by sardemff7** [comment]
Tested it, it works. Sad that the lack of auto rpath addition forces me to drop the subdir anyway. :-)
