### ISSUE TITLE
The path() method does not return an array in 0.39

### ISSUE THREAD

**Issue by ebassi** [mesonbuild/meson#1547]
The `external_program` object's `path()` method should return an array, according to the documentation:

> which returns an array pointing to the executable (this is an array as opposed to a string because the program might be ['python', 'foo.py'], for example)

and it does so in Meson 0.37. On the other hand, in Meson 0.39, it returns a string.

This snippet:

```meson
jasmine = find_program('jasmine')
args = [jasmine.path()[0], '--no-config', '--tap']
```

Results in the error: Tried to index a non-array object.

Using `jasmine.path()` works, but it's not backwards compatible.

**Comment by ignatenkobrain** [comment]
7e805a019ae4d923403af8032776c0c302e3a50c is the first bad commit
```
commit 7e805a019ae4d923403af8032776c0c302e3a50c
Author: Nirbheek Chauhan <nirbheek@centricular.com>
Date:   Sun Feb 19 03:19:13 2017 +0530

    find_program: Fix implementation of .path()
    
    And actually test that prog.path() works. The earlier test was just
    running the command without checking if it succeeded.
    
    Also make everything use prog.get_command() or get_path() instead of
    accessing the internal member prog.fullpath directly.

:040000 040000 32056d2edb2a736b7027ddcdfced56d82d7bd1ba 76f3a76c6a029d1c2bdbeca46204ccce0c4f618d M	mesonbuild
:100755 100755 f72313a97409750155a2abba12025fc98b0775fa 95e52e3b1a0558872dcd7fbad7849f7f9e527e7d M	run_unittests.py
:040000 040000 725b52d70c0d94e724c4da5b9d2bddd5c4141e5e 05ed7261781943e7547052ebb1c85ea2c05d1ad7 M	test cases
```

cc @nirbheek

**Comment by nirbheek** [comment]
I've updated the documentation: https://github.com/mesonbuild/meson/wiki/Reference-manual#external-program-object

As per the discussion on IRC, I'm closing this since the new behaviour is the one we want.
