### ISSUE TITLE
Eclipse Project Generation

### ISSUE THREAD

**Issue by nordlow** [mesonbuild/meson#1552]
Are there any plans to add support for (backend-) generation of an Eclipse project with targets that call the generated ninja files?

**Comment by fabio-porcedda** [comment]
A generator for Eclipse projects would be great!

**Comment by TingPing** [comment]
I don't use Eclipse but wouldn't the other direction be ideal? An Eclipse plugin for Meson?

**Comment by mick-p1982** [comment]
https://wiki.eclipse.org/CDT/Meson/User_Guide
https://help.eclipse.org/photon/index.jsp?topic=%2Forg.eclipse.cdt.meson.docs%2FCDT%2FMeson%2FUser_Guide%2FUser-Guide.html

Above are some links, but they neglect to includey how to add their plugin to Eclipse or what is the minimal version of Eclipse. It suggests it's a plugin. Kind of silly. I'm stuck looking for some form of integration for the FreeDesktop server that uses Meson on Cygwin.

**Comment by williamfgc** [comment]
@mick-p1982 seems to be included with [Eclipse CDT](https://wiki.eclipse.org/CDT/Meson/User_Guide) as a feature, not a proper plugin. Hope it helps.

**Comment by dcbaker** [comment]
Our official stance is that we're not interested in writing backends for every available IDE. We have a fairly powerful introspection API specifically designed for IDE plugins, and we're happy to take patches to expose more information via that API.
