### ISSUE TITLE
add_project_arguments should ensure it is called before build targets only in the current project, not subprojects

### ISSUE THREAD

**Issue by dcbaker** [mesonbuild/meson#1554]
If a subproject is defined, and `add_project_arguments` is called after said subproject, then meson will error out with
```
Tried to set project arguments after a build target has been declared.
This is not permitted. Please declare all project arguments before your targets.
```

This doesn't seem correct, as `add_project_arguments` differese from `add_global_arguments` specifcially in that it doesn't affect subprojects. Specfically this is annoying because it means that if a dependency needs to add define as an argument rather than as configuration_data that must be done before the subproject, making it impossible to use the fallback parameter.

**Comment by nirbheek** [comment]
It's talking about [build targets](https://github.com/mesonbuild/meson/wiki/Reference-manual#build_target), not subprojects. You have to do all dependency fallbacks and subproject calls before defining any build targets (executable, library, etc).

**Comment by nirbheek** [comment]
Also, for the case of a dependency adding a define as an argument, you should be using the `c_args:` keyword argument to build targets, right? The usual way to do this is to keep a list of arguments that apply to (most) of the build targets in your definitions and append to that.

`add_project_arguments()` is there for the rare case when you want args to apply to all build targets, including examples and tools.

**Comment by nirbheek** [comment]
Hmm, I see what you mean about it not applying to subprojects, sorry. It should check if build targets have been defined in the current project, not subprojects.
