### ISSUE TITLE
Change documentation for build directory to "builddir"

### ISSUE THREAD

**Issue by whot** [mesonbuild/meson#1560]
Much of the documentation to meson uses a build directory called "build". That is confusing to newcomers who interpret "build" as a command - which in the context of a build system kinda makes sense :) So "meson build" isn't read as "meson set up a build directory" but rather as "build with meson". It gets worse for a command like "ninja -C build" which looks like a build command with a -C flag, rather than a "ninja -C use-directory-build". And it gets more confusing once you look at "ninja -C build clean" (why do I have to build to clean?). 

Can we switch to using "builddir" or something like that instead, that would make the documentation a lot clearer?

**Comment by nirbheek** [comment]
Would it help if we changed it to `build/`?

**Comment by whot** [comment]
I think it would help, but you might as well go the full length and call it "builddir/" then :)
A slash is easy to forget (e.g. by double-clicking to highlight the word for copy-paste) and it will eventually disappear.

**Comment by nirbheek** [comment]
I will note that this change will also help with projects that already have a `build` directory in their source trees to store m4 macros, vcxprojs, etc. Example: glib and gtk+.

**Comment by whot** [comment]
There's only one occurrence of this in the README, the rest is all in the wiki/doc. But hey, it's a start :)

**Comment by eli-schwartz** [comment]
Originally fixed in #1725 then more got added later on, I think I got everything in #8017
