### ISSUE TITLE
Attach test setup to tests

### ISSUE THREAD

**Issue by derekdai** [mesonbuild/meson#1561]
The idea is to put all the test invocation in meson.build, so I can simply run `mesontest` without any external script (that way, I need to sync between meson.build and the script).

**Comment by nirbheek** [comment]
What is missing from [`test()`](https://github.com/mesonbuild/meson/wiki/Reference-manual#test) that you need? You should be able to do everything except set `exe_wrapper` there. We could of course add that too, if that's what you need.

**Comment by derekdai** [comment]
I have test cases which are to make sure no memory access issues with valgrind.
Currently, I `add_test_setup()` and `test()`, then run `mesontest --setup=` to run test cases with valgrind. This way, I need another script to tell `mesontest` how to pair test/testsuite with test setup, so I have to maintain the test cases (which written in .c), meson.build, and shell script.

**Comment by jpakkane** [comment]
If you want to run only a subset of all tests when running with Valgrind, give them a unique suite name, say `vgtests` and then you can run them with:

    mesontest --setup=valgrind --suite=vgtests

**Comment by derekdai** [comment]
The point is this way I have to maintain a extra script to make sure test cases is run with right test setup.

**Comment by jpakkane** [comment]
How are your tests invoked currently?

**Comment by derekdai** [comment]
`meson --setup=test-setup-name`

**Comment by jpakkane** [comment]
No, I mean what starts that? Is it invoked by CI or something else?

**Comment by derekdai** [comment]
Currently, by hand, plan to integrate with Travis CI.

**Comment by jpakkane** [comment]
In Travis set your test command to `ninja test && mesontest --setup=valgrind <other flags>` and you are set.

If you have a test that must always be run with Valgrind (and only with Valgrind) you can instead do this:

    vg = find_program('valgrind')
    exe = executable('vg_test', ...)
    test('with vg', vg, args : [exe])

But note that this test can then never be run without Valgrind.

**Comment by derekdai** [comment]
OK, thank you, @jpakkane. Although I still think if meson can bind test setup (as test fixture?) with test cases and let user simply choose which test case/test suite to run would be a better idea.

**Comment by jpakkane** [comment]
That hardcodes tests and suites. Most people want to run under a variety of suites.

**Comment by eli-schwartz** [comment]
Since commit 0821462ce382541e120d8d6cfc1a3224a492b275 you can mark a test setup as automatically used via `is_default: true`, which I think covers the remaining usefulness.


As stated above, test setups are for optionally running tests with additional functionality. It's not really the correct way to handle "this test must always, and only, be run XXX way".
