### ISSUE TITLE
Boost Dependency: use -isystem instead of -I for includes, if compiler supports it

### ISSUE THREAD

**Issue by wberrier** [mesonbuild/meson#1569]
I have a case where boost isn't in /usr/include, and I'm using a "cross" compiler (it's a native compiler, but not in the standard paths)

The boost dependency code always sets up the include dirs with "-I" where it really should be using "-isystem", if it's supported for that compiler.

Otherwise, warnings are enabled, and I get errors based on Werror.

In this particular case, I'm actually using the code from #1568 using BOOST_LIBRARYDIR and BOOST_INCLUDEDIR, but I suspect the same issue exists when using BOOST_ROOT.

**Comment by wberrier** [comment]
I'd like to work on this.  Any tips for getting the "system" include switch for the current compiler in the dependency system?  I'll dig around in the meantime...

**Comment by wberrier** [comment]
I think I found it... created a pull request.

**Comment by jpakkane** [comment]
We considered having all dependencies be `isystem` for exactly this reason but there is a problem: `isystem` headers are resolved in a different order than `-I` includes or they behaved weird in some other way. Just enabling it blindly is probably not something we can do.

**Comment by wberrier** [comment]
Yes, unit tests (yay!) for this pull request didn't work when boost was found in /usr/include (couldn't find simple headers such as math.h).

So, it appears that -isystem needs to be used only when boost isn't in a standard location (/usr/include, others? /usr/local/include?).

Is using -isystem for any boost include path except for /usr/include sufficient?  That's my current thinking, and will update the pull request (although it depends on #1568 so I'm kinda waiting for that one to be merged first).

**Comment by wberrier** [comment]
Fixed with pull request #1581
