### ISSUE TITLE
RFE: support failing or retaiing unknown fields in configuration file template

### ISSUE THREAD

**Issue by keszybz** [mesonbuild/meson#1577]
Currently, `configure_file` will replace unknown `@FIELD@`s with an empty string. For some cases this is the right thing to do, but for other cases it can lead to silent failures.

It'd be great to have something like `strict: true | false`, with "false" being current behaviour and the default, and "strict" would fail with an error like "File FOO.in has @bar@ field which is not specified in the configuration object".

**Comment by nirbheek** [comment]
We've been thinking about also adding an option where unknown fields are ignored. This is useful for configuring generators that substitute `@FOO@` themselves, such as glib-mkenums and hence have those just lying around.

I think we need a different kwarg that can support all three modes. Let's not call it `mode:` though.

**Comment by bar** [comment]
@keszybz please don't use my handle to document your code :) thank you

**Comment by keszybz** [comment]
Heh, I started out by writing a different proposed syntax:
```
   unknown_fields : replace, retain, error
```
where 'replace' would be current behaviour, and 'error' would corresponds to my 'strict : true' above, and 'retain' would correspond to what you are describing.

What stopped me, was the trouble with not knowing if the field should be quoted or not by default. E.g. let's say we have a template like
```
#define FOO_NAME "name=" @foo@ 
#define BAR_VALUE @bar@
```
If we leave `@foo@` in there, we'll get a syntax error, which we wouldn't get if `@foo@` was quoted. But maybe that's OK. Actually we'd probably get a syntax error from both of those fields, when they are used, so on second thought, it seems OK to leave all unknown fields unquoted.

**Comment by keszybz** [comment]
@bar, you might want to petition github to be smarter and parse @bar@ not as your name. You're going to be pretty miserable with "foo" and "bar" being such a common placeholders. E.g. here:
```bash
$ git grep '\bbar\b' :/ | wc -l
477
```

I'll try to use quotes around your handle though.

**Comment by bar** [comment]
@keszybz But this is not a Github's issue.

At handling any user will get their attention, but `@keszybz` won't

**Comment by nirbheek** [comment]
@keszybz we have a separate syntax for substitutions that must be quoted: [`set_quoted()`](https://github.com/mesonbuild/meson/wiki/Reference-manual#configuration-data-object).

**Comment by keszybz** [comment]
> @keszybz we have a separate syntax for substitutions that must be quoted: set_quoted().

I know. But if you didn't run `set` or `set_quoted` with a given name, meson cannot know which one you would want. But like I said, that's actually OK, just leaving the `@symbol@` as it was should be OK for both cases.

**Comment by nirbheek** [comment]
I believe this is fixed since https://github.com/mesonbuild/meson/issues/2090.
