### ISSUE TITLE
Compiling with HDF5 libraries, customise compiler command for single target.

### ISSUE THREAD

**Issue by jhidding** [mesonbuild/meson#1584]
Hi,
I'm trying to use Meson to compile a code that uses HDF5. This HDF5 library is distributed with a custom `h5c++` script that adds the needed command line arguments to the same compiler that HDF5 was compiled with. Is there a way of changing the compiler command used for a single target? I don't want to use `custom_target`, since the functionality of `custom_target` is too limited.
Cheers, Johan

**Comment by jpakkane** [comment]
from memory, might need some iterations):

    hd5_cargs = run_command(['your_command', '--get_cflags]).stdout().strip().split()
    hd5_llink_args = run_command(['your_command', '--get_ldflags]).stdout().strip().split()

    executable(..., 
      c_args : hd5_cargs,
      link_args : hd5_link_args)

However if if actually requires using a specific compiler that is different from the default compiler then this is not possible but you should be able to roll your own with a generator + custom target.

**Comment by nirbheek** [comment]
> I don't want to use custom_target, since the functionality of custom_target is too limited.

In what way is it too limited for your use-case?

**Comment by jhidding** [comment]
@jpakkane Thanks, I could make that work by adding a bash script
```
#!/bin/bash

command=$(h5c++ -show \;)
compiler_args=$(echo ${command} | cut -d';' -f1 | cut -d' ' -f2-)
linker_args=$(echo ${command} | cut -d';' -f2)

case "${1}" in
    "--cflags")
        echo "${compiler_args}"
        ;;
    "--libs")
        echo "${linker_args}"
        ;;
esac
```

@nirbheek I'd like to combine the arguments from `h5c++` with those from other library dependcies (via the normal `pkg-config` route), build several object files like this and link them. Using the `custom_target` interface seems would need writing another generator script into Meson, which kind of defeats the purpose of using it at all. To be clear: the fault is with HDF5 for not providing a normal pkg-config file.

**Comment by jpakkane** [comment]
Meson supports a few dependencies that do not have pkg-config but instead their own compiler argument binaries. If you want, you can create a MR adding that to Meson core. The implementation is simple, just copy and change one of the existing classes.

**Comment by dcbaker** [comment]
I'm going to consider this closed as there is an HDF5 dependency now from @scivision. Please re-open if this is still not fixed.

**Comment by scivision** [comment]
Currently Meson HDF5 will use compiler wrappers as a last resort when `method: auto`.  There are other important depedencies like MPI that do similar. Perhaps there is a need to add another `dependency(method: 'wrapper')` ?
