### ISSUE TITLE
cross-compilation is overly complex and not working

### ISSUE THREAD

**Issue by holgerschurig** [mesonbuild/meson#1585]
Hi all.

I have a (hand-crafted) build.ninja that I use to compile a project of mine. I compile it on a x86 Linux box under Debian, the image will be run on bare silicon on an STM32 (ARM Cortex-M4).

in ninja, I specify something like this:

```
cross = arm-none-eabi
cc = ${cross}-gcc

rule cc
  deps = gcc
  depfile = $out.d
  command = $cc -MMD -MF $out.d $cflags $includes_rtos -c $in -o $out
  description = CC   $in
```

This is an abridged version. As said, this ninja build works fine.

However, retyping the basename all over again in lines like `build build/usb_core.o: ccf stm/usb/usb_core.c` get's on my nerves, so I looked into generators for Ninja files and found Meson.

One big difference I see that influences my project is this: Meson assume that everything has to be configured. "Make" and "Ninja" allow projects that don't have any configuration steps.

Not all software needs a configuration, e.g. this bootloader will every only run on one specific device. There is no need to compile it once for, say, x86, and once for arm. Meson doesn't support this. I simply say "ninja" on the command line and everything is done. With Meson, I'll have to type in `meson . build --cross-file arm-none-eabi.conf`, which is MUCH more complicated. Okay, I created an ./autorun.sh file to get around this. But still: an easy thing with other build systems (just typing in "make" or "ninja" for projects that actually don't need any configuration) is more complex with Mason.

Okay, now to the cross-file. I tried this:

```
[binaries]
c = '/usr/bin/arm-none-eabi-gcc'
cpp = '/usr/bin/arm-none-eabi-cpp'
ar = '/usr/bin/arm-none-eabi-ar'
strip = '/usr/bin/arm-none-eabi-strip'

[target_machine]
system = 'none'
cpu_family = 'arm'
cpu = 'cortex-m4'
endian = 'little'
```

But then Mason gives me this error:

```
The Meson build system
Version: 0.39.1
Source dir: /home/schurig/f/md380
Build dir: /home/schurig/f/md380/build
Build type: cross build
Project name: md380
Native c compiler: ccache cc (gcc 4.9.2)
Native cpp compiler: ccache c++ (gcc 4.9.2)
Host machine cpu family: x86
Host machine cpu: i686
Target machine cpu family: arm
Target machine cpu: cortex-m4
Build machine cpu family: x86
Build machine cpu: i686
Build targets in project: 1
Traceback (most recent call last):
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 286, in run
    app.generate()
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 170, in generate
    g.generate(intr)
  File "/usr/share/meson/mesonbuild/backend/ninjabackend.py", line 193, in generate
    self.generate_target(t, outfile)
  File "/usr/share/meson/mesonbuild/backend/ninjabackend.py", line 431, in generate_target
    obj_list.append(self.generate_single_compile(target, outfile, src, False, [], header_deps))
  File "/usr/share/meson/mesonbuild/backend/ninjabackend.py", line 1814, in generate_single_compile
    compiler = get_compiler_for_source(target.compilers.values(), src)
  File "/usr/share/meson/mesonbuild/mesonlib.py", line 180, in get_compiler_for_source
    raise RuntimeError('No specified compiler can handle file {!s}'.format(src))
RuntimeError: No specified compiler can handle file main_rtos.c
```

Also, just specifying the compiler via "CC", e.g. with

```
CC=/usr/bin/arm-none-eabi-gcc meson . build meson . build
```

doesn't work either, then I get an "Compiler /usr/bin/arm-none-eabi-gcc can not compile programs." error ... which is blatantly wrong. I used exactly this compiler previously ...

The question is really why it things that this compiler is unsuitable. Ideally, Meson would just generate the meson file, and not try to run the compiler I specified. As I defined nothing that has to do with configuration, it's simply not Mason's business, or?  For example, my project doesn't depend on Meson finding out if sizeof(int) is 4 or 8, the meson.build file just contains project() and executable() currently.

**Comment by jpakkane** [comment]
Most likely you have not told Meson which languages your project requires. The simplest way to do this is to have something like this in your `project` call:

    project('myproj', 'c')

The reason `CC` does not work is that in Meson that always refers to the "native" compiler, not the "cross" compiler. Meson sanity checks that each specified compiler can compile programs and its output can be run (when not cross compiling). Thus the report of it not being able to produce runnable binaries is accurate, though admittably it may be a bit confusing the first time you run it.

You should use `host_machine` in your cross file rather than `target_machine`. Unfortunately there are two differing viewpoints on how to name cross compilation machines. Meson follows the GNU standard of having `build`, `host` and `target` machines.

**Comment by holgerschurig** [comment]
I can provoke the python backtrace with a cross-file from above and a minimal meson.build like this:

```
project('md380', 'c')
executable('hello', 'main.c')
```
Well, I re-read https://gcc.gnu.org/onlinedocs/gccint/Configure-Terms.html and was confused about

> the machine that you are building for (host)

vs.

> the machine that GCC will produce code for (target)

I always thought that cross-compiling is only about the "target", and a sentence in this page also points into this direction:

> If build and host are the same but target is different, this is called a cross

... and everyone is speaking about **cross**-compiling, no one about **host-x-host,**-compiling, **crossed native**-compiling or **cross-built**-compiling as the GNU text mentions for the host == target != build case.




All in all I'm not too fond that `--cross-file` exists at all. I think the meson´s DSL could handle such cases well, no need to invent a new file format / new syntax (ok, it's ini file, but stil it isn't possible to have this in the main meson.build or included from it).

Anyway, I close this issue.

**Comment by pitti** [comment]
> ... and everyone is speaking about cross-compiling, no one about host-x-host,-compiling, crossed native-compiling or cross-built-compiling as the GNU text mentions for the host == target != build case.

Keep in mind that this is from the GCC documentation, so it makes sense to distinguish between native and cross that way.  The documentation speaks about _cross compilers_, not _cross-compilation_ (from the user perspective).

The [automake documentation](https://www.gnu.org/software/automake/manual/html_node/Cross_002dCompilation.html) provides a more fitting description on the _cross-compilation_ properties:

> To cross-compile is to build on one platform a binary that will run on another platform. When speaking of cross-compilation, it is important to distinguish between the _build_ platform on which the compilation is performed, and the _host_ platform on which the resulting executable is expected to run. 
> [...]
> The --host and --build options are usually all we need for cross-compiling. The only exception is if the package being built is itself a cross-compiler: we need a third option to specify its _target_ architecture.
