### ISSUE TITLE
meson rejects version numbers ending with a dot

### ISSUE THREAD

**Issue by evverx** [mesonbuild/meson#1586]
From https://github.com/systemd/systemd/pull/5704#issuecomment-291959683
```sh
# Ubuntu Zesty Zapus (development branch)

Meson encountered an error in file meson.build, line 536, column 0:
Invalid version to compare against: '2.29.'; only numeric digits separated by "." are allowed: invalid literal for int() with base 10: ''

$ find /usr/lib -name '*.pc' | xargs grep -E 2.29
/usr/lib/x86_64-linux-gnu/pkgconfig/blkid.pc:Version: 2.29.
/usr/lib/x86_64-linux-gnu/pkgconfig/mount.pc:Version: 2.29.
/usr/lib/x86_64-linux-gnu/pkgconfig/uuid.pc:Version: 2.29.
```

@nirbheek wrote
> This is a mistake in util-linux, but it is also a valid pkg-config version, which follows the rpm version comparison rules. Meson barfs on this because we don't implement rpm version comparison bug-for-bug. Arguably, we should, or at least we should be a bit more resilient.

**Comment by xnox** [comment]
I am "fixing" util-linux to generate 2.29.0 on at least Ubuntu artful. Versions with trailing `.` compare fine with `dpkg --compare-versions`. Which logic is chosen on how to treat trailing `.` is irrelevant, as long as there is one.
