### ISSUE TITLE
RFE: add new `install_symlink` command

### ISSUE THREAD

**Issue by keszybz** [mesonbuild/meson#1602]
I have to create a bunch of symlinks, e.g. for alternate binary names. I do by with something like this:
```meson
meson.add_install_script('sh', '-c',
                         'ln -s systemd-mount $DESTDIR@0@/systemd-umount'.format(bindir))
```
This has the following shortcomings:
- requires explicit manipulation of paths and $DESTDIR
- the symlink is not removed on `uninstall` (#371 is about that part too).

I'd be great to have something like
```meson
systemd_mount = executable(..., install : true)
install_symlink(systemd_mount, bindir + '/alternate-name')
# or
install_symlink('systemd-mount', bindir + '/alternate-name')
```
where a symlink from arg2 to arg1 would be created, underneath $DESTDIR. In case an argument like `systemd_mount` which holds a reference to an executable, the install path of that executable would be used.

`install_symlink` should take a boolean keyword arg `relative`, `true` by default, to create relative symlinks (like `ln -s --relative`), even if an absolute path is specified.

The symlink should be removed on uninstallation.

**Comment by dcbaker** [comment]
It would be very useful for mesa if this could install hard links as well. We use hardlinks for our "megadrivers".

**Comment by ximion** [comment]
What's the status on this? Any chance that this feature would land in Meson soonish? (I would need this as well)

**Comment by jpakkane** [comment]
We need comments about this on #1768.

**Comment by MaskRay** [comment]
Would like to see this feature, too

**Comment by Ericson2314** [comment]
I am in need of this too.

**Comment by Ericson2314** [comment]
This workaround I think is getting close, but need to make the symlink with the install path (or better, know how to fix on install).
```
name = 'new'
custom_target(
  name,
  output : name,
  input : old,
  command : ['ln', '-s', '@INPUT', '@OUTPUT'],
  install : true,
  install_dir : get_option('bindir')
)
```
And there's also Windows is getting better at symlinks (https://blogs.windows.com/buildingapps/2016/12/02/symlinks-windows-10/). Between all that, I think built-in support is motivated.

**Comment by mokafolio** [comment]
I'd love to have a symlink command, too!

**Comment by dzhang-b** [comment]
want to have a symlink install too. currently I have to use post install script, which does not track dependencies.

**Comment by Pamplemousse** [comment]
@Ericson2314 

> This workaround I think is getting close, but need to make the symlink with the install path (or better, know how to fix on install).
> 
> ```
> name = 'new'
> custom_target(
>   name,
>   output : name,
>   input : old,
>   command : ['ln', '-s', '@INPUT', '@OUTPUT'],
>   install : true,
>   install_dir : get_option('bindir')
> )
> ```

Also, this workaround does not work when there is already a folder, with the same name as the link to be created, already present in the source directory...
