### ISSUE TITLE
shared_library vs_modules_defs parameter dies when passed anything but string

### ISSUE THREAD

**Issue by dcbaker** [mesonbuild/meson#1605]
I'm not sure whether the bug here is that passing a list (particularly an empty one) is not acceptable, or whether generating a giant stacktrace instead of a nice error message is the bug. But either a more helpful error message or accepting the empty list would be good.

meson psuedo code:
```meson
if cc.get_id() == 'msvc'
  def = 'foo.def'
else
  def = []
endif

libfoo = shared_library(
  'libfoo',
  'foo.c',
  vs_modules_def: def,
)
```

**Comment by dcbaker** [comment]
Actually, it's even worse. I can't use a generated file as input either.

**Comment by jrfonseca** [comment]
> I'm not sure whether the bug here is that passing a list (particularly an empty one) is not acceptable, or whether generating a giant stacktrace instead of a nice error message is the bug.

There were two problems here.  Generated files can now be passed in `vs_module_defs`, but passing an empty list still fails.

I have to say it's a bit annoying that Meson doesn't allow to pass `None` objects around: it forces one to have multiple versions of the same function, just to add a few extra args.

**Comment by nirbheek** [comment]
@jrfonseca Could you please open a new bug about that?
