### ISSUE TITLE
Make it simpler to check program version

### ISSUE THREAD

**Issue by thiblahute** [mesonbuild/meson#1609]
Currently to look for a program version we have to do quite some [manual checks](https://cgit.freedesktop.org/gstreamer/gstreamer/commit/?id=57fd614e02681ee764f9eb0d0ae0aeb4f7ec8ca4), ideally we would like to have meson do it for us in `find_program`, simlilarly to what is done in `dependency`.

Most of the time the last column of the first line is the program version, so we should probably start with that to retrieve the version.

Also we might want an extra argument to specify how to retrieve the version from the command line (defaulting to `--version`).

I would imagine an api like:

``` meson
prog = find_program([pname],
     version : ">= 0.1.2.3",
     get_version_argument: '-v'
)
```

**Comment by mbiebl** [comment]
A lot of programs I know output more then simply the version string. Take git as an example:
```
$ git --version 
git version 2.11.0
```
Or sed:
```
$ sed --version
sed (GNU sed) 4.4
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Jay Fenlason, Tom Lord, Ken Pizzini,
and Paolo Bonzini.
GNU sed home page: <http://www.gnu.org/software/sed/>.
General help using GNU software: <http://www.gnu.org/gethelp/>.
E-mail bug reports to: <bug-sed@gnu.org>.
```
How would you deal with that?

**Comment by tp-m** [comment]
Are we really saying we can't come up with some good heuristics that works in 99% of the case? :)

**Comment by mbiebl** [comment]
> Are we really saying we can't come up with some good heuristics that works in 99% of the case? :)

It sounds like a clever hack, which is likely to break, as --version is not a defined a API.

**Comment by nirbheek** [comment]
A good heuristic is what we use in Meson for [detecting compiler versions](https://github.com/mesonbuild/meson/blob/master/mesonbuild/environment.py#L206). However, it is obvious that this might not work for every tool in existence. Nevertheless, a prototype like this would work for almost everyone:

```
find_program('pname',
    version : ">=0.1.2.3", # by default, will try --version and send EOF to stdin just in case
    version_args : '-v', # optional, can be a list
    version_regex : 'v\d+\.\d+') # optional, will search both stdout and stderr
```

This leaves us with programs that output a version that can't be parsed via regular expressions, but at that point you are so deep in the pits of Mordor that only Hope and Hobbits can save you.

**Comment by tp-m** [comment]
This is really horrible API. A user should never have to provide a regexp.

I would propose that we first concentrate on the common case where `--version` prints something, and then we figure out some heuristics to read the version number from the first line of output (probably the last column, but not always).

**Comment by nirbheek** [comment]
The user doesn't have to provide a regexp, but I expect that if we implement this without any way of overriding the heuristic, we will get a bug within 1-2 months asking for it. :)

**Comment by jpakkane** [comment]
Regexes are like Turing completeness. They seem like a good idea but are not. Supporting everything + dog is just not possible. We could document that we search for a standard semantic version strings with a given command line argument (`--version` usually). That works for 90-99% of all cases out of the box and for programs that produce weirdo version numbers we can just say to get things fixed upstream because anything else is a maintenance nightmare. (not to mention that there are probably only a few binaries where people care about versions).

**Comment by pbor** [comment]
One possibility would be

find_program('pname',
    version : ">=0.1.2.3",
    version_commad : 'pname --info | grep ^version')
)

the command is optional and would default to 'pname --version', but one can point to a script if it needs to do fancy stuff

**Comment by jpakkane** [comment]
Can you give an example of a program (and its output) that would need this?

**Comment by pbor** [comment]
The comments above mention git, sed, awk etc as cases where the output and options vary a lot...
I do not have a specific use case, and I am fine with just having the version heuristic if that works most of the time

I was just mentioning it as an alternative to the regexp param. It could even avoid the version_args param.

**Comment by nirbheek** [comment]
All of those would successfully have their versions detected by the [version detect function](https://github.com/mesonbuild/meson/blob/master/mesonbuild/environment.py#L206) we have in Meson.

**Comment by shawnl** [comment]
> Regexes are like Turing completeness.

Except they are O(n). I completely disagree.

**Comment by textshell** [comment]
I think it would be useful to actually keep the guessed version for later inspection in the executable object, maybe reachable as `.version()` for situations where version specific workarounds are needed. This is a least a use case when meson modules start using this infrastructure (needed by override_find_program usage for code generators provided by subprojects with modules)

**Comment by nirbheek** [comment]
We're now [using a custom script to detect the Flex version in gstreamer](https://gitlab.freedesktop.org/gstreamer/gstreamer/merge_requests/88), which would be trivially replaced by this feature. The regex is simply: `re.search(r'(\d+\.\d+(\.\d+)?(\.\d+)?)', out).group()`
