### ISSUE TITLE
RPATH removal breaks Xorg modules

### ISSUE THREAD

**Issue by fooishbar** [mesonbuild/meson#1619]
Trying to build xorg (from github.com/anholt/xserver, branch Meson; I used `meson --prefix=~/prefix/xorg -Dxorg=yes -Dxephyr=true -Dxwayland=yes -Dglamor=yes -Dxnest=no -Ddmx=false -Dxkb_dir=/usr/share/X11/xkb -Dxkb_output_dir=/var/lib/xkb/compiled -Dhal=no -Dsystemd_logind=yes build` to build) works just fine. But the installation fails, specifically in how the RPATH removal mangles the modules.

With the default set of modules, dlopen() of modesetting_drv.so attempts to resolve a zero-length symbol:
```
[  8270.883] (II) LoadModule: "modesetting"
[  8270.883] (II) Loading /home/daniels/prefix/xorg/lib64/xorg/modules/drivers/modesetting_drv.so
[  8270.884] (EE) Failed to load /home/daniels/prefix/xorg/lib64/xorg/modules/drivers/modesetting_drv.so: /home/daniels/prefix/xorg/lib64/xorg/modules/drivers/modesetting_drv.so: undefined symbol: 
[  8270.884] (EE) Failed to load module "modesetting" (loader failed, 0)
```

Here is the file installed by `meson install`: https://static.fooishbar.org/tmp/modesetting_drv.so.broken
And here is the original: https://static.fooishbar.org/tmp/modesetting_drv.so.working
And, for completeness, the `chrpath -d` module, which also works fine: https://static.fooishbar.org/tmp/modesetting_drv.so.working.chrpath

@aaronp24 and ajax worked out that the difference was Meson NULLing out the rpath, whereas `chrpath` deletes it entirely. NULLing it out breaks entirely, because modesetting has a symbol named `modesetting`. Its rpath is also `.../hw/xorg/driver/modesetting`. Thanks to the magic of read-only data sharing, the symbol definition points to the end of the rpath string, which we've just obliterated. Oops.

Anyway, it looks like switching from `chrpath -r ''` to `chrpath -d` type semantics should fix it.

**Comment by aaronp24** [comment]
FWIW, chrpath -d doesn't actually remove the string. It leaves it completely alone and just mangles other parts of the file.
