### ISSUE TITLE
protobuf generator does not work in sub-directory

### ISSUE THREAD

**Issue by albaguirre** [mesonbuild/meson#1622]
When attempting to use the protobuf generator under a subdirectory, the build complains about missing generated files.

If we use the following setup under say <project_root>/mysubdir/meson.build

```meson
protoc = find_program('protoc')
dep = dependency('protobuf')

gen = generator(protoc, \
  output    : ['@BASENAME@.pb.cc', '@BASENAME@.pb.h'],
  arguments : ['--proto_path=@SOURCE_DIR@', '--cpp_out=@BUILD_DIR@', '@INPUT@'])

generated = gen.process('defs.proto')
e = executable('prog', 'main.cpp', generated, dependencies : dep)
test('prototest', e)
```

Under a project hierarchy like:
<project_root>/meson.build
<project_root>/mysubdir/meson.build
<project_root>/mysubdir/defs.proto

Then:
INPUT=../mysubdir/defs.proto
SOURCE_DIR=../
BUILD_DIR=mysubdir/prog@exe

protoc requires the input files to exist relative to the path given in --proto_path. It uses this relative path to generate files in path given in -cpp-out.

In this case the relative path computed by protoc is mysubdir/ therefore files are generated in "mysubdir/prog@exe/mysubdir/"

Meanwhile, the build target expects generated files to be in mysubdir/prog@exe, so the build fails.

**Comment by rhd** [comment]
Does this work?

```
gen = generator(protoc, \
  output    : ['@BASENAME@.pb.cc', '@BASENAME@.pb.h'],
  arguments : ['--proto_path=@0@'.format(meson.current_source_dir()), '--cpp_out=@BUILD_DIR@', '@INPUT@'])
```

**Comment by albaguirre** [comment]
@rhd, Unfortunately it does not. protoc does not like combining absolute and relative paths (current_source_dir() will return an absolute path on my system, but @INPUT@ is relative
