### ISSUE TITLE
Duplicate kwargs warning doesn't print filename or lineno

### ISSUE THREAD

**Issue by jon-turney** [mesonbuild/meson#1626]
```meson
project('duplicate kwarg', 'c')
a = library('liba', 'a.c')
b = library('libb', 'b.c')
executable('main', 'main.c', link_with: a, link_with: b)
```
Only the last` link_with:` has effect.

I guess this should be reported as an error.

**Comment by jon-turney** [comment]
This error (and the current warning) do not identify the meson.build file and line where the duplicate keywords is.  This is no fun with a large meson.build.

**Comment by nirbheek** [comment]
This was fixed by https://github.com/mesonbuild/meson/pull/1629, but we still don't print the filename and the line no.
