### ISSUE TITLE
Ninja include prefix wrong with italian version of Msvc 2015

### ISSUE THREAD

**Issue by guruDanny67** [mesonbuild/meson#1639]
Meson looks for the prefix to match the /showincludes directive for ninja using two colon ('Note: including file: d:\MyDir\include\stdio.h') but the italian version of the visual studio compiler puts only one and writes 'Nota: file incluso  d:\MyDir\include\stdio.h' so meson matches the second colon after the drive, using as a prefix 'Nota: file incluso  d:' (or similar, depends form where you installed things).

The net result is that the include dependecies are not working correctly but only for a a limited number of file.

For the italian part the fix is trivial, in ninjabackend.c, in detect_vs_dep_prefix(...):

```python
            if line.endswith('stdio.h'):
                # Match for italian version, with only one ':'
                if line.startswith('Nota: file incluso'):
                    matchstr = 'Nota: file incluso'
                else:
                    matchstr = ':'.join(line.split(':')[0:2]) + ':'
                with open(tempfilename, 'a') as binfile:

```

but maybe other languages have the same problem.

**Comment by msink** [comment]
What happens if you call `chcp 850` before calling meson?

[Changing MsBuild error message language](http://stackoverflow.com/questions/2286216/changing-msbuild-error-message-language)

**Comment by guruDanny67** [comment]
Nothing change (the consolle was already with codepage 850), I tried half day yesterday to change in a fast way the language for cl.exe but the only solution was to uninstall visual studio and install the english version, without the language pack.

**Comment by pbor** [comment]
Can you try the patch in https://github.com/pbor/meson/tree/wip/issue-1639 ?

**Comment by guruDanny67** [comment]
Tried it and it doen't work, the output is the same of the previous version.

The checked line (in the licplise/eclipse debug) is:

```python
 b'Nota: file incluso  C:\\\\Program Files (x86)\\\\Windows Kits\\\\10\\\\include\\\\10.0.10240.0\\\\ucrt\\\\stdio.h'
```
and the result in the ninja file is:

```python
Nota: file incluso  C:
```

**Comment by pbor** [comment]
I do not understand... that is exactly what we want, no?

**Comment by guruDanny67** [comment]
No,, there is the also teh drive letter (C:) on the line, the correct one (that works) is (without the quote)
'Nota: file incluso'

The indetect.c output is, on may machine:

Nota: file incluso  C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\stdio.h
Nota: file incluso   C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt.h
Nota: file incluso    C:\dev\vs2015\VC\INCLUDE\vcruntime.h
Nota: file incluso     C:\dev\vs2015\VC\INCLUDE\sal.h
Nota: file incluso      C:\dev\vs2015\VC\INCLUDE\ConcurrencySal.h
Nota: file incluso     C:\dev\vs2015\VC\INCLUDE\vadefs.h
Nota: file incluso   C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt_wstdio.h
Nota: file incluso    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt_stdio_config.h

With the current setup only the first include is checked (because of the indentation) and, if for some reason there are lowercase / uppercase in some of the include path even if it's the first include it's not matched.

**Comment by pbor** [comment]
Ok, sorry. Clearly I misunderstood what we wanted to match.

I have adjusted the regex, can you try now?

**Comment by guruDanny67** [comment]
Tested and it work. I also make a rapid test with a Vs2013 english installation and also there is ok.

The only thing that is different from the old one and I don't know if can cause problem with ninja is that the spaces at the end of the detected match ('Nota: file incluso    ' or 'Note: included file: ') are keep: maybe is enought a strip() before writing to the file just to avoid problems.

Thank you very much for looking at this :)

**Comment by pbor** [comment]
I kept them on purpose since my guess is that we want to strip the space as well.... if we do not want them it is enough to move the \s outside the matched group.

Thanks for testing, I will open a PR
