### ISSUE TITLE
depfixer.py's rpath fixup is broken

### ISSUE THREAD

**Issue by nwnk** [mesonbuild/meson#1640]
In attempting to convert xserver's build to meson, we noticed a mysterious failure when trying to load the "modesetting" video driver; the dlopen would fail, and dlerror would tell us something like:

`(EE) Failed to load /usr/lib64/xorg/modules/drivers/modesetting_drv.so: /usr/lib64/xorg/modules/drivers/modesetting_drv.so: undefined symbol: `

That's not a typo, it really was trying to look up a null symbol name. However simply copying the built driver into place worked just fine. The problem is that the symbol it fails to look up is named "modesetting", and the rpath emitted into the file ends in "hw/xfree86/modesetting"; string merging means the symbol name and the rpath name share storage, so zeroing out the rpath also zeros out the symbol name.

The [chrpath](https://chrpath.alioth.debian.org/) utility, in "delete" mode, simply copies the input dynamic tags to the output, skipping DT_RPATH and DT_RUNPATH and replacing them with DT_NONE terminators at the end. Personally I'd prefer using chrpath if available, but I understand meson doesn't like external dependencies, so at a minimum depfixer.py should do likewise.

Orthogonally, run-in-place for projects with dynamic libraries is perhaps not always a useful feature; if it were possible to not emit the rpath in the first place, this problem could be avoided.

**Comment by nirbheek** [comment]
Sorry if this is a stupid question, but how is this different from https://github.com/mesonbuild/meson/issues/1619? Was there something wrong with [the fix for it](https://github.com/mesonbuild/meson/pull/1620/)?

**Comment by nwnk** [comment]
D'oh. Not different at all, simply didn't see that because I failed to search through closed issues. Sorry for the noise!
