### ISSUE TITLE
ninja clean fails when a target is defined with the same name as a directory

### ISSUE THREAD

**Issue by keszybz** [mesonbuild/meson#1644]
I get the following error:
```
$ ninja-build clean
[2/2] 'Cleaning'
FAILED: clean 
'ninja-build' '-t' 'clean'
ninja: error: remove(man): Directory not empty
Cleaning... 1 files.
ninja: build stopped: subcommand failed.
```
```
$ ls -lG man/
total 8
-rw-rw-r--. 1 zbyszek  404 Apr 19 11:13 custom-entities.ent
drwxrwxr-x. 2 zbyszek 4096 Apr 19 11:13 rules/
```
So the `man` directory should not be removed at all, for two reasons: 1. there's a subdir, 2. there's a generated file. I don't know why `clean` tries to remove it.

I tried to make simple test case, but I couldn't reproduce the error. So it's something in the way that man is defined...

**Comment by keszybz** [comment]
OK, now I get it:
```meson
==> meson.build <==
project('clean1', 'c')
conf = configuration_data()
subdir('sub1')

==> sub1/meson.build <==
config2_h = configure_file(
        output : 'config2.h',
        configuration : conf)
run_target('sub1',
           command : ['echo'])
```
```sh
$ nj clean
[1/1] 'Cleaning'
FAILED: clean 
'ninja-build' '-t' 'clean'
ninja: error: remove(sub1): Directory not empty
Cleaning... 0 files.
ninja: build stopped: subcommand failed.
```

**Comment by QuLogic** [comment]
The name of the run target is the "output" of the build statement and ninja cleans things based on build outputs, so... I'm not sure how to express this in ninja.

**Comment by QuLogic** [comment]
Maybe run targets should depend on the `phony` rule instead of the made-up `CUSTOM_COMMAND`, since they aren't producing any outputs?

**Comment by nirbheek** [comment]
This is also a problem for [libgxps](https://bugzilla.gnome.org/show_bug.cgi?id=786191) and [nautilus](https://bugzilla.gnome.org/show_bug.cgi?id=786233) which have a directory called `test`. The same problem also happens if you define a directory called `benchmark`.

**Comment by nirbheek** [comment]
> Maybe run targets should depend on the `phony` rule instead of the made-up `CUSTOM_COMMAND`, since they aren't producing any outputs?

Can't use `phony` because that means the target is an alias for some other target and if you don't specify some other target it means that it does nothing. The `COMMAND =` line will get ignored in either case.

What we *could* do, to work around this Ninja bug, is to define targets called `meson-test`, `meson-benchmark`, and `meson-RUN_TARGET_NAME` which do the actual work, and have `test`, `benchmark`, `RUN_TARGET_NAME` as aliases for that. I've tested and this does work.

However, simultaneously we should try to fix this in Ninja too.

**Comment by jpakkane** [comment]
The test target is tagged phony and it works just fine (just runs a command). Marking run targets with PHONY should work.

I just tested by creating a directory called test in a build dir and running `ninja test`. It works as it should.

**Comment by nirbheek** [comment]
> I just tested by creating a directory called test in a build dir and running ninja test. It works as it should.

That's not the problem. The problem is that `ninja clean` fails if you define any targets inside a directory called `test` (or `benchmark` or any other `CUSTOM_COMMAND` target).

**Comment by nirbheek** [comment]
FWIW, the upstream bug for the general problem of not recursively deleting directories on non-Windows platforms is https://github.com/ninja-build/ninja/issues/828.

**Comment by jpakkane** [comment]
Okay, let's put in the workaround with a link to that bug.
