### ISSUE TITLE
b_lto=true does not work with static libraries

### ISSUE THREAD

**Issue by keszybz** [mesonbuild/meson#1646]
Meson uses `ar 'csrD'` to link libraries. When b_lto is turned on, this stops working.
gcc-ar must be used instead:
```c
==> meson.build <==
project('ltotest', 'c',
	default_options : ['b_lto=true'])
libfoo = static_library('foo',
			'foo.c',
			'foo.h')
bar = executable('bar',
		 'bar.c',
		 link_with : libfoo,
		 install : true)

==> foo.h <==
int foo(void);

==> foo.c <==
#include "foo.h"

int foo(void) {
  return 11;
}

==> bar.c <==
#include "foo.h"

int main(int argc, char **argv) {
  return 11 - foo();
}
```
```
The Meson build system
Version: 0.40.0.dev1
Source dir: /home/zbyszek/src/meson/meson9
Build dir: /home/zbyszek/src/meson/meson9/build
Build type: native build
Project name: ltotest
Native c compiler: ccache cc (gcc 6.3.1)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Build targets in project: 2
```
```
ninja: Entering directory `build/'
[3/4] Static linking library libfoo.a
ar: foo@sta/foo.c.o: plugin needed to handle lto object
[4/4] Linking target bar
FAILED: bar 
ccache cc  -o bar 'bar@exe/bar.c.o' '-flto' '-Wl,--no-undefined' '-Wl,--as-needed' '-Wl,--whole-archive' '-Wl,--no-whole-archive' 'libfoo.a'  
/tmp/ccbGdQ6K.ltrans0.ltrans.o: In function `main':
<artificial>:(.text+0x10): undefined reference to `foo'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```
When `gcc-ar` is used instead of `ar`, `libfoo.a` is generated without warnings, and `bar` links correctly.

**Comment by nirbheek** [comment]
Using `gcc-ar` instead of `ar` fixes it for GCC but not for Clang. It seems like statically linking LTO objects is unsupported on Clang? Can someone confirm that please? The unit test I wrote for GCC definitely fails on Clang:

```
The Meson build system
Version: 0.40.0.dev1
Source dir: test cases/common/5 linkstatic
Build dir: /tmp/tmprw3vy_eo
Build type: native build
Project name: static library linking test
Native c compiler: clang (clang 3.9.1)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Build targets in project: 2

[1/7] Compiling c object 'prog@exe/main.c.o'
[2/7] Compiling c object 'mylib@sta/libfile3.c.o'
[3/7] Compiling c object 'mylib@sta/libfile.c.o'
[4/7] Compiling c object 'mylib@sta/libfile2.c.o'
[5/7] Compiling c object 'mylib@sta/libfile4.c.o'
[6/7] Static linking library libmylib.a
[7/7] Linking target prog
FAILED: prog 
clang  -o prog 'prog@exe/main.c.o' '-flto' '-Wl,--no-undefined' '-Wl,--as-needed' 'libmylib.a'  
libmylib.a: error adding symbols: Archive has no index; run ranlib to add one
clang-3.9: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

The error is strange because running `ranlib` is equivalent to passing `-s` to `ar`, which we do.

It also looks like `gcc-ar` is equivalent to `ar --plugin /usr/libexec/gcc/x86_64-redhat-linux/6.3.1/liblto_plugin.so`, and that should be [done automatically by `ar`](https://gcc.gnu.org/wiki/LinkTimeOptimizationFAQ#ar.2C_nm_and_ranlib), but it isn't.

So by using `gcc-ar` when available instead of `ar`, we'd be working around a binutils bug, which is fine, but we should document it as such.

**Comment by nirbheek** [comment]
See #1649 for a unit test. To run it, you can do:

```console
$ ./run_unittests.py AllPlatformTests.test_static_library_lto -v
```

**Comment by jpakkane** [comment]
I had an lto Arduino build where LTO stopped working randomly (I had last used it ages ago). It used to work but fails now in the exact same way (standard Ubuntu Arduino toolchain, 4.9.2 or something). This seems to be a GCC regression. Has it been reported upstream?

**Comment by nirbheek** [comment]
It's supposed to work in some version of binutils but it's not clear what that version is supposed to be. It does not work on my machine with binutils 2.26.1.

**Comment by keszybz** [comment]
binutils-2.28-5.fc27.x86_64 – same result.

**Comment by nirbheek** [comment]
Just to be clear, this is not a GCC bug, it's possibly a binutils bug. 

As an aside, in the course of my testing I found out that to support LTO with static libraries on Clang, you need to use `llvm-ar`, so since we need special-casing for that, it doesn't hurt to add the same for `gcc-ar` too.

**Comment by nirbheek** [comment]
It *would* be really nice to be able to accurately deduce the correct `--plugin` argument to pass to `ar` though.

**Comment by nirbheek** [comment]
@keszybz could you please test https://github.com/mesonbuild/meson/pull/1649 with GCC and Clang on systemd?
