### ISSUE TITLE
Promote build_target linker to C++ if linking to C++ libraries

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#1653]
Sometimes people link to C++ libraries that export C APIs, but still link to libstdc++. For example: https://bugzilla.gnome.org/show_bug.cgi?id=781561

Need a test case from @dcbaker for this, and then it can be fixed by adding a special case in `build.py:BuildTarget.get_clike_dynamic_linker()`.

**Comment by dcbaker** [comment]
I've sent a pull request. Interestingly the test passes on 0.39.1, but no against master, so I think this is actually a regression.

**Comment by dcbaker** [comment]
@nirbheek I bisected this down to this commit from you:

```
commit 14d0f381580222f4b4eac376f514fcfcfdb6ee4c
Author: Nirbheek Chauhan <nirbheek@centricular.com>
Date:   Fri Mar 24 18:31:22 2017 +0530

    Try harder to use the C compiler for compiling asm

    Use an ordered dict for the compiler dictionary and sort it according
    to a priority order: fortran, c, c++, etc.

    This also ensures that builds are reproducible because it would be
    a toss-up whether a C or a C++ compiler would be used based on the
    order in which compilers.items() would return items.

    Closes https://github.com/mesonbuild/meson/issues/1370
```

**Comment by nirbheek** [comment]
Right, I thought that might be responsible for this. We traded one bug for one regression. :)

**Comment by nirbheek** [comment]
To see the planning fallacy in action, see how often I add and then remove the "easy" tag on bugs.

**Comment by dcbaker** [comment]
Since this is a regression this should get fixed before the next release, correct?

**Comment by nirbheek** [comment]
Hmm true, I thought we released 0.39.1 with that regression, but it seems I broke it after the last release. So we should indeed fix this before release.

**Comment by ePirat** [comment]
@nirbheek How do you detect if linking to a C++ lib? For example in VLC we have the following case: the vulkan module links with libplacebo, libplacebo itself is a C library and uses glslang which is a C++ library. This breaks with autotools when statically linked glslang + libplacebo is linked into the shared vulkan module. Can meson somehow detect this case? Or will I need the `link_language` kwarg in that case?

**Comment by dcbaker** [comment]
This only works with internal libraries, basically it says "liba was compiled and linked with c++, so libb which link_with's liba also needs to be c++". This internal logic is why I wan't to put the `link_language` in the `find_library()` and `dependency()` function instead of the library, since meson already knows how to handle linking various langauges together.

**Comment by ePirat** [comment]
Any update on this? It's a problematic issue for my VLC port and so far I just use a dummy-meson.cpp which is very ugly.

**Comment by alyssais** [comment]
I've opened an issue about using the right compiler to link C++ dependencies of C projects: https://github.com/mesonbuild/meson/issues/14234
