### ISSUE TITLE
meson should error out  or warn on unknown options

### ISSUE THREAD

**Issue by mbiebl** [mesonbuild/meson#1655]
When trying to use an incorrect/unknown switch using autotools, one gets:
```
./configure --disable-foo
...
configure: WARNING: unrecognized options: --disable-foo
```
Doing the same with meson does not result in an error or warning:
```
meson .. -Dfoo=false
→ no warning
```

**Comment by TingPing** [comment]
Duplicate of #932

**Comment by mbiebl** [comment]
> Duplicate of #932

Indeed, closing this duplicate
