### ISSUE TITLE
compiler object compiles() does not track changes to the files being compiled

### ISSUE THREAD

**Issue by jnikula** [mesonbuild/meson#1656]
The compiler object compiles() method does not take into account changes to the file object being compiled. For example,

```
project('foo', 'c')
cc = meson.get_compiler('c')
test = cc.compiles(files('foo.c'))
```

won't get re-evaluated if `foo.c` changes.

I presume the same applies to link() too, but did not try.

**Comment by nirbheek** [comment]
The same also happens for `configure_file()` when the `input:` kwarg is used. We should probably check all API for this problem.

**Comment by eli-schwartz** [comment]
For configure_file, this was added in commit f0565e6dc80c857b6035b9a754b0495137db64ae.
