### ISSUE TITLE
`ninja clean` fails to remove test file build directory

### ISSUE THREAD

**Issue by MatthewScholefield** [mesonbuild/meson#1659]
I followed [this tutorial on the wiki page][1] to setup meson for a simple library with tests. When running `ninja clean`, I get `ninja: error: remove(test): Directory not empty` because an empty subdirectory, `testexe@exe` still exists. This happens under both Windows and Linux. Under normal behavior, I would expect this to be removed since it was created automatically.

test/build.meson
```
testexe = executable('testexe', test_sources,
					include_directories : inc,
					link_with : lib)
test('lib test', testexe)
```

I tried cheating and adding `custom_target('generated-folder', command : '', output : 'testexe@exe')` but since the custom targets get removed before the build targets, the first time the executable is still in there and it fails (but works the second time I run `ninja clean`).

[Similar issue for slightly different issue (that was closed and seemed to be solved)][2]

[1]:https://github.com/mesonbuild/meson/wiki/IndepthTutorial
[2]:https://github.com/mesonbuild/meson/issues/1220

**Comment by nirbheek** [comment]
This also affects [libgxps](https://bugzilla.gnome.org/show_bug.cgi?id=786191) and nautilus. We should try and get this fixed soon, preferably before the release.

**Comment by nirbheek** [comment]
Amazingly, this only happens if the directory is called 'test' in the root source directory. Renaming `test/meson.build` to `tests/meson.build` fixes it. There is no difference in the generated `build.ninja` files in either case, so this is looking like a Ninja bug.

**Comment by nirbheek** [comment]
Same as https://github.com/mesonbuild/meson/issues/1644
