### ISSUE TITLE
meson 0.40.0 doesn't use cross-compilation property `cpp_args` in `has_header` method.

### ISSUE THREAD

**Issue by mgautierfr** [mesonbuild/meson#1665]
We use a dependency project who has not a pc file.
So we use the old method of checking for the header and lib using the compiler's `has_header` and `find_library` methods.

On top of that, when cross-compiling to windows using mingw we need to define `WIN32`. Else the compilation fails because the dependency's headers do not "detect" the platform correctly.
For that, we have the property `cpp_args = ['-DWIN32']` in the meson cross-file (same for `c_args`).

With last version (0.40.0) of meson, the `cpp_args` seems to not being used in the `has_header` method. So the "compilation check" fails and meson assumes the header is not present.
If version 0.39.1, the `cpp_args` is used in `has_header` and everything works fine.

**Comment by nirbheek** [comment]
You are correct, we should indeed be adding `c_args` and `cpp_args` from the cross-info file even when doing checks that only run the pre-processor such as `has_header()`.
