### ISSUE TITLE
Qt release library is added in debug build 

### ISSUE THREAD

**Issue by brokenbug** [mesonbuild/meson#1671]
Using meson on windows 10 and visual studio 2015.

In the generated project, release versions of QT libraries are added when building debug. Example Qt5Core.lib is added instead of Qt5Core**d**.lib. All QT debug libraries has a "d" appended to their name. 
The release libraries creates some issues. E.g conversion from QString to std::string crashes.

I don't know the Python language, but if I read the code correctly then I believe the issue is located in dependenies.py, row 1145.
`
libfile = os.path.join(libdir, self.qtpkgname + module + '.lib')
` 
I think it should be 
`libfile = os.path.join(libdir, self.qtpkgname + module + 'd.lib')`
in debug builds.

**Comment by nirbheek** [comment]
Does the Qt installer install both debug and non-debug libraries or do you need separate installers for each?

**Comment by brokenbug** [comment]
It installs both.

Screendump example:
![qtinstalllibs](https://cloud.githubusercontent.com/assets/15131458/25382871/c79a7552-29b9-11e7-8bb7-0d5cda2425db.PNG)

**Comment by jeandet** [comment]
Seems fixed [here](https://github.com/mesonbuild/meson/blob/master/mesonbuild/dependencies/ui.py#L301), feel free to reopen the bug if it's not.
