### ISSUE TITLE
VS 2017 backend emits bad ProjectGuid value

### ISSUE THREAD

**Issue by RedSkotina** [mesonbuild/meson#1672]
When I tried generating a VS 2017 solution, all generated *.vcxproj contained this:

```
<PropertyGroup Label="Globals">
		<ProjectGuid>64FCBDC2-8B6E-45D3-AEE0-DA999A2C7A64</ProjectGuid>
</PropertyGroup>
```
Which then causes silent errors in visual studio 2017 IDE: project dont expand in solution explorer
 Reason - ProjectGuid value should contain brackets: 
`<ProjectGuid>{64FCBDC2-8B6E-45D3-AEE0-DA999A2C7A64}</ProjectGuid>`

**Comment by nirbheek** [comment]
Is this also how Guids should be in older versions of Visual Studio?

**Comment by pbor** [comment]
Yes
