### ISSUE TITLE
docs for test suite

### ISSUE THREAD

**Issue by rhd** [mesonbuild/meson#1674]
I noticed that the testing suite logic has changed. I can no longer run `ninja <suitename>` but instead I have to run `mesontest` - which is OK even though I will miss using `ninja` for the simple cases besides `ninja test`.

Anyway, I can't seem to find the docs for test suites anywhere.

Not [here](https://github.com/mesonbuild/meson/wiki/Reference-manual#test) or [here](https://github.com/mesonbuild/meson/wiki/Unit-tests).

I used to be able to type `ninja test-app` to run all of the app tests or `ninja-app-test1` to run just the test called `app-test1` - these were defined in the `suite` section of the `test()`.

This was my old logic:

```meson
runtest = find_program('runTest')

defaultTimeout = 600

tests = [
    ['test1', defaultTimeout],
]

foreach test: tests
    testname = test[0]
    timeout = test[1]
    longtestname = 'app-' + testname

    test(longtestname, runtest,
        args: ['-t', testname, '-l', exedir],
        suite: ['app', longtestname],
        timeout: timeout,
        is_parallel: false,
    )
endforeach
```

**Comment by harikumar6264** [comment]
I am facing "No suitable tests defined".
Can you please explaine how to use --suite option in meson with example
How to add test cases to suite
