### ISSUE TITLE
RFE: add compiler.has_link_argument

### ISSUE THREAD

**Issue by keszybz** [mesonbuild/meson#1676]
There doesn't seem to be a succinct way to check if a compiler arg is supported:
- compiler.has_argument() does no linking
- compiler.links() doesn't seem to have a way to specify compiler arguments (dependencies must be external dependencies).

**Comment by nirbheek** [comment]
Makes sense to add this, yes. Should be easy to do.

**Comment by superm1** [comment]
As I can tell this was fixed in https://github.com/mesonbuild/meson/commit/bd37afeeea0283dac1051b7d9bedf099252c1d19
