### ISSUE TITLE
-L flags returned by pkg-config should not change the order of LDFLAGS

### ISSUE THREAD

**Issue by lantw44** [mesonbuild/meson#1718]
`generate_link` in `mesonbuild/backend/ninjabackend.py` uses `mesonbuild.compilers.CompilerArgs` to collect linking arguments. External dependencies are processed after `c_link_args`, which means pkg-config can change the order of `c_link_args` set by users.

Simple meson.build file used to reproduce the issue:
```meson
project('testproject', 'c')
executable('testproject', 'main.c', dependencies: [ dependency('glib-2.0') ])
```
`LDFLAGS` set by jhbuild:
```
-L/home/lantw44/gnome/devinstall/lib -L/usr/local/lib
```
`pkg-config --libs glib-2.0`:
```
-L/usr/local/lib -lglib-2.0 -lintl
```
After running `meson`, `mesonconf` shows the correct linker arguments:
```
Linker args:
  c_link_args ['-L/home/lantw44/gnome/devinstall/lib', '-L/usr/local/lib']
```
However, querying commands with `ninja` shows that linker arguments are used in a wrong order:
```
ccache cc  -o testproject 'testproject@exe/main.c.o' '-L/usr/local/lib' '-L/home/lantw44/gnome/devinstall/lib' '-Wl,--no-undefined' '-Wl,--as-needed' '-lglib-2.0' '-lintl'
```

This causes undefined reference error when building gst-plugins-base in a jhbuild environment on FreeBSD. When a sysdep like `orc-0.4` is used, `-L/usr/local/lib` is moved to the front of `-L/home/lantw44/gnome/devinstall/lib`, causing the linker to find the old version of `libgstreamer-1.0.so` installed in `/usr/local/lib` instead of the new version installed in jhbuild prefix.

**Comment by nirbheek** [comment]
Yes, this is a bug. Basically, when you append an array to a `CompilerArgs()` object, it assumes that it was ordered in the same way as another `CompilerArgs()` object (which would need reordering). However, the `link_args` and `c_args` we get from the user are supposed to be appended as a unit without any reordering.

**Comment by nirbheek** [comment]
Actually, I may have been wrong about this being a bug in CompilerArgs. I think it's just that we currently give higher priority to the args added by a dependency over `LDFLAGS`. Will investigate a bit.

**Comment by lantw44** [comment]
This bug has caused a lot of build problems that are impossible to fix without patching meson in jhbuild environment on FreeBSD, so I spent time comparing output generated by meson and autotools today.

It seems that meson adds arguments in this order:
`add_*_link_arguments() -> LDFLAGS -> internal deps -> external deps`

This implies that the importance of these flags are:
`external deps > internal deps > LDFLAGS > add_*_link_arguments()`

If we ignore internal deps, which don't seem to include -L options, it can be simplified to:
`external deps > LDFLAGS > add_*_link_arguments()`

I think it is not expected for users to manually add -L options, so the list becomes:
`external deps > LDFLAGS`

This doesn't seems to be correct because the list of external deps is usually not ordered in any meaningful way. Making external deps the most significant source of link arguments means users cannot control the order of -L options.


Let's see what automake and libtool do by building gtk3 with autotools. Open the generated file `gtk/Makefile` and find the rule used to build `libgtk3-la`:
```
libgtk_3_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
    $(LIBTOOLFLAGS) --mode=link $(CCLD) $(libgtk_3_la_CFLAGS) \
    $(CFLAGS) $(libgtk_3_la_LDFLAGS) $(LDFLAGS) -o $@
libgtk-3.la: ...
    $(AM_V_CCLD)$(libgtk_3_la_LINK) -rpath $(libdir) $(libgtk_3_la_OBJECTS) $(libgtk_3_la_LIBADD) $(LIBS)
```
The order of link arguments is:
`target-specific LDFLAGS -> user-set LDFLAGS -> external deps`

libtool processes -L options specified on command line from left to right. When it finds a duplicate -L option, it skips the `func_append` call without changing the order of already added arguments. Therefore, the importance of flags is the same as the order specified on command line:
`target-specific LDFLAGS > user-set LDFLAGS > external deps`

Since it is not expected for users to add any -L or -l options in target-specific LDFLAGS or global LDFLAGS, it can be simplified to:
`LDFLAGS > external deps`

Sometimes libtool makes -L options from .la files and adding them before -L options specified on command line. I think .la files are similar to internal deps in meson because most distributions don't include .la files in their packages, and .la files do cause a lot of linking troubles when FreeBSD ports still install them. JHBuild automatically deletes .la files after 'make install'.
`internal deps > LDFLAGS > external deps`

Is it possible to make meson behave like libtool, where user-set LDFLAGS have precedence over external deps? I think It is acceptable for internal deps to override LDFLAGS because it is sometimes necessary to ensure newly-built versions are used instead of already-installed versions and they are unlikely to include -L options pointing to installation directories.

**Comment by nirbheek** [comment]
> Is it possible to make meson behave like libtool, where user-set LDFLAGS have precedence over external deps?

You mean the `LDFLAGS` variable? Yes, that is possible, and I think we should do that too. It's a simple change. I'll make a PR for it.

**Comment by nirbheek** [comment]
FWIW, in general, you want to make Meson's detected external dependencies point to your jhbuild prefix instead of detecting the system dependencies. This is usually achieved by pointing `PKG_CONFIG_PATH` or `PKG_CONFIG_LIBDIR` to your prefix.

We will fix this because `LDFLAGS` and `CFLAGS`, etc, should always override all other sources of flags, but using that to override detected dependency paths is not going to be reliable.

**Comment by nirbheek** [comment]
Can you try https://github.com/mesonbuild/meson/pull/1925?

**Comment by jpakkane** [comment]
> The order of link arguments is: target-specific LDFLAGS -> user-set LDFLAGS -> external deps

But the Makefile says this:

libgtk_3_la_LINK = <stuff removed>$(libgtk_3_la_CFLAGS) $(CFLAGS) $(libgtk_3_la_LDFLAGS) $(LDFLAGS) -o $@

Which very clearly states that LDFLAGS does not override linker search directories. First it gets `-L/home/whatever` and only after that `-L/usr/local/lib` from ldflags.

The bug we have is this:

    ccache cc  -o testproject 'testproject@exe/main.c.o' '-L/usr/local/lib' '-L/home/lantw44/gnome/devinstall/lib' '-Wl,--no-undefined' '-Wl,--as-needed' '-lglib-2.0' '-lintl'

Which is the exact opposite. The bug is caused by the fact that LDFLAGS _does_ override pkg-config settings because its -L argument is used first. 

> We will fix this because LDFLAGS and CFLAGS, etc, should always override all other sources of flags

There might be a terminology issue here. What we mean is that between settings in LDFLAGS and per-target settings, the _latter_ should always be the ones to use. For arguments that set search flags it means that per-target arguments must be _earlier_ on the command line but for other flags (such as `-Wl,--do_something=foo`) they must come _later_.

**Comment by lantw44** [comment]
> The order of link arguments is: target-specific LDFLAGS -> user-set LDFLAGS -> external deps
> 
> But the Makefile says this:
> 
> libgtk_3_la_LINK = $(libgtk_3_la_CFLAGS) $(CFLAGS) $(libgtk_3_la_LDFLAGS) $(LDFLAGS) -o $@
> 
> Which very clearly states that LDFLAGS does not override linker search directories. First it gets -L/home/whatever and only after that -L/usr/local/lib from ldflags.

`libgtk_3_la_LDFLAGS` cannot include -L options because options required by dependencies are listed in `libgtk_3_la_LIBADD`, so the first -L option found by the linker is in user-set LDFLAGS unless libtool decides that it is required to add -L options for internal deps.

> 
> The bug we have is this:
> 
> ccache cc  -o testproject 'testproject@exe/main.c.o' '-L/usr/local/lib' '-L/home/lantw44/gnome/devinstall/lib' '-Wl,--no-undefined' '-Wl,--as-needed' '-lglib-2.0' '-lintl'
> 
> Which is the exact opposite. The bug is caused by the fact that LDFLAGS does override pkg-config settings because its -L argument is used first.

No, my LDFLAGS is `-L/home/lantw44/gnome/devinstall/lib -L/usr/local/lib`. The -L flag returned by pkg-config is `-L/usr/local/lib`. pkg-config overrides LDFLAGS by changing the order of -L flags.

I know this issue is not easy to reproduce with the simple example given in the issue description, and I  didn't describe the problem very clearly. I will upload another example to demonstrate the problem.

**Comment by jpakkane** [comment]
> My LDFLAGS is -L/home/lantw44/gnome/devinstall/lib -L/usr/local/lib. The -L flag returned by pkg-config is -L/usr/local/lib. pkg-config overrides LDFLAGS by changing the order of -L flags.

Just to be sure:

 - you run the configure step with `LDFLAGS='-L/home/lantw44/gnome/devinstall/lib -L/usr/local/lib' meson <other args>`?
 - pkg-config when run by Meson returns library flags `-L/usr/local/lib`?
 - when building, the "home" path is the correct one that should be used?

**Comment by lantw44** [comment]
> Just to be sure:
>     you run the configure step with LDFLAGS='-L/home/lantw44/gnome/devinstall/lib -L/usr/local/lib' meson <other args>?
>     pkg-config when run by Meson returns library flags -L/usr/local/lib?
>     when building, the "home" path is the correct one that should be used?

Yes, I know it doesn't look like a valid use case, The example in the description was only used to show that the order of -L options can be changed by pkg-config. To avoid confusion, I am going to upload a more complete example to explain the use case of jhbuild on FreeBSD.

**Comment by lantw44** [comment]
[meson-ldflags-test.zip](https://github.com/mesonbuild/meson/files/1066485/meson-ldflags-test.zip)

In this example, we have two libraries installed in two different prefixes. `/usr_upper` contains newer versions of libraries, which is similar to a jhbuild prefix. `/usr_lower` contains older versions of libraries, which is similar to the prefix managed by FreeBSD ports and packages.

There are two libraries included in this example. `libxxx` is installed in `/usr_lower`. `libyyy` is installed in both `/usr_lower` and `/usr_upper`. The version installed in `/usr_upper` is newer then the version installed in `/usr_lower`.

`PKG_CONFIG_PATH` is set to `/usr_upper/lib/pkgconfig:/usr_lower/lib/pkgconfig`, so the new version of `libyyy` is always found before the old version of `libyyy`.

`LDFLAGS` is set to `-L/usr_upper/lib -L/usr_lower/lib` to ensure the correct order of -L options is used.

Now we have an application called `myapp` that uses both `libxxx` and `libyyy`. It uses a symbol that is only available in the new version of `libyyy`. We have set correct `PKG_CONFIG_PATH` and `LDFLAGS` for meson to find the correct version of `libyyy`, but we get undefined reference error if dependencies is specified as `[ yyy, xxx ]` because -L options returned by `pkg-config --libs libxxx` overrides user-set LDFLAGS.

**Comment by jpakkane** [comment]
> LDFLAGS is set to -L/usr_upper/lib -L/usr_lower/lib to ensure the correct order of -L options is used.

This is wrong. The correct flags _must_ come from pkg-config. Trying to fix things afterwards by dropping random linker flags is not the correct solution. 

> we get undefined reference error if dependencies is specified as [ yyy, xxx ] because -L options returned by pkg-config --libs libxxx overrides user-set LDFLAGS.

The bug here is that the order in which the lib dirs are added for dependencies. This should result in the final search order of `path as specified by pc file in /usr_upper/lib/pkgconfig` then by `path as specified by pc file in /usr_lower/lib/pkgconfig` and only then `lib dir as specified in LDFLAGS if any`.

Thinking even further pkg-config should never even return -L files, but instead absolute paths to the libraries it uses. However we'll probably never get that one fixed so we just have to live with it.

**Comment by jpakkane** [comment]
Doing what you propose will break everything outside of JHBuild. Assume that you set LDFLAGS to `-L/usr/local/lib` and further assume that you have libfoo in `/home/name/devroot/lib` and a pc file that points to it. Then if you try to build it you get `-L/home/name/devroot/lib` as expected but then the global LDFLAGS overrides it so all linker invocations will pick up the version in `/usr/local/lib`. You can _not_ tell it to use the other version which is the correct thing to do in most cases and further is the behaviour people expect when pointing `PKG_LIBRARY_PATH` to that directory.

**Comment by jpakkane** [comment]
Would it be possible for you to try #1928 on your problem case? It's mostly an experiment but it would be useful to know if it would fix the issue?

**Comment by lantw44** [comment]
> > LDFLAGS is set to -L/usr_upper/lib -L/usr_lower/lib to ensure the correct order of -L options is used.
> 
> This is wrong. The correct flags must come from pkg-config. Trying to fix things afterwards by dropping random linker flags is not the correct solution.

The problem is that neither pkg-config nor meson knows how to figure out the correct -L order. Meson calls pkg-config for each package and merges them using its own way. Even if meson is modified to call pkg-config only once with all required packages, it still doesn't work.

Currently cairo is a system dependency in GNOME jhbuild modulesets, and GLib is always built from upstream git. If we run `pkg-config --libs glib-2.0 cairo`:
```
-L/home/lantw44/gnome/devinstall/lib -lglib-2.0 -lintl -L/usr/local/lib -lcairo -lpthread
````
This is correct. However, if we run `pkg-config --libs cairo glib-2.0`:
```
-L/usr/local/lib -lcairo -lpthread -L/home/lantw44/gnome/devinstall/lib -lglib-2.0 -lintl
```
The order is incorrect. Developers never know which order they should use because the correct order depends on users' environments.

We used to set `-Wl,-Y/usr/local/lib` in LDFLAGS when using jhbuild on FreeBSD to avoid some -L order problems. I am not sure whether we should bring it back ...


> The bug here is that the order in which the lib dirs are added for dependencies. This should result in the final search order of path as specified by pc file in /usr_upper/lib/pkgconfig then by path as specified by pc file in /usr_lower/lib/pkgconfig and only then lib dir as specified in LDFLAGS if any.
> 

Does this mean meson will use PKG_CONFIG_PATH to sort the list of dependencies? This seems to be a good solution. It seems that meson will have to know the full paths to .pc files in order to sort them. How will it work if an application use both pkg-config and non-pkg-config dependencies?

> Thinking even further pkg-config should never even return -L files, but instead absolute paths to the libraries it uses. However we'll probably never get that one fixed so we just have to live with it.

Yes, I agree. The -L order issue is always a problem that takes much time to fix. If meson can convert -L and -l flags returned by pkg-config to full paths to libraries, it will be unlikely to see -L order issue. However, it is not easy to implement this feature because we have to support many platforms ...

> Doing what you propose will break everything outside of JHBuild. Assume that you set LDFLAGS to -L/usr/local/lib and further assume that you have libfoo in /home/name/devroot/lib and a pc file that points to it. Then if you try to build it you get -L/home/name/devroot/lib as expected but then the global LDFLAGS overrides it so all linker invocations will pick up the version in /usr/local/lib. You can not tell it to use the other version which is the correct thing to do in most cases and further is the behaviour people expect when pointing PKG_LIBRARY_PATH to that directory.

If you have a devleopment prefix in your home directory, isn't it common to set CPPFLAGS and LDFLAGS to include both prefixes, just like `-L/home/name/devroot/lib -L/usr/local/lib` done by jhbuild?
