### ISSUE TITLE
Meson mistakenly reports executable keyword name_suffix as unknown

### ISSUE THREAD

**Issue by noverby** [mesonbuild/meson#1728]
When using the following code:
`executable('hello-world', 'main.c', name_suffix:'js')`
Meson reports:
`WARNING: Unknown keyword argument(s) in target hello-world: name_suffix.`

**Comment by QuLogic** [comment]
This appears to be a documentation issue, as it looks like it accepts `suffix`.

**Comment by noverby** [comment]
But name_suffix also changes behaviour.

**Comment by noverby** [comment]
Same problem with suffix:
`WARNING: Unknown keyword argument(s) in target hello-world: suffix.`
