### ISSUE TITLE
No way to include subproject headers under subdirectory

### ISSUE THREAD

**Issue by MatthewScholefield** [mesonbuild/meson#1729]
What I mean is, if I have a library that installs its headers under a subdirectory like `/usr/local/mylib/headers.h`, naturally, in the code I would include the library with `#include <mylib/headers.h>` however, if using `mylib` as a subproject, the headers will be included directly, thus requiring `#include <headers.h>`. Example:

`subprojects/mylib/meson.build`:
```meson
project('mylib', 'cpp')
# ...
install_headers(headers, subdir : 'mylib')
dep = declare_dependency(link_with : lib,
	include_directories : inc)
```
`meson.build`:
```meson
project('myapp', 'cpp')
sp = subproject('mylib')
deps = sp.get_variable('dep')
exe = executable('myapp', 'main.cpp', dependencies : deps)
```
`main.cpp`:
```C++
#include <mylib/headers.h>

int main()
{
    // ...
}
```

Result:
```gcc
main.cpp:1:27: fatal error: mylib/headers.h: No such file or directory
```
However, `#include <headers.h>` would work fine.

**Comment by TingPing** [comment]
Including paths in includes is always a bad idea, one way some projects work around this is just having their source directory match their include directory name.

**Comment by rhd** [comment]
IMO, the right answer to to have your change your project layout so you have a `mylib/include/mylib/headers.h` - this way everyone who uses your lib's headers (including `mylib` itself) must do `#include <mylib/headers.h`.

**Comment by MatthewScholefield** [comment]
Yeah, I don't really see the use of the subdir argument to install_headers if there's no way (using that parameter) to force consistency between the installed library and ones that include it as a subproject.

**Comment by nirbheek** [comment]
There really is no way to tell the compiler that you must strip a particular prefix from `#include` lines while looking for headers. People should be able to use the same code to include your header when compiling against it installed or uninstalled. I'm closing this bug report, I hope that makes sense!
