### ISSUE TITLE
VSCode Syntax highlighting

### ISSUE THREAD

**Issue by navidR** [mesonbuild/meson#1743]
VSCode became kinda de facto text editor for most people (like myself). I think we need an official extension with minimum functionallity fo VSCode. Noting fancy, I think syntax highlighting is enough.

**Comment by jpakkane** [comment]
Does upstream accept feature requests? (and if yes, do they fullfill them)

**Comment by TingPing** [comment]
Here you go, just needs packaging: https://github.com/TingPing/language-meson

**Comment by asabil** [comment]
I have repackage @TingPing 's atom extension for vscode, you can find It here: https://marketplace.visualstudio.com/items?itemName=asabil.meson
