### ISSUE TITLE
How do I choose which compiler Meson will use?

### ISSUE THREAD

**Issue by tbodt** [mesonbuild/meson#1752]
The default is `cc` and I want to use `clang`, but there doesn't seem to be an option in mesonconf...

**Comment by TingPing** [comment]
`env CC=clang meson ...`

**Comment by dcbaker** [comment]
The canonical way is to pass an environment variable:
`CC=clange meson...`

**Comment by tbodt** [comment]
```
Error during basic setup:

Trying to run Meson on a build directory that has already been configured.
If you want to build it, just run your build command (e.g. ninja) inside the
build directory. Meson will autodetect any changes in your setup and regenerate
itself as required.

If you want to change option values, use the mesonconf tool instead.
```

**Comment by tbodt** [comment]
So I have to delete my build directory?

**Comment by dcbaker** [comment]
Yes, or create a second build directory for clang

**Comment by tbodt** [comment]
Alright then.

**Comment by Seraphime** [comment]
I'm interested in having a directive inside the meson.build file to force the compiler to a specific option.
Is there something upstream which can help me achieve this or if not, would it be useful to have this upstream ? 

For instance, bazel can be configured to use a specific toolchain

**Comment by nirbheek** [comment]
> I'm interested in having a directive inside the meson.build file to force the compiler to a specific option.

Can you give an example of what you're looking for? Most of this is already possible in Meson.

**Comment by Seraphime** [comment]
I'm looking for a way to have my meson.build not depend on environment variables and have everything it needs in itself.

**Comment by nirbheek** [comment]
You're looking for the native file feature: https://mesonbuild.com/Release-notes-for-0-49-0.html#native-config-files

**Comment by cheofusi** [comment]
I still think it would be much cooler to pick a compiler from the available compilers for a given lang in the build file. I think this benefits others who want to rebuild your code as it'll prevent them from manually editing the native-config-file too.

**Comment by eli-schwartz** [comment]
No, it just stops them from using their own compiler... There's no reason to force people to use clang and error out if all they have is gcc.

Meson has separation between project build descriptions in meson.build, and compilation environment / toolchain descriptions in native/cross files.

**Comment by g-berthiaume** [comment]
While [dcbaker](https://github.com/dcbaker)'s solution will work on linux, it won't on windows.
```
meson build-gcc
CC=clang CXX=clang++ meson build-clang
```

Instead, I fix the problem using a "native-file":
```powershell
$ meson --native-file=meson-native-clang build-clang
```
where `meson-native-clang` is the native file:
```toml
[binaries]
c = 'C:\Users\me\scoop\apps\llvm\current\bin\clang.exe'
cpp = 'C:\Users\me\scoop\apps\llvm\current\bin\clang++.exe'
````

**Comment by aaronsuydam** [comment]
I've got a question on this, I am working with heterogeneous compute frameworks, a lot of which have their own dedicated C++ compiler drivers to make the compile process less hellish. For example, Intel's oneAPI initiative has their own compiler for DPC++. If i wanted to specify that the project must use that compiler since the code depends on some of their specific stuff, how would I do that?

**Comment by dcbaker** [comment]
@aaronsuydam you can use the `compiler.get_id()` method with the [table of ids](https://mesonbuild.com/Reference-tables.html). In your case that would be something like:
```meson
cpp = meson.get_compiler('cpp')
if cpp not in ['intel-llvm', 'intel-llvm-cl']
  error('Only the Intel OneAPI compilers are supported by this project')
endif
```
