### ISSUE TITLE
Does run_target() return a buildtarget?

### ISSUE THREAD

**Issue by astavale** [mesonbuild/meson#1793]
The [run_target() documentation](http://mesonbuild.com/Reference-manual.html#run_target) shows a `buildtarget` is returned. 

When the following `meson.build` file is used:

```
project('Chained run targets')
first = run_target( 'first-action',
                    command: ['echo','do this first']
                  )
run_target( 'second-action',
            command: ['echo','this is done after the dependency'],
            depends: [first]
          )
```
Meson, however, reports an error:

```
Meson encountered an error in file meson.build, line 5, column 0:
Depends items must be build targets.
FAILED: build.ninja 
```

**Comment by jpakkane** [comment]
That is incorrect as it does not return a build target but a run target. The latter does not produce any output so it can't be a dependency (in Meson all dependencies are to output files, not to concepts).

There is no builtin support to run one run target before another. If you need this, you have to do it manually by invoking Ninja from the second run target before running other things.

If you just want to run several commands in a row and don't need the first target for anything, put the commands in a standalone script and run that. This makes it easier to debug if the need ever arises.

**Comment by mdrost** [comment]
>That is incorrect as it does not return a build target but a run target. 

It would be nice to fix that in [documentation](http://mesonbuild.com/Reference-manual.html#run_target).
