### ISSUE TITLE
Difference between Redhat 7.2 and Linux Mint 18.1 with meson output

### ISSUE THREAD

**Issue by rhd** [mesonbuild/meson#1803]
This is an odd one. I am using the exact same version of meson on both machines.

#### Redhat 7 (the working one)
```
The Meson build system
Version: 0.40.0
Source dir: /home/doolit/work/MDP1
Build dir: /home/doolit/work/MDP1/build
Build type: native build
Project name: ECS
Native c compiler: ccache cc (gcc 4.8.5)
Native cpp compiler: ccache c++ (gcc 4.8.5)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Dependency threads found: YES
Library rt found: YES
Library crypt found: YES
Dependency Boost (system, regex) found: YES 1.53
```
This results in:

```

[78/78] ccache c++  -o ECS/MDP1/Main/benchmarks/ratecontroller <snip .o> '-Wl,--no-undefined' '-Wl,--as-needed' <snip .so> '-pthread' '-lboost_system' '-lboost_regex' '-lboost_system' '-lboost_regex' '-lrt' '-Wl,-rpath,/work/MDP1/build/ECS/MDP1/Main'  
```

#### Mint Linux (the non-working version)

```
The Meson build system
Version: 0.40.0
Source dir: /home/doolit/work/MDP1
Build dir: /home/doolit/work/MDP1/build
Build type: native build
Project name: ECS
Native c compiler: ccache cc (gcc 5.4.0)
Native cpp compiler: ccache c++ (gcc 5.4.0)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Dependency threads found: YES
Library rt found: YES
Library crypt found: YES
Dependency Boost (system, regex) found: YES 1.58
```
This results in:

```
[78/78] ccache c++  -o ECS/MDP1/Main/benchmarks/ratecontroller <snip .o> '-Wl,--no-undefined' '-Wl,--as-needed' <snip .so> '-pthread' '-lboost_system' '-lboost_system' '-lrt' '-Wl,-rpath,/work/MDP1/build/ECS/MDP1/Main' 
```

The `Mint Linux` version produces `-lboost_system` twice and I have no clue why.

I also tested with meson `0.40.1` with the same result.

Thoughts?

Update: On the Mint Linux machine `cat build/build.ninja | grep boost_regex` produces nothing.. unlike the redhat machine

**Comment by nirbheek** [comment]
Yeah, it's weird that boost_regex isn't used on Mint. Could you paste a list of boost libraries in the system path?

**Comment by nirbheek** [comment]
Also what versions of Python are being used for each?

**Comment by jpakkane** [comment]
Some distributions ship .pc files for Boost even though upstream doesn't. Maybe it's using those?

**Comment by rhd** [comment]
boost's regex module isn't installed in the Mint Linux system

```
 $ find /usr/lib -iname 'libboost*'
/usr/lib/x86_64-linux-gnu/libboost_iostreams.so.1.54.0
/usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.58.0
/usr/lib/x86_64-linux-gnu/libboost_date_time.so.1.58.0
/usr/lib/x86_64-linux-gnu/libboost_system.so.1.58.0
/usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.58.0
/usr/lib/x86_64-linux-gnu/libboost_system.so.1.54.0
/usr/lib/x86_64-linux-gnu/libboost_iostreams.so.1.58.0
/usr/lib/x86_64-linux-gnu/libboost_date_time.so.1.54.0
/usr/lib/x86_64-linux-gnu/libboost_system.a
/usr/lib/x86_64-linux-gnu/libboost_system.so
```

This means that the .pc file is present and meson is getting tricked?

**Comment by rhd** [comment]
> Also what versions of Python are being used for each?

RH:
```
$ python3 --version
Python 3.5.2
```

Mint:
```
$ python3 --version
Python 3.5.2
```

**Comment by rhd** [comment]
Should I close this? Or would you like this debugged further?

**Comment by nirbheek** [comment]
This looks like a bug in `BoostDependency`. We should investigate this further.

**Comment by rhd** [comment]
Yea, looks like if the version is detected it assumes that all modules were
found.

**Comment by NickeZ** [comment]
Could it be that the header directory for regex is installed? Because that is valid according to the current code: https://github.com/mesonbuild/meson/blob/master/mesonbuild/dependencies/misc.py#L145

**Comment by rhd** [comment]
@NickeZ No, the `BoostDependency` is not very robust at validating that all libraries are actually round. If `boost_system` is installed but `boost_regex` is not, it will still report `found` and the build will not be correct. If I remember, this was the case on my mint linux box which had a separate `regex` package.

**Comment by NickeZ** [comment]
@rhd I believe that debian/mint will install the headers for `regex` since they are in the `libboost-dev`. But you didn't install the regex library which is in `libboost-regex1.58.0`. This tripped up the current implementation of the `BoostDependency` because it found `/usr/include/boost/regex` and thought that regex was installed.

I have removed that code in my current PR about boost #2276. That might have been premature however. It could be that some distribution actually splits up boost headers in multiple packages. But I think that is very difficult to do since they have very complex dependencies on each other.

**Comment by rhd** [comment]
@NickeZ ahh, that makes sense. I had the headers installed but not the libs which faked out `BoostDependency`. Interesting - I hope you can land a good fix. 

BTW, did you test if setting `BOOST_ROOT` works correctly - see #669

**Comment by nirbheek** [comment]
This is fixed with https://github.com/mesonbuild/meson/pull/2282
