### ISSUE TITLE
mesontest isn't flushing stdout?

### ISSUE THREAD

**Issue by rhd** [mesonbuild/meson#1805]
I'm using `ninja test` with a gitlab runner for CI. When the runner builds the code, I see the output get updated live. When the tests run, the output doesn't get flushed to the screen until after they are done - about 30 min worth of tests.

My guess is that `mesontest` isn't flushing it's stdout and it's being buffered by the system.

When the current test finishes, I'll rerun with `mesontest.py` changed to `#!/usr/bin/env python3
 -u` which should force unbuffered stdout.

**Comment by rhd** [comment]
Hmm changing to top of `mesontest.py` to `#!/usr/bin/env python3 -u` did not seem to help.

**Comment by jpakkane** [comment]
The printing happens on `mesontest` lines 294 and 296. It uses plain `print`. So it should just work. Dunno why that is.

**Comment by rhd** [comment]
I can't test this until tomorrow - but it's almost certainly related to the line in `build.ninja` not passing the `-u` flag to python3.

```
COMMAND = '/usr/bin/python3' '/usr/local/bin/mesontest' '--no-rebuild' '--print-errorlogs'
```

Or we could call `sys.stdout.flush()` after the `print` statements. Probably easier to modify the build.ninja file - I'll test tomorrow.
