### ISSUE TITLE
How to place all binaries in build/ ?

### ISSUE THREAD

**Issue by kaimast** [mesonbuild/meson#1806]
Is there a way to be able to use subdir and still place all binaries in build/ by default?

**Comment by arteymix** [comment]
Not exactly close, but you can use `meson --layout=flat` to get all the binaries in `build/meson-out`.

**Comment by kaimast** [comment]
Oh okay. That's good enough.

Alternatively is there a way to easily add a subdirectory of sourcefiles without using subdir? I.e., can I avoid putting the path in every filename somehow?

**Comment by tp-m** [comment]
You can always do a loop that adds the paths programmatically to an array of N source files :)

**Comment by arteymix** [comment]
It's possible to use `subdir` to recurse into subdirectories, collect sources with `files` and declare the target at the root. I use this for aggregating the routines for Vast: https://github.com/rainwoodman/vast/blob/master/src/meson.build
