### ISSUE TITLE
mesontest: build with CI and test on target - exception thrown

### ISSUE THREAD

**Issue by rhd** [mesonbuild/meson#1819]
I've just recently changed my CI/test setup. I now build the app with docker but I still need to test it on the target. I'm using gitlab and the amazing gitlab-runner to accomplish this. This problem is the directory structures of the docker container and my target don't match. So when I build the app in docker and move the artifacts (the entire meson `build` directory) and execute `mesontest.py -C build --no-rebuild` it throws an exception.

```
Traceback (most recent call last):
  File "mesontest.py", line 618, in <module>
    sys.exit(run(sys.argv[1:]))
  File "mesontest.py", line 614, in run
    return th.doit()
  File "mesontest.py", line 343, in doit
    self.run_tests(tests)
  File "mesontest.py", line 491, in run_tests
    self.drain_futures(futures, logfile, jsonlogfile)
  File "mesontest.py", line 510, in drain_futures
    self.print_stats(numlen, tests, name, result.result(), i, logfile, jsonlogfile)
  File "/usr/local/lib/python3.5/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/usr/local/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "mesontest.py", line 236, in run_single_test
    preexec_fn=setsid)
  File "/usr/local/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '/builds/HEL/MDP1/build/ECS/MDP1/Main/tests/ecsTest'
```

Obviously this is because the docker container and the directory structure on the target don't match. My target's base path is `/home/gitlab-runner/builds` not `/builds`

It seems to me that meson could avoid recording the full path of the test app and know the relative path from the `build` directory. 

Am I overlooking something obvious? Any workarounds for this that you can think of?

Thanks!

**Comment by jpakkane** [comment]
Moving directories is very much not supported. It it works then it is by accident. There are dozens of ways this can break some of which are obscure.

You could try faking it by creating a few symlinks that recreate the tree structure inside Docker. That's not guaranteed to work either but if it does then it's the simplest solution.

**Comment by nirbheek** [comment]
I actually keep this in mind whenever I work on Meson, and there are too many places where the only option we have is to store the absolute path, and that breaks moving the build directory. It can be done in theory, but in practice it is a lot of work.

Symlinks should work, and we would probably be able to accept patches that make that work.

**Comment by rhd** [comment]
Hmm - this is a big bummer as it makes working with docker and meson much more difficult.

I'm not saying this is a good patch or even a good idea - but how likely would a patch like this be mergeable once it gets cleaned up and tests added? Is there a better way to do it?

```diff
diff --git a/meson/mesontest.py b/meson/mesontest.py
index b59d1ed..e9efe4a 100755
--- a/ECS/MDP1/meson/mesontest.py
+++ b/ECS/MDP1/meson/mesontest.py
@@ -377,6 +377,16 @@ TIMEOUT: %4d
     def load_tests(self):
         with open(self.datafile, 'rb') as f:
             self.tests = pickle.load(f)
+            build_dir = get_private_build_dir(self.options)
+            if not build_dir.endswith(os.path.sep):
+                build_dir = build_dir + os.path.sep
+            for i, test in enumerate(self.tests):
+                # fix all the paths to use the current working directory
+                for j, name in enumerate(test.fname):
+                    if name.startswith(build_dir):
+                        name = name[len(build_dir):]
+                        name = os.path.join(self.options.wd, name)
+                        self.tests[i].fname[j] = name
 
     def load_datafile(self, datafile):
         self.datafile = datafile
@@ -527,6 +537,12 @@ def list_tests(th):
     for t in tests:
         print(th.get_pretty_suite(t, tests))
 
+def get_private_build_dir(options):
+    buildfile = os.path.join(options.wd, 'meson-private/build.dat')
+    with open(buildfile, 'rb') as f:
+        build = pickle.load(f)
+    return build.environment.build_dir
+
 def merge_suite_options(options):
     buildfile = os.path.join(options.wd, 'meson-private/build.dat')
     with open(buildfile, 'rb') as f:
```

**Comment by QuLogic** [comment]
> My target's base path is /home/gitlab-runner/builds not /builds

Can't you just set docker to run in this directory instead? It's not like `/builds` is some requirement.

**Comment by rhd** [comment]
> Can't you just set docker to run in this directory instead? It's not like /builds is some requirement.

You're right - it looks like the runner supports a `build_dir` option and I can set it like this: `  builds_dir = "/home/gitlab-runner/builds"`

Unfortunately, this doesn't work because the real gitlab runner uses some special path to manage concurrent builds and things like that... thus I don't think it's going to work. It's currently using `/home/gitlab-runner/builds/15268147/0/HEL/MDP1` to check the code out into.

**Comment by QuLogic** [comment]
Can you set a volume mount on the docker run? Set `build_dir` to some well known path on _both_ docker and the host, then `-v ${build_dir}:${build_dir}` will mount the host path into docker. You'll still have to figure out that special path for concurrent builds, though.

**Comment by rhd** [comment]
I think I'm screwed w/o a mod to mesontest :(

**Comment by QuLogic** [comment]
[Volumes](https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/blob/master/docs/configuration/advanced-configuration.md#volumes-in-the-runnersdocker-section) and [`${CI_PROJECT_DIR}`](https://docs.gitlab.com/ce/ci/variables/#predefined-variables-environment-variables)

**Comment by rhd** [comment]
Right, the `volumes` is an option in the runner's config file. I'm not expert, but I don't believe it can be set to a volatile environment variable as the config file is read at startup and the associated `-v` options are added to the docker run command (by the runner).

I'm currently using the `volumes` config option to map ccache directories so ccache works inside the docker. I still can't think of a good way to make this work with the `CI_PROJECT_DIR`.

Any other thoughts? I hope I'm understanding you correctly. This is my first foray into docker.

**Comment by QuLogic** [comment]
Why do you need to set it to a volatile variable? Set it to something well-known and use `${CI_PROJECT_DIR}` to run things.

**Comment by rhd** [comment]
@QuLogic Thanks for trying to work with me on this but I'm still not following.

In the docker image `env` shows this: `CI_PROJECT_DIR=/builds/HEL/MDP1` - so I have no way to map it to the build directory on the target - especially since the build target is not docker and has to deal with current jobs which is why the path has extra numbers in it.

So even if I set the `build_dir` to `/some/well/known/dir`, I still have to deal with the extra stuff the runner adds to the path on the target.

If I'm still missing the point, can you please provide an example.

**Comment by rhd** [comment]
@jpakkane @nirbheek How about if we stuck the patch behind an experimental command line option? `--movable-datadir`?

My plea: I'm trying to drag the company I work for into the 21st century - away from crusty `make` to `meson/ninja`. The other side of this having generic CI machines that can do builds and non target specific tests inside of a project specific docker image. I hope this is the future. I'm really tired of busting out the redhat 6 disks to stand up a new machine because an old project got resurrected and won't build on anything besides rh6 with a bunch of custom libs installed in non-standard places. (The board vendors in the market I'm in are way behind the times)

I hope you guys can work with me to help make meson more docker friendly. I'm happy to submit a PR if it's possible that something might get merged.

**Comment by rhd** [comment]
I've added a WIP pull request. Hopefully something can get worked out. I need to add a test but not sure how to integrate at the moment.

**Comment by rhd** [comment]
My workaround was to make the target directory structure match the docker directory structure - namely `/builds/namespace/reponame`

In the `.gitlab-ci.yml`

```yaml
variables:
  DOCKER_NAMESPACE: /builds/$CI_PROJECT_NAMESPACE
  DOCKER_DIR: /builds/$CI_PROJECT_PATH

app:target test:
  stage: test
  script:
    # make the target computer look like the docker directory structure
    - mkdir -p $DOCKER_NAMESPACE
    - ln -sf $CI_PROJECT_DIR $DOCKER_DIR
    - cd $DOCKER_DIR

    - mesontest -C build --no-rebuild
```

I'm going to close this issue for now. Thanks @QuLogic @jpakkane and @nirbheek
