### ISSUE TITLE
Frameworks passed many times on the linker command line

### ISSUE THREAD

**Issue by zajo** [mesonbuild/meson#1826]
I have multiple declare_dependency dependencies, each injecting the gl dependency into targets that use them. Here is partial copy of the linker command line I end up with (this is on mac, I'm not sure if the issue applies to other platforms or to non-frameworks as well). Looks like a bug to me.

'-framework' 'OpenGL' '-framework' 'OpenGL' '-framework' 'OpenGL' '-framework' 'OpenGL' '-framework' 'OpenGL' '-framework' 'OpenGL' '-framework' 'OpenGL' '-framework' 'OpenGL' '-framework' 'OpenGL' '-framework' 'OpenGL' '-framework' 'OpenGL' '-framework' 'OpenGL'

**Comment by zajo** [comment]
It seems to happen at least with all static libraries, too.

**Comment by jpakkane** [comment]
This is most likely the same symptom as in #1545.

**Comment by nirbheek** [comment]
Yes, it is the same thing as #1545. Closing.
