### ISSUE TITLE
The --help output for -D is ambiguous

### ISSUE THREAD

**Issue by williamh** [mesonbuild/meson#1836]
When you run meson --help, it shows the following for -D.

-D PROJECTOPTIONS Set project options.

That's a little ambiguous because it implies that -D is only needed once to set multiple options but doesn't give any hint of how to set multiple options with one -D switch.

**Comment by williamh** [comment]
I see your pull request, but that doesn't quite fix it in my mind.

-D projectoptions

implies that one -D switch can set multiple project options. Is this right? if not, you might want to s/projectoptions/projectoption/.

**Comment by jpakkane** [comment]
That's Python putting the variable name in. It is in plural because that's what it is internally (a list) but it does not really match with the help text. 🤔

**Comment by QuLogic** [comment]
Use `metavar=` to set the name used in the help text.
