### ISSUE TITLE
How to install Meson on Mac OS?

### ISSUE THREAD

**Issue by Takao-7** [mesonbuild/meson#1840]
Ok first of all:
the installation instructions are horrible, because they are basically NON EXISTING.
There is no word about where to move Ninja, in order for it to work from everywhere (PATH).
I have moved to know there.

I have "installed" Meson with **pip3 install meson**.
It was installed here:
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Which is not in PATH, because I can't access the program with meson or meson.py.
Also, when I copy the mesonbuild folder from there into opt/local/bin (a PATH folder) it's still not working.

How do I install Meson, so that it's included in the PATH?
I need meson in order to install libfuse, in order to install a NTFS driver.
Would this be a valid meson command, when executed inside the libfuse folder?:
**meson . build**

**Comment by jpakkane** [comment]
Meson behaves in the same way as any Python application. The Python website has a lot of documentation on how to install and run them.

> Would this be a valid meson command, when executed inside the libfuse folder?:
> meson . build

Yes. You can omit the period and just do `meson build` and Meson will assume that you meant the current directory.

**Comment by eli-schwartz** [comment]
https://mesonbuild.com/Getting-meson.html includes instructions for running via /path/to/meson-git-repo/meson.py (you can put this in PATH or symlink it). No need for pip.
