### ISSUE TITLE
Support for alternative pkgconfig binaries

### ISSUE THREAD

**Issue by zonque** [mesonbuild/meson#1849]
OpenEmbedded currently applies the following patch downstream in order to make Qt-based applications use `pkg-config-native` instead of `pkg-config`, as the two variants have distinct search paths:

  https://github.com/openembedded/meta-openembedded/blob/master-next/meta-oe/recipes-devtools/meson/meson/native_bindir.patch

I wonder whether there is a different approach to achieve this, possibly through environment variables or such? I'd like to update to meson 0.40.x, but this patch currently stands in the way. I could update it, but I'd prefer a cleaner solution if there is one.

**Comment by QuLogic** [comment]
You only need to use a different binary for Qt? That seems odd and kind of broken. Why can't you always use one or the other (with an updated search path)?

**Comment by ribalda** [comment]
You need to call pkg-config-native to get the binaries executed by the host. Other libraries than qt doesn't usually require to call helper binaries.

**Comment by ribalda** [comment]
But in principle, yes. Every library that requires a helping binary on compile time should use pkg-config-native (on openembedded/yocto)

**Comment by jpakkane** [comment]
Because cross compilation terminology is mixed and confusing, let's define some terms first. In Meson "build machine" is the laptop or desktop that is used to compile the code. "Host machine" is the ARM board or equivalent that will run the resulting binaries.

The `PKG_CONFIG` environment variable can be used to tell which pkg-config to use to get "build machine" and respectively the pkg-config entry in the cross file tells which one to use for cross building.

The real question then is what are "binaries executed by the host" in this case, what are they used for and what is the actual bug that caused OE to add this patch.

**Comment by zonque** [comment]
AFAIU, the "binaries executed by the host" in this case are such that Qt needs in its build process in order to cross-compile the sources for the target. In OE, most packages can be built for both the "build machine" and the "host machine" from the exact same sources.

The patch now forces Qt into always using `pkg-config-native`, but I'm not sure whether that's always the right thing to do, given that meson could be used for building both the native and the cross variant.

@ribalda, what recipe did you make this change for? Could you try if setting the `PKG_CONFIG` environment variable to `pkg-config-native` as described above has the same effect?

**Comment by ribalda** [comment]
@zonque & @jpakkane : On OE we have two sysroots, one for the "build machine/X86" and another one for the "host machine/ARM".

To put a simple example: On QT we have:
- ARM: `qt.so`, `rocc.exe` and `pkg-config` pointing to them
- X86: `qt.so`, `rocc.exe` and `pkg-config-native` pointing to them

When we are cross compiling QT we need `rocc.exe` from X86 and `qt.so` from ARM. 

If I change `PKG_CONFIG` to `pkg-config-native` then I will be using qt.so from X86, which is wrong.

**Comment by zonque** [comment]
Hmm, I still don't fully get it. As per your description, `pkg-config` without `-native` is the right thing to use for building binaries for the target. In what situation do you need to use `pkg-config-native` then? If these cases can be handled explicitly by OE, doesn't setting `PKG_CONFIG = pkg-config-native` only in such cases seem the right thing to do?

**Comment by ribalda** [comment]
@zonque Sorry for the delayed answer, I have been on holidays.

On OpenEmbedded we have two sysroots, one for the ARM and one for the X86. Each sysroot have its own pkgconfig folder

X86:
```
ricardo@neopili:~/curro/qt5022/build-qt5022-open/build/tmp/sysroots$ cat x86_64-linux/usr/lib/pkgconfig/QtCore.pc 
prefix=/home/ricardo/curro/qt5022/build-qt5022-open/build/tmp/sysroots/x86_64-linux/usr
exec_prefix=${prefix}
```
ARM:
```
ricardo@neopili:~/curro/qt5022/build-qt5022-open/build/tmp/sysroots$ cat qt5022-fglrx/usr/lib/pkgconfig/QtCore.pc 
prefix=/usr
exec_prefix=${prefix}
```
When we are inside the devshell, pkg-config-native parses X86 and pkg-config ARM:

```
root@neopili:~/curro/qt5022/build-qt5022-open/build/tmp/work/bobcat_64-poky-linux/qtec-bottlescanner/0.1+gitAUTOINC+a4d492bdf9-r0/git/qtec-bottlescanner/qtec-bottlescanner-qt4# pkg-config-native --variable=exec_prefix QtCore
/home/ricardo/curro/qt5022/build-qt5022-open/build/tmp/sysroots/x86_64-linux/usr
root@neopili:~/curro/qt5022/build-qt5022-open/build/tmp/work/bobcat_64-poky-linux/qtec-bottlescanner/0.1+gitAUTOINC+a4d492bdf9-r0/git/qtec-bottlescanner/qtec-bottlescanner-qt4# pkg-config --variable=exec_prefix QtCore
/usr
```

When I am compiling Qt applications I need the mocc binary from X86 and the libs/cflags from ARM. This is why I cannot simply overrul the PKG_CONFIG variable, I need to use both.

**Comment by zonque** [comment]
So, I'm lost - what are we doing with this one then? Do we need a patch in meson to support such setups? I'd really like to get rid of the downstream patch in OE, as it block the update to a newer version of meson.

**Comment by rossburton** [comment]
Disclaimer: I've never used Qt but do work on Yocto.  Why can't meson's qt integration just search $PATH for the binaries it needs? (either our patch, or something we can set so meson doesn't try to search).

**Comment by ribalda** [comment]
I guess the reason is that sometimes you have your qt binaries under /opt/share/thenewqtIwanttotest/ and it is not on your $PATH

**Comment by rossburton** [comment]
Yocto-specific: if the target pkgconfig file in qt contains paths for host binaries then maybe the sysroot population should just fix those paths to point to the right place?

**Comment by textshell** [comment]
What's the status on this? It seems OE is still shipping this patch.

I'm pretty sure the way to go here is to set PKG_CONFIG to pkg-config-native and set the pkg-config for the host architecture in the cross file? Did you try that recently and if so what did go wrong?

**Comment by rossburton** [comment]
That might help but there needs to be a way to tell meson when it does pkgconfig calls if it should be calling the target or native binary.

**Comment by ribalda** [comment]
Next week I could prepare a simple use-case so you can replicate the issue. This week I am pretty loaded :S

**Comment by rossburton** [comment]
A fairly minimal example would be:

1. Using pkg-config get the linkage for gobject-2.0
2. Using pkg-config get the location of the glib-mkenums tool

In a cross environment, using Meson terminology (1) is for build but (2) is for host.

**Comment by textshell** [comment]
Meson is supposed to know which pkg-config to call. For dependencies there is the `native` key word argument. And for the internal usages where meson intends to call the executable if meson does not use the native pkg-config (i.e. PKG_CONFIG (if set), the pkg-config from the native file (if set) or `pkg-config`) that is a bug that we just need to fix.

We had bugs in the recent past with some caching problems fixed in https://github.com/mesonbuild/meson/commit/11e3011a6bf0adeb51582c590c90b0f4dccb4df8#diff-bc427959078b2a6a3516350d36b823ab 
So it might be worth to test again if maybe the problem has gone away in the mean time since you last tried.

**Comment by LRN** [comment]
I thought that you always use the same pkg-config, just with different `PKG_CONFIG_PATH` depending on which prefixes you want to pull package defs from.

**Comment by dcbaker** [comment]
actually, you're better off with two different pkg-configs, becasue PKG_CONFIG_PATH is prepended to the compiled in search paths, so you can end up with things for the wrong arch. PKG_CONFIG_LIBDIR is better in that case.

**Comment by AleXoundOS** [comment]
Currently, I have `PKG_CONFIG=mipsel-linux-pkg-config` environment variable set and get
```
src/meson.build:631:4: ERROR: Pkg-config binary for machine MachineChoice.BUILD not found. Giving up.
```

Doesn't meson use `PKG_CONFIG` variable? What's the proper way to cross-compile?

**Comment by xclaesse** [comment]
@AleXoundOS for cross compilation you should set `pkgconfig=/path/to/mipsel-linux-pkg-config` in `[binaries]` of your cross file. Setting `PKG_CONFIG` should work too in theory, but maybe not for cross build.

**Comment by eli-schwartz** [comment]
IIRC meson completely ignores environment variables when activating a cross build.

**Comment by dcbaker** [comment]
@AleXoundOS for the build machine you want PKG_CONFIG_FOR_BUILD, or to use the cross file.

**Comment by dcbaker** [comment]
In fact, i think we can close this as we have support for setting both the host and build pkg-config via both env var or by machine files
