### ISSUE TITLE
Chaining configure_file() can cause ninja to go in an infinite loop

### ISSUE THREAD

**Issue by rindeal** [mesonbuild/meson#1865]
```meson
cfg1 = configure_file(
    ...
)
cfg2 = configure_file(
    input: cfg1,
    ...
)
```

Currently this is not possible, because cfg1 is saved in builddir and absolute path of the cfg1 File object  is trashed -
 https://github.com/mesonbuild/meson/blob/7882549f860730dda43fcc825b5beb75b0209410/mesonbuild/interpreter.py#L2338,  thus cfg2 is looking for cfg1 in the sourcedir.

**Comment by jpakkane** [comment]
Why do you need to do this? What is the specific use case?

**Comment by rindeal** [comment]
I need to pre-process a file with a `command: ...`, before running it through `configuration: ...`. My current workaround is to build the cfg1 path manually. The behaviour `configure_file` has currently is really unexpected. And because it does the stripping with any File object, an example with a wider use case would probably be:

```meson
file = files('/some/absolute/path')
cfg2 = configure_file(
    input: file,
    ...
)
```

**Comment by nirbheek** [comment]
This is supposed to work already. We even have a test for it: https://github.com/mesonbuild/meson/blob/master/test%20cases/common/146%20C%20and%20CPP%20link/meson.build#L38

What exactly are you trying to do and how is it failing?

**Comment by rindeal** [comment]
```meson
project('hello')

cfg1_output = configure_file(
    input: 'cfg1_input',
    output: 'cfg1_output',
    command : [ find_program('touch'), '@OUTPUT@' ],
)
cfg2 = configure_file(
    input: cfg1_output,
    output: 'cfg2_output',
    configuration: configuration_data(), # this sends ninja into an infinity loop
    #command : [ find_program('touch'), '@OUTPUT@' ], # this is tested in your test suite and really works 
)
```

**Comment by nirbheek** [comment]
I can reproduce the infinite loop, yes.
