### ISSUE TITLE
Add a meson.bat file for Windows

### ISSUE THREAD

**Issue by Timmmm** [mesonbuild/meson#1877]
Running meson on Windows is kind of a huge pain. It would be much better if the installation provided a `meson.bat` file with the following contents on installation:

    @echo off
    c:\Windows\py.exe %LOCALAPPDATA%\Programs\Python\Python36-32\Scripts\meson.py %*

Presumably there is a better way to get the path of `meson.py`. See [here](https://stackoverflow.com/a/44241951/265521) for more info.

I'm about 70% sure I've seen other pip packages create `.bat` files so I think it can be done.

**Comment by jpakkane** [comment]
Python packaging should (in theory?) be able to provide for exe files for executable scripts. That would be the best solution but FWICT it is not really working.

Can you point to an existing project that ships bat files? Especially one that does it via distutils somehow.

**Comment by nirbheek** [comment]
I'm not exactly sure why this is needed. You can run `meson.py` from the command-line just fine with just a Python installation and `meson` installed via `pip3`.

**Comment by Timmmm** [comment]
I think [yotta](https://github.com/ARMmbed/yotta/blob/master/setup.py) does, but I don't really want to install it on my system because it pulls in dozens of dependencies and I doubt that pip has a decent uninstall mechanism. (I checked - [I was right](https://stackoverflow.com/questions/7915998/does-uninstalling-a-package-with-pip-also-remove-the-dependent-packages).)

I found a page that describes [how to set up command line scripts](http://python-packaging.readthedocs.io/en/latest/command-line-scripts.html). I believe it is the `console_scripts` version that will generate an exe.

In *theory* `meson.py` works fine. And actually on my very clean Windows VM it did work. But on my home Windows install, which has about 5 copies of python around the system (every program that uses it seems to install its own copy) it is much more of a mess and didn't work; can't remember why exactly.

And as I said before, it means you can't associate `.py` files with an IDE. *And* it doesn't work with Powershell.

Can you test it like this? If it works you might want to enable it only on Windows like Yotta does.

```
setup(name='meson',
...
    entry_points = {
        'console_scripts': ['meson=meson:main'],
    }
)
```

**Comment by adrientetar** [comment]
> You can run meson.py from the command-line just fine with just a Python installation and meson installed via pip3.

Between `python C:\Users\Admin\AppData\Local\Programs\Python\Python36-32\Scripts\meson.py` and `meson` I'd choose the latter tbh, and it seems the meson docs agree.

**Comment by jpakkane** [comment]
Note that the MSI installer packages provide a `meson.exe` that gets added to path so this should work.

**Comment by nirbheek** [comment]
So recently I was trying this, and running `meson.py` with the `py.exe` launcher sucks because it opens a new console window for the output. `meson.exe` works fine of course, but some people prefer using `pip3` to manage their python stuff. I've changed my mind and I think `meson.bat` would be quite useful.

**Comment by riverar** [comment]
Any traction on this? `pip3 install --user meson` does not produce any executables on Windows (10 RS4) for me. Python 3.7 is available via conda environment.

**Comment by riverar** [comment]
Wiring up [entry_points](https://packaging.python.org/specifications/entry-points/) in `setup.py` resolved the issue for me.

```
setup(name='meson',
...
      entry_points={
          'console_scripts': ['meson=mesonbuild.mesonmain:main'],
      },
)
```

This seems preferable over an arbitrary batch file that will require maintenance over time.

**Comment by nirbheek** [comment]
What does an entry point in setup create on Windows? A batch file or an executable?

**Comment by riverar** [comment]
An executable, linked against kernel32 and shlwapi (basic stuff, very compatible across Windows versions).
