### ISSUE TITLE
find_library deprecated?

### ISSUE THREAD

**Issue by Timmmm** [mesonbuild/meson#1883]
[This](https://github.com/mesonbuild/meson/blob/master/docs/markdown/Reference-manual.md#find_library) does not seem right at all.

**Comment by Timmmm** [comment]
Scratch that, I misread.

**Comment by nirbheek** [comment]
After extensive discussions amongst the core team, we came to the conclusion that "finding libraries" was an obsolete concept and will be replaced with a systemd feature called `sd-package`. In fact, libraries themselves are a deprecated concept, but for backwards compatibility we will continue to provide `library()` and related methods.

It is highly recommended that users migrate to the new `sd-package` feature ASAP, and users on Windows, macOS, and BSD are invited to create their own implementations of the specification for a speedy and smooth migration to the new future.

Thanks!

**Comment by poulson** [comment]
@nirbheek Is there any documentation for the `sd-package` approach? I still see `find_library` [in the documentation](http://mesonbuild.com/Reference-manual.html#compiler-object).

**Comment by nirbheek** [comment]
If the version of meson shipped with your OS is too old, you should install a newer one, see: https://mesonbuild.com/Getting-meson.html

**Comment by nirbheek** [comment]
> that I should read about sd-package instead of upgrading meson

Yes, I've already edited my comment to reflect that it was a joke :smile:

**Comment by poulson** [comment]
Yes, this is obvious in hindsight but was't yesterday as I quickly scanned through for keywords for a fix :-)
