### ISSUE TITLE
New-line handling in if statements is silently dangerous.

### ISSUE THREAD

**Issue by Timmmm** [mesonbuild/meson#1886]
Consider the following `if` statement:

```
if get_option('enable_alsa') == 'true'
	or (get_option('enable_alsa') == 'auto' and meson.get_compiler('cpp').has_header('alsa/asoundlib.h'))
```

The entire `or` clause is silently ignored. No errors or warnings, it just ignores it.

If I put it all one one line is fine, but that's kind of ugly. Does meson not support multi-line statements?

**Comment by jpakkane** [comment]
You can do multi line statements with the standard line continuation method of `\` at the end of line.

But that should produce an error because starting a statement with `or` should not be permitted...

**Comment by Timmmm** [comment]
Ah I see. That isn't mentioned in the [syntax page](http://mesonbuild.com/Syntax.html).

Funnily enough I thought the above should work because when I tested an `or` statement on its own it *did* give an error, and this didn't.

**Comment by Timmmm** [comment]
I added [a test case](https://github.com/Timmmm/meson/commit/f3b459879cda6656882357ebf5eee7190e567f78). Not tested (ha)! I'm not sure how to integrate it into your testing system to say "this should give a syntax error".

**Comment by nirbheek** [comment]
Tests that fail configure should go into `test cases/failing`. If you want to test that a specific error is outputted during configure, a unit test is needed, but in this case just a failing test should suffice.

We really should update `test cases/failing*` to allow specifying a pattern that should be matched for the failure.

**Comment by Timmmm** [comment]
Do you mean `test cases/failing` is for test cases that *currently fail* but should work, or for test cases that currently fail and *should* fail? (If the latter I'd suggest renaming the folder to `should_fail` to make it clearer.

**Comment by jpakkane** [comment]
> or for test cases that currently fail and should fail?

These.

**Comment by Timmmm** [comment]
The lexer output looks correct at least:

```
id
lparen
string
comma
string
rparen
eol
eol
if
id
lparen
string
rparen
equal
string
eol
or
id
lparen
string
rparen
equal
string
eol
else
eol
id
lparen
string
rparen
eol
endif
eol
eol
```

I *think* the parser output is correct too. Is there a way to easily print the AST?

**Comment by Timmmm** [comment]
Thanks!
