### ISSUE TITLE
install_subdir without removing the directory content

### ISSUE THREAD

**Issue by Salamandar** [mesonbuild/meson#1887]
There are some use cases where a non-destructive `install_subdir` is needed

* a "files" directory with a bunch of files that need to be installed. (desktop files, scripts, icons), that "mime" the real directories (/etc, /usr/share/applications,…)
* a software with third-party provided applets installed in a specific directory

Today,
* a "direct" install would destroy the system, or the 'applets' directory would delete installed third-party files
* with a non-direct install, files installed sooner in the process would be deleted

Anyways, it seems bad practice to delete everything before installing the subdir.

**Comment by ernestask** [comment]
beb68274138e6f6140c03709c59b57379a94a7c0 should have fixed it.

**Comment by sarum9in** [comment]
Closing since this is fixed now, please reopen if not.
