### ISSUE TITLE
pkg-config generate(), creates a pc file with backslashes on windows

### ISSUE THREAD

**Issue by duncanmcneal** [mesonbuild/meson#1906]
pc files do not work with \ on windows in my experience.

I have to manually change the .pc files to have /,

i.e. 

from

`includedir=${prefix}\include` 

to:

`includedir=${prefix}/include`

**Comment by nirbheek** [comment]
`\` is wrong, but is `\\` also wrong?

**Comment by guruDanny67** [comment]
Tested right now with json-glib (I'm trying to build it on windows, with gvsbuild): if you change all the \ with \\ everything works without problem.

**Comment by TingPing** [comment]
I believe you should always be using `/`

**Comment by guruDanny67** [comment]
Yes, in my script I changed \ to /, it's clearer (all the ones builded from XXX.pc.in are made in this way). 
In some .pc files there are the \ only in the prefix part that, on windows, is ignored (and built from the .pc location).

**Comment by nirbheek** [comment]
This is fixed since https://github.com/mesonbuild/meson/pull/2611.
