### ISSUE TITLE
Executable names clash between the main project and subprojects

### ISSUE THREAD

**Issue by zajo** [mesonbuild/meson#1908]
I am not in a position to be able to build a simple test case for this right now but I think what I am experiencing is that a test() from the main project ends up running an executable that is built by a subproject, because its name happens to be the same as another executable in the main project.

I'm not sure what's the best solution for this, probably an error should be reported, the build aborted?

**Comment by nirbheek** [comment]
Meson is architectured in a way that this should not happen unless you use a flat layout. Could you describe exactly how you saw this happen?
