### ISSUE TITLE
ninja insists files are dirty if they're a symlink away

### ISSUE THREAD

**Issue by grimmy** [mesonbuild/meson#1909]
I think this is a bug in ninja, but wanted to report here first incase it's part of the ninja file generation.

I have the following setup in my repo:

```
root/
  - packaging/
    - debian/
```

Before using meson I used to `ln -s packages/debian` to have `root/debian` so I could just run `debuild`.  However, when it's symlinked, it just constantly says all build files are dirty (when passing `-d explain` to ninja).  The following line is shown again and again.

```
[0/1] Regenerating build files
```

Meson is being ran with `meson debian/build` and ninja is being ran with `ninja -C debian/build`

I'll work around by copying for now, but would much prefer the symlink option as it's much easier to test changes to the packaging.

**Comment by jpakkane** [comment]
You are most likely seeing [this](https://github.com/mesonbuild/meson/issues/1909). It should be fixed in master, can you test that?

**Comment by grimmy** [comment]
Awesome, that fixed it.  Thanks!!
