### ISSUE TITLE
GNOME module needs fixes for RPATH + $ORIGIN binutils bug.

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#1911]
Continued from #1897 and #1898. At least `gnome.generate_gir()` and probably `gnome.gtkdoc()` need fixing so that they pass `-rpath-link` to `g-ir-scanner` instead of `-rpath`.

```
[11/12] Generating MesonSub-1.0.gir with a custom command.
FAILED: gir/MesonSub-1.0.gir 
/usr/bin/g-ir-scanner ../gir/meson-subsample.c ../gir/meson-subsample.h -pthread -I/usr/include/gobject-introspection-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include --no-libtool --namespace=MesonSub --nsversion=1.0 --warn-all --output gir/MesonSub-1.0.gir '-I/home/nirbheek/projects/repositories/github/meson.git/test cases/frameworks/12 multiple gir/gir' '-I/home/nirbheek/projects/repositories/github/meson.git/test cases/frameworks/12 multiple gir/build/gir' -I./mesongir/. -I../mesongir/. --include=GObject-2.0 --include=Meson-1.0 --symbol-prefix=meson_sub_ --identifier-prefix=MesonSub . -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include '-L/home/nirbheek/projects/repositories/github/meson.git/test cases/frameworks/12 multiple gir/build/gir' -lgobject-2.0 -lglib-2.0 '--add-include-path=/home/nirbheek/projects/repositories/github/meson.git/test cases/frameworks/12 multiple gir/build/mesongir' --library girsubproject
/usr/bin/ld: warning: libgirlib.so, needed by /home/nirbheek/projects/repositories/github/meson.git/test cases/frameworks/12 multiple gir/build/gir/libgirsubproject.so, not found (try using -rpath or -rpath-link)
/home/nirbheek/projects/repositories/github/meson.git/test cases/frameworks/12 multiple gir/build/gir/libgirsubproject.so: undefined reference to `meson_sample_get_type'
collect2: error: ld returned 1 exit status
Traceback (most recent call last):
  File "/usr/bin/g-ir-scanner", line 66, in <module>
    sys.exit(scanner_main(sys.argv))
  File "/usr/lib64/gobject-introspection/giscanner/scannermain.py", line 544, in scanner_main
    shlibs = create_binary(transformer, options, args)
  File "/usr/lib64/gobject-introspection/giscanner/scannermain.py", line 419, in create_binary
    gdump_parser.get_error_quark_functions())
  File "/usr/lib64/gobject-introspection/giscanner/dumper.py", line 328, in compile_introspection_binary
    return dc.run()
  File "/usr/lib64/gobject-introspection/giscanner/dumper.py", line 174, in run
    self._link(bin_path, introspection_obj)
  File "/usr/lib64/gobject-introspection/giscanner/dumper.py", line 296, in _link
    raise LinkError(e)
distutils.errors.LinkError: command 'gcc' failed with exit status 1
ninja: build stopped: subcommand failed.
```

The command-line is:

> /usr/bin/g-ir-scanner ../gir/meson-subsample.c ../gir/meson-subsample.h -pthread -I/usr/include/gobject-introspection-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include --no-libtool --namespace=MesonSub --nsversion=1.0 --warn-all --output gir/MesonSub-1.0.gir '-I/home/nirbheek/projects/repositories/github/meson.git/test cases/frameworks/12 multiple gir/gir' '-I/home/nirbheek/projects/repositories/github/meson.git/test cases/frameworks/12 multiple gir/build/gir' -I./mesongir/. -I../mesongir/. --include=GObject-2.0 --include=Meson-1.0 --symbol-prefix=meson_sub_ --identifier-prefix=MesonSub . -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include '-L/home/nirbheek/projects/repositories/github/meson.git/test cases/frameworks/12 multiple gir/build/gir' -lgobject-2.0 -lglib-2.0 '--add-include-path=/home/nirbheek/projects/repositories/github/meson.git/test cases/frameworks/12 multiple gir/build/mesongir' --library girsubproject

**Comment by nirbheek** [comment]
Just an update, to fix this we just need to reuse `determine_rpath_args()` from the Ninja backend in the GNOME module while building args for `g-ir-scanner` (and for gtk-doc). We really need to fix this before releasing, so I've been working on it.

**Comment by fmuellner** [comment]
> I've been working on it.

Great! I suspect that this issue is preventing me from figuring out the test failure in #1919 (the test fails on my system earlier than in CI, including when running against origin/master) ...

**Comment by nirbheek** [comment]
You're probably right about that. I'll confirm once I have a fix.

**Comment by nirbheek** [comment]
Hum, I just realized that the binutils bug would actually make it really really hard for people to link with system libraries that use `RPATH` with `$ORIGIN` in it to refer to other system libraries. They would have to extract the `DT_RPATH` value from the library and manually construct `-Wl,-rpath-link` arguments. 

Thankfully, projects use `RPATH` in installed binaries only for private libraries in 99% of cases, so maybe we can get away with fixing the bug in GNU ld instead.

**Comment by nirbheek** [comment]
@fmuellner can you try the patches in #1927?

**Comment by fmuellner** [comment]
@nirbheek Success, I can now reproduce the test failure - thanks!
