### ISSUE TITLE
Order of -L and -l flags is incorrect during GIR generation

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#1915]
Originally reported here: https://github.com/mesonbuild/meson/issues/1427#issuecomment-306926562

[meson-link-ordering.txt](https://github.com/mesonbuild/meson/files/1059335/meson-link-ordering.txt)

Relevant part: `g-ir-scanner [...] '-ldazzle-1.0' [...] '-L/home/garrett/hacking/gnome/libdazzle/_mesonbuild/src'`. These two should be reversed.

**Comment by nirbheek** [comment]
This actually does not make a difference. g-ir-scanner reads -L and -l arguments separately.

**Comment by xclaesse** [comment]
> This actually does not make a difference. g-ir-scanner reads -L and -l arguments separately.

This is actually a serious bug in g-ir-scanner. I think generate_gir() never worked correctly because of that.
