### ISSUE TITLE
CCompiler.get_library_dirs assumes en locale and fails on es_ES (and probably other locales)

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#1945]
This is the output of `cc --print-search-dirs` on en_US:

```
install: /usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/
programs: =/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/:/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/:/usr/lib/gcc/x86_64-pc-linux-gnu/:/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/:/usr/lib/gcc/x86_64-pc-linux-gnu/:/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/../../../../x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu/7.1.1/:/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/../../../../x86_64-pc-linux-gnu/bin/
libraries: =/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/:/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/../../../../x86_64-pc-linux-gnu/lib/x86_64-pc-linux-gnu/7.1.1/:/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/../../../../x86_64-pc-linux-gnu/lib/../lib/:/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/../../../x86_64-pc-linux-gnu/7.1.1/:/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/../../../../lib/:/lib/x86_64-pc-linux-gnu/7.1.1/:/lib/../lib/:/usr/lib/x86_64-pc-linux-gnu/7.1.1/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/../../../../x86_64-pc-linux-gnu/lib/:/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/../../../:/lib/:/usr/lib/
```

And on es_ES:

```
instalar: /usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/
programas: =/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/:/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/:/usr/lib/gcc/x86_64-pc-linux-gnu/:/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/:/usr/lib/gcc/x86_64-pc-linux-gnu/:/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/../../../../x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu/7.1.1/:/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/../../../../x86_64-pc-linux-gnu/bin/
bibliotecas: =/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/:/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/../../../../x86_64-pc-linux-gnu/lib/x86_64-pc-linux-gnu/7.1.1/:/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/../../../../x86_64-pc-linux-gnu/lib/../lib/:/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/../../../x86_64-pc-linux-gnu/7.1.1/:/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/../../../../lib/:/lib/x86_64-pc-linux-gnu/7.1.1/:/lib/../lib/:/usr/lib/x86_64-pc-linux-gnu/7.1.1/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/../../../../x86_64-pc-linux-gnu/lib/:/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/../../../:/lib/:/usr/lib/
```

We look for `libraries:`, but maybe we should pick the last line instead. Because of this, `cc.find_library()` fails to find libraries in the search path (f.ex. static libraries that need symbols from other libraries at link time).

Reported on IRC by `chuckdaniels`.

**Comment by nirbheek** [comment]
This has been present for several releases, but we should try to get this into 0.41.1 anyway since it affects a huge number of people, but they haven't hit it yet because most libraries can be found by `CCompiler.links()` and manual searching is not needed.

**Comment by QuLogic** [comment]
Can you export `LANG=C` (or `C.utf8`) before running it?

**Comment by nirbheek** [comment]
Maybe, is it possible to build a system without the `C.utf8` or `C` locales?

Perhaps I'm wrong, but I have a feeling that trying to solve a locale issue with more locale magic when it can all be avoided might lead to increased yak-shaving in the future.

**Comment by QuLogic** [comment]
`LANG=C` is basically "use what's in the code" not what's in the translation file; it's also [required by POSIX](https://superuser.com/a/219953).

**Comment by nirbheek** [comment]
Can we assume that output with `LANG=C` can be decoded as UTF-8?

**Comment by jpakkane** [comment]
If we are precise, the output is directory names that are raw bytestreams and not guaranteed to conform to any encoding. So no. But in practice probably yes.

**Comment by nirbheek** [comment]
So I guess we can set an env object on `Popen_safe` that sets the `LANG`. We probably want to do this at all places where we parse tool output?

**Comment by QuLogic** [comment]
`LANG=C` is "just" bytes, but in practice seems to mean US-ASCII. That's why many Python packages that don't specify an encoding fail when building RPMs and why there's a push for a C.utf8 locale. Whether or not gcc treats directories as raw bytestreams (as @jpakkane notes it should should for passing around) for display (since this output is not technically a machine-interface) is not something I know for sure.

**Comment by nirbheek** [comment]
Alternate question: is there a way to get this information in a machine-readable way? The last time I looked, this was all I found.

**Comment by ChuckDaniels87** [comment]
Just as a temporal workaround if anyone has this issue until it is fixed: `LANG=C meson build` seems to fix this issue on my system (es_ES.utf8).

**Comment by ChuckDaniels87** [comment]
Is this issue related to recent PR #2564? Could be this bug fixed in a similar way?

**Comment by nirbheek** [comment]
Yes, the fix would be similar. You can do:

```python
env = os.environ.copy()
env['LC_ALL'] = 'C'
... = Popen_safe(..., env=env)
```

If you can test this fix, please submit a PR for it :)
