### ISSUE TITLE
Custom targets should build even if nothing depends on them

### ISSUE THREAD

**Issue by tbodt** [mesonbuild/meson#1947]
Currently if you make a custom target and you don't use the output from the custom target anywhere, the custom target never gets built. This prevents using custom targets for things like compilers for languages not supported by meson. Obviously in that case the real fix is to add support for the language to meson, but it's useful to have some sort of stopgap until that can be done.

**Comment by jpakkane** [comment]
build_by_default : true

**Comment by tbodt** [comment]
:face_palm:
