### ISSUE TITLE
BoostDependency must only read BOOST_LIBRARYDIR during object init

### ISSUE THREAD

**Issue by wberrier** [mesonbuild/meson#1958]
It looks to be because get_link_args inspects the environment.

Instead, configuring the dependency should inspect the environment and store appropriately.

I'll be working on a fix, but am logging this in the meantime.

**Comment by nirbheek** [comment]
This is a dupe of https://github.com/mesonbuild/meson/issues/1503. We're not sure what the semantics of such a change would be; for instance how does the user force re-reading of the environment variable?

**Comment by nirbheek** [comment]
I will close this bug, let's discuss on #1503 to keep everything in one place.

**Comment by wberrier** [comment]
This was fixed in ad1b487.
