### ISSUE TITLE
XXX_args: doesn't open mesonlib.File as str

### ISSUE THREAD

**Issue by ignatenkobrain** [mesonbuild/meson#196]
it's not possible to do:
```
gres = files('gnome-scanmem.gresource.xml')
...
  vala_args : ['--gresources', gres]
...
```

**Comment by benwaffle** [comment]
How should the resource path be passed to `--gresources` in `vala_args`?

**Comment by ignatenkobrain** [comment]
@benwaffle https://github.com/mesonbuild/meson/tree/master/manual tests/7 vala composite widgets

**Comment by benwaffle** [comment]
```
Meson encountered an error in file src/meson.build, line 26, column 0:
A non-string passed to compiler args.
```

**Comment by jpakkane** [comment]
Note that this changed recently. If you are using a release version rather than git head, it probably does not work. If you are using git head and have this issue, please post a link to your full code so we can debug.

Thanks,

**Comment by benwaffle** [comment]
Ah, no, I'm using a release version

**Comment by jpakkane** [comment]
The unit test does exactly what is requested in this bug, so closing.
