### ISSUE TITLE
Don't return an error if the build directory is already configured

### ISSUE THREAD

**Issue by devopsdeluxe** [mesonbuild/meson#1962]
Upon running meson on a pre-configured build directory one would get this error message:

```
 » meson build
Error during basic setup:

Trying to run Meson on a build directory that has already been configured.
If you want to build it, just run your build command (e.g. ninja) inside the
build directory. Meson will autodetect any changes in your setup and regenerate
itself as required.

If you want to change option values, use the mesonconf tool instead.
 1 » 
```

As well as the program returning an exit status of 1.

My proposal:

```
 » meson build
Warning: Trying to run Meson on a build directory that has already been configured.

If you want to build it, just run your build command (e.g. ninja) inside the
build directory. Meson will autodetect any changes in your setup and regenerate
itself as required.

If you want to change option values, use the mesonconf tool instead.
 0 » 
```

The proposed suggestion:
1. Returns an exit code of 0, indicating that the initial configuration was successful.
2. Retains the warning message of the original error, relaying important information to the user.

This is really me just nitpicking something small, but I figured I'd at least ask if it's worth changing.

**Comment by jpakkane** [comment]
This has been fixed, so closing.
