### ISSUE TITLE
dist should warn if you have uncommitted changes while creating the tarball

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#1977]
```
<nirbheek> hadess, dist will always build from the tarball 
<hadess> what
<nirbheek> It'll extract it to a temporary directory then build it there
<hadess> nirbheek, the tarball that doesn't pass "check"?
<hadess> that doesn't seem like the right thing to do either
<nirbheek> The tarball that is created anew from HEAD each time you run dist
<nirbheek> If you have uncommitted changes it won't put those in, fwict
<hadess> nirbheek, this is horrible
<nirbheek> Shouldn't it always build the dist tarball from the changes in git?
<hadess> i've been trying to fix tests that probably worked 20 minutes
<hadess> 20 minutes ago
<nirbheek> It should warn that you have uncommitted changes while doing dist, yes
<hadess> that would be helpful :)
```

**Comment by robert-ancell** [comment]
This is particularly bad in that meson will pull the project version from the uncommitted meson.build but with the contents of the committed meson.build. This means you can generate `projectname-5.tar.xz` which actually contains version 4. If it built `projectname-4.tar.xz` that would at least give you a hint that you don't have the correct contents.

**Comment by hadess** [comment]
> You should never create a release tarball with changes that aren't already committed to git. :)

Just in case somebody might want to test before releasing... This sort of comment is just plain silly.

**Comment by domdfcoding** [comment]
> Just in case somebody might want to test before releasing..

Yes, particularly with Python code (where tox installs sdists; interestingly the wheels don't exhibit this problem but it won't install them) this is an issue. Am I supposed to commit every change just to test it?
