### ISSUE TITLE
Add code coverage

### ISSUE THREAD

**Issue by ignatenkobrain** [mesonbuild/meson#198]
we really need this to know what sort of code we are not testing

**Comment by jpakkane** [comment]
I seem to recall doing this back when the test suite was changed to run within a single Python interpreter. Just run run_tests.py under the coverage thing and it should work. The only things it won't measure are the helper scripts (depfixer.py etc) because they are run in a different process.

**Comment by nirbheek** [comment]
We have `b_coverage` now.
