### ISSUE TITLE
git submodule status parsing incomplete, results in backtrace

### ISSUE THREAD

**Issue by wberrier** [mesonbuild/meson#1980]
Currently (0.41.1) it parses ' ' and '-', but not '+', resulting in a backtrace (mesonbuild/wrap/wrap.py).

**Comment by wberrier** [comment]
I'm running into this when I have a subproject that is a git submodule.  I believe that's why it's going through the 'wrap' codepath (even though I'm not really using any 'wraps').

**Comment by nirbheek** [comment]
What's interesting is that this codepath should not get hit at all. If the `subprojects/xxx` dir has a meson.build file, we will not try to do any git submodule shenanigans. What exactly is in that directory?

**Comment by wberrier** [comment]
Note, I haven't seen this in quite a while.  I ran into a few times weeks around this reported bug, but haven't seen it since.  Appropriate to leave open?  Close it?

In any case, the directory layout is as such:

    project/
        meson.build
        git_submodule/
        git_submodule/meson.build

Also note that I have the following in project/meson.build (which apparent is going to be disallowed soon):

    subproject_dir: '.'

**Comment by eli-schwartz** [comment]
This was fixed in #3035
