### ISSUE TITLE
Move to native implementation

### ISSUE THREAD

**Issue by piribes** [mesonbuild/meson#1990]
I like meson, I'm just starting using it and I'm wonder if you ever considered the possibility to move to a native (C or C++) implementation.

**Comment by jpakkane** [comment]
It's a big job but in theory yes, if the Python implementation turns out to be a bottleneck in some way. At the moment it does not seem to be the case.

**Comment by Conan-Kudo** [comment]
@jpakkane It could probably be compiled with some kind of Python compiler, like [Nuitka](http://nuitka.net/), to offer a "native" version for those who worry about such things.

**Comment by jpakkane** [comment]
In (hopefully) the next release we will provide a native Windows executable as an MSI package. Those interested can look at MR #2067.
