### ISSUE TITLE
Tells me to just run ninja but that fails

### ISSUE THREAD

**Issue by hadess** [mesonbuild/meson#1991]
Using `meson-0.41.1-1.fc26.noarch`, I'm trying to port totem to meson:
https://bugzilla.gnome.org/show_bug.cgi?id=783205

After a few build attempts and thinking my jhbuild gobject-introspection is broken, I run `jhbuild uninstall gobject-introspection`. Now running ninja says:
```
ninja: error: '/home/hadess/Projects/gnome-install/bin/g-ir-scanner', needed by 'src/Totem-1.0.gir', missing and no known rule to make it
```

Fair enough, it's not there any more. Let's run meson for it to find the dependencies again:
```
Error during basic setup:

Trying to run Meson on a build directory that has already been configured.
If you want to build it, just run your build command (e.g. ninja) inside the
build directory. Meson will autodetect any changes in your setup and regenerate
itself as required.

If you want to change option values, use the mesonconf tool instead.
```

I probably shouldn't have to nuke my build directory to get out of this loop.

**Comment by ignatenkobrain** [comment]
why don't you wipe directory yourself and start over?

**Comment by hadess** [comment]
Because the tool is telling me I just need to run ninja and that it'll fix everything for me.

**Comment by jpakkane** [comment]
Does `ninja reconfigure` fix it`?

**Comment by hadess** [comment]
Reproducer, in a jhbuild shell, in totem's src directory:
```
$ jhbuild buildone gobject-introspection ; mkdir build ; cd build ; meson ../ ; ninja ; jhbuild uninstall gobject-introspection ; ninja
ninja: error: '/home/hadess/Projects/gnome-install/bin/g-ir-scanner', needed by 'src/Totem-1.0.gir', missing and no known rule to make it
$ ninja reconfigure
[snip]
$ ninja
/usr/include/libpeas-1.0/libpeas/peas-extension.h:26:10: fatal error: girepository.h: No such file or directory
 #include <girepository.h>
          ^~~~~~~~~~~~~~~~
```

Looks like it didn't look for gobject-introspection.pc again, and is using the old cached values from the jhbuilt version of the library (as can be seen in the build commands json file with `-I/home/hadess/Projects/gnome-install/include/gobject-introspection-1.0`)

**Comment by hadess** [comment]
(that's a "no" to your question, sorry)

**Comment by jpakkane** [comment]
Meson stores all successfull searches of system data because it makes things faster. There has been talk of adding a more powerful "purge state" option but currently we don't have it so the only solution is to wipe the build dir and re-initialize it.

**Comment by hadess** [comment]
Can we change the "meson" message then?

**Comment by nirbheek** [comment]
Yes, that should be changed to tell people about `ninja reconfigure` and also that they should wipe the build dir if they still have problems.

**Comment by chetgurevitch** [comment]
As of https://github.com/mesonbuild/meson/pull/2163 ninja reconfigure is documented.

**Comment by nirbheek** [comment]
So now we just need to also add a message saying they should wipe the builddir if they have problems. Anyone willing to put up a PR for that? ;)

**Comment by liberforce** [comment]
Changes have been merged, so shouldn't this bug be closed?

**Comment by hadess** [comment]
Yep, that error message works for me, thanks.
