### ISSUE TITLE
mesonintrospect --dependencies returns list instead of dictionary

### ISSUE THREAD

**Issue by martin-ejdestig** [mesonbuild/meson#2018]
Reported it breaking completely in #1963 .

When I got around to testing the fix just now I noticed that the root object for mesonintrospect --dependencies now is a list instead of an object like it used to be prior to 0.41. Probably not what is wanted.

Example output (added newlines to make it easier to read):

```shell
$ mesonintrospect --dependencies <build path>
["threads", {"compile_args": [], "link_args": []},
 "libjpeg", {"compile_args": [], "link_args": ["-ljpeg"]},
 "libpng", {"compile_args": ["-I/usr/include/libpng16"], "link_args": ["-lpng16"]},
 "libwebp", {"compile_args": [], "link_args": ["-lwebp"]}]
```

**Comment by martin-ejdestig** [comment]
@nirbheek I see that you turned this into a list in ac1c929f66bde7209f1bd7e2d995dbd3949e1d8b . The commit message ("Print all deps, not just those with the same name") does not make sense to me though. When it was a dictionary not only deps with the same name were printed... ?

Do we want this as a list? It makes it a bit more hard to iterate over dependencies in tools that parse this output. (Have to know that a dependency is described with to consecutive elements in the list and that name is the first.)

I think it makes more sense to have this as a dictionary but I do not understand what it was you were trying to fix.

**Comment by nirbheek** [comment]
The dependency name is not a unique identifier. You can have two dependency objects with the same name and different version requirements, or different modules enabled (qt, boost), etc. Earlier we would drop these because the dict is keyed by dependency name.

**Comment by martin-ejdestig** [comment]
OK. Should something be done about making it easier to iterate over them though? Maybe add a "name" key so a single element in the list describes a single dependency fully instead of having a list with mixed elements. E.g. the above would then be:

[{ "name": "threads", "compile_args": [], "link_args": []},
 { "name": "libjpeg", "compile_args": [], "link_args": ["-ljpeg"]},
 { "name": "libpng", "compile_args": ["-I/usr/include/libpng16"], "link_args": ["-lpng16"]},
 { "name": "libwebp", "compile_args": [], "link_args": ["-lwebp"]}]
