### ISSUE TITLE
GCC rejects Precompiled Header when executable has threads dependency

### ISSUE THREAD

**Issue by polarina** [mesonbuild/meson#2022]
meson.build:
```meson
project('mesonthreads', 'c')

executable('magic',
	'main.c',
	dependencies: dependency('threads'),
	c_pch: 'pch/pch.h')
```

main.c:
```c
#include <pthread.h>

int main()
{
	return 0;
}
```
pch/pch.h:
```c
#include <stdlib.h>
```

Executing `meson build && cd build && ninja`:
```
The Meson build system
Version: 0.37.1
Source dir: /home/polarina/projects/mesonthreads
Build dir: /home/polarina/projects/mesonthreads/build
Build type: native build
Project name: mesonthreads
Native c compiler: cc (gcc 6.3.0)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Dependency threads found: YES
Build targets in project: 1
[2/3] Compiling c object 'magic@exe/main.c.o'
FAILED: magic@exe/main.c.o 
cc  '-Imagic@exe' '-fdiagnostics-color=always' '-I.' '-I..' '-pipe' '-Wall' '-Winvalid-pch' '-O0' '-g' '-pthread' '-include' 'pch.h' '-MMD' '-MQ' 'magic@exe/main.c.o' '-MF' 'magic@exe/main.c.o.d' -o 'magic@exe/main.c.o' -c ../main.c
cc1: warning: magic@exe/pch.h.gch: not used because `_REENTRANT' is defined [-Winvalid-pch]
cc1: error: one or more PCH files were found, but they were invalid
cc1: fatal error: pch.h: No such file or directory
compilation terminated.
ninja: build stopped: subcommand failed.
```

**Comment by jpakkane** [comment]
I can't reproduce the failure. Meson compiles the pch file without -pthread (which is a bug) and the source file with -pthread but it works without issues (amd64, Ubuntu zesty). Which platform is this happening on?

**Comment by polarina** [comment]
This is on Debian Stretch.

**Comment by jpakkane** [comment]
I got that wrong. It is passing -pthread to both:

    [2/6] ccache cc  -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O0 -g -pthread -MMD -MQ 'witthreads@exe/thread_pch.h.gch' -MF 'witthreads@exe/thread_pch.h.gch.d' -o 'witthreads@exe/thread_pch.h.gch' -c '../test cases/common/13 pch/pch/thread_pch.h'

Can you test if trunk works for you?

**Comment by polarina** [comment]
It would appear that latest HEAD is working fine, `-pthread` is getting passed to the header compiler.

Thanks for checking into this. I'll make sure to test with latest from now on.
