### ISSUE TITLE
libdir detection is buggy in many cases

### ISSUE THREAD

**Issue by Jehan** [mesonbuild/meson#2038]
I have been cross-compiling json-glib (which uses meson) for 32-bit and it would install it inside lib64/:

The compilation is fine and renders proper 32-bit:

> $ file lib64/libjson-glib-1.0.so.0.301.0 
> lib64/libjson-glib-1.0.so.0.301.0: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, not stripped

Only the path is wrong.
Also since I am building from a 64-bit platform, this may be the problem, of course. Basically do not decide on the installation path from the build OS, but from the host one.
I filled a bug in json-glib, but they tell me the problem is with meson: https://bugzilla.gnome.org/show_bug.cgi?id=784532

Also for information, I do not consider the proposed solution of setting `--libdir` valid. I know of this option, which exists on all other build systems (and that's a good option), but it should not be a reason not to have sane defaults.

**Comment by jpakkane** [comment]
The default for that should probably be settable in the cross file...

**Comment by Jehan** [comment]
What settings would it be? sizeof_int?
In any case, when cross-compiling, if such a settings is not set, that should default to lib/ (this can never go wrong).

Is there no good way to determine if the target is 64 bit? I could think of checking `gcc -dumpmachine` output, and if it has a 64 in it, assuming 64-bit. Now that's dirty and I can say for sure it is not totally reliable (for instance `i686-w64-mingw32-gcc` target is 32-bit).

As a last comment, I would not be against just defaulting to lib/ always, even when the target is know 64-bit. The directory lib64/ is somewhat considered deprecated by many distributions and I think all 64-bit distributions will look in lib/ as well as lib64/ anyway.

**Comment by jpakkane** [comment]
> What settings would it be? sizeof_int?

I was thinking more in the line of `libdir`...

**Comment by Jehan** [comment]
> I was thinking more in the line of libdir...

In which section do you set this? I tried under every section in [your doc](http://mesonbuild.com/Cross-compilation.html) (host_machine, binaries, properties… tried them all just to be sure) but it didn't set `libdir`.

**Comment by jpakkane** [comment]
> did you actually mean that you should add this

Yes.

**Comment by topilski** [comment]
ping

**Comment by TheQwertiest** [comment]
The following changes were made in `meson` 0.50.0:
- Added support for setting `libdir` via crossfile was (via https://github.com/mesonbuild/meson/pull/4743).
- Default `libdir` for cross compilation was changed to `lib` (via https://github.com/mesonbuild/meson/pull/4680).

**Comment by dcbaker** [comment]
I think this should have been closed by 4743 as well. I'm going to close this.
