### ISSUE TITLE
 Language fortran does not support library finding

### ISSUE THREAD

**Issue by sprock** [mesonbuild/meson#2043]
The title summarises the issue.

I'm attaching a meson.build file and hello.f95.

Test system: FreeBSD 10.3-RELEASE-p11, i386, meson-0.41.1

Invocation: LD_LIBRARY_PATH=/usr/local/lib/gcc5 meson ..

[fortran.tar.gz](https://github.com/mesonbuild/meson/files/1131565/fortran.tar.gz)

**Comment by nirbheek** [comment]
Huh, that should have worked. I guess no one tried it before. I can reproduce it:

```
Meson encountered an error in file meson.build, line 7, column 0:
Language fortran does not support library finding.
```
