### ISSUE TITLE
combining multiple static libraries into one

### ISSUE THREAD

**Issue by yoava333** [mesonbuild/meson#205]
it's not uncommon to create a static library that is a combination of multiple static libraries.
Meaning i have my project dir:
-proj
-- a
-- b
-- c

they result in liba.a, libb.a, libc.a. I want to create a libproj.a that contains all other static libraries.
In autotools it's possible to define a Makefile.am that accomplishes the same task:

liba_la_SOURCES = \ 
a/a.cxx \ 
a/a.h \ 
$(NULL) 

libb_la_SOURCES = \ 
b/b.cxx \ 
b/b.h \ 
$(NULL) 

libc_la_SOURCES = \ 
c/c.h \ 
c/c.cxx \ 
$(NULL) 

libcombo_la_LIBADD = \ 
liba.la \ 
libb.la \ 
libc.la \ 
$(NULL)

I think that an API should be implemented for this target.

**Comment by jpakkane** [comment]
You can do the same already like this:

    a = static_library('a', ...)
    b = static_library('b', ...)
    c = static_library('c', ...)

   combined = [a, b, c]

   exe('foo', ..., link_with : combined)

**Comment by yoava333** [comment]
It's not what I'm trying to achieve.
I want to be able to combine libraries into a combined library.
What you offer is a way to link them into an executable.
I want define this combination once, and every project that consumes my project will be able to use the combined library and have access to all symbols of the underlying libraries.

**Comment by ignatenkobrain** [comment]
@jpakkane it's like static_library('lib', objects : combined), but extract_objects() is hell here
