### ISSUE TITLE
pkgconfig appends slash at Cflags, which can break some compilation

### ISSUE THREAD

**Issue by lordheavy** [mesonbuild/meson#2050]
generate_pkgconfig_file() generate following pkgconfile file with libinput:
```
pkgconfig.generate(
	filebase : 'libinput',
	name : 'Libinput',
	description : 'Input device library',
	version : meson.project_version(),
	libraries : lib_libinput
)
```

produces:
```
prefix=/usr
libdir=${prefix}/lib
includedir=${prefix}/include

Name: Libinput
Description: Input device library
Version: 1.8.0
Libs: -L${libdir} -linput
Cflags: -I${includedir}/
```
Following patch fixes the issue:
[0001-pkgconfig-avoid-appending-slash-at-Cflags.patch.txt](https://github.com/mesonbuild/meson/files/1138640/0001-pkgconfig-avoid-appending-slash-at-Cflags.patch.txt)

Archlinux bugreport: https://bugs.archlinux.org/task/54763

**Comment by nirbheek** [comment]
Could you please open a pull request with that patch? We'll merge it asap.

**Comment by lordheavy** [comment]
https://github.com/mesonbuild/meson/pull/2051

**Comment by lordheavy** [comment]
Could this be possible to backport it to branch 0.41 or should i create a new pull request?

**Comment by nirbheek** [comment]
I have added it to my [0.41.2 stable release list](https://github.com/mesonbuild/meson/milestone/18). Once I have some time to fix #1946, we'll make a new release.

**Comment by lordheavy** [comment]
Great!

**Comment by nirbheek** [comment]
Fixed with https://github.com/mesonbuild/meson/pull/2051.
