### ISSUE TITLE
pkgconfig.generate() should be able to take dependency objects

### ISSUE THREAD

**Issue by zmike** [mesonbuild/meson#2079]
When writing a pkgconfig file, the most common usage is to set `requires` to the dependencies of your project. It should be possible to pass a dependency or [dependencies] as the requires argument.

**Comment by zmike** [comment]
To be clear, I'm requesting that dependency objects of type pkgconfig be usable, not e.g., libm which does not have pkgconfig support.

**Comment by nirbheek** [comment]
This is a duplicate of https://github.com/mesonbuild/meson/issues/1204. Closing.
