### ISSUE TITLE
generate-gir: Forgets to add self.include_directories to cflags

### ISSUE THREAD

**Issue by ndufresne** [mesonbuild/meson#2093]
I've hit issue in GStreamer when generating gir for certain libraries if their header were not already installed in my prefix (yet, it's scary, we we endup picking headers from prefix). Looking deep down, I found that the local header are missing in the cflags-being/end parameters. 

Further down, I found that _get_dependencies_flags() will generate flags for all dependency, but ignore the information that is set in self (the library). Those path are really important, and order matter to avoid picking ancient header from the  prefix. I only checked the cflags part so far.

I detected this error when I got:
<unknown>:: Fatal: GstPlayer: Namespace is empty; likely causes are:
* Not including .h files to be scanned
* Broken --identifier-prefix

**Comment by ndufresne** [comment]
Could be related to #1181

**Comment by QuLogic** [comment]
I believe this should be closed by #2095.
