### ISSUE TITLE
pthread function checking can't replicate a cmake check.

### ISSUE THREAD

**Issue by ntzrmtthihu777** [mesonbuild/meson#2106]
Hullo. Sorry if this question has been answered or if the proper way to do it is obvious and I'm blind.
I'm working on porting/creating a wrap for [openal-soft](https://github.com/kcat/openal-soft), getting
pretty far into it, but I'm having trouble replicating the following cmake snippet:
```cmake
CHECK_LIBRARY_EXISTS(pthread pthread_create "" HAVE_LIBPTHREAD)
IF(HAVE_LIBPTHREAD)
    SET(EXTRA_LIBS pthread ${EXTRA_LIBS})
ENDIF()
```
I've tried the following:
```meson
thread_dep = dependency('threads', required : false)
cc.has_function('pthread_create')
cc.has_function('pthread_create', dependencies : thread_dep)
cc.has_function('pthread_create', dependencies : thread_dep, prefix : '#include <pthread.h>')
```

Also, there is an odd snippet I've ran into in this same project which is like so:
```cmake
CHECK_SYMBOL_EXISTS(pthread_setname_np "pthread.h;pthread_np.h" HAVE_PTHREAD_SETNAME_NP)
```

Perhaps cc.has_header_symbol should be able to take an array of header strings? Seems some systems may require two headers to access certain functions.

**Comment by jpakkane** [comment]
> Perhaps cc.has_header_symbol should be able to take an array of header strings

You can already do this with the prefix keyword. Something like this:

    multiline_prefix = '''#include<pthread.h>
    #include<pthread_np.h>'''
    cc.has_function('pthread_create', dependencies : thread_dep, prefix : multiline_prefix)
