### ISSUE TITLE
-Db_sanitize=address does not work with gobject introspection

### ISSUE THREAD

**Issue by chergert** [mesonbuild/meson#2117]
In a GNOME Builder build directory, I ran `mesonconf -Db_sanitize=address` and then `ninja`. I had to manually install `libasan` which wasn't detected by the configure phase (and that is probably a bug in it's own right). But furthermore, when trying to compile GObject Introspection hooks, I get an error like the following and the build stops.

```
g-ir-scanner: link: cc -o /home/christian/Projects/gnome-builder/build/tmp-introspectqp6sl5na/Gstyle-1.0 -ggdb -O0 -fno-omit-frame-pointer /home/christian/Projects/gnome-builder/build/tmp-introspectqp6sl5na/Gstyle-1.0.o -L. -Wl,-rpath,. -Wl,--no-as-needed -lgstyle-private -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -ldazzle-1.0 -lxml2 -lm -L/home/christian/Projects/gnome-builder/build/contrib/gstyle -Wl,-rpath,/home/christian/Projects/gnome-builder/build/contrib/gstyle -L/opt/gnome/lib -Wl,-rpath,/opt/gnome/lib -L/home/christian/Projects/gnome-builder/build/contrib/gstyle -Wl,-rpath,/home/christian/Projects/gnome-builder/build/contrib/gstyle -L/opt/gnome/lib -lgio-2.0 -lgobject-2.0 -Wl,--export-dynamic -lgmodule-2.0 -pthread -lglib-2.0 -L/opt/gnome/lib
//usr/lib64/libasan.so.4: warning: the use of `tmpnam' is dangerous, better use `mkstemp'
//usr/lib64/libasan.so.4: warning: the use of `tempnam' is dangerous, better use `mkstemp'
//usr/lib64/libasan.so.4: warning: the use of `tmpnam_r' is dangerous, better use `mkstemp'
==5886==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.
Command '['/home/christian/Projects/gnome-builder/build/tmp-introspectqp6sl5na/Gstyle-1.0', '--introspect-dump=/home/christian/Projects/gnome-builder/build/tmp-introspectqp6sl5na/functions.txt,/home/christian/Projects/gnome-builder/build/tmp-introspectqp6sl5na/dump.xml']' returned non-zero exit status 1.
```

**Comment by TingPing** [comment]
Fixed by https://github.com/mesonbuild/meson/commit/ccb253189ad970354d46f0a8e3bf381774c404af Duplicate of #1910

**Comment by chergert** [comment]
This seems to have broken again for me, but I'm not sure why. I can't seem to build glib with `-Db_sanitaize=address` either (it fails on install).

But Dazzle also fails, which I had working a couple weeks ago (on perhaps an older meson).

**Comment by jpakkane** [comment]
I don't think we have changed anything specific to this. Could there possibly have been a toolchain update and only some of your object files have been rebuilt but not all of them?

**Comment by chergert** [comment]
I specifically remove my build dirs when I change this just to ensure that can't happen.

**Comment by chergert** [comment]
I also purged the ccache, but that didn't seem to make a difference either.

**Comment by chergert** [comment]
I just tested things on a second computer (both systems using jhbuild on Fedora 28) and the second computer worked fine. The working machine has meson 0.46.1. The broken machine has 0.47.1.

It's possible that there are other things different, but I usually keep a very similar configuration between development machines and use the same `.jhbuildrc` and what not.

**Comment by jpakkane** [comment]
Can you bisect the exact commit that breaks?

**Comment by chergert** [comment]
Let me confirm that updating the second computer to 0.47.1 breaks it.

**Comment by chergert** [comment]
Okay, I can confirm that switching the working machine to 0.47.1 does in fact break things. Will commence with bisect.

**Comment by chergert** [comment]
The commit that broke things is commit cb36add970d448f8b4ace7e4dc6028e5441bccd7

**Comment by chergert** [comment]
@TingPing made a suggestion on IRC that seems to work. I'll leave it to him to make a MR, since it's his patch.

```patch
diff --git a/mesonbuild/modules/gnome.py b/mesonbuild/modules/gnome.py
index 1459ffe4..afc0b3a2 100644
--- a/mesonbuild/modules/gnome.py
+++ b/mesonbuild/modules/gnome.py
@@ -511,7 +511,7 @@ class GnomeModule(ExtensionModule):
                 sanitize = state.environment.coredata.base_options['b_sanitize'].value
                 cflags += compilers.sanitizer_compile_args(sanitize)
                 if 'address' in sanitize.split(','):
-                    external_ldflags += ['-lasan']
+                    internal_ldflags += ['-lasan']
                 # FIXME: Linking directly to libasan is not recommended but g-ir-scanner
                 # does not understand -f LDFLAGS. https://bugzilla.gnome.org/show_bug.cgi?id=783892
                 # ldflags += compilers.sanitizer_link_args(sanitize)
```
