### ISSUE TITLE
read cmake export config files

### ISSUE THREAD

**Issue by nschloe** [mesonbuild/meson#2119]
I'm in the process of converting my first project from CMake to meson. While everything started out just fine, I seem to have hit a dead end: Some of my dependencies install CMake export files only, 
```
FooConfig.cmake
FooTargets.cmake
FooTargets-none.cmake
```
and _not_ pkg-config files. If I understand correctly, meson cannot read those CMake files.

Given the fact that the body of software built with CMake is so large, I suspect that being unable to read CMake export files will be a limiting factor to meson's growth.

**Comment by hardening** [comment]
Perhaps https://github.com/mesonbuild/meson/pull/3098 could be a good start ?

**Comment by eli-schwartz** [comment]
This was implemented in #4444
