### ISSUE TITLE
referencing another target in a "custom_target" command does not add it as a dependency

### ISSUE THREAD

**Issue by bruce-richardson** [mesonbuild/meson#2120]
When using custom_target to generate sources, sometimes the binary doing the generation needs to be called via a script, passing in to the script the path to the binary if it is generated via meson earlier in the build.  In these cases, despite the generated binary being referenced in the custom_target command, it is not recognised as a dependency.

For example:

gen = executable('gen', gen.c)
gen_sh = find_program('gen.sh') # which takes path to gen as parameter
....
sources += custom_target('out.c', command: [gen_sh, '@INPUT@', '@OUTPUT@', gen.full_path()], 
                   input: src, output: 'out.c')

In the above example, the build can fail when run with many cores, as the custom_target call can be run before "gen" has been build.

Adding in "depends:" to custom_target fixes this, but the fact that "gen" is referenced in the parameters should mean it gets added as an implicit dependency.

**Comment by jpakkane** [comment]
`gen.full_path()` should be just `gen`.

**Comment by bruce-richardson** [comment]
yes, that works. 

However, on a related matter: to pass in e.g. a static lib as parameter we do need the explicit full_path() call. This seems inconsistent (though that is a different issue to this one). Does adding lib.full_path() to the command parameters add a dependency in that case? My builds seem to pass, but that doesn't guarantee there is not a problem.

**Comment by jpakkane** [comment]
> we do need the explicit full_path() call

If this is the case then that is a bug, please file an issue with specifics.

> Does adding lib.full_path() to the command parameters add a dependency in that case?

No. `lib.full_path()` is only a string representation of the path in question, nothing else. In >99% of cases you just use the object as is and we take care of everything else. The reason `full_path` even exists is that there are executables (such as the Arduino flasher application) that take file paths as a part of a string, something like `foo:/path/to/thingy:bar`. `full_path` should only be used in these cases (and preferably not even then but by fixing the original program to take arguments in a more sane way but often that is not possible).

**Comment by bruce-richardson** [comment]
Ok. So no issue with passing a binary. Will reconfirm the library case and log bug if that doesn't work as expected.
