### ISSUE TITLE
vs2010 backend attempts to honor link_whole, but lacks support

### ISSUE THREAD

**Issue by dcbaker** [mesonbuild/meson#2122]
Starting with vs2015 of MSVC a `/WHOLEARCHIVE` flag allows link_whole to be implemented. VS2010 doesn't have this flag, but still attempts to generate libraries using it. It seems like basically using link_whole excludes the use of VS2010.

**Comment by nirbheek** [comment]
I guess we should output a warning or maybe even error out if `link_whole:` is used and the current backend is vs2010.

**Comment by fanc999** [comment]
Hi,

I am taking a shot at this in PR 8802
