### ISSUE TITLE
Windows UTF-8 Encoding

### ISSUE THREAD

**Issue by Godrod** [mesonbuild/meson#2126]
I am building my own project with meson but I get this error when I run meson with native windows python: [log.txt](https://github.com/mesonbuild/meson/files/1176846/log.txt)

**Comment by voidhoschi** [comment]
Hmm. I remember a rather nasty error in my build on Windows. Is it possible, that you use accidentally a SHELL-Variable which is not existing?

**Comment by Godrod** [comment]
Switching Windows language from French to English fixed the issue.

**Comment by nirbheek** [comment]
Can you try the latest git master with the Windows language as French? We recently pushed a patch that should make this work better: https://github.com/mesonbuild/meson/pull/2331

**Comment by Godrod** [comment]
It still doesn't work with the same error

**Comment by nirbheek** [comment]
Could you please reduce it to a small testcase that you can upload here? I'll try to reproduce it in a VM and see what I can do about it.

**Comment by Norman0406** [comment]
I'm also experiencing the same problem, same log message as @Godrod. Windows language is german. Seems as if Meson is trying to read a file with code page `cp1252`. Any news on this?

**Comment by Tachi107** [comment]
@Godrod @Norman0406 are you still expecting the issue in the latest Meson release?

**Comment by nirbheek** [comment]
Yeah, this should be fixed now. Let's close it and we can reopen if it's not fixed.
