### ISSUE TITLE
Support thin archives for static libraries that are not installed

### ISSUE THREAD

**Issue by vaeth** [mesonbuild/meson#2129]
I have a project which generates several executables which (partially) share the same source files.
Since each executable is first compiled in its own subdirectory, all these shared source files are recompiled for every executable. This is undesirable if I know that identical object files will be produced (that is, the compiler options are identical).

Is there a way to specify the name of the build-subdirectory to avoid this repeated redundant compilation?

I am aware that one could use static libraries to work around this problem, but besides being overkill this also has several disadvantages: It also has the overhead of building the library, and moreover, to support e.g. proper support for LTO it requires linker plugins etc.

**Comment by nirbheek** [comment]
LTO works just fine across static libraries. The overhead of creating static libraries is small, but we should actually start supporting "thin archives" for static libraries that are never installed. That would completely remove that overhead too, for cases in which the static library contains many object files.

**Comment by vaeth** [comment]
> LTO works just fine across static libraries.

This information is wrong. I first believed this information and unfortunately made a buggy release which breaks for people who have not configured linker plugins:

Only if gcc has linker plugins installed (e.g. if /usr/x86_64-pc-linux-gnu/binutils-bin/lib/bfd-plugins contains a symlink to the current gcc's liblto_plugin.so.0.0.0) static libraries compiled with -flto (and without -ffat-lto-objects) can be accessed correctly.

Here is the (correct) bug report which I received when people do not have the plugin installed:
https://github.com/vaeth/mv-overlay/issues/2

**Comment by nirbheek** [comment]
Interest, I wonder if it's a distro-specific toolchain thing. Maybe Gentoo should enable the liblto plugin by default?

Could you provide a test case for LTO via static archives? The last time I tested it, it worked for me on Fedora. I would like to investigate this more.

**Comment by vaeth** [comment]
Strange. Now I cannot reproduce it anymore. Of course, my toolchain has changed meanwhile, so there may be a lot of causes. I am sure, everything I did last time to get the error was to remove my manually set symlink `/usr/x86_64-pc-linux-gnu/binutils-bin/lib/bfd-plugins/liblto_plugin.so.0.0.0` (on amd64) or `/usr/i686-pc-linux-gnu/binutils-bin/lib/bfd-plugins/liblto_plugin.so.0.0.0` (on i686).

I append a somewhat minimal meson.build which should produce the error (though currently it doesn't, here). Note the usage of -fno-fat-lto-objects so that really some sort of ar plugin/wrapper must be used to access the static archive.
```
project('test','cpp',version:'0')
run_command(find_program('sh'), '-c', '''
echo 'int dummy(int i);int dummy(int i){return i;}' >sub.cc
echo 'int dummy(int i);int main(){return dummy(0);}' >main.cc
''')
args=['-use-linker-plugin','-flto',-fno-fat-lto-objects']
add_global_arguments(args,language:'cpp')
add_global_link_arguments(args,language:'cpp')
executable('main','main.cc',link_with:static_library('sub','sub.cc'))
```

**Comment by vaeth** [comment]
Now I found the reason:

meson defaults to gcc-ar which does not require a linker plugin. The linker plugin is required if one uses the original binutil's ar. For instance, on my gentoo system the above meson.build fails when called after
```export AR=ar```
or, equivalently, (on an amd64 system)
```export AR=x86_64-pc-linux-gnu-ar```
or (on an x86 system)
```export AR=i686-pc-linux-gnu-ar```
Gentoo's meson.eclass by default exports this architecture-specific AR variable (alongside with architecture-specific CC, CXX, STRIP) depending on cross-compilation mode. This behaviour appears to be correct to me (note that also other compilers than gcc might be used, especially when cross-compiling). Unfortunately, it does not work without the symlinks mentioned in the previous comment.

@nirbheek I do not know why gentoo does not set the mentioned symlinks by default. I suppose that it has something to do with its cross-compiler support and for supporting switching gcc versions on the fly. (In the moment, things seem to work when the symlink points to a non-matching gcc version's library, but this might be accidental and change.)

**Comment by vaeth** [comment]
A corresponding bug is reported for gentoo https://bugs.gentoo.org/show_bug.cgi?id=630066

Independent of that, it would be nice to have a way to avoid creating a static archive which is actually unneeded since the .o files could be accessed directly in the corresponding subdirectory.

**Comment by nirbheek** [comment]
> Independent of that, it would be nice to have a way to avoid creating a static archive which is actually unneeded since the .o files could be accessed directly in the corresponding subdirectory.

People have requested an "object library" of sorts from time to time, but their use-cases can always be fulfilled by static libraries, and a thin static library would cover even the 'hundreds of objects' use-case. We are hesitant to add a 'virtual object bundle' unless absolutely needed because a static library is already supposed to be that.

**Comment by pwnorbitals** [comment]
This feature request doesn't seem to have a high demand. Not sure if there is any plan to implement this in the future
