### ISSUE TITLE
`python3 setup.py install` does not explicitly set file modes

### ISSUE THREAD

**Issue by vcaputo** [mesonbuild/meson#2147]
To reproduce, set your umask to 027, clone the meson repo, then perform the install with root.  Then try use meson as a regular user, none of the installed python module files are readable by other.

For users (like myself) running with a 027 umask (safer in multi-user environments), this results in a quite annoying failure mode.

**Comment by nirbheek** [comment]
`setup.py install` is only for use by distributors. Users are expected to directly run `meson.py` from the git repository as-is.

**Comment by eli-schwartz** [comment]
If your home directory is not world-readable, then you don't need to fiddle with umask. Anyway, this is a setuptools "bug".

**Comment by vcaputo** [comment]
There's a reason 'install(1)' exists *and* takes a mode flag.

Telling me to not use umask is unhelpful.

**Comment by eli-schwartz** [comment]
Again, this is not a meson bug. pip, or setuptools, is the installation framework here. meson does not control this.

My opinions on umask vs. `chmod go-rwx "$HOME"` are an aside.

meson bows to the will of setuptools for handling distribution install. I don't believe any alternative python packaging mechanism solves this, but I could be wrong. Makefile build systems are just as broken on average, though some permit `make INSTALL="install -m755"` I guess.
You could alternatively symlink meson.py into $HOME/bin or wherever.

**meson as a build system** does not perpetuate this -- see https://mesonbuild.com/Builtin-options.html#core-options
`meson setup builddir/ -Dinstall_umask=[preserve|0000-0777]`, the default is a nice sane 0022. It thus works even on distros which unwisely set /home/* to be world-readable.

**Comment by eli-schwartz** [comment]
Another possibility is to run `python3 ./packaging/create_zipapp.py && sudo install -m755 meson.pyz /usr/local/bin/meson`. It creates a single-file executable for meson.
