### ISSUE TITLE
b_pgo=use is missing -fprofile-correction

### ISSUE THREAD

**Issue by heftig** [mesonbuild/meson#2159]
Replace `-fprofile-use` with `-fprofile-use -fprofile-correction`.

This is often needed in order to be able to use profiles generated by multithreaded programs. It avoids GCC exiting with an `error: corrupted profile info: …`.

**Comment by jpakkane** [comment]
Why is that not the default for GCC? Corrupting files by default seems like a bad choice.

**Comment by heftig** [comment]
Apparently the instrumentation that writes the profiles is deliberately not thread-safe to make it faster. 
The only explanation I found is at https://gcc.gnu.org/ml/gcc-patches/2008-03/msg01235.html . It's supposed to be an "interim solution" but is still in place as of GCC 7.

**Comment by heftig** [comment]
Any progress? This should be trivial to add, although perhaps not trivial to test for regressions.

AFAIU correction is necessary for profiles from multithreaded programs to be usable, but does not harm profiles that do not need correction.
