### ISSUE TITLE
unknown method to_upper for string object

### ISSUE THREAD

**Issue by Flow-It** [mesonbuild/meson#2162]
Following line throws the error message from the title:
`'hello world'.to_upper()`

This happens on Ubuntu 16.04, meson version is 0.29. Unfortunately I couldn't find any documentation in which version which methods were added, so I couldn't find out if the error is related to the rather old version.

**Comment by nirbheek** [comment]
0.29 is extremely old, before we started tracking which versions added which methods. I am not even sure if we had the reference manual back then. Please use a newer version of Meson. You can either use:

```
$ pip3 install --user meson
```

Which will install the last meson release and provide `meson` in `~/.local/bin`, or you can just git clone meson's repository and run `meson.py` from there.

I am closing this issue, but feel free to open new issues about bugs you find with more recent Meson versions. Thanks :)

**Comment by nirbheek** [comment]
Alternatively, you can enable xenial-backports which will give you a much more recent version of Meson.

**Comment by TingPing** [comment]
`apt install meson/xenial-backports` specifically.
