### ISSUE TITLE
Can't add generated files to the tarball during dist, needed for gtk-doc and tracker

### ISSUE THREAD

**Issue by hadess** [mesonbuild/meson#2166]
This would make it easier to install documentation without having to compile the library. library.gnome.org 's software doesn't integrate with a C-I and expects generated gtk-doc help files to be available in the distribution tarballs.

**Comment by jpakkane** [comment]
Source is source and generated files are generated files and mixing the two will not be supported. If you want to do this you need to generate a custom dist target generator or something similar. The proper fix is to fix the CI pipeline to not require prepackaged files. This makes it also support building directly from Git without interim dist files.

**Comment by tp-m** [comment]
Might just as well check the html into git then tbh and update from time to time ;)

**Comment by nirbheek** [comment]
Why make releases at all then? Just tell people to use the git tag.

The answer of course is that the release tarball is not always the same as the git tag. Some people do need to generate OS-independent files for various reasons (reduced build time, reduced build dependencies, and so on) and distribute them with the tarball.

**Comment by nirbheek** [comment]
FWIW, I do agree that there is a line to be drawn somewhere. For instance, I don't think we should allow other types of targets to be run as a part of dist because it can and will confuse meson (think, stale glib-mkenums enumtypes in the source tree). But we do need a way to define targets that will be run as part of dist, and run targets are a good choice, IMO.

**Comment by TingPing** [comment]
This was discussed on the mailinglist also but doing this for gtk-doc was just a workaround for poor infrastructure on GNOMEs part and with better CI and hosting potentially coming this workaround might no longer be needed?

**Comment by nirbheek** [comment]
I did get that impression from the mailing list, but it requires someone to do the work first and/or wait for the Gitlab transition. Both of those are suboptimal, and in the meantime people are putting in some really hacky workarounds in their projects. I think we can only hope that it gets resolved one way or another before the next GNOME release. :)

**Comment by hadess** [comment]
> Might just as well check the html into git then tbh and update from time to time ;)

You should be worried that the "current stable" version of GStreamer's docs on developer.gnome.org has 1.2 from around 2014 (for reference, current is 1.12), because of this exact problem.

**Comment by nirbheek** [comment]
> You should be worried that the "current stable" version of GStreamer's docs on developer.gnome.org has 1.2 from around 2014 (for reference, current is 1.12), because of this exact problem.

That seems unrelated because GStreamer still has Autotools as its primary build system, our tarballs have gtk-doc documentation, and the Meson build files were only added in 1.10.

**Comment by tp-m** [comment]
Yeah, I have no idea why that is. Tried to find out a few times, but no one could tell me who to poke or what the reason might be. I think that's unrelated though :)

**Comment by nirbheek** [comment]
As another datapoint, Tracker needs to include generated files in the dist tarball, and changing that will involve difficult code changes, see [comment 4 on this bug](https://bugzilla.gnome.org/show_bug.cgi?id=785247#c4). 

Background: Tracker automatically tracks when its parser code changed by storing the [SHA1 of the last commit to the parser code in a header](https://git.gnome.org/browse/tracker/tree/src/libtracker-common/Makefile.am#n16) so that it can migrate local databases whenever needed. This works fine in git, but doesn't work in tarballs.

> `<garnacho>` nirbheek: background: I need to track changes over a group of files, so users get stuff triggered on their local databases when running newer/older trackers
> `<garnacho>` this takes seconds to minutes, so I'd rather not do it on every new version

The autotools build adds that header to [`EXTRA_DIST`](https://git.gnome.org/browse/tracker/tree/src/libtracker-common/Makefile.am#n85) so it gets included in the tarball. Not every tracker release touches the parser code, so doing the update on every release is going to be painful for users.

I think we need a mechanism to have targets that are:

1) Only run when building from code in version control
2) Can be run during dist and included in the generated tarball

`run_target()`s are probably not a good choice for this because of (1), which implies being built during compilation. We could either extend `custom_target()`s or create a new target called `dist_target()` or similar.

**Comment by jpakkane** [comment]
> We could either extend custom_target()s or create a new target called dist_target() or similar.

Or `add_dist_script` which behaves similarly to `add_install_script`.

**Comment by nirbheek** [comment]
That would solve it for Tracker, but would also duplicate code. Maybe we should also have `add_dist_target()` which takes a `custom_target()` or a `run_target()`?

**Comment by ignatenkobrain** [comment]
I would say that it would be very handy to declare some generated files (be that gtk-doc or a2x manpages), people should be able to include those in dist tarball.. This really saves a lot of time for building such projects because stuff like sphinx pulls texlive.. But we need to have really good design for such things..

**Comment by inigomartinez** [comment]
This also happens withd docbook documentation created by `gdbus-codegen`. NetworkManager for example, distributes these docbook files, but since these are generated they are not added to the distributable file.

**Comment by smcv** [comment]
Having a way to add files to dist tarballs would also resolve #688 by providing what `git-version-gen` needs, I think (specifically, it wants to add `.tarball-version` to the dist tarball so that the dist tarball can know its own version without `.git` being available).

**Comment by smcv** [comment]
It is now possible to do this with a dist script (#3906).

**Comment by xclaesse** [comment]
Thanks, closing then.

**Comment by eli-schwartz** [comment]
In practice... how do you recommend using these, for example to build a2x manpages via a custom_target from a git checkout, but use the dist artifacts in the source tre if they exist? And how to make sure they use the same command to generate them?

Duplicate lots of code and ifdef the install targets?

What about detecting when they are out of date?

**Comment by jpakkane** [comment]
Something like the following seems like a reasonable approach:

```meson
fs = import('fs')
if fs.exists('prebuiltdir')
    install_subdir(...)
else
   # build and install as usual
endif
```

Where your dist script copies the man dir as-is under `prebuiltdir`.

**Comment by thmo** [comment]
> Having a way to add files to dist tarballs would also resolve #688 by providing what `git-version-gen` needs, I think (specifically, it wants to add `.tarball-version` to the dist tarball so that the dist tarball can know its own version without `.git` being available).

In principle yes, however, unfortunately `run_dist_scripts()` is called after `del_gitfiles()`, hence a custom dist script cannot use `git describe` or similar anymore to get the version from git, as the `.git` files are gone at this point already.

**Comment by eli-schwartz** [comment]
> Where your dist script copies the man dir as-is under `prebuiltdir`.

The problem I'm having here, is that I'm unclear how you expect the man dir to be copied over, given it is accessible to the main meson builddir, but not the meson-dist hierarchy. Should I configure meson, build the manpages, install it into a prefix, and then copy out my man pages? Should I assume things based on my empirical observations of how meson lays out its builddir, and hardcode some paths?

Can I tell meson to check whether the `prebuiltdir` files are newer than the original sources, and if not (for example, if I apply a downstream backported patch which modifies a manpage) to rebuild them even though they exist?

**Comment by stapelberg** [comment]
> The problem I'm having here, is that I'm unclear how you expect the man dir to be copied over, given it is accessible to the main meson builddir, but not the meson-dist hierarchy. Should I configure meson, build the manpages, install it into a prefix, and then copy out my man pages? Should I assume things based on my empirical observations of how meson lays out its builddir, and hardcode some paths?

Here’s what works for me, stored as `meson-dist-script`:

```shell
#!/bin/sh

set -eu

cd "${MESON_DIST_ROOT}"
mkdir build
cd build
meson .. -Dprefix=/usr -Ddocs=true -Dmans=true
ninja
cp *.1 ../man/
cp *.html ../docs/
cd ..
rm -rf build
```

…and referenced in meson.build as:
```python
meson.add_dist_script('meson-dist-script')
```

**Comment by stefanv** [comment]
> Something like the following seems like a reasonable approach:
> 
> ```meson
> fs = import('fs')
> if fs.exists('prebuiltdir')
>     install_subdir(...)
> else
>    # build and install as usual
> endif
> ```
> 
> Where your dist script copies the man dir as-is under `prebuiltdir`.

What do you do in the case where the dist script generates a single file? I need the equivalent of "allow generated_file.txt to be included in the sdist". What I see at the moment is that the file is generated, but then removed before generating the archive, despite being allowed in the gitattribute file.

I invoke the script as follows to ensure that the output lands in the staging directory:

```
source = meson.project_source_root()
meson.add_dist_script(
  py,
  [f'@source@/numpy/_build_utils/gitversion.py', '--write', f'numpy/version.py']
)
```

**Comment by eli-schwartz** [comment]
You have to create it in `os.environ['MESON_DIST_ROOT']` as seen by the dist script. Using project_source_root will result in it being produced inside your current source directory instead of the staging directory.

**Comment by stefanv** [comment]
> You have to create it in `os.environ['MESON_DIST_ROOT']` as seen by the dist script. Using project_source_root will result in it being produced inside your current source directory instead of the staging directory.

Note that I only use `project_source_root` to find the repo location (it needs git information from the original repo), but the output is being generated where it should go (I think).

**Comment by eli-schwartz** [comment]
Hmm, you should be able to use `files('numpy/_build_utils/gitversion.py')` for that.

You still do need to ensure that the output is written to the dist root, rather than "whatever `os.getcwd()` is".

**Comment by stefanv** [comment]
Ah, OK, it wasn't clear to me from https://mesonbuild.com/Reference-manual_builtin_meson.html#mesonadd_dist_script whether the dist script is guaranteed to run in the staging dir or not. It's a bit frustrating not being able to query the distdir programmatically, and only have it exposed through environment variable.

**Comment by stefanv** [comment]
Thanks, @eli-schwartz, this seems to work:

```meson
source = meson.project_source_root()
python_bin = py.path()
meson.add_dist_script(
  'sh',
  ['-c', f'@python_bin@ @source@/numpy/_build_utils/gitversion.py --write ${MESON_DIST_ROOT}/numpy/version.py']
)
```

It would be helpful to be able to get hold of distdir somehow, but sending the above through sh does the trick.

**Comment by eli-schwartz** [comment]
That may break if the path has whitespace in it. Is it not possible to check the distdir environment variable inside gitversion.py?

**Comment by stefanv** [comment]
That script doesn't know anything about meson; it can be made to do so, I suppose, but it doesn't quite fit the mental model (i.e. it'd be an obscure hack).

BTW `files` does not seem to be usable inside string interpolation, as in:

```
gitversion = files('_build_utils/gitversion.py')[0]
python_bin = py.full_path()
meson.add_dist_script(
  'sh',
  ['-c', f'@python_bin@ @gitversion@ --write ${MESON_DIST_ROOT}/numpy/version.py']
)
```

**Comment by eli-schwartz** [comment]
> BTW `files` does not seem to be usable inside string interpolation, as in:

Correct, but it would work in:
```
[
    'sh',
    '-c',
    '"$1" "$2" --write "${MESON_DIST_ROOT}/numpy/version.py"',
    '_discard', python_bin, gitversion,
]
```

Which you'd need to do anyway, if you wanted to rely on `sh` itself providing safe tokenization of argv without relying on "SQL injection except shell". (Not that it's a security vulnerability, but it tends to be faiiure prone.)

**Comment by pevik** [comment]
> Here’s what works for me, stored as `meson-dist-script`:
> 
> ```shell
> #!/bin/sh
> 
> set -eu
> 
> cd "${MESON_DIST_ROOT}"
> mkdir build
> cd build
> meson .. -Dprefix=/usr -Ddocs=true -Dmans=true
> ninja
> cp *.1 ../man/
> cp *.html ../docs/
> cd ..
> rm -rf build
> ```
> 
> …and referenced in meson.build as:
> 
> ```python
> meson.add_dist_script('meson-dist-script')
> ```

@stapelberg @thesamesam This will not work when cross compile with `-f meson.cross`:
```
meson.build:3:0: ERROR: Could not invoke sanity test executable:
[Errno 8] Exec format error: '/tmp/tmp.QbaqINSw7b/meson-private/sanitycheckc.exe'.
```
Any hint, how to run this in host environment? Or at least how could I detect cross-compilation to avoid failure or quit with `make dist not supported on cross compilation`. I don't see any hint in https://mesonbuild.com/Cross-compilation.html

**Comment by thesamesam** [comment]
We can do [meson.is_cross_build()](https://mesonbuild.com/Reference-manual_builtin_meson.html#mesonis_cross_build) or [meson.can_run_host_binaries()](https://mesonbuild.com/Reference-manual_builtin_meson.html#mesoncan_run_host_binaries), I think.
