### ISSUE TITLE
find_library() should honor LDFLAGS (or similar) for library search path

### ISSUE THREAD

**Issue by tsnoam** [mesonbuild/meson#217]
Following email thread: https://groups.google.com/forum/#!topic/mesonbuild/WFyBhk4pQQY
Filing this bug report so discussion may continue here.

__The problem:__
1. We need to know the location of a library.
2. Tools we have to determine the location: pkg-config & looking at a pre-defined list of directories (what find_library() does)
3. pkg-config is not always an option.

__Possible solutions:__
If one would be able to use pkg-config, he may help it by setting PKG_CONFIG_PATH environment variable.
A very similar approach in semantics would be to either set LDFLAGS or LD_LIBRARY_PATH. However, parsing LDFLAGS and/or LD_LIBRARY_PATH is very hacky.

So can we hint meson to look in the right place?
One way is to add a new CLI argument to meson. Something like `meson -L/somewhere/lib ...`
This approach can be extended and provide a more complete solution for headers (include dirs) as well.

However, in the email thread Jussi is reluctant to add new CLI argument unless they are really needed.
So another solution is needed, or to come to agreement that adding a new CLI argument is necessary.

**Comment by jpakkane** [comment]
One of the problems here is how this works together with cross compilation. Ideally you would want to be able to search for libraries in both build and host but this would mean adding two new command line arguments. Pkg-config already deals with this quite nicely.

**Comment by tsnoam** [comment]
Actually, pkg-config doesn't handle target/host on cross-compiling very good.
There's a propsed change, though: http://www.freedesktop.org/wiki/Software/pkg-config/CrossCompileProposal/

**Comment by jpakkane** [comment]
You can specify a host specific pgk-config binary in your cross file as discussed here:

https://autotools.io/pkgconfig/cross-compiling.html

Come to think of it, I don't remember if I have wired the internals to use that. I'll need to fix that if it's not the case.

**Comment by tsnoam** [comment]
Correct me if I wrong, but as far as I understand it:
1. using a separate "pkg-config" for cross-compile still shares environment variables (PKG_CONFIG_PATH for example) between the host & the target.
that makes it difficult to control only one of them to access specific directories. (as it will affect both)

2. Using "PKG_CONFIG_SYSROOT_DIR" to add prefixes assumes identical conventions between the host machine and the cross-compiler toolchain ecosystem (i.e. assumes that both should have $SYSROOT/usr/lib/pkgconfig)

so unless I got it completely wrong, what I'm saying here is with the current state of pkg-config it is not yet perfect for cross-compiling.

**Comment by jpakkane** [comment]
It's not perfect by any means but it should be good enough to get work done and people are working on improving it.

As the old saying goes, you go to war with the army you have, not the one you wish you had. :)

**Comment by tsnoam** [comment]
after the pkg-config detour, back to the main issue here. how should lib directories be supplied when pkg-config is not an option?

**Comment by jpakkane** [comment]
One thing which I have been considering is to make custom options as easy to use as native options. One example would be to provide a data type for string array. This would array you to have a command line like this

    meson <other args> '-Dlibdirs=/lib/one /lib/two /lib/three'

And then in your Meson file you would access it like this:

    mylibdirs = get_option('libdirs')
    xlib = find_library('x', directories : mylibdirs)

Note that you can already do this today by doing this:

    mylibdirs = get_option('libdirs').split()

**Comment by nirbheek** [comment]
> after the pkg-config detour, back to the main issue here. how should lib directories be supplied when pkg-config is not an option?

`find_library` is now `cc.find_library` and now uses the linker to check if a particular library is available (similar to how `AC_CHECK_LIB` does it). This means you can set the `LIBRARY_PATH` env variable (when using gcc/clang and the `LIBPATH` env variable when using MSVC) to point to your "library providing" root. It also accepts a colon-separated list of directories. This is how almost everyone does non-default-linker-search-path library searching.

Alternatively, you can also do `cc.find_library (..., args : ['-L/some/dir/'])` if you wish. We're already using the `LIBRARY_PATH` method in the GStreamer project for our cross-platform builds with the Cerbero build system.

I think this issue is resolved now.

**Comment by tsnoam** [comment]
sorry for the *late* response.
yeah.. this looks like it will cover things.
