### ISSUE TITLE
configure_file() always regenerates config.h from the configuration: if there is no input: file

### ISSUE THREAD

**Issue by taz-007** [mesonbuild/meson#2170]
In a project with a configuration file, everytime a meson.build file is modified, this triggers the reconfigure part but also regenerates the config.h, meaning that when ninja is invoked just after it rebuilds every file depending on that config.h even though nothing changed regarding the config.h file.

content of meson.build:
project('foo', 'cpp' )
foo_sources = [ 'foo.cpp' ]
conf_data = configuration_data()
conf_data.set('VERSION', '"1.2.3"')
configure_file(output : 'config.h', configuration : conf_data)
foo_exe = executable('foo', foo_sources  )

content of foo.cpp
#include "config.h"
int main(){return 0;}

meson ; ninja ; touch meson.build ; ninja ; it now recompiles foo.cpp

Ideally the config.h file should not be overwritten(or mdate changed) if the content did not change

Tested with meson 0.41.2

**Comment by nirbheek** [comment]
This only happens when you're using `configuration:` and don't use an `input:` file. Ideally, we should always check if the contents have changed before replacing the original config.h, even if we run a command.

**Comment by nirbheek** [comment]
This was fixed with https://github.com/mesonbuild/meson/issues/2952.
