### ISSUE TITLE
Add a PcapDependency() that runs pcap-config and calls pcap_lib_version() for version checks

### ISSUE THREAD

**Issue by Flow-It** [mesonbuild/meson#2171]
Ubuntu 16.04
libpcap 1.7.4
meson 0.40.0

The following fails:
```
p = ['libpcap', '>= 1.7.4']
deps += dependency (p[0], version : p[1])
```

This works:
`deps += find_library (p[0])`

Unfortunately, I don't have the exact error message here. It it something like "Unable to find native dependency"

**Comment by nirbheek** [comment]
As the reference manual states, `dependency()` looks for pkg-config files, and libpcap does not ship with any. This is working as expected, and `cc.find_library()` is exactly what you should be using in this case.

**Comment by Flow-It** [comment]
The manual also states that in case no pkg-config files are found a library-specific fallback is invoked. I am not on the ubuntu machine now, so I don't know if it's the case there, but libpcap ships with the libpcap-config utility. The same would apply for example for libraries from the gnupg project, which also don't ship .pc files, but the *-config utilities. It would be nice if meson could support such a fallback, because the dependency function is a lot nicer to work with and provides more functionality (most importantly version checks) compared to the find_library function.

**Comment by nirbheek** [comment]
`pcap-config` seems to be a simple shell script that just tells you to use `-lpcap` + the prefix. It doesn't even have a `--version` param to find out the version, which is unfortunate.

It might be useful to have a `PcapDependency()` that can read `pcap-config` for the prefix and can fetch the return value of `pcap_lib_version()` for version checks. We'd be happy to review a pull request that adds it. Would you like to work on that?

**Comment by nirbheek** [comment]
Actually, there's already a PR for this: https://github.com/mesonbuild/meson/pull/2130
