### ISSUE TITLE
Scripts always trigger single-executable warning

### ISSUE THREAD

**Issue by QuLogic** [mesonbuild/meson#2178]
Scripts like a postconf script get a `MESONINTROSPECT` environment variable that points to `mesonintrospect`, but running this command _always_ generates a warning that it's deprecated. There is no `MESON` environment variable, so there's no way to avoid it.

**Comment by nirbheek** [comment]
I'm not sure why we warn at all, tbh. Git didn't start warning when it moved to a single entry point for all commands, and I don't see any advantage for it.

**Comment by jpakkane** [comment]
The advantage is to get rid of the standalone commands.

**Comment by nirbheek** [comment]
Why do we want to get rid of them? Why can't they co-exist with the single-executable mode?

**Comment by nirbheek** [comment]
This also happens with you run `ninja test`:

> Warning: This executable is deprecated. Use "meson test" instead.

This one is easier to fix.

**Comment by QuLogic** [comment]
It looks like `MESONINTROSPECT` was changed to be `python3 meson introspect` in 50fb7d37abc02b674b66071b51b1a2862fabb3cd, but now I need to manually/explicitly shell parse that. It was easier as a single path.

It's also a sort of API breakage, if you had written your post-conf script using best-practices, i.e., Python 3 and subprocess using lists. If you didn't split the environment variable (which seemed unnecessary since it was originally a single path), you won't be able to run introspection since `python3 meson introspect` is not a path to anything.

**Comment by nirbheek** [comment]
Yeah, it is ABI breakage, I agree. We can ease it with the method that I have mentioned earlier: https://github.com/mesonbuild/meson/pull/761#issuecomment-292801542. Quoting myself:

> Idea was that we check the `meson_version` specified in `project()`, and if it is older than the version in which the change was made, we use the older behaviour and print a warning. This code would be kept around for at most 3 releases (so people have 3 months) and then removed.

I tried implementing something like this in https://github.com/mesonbuild/meson/pull/1867, so we could probably repurpose it and do the ABI breakage properly for the 0.43.0 release.

**Comment by nirbheek** [comment]
In the meantime, I have removed that PR (https://github.com/mesonbuild/meson/pull/2195) from the 0.42.1 stable list, because we don't want to break people's scripts in a stable release.

**Comment by eli-schwartz** [comment]
The old executable entry points no longer exist at all, this warning cannot be generated and `$MESONINTROSPECT` cannot point to it anymore. :)
