### ISSUE TITLE
Can't create a library from link_whole static libraries and without any source files

### ISSUE THREAD

**Issue by SirCmpwn** [mesonbuild/meson#2180]
I have a project that is designed with several subprojects that are built into static libraries, then a larger library which is linked from all of them like so:

```meson
lib_wlr = library('wlroots', [],
    link_whole: [
        lib_wl_protos,
        lib_wlr_backend,
        lib_wlr_render,
        lib_wlr_types,
        lib_wlr_util,
        lib_wlr_xcursor,
    ],
    dependencies: _wlr_deps,
    include_directories: wlr_inc)
```

This fails: "Build target wlroots has no sources"

This commit includes our workaround: https://git.io/v7HNX

**Comment by nirbheek** [comment]
This is a good point, we need meson to realize that static libraries added with `link_whole:` are also 'sources' for a static or shared library, and perhaps also an executable.

**Comment by SirCmpwn** [comment]
It would also be nice if the sources parameter was optional so that I didn't have to specify an empty array in such cases.

**Comment by nirbheek** [comment]
That is already the case. You can have a library consisting of only `objects:` and no sources, which is why this bug is 'easy' to fix.

**Comment by SirCmpwn** [comment]
Ah, gotcha.

**Comment by jnikula** [comment]
Is it reasonable to be able to have a static library without any sources or objects?

I'm adding files to a static library based on configure tests, and if everything checks out and no compatibility code is required, the library will be empty. My current workaround is to add an empty dummy source file to the library, which feels a bit silly.

**Comment by SirCmpwn** [comment]
You can't actually invoke ar without any objects, so no, that doesn't make sense.

**Comment by jnikula** [comment]
@SirCmpwn you didn't actually try that, did you? 'ar rcs foo.a' happily creates an archive without objects.

**Comment by SirCmpwn** [comment]
You're right, I didn't try it, and it does work.

**Comment by SirCmpwn** [comment]
Thanks!
