### ISSUE TITLE
cpp_args = '' causes g++ build to fail

### ISSUE THREAD

**Issue by rhd** [mesonbuild/meson#220]
I'm not sure this is a bug or not, but it caused me a bit of pain tonight trying to figure out why g++ compile was failing bug clang++ was working. Turns out that having an empty cpp_args causes this issue.

```
executable('meson-test', 'main.cpp', cpp_args : '')
```

**Comment by jpakkane** [comment]
What you are specifying here is that you have one argument whose length is zero. If you wish to express that you don't have any flags to pass, use the empty array, like this:

    executable('meson-test', 'main.cpp', cpp_args : [])

**Comment by rhd** [comment]
It was my mistake. I still in the feeling out phase for meson and was working with clang which didn't error out with the empty string. I then switched over to gcc and saw that my test build had broken. It took me a while to figure out why. 

This is just FYI, please close the issue if you don't feel like this is a bug. 

Thanks for making this build system!

**Comment by jpakkane** [comment]
The difference here is that Meson deals with all arguments as arrays. Traditional systems use flattened strings. The latter have the problem that quoting them reliably is a nightmare (or in some cases impossible). Thus I'd say it is working as it should, so closing. Thanks.

**Comment by rhd** [comment]
Thanks for the clarification. The takeaway here for me, as a new user, is that all args should be an array of strings.
