### ISSUE TITLE
meson.py command does not work well on PowerShell

### ISSUE THREAD

**Issue by aruiz** [mesonbuild/meson#2204]
On Windows, if you call meson.py from PowerShell, meson.py spawns a cmd.exe shell window and closes it when you quit, leaving no build output on the PowerShell whatsoever

**Comment by nirbheek** [comment]
Strange, does this happen even if you run `python [full-path-to-meson.py]`? I suspect the `py` launcher might be at fault here.

**Comment by amitdo** [comment]
https://www.google.com/search?q=PowerShell+Python&oq=PowerShell+Python

https://www.quora.com/Why-wont-Python-work-in-PowerShell-for-me

https://stackoverflow.com/questions/19676403/running-python-in-powershell

**Comment by nirbheek** [comment]
Since 0.48 we've been installing a meson.exe entry point on Windows, so this has been fixed.
