### ISSUE TITLE
Allow for duplication of configuration_data()

### ISSUE THREAD

**Issue by whot** [mesonbuild/meson#2206]
I've had this in two projects now where I needed to generate files based on *almost* the same `configuration_data()`, usually for some development binaries. Right now, this means separately initializing both `configuration_data` objects: 
````
one = configuration_data()
one.set('foo', 'bar')
// repeat 10 times

two = configuration_data()
two.set('foo', 'bar')
// repeat 10 times
two.set('some-option-one-doesnt-have', '0')
````

We cannot re-use a `configuration_data` object and that makes sense, but it'd be nice to be able to duplicate it, so the above code is:
````
two = one.duplicate()
two.set('some-option-one-doesnt-have', '0')
````

Is this something of interest? Another alternative could be to initialize based on another one `configuration_data(prepopulate=one)`

**Comment by nirbheek** [comment]
This already exists starting from 0.41.2: 

```meson
cdata = configuration_data()
cdata.set(...)

cdata2 = configuration_data()
cdata2.merge_from(cdata)
cdata2.set(...)
```

However, I notice now that we forgot to document it. Will fix that.

**Comment by tp-m** [comment]
Can't you just do:
```
cdata = configuration_data()
cdata.set(...)

cdata2 = cdata
cdata2.set(...)
```
? (we use this here for example: https://cgit.freedesktop.org/gstreamer/gstreamer/tree/gst/meson.build#n158)

**Comment by nirbheek** [comment]
Yeah, that will also work since all assignments in meson are copies.

**Comment by jpakkane** [comment]
Docs updated so closing.

**Comment by whot** [comment]
Thanks guys, much appreciated
