### ISSUE TITLE
Local ITS data directories are not working in i18n module

### ISSUE THREAD

**Issue by inigomartinez** [mesonbuild/meson#2213]
[i18n module's](http://mesonbuild.com/i18n-module.html) data_dirs parameter is not working at least when using the [merge_file function](http://mesonbuild.com/i18n-module.html#i18nmerge_file). ITS files must be copied to system's ITS file location (usually /usr/share/gettext/its) to be found.

This problem can be tested with the following [bijiben's branch](https://git.gnome.org/browse/bijiben/log/?h=wip/inigomartinez/gettext) where it has been migrated from Intltool to Gettext.

**Comment by TingPing** [comment]
Your path is just wrong, try:

```diff
-its_dir = join_paths(meson.source_root(), 'gettext', 'its')
+its_dir = join_paths(meson.source_root(), 'gettext')
```

**Comment by inigomartinez** [comment]
Oh, my bad! I thought that it should point to the directory holding ITS files. Thank you very much @TingPing.

Closing this.

**Comment by TingPing** [comment]
Also as mentioned on IRC this is purely a limitation of gettext as it only supports two env vars to add paths to lookup that expect a certain layout.
