### ISSUE TITLE
Introspection of target's files is broken

### ISSUE THREAD

**Issue by evgenyz** [mesonbuild/meson#222]
The mesonintrospection's --target-files is broken in 0.25.0.

It can't find a target by a name that was given by --targets, and, if you change the name to what it really could find it bails out with an exception.

```
> meson build
The Meson build system
Version: 0.25.0
Source dir: /home/evgenyz/Devel/meson/test
Build dir: /home/evgenyz/Devel/meson/test/build
Build type: native build
Project name: test
Native c compiler: cc (gcc 5.1.1)
Build targets in project: 2

>mesonintrospect build --targets
[{"name": "t", "type": "executable", "installed": false, "filename": "t"}, {"name": "tl", "type": "shared library", "installed": false, "filename": "libtl.so.0.0.0"}]

>mesonintrospect build --target-files t
Unknown target t.

>mesonintrospect build --target-files t@exe
Traceback (most recent call last):
  File "/usr/bin/mesonintrospect", line 167, in <module>
    list_target_files(options.target_files, coredata, builddata)
  File "/usr/bin/mesonintrospect", line 81, in list_target_files
    sources = [os.path.join(subdir, i) for i in sources]
  File "/usr/bin/mesonintrospect", line 81, in <listcomp>
    sources = [os.path.join(subdir, i) for i in sources]
  File "/usr/lib64/python3.4/posixpath.py", line 79, in join
    if b.startswith(sep):
AttributeError: 'File' object has no attribute 'startswith'
```

**Comment by evgenyz** [comment]
All in all, introspection looks a little bit orphaned to me. It deserves some integration tests at least. Something like run_introspection_in_process for common tests group.

**Comment by jpakkane** [comment]
In the original design "name" was an unique identifier but since we now permit multiple different top level target this is not the case any more. I'll need to think about the proper fix for this. It probably means changing the json format to add an `id` field that is unique and possible also `subproject`.

**Comment by jpakkane** [comment]
Fixing this properly took some core changes. Can you please test the linked MR and see if it works for you? Thanks.
