### ISSUE TITLE
Remove no path component restriction in output for custom_target

### ISSUE THREAD

**Issue by mqudsi** [mesonbuild/meson#2230]
I understand the rationale of the no path components allowed in output for custom targets, but it's not a very enforceable policy, and all of `custom_target` is no-man's land anyway.

It's easy enough to "work around" but not in any standard way that lets one take advantage of meson's features:

```
logmailer = custom_target('logmailer', build_by_default: true, 
    command: ['cargo', 'build', '--manifest-path', '@INPUT@'],
    input: 'logmailer/Cargo.toml',
    depend_files: ['logmailer/src/main.rs', 'logmailer/src/logmailer.rs', 'logmailer/src/ses_mailer.rs'],
    output: ['.fake'],
  )
custom_target('logmailer_copy', depends: logmailer, build_by_default: true,
    depend_files: ['logmailer/target/debug/logmailer'],
    input: 'logmailer/target/debug/logmailer',
    command: ['cp', '@INPUT@', 'logmailer'],
    output: ['logmailer'],
  )
```

What would the harm be in allowing the use of the following instead:

```
custom_target('logmailer', build_by_default: true, 
    command: ['cargo', 'build', '--manifest-path', '@INPUT@'],
    input: 'logmailer/Cargo.toml',
    depend_files: ['logmailer/src/main.rs', 'logmailer/src/logmailer.rs', 'logmailer/src/ses_mailer.rs'],
    output: ['logmailer/target/debug/logmailer'],
  )
```

**Comment by jpakkane** [comment]
Because different backends lay out their files differently. You can even toggle between mirror and "flat" layouts in the Ninja build. The latter is especially useful on Windows which does not have rpath (you can fake it with manifests but we don't have that yet). That decision is made by the backend system, and the build targets must conform to that.

**Comment by mqudsi** [comment]
Yes, but this would be for a custom target, which by definition means it will have custom behavior. Wouldn't my "workaround" be applicable on any system so long as `cargo` is the custom target being invoked?

**Comment by jpakkane** [comment]
> Yes, but this would be for a custom target, which by definition means it will have custom behavior.

"Custom" does not mean "exempt from rules".

**Comment by mqudsi** [comment]
Perhaps it should, at least for rules that don't make sense for non-meson builds.

Custom means "build something that can't be built by meson via a non-custom target rule". Something like Cargo cannot be told to output its files in the source directory (as with most other tools, meson itself included).

Meson's restrictions on output file paths makes sense for meson outputs. But outputs from other build systems may not have the luxury of following this overly-onerous rule.
