### ISSUE TITLE
Enabling code coverage on 0.42.0 with lcov installed causes a ninja error

### ISSUE THREAD

**Issue by musicinmybrain** [mesonbuild/meson#2238]
Seems like coverage analysis (`b_coverage`) is broken on 0.42.0. When `lcov`/`genhtml` are installed (whether `gcovr` is installed or not), enabling this option always results in an error:
```
Meson encountered an error:
Multiple producers for Ninja target "coverage-html". Please rename your targets.
```
Confirmed on both MacOS with Homebrew and Fedora (using 0.42.0 RPM from Rawhide); 0.41.2 on Fedora works fine.

Detailed steps to reproduce:

1. Create `meson.build`:
```
project('mwe', 'c')
executable('mwe', 'mwe.c')
```
2. Create `mwe.c`:
```
int main(int argc, char * argv[]) {
  return 0; 
}
```

3. Confirm `lcov` and `genhtml` are installed. (Run each command with `--version`.)

4. Execute `meson _build -Db_coverage=true`, which fails with the error reported above.

**Comment by QuLogic** [comment]
I think this is fixed by #2214.

**Comment by musicinmybrain** [comment]
You're right! I built meson from git master f3812849 (which includes #2214) and it works fine.

**Comment by nirbheek** [comment]
The fix for this will go into a stable release soon.
