### ISSUE TITLE
pip support in meson

### ISSUE THREAD

**Issue by AbdealiJK** [mesonbuild/meson#224]
A major issue I have with autotools is that I cannot deploy anything built with it to pip (for python packages)

It would be good if meson would be able to automatically make a pip compatible package (maybe even deploy to pip? if the auth key for a pip account is given)

**Comment by jpakkane** [comment]
I have no experience with pip generation but assuming it does not require invasive changes, it is totally possible.

**Comment by AbdealiJK** [comment]
Not sure what you mean by invasive changes.

What it would need is a setup.py file which uses distutils or setuptools. And the data given to meson about how to install, what to install, where to keep data files, etc. would need to be converted into something distutils can understand (in the setup.py)

**Comment by jpakkane** [comment]
Could you give a sample project that is doing this and how it should work.

**Comment by AbdealiJK** [comment]
One project which I've contributed to a bit is : https://github.com/coala-analyzer/coala (I know the code for setuptools they use)

Other than that some popular modules which use pip:
ipython - https://github.com/ipython/ipython
django - https://github.com/django/django
ansible - https://github.com/ansible/ansible
scrapy - https://github.com/scrapy/scrapy

**Comment by jpakkane** [comment]
So is your idea roughly to have a Meson project and then be able to tell "ok, now generate a setup.py and related things automatically".

**Comment by AbdealiJK** [comment]
Yes

-----Original Message-----

**Comment by jpakkane** [comment]
The problem here is that writing a setuptools backend for Meson is a lot of work. About as much as any other backend. The better solution would be to add Meson support for pip. That would require changing pip instead.

**Comment by ignatenkobrain** [comment]
I think we should implement #226 rather than this.

**Comment by nirbheek** [comment]
This is not going to happen, most likely, unless someone steps up to do it. Closing. Please reopen if you wish to work on it. :)

**Comment by TingPing** [comment]
Just on a random note I looked into having a setup.py that build Meson projects before and decided it wasn't worth the hassle. It would basically be re-implementing setuptools (which just extends distutils itself) to call out to Meson. Even if this is all done it still doesn't really map to the Python ecosystem imo.

**Comment by nirbheek** [comment]
Yes, I don't think having Yet Another Setuptools clone is going to help anyone in the world.

**Comment by jpakkane** [comment]
Setuptools or distutil has grown support for building with an external build system. There is a brigde for e.g. Scons. The proper fix would probably be to code one of those.
