### ISSUE TITLE
0.42.0 breaks install_man() - gives "does not exist" on file created by custom target

### ISSUE THREAD

**Issue by siriobalmelli** [mesonbuild/meson#2244]
The below code works in 0.41.2 and breaks in 0.42.0 with a **File /path/fnvsum.1 does not exist**

```meson
man_pages = [ 'fnvsum.1' ]

md2man = find_program('md2man-roff')

foreach m : man_pages
	one_man = custom_target(' '.join(['man', m]),
			input : '.'.join([m.split('.')[0], 'md']),
			output : m,
			capture : true,
			build_by_default : true,
			command : [ md2man.path(), '@INPUT@' ])
	install_man(one_man.full_path())
endforeach
```

For full context, the repo in question is [here](https://github.com/siriobalmelli/nonlibc/tree/master/man).

To reproduce:

```bash
pip3 install meson==0.42.0 --force-reinstall
```

To fix:

```bash
pip3 install meson==0.41.2 --force-reinstall
```

Any pointers are appreciated, thank you!

**Comment by QuLogic** [comment]
You shouldn't use `full_path`. It's too bad that `install_man` doesn't accept built files (I assume from you not passing plain `one_man`), but you can replicate the behaviour by using `install:true` and `install_dir:join_paths(get_option('mandir'), 'man1')`.

You also don't need to expand the path to `md2man`.

**Comment by siriobalmelli** [comment]
Thank you, sir.

That worked; it looks as follows (in case someone else runs into this later):

```meson
man_pages = [ 'fnvsum.1' ]

md2man = find_program('md2man-roff')

foreach m : man_pages
	one_man = custom_target(
			' '.join(['man', m]), # e.g.: 'man fnvsum'
			input : '.'.join([m.split('.')[0], 'md']), # e.g.: 'fnvsum.md'
			output : m, # e.g.: 'fnvsum.1'
			capture : true,
			build_by_default : true,
			command : [ md2man, '@INPUT@' ],
			install : true,
			install_dir : join_paths(get_option('mandir'), ''.join(['man', m.split('.')[1]])) # e.g.: 'man1'
			)
endforeach
```
