### ISSUE TITLE
SDL_image to be found by dependency method

### ISSUE THREAD

**Issue by marcosps** [mesonbuild/meson#2245]
Hello, is there a way to add SDL_image as a dependency in the same way of sdl?

Thanks!

**Comment by ignatenkobrain** [comment]
Well, SDL2_image ships pkg-config file, so it should just work. And SDL_image ships pkg-config file as well. So I don't see any problem why it doesn't work for you.

**Comment by marcosps** [comment]
@ignatenkobrain well, it didn't worked. You can check it here:

https://github.com/marcosps/v4l2_webcam/blob/master/meson.build#L6

As a result, I added -lSDL_image in link_args, as meson didn't found sdl-image dep. I tried "sdl-image", "sdl_image", but without success.

Am I missing something?

**Comment by jpakkane** [comment]
You need to specify the Pkg-config name, which apparently is `SDL_image`. If not, try grepping the output of `pkg-config --list-all`.

**Comment by marcosps** [comment]
@jpakkane thanks, I'll try once I have access to my machine again!

**Comment by marcosps** [comment]
@jpakkane @ignatenkobrain sorry for the noise, it worked here using SDL_image, the same name of pkg-config.

Thanks!

**Comment by nirbheek** [comment]
We should probably also support this in the `SdlDependency()` class as a module.
