### ISSUE TITLE
Generate compiler definition from configuration data

### ISSUE THREAD

**Issue by whs** [mesonbuild/meson#2247]
Instead of writing to a header file, we should be able to supply it to the compile which will set `-DKEY=value` instead.

This is currently doable by using `add_project_arguments`, but using configuration data should make it more simpler.

**Comment by jpakkane** [comment]
In general you should minimize the number of compiler arguments whenever possible. A configuration file is a very good way to do this and it is more readable than a ton of compiler arguments. Adding functionality that adds more compiler arguments is very unlikely to be accepted.

You don't even need an input file to generate a header, so having one is straightforward.

**Comment by whs** [comment]
Thanks for the response
