### ISSUE TITLE
Support python project

### ISSUE THREAD

**Issue by vrutkovs** [mesonbuild/meson#226]
That's rather weird that python app doesn't support building other python apps :)

**Comment by ignatenkobrain** [comment]
We should add `python` language. It should find python interpreter and python libs directory. then if user will specify something like
```
executable('foo', sources : ['bar.py', 'baz.py'], install : true)
```
we will just name target as `foo`, do byte-compiling and install python files to python site-packages directory.

**Comment by jpakkane** [comment]
This is closely related to #224. Some level of Python support should be added, yes. However pure Python projects should probably just use setuptools/distutil as it works quite nicely. The main advantage of Meson would be when your Python app has a compiled C/C++ extension.

Is byte compilation distro specific? AFAICR at least on Debian you should not byte compile your own packages but rather have the debhelper scripts/something like those do it at package generation time.

**Comment by vrutkovs** [comment]
My initial goal porting a GNOME Python projects to Meson, so we heavily use GNOME's features such as resources, schemas, translations etc, so traditional python way wouldn't cut it

**Comment by jpakkane** [comment]
Can you post a link to a sample project and explain roughly what you would expect to have to get it working?

**Comment by vrutkovs** [comment]
Its [GNOME Music](https://git.gnome.org/browse/gnome-music).

Build procedure is fairly simple:
 * Replace some vars (package version, wiki link) in ```.in``` files
 * Compile GNOME resources
 * Build translations
 * Put all of these in standart python location

I'm working on porting this meanwhile

**Comment by vrutkovs** [comment]
Here's a simplest possible version: https://github.com/vrutkovs/gnome-music/tree/wip/meson

Fetching a python install dir is done in https://github.com/vrutkovs/gnome-music/blob/wip/meson/meson.build#L21

**Comment by gour** [comment]
Interesting for Meson and considering to use it instead of CMake for python3+pyqt5+cython+rst/Sphinx project, so would like to see more python support here.

**Comment by jpakkane** [comment]
Now supported.

**Comment by tmandry** [comment]
In case anyone's looking for the PR where support was added, it looks like it's #383.

Examples for how to actually do this are in [`test cases/python3`](https://github.com/mesonbuild/meson/tree/master/test%20cases/python3).
