### ISSUE TITLE
testing: timeout behavior

### ISSUE THREAD

**Issue by liamstask** [mesonbuild/meson#2281]
when testing via `meson test mytestcase` on meson 0.42.0, I am seeing 2 issues:
* stdout does not appear to be included in `build/meson-logs/testlog.txt` if the test times out. If it passes or fails, it is included as expected, and stderr is included in all cases.
* I haven't found a convenient way to kill the test executable when running the meson test harness. ctrl-C kills the `meson test` parent process, but does not appear to kill the test executable.

**Comment by nirbheek** [comment]
> I haven't found a convenient way to kill the test executable when running the meson test harness. ctrl-C kills the meson test parent process, but does not appear to kill the test executable.

This is a bug, we should forward SIGINT to child processes in `mesontest.py`

**Comment by rhd** [comment]
This was fixed a long time ago in #377 - I hope a new fix can make it into the next release. I have tests that sometimes get stuck and I need this to be working. I wonder when it broke?

**Comment by nirbheek** [comment]
We should add a unit test when we fix it again.

**Comment by rhd** [comment]
Is this still a problem with 0.44+? I was trying to reproduce meson not killing children but I **think** it's working. 

This code looks a bit fishy though...

```python
            if not self.options.verbose:
                stdout = subprocess.PIPE
                stderr = subprocess.PIPE if self.options and self.options.split else subprocess.STDOUT

                if not is_windows():
                    setsid = os.setsid

            p = subprocess.Popen(cmd,
                                 stdout=stdout,
                                 stderr=stderr,
                                 env=child_env,
                                 cwd=test.workdir,
                                 preexec_fn=setsid)
```

This is only setting the `setsid` variable if it's not in verbose mode.

**Comment by rhd** [comment]
scratch that - confirmed, it's still an issue.
