### ISSUE TITLE
How to configure meson to find gtest?

### ISSUE THREAD

**Issue by NickeZ** [mesonbuild/meson#2285]
I think best practice is to ship the whole gtest with your sources so that you always compile with the same version. Is this possible to do with meson?

I tried putting it in `subprojects/gtest` and add `dependency('gtest')`, but it doesn't work.

**Comment by jpakkane** [comment]
If you use the version from wrapdb, it already does this. You do need to do the necessary fallback magic, though. See the docs for details.

**Comment by NickeZ** [comment]
Awesome, didn't realize that that existed!
