### ISSUE TITLE
qt5.preprocess: enable rcc 'name' command line option for use with Q_INIT_RESOURCE

### ISSUE THREAD

**Issue by chkurz** [mesonbuild/meson#2297]
Using resources from a static library requires initialization by [Q_INIT_RESOURCE(X)](http://doc.qt.io/qt-5/qdir.html#Q_INIT_RESOURCE) for a resource file `X.qrc` compiled into the static library.

Currently, executable linking fails with an undefined reference to `qInitResources_X`, because the appropriate function is not generated by [rcc](http://doc.qt.io/qt-5/rcc.html).
Manually modifying the rcc command in build.ninja to include `-name X` solves this problem for me.

CMake appears to do this automatically, but for meson I could not find any provisions to do this in [qt5.py](https://github.com/mesonbuild/meson/blob/master/mesonbuild/modules/qt5.py).

**Comment by jeandet** [comment]
Hello as a workaround you can do this:
```
rcc = find_program('rcc-qt5','rcc')
rcc_gen = generator(rcc,
                output  : 'qrc_@BASENAME@.cpp',
                arguments : ['--name=@BASENAME@"',
                 '--output',
                 '@OUTPUT@',
                 '@INPUT@'])

rcc_files = rcc_gen.process(your_resources)
```
But yes the qt5 module needs more love, moc also sometimes needs include path...

**Comment by nirbheek** [comment]
The best people to fix such issues are those that use it and hence know it best. Luckily Python makes it easy to contribute to Meson. I'd be happy to review your PR. :)

**Comment by chkurz** [comment]
@jeandet Thanks for the workaround! I couldn't get it to work out of the box, unfortunately.
For some reason `-name=@BASENAME@` in the arguments is not getting substituted, while it works for `qrc_@BASENAME@.cpp`.

I've ended up using the `@EXTRA_ARGS@`, because in that case substitution works:
```
rcc_gen = generator(rcc,
                output  : 'qrc_@BASENAME@.cpp',
                arguments : [
                 '--output',
                 '@OUTPUT@',
                 '@INPUT@',
                 '@EXTRA_ARGS@'])

rcc_files = rcc_gen.process('/path/to/file.qrc', extra_args : ['-name', 'file'])
```

@nirbheek My understanding of Python, meson, and Qt5/rcc compilation is limited at the moment. If this is still an issue when it has improved, I might give it a try. ;)
