### ISSUE TITLE
meson configure for subprojects?

### ISSUE THREAD

**Issue by jasonszang** [mesonbuild/meson#2305]
I just encountered the problem in #2289, which made me wonder if there could be a `meson configure` for subprojects so that if some options went wrong with a subproject I could manually fix it up. Sorry if there is already one. I'm new to Meson.

**Comment by nirbheek** [comment]
This cannot be done without reconfiguring the entire project because subprojects are never standalone. It could be done in theory, but it would greatly complicate the parser code. We should try to fix #2289 instead.
