### ISSUE TITLE
subproject('../../foo') escapes the current source directory and writes directories outside of the builddir

### ISSUE THREAD

**Issue by jasonszang** [mesonbuild/meson#2306]
I tried to use subproject() to depend on two projects outside of project folder with `subproject('../../foo')`. Everything went well with `--layout flat`, besides that meson still creates `subproject` directory tree with only empty directories in the build dir. Since I used `subproject('../../foo')` this result in empty directories being created outside of build dir. Are these empty subproject directories necessory? Or perhaps may be removed under `--layout flat`?

**Comment by nirbheek** [comment]
Uh, we should never allow people to escape the subprojects directory by using a leading `'..'`. That is definitely a bug. Please use symlinks inside `subprojects/` if you really want to use directories outside your source tree.

**Comment by jasonszang** [comment]
Thank you for reminding me to use symlinks! That solved my problem.

**Comment by narendravardi** [comment]
@nirbheek can i work on this?

**Comment by nirbheek** [comment]
@narendravardi sure! You should be able to work on any issue with an `easy` tag. If it turns out to not be an easy issue, do tell me so I can remove that tag since it's only an estimate. :)

In this case what you want to do is to run `os.path.normpath` on the argument to `subproject()` and error out if the resulting path starts with `../`.

**Comment by narendravardi** [comment]
@nirbheek, making changes to func_subproject() function in interpreter.py file.
Raising InvalidArguments with "Subproject name should not start with ../"
Please let me know if this is correct.

**Comment by jpakkane** [comment]
A better check would be to prohibit both `/` and `\` in the subproject name.
