### ISSUE TITLE
meson fails to find binaries with CFLAGS='-fcheck-pointer-bounds'

### ISSUE THREAD

**Issue by pksadiq** [mesonbuild/meson#2316]
meson-version: 0.43.0.dev1 (I wish there is a short corresponding commit hash as its compiled from git)

When trying to configure some project with  `CFLAGS='-fcheck-pointer-bounds'`, it fails to find some functions. It works fine If I avoid`-fcheck-pointer-bounds`,

What I did:
* cloned gnome-calendar from https://git.gnome.org/browse/gnome-calendar
* from the root directry, I ran `CFLAGS='-fcheck-pointer-bounds' ./configure`

Result:

```
adiq@rose:~/jhbuild/checkout/gnome-calendar$ CFLAGS='-fcheck-pointer-bounds' ./configure
The Meson build system
Version: 0.43.0.dev1
Source dir: /media/sadiq/Main/Software/src/gnome/gnome-calendar
Build dir: /media/sadiq/Main/Software/src/gnome/gnome-calendar/_build
Build type: native build
Project name: gnome-calendar
Native C compiler: ccache cc (gcc 6.3.0)
Appending CFLAGS from environment: '-fcheck-pointer-bounds'
Appending LDFLAGS from environment: '-L/home/sadiq/jhbuild/install/lib '
Build machine cpu family: x86_64
Build machine cpu: x86_64
Has header "dlfcn.h": YES
Has header "inttypes.h": YES
Has header "langinfo.h": YES
Has header "locale.h": YES
Has header "memory.h": YES
Has header "stdint.h": YES
Has header "stdlib.h": YES
Has header "strings.h": YES
Has header "string.h": YES
Has header "sys/stat.h": YES
Has header "sys/types.h": YES
Has header "unistd.h": YES
Checking for function "dcgettext": NO
Checking for function "gettext": NO
Checking for function "floor": NO
Checking for function "iconv": NO
Checking for function "memset": NO
Checking for function "nl_langinfo": NO
Checking for function "pow": NO
Checking for function "setlocale": NO
Checking for function "strstr": NO
Checking for function "strerror": NO

Meson encountered an error in file meson.build, line 112, column 0:
Assert failed: "strerror" not found
```

**Comment by pksadiq** [comment]
Sorry, that was a problem on my side

**Comment by pksadiq** [comment]
The issue was that gcc requires `-mmpx` along with `'-fcheck-pointer-bounds'`. I tried the same with gnome-control-center, and the issue was listed in `config.log`.

I wish meson would too log the errors to some file. Please re-open if this case is relevant.

Thanks

**Comment by nirbheek** [comment]
Meson logs to `builddir/meson-logs/meson-log.txt`. We should probably print that on failed configures.

**Comment by pksadiq** [comment]
Yeah. I see it there. `configure' script from GNU autotools suggests to see the `config.log' file on failure, but not meson.
