### ISSUE TITLE
gtk-doc issues

### ISSUE THREAD

**Issue by ignatenkobrain** [mesonbuild/meson#232]
```
build hello-world-doc: CUSTOM_COMMAND 
 COMMAND = '/usr/bin/python3' '/home/brain/git/mesonbuild/meson/commandrunner.py' '/home/brain/tmp' '/home/brain/tmp/build' 'doc' '/home/brain/git/mesonbuild/meson/gtkdochelpe
r.py' '/home/brain/tmp' '/home/brain/tmp/build' 'doc' 'src' 'hello-world.xml' 'hello-world'
 description = 'Running$ external$ command$ hello-world-doc.'
 pool = console
```

* I think we should add `hello-world.xml` to line where CUSTOM_COMMAND is (to do rebuild if file changed).

It creates nothing at all in doc directory

**Comment by jpakkane** [comment]
Gtk-doc targets are run_targets. They are not run automatically on regular builds. To build them run 'ninja hello-world-doc'. They are automatically rebuilt on 'ninja install'.

Because run targets are only executed on request, they don't need dependencies.

**Comment by ignatenkobrain** [comment]
I think it should run automatically

**Comment by jpakkane** [comment]
During development over 90% of all compiles are for development and debugging where people don't care about docs. Running doc build automatically would slow that down unnecessarily.
