### ISSUE TITLE
yelp tests do not skip gracefully if itstool not found

### ISSUE THREAD

**Issue by dcbaker** [mesonbuild/meson#2325]
There's a nice traceback if the tool ins't found, it would be nice if the tests would skip if they can't find the tool they want.

**Comment by jon-turney** [comment]
I believe this is fixed by #3060 and can be closed.

**Comment by rastersoft** [comment]
> I believe this is fixed by #3060 and can be closed.

I think it isn't, because I stumbled with this bug a week ago, when building Evince. In fact, I sent a patch, but they recommended to try to fix it here.

The merge request: https://gitlab.gnome.org/GNOME/evince/merge_requests/180/

**Comment by jon-turney** [comment]
I'd suggest raising a new issue: "`gnome.yelp()` doesn't check for `itstool`" or similar,  (since this one is really about meson's framework tests)

**Comment by jon-turney** [comment]
(and you might want to audit the gnome module for a similar problem with other tools it requires)

**Comment by dhewg** [comment]
It happens outside of tests too, see https://github.com/mesonbuild/meson/issues/821#issuecomment-549239357
