### ISSUE TITLE
@CURRENT_SOURCE_DIR@ expands to ../ instead of ..

### ISSUE THREAD

**Issue by liamstask** [mesonbuild/meson#2336]
Using meson 0.42.0.

My goals were similar to those in https://github.com/mesonbuild/meson/issues/1622 but my sources are setup as follows:

```
├── meson.build
├── proto
│   ├── myproto.capnp
├── src
└── test
    ├── meson.build
    ├── proto
    │   └── testproto.capnp
    ├── tests-main.cpp
```

and as such, I'd like to create a single `generator` in the top level meson.build:

```
capnproto_gen = generator(capnp,
    output    : ['@PLAINNAME@.c++', '@PLAINNAME@.h'],
    arguments : ['compile', '--src-prefix=@CURRENT_SOURCE_DIR@/proto', '-oc++:@BUILD_DIR@', '@INPUT@']
)
```

However, in the top level build file `@CURRENT_SOURCE_DIR@` expands to `../` (as verified w `ninja -v`) instead of `..`, which creates paths like `--src-prefix=..//proto` which the generator does not accept.

It actually ends up working in the subdir, as it expands to `../test` which happens to work OK.

I tried `arguments : ['compile', '--src-prefix=@0@/proto'.format(meson.current_source_dir()), '-oc++:@BUILD_DIR@', '@INPUT@']` but that doesn't work since the call to `format()` only happens when the top level build file is processed, not at expansion time.

**Comment by QuLogic** [comment]
Why can't you remove the slash you added in the string?

**Comment by liamstask** [comment]
because in the subdir that would resolve to `--src-prefix=../testproto` instead of the correct `--src-prefix=../test/proto`.

**Comment by liamstask** [comment]
it's also inconsistent w `@SOURCE_DIR@` which expands to `..` (but of course doesn't work for the subdir).

**Comment by liamstask** [comment]
the following diff resolves the issue, but i'm not sure if this is an acceptable approach:

```diff
diff --git a/mesonbuild/backend/backends.py b/mesonbuild/backend/backends.py
index 97959b60..366e5b0c 100644
--- a/mesonbuild/backend/backends.py
+++ b/mesonbuild/backend/backends.py
@@ -157,7 +157,7 @@ class Backend:
 
     def get_target_source_dir(self, target):
         dirname = os.path.join(self.build_to_src, self.get_target_dir(target))
-        return dirname
+        return os.path.relpath(dirname)
 
     def get_target_private_dir(self, target):
         dirname = os.path.join(self.get_target_dir(target), target.get_basename() + target.type_suffix())
```
