### ISSUE TITLE
Get static library from a dependency fallback.

### ISSUE THREAD

**Issue by trhd** [mesonbuild/meson#2342]
It should be possible to get a static library from a dependency fallback even if `default_library` has been defined as `shared`.

Dependency has the `static` argument but it doesn't seem to have an effect on the fallback dependency.

`default_library` can not be defined for the fallback in `default_options` as it is a base option and those are allowed to be modified only from the main project.

**Comment by eli-schwartz** [comment]
#4157 added per-subproject default_library.

Since #9061 if default_library is not set on the subproject already, and a dependency fallback is used with `static: true`, `default_options: ['default_library=static']` is automatically set.
