### ISSUE TITLE
custom_targets that return code and header

### ISSUE THREAD

**Issue by dcbaker** [mesonbuild/meson#2346]
In my case I have a generator that create a C source file and header as a single rule, I then have multiple targets that need said header, but should not be compiled with the C file (it will cause symbol collisions because we're doing ugly stuff with the preprocessor).

Have the generator return both the .c and .h file from a single rule is nice and I'd prefer to keep it that way (the logic of calculating what goes in the files is far more expensive than actually writing them, and ensuring that they match is very nice)

I can think of a couple of ways to solve this. One would be to add a `depends` keyword to `executable` and the various `library` functions. This would provide a nice symmetry with `custom_target`, which already has this field. I like this approach since it's not adding new features to meson, just extending them to new types. I'd be happy to implement that functionality, but don't want to waste time if there's a preferred approach.

**Comment by nirbheek** [comment]
This is the same as https://github.com/mesonbuild/meson/issues/1470, isn't it? One (IMO good) solution is to add subscripting to `custom_target`s as I explain in that issue. Would you be willing to work on that?

**Comment by dcbaker** [comment]
Sure, that sounds like an even better solution. I'll have a look at it.
