### ISSUE TITLE
pkg-config binary cached when doing cross build

### ISSUE THREAD

**Issue by lfxgroove** [mesonbuild/meson#2353]
I have a project where i need cross-compiling. One binary needs to be built on the build machine, this binary is then used to generate sources for the compilation to the target/host machine.

The problem stems from needing different environments for pkg-config to be used when looking up the dependencies. To solve this I created a small wrapper script calling pkg-config with `PKG_CONFIG_PATH` and `PKG_CONFIG_SYSROOT_DIR` set to the correct values, I then point to this wrapper in `cross_file.txt`. I expected the binaries from the cross_file to be used for targets which are going to be compiled to the target/host machine and the usual binaries found on the build machine to be used when compiling something with `native: true`. This seems to be the case for gcc/g++ etc. but not for pkg-config. Is there any reason the same pkg-config is used for both native and non-native targets when looking up dependencies? Otherwise I would suggest that different pkg-configs are allowed to be used. 

Are there any pros/cons to allowing/disallowing this? I could probably create a patch to implement this behaviour if there is no objection to it. Thanks for your time!

**Comment by QuLogic** [comment]
I'm pretty sure this should work; how did you set the binary in the cross file? Do you have a log of it not working?

**Comment by lfxgroove** [comment]
Hi again, I just retried the whole process for the x'th time and now it seems to magically work, I don't even know what changed :/ But as it seems to work I'm gonna go ahead and close this. Thanks for the quick reply!
