### ISSUE TITLE
Compiling C file with C++ compiler

### ISSUE THREAD

**Issue by matze** [mesonbuild/meson#2381]
Is it possible to compile C source files with a C++ compiler (don't ask …)? At the moment, when I set the project language to `cpp` and try to compile files with `.c` extensions I get

    RuntimeError: No specified compiler can handle file foobar.c

**Comment by TingPing** [comment]
I believe you can pass `-x c++` to `gcc` in your cflags.

**Comment by TingPing** [comment]
You can pass `-x c++` to `gcc`.

**Comment by matze** [comment]
Yes that should work, however meson escapes `-x c++` to `'-x c++'` which gcc complains about

    gcc: error: language  c++ not recognized

**Comment by NickeZ** [comment]
Give it as to arguments or remove the space.

**Comment by matze** [comment]
Thanks @NickeZ, that did the trick!
