### ISSUE TITLE
Qt5 module - method to get the moc executable

### ISSUE THREAD

**Issue by adrianjohnson** [mesonbuild/meson#2403]
I am running moc on cpp files using a generator() because I need to specify the output name as the code contains #includes for the output.

I currently use find_program('moc') to specify the executable for generator(). But this is unreliable. For example on my system there is a 'moc' for qt5 and 'moc-qt4' for qt4. I would like a method that returns the moc executable that the Qt5 module is using that I can pass it to generator().

**Comment by jeandet** [comment]
We shouldn't ease such workaround, but instead fix qt module if something is wrong.
For your usecase I would say that we use the same naming convention that CMake and qmake, normally you should be able to use preprocess method as [here](https://github.com/jeandet/SciQLOPCore/blob/master/tests/meson.build#L128) and [here](https://github.com/jeandet/SciQLOPCore/blob/master/tests/Variable/TestVariableController2.cpp#L145).

I close this, feel free to open it again if I missed something.
