### ISSUE TITLE
adding warning() function

### ISSUE THREAD

**Issue by adrianjohnson** [mesonbuild/meson#2405]
I would like a warning function that like message() prints a mesage but prefixed with 'WARNING' in the warning color instead of 'Message'.

**Comment by adrianjohnson** [comment]
Here is a patch that works for me. #2370 would also need to be fixed.
[warning.txt](https://github.com/mesonbuild/meson/files/1355070/warning.txt)

**Comment by nirbheek** [comment]
Don't attach patches to issues; it is impossible to do anything with a patch attached like this on GitHub. If you want a patch to be reviewed and pushed, please open a pull request.

**Comment by dcbaker** [comment]
This was fixed in #2429
