### ISSUE TITLE
Add fail message to dependency() to print if not found.

### ISSUE THREAD

**Issue by adrianjohnson** [mesonbuild/meson#2407]
If the dependency is not found I would like to print a message explaining where to obtain the library.

something like:
```
zlib_dep = dependency('zlib',
                      not_found_msg : '(http://www.gzip.org/zlib)')
```
Would output

Dependency zlib found: NO (http://www.gzip.org/zlib)

Also useful for libraries like freetype where the pkg-config version numbering is different to the release version. I would like to be able to print the release version required if the version check fails.

**Comment by zeehio** [comment]
Do you mean something like?

    zlib_dep = dependency('zlib')
    if not zlib_dep.found()
      message ('zlib not found. Check http://www.gzip.org/zlib')
    endif

**Comment by adrianjohnson** [comment]
Doesn't work if required : true.

**Comment by ppaalanen** [comment]
I think I will be writing a lot of code like this:
```
dep_foo = dependency('foo', required: false)
if not dep_foo.found()
        error('\'foo\' was not found. Frobber tool depends on it, but if you do not want to build it, you can disable Frobber with -Dfrobber=false')
endif
```

It would be more convenient if I could write just
```
dep_foo = dependency('foo', required: true, message: 'Frobber depends on this, but if you do not want to build Frobber, use -Dfrobber=false')
```

**Comment by jpakkane** [comment]
Can you test if the linked MR fixes this for you?

**Comment by nielsdg** [comment]
@ppaalanen: I tested this locally with some minor changes weston's meson.build, and it seems to work. This is an example of what it looks like:

```
Dependency egl found: YES (cached)
Dependency wayland-egl found: YES (cached)
Dependency glesv2 found: YES (cached)
Dependency wayland-cursor found: YES (cached)
Dependency wayland-cursor found: YES (cached)
Dependency cairo found: YES (cached)
Dependency pangocairo found: YES (cached)
Dependency libdrm_etnaviv found: NO (tried pkgconfig and cmake)
Message: Can't build clients without libdrm_etnaviv

clients/meson.build:285:2: ERROR:  Dependency "libdrm_etnaviv" not found, tried pkgconfig and cmake
```

Personally, I think it would be clearer if the message was part of the error message itself though.

**Comment by ascent12** [comment]
Would the 'not found message' be printed if the dependency was used with a disabled feature option?
I think it would be better to not potentially confuse the user by saying we didn't find something when we didn't even look.
