### ISSUE TITLE
qt5.preprocess() does not accept nested lists

### ISSUE THREAD

**Issue by adrianjohnson** [mesonbuild/meson#2408]
```
public_headers = [ 'a.h', 'b.h' ]
private_headers = [ 'c.h', 'd.h' ]
moc_files = qt5.preprocess(moc_headers : [public_headers, private_headers])
```
fails

it should be consistent with other functions that accept lists of sources like executable().

**Comment by nirbheek** [comment]
The problem is that it uses `extract_as_list` which doesn't flatten lists. See: `mesonbuild/modules/qt5.py`. Would you like to work on a patch for this?
