### ISSUE TITLE
missing runtime vcruntime140.dll 

### ISSUE THREAD

**Issue by simevo** [mesonbuild/meson#2417]
Hi thanks for your great project ! I installed **meson-0.42.1-32.msi** on a mostly clean 32-bit Windows 7, then on launching `meson --version` in a cmd, I get the "missing runtime vcruntime140.dll " pop-up.

To fix it, I installed the [Microsoft Visual C++ 2015 Redistributable](https://www.microsoft.com/en-US/download/details.aspx?id=53587), this should probably be documented.

**Comment by nirbheek** [comment]
We should distribute that with the MSI, ideally. We can start doing that with the next release.

**Comment by simevo** [comment]
http://wixtoolset.org/documentation/manual/v3/howtos/redistributables_and_install_checks/install_vcredist.html

**Comment by jpakkane** [comment]
Opened #2420. I don't know if it actually works. If someone does know, try it and tell us how it turned out.
