### ISSUE TITLE
How to set warnings as errors?

### ISSUE THREAD

**Issue by Kulak** [mesonbuild/meson#2427]
I have a CPP build and I would like to treat warnings as errors.  How do I do that?

**Comment by jpakkane** [comment]
By turning on the `werror` option, either with a command line option `--werror` when first running Meson or with `meson configure` later.

**Comment by Kulak** [comment]
examples:

    meson build --werror

or

    cd build
    meson configure -Dwerror=true
    meson configure -Dwerror=false
    meson configure
