### ISSUE TITLE
please consider adding the install_mode keyword to configure_file

### ISSUE THREAD

**Issue by williamh** [mesonbuild/meson#2433]
I see in your howto documents that if I want a file that is generated by configure_file() to be executable, the input/template file must be executable. I disagree with this and would like to ask you to restore the install_mode keyword to the configure_file function for the following reasons.

1. Turning on the execute bit on a template implies that it can be executed directly, which is not correct, so I don't want the execute bit on. Honestly I would rather not have anything in my source repositories that has the execute bit turned on.

2. Removing the install_mode keyword from configure_file() creates a regression if someone was using it to set the owner and group on the output files. I am not doing this, but can see that it could be useful.

Thanks much for your time.

**Comment by williamh** [comment]
I want to clarify something. I'm not asking you to ditch your current behavior, but make it optional.
If I don't supply install_mode, use the current behavior, but if I do, can it be respected instead of forcing me to mark the templates executable in my source repository?

**Comment by QuLogic** [comment]
Are you sure this ever worked? What version are you using where `install_mode` does something? I can't find anything in the diff log about it, but maybe I've missed something.

**Comment by williamh** [comment]
@QuLogic Somewhere between 0.39.1 and the current release it was removed and now it directs us to remove the install_mode keyword from config_file calls. I didn't notice it sooner because I've been working on other things and converting my project in the background.

**Comment by williamh** [comment]
@QuLogic I just did some testing and this worked all the way up to 0.42.0. That is the version where meson starts complaining about the install_mode keyword being passed to configure_file().

**Comment by QuLogic** [comment]
`0.4something` added warnings about unused keyword arguments. Looking at 0.39.1, I don't see [`configure_file` doing anything with `install_mode`](https://github.com/mesonbuild/meson/blob/8ce7412b354d1dc09665bde7dfa498e6e9b54773/mesonbuild/interpreter.py#L2226); I think it's just been ignoring your argument all this time.

**Comment by williamh** [comment]
I will check and attach files if necessary. give me a few.

**Comment by williamh** [comment]
@QuLogic Well, I don't know why I thought it was working, but I've tested backward for 10 versions and can't seem to find it. So, I'm really sorry about making this sound like a regression.

If you are willing to consider it, this would be a nice addition. You could keep the current behavior if install_mode isn't specified, and allow overriding the current behavior if it is.

Is this something you would consider rather than making this an error?

**Comment by williamh** [comment]
Here is a small example illustrating what I would like to be able to do.

script.in in this case should definitely not be executable, but at the end, ${DESTDIR}/usr/bin/script should be. Is it possible to do this?



[proj.tar.gz](https://github.com/mesonbuild/meson/files/1361330/proj.tar.gz)

**Comment by jpakkane** [comment]
I personally like the fact that we just copy the properties of the template file. Because that is exactly what it is, a template. The status bits are just one facet of the template to be copied. Every now and then people ask about this and when told that template file attributes are copied they seem to find it straightforward and natural.

**Comment by floppym** [comment]
Possible workaround:
```
project('foo')
conf = configuration_data()
conf.set('FOO', 'bar')
script = configure_file(input: 'script.in', output: 'script', configuration: conf)
install_data(script, install_dir: 'bin', install_mode: 'rwxr-xr-x')
```

**Comment by williamh** [comment]
@jpakkane Sure, and I'm not asking for a breaking change.
If @floppym's workaround is the way this should be done, I'm fine with that, and I also suggest
documenting this as the way to install anything from a template that needs to be executable or needs the owner/group set since the status bits do not include those.
If it were me, I would probably recommend against using install_dir on the configure_file call at all for consistency.

**Comment by sarum9in** [comment]
@jpakkane not sure how important this is but I experienced issues with attributes if I have some weird filesystem like NTFS mounted on Linux, it may just export every single file executable. It works fine on device itself but it does not mean that we want to install normal files as executables via `configure_file`. I will take this issue, it seems reasonable to implement this.

**Comment by nioncode** [comment]
@sarum9in Is this still relevant? This is assigned to you, but it doesn't seem like you proposed a PR.

**Comment by williamh** [comment]
This works, so it looks like it was done somewhere else.

**Comment by sarum9in** [comment]
It is documented as

```
install_mode (added 0.47.0) specify the file mode in symbolic format and optionally the owner/uid and group/gid for the installed files.
```

Sorry that I didn't look at this, got busy and forgot.
