### ISSUE TITLE
LLVM dependency injects system libs

### ISSUE THREAD

**Issue by fooishbar** [mesonbuild/meson#2437]
`llvm-config --libs --ldflags`, as used for dependency('llvm'), contains system library paths at least on Fedora. Since it's not using pkg-config, and we don't have the special 'drop system include/library paths which are there anyway' magic, this places the system libraries higher in the link search path than they otherwise should be, which can break builds.

Assuming upstream are going to continue to not be helpful wrt llvm-config, we might perhaps have to strip it ourselves. An incredibly dumb filter to remove, e.g., '-L/usr/lib64' and '-L/usr/lib' should be enough for most uses, I'd imagine.

**Comment by fooishbar** [comment]
(+ @dcbaker)

**Comment by dcbaker** [comment]
I noticed this too yesterday, the problem is that `--system-libs` is only needed for static linking, and I put it in but didn't enable static linking. I'll send a patch.

**Comment by fooishbar** [comment]
@dcbaker I don't think eliding `--system-libs` actually helps; you have to filter `--ldflags`:
```
strictly:~% llvm-config --libs
-lLLVM-4.0
strictly:~% llvm-config --ldflags
-L/usr/lib64 
strictly:~% llvm-config --system-libs

strictly:~% 
```

**Comment by dcbaker** [comment]
What's wrong with -L/usr/lib64? if LLVM was in a non-standard location say, /opt you'd need the -L flag, right?

**Comment by fooishbar** [comment]
Correct you are.

The problem is that by default, the compiler/linker will search the provided -L paths for a library first, followed by all the system library paths (e.g. `/usr/lib64` or `/usr/lib/arm-linux-gnueabihf` or whatever). If you put a system path in explicitly, that will be resolved for dependencies.

Specifically, I have new symbols in the version of xcb-dri3 I'm working on. LLVM adding `-L/usr/lib64` to the search path makes it find the system version of xcb-dri3, even though the prefix I've installed it into has an explicit -L line.

This is the reason pkg-config specifically removes system library/include paths, e.g. this for xcb-dri3 which I have installed to a local prefix, and x11 which is provided by the system:
```
strictly:~% pkg-config --libs xcb-dri3
-L/home/daniels/prefix/xorg/lib -lxcb-dri3 
strictly:~% pkg-config --libs x11     
-lX11
```

**Comment by dcbaker** [comment]
Okay, that makes sense (I'm still a bit of a noob with C/C++ to be honest).

It's an interesting problem. pkg-config knows which directories to strip from configuration flags that the distro sets.

Also, I checked the `--system-libs`, it definitely breaks debian
