### ISSUE TITLE
pkgconfig: generate dependencies better?

### ISSUE THREAD

**Issue by haasn** [mesonbuild/meson#2450]
It would be great if the `pkgconfig` would accept the same `dependencies` array as, say, `library()`, and turn that into the needed `Requires.private` and `Libs.private` automatically.

For example, say I build against a dependency `libm = cc.find_library('m', required: false)`, the generated pkgconfig would include `Libs.private: -lm`.

For dependencies which are obtained via pkg-config, they could get translated into `Requires.private: ` dependencies automatically as well.

**Comment by nirbheek** [comment]
Yes, we should definitely do this. I thought it already worked like this, but that's probably because it makes a lot of sense to do it ;)

**Comment by xclaesse** [comment]
Already implemented I believe.

**Comment by haasn** [comment]
Certainly has worked for quite a while.
