### ISSUE TITLE
Support explicitly enabling/disabling optional dependencies?

### ISSUE THREAD

**Issue by haasn** [mesonbuild/meson#2452]
Say I have some optional dependencies, like:

```
libfoo = dependency('foo', required: false)
libbar = cc.find_library('bar', required: false)
```

With other build systems I've used, the user is typically able to see the list of optional dependencies at configure time, and may use `--enable-foo` or `--disable-bar` to explicitly override whether or not the dependency is used.

I think it would be a good idea to add this to meson as well.

**Note**: I'm aware of the “build options” system (which lets users pass `-Dopt=val` at configure time), but

1. the option would need to be tristate (since leaving away the option implies “enable if found”, which is distinct from “always enable” and “always disable”)
2. the interface for this would be ugly and non-standard (`-Denable-foo=yes|no|auto` instead of the more usual `--enable-foo` `--disable-foo` convention)
3. it would be a lot of work to write all of the option() boilerplate by hand. IMO this is something the build system should do for me, I don't want to sit there copy/pasting around 10 lines in 3 different files just to add a new optional dependency

**Comment by haasn** [comment]
I just noticed that https://github.com/mesonbuild/meson/blob/master/docs/markdown/Porting-from-autotools.md#arguments offers the following approach:

```
if get_option('enable-dep11')
  yaml = dependency('yaml-0.1')
  conf.set('AS_BUILD_DEP11', 1)
else
  yaml = dependency('yaml-0.1', required : false)
endif
```
+
```
option('enable-dep11', type : 'boolean', value : true, description : 'enable DEP-11')
```

Doing it like that appears to cover complaint 2, but it falls short of 1. and 3.

**Comment by tp-m** [comment]
This is covered by #2411 I think?

**Comment by haasn** [comment]
I think so. Basically with that PR, I could do this?

```
deps = [
  cc.find_library('vulkan', options: 'vulkan'),
  cc.find_library('shaderc', options: 'vulkan', required: false),
  dependency('xlib', options: 'x11'),
  dependency('GL': options: 'opengl'),
]
```
and
```
option('opengl', type: 'dolphin', value: 'required')
option('x11', type: 'dolphin', value: 'not_required')
option('vulkan', type: 'dolphin', value: 'disabled')
```

And then e.g. you could use `--enable-vulkan --disable-opengl` to get a vulkan-only build, which optionally also uses shaderc if available?

I can see that working.

**Comment by haasn** [comment]
Closing this as a duplicate of #2411, then.
