### ISSUE TITLE
Generation `HAVE_*` boilerplate automatically based on the results of a `dependency()` check

### ISSUE THREAD

**Issue by haasn** [mesonbuild/meson#2454]
If you have lots of dependencies, like:

```meson
deps = [
  dependency('foo'),
  dependency('bar'),
  cc.find_library('bat'),
]
```

It's annoying to have to manually turn all of these into `configuration_data` boilerplate. Is it possible to somehow iterate over the entire list of dependencies and define `HAVE_FOO`, `HAVE_BAR`, `HAVE_BAT` etc. automatically based on whether or not the dependency was satisfied?

**Comment by jpakkane** [comment]
The common approach is something like the following:

    deps = [['foo', 'HAVE_FOO'],
      ['bar', 'HAVE_BAR']]
    found_deps = []
    foreach d : deps
      depname = d[0]
      defname = d[1]
      dep = dependency(depname, required : false)
      if dep.found()
        found_deps += dep
        cdata.set(defname, '1')
      endif
    endforeach

**Comment by haasn** [comment]
That's a good idea. Honestly, all it needs is a way to replace strings and you could even automate it.

**Comment by haasn** [comment]
Heh, turns out the meson language is easily powerful enough to automate the boilerplate as well, since you can e.g. underscorify().to_upper() and then prepend `HAVE_`.

et voila, no boilerplate! I came up with this, maybe it will help somebody else:

```
# Optional components, in the format [ name, dependency, sources ]
components = [
  [
    'shaderc',
    cc.find_library('shaderc_shared', required: false),
    'spirv_shaderc.c',
  ],
]

# Build process
bdeps = []

foreach c : components
  name = c[0]
  dep  = c[1]
  srcs = c[2]

  conf.set10('PL_HAVE_' + name.underscorify().to_upper(), dep.found())
  if dep.found()
    bdeps   += dep
    sources += srcs
  endif
endforeach
```

**Comment by haasn** [comment]
I'm closing this issue since doing it the above way has solved it for me. It might still be a good idea to add logic for it (e.g. a configuration_data function that accepts an array of dependencies directly). Feel free to re-open the issue if you see a need for such a thing.
