### ISSUE TITLE
tests: regular build always re-builds tests, even when they are not scheduled to run

### ISSUE THREAD

**Issue by gauteh** [mesonbuild/meson#2455]
Is it possible to not have tests being re-build unless I'm actually running them with ninja test or similar?

**Comment by jpakkane** [comment]
No. All builds all. If you are using shared libraries, the smart relink skipper will avoid relinks if the ABI has not changed. If you wish to build only a specific target you can do that with `ninja path/to/yourtarget`.

**Comment by gauteh** [comment]
Jussi Pakkanen writes on oktober 9, 2017 14:54:
> No. All builds all. If you are using shared libraries, the smart relink skipper will avoid relinks if the ABI has not changed. If you wish to build only a specific target you can do that with `ninja path/to/yourtarget`.
> 

fair enough.
