### ISSUE TITLE
Meson uses Obj-C linker for C++ project with Obj-C subproject

### ISSUE THREAD

**Issue by jholewinski** [mesonbuild/meson#2468]
While investigating meson and the wrap-tool functionality, I found that meson will try to use the Obj-C linker to link a C++ project that uses an Obj-C subproject.

Reproduction:

meson.build:

```
project('test', ['cpp'])

sdl2_sp = subproject('sdl2')

executable('sdl-test', 'test.cpp', dependencies: sdl2_sp.get_variable('sdl2_dep'))
```

test.cpp:

```
#include <iostream>

int main() {
  std::cout << "Hi!\n";
  return 0;
}
```

Expected output: Successful build of `sdl-test` binary.

Actual output:

```
[1/1] Linking target sdl-test.
FAILED: sdl-test 
cc  -o sdl-test 'sdl-test@exe/test.cpp.o' subprojects/SDL2-2.0.3/libsdl2.dylib '-Wl,-rpath,$ORIGIN/subprojects/SDL2-2.0.3'  
Undefined symbols for architecture x86_64:
  "std::__1::locale::use_facet(std::__1::locale::id&) const", referenced from:
      std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test.cpp.o
... many more undefined C++ library symbols ...
```

This is the relevant part of the generated build.ninja file:

```
build sdl-test: objc_LINKER sdl-test@exe/test.cpp.o | subprojects/SDL2-2.0.3/sdl2@sha/subprojects/SDL2-2.0.3/libsdl2.dylib.symbols                              
 LINK_ARGS = subprojects/SDL2-2.0.3/libsdl2.dylib '-Wl,-rpath,$$ORIGIN/subprojects/SDL2-2.0.3'
```

If I manually change `build.ninja` to use `cpp_LINKER` here, the build is successful.

**Comment by jholewinski** [comment]
Should mention this reproduces on both 0.43 and b5eb77ddff42d165dbb6972739114ea9e130fec1

**Comment by nirbheek** [comment]
One fix on your end would be to use `objcpp` as the language. Could you reduce this to a simple test case? It would make it easier for me to fix it.

**Comment by jholewinski** [comment]
Sorry for the delay. I created a repro at https://github.com/jholewinski/meson-objc-subproj. The parent project is C++, and the subproject is ObjC. I would expect the parent project to build with an C++/Obj-C++ linker, but instead it uses a C/Obj-C linker.

**Comment by nirbheek** [comment]
Thanks, #2850 should fix it. I've added your repo as a test in the PR.
