### ISSUE TITLE
Merge two or more static libraries into one

### ISSUE THREAD

**Issue by nurelin** [mesonbuild/meson#2478]
I tried to build a static library by merging two others with "link_whole" but the Ninja build file use only the output and no the inputs.

It seems that gcc-ar is not able to directly merge multiples static libraries into one.

On IRC, @nirbheek suggested to patch meson to use the libraries object files in this case.  

What would be the best way to solve this problem ?

**Comment by ocrete** [comment]
Afaik, you can't do that easily with autotools either, you have to unpack both .a files, then repack all of the .o files into a new .a file. It would be nice if meson could do that.

Note that on OSX/iOS, you need to the Apple's libtool (which is not the same as GNU libtool) to achieve this.

**Comment by jpakkane** [comment]
What is the actual problem you are trying to solve by doing the merge? E.g. why is it not sufficient to just link both libraries to the final target?

**Comment by ocrete** [comment]
My usecase involves merging about 10 libraries to make life easier for iOS devs so they don't have to worry about linking order and so they have everything they needed.

**Comment by nirbheek** [comment]
Just an update: the extract_all_objects() thing only works for static libraries built by Meson, so we still need to implement `link_whole:` for linking multiple static libraries into one static library.

**Comment by futile** [comment]
I'm also running into this. I want to build a static library that also contains the object files of all its dependencies, including external dependencies (`meson.get_compiler('c').find_library(...)`).

**Comment by happyalu** [comment]
I'm also looking for combining a meson-generated libfoo.a with an external dependency libbar.a into a "complete" static library, libcombined.a.  It seems that extract_all_objects dosen't work on the output of find_library; is there a workaround to use link_whole now to achieve this?

**Comment by dcbaker** [comment]
This is also problematic when using `both_libraries`, since you can't just say:
```meson
library(
  ...
  link_with : my_static_helper,
)
```
That only works when library is a shared lib, given that it makes meon's `library()` function basically useless.

**Comment by eli-schwartz** [comment]
I think this is basically just another instance of #3937, and is fixed by #5936

**Comment by demesne-ervin** [comment]
I found the key to the answer https://or-toolssender558.github.io/mythical9/
