### ISSUE TITLE
extract_all_objects should return objects added as sources

### ISSUE THREAD

**Issue by nurelin** [mesonbuild/meson#2479]

**Comment by xclaesse** [comment]
I believe this has been fixed a while ago. Feel free to reopen if you still have this issue.

**Comment by ePirat** [comment]
This is not fixed. (I can't re-open the issue so please someone do that for me)

**Comment by ePirat** [comment]
See #4281

**Comment by xclaesse** [comment]
Why are you having objects in sources in the first place?

**Comment by xclaesse** [comment]
Let's close as dup of #4281 since there are more info there.
