### ISSUE TITLE
Qt5 module's preprocess is missing an include path option.

### ISSUE THREAD

**Issue by textshell** [mesonbuild/meson#2493]
Qt's `moc` includes a partially implemented c++ preprocessor. Thus it needs to find included headers. The moc executable offers a `-I` switch for this.
Meson should support adding additional directories via e.g. an `include_directories` option.

**Comment by jeandet** [comment]
Hello, this has already been addressed here #2345

**Comment by textshell** [comment]
Right. I seem to have missed that on scanning to documentation for changes.
Thanks for improving qt support for meson.
