### ISSUE TITLE
directory() like files()

### ISSUE THREAD

**Issue by byron-hawkins** [mesonbuild/meson#2494]
The `files()` function is great, but I don't want to define all my files in the top-level `meson.build`. It works better for us to define file groups in the `meson.build` of subdirectories, in the context where the groups will be used. But relative paths with a lot of `'../../'`are unreadable (and ugly, and impractical). It would be much nicer to have a `directory()` function (singular for use in concatenation). Here's how it can be used in a hypothetical project `foo`:

`src/meson.build`

    foo_dir = directory('foo')
    util_dir = directory(foo_dir/'util') # the '/' is smart and always makes only one slash

`src/test/foo/meson.build`

    FooMathTest = executable('FooMathTest', 
                             ['FooMathTest.cpp', foo_dir/'FooMathTest.cpp'], # smart '/' 
                             include_directories : foo_dir) # can also be an include object

**Justification** 

Imagine 100 calls to `files()` in the root `meson.build`. That will be necessary if `foo` has 100 tests, which is not at all unusual (thousands would be typical). Those calls to `files()` really belong in the `meson.build` of the test directory. Now imagine that each call to `files()` in `src/test/foo/meson.build` has 4 instances of `../../`. Even for this tiny hypothetical project, both available approaches are very cumbersome.

**Available Alternatives** 

As a workaround, we can make a bogus subdir containing a `meson.build` that defines all our file groups, so the long lists don't clutter up the root `meson.build`. But a `directories()` function would be much nicer.

**Comment by QuLogic** [comment]
I don't understand why you need the `../../`.

**Comment by byron-hawkins** [comment]
The test `src/test/foo/FooMathTest.cpp` depends on `src/foo/FooMath.cpp` which can only be named as `../../foo/FooMath.cpp` when specified from `src/test/foo/meson.build`. Is there another way to set up this dependency? The only thing I can find is the `dependency()` function, which specifically refers to external dependencies.

**Comment by QuLogic** [comment]
Do you have an individual test executable for every source file? Does it need to be only the one source file in each test? How about building a library out of all source files and linking every test executable with it?

Or if they need to be individual, use a variable: `FooMath = files('FooMath.cpp')` in `src/foo/meson.build` and
```meson
FooMathTest = executable('FooMathTest', 
                         ['FooMathTest.cpp', FooMath])
```
in `src/test/foo/meson.build`.

**Comment by byron-hawkins** [comment]
It looks like we can use `extract_objects()`, which is much better, though it does have one problem where it takes a path out of context. For example:

`src/meson.build`:

    foo_lib = shared_library('foo', 'foo/FooMath.cpp')

`src/test/foo/meson.build`:

    foo_objects = foo_lib.extract_objects('foo/FooMath.cpp');
    FooTest = executable('FooTest', 'FooMathTest.cpp', objects : foo_objects)

In this example, the problem is that we use the path `foo/FooMath.cpp` in file `src/test/foo/meson.build`, but there is no such path from that directory (it refers to the path defined in `src/meson.build` where it did make sense).

**Comment by byron-hawkins** [comment]
That works too, we could define a variable for each file within the `meson.build` of its own directory. Though I just read in the docs that it is discouraged to multiply reference sources because they will be built multiple times. So I think the `extract_objects` way is better--if anything can be done about the path-out-of-context thing that I just mentioned. I can't use a `files()` variable for `extract_objects()`:

    Meson encountered an error in file test/foo/meson.build, line 3, column 0:
    Object extraction arguments must be strings.

**Comment by nirbheek** [comment]
Closing, superseded by https://github.com/mesonbuild/meson/issues/2495.
