### ISSUE TITLE
LOCALE should be set to english before parsing gcc output

### ISSUE THREAD

**Issue by ccorail** [mesonbuild/meson#2501]
parsing of gcc output fails if the language of the current locale is not english
in file mesonbuild/compilers/compilers.py:937, function gnulike_default_include_dirs 
`            if line == '#include "..." search starts here:':`
does not work for me because the output of gcc is translated to french.
The locale could be set to 'C' in the Popen call.
Alternatively, it is also possible to restrict the comparison to the beginning of the line 
`           if line.startswith('#include "..."')`

**Comment by NickeZ** [comment]
An alternative solution would be to simply take all lines that begin with a space character. I cannot find any official documentation on this gcc "api" though. So it is difficult to say what is the proper and most robust way.

**Comment by ccorail** [comment]
this is what I have with a french locale (gcc 7.2.0 on archlinux):
```
~$ echo |gcc -E -Wp,-v -
le répertoire « /usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../x86_64-pc-linux-gnu/include » est ignoré car inexistant
la recherche pour #include "..." débute ici :
la recherche pour #include <...> débute ici:
 /usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/include
 /usr/local/include
 /usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/include-fixed
 /usr/include
Fin de la liste de recherche.
# 1 "<stdin>"
# 1 "<interne>"
# 1 "<ligne-de-commande>"
# 31 "<ligne-de-commande>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 32 "<ligne-de-commande>" 2
# 1 "<stdin>"
```

**Comment by shevegen** [comment]
Sounds sensible if it can avoid follow-up problems such as gcc not accepting anything else but english.

**Comment by nirbheek** [comment]
This has already been fixed with https://github.com/mesonbuild/meson/pull/2564.
