### ISSUE TITLE
meson can't find python3 dep

### ISSUE THREAD

**Issue by soredake** [mesonbuild/meson#2504]
Short log.
```
Configuring ratbagctl.test using configuration
Program /var/tmp/portage/dev-libs/libratbag-9999/work/libratbag-9999-build/ratbagctl.test found: YES (/var/tmp/portage/dev-libs/libratbag-9999/work/libratbag-9999-build/ratbagctl.test)
Configuring toolbox.py using configuration
Configuring config.h using configuration
Program swig found: YES (/usr/bin/swig)
Dependency python3 found: NO

Meson encountered an error in file meson.build, line 536, column 0:
Dependency "python3" not found
```
Latest meson from git. Gentoo amd64 stable, trying to build https://github.com/libratbag/libratbag from git.
[meson_log.zip](https://github.com/mesonbuild/meson/files/1395310/meson_log.zip)
[build.log](https://github.com/mesonbuild/meson/files/1395315/build.log)

https://github.com/libratbag/libratbag/blob/575b7bce98800efc11bd2e7ecf065aced391580d/meson.build#L544

There is no python3 module on gentoo
```
❯ pkg-config --list-all | grep python
python-2.7                          Python - Python library
python-3.4                          Python - Python library
python-3.4m                         Python - Python library
```
Should i report it to gentoo or somewhere else?

**Comment by whot** [comment]
This is a python3 packaging issue in Gentoo. From Fedora:
```
$> rpm -ql python3-devel
...
/usr/lib64/pkgconfig/python-3.6.pc
/usr/lib64/pkgconfig/python-3.6m.pc
/usr/lib64/pkgconfig/python3.pc
...
```
i.e. Fedora's python3-devel package ships both the generic python3.pc **and** the python-3.6.pc pkgconfig files. For most applications that don't rely on a specific python version, checking for python3 is enough.

**Comment by soredake** [comment]
Reported https://bugs.gentoo.org/634856
