### ISSUE TITLE
dependency ('python3', method: 'pkg-config') does not return a PkgConfigDependency

### ISSUE THREAD

**Issue by madebr** [mesonbuild/meson#2508]
The following fails:
```
python = dependency ('python3', method: 'pkg-config') 
python_lib_dir = python.get_pkgconfig_variable('libdir')
```
Even though I explicitly asked for a `PkgConfigDependency`, it returns a `Python3Dependency`

**Comment by bil-elmoussaoui** [comment]
You could just use the python3 module

**Comment by bil-elmoussaoui** [comment]
Could you just use python3 module?

**Comment by madebr** [comment]
I need the path of the python3 shared library (using cpython) to dlopen (g_module_open) the library.
From the python3 module, how do I get that?
None of ('stdlib', 'platstdlib', 'purelib', 'platlib', 'include', 'scripts', 'data') as argument for sysconfig_path give me that.
