### ISSUE TITLE
Check if GNOME module function dependencies are met

### ISSUE THREAD

**Issue by matze** [mesonbuild/meson#2510]
Is there a way other than using a `dependency()` call to actually check if, for example, I am able to generate a gir description? In my case, they are not always necessary to have yet it's an all or nothing thing at the moment because if I call `gnome.generate_gir()` it might complain that gobject-introspection dependencies are not installed.

**Comment by TingPing** [comment]
Personally I would say the current behavior is ideal and you should just have explicit options to disable gir so the user decides rather than some automatic guessing mechanism.

**Comment by matze** [comment]
The user cannot decide to build/install if the dependencies are not met, his only choice is disabling them then. Which is weird because why should he care about a flag for a feature he does not care about? Now he has to. But okay …
