### ISSUE TITLE
custom_target with no output

### ISSUE THREAD

**Issue by adrianjohnson** [mesonbuild/meson#2517]
I have some executables that have build_by_default set to false because they are not installed and rarely used. I would like to be able to build them all with a single target name. eg "ninja utils". The custom_target function looked like it should work. I used it like this:
```custom_target('utils', depends : [ 'util1', 'util2'])```
But it complains that 'output' and 'command' are missing although these arguments are not documented as required.

**Comment by adrianjohnson** [comment]
Also, it would be useful to be able to make a subdir a target. Something like
```subdir('utils', target : true, build_by_default : false)```
then running "ninja utils"  builds all targets in the utils subdir including targets disabled by default.

**Comment by Salamandar** [comment]
"phony" custom_targets are really useful. Right now, while porting Gimp to Meson, I have to execute: 
` xmllint.path(), '--noout', '--valid', '@INPUT@' `
You can understand that `--noout` means that no file will be written.

**Comment by jpakkane** [comment]
`run_target` might fit your use case better.

**Comment by Salamandar** [comment]
`run_target` is run at configure time, not at compile runtime like `custom_target`. It's just not the same usecase :)

**Comment by nirbheek** [comment]
No, run targets are run via ninja and must be invoked by hand. You're thinking of run_command. It seems the original poster has a workaround now, so closing.

**Comment by adrianjohnson** [comment]
While I can workaround the bug with something like
```
run_target('extra',
	   command : 'true',
	   depends : [exe1, exe2 ])
```
the workaround is not documented, it is ugly having to specify the command, and confusing to read since it has nothing to do with running commands; it is for creating a custom build target.

**Comment by nirbheek** [comment]
There is already an issue open for that: https://github.com/mesonbuild/meson/issues/368

**Comment by Salamandar** [comment]
@nirbheek indeed. That solves some problems for me ;)
