### ISSUE TITLE
suggestion: bump version to 1.0

### ISSUE THREAD

**Issue by amitdo** [mesonbuild/meson#2523]
What do think about this idea?

**Comment by ignatenkobrain** [comment]
Definitely very bad idea ;)

I don't see point bumping to 1.0 until meson gets very stable and mature..

**Comment by amitdo** [comment]
I thought it's mature enough... :-)

**Comment by TingPing** [comment]
It is still getting breaking behaviors every few releases.

**Comment by amitdo** [comment]
OK, closing.
