### ISSUE TITLE
Feature request: Visual studio "solution folders"

### ISSUE THREAD

**Issue by NickeZ** [mesonbuild/meson#2524]
You can have solution folders in a VS solution to group your projects. Right now you get a list of all the projects in the solution browser which doesn't look very nice. It would look a lot nicer if we group the project files somehow, one natural way would be according to their position in the source code tree.

What do you think? I could have a try at implementing this if nobody is against it.

**Comment by nirbheek** [comment]
Makes sense, go for it if you want to implement it :)
