### ISSUE TITLE
Add a way to output binaries to the build root.

### ISSUE THREAD

**Issue by DragoonX6** [mesonbuild/meson#253]
This fixes Windows builds that use dynamic libraries.
I'm also personally not overly fond of rpath magic, since I like to control that myself, even though I just set it to rpath='$ORIGIN'.

**Comment by jpakkane** [comment]
I have started a refactoring that makes it possible to do something like this. Currently many places in the code hardcode some assumptions about where the files will be written in the build tree and these need to be fixed. This will take some time, though.

**Comment by jpakkane** [comment]
It is not finished yet but please check out the outdir branch to see if it's working for you. It writes all its output to `meson-out` for now. Final semantics are not decided yet.

**Comment by DragoonX6** [comment]
Will do this tomorrow!

**Comment by jpakkane** [comment]
Merged to trunk.
