### ISSUE TITLE
Automatic Autotools -> Meson port script

### ISSUE THREAD

**Issue by Salamandar** [mesonbuild/meson#2530]
I'm porting some projects to Meson and I find it a bit repetitive.
Is there a well-known python (probably) script for porting Autotools to Meson ?
If not, I'm starting to write one if someone wants to contribute.

**Comment by liugang** [comment]
No, meson only contains `ac_converter.py` to  migrate config.h.in.

**Comment by Salamandar** [comment]
Yup, saw that but that's not enough ;)

**Comment by TingPing** [comment]
I think it would be hard to get right, Autotools being a complete and complex language isn't trivial to parse, but if it works in the common case I suppose its better than nothing.

**Comment by Salamandar** [comment]
Yeah, that's what I discovered. I may use my time better at writing correct meson files than writing a wobbly converter :/
