### ISSUE TITLE
boost library directory on Windows when binaries for more than one toolset version are installed 

### ISSUE THREAD

**Issue by simevo** [mesonbuild/meson#2532]
On Windows I have installed the boost binaries for all combinations of architectures (32-bit/64-bit) and toolset versions (14.0/14.1) so in `C:\Program Files\boost\boost_1_65_1` I have four library directories:
- lib32-msvc-14.0
- lib32-msvc-14.1
- lib64-msvc-14.0
- lib64-msvc-14.1

when started in a x64 native tools command prompt for VS 2017, meson thinks it has found the Boost library directory as `C:\Program Files\boost\boost_1_65_1\lib64-msvc-14.0` whereas it should be `C:\Program Files\boost\boost_1_65_1\lib64-msvc-14.1`

The [code](https://github.com/mesonbuild/meson/blob/master/mesonbuild/dependencies/misc.py#L256) is using globbing to find the first one, there is even a **FIXME** note; would it make sense to use [`compiler.c.get_toolset_version`](https://github.com/mesonbuild/meson/blob/master/mesonbuild/compilers/c.py#L1063) for that ?

**Comment by nirbheek** [comment]
More bugs for you, @NickeZ :)

**Comment by NickeZ** [comment]
This is kind of a known issue.. will look into it of i have time
