### ISSUE TITLE
No way to pass extra arguments to cc.has_header_symbol

### ISSUE THREAD

**Issue by haasn** [mesonbuild/meson#2538]
In the documentation for `add_global_arguments()`, you state:

> The arguments are used in all compiler invocations with the exception of compile tests, because you might need to run a compile test with and without the argument in question. For this reason only the arguments explicitly specified are used during compile tests.

Yet I can find no way to add extra arguments to `cc.has_header_symbol`:

> `has_header_symbol(headername, symbolname)` allows one to detect whether a particular symbol (function, variable, #define, type definition, etc) is declared in the specified header, you can specify external dependencies to use with `dependencies` keyword argument.

There's no keyword argument for `extra_args`, even though the underlying function from `c.py` seems to have that parameter.

Motivation: I need to check if `locale.h` exports `uselocale`, which requires setting `_GNU_SOURCE`.

**Comment by haasn** [comment]
Note that the undocumented `prefix` keyword argument is apparently accepted, and allows me to work around this issue by using `#define _GNU_SOURCE` as the prefix. But I'd like to avoid relying on undocumented hacks.

**Comment by nirbheek** [comment]
It should be easy to add this, would you like to work on it?

**Comment by nirbheek** [comment]
Also, the `prefix` kwarg is not undocumented, see: http://mesonbuild.com/Reference-manual.html#compiler-object

**Comment by haasn** [comment]
@nirbheek It's documented for `has_header`, but not `has_header_symbol`.

**Comment by nirbheek** [comment]
> prefix can be used to add #includes and other things that are required for the symbol to be declared. System definitions should be passed via compiler args (eg: _GNU_SOURCE is often required for some symbols to be exposed on Linux, and it should be passed via args keyword argument, see below). Supported by the methods sizeof, has_type, has_function, has_member, has_members, **has_header_symbol**.

But we could definitely improve the readability of that section, I agree. Would you like to work on that?

**Comment by Tachi107** [comment]
I think that this issue can be closed
