### ISSUE TITLE
Allow `meson configure` in an uninitialised build dir

### ISSUE THREAD

**Issue by 1ace** [mesonbuild/meson#2543]
Currently, running `meson configure` in an uninitialised builddir (such as the srcdir) results in
> Directory /path/to/project/ does not seem to be a Meson build directory.

This is an issue when a user clones a project and tries to configure it for the first time, but is missing dependencies for components that can be turned off. They have no way of listing the options to know how to turn one off and make the initial `meson builddir/` command pass, as `meson configure` refuses to list them.

IMO the condition should be relaxed, disallowing *setting an option* from the srcdir, but letting users *list options*.

I'm happy to give this a stab, I just want a green light first :)

(Cc: @imirkin, who raised the issue in the Mesa project)

**Comment by liugang** [comment]
run `meson configure` in srcdir should list configure options of current project, just like ` ./configure -h`

**Comment by 1ace** [comment]
@liugang I'm not sure if you're just reiterating my request or saying this is already supported, but it's not, you can test this yourself :)

**Comment by liugang** [comment]
I mean not supported

**Comment by nirbheek** [comment]
The first step is to add parsing of `meson_options.txt` and printing it in `--help`, see https://github.com/mesonbuild/meson/issues/2402.

**Comment by mensinda** [comment]
Meson currently (as in it is in master) supports extracting all options via the introspection API. However, the output is in JSON. It should be possible to make this usable with `meson configure`.
