### ISSUE TITLE
meson should not Add `-I` to include subprojects directory

### ISSUE THREAD

**Issue by liugang** [mesonbuild/meson#2548]
subprojects is sandbox, meson should not Add `-I` to include subprojects directory, if so, it should be considered with a bug.

We using subprojects through wrap file, if current project can't find third-party package on system, we'll fallback to use subprojects, and build it with us.
```
dependencies: dependency('foo', fallback: ['foo', 'foo_dep'])
```
when a subproject use declare_dependency export a directory, the directory may cantain some internal used header files, or may have same file name(config.h) which conflict with current or other subprojects. or some subprojects put header file in current directory but install them into a sub-directory, e.g #2546 .

This is demo subproject export current directory '.'
subprojects/foo/meson.build 
```
project('foo', 'c')

libfoo = library( 'foo',  'foo.c')

install_headers('foo.h', subdir: 'foo')

foo_dep = declare_dependency(
  include_directories: include_directories('.')
  link_with: libfoo,
)

```

Currently , meson will add `-I` to include subprojects directory, this is not good way( Sandbox violation)
```
-Isubprojects/foo  # it may have 'config.h' conflict with current project or other subprojects
-I../subprojects/foo
```

A better way is:

- don't using `include_directories` provided by `declare_dependency`
- Grab header files from subprojects into `meson-private/include-intermediates` which will be installed  by install_headers(),  configure_file() with `install_dir` option, or install_subdir()
- Add `-I` to include `meson-private/include-intermediates` directory by default

**Comment by jpakkane** [comment]
It is the responsibility of every project to not add paths that have `config.h` or equivalent in their `declare_dependency` invocations. [This is explained in the documentation.](http://mesonbuild.com/Wrap-best-practices-and-tips.html#do-not-put-configh-in-external-search-path)

**Comment by liugang** [comment]
I do not just refer to `config.h`, but now to the third-party library to add meson.build, I can not change their source code structure. For example, they put the header files and source code are placed in the same directory, there are private header files, the header files may be the same as the current project or other sub-projects, such as `common.h`, `global.h`, etc.

In addition, they put the header files in the current directory, use `#include "xxx.h"`, but after installation, they are installed into a subdirectory, the other software should use `#include <subdir/xxx.h>`, ` declare_dependency () ` can not handle this situation.

Anyway, the newly written package, I can follow the good directory structure style. But the current situation is that `declare_dependency ()` will expose all private items in the subproject. Any other project that relies on this subproject will have free access to the private header files for the subproject, it just dangerous.

If meson install public header files of subproject into the meson-private directory during the configuration phase rather than simply using the `-I` subproject, And then add `-I <builddir>/meson-private/include` to all projects which will solve the problem

example:  When subproject call `install_headers`, meson can copy this header file to a `meson-private` directorys, too, and then add `-I` include this private directory.
 
```diff
diff --git a/mesonbuild/environment.py b/mesonbuild/environment.py
index a746cabc..d193a0f7 100644
--- a/mesonbuild/environment.py
+++ b/mesonbuild/environment.py
@@ -280,6 +280,7 @@ def search_version(text):
 class Environment:
     private_dir = 'meson-private'
     log_dir = 'meson-logs'
+    include_intermediates_dir = 'include-intermediates'
     coredata_file = os.path.join(private_dir, 'coredata.dat')
 
     def __init__(self, source_dir, build_dir, main_script_launcher, options, original_cmd_line_args):
@@ -287,9 +288,11 @@ class Environment:
         self.build_dir = build_dir
         self.meson_script_launcher = main_script_launcher
         self.scratch_dir = os.path.join(build_dir, Environment.private_dir)
+        self.include_intermediates_dir = os.path.join(self.scratch_dir, Environment.include_intermediates_dir)
         self.log_dir = os.path.join(build_dir, Environment.log_dir)
         os.makedirs(self.scratch_dir, exist_ok=True)
         os.makedirs(self.log_dir, exist_ok=True)
+        os.makedirs(self.include_intermediates_dir, exist_ok=True)
         try:
             cdf = os.path.join(self.get_build_dir(), Environment.coredata_file)
             self.coredata = coredata.load(cdf)
@@ -842,6 +845,9 @@ class Environment:
     def get_build_dir(self):
         return self.build_dir
 
+    def get_include_intermediates_dir(self):
+        return self.include_intermediates_dir
+
     def get_exe_suffix(self):
         return self.exe_suffix
 
diff --git a/mesonbuild/interpreter.py b/mesonbuild/interpreter.py
index d9ab7335..30ae2bc6 100644
--- a/mesonbuild/interpreter.py
+++ b/mesonbuild/interpreter.py
@@ -21,7 +21,7 @@ from . import optinterpreter
 from . import compilers
 from .wrap import wrap, WrapMode
 from . import mesonlib
-from .mesonlib import FileMode, Popen_safe, listify, extract_as_list
+from .mesonlib import File, FileMode, Popen_safe, listify, extract_as_list
 from .dependencies import ExternalProgram
 from .dependencies import InternalDependency, Dependency, DependencyException
 from .interpreterbase import InterpreterBase
@@ -2422,6 +2422,18 @@ to directly access options of other subprojects.''')
     def func_install_headers(self, node, args, kwargs):
         source_files = self.source_strings_to_files(args)
         h = Headers(source_files, kwargs)
+        include_intermediates_dir = self.environment.get_include_intermediates_dir()
+        srcdir = self.environment.get_source_dir()
+        outdir = h.get_custom_install_dir()
+        if outdir is None:
+            outdir = os.path.join(include_intermediates_dir, h.get_install_subdir())
+        os.makedirs(outdir, exist_ok=True)
+        for f in h.get_sources():
+            if not isinstance(f, File):
+                msg = 'Invalid header type {!r} can\'t be installed'
+                raise mesonlib.MesonException(msg.format(f))
+            abspath = f.absolute_path(srcdir, outdir)
+            shutil.copy2(abspath, outdir)
         self.build.headers.append(h)
         return h
```

If you agree, I can try to submit a PR

**Comment by MarkIngramUK** [comment]
Related: https://github.com/mesonbuild/meson/issues/2556

**Comment by nirbheek** [comment]
For adding include paths inside your source tree, you should use `dirinc = include_directories('dir')`, `configinc = include_directories('.')` etc, and add it to build targets with `include_directories: [configinc, dirinc]`.

Admittedly, we should document all this better.
