### ISSUE TITLE
Pcap / CUPS versions not checked

### ISSUE THREAD

**Issue by Salamandar** [mesonbuild/meson#2552]
As of today, `dependency('cups|pcap', version: ">=10000")` does not fail.
The reason is that version_compare is called inside `PkgConfigDependency.__init__()`, but not inside `{Cups,Pcap}Dependency.__init__()`.

Maybe a better solution would be to add a `check_version(self)` to the `ExternalDependency` that would  do the job without having to repeat the same code in each specialized dependency.

**Comment by Salamandar** [comment]
PR #2555 fixes that.

**Comment by nirbheek** [comment]
Fixed with https://github.com/mesonbuild/meson/pull/2512.
