### ISSUE TITLE
Write OS specific setup in meson.build for support of non-standard library

### ISSUE THREAD

**Issue by Ron89** [mesonbuild/meson#2554]
Using meson.build with non-standard library require `find_library` with specified folder. Yet if cross platform is needed(build on Windows for Windows environment and build on Linux for Linux environment, etc), an OS conditioned folder specification is needed. Yet I couldn't find it in the documentation the function that return OS and architecture. Nor could I find the method for me to read environment variable. May I know if such function exist or not? Is it a must to use external command to get OS and Arch information?

**Comment by liugang** [comment]
https://github.com/mesonbuild/meson/blob/master/docs/markdown/Cross-compilation.md

**Comment by Ron89** [comment]
@liugang The link you post is about cross-compilation. It's not exactly what I was talking about. If the case I mentioned is "cross-compilation", it is the case that 'build machine' and 'host machine' is the same one, i.e. for both platform, the program is to be built in `native` way. Just that the dependency would be in different folder, which needs to be specified when build machine is determined. I need something like

```
if sys.OS() is 'Linux':
    if sys.Arch() is 'x86_64':
        ...
if sys.OS() is 'Windows':
    ...
```

**Comment by liugang** [comment]
https://github.com/mesonbuild/meson/blob/master/docs/markdown/Reference-manual.md

build_machine object

Provides information about the build machine — the machine that is doing the actual compilation. See Cross-compilation. It has the following methods:

cpu_family() returns the CPU family name. Guaranteed to return x86 for 32-bit userland on x86 CPUs, x86_64 for 64-bit userland on x86 CPUs, arm for 32-bit userland on all ARM CPUs, etc.

cpu() returns a more specific CPU name, such as i686, amd64, etc.

system() returns the operating system name, such as windows (all versions of Windows), linux (all Linux distros), darwin (all versions of OS X/macOS), cygwin (for Cygwin), and bsd (all *BSD OSes).

endian() returns big on big-endian systems and little on little-endian systems.

**Comment by Ron89** [comment]
So the platform information is encoded as methods of an object. I didn't notice `build_machine` is actually referring to the name of an object when reading the cross compilation article section.

Thanks~

**Comment by liugang** [comment]
you need call run_command() to run your own script to detect OS, or arch if build_machine is not  you want

**Comment by Ron89** [comment]
The object is what I want. It seems OS detection, environment variables are all well encapsulated as objects. I am reading in these sections.

On the other hand, writing commands for OS detection wouldn't be quite straightforward, as in, `cmd` syntax and `bash` syntax are way too different. I think they are better suited to execute environment specific commands.

Thanks again for your help. 👍
