### ISSUE TITLE
pot file generation only works with certain macro/wrapper formats _() vs D_() etc

### ISSUE THREAD

**Issue by wltjr** [mesonbuild/meson#2558]
I was porting a project from [autotools](https://github.com/thewaiter/Clipboard) to [meson](https://github.com/Obsidian-StudiosInc/clipboard). In the process I was having problems generating the pot file for the project. I had everything identical to another project. But the file was not being generated and took some time to discover why. Turns out it was due to the macro/wrapper. The project was using the following.
```c
define D_(string) dgettext(PACKAGE, string)
```

At first thought it was dgettext vs gettext. Turns out it was the D_ prefix that caused the issue. Soon as I [switched](https://github.com/Obsidian-StudiosInc/clipboard/commit/8657634d10b69e2aecdd4b4f24b3fc008eb3d3fe) from D_() to _() like in my other projects.
```c
define _(x) gettext(x)
```

Meson was able to generate the pot file. Not sure if its a bug per se. But the documentation did not mention such. Either should mention such on documents. Or adapt code to work with other macros/wrappers. Either is fine, just mentioning it in case others have not run into that yet.

**Comment by TingPing** [comment]
`i18n.gettext()` takes an `args` kwarg where you can set whatever custom flags you need.

**Comment by wltjr** [comment]
I am not sure what flags would be needed here. Maybe some not documented. I assumed the macro/pattern could be specified somehow. That may have been another route to go.

**Comment by TingPing** [comment]
The same args you passed to it in Autotools: https://github.com/thewaiter/Clipboard/blob/master/po/Makevars#L11

**Comment by wltjr** [comment]
Ah missed that, thanks!
