### ISSUE TITLE
custom_target creates target with wrong name (Ninja only ?)

### ISSUE THREAD

**Issue by Salamandar** [mesonbuild/meson#2559]
The current code:
```
custom_target('MyTarget', 
  input : 'my_input', 
  output: 'my_output', 
  command: [ 'touch', '@OUTPUT@', ]
)
```
should create a target called `MyTarget`. At least that's what the doc suggests.
It currently creates a target called `my_output`. 
It poses 2 problems: 

* we can't "customize" our targets
* we can't create "phony" targets (with zero outputs).

The bug seems to be here:
```
  File "/usr/lib/python3.6/site-packages/mesonbuild/backend/ninjabackend.py", line 2583, in generate_ending
    targetlist.append(os.path.join(self.get_target_dir(t), t.get_outputs()[0]))

```

That would probably fix #2517 .

**Comment by sarum9in** [comment]
> we can't create "phony" targets (with zero outputs).

Did you try [run_target()](http://mesonbuild.com/Reference-manual.html#run_target) instead?

What are you trying to do? If you want to introduce a dependency on `custom_target`, use [object](http://mesonbuild.com/Reference-manual.html#custom-target-object) that is returned by it.

**Comment by Salamandar** [comment]
> > we can't create "phony" targets (with zero outputs).
>
> Did you try run_target() instead?
Yeah for targets with zero outputs that obviously makes more sense. But that doesn't change that this target name is never "used" (as is I can't execute `ninja target_name`)

**Comment by sarum9in** [comment]
For this you need to create `run_target` with dummy command like `echo Building foobar` and add dependency on `custom_target`. It is documented [here](http://mesonbuild.com/Reference-manual.html#run_target). Closing. Please reopen if I missed something.
