### ISSUE TITLE
Conversion scripts in tools should use /usr/bin/env to call Python

### ISSUE THREAD

**Issue by eschnett** [mesonbuild/meson#256]
The conversion scripts in `tools` (`autotools2meson.py`, `cmake2meson.py`) call `/usr/bin/python3` directly. This does not work on OS X. I suggest using the `/usr/bin/env` mechanism instead that `meson` itself is already using.

**Comment by ignatenkobrain** [comment]
Yeah, it should do /usr/bin/env python3

On Fri, Sep 4, 2015, 5:14 AM Erik Schnetter <notifications@github.com>
wrote:

> The conversion scripts in tools (autotools2meson.py, cmake2meson.py) call
> /usr/bin/python3 directly. This does not work on OS X. I suggest using
> the /usr/bin/env mechanism instead that meson itself is already using.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mesonbuild/meson/issues/256>.
>
-- 

-Igor Gnatenko
