### ISSUE TITLE
How to handle Qt5 translations?

### ISSUE THREAD

**Issue by z3ntu** [mesonbuild/meson#2575]
In CMake there's a macro called `qt5_add_translation` which handles the conversion of `.ts` files to `.qm` files automatically (see eg [in sddm](https://github.com/sddm/sddm/blob/b78a49f03a265c73c41db31148d2e52f9c87604b/data/translations/CMakeLists.txt)).
I didn't find anything about how to handle translations properly in meson (except using GNU gettext).
Thanks.

**Comment by z3ntu** [comment]
I have created a custom target for getting it to work for now:
```
# Translations
languages = ['de']  # add new languages here!
translationsdir = join_paths(get_option('datadir'), 'razergenie/translations')
lrelease = find_program('lrelease')

foreach lang : languages
    custom_target('translation_' + lang,
        output : lang + '.qm',
        input : 'translations/'+lang+'.ts',
        command : [lrelease, '@INPUT@', '-qm', '@OUTPUT@'],
        install : true,
        install_dir : translationsdir)
endforeach
```

**Comment by jeandet** [comment]
@z3ntu thank, for reporting this. I'll make a PR to integrate this in Qt module.

**Comment by z3ntu** [comment]
Thanks!
