### ISSUE TITLE
'Sandbox Violation: Tried to grab file X.cxx from a different subproject' In same directory

### ISSUE THREAD

**Issue by XAMPP** [mesonbuild/meson#2582]
I'm not 100% that this not just a bug on my end, but I seem to have run into an issue where meson will refuse to add a source file in the same directory as the `meson.build` file.

The rough structure of the project is like this
```
- /
- meson.build
- bootstrap/
- - meson.build
- - <srcs>
- - platform/
- - - linux/
- - - - 64/
- - - - - meson.build
- - - - - <srcs>
- - - - 32/
- - - - - <same as 64>
```
So in the case of platform/linux/[64/32]/meson.build it will complain that the src files are out of scope. 

I've got no idea why it's doing this, too many subprojects maybe?

**Comment by anordal** [comment]
Can you reproduce #2465? Same error message.

**Comment by XAMPP** [comment]
Hi,

I'm running version 0.43.0 of meson and I do indeed get the same error:
```
Meson encountered an error in file subprojects/zlib-1.2.8/meson.build, line 7, column 0:
Sandbox violation: Tried to grab file adler32.c from a different subproject.
```

**Comment by liugang** [comment]
latest dev has fixed this issue, it will be resolved in next release
