### ISSUE TITLE
Configure file doesn't write defines

### ISSUE THREAD

**Issue by SloCompTech** [mesonbuild/meson#2587]
Hi,
I found error in process of generating configure file. I was trying to get 
``` c++
#define HAS_I2C
```
in configure file so I set up in `meson.build` file:
``` meson
conf_file = configuration_data()
if has_i2c
  conf_file.set('HAS_I2C',true)
  message('I2C feature is enabled')
else
  conf_file.set('HAS_I2C',false)
  message('I2C feature is DISABLED')
endif
configure_file(input : 'config.hpp.in',
               output : 'config.hpp',
               configuration : conf_file)
```
but in either case I don't get define in generated config file.
Have I done something wrong or is this a bug ? In console message is written, but configure file is not generated properly.

Any help appreciated :)

**Comment by jpakkane** [comment]
Does `config.hpp.in` contain the appropriate `#mesondefine HAS_I2C`?

Also, if you just want to serialise out every setting in `conf_file`, leave out the input file. Meson will create one from scratch.

**Comment by SloCompTech** [comment]
Oh, probably I missed that, I will give it a try and report

**Comment by SloCompTech** [comment]
Yes, it works, thanks :)
