### ISSUE TITLE
Overriding boolean variable value doesn't trigger an error

### ISSUE THREAD

**Issue by swilmet** [mesonbuild/meson#2606]
I thought that the variables were immutable.

I've tested this:
- In the root meson.build, have a bool variable.
- Override the value of the bool variable in a subdir meson.build.
- Use that bool variable in a condition in the same subdir meson.build.

What I would expect:
An error when running meson, variables are supposed to be immutable.

What I get instead:
The condition in the subdir meson.build uses the new value.

**Comment by jpakkane** [comment]
Objects are immutable, not variables. You can reassign them.

**Comment by swilmet** [comment]
This is not what I've understood when reading:

> One important difference in how variables work in Meson is that all variables are immutable.

http://mesonbuild.com/Syntax.html

I think it was also explained a bit before in the manual, in a previous chapter.

**Comment by nirbheek** [comment]
```meson
var1 = true
var2 = var1
var2 = false
assert(var1 == true, 'oh no')
```

This does not assert. Everything seems fine to me.

**Comment by swilmet** [comment]
There is a difference between:
- an immutable object;
- an immutable variable.

With Meson it is the former, while the documentation explains the latter. With an immutable *variable*, there can be at most one value assignment, some functional languages work like this. With an immutable *object*, it is the value which is immutable, but the variable can be re-assigned a different value.

**Comment by QuLogic** [comment]
It's a variable because it can _vary_; an immutable variable with the meaning you describe does not make sense. What you describe is a constant.

In any case, the Meson documentation uses "object" in all cases except for the `foreach` statement; this should probably be changed to match the rest.

**Comment by swilmet** [comment]
In functional languages (or multi-paradigms languages) which support by default only one assignment, the “thing” that stores the value is still called a variable, even though it cannot really vary (apart from being unassigned -> assigned). My book reference on the subject is:
http://www.e-booksdirectory.com/details.php?ebook=1085
And I've checked, the term used is “variable” even for something that can have at most one value assignment.
