### ISSUE TITLE
Cannot use boost in non-default directory

### ISSUE THREAD

**Issue by germandiagogomez** [mesonbuild/meson#261]
Hello,

I am facing a problem converting a package of my own from autotools to meson.
The problem is that boost is in a non-standard directory and I cannot figure out how to make it work.

I have something like the following:

    boost_dep = dependency('boost', modules : ['serialization'])
    boost_test_dep = dependency('boost', modules: ['test'])

    libmylib = static_library('mylib', 'source.cpp', dependencies: boost_dep)

    myexe = executable('testmylib', dependencies: boost_test_dep, link_with: libmylib)

    test(...)

What happens here is that boost is installed in a non-default directory, so, I need to give the `include_directories` to the boost headers. This will provoke boost headers to be found and, hence, detection working when building, but no libs for linking are found, because they do not live in a standard directory.
Module detection assumes that libraries are header only.

- I could not find a way to give the BOOST_ROOT to the dependency. Is there a way to do it?
- Is there a way to modify the library search path so that libraries are properly found and linked?

Because the libraries, even when giving include_directories, are not linked because they are not found in the standard search paths.

**Comment by germandiagogomez** [comment]
So I tried to use `BOOST_ROOT` environment variable:

    BOOST_ROOT=/usr/local/Cellar/boost/1.55.0 meson ..

Still does not detect the libs. Maybe homebrew is using a custom layout for the boost libraries? It looks like this:

    1.55.0/
        include/
        lib/

Any ideas?

**Comment by jpakkane** [comment]
Boost is a pain to support because they don't provide pkg-config files. Thus every Boost installation type needs to be specified by hand and this has not been done for homebrew. Could you please write the absolute full path to the Boost thread main header file and to the boost thread shared library?

For even more help, please check out Meson from git and try to run the unit test for boost with BOOST_ROOT set properly. Then get `meson-logs/meson-log.txt` and attach it here. Thanks,

**Comment by germandiagogomez** [comment]
Hello @jpakkane,

No need anymore. The problem was that it is looking for .so files in unix (not .dylib). I corrected that. I will send a pull request soon.

**Comment by germandiagogomez** [comment]
The pull request is here: https://github.com/mesonbuild/meson/pull/262
