### ISSUE TITLE
Overriding default_options in subproject does nothing

### ISSUE THREAD

**Issue by jibsen** [mesonbuild/meson#2612]
I may have misunderstood how it works, but I was expecting the `default_options` argument to `subproject()` and `dependency()` to override the default options in the subproject, but I can't get it to work.

I have a project foo:
~~~Meson
project('foo', 'c')
message('build type is ' + get_option('default_library'))
message('warning level is ' + get_option('warning_level'))
bar_dep = dependency('bar',
  default_options : [ 'default_library=static', 'warning_level=3' ],
  fallback : ['bar', 'bar_dep']
)
executable('foo', 'foo.c', dependencies : bar_dep)
~~~
And a subproject bar:
~~~Meson
project('bar', 'c')
message('build type is ' + get_option('default_library'))
message('warning level is ' + get_option('warning_level'))
lib = library('bar', 'bar.c')
bar_dep = declare_dependency(link_with : lib)
~~~

When I run meson it prints build type shared and warning level 1 for both projects (and building creates a shared library bar).

This issue was mentioned in #2289.

**Comment by jpakkane** [comment]
In Meson you can never, ever change the value of existing options inside your build files. You can only specify a new default value for options that do not exist yet. Global options are shared for all projects. When a subproject is called, the option already exists and has a value, thus it can not be changed.

Default _options for subprojects can only provide values for project options, not global options.

**Comment by jibsen** [comment]
I see, thanks. Perhaps the reference manual for [dependency()](http://mesonbuild.com/Reference-manual.html#dependency) needs updating?
> `default_options` _(added 0.37.0)_ an array of option values that override those set in the project's `default_options` invocation (like `default_options` in `project()`, they only have effect when Meson is run for the first time, and command line arguments override any default options in build files)

If it can only change project options, how about calling it `project_options` or `project_default_options`?

If it cannot change global options, perhaps an error or warning when trying to would be helpful.

**Comment by jasonszang** [comment]
Perhaps subproject default option should be allowed to override master project default option but not options set with meson conf? This should provide some more flexible control over compilation of external subprojects that does not go well with master project default options.

**Comment by jibsen** [comment]
For the `default_library` case, this is what I've come up with so far:
~~~Meson
# In meson_options.txt
option('lib_type',
  type : 'combo',
  choices : ['default', 'shared', 'static'],
  value : 'default',
  description : 'Library type (default uses default_library)'
)

# In meson.build
lib_type = get_option('lib_type')
if lib_type == 'default'
  lib_type = get_option('default_library')
endif
~~~

This defaults to the current situation, and if `lib_type` is set through configure (as `mysubproj:lib_type`) or with the `default_options` argument to `dependency()`, it can be used to override the global `default_library`.

For `warning_level` and `werror` I don't think there is an easy workaround.

Btw, what is the correct name for the options in `meson_options.txt`? In the command-line help they're called _project options_, while in the [manual](http://mesonbuild.com/Build-options.html) they're called _build options_. The manual also talks about _built-in project options_, which I guess is what you call _global options_? The command-line help also lists _core options_ and _base options_. Sorry about all the questions, but being new to meson I am easily confused.

On a side note, nice to find there is syntax highlighting for meson here!

**Comment by ericwomer** [comment]
> In Meson you can never, ever change the value of existing options inside your build files. You can only specify a new default value for options that do not exist yet. Global options are shared for all projects. When a subproject is called, the option already exists and has a value, thus it can not be changed.
> 
> Default _options for subprojects can only provide values for project options, not global options.

Sadly I think this is one of meson's drawbacks to have the options hard tied between a project and subproject, or even have separate projects initiated by a root meson.build but have different options per project/subproject, especially when the default options override the [lang]_args and link_args in the executable function. The only clean way to handle this is to wrap the meson build setup in a Makefile or some other script.
