### ISSUE TITLE
Could run_target() have a run_by_default option?

### ISSUE THREAD

**Issue by jibsen** [mesonbuild/meson#2626]
Like `custom_target()` has a `build_by_default`, it would be nice if `run_target()` had an option to run the command by default.

My use case is I have a tool to post-process a target in place. Since `custom_target()` requires an output file, I cannot use that.

Alternatively, support for phony targets with `custom_target()` (#2517) could also work.

**Comment by jpakkane** [comment]
That's not really how run_targets are supposed to work, they are meant for manual shortcuts for stuff like running clang-format.

Any tool that does only does in-place processing is broken and difficult to integrate with a reasonable toolchain. You should file a bug to the tool vendor to properly support a `-o` option (in some backends this is really difficult to retrofit). In the mean time you can work around this by writing your own script that takes as argument the created executable, copies it to a new name (the output) and then runs the actual tool on that.

**Comment by jibsen** [comment]
Thanks, I'll try that.
