### ISSUE TITLE
clang's linker doesn't like -pthread

### ISSUE THREAD

**Issue by mojca** [mesonbuild/meson#2628]
There is already #2118, but I'm not sure if this is the same issue.

When I include `googletest` which requests `pthreads`, the compiler complains:
```
clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
```

The command used to compile is:

```
 c++  -o test/unittest/simpletest 'test/unittest/simpletest@exe/simpletest.cpp.o' 'test/unittest/simpletest@exe/.._.._subprojects_googletest-release-1.8.0_googletest_src_gtest-all.cc.o' 'test/unittest/simpletest@exe/.._.._subprojects_googletest-release-1.8.0_googletest_src_gtest_main.cc.o' src/mylib.a -pthread
```
and there are no duplicate entries of `-pthread`.

Note that this is a super low priority issue (it's just a warning after all).

See https://stackoverflow.com/a/19382663/585897

**Comment by dcbaker** [comment]
This only applies to Apple's clang, right? I've seen this working on macOS, but I don't remember seeing it on Linux.

**Comment by mojca** [comment]
Strange. Now that you mentioned it I tried two compilers, the native `clang` that's shipped by the system, and version 5.0 as compiled by MacPorts. Only the one which comes with the system complains, the other one does not.

But just to confirm once again:
* `clang[++] -pthread hello.c[pp] -o hello` OK
* `clang[++] -pthread hello.o -o hello` complains because this only calls linker
* `clang[++]-mp-5.0 -pthread hello.c[pp] -o hello` OK
* `clang[++]-mp-5.0 -pthread hello.o -o hello` OK

**Comment by nirbheek** [comment]
I believe clang is wrong here, according to `man gcc`:

```
-pthread
    Define additional macros required for using the POSIX threads library. 
    You should use this option consistently for both compilation and linking.
    This option is supported on GNU/Linux targets, most other Unix derivatives,
    and also on x86 Cygwin and MinGW targets.
```

However ff clang does not require `-pthread` during linking, then we can filter it out.

**Comment by mojca** [comment]
@jeremyhu, do you perhaps have any idea about why clang is throwing warnings for `-pthread` when used just for linking? But in particular, why only the one shipped by macOS does that, while the one compiled by MacPorts doesn't complain at all? And how this compares to `gcc` and the behaviour of `clang` on FreeBSD or Linux?

**Comment by mqudsi** [comment]
clang 7 under Linux similarly complains. Isn't the version that ships with macOS rather old?

@nirbheek I must be missing something, because I don't see how quoting the *gcc* man page could show that *clang* is wrong.

**Comment by nirbheek** [comment]
> @nirbheek I must be missing something, because I don't see how quoting the gcc man page could show that clang is wrong.

Well, if clang has decided to stop being compatible with gcc w.r.t. the `-pthread` flag, then we can change things.

If you could figure out which version of clang changed this, the fix is trivial.

**Comment by franko** [comment]
I have exactly the same problem using clang provided by Msys2, the mingw-w64 version.

```
clang++: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
```

The meson version I am using is 0.51.1. The clang version is:

```
clang version 8.0.1 (tags/RELEASE_801/final)
Target: i686-w64-windows-gnu
Thread model: posix
InstalledDir: C:\msys64\mingw32\bin
```

I guess this fix should not be restricted ot Mac OS X.
