### ISSUE TITLE
Support variable as a path argument to run_target

### ISSUE THREAD

**Issue by Maratyszcza** [mesonbuild/meson#264]
I have a Meson script that tries to run compiled executable through `run_target` command:

```python
project('demo', 'c')
demo = executable('demo', 'main.c')
run_target('demo', demo)
```

I get an error:

```
$ meson build
The Meson build system
Version: 0.26.0-research
Source dir: /Users/marat/Projects/meson-test
Build dir: /Users/marat/Projects/meson-test/build
Build type: native build
Build machine cpu: x86_64
Project name: demo
Native c compiler: ccache cc (clang 6.1.0)

Meson encountered an error in file meson.build, line 3, column 0:
Arguments must be strings.
```

I seems reasonable to support variables as an argument to `run_target` because it may be necessary to execute the compiled binary through a wrapper when doing cross-compilation.

**Comment by Maratyszcza** [comment]
Thank you for the fix. However, when I try to use the rule in cross-compilation environment, I get error on https://github.com/mesonbuild/meson/blob/master/ninjabackend.py#L334:

```
Traceback (most recent call last):
  File "/usr/local/bin/meson", line 208, in run
    app.generate()
  File "/usr/local/bin/meson", line 161, in generate
    g.generate()
  File "/usr/local/share/meson/ninjabackend.py", line 130, in generate
    [self.generate_target(t, outfile) for t in self.build.get_targets().values()]
  File "/usr/local/share/meson/ninjabackend.py", line 130, in <listcomp>
    [self.generate_target(t, outfile) for t in self.build.get_targets().values()]
  File "/usr/local/share/meson/ninjabackend.py", line 164, in generate_target
    self.generate_run_target(target, outfile)
  File "/usr/local/share/meson/ninjabackend.py", line 334, in generate_run_target
    and wrapper is not self.environment.cross_info.config['binaries'].get('exe_wrapper', None):
NameError: name 'wrapper' is not defined
```

**Comment by Maratyszcza** [comment]
Thanks, now now Meson does generate the Ninja build file. However, it still doesn't work, due to two problems:

1. If I use the `meson.build` file above, the generated `build.ninja` has two `demo` targets: one to build executable and another to run it. As a result, Ninja always builds the executable, and never executes it (it also prints a warning about duplicate targets). However, the meson didn't print any warning.

2. If I change the name of the target to `run`, the build still doesn't work with Native Client's `sel_ldr.py` exe_wrapper. `sel_ldr.py` interprets the filename of the executable in the same way as shell: if executed as `sel_ldr.py demo` it will look the `demo` binary in the `$PATH`. To run the `demo` binary from the working directory, it must be executed as `sel_ldr.py ./demo`, but unfortunately Meson generates the first variant.

**Comment by jpakkane** [comment]
Should be fixed now.

**Comment by Maratyszcza** [comment]
Thank you. Can confirm it all works now
