### ISSUE TITLE
appveyor sample in the docs is broken

### ISSUE THREAD

**Issue by z3ntu** [mesonbuild/meson#2641]
The embedded yml on `docs/markdown/Continuous-Integration.md` fails to parse on appveyor (try on https://ci.appveyor.com/tools/validate-yaml)

* download link mentioned is dead (404)
* build matrix is broken
* I think the line with `pip` requires single quotes around the whole command to parse
* and more

**Comment by z3ntu** [comment]
When I copy-paste this into a project, I get the error `Error parsing appveyor.yml: (Line: 20, Col: 10, Idx: 613) - (Line: 20, Col: 11, Idx: 614): While scanning for the next token, find character that cannot start any token.` in the appveyor build.

When making that line to a `cmd: echo Using Python at "%MESON_PYTHON_PATH%"` (added double quotes), it results in a download exception of ninja.exe, because the path doesn't exist (it should be mentioned that the C:\projects\PROJECTNAME path is created and the sample uses "meson" as PROJECTNAME; unfortunately powershell exceptions on appveyor are worthless).

And then after that's fixed, it doesn't find `pip` at `%MESON_PYTHON_PATH%\pip`. This is where I'm stuck unfortunately as I've never used appveyor before and don't know how to install pip properly (or if it should be automatically)

**Comment by jpakkane** [comment]
When you install Python, it asks you if you wish to install pip as well.

**Comment by z3ntu** [comment]
I found that pip is located at `%MESON_PYTHON_PATH%\\Scripts\\pip` and not in the root python folder.
