### ISSUE TITLE
Add special-case dependency for zlib

### ISSUE THREAD

**Issue by dmacks** [mesonbuild/meson#2654]
Apple supplies libz as part of its core OS (/usr/lib/libz*.dylib, /usr/include/zlib.h) but does not supply a pkgconfig file for it. As a result, a package that has a meson.build assertion `dependency('zlib')` fails, or falls back to downloading and building libz from source if the package includes its own .wrap file for it. Apple has been doing this for the entire history of zlib in OS X and doesn't seem inclined to change. It would therefore be useful if meson supplied a special case for this library, analogous to other cases that don't supply pkgconfig files. Presumably this would go in one of the mesonbuild/dependencies, I guess misc.py (like pcap and cups)? If this would be generally useful, let me know and I can have a go at writing a patch.

**Comment by jpakkane** [comment]
Are there other libraries that should be treated in the same way?

**Comment by dmacks** [comment]
I have no idea (I do not have a linux box to compare my /usr/lib/lib*.dylib and /usr/lib/pkgconfig). From googling, the zlib case appears not to be solely an OS X situation (so misc.py not platform.py?). By randomly comparing fink's and Apple's versions, i suspect also libexpat, libxml2, libxslt, liblzma, the libicu suite, and probably many more "have lib*.dylib but no .pc via Apple but probably do have .pc in the original sources"

**Comment by nirbheek** [comment]
It would also be useful to do a `cc.find_library('z')` as part of the dependency implementation since some distros ship `libz.so` but don't ship a pkg-config file.

**Comment by lantw44** [comment]
It would be nice if we can also make a special case for OpenSSL (openssl.pc, libssl.pc, libcrypto.pc) on FreeBSD. FreeBSD has OpenSSL installed in base, but .pc files are not available.

FreeBSD has zlib.pc since a few years ago because of the request from GNOME. I remember that there was plan to make OpenSSL a private library on FreeBSD, but it seems that it is not going to happen anytime soon.

**Comment by xclaesse** [comment]
I'm wondering if we could have some form of fallback chain in `dependency()`. Something like:

```meson
dependency(
  [
    'zlib',
    'another-zlib-pkgconfig-name',
    {
      'language': 'c',
      'library': ['z', 'zlib', 'zlib1', 'inflate'],
      'header': 'zlib.h'
    },
    {
      'subproject' : 'zlib',
      'variable' : 'zlib_dep'
    },
  ],
  required : true,
)
```
