### ISSUE TITLE
Feature request: get_option('libdir') to return libdir

### ISSUE THREAD

**Issue by krogueintel** [mesonbuild/meson#2658]
I can get the prefix and bindir, with get_option(), but not the libdir. Tried with meson 0.43.0. (Linux)

**Comment by TingPing** [comment]
That already works.

**Comment by krogueintel** [comment]
i.e. you mean from git master? but not yet as a release?

**Comment by TingPing** [comment]
It has worked for many releases.

**Comment by krogueintel** [comment]
Now I understand the issue: the value of get_option('libdir') is the directory without the prefix. Sorry for the mistake.

**Comment by TingPing** [comment]
It *may* have the prefix if a user passes `--libdir=/foo/bar`, use `join_paths()` to join the prefix and libdir if an absolute path is needed.

**Comment by nirbheek** [comment]
No, `get_option('libdir')` will *always* return the path relative to prefix. The behaviour you are talking about was the case almost a year ago, but I changed it so we have consistent values returned.
