### ISSUE TITLE
Meson is trying to build against 'somelib.dll' instead of 'somelib.lib'

### ISSUE THREAD

**Issue by mojca** [mesonbuild/meson#2659]
I'm reporting a regression that happened some time between release 0.43.0 and commit 05ee756ba045e6b298951bd00a0e4b0c5ec46150 (this is the only one I tested so far and noticed a problem, I didn't do any bisection yet).

When doing a cross-compilation from Mac to Windows with MinGW's gcc 7.2, I started getting these warnings after the upgrade:
```
Warning: resolving _Foo@12 by linking to _Foo
Use --enable-stdcall-fixup to disable these warnings
Use --disable-stdcall-fixup to disable these fixups
```

I'm using the following code to find the library:
```
my_dep = meson.get_compiler('cpp').find_library('mylib', dirs : meson.current_source_dir())
```

It turns out that the old meson would generate this call for ninja:
```
/opt/local/bin/i686-w64-mingw32-g++ -o test/hello.exe 'test/hello@exe/hello.cpp.obj' -static-libgcc -static-libstdc++ -Wl,--start-group src/libThisLib.a /path/to/mylib.lib -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 -Wl,--end-group
```
while the new one generates:
```
/opt/local/bin/i686-w64-mingw32-g++ -o test/hello.exe 'test/hello@exe/hello.cpp.obj' -static-libgcc -static-libstdc++ -Wl,--start-group src/libThisLib.a /path/to/mylib.dll -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 -Wl,--end-group
```
the difference being `mylib.lib` vs. `mylib.dll`.

I'm using a third-party library that ships a header file, a `dll` and a `lib` file. I assume it was written primarily for Visual Studio.

See also https://stackoverflow.com/a/8104077/585897

**Comment by mojca** [comment]
See also #2611

**Comment by nirbheek** [comment]
The order needs to be changed here: https://github.com/mesonbuild/meson/blob/master/mesonbuild/compilers/c.py#L730, that'll fix it.

**Comment by mojca** [comment]
Indeed. If I put `lib` first, the problem is gone.

I don't know what other implications the change might have, but it looks like writing a simple test case for this would be beneficial for the future changes. What I don't know is how to properly create a test case which starts with a set of binary lib/dll files (of course adding sources and meson instructions for building them) and how to only execute that test when a cross-compiler is present.

**Comment by mojca** [comment]
@nirbheek: can you please commit the fix? Or should I open a PR?

**Comment by nirbheek** [comment]
https://github.com/mesonbuild/meson/pull/2703
