### ISSUE TITLE
add install_mode to custom_target() or something to say it is an executable on install

### ISSUE THREAD

**Issue by krogueintel** [mesonbuild/meson#2665]
For the simple case of generating a shell script and installing it, I have been using custom_target() with sed. However, custom_target() does not have an option to declare that the ouput is an executable, inspite that it does have install and install_dir options. I think it would be quite useful to have an option to declare that the value is an executable or an option to specify its install_mode.

**Comment by eli-schwartz** [comment]
Implemented by now.

https://mesonbuild.com/Reference-manual.html#custom_target
>  install_mode (since 0.47.0): the file mode and optionally the owner/uid and group/gid
