### ISSUE TITLE
Escaping '@'

### ISSUE THREAD

**Issue by jibsen** [mesonbuild/meson#2667]
Meson is using `@` characters to identify template strings that can be replaced at various places (string formatting, configuration, various kwargs). In the source that handles configuration, there is an attempt to allow escaping, but as far as I can tell it does nothing:

https://github.com/mesonbuild/meson/blob/d5a6ab31bfbcec9838805c598be75abb036aff87/mesonbuild/mesonlib.py#L446

I think I fixed that in #2648, but it got me wondering about the escaping. In the case of configuration files, should the escape character not be removed as the file is processed?

Should escaping be added to the other places where template strings are used?

How do you escape the escape character if you need that?

**Comment by jibsen** [comment]
I thought I'd try to describe the current situation:

### String format

Replace `@n@` with argument number `n`. Handled by [`format_string()`](https://github.com/mesonbuild/meson/blob/d882b6fbd466940d452cfaa890bd9270e10a93b4/mesonbuild/interpreter.py#L2983).

No way to escape, but I imagine it is rare people need to write strings containing literal `@0@`. If `n` is larger than the number of arguments it is ignored. Unused arguments are ignored. Replace order depends on argument order (in `@1@0@` argument 0 is replaced first). Can result in recursive replace (#2653).

### Configuration

Replace `@id@` with configuration data value for `id`. Handled by [`do_replacement()`](https://github.com/mesonbuild/meson/blob/d882b6fbd466940d452cfaa890bd9270e10a93b4/mesonbuild/mesonlib.py#L405).

Since #2648, the template sequence can be escaped with `\@id@`, but the `\` is copied to the output, and there is no way to escape the escape character. Unknown templates in the input file are reported and replaced with the empty string. Replace order is left-to-right.

### Custom command kwargs

Replace specific template strings (`@INPUT@`, `@BASENAME@` and such). Handled by [`substitute_values()`](https://github.com/mesonbuild/meson/blob/d882b6fbd466940d452cfaa890bd9270e10a93b4/mesonbuild/mesonlib.py#L696)

No way to escape, but fixed format of template string, so unlikely needing to pass them literally as arguments to a custom command. Replace order depends on order in dict. Highly theoretical possibility for recursive replace (#2638).

### Thoughts

I think the configuration is probably the place most likely to need escaping. The user could need to have all kinds of stuff in the input file, and the template format is loose enough it could match something in the input file which is then replaced with the empty string.

Having to escape `\` in general could lead to LTS, so perhaps only handle it as an escape before `@`? Another choice would be to ignore the issue, I don't know how often it would come up.

For the other two, the template format is perhaps rare enough that it is not needed to be able to escape it?

It might be nice if replace order was consistent left-to-right.

**Comment by nirbheek** [comment]
Fixed in https://github.com/mesonbuild/meson/pull/2679. In the future please add a line like "Closes #issuenumber" to the commit message so this happens automatically.
