### ISSUE TITLE
Target’s dependencies should match the build type 

### ISSUE THREAD

**Issue by marioux** [mesonbuild/meson#267]
I took the test case number 62 and modified meson.build with

    exe = executable('prog', 'prog.c', link_with : statlib, native : true)    

I then ran meson with ```meson . build --cross-file=cross/ubuntu-mingw.txt```

And ninja failed with

    FAILED: cc    -o prog.exe 'prog@exe/prog.c.obj' 'stat.lib' 'subdir/shar.dll' 'subdir/shar.dll' '-Wl,-rpath,/home/marioux/bin/meson-git/test cases/common/62 exe static shared/build/subdir'

I was expecting Meson to match the build type of the dependencies to the target (so, if B depends on A, by default that means that a target build of B depends on a target build of A)

Also, it tried to name the executable ```prog.exe``` instead of the convention for the native platform, ```prog```.

**Comment by jpakkane** [comment]
The build types do not get matched automatically by type, you have to be explicit. If it's not noticing that it's linking the wrong type then we need to add a check for that. It should print a message and error out if you try to link native and non-native code in the same target.

**Comment by marioux** [comment]
So if I want to build the same shared or static library for both the target and the host I have to declare the target twice? Or do you have another way of achieving this.

Based on test 62 again, it would look like
meson.build
```
project('statchain', 'c')

subdir('subdir')
statlib = static_library('stat', 'stat.c', link_with : shlib)
exe = executable('prog', 'prog.c', link_with : statlib)
test('runtest', exe)

statlib_native = static_library('stat_native', 'stat.c', link_with : shlib_native, native : true)
exe_native  = executable('prog_native', 'prog.c', link_with : statlib_native, native : true)
test('runtest', exe_native)
```
subdir/meson.build
```
shlib = shared_library('shar', 'shlib.c')
shlib_native = shared_library('shar_native', 'shlib.c', native : true)
```

The output executable are named ```prog.exe``` and ```prog_native.exe```

**Comment by jpakkane** [comment]
Yes, you do need to declare it twice. Added a check that errors out when you try to mix native and cross code.
