### ISSUE TITLE
Add support for JSON depfiles

### ISSUE THREAD

**Issue by lamefun** [mesonbuild/meson#2671]
JSON is the universal data format and I haven't found any pre-made parsers or generators for Make-style depfiles.

**Comment by nirbheek** [comment]
Not sure I understand this issue. Do you have a specific tool that outputs depfiles in JSON? And if so, what is the format for the dependency information? Almost all compilers (gcc, clang, icc, rustc, etc) output make-style depfiles and the format is self-explanatory.

In any case, depfiles are passed directly to Ninja so you would have to file a feature request there. Meson does not parse depfiles at all.
