### ISSUE TITLE
Enhancement: allow module methods to return arbitrary objects

### ISSUE THREAD

**Issue by MathieuDuponchelle** [mesonbuild/meson#268]
Currently they can only return build.CustomTarget or build.GeneratedList, as per the code in interpreter.py around L859

**Comment by nirbheek** [comment]
This can be changed as and when required by a module. Closing.

**Comment by MathieuDuponchelle** [comment]
@nirbheek , a little more info on that would be nice, I can't remember why I filed that, but I'm pretty sure I wouldn't have been happy with that answer at the time ^^

**Comment by tp-m** [comment]
I think it means that this can be changed as and when someone needs that when they implement and submit a new module, and until then it's an internal implementation detail and there's no need to change anything or keep this bug open :)

**Comment by nirbheek** [comment]
Couldn't have said it better myself, thanks Tim :)

**Comment by MathieuDuponchelle** [comment]
If that's your maintaining policy, so be it, but I'm pretty sure I remember filing this after discussing with @jpakkane , in order for the enhancement request not to be forgotten, anyway ¯\_(ツ)_/¯

**Comment by TingPing** [comment]
Well as an example I needed more to be handled for #895 so It was just added as part of that PR. Since modules are all in-tree what little module API there is is flexible to the needs at the time.
