### ISSUE TITLE
Meson doesn't link libgfortran when linking Fortran together with C++

### ISSUE THREAD

**Issue by cschwan** [mesonbuild/meson#2685]
I get the following linker error:

    cschwan@cschwan-laptop ~/projects/mwe-cpp-fortran-meson/build $ ninja -v
    [1/3] gfortran  -Iexe@exe -I. -I.. -pipe -Wall -O0 -g -Jexe@exe  -o 'exe@exe/fortran.f.o' -c ../fortran.f
    [2/3] c++  -Iexe@exe -I. -I.. -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -O0 -g -MMD -MQ 'exe@exe/main.cpp.o' -MF 'exe@exe/main.cpp.o.d' -o 'exe@exe/main.cpp.o' -c ../main.cpp
    [3/3] c++  -o exe 'exe@exe/main.cpp.o' 'exe@exe/fortran.f.o' -Wl,--no-undefined -Wl,--as-needed  
    FAILED: exe 
    c++  -o exe 'exe@exe/main.cpp.o' 'exe@exe/fortran.f.o' -Wl,--no-undefined -Wl,--as-needed  
    exe@exe/fortran.f.o: In function `fortran':
    /home/cschwan/projects/mwe-cpp-fortran-meson/build/../fortran.f:4: undefined reference to `_gfortran_rand'
    collect2: error: ld returned 1 exit status
    ninja: build stopped: subcommand failed.

with this minimal working example: [mwe-cpp-fortran-meson.tar.gz](https://github.com/mesonbuild/meson/files/1502664/mwe-cpp-fortran-meson.tar.gz)

The program is basically the following callchain: `main` (written in C++) calls `fortran` (written in Fortran) calls `rand` (in the Fortran runtime library). Because the C++ linker is used to link everything together, `libgfortran` is not linked which leads to the linker error. Manually linking `libgfortran` circumvents the problem, but this specific to GCC, of course. Meson should figure out all the runtime libraries and link against them.

**Comment by nirbheek** [comment]
The way to fix this would be to add gfortran to the linker arguments when detecting the linker in `mesonbuild/build.py:BuildTarget.process_compilers_late()`. See also `get_clike_dynamic_linker()` on the same object.

**Comment by cschwan** [comment]
I think I might attempt to write a fix myself if noone is interested. However, I am uncertain how to fix this bug. The following is an easy workaround:

    fortran = meson.get_compiler('cpp').find_library('gfortran')

But that assumes that I am using GCC's Fortran compiler. Do you have any idea how to find out that library name in general?

**Comment by jpakkane** [comment]
How does this work when doing it by hand? Which linker is being used and what args is it given to find the other language's libraries?

**Comment by cschwan** [comment]
That was basically my question. For my case I noticed that the example failed to find the function `_gfortran_rand`. Then I just happened to know that this function is in `libgfortran` (which is not really an algorithm one can implement, of course).

**Comment by cschwan** [comment]
With autotools one can use the macro `AC_FC_LIBRARY_LDFLAGS`, which one can find [here](http://git.savannah.gnu.org/cgit/autoconf.git/tree/lib/autoconf/fortran.m4). Maybe this is helpful.

**Comment by cschwan** [comment]
I had a closer look into the autotools macro and it basically does the following:

1. First, it tries to figure out the "verbose" mode of the compiler, meaning how to get the compiler to print what command line parameters it actually selects. For the GCC installed on my box, this is the switch `-v`. Autoconf also tries (in that order) `-verbose`, `--verbose` (Lahey compilers), `-V` (XL Fortran), and `-###` (Fujitsu). The switch that makes the compiler exit without an error is used.
2. Then an empty program is compiled, using the "verbose" switch; stdout/stderr is parsed where a or more calls to sed throws away all lines that contain compiler/linker switches that must not be considered.
3. The remaining switches are run through a filter. The result is `-lgfortran -lm -lquadmath`.
