### ISSUE TITLE
invalid SSL certifate on web http://mesonbuild.com/

### ISSUE THREAD

**Issue by ondratu** [mesonbuild/meson#2694]
mesonbuild.com use certificates for: *.github.com, github.com, *.github.io, github.io

**Comment by jpakkane** [comment]
That is how Github pages has set it up. I don't think there's anything we can do about it except wait for them to finally get letsencrypt working or switch hosting providers.

**Comment by sarum9in** [comment]
https://gist.github.com/cvan/8630f847f579f90e0c014dc5199c337b

We could set up cloudflare reverse proxy if we absolutely want HTTPS. Not sure if it is worth and if meson is eligible for free tier.

**Comment by eli-schwartz** [comment]
Now working...
