### ISSUE TITLE
meson test -C builddir does not chdir before running tests

### ISSUE THREAD

**Issue by dcbaker** [mesonbuild/meson#2710]
This means that if there are tests that need to be passed filesystem arguments they will fail, since those arguments will be relative builddir.

This is rather suprising since `ninja -C builddir` does chdir before running tests (since ninja does the chdir).

**Comment by polarina** [comment]
You can pass the `workdir` option to `test()` to specify the working directory for that test: http://mesonbuild.com/Reference-manual.html#test

**Comment by dcbaker** [comment]
Which is nice and I'll probably use, thanks for pointing that out. I still think its suprising that `ninja -C builddir` and `meson test -C builddir` do different things.
