### ISSUE TITLE
Linking static library into shared library : use -Wl,--whole-archive 

### ISSUE THREAD

**Issue by Salamandar** [mesonbuild/meson#2715]
When linking (multiple) static_libraries into a shared_library, symbols from the static_libraries **are not visible** from the outside.
If `my_lib/my_sublib/my_sublib.a` is linked into `my_lib/my_lib.so`, referencing `my_sublib` will throw undefined references at link time…

The best way to fix that is to add (at shared_library link-time):
```
-Wl,--whole-archive all_the_static_libs.a -Wl,--no-whole-archive
```
Unfortunately Meson doesn't allow users to add such flags…

Usually, static_libraries are the best mean to regroup source files (as long as object libs aren't a thing, #621). But right now, the only workaround is passing the source files list to the shared_library. Not great.

**Comment by nirbheek** [comment]
You're looking for `link_whole:`?

**Comment by Salamandar** [comment]
:'(
How the hell did I not stumble on that this last hour or so ?
Thank you for pointing this, I suppose that'll solve all that. Maybe add "whole-archive" as keyword in the doc will help folks like me to find it.

**Comment by nirbheek** [comment]
Documentation bug, send patches!

**Comment by Salamandar** [comment]
Yeah, I'll think about it ;)
