### ISSUE TITLE
Build error when using target.extract_all_objects() when target has header sources

### ISSUE THREAD

**Issue by xclaesse** [mesonbuild/meson#2716]
An issue has been discovered while working on PR #2711:

> ninja: error: 'gio/gio-2.0@sha/meson-generated_.._gnetworking.h.o', needed by 'gio/libgio-2.0.a', missing and no known rule to make it

According to @nirbheek it is a bug in extract_all_objects():
> I've seen this bug before elsewhere. It's because when figuring out the list of sources to use in extract_all_objects(), we don't skip over headers. See the sources classification in backends/ninjabackend.py:NinjaBackend.generate_target(). Specifically, look at how we handle the contents oftarget_sources and generated_sources.
>
>This file classification needs to be factored out and probably moved to the BuildTarget object so it can also be used by extract_all_objects().

**Comment by bonzini** [comment]
This causes #791 to regress.
