### ISSUE TITLE
"Subproject_dir must not contain a path segment" in master breaks projects

### ISSUE THREAD

**Issue by ximion** [mesonbuild/meson#2719]
Hi!
The new check introduced in https://github.com/mesonbuild/meson/commit/c178a5766b38d49f5fe44abcf2aa945e1156cf4f breaks existing projects which place their subprojects' wrap files in project subdirectories, e.g. `contrib/subprojects`.
I've seen this quite often and actually used that particular path myself (why create another toplevel directory if there already is a directory dedicated for similar stuff?).

While I agree that paths like `../dummy` in there are awful, I think disallowing putting the files in any subdirectory is a bit aggressive. Can the check be relaxed to only check for the "is an absolute path used" and "is a relative path used that goes beyond the source_root" cases, or is there an obvious bug in using a level-2-subdirectory in source_root?

**Comment by ximion** [comment]
I just now was debugging an issue someone found in the Vibe.d project when compiling it with Meson (see https://github.com/vibe-d/vibe.d/pull/1983#issuecomment-348399761 for reference).
The Vibe.d project uses `lib/subprojects/` as its directory, and compiles fine with Meson 0.42.x. When upgrading to Meson 0.43.x that apparently broke with the worst possible error message (stating a wrong cause). Upon moving the subprojects dir to the project's toplevel directory, everything started to work again.

So, I guess there is definitely some issue here with using a nested subproject directory, but this issue was only introduced with Meson 0.43 and isn't present in prior versions.

**Comment by ximion** [comment]
Any news on this one? I would really like to know what the course of action is (I can't even submit a patch without knowing what the Meson maintainers would like to do).
This is also blocking updates to newer Meson versions in a couple of projects, and it's one of the bugs keeping Meson from being updated in Debian testing.

**Comment by jpakkane** [comment]
I guess we can change the check to ensure that there are no `..` segments in the directory name.

**Comment by ximion** [comment]
That would work for me, and also ensure the subproject dir stays in the project's source tree and not some random location. So, check that `subprojects_dir` is not an absolute path and contains no `..` would definitely resolve this for 99.9% of all people (and the rest could fix their Meson file).
