### ISSUE TITLE
Extract compiler/linker flags from threads dependency

### ISSUE THREAD

**Issue by ebassi** [mesonbuild/meson#2725]
GLib can build against different threading implementation, depending on the platform, as it provides portable threading primitives. In order to properly communicate the dependency to projects depending on GLib itself, the compiler and linker flags for the threading implementation are passed inside the glib-2.0 pkgconfig file:

```
Name: GThread
Description: Thread support for GLib
Requires: glib-2.0
Version: @VERSION@
Libs: -L${libdir} -lgthread-2.0 @G_THREAD_LIBS@
Cflags: @G_THREAD_CFLAGS@
```

When building GLib with Meson, the `G_THREAD_LIBS` and `G_THREAD_CFLAGS` are empty, as GLib uses `dependency("threads")`. This means that projects using GLib and the threading primitives are now missing the appropriate compiler and linker flags depending on the platform, and they'll have to manually add the dependency on the threading library on their own build system, and hope it's the same library used by GLib.

A possible solution would be to allow calling `get_pkgconfig_variable("Cflags")` and `get_pkgconfig_variable("Libs")` on the "threads" dependency object.

**Comment by nirbheek** [comment]
Upstream bug for this: https://bugzilla.gnome.org/show_bug.cgi?id=788773

Like I said there, the best way is probably to use the pkg-config generator.

**Comment by ebassi** [comment]
I'm fine with that, assuming we can replace all the variables that currently exist inside the pkg-config template files, and are part of our exported "API".

**Comment by xclaesse** [comment]
I gave it a quick try, but passing `thread_dep` to `libraries_private` generate error:

> Library argument not a library object nor a string.
