### ISSUE TITLE
Problem regarding assert in function "rpaths_for_bundled_shared_libraries"

### ISSUE THREAD

**Issue by behlec** [mesonbuild/meson#2726]
So, I ran into an issue where the assert "assert(not os.path.isabs(rel_to_src))" in function "rpaths_for_bundled_shared_libraries" in backends.py is triggered. I do not understand what this assert is supposed to assure exactly and I do have the suspicion that the check does not really accomplish what it should:

I run into this when I have the build dir in /tmp. The problem seems to be that I am using a library which is located in my home directory. If the build dir is also in my home directory this is not a problem but when I try to build in /tmp it fails. If I comment out the assert the project compiles and runs.
The values of the variables are:
absdir: /home/user/local/boost/lib
rel_to_src: /local/boost/lib
self.environment.get_source_dir():  /tmp/foo

The test seems to be broken: In the case where it works for me the length of the build  dir plus one is the same lenght as the absdir and rel_to_src is accepted.

If you need a small example that triggers the problem I could probably give you some.

**Comment by behlec** [comment]
This seems to be connected to issue #2661

**Comment by jpakkane** [comment]
Should be fixed by the same PR that fixed #2661.
