### ISSUE TITLE
Add dependencies to tests

### ISSUE THREAD

**Issue by Salamandar** [mesonbuild/meson#2740]
* Some tests depend on specific targets
* Some tests depend on specific tests (test1 creates a file1, test2 reads file1 and writes file2)

Such dependencies for tests are not possible now, but would be useful in some cases.

**Comment by jpakkane** [comment]
The latter is a very bad idea. Every test should be runnable on its own in isolation. This kind of test setups are a code smell and should be refactored either so that the file creation and using is in the same test unit or by having the file generation code in a helper function that each test calls on its own as necessary.

**Comment by Salamandar** [comment]
> or by having the file generation code in a helper function that each test calls on its own as necessary.
Well those are unit tests of a file-generating library… So the test basically are "Can I output a file ?" "Can I read back this file ?"

**Comment by jpakkane** [comment]
> Well those are unit tests of a file-generating library… So the test basically are "Can I output a file ?" "Can I read back this file ?"

Yes, and this should be one test at least as far as Meson test specifications are concerned. In pseudocode something like this;

    void test_file_creation() {
      const char *fname = create_temp_filename();
      ASSERT_TRUE(create_file(fname));
      ASSERT_TRUE(file_exists(fname));
      ASSERT_TRUE(can_parse_file(fname));
      unlink(fname);
    }

Spreading that over multiple tests is extremely brittle and makes things such as running unit tests in parallel tricky or impossible.

**Comment by nirbheek** [comment]
(1) is the same as https://github.com/mesonbuild/meson/issues/1704. Closing because (2) will not be supported.
