### ISSUE TITLE
mesontest and mesonintrospect are broken with meson 0.44.0

### ISSUE THREAD

**Issue by mgautierfr** [mesonbuild/meson#2761]
With last version, meson try to detect the location of meson and assume the executable name to be "meson" or "meson.py".

But if a user uses `mesontest` instead of `meson test`, the executable name is "mesontest" and `meson` cannot find the executable.
It is probably the same with other tools as `mesonconf` or `mesonintrospect`

I know that those scripts are deprecated since 0.42.0, but they are still present in 0.44.0 and not mark as deleted in 0.44.0 release note.

**Comment by nirbheek** [comment]
This is fixed with https://github.com/mesonbuild/meson/pull/2840.
