### ISSUE TITLE
RFE: provide full compiler version info

### ISSUE THREAD

**Issue by keszybz** [mesonbuild/meson#2762]
meson currently prints only the basic version string:
```
Native C compiler: cc (gcc 7.2.1)
```
but often the devil is in the details. It'd be great if the whole first line of `gcc --version` output could be printed:
```console
$ gcc --version |head -n1
gcc (GCC) 7.2.1 20170915 (Red Hat 7.2.1-3)
```

(I'm investigating a segfault in gcc and "7.2.1" is just not enough information, I really need to know that it's 7.2.1-3 and not 7.2.1-4 and I cannot glean this from the meson logs.)

**Comment by nirbheek** [comment]
This should be very easy to implement.

**Comment by shawnl** [comment]
I also need the triplet from gcc -dumpmachine https://github.com/mesonbuild/meson/issues/2774

**Comment by jpakkane** [comment]
Fixed now but close stanza was missing.
