### ISSUE TITLE
(Spurious?) RuntimeError: No specified compiler can handle file impl/json/jsmn.c

### ISSUE THREAD

**Issue by zajo** [mesonbuild/meson#2768]
With 0.44.0, I get this error:

```
RuntimeError: No specified compiler can handle file impl/json/jsmn.c
```

This in a project which is mostly C++, but it uses this one `.c` file, defined as:

```
jsmn = declare_dependency( sources: ['impl/json/jsmn.c'], compile_args: [ '-DJSMN_STRICT=1', '-DJSMN_PARENT_LINKS=1' ])
```

The project statement at the top was:

```
project('name','cpp',default_options : ['cpp_std=c++11','b_pch=false'])
```

Previous versions of Meson didn't report any errors, but I figured I'd have to add `'c'` to the list. I tried:

```
project('name',['cpp','c'],default_options : ['cpp_std=c++11','b_pch=false'])
```

which gave me the error message I quoted at the top of this report.

**Comment by nirbheek** [comment]
Can you please reduce this to a small test case so we can reproduce it?

**Comment by nirbheek** [comment]
Removing from stable release milestone since this regressed between 0.42 and 0.43, and there is no final fix available yet.
