### ISSUE TITLE
No modules named codecs

### ISSUE THREAD

**Issue by mlschneid** [mesonbuild/meson#2769]
Windows 10 x64
Python version 3.6.3 x64

Just installed meson from the nightly .msi (e674434). When I run meson from cmd, I get the error below:

```
Fatal Python error: Py_Initialize: unable to load the file system codec
Traceback (most recent call last):
  File "C:\Python\lib\encodings\__init__.py", line 31, in <module>
ModuleNotFoundError: No module named 'codecs'

```

It's a pretty fresh install of windows / python / cl.exe. Am I missing something?

**Comment by jibsen** [comment]
I have the same problem with the release .msi installer, also on Win10 x64.

**Comment by jpakkane** [comment]
[Caused by a bug in cx-freeze](https://github.com/anthony-tuininga/cx_Freeze/issues/325). We'll do a new release once they have a fix out.

**Comment by polarina** [comment]
Upstream has allegedly fixed this issue with cx-freeze 5.1.1.

**Comment by jpakkane** [comment]
The msi installer has been updated with a newer version built with 5.1.1. Please test and let us know if it has been fixed. Thanks.

**Comment by polarina** [comment]
The installer now works on my computer. Thanks!
