### ISSUE TITLE
gnome.compile_schemas() doesn't re-compile when schema source changes

### ISSUE THREAD

**Issue by mjog** [mesonbuild/meson#2770]
Geary compiles its GSettings schema at compile time to allow the app to be run from the source and for use by unit tests. However if the schema source XML changes, the binary schema file is not updated, leading to client errors and failed unit tests.

A trivial fix is to allow `depend_files` as a kwarg via adding it to `@permittedKwargs` for `GnomeModule. compile_schemas`, allowing the developer to specify the name of the source XML file, thus meson will ensure schema is re-compiled when the source changes.

E.g: This already fixes the issue, albeit with a warning from Meson at run time:

```meson
 geary_compiled_schema = gnome.compile_schemas(
    depend_files: files('org.gnome.Geary.gschema.xml'),
 )
```

Meson 0.42.1.

**Comment by TingPing** [comment]
I agree that is a reasonable solution (since we have no reasonable way to track the dependency otherwise). Mind opening a PR?

**Comment by mjog** [comment]
Thoughts?

**Comment by nirbheek** [comment]
Fixed with https://github.com/mesonbuild/meson/pull/2771. In the future please put "Closes #XXX" in the commit message so this happens automatically :smile:

**Comment by mjog** [comment]
Will do, thanks!
