### ISSUE TITLE
meson: Need to generate a .pc file for library for static compilation

### ISSUE THREAD

**Issue by ocrete** [mesonbuild/meson#2772]
When building against a static plugin, you need to have explicit dependencies that it uses as those are not stored in the `.a` file. With libtool, those are stored in a `.la` files. Meson does not use `.la` files and prefers to use pkgconfig files for this, so it need to provide the same information in the Libs.private/Requires.private sections.

Therefore, we need to generate a .pc file for every single static library to know what external libraries it should be compiled against.

I suggest that this should be a meson feature (and yes, we just re-invented .la files).

**Comment by xclaesse** [comment]
I don't think library() call should generate a pc file, there are too many extra info to pass (name, file base, description, ...). However with PR #2757 generating a simple pc file is just a few lines.

**Comment by ocrete** [comment]
Indeed this is a bit onerous.. Maybe it should generate a warning if you create a static library that has deps other than libc and dont create a matching pkgconfig file?

**Comment by xclaesse** [comment]
I think when https://github.com/mesonbuild/meson/pull/3284 gets merged we can consider this fixed.

**Comment by nirbheek** [comment]
Fixed by https://github.com/mesonbuild/meson/pull/3284.
