### ISSUE TITLE
RFE: provide GNU triplet of host

### ISSUE THREAD

**Issue by shawnl** [mesonbuild/meson#2774]
I need autoconf's GNU_HOST, which can be gotten from gcc or clang with `gcc -dumpmachine`. it is also what is passed to `clang -target` when cross compiling (so meson already knows this)

This is GNU triplet of the host when cross-compiling.

This information is roughly available in its component form through
`compiler.cpu_family`
and
`compiler.system`
but the GNU triplet also provides some info about libc (e.g. android vs gnu) and ABI (gnueabi and gnueabihf on ARM) and is used in many places, and it would be good to provide it directly. (I need it to pass to clang -target from distccd so distccd supports cross compiling)

RFE: `compiler.gnu_triplet`

Perhaps only supported for gcc and clang.

**Comment by shawnl** [comment]
Autoconf removed $host from latest version, and I don't know how to get it. I still need this.

**Comment by dcbaker** [comment]
Probably related to  #4852
