### ISSUE TITLE
gnome.yelp() doesn't compile help pages at compile time

### ISSUE THREAD

**Issue by mjog** [mesonbuild/meson#2775]
Currently, `gnome.yelp()` does not build Yelp help pages at compile time, instead it both builds and installs the help pages using (what I assume is) an install-time script hook.

Geary has historically built its help pages as part of the build process so we know it's working, to be able to proofread the manual using the app from the source directory, to catch tool errors, and so on. It would be good to be able to continue to do this.

PR to follow.

**Comment by mjog** [comment]
Famous last words. This is a bit murkier than I was expecting. My initial plan was to simply to arrange to call `yelphelper.py build` as a run target, but then that still won't get executed by default, so then I looked at making it a custom target, but realised that would need a list of generated output files so it knows when it is out of date, but then you want to only rebuild the minimum if something has actually changed (e.g. a page or a .po file), and it all started to look kind of sucky.

So my currently plan of attack is to actually do it properly: as follows, in `gnome.yelp()`

* Read `LIGUAS` to work out what languages are present
* Create two custom target for each lang:
    1. Run `msgfmt` to create `builddir/lang/lang.gmo`, depending on `srcdir/lang/lang.po`
    2. Run `itstool` to create each `builddir/lang/source.page`, depending on `builddir/lang/lang.gmo` and each source page
 * Create a new custom target `project-help` that depends on each merged source page, and return that along with the current `help-project-pot` and `help-project-po` targets.

Thoughts?

**Comment by mjog** [comment]
This is slightly problematic in that if the user does a ninja install as root the gmo files and merged pages in the build directory are owned by root, so you also need to be root to delete them.

This was [reported by a user](https://bugzilla.gnome.org/show_bug.cgi?id=777044#c14) for Geary's build.

**Comment by TingPing** [comment]
That is a general problem any time you call `ninja` as another user, just a bit more prominent if its under `install`.

**Comment by fedelibre** [comment]
As [mentioned here](https://gitlab.gnome.org/GNOME/geary/issues/126#note_359240), a consequence of this bug is that files built at install step won't be removed by `ninja uninstall`.

**Comment by TingPing** [comment]
> As [mentioned here](https://gitlab.gnome.org/GNOME/geary/issues/126#note_359240), a consequence of this bug is that files built at install step won't be removed by `ninja uninstall`.

That is https://github.com/mesonbuild/meson/issues/1601

**Comment by abderrahim** [comment]
@mjog Any news on this one?

It's really annoying that `ninja install` takes more than a minute (on an SSD) even though I just ran install.

**Comment by mjog** [comment]
@abderrahim, sorry, fell right off my plate, quite far apparentl. :/
