### ISSUE TITLE
Array based default values

### ISSUE THREAD

**Issue by inigomartinez** [mesonbuild/meson#2777]
meson's 0.44 version features the [array type for options](http://mesonbuild.com/Release-notes-for-0-44-0.html#an-array-type-for-user-options), which may have an array as the default value.

It could also be interesting to allow an array for default values for those types which are not an array. An interesting example the options used for paths, which are based on the string type, that can have different alternative paths as default values:

The following `code` is a slightly modified code from the wip NetworkManager meson port:

```
resolvconf_path = get_option('resolvconf')
if enable_resolvconf
  if resolvconf_path == ''
    name = 'resolvconf'
    locations = [
      name,
      '/sbin/' + name,
      '/usr/sbin/' + name,
      '/usr/local/sbin/' + name
    ]
  else
    locations = resolvconf_path
  endif

  resolvconf = find_program(locations)
  config_h.set_quoted('RESOLVCONF_PATH', resolvconf.path())
endif
```
Which could be improved by the following:

`option('resolvconf', type: 'string', value: ['resolvconf', '/sbin/resolvconf', '/usr/sbin/resolvconf', '/usr/local/bin/resolvconf'], description: 'Enable resolvconf support')`

And the meson build file can be as follows:

```
resolvconf = find_program(get_option('resolvconf'))
config_h.set_quoted('RESOLVCONF_PATH', resolvconf.path())
```

This would cover the case where the user might use it's own path, or in other case the array with different default locations.

I suppose that this could also be useful for the rest supported types.

**Comment by nirbheek** [comment]
I am not sure I understand, are you thinking of the combo option with choices or if not, how is this different from that?

**Comment by inigomartinez** [comment]
The combo option is limited to the choices available. I haven't tried the array option yet, but I've guessed that it works in a similar way.

In my suggestion, the user might introduce something different not limited to the available choices, and defaults to the array of values in the `values` field in other case.

Following the previous example, think about an use case where the user wants to use the last released version of `resolvconf`, due to a security update or a feature not present in the `resolvconf` available in the repositories, which he has installed under his home directory. He could use the following command:

`meson -Dresolvconf=/home/user/resolvconf-git/resolvconf _build` -> `resolvconf.path() = /home/user/resolvconf-git/resolvconf`

In the other hand, another user may use the `resolvconf` installed by distribution, which should be usually found in one of the directories used as default values.

`meson _build` -> `resolvconf.path() = /usr/sbin/resolvconf`

I hope this example helps.

**Comment by nirbheek** [comment]
From what I understand, you want to provide a list of 'default' values for an option, and also allow people to select any other value for that option? What's the point of that list of 'default' values? How does Meson make use of it?

**Comment by inigomartinez** [comment]
I've seen that the proposed use case is actually covered by f8a419b27, so this issue not useful anymore.
