### ISSUE TITLE
LLVM library detection fails because of *git* version suffix

### ISSUE THREAD

**Issue by gerddie** [mesonbuild/meson#2786]
See here: https://travis-ci.org/gerddie/mesa/jobs/316903830 

meson should use the new link library detection method but uses the old method searching for libLLVM-5.0.so - probably because it fails to extract the proper version due to the *git+xxx* suffix.

**Comment by dcbaker** [comment]
This is annoying on many levels. Mostly that travis has appended a git tag to the end of the version while LLVM uses SVN, and we already have logic to strip the default svn off the end of the version if that's present.

**Comment by gerddie** [comment]
FWIW, it is actually not travis, but LLVM upstream who adds this suffix, in this case to the Ubuntu 14.04 tarball provided on their [download page](http://releases.llvm.org/download.html#5.0.0).

**Comment by dcbaker** [comment]
That is very strange, LLVM built from SVN (which is the canonical source for LLVM and Clang) adds "svn" to the version, ie: "5.0.0svn".
