### ISSUE TITLE
Add something like depend_files to windows.compile_resources()

### ISSUE THREAD

**Issue by jibsen** [mesonbuild/meson#2789]
Resource script can include various other files (bitmap, cursor, font, html, icon, message table, binary data, manifest), it would be nice if it were possible to declare the resource script depends on these.

**Comment by jpakkane** [comment]
Compile resources parses the dependency file's contents and adds dependencies to files listed in it. This should already work.

**Comment by jibsen** [comment]
Perhaps I should have noted I meant in the Windows module. I created a sample project with a resource file that includes an application manifest, and there does not seem to be any dependency on it.

**Comment by jon-turney** [comment]
> Resource script can include various other files (bitmap, cursor, font, html, icon, message table, binary data, manifest), it would be nice if it were possible to declare the resource script depends on these.

The other class of files the resource script may depend on are files which are  #included using the C preprocessor.  I guess it may be possible to write the custom target for invoking the resource compiler such that a depfile is generated by the preprocessor?

**Comment by jon-turney** [comment]
Please re-open this issue.  #2815 contains text like "could fix #2789", but doesn't fix this issue.
