### ISSUE TITLE
Build not reproducible with Fortran, improper USE dependency scanning

### ISSUE THREAD

**Issue by vedranmiletic** [mesonbuild/meson#2795]
I'm evaluating Meson for usage in [CP2K](https://www.cp2k.org/) ([source](https://github.com/cp2k/cp2k)), a large Fortran codebase using handwritten Makefile and some scripts. I started with `cp2k/src/base` and I'm overjoyed with how simple the syntax is; my `meson.build` is:

```python
project('cp2k_base', 'fortran')
add_project_arguments('-ffree-form', '-std=f2003', '-fimplicit-none', language : 'fortran')

base_files = files(
        'base_hooks.F',
        'kinds.F',
        'machine.F',
        'machine_internal.F'
)
dynamic = shared_library('cp2k_base', base_files)
```

Unfortunately, the build is not reproducible, and `ninja` will fail most of the time (but **not every time**) because `base_hooks.F` has `USE kinds` directive, and `kinds.F` hasn't been compiled before it. If I put `kinds.F` before `base_hooks.F` then the build seems to succeed more often, but still not every time in a reproducible way.

**Comment by nirbheek** [comment]
The relevant code that does the dependency scanning is `get_fortran_deps()` in `mesonbuild/backend/ninjabackend.py`. Perhaps you'd like to look at that and improve it?

**Comment by QuLogic** [comment]
Do you have a short example to try? The scanner does appear to correctly use a case-insensitive search and lowercases the names of the modules. I think what might be missing is support for line continuations, i.e., `use` and `module` names must be on one line.

**Comment by QuLogic** [comment]
I think your problem is that `machine.F` `#include`s `machine_posix.f90` and our simplistic parser isn't able to properly parse that.

**Comment by scivision** [comment]
closed by https://github.com/mesonbuild/meson/pull/5081
