### ISSUE TITLE
Add dependencies: to windows.compile_resources

### ISSUE THREAD

**Issue by yselkowitz** [mesonbuild/meson#2830]
Windows Resource (.rc) files often include headers, Windows Icon (.ico) files, and/or manifest files.  If any of those change, the .rc should be recompiled to include those changes.  Currently, however, there is no way of specifying this in windows.compile_resources(), which makes it practically unusable for any of my use cases.

A dependencies: keyword argument should be added to specify files and/or targets whose modification should trigger a recompile.

**Comment by jibsen** [comment]
Think this is a duplicate of #2789.

**Comment by yselkowitz** [comment]
Indeed, thanks.
