### ISSUE TITLE
How to override the default compiler for the platform

### ISSUE THREAD

**Issue by yuhangwang** [mesonbuild/meson#284]
I have multiple compilers install on my machine. How to tell Meson to use the one I need?

**Comment by jpakkane** [comment]
Meson obeys the standard way of setting the compiler with CC/CXX environment variables. When you first set up your project do it like this:

CC=someccompiler meson build_dir

Note that you must set the compiler when first running Meson. You can't change it afterwards.

**Comment by yuhangwang** [comment]
Thanks!
