### ISSUE TITLE
msgfmthelper builds wrong paths since 0.44

### ISSUE THREAD

**Issue by ximion** [mesonbuild/meson#2845]
Hi!
Since upgrading to Meson 0.44, the AppStream CI fails with this error:
```
FAILED: data/org.freedesktop.appstream.cli.metainfo.xml 
/usr/bin/python3 /usr/bin/meson --internal msgfmthelper ../data/org.freedesktop.appstream.cli.metainfo.xml data/org.freedesktop.appstream.cli.metainfo.xml xml /build/po --datadirs=/build/data/
msgfmt: error while opening "/build/po/tr.po/nhu.po/nuk.po/nnb_NO.po/nsr@latin.po/nfr.po/nid.po/npt_BR.po/nsl.po/nar.po/noc.po/nde.po/npt.po/ngd.po/nca.po/nda.po/nko.po/ncs.po/nru.po/nsr.po/nsv.po/nlt.po/neu.po/nes.po/nnl.po/nen_GB.po/nzh_TW.po/nsk.po/nzh_CN.po/nit.po/nfi.po/ngl.po/npl.po/nja.po/nckb.po" for reading: Not a directory
```
The corresponding Meson definition is:
```meson
i18n.merge_file (
    input:  'org.freedesktop.appstream.cli.metainfo.xml',
    output: 'org.freedesktop.appstream.cli.metainfo.xml',
    type: 'xml',
    data_dirs: [meson.current_source_dir()],
    po_dir: join_paths (source_root, 'po'),
    install: true,
    install_dir: join_paths (get_option ('datadir'), 'metainfo')
)
```
Reverting back to Meson 0.43 fixes this issue. I don't know (yet) what happened here, but this looks like a regression (unless I am missing some obvious issue in the Meson file).

**Comment by TingPing** [comment]
I'm not sure I see any obvious problem. `msgfmthelper.py` has not been touched in many releases (since april), the generated command looks correct, and your usage seens fine.

**Comment by tp-m** [comment]
Is that long thing in quotes that msgfmt complains about supposed to look like that?

**Comment by ximion** [comment]
@tp-m The problem is that for some reason all the .po files are joined together to one path (pointing to a file that doesn't exist). I assume those have to be listed individually.

@TingPing The [LINGUAS](https://github.com/ximion/appstream/blob/master/po/LINGUAS) file is fine. If it wasn't, the problem would not go away when downgrading Meson.

**Comment by TingPing** [comment]
@ximion Strange, but the thing is `meson` isn't involved in that process at all, it just points `msgfmt` at the directory.

https://github.com/mesonbuild/meson/blob/master/mesonbuild/scripts/msgfmthelper.py#L33-L35

**Comment by ximion** [comment]
Yeah, I don't get it either... Also, the files it complains about are not for languages listed in LINGUAS (except for "tr"), so I wonder what adds them there.

**Comment by TingPing** [comment]
Does running `msgfmt` by hand with the same args have the same results?

**Comment by ximion** [comment]
Okay... So, I now know the culprit, but I have no firm idea on why the Meson version makes such a difference.
So, the failing project contained this snippet, which I wasn't aware of:
```
make_linguas = custom_target ('make-linguas',
    build_always: true,
    output: 'LINGUAS_dummy', # fake output
    command: [
        'sh', '-c',
        'find ' + meson.current_source_dir() +
        ' -type f' +
        ' -iname "*.po"' +
        ' -printf \'%f\\n\'' +
        ' | grep -oP \'.*(?=[.])\' | sort' +
        ' > ' + join_paths(meson.current_source_dir(), 'LINGUAS')
    ]
)
```
This sometimes messes badly with the `LINGUAS`  file, breaking it. Fixing the character escaping (`-printf \'%f\\n\''` --> `-printf \\\'%f\\n\\\''`) appears to resolve this issue.
For some reason, this problem did not manifest itself with older Meson versions, and I am not 100% sure why. My guess is though that this particular target just wasn't executed by default before. It is meant to be only executed upon explicit request, yet, newer Meson versions started to run it on regular builds.

Therefore, I am pretty sure this issue is actually a duplicate of https://github.com/mesonbuild/meson/issues/1942

Also, I am sorry for the noise - I couldn't get around to debug this before the holidays, and I just now found the time to take a close enough look at it. Thank you for all the feedback!
And on the positive side: One regression less now :-)

**Comment by TheAssassin** [comment]
As mentioned in issue #2763, I am trying to build an AppImage for the GNOME application Multi Writer. 

@nirbheek redirected me here. The build systems I tried is Ubuntu xenial, using the latest version of Meson.

Please check https://travis-ci.org/TheAssassin/gnome-multi-writer. Meson does calculate relative paths to some files relative to the wrong directory. I couldn't find out how to fix that yet, as I never worked with Meson before, I was only able to find the cause of the error in the resulting build configuration.
Now, one way to fix these issues would be to use absolute paths, but that's something that would have to change in meson itself.

@nirbheek mentioned he's running Fedora 27, so I'll try to build it in such a container. But I'd like to be able to build the application on an older distro, as AppImages usually run on distros as old as or newer than the build system (see also https://github.com/mesonbuild/meson/issues/2763#issuecomment-366803260).

**Comment by nirbheek** [comment]
If you could figure out what the difference is in the build.ninja generated on Xenial and F27, we should be closer to figuring this out.

**Comment by TheAssassin** [comment]
Thanks for looking into this, @nirbheek. I didn't get to building it myself yet. Please let me know if you need more information from me.

**Comment by eli-schwartz** [comment]
AFAICT the problem with gnome-multi-writer was never defined, logs are gone, and nothing ever happened here. The original issue was resolved, though.
