### ISSUE TITLE
Subprojects should be able to 'yield' (or 'inherit') option values to (from) the parent project

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#2853]
See https://github.com/mesonbuild/meson/pull/2846#issuecomment-354539160 and later comments.

This would be useful in the GStreamer and GNOME ecosystems, and it would become useful for others too if we describe a convention on how to name options (this is already sorely needed because people keep prefixing options with `enable_`, `disable-`, or `with-`).

**Comment by jpakkane** [comment]
> I also think the default should be inherit: true to avoid boilerplate in every project to make it work properly in subprojects.

That is a potentially breaking change as the current behaviour defaults to `false`.

**Comment by nirbheek** [comment]
I'm also constantly conflicted on whether to temporarily break existing projects or keep a suboptimal design around forever.

**Comment by NickeZ** [comment]
> I'm also constantly conflicted on whether to temporarily break existing projects or keep a suboptimal design around forever.

If you maintain a list of "well-maintained" projects that use meson and build all those projects you could get a feeling of how bad the breakage would be. A bit like how the rust community [builds all projects](https://github.com/rust-lang-nursery/crater) on crates.io before merging larger PRs to rustc. This is not something that you should run for every commit because it could take several hours to run.

**Comment by nirbheek** [comment]
I already have such a list of repos, and I run tests on all of them before a release (I wasn't able to do it for the last two because I've been busy). 

The problem here transcends that since breakage here depends not on how upstreams write their build files, but how (other?) people use them in subprojects.

With some projects like gstreamer, the subproject setup is in a single git repo so it's easy to test. It's harder to know what other people are doing in their subproject setups. We only find out when we break something.

One simple way to minimize breakage would be to specify a list of common-action-option-names and default to `yielding: true` on those.

**Comment by nirbheek** [comment]
Fixed with https://github.com/mesonbuild/meson/pull/2864.
