### ISSUE TITLE
Python module's extension_module() method should auto-detect install_dir

### ISSUE THREAD

**Issue by kaimast** [mesonbuild/meson#2859]
I use boost python to generate python bindings for my application. Meson compiles these bindings to a shared object and places them in /usr/local/lib. However, they're not detected by python. 

The only way to install the bindings properly seems to have a dedicated setup.script. However, that feels kind of disconnected from the meson build process. 

Any idea how I can actually build my python bindings and make them visible to my local python installation?

**Comment by nirbheek** [comment]
Are you using the [Python 3 module](http://mesonbuild.com/Python-3-module.html) to build this? If so, you can pass `install_dir: <path-relative-to-prefix>` to `extension_module()` to change where it's installed.

However, perhaps we should autodetect the correct location and set the default installation directory to that.

**Comment by kaimast** [comment]
Oh that works. Thanks a lot! 

Is this behaviour documented anywhere? I assumed that the python3 module would detect the path for me.

A small issue I run into with this is that my python module has the same name as my c++ bindings, which is not allowed by meson it seems.
Is there any way to let meson have to targets with the same name, for cases like this?

**Comment by nirbheek** [comment]
> Is this behaviour documented anywhere?

Yes, it's documented on the page I linked above (takes the same arguments as `shared_module()`). It could be more explicit though, we'd be happy to accept doc improvements to that page.

> I assumed that the python3 module would detect the path for me.

Yeah, we should probably fix that.

> A small issue I run into with this is that my python module has the same name as my c++ bindings, which is not allowed by meson it seems.

It has been a point of contention, you can find the discussion here: https://github.com/mesonbuild/meson/pull/1867#issuecomment-304692989

**Comment by eli-schwartz** [comment]
This works correctly in the `python` module, the python***3*** module is deprecated and won't be fixed.
