### ISSUE TITLE
Warn or error out when targets try to link_with: shared modules

### ISSUE THREAD

**Issue by marcelhollerbach** [mesonbuild/meson#2865]
On osx shared modules are NOT getting -install arguments, (there seems to be a reason for this).

But when creating the .symol files, we rely on finding a LC_ID_DYLIB. Which will read to a crash.

**Comment by nirbheek** [comment]
It's not really clear what you are trying to say, could you please describe:

1. What version of meson you are using
2. What you are trying to do
3. Why it doesn't work (and how did it work earlier, and with what build system)

**Comment by marcelhollerbach** [comment]
The bug meanwhile clarified itself a bit more, and i managed to fix it on my side, however, there are a few things:

First of all, what was my mistake:
I used 
```
tmp = shared_module(...) 
[...]
shared_library(...
   link_with : tmp
)
```

Which does not give a error at `meson` stage. However, when building you will get a meson crash, since meson wants to create a .SYMBOL file of a .so file, this means it searches for a LC_ID_DYLIB in the .so file, but that one is not set. And thus the code fails.

What I would have expected:
It would be super usefull if meson would tell me in such a case that that is usally not really what i should do, (linking a shared_module into a shared_library).
