### ISSUE TITLE
Non-gcc compile and link-flags

### ISSUE THREAD

**Issue by zabeloliver** [mesonbuild/meson#2867]
Hi, 

i'm currently looking into a replacement of our old self-written make-files. Since we're only doing cross-compilation for embedded uCs the handling of this very important. 
By looking into CMake i hit a point, where it is very complicated to go on: If a compiler has not gcc compile flags.
For example the toolchain for renesas RX processors uses "-define=" instead of "-D" for symbols or the linker uses "-include=" instead of "-I".

So the main question for me, before digging deeper into meson, is: Is this scenario covered by meson??

Thanks a lot for your help!
Regards, 
Oli

**Comment by nirbheek** [comment]
In Meson, you can extend the base `Compiler` or `CCompiler` classes to support your embedded microcontroller compiler. It's fairly simple, and people have already added support for their compilers in this way.

However, one caveat is that quite a few places hard-code that defines are added with `-D` and includes with `-I`. This is not difficult to fix, but requires someone to do it.

**Comment by zabeloliver** [comment]
Hi, thanks for the quick reply. Do you know one of the projects who extended the `Compiler` class? If this would work i'd be trying to find the hard-coded references and modify the code.

**Comment by jpakkane** [comment]
There is no way for projects to extend the Compiler class. It needs to be submitted upstream.

**Comment by zabeloliver** [comment]
Hi, thanks - that was my missing link. I will take a look into it. 

Von meinem iPhone gesendet
