### ISSUE TITLE
gnome gtkdoc should provide for extra xml content to be copied into builddir

### ISSUE THREAD

**Issue by tp-m** [mesonbuild/meson#287]
In a gtk-doc setup not all xml files are necessarily generated. There's the main sgml/xml file of course, but there might also be other xml files such as a 'Running libfoo applications' section or version.entities.

These files need to be copied from the source dir into the docs xml/ build dir (or from the docs build dir into the docs xml/ build dir if they are generated via configure_file, as version.entities might be).

It would be nice if something like

    extra_content: [ 'foo.xml', 'bar.xml' ]

could be added for this purpose. Apologies in advance if this already exists and I missed it.

**Comment by tp-m** [comment]
Or perhaps there's an option to pass to it to also look in the source directory and the docs build directory.

**Comment by jpakkane** [comment]
MR #288 added compiler options to gtkdoc.
