### ISSUE TITLE
Passing a dummy dependency to library() doesn't work

### ISSUE THREAD

**Issue by lazka** [mesonbuild/meson#2872]
Trying to pass a dummy dependency to library() I saw that it is suggested in the dependency() docs that one creates a dependency with name "" and required: false.

```
project('glib', 'c', 'cpp',
  version : '2.55.0',
  meson_version : '>= 0.44.0',
)
thread_dep = dependency('', required : false)
library('glib-2.0',
        dependencies: [thread_dep])
```
but this results in the following error:

```
Meson encountered an error in file meson.build, line 6, column 0:
Argument is of an unacceptable type 'Dependency'.
Must be either an external dependency (returned by find_library() or dependency()) or an internal dependency (returned by declare_dependency()).
```

What am I doing wrong?

**Comment by lazka** [comment]
Would a simple "declare_dependency()" have the same effect? (maybe the docs should recommend that instead if that's the case)

**Comment by nirbheek** [comment]
@jon-turney I believe your patch from https://github.com/mesonbuild/meson/pull/2615 caused this regression.

**Comment by lazka** [comment]
ah, the object returned by declare_dependency() returns true for found(), so that's not a viable replacement.

**Comment by jon-turney** [comment]
Bother, that's a bit disappointing.

Not sure of the best way to fix this, so I create a couple of solutions as separate PRs.

**Comment by jon-turney** [comment]
I also notice that the test case given fails when using msvc and ninja backed, I think because library() is used with zero sources.  I'll  raise a separate issue for that.

**Comment by lazka** [comment]
Thanks @jon-turney!

**Comment by jon-turney** [comment]
@lazka no problem
