### ISSUE TITLE
Is library() with an empty list of sources valid?

### ISSUE THREAD

**Issue by jon-turney** [mesonbuild/meson#2876]
As noted in issue #2872, `library()` currently permits an empty list of sources, but this doesn't always work (it seems to fail with windows/msvc/ninja and osx/clang/ninja)

**Comment by jon-turney** [comment]
windows/msvc/ninja  (only) also seems to fail for `executable()` with an empty list of sources

**Comment by nirbheek** [comment]
Using an empty list of sources should indeed work in a number of cases, such as when you're using `objects:` and `link_whole:`. I thought we had tests for this already?

**Comment by eli-schwartz** [comment]
This originally did get checked, but in commit d070100c8c0529db984b4cb10de745e762b9199a that got broken and later fixed in commit 5ca5e0c900340110eb26bcf4491033e9d1bacf08.
