### ISSUE TITLE
Move to Python 3.6

### ISSUE THREAD

**Issue by jpakkane** [mesonbuild/meson#2891]
The thing currently blocking this is that Debian Stretch has 3.5. EPEL has 3.6 so that is no longer an issue.

**Comment by Ericson2314** [comment]
It would be very nice to go through and add type annotations everywhere

**Comment by Ericson2314** [comment]
https://packages.debian.org/buster/python3.7 https://packages.debian.org/buster/python3.6 If I understand this correctly, maybe Debian will go straight to 3.7? Then we can double down on annotations without fear of performance issues. CC @dcbaker.

**Comment by xclaesse** [comment]
I personally don't mind depending on Python 3.6, but when we moved to 3.5 we already had a lot of people complaining.

Just to put some timeline:
- Python 3.5 is EOL on 2020-09-13.
- Ubuntu 16.04 LTS has Python 3.5 and is EOL in 2021.
- Debian stable (stretch) has Python 3.5 and is EOL in between 2020 and 2022.

**Comment by dcbaker** [comment]
I'm going to tak a lot of flak in the X/mesa community if we drop support for python versions that aren't EOL. There are a lot of EL/LTS users in our community (I get complaints about Ubuntu 12.04 and 14.04 not working, for reference), and they're already annoyed that they can't continue using python 2.7 until ${END_OF_TIME}.

I'd really like to avoid deprecating python versions that are not EOL or *very* close to EOL according to the python foundation if at all possible. I'd much prefer that we require backport modules for old versions of python than drop support. Ala,
python 3.5 is supported, but you need backports.new_in_36 when using 3.5

**Comment by xclaesse** [comment]
tbf, mesa could just keep compat with latest version of meson that supports python 3.5, but given that meson still evolves pretty quickly I guess you're always targetting the latest release? Another option would give longer support to latest meson stable branch targetting python 3.5, but given we are already understaffed and we barely can do a .1 release, I don't think that's reasonable.

**Comment by Ericson2314** [comment]
Well for the specific case of annotations, it should be possible to pre-process them all away for release builds.

**Comment by amitdo** [comment]
https://pypi.org/project/f2format/

**Comment by eli-schwartz** [comment]
Fixed in #7671
