### ISSUE TITLE
Dependencies missing with static libraries

### ISSUE THREAD

**Issue by inigomartinez** [mesonbuild/meson#2893]
NetworkManager has recently merged meson support. While improving it, I have noticed that some static libraries which depends on generated sources, are not building properly.

I don't know if this should be its normal behaviour, but this seems to be happening due to missing dependencies in `ninja` rules.

You can find this behaviour when building the [libNetworkManagerBase.a](https://cgit.freedesktop.org/NetworkManager/NetworkManager/tree/src/meson.build#n96) library. One of its dependencies is [libnmdbus](https://cgit.freedesktop.org/NetworkManager/NetworkManager/tree/src/meson.build#n87), which is a static library [built](https://cgit.freedesktop.org/NetworkManager/NetworkManager/tree/introspection/meson.build#n88) by a set of [sources](https://cgit.freedesktop.org/NetworkManager/NetworkManager/tree/introspection/meson.build#n60) that are generated at build time. However, when building `libNetworkManagerBase.a`, I was expecting it to force the building of `libnmdbus.a` and finally the generated source, but it doesn't trigger their rules.

The `ninja` rule is as follows:

```
build src/libNetworkManagerBase.a: STATIC_LINKER src/NetworkManagerBase@sta/dhcp_nm-dhcp-client.c.o src/NetworkManagerBase@sta/dhcp_nm-dhcp-manager.c.o src/NetworkManagerBase@sta/dhcp_nm-dhcp-systemd.c.o src/NetworkManagerBase@sta/dhcp_nm-dhcp-utils.c.o src/NetworkManagerBase@sta/ndisc_nm-lndp-ndisc.c.o src/NetworkManagerBase@sta/ndisc_nm-ndisc.c.o src/NetworkManagerBase@sta/platform_wifi_wifi-utils-nl80211.c.o src/NetworkManagerBase@sta/platform_wifi_wifi-utils.c.o src/NetworkManagerBase@sta/platform_nm-linux-platform.c.o src/NetworkManagerBase@sta/platform_nm-platform.c.o src/NetworkManagerBase@sta/platform_nm-platform-utils.c.o src/NetworkManagerBase@sta/platform_nmp-netns.c.o src/NetworkManagerBase@sta/platform_nmp-object.c.o src/NetworkManagerBase@sta/main-utils.c.o src/NetworkManagerBase@sta/NetworkManagerUtils.c.o src/NetworkManagerBase@sta/nm-core-utils.c.o src/NetworkManagerBase@sta/nm-exported-object.c.o src/NetworkManagerBase@sta/nm-ip4-config.c.o src/NetworkManagerBase@sta/nm-ip6-config.c.o src/NetworkManagerBase@sta/nm-logging.c.o src/NetworkManagerBase@sta/platform_wifi_wifi-utils-wext.c.o
 LINK_ARGS = csrD
```
The `libnmdbus.a` target is missing, which should force the generation of files needed by `libNetworkManagerBase.a`.

**Comment by jpakkane** [comment]
If nmdbus has generated headers that base.a uses, then those need to be explicitly put in the source list of base.a somehow (usually by a `declare_dependency` whose `sources` includes said headers). Simply having a link with between two static libraries does not add a link between them because the dependency .a file does not need to exist before building the dependent .a. Enforcing this kind of serialisation would inhibit build parallelism.

If this is not enough to fix the issue, please post the full error message you get when compiling.

**Comment by inigomartinez** [comment]
You're right, and I suspected that that was the right answer. Actually, the headers can't be used directly because those sources are generated using [gnome.gdbus_codegen](http://mesonbuild.com/Gnome-module.html#gnomegdbus_codegen) which returns an opaque object. I have included a `FIXME` comment in a [path](https://mail.gnome.org/archives/networkmanager-list/2018-January/msg00039.html) that I have sent today, though I wasn't fully sure.

The main issue with glib's `gdbus-codegen` is that it [generates the header and the body file at the same time](https://bugzilla.gnome.org/show_bug.cgi?id=789877#c16). However, there are some [patches](https://bugzilla.gnome.org/show_bug.cgi?id=791015#c10) on the way.

Thank you for your kind support,
