### ISSUE TITLE
D: Unknown compiler "dmd"

### ISSUE THREAD

**Issue by puffi** [mesonbuild/meson#2895]
Error: `Unknown compiler "dmd"`
dmd --version output:
`
DMD64 D Compiler v2.078.0
Copyright (c) 1999-2017 by The D Language Foundation written by Walter Bright
`
This is on Arch Linux, using `DC=dmd meson build` to generate the ninja file.
Looked at the code and the culprit might be: [https://github.com/mesonbuild/meson/blob/5133d8650fb12e1635fda6a36794fdff9262bb7a/mesonbuild/environment.py#L729](url)

**Comment by jpakkane** [comment]
[Already fixed in master](https://github.com/mesonbuild/meson/commit/5133d8650fb12e1635fda6a36794fdff9262bb7a). Will be in 0.44.1.

**Comment by puffi** [comment]
Just a quick question: if the string returned by dmd --version is split on '\n', only the first part `DMD64 D Compiler v2.078.0` is searched for `The D Language Foundation`? If so, it won't find it as there's a new line before `Copyright (c) 1999-2017 by The D Language Foundation written by Walter Bright`. Don't know if i misunderstood the code though.

**Comment by puffi** [comment]
Forget it, read it all wrong.
