### ISSUE TITLE
include_directories should transform to string natively

### ISSUE THREAD

**Issue by ignatenkobrain** [mesonbuild/meson#2899]
`cxx.has_header('catch.hpp', args : '-I@0@'.format(inc_catch))` gives interesting result of ` 51 Command line:  c++ -I<Holder: <IncludeDirs /['/usr/include/catch']>> /tmp/tmp6di8ir9w/testfile.cpp -O0 -fpermissive -std=c++14 -pipe -D_FILE_OFFSET_BITS=64 -E -P`

**Comment by jpakkane** [comment]
Why aren't you using `include_directories` kwarg for this?

Regardless of that, automatic implicit string conversions are terrible for reliability and will not be added anywhere without a really damn good reason.

**Comment by ignatenkobrain** [comment]
@jpakkane hmmm, because there is no such thing in documentation.

**Comment by jpakkane** [comment]
There is, it's below because the kwargs listed there are usable on all check methods.
