### ISSUE TITLE
Provide a way to install an empty directory

### ISSUE THREAD

**Issue by Salamandar** [mesonbuild/meson#2904]
Sometimes you need to create an empty directory (for third-party plugins, fonts, themes,…) as part of the software install. 
It does not seem currently possible. Maybe allow passing an empty subdir name to install_subdir to do the trick ?

**Comment by sunharis** [comment]
Is this issue being worked upon still ?
I have a requirement to create an empty directory at the /var/lib/ path of the target during the install time.

**Comment by whot** [comment]
I just blindly tried `install_subdir()` for a non-existing source directory and it looks like this works
```
$ ls
meson.build
$ cat  meson.build
project('test')
install_subdir('foobar', install_dir: get_option('prefix'))
$ meson build --prefix=$PWD/../_inst
...
$ ninja -C build install
$ ../_inst
└── foobar
1 directory, 0 files
```
If this is intended and not just by accident, documenting it would be a good solution to this bug.

**Comment by dcbaker** [comment]
I'm okay with making this a feature not an implementation detail, we should document it and add a test. @jpakkane, objections?

**Comment by whot** [comment]
ftr, as documented in #8292, the creation of nested directories doesn't work as expected, so that's a bug waiting to be fixed.

**Comment by sunharis** [comment]
Thank you!

**Comment by johan-bjareholt** [comment]
Even with this documentation, it is not possible to create an empty directory with a specific owner/group/mode.
So a proper install_dir command would be necessary for my use-case.
Until that exists I'll simply use meson.add_install_script with the following shell script.

```
#!/bin/sh
set -eu

# this is needed because the only way meson has to create empty directories                                                                       
# is with install_subdir which does not allow you to set mode for directory,                                                                      
# but only to set mode for files inside its directory.

if [ $# -ne 4 ]; then
  echo "Invalid amount of arguments passed to $0"
  exit 1
fi

dir=$1
owner=$2
group=$3
mode=$4

install -d -o $owner -g $group -m $mode $dir
```

**Comment by eli-schwartz** [comment]
Even with this documentation, it looks so ugly to actually do it that I'm still using meson.add_install_script as well!

**Comment by eli-schwartz** [comment]
Finally got around to doing this *properly*.

#9344
