### ISSUE TITLE
Problem with meson_version in meson.build file...

### ISSUE THREAD

**Issue by kepeter** [mesonbuild/meson#2906]
Hello,

My Fedora 27 reports me that I have **meson 0.44.0** but when building GNOME Builder with following header I get an error of wrong version...

**meson.build header:**
```meson
project('gnome-builder', 'c',
          license: 'GPL3+',
          version: '3.27.4',
    meson_version: '>= 0.44.0',
  default_options: [
                     'c_std=gnu11',
                     'cpp_std=c++11',
                     'warning_level=2',
                     'with_channel=other',
                   ],
)
```

**the error:**
`
Meson version is 0.43.0 but project requires >= 0.44.0.
`

It seems that changing the header to 43 solves the problem, however it seems to be a bug somewhere - can't say where...

Regards,
Peter

**Comment by TingPing** [comment]
output of `meson --version` and `which -a meson`

**Comment by kepeter** [comment]
rpm -q meson = meson-0.44.0-1.fc27.noarch
which -a meson = /usr/bin/meson
meson -v = 0.44.0

**Comment by kepeter** [comment]
I found the problem... It isn't meson but GNOME Builder... GNOME Builder does not uses the meson package installed on the system but - via flatpack - installs local toolchains according to the SDK/Platform one chooses to build against... Those installations have older versions of libraries and seems to be overlapping,,,
I'm closing this and move to GNOME... :-)

**Comment by TingPing** [comment]
The Flatpak runtime just got a Meson update.

**Comment by naveenmosess** [comment]
> `meson --version`
0
af b a n¯             ssssssssssssssssssssssas\\ela  0101
