### ISSUE TITLE
-Ddefault_library=static doesn't set the default_library option

### ISSUE THREAD

**Issue by djdeath** [mesonbuild/meson#2910]
Configuring a project with -Ddefault_library=static leaves subprojects' libraries dynamically linked.
Passing --default-library=static does make them link statically.

Similarly giving default_library: 'static' in the project doesn't work either : 
```
project('GPUTop', 'c', 'cpp',            
        version : '0.0.2',               
        default_options : [              
          'warning_level=2',             
          'c_std=gnu99',                 
        ],                               
        license : 'MIT',                 
        default_library : 'static',      
        meson_version : '>0.40.0')       
```

Is this expected behavior?

**Comment by jpakkane** [comment]
Are the subprojects using `library()` and not `shared_library()`?

What is the output of `meson configure` in said build dir? (specifically, the value of `default_library`)

**Comment by djdeath** [comment]
Subprojects are using ```library()```

```
$ meson configure
Core properties:
  Source dir /home/djdeath/src/mesa-src/gputop
  Build dir  /home/djdeath/src/mesa-src/gputop/meson-native

Core options:
  Option          Current Value Possible Values                                  Description
  ------          ------------- ---------------                                  -----------
  buildtype       debug         [plain, debug, debugoptimized, release, minsize] Build type to use.
  warning_level   2             [1, 2, 3]                                        Compiler warning level to use.
  werror          false         [true, false]                                    Treat warnings as errors.
  strip           false         [true, false]                                    Strip targets on install.
  unity           off           [on, off, subprojects]                           Unity build.
  default_library static        [shared, static]                                 Default library type.

  Option            Current Value Description
  ------            ------------- -----------
  backend_max_links 0             Maximum number of linker processes to run or 0 for no limit

Base options:
  Option      Current Value Possible Values                                               Description
  ------      ------------- ---------------                                               -----------
  b_asneeded  true          [true, false]                                                 Use -Wl,--as-needed when linking
  b_colorout  always        [auto, always, never]                                         Use colored output
  b_coverage  false         [true, false]                                                 Enable coverage tracking.
  b_lto       false         [true, false]                                                 Use link time optimization
  b_lundef    true          [true, false]                                                 Use -Wl,--no-undefined when linking
  b_ndebug    false         [true, false]                                                 Disable asserts
  b_pch       true          [true, false]                                                 Use precompiled headers
  b_pgo       off           [off, generate, use]                                          Use profile guided optimization
  b_sanitize  none          [none, address, thread, undefined, memory, address,undefined] Code sanitizer to use
  b_staticpic true          [true, false]                                                 Build static libraries as position independent

Compiler arguments:
  c_args ['-O0', '-g']
  cpp_args ['-O0', '-g']

Linker args:
  c_link_args ['-O0', '-g', '-L/home/djdeath/src/mesa/lib', '-L/home/djdeath/src/gnome-build/lib']
  cpp_link_args ['-O0', '-g', '-L/home/djdeath/src/mesa/lib', '-L/home/djdeath/src/gnome-build/lib']

Compiler options:
  Option       Current Value Description
  ------       ------------- -----------
  c_std        gnu99         C language standard to use
  cpp_debugstl false         STL debug mode
  cpp_std      none          C++ language standard to use

Directories:
  Option         Current Value        Description
  ------         -------------        -----------
  prefix         /usr/local           Installation prefix.
  libdir         lib/x86_64-linux-gnu Library directory.
  libexecdir     libexec              Library executable directory.
  bindir         bin                  Executable directory.
  sbindir        sbin                 System executable directory.
  includedir     include              Header file directory.
  datadir        share                Data file directory.
  mandir         share/man            Manual page directory.
  infodir        share/info           Info page directory.
  localedir      share/locale         Locale data directory.
  sysconfdir     etc                  Sysconf data directory.
  localstatedir  /var/local           Localstate data directory.
  sharedstatedir /var/local/lib       Architecture-independent data directory.

Project options:
  Option Current Value Possible Values Description
  ------ ------------- --------------- -----------
  webui  false         [True, False]   webui

Testing options:
  Option    Current Value Possible Values Description
  ------    ------------- --------------- -----------
  stdsplit  true          [true, false]   Split stdout and stderr in test logs.
  errorlogs true          [true, false]   Whether to print the logs from failing tests.
```

**Comment by djdeath** [comment]
I think I figured part of the problem.
For the project option I need to set the value in the default_options rather that through ```project()``` directly : 
```
project('GPUTop', 'c', 'cpp',        
        version : '0.0.2',           
        default_options : [          
          'warning_level=2',         
          'c_std=gnu99',             
          'default_library=static',  
        ],                           
        license : 'MIT',             
        meson_version : '>= 0.43.0') 
```

**Comment by inigomartinez** [comment]
There is some odd behaviour behind the `default library` option. The default command line option which is shown in meson's help says that the option to be used is `--default-library`. However, using `--default-library=[shared|static]` or `--default-library [shared|static]` makes no effect.

I've also used the `-Ddefault_library` option. In this case it seems that if the option is present, the option is always `shared`. For example `-Ddefault_library=static` is ignored.

**Comment by nirbheek** [comment]
> However, using --default-library=[shared|static] or --default-library [shared|static] makes no effect.

How are you testing this? I just tried this with a simple build file with just `library()` and it worked fine.

**Comment by djdeath** [comment]
Maybe there is something I don't get about the --default-library= vs -Ddefault_library=
I thought both would be equivalent, maybe they aren't?

**Comment by nirbheek** [comment]
> I thought both would be equivalent, maybe they aren't?

They are parsed at different points, and they are not equivalent. However, they should be, and the fact that this and a bunch of other options are not is a bug.

**Comment by inigomartinez** [comment]
> How are you testing this? I just tried this with a simple build file with just library() and it worked fine.

I tested this when trying to remove the duplicated ‘static‘ user option from
libgnome-volume-control. Please see [this](https://bugzilla.gnome.org/show_bug.cgi?id=792948#c18).

**Comment by inigomartinez** [comment]
I have done some modifications to use `default_library` parameter along with `libgnome-volume-control`, to avoid the duplication of this feature in the `static` user option. You can use the [following repository](https://gitlab.gnome.org/inigomartinez/libgnome-volume-control). Although the project is expected to be used as a subproject, I have removed that limitation so it can be used as a standalone project. My results when testing it are as follows:

* `meson --prefix=/tmp/gvc --libdir=lib --default-library static builddir` -> `static`
* `meson --prefix=/tmp/gvc --libdir=lib --default-library shared builddir` -> `static`
* `meson --prefix=/tmp/gvc --libdir=lib -Ddefault_library=static builddir` -> `shared`
* `meson --prefix=/tmp/gvc --libdir=lib -Ddefault_library=shared builddir` -> `shared`

Actually the goal of this modifications is to be able to choose between a `static` or `shared` library from a parent project when using `libgnome-volume-control` as a subproject. However, at the moment, setting a different option for a subproject [is not possible](https://github.com/mesonbuild/meson/issues/2289#issuecomment-361328046).

**Comment by nirbheek** [comment]
This was fixed with https://github.com/mesonbuild/meson/pull/3612.
