### ISSUE TITLE
AC_TRY_LINK functionality

### ISSUE THREAD

**Issue by ieei** [mesonbuild/meson#293]
autotools/autoconf has `AC_TRY_LINK` which tries to link, which could be useful instead of only `compiler.compiles()` (The underlying functionality for `has_function()` and friends).

In GLib this is used like this:
```
AC_CACHE_CHECK([for __libc_enable_secure], glib_cv_have_libc_enable_secure,
  [AC_TRY_LINK([#include <unistd.h>
    extern int __libc_enable_secure;],
    [return __libc_enable_secure;],
   glib_cv_have_libc_enable_secure=yes,
   glib_cv_have_libc_enable_secure=no)])
AS_IF([test x$glib_cv_have_libc_enable_secure = xyes], [
   AC_DEFINE(HAVE_LIBC_ENABLE_SECURE, 1,
     [Define if you have the __libc_enable_secure variable (GNU libc, eglibc)])
])
```

It could be useful to add something similar in Meson. Meson has `compiler.run()`, but that isn't that useful when cross compiling.

**Comment by jpakkane** [comment]
I added a link checker in the linkargs branch. Please test if it works for you (sample test is in `test cases/linuxlike/2 external library`).

**Comment by ieei** [comment]
LGTM! and it works in my working tree. Ship it! :+1:
