### ISSUE TITLE
Rethink build types

### ISSUE THREAD

**Issue by jpakkane** [mesonbuild/meson#2939]
Currently we have a few project types, `plain`, `debug` etc. This is straightforward and simple but also lacks in flexibility. For example the release mode builds with `-O3` but without `-g`. This is a bit unfortunate as people might want to have both of these at the same time.

It would be nice to be able to mix and match types better while still preserving backwards compatibility.

One approach would be to add new core options such as `optimization_level` which is a combo with values `0`, `1`, `2`, `3` and `size`, and `debug_info` which is a boolean. These could be toggled freely but setting `buildtype` to, say, `debugoptimized` would set optimization value to 2 and debug to true. Setting build flags to a combination that is not any of the preset ones would change the buildtype to `custom`.

**Comment by ignatenkobrain** [comment]
Something like Rust's model is probably what you are looking for... -Copt-level=3 -Cdebuginfo=2

**Comment by phillipjohnston** [comment]
This can be closed now, right? @jpakkane
