### ISSUE TITLE
Names created by meson should not have '@' in them

### ISSUE THREAD

**Issue by winksaville** [mesonbuild/meson#294]
Currently in build.py the type_suffix method returns suffixes of the form xxxx@yyy it is unusual to have an '@' in a file or directory and I ran into a case where the gcc linker script looks to interpret '@' in directories in a special manner, see [this](https://github.com/winksaville/baremetal-hi/commit/d358e064bb6526df2a221d022df600093cd61c89) from Jussi for my [baremetal-hi](https://github.com/winksaville/baremetal-hi) project and [this](https://github.com/mesonbuild/meson/pull/291) pull request of mine to meson.

My pull request is not acceptable because '@' is special and those uses of it need to be considered.

Doing the follow grep of the code base most of the uses of '@' are either meson variable substitution or python decorators:
```
find . -type f -name '*.py' -print0 | xargs -0 grep '@'
...
./vs2010backend.py:51:                args = [x.replace("@INPUT@", infilename).replace('@OUTPUT@', sole_output)\
./vs2010backend.py:53:                args = [x.replace("@SOURCE_DIR@", self.environment.get_source_dir()).replace("@BUILD_DIR@", self.get_target_private_dir_abs(target))
./mesonlib.py:29:    @staticmethod
./mesonlib.py:35:    @staticmethod
./mesonlib.py:39:    @staticmethod
./mesonlib.py:205:        line = line.replace('@' + varname + '@', var)
./mesonlib.py:233:    regex = re.compile('@(.*?)@')
```
Here are the type_suffix uses:
```
./build.py:614:        return "@exe"
./build.py:634:        return "@sta"
./build.py:705:        return "@sha"
./build.py:827:        return "@cus"
./build.py:861:        return "@run"
./build.py:875:        return "@jar"
```
And two possibly interesting cases:
```
./tools/cmake2meson.py:39:            ('id', re.compile('''[,-><${}=+_0-9a-z/A-Z@.*]+''')),
./build.py:186:        return self.subproject + '@@' + base
```
Of course I may be way off base.

**Comment by ieei** [comment]
Hmm, I fail to understand your reasoning. Why exactly do you want meson not to produce file names/directories with `@`? Maybe output from whats actually failing or steps to reproduce would help me and others?

**Comment by jpakkane** [comment]
This issue has actually been dealt with already so closing.

**Comment by marc-hb** [comment]
For the record this was discussed in PR #291 (not sure why it wasn't automatically "backlinked")

**Comment by marc-hb** [comment]
Just FYI: `Is BUILD_DIR = executable.get_id() OK? For: configure_file('linker_script.ld', BUILD_DIR)` #5995

**Comment by marc-hb** [comment]
New! Add a binutils module #6063
