### ISSUE TITLE
Build debugoptimized with -Og

### ISSUE THREAD

**Issue by snsmac** [mesonbuild/meson#2940]
I think it would be a good idea to compile with -Og when running a debugoptimized build.
From the gcc manual:

> -Og
Optimize debugging experience. -Og enables optimizations that do not interfere with debugging. It should be the optimization level of choice for the standard edit-compile-debug cycle, offering a reasonable level of optimization while maintaining fast compilation and a good debugging experience.

Clang does also support this option

**Comment by 1ace** [comment]
There was already a discussion about this: #509

From what the docs say, `-Og` should be better than `-O0` for debugging, but in my personal experience `-Og` does too many optimisations and removes too many symbols to be able to debug comfortably anymore.
My vote is to keep `-O0`.

**Comment by snsmac** [comment]
@1ace I only had good experiences with -Og and clang. -O0 can be unusable because the code is really slow.
Personally i would fill a bug agaist the compiler if -Og has a bad impact on debugging

**Comment by nirbheek** [comment]
Filing a bug against the compiler is certainly an option, but it usually leads to no progress at all.

If you really want to use -Og for your projects, you should use `--buildtype=plain` and add your own CFLAGS/c_args.

**Comment by nirbheek** [comment]
We can revisit this if `-Og` improves in debug ability, keeping the issue closed to reduce clutter.

**Comment by okias** [comment]
Yeah, debugoptimized SHOULD be the `-Og` where is possible.
