### ISSUE TITLE
Add project-wide `include_directories` object?

### ISSUE THREAD

**Issue by haasn** [mesonbuild/meson#2944]
Say I have a project with several libraries and several executables. I want them to all share an `include_directories` object. Rather than having to append `include_directories: inc` to every sincle `executable()` / `library()` and whatnot, would it be possible to add an include_directories as a project-wide setting?

Ideally I'd imagine something like an `add_project_include_directories` alongside the `add_project_arguments` and so forth.

**Comment by jpakkane** [comment]
Yes, this would make sense. Patches welcome. :)

**Comment by phillipjohnston** [comment]
Given that I just found a need for this in my own project, I will add it to my list to tackle in the coming month or two.

**Comment by xclaesse** [comment]
What about `add_project_arguments(include_directories('.'), language : 'c')` ?

**Comment by phillipjohnston** [comment]
Does that work, or is that what you're proposing as the interface?

**Comment by xclaesse** [comment]
Suggesting as interface, instead of adding new function.

**Comment by eli-schwartz** [comment]
Duplicate of #10206

**Comment by eli-schwartz** [comment]
Duplicate of #1139

**Comment by eli-schwartz** [comment]
Also note that that ticket is closed as implemented in Meson 0.63.0
