### ISSUE TITLE
Meson rebuilds everything on meson.build file change

### ISSUE THREAD

**Issue by Salamandar** [mesonbuild/meson#2946]
Hi,
Meson seems to rebuild every obj file on any meson.build change (even touch).
That's not a Ninja issue as CMake+Ninja does not have this behaviour. Does Meson internally store build informations, to know which targets need rebuild ?

**Comment by jpakkane** [comment]
No. This might be caused by timestamps getting out of whack (though it is very rare). If this keeps happening, post specific details of your setup.

**Comment by Salamandar** [comment]
That's strange. I've been using Meson on windows, multiple linux distros, multiple PCs, and ever had that behaviour. 

EDIT : That's related to a `configure_file`'d `config.h` : 

    ninja explain: output libs/rgbe/rgbe@sta/rgbe.c.o older than most recent input config.h (1516357787 vs 1516357810)
    ninja explain: libs/rgbe/rgbe@sta/rgbe.c.o is dirty

That means the configuration used for the configure_file is not detected as "unchanged" even if it didn't change… And that this configure_file is used as input for *every* target (well, why not).

Meson should re-write the configure_file only if its content changed (the easiest way would be to write a temp file, compare both files, and replace if needed).

**Comment by Salamandar** [comment]
Okay, found the bug. When 'input' is specified, the expected behaviour occurs. But if 'input' is not given, the output file is directly written, without a temporary file.

**Comment by rulatir** [comment]
Wait, so meson relies on timestamps? I thought it only relied on hashes...

**Comment by Salamandar** [comment]
It does not. It writes the temporary file then compares it to the existing file, replacing only if necessary to prevent any unnecessary rebuilds.
