### ISSUE TITLE
Inconsistency in compiler flags checking vs building

### ISSUE THREAD

**Issue by ieei** [mesonbuild/meson#296]
This is an observation more than a bug report. I'm not sure if this actually is a bug. Please close and educate me if the latter is the case!

I was checking for `setenv` which according to internets and the man page:
```
CONFORMING TO
       4.3BSD, POSIX.1-2001.
```
Meaning, not part of the ISO C standard.

When checking for `setenv` I used
```
cc = meson.get_compiler('c')

conf = configuration_data()
if cc.has_function('setenv', prefix : '#include <stdlib.h>')
  conf.set('HAVE_SETENV', 1)
endif
configure_file(input : 'config.h.in', output : 'config.h', configuration : conf)
```
this invokes the compiler like this (according to the logs):
```
Native c compiler: cc (gcc 4.9.2-10ubuntu13)
Running compile:
Command line:  cc -c /tmp/tmpk_7alfwn.c
Code:
 #include <stdlib.h>
int main(int argc, char **argv) {
    void *ptr = (void*)(setenv);
    return 0;
};

Compiler stdout:
 
Compiler stderr:
 
Checking for function "setenv": YES
```
But when I build/compile my simple executable the compiler is invoked with -std=c11 which is default
```
[1/2] cc  '-pipe' '-Wall' '-Winvalid-pch' '-std=c11' '-g' '-Isetenvtest@exe' '-I.../meson/test cases/common/95 setenv' '-I.' '-MMD' '-MQ' 'setenvtest@exe/prog.c.o' '-MF' 'setenvtest@exe/prog.c.o.d' -o 'setenvtest@exe/prog.c.o' -c '.../meson/test cases/common/95 setenv/prog.c'
.../meson/test cases/common/95 setenv/prog.c: In function ‘main’:
.../meson/test cases/common/95 setenv/prog.c:8:3: warning: implicit declaration of function ‘setenv’ [-Wimplicit-function-declaration]
   return setenv ("FOO", "BAR", 0);
   ^
[2/2] cc    -o setenvtest 'setenvtest@exe/prog.c.o'  
```
This yields `__STRICT_ANSI__` and gives a warning because `setenv` isn't declared.

Are there anything I should do or anything meson could do to fix this? It seems a bit weird that the configuration step says yay, we have setenv, but when using it, it will complain.

**Comment by jpakkane** [comment]
The reason Meson does not automatically put anything in the compile flags for tests is that you may need to run compile tests without those flags. As an example you might need to compile some test first with -std=c99 and then with -std=c11 before choosing which one to use. If project flags were used automatically that would not be possible.

You can fix this particular issue by specifying extra arguments to the compile test with `args` keyword argument. There should probably be a "get the default flags" kinda thing that you could pass to the tests, but that requires some thinking as it is not immediately obvious how it should be done.
