### ISSUE TITLE
meson test - why save full path to exe?

### ISSUE THREAD

**Issue by rhd** [mesonbuild/meson#2963]
Hi,

It looks like `meson` is saving the full path to all `test` executables in `meson_test_setup.dat`. I'm wondering why this is as it's breaking my CI setup.

I'm wondering if we can safe the relative path of the test executable instead of the full path? I can't think of a situation where this breaks... can you?

**Comment by jpakkane** [comment]
Absolute paths are safe against changes in `PATH`. It is fairly common to want to build and run an executable that is already in the system already.

**Comment by rhd** [comment]
Right, but the test exe's are built with meson and thus live in the build directory. A full path is not needed in this case. A full path in this cases causes havoc with CI. I didn't know this until just before I posed this message, but I had a CI runner executing a test from a different runner's build directory.

My specific example:

```python
wlltest = executable('wlltest' + ext, src,
  dependencies: [deps],
)

test('WLL Test', wlltest)
```

`wlltest` lives in the build directory and thus meson should be able to use relative paths with 100% certainty nothing will break as long as we record the path relative to the build directory.

Are there edge cases I'm not thinking about?

**Comment by jpakkane** [comment]
Just to be sure:

Meson build dirs are _not_ movable. If you set up a build dir in a specific (absolute) path, it is only guaranteed to work in the exact same directory. If it gets relocated, the behaviour is undefined. There are a ton of weird things that can go wrong if the directory is changed.

**Comment by rhd** [comment]
Ok, I see what you're saying. I just with there was some middle ground with regard to these paths. Currently, meson is very CI unfriendly. I guess most of these issues go away with a switch to using docker for builds/tests as this normalizes the paths.

In the mean time, I can just call the tests directly from CI like `./build/tests/wlltest`

I'll close this issue. Thanks for responding.
