### ISSUE TITLE
gettext priorize local its files

### ISSUE THREAD

**Issue by inigomartinez** [mesonbuild/meson#2968]
Since meson 0.36, the `i18n` module's `gettext` function can use the `data_dir` parameter to set `GETTEXTDATADIRS` and use local `its` files. However, if the same `its` file is present in the host system, it would take preference over the passed directory. This would make any update made to the local `its` files not to work.

It would be nice to priorize the local `its` files.

**Comment by TingPing** [comment]
This is a bug you'll need to report upstream to `gettext` as Meson does nothing beyond calling the regular tools.

**Comment by inigomartinez** [comment]
You are right. I have opened a bug at [savannah](https://savannah.gnu.org/bugs/index.php?52966).
