### ISSUE TITLE
Suppress ranlib warning when building on macOS

### ISSUE THREAD

**Issue by kirushyk** [mesonbuild/meson#2977]
It looks like there is no way to pass "-no_warning_for_no_symbols" command line argument to ranlib.

**Comment by nirbheek** [comment]
It's not clear what the issue is here, could you please elaborate?

**Comment by eli-schwartz** [comment]
Closing due to lack of information about what the problem is.

Feel free to re-open if this is still a problem and the problem can be described in greater detail.
