### ISSUE TITLE
Solution for combining multiple static libraries doesn't support merging external static libs

### ISSUE THREAD

**Issue by compenguy** [mesonbuild/meson#2980]
This is like issue #205, but instead of my input staticlibs being produced by my meson build, they were supplied to me externally.

If I'm supplied libfoo.a, and I want to build a wrapper for it libfoo_wrapper.a and have it all merged together in the end, the following doesn't work, because extract_all_objects() was only implemented on static_library() objects, but doesn't exist on find_library() objects:
```
foo_staticlib = cpp.find_library('foo')
foo_objs = foo_staticlib.extract_all_objects() # <- extract_all_objects isn't implemented on found libraries, so this won't work
static_library('foo_wrapper', ['foo_wrapper.cpp'], objects: foo_objs)
```

**Comment by nirbheek** [comment]
Duplicate of https://github.com/mesonbuild/meson/issues/2478.

**Comment by Bassem-Ramzy** [comment]
Have a look on and follow [this related solution](https://github.com/mesonbuild/meson/pull/9218)
