### ISSUE TITLE
multi-line comments

### ISSUE THREAD

**Issue by mjsurette** [mesonbuild/meson#2981]
One thing that I would like to propose as an enhancement is multi-line comments which would be a mix of the CMake multi-line comment with a Lua style enhancement.
#[[ would introduce a multi-line comment
#]] would end it
##[[ would be considered a single line comment.  In this case the corresponding #]] would also be considered a single line comment, thereby uncommenting the block.

I feel that this would make it easier to develop and document meson.build scripts.

**Comment by nirbheek** [comment]
Python seems to do just fine without multi-line comments. However, if you really want them, one easy way is to use:

```meson
'''
some code
that you want to
comment
'''
```

This will create a multi-line string out of it and discard it.

**Comment by mjsurette** [comment]
Awesome.  Thanks for the pointer.
