### ISSUE TITLE
google + meson github wiki

### ISSUE THREAD

**Issue by lazka** [mesonbuild/meson#2988]
Just something I've noticed, searching for anything "meson xxx" gives the empty wiki pages as first results. Maybe the wiki could be removed?

**Comment by jpakkane** [comment]
Empty pages or ones pointing to the real website?

**Comment by lazka** [comment]
The ones linking to the real website.

**Comment by nirbheek** [comment]
I suspect that the fact that the new website is all generated in JS is causing it to have a lower google rank.

**Comment by lazka** [comment]
Tested some commands and looks like the real docs win now.
