### ISSUE TITLE
MSYS2 support question

### ISSUE THREAD

**Issue by lazka** [mesonbuild/meson#2989]
We have some downstream patches in MSYS2 now to work around MSYS2 quirks etc: https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-meson

Is this something you'd want to be upstreamed even if it only applies to MSYS2?

```python
# using something like this for detection...
def is_msys2():
    return is_windows() and os.environ.get("MSYSTEM", "")
```

**Comment by jpakkane** [comment]
If they improve MSYS2 and don't break any other platform, sure.

**Comment by lazka** [comment]
ok :)
