### ISSUE TITLE
Add --no-rebuild to meson install

### ISSUE THREAD

**Issue by rhd** [mesonbuild/meson#3003]
I can run `meson test` without meson attempting to rebuild anything. I'd really like to `meson install` without rebuild. Possible?

**Comment by nirbheek** [comment]
It would involve implementing a `meson install` target, but it could be done.

**Comment by rdiez** [comment]
Is this not done already? Argument "--no-rebuild" is documented under "install" in [https://mesonbuild.com/Commands.html](https://mesonbuild.com/Commands.html)

Or does that not work with the "meson test" mentioned above?
