### ISSUE TITLE
Document dependency('python3') and add reference to it from Python3 module

### ISSUE THREAD

**Issue by sarum9in** [mesonbuild/meson#3009]
In order to build python extension it is convenient to use `python3.extension_module()`. The problem is user must specify `include_directories`, which is non-trivial to get from current `python3` module. I would imagine using `include_directories(python3.sysconfig_path('include'))`, but this path is relative. Looking at source code of `python3.sysconfig_path()`, it strips prefix, so there is no way to retrieve it. This makes sense if you use this path for installation but you need to have actual full path for dependencies. I see 2 options

### set include_directories in extension_module()
Every single python module built has to include correct `pyconfig.h`, so since `python3` module is already bound to a specific python version, meson may just provide include_directories.

This option seems to be more in line with meson ideology of keeping things simple for user.

```python
python3 = import('python3')
python3.extension_module('hello', [...],
    # include_directories not specified,
    # defaults to /usr/include/python3.6m from sysconfig_path()
    # ...
)
```

```python
python3 = import('python3')
python3.extension_module('hello', [...],
   include_directories : [
        # python3 prepends /usr/include/python3.6m from sysconfig_path
        include_directories(project_specific_include),
    ],
    # ...
)
```

### add relative/absolute/with_prefix/etc keyword to python3.sysconfig_path()
This is more boilerplate but allows more flexibility.

```python
python3 = import('python3')
python3.extension_module('hello', [...],
    include_directories : [
        include_directories(python3.sysconfig_path('include', relative : false)),
        # include_directories(python3.sysconfig_path('include', absolute : true)),
        # include_directories(python3.sysconfig_path('include', with_prefix : true)),
    ],
    ...
)
```

**Comment by sarum9in** [comment]
#2859 is related

**Comment by nirbheek** [comment]
> I would imagine using `include_directories(python3.sysconfig_path('include'))`

[`include_directories()`](http://mesonbuild.com/Reference-manual.html#include_directories) is for directories that are inside the source tree, so this is not correct.

Could you describe the problem, with a description of your setup and perhaps a test case? It's difficult to review/understand your solutions when it's not clear what the issue is.

**Comment by sarum9in** [comment]
OK, I read some source code and `test cases/python3/2 extmodule` and now I realize there is `dependency('python3')`, however it was non-obvious that it exists. There is a custom `Python3Dependency` class that does the job and there is a single occurrence of the usage in source code, `git grep "dependency('python3')"` shows test case I mentioned above, so this is documentation problem.

```meson
py3_dep = dependency('python3', required : false)
...
pylib = py3_mod.extension_module('tachyon',
  'tachyon_module.c',
  dependencies : py3_dep,
)
```

It could be worth to consider including `python3` dependency by default via `extension_module` but maybe it is not desired in some cases, I am not sure. Anyway I can add a reference to `python3` dependency on http://mesonbuild.com/Python-3-module.html if you think this is the right place.

**Comment by nirbheek** [comment]
We should probably add the python 3 dependency automatically, but we need to think about the interaction there. For instance, right now the python3 module always returns the python that is currently running Meson, while the python3 dependency may not.

For now, it makes sense to document python3 dependency like you said. Please open a PR for that, thanks!
