### ISSUE TITLE
add_global_link_arguments applies to cross compiler AND native compiler

### ISSUE THREAD

**Issue by tlawork** [mesonbuild/meson#3014]
I have a cross compiler that requires a --sysroot option be passed in when running the linker.
So I set a global link option like this:

`add_global_link_arguments('--sysroot=xxxxxxxxxxxx', language : 'c')
`

I need this to be a global option because the majority of subdir compilations are cross compiled.  HOWEVER, I found that it is applying that global link argument to the NATIVE HOST COMPILER as well -
 and this is throwing an error since that is not a valid argument for the host compiler.

That does not seem to be very intuitive and I would suggest this is wrong behavior.  If a cross compile is active then adding global options should apply to the cross compiler and if host only variables are needed, they should be specified more preferably as a new function: add_global_native_link_arguments function.

In the meantime as this potential bug is discussed what would be the workaround short of having to add an add_project_link_arguments in every meson.build file?

thanks

**Comment by tlawork** [comment]
This is actually a show-stopper for me - I have a single project declaration - and a huge number of subdir( ) commands to process the individual libraries and programs and unit tests.  All of my unit tests will break if the global link option propagates to the host compiler.  BUT the issue is even if I were to use a project_link_arguments - since I have one big project, that would not help - I will be constrained to modifying every meson.build file to include link_args directly - and that I hope makes this worthy of accepting as a bug.

**Comment by jpakkane** [comment]
This is a bug and it needs to be fixed. However you should be able to put `--sysroot` et al flags to your cross file in `c_args` or `cpp_args` and it should do the right thing.

**Comment by tlawork** [comment]
I have worked around this problem by supplying the sysroot parameter in the definition of the LD in cross compile file:
[binaries]
ld = '/path/to/cross-ld --sysroot /path/to/sysroot'

This seems to have fixed my issue - If this needs to be the solution to this bug then so be it - however I believe that a function called: add_global_host_link_argument and add_project_host_link_argument should be created and that data dictionary used when doing a native:true build.

**Comment by jpakkane** [comment]
That should not do anything. We always invoke linker via the compiler. You should be able to set it with `link_args` like this:

    link_args = ['--sysroot', '/path/to/sysroot']

(or using `c_link_args` or `cpp_link_args` as appropriate)

**Comment by nirbheek** [comment]
I am confused. You are not supposed to add platform-specific options in your build files at all, especially not in `add_global_link_arguments()`. That's what the cross-file is for.

**Comment by tlawork** [comment]
Please tell me how to add a c and link option to the cross compile file. If
I add it to the definition of c='/path/to/gcc' it does not work. It says
can not find compiler

**Comment by nirbheek** [comment]
1. c/cpp definitions are arrays, not space-delimited strings.
2. You can add extra args like this:

```
[properties]
# C arguments
c_args = ['-DFOO="foo"', '--sysroot=blah']
# C++ arguments
cpp_args = ['-DFOO="foo"', '--sysroot=blah']
```

For more info, see: http://mesonbuild.com/Cross-compilation.html#defining-the-environment

**Comment by tlawork** [comment]
i am going to close this based on the previous response.  I missed this portion of the cross compile documentation page.  However, I created a pull request for the reference manual to make this more clear.

**Comment by tlawork** [comment]
I am reopening this due to the differing point of views that were expressed in my Pull Request intending to make it more clear how it works.  However I agree that this should be fixed rather than tolerated.  If core developers agree to not fix this - then I will let you close this with no action.

**Comment by nirbheek** [comment]
This is no longer applicable since 0.48, we have a kwarg for controlling this: `native:`.
