### ISSUE TITLE
Providing Output of Tests

### ISSUE THREAD

**Issue by computerquip-streamlabs** [mesonbuild/meson#3017]
It would be useful to know why the tests fail by providing their output somehow. For instance, if a call to `compiles` fails, it would be nice if I can fetch the output and write that to a file somewhere.

**Comment by jpakkane** [comment]
At the end of a test run Meson prints the location of the test log file that should have all that information.

**Comment by computerquip-streamlabs** [comment]
Oh, I missed that entirely. Thanks.
