### ISSUE TITLE
XCode generator not working for non-install lib + exe config.

### ISSUE THREAD

**Issue by germandiagogomez** [mesonbuild/meson#302]
My use case is the following:

```
root/
    meson.build
    exe/
        meson.build
    library/
        meson.build
```

The project is at the root. The library is not installed, it is just used by the executable.

When I do the following from the root dir:

``` sh
meson/meson.py --backend xcode build-xcode
```

I get the following error:

```
Dependency Boost (signals, regex, serialization, system) found: YES (1.55)
Dependency Boost (test) found: YES (1.55)
Dependency Boost (program_options, filesystem, iostreams, system) found: YES (1.55)
Dependency Boost () found: YES (1.55)
Build targets in project: 3
Traceback (most recent call last):
  File "meson/meson.py", line 209, in run
    app.generate()
  File "meson/meson.py", line 162, in generate
    g.generate(intr)
  File "/Users/germandiago/git/guinyote-project/meson/xcodebackend.py", line 93, in generate
    self.generate_pbx_native_target()
  File "/Users/germandiago/git/guinyote-project/meson/xcodebackend.py", line 419, in generate_pbx_native_target
    idval = self.pbx_dep_map[lt.get_basename()]
KeyError: 'guinyote'
```

**Comment by jpakkane** [comment]
The XCode backend has not had a lot of love recently and has bitrotted. This is mainly caused by two things: there is only a limited amount of time and effort that can be put in this project and secondly XCode's file format is a lovecraftian horror experience that will destroy your soul if you look too deeply unto it.

**Comment by germandiagogomez** [comment]
> This is mainly caused by two things: there is only a limited amount of time and effort that can be put in this project and secondly XCode's file format is a lovecraftian horror experience that will destroy your soul if you look too deeply unto it.

I can tolerate this in Mac OSX, even if I'd rather have it working. After all we have ninja. But now that you mention, how about Visual Studio support? I am choosing Meson over CMake for several reasons, among them, easier to learn, but, if Visual Studio is not well supported that would be a big problem for me and would have to consider CMake. :)

**Comment by jpakkane** [comment]
Visual studio compiler works seamlessly with the Ninja backend. The VS2013 project generator is in a bit better shape than the XCode backend but is probably not good enough for serious work.

**Comment by germandiagogomez** [comment]
> Visual studio compiler works seamlessly with the Ninja backend. The VS2013 project generator is in a bit better shape than the XCode backend but is probably not good enough for serious work.

I like what I saw for now from Meson. Way better than cmake, but still not as mature in some areas. I really think that for getting more adoption,
it is a must to have at least a good visual studio generator. I do know I am just asking without contributing.

Is there a way to discuss about the project when I can throw a couple of opinions/ideas? I am all for Meson if it can generate projects for Visual Studio, because I think this is the killer feature of CMake.

**Comment by scivision** [comment]
I believe this is a stale/corrected issue as Xcode backend seems to work correctly here.
