### ISSUE TITLE
Add check for meson version at feature use

### ISSUE THREAD

**Issue by Salamandar** [mesonbuild/meson#3022]
It's currently difficult to evaluate which minimum Meson version a project requires.

For instance, when using Meson 0.45.0, I could write `meson_version: '>=0.1.0'` without Meson warning about using new features since 0.1.0.
CMake partly does that.

Some decorator `@feature_version('>=0.40.0')` in the Meson code could help diagnose meson_version.

That could be used on function call, function argument call,...

**Comment by nirbheek** [comment]
This makes a lot of sense, but it's difficult to support in the codebase. Ideally, you should run your CI on the minimum version of meson you support (to maintain backwards-compat), and also on the latest version (to check for regressions).

**Comment by Salamandar** [comment]
Everyone does not have a CI framework in place, and it's obviously less efficient ;)
If you're not against it, I can do a pull request someday adding the decorator feature. Then, it'll just be a matter of adding it everywhere needed !

**Comment by nirbheek** [comment]
Sounds good, but how would you handle, f.ex, the addition of new kwargs to existing functions?

**Comment by Salamandar** [comment]
I'm not sure it's doable, but some decorator could be added :

    @version_new_kwarg('>=0.40.0', 'thekwarg')

Then in the decorator, check if thekwarg: was passed in the meson code.

**Comment by nirbheek** [comment]
I'm sure you can come up with something after thinking about it for a while, I look forward to your PR 👍

**Comment by Salamandar** [comment]
That may take some time to come but I'll definitely work on this !

**Comment by Salamandar** [comment]
I finally started to work on it here :
https://github.com/Salamandar/meson/tree/salamandar/meson_version_introspection

**Comment by Salamandar** [comment]
That gives something like that (yeah i know, those version numbers don't mean anything):
![capture du 2018-04-26 15-27-22](https://user-images.githubusercontent.com/6552989/39308693-5aff8356-4966-11e8-852c-f28e054e4b0e.png)

**Comment by eli-schwartz** [comment]
This never got closed when the linked PR was merged.
