### ISSUE TITLE
subprojects always inherit c_std and cpp_std from the parent project

### ISSUE THREAD

**Issue by dcbaker** [mesonbuild/meson#3025]
If I have a project that uses `c_std=c99` and a subproject that uses `c_std=gnu99`, then the subproject will be compiled with `c_std=c99`. This might be fine, or there might be gnu extensions in use in the subproject.

**Comment by nirbheek** [comment]
We have discussed this elsewhere in issues and PRs, and it's not clear what we should do in this case.

I think at least `c_std` does not need to be inherted by subprojects because there is no ABI incompatibility between various C standards.

**Comment by nirbheek** [comment]
Duplicate of https://github.com/mesonbuild/meson/issues/1889
