### ISSUE TITLE
compile_commands.json is useless on Windows due to rsp files

### ISSUE THREAD

**Issue by jhasse** [mesonbuild/meson#3030]
The `compile_commands.json` is needed for tooling like clang-tidy or a language server like [cquery](https://github.com/cquery-project/cquery). But on Windows this file isn't very useful as the command line looks like this:

```json
"command": "c++ @foo.cpp.obj.rsp",
```

The unit tests know this and already extract the real command lines: https://github.com/mesonbuild/meson/blob/dfd368d4054bfe067545112717a5bd21bc37aca7/run_unittests.py#L583
But this is also needed for tooling, as there's no standard way for e.g. cquery to know that the `compile_commands.json` came from Meson+Ninja and to extract the real command line flags using a dry run.

I've thought of three possible solutions:

## 1. Let Meson fix up compile_commands.json after Ninja generated it

This basically means moving the stuff from run_unittests.py into: https://github.com/mesonbuild/meson/blob/6cc1849b8f7528fc713405f5f6b0cdebd810c088/mesonbuild/backend/ninjabackend.py#L211
I've tried this and this is what I've got so far:

```python
    def generate_compdb(self):
        pch_compilers = ['%s_PCH' % i for i in self.build.compilers]
        native_compilers = ['%s_COMPILER' % i for i in self.build.compilers]
        cross_compilers = ['%s_CROSS_COMPILER' % i for i in self.build.cross_compilers]
        ninja_compdb = [self.ninja_command, '-t', 'compdb'] + pch_compilers + native_compilers + cross_compilers
        builddir = self.environment.get_build_dir()
        jsondb = subprocess.check_output(ninja_compdb, cwd=builddir)
        contents = json.loads(jsondb)
        # If Ninja is using .rsp files, generate them, read their contents, and
        # replace it as the command for all compile commands in the parsed json.
        if len(contents) > 0 and contents[0]['command'].endswith('.rsp'):
            # Pretend to build so that the rsp files are generated
            subprocess.check_call([self.ninja_command, '-d', 'keeprsp', '-n'] + pch_compilers + native_compilers + cross_compilers)
            for each in contents:
                # Extract the actual command from the rsp file
                compiler, rsp = each['command'].split(' @')
                rsp = os.path.join(builddir, rsp)
                # Replace the command with its contents
                with open(rsp, 'r', encoding='utf-8') as f:
                    each['command'] = compiler + ' ' + f.read()
            jsondb = json.dumps(contents)
        with open(os.path.join(builddir, 'compile_commands.json'), 'wb') as f:
            f.write(jsondb)
```

Unfortunately running ninja again at this stage causes it to only run `[0/1] Regenerating build files.` :( Maybe there's a way to fix this?

## 2. Fix it in Ninja itself

There's actually a PR for this already! https://github.com/ninja-build/ninja/pull/1223
Unfortunately I don't think it will be merged any time soon. Ninja looks a bit unmaintained to be honest :(

## 3. Use something else instead of Ninja to generate compile_commands.json

This is what CMake does IIRC. I've created a PR for Shake, a Ninja-compatible build tool which can also generate `compile_commands.json`: https://github.com/ndmitchell/shake/issues/562

**Comment by nirbheek** [comment]
It really is a bit of a crappy situation, yes. One workaround for people reading this is to use `ninja -d keeprsp` which will keep them around, and you can then read the rsp file in whatever tool is parsing compile_commands.json.

**Comment by jhasse** [comment]
I think we'll have to wait for a new Ninja release (probably 1.9.0) for the PR to be included. Then we can use the ninja version to see if we can add the `-x` flag.

**Comment by nathanaelg** [comment]
Ninja 1.9.0 has been released https://github.com/ninja-build/ninja/releases/tag/v1.9.0
