### ISSUE TITLE
Meson does not set rpath to built shared library

### ISSUE THREAD

**Issue by bredelings** [mesonbuild/meson#3038]
Hi,
  I tried converting another project from autotools to meson, and almost everything works.  We build a shared library and link to it from  several tools.  However,
(a) the library is not installed, unless we set is as install: true
(b) when the library is installed, the tools can't find the library.
I though that meson automatically set the rpath for executables to point to shared libraries. Is this not right? Also, it seems that if we are installing an executable, and not installing a shared library that the executable links against, then we should complain.

But I'm not perhaps I haven't written the build files correctly.  They are available here:
https://github.com/mtholder/otcetera
The shared lib is defined in `otc/meson.build` and used by all the tools in `tools/meson.build`.

Thanks for any help! :-)

**Comment by tp-m** [comment]
I believe that by default Meson sets rpath for things in the builddir (so that if you run the tool from the builddir it will pick up the right libs), but strips it on install. There seems to be an `install_rpath` argument you can pass to `executable()` though - does that help?

**Comment by bredelings** [comment]
Hmm.. OK.  I tried that at first, but I found out that I don't know where meson will put the installed library.  For example, seting the rpath to $ORIGIN/../lib does not work, but I think $ORIGIN/../lib/x86_64-linux-gnu/ would work.  However, in order to be cross-platform, I should not code the /x86_64-linux-gnu part.  How do I ask meson where the library was placed?

**Comment by nirbheek** [comment]
> (a) the library is not installed, unless we set is as install: true

Not all libraries must be installed. Some are internal ones, so the default is to not install.

> I though that meson automatically set the rpath for executables to point to shared libraries. Is this not right?

See: https://github.com/mesonbuild/meson/issues/314 for a detailed discussion. This is an ongoing topic of discussion.

If your installed library is not in the system library path, you need to use `install_rpath` to add it manually. You can get the libdir from get_option('libdir'). Alternatively, you should use `LD_LIBRARY_PATH`.

> Also, it seems that if we are installing an executable, and not installing a shared library that the executable links against, then we should complain.

This makes sense. We would be happy to accept a patch that implements this.

**Comment by bredelings** [comment]
I looked at the discussion in #314, and maybe will comment there later.  Recommending that people use LD_LIBRARY_PATH seems clearly wrong.

OK, now that I know that you can use get_option("libdir"), the install_rpath thing works.

I will see if I can prepare a patch to warn if people install an executable but not its libraries.  This might take a while, though.

**Comment by bredelings** [comment]
On the install_rpath issue, it would be nice if there was a way to specify that for a specific library, i want installed executables to link against it.  (Maybe a declared dependency could get a install_rpath attribute in addition to link_with and include_directories?)  But in specific cases we might want to use that dependency and ignore the rpath.  (So, maybe a function to remove the rpath from a dependency.)

**Comment by siriobalmelli** [comment]
I'm running into this as well - did a precise write-up and opened a separate issue so as not to hijack this thread: #3077

**Comment by voidtrance** [comment]
Hi,

I am trying to build a python extension through `meson-python` and I am seeing that the rpath is not being set. The extension links to a shared library that is part of the project and is not installed in the standard library directories.

The extension build directive is defined as:
```python
py.extension_module('_vortex_core',
                    ['core.c', 'thread_control.c'],
                    include_directories: core_utils_include,
                    dependencies: [core_utils_dep, pthreads],
                    link_with: core_utils,
                    install: true,
                    install_dir: py.get_install_dir(pure: false) / 'vortex/core',
                    install_rpath: py.get_install_dir(pure: false) / 'vortex/core/lib')
```

However, when I use `readelf` to check the rpath value, I get this:
```bash
# readelf -d ~/voron/nas/Git/vortex/build/cp311/src/core/_vortex_core.cpython-311-x86_64-linux-gnu.so

Dynamic section at offset 0x6dd0 contains 26 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libutils.so]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/../lib]
 0x000000000000000c (INIT)               0x2000
 0x000000000000000d (FINI)               0x4cd8
 0x0000000000000019 (INIT_ARRAY)         0x6cf0
 0x000000000000001b (INIT_ARRAYSZ)       8 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x6cf8
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x300
 0x0000000000000005 (STRTAB)             0x970
 0x0000000000000006 (SYMTAB)             0x328
 0x000000000000000a (STRSZ)              1114 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x6fe8
 0x0000000000000002 (PLTRELSZ)           1416 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x1550
 0x0000000000000007 (RELA)               0xe90
 0x0000000000000008 (RELASZ)             1728 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffe (VERNEED)            0xe50
 0x000000006fffffff (VERNEEDNUM)         1
 0x000000006ffffff0 (VERSYM)             0xdca
 0x000000006ffffff9 (RELACOUNT)          65
 0x0000000000000000 (NULL)               0x0
```
I know this bug is closed but it seems that there is something else that is causing rpath to not be set.
