### ISSUE TITLE
Shared module should have .so extension on Unix-like

### ISSUE THREAD

**Issue by arteymix** [mesonbuild/meson#3053]
I'm having this issue: https://github.com/valum-framework/example/issues/2

GModule use `.so` extension on most Unix platforms (including Mac OS), so it might be better to mimic this behaviour. See https://developer.gnome.org/glib/stable/glib-Dynamic-Loading-of-Modules.html

I'd be glad to have some feedback on that.

**Comment by nirbheek** [comment]
You can use dlopen on dylibs just fine, so `g_module_build_path()` seems to be wrong here. It's even wrong on Windows because MinGW dlls are called libmylibrary.dll not mylibrary.dll.

Actually, looking at the definition of `G_MODULE_SUFFIX` it was defined in 2000 and never changed since then. I doubt it was updated when Mac OS X was released. I recommend not using it.

**Comment by nirbheek** [comment]
Actually, now I remember investigating this like 2 years ago. `g_module_build_path()` is broken, unfixable, and should not be used. To fix this, we need a new function like:

```c
GModule *
g_module_open_at (const gchar * directory,
                  const gchar * name,
                  GModuleFlags flags);
```

That way, the function can search for (libfoo.so, foo.so) on Linux/BSD, (libfoo.dylib, foo.dylib, libfoo.so) on macOS, and (libfoo.dll, foo.dll) on Windows. This is the only sane way to implement it. I suspect there is already a bug upstream about this. You will want to take this there.

**Comment by nirbheek** [comment]
Haha, I even commented on it: https://bugzilla.gnome.org/show_bug.cgi?id=671212#c5

**Comment by arteymix** [comment]
I think the best would be to use GModule-esque definitions in the build to avoid the boilerplate in the code. I think we should consider something like `gnome.module` with corresponding behaviour.

**Comment by arteymix** [comment]
I agree it's broken, but that's how it's defined and a lot of GNOME code relies on these specific conventions for portability.

**Comment by nirbheek** [comment]
Do GNOME projects actually hack around Autotools to build modules with .so on macOS? Because the default with Autotools is .dylib.

**Comment by arteymix** [comment]
Here you go: https://git.gnome.org/browse/libpeas/tree/libpeas/peas-object-module.c#n94

**Comment by arteymix** [comment]
File > Make a copy...

**Comment by nirbheek** [comment]
> Here you go: https://git.gnome.org/browse/libpeas/tree/libpeas/peas-object-module.c#n94

The examples don't contain any special code to change the extension on macOS: https://git.gnome.org/browse/libpeas/tree/peas-demo/plugins/helloworld/Makefile.am

So what does it actually build? How does it work on macOS?

In the end, regardless of all this discussion, the fix here is even simpler than I thought. Just need to change `g_module_open()` to also look for `.dylib` on macOS when the path has no extension.

As it stands, `g_module_build_path()` is not usable on macOS. Note that there is nothing GNOME-specific in that API; it just uses `NSCreateObjectFileImageFromFile()` and that works with all libraries.

> File > Make a copy...

Was this a typo? :)

**Comment by arteymix** [comment]
It's a separate conversation.. but yeah, could apply here as well.

**Comment by arteymix** [comment]
Oh, I see now, `g_module_open` has some wild strategy already :D I'll test that out!

**Comment by tschoonj** [comment]
@nirbheek Just reading this thread now. 

The default extension when building plugins with autotools (with `-module -avoid-version` added to `_LDFLAGS`) on macOS is `.so`, not `.dylib`.

Also whether there is a `lib` prefix or not depends entirely on what the user specified as name for the plugin. 

Sorry for being a bit late to the party...
