### ISSUE TITLE
Custom pkg-config wrapper cannot be used from the source directories

### ISSUE THREAD

**Issue by germandiagogomez** [mesonbuild/meson#307]
Hello,

I have the following usage problem using meson. I have a libcurl dependency. libcurl provides a pkg-config .pc file. So, when I want to cross compile for android, I created a .pc file for my android compiled libcurl.

I followed the way of pull request  #138, with the difference that my pkg-config wrapper is in the root directory of my project, instead of in the path in my Mac. 
Using a custom pkg-config wrapper in the root of my project will not work: libcurl dependency is not found when cross-compiling. Only if I copy my pkg-config wrapper into /usr/bin everything works fine. 

So I cannot do this in my cross-compile file:

``` python
#This is cross compile file. Not working.
[binaries]
pkgconfig = 'armv7-linux-armeabi-pkg-config'
```

But I can do this, of course previously copying the script to `/usr/bin/`, which I want to  avoid:

``` python
#This is cross compile file. Works correctly.
[binaries]
pkgconfig = '/usr/bin/armv7-linux-armeabi-pkg-config'
```

Another thing that keeps my attention is that even if the second way it is working, it still says:

``` sh
Found pkg-config: /usr/local/bin/pkg-config
```

I would expect `/usr/bin/armv7-linux-armeabi-pkg-config` found in my case. But it is working anyway, maybe the info shown is not correct but still using my wrapper.

I want to avoid copying it and use my custom pkg-config wrapper to keep the project self-contained when compiling in other platforms.

**Comment by jpakkane** [comment]
If you wish to use pkg-config then either it needs to be in path or you need to write the full path. That is the way people expect pkg-config to work. Meson has the extra requirement that it must support native and cross pkg-configs at the same time, which is something no other build system (that I know of) does. Because of this absolute paths in the cross file are practically necessary.

Cross files can't really be per-project, because they are very heavily dependent on the machine they are run on. On the other hand once you have a cross file for a given machine, you can use it on as many different projects as you want.

**Comment by germandiagogomez** [comment]
> Meson has the extra requirement that it must support native and cross pkg-configs at the same time, which is something no other build system (that I know of) does. Because of this absolute paths in the cross file are practically necessary.

Use case: if you allow to set the pkg-config wrapper or allow environment variables and/or normal meson code in cross files, I can use the same file from windows, linux and mac os x machines even for cross compilation. Otherwise, I need to keep creating multiple files. Maybe not high prio, but wouldn't be nice to be able to download a project and sdk and cross-compile yourself? :)

**Comment by germandiagogomez** [comment]
> Cross files can't really be per-project, because they are very heavily dependent on the machine they are run on

Why not? As long as you can setup some options/environment variables, it is possible, and very convenient, IMHO. I am not sure, but with cmake it should be possible. Not a showstopper, but anyway, I think that being able to use meson syntax in cross files should be possible. This way you say what to cross compile for and from which machine.

**Comment by nirbheek** [comment]
This can be fixed by providing access to the source root and the build root from the cross-info file. Something like:

```
[binaries]
pkgconfig = '{source_root}/armv7-linux-armeabi-pkg-config'
```

This will replace `{source_root}` with the full path of the source directory so that you can ship your own wrappers of binaries if you wish.

**Comment by germandiagogomez** [comment]
@nirbheek Is `{source_root}` implemented? I tried and it is not working. As per @jpakkane comments I can see that native build machine pkg-config could do the trick if there is a way to set PKG_CONFIG_LIBDIR. I would like to keep this as a detail and not do it from the command-line to avoid wrappers that call meson. Is that possible?

**Comment by nirbheek** [comment]
`{source_root}` is not implemented, and there is no way to set `PKG_CONFIG_LIBDIR` either. We also don't remember the value if there's a reconfigure done via Ninja. We should probably fix this by remembering the value. Right now we just warn that the value has changed.

**Comment by germandiagogomez** [comment]
@nirbheek Is `{source_root}` implemented? I tried and it is not working. Can PKG_CONFIG_LIBDIR be set from inside meson.build file? That would be convenient to release the user from specifying PKG_CONFIG_LIBDIR. Otherwise I need to provide a shell script that sets the variable first, but the PKG_CONFIG_LIBDIR should point to the same place all the time at least in my use case, so it can be hardcoded.

**Comment by pwnorbitals** [comment]
@germandiagogomez Is your problem now solved ?

**Comment by eli-schwartz** [comment]
This is probably solved due to the addition of the constants section in cross files: https://mesonbuild.com/Machine-files.html#constants
