### ISSUE TITLE
Document assert function

### ISSUE THREAD

**Issue by inigomartinez** [mesonbuild/meson#3076]
There has been a discussion about the [assert](https://github.com/mesonbuild/meson/blob/master/mesonbuild/interpreter.py#L1462) [function](https://github.com/mesonbuild/meson/blob/master/mesonbuild/interpreter.py#L1641), whether it should be [used](https://bugzilla.gnome.org/show_bug.cgi?id=784212#c33) or [not](
https://bugzilla.gnome.org/show_bug.cgi?id=784212#c32).

I've been heavily using it, because it's very handy for me, but apart from meson's unit test and the projects I've been working on, I've only seen it in one [project](https://github.com/jpakkane/mesonarduino/blob/master/meson.build#L7).

It would be nice to document it properly by also clarifying if it should also be used in other projects in addition to meson's unit tests.

**Comment by nirbheek** [comment]
I am not sure if `assert()` should be used by anything other than tests. The error message it gives is not very friendly.

**Comment by inigomartinez** [comment]
`error('message')` shows:

```
Meson encountered an error in file meson.build, line 47, column 0:
Error encountered: message
```

`assert(false, 'message')` shows:


```
Meson encountered an error in file meson.build, line 47, column 0:
Assert failed: message
```

The assert message is not very different from an error message.

**Comment by tp-m** [comment]
I would argue that an assert is something used in code to assert internal consistency, to make sure preconditions have been checked and maybe even to document in code what assumptions can be made at some point.

When writing C code we also don't use `assert()` for erroring out in command line apps.

The error message may not be 'much different', but it is different. Your normal user might not know what 'assert failed' means, and developers might be confused about whether it's a bug in your meson build file or an attempt to report an error ;)

**Comment by nirbheek** [comment]
Indeed, and to make things worse, the current implementation of `assert()` doesn't have the equivalent of `g_assert_cmpint (a, ==, b);` and so on which would at least print the values of `a` and `b` to make the message more useful.

I would actually like it if we could find a way to make `assert()` be totally unavailable in user build files, or at least print a warning.

**Comment by tp-m** [comment]
I also feel that the more verbose way of doing
```
if ..
  error('No good!)
endif
```

is much nicer to read, but that's beside the point. Maybe we should introduce `error_if` and `error_unless` functions then if you are really keen on writing things that way?

**Comment by inigomartinez** [comment]
> I would argue that an assert is something used in code to assert internal consistency, to make sure preconditions have been checked and maybe even to document in code what assumptions can be made at some point.
> 
> When writing C code we also don't use assert() for erroring out in command line apps.

I am in total agreement.

However, it does come very hand. The following pattern:

```
if condition
  error('message')
endif
```

Can be replaced by:

`assert(not condition, 'message')`

This involves less lines an less parsing. It `assert` becomes unavailable, it would be nice to have somekind of replacement. Something like:

`error_if_false(no condition, 'message')`

**Comment by nirbheek** [comment]
IME it's kinda rare to have an error() after a simple condition like that. Manually erroring out in a build file is usually a last-resort thing, because it's a bad build experience for everyone except distros.

For example, in glib we have:

```meson
if int_size == 8
  ...
elif long_size == 8
  ...
elif long_long_size == 8
  ...
else
  error('Compiler provides no native 64-bit integer type')
endif
```

Has your experience been different?

**Comment by inigomartinez** [comment]
I use it heavily for custom messages in missing dependencies, programs, compiler flags, ... and also for preconditions:

`./gnome-documents/man/meson.build:assert(xsltproc.found(), 'xsltproc is required to build documentation')`

```
./NetworkManager/meson.build:  assert(enable_wifi, 'Enabling iwd support requires Wi-Fi support as well')
./NetworkManager/meson.build:  assert(gir_dep.found(), 'introspection support was requested, but the gobject-introspection library is not available. Use -Dintrospection=false to build without it.')
./NetworkManager/meson.build:  assert(dbus_dep.found() and dbus_glib_dep.found(), 'Configure with -Dlibnm_glib=false if you do not need the legacy libraries'
./NetworkManager/meson.build:  assert(add_languages('vala', required: false), 'vala is required to build. Use -Dvapi=false to disable it')
./NetworkManager/meson.build:  assert(meson.get_compiler('vala').version().version_compare(vala_req_version), 'vala ' + vala_req_version + ' is required to build. Use -Dvapi=false to disable it')
```

```
./gvfs/meson.build:  assert(libgcrypt_version.version_compare(libgcrypt_req_version), 'gcrypt required but libgcrypt ' + libgcrypt_req_version + ' not found')
./gvfs/meson.build:  assert(enable_gudev, 'UDisks2 requested but gudev is required')
```
`
./gnome-characters/meson.build:assert(cc.links(libunistring_src, name: 'libunistring support', args: '-lunistring'), 'libunistring is required but not found')`

`./vte/meson.build:  assert(cxx.has_argument(flag), cxx.get_id() + ' doesn\'t support required flag -fvisibility=hidden')`

```
./gnome-calendar/meson.build:assert(cc.has_function('strerror'), '"strerror" not found')
./gnome-calendar/meson.build:assert(cc.has_function('icaltime_days_in_year', dependencies: libical_dep)
```

```
./libgit2-glib/meson.build:  assert(cc.compiles(libgit2_ssh_src, name: 'libgit2 supports SSH'), 'libgit2 ssh support was requested, but not found. Use -Dssh=false to build without it.')
./libgit2-glib/meson.build:  assert(python.language_version().version_compare('>= ' + python_req), 'python support was requested, but version >= ' + python_req + ' not found.')
```
`
./gnome-terminal/meson.build:  assert(res.returncode() == 0, 'gnome-shell search provider requested but interface definition file not found')`

`./gnome-session/meson.build:    assert(dbus_glib_dep.found(), 'ConsoleKit support explicitly required, but dbus-glib not found')`

```
./gnome-photos/meson.build:assert(libjpeg_dep.found(), 'JPEG library not found')
./gnome-photos/meson.build:assert(cc.has_function('jpeg_destroy_decompress', dependencies: libjpeg_dep), 'jpeg_destroy_decompress not found')
./gnome-photos/meson.build:assert(cc.has_header('jpeglib.h', dependencies: libjpeg_dep), 'JPEG headers not found')
./gnome-photos/meson.build:assert(cc.has_function('jpeg_save_markers', dependencies: libjpeg_dep), 'JPEG library is too old')
```

`./gnome-settings-daemon/meson.build:assert(enable_rfkill or not host_is_linux, 'rfkill is not optional on Linux platforms')`
```

./gnome-control-center/meson.build:  assert(cc.has_header(header[1], args: cups_cflags), 'CUPS headers not found: ' + header[1])
./gnome-control-center/meson.build:  assert(clutter_gtk_dep.found(), 'cheese support requested, but clutter-gtk library is not available. Use -Dcheese=false to build without it.')
```

`./eog/meson.build:assert(have_zlib, 'No sufficient zlib library found on your system')`

I regret to say that the list is quite long, although I think these cases reflect my use of it.

**Comment by nirbheek** [comment]
> ./NetworkManager/meson.build: assert(gir_dep.found(), 'introspection support was requested, but the gobject-introspection library is not available. Use -Dintrospection=false to build without it.') ./NetworkManager/meson.build: assert(dbus_dep.found() and dbus_glib_dep.found(), 'Configure with -Dlibnm_glib=false if you do not need the legacy libraries' ./NetworkManager/meson.build: assert(add_languages('vala', required: false), 'vala is required to build. Use -Dvapi=false to disable it')
> ./gnome-session/meson.build: assert(dbus_glib_dep.found(), 'ConsoleKit support explicitly required, but dbus-glib not found')
> ./gnome-photos/meson.build:assert(libjpeg_dep.found(), 'JPEG library not found')
> ./gnome-control-center/meson.build: assert(clutter_gtk_dep.found(), 'cheese support requested, but clutter-gtk library is not available. Use -Dcheese=false to build without it.')
> ./eog/meson.build:assert(have_zlib, 'No sufficient zlib library found on your system')

Most of these seem redundant? They output the same error that meson would? For the others, in the future meson can automatically tell the user what option to disable: #2411

> ./gnome-characters/meson.build:assert(cc.links(libunistring_src, name: 'libunistring support', args: '-lunistring'), 'libunistring is required but not found')
> 
> ./vte/meson.build: assert(cxx.has_argument(flag), cxx.get_id() + ' doesn\'t support required flag -fvisibility=hidden')
> 
> ./gnome-calendar/meson.build:assert(cc.has_function('strerror'), '"strerror" not found')
> ./gnome-calendar/meson.build:assert(cc.has_function('icaltime_days_in_year', dependencies: libical_dep)
> ./libgit2-glib/meson.build:  assert(cc.compiles(libgit2_ssh_src, name: 'libgit2 supports SSH'), 'libgit2 ssh support was requested, but not found. Use -Dssh=false to build without it.')
> ./gnome-photos/meson.build:assert(cc.has_function('jpeg_destroy_decompress', dependencies: libjpeg_dep), 'jpeg_destroy_decompress not found') ./gnome-photos/meson.build:assert(cc.has_header('jpeglib.h', dependencies: libjpeg_dep), 'JPEG headers not found') ./gnome-photos/meson.build:assert(cc.has_function('jpeg_save_markers', dependencies: libjpeg_dep), 'JPEG library is too old')
> ./gnome-control-center/meson.build: assert(cc.has_header(header[1], args: cups_cflags), 'CUPS headers not found: ' + header[1])

For all these, we should provide a way for build files to tell Meson that a failing compiler check is a hard error.

**Comment by textshell** [comment]
assert is documented now. So this can be closed.

**Comment by tp-m** [comment]
This kind of missed the point of the issue, which was that it should be documented whether it's meant for general use or primarily for use in meson unit tests.

**Comment by textshell** [comment]
I raised that when the PR was merged on irc. Having it documented like it is now seems to be to be a decision that this is just a normal meson function for normal usage. It it was not that would surely be in the documentation?
