### ISSUE TITLE
Exclude files from ninja dist?

### ISSUE THREAD

**Issue by infirit** [mesonbuild/meson#3081]
Looking into meson bu I could not find anything in the docs how to exclude files from ``ninja dist``. I don't want to have my transiflex or travis configuration files included in the tarball.

**Comment by jpakkane** [comment]
There is a plan to be able to run arbitrary scripts before the tarfile is created. This would allow arbitrary post-processing (such as adding extra sample files etc). It's not yet implemented, though...

**Comment by QuLogic** [comment]
If dist used `git archive` (like `hg`), then it could get [export-ignore](https://git-scm.com/docs/git-archive#ATTRIBUTES) done for "free".

**Comment by infirit** [comment]
Hmm, not looking forward to use post-processing for something like this. Personally I would expect a modern build system to have this integrated into it's core. I'll experiment with my own dist script or just look for something else.

Anyway, either close this or leave it open as a feature request.

**Comment by infirit** [comment]
@QuLogic yes ``git archive`` with export-ignore works pretty good. Thx

**Comment by infirit** [comment]
@Kekun That is a vcs specific workaround for this problem. Mercurial can be configured to exclude files in its .hgrc file. But they are workarounds and this request is to integrate this into meson independent of the vcs used.

Currently git and mercurial are supported but there are hundreds of vcs, some have features like gitattributes some don't but is meson going to support all them? It becomes quite unworkable quickly and I doubt they are going to do that. Which means they will be excluding many users that have to do their own release script.

**Comment by thmo** [comment]
> There is a plan to be able to run arbitrary scripts before the tarfile is created. This would allow arbitrary post-processing (such as adding extra sample files etc). It's not yet implemented, though...

This has been implemented in the meantime. However unfortunately `run_dist_scripts()` is called after `del_gitfiles()` (which itself is called in `git_clone()`), hence a custom dist script cannot rely on the `export-ignore` attribute, as `.gitattributes` is not available at this time anymore.

**Comment by jpakkane** [comment]
#6491 allows you to access the source dir from your dist script. Is that sufficient or do you need something more?

**Comment by thmo** [comment]
The source dir itself might be modified, so the `.gitignore` from there might be different. Hence one would have to again use `git` to get the version that has been deleted just before. To me, this looks very hackish and complicated.

Why not provide a hook that is called just _before_ running `del_gitfiles()`?

**Comment by nirbheek** [comment]
> The source dir itself might be modified

`dist` clones HEAD, so modifications are explicitly ignored. The idea is that dist is for testing the git state, not the dirty tree. We should definitely warn when that happens, though.

**Comment by thmo** [comment]
> `dist` clones HEAD, so modifications are explicitly ignored. The idea is that dist is for testing the git state, not the dirty tree.

I know, and that's why I basically said that the possibility to access the source dir is not enough.

**Comment by eli-schwartz** [comment]
We now have both dist scripts, which can post-process the tree, and a linked PR which makes gitattributes export-subst be used by default.
