### ISSUE TITLE
cross compilation struct size guessing "high" limit is too low.

### ISSUE THREAD

**Issue by asavah** [mesonbuild/meson#3113]
When crosscompiling meson size checks for large structs fails,
for example systemd just introduced statx check here https://github.com/systemd/systemd/blob/master/meson.build#L462

Cross compilation fails
```
Checking for size of "struct ethtool_link_settings": 48
Checking for size of "struct fib_rule_uid_range": 8

Meson encountered an error in file meson.build, line 466, column 8:
Cross-compile check overflowed
```
The cause is that here
https://github.com/mesonbuild/meson/blob/master/mesonbuild/compilers/c.py#L419
"high" limit of 128 is too low for statx which size is 256 on ARM 32 bit (glibc 2.27, kernel headers 4.14.x),
Manually bumping "high" value to 1024 in the line above allows the check to determine the correct size of 256.

```
Checking for size of "struct ethtool_link_settings": 48
Checking for size of "struct fib_rule_uid_range": 8
Checking for size of "struct statx": 256
```
Build succeeds.

I don't know whether 1024 is a sane value, but 128 is too low.

Edit: forgot to mention meson version: 0.44.1

**Comment by nirbheek** [comment]
1024 is a good start, bug maybe we should rethink our overflow behaviour. Or, perhaps, there is a better way to detect this without doing bisection.

**Comment by tp-m** [comment]
I think there may be another issue about how this could be implemented differently (or was it a todo in the code? don't remember)

**Comment by shlevy** [comment]
FYI in nixpkgs we're carrying https://github.com/NixOS/nixpkgs/commit/b2a2131ff0f0a7ecd521408841e55ea21dbe3c40 for now.

**Comment by jpakkane** [comment]
This is now in master so closing.
