### ISSUE TITLE
compile c++ exe with d library dependency does not work

### ISSUE THREAD

**Issue by germandiagogomez** [mesonbuild/meson#3125]
Hello,

So, this is my use case:

```python
my_d_lib = static_library('dlib', sources : ['src/dsource.d'], ...)

wx_dep = dependency('wxwidgets', version : '>=3.0.0', required : true)

my_cpp_exe = executable('mywxgui', sources : ['src/some.cpp'], dependencies : [wx_dep],
                                             link_with : my_d_lib)
```

my_d_lib has some code that can be called from c++. I want to compile my c++ executable and link it with my_d_lib and call my_d_lib routine (which has extern "C" linkage) from C++. The problem seems to be that executable assumes this is a d executable when I use `link_with` so it uses dmd to try to put everything together. It should use, for my use case, the c++ compiler and link against the d library.

**Comment by nirbheek** [comment]
So, basically, the object files outputted by `dmd` use the C ABI, so we can always safely link D objects with a C linker, and if C++ objects are to be linked in, use C++?
