### ISSUE TITLE
Multiple version fail in 0.44.1-1

### ISSUE THREAD

**Issue by mikolajpp** [mesonbuild/meson#3133]
There is a simple bug in file `mesonbuild/interpreter.py`
Line `2291` should invoke `mesonlib.version_compare_many` instead of `mesonlib.version_compare`.
Changing it in source code fixed the error.

**Comment by sarum9in** [comment]
Could you provide a test case for this (even just copy & paste meson.build here)? I am not sure I understand what behavior you are talking about.

**Comment by nirbheek** [comment]
Closing due to no response. Please reopen if this is still not fixed with 0.47.
