### ISSUE TITLE
meson-options.txt allows upper case characters in array but setting them is imposible

### ISSUE THREAD

**Issue by infirit** [mesonbuild/meson#3149]
meson version is 0.44.1

I have an array in meson-options.txt similar to below which is title case. However when I set it with ```-Dplugins=PlugTwo``` it is set with lower case.

```
option('plugins', type: 'array', choices: ['PlugOne', 'PlugTwo'], value: ['PlugOne', 'PlugTwo'], description: 'Select plugins')
```

The output of meson configure looks like below then

```
plugins       ['plugtwo']              ['PlugOne', 'PlugTwo'] Select plugins
```

**Comment by jpakkane** [comment]
This may be caused by the fact that we don't want to have options that differ only by case for simplicity. It should preserve the case, though, so probably something wrong with the cleanupper or validator.

**Comment by infirit** [comment]
The good news is that it is purely cosmetic and the actual values retain their case. The function ``print_aligned`` calls lower when it shouldn't for my example. I'll have a fix for this soon.

**Comment by infirit** [comment]
See #3177
