### ISSUE TITLE
Feature Request: generator.process() to allow 'extra_args' argument

### ISSUE THREAD

**Issue by rhd** [mesonbuild/meson#315]
Hi Jussi,

I have a generator for cuda's `nvcc` command and it's working OK. The issue is - sometimes an app needs to add custom args to `nvcc`.

Would something like this be possible?

```
cuda_gen = generator(nvcc,
    output: '@BASENAME@.o',
    arguments: ['-c', '@INPUT@', '-o', '@OUTPUT@'],
)
```

```
generated = cuda_gen.process('f1.cu', extra_args=['-Darg1', '-Darg2', '-foo-bar-arg3'])
```

Being about to pass extra args to the nvcc command would be ideal. The alternative is to create multiple generators.... not that huge of a deal, but breaks the DRY principle.

Thanks!

**Comment by jpakkane** [comment]
Can you try pr #318 and tell if it works for you? Thanks.

**Comment by rhd** [comment]
I will test it out today - thank you so much. Do you think 'opt_args' or 'optional_args' is a better name?

**Comment by jpakkane** [comment]
I prefer unabbreviated keyword argument names, and since extra_args is shorter than optional_args, it seems the best choice.
