### ISSUE TITLE
Compiler cannot find dependency's includes

### ISSUE THREAD

**Issue by AlexandreFoley** [mesonbuild/meson#316]
I am attempting to build a sample project that depend on an external template library on MacOSX 10.9.5.
The build file is here: [meson.build.txt](https://github.com/mesonbuild/meson/files/43981/meson.build.txt)

The meson.build file specify that the library in question is a depedancy, and meson find that it is available. Here's the output from meson:
```
[Alex@apremont EigenTest]$ meson build
The Meson build system
Version: 0.27.0-research
Source dir: /Users/Alex/Documents/qcm3/EigenTest
Build dir: /Users/Alex/Documents/qcm3/EigenTest/build
Build type: native build
Build machine cpu family: x86_64
Build machine cpu: x86_64
Project name: Eigen_UTest
Native cpp compiler: c++ (clang 3.7.0)
Found pkg-config: /opt/local/bin/pkg-config (0.28)
Native dependency eigen3 found: YES 3.2.7
Build targets in project: 1
```
but the compilation fails because the compiler fails to find the file to be included:

```
[Alex@apremont EigenTest]$ cd build/
[Alex@apremont build]$ ninja
[1/2] Compiling cpp object 'Utest@exe/Eigen_test.cpp.o'
FAILED: c++  '-Wall' '-Wpedantic' '-Winvalid-pch' '-Wnon-virtual-dtor' '-std=c++11' '-std=c++11' '-g' '-Iinclude/eigen3' '-IUtest@exe' '-I..' '-I.' '-MMD' '-MQ' 'Utest@exe/Eigen_test.cpp.o' '-MF' 'Utest@exe/Eigen_test.cpp.o.d' -o 'Utest@exe/Eigen_test.cpp.o' -c ../Eigen_test.cpp
../Eigen_test.cpp:2:10: fatal error: 'Eigen/Dense' file not found
#include <Eigen/Dense>
         ^
1 error generated.
ninja: build stopped: subcommand failed.
```
The library is located at /opt/local/include.  If i add '/opt/local/include/eigen3' as an include in the meson file, it compiles fine. But then meson's autodetect of Eigen3 becomes useless.

I am not even sure that i am not doing something wrong. I am sorry if the problem is my own fault. 
In any case, thank you for your time.

**Comment by jpakkane** [comment]
First of all, you don't need to put -std=c++11, Meson does it by default (you can change it via options).

Second of all it seems like pkg-config is giving out incorrect paths. The include path given is this:

    '-Iinclude/eigen3'

This is a relative path, not absolute. Try running this command to see the flags it produces:

    /opt/local/bin/pkg-config --cflags eigen3

If those are incorrect then the detection fails because pkg-config gives out bad data.

**Comment by AlexandreFoley** [comment]
> First of all, you don't need to put -std=c++11, Meson does it by default.

Yes i had realised that when i saw the compiler error, i just didn't bother with it. It does look silly, but in the end it doesn't do much.

It is indeed the fault of my pkg-config, it gives out a relative path...
Thank you for your help, I guess i have some stuff to figure out about pkg-config, and maybe some other devs to bother =p . Thank you for your time Jussi. I wish you a good day.
