### ISSUE TITLE
Permissions of files in install tree should not depend on umask in various stages of the process

### ISSUE THREAD

**Issue by filbranden** [mesonbuild/meson#3160]
**EDIT:** My original post was about install_data() only, rewrote this to make it generic.

Hi,

I find that Meson's handle of file permissions in the "install" step is awkward and not very hermetic.

It turns out the permission of files in the install tree will depend on the umask on various of the previous steps of the system. In may cases, the developers have little way to control those and in many cases getting the permissions right is difficult or error-prone.

So I did some experiments and I noticed that:

* Files installed directly from the source tree, using install_data(), will be affected by what the umask was when the tree was created using `git clone`.
* Files installed from the build tree (i.e. compiled executables, generated files, etc.) will be affected by what the umask was when the build step was done, with the `ninja` command.
* Directories in the install tree will be affected by what the umask was when the install step was done, with the `ninja install` command.

Ideally, the permissions of the files in the install tree should not depend on the umask, much less on the umask on events as early as the checkout of the source tree!

If you're using a 022 umask in your day-to-day, everything should look fairly normal, but that's by no means the only useful umask:

* Distributions like Fedora/RHEL/CentOS, which create a primary group for each user (i.e. `filbranden:filbranden`) will set the umask to 002, to make everything group-writable by default. Since the primary group only contains the primary user, that's not opening up to other users, but it makes creating group-shared directories easier since the umask is already set to support that.
* Company policies might want to set the umask to something like 027, to minimize accidents with world-readable files being created somewhere accessible where non-authorized users may have access to them.

So: Supporting custom umasks is important. It's really hard to enforce umask 022 everywhere. And, even if it was possible, there's really no good reason for that...

Regardless of umask, the install tree should be consistent.

The typical setup is to have directories and executable files with mode 0755, while data files have mode 0644. (Note that that's not the only possible setup, but it's by far the most common one.) Note that this also matches the 022 umask.

In #3162, @jpakkane mentioned that "there are people who absolutely, positively *want* to preserve the value of each of those bits", but I'd like a clarification from him on that. Are these people the developers, writing the software, the users, building and installing it, or the packagers, integrating it into distros? Do you see how the interactions with the umask make this system *less* reliable in terms of preserving any permissions?

What I find that Meson *does* get right (and autotools is quite bad in that) is preserving whether a file is *executable* when it gets installed. It does make sense to preserve that! If I ship an executable script in my source repository (git does preserve that information, even though it will properly apply the umask when cloning the tree!), I do want it to be, by default, executable on my install tree. The same for produced artifacts. Compilers will produce binaries with the executable bit set. If I'm pre-processing some data from a template, I'll have it produced without the executable bit set. I do want those preserved in the install tree... Nevertheless, they should default to 0755 (if executable) and 0644 (if not executable.)

You can also look at how other build systems handle this. The `/usr/bin/install` tool (see [man page](https://linux.die.net/man/1/install)), which is used in the install rule of most hand-written Makefiles, will by default install files with permission 0755, since its primary use is to install binaries.

Automake will create two variables, $(INSTALL_PROGRAM) and $(INSTALL_DATA), the former of which will just call `/usr/bin/install`, the latter will call it with `-m 0644` to install a file without the executable bit set.

I haven't checked other systems such as cmake or scons, but I'd expect they'd do the same...

So my proposal is:

* Keep preserving whether files have the *executable* bit set. That's reliable and doesn't break with umask! (Unless umask is something crazy such as 0133 to strip executable bit of all files... But if an user does that, they're shooting their own foot!)
* Have the "install" step create files with one of two modes, for executable or non-executable files.
* These two modes should default to 0755 and 0644. Though I guess having a way to configure them, probably on a per-project base, would be good and nice!
* To give developers more control over permissions, expanding install_mode to all the rules that install files is recommended. Right now, they can override the permissions of files installed from the source tree, but there's not really a good way to override the permissions of generated/compiled files that get installed.

For the configuration of the default modes, one idea is to add one attribute for each, such as:

```
project('myproject', 'c',
        default_executable_install_mode : 0755,
        default_data_install_mode : 0644)
```

But I find that a better way to specify that is with a umask, since these two are related by that same umask:

```
project('myproject', 'c',
        install_umask : 022)
```

Other possibly useful umasks would be 0222 (not writable by owner, some OSs tend to do that), 066 (executable bit set but not read bit for group/others, though not sure if this is viable as a global option.)

The default, if unspecified, should be 022. I think it should be fine to push such a default, even if it's a change from current behavior... For anyone using meson with a umask 022, it doesn't really change anything. For anyone using it with a different umask, I'd argue it's already broken for them, so I can't imagine they'd have problems with such a change.

I'm happy to implement this and send a PR, just wanted to have this RFE acked first and possibly discuss the design before I work on code.

**Comment by filbranden** [comment]
So on further investigation, it seems it's not only install_data() that's affected, but essentially all binaries and generated files when installed to the destination tree get affected by the umask used when source is first built...

I still think that's not great behavior, since the umask used in several steps of the process (git clone for install_data, ninja for the generated files) will determine how the files will be installed...

I think the appropriate behavior is to generate all files and directories with mode 0644 or 0755.

I *do* think that it's useful to detect whether the file is executable in the orgin and to preserve that attribute. That attribute *is* useful!

Furthermore, (at least from reading the docs) it seems the only permissions that can be controlled are those in install_data(), which makes it hard to control how executables are installed. It might be nice to be able to support something like install_mode for other objects such as executable(), etc.

I'm happy to contribute patches (as you can see), just wanted to understand if you agree this is a problem and what you think is the best way forward towards fixing this...

Thanks!
Filipe

**Comment by sarum9in** [comment]
#2433 is related

**Comment by keszybz** [comment]
That's a very nice writeup. Proposed solution sounds right, in particular the first bit of installing data and executable files as if umask=022 was always set.

**Comment by jpakkane** [comment]
The case I was thinking of would involve extracting a full tarball, building and installing. This would change the mode bits of the end result compared to what we do currently.

I can imagine that this would be an issue for some but I don't have enough distro and deployment experience to be able to say conclusively.

**Comment by keszybz** [comment]
From distro point of view, predictability is *very* important, and current scheme "leaks" information about the build environment. (For example, when building in Fedora's mock environment, the umask might be different then when building as a normal user. Another example it that the installation result will be different from a normal git clone and the same repo with `git cloned --shared`.) It's much more desirable to know that the permissions are always 0644/0755 for the two file types after installation.

**Comment by sarum9in** [comment]
I disagree about hardcoding 0644/0755. But making this configuration variables, please correct names but something like `-Dexecutable_mode=0755` and `-Dnon_executable_mode=0644`. And make these defaults like `-Ddefault-library=shared`.

**Comment by keszybz** [comment]
Heh, I was just bitten by this (older meson). I set umask to 077 to test something, and a few days later called `sudo ninja -C build install`, and was a bit surprised when `git rebase -i` failed because it couldn't launch emacs, and emacs wouldn't launch because `/usr/lib64/libsystemd.so` had permissions of 0700. It's nice to see this implemented, I just now have to wait for the updated version.
