### ISSUE TITLE
Unable to use multiple outputs on generator / custom_target?

### ISSUE THREAD

**Issue by mithro** [mesonbuild/meson#3166]
According to [this documentation](https://github.com/mesonbuild/meson/blob/master/docs/markdown/Generating-sources.md#using-generator) you should be able to use multiple `outputs` on a generator;

> Generators can also generate multiple output files with unknown names:
> 
> ```meson
> gen2 = generator(someprog,
>                  outputs : ['@BASENAME@.c', '@BASENAME@.h'],
>                  arguments : ['--out_dir=@BUILD_DIR@', '@INPUT@'])
> ```

However, when I try to do this, I get the following error from meson;
```bash
Program utils/mux_gen.py found: YES (XXXX/catx/vtr/utils/mux_gen.py)
WARNING: Passed invalid keyword argument "outputs" in meson.build line 25.
This will become a hard error in the future.
tansell@tansell:~/work/catx/vtr$ meson . build
The Meson build system
Version: 0.44.1
Source dir: /usr/local/google/home/tansell/work/catx/vtr
Build dir: /usr/local/google/home/tansell/work/catx/vtr/build
Build type: native build
Project name: symbiflow-arch-defs
Build machine cpu family: x86_64
Build machine cpu: x86_64
Program find found: YES (/usr/bin/find)
Program utils/mux_gen.py found: YES (XXXX/catx/vtr/utils/mux_gen.py)
WARNING: Passed invalid keyword argument "outputs" in meson.build line 25.
This will become a hard error in the future.

Meson encountered an error in file meson.build, line 25, column 0:
Generator must have "output" keyword argument.

A full log can be found at XXXX/catx/vtr/build/meson-logs/meson-log.txt
```

I thought that it might be because it is only supported in `0.45.0.dev1`, but I tried it and get the same error.

You can find my meson config file here -> https://github.com/mithro/symbiflow-arch-defs/blob/meson-config/meson.build

I've tried `outputs` with both `generators` and `custom targets`.

Any idea what I'm doing wrong?

**Comment by jpakkane** [comment]
The generator function has `outputs` rather than `output` at least.

**Comment by mithro** [comment]
Yeah - it looks like the docs are wrong...
