### ISSUE TITLE
What is the reason of not automatically picking up changes to default project options?

### ISSUE THREAD

**Issue by koponomarenko** [mesonbuild/meson#3176]
I thought the idea is to run meson just once, and then every time ninja is called any changes are automatically detected. But then I added `default_options : ['cpp_std=c++11']` to the project and was confused by the fact that it is not detected automatically.

I found that you can set this option using `meson configure` command, but there is no something like "check if my build config is up to date, and make it so if it's not" or something like that.

**Comment by jpakkane** [comment]
This is an [FAQ](http://mesonbuild.com/FAQ.html#why-are-changes-to-default-project-options-ignored).

**Comment by koponomarenko** [comment]
Yup, I saw this FAQ. My question is more about the answer in that FAQ. It says:

> The reason for this is that default options are only looked at when you are setting up a build directory for the very first time.

I was just curious why not to check this options all the time? Or at least maybe make an option to refresh this parameters from the `meson.build` without completely removing the build dir?

**Comment by jpakkane** [comment]
Updated the faq with said information.
