### ISSUE TITLE
Recursive declare_dependency()

### ISSUE THREAD

**Issue by rhd** [mesonbuild/meson#321]
Hi Jussi,

This is somewhat related to #304 - should this work? I ran into this the other day. I have a library that depends on another library and there is a `declare_dependency` for both of them.

```
opencl_inc = include_directories('/usr/local/opencl12', '/opt/AMDAPP/include')
opencl_dep = declare_dependency(
    include_directories: opencl_inc,
    dependencies: find_library('OpenCL', dirs:'/usr/lib64'),
)

another_dep = declare_dependency(
    include_directories: another_inc,
    dependencies: opencl_dep
)

foo = executable('foo', src,
    dependencies:[another_dep],
)
```

This is the error:
```
Dependencies must be external deps
```

**Comment by rnburn** [comment]
+1. I'm also running into this issue.

**Comment by rhd** [comment]
The workaround for this would be
```
another_dep = [declare_dependency(
    include_directories: another_inc,
), opencl_dep]
```
or (which I think I like better)
```
opencl_dep = declare_dependency(
    include_directories: opencl_inc,
    dependencies: find_library('OpenCL', dirs:'/usr/lib64'),
)

another_dep = declare_dependency(
    include_directories: another_inc,
)

another_deps = [opencl_dep, another_dep]
```

Obviously, recursive deps is by far the most ideal.

**Comment by jpakkane** [comment]
I'll try to get this fixed this weekend.

**Comment by jpakkane** [comment]
Can you try the linked MR?

**Comment by rhd** [comment]
I haven't tested it, but your unit tests look exactly like how my code did at the time (one dependency level deep). :+1: I'll try to do my own test today, but it LGTM.

**Comment by rhd** [comment]
A little late, but I just played around with this change and it works for me... thanks! This is a nice addition to dependency hell.

**Comment by rhd** [comment]
Does it make sense to keep the dependency list as a `set` (or maybe `OrderedDict`) instead of a `list`? Or will this lead to other issues?

```
a = declare_dependency(..., include_directories:include_directories('foo'))
b = declare_dependency(..., dependencies:a)
c = declare_dependency(..., dependencies:a)
d = declare_dependency(..., dependencies:[b,c])

executable('foobar', 'foobar.c',
    dependencies: d,
)
```

The include directory `-Ifoo` will get issued twice when `foobar` gets built.

**Comment by jpakkane** [comment]
Having -I or -L flags multiple times is harmless. We might put a filter in the backend generator to remove dupes because they can come from other places, too. However due to the way linking works, you might need to put library flags there multiple times (usually this means that your code is badly organised, but still).
