### ISSUE TITLE
pip install meson SyntaxError

### ISSUE THREAD

**Issue by elig0n** [mesonbuild/meson#3216]
> $ pip install meson
Collecting meson
  Downloading meson-0.45.0.tar.gz (1.2MB)
    100% |████████████████████████████████| 1.2MB 474kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-uAJEFj/meson/setup.py", line 20, in <module>
        from mesonbuild.coredata import version
      File "mesonbuild/coredata.py", line 15, in <module>
        from . import mlog
      File "mesonbuild/mlog.py", line 82
        print(*args, **kwargs)
              ^
    SyntaxError: invalid syntax

on WSL

**Comment by elig0n** [comment]
Installing python3-pip and using pip3 solved it

**Comment by nirbheek** [comment]
Please don't comment on closed issues unless your issue is exactly what it was before and it has regressed since then.

In your case I would recommend looking at what is providing `pip3` and whether it actually is Python 3.5 or newer. What's the output of `which pip3`?
