### ISSUE TITLE
Pkg-config not found.

### ISSUE THREAD

**Issue by elig0n** [mesonbuild/meson#3221]
Found Pkg-config: NO

app\meson.build:21:0: ERROR: Pkg-config not found.

Windows 10, pip3

**Comment by nirbheek** [comment]
Not sure what you're reporting here. If you don't have pkg-config in `PATH` it can't be found, of course? :)

**Comment by elig0n** [comment]
I have it in PATH

**Comment by nirbheek** [comment]
Where is it? Can you run it manually? What's the value of `%PATH%` or `$PATH` in the console you're running meson in?

**Comment by elig0n** [comment]
It is in its place, I can run it. Still...

**Comment by nirbheek** [comment]
Please give the details that I asked for. We're not clairvoyants, so we can't really help you without details. :)

It would also be helpful if you could paste the contents of `your-builddir/meson-logs/meson-log.txt`.

**Comment by elig0n** [comment]
D:\GitHub>PATH=%PATH%:D:\Programs\pkgconfig

D:\GitHub>meson.py scrcpy scrcpy-build-win
The Meson build system
Version: 0.45.0
Source dir: D:\GitHub\scrcpy
Build dir: D:\GitHub\scrcpy-build-win
Build type: native build
Project name: scrcpy
Native C compiler: gcc (gcc 7.1.0 "gcc (x86_64-posix-seh, Built by strawberryperl.com project) 7.1.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found Pkg-config: NO

app\meson.build:21:0: ERROR: Pkg-config not found.

A full log can be found at D:\GitHub\scrcpy-build-win\meson-logs\meson-log.txt

D:\GitHub>pkg-config
Must specify at least one library at D:\Programs\Strawberry\perl\bin/pkg-config line 1200.

D:\GitHub>type D:\GitHub\scrcpy-build-win\meson-logs\meson-log.txt
Build started at 2018-03-11T22:09:13.769471
Main binary: c:\users\x\appdata\local\programs\python\python36\python.exe
Python system: Windows
The Meson build system
Version: 0.45.0
Source dir: d:\GitHub\scrcpy
Build dir: d:\GitHub\scrcpy-build-win
Build type: native build
Project name: scrcpy
Sanity testing C compiler: gcc
Is cross compiler: False.
Sanity check compiler command line: gcc d:\GitHub\scrcpy-build-win\meson-private\sanitycheckc.c -o d:\GitHub\scrcpy-build-win\meson-private\sanitycheckc.exe
Sanity check compile stdout:

\-----
Sanity check compile stderr:

\-----
Running test binary command: d:\GitHub\scrcpy-build-win\meson-private\sanitycheckc.exe
Native C compiler: gcc (gcc 7.1.0 "gcc (x86_64-posix-seh, Built by strawberryperl.com project) 7.1.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found Pkg-config: NO

app\meson.build:21:0: ERROR: Pkg-config not found.

**Comment by nirbheek** [comment]
https://github.com/mesonbuild/meson/pull/3222 has details on what your issue is, and should fix it. Thanks for reporting it!

**Comment by elig0n** [comment]
OK. In the mean time how can I tell it to use my other version ?

**Comment by nirbheek** [comment]
You should put it in the beginning of PATH, not at the end. Also your syntax was incorrect, path-separator on Windows is `;` not `:`.

```
> set PATH=D:\Programs\pkgconfig;%PATH%
```

**Comment by soulilya** [comment]
Doesnt work for me. My ass i burning! Why use every time new tools? Its killing open source. Every time new glich tools, that dosnt work propertly.

**Comment by eli-schwartz** [comment]
I'm not sure what you're trying to say about something burning, "new tools", or the death of open source.

Note that Meson doesn't require you to use pkg-config, one of the very old tools of open source. You can do complicated and flaky compiler checks and manually found libraries instead, just like primitive hand-rolled build systems from decades ago that predate even GNU autotools (autotools has good integration with pkg-config and most autotools projects I see require it).

I don't advise it, but you can do that.

However Meson does also allow you to use subprojects, and even provides a bunch of them for common libraries.

...

Would you mind explaining why it doesn't work for you? If you don't explain the problem, no one can help you find a solution.

**Comment by soulilya** [comment]
Ok, im trying cross compile wayland from catalina VM on windows 10.
Autotools and configure woking just fine. I spend HOURS to read manual for meson.  Every time same result:

Found Pkg-config: NO
Found CMake: NO
Run-time dependency libffi found: NO (tried framework)

libffi is compiled and installed, PKG_CONFIG_PATH and LD_LIBRARY_PATH are set propertly. And still after spending 9 hours - nothing. No clue.

I'm not sure what you're trying to say about something burning, "new tools", or the death of open source.

Ok, take a look. You want to do something, try somthing new you take a tool and dont understand why things are happening, Even after reading docs and examples. After that, i want leave it all and forget about it. Ask yourself do you want use tool with 2k issuses? Somthing is wrong with that right? When you want to go somwhere you just take a car and drive (with driving license).

P. S. With autotools i have never have any problems.

**Comment by eli-schwartz** [comment]
> Ask yourself do you want use tool with 2k issuses? Somthing is wrong with that right? When you want to go somwhere you just take a car and drive (with driving license).

You will probably not be happy to find out how many issues autotools has.

Also note that many of the issues you are seeing, are feature requests and not bugs.

> Ok, im trying cross compile wayland from catalina VM on windows 10.

Have you read:
https://mesonbuild.com/Cross-compilation.html

**Comment by soulilya** [comment]
Yes, im tryed many things.
 Ok, make it more specific. How i can set path to external libs? 
You can take a look i have propertly set env:
export ARCH=armv7           
export SDK=iphoneos
export DEPLOYMENT_TARGET=8.4
export CPPFLAGS=-I/usr/local/armv7-apple-darwin/include
export PKG_CONFIG_PATH=/usr/local/armv7-apple-darwin/lib/pkgconfig
export LDFLAGS=-L/usr/local/armv7-apple-darwin/lib
export CFLAGS="-arch $ARCH -isysroot $(xcrun -sdk $SDK --show-sdk-path) -m$SDK-version-min=$DEPLOYMENT_TARGET"
export LD_LIBRARY_PATH=/usr/local/armv7-apple-darwin/lib

admin@Mac-Admin wayland % ls /usr/local/armv7-apple-darwin/include          
X11			ffitarget.h		pnglibconf.h
expat.h			libpng16		zconf.h
expat_config.h		pixman-1		zlib.h
expat_external.h	png.h
ffi.h			pngconf.h
admin@Mac-Admin wayland % ls /usr/local/armv7-apple-darwin/lib              
cmake				libpixman-1.dylib
libexpat.1.8.8.dylib		libpixman-1.la
libexpat.1.dylib		libpng.a
libexpat.a			libpng.dylib
libexpat.dylib			libpng.la
libexpat.la			libpng16.16.dylib
libffi.7.dylib			libpng16.a
libffi.8.dylib			libpng16.dylib
libffi.a			libpng16.la
libffi.dylib			libz.1.2.12.dylib
libffi.la			libz.1.dylib
libpixman-1.0.40.0.dylib	libz.a
libpixman-1.0.dylib		libz.dylib
libpixman-1.a			pkgconfig

# This is a cross compilation file from OSX to iPhone
# Apple keeps changing the location and names of files so
# these might not work for you. Use the googels and xcrun.

[binaries]
c = 'clang'
cpp = 'clang++'
objc = 'clang'
objcpp = 'clang++'
ar = 'ar'
strip = 'strip'
pkg-config = 'pkg-config'

[built-in options]
c_args = ['-arch', 'armv7', '-miphoneos-version-min=8.4', '-isysroot', '/Users/admin/Downloads/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.4.sdk']
cpp_args = ['-arch', 'armv7', '-miphoneos-version-min=8.4', '-isysroot', '/Users/admin/Downloads/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.4.sdk']
c_link_args = ['-arch', 'armv7', '-miphoneos-version-min=8.4', '-isysroot', '/Users/admin/Downloads/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.4.sdk']
cpp_link_args = ['-arch', 'armv7', '-miphoneos-version-min=8.4', '-isysroot', '/Users/admin/Downloads/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.4.sdk']
objc_args = ['-arch', 'armv7', '-miphoneos-version-min=8.4', '-isysroot', '/Users/admin/Downloads/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.4.sdk']
objcpp_args = ['-arch', 'armv7', '-miphoneos-version-min=8.4', '-isysroot', '/Users/admin/Downloads/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.4.sdk']

[properties]
root = '/Users/admin/Downloads/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer'
has_function_printf = true
has_function_hfkerhisadf = false
allow_default_for_cross = true

[host_machine]
system = 'darwin'
cpu_family = 'arm'
cpu = 'arm'
endian = 'big'

Thanks for your help, im very appreciate it!

**Comment by soulilya** [comment]
Ok, pkgconfig = 'pkg-config' you must set it manually. Solved.

**Comment by shrkamat** [comment]
note in the above example it should have been `pkgconfig = 'pkg-config'`. I spent quiet some time figuring it out.

**Comment by lbmeng** [comment]
> Ok, pkgconfig = 'pkg-config' you must set it manually. Solved.

This saves my time when doing cross-compiling with meson.

The https://mesonbuild.com/Cross-compilation.html should be updated to explicitly mention this.

**Comment by bonzini** [comment]
pkgconfig vs. pkg-config was fixed in 1.3.0; pkgconfig is now deprecated.

See https://mesonbuild.com/Release-notes-for-1-3-0.html
