### ISSUE TITLE
Rename functionality for executable, shared_module and jar

### ISSUE THREAD

**Issue by sarum9in** [mesonbuild/meson#3224]
Moving discussion about this here. I don't think we should support rename on install for `static_library()` and `shared_library()`, but for anything relocatable it should be possible.
Related to #2861.

**Comment by rilian-la-te** [comment]
Especially for modules (.so) and JARs, it is important for me to move from CMake)

**Comment by nirbheek** [comment]
> Especially for modules (.so) and JARs, it is important for me to move from CMake)

What's the use-case for having separate names in the build directory and the install prefix for those?

**Comment by sarum9in** [comment]
I don't think there is. We should just generate file in build directory with the same name as installed. But it does not have to be the same as target name.

**Comment by rilian-la-te** [comment]
I need to install GTK2 and GTK3 modules with same name from same sources to different directories.

**Comment by rilian-la-te** [comment]
In CMake I do it as [there](https://github.com/rilian-la-te/vala-panel-appmenu/blob/master/subprojects/appmenu-gtk-module/src/CMakeLists.txt). How to do it on Meson without rename?

**Comment by sarum9in** [comment]
Can we do this with code below (it's not currently supported)?
```meson
shared_module('target-name1', srcs, install : true, install_dir : 'libdir/myapp', rename : 'my-target-1')
shared_module('target-name2', srcs, install : true, install_dir : 'libdir/myapp', rename : 'my-target-2')
```

I don't think it will even need to compile all sources twice, only link.

**Comment by rilian-la-te** [comment]
If rename will be handled, we can, AFAIK) And this is the cause why I want rename for shared modules - modules can require a specific name, and we may want to rename it on install.

**Comment by sarum9in** [comment]
Rename for `shared_module()` is in my personal priority list, specifically for https://github.com/artyom-beilis/cppcms framework support. But we need to figure out the API here and this warrants a discussion because unlike plain data there are weird corner cases with extensions and so on.

**Comment by rilian-la-te** [comment]
For me a Jar manifest is also important and other goodies for CMake's UseJava (remove requirement for directory layout for jars).

**Comment by nirbheek** [comment]
I actually don't understand this entire discussion. It's trivial to remove the restriction that Meson has about having target names be unique across the entire build, and that solves this. Renaming build targets on install completely breaks subprojects and uninstalled runs, and should not be implemented.

**Comment by rilian-la-te** [comment]
And how we should name, for example, 2 GTK modules, which required to have same name and built from same sources? Because target at least in a folder level should be unique, AFAIU.

**Comment by sarum9in** [comment]
@nirbheek if uniqueness is trivial then I agree that we don't need rename. I am sorry I didn't realize it is easy to implement. I will try to look into #2861, any hints what I should consider or what to change are appreciated.

**Comment by nirbheek** [comment]
> I will try to look into #2861, any hints what I should consider or what to change are appreciated.

The only blocker that I know of (besides the edge-cases on Windows which we're already breaking) is talking to Jussi about it. It's still not clear to me what his objections about this are.

**Comment by sarum9in** [comment]
I don't see any discussion in the thread but I will follow up, thank you.

**Comment by sarum9in** [comment]
Closing as dupe of #2861

**Comment by nirbheek** [comment]
> I don't see any discussion in the thread but I will follow up, thank you.

The previous discussion was on https://github.com/mesonbuild/meson/pull/1867.
