### ISSUE TITLE
Issue running Meson via Python subprocess.run()

### ISSUE THREAD

**Issue by kjerstadius** [mesonbuild/meson#3230]
I'm seeing a repeatable issue when running Meson from a Python script via subprocess.run(). Basically I want to create a build helper script that deals with a few things (such as setting multiple build options based on a single command line argument) before invoking Meson to initialize the build dir, as well as handle multiple Meson invocations in order to run multiple builds with different compilers (in different build dirs of course) on a CI system. The issue I've found is that it seems that the initial 'meson _build_dir_' invocation returns before it's fully completed. This causes the subsequent 'meson configure' call to not always have an effect, which is clearly problematic. What's worse is that it only happens sometimes and when it happens, running 'meson configure' would have you believe that the option is set as the script would configure it, but calling ninja any number of times doesn't make the option actually update. I've created a [small example](https://github.com/mesonbuild/meson/files/1804353/simple_test.zip) where the build often behaves as if foo=foo, even though 'meson configure' states that foo=bar. Interestingly, inserting a sleep of 1 second after the initial call to meson seems to avoid the problem, which is what leads to me believe that call is returning prematurely. This sleep is in my example code, but commented out (line 7 in build.py). To run the test, simply unzip and run build.py. It should error out, but quite often will not.

I have tested and confirmed this issue using Python 3.6.4 and meson 0.45 on both Linux (Arch Linux 4.15.5-1) and Mac OSX High Sierra. As far as I can tell, behavior is identical if I use subprocess.call(), which I guess is to be expected.

I realize that maybe there's a more straightforward way to invoke Meson from Python seeing as Meson itself is implemented in Python, but I couldn't really find any documentation indicating that to be the case. Please direct me towards any such examples if my use case here is outright wrong.

Thanks
/Richard

**Comment by kjerstadius** [comment]
As it happens, it seems this problem isn't limited to subprocess.run(), or even Python. Just running the following from bash gives the same (often incorrect) result:

`meson build && meson configure build '-Dfoo=bar' && ninja -C build`

**Comment by nirbheek** [comment]
This is because of https://github.com/ninja-build/ninja/issues/371. You can either apply the attached patch, use an unreleased version of Ninja, [use the binary we use in our CI](https://nirbheek.in/files/binaries/ninja/), or add a `sleep 2` between configure and ninja. 

Also note that this will never work on MacOS High Sierra as long as you're using HFS+ since it only stores timestamps in 1-second resolution.

**Comment by kjerstadius** [comment]
Well that explains it. Thank you!

Any idea on when the next official release of ninja will be made? It seems the official release cadence is, well, not supersonic... Also, thanks for the gotcha on HFS+. I have upgraded to APFS, but looking at the ninja mailing list it seems that may actually bring other issues related to the nanosecond timestamp resolution. I guess you can't have everything ;) Anyway, I'll probably just insert an 'if os == darwin' to ensure HFS+ compatibility. Thanks again.

**Comment by nirbheek** [comment]
> Any idea on when the next official release of ninja will be made? It seems the official release cadence is, well, not supersonic...

Yes, it's a bit of a strange situation. Ninja seems to be unmaintained at this point, and that may become a problem in the future.

> I have upgraded to APFS, but looking at the ninja mailing list it seems that may actually bring other issues related to the nanosecond timestamp resolution

Did you mean [this post](https://groups.google.com/forum/#!topic/ninja-build/WBYgTsipznw)? That seems to be a problem with `cp -p` on macOS not having nanosecond resolution, and instead chopping off the last 3 digits to retain only microsecond resolution.

Meson build files should avoid using external tools like `cp` anyway.

**Comment by kjerstadius** [comment]
> Yes, it's a bit of a strange situation. Ninja seems to be unmaintained at this point, and that may become a problem in the future.

Should I be worried that ninja is seemingly in limbo? What is the Meson dev team stance on the subject?

> Did you mean this post? That seems to be a problem with cp -p on macOS not having nanosecond resolution, and instead chopping off the last 3 digits to retain only microsecond resolution.

Yes, that's the one I was thinking of. You're right though, and I guess I read it a bit too quickly as I interpreted it as something that would have to be fixed in ninja, whereas it was a case of "don't do this".

Anyway, thanks for your explanations. I really appreciate the quick turnaround.

**Comment by nirbheek** [comment]
> Should I be worried that ninja is seemingly in limbo? What is the Meson dev team stance on the subject?

If the situation becomes dire, we can always ask them nicely to let us help maintain it or we can fork it. @QuLogic is already familiar with the Ninja codebase, and he ~~enjoys~~ is good at writing C++ ;)
