### ISSUE TITLE
Can't build with nested submodules

### ISSUE THREAD

**Issue by mkrogius** [mesonbuild/meson#3237]
I have the following structure. A top-level project, A, containing a subproject, B, in a submodule which itself contains a subproject, C, in a submodule. When I attempt to build I get the error: 'AssertionError: Unknown git submodule output: b'''. See the attached file for the full trace.

A
-- B
   -- C

Debugging a little, it looks like meson tries to run 'git submodule status' for the innermost submodule, but it runs this command in the outermost project instead of the middle one. In other words, it does

cd A; git submodule update C
 
when it should do

cd B; git submodule update C

[bug_rep.txt](https://github.com/mesonbuild/meson/files/1808320/bug_rep.txt)

**Comment by jpakkane** [comment]
http://mesonbuild.com/Subprojects.html#why-must-all-subprojects-be-inside-a-single-directory

**Comment by mkrogius** [comment]
Thank you for the reference, I hadn't seen that before.

What would be the right way to solve this problem? I already have a project B which contains a subproject C as a submodule and I am now creating a new project, A, which needs to include B as a subproject/submodule.

My current solution is to add a symlink from the root of A to the nested submodule. This works, but I feel like this might not be the best solution with meson?

**Comment by jpakkane** [comment]
Newest Meson has the `meson wrap promote` command to bring dependencies from subsubprojects to the top level. Depending on your setup it might or might not be the right thing to do. There are many different ways of setting up your dependency tree. [Here is a blog post with some ideas.](http://nibblestew.blogspot.com/2017/07/managing-build-definitions-of-big.html).

This is all fairly new and there has not yet been enough experience for best practices to form.

**Comment by mkrogius** [comment]
Thanks! The liftoff example looks exactly like what I was thinking of doing, I just wasn't sure if it would be possible in meson and now I know that it is possible, and I think if I were working on a larger project which might ever need to be released I would switch to this method of writing dependencies.
