### ISSUE TITLE
PyQT5 is GPLv3+ licensed

### ISSUE THREAD

**Issue by drbo** [mesonbuild/meson#324]
PyQT5 is licensed under the GNU GPL v3+.  Therefore, meson inherits this license.  The best solution would be to switch to an alternative GUI such as PySide or PyGObject (both LGPL2.1+).

**Comment by jpakkane** [comment]
This only affecst meson-gui, not Meson proper as it does not use PyQT. The situation is a bit unfortunate as PySide does not have Qt5 support (in Ubuntu at least) and PyGObject is not as good at cross platformness. The gui app has not had a lot of love recently and I'm not entirely sure if anyone is even using it. So we might just drop it.

**Comment by drbo** [comment]
[PySide2](https://github.com/PySide/pyside2) has QT5 support.

**Comment by jpakkane** [comment]
The gui is dead for now so closing.
