### ISSUE TITLE
configure_file function install parameter

### ISSUE THREAD

**Issue by inigomartinez** [mesonbuild/meson#3248]
Looking at the [functions documentation](http://mesonbuild.com/Reference-manual.html#configure_file), unlike other similar functions, it doesn't seem to have an `install` parameter. However, the parameter is on the [list of permitted parameters](https://github.com/mesonbuild/meson/blob/master/mesonbuild/interpreter.py#L1495).

The parameter should be removed from the list of permitted parameters or it should be documented properly.

**Comment by mcatanzaro** [comment]
In particular, it's weird that files may be installed even if passing `install: false`. See https://bugzilla.gnome.org/show_bug.cgi?id=794372.

**Comment by FelixSchwarz** [comment]
The docs list an "install" parameter now. Maybe this was fixed in the mean time? (or I misunderstood your ticket)

**Comment by nirbheek** [comment]
Yep, this is fixed now.
