### ISSUE TITLE
Incremental construction of include_directories()

### ISSUE THREAD

**Issue by byron-hawkins** [mesonbuild/meson#3249]
I'm using Meson to build a project on a variety of different workstations, along with some machines in a cluster where I have little control over the installed packages (and I do not have root). So in some cases I need to manually install dependencies to a local directory, and in other cases the dependencies are all available as standard package distros. This makes it awkward to assemble the `include_directories` in Meson because it cannot be assembled incrementally. For example, I have:

    if (libelf_local)
        third_party_inc = include_directories(dynamorio_dir + '/include',
                                              dynamorio_dir + '/ext/include',
                                              papi_dir + '/src',
                                              libelf_dir + '/include')
    else
        third_party_inc = include_directories(dynamorio_dir + '/include',
                                              dynamorio_dir + '/ext/include',
                                              papi_dir + '/src')
    endif

In a bigger project, this could get extremely difficult to manage. What would be much better is this:

        third_party_inc = include_directories(dynamorio_dir + '/include',
                                              dynamorio_dir + '/ext/include',
                                              papi_dir + '/src',
                                              libelf_inc) # possibly empty (set earlier)

It's just a matter of allowing an existing `include_directories` object to be copied into a new one.

**Comment by NickeZ** [comment]
I think you can do like this:

```
    libelf_inc = include_directores(...)
    third_party_inc = [include_directories(dynamorio_dir + '/include',
                                          dynamorio_dir + '/ext/include',
                                          papi_dir + '/src'),
                       libelf_inc]
```

**Comment by byron-hawkins** [comment]
Nice! Seems to work fine, thanks for the quick solution.
