### ISSUE TITLE
`b_ndebug` set to `if-release` is ineffective

### ISSUE THREAD

**Issue by alex-robbins** [mesonbuild/meson#3258]
`-DNDEBUG` is not passed to GCC, even if `buildtype` is `'release'` and `b_ndebug` is `'if-release'`. 

A cursory investigation reveals that `options['buildtype']` [in compilers.py] raises a `KeyError`...

[in compilers.py]: https://github.com/mesonbuild/meson/blob/f48da481abc6d15f722a6c8083e79b4017a84fc4/mesonbuild/compilers/compilers.py#L318

**Comment by sarum9in** [comment]
Should be fixed by #3274
Thanks for your hint about `KeyError`, it helped a lot with debugging.

**Comment by alex-robbins** [comment]
Thanks.
