### ISSUE TITLE
meson adds a hard coded path for .so files before and after 'ninja install'

### ISSUE THREAD

**Issue by rhd** [mesonbuild/meson#3262]
Hi Jussi et al.,

When we use `find_library()` for things in odd places, meson leaves behind a hard coded path for the `.so` file after `ninja install`.

Example:

This is after a `ninja install` was done.

```
$ readelf -d dist/bin/encoder 

Dynamic section at offset 0x8f088 contains 26 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [/usr/local/tungsten-3.6.0/lib/linux-x64-gcc4.8/libtungstencore.so]
 0x0000000000000001 (NEEDED)             Shared library: [/usr/local/tungsten-3.6.0/lib/linux-x64-gcc4.8/libtungstenmch264encoder.so]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
```

I appreciate this for running out of the build dir, but after a `ninja install`, I would expect those full paths to get stripped such that only `libtungstencore.so` was remaining. This hard coded path is very troublesome when dealing with machines that aren't set up 100% the same way. This same thing happens if the `.so` files in in the source directory too... which is even worse.

Thoughts?

Thanks!

**Comment by jpakkane** [comment]
This usually happens if the library one links against does not have `soname` properly set. Can you try linking a dummy exe manually against it with both an absolute path and with `-L/foo` and `-lbar` and report what gets written in the file.

**Comment by rhd** [comment]
Hi @jpakkane, I was just about to post my workaround... which is to use `link_args` in the `dependency()` like `link_args: ['-L/usr/local/tungsten-3.6.0/lib/linux-x64-gcc4.8/', -ltungstencore']`

This works and removes the full path to `libtungstencore.so`.

**Comment by rhd** [comment]
Also, on the gcc command line meson is adding the full path to the .so when `find_libary()` is used: `ccache g++-4.8.1  -o apps/encoder/src/tungsten/encoder ... /usr/local/tungsten-3.6.0/lib/linux-x64-gcc4.8/libtungstencore.so ...`

Which I guess explains the hard dependency on that specific file location.

**Comment by rhd** [comment]
Oh - so this is the issue...

```
$ objdump -p /usr/local/tungsten-3.6.0/lib/linux-x64-gcc4.8/libtungstencore.so | grep SO
$
```

The `SONAME` is not set.

**Comment by jpakkane** [comment]
There you go then. That is a bug for Tungsten upstream.

**Comment by rhd** [comment]
Crap - I'm guessing you're not willing to deal with broken `.so` files by detecting this case and doing something different?

**Comment by rhd** [comment]
@jpakkane Just want to say thanks - you and the rest of the team are amazing. :+1: 

I'm going to close this issue. If you think this is worth dealing with, let me know and I'll open a new issue.

**Comment by mxpawl** [comment]
Is there any workaround for this issue that doesn't involve adding the library to the link arguments of the final binary explicitly?

I have the following situation - an external dynamic library A (one that I do not compile) is needed by a static library B that I build with meson. Then this static library B is linked to several different targets, executables, dynamic libraries and static libraries.

If I declare library A as a dependency of library B then the linking is handled automatically by meson and I don't have to keep that dependency in mind when declaring further targets. But since library A has no SONAME, I have to explicitly link to that library every time I use library B?
