### ISSUE TITLE
CPPFLAGS are not appended to `fortran_args`

### ISSUE THREAD

**Issue by cschwan** [mesonbuild/meson#3280]
`CPPFLAGS` are the C-preprocessor flags and according to [GNU make](https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html) they are also used for pre-processing Fortran files. `meson` doesn't follow this practice, meaning that

    CPPFLAGS="-I$HOME/prefix/include" meson buildir

does not populate the `fortran_args` variable. Is this a bug or the intended behavior?

**Comment by scivision** [comment]
CMake doesn't seem to follow this behavior. I would rather specify the Fortran variables separately.

**Comment by cschwan** [comment]
My problem is really that GCC doesn't offer any way to set the include paths for the Fortran compiler with an environment variable, unlike C or C++ where you can set `CPATH` once and for all. This means that I always have to pass `-Dfortran_args=-I/my/path/to/my/special/libraries` to `meson configure`, which, admittedly, is not meson's fault. It would be nice, however, if meson offered a way to work around this problem (which seems to be a known [problem](https://stackoverflow.com/questions/23991664/gfortran-include-path-is-there-an-alternative-to-passing-multiple-i-options)).

Reading the environment variable `CPPFLAGS` would be one way, but I'd be happy with any other environment variable. But I'd also understand if someone closes this with WONTFIX, as its technically not problem of meson.

**Comment by jpakkane** [comment]
There's `FFLAGS` for Fortran. [See here](https://mesonbuild.com/Reference-tables.html#compiler-and-linker-flag-environment-variables). Is that sufficient for you?

**Comment by cschwan** [comment]
It is! Thank you and sorry for the noise.
