### ISSUE TITLE
Binaries for build->build tools

### ISSUE THREAD

**Issue by Ericson2314** [mesonbuild/meson#3282]
The cross documentation mentions the `[binaries]` section of the cross file, along with `native : true` for building build tools. But how are the tools for those native builds chosen? Just as autoconf has support for various `*_FOR_BUILD` variables (like `CC_FOR_BUILD`), I think it would be best to support `[binaries_for_build]` for that purpose. Maybe `[binaries]` could be renamed `[binaries_for_host]` for consistency, too.

CC @eternaleye

**Comment by nirbheek** [comment]
Let's discuss this on https://github.com/mesonbuild/meson/issues/3969.

**Comment by Ericson2314** [comment]
Quite separate from #3969, native files have a `[binaries]` section, so this is totally done.
