### ISSUE TITLE
Meson results in larger firmware when building executable incorporating static library (-fPIC)

### ISSUE THREAD

**Issue by justyn** [mesonbuild/meson#3291]
I have been evaluating using Meson for building the firmware for an embedded system (ARM Cortex-M0+).

The vendor library for the system requires compilation with certain flags. In previously used build systems (SCons and also Make) the objects for the vendor library were compiled with a separate set of flags to the rest of the system. Since this is not supported in Meson I have attempted to declare them using static_library.

However the resultant binary is larger when the vendor files are specified as a static library rather than as files along with the rest of the code, even when extracting the object files from the library using extract_all_objects() before linking.

Looking at the Ninja build commands, they are linked identically in both cases, and the only difference in compilation is the use of the -fPIC flag for the files when they are compiled for the static library. Furthermore, I can see the Global Offset Table section in the resultant objects prior to linking. LTO is disabled.

The difference in firmware size is significant (7.5% larger for the program in flash). The results of arm-none-eabi-size in both cases are below.

```
   text	   data	    bss	    dec	    hex	filename
   5616	      0	  10072	  15688	   3d48	vend_not_lib.elf
   6036	     84	  10072	  16192	   3f40	vend_as_lib.elf
```
Is there a way of disabling the use of -fPIC for a static library in this case, or an alternative way of compiling some files with different flags?

Versions:
Meson 0.42.1
Ninja 1.7.2
arm-none-eabi-gcc (GNU Tools for Arm Embedded Processors 7-2017-q4-major) 7.2.1 20170904 (release)

**Comment by jpakkane** [comment]
The use of `-fPIC` on static libraries is governed by the `b_staticpic` build option. Setting it to `false` should achieve that.

**Comment by justyn** [comment]
Great, that has resolved the problem, thank you.

For anyone else, the base options and their descriptions can be seen by running `meson configure` in the build directory. I don't think they are covered in the Meson docs.
