### ISSUE TITLE
cc.has_header_symbol() etc. checks should add global args to checks

### ISSUE THREAD

**Issue by tp-m** [mesonbuild/meson#3301]
If I do:
```
add_project_arguments('-D_GNU_SOURCE', language: 'c')
cc = meson.get_compiler('c')
cc.has_header_symbol('sched.h', 'CPU_COUNT')
```

I would expect the `has_header_symbol()` check to be done with `-D_GNU_SOURCE`, since that's the configuration my code base will "see" if you like. Without this, the check fails.

I know I can work around this by passing a `prefix` kwarg, but I don't think this should be needed here.

I think adding global/project args is the right thing to do here, and what users will expect intuitively.

Risk of breaking anything should be fairly low (famous last words).

**Comment by jpakkane** [comment]
We explicitly do not do that to ensure things are not order dependent. This is even documented (somewhere, I don't remember offhand where).

**Comment by tp-m** [comment]
Right, thanks. I guess it's also problematic if people add warning or -Werror to global args, or when people rely on target cargs to override things from the environment or global args.
