### ISSUE TITLE
gtkdoc-scangobj fails to find the shared library it scans (W32)

### ISSUE THREAD

**Issue by LRN** [mesonbuild/meson#3307]
For example:
`Error in gtkdoc helper script:`
`'mingw\\bin\\python.EXE' failed with status 3221225781`
`WARNING:root:Running scanner failed: -1073741515, command: ./gtk4-scan.exe`
This is because the shared library being scanned is not in library search path. On *nix that is handled by adjusting `LD_LIBRARY_PATH`, but on W32 the variable that needs adjustment is `PATH`, and meson doesn't change it.

Here's a patch to fix that.
[0001-gtk-doc-Use-LD_LIBRARY_PATH-to-modify-PATH-on-W32.patch.txt](https://github.com/mesonbuild/meson/files/1843401/0001-gtk-doc-Use-LD_LIBRARY_PATH-to-modify-PATH-on-W32.patch.txt)

**Comment by jpakkane** [comment]
Please file a MR with that instead.

**Comment by lazka** [comment]
I can confirm that his fixes the docs build for pango

**Comment by lazka** [comment]
I've create #3975 for this.
