### ISSUE TITLE
Using gnome.compile_resources with generated files

### ISSUE THREAD

**Issue by smspillaz** [mesonbuild/meson#3309]
More of a question than a bug report, but something I haven't been able to figure out yet as a new user

How would I use `gnome.compile_resources` with files created by a `generator`? When I try to pass the list of generated files directly to the `dependencies` argument, I get:

```meson
scss_gen = generator(
  meson_sassc,
  output: '@BASENAME@.css',
  depfile: 'sassc.deps',
  arguments: ['@INPUT@', '@OUTPUT@', '@DEPFILE@']
)

scss_generated_css = scss_gen.process(
    scss_sources,
    process_path_from: meson.current_source_dir()
)
```

```
Meson encountered an error in file meson.build, line 37, column 0:
Unexpected dependency type <mesonbuild.build.GeneratedList object at 0x7f4afb015240> for gnome.compile_resources() "dependencies" argument.
Please pass the return value of custom_target() or configure_file()
```

Trying to use a target instead, it isn't clear to me how I can set the generated outputs as the outputs of the target:

```meson
scss_generated_css_target = custom_target(
    'generate-template-scss',
    input: scss_generated_css,
    output: scss_generated_css,
    command: 'touch @OUTPUT@'
)
```

```
Meson encountered an error in file data/meson.build, line 31, column 0:
Output argument not a string.
```

For what its worth, here's the project I'm working on at the moment: https://github.com/endlessm/eos-knowledge-content-renderer/blob/T21272/data/meson.build (and https://github.com/endlessm/eos-knowledge-content-renderer/blob/T21272/meson.build for  `gnome.compile_resources` usage)

**Comment by TingPing** [comment]
Using a `custom_target()` is correct, just remove the generator entirely.

**Comment by smspillaz** [comment]
> Using a custom_target() is correct, just remove the generator entirely.

Thanks for the help. If that were the case, how would we set dependency information between generated sources? Currently I use the depfile functionality in `generator()`

**Comment by TingPing** [comment]
It has the same `depfile` argument.

**Comment by smspillaz** [comment]
Ah, got it, thanks.

The other thing that isn't entirely clear to me is how we would support a variable number of inputs for `custom_target`. At least from reading the documentation:

> @INPUT@ the full path to the input passed to input. If more than one input is specified, all of them will be substituted as separate arguments only if the command uses '@INPUT@' as a standalone-argument. For instance, this would not work: command : ['cp', './@INPUT@'], but this would: command : ['cp', '@INPUT@'].

It seems to me like if I had an input like `['foo', 'bar', 'baz']` this would run `'command', 'foo', 'bar', 'baz'`. Or does it invoke the command N times?

**Comment by TingPing** [comment]
It expands to a single command with multiple arguments.

**Comment by TingPing** [comment]
If you need multiple commands you can just `foreach` over them.

**Comment by smspillaz** [comment]
Hrm okay, I'm guessing that I'll also need to make gnome.compile_resources depend on N targets too

**Comment by TingPing** [comment]
```meson
generated_targets = []
inputs = [...]
foreach input : inputs
  generated_targets += custom_target(...)
endforeach
gnome.compile_resources(..., dependencies: generated_targets)
```

**Comment by smspillaz** [comment]
Okay, after a little bit of wrangling (I needed to use `subdirs` and a meson.build file in the same subdirectory as the css files to avoid having outputs with path separators in their names), that seems to have worked. Thank you for the help!
