### ISSUE TITLE
test() should have a depends arg

### ISSUE THREAD

**Issue by TingPing** [mesonbuild/meson#3310]
It is just useful for tests that depends upon targets not built by default:

```meson
foo = custom_target(...)

test(..., depends: foo)
```

**Comment by sarum9in** [comment]
Some observations from current implementation:
- `test` target depends `meson-test`, which depends on `all`
- `foo` is not included into `all` and that's why it is not built (expected)

I see 2 options to fix this:
- add `foo` to `all`
- add `foo` to `meson-test`

**Comment by sarum9in** [comment]
And now I see awesome piece of code `get_build_by_default_targets()`. First it lists all targets built by default, then it lists all exe arguments with a comment saying
```text
Get all targets used as test executables and arguments. These must
also be built by default. XXX: Sometime in the future these should be
built only before running tests.
```

This is definitely right place to put this logic. If in the future we split move executables that are used only in tests out of `all`, we will automatically move other dependencies as well.

**Comment by jpakkane** [comment]
The goal of that is that we should be able to do something like:

    meson test --minimal-rebuild testname

And then it would only build the targets needed to run that one test. This could then be used for e.g. fast automatic git bisect searches.
