### ISSUE TITLE
Add way to use custom configure_file formats

### ISSUE THREAD

**Issue by eintw1ck** [mesonbuild/meson#3311]
For example outputting:
```
%define ARCH_AARCH64 0
%define ARCH_ARM 0
%define ARCH_AVR32 0
```
Without having to have a .in file such as:
```
%define ARCH_AARCH64 @ARCH_AARCH64@
%define ARCH_ARM @ARCH_AARCH64@
%define ARCH_AVR32 @ARCH_AARCH64@
```

A couple ways I thought to do this:

1. Implement foreach for configuration_data which would allow:
```
asm_conf = ''
foreach c : configuration_data
    asm_conf += '%define @0@ @1@'.format(c, configuration_data.get(c, false) ? 1 : 0)
endforeach
```
2. Allow definitions of custom formats for configure_file to use (unsure of how this would work)

**Comment by tp-m** [comment]
So basically you want standard `configure_file()` behaviour when no input file is specified, only that instead of `#define` you need it to be `%define` ?

**Comment by nirbheek** [comment]
What will consume that output?

**Comment by eintw1ck** [comment]
@nirbheek it is then included into nasm/yasm assembler files. For some context, we are potentially trying to port @FFmpeg’s multi thousand line shell script + hundreds of makefiles to meson.

**Comment by nirbheek** [comment]
Sounds like a kwarg like `format: ('nasm'|'c')` would be appropriate, with the default being `'c'` if unspecified. I'm sure people will ask for support in the future for other formats.

**Comment by ystreet** [comment]
Is this not https://github.com/mesonbuild/meson/pull/3636 ?

**Comment by tp-m** [comment]
I think so, yes.
