### ISSUE TITLE
Cannot locate objects previously found with find_program() in MINGW

### ISSUE THREAD

**Issue by jtm94** [mesonbuild/meson#3321]
The test case below will create build files under ubuntu 16.04 native / ubuntu 16.04 cross to mingw and MSYS2/mingw native however it crashes when running ninja on MSYS2/mingw with the message
`ninja: error: '/usr/bin/env.exe', needed by 'test.txt', missing and no known rule to make it`

```meson
project('mingw-test', 'c',
  meson_version: '>=0.40.0',
)

host_os = host_machine.system()
message('Host os: ' + host_os)

# Build system environment
build_os = build_machine.system()
message('Build os: ' + build_os)

build_platform_win32 = (build_os.startswith('mingw') or 
                        build_os.startswith('cygwin') or 
                        build_os.startswith('windows'))

native_bin_ext  = ( build_platform_win32 ? '.exe'  : '' )

env_bin = find_program('env' + native_bin_ext, required: true, 
  native: true)

target = custom_target(
  'test_target',
  output: [ 'test.txt', ],
  command: [
    env_bin,
    'ls',
    '-al',
    env_bin.path(),
  ],
  capture: true,
  build_by_default: true,
)
```

**Comment by bredelings** [comment]
So.... is it missing on MSYS2/mingw?  Is it in the PATH?

**Comment by jtm94** [comment]
Sorry, I wasn't really as clear as I could have been.  The program exists and is located by meson `find_program()` in the configure step but is reported as missing by ninja when trying to build the project.
This is just a small test case the problem seems quite pervasive with custom targets in my set up.

**Comment by nirbheek** [comment]
Are you also using Ninja from MSYS? If so, this is an MSYS bug. There's nothing we can do it about, except to tell people to not use `env` on Windows.

Basically, MSYS tools believe there is a `/` on Windows, which is a lie, and not all tools provided by MSYS have been (or can be) ported to believe that lie.

In this case, Python says `env` is at `/usr/bin/env.exe`, and Ninja can't find it.

But setting that aside, why do you use `env` in your custom target commands?

**Comment by nirbheek** [comment]
> native_bin_ext = ( build_platform_win32 ? '.exe' : '' ) env_bin = find_program('env' + native_bin_ext, required: true, native: true)

Also, you don't need this code. Meson will handle this for you, for any binaries.

**Comment by jtm94** [comment]
Yes, I am using the MSYS ninja. This isn't specifically a problem with env it is a problem with custom targets and native programs - env was just a handy example.  I was using it as a means of setting up an environment in a custom target (this may just be my lack of experience with Meson).

**Comment by bredelings** [comment]
@jtm94 OK, so assuming that `env` is serving merely as an example of an executable that meson finds but ninja cannot, then it seems that 
* meson (i.e. python) find `env` at /usr/bin/env.exe
* ninja cannot find `env`

So, the question then is:
A. is env, in fact at /usr/bin/env.exe?
B. if so, why can ninja not find it?

Expanding question B:
B1. Does your version of ninja understand UNIX paths like `/usr/bin/` at all?  Or does it only handle windows paths like `C:/`?
B2. Also, do you understand the difference between mingw (which doesn't understand UNIX paths), cygwin (which hacks them in), and msys2 (which is a version of cygwin)?

**Comment by nirbheek** [comment]
One possibility, is for Meson to always convert all MSYS unix-style paths to native-Windows paths, but I do not know if there are MSYS tools that will fail if you pass them Windows-style paths.

**Comment by jtm94** [comment]
@nirbheek 

>>`native_bin_ext = ( build_platform_win32 ? '.exe' : '' ) env_bin = find_program('env' + native_bin_ext, >>required: true, native: true)`
>Also, you don't need this code. Meson will handle this for you, for any binaries.

I think that setting the exe_ext for native binaries is left over from some earlier hacking around the problem. Thanks for the reminder.

I will hack around some more to see if I can narrow down the problem.

**Comment by MathieuDuponchelle** [comment]
Here is a simple may to reproduce this:

``` meson
project('plop', 'c',
  version: '1.0',
  default_options: [
    'warning_level=1',
    'buildtype=debugoptimized',
  ],
)

pymod = import('python3')

python3 = pymod.find_python()

res = custom_target('plop',
  build_by_default: true,
  output: 'nowhere',
  command : [python3])
```

Open the mingw32 / MSYS2 shell, install ninja with `pacman -S mingw-w64-i686-ninja`, then:

``` shell
User@WinDev1709Eval MINGW32 /c/Users/User/source
$ python3 /c/Users/User/source/meson/meson.py builddir
The Meson build system
Version: 0.46.0.dev1
Source dir: /c/Users/User/source
Build dir: /c/Users/User/source/builddir
Build type: native build
Project name: plop
Native C compiler: cc (gcc 7.2.0 "cc.exe (Rev1, Built by MSYS2 project) 7.2.0")
Build machine cpu family: x86
Build machine cpu: x86
Build targets in project: 1
Found ninja-1.8.2 at /mingw32/bin/ninja

User@WinDev1709Eval MINGW32 /c/Users/User/source
$ ninja -C builddir
ninja: Entering directory `builddir'
ninja: error: '/usr/bin/python3', needed by 'nowhere', missing and no known rule to make it

User@WinDev1709Eval MINGW32 /c/Users/User/source
$
```

I assume the problem is that this version of ninja does not understand UNIX paths, not sure why the same problem doesn't occur in the MINGW64 shell. Is there another way to obtain ninja in that environment? If so, it would be helpful to specify this in the documentation.

**Comment by nirbheek** [comment]
AFAIK, this is a fundamental problem with MSYS2.

In MSYS (1.0), the shell would translate `/usr/bin` or `/c/Users/blah` paths to the corresponding `C:/blah/blah` paths automatically before passing them as arguments to a command. MSYS2 does not do this, so you should always pass Native-Windows paths to all utilities.

Personally, I would just recommend that no one should use MSYS2 on Windows at all, but that's just me ;)

**Comment by MathieuDuponchelle** [comment]
Turns out the issue for me was that I hadn't installed the mingw32 python, and was using msys' python

**Comment by nirbheek** [comment]
We now explicitly error out when someone tries to run Meson with the MSYS python: 

https://github.com/mesonbuild/meson/commit/107e061506fb0e8f2783ba07de7f6ce79634688b
