### ISSUE TITLE
Add object file specific flags

### ISSUE THREAD

**Issue by mikkelfj** [mesonbuild/meson#3345]
When compiling specific source files for dedicated hardware such as functions with or without -mavx then both version may have to be include in the project and selected based on runtime detection.

It is critically important that one version does not use -mavx because otherwise it might run incorrect instructions on some system it is distributed to where build time detection is insufficient.

dpdk librte (that I am not related to) uses a workaround by building a staging library and extracting the objects
```
avx2_tmplib = static_library('avx2_tmp',
				'acl_run_avx2.c',
				dependencies: static_rte_eal,
				c_args: '-mavx2')
		objs += avx2_tmplib.extract_objects('acl_run_avx2.c')
# later
library (..., objects: objs)
```
, but this is rather tedious on a larger scale and it results in linking staging libraries with object files even though only the object files are needed. It also requires the introducting of objects on build targets which is a bit messy. Also, it produces hard to decipher errors about target not built when calling extract_objects unless the extracted object is added to objects of some other target elsewhere, even if the tmp library itself is in fact built.

So while there are philosofical reasons for sharing build settings globally, it does not work in all places and it ought to be more convenient to deal with this, even if using special syntax such as `custom_c_args: '-mavx'` or similar.

**Comment by jpakkane** [comment]
You might consider using [the SIMD module instead](http://mesonbuild.com/Simd-module.html).

You also don't really need to extract the objects. You can instead link directly with your templib.

**Comment by mikkelfj** [comment]
I have looked at SIMD but it didn't really understand what it did. My impression was that it was a compile time selector which is fine, but does not solve the runtime detection issue.

As to linking with the library, I tried the used link_with, and link_whole in a combination of static and shared forms. In all cases it resultet in the final test application linking with all the tmp libraries, but failed to actually build a self-contained parent library with all source inside.

Using the extract_object methods did the job. So it actually deals with two separate problems: forcing embedding source from one library in another, and building with special flags.

I carefully inspected build.ninja to come at these conclusions.

**Comment by nirbheek** [comment]
> I have looked at SIMD but I didn't really understand what it did. My impression was that it was a compile time selector which is fine, but does not solve the runtime detection issue.

The SIMD module is a runtime selector of objects built with arch-specific optimisations, quote:

> Generating code to detect the proper instruction set at runtime is straightforward. First you create a header with the configuration object and then a chooser function that looks like this:

**Comment by mikkelfj** [comment]
OK, my impression was that the runtime checks where similar to trial compilations to see if a function is supported and then select an implitation. But it actually compiles and links multiple versions assuming you use link_with and provide runtime detector functions in a hidden implementation.

This would solve most problems - if it were a stable module. But not quite:
I can't use the runtime detector with already implemented 3rd party source, but that might not be an issue becaue noone is forcing me to use the hidden runtime detector logic, I can still compile for different targets.

The other issue is that link_with doesn't work. Based on the description and witout having testet SIMD, I assume it works exactly like what I already do, just automated. This means the test application will get a ton of micro libraries all linked unnecessarily (survivable), but these libraries never enter the parent library I'm trying to build. Hence extract_objects are still required. But that really is a separate issue.

**Comment by eli-schwartz** [comment]
Modern versions of meson do support uninstalled static libraries as "object libraries" properly.

For the general case of file-specific flags, this is likely not going to ever happen due to the reasons explained in #1367
