### ISSUE TITLE
g++: error: /LIBPATH:: Invalid argument

### ISSUE THREAD

**Issue by chenshuiluke** [mesonbuild/meson#335]
Hi, I'm having a problem compiling a program of mine on Windows 8.1 x64. I'm not sure what's wrong, so I'll try and give as much information as possible. 

I'm using the nuwen MinGW distro, which includes Boost, which I'm using in my code. I ran set_distro_paths.bat file in my terminal and ran `ninja` and got the following:

	[1/1] Regenerating build files
	The Meson build system
	Version: 0.27.0
	Source dir: C:\Users\Sky\git\timely_archiver
	Build dir: C:\Users\Sky\git\timely_archiver\build
	Build type: native build
	Build machine cpu family: amd64
	Build machine cpu: amd64
	Project name: recursive_readdir
	Native cpp compiler: g++ (gcc 5.2.0)
	Build targets in project: 1
	[2/2] Linking target recursive_readdir.exe
	FAILED: g++ @recursive_readdir.exe.rsp
	g++: error: /LIBPATH:: Invalid argument
	ninja: build stopped: subcommand failed.

and here is my meson.build file:

	project('recursive_readdir', 'cpp')
	add_global_arguments('-std=c++11', language:'cpp')
	boost = dependency('boost', modules : ['system', 'filesystem'],required : true)
	if boost.found()
		exe = executable('recursive_readdir', 'recursive_readdir.cpp', dependencies: [boost])
	endif

Any help will be much appreciated.

**Comment by jpakkane** [comment]
The issue you are having here is that Boost is a very unique snowflake. Every binary distribution of Boost does things very differently and thus won't work unless someone writes special purpose detection logic for said distribution. Nuwen is 64 bit only whereas the only Windows I have is a 32 bit XP in a virtual machine. The actual fix is not that difficult, mostly just some special checks in `dependencies.py` but I don't have the environment to add the checks. If someone fixes that then patches are gladly accepted.

(The "correct" solution would be to put Boost in wrapdb so it can be used in any environment but that is a massive undertaking and not really feasible in the short term.)

**Comment by jpakkane** [comment]
Also, don't do this:

    add_global_arguments('-std=c++11', language:'cpp')

That is added automatically for you via compiler options.

**Comment by jpakkane** [comment]
And even further, you don't need `required : true`, it's the default. And you also don't need `if boost.found()` because `dependency` immediately aborts execution if a required dep is not found.

**Comment by chenshuiluke** [comment]
@jpakkane Thanks, so I can't do anything about it until a patch is submitted? If so, I think I'd like to try and do it. Do you have any suggestions for doing that aside from what you mentioned?

**Comment by jpakkane** [comment]
If you just want to make it work for this particular case, then you can set the compiler arguments manually. Something along the lines of this:

    executable(...
      cpp_args : ['-I/path/to/headers'],
      link_args : ['/path/to/boost_something.lib', '/path/to/boost_other.lib']
    )

That is extremely ugly, but works.

For fixing the issue itself, there's not much to it. `dependencies.py` has a `BoostDependency` class that has a few methods that detect the locations and return corresponding compiler and link arguments. Just be careful not to break existing working cases. :)

If you submit a patch, remember to add your name at the end of authors.txt.

**Comment by chenshuiluke** [comment]
Alright, I think I'll opt to just do it the ugly way for now. The only problem I really have is that this program is crossplatform, so would it be possible to have something like:

    if os == windows:
     executable(...
       cpp_args : ['-I/path/to/headers'],
       link_args : ['/path/to/boost_something.lib', '/path/to/boost_other.lib'],
       ...
       )
   
    else:
       #what i've already got

**Comment by jpakkane** [comment]
if host_machine.system() == 'windows'
      boost_dep = []
      args = ['yourtghing']
      link_args = ['otherthings']
    else
      boost_dep = dependency(...)
      args = []
      link_args = []
    endif

    executable(...,
      c_args : args,
      link_args : linkargs,
      dependencies : boost_dep)

**Comment by chenshuiluke** [comment]
Thanks for all your help good sir :)

**Comment by jpakkane** [comment]
The actual issue in this bug has been fixed. The detection might still not be perfect but it should be better so closing.
