### ISSUE TITLE
Add a name() method to dependency_object

### ISSUE THREAD

**Issue by nielsdg** [mesonbuild/meson#3351]
For several times, I've needed to refer to a dependency's name for external tools. This requires defining your dependencies in multiple times. It would be handy if we could just use the list of dependencies that you already use for you library, and reuse it with a `foreach` to build a list of names out of that.

For example: valadoc requires you to specify the dependencies of your library as `--pkg <dependency_name>` options. [code example](https://gitlab.gnome.org/GNOME/gnome-contacts/blob/master/docs/meson.build#L9-20)

Other use cases are not hard to think of: for example, one might want to print a list of dependencies in the documentation. Some tools other than valadoc might also need this.

**Comment by obilaniu** [comment]
A `.name()` method seems to have been added in 0.48.0, but it appears to have been accidentally left undocumented.

@nirbheek Could you please quickly add to the [documentation](https://mesonbuild.com/Reference-manual.html#dependency-object) that `name()` now exists, and close this bug?
