### ISSUE TITLE
Cross-Compiling gtk 3: looks on build machine for dependencies

### ISSUE THREAD

**Issue by MartinEmrich** [mesonbuild/meson#3359]
Hi!

I'm new to meson, as I am just trying to cross-compile GTK+ 3.

My cross-compile.txt:

```ini
[binaries]
c = 'arm-unknown-linux-gnueabihf-gcc'
cpp = 'arm-unknown-linux-gnueabihf-g++'
ar = 'arm-unknown-linux-gnueabihf-ar'
strip = 'arm-unknown-linux-gnueabihf-strip'
pkgconfig = 'arm-unknown-linux-gnueabihf-pkg-config'
mount = 'mount'
exe_wrapper = 'runinqemu' # A command used to run generated executables.

[properties]
c_args = [ '-mtune=cortex-a53', '-march=armv7-a', '-mfloat-abi=hard', '-mlittle-endian', '-mfpu=neon', '-pipe', '-O2' ]
cpp_args = [ '-mtune=cortex-a53', '-march=armv7-a', '-mfloat-abi=hard', '-mlittle-endian', '-mfpu=neon', '-pipe', '-O2' ]
root = '/home/martin/temp/cross-raspi/target'

[host_machine]
system = 'linux'
cpu_family = 'arm'
cpu = 'cortex-a53'
endian = ''
```

My problem is that running meson, it looks for dependencies on my build machine, and not on my under my target root directory (/home/martin/temp/cross-raspi/target).

What am I missing?

Thanks,

Martin

**Comment by TingPing** [comment]
Maybe try setting `pkgconfig` to an absolute path? It has worked for me in the past just fine.

**Comment by jpakkane** [comment]
Having pkg-config return the incorrect dependency paths is the most probable reason.

Also, don't add `-O2' or `-pipe` manually. The latter is added automatically by Meson and the former comes from the build type.

**Comment by MartinEmrich** [comment]
I built a "cross-"pkg-config with the correct prefix built-in, that seems to have solved the issue. 
All the autotools-based packages went fine with fixed paths in .pc files, but having a target-pkg-config seems to be the clean thing to do, anyways.

Thanks,
Martin

**Comment by r3d9u11** [comment]
@MartinEmrich Hi. Did you have a success with a cross-compilation of Gtk3 ? I'm looking for any information for this theme, but, unfortunately, haven't a successful way to build it for 'ARM'.

**Comment by MartinEmrich** [comment]
Sorry, a short time later I put that project on hold, as other things did not work out... I honestly do not remember for sure.

IIRC it did build, but I did not reach the stage where I could actually try it out.

**Comment by r3d9u11** [comment]
@MartinEmrich thanks for answer. today I did a cross-compilation successfully (but with older release 3.20.10, which doesn't use meson system)

**Comment by MartinEmrich** [comment]
@r3d9u11 took a look my scripts, I, too, went for 3.22 instead of the meson-based later versions ;)
