### ISSUE TITLE
googlemock repackaging

### ISSUE THREAD

**Issue by sittim** [mesonbuild/meson#336]
Looking at https://github.com/mesonbuild/meson/blob/7bb28ef3c87f4f19daf83f4f564d9e3338eff10a/test%20cases/frameworks/3%20gmock/gmocktest.cc, I should be able to build the file using the sample build, but I get the following:

```
The Meson build system
Version: 0.28.0-research
Source dir: /home/sporty/ws-ccs/hw_1_5
Build dir: /home/sporty/ws-ccs/hw_1_5/build
Build type: native build
Build machine cpu family: x86_64
Build machine cpu: x86_64
Project name: gmock test
Native cpp compiler: c++ (gcc 4.9.2-10ubuntu13)
Dependency GTest found: NO

Meson encountered an error in file meson.build, line 6, column 0:
Dependency "gtest" not found
```

Looking at the dependency.py file, it looks like the build system is looking for the files in very specific directories, would it be possible to add tutorial to wiki on how to configure googlemock as a valid dependency?

**Comment by jpakkane** [comment]
What version of Ubuntu are you running? Do you have libgtest-dev package installed? If yes, where has it put the gtest files?

**Comment by sittim** [comment]
Thanks, that answers my question, so on Ubuntu before using meson, the following is required:

```
sudo apt-get install google-mock
```

I poked around wiki to see if I can find a good place to add this piece if information, but I did not find one.
