### ISSUE TITLE
dependency for testlib or Qt5Test.dll on windows 

### ISSUE THREAD

**Issue by 42sol-eu** [mesonbuild/meson#3362]
The Qt5 `testlib` module cause an 

meson.build:... ERROR: Qt5 native dependency not found (checked pkgconfig, qmake-qt5 and qmake)

see https://doc.qt.io/qt-5.10/qttest-index.html

**MAYBE:** the name testlib in qmake differs from the qt.dll (Qt5Test.dll)

details in meson.build:
```
qt5_mod = import('qt5')
qt5 = dependency('qt5', modules : ['core','network','websockets','widgets','testlib'])
# The dependency function tells Meson to find the library (by default using pkg-config). 
# If the library is not found, Meson will raise an error and stop processing the build definition.
```

**Comment by jeandet** [comment]
Hi @42sol-eu, 

can you try with:
```qt5 = dependency('qt5', modules : ['core','network','websockets','widgets','Test'])```

The culprit here is that qmake doesn't cares about library name, it looks for a pri or prf file in its mkspecs directory. The module name for QtTest is 'Test', CMake also uses 'Test'.
I don't know why they choose testlib for QtTest module as config name in qmake.
