### ISSUE TITLE
mingw + subproject problems

### ISSUE THREAD

**Issue by lazka** [mesonbuild/meson#3370]
I'm trying to build gtk4 in msys2 and it currently tries to pull in pango as a subproject but fails at the linker stage:

```
FAILED: gtk/libgtk-4-0.9300.0.dll 
cc @gtk/libgtk-4-0.9300.0.dll.rsp
C:/msys64/MINGW32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../i686-w64-mingw32/bin/ld.exe: warning: subprojects/pango/pango/libpango-1.0.dll.a(d000212.o): local symbol `ext' has no section
C:/msys64/MINGW32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../i686-w64-mingw32/bin/ld.exe: warning: subprojects/pango/pango/libpango-1.0.dll.a(d000212.o): local symbol `0`.idata' has no section
C:/msys64/MINGW32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../i686-w64-mingw32/bin/ld.exe: warning: subprojects/pango/pango/libpango-1.0.dll.a(d000212.o): local symbol `' has no section
collect2.exe: error: ld returned 1 exit status
```

Full logs: https://gitlab.gnome.org/creiter/gtk/-/jobs/21892

The gtk build succeeds when a new enough pango is installed globally. To rule out autotools meson differences I've ported the msys2 pango package to meson and this also works (https://github.com/Alexpux/MINGW-packages/pull/3570).

Any ideas what this could be or how to debug?

**Comment by lazka** [comment]
I assume this isn't obvious and I haven't debugged this further, so there is no point in keeping this open.

**Comment by lazka** [comment]
I can no longer reproduce this with gtk/pango master :)

**Comment by lazka** [comment]
It's back again, both with pango and glib

**Comment by AvtechScientific** [comment]
And it also might [affect Gnome Text Editor](https://gitlab.gnome.org/GNOME/gtk/-/issues/5053)

**Comment by AvtechScientific** [comment]
So, please, re-open...

**Comment by AvtechScientific** [comment]
Looks like the problem was with binutils:

https://sourceware.org/bugzilla/show_bug.cgi?id=29389

**Comment by AvtechScientific** [comment]
It was fixed by binutils guys, so this issue can closed. Thank you!
