### ISSUE TITLE
Use of cmake as fallback to pkg-config

### ISSUE THREAD

**Issue by jeandet** [mesonbuild/meson#3377]
There are many projects which only provides CMake modules without pc files.
Instead of trying to port all of them to Meson and wait for PRs to get merged when they get. We can as a workaround use CMake like pkg-config with ```--find-package``` as documented [here](https://cmake.org/cmake/help/v3.11/manual/cmake.1.html?highlight=find%20package#find-package-tool-mode).
[Here](https://cmake.org/pipermail/cmake/2018-April/067318.html) is an answer about the deprecation note in the documentation.
[Here](https://stackoverflow.com/questions/28863366/command-line-equivalent-of-cmakes-find-package) are some examples how to invoke it.

In meson we could add this method as fallback when we fail to find a dependency with pkg-config.
```dependency('qt5', modules: 'Core')``` would find it with pkg-config on linux by default and might fallback to cmake or qmake on others platforms.
```dependency('qt5', modules: 'Core', method:'cmake')``` would directly try to find Qt5Core with CMake.

Some open points:
- check that there is no pitfall with cross compilation
- what should we do with -DLANGUAGE= ?

**Comment by barcharcraz** [comment]
There may be additional issues with generator expressions

**Comment by jeandet** [comment]
This PR [here](https://gitlab.kitware.com/cmake/cmake/merge_requests/2017) has been made on CMake to get dependency version.
This mode isn't ready yet for Meson usage, an alternative would be to write a similar CMakeLists.txt to find and extract all dependencies information. Meson could invoke CMake in a dedicated tmp folder.

**Comment by dcbaker** [comment]
This is done, and has been for some time. Closing.
