### ISSUE TITLE
gnome.gtkdoc() doesn't pass correct dependency paths for gtkdoc-scangobj

### ISSUE THREAD

**Issue by bilboed** [mesonbuild/meson#3379]
(This is my understanding of the issue, but I'm not 100% familiar with meson internals so correct at will)

Tested using meson git as of now : e103675a3995f799d65a90595c62ad7f0ed4a088

When passing dependencies to gnome.gtkdoc(), it seems as though it assumes that everything is being run from the top-level build directory.

Ex: in gstreamer we have the documentation in `/docs/gst/` and the code (header, libraries) is in `/`

the documentation `meson.build` contains:
```
types = configure_file(input : 'gstreamer.types.in',
  output : 'gstreamer.types',
  configuration : configuration_data())

gnome.gtkdoc('gstreamer',
  main_sgml : 'gstreamer-docs.sgml',
  src_dir : '@0@/../../gst'.format(meson.current_source_dir()),
  scan_args : ['--deprecated-guards=GST_DISABLE_DEPRECATED',
            '--ignore-decorators=GST_API',
            '--ignore-headers=gettext.h glib-compat-private.h glib-compat.h gst-i18n-app.h gst-i18n-lib.h gst_private.h gstelementdetails.h gstmacros.h grammar.tab.h grammar.tab.pre.h math-compat.h types.h'
            ],
  scanobjs_args : ['--type-init-func="gst_init(NULL,NULL)"'],
  gobject_typesfile : types,
  dependencies : [gst_dep],
  content_files: ['building.xml', 'running.xml', version_entities],
  install : true)
```
After we run `meson build`, `cd build`, `ninja`, when running `ninja gstreamer-doc` we end up with:

> 
> [0/1] Running external command gstreamer-doc.
> Building documentation for gstreamer
> ERROR: 
> Error in gtkdoc helper script:
> 
> ERROR: 'gtkdoc-scangobj' failed with status 1
> gstreamer-scan.c:7:10: fatal error: gst/gst.h: No such file or directory
>  #include <gst/gst.h>
>           ^~~~~~~~~~~
> compilation terminated.
> WARNING:root:Compiling scanner failed: 1, command: gcc -I./. -I../. -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -pthread -c -o gstreamer-scan.o gstreamer-scan.c
> 
> FAILED: meson-gstreamer-doc 
> /usr/bin/python3 /home/bilboed/work/devel/meson/meson.py --internal commandrunner /home/bilboed/work/devel/1.0/gstreamer /home/bilboed/work/devel/1.0/gstreamer/build docs/gst /usr/bin/python3 /home/bilboed/work/devel/meson/meson.py /usr/bin/python3 /home/bilboed/work/devel/meson/meson.py --internal gtkdoc --sourcedir=/home/bilboed/work/devel/1.0/gstreamer --builddir=/home/bilboed/work/devel/1.0/gstreamer/build --subdir=docs/gst --headerdirs=/home/bilboed/work/devel/1.0/gstreamer/docs/gst/../../gst --mainfile=gstreamer-docs.sgml --modulename=gstreamer --mode=auto '--scanargs=--deprecated-guards=GST_DISABLE_DEPRECATED@@--ignore-decorators=GST_API@@--ignore-headers=gettext.h glib-compat-private.h glib-compat.h gst-i18n-app.h gst-i18n-lib.h gst_private.h gstelementdetails.h gstmacros.h grammar.tab.h grammar.tab.pre.h math-compat.h types.h' '--scanobjsargs=--type-init-func="gst_init(NULL,NULL)"' --gobjects-types-file=/home/bilboed/work/devel/1.0/gstreamer/build/docs/gst/gstreamer.types --content-files=/home/bilboed/work/devel/1.0/gstreamer/docs/gst/building.xml@@/home/bilboed/work/devel/1.0/gstreamer/docs/gst/running.xml@@/home/bilboed/work/devel/1.0/gstreamer/build/docs/version.entities '--cflags=-I./. -I../. -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -pthread' '--ldflags=-L/home/bilboed/work/devel/1.0/gstreamer/build/gst -Wl,-rpath,/home/bilboed/work/devel/1.0/gstreamer/build/gst -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0 -lgmodule-2.0 -pthread -lm -ldl -lunwind -ldw -lelf' '--cc=ccache cc' '--ld=ccache cc'
> ninja: build stopped: subcommand failed.

Note that the include arguments provided to gtkdoc-scangobj *are* correct ... from the build directory perspective (i.e. it includes both the source directory and build directory). But this assumes that everything will be executed from that directory, which isn't the case. The various gtkdoc commands will be executed from the build directory (i.e. `/build/docs/gst`).

Some part of the code (not sure if it's `gtkdochelper` or `gnome.gtkdoc()`) should convert those directories accordingly.

**Comment by xclaesse** [comment]
I believe this is regression in 0.40.0 introduced by 976c9abcd0348ffb29863ac2688c661eda524a47.
