### ISSUE TITLE
transitive extract_all_objects no longer works

### ISSUE THREAD

**Issue by bruce-richardson** [mesonbuild/meson#3401]
There is new error added by commit 809f01833336be63eb07441e120de2e4f8c4b3c4: "extract_all_objects: Also extract generated sources". 

 ERROR:  Cannot extract objects from a target that itself has extracted objects

There are many cases where this might be needed, and it seemed to work fine in previous versions of meson. This is breaking the build of the DPDK project where we are compiling for older x86_64 targets without AVX2 instruction set support. In that case, we compile the AVX2 code separately as a static lib, extact it and then merge with the rest of the code into the official library static lib. That lib in turn is converted to a shared lib again by extract_all_objects(). [Yes, I have a TODO to look at SIMD module and "both_library" support for this, but it is what it is now.]

Please fix before next release. This used to work and is a regression IMHO.

**Comment by nirbheek** [comment]
@xclaesse

**Comment by xclaesse** [comment]
It never worked, it was silently not including those objects.

**Comment by nirbheek** [comment]
Then we should convert that error into a warning.

**Comment by xclaesse** [comment]
We should fix it instead. Shouldn't be hard ;-)

**Comment by nirbheek** [comment]
I'm assuming you're volunteering for that 😉
