### ISSUE TITLE
Download all wraps without configuring the project

### ISSUE THREAD

**Issue by sarum9in** [mesonbuild/meson#3419]
This can be useful if you want to prepare project to be compiled in hermetic environment.

**Comment by becm** [comment]
If a all `wrap` operations are performed before build directory creation this could make it possible to ban source directory changes from `meson setup` executions.

@jpakkane this would make a *improved* `meson setup` subcommand cleaner not only for [command line argument considerations](https://github.com/mesonbuild/meson/issues/2857#issuecomment-373531223) but in regards to the operation itself.

The operation split would also help in shared read only source directory environments.
The admin can prepare a consistent source tree (matching dependencies) and users can create build directories with special options without need to duplicate the source tree.

**Comment by eli-schwartz** [comment]
This was implemented in #4389
