### ISSUE TITLE
Feature request: array of all project build options

### ISSUE THREAD

**Issue by justyn** [mesonbuild/meson#3422]
I'm trying to create some configuration data automatically from project build options that have a certain prefix.

It seems like most of the functionality is there, however it doesn't seem to be possible to inspect what build options are defined for a build from within meson.build without specifying them all by name manually, or perhaps using an external script to parse meson_options.txt.

**Comment by astavale** [comment]
Is `meson introspect builddir/ --buildoptions` of any use? If it is then read [IDE integration](http://mesonbuild.com/IDE-integration.html)

**Comment by justyn** [comment]
Thanks for the tip, however perhaps I should have been more clear that I am looking for a solution as part of the meson.build script (I've edited the question slightly).

For example, something like this:

```
foreach opt : get_build_options()
  # do something
endforeach
```

**Comment by justyn** [comment]
I have been able to reconfigure my build setup to use a single [option of array type](https://mesonbuild.com/Build-options.html#arrays) in place of multiple build options.

This replaces the need to populate an array with all user options. In the absence of a need for this feature myself, I'm closing the issue.
