### ISSUE TITLE
regression with string escaping/formatting and cc.run()

### ISSUE THREAD

**Issue by tp-m** [mesonbuild/meson#3429]
#3169 seems to have caused a regression with the GLib meson build, which does the following thing (simplified):
```
  templ = '''
#include<stdio.h>
int main(int argc, char **argv) {
  printf("%d\n", (int)@0@);
  return 0;
}'''
value_FOO = cc.run(templ.format('FOO'), name : 'FOO value').stdout().strip()
```

Let's ignore for now that this is not cross-compile friendly and should be using `cc.compute_int()` or such instead.

Since the above commit 36aab0f4b2a05a1ae4c8603e57b4c3c684fe8ea8 this now fails with `Checking if "POLLIN value" runs: DID NOT COMPILE`

The reason this fails to compile is because the code to be compiled is now (excerpt from log file):

```
Code:
#include<stdio.h>
int main(int argc, char **argv) {
  printf("%d
", (int)FOO);
  return 0;
}
Compiler stdout:
 
Compiler stderr:
 /tmp/tmpguawnoj0/testfile.c: In function ‘main’:
/tmp/tmpguawnoj0/testfile.c:5:10: warning: missing terminating " character
   printf("%d
```

As you can see, the `\n` in the multi-line string has been turned into an actual newline here. Before the commit, the code would have a backslash and an `n` character there instead.

**Comment by jpakkane** [comment]
Would it be enough to only not expand \n in triple quoted strings or do we need to revert fully and come up with something else?

**Comment by xclaesse** [comment]
To be fully backward compatible I guess we should introduce a new type of string that does escaping. Maybe use "some\nstring" or escape_string('some\nstring').

**Comment by jpakkane** [comment]
No double quotes. And the latter does not work because the escaping is already done by the time the method is called and you can't reliably undo it because some linefeeds might come from actual newlines.

**Comment by xclaesse** [comment]
otoh, the doc previously said:
> Similarly `\n` gets converted to a newline
So one could argue that glib's code should never have worked.

**Comment by xclaesse** [comment]
@jpakkane or just like python has `b'binary string'` we could have `e'escaped string'`

**Comment by jpakkane** [comment]
The real question is how many projects would break with this change? If it's only one or two we can break it but not if it affects many or popular projects.

Maybe we could detect strings with those newline settings, print a warning for a release or two and then change it to the current behaviour or something like that?

**Comment by xclaesse** [comment]
> And the latter does not work because the escaping is already done by the time the method is called

Actually not, \n was not replaced by newline otherwise glib code would never have worked. So we could add in function that does additional replacements.

**Comment by NickeZ** [comment]
This is a well documented breakage. If we don't want to introduce any breakage at all we simply can't change the escaping rules.. I think we are early enough in mesons development that we should be able to fix this kind of "soundness" issues. IMO it is broken behavior that `\n` does not convert to a newline.

But if it is your opinion to introduce a new  string type I'm open for that as well. I could also output a warning for every single escape sequence.

**Comment by NickeZ** [comment]
How about introducing raw strings like `r'nothing is escaped here'`?

**Comment by tp-m** [comment]
That doesn't fix the backwards compatibility issue though, does it?

It's also unclear to me why anyone would ever want to see a literal `\n` in a multi-line string constant be turned into an actual newline. If they wanted a newline they'd just put an actual newline there, it's a multi-line string constant after all.

**Comment by NickeZ** [comment]
For consistency, but we can remove all escape sequences in triplequoted strings to keep some backwards compatibility.

**Comment by nirbheek** [comment]
We do need something like Python's raw strings. However, in the absence of `r''` and other notations, I like the idea of having `'''` mean no escaping is done.

**Comment by NickeZ** [comment]
You like it until you want to put in a \t or a unicode character. But sure then we can have `e''''''` to be escaped version of triple-qouted string.
