### ISSUE TITLE
ninja install doesn't always work

### ISSUE THREAD

**Issue by rhd** [mesonbuild/meson#343]
Hi Jussi,

These sequence of commands cause ninja/meson to not install the apps correctly.

```
ninja install
touch ./some/file.cpp
ninja
ninja install
```

The last `ninja install` doesn't actually install anything.

**Comment by rhd** [comment]
I also tested by actually modifying the code in `./some/file.cpp` just to make sure I wasn't getting outsmarted... but `ninja install` still didn't install as I would expect it to.

**Comment by jpakkane** [comment]
Ninja install will always copy over all the files in your install set (and run the equivalent of 'ninja all' before it. As an example here is a log for two consecutive invocations:

    ninja install
    [1/1] Installing files.
    Installing libshar.dylib to /tmp/foo/lib/libshar.dylib
    Installing libstat.a to /tmp/foo/lib/libstat.a
    Installing prog to /tmp/foo/bin/prog
    
    ninja install
    [1/1] Installing files.
    Installing libshar.dylib to /tmp/foo/lib/libshar.dylib
    Installing libstat.a to /tmp/foo/lib/libstat.a
    Installing prog to /tmp/foo/bin/prog

If I touch a source file and run `ninja install` it will rebuild and install the target as expected.

Please verify that your data is actually properly set up. If you can't find any issues, run `ninja install` twice in a row and paste the log.

**Comment by rhd** [comment]
The only thing I can think of is I have my install directory inside of my build directory.

```
default_options: ['prefix=@0@/install/'.format(meson.current_build_dir())],
```

`ninja install` definitely doesn't run unless something changes on my code base. I looked at the log and nothing good is in there.
