### ISSUE TITLE
subprojects are not extracted if directory exists (even if packagecache is nuked)

### ISSUE THREAD

**Issue by glslang** [mesonbuild/meson#3438]
Hi,

Consider the following tree

.
├── main.c
├── meson.build
└── subprojects
    ├── libpng-1.6.34
    │   └── stub.txt
    └── libpng.wrap

If I run meson on this structure it'll always fail since libpng-1.6.34 exists. If a patch_url is updated in the wrap file then it'll never be applied even if packagecache is deleted.
The only way to make it work is to delete the libpng-1.6.34 directory.

Raising the issue since I don't know if this is intended behaviour. I wrote a small patch with a test that demonstrates the issue and some code to circumvent it.
It can be found here,

https://github.com/glslang/meson/commit/7d5fa80acecadf3ff09ca6b537a5b5bbc2b68104

**Comment by eli-schwartz** [comment]
This was implemented in #4389

```
meson subprojects update --reset libpng
```
