### ISSUE TITLE
Visual studio default build project

### ISSUE THREAD

**Issue by NickeZ** [mesonbuild/meson#3448]
The first declared project in the visual studio solutions file is the "start-up" project, i.e. the default project. Should we have a `BUILD_ALL` project as the default project like cmake has?

**Comment by NickeZ** [comment]
Since `msbuild` builds all projects by default and VS has a `Build solution (F7)` which also does that I don't really see a reason to add a `BUILD_ALL` project.

However, it would still be nice to have a main entrypoint project. VS calls it "StartUp Project". You can right click any project and "Set as StartUp Project". This is then the executable that will be run by default with "Start Debugging (F5)". My goal with this issue is that I can do `meson build` and then `F5` immediately in VS and compile/run the correct program every time.

Being able to define a main entrypoint would also allow us to implement something like `meson run` that would run the entrypoint executable.

What would be the preferred way to define such an entrypoint?

```
my_exe = executable(..., project_entrypoint: true)
```

or

```
my_exe = executable(...)
project_entrypoint(my_exe)
```

**Comment by jpakkane** [comment]
It seems more reasonable to have this as a visual studio backend option. That way it can be changed without needing to edit build definition files.

**Comment by NickeZ** [comment]
So something like:

```
project('my_proj', 'cpp', default_options: ['vs_startup_project=my_exe'])
```

**Comment by jpakkane** [comment]
Something like that yes.
