### ISSUE TITLE
MXE version of meson/ninja

### ISSUE THREAD

**Issue by highperformancecoder** [mesonbuild/meson#3449]
MXE (http://mxe.cc) is a Linux=>Windows cross-compiler environment that I particularly use to deliver software to the Win32 platform. I am considering reworking my code to use the meson build system, but for that to be a starter, I will need a MXE port of meson and ninja. Currently, MXE does provide a customised version of cmake, for example, that generates all the compiler options appropriate for the MXE environment,

**Comment by SolarAquarion** [comment]
@highperformancecoder https://github.com/mxe/mxe/tree/master/plugins/meson-wrapper

**Comment by highperformancecoder** [comment]
I missed that. I forgot to check the plugins directory.

**Comment by eli-schwartz** [comment]
I guess there is nothing we need to do for this, then?
