### ISSUE TITLE
Feature Request: include_directories() support -isystem

### ISSUE THREAD

**Issue by rhd** [mesonbuild/meson#345]
Hi Jussi,

It would be really great if include_directories took a named argument so that instead of doing `-I/path/to/incdir` it would do `-isystem /path/to/incdir`

Thoughts?

Update: rationale: http://stackoverflow.com/questions/1867065/how-to-suppress-gcc-warnings-from-library-headers boost is so noisy with clang.

**Comment by ignatenkobrain** [comment]
Makes sense...

**Comment by jpakkane** [comment]
I'd rather do this automatically so people don't have to care. Something like "for all subprojects use `-isystem`, for current ones use `-I'.

**Comment by rhd** [comment]
Hi guys - using -isystem for subprojects only won't work for me :( Our version of boost was "installed" via scp from one dev box to another :/

**Comment by rhd** [comment]
or how about adding `include_system_directories()` ?
