### ISSUE TITLE
meson output test on failure?

### ISSUE THREAD

**Issue by asartori86** [mesonbuild/meson#3462]
Hi,

is it possible to ask to  `meson test` to report the stdout and/or stderr in case a test fails? This is useful for example on travis and the like.

If it is not possible, and you would like to have this feature, I could work on a patch

**Comment by asartori86** [comment]
thanks @astavale, but digging among hundreds of tests for the output of one failing test is not that helpful. Moreover, since many tests are run in parallel, trying to see the output of one specific test is harder

**Comment by asartori86** [comment]
of course I use `meson test testname -v` to debug it locally

**Comment by jpakkane** [comment]
The output is also written to a JSON file which can be shown in Jenkins. [Here is an example from GStreamer](https://ci.gstreamer.net/job/GStreamer-master-meson/lastSuccessfulBuild/testReport/).

**Comment by jpakkane** [comment]
> Is this a JSON 'standard' for test results?

No, just something I came up on my own. The reason for that is that the format needs to be streamable (as in, an IDE can show results in real time) and XML does not do that.

> A pointer to the plugin would be great.

I actually don't know the details of that system is set up. @nirbheek?

**Comment by monouser7dig** [comment]
> but digging among hundreds of tests for the output of one failing test is not that helpful. Moreover, since many tests are run in parallel, trying to see the output of one specific test is harder

I agree, seing the output of failed tests would be useful.

thanks

**Comment by asartori86** [comment]
`meson test --print-errorlogs` does the job. Thanks

**Comment by sdroege** [comment]
> > A pointer to the plugin would be great.
> 
> I actually don't know the details of that system is set up. @nirbheek?

From what I understand we run `meson test` via gst-validate, and let gst-validate write a junit XML file (it runs each test individually, collects the success/failure, etc). Having this feature in meson would be quite useful to prevent this workaround.

While the XML is not streamable, this does not change the junit XML is the de-facto standard for machine-readable test results.

**Comment by nirbheek** [comment]
fwiw, `junit.xml` is a standard format for slurping test results that is readable or required by almost all CI software out there. Doesn't hurt to always output test results in that format into a well-known place like the `meson-private` directory.
