### ISSUE TITLE
Massive regression in performance of the ninja backend

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#3465]
I noticed that despite the perf improvements in the interpreter run time that were achieved for 0.46, the configure time for gtk+ actually went up by a few seconds. So I added some profiling and found this:

`intr.run()` time went from [25.2s](https://github.com/mesonbuild/meson/files/1943956/intr-0.45.1.log) to [13.8s](https://github.com/mesonbuild/meson/files/1943958/intr-0.47.0.dev1.log)
`g.generate()` time went from [4.2s](https://github.com/mesonbuild/meson/files/1943959/generate-0.45.1.log) to [*20.6s*](https://github.com/mesonbuild/meson/files/1943960/generate-0.47.0.dev1.log)

The above links are all profile stat dumps which can be parsed with the [pstats module](https://docs.python.org/3/library/profile.html#module-pstats). I haven't looked into the profiles properly yet.

**Comment by nirbheek** [comment]
Looks like this was because of #3094:

>       536    0.225    0.000   16.008    0.030 mesonbuild/backend/ninjabackend.py:2425(guess_external_link_dependencies)
> 116446    1.412    0.000    7.769    0.000 mesonbuild/backend/ninjabackend.py:2417(guess_library_absolute_path)

16 seconds out of 20.6 seconds is spent in that function, with 7 seconds spent just finding the absolute path for all libraries. Probably because we're re-computing the same stuff over and over.

CCing @textshell.

**Comment by textshell** [comment]
I will not be able to look into this until later this week.
But that sounds like either an insane amount of library directories or an insane amount of duplication of libraries?
If it is the later i wonder if #3414 would make a difference by reducing duplicated libraries (by generating abs paths earlier and thus allowing recently added dedup code that only works with abs paths to remove duplicates)?
