### ISSUE TITLE
Cannot use private Qt headers without hacks

### ISSUE THREAD

**Issue by SirCmpwn** [mesonbuild/meson#3471]
https://github.com/SirCmpwn/qtlayershell/blob/6315d292a72690391d207894f066a10becd1c8e6/qtlayershell/meson.build#L1-L10

**Comment by jeandet** [comment]
@SirCmpwn , sadly this is a known issue, we might be able to fix this when using qmake as method to find Qt dependency, if we can make assumptions on path.
For pkg-config method, we need to make an upstream PR to solve this, in current version pc files don't contain private header path such as cmake generated files in some cases.

**Comment by nirbheek** [comment]
The fix for this seems to have been wrong, see https://github.com/mesonbuild/meson/pull/3491#issuecomment-393543504 and later comments.

**Comment by jeandet** [comment]
@nirbheek, I can't reproduce the bug with master branch of Meson.
