### ISSUE TITLE
[wiki] Minor style issue in 'Run targets' page

### ISSUE THREAD

**Issue by amitdo** [mesonbuild/meson#349]
https://github.com/mesonbuild/meson/wiki/Run%20targets

>To make this a run target we write it to a script file called `scripts/inspect.sh and specify it in the top level Meson file like this.`

It should be:

>To make this a run target we write it to a script file called `scripts/inspect.sh` and specify it in the top level Meson file like this.

**Comment by jpakkane** [comment]
Fixed, thanks.
