### ISSUE TITLE
Support for Windows message compiler

### ISSUE THREAD

**Issue by wasim42** [mesonbuild/meson#3494]
Hello,

It appears that meson doesn't support ".mc" files as used by the message compiler on Windows.  For example, given the following "my-msgs.mc" and "meson.build" in the same directory on Windows, I get a huge traceback ultimately telling me `AssertionError: Unknown source type: <CustomTargetIndex: <CustomTarget my-msgs@cus: ['mc', '@INPUT@']>[0]>`

Are they really not supported yet, or am I doing something stupid?

```
MessageId = 0x1
Severity = Informational
SymbolicName = MSG_MY_INFO
Language=English
%1
.

MessageId = 0x2
Severity = Warning
SymbolicName = MSG_MY_WARN
Language=English
%1
.

MessageId = 0x3
Severity = Error
SymbolicName = MSG_MY_ERROR
Language=English
%1
.
```

```
project('mc-test', 'c', 'cpp', default_options: ['werror=true'])

msgs = 'my-msgs'

my_msgs = custom_target(msgs,
    input: msgs+'.mc',
    output: [msgs+'.rc', msgs+'.h', 'msg00001.bin'],
    command: ['mc', '@INPUT@'])

msgs_rc = custom_target(msgs+'.rc',
    input: my_msgs[0],
    output: msgs+'res',
    command: ['rc', '@INPUT@'])
```

**Comment by wasim42** [comment]
Excellent. On the “I’m not stupid” front (let’s not mention the time I’d written up a whole bug report, and was about to send when I worked it out).

**Comment by NickeZ** [comment]
This is a bug in meson. Either wait for my patch to land and use latest master of meson. Or perhaps a workaround is:

```
msgs_rc = custom_target(msgs+'.rc',
    input: my_msgs,
    output: msgs+'res',
    command: ['rc', '@INPUT0@'])
```
