### ISSUE TITLE
[wiki] Minor fix to 'Comparisons' page

### ISSUE THREAD

**Issue by amitdo** [mesonbuild/meson#350]
>Needlessly slow, complicated, hard to use correctly, unreliable, painful to debug, ununderstandable for most people, poor support for non-Unix platforms (especially Windows).

I suggest to replace 'ununderstandable' with 'not understandable' or 'unclear'.

http://english.stackexchange.com/questions/4031/what-is-a-good-replacement-for-ununderstandable
https://answers.yahoo.com/question/index?qid=20120207134123AAWb6Rm

**Comment by jpakkane** [comment]
It is "ununderstandable" on purpose due to stylistic choices. There are two main reasons. 1) I think it's a funny word. 2) It perfectly describes the complicatedness Autotools in a single word.

I'm closing this one as a wontfix but thanks for the report.

**Comment by amitdo** [comment]
I **un**derstand you :-)
