### ISSUE TITLE
Support semver (more precisely, non-numeral versions)

### ISSUE THREAD

**Issue by Salamandar** [mesonbuild/meson#3505]
https://semver.org/

The most interesting part here is to be able to name projects '1.0.0-rc.1' (or alpha/beta).

**Comment by tom-corwin** [comment]
This is something that would be nice to see. 🙂

**Comment by eli-schwartz** [comment]
The project version is already a free-form string and can be whatever you want (hopefully actually a version of some sort, but not actually enforced). You are definitely not limited to numerals. :)
