### ISSUE TITLE
Python 3 module outputs different name than distutils

### ISSUE THREAD

**Issue by bruxisma** [mesonbuild/meson#3508]
Currently, when building an extension module with the python3 module, the output name is `<name>.<simplified extension>`. This differs from `distutils`, which uses `distutils.sysconfig.get_config_var('EXT_SUFFIX')`. While the current approach works, there is no way to prevent ABI incompatible versions of python from loading extensions built for another version. Using the `get_config_var` approach is (at least according to various PEPs) resolve this.

However, this changes the current behavior and could cause an issue if the python3 found and used is not the one meson is executing on. 

I also wanted to mention [this](https://github.com/mesonbuild/meson/blob/master/mesonbuild/modules/python3.py#L41) comment, and briefly explain that because of how windows shared library loading searches occur, python extensions use `.pyd` so that potential specific DLL name collisions can't happen (`kernel32.dll` vs `kernel32.pyd`, etc).

**Comment by eli-schwartz** [comment]
The python3 module is deprecated and shall not be used.

The python module (originally released just days before this ticket was submitted) gets this correct.

**Comment by bruxisma** [comment]
I completely forgot about this issue, lmfao. Glad it's been fixed.

**Comment by eli-schwartz** [comment]
I found it in a list of search results for distutils and figured it was a good chance to clean up an old ticket. :D
