### ISSUE TITLE
meson 0.46.0 - bad library in the generated .pc file

### ISSUE THREAD

**Issue by rezso** [mesonbuild/meson#3509]
Another problem with .pc file generation.
If I build libxkbcommon 0.8.0 with meson 0.44, the xkbcommon.pc contains the expected Libs line:
Libs: -L${libdir} -lxkbcommon
But if I build ibxkbcommon 0.8.0 with meson 0.46, the pc file contains a bad Libs line:
Libs: -L${libdir} -lxkbcommon-internal
The libxkbcommon-internal is an static library, the final shared library is the libxkbcommon.so.
(This true for the xkbcommon-x11 lib also.)

Here is the meson.build file:
https://github.com/xkbcommon/libxkbcommon/blob/master/meson.build#L201

I don't tried the build with another meson versions.

**Comment by anordal** [comment]
Meson 0.45.0 seems good:

    Libs: -L${libdir} -lxkbcommon
    Libs.private: -L${libdir} -lxkbcommon-internal

(I cloned that repo and checked out the *xkbcommon-0.8.0* tag.)

**Comment by nirbheek** [comment]
The issue is that we are adding 'private libraries' which are actually `link_whole:`. It should not show up in `Libs.private:` either, so 0.45.0 was also wrong, just less noticeably so.
