### ISSUE TITLE
Add https support to mesonbuild.com

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#3513]
GitHub pages now support HTTPS: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

There's no way to set an HSTS policy yet, but this is a good first step.

**Comment by jpakkane** [comment]
DNS records updated. Closing once there is confirmation that it actually works (currently it does not, probably due to stale DNS data).

**Comment by xclaesse** [comment]
For me https://mesonbuild.com works but not https://www.mesonbuild.com.

**Comment by nirbheek** [comment]
Simplest way to fix that is to set a DNS record for www.mesonbuild.com to a separate server that does a 301 redirect to mesonbuild.com.

**Comment by nirbheek** [comment]
Closing because https://mesonbuild.com works and that's good enough.
