### ISSUE TITLE
custom_target @OUTDIR@ is not a full path

### ISSUE THREAD

**Issue by DavidGamba** [mesonbuild/meson#3515]
meson version 0.4.6

The documentation for [custom_target](http://mesonbuild.com/Reference-manual.html#custom_target) indicates that `@OUTDIR@` is `the full path to the directory where the output(s) must be written`.

This is not true, when run in the root of the project, `@OUTDIR@` is `.` and when run through `subdir('diagrams')` for example, `@OUTDIR@` is `diagrams`. 

The full path is really needed, otherwise the build outputs are sent relative to the source.

**Comment by jpakkane** [comment]
This is perhaps a bit poorly documented but "full path" here means the path to where the output will be written. It may be an absolute path. It might be a relative path. Some backends do one, some do the other. Tools should not care which one it is. They are expected to write their output to whatever path is given to them.

**Comment by DavidGamba** [comment]
It should be the absolute path, otherwise tools will write to the output relative to either the source or the binary. 
Is there a way to define the absolute path?

**Comment by sarum9in** [comment]
I guess the point is that it is relative to current working directory of the process. So `join_paths($PWD, @OUTDIR@)` would produce full path.

**Comment by jpakkane** [comment]
No, because having path separators in target output names is forbidden.

**Comment by DavidGamba** [comment]
@jpakkane thank you for your help on the IRC channel. What worked for me was to use `meson.current_build_dir()` which actually provides the absolute path.
More details in the [meson-object documentation](http://mesonbuild.com/Reference-manual.html#meson-object).

I think the documentation for custom_target should be updated to indicate that `@OUTDIR@` is not a full path but relative, and that if full is needed, use the meson object instead.
