### ISSUE TITLE
Cross definitions files "inherit"

### ISSUE THREAD

**Issue by Salamandar** [mesonbuild/meson#3518]
When writing a new cross-compilation definition but very resemblant to another one, we need to rewrite the whole file.
Could a `based_on` or `inherit` tag be added to the files to minimize the definitions duplication ?
Moreover, could `meson --cross-file` take multiple files ?

**Comment by Akaricchi** [comment]
I have another use case for this: overlaying custom project-specific cross properties on top of a generic 
 cross file (which could be distro-supplied, or even generated, as is the case with MXE's meson plugin).

For a specific example, we have an option to distribute ANGLE with Windows builds of Taisei. Building of ANGLE is currently not integrated into our build system (because Google went out of its way to make cross-compilation virtually impossible). We have to supply paths to pre-built libgles and libegl DLLs that are copied into the installation directory. This is currently implemented via project options, just because editing the generic cross file for this purpose is not desirable.

**Comment by dcbaker** [comment]
It would be very easy to allow cross files to be layered like we do for native files. We didnt' implement this initially because we wanted to see if there was a usecase for it. Shouldn't be that hard to do if someone wants to write the patch, the native files support should make a decent template.

**Comment by dcbaker** [comment]
I think this is going to be basically necessary once my series for paths in cross and native files lands, debian (for example) can provide a bunch of cross files that only set the [paths] sections for various architectures, and end users can layer them together with cross files for gcc and clang (for example).

I think we should do the same thing for cross files that we do for native files.

**Comment by rossburton** [comment]
Another use case:  We have a shared cross file for the compiler but then also need to build e.g. glib, which has some glib-specific properties.  I tried passing --cross-file twice, but that just broke the build.

**Comment by Salamandar** [comment]
Some implementation would be… Parsing the cross-files **as meson full language**, allowing the cross-files to do some smart things.

**Comment by jpakkane** [comment]
> Parsing the cross-files as meson full language, allowing the cross-files to do some smart things.

It was an explicit design goal to _not_ do that. Cross files should be as simple as unsurprising as possible to make them easily auditable.

**Comment by rossburton** [comment]
So I've a *very rough* patch that appears to work to let you pass more than one cross file at https://github.com/rossburton/meson/commit/1757577549ef49be329632dd4070cbf9f2b8bd9c.  It appears to work.

**Comment by dcbaker** [comment]
I'm *not* in favor of letting cross files do smart things, but I am in favor of allowing cross files to be layered like native files. As we keep adding things (and it's on the roadmap for me to keep adding things) it makes sense to be able to layer cross files. We allowed layering native files for exactly the situation that @rossburton described, but with native files.

**Comment by rossburton** [comment]
https://github.com/rossburton/meson/tree/crossfiles has a patch that appears to do the right thing but 3 of the unit tests are failing and I'm just not seeing how my patch is relevant. :(  Just running `run_unittests.py LinuxlikeTests.test_compiler_check_flags_order` works with master but fails with crossfiles.
