### ISSUE TITLE
get_supported_link_arguments() should accept lists

### ISSUE THREAD

**Issue by etrunko** [mesonbuild/meson#3527]
Some link arguments will only work when used together, for instance `-Wl,-z -Wl,relro` and `-Wl,-z -Wl,now`. The call to `get_supported_link_arguments([['-Wl,-z', '-Wl,relro'], ['-Wl,-z', '-Wl,now']])` should take into consideration the type of the argument, instead of flattening the list and checking for each one individually. In this case, the current result is `-Wl,-z` is supported, while '-Wl,relro' and '-Wl,now' are not.

@xclaesse Can you take a look at the provided patch to see if it makes sense?
[get_supported_link_arguments.txt](https://github.com/mesonbuild/meson/files/1975069/get_supported_link_arguments.txt)

**Comment by xclaesse** [comment]
Isn't this the same as doing get_supported_link_arguments(['-Wl,-z,relro', '-Wl,-z,now']) ?

**Comment by etrunko** [comment]
I just tried the patch and it does not work because the list is already flattened by the time the function is called. I will investigate a bit further on how to do it.

**Comment by etrunko** [comment]
Thanks for the help, closing this issue for now. :+1:
