### ISSUE TITLE
How to set cross compiled install prefix?

### ISSUE THREAD

**Issue by luked99** [mesonbuild/meson#3529]
I have a cross-compiled project targetting ARM32. The rule for installation puts everything into this kind of path:

   ```<prefix>/usr/lib/x86_64-linux-gnu/libmylibrary.so```

This is particularly weird considering the the library is ARM32.

I run meson as:
   ``` meson <srcdir> <builddir> -Dprefix=/usr --cross-file=<crossfile.txt> ```

And ninja as:
    ```DESTDIR=<dest> ninja```

How do I remove the **x86_64-linux-gnu** portion of the path?

**Comment by jpakkane** [comment]
By setting the `libdir` option, usually with `-Dlibdir=lib`.

Yes, it's a bit silly that it grabs the "native libdir" in this case but that is the current behavior.

**Comment by luked99** [comment]
That's great, thanks!
