### ISSUE TITLE
AttributeError: 'InstallData' object has no attribute 'install_umask'

### ISSUE THREAD

**Issue by egraff** [mesonbuild/meson#3541]
With the latest version of meson on Windows, built from master (66ec45bb04772dc29c8f2f3aa1a2b43ab51faeed), we sometimes intermittently get the following error:

```
Traceback (most recent call last):
  File "F:\\buildbot\\pexslave_pmx\\build\\external\\meson\\meson.py", line 26, in <module>
    sys.exit(main())
  File "F:\\buildbot\\pexslave_pmx\\build\\external\\meson\\meson.py", line 23, in main
    return mesonmain.run(sys.argv[1:], launcher)
  File "F:\buildbot\pexslave_pmx\build\external\meson\mesonbuild\mesonmain.py", line 320, in run
    sys.exit(run_script_command(args[1:]))
  File "F:\buildbot\pexslave_pmx\build\external\meson\mesonbuild\mesonmain.py", line 269, in run_script_command
    return cmdfunc(cmdargs)
  File "F:\buildbot\pexslave_pmx\build\external\meson\mesonbuild\scripts\meson_install.py", line 415, in run
    do_install(datafilename)
  File "F:\buildbot\pexslave_pmx\build\external\meson\mesonbuild\scripts\meson_install.py", line 230, in do_install
    if d.install_umask is not None:
AttributeError: 'InstallData' object has no attribute 'install_umask'
```

It seems the `InstallData` object that is unpickled from the `install.dat` file is somehow missing the `install_umask` attribute (although I'm not sure how this could have happened, since the attribute is set in the `InstallData` constructor).

This is what I get when manually trying to unpickle `install.dat`:
```
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pickle
>>> with open('install.dat', 'rb') as ifile:
...     d = pickle.load(ifile)
...
>>> d
<mesonbuild.backend.backends.InstallData object at 0x0000029770C1DEF0>
>>> dir(d)
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'build_dir', 'data', 'headers', 'install_scripts', 'install_subdirs', 'man', 'mesonintrospect', 'po', 'po_package_name', 'prefix', 'source_dir', 'strip_bin', 'targets']
```

I've uploaded the relevant `install.dat` file here: https://ufile.io/hr0qs.

**Comment by nirbheek** [comment]
Have you been running meson master and upgraded without deleting your build directory? In that case, meson will not know that the build directory needs to be wiped since the version stays the same.

**Comment by nirbheek** [comment]
I cannot see any reason other than a stale builddir while using master. Downgrading from regression.

Please add more details here when you can so we can decide whether this is a regression that needs to go into the stable release.

**Comment by egraff** [comment]
@nirbheek: yes, you are absolutely right! This was something that was caught by our CI, so I didn't realize that our meson submodule had been updated between two successive incremental builds.

**Comment by tp-m** [comment]
@egraff: This can be closed then, right?

**Comment by egraff** [comment]
@tp-m: absolutely!
