### ISSUE TITLE
builddir not usable if new option is added

### ISSUE THREAD

**Issue by NickeZ** [mesonbuild/meson#3543]
Create a project.

```
mkdir foo
cd foo
echo 'int main(){return 0;}' > main.cpp
meson init
meson build
ninja -C build
```

Update project with an option that breaks "meson setup" on your machine. (The real usecase is that you did `git pull`)

```
echo "option('bar_root', type: 'string', value: 'C:\\\\doesnotexist')" > meson_options.txt
echo "lib = meson.get_compiler('cpp').find_library('bar', dirs: get_option('bar_root'))" >> meson.build
```

ninja will of course fail to build.

```
$ ninja -C build
ninja: Entering directory `build'
[0/1] Regenerating build files.
The Meson build system
Version: 0.47.0.dev1
Source dir: /tmp/foo
Build dir: /tmp/foo/build
Build type: native build
Project name: foo
Native C++ compiler: ccache c++ (gcc 7.3.0 "c++ (Ubuntu 7.3.0-16ubuntu3) 7.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
meson.build:9:0: ERROR:  Search directory C:\doesnotexist is not an absolute path.
A full log can be found at /tmp/foo/build/meson-logs/meson-log.txt
FAILED: build.ninja
/usr/bin/python3 /home/niklas/.local/bin/meson.py --internal regenerate /tmp/foo /tmp/foo/build --backend ninja
ninja: error: rebuilding 'build.ninja': subcommand failed
```

It is not possible to set the correct new value:

```
$ meson configure build/ -Dbar_root=/opt/bar
Meson configurator encountered an error:
ERROR: Unknown option bar_root.
```

This problem would be less annoying if there was a simple way to figure out the original `meson build -D...` command that was run. #3542

**Comment by xclaesse** [comment]
I can confirm this issue, and it still happens with my PR #3528 that rework cmd line options.

The reason is mconf can only set options that are defined in `coredata.dat` file because it won't parse again `meson.build` and `meson_options.txt`. But `coredata.dat` is not created/updated until configure succeed, see the comment above `cdf = env.dump_coredata()` in https://github.com/mesonbuild/meson/blob/master/mesonbuild/mesonmain.py#L189.

**Comment by NickeZ** [comment]
What would be the acceptable fix here? Reading `meson_options.txt` early in `mconf` and update `coredata.dat` with missing variables?

**Comment by NickeZ** [comment]
Shouldn't ninja be able to figure out that `meson_options.txt` has changed and run the appropriate command to "import" the new options?

**Comment by xclaesse** [comment]
The problem here, if I understand correctly, is it does import the new option but its default value doesn't work. And that ninja cannot know. User must provide a new value, but currently user has no way to set that new value without wiping everything. Or did I miss-understood?

**Comment by NickeZ** [comment]
No I think you are right. I'm not 100% sure on the internals of meson here, but as far as I understand it `ninja reconfigure` doesn't update `coredata.dat` because `meson` fails. And `meson conf` doesn't work because `coredata.dat` wasn't updated. Please correct me if I'm wrong. So, I was thinking that, if `ninja reconfigure` does two steps 1. parse `meson_options.txt` and update `coredata.dat` and then 2. try to setup the project. Then a subsequent `meson conf` would work because `coredata.dat` knows about the new variables. Does that make sense?
