### ISSUE TITLE
Linking may fail with CC=clang and -Db_sanitize=address,undefined 

### ISSUE THREAD

**Issue by kdex** [mesonbuild/meson#3544]
When building [this project](https://github.com/kdex/hell), I noticed that building via

```bash
CC=clang meson --buildtype=release -Db_sanitize=address,undefined .. && ninja
```

makes the linker fail due to undefined references that stem from the Google/LLVM sanitizers.

Interestingly, building with `CC=gcc` works just fine:

```bash
CC=gcc meson --buildtype=release -Db_sanitize=address,undefined .. && ninja
```

Is this a bug or did I mess up my build configuration?

--------------
executable | version
--- | ---
clang | 6.0.0
gcc | 7.3.1
meson | 0.46.0
ninja | 1.8.2

**Comment by kdex** [comment]
Thanks! For future readers, using `clang++` instead of `clang` flagged with `-fsanitize=address,undefined` appears to work on some example files I've tried. Do you happen to know if this has been fixed upstream, @jpakkane?

I'll close this issue, since this isn't meson's fault.

**Comment by jpakkane** [comment]
There is an upstream bug that I filed but I haven't gotten any emails about for a while so I'm assuming it has not been fixed.

**Comment by kdex** [comment]
Thank you again. Hint for future readers: The flag is actually called `b_lundef`, and there's more info over at #764.
