### ISSUE TITLE
Support compile_commands.json

### ISSUE THREAD

**Issue by mqudsi** [mesonbuild/meson#3545]
`compile_commands.json` is defacto method for a build system to inform development tools about the commands executed to compile a compilation unit, documented here: https://clang.llvm.org/docs/JSONCompilationDatabase.html

CMake can generate such a database of compilation commands by setting `CMAKE_EXPORT_COMPILE_COMMANDS` in the cmake configuration (despite what it says on the linked LLVM page above, this _is_ supported under Ninja and Unix Makefiles generators alike). 

The resulting database of compilation commands can then be used by development tools such as intellisense/autocomplete providers (e.g. language server protocol clients), code formatting tools, and others to allow for the correct compilation of individual compilation units without the user needing to configure them manually.

It would be immensely useful if meson could support the generation of this file as a build artifact.

**Comment by mqudsi** [comment]
Spoke too soon! http://mesonbuild.com/IDE-integration.html#ide-integration

**Comment by delthas** [comment]
For information, all mentions of `compile_commands.json` have been removed from the [IDE integration](https://github.com/mesonbuild/meson/blob/master/docs/markdown/IDE-integration.md) page, but Meson [does output a `compile_commands.json` file](https://github.com/mesonbuild/meson/blob/23f831a67497135091bcb44675ff5a7fb9ce8425/mesonbuild/backend/ninjabackend.py#L320) in the build directory.

**Comment by nh2** [comment]
> all mentions of `compile_commands.json` have been removed from the [IDE integration](https://github.com/mesonbuild/meson/blob/master/docs/markdown/IDE-integration.md) page, but Meson [still outputs a `compile_commands.json` file](https://github.com/mesonbuild/meson/blob/23f831a67497135091bcb44675ff5a7fb9ce8425/mesonbuild/backend/ninjabackend.py#L320) in the build directory.

I've pointed that out here: https://github.com/mesonbuild/meson/pull/4547#pullrequestreview-361323958

It should probably be added back to the docs.
