### ISSUE TITLE
flags from add_global_link_arguments not in build project

### ISSUE THREAD

**Issue by holgerschurig** [mesonbuild/meson#3547]
Hi,

I have this code in my meson.build:

```
to_be_tested_linker_args = [
	'-Wl,-z,defs',              # Detect and reject underlinking
	'-Wl,-z,now',               # Disable lazy binding
	'-Wl,-z,relro',             # Read-only segments after relocation
]
foreach arg: to_be_tested_linker_args
	if cc.has_link_argument(arg)
		add_global_link_arguments(arg, language: 'c')
	endif
	if cpp.has_link_argument(arg)
		add_global_link_arguments(arg, language: 'cpp')
	endif
endforeach
```

At `meson build` time I see that the arguments are supported by the linker:

```
Compiler for C supports link arguments -Wl,-z,defs: YES
Compiler for C++ supports link arguments -Wl,-z,defs: YES
Compiler for C supports link arguments -Wl,-z,now: YES
Compiler for C++ supports link arguments -Wl,-z,now: YES
Compiler for C supports link arguments -Wl,-z,relro: YES
Compiler for C++ supports link arguments -Wl,-z,relro: YES
```
So clearly, the test itself worked. But adding the linker args did somehow not work. While I don't see any error in the meson log, they aren't activated. There is, for example, no `-Wl,-z,relro` in the compile_commands.json file. Nor is there "relro" anywhere to be seen: `grep -r relro build/` returns nothing, except in the meson-log.txt file.

BTW, my executables aren't any special. I don't have any link-specific clauses in my executable. Here's an example of a short one:

```
test_beep_src = [
	'test_beep/main.cpp',
	'util_sound.cpp',
]
executable('test_beep',
	test_beep_src,
	dependencies: [qt_core, lib_asound],
	build_by_default: false,
)
```

**Comment by nirbheek** [comment]
This is on purpose, because then you would not be able to add flags to `add_project_arguments()` after running compiler checks.

Compiler checks do not inherit flags from anywhere else: the command-line, the environment, etc. They are completely stand-alone, and this is a feature, since then you can be absolutely sure that flags aren't unexpectedly added to your compiler checks, which can break them.

**Comment by nirbheek** [comment]
This is also already mentioned in the reference manual: http://mesonbuild.com/Reference-manual.html#add_global_arguments

**Comment by holgerschurig** [comment]
> Compiler checks do not inherit flags from anywhere else

I'm not just checking with `cc.has_link_argument()`  !!

I'm calling `add_global_link_arguments()`. So what you wrote here is not related.

> This is also already mentioned in the reference manual: http://mesonbuild.com/Reference-manual.html#add_global_arguments

The help text states that ...

* global arguments aren't used in subprojects
* or in the presence of `add_project_arguments()`

... if I understand the text correctly. But ...

* I never use a subproject nor am I a subproject
* I don't use `add_project_link_arguments()` at all
* actually `grep project` on my meson.build only yields on result: the initial call to `project()` in line 1

So the bug is still as described by me: `add_global_link_arguments()` is a no-op, and quite unexpectedly.

Now, still, I tried to follow your advice. And I replaced `add_global_link_arguments()` with `add_project_link_arguments()`. And still the linker options don't make it into the ninja calls or the json command file.

**Comment by nirbheek** [comment]
Apologies, I read your comment too quickly and misunderstood.

**Comment by nirbheek** [comment]
I cannot reproduce the bug as you have described it:

```meson
if cc.has_link_argument('-Wl,-z,now')
  add_project_link_arguments('-Wl,z,now', language: 'c')
endif
e = executable('exe', 'exe.c')
```

This adds `-Wl,z,now` to the 'exe' executable
