### ISSUE TITLE
Allow passing ExternalProgram objects as test() and add_install_script() arguments.

### ISSUE THREAD

**Issue by scontini76** [mesonbuild/meson#3552]
http://mesonbuild.com/Reference-manual.html#external-program-object states that path() returns an array:

> path() which returns an array pointing to the executable (this is an array as opposed to a string because the program might be ['python', 'foo.py'], for example)

but it seems to me that it return a string, as if I try to concatenate it with an array like this:

`find_program('my program').path() + ['some', 'other', 'stuff']`

I get this error:

> Invalid use of addition: must be str, not list

`[find_program('my program').path(), 'some', 'other', 'stuff']`

works fine.

**Comment by nirbheek** [comment]
Hum, we can't change this now because it would break too many build files, but we could add a new `.command()`. Not sure what the use-case for that would be, though.

**Comment by nirbheek** [comment]
Actually, why are you using `.path()` at all?

**Comment by scontini76** [comment]
I'm not asking for API change, just to align the documentation to avoid that others go mad trying to figure out why they don't obtain what they are excepting :)

Anyway... I'm using .path() probably because I'm doing something ugly like this:

```
py3 = find_program('python3')
test('python_pycodestyle', py3,
     workdir: meson.source_root(),
     args: [find_program('pycodestyle').path(), 'python'])

[ many other tests using py3 as interpreter]
```

I want to test my python code, inside the `python` directory, against pycodestyle (or other tools like pylint and so on). I want to be sure that I have the tool and I'm going to use it with the right interpreter (sometime I have python2 code, sometime I have python3 code). That way I force the startup script to be interpreted by the correct python version. Maybe there is many simpler ways, that one works absolutely fine for me with parallel installation of python and with linters for both (installed with pip2 and pip3). Previously I was struggling because following the documentation I was doing:

```
py3 = find_program('python3')
test('python_pycodestyle', py3,
     workdir: meson.source_root(),
     args: find_program('pycodestyle').path() + ['python'])
```

Hope all that things doesn't looks too silly ;)

**Comment by nirbheek** [comment]
Even in your case, when you pass a `find_program()` object to `test()` `args:`, you shouldn't need to use `.path()`. Passing the object directly should work. Does that not work for you?

**Comment by scontini76** [comment]
Thank you very much for the documentation updates and to indicate me (so quickly) the right way to use find_program() in test()!

**Comment by michaelcadilhac** [comment]
In the same vein, the following:

```
project ('test-test')
echo_exe = find_program ('echo')
py = import('python').find_installation()
test ('test', echo_exe, args : [ py ])
```

fails with:

`meson.build:4:0: ERROR: Command line arguments must be strings, files or targets.`

Is this the same problem?  Using `py.path ()` solves the problem.

**Comment by dcbaker** [comment]
Yeah. Can you open a new issue for that?

**Comment by eli-schwartz** [comment]
This was wrongly closed, the linked PR only implemented this for `add_*_script` and not for `test()`.
