### ISSUE TITLE
wrap/wrapb version ordering wrong

### ISSUE THREAD

**Issue by fzwoch** [mesonbuild/meson#3558]
I have manually downloaded the `zlib 1.11.2 1` wrap from wrapdb. Running `meson wrap status` yields in the following output:

```shell
$ meson wrap status
Subproject status
 zlib not up to date. Have 1.2.11 1, but 1.2.8 8 is available.
```

Not sure how things are sorted by wrap/wrapdb, But for me 1.2.11 seems more recent than 1.2.8 and the downgrade is probbaly not what I want.

**Comment by nirbheek** [comment]
This was fixed with https://github.com/mesonbuild/wrapweb/pull/45.
