### ISSUE TITLE
make exe wrapper optional even if setted in cross build definition file

### ISSUE THREAD

**Issue by drakkan** [mesonbuild/meson#3562]
Hi,

I recently added to archlinux a package to cross compile for windows using meson

https://aur.archlinux.org/packages/mingw-w64-meson/

since we define an exe_wrapper here:

https://aur.archlinux.org/cgit/aur.git/tree/toolchain-mingw.meson?h=mingw-w64-meson#n10

meson will crash if wine is not installed, with an error like this

```
FileNotFoundError: [Errno 2] No such file or directory: 'i686-w64-mingw32-wine': 'i686-w64-mingw32-wine'
```

wine is necessary for building some packages since they need to run the created windows executables to generate configs/build files or they run test binaries in the check() step, but there are also several packages that build just fine without wine, so I would like to have wine as optdepends for mingw-w64-meson and the packages that really need wine will add it to their depends. 

For this to work meson should automagically set exe_wrapper to None if setted in cross build definition file but not found on disk. What do you think about this change?

**Comment by nirbheek** [comment]
The change that makes the most sense would be to error out (with a good message) only if the exe wrapper is actually used.

**Comment by jpakkane** [comment]
Yes, that behavior seems to make the most sense.

**Comment by nirbheek** [comment]
Changes needed, if exe wrapper is not found:

1. Compiler sanity check should be skipped
2. Compiler checks should fall back to non-exe-wrapper codepaths

Things that will stay the same:

1. `meson.has_exe_wrapper()` inside build files will continue to return true
2. tests will still be attempted to be run with the exe wrapper
