### ISSUE TITLE
Using meson='meson --wrap-mode nodownload' alias breaks subcommands

### ISSUE THREAD

**Issue by jadahl** [mesonbuild/meson#3564]
I have the alias

```
alias meson='meson --wrap-mode nodownload'
```

in my .bashrc to avoid having meson accidentally download dependencies just because I didn't update one or the other. I discovered, however, that this breaks `meson configure` and similar commands. The same error message can be seen by doing this:

```
$ meson --wrap-mode nodownload configure build
Error during basic setup:

configure is not a directory
```

**Comment by jpakkane** [comment]
Does `meson configure --wrap-mode nodownload build` work?

**Comment by xclaesse** [comment]
The error message is a bit obscure indeed, but that command line is not valid. The first argument must be the command to run, and --wrap-mode is not an argument accepted by configure command.

I think you should not override the `meson` command, better invent another command name. I personally use `mconf`, you could have `alias mconf=meson --wrap-mode build`. That way you can still use the `meson` command.
