### ISSUE TITLE
what is the proper way to find a header file?

### ISSUE THREAD

**Issue by asartori86** [mesonbuild/meson#3576]
I may have missed something from the documentation, but I didn't understand what is the proper way to find a header file.

I need to link against a library (which does not provide `.pc` file). It is simply a library and a collection of header files. So I need to 
1. find the library  -- which works well with `lib = meson.get_compiler('cpp').find_library(..., dirs:['some/paths']) 
2. find the path to the header files. How should I look for `header.h`?

to make a comparison with CMake, I would like to do the following
```
find_path(LIB_INCLUDE_DIR header.h
  /usr/include
  /usr/local/include
  /whatever/path/you/should/look
  )

find_library(LIB
  NAMES name_of_library
  PATHS /usr/lib64 /non/standard/paths
  )

include_directories(${LIB_INCLUDE_DIR})
target_link_libraries(target_name ${LIB})
```

Thanks

**Comment by tp-m** [comment]
You could do something like:
```
cxx = meson.get_compiler('cpp')
my_lib_cargs = []
found = false
foreach idir : ['/usr/include', '/usr/local/include', '/whatever/path/you/should/look']
  inc_arg = '-I' + idir
  if not found and cxx.has_header('foobar.h', args: inc_arg)
    my_lib_cargs += [inc_arg]
    found = true
  endif
endforeach
```
See http://mesonbuild.com/Reference-manual.html#compiler-object

Or you check all includes in one go and add all `-I` to the c_args if found.

**Comment by asartori86** [comment]
thanks @tp-m
