### ISSUE TITLE
meson.build:86:0: ERROR: Native dependency 'udisks2' not found

### ISSUE THREAD

**Issue by MasterCATZ** [mesonbuild/meson#3591]
sudo apt install meson
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  ninja-build
The following NEW packages will be installed:
  meson ninja-build
0 to upgrade, 2 to newly install, 0 to remove and 0 not to upgrade.
Need to get 309 kB of archives.
After this operation, 1,650 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://archive.ubuntu.com/ubuntu bionic/universe amd64 ninja-build amd64 1.8.2-1 [93.3 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic/universe amd64 meson all 0.45.1-2 [216 kB]
Fetched 309 kB in 3s (110 kB/s)
Selecting previously unselected package ninja-build.
(Reading database ... 686236 files and directories currently installed.)
Preparing to unpack .../ninja-build_1.8.2-1_amd64.deb ...
Unpacking ninja-build (1.8.2-1) ...
Selecting previously unselected package meson.
Preparing to unpack .../meson_0.45.1-2_all.deb ...
Unpacking meson (0.45.1-2) ...
Processing triggers for doc-base (0.10.8) ...
Processing 1 added doc-base file...
Registering documents with scrollkeeper...
Processing triggers for man-db (2.8.3-2) ...
Setting up ninja-build (1.8.2-1) ...
Setting up meson (0.45.1-2) ...

aio@aio:~/Downloads/gnome-disk-utility-3.28.2$ sudo apt install --reinstall udisks2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 to upgrade, 0 to newly install, 1 to reinstall, 0 to remove and 0 not to upgrade.
Need to get 231 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/main amd64 udisks2 amd64 2.7.6-3 [231 kB]
Fetched 231 kB in 2s (101 kB/s)   
(Reading database ... 686355 files and directories currently installed.)
Preparing to unpack .../udisks2_2.7.6-3_amd64.deb ...
Unpacking udisks2 (2.7.6-3) over (2.7.6-3) ...
Setting up udisks2 (2.7.6-3) ...
Processing triggers for man-db (2.8.3-2) ...
Processing triggers for dbus (1.12.2-1ubuntu1) ...
aio@aio:~/Downloads/gnome-disk-utility-3.28.2$ sudo meson builddir
The Meson build system
Version: 0.45.1
Source dir: /home/aio/Downloads/gnome-disk-utility-3.28.2
Build dir: /home/aio/Downloads/gnome-disk-utility-3.28.2/builddir
Build type: native build
Project name: gnome-disk-utility
Native C compiler: ccache cc (gcc 7.3.0 "cc (Ubuntu 7.3.0-16ubuntu3) 7.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Message: Checking for valid fallocate() function
Compiler for C supports arguments -fno-strict-aliasing -Wcast-align -Wdeclaration-after-statement -Wformat=2 -Winit-self -Winline -Wmissing-declarations -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn -Wmissing-prototypes -Wnested-externs -Wno-error=missing-field-initializers -Wno-error=unused-parameter -Wno-missing-field-initializers -Wno-unused-parameter -Wold-style-definition -Wpacked -Wredundant-decls -Wshadow -Wsign-compare -Wstrict-aliasing -Wstrict-prototypes -Wswitch-default -Wswitch-enum -Wundef -Wunused-but-set-variable -Wwrite-strings: YES
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency gmodule-2.0 found: YES 2.56.1
Native dependency gio-unix-2.0 found: YES 2.56.1

meson.build:86:0: ERROR: Native dependency 'udisks2' not found

A full log can be found at /home/aio/Downloads/gnome-disk-utility-3.28.2/builddir/meson-logs/meson-log.txt
aio@aio:~/Downloads/gnome-disk-utility-3.28.2$

**Comment by jpakkane** [comment]
`udisks2` is the runtime dependency. You need to install the dev package to get the development files. Those are provided by dev packages such as `libudisks2-dev` or equivalent for your distro.

**Comment by mcatanzaro** [comment]
> `udisks2` is the runtime dependency. You need to install the dev package to get the development files. Those are provided by dev packages such as `libudisks2-dev` or equivalent for your distro.

Indeed. This issue should be closed.
