### ISSUE TITLE
grammar: add new keyword, 'in'

### ISSUE THREAD

**Issue by MathieuDuponchelle** [mesonbuild/meson#3600]
I've noticed the pattern here and there of using:

```
if ['foo', 'bar'].contains(variable)
```

It's a minor annoyance, but the following would be nicer:

```
if variable in ['foo', 'bar']
```

Thoughts?

**Comment by tp-m** [comment]
Yes, please. I've been wanting that as well!

**Comment by MathieuDuponchelle** [comment]
Hey @jpakkane , if you feel like that's a good idea just say so and I'll implement it at some point :)

**Comment by jpakkane** [comment]
Basically yes, but there are a bunch of tricky design choices that need to be made:

 - does this work only for arrays or also for dicts? Should it check for keys like Python? What about strings?
 - What type can the first variable be? Checking for strings and numbers is easy. What about stuff like generated file lists? Is it ok to just forbid checking for anything else than strings and numbers?
 - Should there be a `not in` like in Python or should it do `if not x in foo`? How does the precedence go in this case?

**Comment by MathieuDuponchelle** [comment]
does this work only for arrays or also for >

**Comment by MathieuDuponchelle** [comment]
> does this work only for arrays or also for dicts?

Both

> Should it check for keys like Python?

Yes

> What about strings?

I don't really see a use case for it so I'd say not at first, unless this is what a user would expect if the keyword did exist, really not sure :)

> What type can the first variable be? Checking for strings and numbers is easy. What about stuff like generated file lists? Is it ok to just forbid checking for anything else than strings and numbers?

Good question, I don't really have an answer here, I think it *is* completely OK to start small, what's important really is consistency IMHO

> Should there be a not in like in Python or should it do if not x in foo? How does the precedence go in this case?

`not in` would be nice yes, to be honest I'm really basing my idea of what `in` could do off of python :)

Another point to think about is how adding this keyword could break existing build definitions, as far as I can tell this is context-dependent enough that it could be safe, but there might be corner cases I haven't thought of

**Comment by xclaesse** [comment]
I quickly checked the parser code to implement this, I think it means that `in` must be added in keywords, so `in='foo'` would generate an error (like python does). That's not backward compatible, and I think it has a high risk of causing failures in many projects, even if they just have to rename their `in` variables.

**Comment by MathieuDuponchelle** [comment]
We could make this opt-in maybe ?

**Comment by xclaesse** [comment]
Just to proof my point about backward compatibility, we have a unit test using "in" as variable name, that's why CI failed.

**Comment by xclaesse** [comment]
> We could make this opt-in maybe ?

I guess we could have opt-in language features, or language versioning. Like `project(..., language_version : 2)`. I don't think @jpakkane gonna like that, but why not.

**Comment by kaimast** [comment]
Imho "in" is a horrible name for a variable. I understand that a unit test might use it but I think this change breaking "many projects" is an overestimation.

**Comment by xclaesse** [comment]
People do horrible things all the time, sadly ;-)

**Comment by MathieuDuponchelle** [comment]
Yes, backwards compatibility should obviously be preserved, plus "in / out" variable names seem like a pretty common and acceptable naming pattern to me ;)
