### ISSUE TITLE
grammar: add new statement, 'break'

### ISSUE THREAD

**Issue by MathieuDuponchelle** [mesonbuild/meson#3601]
The lack of a break statement in foreach loops forces the usage of the following pattern in certain situations:

```
array = ['foo', 'bar']

condition_was_met = false

foreach element : array
  if not condition_was_met
    if element_meets_condition()
       # Do something with element
       condition_was_met = true
    endif
  endif
endforeach
```

A break statement would allow the following:

```
array = ['foo', 'bar']

foreach element : array
  if element_meets_condition()
    # Do something with element
    break;
  endif
endforeach
```

Thoughts?

**Comment by MathieuDuponchelle** [comment]
'continue' would also be useful in cases where each element needs to fulfill a certain set of conditions, I can open a separate issue for that or we can discuss that here, just let me know :)

**Comment by tp-m** [comment]
I've been wanting a `break` statement as well. Don't think I ever needed `continue`.

**Comment by xclaesse** [comment]
Same as for `in`, this would introduce new keywords that would break projects that use `continue` or `break` as variable name. Could be a function instead, `continue()` and `break()` just like we have `subdir_done()`, even if that's a bit ugly IMHO.

**Comment by tp-m** [comment]
is it not possible to make the parser distinguish `break` from `break()` or `break=...` ?

**Comment by xclaesse** [comment]
I guess we could detect if `continue` is alone on a line and then treat it as a keyword instead of identifier. That sounds like a little bit hackish in the interpreter, but why not... Technically it would still not be backward compatible because a variable could be alone on its line to evaluate to nothing, that's not a syntax error. But much more corner case.
```meson
continue = 1
continue
```

**Comment by tp-m** [comment]
> because a variable could be alone on its line to evaluate to nothing, that's not a syntax error. But much more corner case.

That doesn't really make sense though, does it? So not sure we need to support that..

**Comment by xclaesse** [comment]
> I mean: this isn't C

And even for C, there is `-Wunused-value` to warn about it.

**Comment by jpakkane** [comment]
One option is to publish a release that checks for those keywords and prints a warning that the name will become reserved in the future. Then add this in the next release.
