### ISSUE TITLE
No way to set DT_RUNPATH?

### ISSUE THREAD

**Issue by pb-cdunn** [mesonbuild/meson#3605]
I have experimented with `install_rpath : '$ORIGIN/../lib'` in my `executable()` definition. My understanding is that it modifies the ELF header to add DT_RPATH.

I have read #314 and much related info. I do not want to get into the discussion of shoulds and should nots on ELF headers. But I have a question.

I personally would never use [`DT_RPATH`](http://blog.qt.io/blog/2011/10/28/rpath-and-runpath/), but I do sometimes use `DT_RUNPATH` for convenience in testing. Would it be possible to provide `install_runpath`? Or if that's a bad idea, why not?

**Comment by nirbheek** [comment]
`DT_RPATH` vs `DT_RUNPATH` is an implementation detail, and `DT_RPATH` is deprecated. On Debian, you `-Wl,-rpath` will always set `DT_RUNPATH` unless you pass `-Wl,--disable-new-dtags`.

I don't think the distinction requires new API in Meson. You should pass `-Wl,--disable-new-dtags` or `-Wl,--enable-new-dtags` depending on whether you want RPATH or RUNPATH.

**Comment by pb-cdunn** [comment]
Thanks for the info.  Setting DT_RPATH would cause problems, so I'll just set neither. Not a problem.
