### ISSUE TITLE
Need to pass flags to pkg-config? (to set `prefix`)

### ISSUE THREAD

**Issue by pb-cdunn** [mesonbuild/meson#3606]
I have generated a .pc for a dependency, using `prefix` [to make the file relocatable](https://people.freedesktop.org/~dbn/pkg-config-guide.html):
```ini
prefix=/PREFIX
libdir=${prefix}/lib
includedir=${prefix}/include

Name: dazzdb
Description: DAZZDB library
Version: 0.0.1
Libs: -L${libdir} -ldazzdb
Libs.private: -lm
Cflags: -I${includedir}/dazzdb
```
Now, I want to build something which uses this. It's not installed, so I need to run

    pkg-config --cflags --define-variable=prefix=mydir dazzdb

A new argument to `dependency()` could support that, but that would require altering my `meson.build`. So let's assume I install all such `.pc` files into a common location, different than the system default pkg-config path. And let's assume I will modify my shell environment, rather than `meson.build` itself.

How can I pass `--define-variable` to **pkg-config**? (My best idea so far is to use an alias for `pkg-config`.)

Or, what is the recommended way to deal with relocatable `.pc` files?

Or, what is the recommended way to locally install relocatable `.pc` files so they end up with hard-coded `prefix`?

**Comment by nirbheek** [comment]
See `define_variable:` on `dependency()`: http://mesonbuild.com/Reference-manual.html#dependency-object

**Comment by nirbheek** [comment]
Also, pkg-config will usually automatically define the prefix itself, so you don't need to manually define it. This is enabled by default, and disabled if you pass `--dont-define-prefix`.

**Comment by jpakkane** [comment]
Also note that this has a very specific and unfortunate side effect: the build environment of the machine is now inside your build definition file. That means that building the project on any other machine with different configurations no longer works unless they edit the source files. This is something that you usually want to avoid if possible.

**Comment by nirbheek** [comment]
The usual reason to use `define_variable:` for prefix is if you want to get a value and use that as the `install_dir:` while ensuring that *your own* prefix is used. In that case, the source does not need to be edited.

**Comment by pb-cdunn** [comment]
Yes, I saw `dependency.define_variable()` and `--dont-define-prefix`. The problem is basically what @jpakkane mentions. We have relocatable `.pc` files (generated earlier by a different run of Meson, actually). I'm looking for advice on how to work with that.

Do you recommend that I install the `.pc` files for dependencies into the same place that Meson is about to install the new `.pc` file for the current project (`DESTDIR/PREFIX`)? Slightly complicated, since the dependencies will not be among the new build artifacts, but it's possible.

It's important to be aware that in an enterprise environment (e.g. Amazon, where I used to work), we must build one project at a time, export artifacts, and then import those artifacts for high-level project, etc. The Meson subproject system is not used in such an environment.

**Comment by cdunn2001** [comment]
Hmmm. That's what we're doing at my new company, where we do not use build-artifacts. But what if the `.pc` files are among the build-artifacts for the libraries upon which my new project depends?

I guess you're suggesting that the `.pc` files be copied from the build-artifacts for the dependencies and actually installed where we intend to install the build-artifacts for the current project. I suppose that's good enough for now.

**Comment by pb-cdunn** [comment]
Would this environment variable help?
```
       PKG_CONFIG_TOP_BUILD_DIR
              A value to set  for  the  magic  variable  pc_top_builddir
              which may appear in .pc files. If the environment variable
              is not set, the default value  '$(top_builddir)'  will  be
              used.  This  variable  should refer to the top builddir of
              the Makefile where the compile/link flags reported by pkg-
              config  will  be  used.   This  only  matters when compil-
              ing/linking  against  a  package  that  hasn't  yet   been
              installed.
```
**Meson** could create `.pc` files with `top_builddir` set, but when *using* the `.pc` files it could provide the `PKG_CONFIG_TOP_BUILD_DIR` environment variable to override that. Would that work?

**Comment by eli-schwartz** [comment]
`${pc_top_builddir`} is wrong here.

In #10277 we added support for automatically handling `${pcfiledir}` instead.

**Comment by eli-schwartz** [comment]
> See `define_variable`: on `dependency()`: http://mesonbuild.com/Reference-manual.html#dependency-object

Btw this confuses the dependency function lookup, which yields an object that intrinsically has some Cflags/Libs, and the dependency object method that lets you get *additional* variables with the value of prefix redefined.

Obviously get_variable() cannot change the compile flags of the original object.
