### ISSUE TITLE
Logging system-calls?

### ISSUE THREAD

**Issue by pb-cdunn** [mesonbuild/meson#3607]
Would there be value in a command-line flag to force Meson to log all `Popen_safe()` system calls, for debugging? (Of course, I can use `strace` in a pinch.)

For reference:
* https://github.com/mesonbuild/meson/blob/fc5e8dfcdae11d23469fd01d878c7c9c30d67d30/mesonbuild/dependencies/base.py -- `class Dependency`, which runs **pkg-config** invisibly
* https://github.com/mesonbuild/meson/blob/fc5e8dfcdae11d23469fd01d878c7c9c30d67d30/mesonbuild/mesonlib.py -- `Popen_safe()`

**Comment by pb-cdunn** [comment]
I'm willing to submit a pull-request for this. It's *very important*. We spend too much debugging `pkg-config` problems in our builds. We need to know exactly how pkg-config was called.

**Comment by nirbheek** [comment]
Sounds like you just want a `mlog.debug()` in `mesonbuild/dependencies/base.py` `PkgConfigDependency:_call_pkgbin()`. I'd be happy to review and merge such a change.
