### ISSUE TITLE
wraps should not have version numbers in the directory name

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#3608]
Having version numbers in the directory name is both redundant and causes unnecessary work when upgrading fallback dependencies in subprojects. For instance, in GStreamer we have the following projects using zlib:

glib, gstreamer, cairo, openssl, gnutls, gdk-pixbuf, freetype, fontconfig, libpng, ffmpeg.

All of these have: `dependency('zlib', ..., fallback: ['zlib-1.2.11', 'zlib_dep'])`. The directory will change on update, and require changes to all these projects. Multiply by the fact that all these have dependencies on each other, and it's a tiresome situation.

Updating a wrap should just be a matter of changing the version in the wrap file and should not require changes anywhere else.

**Comment by sarum9in** [comment]
I believe this is already supported, see https://github.com/mesonbuild/meson/tree/master/manual%20tests/1%20wrap

I just manually checked it also by replacing

```meson
project('downloader', 'c')

cc = meson.get_compiler('c')

#s = subproject('sqlite').get_variable('sqlite_dep')
s = dependency('ssss', fallback : ['sqlite', 'sqlite_dep'])
th = dependency('threads')

libdl = cc.find_library('dl', required : false)

e = executable('dtest', 'main.c',
  dependencies : [th, libdl, s])

test('dltest', e)
```

And it still works.
