### ISSUE TITLE
Passing arguments to run_target

### ISSUE THREAD

**Issue by matteomaser** [mesonbuild/meson#3610]
I created a `run_target` which deploys and runs the cross compiled program to a ssh target.
```meson
run_target('run', command: ['scripts/run.sh'], depends: executables)
```
I would like to pass the target machine as an argument.

Reading documentation and making some tests (meson `0.46.0`) I noticed:
- Environment variables are not passed to the script. eg. `TARGET=192.168.1.80 ninja run` won't work
- There is no way to pass arguments (`ninja run 192.168.1.80` obviously won't work)

Am I missing something? Should I give up using `run_target` and call the script directly?

I think this is somewhat related to #1314

**Comment by jpakkane** [comment]
Arguments are put in the command array after the program. [See here](http://mesonbuild.com/Run-targets.html).

**Comment by matteomaser** [comment]
That allows me to pass arguments from the `meson.build` to the script, but I have no way to set it from command line. Furthermore, I would like to use the same build for multiple targets, setting the value and configuration time wouldn't help.

The best solution I can think of for my use-case is writing the ip argument to a file and reading it back from the script. eg. 
```echo 192.168.1.80 > ~/.target && ninja run```

I agree environment variables [are bad](http://mesonbuild.com/Contributing.html#environment-variables) for the build system configuration and actual build process, but I don't think they would pose a problem for run targets.

**Comment by jpakkane** [comment]
The common solution in these cases is to define a project option and then do something like:

    run_target('run', command : ['scripts/run.sh', get_option('device_address')])

**Comment by matteomaser** [comment]
Thanks, it works perfectly.

If anyone else finds this issue searching google, to pass arguments to run_targets:

- Add an option to `meson_options.txt`
```
option('target', type: 'string', value: 'lizard',
       description: 'Target machine for deploy commands')
```
- Pass it to the run_target in `meson.build`
```
...
run_target('run', command: ['scripts/run.sh', get_option('target')], depends: all)
```
- Invoke command with
```
meson configure -Dtarget=root@192.168.1.82 && ninja run
```
