### ISSUE TITLE
Fail to run tests under wine when cross building

### ISSUE THREAD

**Issue by xclaesse** [mesonbuild/meson#3620]
I wrote CI for a project that cross build it using mingw. If I add exe_wrapper=wine in my cross file, "ninja test" fails because test exe cannot find built libraries.

> 000d:err:module:import_dll Library libglib-2.0-0.dll (which is needed by
> L"Z:\\home\\user\\app\\_build\\glib\\tests\\array-test.exe") not found

I suspect meson already has magic to make those libraries found when running native tests, would be nice to also add special case for wine there.

While at it, I'm wondering if we could split exe_wrapper into one wrapper to build and one wrapper to run tests. My use case here is I want my CI to verify that build works with no wrapper (stuff like cc.compute_int() must work without running code), but use a wrapper for running tests once the build complete.

**Comment by jpakkane** [comment]
This is not actually something Meson can fix. On Windows the library search path comes from `$PATH` but not from the shell's path. It actually comes from a Wine config file (somewhere, I don't remember where).

**Comment by xclaesse** [comment]
Maybe cross file could have `exe_wrapper_env = ['WINEPATH': '/foo']` ? But the path is actually inside meson's build tree, so only meson really knows the value. Right?

**Comment by nirbheek** [comment]
@xclaesse try https://github.com/mesonbuild/meson/pull/3621?

**Comment by nirbheek** [comment]
Strange, it works for me with Cerbero:

```console
$ WINEPATH="Z:/home/nirbheek/projects/repositories/gst/cerbero.git/build/dist/windows_x86/bin" meson test -C _buildtest/ bytes --verbose
ninja: Entering directory `/home/nirbheek/projects/repositories/gst/cerbero.git/build/sources/windows_x86/glib-2.56.1/_buildtest'
ninja: no work to do.
000b:fixme:winediag:start_process Wine Staging 3.6 is a testing version containing experimental patches.
000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
/bytes/new: OK
/bytes/new-take: OK
/bytes/new-static: OK
/bytes/new-with-free-func: OK
/bytes/new-from-bytes: OK
/bytes/new-from-bytes-slice: OK
/bytes/new-from-bytes-shared-ref: OK
/bytes/hash: OK
/bytes/equal: OK
/bytes/compare: OK
/bytes/null: OK
/bytes/to-data/transfered: OK
/bytes/to-data/two-refs: OK
/bytes/to-data/non-malloc: OK
/bytes/to-array/transfered: OK
/bytes/to-array/two-refs: OK
/bytes/to-array/non-malloc: OK
1/1 bytes                                   OK       0.37 s

OK:         1
FAIL:       0
SKIP:       0
TIMEOUT:    0
```

I'll try with the MinGW64 that ships with Fedora.

**Comment by nirbheek** [comment]
> I'll try with the MinGW64 that ships with Fedora.

That also works fine.
