### ISSUE TITLE
windows msvc cross-compilation linker arguments are wrong for sanity-check

### ISSUE THREAD

**Issue by exhu** [mesonbuild/meson#3629]
given a cross-file:
``
[binaries]
c = 'C:\\\\Program Files (x86)\\\\Microsoft Visual Studio\\\\2017\\\\Professional\\\\VC\\\\Tools\\\\MSVC\\\\14.11.25503\\\\bin\\\\Hostx64\\\\x86\\\\cl'

[properties]
c_link_args = ['/LIBPATH:C:\\\\Program Files (x86)\\\\Microsoft Visual Studio\\\\2017\\\\Professional\\\\VC\\\\Tools\\\\MSVC\\\\14.11.25503\\\\lib\\\\x86',
    '/LIBPATH:C:\\\\Program Files (x86)\\\\Windows Kits\\\\NETFXSDK\\\\4.6.1\\\\lib\\\\um\\\\x86',
    '/LIBPATH:C:\\\\Program Files (x86)\\\\Windows Kits\\\\10\\\\lib\\\\10.0.16299.0\\\\ucrt\\\\x86',
    '/LIBPATH:C:\\\\Program Files (x86)\\\\Windows Kits\\\\10\\\\lib\\\\10.0.16299.0\\\\um\\\\x86',
    '/MACHINE:X86']
``

it tries to run cl.exe sanity-check.c with linker arguments which are not recognized (linker arguments must be prefixed with /link and passed after all other options and source files)

**Comment by nirbheek** [comment]
> linker arguments must be prefixed with /link and passed after all other options and source files

We do this correctly for arguments added from other sources, but I guess we missed this and no one ever tested it.

What happens if you add `/link` yourself in that list in the cross file?

**Comment by NNemec** [comment]
Seems like I am just stumbling over the same issue:
The log output of my build contains:

Appending CFLAGS from environment: ' /DWIN32 /D_WINDOWS /W3 /utf-8  /MD /O2 /Oi /Gy /DNDEBUG /Z7'
Appending LDFLAGS from environment: ' /DEBUG  /INCREMENTAL:NO /OPT:REF /OPT:ICF'
Appending CPPFLAGS from environment: ' '
Sanity testing C compiler: cl
Is cross compiler: False.
Sanity check compiler command line: cl /MDd /DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF C:\BUILDDIR\sanitycheckc.c /FeC:\BUILDDIR\sanitycheckc.exe

and a few lines later:

Sanity check compile stderr:
Microsoft (R) C/C++ Optimizing Compiler Version 19.21.27702.2 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9002 : ignoring unknown option '/OP'
cl : Command line warning D9002 : ignoring unknown option '/OT'
cl : Command line warning D9002 : ignoring unknown option '/O:'
cl : Command line warning D9002 : ignoring unknown option '/OR'
cl : Command line warning D9002 : ignoring unknown option '/OE'
cl : Command line warning D9002 : ignoring unknown option '/OF'
cl : Command line warning D9002 : ignoring unknown option '/OP'
cl : Command line warning D9002 : ignoring unknown option '/OT'
cl : Command line warning D9002 : ignoring unknown option '/O:'
cl : Command line warning D9002 : ignoring unknown option '/OI'
cl : Command line warning D9002 : ignoring unknown option '/OC'
cl : Command line warning D9002 : ignoring unknown option '/OF'

So it seems like LDFLAGS is just in the middle of the cl command line without prepending the necessary '/link' (see https://docs.microsoft.com/en-us/cpp/build/reference/compiler-command-line-syntax)

Digging into the mesonbuild code, I find that compiler.py does contain a routine 'linker_to_compiler_args' that prepends a '/link' option as well as a comment about correctly handling 'extra_flags' to deal with the /link flag.

However CLikeCompiler.sanity_check_impl uses its own code for constructing the command line which puts LDFLAGS somewhere in the middle of the options, which can't work for MSVC.

**Comment by jpakkane** [comment]
Most of those flags are things you should not need to have in CFLAGS et al. We provide builtin options for them, for example `/w3` is the internal option warning level and so on.

**Comment by NNemec** [comment]
Well possible, but since LDFLAGS is passed on, I think it is important that it is passed on correctly.

Also, in my case, LDFLAGS is provided externally and having to do a reverse translation would be quite painful...

**Comment by NNemec** [comment]
I'm trying to dig into this further and am wondering:

Why does CLikeCompiler.sanity_check_impl not go through the regular routines for compiling/linking in the first place? The routine constructs the command line in a completely non-standard way which is bound to lead to problems like this one.

B.t.w.: To answer your question @nirbheek : Adding /link to the cross file can't work. The sanity_check code not only fails to add /link but it also does not respect the necessary ordering. 'extra_flags' which contains the LDFLAGS is added before [source_name]
