### ISSUE TITLE
suport for exec_prefix and libexecdir

### ISSUE THREAD

**Issue by tp-m** [mesonbuild/meson#364]
I noticed meson does not have out of the box support for *libexecdir* yet.

Or, more generally speaking, there's also no distinction between --prefix and --exec-prefix which autotools seems to make these days, e.g. ./configure --help shows:
```
Installation directories:
  --prefix=PREFIX         install architecture-independent files in PREFIX
                          [/usr/local]
  --exec-prefix=EPREFIX   install architecture-dependent files in EPREFIX
                          [PREFIX]
```
It seems to default to this for libexecdir, but distros will likely want to override that:
```
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
```
exec_prefix will likely be the same as prefix, and default to the same, but the distinction seems useful.

**Comment by jpakkane** [comment]
What are the use cases for these? When would you install to exec-prefix/libexecdir/whatever instead of regular prefix/bin or somesuch? Is there a case when a project would want to install to both at the same time?

**Comment by tp-m** [comment]
Not sure how much light I can shed on practical use cases here, I can only point out that these exist in the autotools-world and that in my experience distro packagers make use of all of these (perhaps due to packaging guidelines): https://www.gnu.org/prep/standards/html_node/Directory-Variables.html

**Comment by jpakkane** [comment]
Hmmm. That document does not really tell _why_ they are needed, only that they are. And it is written assuming (understandably) Autotools' late evaluation semantics.

I'm all for supporting this, but I'm hesitant to add functionality without understanding the reasoning behind it. That usually leads to code that seems to work but does the wrong thing. Getting comments from someone who has dealt with this issue would be necessary to get this functionality to come out right.

**Comment by ignatenkobrain** [comment]
libexecdir sometimes is used..

For `tracker`, `telepathy`, `NM`, `ibus`, `gvfs` and many other stuff. What is exec_prefix I have no idea.

**Comment by nirbheek** [comment]
`libexecdir` is used for 'helper' executables that are not supposed to be run by the user and should not be in PATH. They are usually helpers that are executed by libraries or via dbus activation. You will see lots of things in `/usr/libexec` on Fedora. GStreamer uses this too.

In theory, `exec_prefix` vs `prefix` allows you to share the architecture-independent prefix between several machines or to create an image that can run on multiple architectures without duplicating everything. In practice, I've never seen anyone use this.

**Comment by tp-m** [comment]
```libexecdir``` support is there now, let's skip the ```exec_prefix``` part until someone actually has a use for it.
