### ISSUE TITLE
When a test failures due to termination by a signal report that in the log

### ISSUE THREAD

**Issue by krader1961** [mesonbuild/meson#3642]
I've been helping bring the [Korn shell](https://github.com/att/ast/) project into the 21st century. It is not unusual for a unit test to fail, with no output, due to the ksh binary dying from a signal (e.g., SIGSEGV). Meson correctly reports the test failed but the details in *meson-logs/testlog.txt* is ambiguous. It would greatly help if details about the unit test exit status were reported in the log. For example, "Test terminated with exit status 3" or "Test terminated due to signal SIGSEGV". If the test passes there is no need to report "Test terminated with exit status 0".

**Comment by nirbheek** [comment]
This makes sense, and is also an easy enhancement, would you like to work on it? :)

The relevant code is in `mesonbuild/mtest.py`.
