### ISSUE TITLE
Feature Request: check optionally if compiler for a certain language is available

### ISSUE THREAD

**Issue by tp-m** [mesonbuild/meson#365]
It would be useful to be able to check optionally if a compiler for a certain programming language is available, i.e. some kind of:

```
have_cxx = meson.check_compiler('cpp')
if have_cxx
  add_languages('cpp')
  ..
endif
```

This is useful when there are some non-essential parts of a module written in another programming language, and those bits should be compiled if a suitable compiler is installed, but otherwise will just not be built.

For example, in a plugin-based system there might be some exotic plugins that are written in another programming language, or some examples or benchmarks or unit tests that are written in another programming language, but one can do well without those as well. (e.g. in GStreamer there are unit tests written in C++ just to make sure our headers don't contain anything that would trip up a C++ compiler, but that shouldn't really make the project hard-depend on C++, even if in practice that's probably not a problem, it's just an example).

As Jussi pointed out on IRC, one can work around this with find_program(), but it seems nicer to have in-built support for this in meson.

**Comment by jpakkane** [comment]
It would seem neater to combine this with add_languages somehow. Perhaps like this:

    if add_languages('cpp', required : false)
      # C++ was added
    else
      # C++ was not added
    endif
