### ISSUE TITLE
Compiler get_define returns unexpected string value

### ISSUE THREAD

**Issue by ePirat** [mesonbuild/meson#3663]
In specific circumstances, `get_define()` returns weird results, for example:

```
    mingw_version = cc.get_define('__MINGW64_VERSION_STR',
        prefix : '#include <_mingw.h>')

    message('Using MinGW-w64 ' + mingw_version)
```

This is defines as:

```c
#define __STRINGIFY(x) #x
#define __MINGW64_STRINGIFY(x) \
  __STRINGIFY(x)

#define __MINGW64_VERSION_MAJOR 6
#define __MINGW64_VERSION_MINOR 0
#define __MINGW64_VERSION_BUGFIX 0

// […]

#define __MINGW64_VERSION_STR	\
  __MINGW64_STRINGIFY(__MINGW64_VERSION_MAJOR) \
  "." \
  __MINGW64_STRINGIFY(__MINGW64_VERSION_MINOR) \
  "." \
  __MINGW64_STRINGIFY(__MINGW64_VERSION_BUGFIX)
```

So what I expected was `6.0.0` or `"6.0.0"` but instead it is `"6" "." "0" "." "0"`, which I guess is technically correct but at least for my usecase relatively useless/unreadable and I can't find an easy way to get the "normalized" string for this.

**Comment by nirbheek** [comment]
This should not be hard to fix, luckily. The `get_define()` implementation needs to be made aware of string concatenation rules. We could use `ast.literal_eval()` since Python has the same rules, or we could do it manually.
