### ISSUE TITLE
Wrong meson/python for tests

### ISSUE THREAD

**Issue by cdunn2001** [mesonbuild/meson#3678]
* https://github.com/open-source-parsers/jsoncpp/blob/master/meson.build

```sh
rm -rf build-static
meson --buildtype debug --default-library static . build-static
ninja -vv -C build-${LIB_TYPE} test
```
```
[9/10] ccache c++  -o jsoncpp_test 'jsoncpp_test@exe/src_test_lib_json_jsontest.cpp.o' 'jsoncpp_test@exe/src_test_lib_json_main.cpp.o' libjsoncpp.a
[9/10] /usr/local/opt/python/bin/python3.6 -u /usr/local/Cellar/meson/0.44.1_1/libexec/bin/meson test --no-rebuild --print-errorlogs
/usr/local/Cellar/meson/0.44.1_1/libexec/bin/meson <source directory> <build directory>
If you omit either directory, the current directory is substituted.
Run /usr/local/Cellar/meson/0.44.1_1/libexec/bin/meson --help for more information.
FAILED: meson-test
```
The problem seems to come from this part of the generated ninja file, `build-static/build.ninja`:
```make
# Test rules

build meson-test: CUSTOM_COMMAND all PHONY
 COMMAND = /usr/local/opt/python/bin/python3.6 -u /usr/local/Cellar/meson/0.44.1_1/libexec/bin/meson test --no-rebuild --print-errorlogs
 DESC = Running$ all$ tests.
 pool = console

build test: phony meson-test
```
It works fine if I alter that manually to run
```sh
meson test --no-rebuild --print-errorlogs
```
I am on OSX with up-to-date brew-installed **meson** and **ninja**. More details:
```sh
$ cat /usr/local/bin/meson
#!/bin/bash
PYTHONPATH="/usr/local/Cellar/meson/0.44.1_1/lib/python3.6/site-packages" exec "/usr/local/Cellar/meson/0.44.1_1/libexec/bin/meson" "$@"

$ which python3.6
/usr/local/bin/python3.6

$ greadlink -f /usr/local/bin/python3.6
/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/bin/python3.6
```
This used to work, and I don't know what changed. How do I convince Meson to generate a ninja file which either uses the correct Python3.6 (not `/usr/local/opt/python/bin/python3.6`) or simply calls `meson test` from my `$PATH`?

**Comment by cdunn2001** [comment]
(I just upgrade Meson from `0.44.1_1` to `0.46.1`. Same problem.)

**Comment by nirbheek** [comment]
It's strange that the python3 thing is wrong, because we literally use `sys.executable`, aka the Python that is being used by Meson while it is running.

Can you try latest git? We made some changes to how Meson detects how it was invoked.

**Comment by cdunn2001** [comment]
Hmmm. That *might* have fixed it. Not sure. I have this now:
```
build meson-test: CUSTOM_COMMAND all PHONY
 COMMAND = /usr/local/opt/python/bin/python3.6 -u /Users/cdunn2001/repo/gh/jsoncpp/.git/LOCAL/bin/meson test --no-rebuild --print-errorlogs
```
That's after
```sh
# d777ffc0 (HEAD -> master, origin/master) Fix #mesondefine token ...
export PYTHONUSERBASE=/Users/cdunn2001/repo/gh/jsoncpp/.git/LOCAL
pip3 install --user .
```
So the `python3.6` is still wrong, but oddly **ninja** now works. But maybe the problem was with the **brew** installation.

What earlier commit should I use to try to repro the problem?

**Comment by cdunn2001** [comment]
I guess I should try something before this:
```
commit 0a035dea6d0b1416fc76e323bbd7b0ab5a60a4af
Author: Nirbheek Chauhan <nirbheek@centricular.com>
Date:   Fri Jun 1 02:30:17 2018
```
I'll try 583e9c4a ...

**Comment by cdunn2001** [comment]
That worked too. I think the problem is with how **brew** installs **meson**.

**Comment by cdunn2001** [comment]
Suddenly, I cannot reproduce this at all.
```
[9/10] /usr/local/opt/python/bin/python3.6 -u /usr/local/Cellar/meson/0.46.1/libexec/bin/meson test --no-rebuild --print-errorlogs
(no errors)
```
I'll re-open if I ever reproduce this reliably. Thanks for the pointer to the recent changes.
