### ISSUE TITLE
gnome.generate_gir() should accept multiple libraries

### ISSUE THREAD

**Issue by MathieuDuponchelle** [mesonbuild/meson#3688]
From `g-ir-scanner --help`:

```
  -l LIBRARIES, --library=LIBRARIES
                        libraries of this unit
```

Harfbuzz relies on this feature:

https://github.com/harfbuzz/harfbuzz/blob/master/src/Makefile.am#L434-L437

**Comment by esodan** [comment]
generate_gir() already support multiple libraries. GDA requires them, just add your dependency objects to your library, then they are added by generate_gir() automatically to g-ir-scanner using -l switch.

Result of command: https://gitlab.gnome.org/GNOME/libgda/blob/master/libgda/meson.build#L293
is:

/usr/bin/g-ir-scanner -pthread -I/usr/include/gobject-introspection-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include --no-libtool --namespace=Gda --nsversion=6.0 --warn-all --output libgda/Gda-6.0.gir --c-include=libgda/libgda.h -I/home/despinosa/Proyectos/libgda/libgda -I/home/despinosa/Proyectos/libgda/_build/libgda -I./. -I../. -I./libgda/. -I../libgda/. -I./libgda/sqlite/sqlite-src -I../libgda/sqlite/sqlite-src -I./libgda/sqlite -I../libgda/sqlite -I./libgda/sql-parser/. -I../libgda/sql-parser/. --filelist=/home/despinosa/Proyectos/libgda/_build/libgda/libgda@@gda-6.0@sha/Gda_6.0_gir_filelist --include=GLib-2.0 --include=GObject-2.0 --include=Gio-2.0 --include=libxml2-2.0 --identifier-prefix=Gda --cflags-begin -Wall -Wextra -Wformat-security -Wno-address -Wno-unused-variable -Wno-unused-parameter -Wno-pointer-sign -Wno-missing-field-initializers -DGSEAL_ENABLE '-DLIBGDA_ABI_NAME="libgda-5.99"' -I./. -I../. -I./libgda/. -I../libgda/. -I./libgda/sqlite/sqlite-src -I../libgda/sqlite/sqlite-src -I./libgda/sqlite -I../libgda/sqlite -I./libgda/sql-parser/. -I../libgda/sql-parser/. -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -pthread -I/usr/include/libxml2 -I/usr/include/libsoup-2.4 --cflags-end -L/home/despinosa/Proyectos/libgda/_build/libgda -lglib-2.0 -lgobject-2.0 -lgio-2.0 -lgmodule-2.0 -pthread -lxml2 -lsoup-2.4 -ldl --library gda-6.0

So as you can see, -l switches are added automatically.

**Comment by MathieuDuponchelle** [comment]
@esodan , that is unrelated, what's missing is the ability to pass multiple libraries to the `-l` (`--library`) switch. Thanks anyway :)
