### ISSUE TITLE
Empty string in meson being passed as 2 quotes to an external program

### ISSUE THREAD

**Issue by Hi-Angel** [mesonbuild/meson#3692]
## Steps to reproduce:

1. Create `meson.build`:

	```
	project(
	  'foo',
	  'cpp',
	  version: '0.1.0',
	)

	EXTRA_DEBUG_ARGS = (get_option('buildtype') == 'debug')? ['-g3'] : ['']

	executable(
	  'foo',
	  'test.cpp',
	  cpp_args: EXTRA_DEBUG_ARGS,
	  install: false
	)
	```

	…and `test.cpp`:
	```c++
	int main() {}
	```

2. Run `meson release --buildtype release`, and then `ninja -C release`

## Expected:

A successful build.

## Actual:

The `''` is passed as is, resulting in:

```
$ ninja -C release
ninja: Entering directory `release'
[1/2] Compiling C++ object 'foo@exe/test.cpp.o'.
FAILED: foo@exe/test.cpp.o 
c++ -Ifoo@exe -I. -I.. -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -O3 ''  -MD -MQ 'foo@exe/test.cpp.o' -MF 'foo@exe/test.cpp.o.d' -o 'foo@exe/test.cpp.o' -c ../test.cpp
c++: error: : No such file or directory
ninja: build stopped: subcommand failed.
```

## Additional info:

meson version: 0.46.1

**Comment by tp-m** [comment]
I don't think this is a bug, this is working as expected.

You should use an empty array `[]` to represent no arguments.

**Comment by Hi-Angel** [comment]
> You should use an empty array `[]` to represent no arguments.

Thanks for the workaround! Still, it actually is a bug, see: if you pass `['-g3']`, it ends up being just `-g3`. By similar logic, if you pass `['']`, it should end up in nothing. However, even if you put a space, as in `[' ']`, it still being passed as `' '`.

**Comment by nirbheek** [comment]
> By similar logic, if you pass [''], it should end up in nothing.

This logic is flawed. If you want to pass an empty string, we will pass an empty string. This is how everything in the world behaves, including shell:

```shell
$ args=('' '')
$ cat "${args[@]}"
cat: '': No such file or directory
cat: '': No such file or directory
```

**Comment by tp-m** [comment]
Sorry, but that's not how it works, and I think your "by similar logic" is not conclusive. `''` expresses an empty string argument, so if `['-g3']` ends up as just `-g3` then `['']` should clearly end up as an empty argument and not as nothing. Perhaps you're thinking about these things in terms of shell strings, but that's not how it works, and it was designed intentionally to not be like that.

Things are really working as intended here. The `[]` is not a workaround, it's what you're supposed to use.

There is a difference between no argument and an argument that's an empty string. In your case that difference might not be useful, but in other scenarios it might be important to be able to express that.

Argument arrays are flattened, so `[]` will end up as nothing just like `[ [] ]` will end up as nothing or `['-g3', [] ]` will end up as just `-g3`.

**Comment by Hi-Angel** [comment]
Err… Okay, then why can't I pass a space, e.g. `[' ']`?

For the record, it behaves like this in literally every language, including python which your project is using. I can't comment offhand on @nirbheek's example, because I'm historically confused by behavior of different sorts of braces in sh.

**Comment by tp-m** [comment]
I don't understand your question about the space. `''` ends up as an argument with an empty string, and `' '` or `[' ']` will result in an argument that represents a single space. (And the compiler also doesn't like it of course)

**Comment by Hi-Angel** [comment]
As I noted my 1-st comment, passing `[' ']` to meson ends up in `' '`, i.e. not a single space, but a space surrounded by quotes. See:

```$ ninja -C release
ninja: Entering directory `release'
[0/1] Regenerating build files.
The Meson build system
Version: 0.46.1
Source dir: /home/constantine/Projects/meson-test
Build dir: /home/constantine/Projects/meson-test/release
Build type: native build
Project name: foo
Native C++ compiler: c++ (gcc 7.3.1 "c++ (GCC) 7.3.1 20180406")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Build targets in project: 1
Found ninja-1.8.2 at /usr/bin/ninja
[1/2] Compiling C++ object 'foo@exe/test.cpp.o'.
FAILED: foo@exe/test.cpp.o 
c++ -Ifoo@exe -I. -I.. -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -O3 ' '  -MD -MQ 'foo@exe/test.cpp.o' -MF 'foo@exe/test.cpp.o.d' -o 'foo@exe/test.cpp.o' -c ../test.cpp
c++: error:  : No such file or directory
ninja: build stopped: subcommand failed.
```

**Comment by tp-m** [comment]
I think you are misinterpreting the output here. It's just what ninja prints so it's clear that there is an empty argument. It's also needed for the shell command line to denote the argument. The compiler would see an empty string.

I would suggest we handle further questions on IRC.

**Comment by Hi-Angel** [comment]
Ah, I see

> I would suggest we handle further questions on IRC.

I didn't ask anything, it's an information relevant to the report. Can't say I agree with decision on this, but oh, well.

**Comment by nirbheek** [comment]
> Can't say I agree with decision on this, but oh, well.

You should look up how arguments are passed via command-line arguments in shells. For instance, https://docs.python.org/3/library/shlex.html#shlex.quote

You can disagree all you want, but your mental model of how all this works does not agree with reality :)

**Comment by Hi-Angel** [comment]
@nirbheek I took a look at your link, and I know about that. I still don't see what you're getting at.

Do you, perhaps, imply that if you pass an empty string to `quote()` function, it will make it into `''`? It could be the case, but it doesn't make any sense there either.

A usecase for that to not work like this is in the header of the report — just show me the usecase for "the intended behavior" to be what it is now.

**Comment by cdunn2001** [comment]
We have [a related problem](https://github.com/open-source-parsers/jsoncpp/pull/799). Someone recently modified our `meson.build` this way:
* https://github.com/open-source-parsers/jsoncpp/pull/799/commits/2654b6bbbf089bf85d29c9a9ca1283e07cc6fe43

Pretty simple change, right? `cpp_args` is now set to the value of this variable, which should be empty by default. However, **meson** is actually passing `''` to the compiler. **clang++** ignores the empty string, but **g++-4.9** fails on it. Compare the first "g++" jobs in the following TravisCI builds:

* https://travis-ci.org/cdunn2001/jsoncpp/builds/387473945
  * no `''`; g++ passes
* https://travis-ci.org/open-source-parsers/jsoncpp/builds/395927930
  * `''` passed to clang and g++; g++ fails

How do I tell `cpp_args` to substitute *nothing*?

**Comment by NickeZ** [comment]
Set your variable to `[]` and not `''`

**Comment by cdunn2001** [comment]
Thanks. That worked.

That needs to be in either the [Syntax section of the Reference Manual](http://mesonbuild.com/Syntax.html), or in the FAQ.

**Comment by NickeZ** [comment]
I think what is tricking people here is that there is an "ergonomic" feature that strings atomically are turned into lists of one element, i.e. that `''` actually means `['']`. If one always were forced to write out the array brackets it would be clear that `[]` isn't the same as `['']`.
