### ISSUE TITLE
Known issues with the FeatureNew framework

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#3697]
- [x] [FeatureNew prints the same warning twice sometimes](https://github.com/mesonbuild/meson/issues/3660). Fixed in: https://github.com/mesonbuild/meson/pull/3681
- [x] Mention the decorators in `Contributing.md`, fixed in https://github.com/mesonbuild/meson/pull/3823
- [x] [`windows.compile_resources` decorator is broken](https://github.com/mesonbuild/meson/pull/3661#discussion_r192525020). Fixed in: https://github.com/mesonbuild/meson/pull/3681
- [x] [Parent project version is incorrectly used when printing warnings for subprojects](https://github.com/mesonbuild/meson/pull/3661#issuecomment-394190910), fixed in https://github.com/mesonbuild/meson/pull/3823
- [x] [`FeatureNew` usage is always printed in summary, even if no warning is caused](https://github.com/mesonbuild/meson/issues/3660#issuecomment-394974235), fixed in https://github.com/mesonbuild/meson/pull/3681
- [x] Version comparison thinks `0.47` is older than `0.47.0`, fixed in https://github.com/mesonbuild/meson/pull/3681

CC @Salamandar

**Comment by NickeZ** [comment]
> 00:42 < __tim> there's also an issue with the version comparison, if I specify meson version >= 0.47 it will complain about dict use and say that >=0.47.0 is required :)

**Comment by Salamandar** [comment]
> FeatureNew usage is always printed in summary, even if no warning is caused

Potential fix: #3681

> FeatureNew prints the same warning twice sometimes. Potential fix: #3682

#3682 has been merged into #3681

**Comment by Salamandar** [comment]
> Version comparison thinks 0.47 is older than 0.47.0

I found out that the Meson way of comparing versions was buggy (not only the features comparison). It fails if the version arrays are not the same length. I fixed it in #3681 too.

**Comment by Salamandar** [comment]
> Parent project version is incorrectly used when printing warnings for subprojects

More than reproduced. subproject breaks the whole thing.

How can I store thing separately for each project ? I need to store the meson_version, and the list of warnings.

**Comment by nirbheek** [comment]
> Parent project version is incorrectly used when printing warnings for subprojects

I'm working on this. My first approach was to pass the interpreter to `.use()`, but I soon realized that Holder objects will need to have the interpreter, which defeats their purpose since you can't pickle interpreters.

Next, I tried passing the target version to `.use()`, which involved touching a lot of code, but I got it mostly working. Then I realized that while reporting, we also need to know the subproject name so we can print the correct warnings and deprecations.

My next approach will store a dict mapping the subproject name to the target version in that subproject as a replacement for `mesonlib.target_version`. Then I will use the machinery I wrote above to pass the subproject name to all `.use()` calls, and store FeatureNew and FeatureDeprecations keyed by subproject name. Then, when the time comes to report them, I just need to pass the subproject name to `called_features_report()`.

I will implement this tomorrow, so that we can fix this for the release. Otherwise the output is completely useless and confusing when subprojects are involved.

**Comment by nirbheek** [comment]
All fixed now.
