### ISSUE TITLE
Add support for removing files created by custom install scripts to `ninja clean` 

### ISSUE THREAD

**Issue by rhd** [mesonbuild/meson#371]
Hey Jussi,

I have a custom install script which does lame things like creating symlinks and other things inside of the install directory. When you type `ninja clean`, you get something like this:

```
ninja -C build-gcc clean
ninja: Entering directory `build-gcc'
[1/1] 'Cleaning'
FAILED: 'ninja' '-t' 'clean'
ninja: error: remove(install): Directory not empty
Cleaning... 1763 files.
ninja: build stopped: subcommand failed.
```

It's not the greatest user experience - can anything be done to pretty up that error (it's not really an error) but it looks scary.

**Comment by jpakkane** [comment]
Which operation is failing in this case? Is it a plain copy, installing an entire directory or running a custom script?

**Comment by rhd** [comment]
The install doesn't fail. The `clean` fails... or at least prints out an ugly error message.

I have a custom install script that does things like:
```
cp $MESON_SOURCE_ROOT/libs/python/*py                 $MESON_INSTALL_PREFIX/lib/python/.
ln -fs $MESON_INSTALL_PREFIX/lib/python/foo.py $MESON_INSTALL_PREFIX/bin/foo
```

I'm assuming the `clean` isn't keeping track of the things the custom install script is doing and thus, it prints out that ugly message because it can't delete the install directory because there is extra stuff in there.

**Comment by nirbheek** [comment]
We would need to add a keyword argument to `meson.add_install_script()` called `clean:` that takes a list of directories and files inside the builddir that this script could possibly create so we can clean them up before `ninja clean` runs.

**Comment by nirbheek** [comment]
Actually, this is fixed now thanks to https://github.com/mesonbuild/meson/pull/2191. We misdiagnosed the problem at first.
