### ISSUE TITLE
configure_file() called on the same output file multiple times silently overwrites earlier calls

### ISSUE THREAD

**Issue by iainlane** [mesonbuild/meson#3714]
I was trying to make an "override" desktop file, which is a copy of an XDG autostart desktop file in another directory with `Hidden=true` appended. I was attempting to use `configure_file` for this:

```
    configure_file(
      input: join_paths(plugin_name, desktop + '.in'),
      output: desktop,
      configuration: plugins_conf,
      install: true,
      install_dir: gsd_xdg_autostart
    )
    configure_file(
      input: join_paths(plugin_name, desktop + '.in'),
      output: desktop,
      configuration: plugins_conf_hidden,
      install: true,
      install_dir: join_paths(gsd_datadir, 'gnome-session')
    )
```

OK, I understand that meson's design is that this can't work because we always output in the build directory. What actually happened, though, is that the second call overwrote the output from the first one - so both copies got the file with replacements from `plugins_conf_hidden`. My suggestion is that an error would have been nice in this case, to tell me that I'm trying to write to the same file from multiple calls and this isn't allowed.

**Comment by nirbheek** [comment]
We probably can't error out because it might break existing build files, but we should definitely warn.
