### ISSUE TITLE
Project unittest in script language

### ISSUE THREAD

**Issue by vit1251** [mesonbuild/meson#3719]
How to specify in meson.build my unittest write on script language like Python or Lua. Right now I receive console error message:

```
RuntimeError: No specified compiler can handle file test/01_test.py
```
And I specify my test right now:

```python
test_1 = executable('01_test', 'test/01_test.py')

test('Import custom Python module', test_1)
```

**Comment by kernigh** [comment]
Use find_program(), as in `test_1 = find_program('test/01_test.py')`

**Comment by vit1251** [comment]
Thanks.
