### ISSUE TITLE
Includes order: local includes should go first

### ISSUE THREAD

**Issue by tp-m** [mesonbuild/meson#372]
When passing includes to the compiler, includes from dependencies are currently put before the local includes specified via include_directories. I think this is not right, and it should be the other way round. Local includes should always go first. It's the only way to avoid unexpected problems since one has little control over what's installed in the public include paths.

The specific problem at hand is with GStreamer, where headers from multiple source modules get installed under $includedir/gstreamer-1.0/

So we have for example:
$includedir/gstreamer-1.0/gst/gst.h - GStreamer core library header
$includedir/gstreamer-1.0/gst/audio/audio.h - gst-plugins-base audio library header

Now, when building the audio library in gst-plugins-base, it depends on the GStreamer core library.

So what happens is that one of the first includes will be -I$includedir/gstreamer-1.0

The local module includes (-Igst-libs etc.) will be last.

So when the audio library gets compiled, it uses ```#include <gst/audio/audio.h```> or such, and because of the include order it will pick up old headers from a previously installed gst-plugins-base instead of the headers from the local source dir.

There are ways to work around this of course, but I believe there is a general conceptual problem here, and it's something that should be fixed in meson.

The reason it's not come up as a problem so far might be that compilers tend to special-case 'system include' directories, in that they will first try all explicitly specified -I before they try to find stuff in /usr/include, so things will work as expected as long as a standard prefix is used, but that won't work with a custom prefix, for example.

**Comment by jpakkane** [comment]
Can you try the linked MR and see if it works for you?

**Comment by tp-m** [comment]
Thanks for the fast fix, but I am not sure this works right yet. I've made a little demo to test this:

```
$ git clone git://people.freedesktop.org/~tpm/meson-include-test
$ cd meson-include-test
$ mkdir build
$ cd build
$ ~/Devel/meson/meson .. && ninja -v
Cloning into 'meson-include-test'...
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 7 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (7/7), done.
Checking connectivity... done.
The Meson build system
Version: 0.30.0.dev1
Source dir: /tmp/meson-include-test
Build dir: /tmp/meson-include-test/build
Build type: native build
Build machine cpu family: x86_64
Build machine cpu: x86_64
Project name: include-test
Native c compiler: ccache cc (gcc 5.3.1-6)
Found pkg-config: /usr/bin/pkg-config (0.29)
Native dependency gstreamer-1.0 found: YES 1.6.3
Native dependency gstreamer-audio-1.0 found: YES 1.6.3
Build targets in project: 1
[1/2] ccache cc  '-pipe' '-Wall' '-Winvalid-pch' '-g' '-pthread' '-I/usr/include/gstreamer-1.0' '-I/usr/lib/x86_64-linux-gnu/gstreamer-1.0/include' '-I/usr/include/glib-2.0' '-I/usr/lib/x86_64-linux-gnu/glib-2.0/include' '-Iinclude-test@exe' '-I..' '-I.' '-I.' '-I../.' '-MMD' '-MQ' 'include-test@exe/test.c.o' '-MF' 'include-test@exe/test.c.o.d' -o 'include-test@exe/test.c.o' -c ../test.c
FAILED: ccache cc  '-pipe' '-Wall' '-Winvalid-pch' '-g' '-pthread' '-I/usr/include/gstreamer-1.0' '-I/usr/lib/x86_64-linux-gnu/gstreamer-1.0/include' '-I/usr/include/glib-2.0' '-I/usr/lib/x86_64-linux-gnu/glib-2.0/include' '-Iinclude-test@exe' '-I..' '-I.' '-I.' '-I../.' '-MMD' '-MQ' 'include-test@exe/test.c.o' '-MF' 'include-test@exe/test.c.o.d' -o 'include-test@exe/test.c.o' -c ../test.c
../test.c:4:2: error: #error "TEST_ME not defined, wrong header pulled in"
 #error "TEST_ME not defined, wrong header pulled in"
  ^
ninja: build stopped: subcommand failed.
tpm@xps:/tmp/meson-include-test/build$ more ../gst/audio/audio.h 
#define TEST_ME
```

I just checked out your branch in the meson repo, I think that's enough, isn't it?

**Comment by jpakkane** [comment]
My bad, now it should work.

Your meson.build has `required : true` for `dependency()`. You don't need to do that, `true` is the default.

**Comment by tp-m** [comment]
Thanks! Seems to work now, yay:
```
[1/2] ccache cc  '-pipe' '-Wall' '-Winvalid-pch' '-g' '-I.' '-I../.' '-pthread' '-I/usr/include/gstreamer-1.0' '-I/usr/lib/x86_64-linux-gnu/gstreamer-1.0/include' '-I/usr/include/glib-2.0' '-I/usr/lib/x86_64-linux-gnu/glib-2.0/include' '-Iinclude-test@exe' '-I..' '-I.' '-MMD' '-MQ' 'include-test@exe/test.c.o' '-MF' 'include-test@exe/test.c.o.d' -o 'include-test@exe/test.c.o' -c ../test.c
```
Just noticing that there's another ```-I.. -I.``` at the end, is that a default include for the current source/build directory ? If yes, they should probably also go at the front?

**Comment by jpakkane** [comment]
Meson will always put the current source, build and target private directories in the path because that is what everyone in the real world wants to happen.

**Comment by tp-m** [comment]
> Meson will always put the current source, build and target private directories
> in the path because that is what everyone in the real world wants to happen.

Yes, and that's how it should be. I was just wondering whether those should go at the beginning as well, before the dependency includes, rather than at the end.

**Comment by nirbheek** [comment]
They should definitely go in the beginning and not the end otherwise headers from other include paths can override `config.h`. I just had this happen to me, and I only noticed because of a chance build failure. In all other cases it was silently overriding the defaults with incorrect values.

**Comment by tp-m** [comment]
```
17-02-2016 17:49:27 __tim: jpakkane, did you see my last comment in https://github.com/mesonbuild/meson/issues/372 ?
17-02-2016 17:51:24 jpakkane: Yes. Seems sensible. I'll wrestle the outstanding mrs and other stuff first...
```

Could we re-open this then until it's fully fixed? :)
