### ISSUE TITLE
CLFAGS/LDFLAGS ignored for compiler has_function / find_library and other tests

### ISSUE THREAD

**Issue by ePirat** [mesonbuild/meson#3720]
Setting CLFAGS and LDFLAGS in the env are ignored for compiler tests like `has_function` and `find_library`, which can cause misleading results for those, like not finding a library or function during the checks that would be found during "normal" compilation.

**Comment by nirbheek** [comment]
They are not ignored for some compiler checks (see https://github.com/mesonbuild/meson/pull/3582), but yes they are not used consistently.

**Comment by ePirat** [comment]
It seems the exact same problem exists with `add_project_arguments` and `add_project_link_arguments` which is a big problem, as I have something like:

if host_system == 'darwin'
    add_languages('objc')
    add_project_arguments('-mmacosx-version-min=10.10',
        language: ['c', 'cpp', 'objc'])
    add_project_link_arguments('-mmacosx-version-min=10.10',
        language: ['c', 'cpp', 'objc'])
endif

and if those have no effect on the checks, the checks are useless because the results are wrong, as they are not valid for the correct macOS min OS version.

**Comment by jpakkane** [comment]
Maybe we should have a base option for osx version instead. Or does it get too niche?

**Comment by ePirat** [comment]
> Or does it get too niche?

Not sure, then at least one is needed for iOS too.

And it affects other things too, like if you use `-L/something/lib/`, meson still won't find libraries there even though those would be found when using the argument.

**Comment by tp-m** [comment]
I once filed #3301 fwiw but was subsequently persuaded that those flags should indeed be ignored (though the discussion might actually have mostly occurred on IRC, I don't remember).

**Comment by ePirat** [comment]
While I get why this is desired, I have the opinion that this causes more problems than the IMO little benefit of not being order-dependent with regard to adding arguments for compiler/linker… As with the situation how it currently is, meson tests basically a different "environment" different from what later will be used to compile/link, which is nearly guaranteed to cause problems.

For `meson.build` defined arguments (using `add_project_arguments()` or `add_project_link_arguments()`) it might be possible to not add them and force people to explicitly add required args with the `args` kwarg on the checks itself, even though this is not really a nice solution IMO.

For "global" `CFLAGS`, `LDFLAGS` and similar env variables and cross-file `c_args`, `c_link_args`, etc., I see no way how meson could ignore those for the checks but use them while compiling and not end up unexpectedly failing in some cases because of mismatches of detection vs. reality.

Even worse, in case of `-mmacosx-version-min` everything will compile just fine, you get only a warning that most users will probably ignore, when using a too new function that would have failed to be detected using the correct macOS min version, and the resulting binary will run on the OS you compiled on, but crash on older OS versions.

**Comment by nirbheek** [comment]
> Even worse, in case of -mmacosx-version-min everything will compile just fine, you get only a warning that most users will probably ignore, when using a too new function that would have failed to be detected using the correct macOS min version, and the resulting binary will run on the OS you compiled on, but crash on older OS versions.

Yeah, the same issue is also there for targetting specific Android NDK and Windows SDK versions.

**Comment by jpakkane** [comment]
The simple (but not final) fix for this is to use `c_args`, `c_link_args` et al in configuration checks. The this can at least be made to work by passing the `-mmacosx-version-min` from the outside with `CPPFLAGS`.

**Comment by jpakkane** [comment]
#3916 is for this.

**Comment by ePirat** [comment]
Seems to work fine, except for #4272.
