### ISSUE TITLE
If CFLAGS/... is set explicitly, skip meson's defaults

### ISSUE THREAD

**Issue by andreygursky** [mesonbuild/meson#3723]
A common way to set custom warnings/debug/optimization options is to define CFLAGS/CXXFLAGS/LDFLAGS/... environment variables. In this case meson should skip setting its defaults (like '-Wall', '-g', '-O0', '-O2'). Otherwise these flags appear twice and lead to confusion needlessly.

In a Makefile it is done with '?=' like:
```
CFLAGS?=-Werror -g -O2
```

**Comment by jpakkane** [comment]
This is already achievable by setting the `buildtype` option to `plain`. [This is even documented on the web site](http://mesonbuild.com/Quick-guide.html#using-meson-as-a-distro-packager).

**Comment by andreygursky** [comment]
I'd say this issue still persists. Meson will not skip its defaults unless additionally a special option is set.

Another issue, why I could not use ```plain``` is because a project (particularly GTK) depending on ```buildtype``` sets project specific defines (not compiler flags). That's why it is important to only skip mesons default compiler flags.

**Comment by nirbheek** [comment]
> CFLAGS?=-Werror -g -O2

This simplistic example may make it seem like it's possible, but in reality there's a lot of build options that meson adds automatically based on user options, or the compiler being used, linker, etc. 

> Another issue, why I could not use plain is because a project (particularly GTK) depending on buildtype sets project specific defines (not compiler flags). That's why it is important to only skip mesons default compiler flags.

When you use `plain`, you are expected to handle all that yourself too. `plain` means "I want full control over what this".

**Comment by andreygursky** [comment]
> This simplistic example may make it seem like it's possible, but in reality there's a lot of build options that meson adds automatically based on user options, or the compiler being used, linker, etc.

Sure, some flags might be essential to build a project. But there are classic optional flags I've mentioned that are checked for overriding at the very beginning.

> When you use plain, you are expected to handle all that yourself too. plain means "I want full control over what this".

I think compiler flags and defines should be treated differently and there should be separate control over them. While defines are mostly specific and less likely needed to be overridden, compiler flags are subject to override more often.
