### ISSUE TITLE
macOS static linker doesn't support archives that are only aggregates of other static archives

### ISSUE THREAD

**Issue by justinjoy** [mesonbuild/meson#3735]
I found this bug while building libnice on Mac OSX.

```
[1/67] Linking static target nice/libnice.a.
FAILED: nice/libnice.a
rm -f nice/libnice.a && ar csr nice/libnice.a
ar: no archive members specified
usage:  ar -d [-TLsv] archive file ...
	ar -m [-TLsv] archive file ...
	ar -m [-abiTLsv] position archive file ...
	ar -p [-TLsv] archive [file ...]
	ar -q [-cTLsv] archive file ...
	ar -r [-cuTLsv] archive file ...
	ar -r [-abciuTLsv] position archive file ...
	ar -t [-TLsv] archive [file ...]
	ar -x [-ouTLsv] archive [file ...]
```

Actually, `ar` on Mac OSX seems not to support generating a static library without arguments.
How can I fix or avoid this problem?

```
 $ ar csr libfoo.a
ar: no archive members specified
usage:  ar -d [-TLsv] archive file ...
	ar -m [-TLsv] archive file ...
	ar -m [-abiTLsv] position archive file ...
	ar -p [-TLsv] archive [file ...]
	ar -q [-cTLsv] archive file ...
	ar -r [-cuTLsv] archive file ...
	ar -r [-abciuTLsv] position archive file ...
	ar -t [-TLsv] archive [file ...]
	ar -x [-ouTLsv] archive [file ...]
```

**Comment by tp-m** [comment]
Probably/hopefully https://github.com/centricular/libnice

**Comment by xclaesse** [comment]
Oh that's an interesting one:

```meson
libnice = both_libraries('nice',
  link_whole: [libagent, libsocket, libstun, librandom],
  version : libversion,
  soversion : soversion,
  install: true)
```

Side note, shouldn't you use `library()` and let user decide if he wants both using `-Ddefault_library=both` ?

So indeed there is no sources for that target, it's only made of static libraries... definitely didn't thought about that case when implemented `both_libraries()`.

**Comment by tp-m** [comment]
Yes, I think you're right and it should just use `library()`

**Comment by xclaesse** [comment]
Probably `static_library()` would fail the same way on MacOSX, it shouldn't make a difference if we are building both or just static. Can you confirm this?

**Comment by tp-m** [comment]
It's not really a fix, as it will still fail if static libs are also requested, but it might be defaulting to shared only now :)

**Comment by xclaesse** [comment]
This has been fixed already.
