### ISSUE TITLE
Phantom include_directories error

### ISSUE THREAD

**Issue by RomanHargrave** [mesonbuild/meson#3756]
I am working on a PR for a project built with meson (disks86/VK9), and am encountering a strange problem.
I have done some troubleshooting, but am feeling quite under the weather, so forgive me if i've missed something.

The gist of the problem is that attempting to run the meson build results in this error:  `VK9-Library/meson.build:46:0: ERROR:  Include directory to be added is not an include directory object.`

This is quite remarkable, as upon examining the suspect build file, the directive on line 46 is free of any `include_directory` information:

```meson
# Line 46 (below)
d3d9_dll = shared_library('d3d9', d3d9_src,
  name_prefix         : '',
  link_with           : [ ],
  dependencies        : [ boost_dep, vulkan_dep, eigen_dep ],
  cpp_args            : [ vulkan_defs, '-DSCHAEFERGLLIBRARY_EXPORTS' ],
  cpp_pch             : ['pch/stdafx.h', 'pch/stdafx.cpp'],
  install             : true,
  vs_module_defs      : 'd3d9.def',
  override_options    : ['cpp_std='+vk9_cpp_std])
#Line 56 (below)
d3d9_dep = declare_dependency(
  link_with           : [ d3d9_dll ],
  include_directories : [ include_directories('.') ])
```

The nearest such property or directive is part of the directive on line 56, and removing it does not solve the problem. All that removing it has achieved is a file free of any `include_directories` statements that is causing meson to to exit claiming quite the opposite.

Although this may potentially be project specific, I am opening this issue _here_ as if it is a problem caused by another file in the build structure, the problem is still being misdiagnosed _by meson_.

**Comment by jpakkane** [comment]
It's hard to say without having access to your entire build definition but most likely one of your dependencies (`boost_dep`, `vulkan_dep`, or `eigen_dep`) is malformed somehow. Either someone has used `declare_dependency` and given it incorrect `include_directories` object or, if they come from the system, we have a bug in the detector logic.

We should check for the former but it's possible there is a bug. Maybe an  `include_directories : 'foobar')` has slipped through (it should be `include_directories : include_directories('foobar')`.

**Comment by RomanHargrave** [comment]
I'll look in to. The project is public, but I have added a bit to the build tree (building in local copies of boost components). So it's quite possibly that. 

I'll check my definitions, I have an idea of which one it is. I do thing it's a rather cryptic error in this case, though.

**Comment by RomanHargrave** [comment]
Yes, it was in fact a statement in another file that was causing the issue. I suppose I'll close as invalid, but I am curious if there is a preexisting issue for the somewhat misleading error description.

**Comment by jpakkane** [comment]
Creating a broken dependency object should not be possible. If you can find out how it happened, please file a bug with details so we can fix it.
