### ISSUE TITLE
Can't i18n.merge the same output filename even in different directories

### ISSUE THREAD

**Issue by iainlane** [mesonbuild/meson#3759]
This is similar to https://github.com/mesonbuild/meson/issues/3714 but with a quirk. I'm trying to use i18n.merge in two different directories (the workaround from #3714) to create the same filename, installed to different destinations.

This errors with `data/wayland-session/meson.build:6:5: ERROR:  Tried to create target "gnome.desktop_merge", but a target of that name already exists.`

So it seems like meson has generated the same target name. Perhaps the path should be encoded in there somehow to get around this.

(I suppose as a workaround I can pick a different output filename and rename using a `meson_post_install` script.)

**Comment by eli-schwartz** [comment]
A duplicate issue was opened for this, and then it got fixed in #4076

This is no longer a problem.
