### ISSUE TITLE
How to show available tests? mesonintrospect?

### ISSUE THREAD

**Issue by rhd** [mesonbuild/meson#376]
Hi Jussi,

I was curious about what one of my tests was called and I remember somewhere about `mesonintrospect` - so I ran `mesonintrospect build-gcc --tests` and was presented with an unformatted blob. Is `mesonintrospect` meant to be used by humans? Or IDEs only? Is there another way to show the available tests?

**Comment by jpakkane** [comment]
Introspect is for IDE integration only. At the moment there is no other way to show available tests.
