### ISSUE TITLE
environment().append does not append

### ISSUE THREAD

**Issue by lazka** [mesonbuild/meson#3761]
Maybe I'm missing something. I expected the example to print `BAR:QUUX`, but I get only `QUUX`

```python
project('test', 'c', 'cpp',
  version : '1.0',
  meson_version : '>= 0.46.1',
)

env = environment()
env.append('FOO', 'BAR')
env.append('FOO', 'QUUX')

test('test', find_program('python3'), args: ['-c', 'import os; assert 0, os.environ["FOO"]'], env: env)
```

**Comment by nirbheek** [comment]
Hum, I can make a case for both the existing behaviour and the one you're expecting. The main argument I have in favour of the one you're expecting is that it's cross-platform compatible because we will use the correct `os.pathsep` automatically.

**Comment by lazka** [comment]
Assuming the current behavior is correct, what is the difference to environment.set() then?

**Comment by QuLogic** [comment]
@nirbheek Append is how it's [supposed to work](https://github.com/mesonbuild/meson/pull/781#issuecomment-246518210), no? Though maybe it needs the separator?

@lazka Or are you explicitly asking for not having to specify the separator?

**Comment by nirbheek** [comment]
> Append is how it's supposed to work, no?

That's not how it's documented, we should recommend that yes.

`.append()` and all other methods replace the previous value, so we should document that too.
