### ISSUE TITLE
Race in running and removing of compiler test executables on Windows

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#378]
There seems to be a race in running the executable for a compiler test and then removing it. I get the following backtrace once every 3-4 runs:

[has_header-race.txt](https://github.com/mesonbuild/meson/files/114931/has_header-race.txt)

Presumably this is only a problem on Windows because of the differing file locking semantics.

**Comment by jpakkane** [comment]
Do you have anti virus software running? They scan files immediately upon creation and keep them open for too long. That could be causing your issue.

**Comment by nirbheek** [comment]
The only AV I have running is the default Windows Defender.
