### ISSUE TITLE
Some Wl flags with 2 or more arguments don't work

### ISSUE THREAD

**Issue by jsapparts** [mesonbuild/meson#379]
**Work**
> '-Wl,--allow-multiple-definition',

**Don't Work**
> '-Wl,-static -lmysqlclient',

```
/usr/bin/i686-w64-mingw32-ld: unrecognized -a option `tic -lmysqlclient'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

**Comment by jpakkane** [comment]
Based on ld's man page your format is incorrect. Here's the relevant sample code from `man ld`:

    -Wl,--push-state,--as-needed

In you case the flag should probably be

    -Wl,--static -Wl,-lmysqliclient

or
    -Wl,--static,-lmysqlclient

Where are you getting these link arguments? Are you writing them manually or do they come from some external source?

**Comment by jsapparts** [comment]
This is from many questions in the internet.
[Like This](http://fixunix.com/linux/6335-how-link-some-libs-static-some-shared-one-app.html)
```
gcc foo.o -o foo -Wl,-static -lbaz -lkaz -Wl,-Bdynamic -lkaz
links in libbar libkaz(and system libraries such as libc) dynamic,
while libbaz and libkaz are linked statically.
```

I try to use the commands that you pass and ..
`-Wl,--static,-lmysqlclient`
.. appears to work but my build is broken because of 'undefined reference' so 
I can't say that works 100% but the LD don't point any errors like syntax error on flag or non-existent flag. 

But if you look more at my error log in the first post you can see that meson pass to the LD the flag
`'tic -lmysqlclient'`
.. this is a part of the full link that make the error
`'-Wl,-static -lmysqlclient',`
so, looks like meson is passing wrong argument because maybe a wrong parse of the linker flags

**Comment by jpakkane** [comment]
Please post the Meson build definition snippet you user for this and the full output (including the command it runs) below.

**Comment by rhd** [comment]
Something like this should work.

`link_args = ['-Wl,-static', '-lbaz', '-lkaz', '-Wl,-Bdynamic', '-lkaz'],`

**Comment by jsapparts** [comment]
in the linkers I use this
```
# Linker Arguments and options
all_args_lnk = [
'-lws2_32',
'-lwsock32',
'-lboost_system',
'-Wl,--allow-multiple-definition',
'-Wl,-static',
'-lmysqlclient'
]
```

and the executable 
```
# Executable final
finalexe = executable('Erathorn Server', files, include_directories : [incdir], dependencies : all_dep, cpp_args : all_args, link_args : all_args_lnk)
```

Now trying what RHD says it seems to work.
the final lines of build command:
`Erathorn Server@exe/src_ban.cpp.obj' 'Erathorn Server@exe/src_actions.cpp.obj' '-lws2_32' '-lwsock32' '-lboost_system' '-Wl,--allow-multiple-definition' '-Wl,-static' '-lmysqlclient' '-L/usr/i686-w64-mingw32/lib' '-L/usr/local/lib' '-llua' '-lm' '-L/usr/local/lib' '-lgmp' '-L/usr/local/lib' '-lmysqlclient' `

It really looks the right way to do this. I gonna close because I found what I wanted. thanks for the help
