### ISSUE TITLE
Should  'threads' dependency define _REENTRANT ?

### ISSUE THREAD

**Issue by xclaesse** [mesonbuild/meson#3810]
I noticed that GLib when built with autotools for Solaris and MacOSX adds -D_REENTRANT in CFLAGS. I don't know if that's still needed nowadays or if it's there only for historical reasons. Should meson add that compiler flag?

Opening this issue here in the hope someone in the Meson community knows better those platforms than me.

**Comment by nirbheek** [comment]
From what I can make out, gcc and clang automatically set `-D_REENTRANT` on the platforms that need it, if you pass `-pthread`. 

The Sun compiler might require setting `-D_REENTRANT` manually, but that compiler is not supported with Meson yet and the FOSS fork of Solaris (OpenIndiana) has already moved to GCC.

**Comment by pwithnall** [comment]
OK, that’s good enough for me. If OpenIndiana is using gcc now, that simplifies things.

From my point of view, this issue can be closed (I have no interest in the Sun Studio Compiler/Oracle Developer Studio being supported). I guess the reason for keeping it open would be to remember to check this if SSC does become supported at some point in the future.

**Comment by xclaesse** [comment]
Fine with me, thanks for the confirmation.
