### ISSUE TITLE
build_always: false does not match the 0.46.1 behaviour

### ISSUE THREAD

**Issue by Akaricchi** [mesonbuild/meson#3815]
Specifying `build_always: false` and `build_by_default: true` on the same target seems to suppress the later. Targets declared as such are therefore never built unless something depends on them (but if you are using `build_by_default`, then chances are nothing does). ~~I suspect it also affects `build_always_stale: true` in the same way, but I have not tested that yet.~~ 

`build_always` must have lower priority than the other two for compatibility with older Meson releases. In addition, please don't be too trigger happy with deprecation warnings. As it stands, it is impossible to avoid the warning in meson git without also breaking compatibility with every current stable release, even if this bug is fixed.

**Comment by nirbheek** [comment]
Make sense to fix this. Thanks for reporting it!

> As it stands, it is impossible to avoid the warning in meson git without also breaking compatibility with every current stable release, even if this bug is fixed.

This is a problem that we are aware of and have some ideas to fix it, but at least for now deprecation warnings are not fatal ;)
