### ISSUE TITLE
0.47.0 attempts to compile find_library dependency with incorrect arguments

### ISSUE THREAD

**Issue by nathanaelg** [mesonbuild/meson#3832]
In one of my projects I am using `find_library` to find a pre-compiled static library. Since 0.47, meson seems to be attempting to compile and link a `testfile.cpp` with the library that it is finding. 

This doesn't seem particularly sane because unsurprisingly it doesn't link, both because it doesn't have compatible compiler arguments (in my case the static library uses hard floating point so you get lots of `[library] uses VFP register arguments, /tmp/tmpjjtvpdqe/output.exe does not`), but it also just doesn't have a bunch of symbols that it would need to link because it was never designed to be linked with some arbitrary test file...

Possibly related to this? https://github.com/mesonbuild/meson/commit/af546b52ca0281a595f4395425905c68ff0d21c2

**Comment by nirbheek** [comment]
@nathanaelg can you try the patch from https://github.com/mesonbuild/meson/pull/3833 and see if it helps?

**Comment by nathanaelg** [comment]
Thanks for the quick response! Yes, that branch seems to work fine.
