### ISSUE TITLE
gnome.generate_gir(): need ability to set environment variables when calling g-ir-scanner

### ISSUE THREAD

**Issue by tp-m** [mesonbuild/meson#384]
I need to set some environment variables so that when g-ir-scanner calls gst_init() no GStreamer plugins from the install prefix (or anywhere really) get loaded, amongst other things.

**Comment by jpakkane** [comment]
Unfortunately there is no reliable cross tool way of setting environment variables. This needs to be implemented somehow by having a wrapper script that sets the environment transparently (many Meson features do the same behind the scenes).

The question then is whether we should make it possible to add a custom wrapper to this command or a create a syntax for setting envvars and then do that transparently. The latter can be said to be more user friendly but the former gives more freedom for people to do other crazy customisation as well and we might need to provide it at some point anyway.

**Comment by tp-m** [comment]
I guess the answer is both then? :)

I would always prioritise user-friendliness. It's one of the main selling points of meson IMHO. (But then I would say that, wouldn't I)

**Comment by tp-m** [comment]
I don't think this is something that only GStreamer will want/or need btw.

**Comment by nirbheek** [comment]
https://github.com/mesonbuild/meson/pull/494 sets up the infrastructure that will be required to implement this.
