### ISSUE TITLE
meson install and VisualStudio backend

### ISSUE THREAD

**Issue by pelijah** [mesonbuild/meson#3841]
There is no `meson-private/install.dat` for VS backend.

**Comment by nirbheek** [comment]
Please describe your issue in more detail. What are you trying to do, what do you expect, and what actually happens?

**Comment by pelijah** [comment]
I want to install VS project via `meson install` like it does `ninja install`. But meson returns error `Install data not found. Run this command in build directory root.` because `install.dat` isn't generated for VS projects.

**Comment by nirbheek** [comment]
@jpakkane This is a new bug in 0.47 because `meson install` didn't exist before.

**Comment by nirbheek** [comment]
This is not a regression, but for the stable release we should give a proper error message when someone tries to run `meson install` on Visual Studio. We can fix it properly for the next release.

**Comment by nirbheek** [comment]
[0.47.1](https://github.com/mesonbuild/meson/milestone/27) is due soon, punted to [0.47.2](https://github.com/mesonbuild/meson/milestone/29)

**Comment by riverar** [comment]
@nirbheek Did this ever ship? Still slated to release?
