### ISSUE TITLE
ERROR: Unknown CPU family 'mipsel'

### ISSUE THREAD

**Issue by nickersk** [mesonbuild/meson#3842]
configure produces error on mipsel cpu family

**Comment by nirbheek** [comment]
Please paste the complete meson log with details about your system: `uname -a` and `cat /proc/cpuinfo`.

**Comment by nickersk** [comment]
crosscompiling for mipsel under openembedded. i think this patch http://git.openembedded.org/openembedded-core/commit/?id=be194a459944dfcc41bae7315643a5d284683efc is causing the issue, so probably this is wrong place to report this bug...

**Comment by nirbheek** [comment]
@rossburton you upgraded the warning to an error, but forgot to change the URL to report the error ;)

@nickersk please provide the details I asked, because we need to add that to the known architectures list anyway

**Comment by nickersk** [comment]
Linux vusolose 3.13.5 #1 SMP Wed Nov 22 11:42:13 CET 2017 mips GNU/Linux

system type             : BCM7429B0 STB platform
machine                 : Unknown
processor               : 0
cpu model               : Broadcom BMIPS5000 V1.1  FPU V0.1
BogoMIPS                : 864.25
cpu MHz                 : 1305.085
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 64
extra interrupt vector  : yes
hardware watchpoint     : no
isa                     : mips1 mips2 mips32r1
ASEs implemented        :
shadow register sets    : 1
kscratch registers      : 0
core                    : 0
VCED exceptions         : not available
VCEI exceptions         : not available

processor               : 1
cpu model               : Broadcom BMIPS5000 V1.1  FPU V0.1
BogoMIPS                : 655.36
cpu MHz                 : 1305.085
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 64
extra interrupt vector  : yes
hardware watchpoint     : no
isa                     : mips1 mips2 mips32r1
ASEs implemented        :
shadow register sets    : 1
kscratch registers      : 0
core                    : 0
VCED exceptions         : not available
VCEI exceptions         : not available

**Comment by nirbheek** [comment]
Could you also paste the output of:

`python3 -c "import platform; print(platform.machine())"`

**Comment by nickersk** [comment]
mips

**Comment by nirbheek** [comment]
Yes but why is the value different in the two cases? Is a different python used while building?

**Comment by nickersk** [comment]
it builds 2.7.15 and 3.5.5 for native sdk

**Comment by nickersk** [comment]
i think we can close this issue, because it is openembedded related. Thank you :-)

**Comment by rossburton** [comment]
Yes, sorry, I need to change the message to report a bug to OE.

Nicker, you can test a change for this yourself.  Open
meta/classes/meson.bbclass and add another case to the meson_cpu_family()
function:

if arch == "mipsel":
    return "mips"

That should map the name back to something that Meson is happy with.

Ross

**Comment by nirbheek** [comment]
So I guess we should map `le` and `be` archs to one arch, and people should use `build_machine.endian()` to find out the endianness? This needs to be fixed in Meson anyway, so I'm reopening this.

**Comment by nickersk** [comment]
Sounds OK to me.

**Comment by rossburton** [comment]
Not entirely convinced that mapping mipsel in environment is the right move, as I believe 'mipsel' is coming from the OE cross file (which uses GCC triples as a source, with exceptions as required).

The important question is does CPU family include endian or not?  If not then environment should map ppc64le to ppc64 as it appears those are the values that platform.machine() returns.

Next, what does platform.machine() return on little and big endian MIPS hosts.  I've got some builds going now to find this out.

We can fix up the cross file generation to turn mipsel to mips as required, but Meson itself should be working purely on what platform returns.

**Comment by rossburton** [comment]
Default (big-endian) MIPS:

>>> platform.machine()
'mips'
root@bob:~# uname -a
Linux bob 4.14.48-yocto-standard #1 SMP PREEMPT Fri Jul 6 13:27:14 UTC 2018 mips GNU/Linux

mipsel building now.

**Comment by rossburton** [comment]
With little-endian MIPS:
```
>>> sys.byteorder
'little'
>>> platform.machine()
'mips'

Linux bob 4.14.48-yocto-standard #1 SMP PREEMPT Fri Jul 6 13:57:07 UTC 2018 mips GNU/Linux
```

So yes, Meson should document that 'mips' is all MIPS machines and we'll map mipsel to mips.

**Comment by rossburton** [comment]
Of course it does that for MIPS already.  Presumably the same logic should be applied to ppc?

**Comment by rossburton** [comment]
@nickersk FYI there are patches on the oe-core list to add the mipsel->mips mapping

**Comment by nickersk** [comment]
GJ guys. Thank you all once again.

**Comment by jpakkane** [comment]
This should be fixed now.
