### ISSUE TITLE
Running `meson` in the source dir without any arguments takes the parent directory as the build dir

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#3857]
This is a major regression over 0.46. The parent dir implicit selection should only be for finding the source directory, not the build directory.

**Comment by nirbheek** [comment]
This is likely because of https://github.com/mesonbuild/meson/pull/3612 by @xclaesse 

```python
p.add_argument('builddir', nargs='?', default='..')
p.add_argument('sourcedir', nargs='?', default='.')
```
These default values are wrong. These are the cases:

1. `meson` from inside the builddir where `..` is the sourcedir
2. `meson builddir` from the sourcedir
3. `meson builddir srcdir` from an arbitrary location
4. `meson srcdir builddir` from an arbitrary location

**Comment by xclaesse** [comment]
IMHO those checks should go in validate_core_dirs(), but it's not a big deal. That fix fixing this regression.

**Comment by nirbheek** [comment]
> IMHO those checks should go in validate_core_dirs(), but it's not a big deal. That fix fixing this regression.

Yeah, this seemed like a quick fix for the regression. We should fix it cleanly in master though, will you be submitting a patch for it?
