### ISSUE TITLE
Regression in gdbus-codegen

### ISSUE THREAD

**Issue by inigomartinez** [mesonbuild/meson#3870]
Since 0.47, `docbook` generation using gnome's `gdbus-codegen` fails with the following error:

`ERROR:  Output must not contain a path segment`

This used to work in 0.45 and 0.46 versions. To test this, [`gnome-online-account`'s meson port](https://gitlab.gnome.org/inigomartinez/gnome-online-accounts.git) can be used.

**Comment by nirbheek** [comment]
How strange, there isn't even a `/`:

```meson
dbus = 'goa-generated'

dbus_sources = gnome.gdbus_codegen(
  dbus,
  sources: dbus_ifaces,
  interface_prefix: 'org.gnome.OnlineAccounts.',
  namespace: goa_ns,
  object_manager: true,
  docbook: dbus + '-doc',
  install_header: true,
  install_dir: join_paths(goa_pkgincludedir, goa_name)
)
```

We'll look into this and fix it for 0.47.2
