### ISSUE TITLE
Add a way to disable subproject using the new `feature` options

### ISSUE THREAD

**Issue by thiblahute** [mesonbuild/meson#3880]
In `gst-build` in particular it would be very useful to be able to pass a `feature` option to `subproject()` so that it is taken into account and failure in `auto` case is ignored.

Also in the case where we have a disabled `subproject('subproject')` then if another subproject tries to `dependency('subproject', fallback: ['subproject', 'dep'])` it sould fail (or if `required: auto` it should just ignore the dep).

**Comment by nirbheek** [comment]
Currently, `subproject()` calls are unconditional, and can't fail. In the case of `dependency()`, we return a not-found dependency, but I'm not sure how that would work for `subproject()`.

**Comment by thiblahute** [comment]
> Currently, subproject() calls are unconditional, and can't fail. In the case of dependency(), we return a not-found dependency, but I'm not sure how that would work for subproject().

I know and that is what this issue is about, allowing to have conditionnal subproject, not failing if a dependency is not found and the subproject is "auto" fail if it is "enabled" and do not run the subproject at all if it is "disabled".

**Comment by tp-m** [comment]
That would be neat, yes.

**Comment by nirbheek** [comment]
The main issue is that the usage of `dependency()` is very straightforward, but with `subproject()` you run `get_variable()` to fetch arbitrary variables that we don't know the type of. For instance, it can be a list of sources.

The current workaround I've been using everywhere is: `dependency('', fallback ['foo', 'foo_dep'], required: false)`. Maybe that can work for gst-build?

**Comment by thiblahute** [comment]
> The main issue is that the usage of dependency() is very straightforward, but with subproject() you run get_variable() to fetch arbitrary variables that we don't know the type of. For instance, it can be a list of sources.

I am not sure I understand what you mean,  we are already able to handle that for dependency fallbacks, how is it different for `subproject()`? Basically a `subproject` object that was not built will not be usable and we need to add a method to check its status, like `.found()` for dependencies.

**Comment by nirbheek** [comment]
> Basically a subproject object that was not built will not be usable and we need to add a method to check its status, like .found() for dependencies.

Hmm, I see, we *can* add `subproject(required: false)` and then you need to check the return value before trying to use it. We can't change the `required: true` behaviour though, because that breaks existing build files.

**Comment by thiblahute** [comment]
> Basically a subproject object that was not built will not be usable and we
> need to add a method to check its status, like .found() for dependencies.
>
> Hmm, I see, we *can* add subproject(required: false) and then you need to
> check the return value before trying to use it. We can't change the required:
> true behaviour though, because that breaks existing build files.
>

There is now `required` arg in `subproject` yet is there?

**Comment by nirbheek** [comment]
> There is now `required` arg in `subproject` yet is there?

No, but the default will continue to be `required: true`, unless we want to treat that differently than not-specified.

**Comment by thiblahute** [comment]
Sure, yes, default has to be `required: true` for backward compat.
