### ISSUE TITLE
Versioned .so* symlinks still created with 'default_library=static` 

### ISSUE THREAD

**Issue by haaspors** [mesonbuild/meson#3888]
I'm using `library()` and have set `'default_library=both'` in `default_options`. So when I compile for my system it generates both shared library and static library as expected. However, for a particular cross file I have, it sets `default_library='static'` as the system it compiles for doesn't support shared libraries.

Still I'm seeing <libXX.so.*> symlinks generated in build output.
Only tested using `meson 0.47.1` btw.

Please let me know if I'm using `default_library` correctly? Is there another way of specifying that the host system doesn't support and therefor shouldn't generate shared libraries/modules?

**Comment by haaspors** [comment]
Hmm, seems like I'm wrong, it is generating the shared library as well.

**Comment by haaspors** [comment]
How do I use `library()` and control whether it is creating a shared or static library based on `host system`?

**Comment by jpakkane** [comment]
You don't. The type is defined by the value of `default_library` option which you can toggle.

To get the behaviour you want, you'd probably want to use the `build_target` command instead.
