### ISSUE TITLE
quadmath is used unconditionally, even if not available

### ISSUE THREAD

**Issue by xnox** [mesonbuild/meson#3896]
```
class GnuFortranCompiler(GnuCompiler, FortranCompiler):

    def language_stdlib_only_link_flags(self):
        return ['-lgfortran', '-lm', '-lquadmath']
```

However quadmath is not available on all architectures. On ubuntu, it is shipped for i686, x86_64 and ppc64el. But not other arches. Thus somehow, detection should be executed here and quadmath returned, only if available.

**Comment by jpakkane** [comment]
I don't know how that could be checked but if someone does, please file a MR.

**Comment by xnox** [comment]
So far I have identified that quadmath is available on intel (x86_64 and i*86) and ppc64el. However, it's not used/not-needed on ppc64el for fortran. It seems like we can simply hardcode to use -lquadmath on intel platforms only. Another way, is to inspect what libgfortran shared library is linked too... but that too might be fragile.

My crude patch, that I uploaded into ubuntu is:
```
--- meson-0.47.1.orig/mesonbuild/compilers/fortran.py
+++ meson-0.47.1/mesonbuild/compilers/fortran.py
@@ -20,6 +20,7 @@ from .compilers import (
     ElbrusCompiler,
     IntelCompiler,
 )
+import platform
 
 class FortranCompiler(Compiler):
     library_dirs_cache = CCompiler.library_dirs_cache
@@ -226,7 +227,10 @@ class GnuFortranCompiler(GnuCompiler, Fo
         return ['-J' + path]
 
     def language_stdlib_only_link_flags(self):
-        return ['-lgfortran', '-lm', '-lquadmath']
+        if platform.machine().lower() in ['x86_64', 'i686']:
+            return ['-lgfortran', '-lm', '-lquadmath']
+        else:
+            return ['-lgfortran', '-lm']
 
 
 class ElbrusFortranCompiler(GnuFortranCompiler, ElbrusCompiler):
```

Mostly because I have failed to use `detect_cpu` as it appears to be impossible to use that from inside a compiler class.

**Comment by scivision** [comment]
perhaps this can be closed, as `lquadmath` is not anywhere in Meson code anymore.
