### ISSUE TITLE
Symlinks can't be copied by install_subdir() since 0.47.0

### ISSUE THREAD

**Issue by didrocks** [mesonbuild/meson#3914]
If you have a dangling symlink (the symlink is referencing a path that is coming from another package on the system, so only resolved once installed on the system), in a directory, `install_subdir` is now reporting a stacktrace since the minstall.py rewrite (worked fine with 0.46, failing since 0.47.0 and still on 0.47.1).

For instance, you have:
`data/ubuntu-wayland/applications/gnome-initial-setup.desktop -> ../../ubuntu/applications/gnome-initial-setup.desktop` (only resolved on the installed system)

meson.build has:
```install_subdir('data/ubuntu-wayland', install_dir: datadir)``` with datadir built as a package, so a destdir/prefix combo.

When building:
```
Installing subdir /home/didrocks/work/build-area/ubuntu-settings-18.04.6/data/ubuntu-wayland to /home/didrocks/work/build-area/ubuntu-settings-18.04.6/debian/tmp/usr/share/ubuntu-wayland
Traceback (most recent call last):
  File "/usr/bin/meson", line 29, in <module>
    sys.exit(mesonmain.main())
  File "/usr/lib/python3.6/dist-packages/mesonbuild/mesonmain.py", line 367, in main
    return run(sys.argv[1:], launcher)
  File "/usr/lib/python3.6/dist-packages/mesonbuild/mesonmain.py", line 281, in run
    return minstall.run(remaining_args)
  File "/usr/lib/python3.6/dist-packages/mesonbuild/minstall.py", line 466, in run
    installer.do_install(datafilename)
  File "/usr/lib/python3.6/dist-packages/mesonbuild/minstall.py", line 297, in do_install
    self.install_subdirs(d) # Must be first, because it needs to delete the old subtree.
  File "/usr/lib/python3.6/dist-packages/mesonbuild/minstall.py", line 318, in install_subdirs
    self.do_copydir(d, src_dir, full_dst_dir, exclude, mode)
  File "/usr/lib/python3.6/dist-packages/mesonbuild/minstall.py", line 281, in do_copydir
    self.do_copyfile(abs_src, abs_dst)
  File "/usr/lib/python3.6/dist-packages/mesonbuild/minstall.py", line 196, in do_copyfile
    '{!r}'.format(from_file))
RuntimeError: Tried to install something that isn't a file:'/home/didrocks/work/build-area/ubuntu-settings-18.04.6/data/ubuntu-wayland/applications/gnome-initial-setup.desktop'
```
Shouldn't we either have a `copy_symlink()` or `copy_file()` be extended to support symlinks? (I see the code has a `# FIXME: what about symlinks?` as well ;))

**Comment by nirbheek** [comment]
This is a regression and will be fixed for 0.47.2.

**Comment by nirbheek** [comment]
@didrocks can you try the patch in https://github.com/mesonbuild/meson/pull/4014?

**Comment by 3v1n0** [comment]
Unforunately, this is not closed in the case where an install_umask is set, as happens with this test.

```python

def test_install_subdir_symlinks_with_default_umask(self):
    '''
    Test that installation of broken symlinks works fine.
    https://github.com/mesonbuild/meson/issues/3914
    '''
    testdir = os.path.join(self.common_test_dir, '199 install_mode')
    subdir = os.path.join(testdir, 'sub1')
    curdir = os.getcwd()
    os.chdir(subdir)
    # Can't distribute broken symlinks in the source tree because it breaks
    # the creation of zipapps. Create it dynamically and run the test by
    # hand.
    src = '../../nonexistent.txt'
    os.symlink(src, 'invalid-symlink.txt')
    try:
        self.init(testdir)
        self.build()
        self.install()
        link = os.path.join(self.installdir, 'usr', 'share', 'sub1', 'invalid-symlink.txt')
        self.assertTrue(os.path.islink(link), msg=link)
        self.assertEqual(src, os.readlink(link))
        self.assertFalse(os.path.isfile(link), msg=link)
    finally:
        os.remove(os.path.join(subdir, 'invalid-symlink.txt'))
        os.chdir(curdir)
```

**Comment by xnox** [comment]
@didrocks these fixes broke systemd installations!

**Comment by 3v1n0** [comment]
@didrocks, @xnox nope, my change didn't break anything related to this (and in fact wasn't reverted) as it was just related to permissions/ownership of symlinks. The original fix for this (which @nirbheek did) was causing the systemd issue.
However, I agree the problem there was the systemd assumption and not meson change itself.

**Comment by xnox** [comment]
@didrocks @3v1n0 btw, i uploaded the fixed up patch to cosmic. Could you please double-check that whatever was affected for you two, is still working correctly in cosmic? (the thing that prompted upload of the first batch of cherrypicks)

**Comment by nirbheek** [comment]
Note that this change broke systemd's optional installed tests, not systemd itself.

**Comment by Hi-Angel** [comment]
This seems to have regressed again. On meson 0.59.1 trying to install a subdir with symlinks results in:

```
Warning: trying to copy a symlink that points to a file. This will copy the file,
but this will be changed in a future version of Meson to copy the symlink as is. Please update your
build definitions so that it will not break when the change happens.
```

…and then instead of copying the symlink it copies the file.
