### ISSUE TITLE
Append custom library path

### ISSUE THREAD

**Issue by MatthewScholefield** [mesonbuild/meson#3926]
I'm writing a meson build file for a C++ game with a custom toolchain (using a meson cross spec file) that has its own `lib` directory. Because of this, `dependency('xyz')` doesn't find anything. Is there a way to add a custom library path (that would add `-L/path/to/toolchain/lib` to the compiler options)

Right now as a workaround I'm doing:

```meson
compiler = meson.get_compiler('cpp')
devkitpro_dir = '/opt/devkitpro'

deps = []
foreach libname : ['dswifi9', 'mm9', 'filesystem', 'fat', 'nds9']
    deps += [compiler.find_library(libname, dirs : [devkitpro_dir + '/libnds/lib'])]
endforeach
```

**Comment by nirbheek** [comment]
`dependency()` will never find arbitrary libraries, it is only for pkg-config and for special-cased projects which have config tools or need special handling to find the location of the libraries and headers (such as qt and boost).

The 'workaround' you are using is the preferred way to find arbitrary libraries that don't have pkg-config files.

To support custom locations for the library, you'd want `devkitpro_dir` be an `option()` in `meson_options.txt`, see: http://mesonbuild.com/Build-options.html and set the default as `/opt/devkitpro` if unspecified, and if it isn't found, print a custom message that says which option to change.

**Comment by MatthewScholefield** [comment]
Okay, thanks. It just doesn't feel consistent that `dependency()` supports nont-pkg-config libraries like `/usr/lib/xyz.a` but not `/opt/foo/lib/xyz.a`.

**Comment by MatthewScholefield** [comment]
Nevermind, you're right, I didn't even realize there was a pkg-config for all the libraries I've used in the past xD. I would just look in `/usr/lib` to find it and it would just work.

**Comment by RoyiAvital** [comment]
When using Clang on Windows folders are easy to locate using the location of the Compiler.
Any way extracting the path of the binary of the compiler?
