### ISSUE TITLE
rpath order of two subprojects is not deterministic

### ISSUE THREAD

**Issue by espindola** [mesonbuild/meson#3928]
This is related to issue #3922.
In the attached testcase meson sometimes uses

'-Wl,-rpath,$$ORIGIN/subprojects/sub1:$$ORIGIN/subprojects/sub2'

and sometimes

'-Wl,-rpath,$$ORIGIN/subprojects/sub2:$$ORIGIN/subprojects/sub1'

[meson-test.zip](https://github.com/mesonbuild/meson/files/2217864/meson-test.zip)

**Comment by nirbheek** [comment]
This is likely because we use a `set()` in `mesonbuild/backend/backends.py:determine_rpath_dirs()` could you open a PR that fixes that with a test? Maybe add it to https://github.com/mesonbuild/meson/pull/3927?

**Comment by espindola** [comment]
I will probably have a pr for it tomorrow.
