### ISSUE TITLE
New dependency type: libintl

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#3929]
The functions provided by libintl can be either a compiler built-in (on Linux and macOS) or provided by an external library (on Windows). GLib does this:

```meson
if cc.has_function('ngettext')
  libintl = []
else
  libintl = cc.find_library('intl', required : false)
  if not libintl.found()
    libintl = subproject('proxy-libintl').get_variable('intl_dep')
  endif
endif
```

This simplifies to:

```meson
if cc.has_function('ngettext')
  libintl = []
else
  libintl = cc.find_library('intl')
endif
```

There is no way to specify a 'found dependency with no arguments' in build files, so this complicates the logic quite a bit since you can't call `libintl.found()` without first checking the type. Having a special dependency type would solve this.

There are probably more edge-cases ([glib-gettext.m4](https://gitlab.gnome.org/GNOME/glib/blob/4e1488eebb2129c6e39162b56275d311f24216ab/m4macros/glib-gettext.m4)), and we can slowly grow those in Meson as needed.

**Comment by xclaesse** [comment]
> There is no way to specify a 'found dependency with no arguments' in build files

This seems to be working:
```meson
dep = declare_dependency()
assert(dep.found(), 'not found')
```

**Comment by nirbheek** [comment]
You can't use internal deps in compiler checks, which is done by, f.ex., gtk:

```meson
libintl_dep = cc.find_library('intl', required : false)
if cc.has_function('bind_textdomain_codeset', dependencies: libintl_dep)
  cdata.set('HAVE_BIND_TEXTDOMAIN_CODESET', 1)
endif
```

**Comment by xclaesse** [comment]
I don't know why you can't, but that sounds like a bug we should fix. Right?

**Comment by nirbheek** [comment]
You can't run compiler checks against internal dependencies because they don't exist yet at configure time, since internal dependencies are only for build targets.

**Comment by ePirat** [comment]
> You can't use internal deps in compiler checks

Can you clarify this? What is a "internal" dependency? The snippet you posted is something I do in VLC (but with the math library instead of intl) and it seems to work fine?

**Comment by nirbheek** [comment]
> What is a "internal" dependency?

See `internal` at https://mesonbuild.com/Reference-manual.html#dependency-object

> The snippet you posted is something I do in VLC (but with the math library instead of intl) and it seems to work fine?

Yes, it will work fine since the dependency type is `library` (or `pkgconfig`), but it won't work if the type is `internal`.

**Comment by eli-schwartz** [comment]
I guess `dependency('', required: false)` would work though, right?

...

Looking at [gettext.m4](https://github.com/autotools-mirror/gettext/blob/ec0e6b307456ceab352669ae6bccca9702108753/gettext-runtime/m4/gettext.m4#L81-L96), it seems to want to do magical checks for libiconv at the same time, with the comment: "Sometimes libintl requires libiconv, so first search for libiconv.". Also, "Sometimes, on Mac OS X, libintl requires linking with CoreFoundation."

**Comment by eli-schwartz** [comment]
I have a PR to implement this.

> There are probably more edge-cases ([glib-gettext.m4](https://gitlab.gnome.org/GNOME/glib/blob/4e1488eebb2129c6e39162b56275d311f24216ab/m4macros/glib-gettext.m4)), and we can slowly grow those in Meson as needed.

Haven't really taken a look at fancy cases, but I'd be happy to start growing them in meson right now if anyone has suggestions before that^^ is merged.

**Comment by xclaesse** [comment]
> There is no way to specify a 'found dependency with no arguments' in build files

That's not true (anymore?), `declare_dependency()` works.

**Comment by xclaesse** [comment]
> Haven't really taken a look at fancy cases

I think that can be ignored, that was written when porting glib from autotools to meson years ago, and nobody complained so far. Must be edge cases for toolchains from 1980.

**Comment by eli-schwartz** [comment]
Yeah, I am more interested in edge cases people can trigger on their (current) systems by trying to build code with this PR, rather than "porting" gettext.m4 to meson.
