### ISSUE TITLE
Meson does not add objects from not-installed static libraries while creating static libraries

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#3937]
Projects often have internal (not-installed) static libraries which are linked into the installed library (f.ex., `libcharset.a`, `libgnulib.a`, and `libpcre.a` into `libglib-2.0`). These static libraries are always correctly linked into the shared library, but not into the static library, because Meson assumes that all static libraries that we `link_with:` are available after installation, and must be linked via the pkg-config file.

However, the aforementioned libraries must *NOT* be `link_whole:` because when you're doing a shared link, you don't want all the objects from them, only those that are actually used.

Solution: add the objects from not-installed static library that a static library links with.

This is also what autotools does: it tracks `noinst_LTLIBRARIES` and transparently adds the objects from libraries in `LIBADD` when generating a static librari.

**Comment by nirbheek** [comment]
Actually, it's worse, even objects from `link_whole:` static libraries don't get added.

**Comment by nirbheek** [comment]
As a crutch for this bug, we had another bad behaviour: we were always transitively adding static libraries when linking to a static library, even with `link_whole:`. This actually hid the fact that our built static libraries were unusable because executables using that static library would work just fine.

As a side-effect of this, we were also incorrectly adding internal static library dependencies of shared libraries while linking to shared libraries.

**Comment by ernestask** [comment]
As a side note, https://github.com/swaywm/wlroots seems to be affected as well when built with `-Ddefault_library=static`. An eight-byte file only is generated in the end.

**Comment by xclaesse** [comment]
Should be fixed by https://github.com/mesonbuild/meson/pull/5936
