### ISSUE TITLE
Default value of UserFeatureOption is `enabled` instead of `auto`

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#3938]
According to `meson --help`:

```
  --auto-features {enabled,disabled,auto}
                        Override value of all 'auto' features (default: auto).
```

However, in reality the default value is `enabled`. We should fix it to be `auto`.

**Comment by xclaesse** [comment]
Weird, it's set to "auto" by default in the code `'auto_features':   [UserFeatureOption, "Override value of all 'auto' features.", 'auto'],`.

**Comment by nirbheek** [comment]
It might be that the default value for `UserFeatureOption` is `enabled` instead of `auto` (when unspecified).

**Comment by xclaesse** [comment]
You're right:
```python
    return coredata.UserFeatureOption(name,
                                      description,
                                      kwargs.get('value', 'enabled'),
                                      yielding=kwargs.get('yield', coredata.default_yielding))
```
