### ISSUE TITLE
Meson scripts are unusable on Windows

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#394]
The following files need to end in .py on Windows to be usable:

> mesonconf
> mesongui
> mesonintrospect
> meson

Windows only recognizes scripts that end in one of the file extensions listed in %PATHEXT%. `meson.py` in %PATH% with `.py` in %PATHEXT% allows you to run `meson` from the command line.

**Comment by jpakkane** [comment]
If you rename these files to have .py extension then setuptools helpfully copies the files to their suffixless form, too, which is exactly the opposite of what you want for Debian packaging.

**Comment by aleb** [comment]
You should also update the documentation to reflect this change.

Maybe also the manual pages? Now I have to run "man meson" which seems inconsistent because the script is "meson.py"

**Comment by jpakkane** [comment]
It is the job of the distro packager to make sure Meson is runnable as plain `meson`. This is what the Debian packaging does, for example. Having the executable called `meson.py` is silly, because end users don't care (and should not even know) that it is implemented in Python.

**Comment by thiblahute** [comment]
> It is the job of the distro packager to make sure Meson is runnable as plain meson

So installing with pip install should lead to meson being usable as is right?

**Comment by jpakkane** [comment]
When you do an install with setuptools, it renames `foo.py` scripts to plain `foo`. But only sometimes. On some platforms. When the moon is in the proper orientation.

I am completely fed up with how entirely screwed this entire thing is and am not going to work on it. But if someone submits a patch that makes it work on all platforms out of the box, it will be merged immediately with my sincerest thanks.

**Comment by thiblahute** [comment]
This is how you distribute meson, and I think it is worth making sure it works for anyone just using pip or setup.py install, otherwise it is just plain broken.

**Comment by jpakkane** [comment]
It does work, you just have to call `meson.py` instead of `meson`. The readme has been updated with a clarification on this.

**Comment by thiblahute** [comment]
Right, that was an over statement and I understand your point, I just think it is weird and it mean scripts need to take care of that etc... I think it is a bit annoying.

**Comment by zpgaal** [comment]
On windows an optional solution is to add a meson.bat that forwards all argument to the python. Ive added neson to the path and It works fine. Except for the regeneration as it is trying to execute through invoking python itself

For nix* the shebang should work fine.

**Comment by aleb** [comment]
Now some distributions have `meson` (debian, fedora) because they prefer not to change things and others have `meson.py` (archlinux) because "Many files in /usr/bin end in .sh, why should we care about .py. Plus `setup.py install` installs *.py. If you think it is wrong then work with upstream on their installation script to rename binaries during *nix installation".

This inconsistency affects the meson users who now have to check whether `meson.py` or `meson` is available, since upstream does not have a recommendation for distributors.

Is it reasonable to change setup.py to rename the binaries and remove ".py" on *nix?
