### ISSUE TITLE
Compiling non-standard cpp file extension

### ISSUE THREAD

**Issue by aacirino** [mesonbuild/meson#3957]
I am working on a legacy Make-based project with lots of TinyC .tcc files that I don't want to change the extension in order not to mess with the Make project, but I surely want to complete the migration to Meson. These files are regular cpp source code that can be compiled with clang or gcc, I don't need to rely on TinyC.

Having an option to add aliases to file extensions or adding file extensions to a compiler would help a lot. Without such an option I am trying with a generator like this:

`crypto_gen = generator(find_program('cat'),
                        output : ['@BASENAME@_tcc.cpp'],
                        arguments : ['@INPUT@'],
                        capture : true)`

But, despite the generated file being a _fac simile_ copy of the original the compiler is given duplicate contents, for instance:

`src/crypto/src@crypto@@libbitcoin_crypto@sta/equihash_tcc.cpp:11:6: error: redefinition of 'DistinctIndices'
bool DistinctIndices(const FullStepRow<WIDTH>& a, const FullStepRow<WIDTH>& b, size_t len, size_t lenIndices)
     ^
/Users/aacirino/git/Zero/build/../src/crypto/equihash.tcc:11:6: note: previous definition is here
bool DistinctIndices(const FullStepRow<WIDTH>& a, const FullStepRow<WIDTH>& b, size_t len, size_t lenIndices)`

Meson seems to be compiling both the input and the output files.

How should I use the generator to create a compilable copy of the original file?

**Comment by jpakkane** [comment]
Can you post the full build definition file somewhere for review?

**Comment by aacirino** [comment]
This is the simplest case for the meson build I am trying to create:

`
crypto_src = [  'equihash.cpp',
                'hmac_sha256.cpp',
                'hmac_sha512.cpp',
                'ripemd160.cpp',
                'sha1.cpp',
                'sha256.cpp',
                'sha512.cpp' ]

crypto_gen = generator(find_program('cat'),
                        output : ['@BASENAME@_tcc.cpp'],
                        arguments : ['@INPUT@'],
                        capture : true)

crypto_static_lib = static_library('libbitcoin_crypto',
 sources : [crypto_src, crypto_gen.process(['equihash.tcc'])],
  cpp_pch : 'pch/crypto_pch.hpp',
  include_directories : [ zero_inc_dirs ],
  cpp_args : '-DENABLE_MINING')
`

It has only one .tcc file. The `equihash_tcc.cpp` file is correctly created in the build directory and seems to be compiled twice.

**Comment by tp-m** [comment]
> `static_library('libbitcoin_crypto', ..)`  

Unrelated, but this should probably be `static_library('bitcoin_crypto', ..)`  without the `lib` prefix.

**Comment by aacirino** [comment]
I know, but the original make file uses this naming.

**Comment by nirbheek** [comment]
If you want to rename source files with an arbitrary extension into something meson can understand, you can do:

```meson
bad_src = [  'equihash.tcc' ]
fixed_src = []
foreach s : bad_src
  fixed_src += configure_file(s, s + '.cpp', copy : true)
endforeach

crypto_static_lib = static_library('libbitcoin_crypto',
 sources : crypto_src + fixed_src,
  cpp_pch : 'pch/crypto_pch.hpp',
  include_directories : [ zero_inc_dirs ],
  cpp_args : '-DENABLE_MINING')
```

> I know, but the original make file uses this naming.

The original `Makefile` outputs `liblibbitcoin_crypto.a`?

**Comment by aacirino** [comment]
Never mind, I found the origin of the compilation duplicates and fixed it. Deep in a header file there was an include for the .tcc file.

Using a generator as I originally intended solved my problem of compiling the non-standard file extensions. Thanks a lot for your patience and help.
