### ISSUE TITLE
Since fd11dbcc, Meson incorrectly detects "c:" as a valid absolute path

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#397]
`os.path.isabs('c:')` returns False because that is not an absolute path. `c:\` on the other hand is an absolute path.

For legacy reasons, the Windows convention is that string `c:somedir` (which is what you get with `os.path.join('c:', 'somedir')`) checks for the existence of that directory in the current directory if the current directory is on drive `c:`, and checks for that on the root of the drive `c:` if the current directory is on a different drive.

This causes `ninja install` to install everything inside the build directory by default (if it is on `c:` drive) because the prefix is interpreted as a relative directory.

So the correct fix for commit fd11dbcc is to change the default prefix to be `c:\`. Accepting `c:` as a valid absolute prefix is incorrect.

**Comment by jpakkane** [comment]
`C:\` is the default prefix. This bug is caused by a patch earlier that strips path separators at the end of prefix (because on Unix you don't want those). I'll need to fix that to not strip it in this case.

**Comment by nirbheek** [comment]
Thanks :)

I think at the same time the following change also needs to be reverted? Since os.path.isabs is actually sufficient as a check?

```
--- a/mesonbuild/coredata.py
+++ b/mesonbuild/coredata.py
@@ -61,8 +61,10 @@ class UserStringOption(UserOption):
     def validate(self, value):
         if not isinstance(value, str):
             raise MesonException('Value "%s" for string option "%s" is not a string.' % (str(newvalue), self.name))
-        if self.name == 'prefix' and not os.path.isabs(value):
-            raise MesonException('Prefix option value \'{0}\' must be an absolute path.'.format(value))
+        if self.name == 'prefix':
+            if not os.path.isabs(value):
+                if len(value) >= 2 and value[1] != ':':
+                    raise MesonException('Prefix option value \'{0}\' must be an absolute path.'.format(value))
         if self.name in ('libdir', 'bindir', 'includedir', 'datadir', 'mandir', 'localedir') \
             and os.path.isabs(value):
             raise MesonException('Option %s must not be an absolute path.' % self.name)
```

**Comment by jpakkane** [comment]
Yes.

**Comment by nirbheek** [comment]
Cool, thanks!
