### ISSUE TITLE
Documentation does not mention version required for check_header

### ISSUE THREAD

**Issue by onkarshinde** [mesonbuild/meson#3974]
While attempting to convert my application from autotools to meson I was trying to compiler.check_header. I got following error on meson 0.45.
src/meson.build:35:9: ERROR: Unknown method "check_header" in object.

After reading through release notes I realised that check_header has been added in version 0.47. But this is not mentioned in the documentation of compiler object.
http://mesonbuild.com/Reference-manual.html#compiler-object

**Comment by nirbheek** [comment]
Would you like to provide a pull request for this? You can edit the
documentation online and it will automatically create a pull request for
you.
