### ISSUE TITLE
mesonconf: default to cwd

### ISSUE THREAD

**Issue by rhd** [mesonbuild/meson#400]
Hi Jussi,

mesonconf doesn't print out anything when run without any args... it's confusing. Here is a quick fix that seems to do the thing that I would expect.

```diff
diff --git a/mesonbuild/mconf.py b/mesonbuild/mconf.py
index f174425..a3e2e7e 100644
--- a/mesonbuild/mconf.py
+++ b/mesonbuild/mconf.py
@@ -182,7 +182,7 @@ class Conf:
 def run(args):
     args = mesonlib.expand_arguments(args)
     if not args:
-        sys.exit(1)
+        args.append(os.getcwd())
     options = parser.parse_args(args)
     if len(options.directory) > 1:
         print('%s <build directory>' % args[0])
```

**Comment by jpakkane** [comment]
What do you mean by "doesn't print out anything"? When you run Meson without any arguments it prints out the following:

    ./meson <source directory> <build directory>
    If you omit either directory, the current directory is substituted.
    Run ./meson --help for more information.

**Comment by rhd** [comment]
`mesonconf` not `meson`.
