### ISSUE TITLE
RFE: an string .replace method

### ISSUE THREAD

**Issue by keszybz** [mesonbuild/meson#4007]
Sometimes it is necessary to perform arbitrary substitutions. Allowing something like `s.replace("a", "b")` would be nice. It is already possible to do `"b".join(s.split("a"))`, but that's cumbersome.

**Comment by KingDuckZ** [comment]
I just found this issue while looking for how to do just this. In case it's helpful, I came across [this](https://mesonbuild.com/Syntax.html#replace) in the documentation:

```
.replace()
Since 0.58.0, you can replace a substring from a string.
```

so it sounds like this is solved.
