### ISSUE TITLE
CFLAGS environment triggers DEPRECATION warning

### ISSUE THREAD

**Issue by dvdhrm** [mesonbuild/meson#4021]
Hey

Running `meson` (0.47.1) with custom `CFLAGS` set in the environment can easily trigger two new DEPRECATION warnings:

```
DEPRECATION: Duplicated values in array option "c_args" is deprecated. This will become a hard error in the future.
DEPRECATION: Duplicated values in array option "c_link_args" is deprecated. This will become a hard error in the future.
```

Meson complains about duplicates in its own `c_args`, but it is common practice in distributions to have duplicates in `CFLAGS`. This can be easily triggered via:

`CFLAGS="-g -g" meson ..`

..in any C-project using meson.

This bug-report is supposed to be a hint in case you really intend to make this a hard-error. Many build-environments append CFLAGS via something like `CFLAGS="${CFLAGS} ${MY_CFLAGS}"`. All these are in risk of failing when this becomes a hard-error. A google search for the warning-strings shows up many CI reports that trigger this exact issue.

If you are fully aware of this issue, please feel free to close this report. I couldn't find any discussion of this, though.

Thanks
David

**Comment by xclaesse** [comment]
I think we should just remove the deprecation warning, why is it a problem to have duplicates in UserArrayOption ? At least when used as c_args it should be accepted.

**Comment by nirbheek** [comment]
Sounds fine to me, I was under the impression that you added that deprecation, so if you say we should remove it I'm all for it :)

**Comment by xclaesse** [comment]
I refactored that code, but the warning was already there. What I also changed is that c_args is now using UserArrayOption and it was not using that before, that's why we started getting that warning. But that's unintentional.

**Comment by xclaesse** [comment]
For the record, the warning was added in UserArrayOption in PR #2799. Maybe we should skip the warning only when UserArrayOption is used for c_args and friends? I think there could be legitimate use-cases for dups in CFLAGS (e.g. `-Wl,--start-group`).

**Comment by nirbheek** [comment]
Ah, my bad then. Let's special-case and only warn for options that were declared in `meson_options.txt`? Is there a way for us to detect that at the warning location?
