### ISSUE TITLE
Cannot create shared libraries from D sources on OSX (and macOS)

### ISSUE THREAD

**Issue by russel** [mesonbuild/meson#4025]
Using the `library` function in a 'meson.build' to create a shared library on Debian Sid and Fedora Rawhide works fine. For example:
```
tinyendian_lib = library(
    meson.project_name(),
    [tinyendian_src],
    include_directories: [src_dir],
    version: meson.project_version(),
    pic: true,
    install: true,
)
```
correctly builds the '.so' file and it all installs fine. However on OSX (I am on El Capitan) and I assume macOS, the option `-L-soname` is passed to the 'ldc2' command line, and whilst this works for Linux, it does not work for OSX:
```
  FAILED: libtinyendian.0.dylib 
ldc2  -of libtinyendian.0.dylib 'tinyendian@sha/source_tinyendian.d.o' -shared -relocation-model=pic -L-soname -Llibtinyendian.dylib.0  
ld: unknown option: -soname
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: /usr/bin/gcc failed with status: 1
```
I believe this to be an error in the D tooling for Meson.

**Comment by GoaLitiuM** [comment]
Can you confirm if the #4031 fixes this? I don't have any access to mac machines, so I can't confirm if the fix works, but I mirrored the changes based on how the ``-soname`` is handled on other compilers, so it shouldn't be far off.

**Comment by nirbheek** [comment]
A good way to test whether the fix works would be to add the ldc toolchain to Travis CI and ensure that the D tests run on macOS. Homebrew is available, so that seems like the obvious choice to add the toolchain.

**Comment by russel** [comment]
I am not able to check on the El Capitan OSX machine till Sunday, sorry.

**Comment by russel** [comment]
I fetched goalitium/d-soname and rebuilt the project on my El Capitan machine and:
```
|> ninja
[0/1] Regenerating build files.
The Meson build system
Version: 0.48.0.dev1
Source dir: /home/users/russel/Repositories/Git/Forks/TinyEndian
Build dir: /Users/russel/BuildArea/TinyEndian
Build type: native build
Project name: tinyendian
Project version: 0.2.0
Native D compiler: ldc2 (llvm 1.11.0 "LDC - the LLVM D compiler (1.11.0git-16f3746):")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Build targets in project: 1
Found ninja-1.8.2 at /usr/local/bin/ninja
[2/2] Linking target libtinyendian.0.dylib.
FAILED: libtinyendian.0.dylib 
ldc2  -of libtinyendian.0.dylib 'tinyendian@sha/source_tinyendian.d.o' -shared -relocation-model=pic -install_name @rpath/libtinyendian.0.dylib  
ldc2: Unknown command line argument '-install_name'.  Try: 'ldc2 -help'
ldc2: Did you mean '-soname'?
ninja: build stopped: subcommand failed.
```

**Comment by GoaLitiuM** [comment]
I forgot to pass the translated argument to linker. Pull from the same branch again and see what changes.

**Comment by GoaLitiuM** [comment]
Ugh, I made a typo... Can you try and change the following line in mesonbuild/compilers/d.py
```
elif arg.startswith('-install-name'):
```
to:
```
elif arg.startswith('-install_name'):
```

**Comment by russel** [comment]
Apologies for not responding to this, I can check things end of next week.
