### ISSUE TITLE
Meson strips rpaths set via pkgconfig on install

### ISSUE THREAD

**Issue by dankegel** [mesonbuild/meson#4027]
If a .pc file specifies -Wl,-rpath, it probably has a good reason to.
Thus it is surprising that meson strips those rpaths on install.
The workaround suggested by https://github.com/mesonbuild/meson/issues/1411
is awkward as it requires knowing what rpath the library needed.
[Edit: and it requires editing the meson config, which is awkward when
you're just trying to package, say, gstreamer to install to /opt/foo.
What's the point of meson's --prefix option if it forbids rpaths pointing into that prefix?]

Since rpath in .pc files are frowned upon in linux distributions, this is likely to only
affect third-party software that installs libraries to /opt.

If meson is making a policy statement that .pc files must not contain rpath options, it should say so clearly, and possibly abort when such .pc files are encountered

**Comment by barcharcraz** [comment]
This issue affects SWI Prolog from Fedora 28 main repositories.

**Comment by nirbheek** [comment]
Instead of stripping all RPATHs set, we could strip only the values that point to the builddir and sourcedir. I have no objections to this, since all other build systems seem to allow it, but it requires @jpakkane's approval.

**Comment by michaelkuhn** [comment]
Meson's rpath stripping also impacts Spack (see spack/spack#10463). Spack sets rpaths for all dependencies on purpose but Meson removes them all on install. It would be nice to be able to tell Meson to leave the rpaths alone.

**Comment by dankegel** [comment]
There are a large number of related issues, e.g.
https://github.com/mesonbuild/meson/issues/2567

A really nice one that led to a fix for a similar issue on MacOS is
https://github.com/mesonbuild/meson/issues/3077

The original bug about rpath appears to be
https://github.com/mesonbuild/meson/issues/314
which was closed after fixing some build rpath issues, but not the install rpath issues.

**Comment by dankegel** [comment]
The workaround I'm trying now is:
- disable rpath stripping by patching meson, https://raw.githubusercontent.com/MontaVista-OpenSourceTechnology/poky/f705787a07f1043d9143516cb3b9775fd758107d/meta/recipes-devtools/meson/meson/disable-rpath-handling.patch
- set LDPATH when building gstreamer

e.g. in my debian/rules, I have
```
DEB_HOST_MULTIARCH ?= $(shell dpkg-architecture -qDEB_HOST_MULTIARCH)
LDFLAGS:=-Wl,-rpath,$(PREFIX)/lib/$(DEB_HOST_MULTIARCH),-rpath,$(PREFIX)/lib
export LDFLAGS
```

Finners crossed.

**Comment by dankegel** [comment]
Turns out I really do also need to inject an rpath into the .pc file as I mentioned earlier, so on Linux I'm also trying:
```
--- gstreamer-1.16.0/pkgconfig/gstreamer.pc.in.old      2019-04-25 11:29:08.385748960 -0700
+++ gstreamer-1.16.0/pkgconfig/gstreamer.pc.in  2019-04-25 11:30:09.201693902 -0700
@@ -14,5 +14,5 @@
 Version: @VERSION@
 Requires: glib-2.0, gobject-2.0
 Requires.private: gmodule-no-export-2.0 @UNWIND_REQUIRE@ @DW_REQUIRE@
-Libs: -L${libdir} -lgstreamer-@GST_API_VERSION@
+Libs: -L${libdir} -lgstreamer-@GST_API_VERSION@ -Wl,-rpath,${libdir}
 Cflags: -I${includedir}
```

**Comment by dankegel** [comment]
None of my workarounds really do the job, so I enabled the test case in question and started scratching my head :-)
https://github.com/dankegel/meson/commits/bug4027-enable-test-case

**Comment by dankegel** [comment]
Had a moment to write a clean test for this use case; it's the top commit in https://github.com/dankegel/meson/commits/bug4027-add-testcase

**Comment by dankegel** [comment]
Now released, https://mesonbuild.com/Release-notes-for-0-55-0.html
