### ISSUE TITLE
meson should deduplicate munged C[XX]FLAGS/CPPFLAGS flags

### ISSUE THREAD

**Issue by mqudsi** [mesonbuild/meson#4039]
Meson has new detection for duplicated compiler arguments, but meson itself can trigger this when it applies both CPPFLAGS and CXXFLAGS/CFLAGS to the argument list.

```
mqudsi@ZBook /m/c/U/m/g/w/libtorrent> meson build
The Meson build system
Version: 0.47.1
Source dir: /mnt/c/Users/mqudsi/git/wintorrent/libtorrent
Build dir: /mnt/c/Users/mqudsi/git/wintorrent/libtorrent/build
Build type: native build
Project name: libtorrent
Project version: undefined
Appending CFLAGS from environment: '-march=native'
Appending CPPFLAGS from environment: '-march=native'
DEPRECATION: Duplicated values in array option "c_args" is deprecated. This will become a hard error in the future.
Native C compiler: scc (clang 7.0.0-svn337258 "clang version 7.0.0-svn337258-1~exp1+0~20180717095246.642~1.gbp8ac377 (trunk)")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Build targets in project: 0
Found ninja-1.8.2 at /usr/bin/ninja
```

I have the same values in both `CFLAGS` and `CPPFLAGS` because some build scripts do not respect one or the other. Since meson automatically merges these (and it has nothing to do with the contents of the build file) I think the right thing to do here is to drop duplicates without an error or warning when it results from the merging of these environment variables.

**Comment by xclaesse** [comment]
Looks like dup of #4021
