### ISSUE TITLE
Unable to install on Debian 9

### ISSUE THREAD

**Issue by TerrenceHenry** [mesonbuild/meson#4045]
I have tried installing meson as below, but with no success.
What am I doing wrong?

pip3 install --user meson
Collecting meson
  Downloading https://files.pythonhosted.org/packages/f6/3f/4cc08fcfb1f6615279a3fbdf48720c77eeed8427aef37d28830f35548427/meson-0.47.1.tar.gz (1.3MB)
    100% |████████████████████████████████| 1.3MB 278kB/s 
Building wheels for collected packages: meson
  Running setup.py bdist_wheel for meson ... done
  Stored in directory: /home/terrence/.cache/pip/wheels/0c/a4/ed/dee8695203572a0eec19c23336014eaffdfda6a22705078ca8
Successfully built meson
Installing collected packages: meson
Successfully installed meson-0.47.1
terrence@debian:~/Downloads$ meson --version
bash: meson: command not found

**Comment by nirbheek** [comment]
Do you have [`~/.local/bin` in `PATH`](https://mesonbuild.com/Getting-meson.html#installing-meson-with-pip)?

**Comment by TerrenceHenry** [comment]
This is the result of echo path
echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games

Is that correct?
