### ISSUE TITLE
Running project tests fails due to wrong line endings in generated text files

### ISSUE THREAD

**Issue by GoaLitiuM** [mesonbuild/meson#4046]
Running run_project_tests.py after #4026 results to this on Windows:
```
File .\meson-test-run.txt contains DOS line ending on line 1. Only unix-style line endings are permitted.
```

I propose all the .txt files in root folder should be ignored for this check, and all the unnecessary logging files (like meson-test-run.txt) should change their file extensions from .txt to .log so everyone knows these files are not important and can be safely deleted.

**Comment by jpakkane** [comment]
> I propose all the .txt files in root folder should be ignored for this check

What is the reason for this? There should not be any stray files in the root dir.

**Comment by nirbheek** [comment]
My guess is that a manually-run builddir exists in the `test cases/` directory and that's getting scanned by `run_project_tests.py`. We may want to skip that check on files that are not known by git.

**Comment by nirbheek** [comment]
Alternatively, we may want to run that check only on the CI.

**Comment by GoaLitiuM** [comment]
I find it odd that common file types like .txt that many people use for adding notes or storing other hand typed information are treated like they are special files under the meson root directory, when they are only so in the test cases directory. And for logging purposes, naming the files with .log extension is very widely accepted practice to denote these files have no other purpose other than being used for diagnostics, where .txt is used for things like readmes and notes.
