### ISSUE TITLE
Documentation forbids a working behaviour

### ISSUE THREAD

**Issue by Salamandar** [mesonbuild/meson#4065]
Documentation says about `custom_target`:

> @INPUT@ the full path to the input passed to input. If more than one input is specified, all of them will be substituted as separate arguments only if the command uses '@INPUT@' as a standalone-argument. For instance, this would not work: command : ['cp', './@INPUT@'], but this would: command : ['cp', '@INPUT@'].

But… That seems to work fine.

**Comment by jpakkane** [comment]
I tested this with a sample project and got this:

    ERROR: Command has '@INPUT@' as part of a string and more than one input file

Which is exactly what it should do. The command specification is this:

```meson
custom_target('something',
  input : ['input1.txt', 'input2.txt'],
  output : 'the_end.txt',
  command : [prog, './@INPUT@'])
```

**Comment by Salamandar** [comment]
Oh. I missread the doc. I was using this with only one input.
