### ISSUE TITLE
Qt ui produces headers with unexpected names and locations

### ISSUE THREAD

**Issue by ePirat** [mesonbuild/meson#4066]
In VLC we used to include generated Qt UI file headers like this:

```
#include "ui/open_capture.h"
```

With meson, we generate those like this (simplified example):

```
ui_sources = files('ui/open_capture.ui')

qt5pre_files = qt5.preprocess(ui_files : ui_sources, […])
```

Doing that we can't include those as expected but have to use

```
#include "ui_open_file.h"
```

instead. This is really unexpected and requires quite some amount of source changes to adapt the includes everywhere.

**Comment by jeandet** [comment]
That's unfortunate, I think that  ui_<basename>.h is also the default with qmake and CMake.
https://cmake.org/cmake/help/v3.9/prop_tgt/AUTOUIC.html
http://doc.qt.io/qt-5/uic.html
One way to workaround this would be to use your own generator based on what meson does here:
https://github.com/mesonbuild/meson/blob/master/mesonbuild/modules/qt.py#L163
The drawback is that you may have to ensure that you use the same Qt kit than Meson internally.

You should really consider migrating your code base to ```ui_<basename>.h``` even if this painful.

**Comment by ePirat** [comment]
Indeed, I've checked again and all my other Qt projects use `ui_<name>.h`. Not sure why this wasn't the case for VLC already.

**Comment by Tanishq-Banyal** [comment]
what is difference between qt5.ui_compile() and qt5.preprocess() ? how do i use them ?
I am unable  to understand from meson docs, can someone please guide me ?

Here is a simplified version of my meson.build file :-
```py
project('example', 'cpp')

qt5 = import('qt5')
qt5.compile_ui(sources: 'gui/main.ui')
qt5.preprocess(ui_files: 'gui/main.ui')

deps = [
    dependency('threads'),
    dependency('qt5', modules: ['Core','Gui','Widgets'])
]

executable('example', 'src/main.cpp', dependencies: deps)
```

Error :-
```
../src/main.cpp:11:10: fatal error: ui_main.h: No such file or directory
   11 | #include <ui_main.h>
      |          ^~~~~~~~~~~
```

also tried including `gui/ui_main.h` and `gui/main.h`, still same error. Where exacly is the output of uic stored ?

**Comment by dcbaker** [comment]
`preprocess` is a "mega function" that does all of what `compile_resources`, `compile_ui`, and `compile_moc ` do. You can use either, but I would recommend using the individual functions if you can rely on a new enough version of meson.

The problem in this case though, is that there isn't a dependency between the ui generated files and the executable, try:

```meson
project('example', 'cpp')

qt5 = import('qt5')

deps = [
    dependency('threads'),
    dependency('qt5', modules: ['Core','Gui','Widgets'])
]

executable('example', 'src/main.cpp', qt5.compile_ui(sources: 'gui/main.ui'), dependencies: deps)
```

**Comment by Tanishq-Banyal** [comment]
Yes I figured that out after a closer look at examples in docs.

BTW, `#include <ui_main.h>` works, there isn't any `gui_` prefix

**Comment by dcbaker** [comment]
You're right, I'm not sure whether that was a typo or a thinko :D
