### ISSUE TITLE
please, set some timeout value when using ``urllib.request`` (or use something other apart from ``urllib.request``)

### ISSUE THREAD

**Issue by polymorphm** [mesonbuild/meson#4087]
what has happened?
--------------------------

please, I'm begging you :-) .. set some timeout value when using ``urllib.request`` (or use something other apart from ``urllib.request``..). stop using ``urllib.request`` without setting a timeout value.

because your current style of doing http(s)-requests lets Meson process hangup **forever**.

(yes! **hanging up** is **forever**, until manual killing process of Meson).

the probability of hanging up of Meson process is exists on Linux kernel based OS. and maybe on other OS too -- I don't know about thin details of other OS's.

why does hanging up (forever) is able to happen?
--------------------------------------------------------------

this is theoretical part of the issue. (**the practical part including reproduction of hanging up -- is here -- below in this text**).

see documentation of module ``urllib.request`` [ https://docs.python.org/3/library/urllib.request.html#urllib.request.urlopen ]:

>  urllib.request.urlopen(url, data=None, [timeout, ]*, cafile=None, capath=None, cadefault=False, context=None)
>
> ...
> The optional timeout parameter specifies a timeout in seconds for blocking operations like the connection attempt (if not specified, the global default timeout setting will be used). This actually only works for HTTP, HTTPS and FTP connections.
> ...

what does it mean -- "global default timeout"?

if you look in the source code you'll see -- it means the default timeout of socket object. and you'll see that ``urllib.request`` does **not** set ``socket.SO_KEEPALIVE`` option (in Linux ``SO_KEEPALIVE`` by default is 0 (zero). 0 (zero) means kernel won't probe socket to checking to alive status).

check the ``socket`` python-module documentation [ https://docs.python.org/3/library/socket.html#socket.getdefaulttimeout ]:

> socket.getdefaulttimeout()
> 
> Return the default timeout in seconds (float) for new socket objects. A value of None indicates that new socket objects have no timeout. When the socket module is first imported, the default is None.
> 
> socket.setdefaulttimeout(timeout)
> 
> Set the default timeout in seconds (float) for new socket objects. When the socket module is first imported, the default is None. See settimeout() for possible values and their respective meanings.

in Linux kernel (with all default parameters and default parameters like in all popular linux-distros) -- socket object's behaviour assumes next situations:

* the socket is in connection phase. in this case there is some default timeout (not large) for the operation. socket operation is **NOT able** to hangup forever during this phase.
* the connected socket is in sending data phase. in this case also there is some default timeout (also not large) for acknowledging of sending. and socket operation is also **NOT able** to hangup forever during this phase .
* the connected socket is in the middle of receiving data phase. in this case also there is some default timeout (can be pretty large) for making acknowledging and continuing functionality. and socket operation is also (ALSO!) **NOT able** to hangup forever during this phase.
* the connected socket is NOT sending anything AND is NOT in the middle of receiving data, but the socket is waiting of receiving new sequence of data. the client's socket is waiting new data, but the server's socket is not sending anything yet, for example the server has to do some own work before starting new sending data to the client . YES! this phase **IS able to hangup FOREVER**. if socket connection had broken down during that phase, we wouldn't know when we should stop the waiting, and timeout for this phase is **infinite by default**.

the last theoretical question -- where is the phase with infinite waiting in ``urllib.request`` implemented http(s)-protocol?

the answer -- it is after sending of http-headers and http-body, but before receiving http-headers from a server. 

(ok! theoretical aspects are over. thank you for reading.. I'm sorry for lots of words.. really.. sorry for it)

how can we reproduce hanging up forever -- in practice? for Meson process, surely
---------------------------------------------------------------------------------------------------------

it wasn't easy for me, but I've found how to make some synthetic environment to do this.

the main rule -- I should not change ANYTHING on my laptop (where I run the Meson processes). my laptop should be with default Linux settings (network and other kernel settings), connected somehow to the Internet.

I should invoke a hanging up (forever) of a Meson process (running on my Laptop) -- only including bad fluctuation via my synthetic network infrastructure. and it should likely to be close to a reality (for example: I should NOT spoil ip package's payloads , because it would be far from the reality).

my test stand:

```
    +-------------------+               +----------+               +--------+
    | my Linux laptop   |   ethernet    | Ethernet |   some link   | Linux  |
    | (with running     | ------------> |  Switch  | ------------> | Router |
    |  Meson processes) |   (port "A")  |          |   (port "B")  |        |
    +-------------------+               +----------+               +--------+
                                                                        |
                                                                        |
                                                                        V
                                                                   +----------+
                                                                   |   The    |
                                                                   | Internet |
                                                                   |          |
                                                                   +----------+
```

to increase probability of the issue -- I've configured the Linux Router to simulate connection with bad latency:

```
    # commands on the Router
    
    tc qdisc add dev ens3 root netem delay 1500ms
    
    tc qdisc show dev ens3
    
    #tc qdisc del dev ens3 root # the command to reset it
```

so we've increased RTT (round-trip time) on a router. it's important that we did it on a router, not on a localhost machine.

next, I ran script on the Laptop to running several Meson processes, shifting their start-time to some milliseconds from each other.

the test script:

```
    #!/bin/bash
    
    count="300"
    sleep="0.100"
    
    echo "TEST: begin"
    
    for ((i = 0; i < count; ++i))
    do
    echo "TEST: starting $i/$count..."
    meson wrap status & sleep "$sleep"
    done
    
    echo "TEST: waiting all..."
    
    wait
    
    echo "TEST: we are we're not freezed" \
            $'\n\t'"(it would be bad if we wanted to reproduce freezing)"
```

in the middle of script's action -- I pulled out a wire from the Ethernet Switch (``port "B"``).

I had to make several attempts of the test -- to found out: correct script's parameters, correct router's parameters, the time of pulling out the wire ``port "B"``. eventually, it has happend successfully: some meson processes has hanged up!

the picture of successfully hanging up of ten Meson processes --

```
    [regular-user@plm-notebook ~]$ ps -eF | grep -Fi meson | nl; date
         1	regular+  1843 20787  0  3259  2364   2 15:07 pts/0    00:00:00 grep -Fi meson
         2	regular+ 27897 27794  0 30066  5244   0 00:56 pts/1    00:00:00 /usr/bin/python /usr/bin/meson wrap status
         3	regular+ 27900 27794  0 30069  5320   3 00:56 pts/1    00:00:00 /usr/bin/python /usr/bin/meson wrap status
         4	regular+ 27956 27794  0 30068  5276   2 00:56 pts/1    00:00:00 /usr/bin/python /usr/bin/meson wrap status
         5	regular+ 27962 27794  0 30068  5276   3 00:56 pts/1    00:00:00 /usr/bin/python /usr/bin/meson wrap status
         6	regular+ 27964 27794  0 30069  5320   3 00:56 pts/1    00:00:00 /usr/bin/python /usr/bin/meson wrap status
         7	regular+ 27967 27794  0 30066  5276   3 00:56 pts/1    00:00:00 /usr/bin/python /usr/bin/meson wrap status
         8	regular+ 27971 27794  0 30068  5288   3 00:56 pts/1    00:00:00 /usr/bin/python /usr/bin/meson wrap status
         9	regular+ 27974 27794  0 30067  5196   1 00:56 pts/1    00:00:00 /usr/bin/python /usr/bin/meson wrap status
        10	regular+ 27978 27794  0 30068  5272   3 00:56 pts/1    00:00:00 /usr/bin/python /usr/bin/meson wrap status
        11	regular+ 28001 27794  0 30067  5328   3 00:56 pts/1    00:00:00 /usr/bin/python /usr/bin/meson wrap status
    Sun 26 Aug 15:07:37 MSK 2018
    [regular-user@plm-notebook ~]$ 
```

the log of test running the test script -- https://gist.github.com/polymorphm/b7654f3ff3412f2094ea3c26fda547be

before successfully end, I had lots of bad attempts of the test. I tried variuos things, for example: I tried to increase RTT on localhost (the Laptop) -- it did not work -- Meson processes hanged up but not forever (they hanged up for about 10~15 minutes, then Linux kernel successfully detected broken connections).

(I'm writing the issue's text right now, I have the internet connection again, but those processes are still hanged up.. I haven't killed them yet)

conclusion
-------------

Meson source code has only few places with ``urllib.request`` (exactly -- with calling ``urllib.request.urlopen(url)``).

* ``mesonbuild/wrap/wrap.py``
* ``ghwt.py``
* some test files

I don't think that it is a huge problem to add ``timeout`` to **all** calling of ``urllib.request.urlopen()`` :-) .. (but I had to write this huge text for proving of lack these changes :-))

for example ``600.0`` seconds in general case should be enough, I guess. (for some specific cases -- we probably would like to reduce ``600.0`` to ``60.0`` -- for example for getting of list and statuses of ``wrap``-packages).

Meson utility would be used in automated scripts (of outer programs), if it had guarantee not hanging up.

currently (with this issue), we can run Meson utility only manual (not from automated scripts).

thank you in advance!

**Comment by polymorphm** [comment]
I'll close it. thank you!

**Comment by eliandroribeiro** [comment]
Thank you very much!
I don't know why, but my `urlopen` request was taking 2 minutes to be fulfilled. After setting `timeout` parameter to _2 seconds_, then the response time was just 2 seconds (not perfect, but reasonable).
THANK YOU FOR YOUR GREAT TIP!!!!!
