### ISSUE TITLE
Google Test dependency problematic when building with libc++ on Linux

### ISSUE THREAD

**Issue by martin-ejdestig** [mesonbuild/meson#409]
Google Test unit-test executables will not link when building with "clang++ -stdlib=libc++" and the Linux distribution ships a prebuilt libgtest.so (built with libstdc++).

Since the Google Test authors recommend against precompiling it (see https://github.com/google/googletest/blob/master/googletest/docs/FAQ.md#why-is-it-not-recommended-to-install-a-pre-compiled-copy-of-google-test-for-example-into-usrlocal ) I wonder if Meson should prefer compiling the source if it is available. Maybe prebuilt .so:s should be ignored completely for GTest and GMock? At least Arch, Debian and Fedora seem to ship the soruce in /usr/src/gtest .

Another problem I discovered when trying out this by hacking GTestDependency is that warning flags are passed along when building the GTest sources. When building with a custom Make based build system I have previously had to do something like this:

```
# Disable some warnings for main gtest source files.
# - There are a lot of implicit conversions from signed to unsigned integers.
# - GTEST_DEFINE_STATIC_MUTEX_ does not initialize owner_ field. See
#   documentation for the macro in /usr/include/gtest/internal/gtest-port.h.
# - override is missing... everywhere
# - NULL is used by gtest.
# - Clang warns for non string literal format strings in custom printf-like
#   functions in gtest-all.cc while GCC does not.
$(GTEST_MAIN_OBJS): CXXFLAGS += -Wno-sign-conversion
$(GTEST_MAIN_OBJS): CXXFLAGS += -Wno-missing-field-initializers
ifeq ($(CXX),g++)
 $(GTEST_MAIN_OBJS): CXXFLAGS += -Wno-suggest-override
 $(GTEST_MAIN_OBJS): CXXFLAGS += -Wno-zero-as-null-pointer-constant
endif
ifeq ($(CXX),clang++)
 $(GTEST_MAIN_OBJS): CXXFLAGS += -Wno-format-nonliteral
endif
```

Should Meson perhaps not build the GTest source with warnings? I do not see an easy way to do that though. I am not that familiar with the Meson code base.

**Comment by jpakkane** [comment]
The dep detector of Meson will detect whether the version on your system is prebuilt or only ships sources and adapts itself accordingly. For the `libc++` case you might want to get gtest from [wrapb](https://wrapdb.mesonbuild.com/) instead, that also works on OSX/Windows/others. A sample project for using wraps are [the first two here](https://github.com/mesonbuild/meson/tree/master/manual%20tests).

As for flags to use, patches to wrapdb packaging are gladly accepted. :)

**Comment by martin-ejdestig** [comment]
Looks like Debian (and therefor also Ubuntu) stopped shipping libraries four years ago. While Fedora and Arch still ship them. I think Meson should prefer to follow upstream's advice even if some distros do not.

**Comment by martin-ejdestig** [comment]
Are global compiler flags in the main proeject passed down to subprojects?

**Comment by jpakkane** [comment]
Yes.

**Comment by martin-ejdestig** [comment]
Apparently documentation recommending against prebuilt binaries was removed in 5437926b2213b1c45c2f34bd858734de90e5fffd with the wonderful commit message "Doc sync".

Still problematic, but... c'est la vie. Closing.
