### ISSUE TITLE
Wrong linking order in module `pkgconfig`

### ISSUE THREAD

**Issue by haasn** [mesonbuild/meson#4091]
With the way `_process_libs` first appends to the `priv/pub_libs` and then returns `processed_libs` (which the calling code then also appends to those same lists), you effectively end up in a scenario where the library itself will typically be specified last, after all of its dependencies.

Example:
```
Name: libplacebo
Description: Reusable library for GPU-accelerated video/image rendering
Version: 0.5.0
Requires: lcms2 >= 2.6, vulkan >= 1.0.42
Libs: -pthread -lm -lglslang -lHLSL -lOGLCompiler -lOSDependent -lSPIRV -lSPVRemapper -L${libdir} -lplacebo
Cflags: -I${includedir} -pthread
```

This is the wrong way around, and results in a linking failure. The library must be specified first, *followed* by its dependencies.

The easiest solution would be most likely to make `add_pub_libs`/`add_priv_libs` prepend instead of appending the result of `_process_libs`.

**Comment by haasn** [comment]
This bug is still affecting meson and causing issues with the same project.

**Comment by nirbheek** [comment]
Sounds good. Could you open a PR with those changes + a test that demonstrates the issue?

**Comment by haasn** [comment]
Sorry, it seems as though this issue has actually been implicitly fixed in master: the static link dependencies are now (correctly!) generated as `Libs.private` entries instead of `Libs` entries, which side-steps the ordering concerns. (It's possible it may still arise in other contexts, but I don't know how to construct such an example)

(I suspect the user who ran into this bug recently may have been using an older version of meson)

**Comment by haasn** [comment]
This issue still arises when using static linking instead of dynamic linking. I'll start work on a fix.

**Comment by haasn** [comment]
So I've confirmed that simply swapping the order of the dependencies like this fixes the issue. I've also come up with a minimal reproduction test case. But, I couldn't figure out from a few glances how to integrate it properly into your test system.

```diff
diff --git a/mesonbuild/modules/pkgconfig.py b/mesonbuild/modules/pkgconfig.py
index 8684864d..36984b15 100644
--- a/mesonbuild/modules/pkgconfig.py
+++ b/mesonbuild/modules/pkgconfig.py
@@ -35,13 +35,13 @@ class DependenciesHelper:
 
     def add_pub_libs(self, libs):
         libs, reqs, cflags = self._process_libs(libs, True)
-        self.pub_libs += libs
+        self.pub_libs = libs + self.pub_libs # prepend to preserve dependencies
         self.pub_reqs += reqs
         self.cflags += cflags
 
     def add_priv_libs(self, libs):
         libs, reqs, _ = self._process_libs(libs, False)
-        self.priv_libs += libs
+        self.priv_libs = libs + self.priv_libs
         self.priv_reqs += reqs
 
     def add_pub_reqs(self, reqs):
```

Minimal test case:
```meson
project('link order demo', 'c')

lib1 = library('foo', [])
lib2 = static_library('bar', [], link_with: lib1)
pkg = import('pkgconfig')
pkg.generate(
    name: 'bar',
    description: '',
    libraries: lib2,
    version: '1'
)
```

With current meson this generates:
```pkgconfig
prefix=/usr/local
libdir=${prefix}/lib64
includedir=${prefix}/include

Name: bar
Version: 1
Libs: -L${libdir} -lfoo -lbar
Cflags: -I${includedir}
```

With my patch applies it generates:
```
prefix=/usr/local
libdir=${prefix}/lib64
includedir=${prefix}/include

Name: bar
Version: 1
Libs: -L${libdir} -lbar -lfoo
Cflags: -I${includedir}
```

How would I write a test case that makes sure the order is correct here?

**Comment by haasn** [comment]
I came up with a hacky way to write a test case, by having bar export a symbol `bar` (which depends on `foo`) and then building against it like this:

```meson
# Test that we can link something against this .pc file
test('check-link', find_program('./test.sh'),
  env: [
    'PKG_CONFIG_PATH=' + meson.current_build_dir() + '/meson-private',
    'CFLAGS=-L' + meson.current_build_dir(),
  ]
)
```

```shell
#!/bin/sh
gcc -o /dev/null $CFLAGS -Wl,--as-needed -xc - $(pkg-config --libs bar) <<EOF
int bar();

int main() {
    return bar();
}
EOF
```

But that's a very ugly way to test. Isn't there a cleaner solution?
