### ISSUE TITLE
Cross-compiling with emscripten

### ISSUE THREAD

**Issue by Eric-Ryan** [mesonbuild/meson#4101]
I am cross compiling meson using the emscripten compiler using this cross-file:
```
    [binaries]
    c = '../../../emsdk/emscripten/1.38.11/emcc.py'
    cpp = '../../../emsdk/emscripten/1.38.11/em++.py'
    ar = '../../../emsdk/emscripten/1.38.11/emar.py'
    #exe_wrapper = 'node'

    [properties]
    root = '../../../emsdk/emscripten/1.38.11/system'
    c_args = ['-s', 'WASM=1', '-O2']
    c_link_args = ['-s', 'WASM=1','-O2']
    cpp_args = ['-s', 'WASM=1','-O2']
    cpp_link_args = ['-s', 'WASM=1','-O2']
    shared_lib_suffix = 'js'
    static_lib_suffix = 'js'
    shared_module_suffix = 'js'
    exe_suffix = 'js'

    [host_machine]
    system = 'emscripten'
    cpu_family = 'x86'
    cpu = 'i686'
    endian = 'little'
```
When I run it I get an error telling me I need a 32-bit version of the Emscripten compiler:
```
    meson.build:17:0: ERROR:  Unknown compiler(s): [['../../../emsdk/emscripten/1.38.11/em++.py']]
    The follow exceptions were encountered:
    Running "../../../emsdk/emscripten/1.38.11/em++.py --version" gave "[WinError 193] %1 is not a valid Win32 application"
```
I read that emscripten stopped supporting 32-bit on Windows. So this means I have to manually build it from source using this page: https://kripken.github.io/emscripten-site/docs/building_from_source/building_emscripten_from_source_on_windows.html
Does this seem correct or am I doing something wrong?

**Comment by nirbheek** [comment]
Did you mean to file this again? You already filed https://github.com/mesonbuild/meson/issues/4097 about this.
