### ISSUE TITLE
Minor dependency formatting glitch

### ISSUE THREAD

**Issue by SoapGentoo** [mesonbuild/meson#4116]
On Meson 0.47.2 I get

    Dependency GMock found: YES (prebuilt)

On HEAD Meson I get

    Dependency GMock found: YES , prebuilt

due to the system GMock missing a version specifier.

**Comment by jon-turney** [comment]
This is probably the result of changes in #3657.

What do you think the correct output should be?

**Comment by SoapGentoo** [comment]
For simplicity, I would keep the formatting the old way, if only to remove the context-sensitive nature of the comma. I would suggest

    Dependency GMock found: YES (prebuilt)

and 

    Dependency GMock found: YES 1.9.0 (pkgconfig)

as all log components are space-separated and don't require extra context-aware information for handling the comma. Alternatively

    Dependency GMock found: YES (1.9.0, pkgconfig)

which only requires appending the comma to the version string, if present.

 Your ideas?

**Comment by jon-turney** [comment]
> Your ideas?

I was just trying to keep things the same, unfortunately the logging wasn't consistent.

after this PR, I get

```
Dependency GTest found: NO (tried pkgconfig and system)
```
and
```
Dependency GTest found: YES (building self)
```
