### ISSUE TITLE
python module doesn't find python3.7

### ISSUE THREAD

**Issue by prlw1** [mesonbuild/meson#4128]
The python binaries available in my path are python2.7, python3.6, python3.7. (There are also python2.7-config etc. config files, and they each have a .pc in PKG_CONFIG_PATH.)

glib hunts for python by doing
```
python = import('python').find_installation('python3')
# used for '#!/usr/bin/env <name>'
python_name = 'python3'

python_version = python.language_version()
python_version_req = '>=3.4'
if not python_version.version_compare(python_version_req)
  error('Requires Python @0@, @1@ found.'.format(python_version_req, python_version))
endif
```
and errors out with 'meson.build:1876:0: ERROR:  python3 not found'

meson itself is happily running python3.6.

- maybe modules/python.py could try more version variations?
- in autotools the traditional hint was to set the PYTHON environment variable - is there an equivalent?

**Comment by nirbheek** [comment]
Which distro are you running?

CCing @MathieuDuponchelle who wrote this code.

**Comment by prlw1** [comment]
packages from www.pkgsrc.org, so not distro-dependent.

**Comment by SoapGentoo** [comment]
What is the `LIBPC` value in the sysconfig module? Is it correct, that is, does the value point to a directory that exists? Python itself is not relocatable and if you just package it up and untar it somewhere else, the `LIBPC` entry will be bogus and Meson won't be able to find the `python-3.7.pc` file. Have you tried explicitly adding the directory containing the `python-3.7.pc` to `PKG_CONFIG_LIBDIR`? Meson HEAD contains a slightly more robust way of finding python, and this might just work for you.

**Comment by prlw1** [comment]
```
quark$ python3.6 -c 'import sysconfig;print(sysconfig.get_config_var("LIBPC"))'
/usr/pkg/lib/pkgconfig
quark$ ls /usr/pkg/lib/pkgconfig/python*
/usr/pkg/lib/pkgconfig/python-2.7.pc    /usr/pkg/lib/pkgconfig/python-3.7.pc
/usr/pkg/lib/pkgconfig/python-3.6.pc
```
I must check what the build environment does though...

**Comment by MathieuDuponchelle** [comment]
I'm not sure I understand what's happening here, but afaiu the error is thrown before we do anything related to pkg-config, ie it is thrown by find_installation().

At that stage, what we do is very simple:

* Look for an executable named `python3` in the PATH (is python3 a valid command in your system?)

* If not found, for two well-known-names (`python2` and `python3`) we go an extra mile and also check whether `python` is available in the PATH. If it is, we then run `import sysconfig; print (sysconfig.get_python_version())` and compare with the expected version. If `python3` is not a valid command on your system, is `python`? If yes, what python executable does it link to?

We finally check that whatever the executable that was found, it "looks like" a python, but if not the error that is output is different (`'{} is not a valid python'.format(python)`)

Please triple check these things, in any case the `find_installation()` method is pretty simple so if you feel like it you should have no trouble adding some debug in there to figure what's what :)

**Comment by prlw1** [comment]
Right: as I wrote in the original report above, the binaries are called python2.7, python3.6 and python3.7.
There is no python, python2 nore python3. meson itself happens to be running python3.6.

**Comment by MathieuDuponchelle** [comment]
That's curious, how did you install meson? Perhaps the entry point that gets installed takes into account the python it's been run with, for example on my end:

```
 meh  ~  cat /home/meh/.local/bin/meson
#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'meson==0.48.0.dev1','console_scripts','meson'
__requires__ = 'meson==0.48.0.dev1'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('meson==0.48.0.dev1', 'console_scripts', 'meson')()
    )
 meh  ~ 
```

In any case, the fix seems easy enough, just make a `python3` alias somewhere in your PATH :)

**Comment by nirbheek** [comment]
Some BSDs also don't ship with `python3`, and only ship versioned pythons. I think we should fallback to using whatever Python meson is using in these cases.

**Comment by MathieuDuponchelle** [comment]
I feel like this is too much of a special casing, and will break backwards compatibility if meson ever moves to another python major version

**Comment by MathieuDuponchelle** [comment]
I'm curious how such shebangs: `#!/usr/bin/env python3` work on BSD in that case, any clue @nirbheek ?

**Comment by nirbheek** [comment]
> I'm curious how such shebangs: `#!/usr/bin/env python3` work on BSD in that case, any clue @nirbheek ?

Same as what @prlw1 said. They change the shebang lines for all scripts that are installed by packages.

**Comment by nirbheek** [comment]
> this has nothing to do with "BSD" which you seem to be stuck on

The difference is that since pkgsrc is a custom setup that requires user interaction anyway, we can ask you to add a symlink to the python you want to use and call it a day. But the 'default' workflows in distros should not require the user to fiddle with their Python installation, which is why I mentioned BSDs. Fixing that for them will fix it for you for free.

**Comment by prlw1** [comment]
[the "stuck on" was for Mathieu - nirbheek, you clearly got the point.]

It would be a pain to tell people "After you did your system upgrade using binary packages and pkgin, add this symlink by hand..." We seem to manage to keep track of the few python packages which are current, so I dispute the "I feel like this is too much of a special casing, and will break backwards compatibility if meson ever moves to another python major version". - or just fall back to the one which meson uses as already suggested by nirbheek.

**Comment by MathieuDuponchelle** [comment]
@prlw1 , please don't be rude, that was a simple question, addressed to @nirbheek , thanks.

**Comment by MathieuDuponchelle** [comment]
In any case:

> It works on your linux box doesn't equate to it works on linux.

I haven't made such an assertion. However my point here is that we should not adopt a fragile solution to cater for Unix-like environments that do not follow the recommendations made in [PEP 394](https://www.python.org/dev/peps/pep-0394/):

> Unix-like software distributions (including systems like Mac OS X and Cygwin) should install the python2 command into the default path whenever a version of the Python 2 interpreter is installed, and the same for python3 and the Python 3 interpreter.

> I dispute the "I feel like this is too much of a special casing, and will break backwards compatibility if meson ever moves to another python major version". - or just fall back to the one which meson uses as already suggested by nirbheek.

I don't understand how this disputes my point, let me try to make it clearer:

* We choose to use meson's python as a fallback for `python3`
* `python3` is now found on platforms that do not follow PEP 394
* Meson switches to a new python major version, and the `python3` fallback is removed
* Build scripts that used to work on non-PEP 394 platforms now fail again

This, to me, is a fragile solution, and does not in any case really address the brokenness of an environment that does not follow PEP 394: what should happen when a build script calls `pymod.find_installation('python2')`?

If I were to make a suggestion, I would propose implementing support for module-level options, then exposing options in the python module to let users influence the search for `python3`, `python2`, `python`, etc.

There is already an API for using the default meson python (don't pass an argument to `find_installation`), but it should IMHO be left up to the `meson.build` author to decide whether meson's python is a valid fallback.

**Comment by MathieuDuponchelle** [comment]
Should be closed, reporter never replied to that last comment

**Comment by askovpen** [comment]
```
>python3 --version
Python 3.8.3

>python3 -c "import sysconfig; print(sysconfig.get_config_var('BINDIR'))" 
D:\Users\user\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0

>meson build
meson.build:2:0: ERROR: python3 not found
```
