### ISSUE TITLE
Regression from 0.46.0 to 0.47.0 using custom pkg-config modules

### ISSUE THREAD

**Issue by nacho** [mesonbuild/meson#4135]
I have a custom script that does the following:

```
export PKG_CONFIG_PATH="${_dir}/deps/gtk-binaries/${_flavor}/x86_64/lib/meson-pkgconfig/"
rm -rf "${_builddir}"
mkdir -p "${_builddir}"

meson "${_builddir}" --prefix ${_prefix}
ninja -C "${_builddir}" $@
```

With meson 0.46.0 it picks the right libraries specified by the custom pkgconfig, instead with 0.47.2 it tries to use the system libraries and clearly fails because they are older.
If the behaviour has changed and I need to specify something else fine for me, just asking for help here.

This is the error I get:
/usr/bin/ld.bfd.real: /usr/lib/x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-turbojpeg.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC
/usr/lib/x86_64-linux-gnu/libturbojpeg.a: error adding symbols: Bad value

**Comment by nacho** [comment]
This is the one failing:
[meson-log.txt](https://github.com/mesonbuild/meson/files/2357133/meson-log.txt)

**Comment by nacho** [comment]
This is 0.46.0 working fine
[meson-log.txt](https://github.com/mesonbuild/meson/files/2357144/meson-log.txt)

**Comment by nacho** [comment]
This is the linker line:
```
[123/123] Linking target viewer/dcvviewer.
FAILED: viewer/dcvviewer 
cc  -o viewer/dcvviewer 'viewer/viewer@@dcvviewer@exe/meson-generated_.._dcvviewer-resources.c.o' 'viewer/viewer@@dcvviewer@exe/.._common_clipboardmonitor.c.o' 'viewer/viewer@@dcvviewer@exe/.._common_clipboardmonitorgtk.c.o' 'viewer/viewer@@dcvviewer@exe/.._common_clipboardstorage.c.o' 'viewer/viewer@@dcvviewer@exe/.._common_cursor.c.o' 'viewer/viewer@@dcvviewer@exe/.._common_cursorcache.c.o' 'viewer/viewer@@dcvviewer@exe/.._common_displaycodecinfo.c.o' 'viewer/viewer@@dcvviewer@exe/.._common_displayhead.c.o' 'viewer/viewer@@dcvviewer@exe/.._common_displaylayout.c.o' 'viewer/viewer@@dcvviewer@exe/.._common_errors.c.o' 'viewer/viewer@@dcvviewer@exe/.._common_health.c.o' 'viewer/viewer@@dcvviewer@exe/.._common_license.c.o' 'viewer/viewer@@dcvviewer@exe/.._common_log.c.o' 'viewer/viewer@@dcvviewer@exe/.._common_message.c.o' 'viewer/viewer@@dcvviewer@exe/.._common_messagestream.c.o' 'viewer/viewer@@dcvviewer@exe/.._common_protobufutils.c.o' 'viewer/viewer@@dcvviewer@exe/.._common_protocolversion.c.o' 'viewer/viewer@@dcvviewer@exe/.._common_rand.c.o' 'viewer/viewer@@dcvviewer@exe/.._common_rect.c.o' 'viewer/viewer@@dcvviewer@exe/.._common_settingsenums.c.o' 'viewer/viewer@@dcvviewer@exe/.._common_softwareinfo.c.o' 'viewer/viewer@@dcvviewer@exe/.._common_streamtransport.c.o' 'viewer/viewer@@dcvviewer@exe/.._common_systeminfo.c.o' 'viewer/viewer@@dcvviewer@exe/.._common_throttler.c.o' 'viewer/viewer@@dcvviewer@exe/.._common_transport.c.o' 'viewer/viewer@@dcvviewer@exe/.._common_utils.c.o' 'viewer/viewer@@dcvviewer@exe/.._common_websockettransport.c.o' 'viewer/viewer@@dcvviewer@exe/aboutdialog.c.o' 'viewer/viewer@@dcvviewer@exe/application.c.o' 'viewer/viewer@@dcvviewer@exe/certificatedialog.c.o' 'viewer/viewer@@dcvviewer@exe/chart.c.o' 'viewer/viewer@@dcvviewer@exe/connectionsettingsdialog.c.o' 'viewer/viewer@@dcvviewer@exe/connectionconfig.c.o' 'viewer/viewer@@dcvviewer@exe/connectionviewer.c.o' 'viewer/viewer@@dcvviewer@exe/display.c.o' 'viewer/viewer@@dcvviewer@exe/filestoragedialog.c.o' 'viewer/viewer@@dcvviewer@exe/filestoragelistboxrow.c.o' 'viewer/viewer@@dcvviewer@exe/historyentry.c.o' 'viewer/viewer@@dcvviewer@exe/main.c.o' 'viewer/viewer@@dcvviewer@exe/modelbutton.c.o' 'viewer/viewer@@dcvviewer@exe/notificationlistboxrow.c.o' 'viewer/viewer@@dcvviewer@exe/notificationtogglebutton.c.o' 'viewer/viewer@@dcvviewer@exe/resolutiondialog.c.o' 'viewer/viewer@@dcvviewer@exe/streamingmodedialog.c.o' 'viewer/viewer@@dcvviewer@exe/window.c.o' -Wl,--no-undefined -Wl,--as-needed -Wl,--start-group dcvmetrics/libdcvmetrics.a libdv/libdv.a -Wl,-z,relro -Wl,-z,now -pie /usr/lib/x86_64-linux-gnu/libglib-2.0.so /usr/lib/x86_64-linux-gnu/libgthread-2.0.so -pthread /usr/lib/x86_64-linux-gnu/libgobject-2.0.so /usr/lib/x86_64-linux-gnu/libgio-2.0.so /usr/lib/x86_64-linux-gnu/libffi.so /usr/lib/x86_64-linux-gnu/libsoup-2.4.so /usr/lib/x86_64-linux-gnu/libsasl2.so /usr/lib/x86_64-linux-gnu/libportaudio.so /usr/lib/x86_64-linux-gnu/libasound.so -lm -lpthread /usr/lib/x86_64-linux-gnu/libopus.so /usr/lib/x86_64-linux-gnu/libturbojpeg.a /usr/lib/x86_64-linux-gnu/libjpeg.so /usr/lib/x86_64-linux-gnu/liblz4.so /usr/lib/x86_64-linux-gnu/libavcodec.so /usr/lib/x86_64-linux-gnu/libswscale.so /usr/lib/x86_64-linux-gnu/libavutil.so -L../deps/gtk-binaries/ubuntu16/x86_64/lib -lx264 /usr/lib/x86_64-linux-gnu/libprotobuf-c.so /usr/lib/x86_64-linux-gnu/libpcsclite.so /usr/lib/x86_64-linux-gnu/libssl.so /usr/lib/x86_64-linux-gnu/libcrypto.so /usr/lib/x86_64-linux-gnu/libgtk-3.so /usr/lib/x86_64-linux-gnu/libgdk-3.so /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so /usr/lib/x86_64-linux-gnu/libpango-1.0.so /usr/lib/x86_64-linux-gnu/libatk-1.0.so /usr/lib/x86_64-linux-gnu/libcairo-gobject.so /usr/lib/x86_64-linux-gnu/libcairo.so /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so -pthread -pthread -lm -lpthread -L../deps/gtk-binaries/ubuntu16/x86_64/lib -lx264 -Wl,--end-group  
/usr/bin/ld.bfd.real: /usr/lib/x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-turbojpeg.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC
/usr/lib/x86_64-linux-gnu/libturbojpeg.a: error adding symbols: Bad value

```

**Comment by nacho** [comment]
I guess you want this one instead:

`build viewer/dcvviewer: c_LINKER viewer/viewer@@dcvviewer@exe/meson-generated_.._dcvviewer-resources.c.o viewer/viewer@@dcvviewer@exe/.._common_clipboardmonitor.c.o viewer/viewer@@dcvviewer@exe/.._common_clipboardmonitorgtk.c.o viewer/viewer@@dcvviewer@exe/.._common_clipboardstorage.c.o viewer/viewer@@dcvviewer@exe/.._common_cursor.c.o viewer/viewer@@dcvviewer@exe/.._common_cursorcache.c.o viewer/viewer@@dcvviewer@exe/.._common_displaycodecinfo.c.o viewer/viewer@@dcvviewer@exe/.._common_displayhead.c.o viewer/viewer@@dcvviewer@exe/.._common_displaylayout.c.o viewer/viewer@@dcvviewer@exe/.._common_errors.c.o viewer/viewer@@dcvviewer@exe/.._common_health.c.o viewer/viewer@@dcvviewer@exe/.._common_license.c.o viewer/viewer@@dcvviewer@exe/.._common_log.c.o viewer/viewer@@dcvviewer@exe/.._common_message.c.o viewer/viewer@@dcvviewer@exe/.._common_messagestream.c.o viewer/viewer@@dcvviewer@exe/.._common_protobufutils.c.o viewer/viewer@@dcvviewer@exe/.._common_protocolversion.c.o viewer/viewer@@dcvviewer@exe/.._common_rand.c.o viewer/viewer@@dcvviewer@exe/.._common_rect.c.o viewer/viewer@@dcvviewer@exe/.._common_settingsenums.c.o viewer/viewer@@dcvviewer@exe/.._common_softwareinfo.c.o viewer/viewer@@dcvviewer@exe/.._common_streamtransport.c.o viewer/viewer@@dcvviewer@exe/.._common_systeminfo.c.o viewer/viewer@@dcvviewer@exe/.._common_throttler.c.o viewer/viewer@@dcvviewer@exe/.._common_transport.c.o viewer/viewer@@dcvviewer@exe/.._common_utils.c.o viewer/viewer@@dcvviewer@exe/.._common_websockettransport.c.o viewer/viewer@@dcvviewer@exe/aboutdialog.c.o viewer/viewer@@dcvviewer@exe/application.c.o viewer/viewer@@dcvviewer@exe/certificatedialog.c.o viewer/viewer@@dcvviewer@exe/chart.c.o viewer/viewer@@dcvviewer@exe/connectionsettingsdialog.c.o viewer/viewer@@dcvviewer@exe/connectionconfig.c.o viewer/viewer@@dcvviewer@exe/connectionviewer.c.o viewer/viewer@@dcvviewer@exe/display.c.o viewer/viewer@@dcvviewer@exe/filestoragedialog.c.o viewer/viewer@@dcvviewer@exe/filestoragelistboxrow.c.o viewer/viewer@@dcvviewer@exe/historyentry.c.o viewer/viewer@@dcvviewer@exe/main.c.o viewer/viewer@@dcvviewer@exe/modelbutton.c.o viewer/viewer@@dcvviewer@exe/notificationlistboxrow.c.o viewer/viewer@@dcvviewer@exe/notificationtogglebutton.c.o viewer/viewer@@dcvviewer@exe/resolutiondialog.c.o viewer/viewer@@dcvviewer@exe/streamingmodedialog.c.o viewer/viewer@@dcvviewer@exe/window.c.o | /usr/lib/x86_64-linux-gnu/liblz4.a /usr/lib/x86_64-linux-gnu/libffi.a /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.a /usr/lib/x86_64-linux-gnu/libcrypto.a /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0.3200.2 dcvmetrics/libdcvmetrics.a /usr/lib/x86_64-linux-gnu/libsasl2.a /usr/lib/x86_64-linux-gnu/libavutil-ffmpeg.a /usr/lib/x86_64-linux-gnu/libcairo.a /home/local/ANT/qignacio/git/DCV-viewer-gtk/deps/gtk-binaries/ubuntu16/x86_64/lib/libopus.so.0.6.1 /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.1800.9 /home/local/ANT/qignacio/git/DCV-viewer-gtk/deps/gtk-binaries/ubuntu16/x86_64/lib/libprotobuf-c.so.1.0.0 /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 /usr/lib/x86_64-linux-gnu/libopus.a /usr/lib/x86_64-linux-gnu/libgdk-3.so.0.1800.9 /usr/lib/x86_64-linux-gnu/libpthread.a /usr/lib/x86_64-linux-gnu/libavcodec-ffmpeg.a /home/local/ANT/qignacio/git/DCV-viewer-gtk/deps/gtk-binaries/ubuntu16/x86_64/lib/libx264.so.152 /usr/lib/x86_64-linux-gnu/libgthread-2.0.a /home/local/ANT/qignacio/git/DCV-viewer-gtk/deps/gtk-binaries/ubuntu16/x86_64/lib/libffi.so.6.0.4 /usr/lib/x86_64-linux-gnu/libpthread.so /usr/lib/x86_64-linux-gnu/libswscale-ffmpeg.a /home/local/ANT/qignacio/git/DCV-viewer-gtk/deps/gtk-binaries/ubuntu16/x86_64/lib/libsasl2.so.3.0.0 /home/local/ANT/qignacio/git/DCV-viewer-gtk/deps/gtk-binaries/ubuntu16/x86_64/lib/libavcodec.so.58.18.100 /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0.21809.1 libdv/libdv.a /usr/lib/x86_64-linux-gnu/libgobject-2.0.a /home/local/ANT/qignacio/git/DCV-viewer-gtk/deps/gtk-binaries/ubuntu16/x86_64/lib/libjpeg.so.62.2.0 /usr/lib/x86_64-linux-gnu/libpango-1.0.a /home/local/ANT/qignacio/git/DCV-viewer-gtk/deps/gtk-binaries/ubuntu16/x86_64/lib/libavutil.so.56.14.100 /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0.3800.1 /usr/lib/x86_64-linux-gnu/libsoup-2.4.a /lib/x86_64-linux-gnu/libssl.so.1.0.0 /usr/lib/x86_64-linux-gnu/libcairo-gobject.a /usr/lib/x86_64-linux-gnu/libasound.so.2.0.0 /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0.3800.1 /usr/lib/x86_64-linux-gnu/libglib-2.0.a /usr/lib/x86_64-linux-gnu/libm.so /home/local/ANT/qignacio/git/DCV-viewer-gtk/deps/gtk-binaries/ubuntu16/x86_64/lib/libgio-2.0.so.0.5600.2 /usr/lib/x86_64-linux-gnu/libcairo-gobject.so.2.11400.6 /lib/x86_64-linux-gnu/libpcsclite.so.1.0.0 /home/local/ANT/qignacio/git/DCV-viewer-gtk/deps/gtk-binaries/ubuntu16/x86_64/lib/libglib-2.0.so.0.5600.2 /home/local/ANT/qignacio/git/DCV-viewer-gtk/deps/gtk-binaries/ubuntu16/x86_64/lib/libgobject-2.0.so.0.5600.2 /usr/lib/x86_64-linux-gnu/libgio-2.0.a /home/local/ANT/qignacio/git/DCV-viewer-gtk/deps/gtk-binaries/ubuntu16/x86_64/lib/libturbojpeg.so.0.1.0 /usr/lib/x86_64-linux-gnu/libturbojpeg.a /usr/lib/x86_64-linux-gnu/libjpeg.a /home/local/ANT/qignacio/git/DCV-viewer-gtk/deps/gtk-binaries/ubuntu16/x86_64/lib/libsoup-2.4.so.1.8.0 /usr/lib/x86_64-linux-gnu/libssl.a /home/local/ANT/qignacio/git/DCV-viewer-gtk/deps/gtk-binaries/ubuntu16/x86_64/lib/libportaudio.so.2.0.0 /home/local/ANT/qignacio/git/DCV-viewer-gtk/deps/gtk-binaries/ubuntu16/x86_64/lib/libgthread-2.0.so.0.5600.2 /home/local/ANT/qignacio/git/DCV-viewer-gtk/deps/gtk-binaries/ubuntu16/x86_64/lib/libswscale.so.5.1.100 /usr/lib/x86_64-linux-gnu/libprotobuf-c.a /usr/lib/x86_64-linux-gnu/libcairo.so.2.11400.6 /usr/lib/x86_64-linux-gnu/libm.a /home/local/ANT/qignacio/git/DCV-viewer-gtk/deps/gtk-binaries/ubuntu16/x86_64/lib/liblz4.so.1.8.2 /usr/lib/x86_64-linux-gnu/libportaudio.a`

**Comment by nacho** [comment]
Here is the output of runnign the following commands:

```
export PKG_CONFIG_PATH="${_dir}/deps/gtk-binaries/${_flavor}/x86_64/lib/meson-pkgconfig/"
pkg-config --libs libturbojpeg
pkg-config --libs glib-2.0
pkg-config --libs gobject-2.0
pkg-config --libs gthread-2.0
pkg-config --libs gio-2.0
pkg-config --libs gio-unix-2.0
pkg-config --libs libffi
pkg-config --libs libsoup-2.4
pkg-config --libs libsasl2
pkg-config --libs portaudio-2.0
pkg-config --libs opus
pkg-config --libs openssl
pkg-config --libs libturbojpeg
pkg-config --libs libjpeg
pkg-config --libs liblz4
pkg-config --libs libavcodec
pkg-config --libs libswscale
pkg-config --libs libavutil
pkg-config --libs x264
pkg-config --libs libprotobuf-c
pkg-config --libs libpcsclite
pkg-config --libs gtk+-3.0
```

```
-L../deps/gtk-binaries/ubuntu16/x86_64/lib -lturbojpeg
-L../deps/gtk-binaries/ubuntu16/x86_64/lib -lglib-2.0
-L../deps/gtk-binaries/ubuntu16/x86_64/lib -lgobject-2.0 -lglib-2.0
-L../deps/gtk-binaries/ubuntu16/x86_64/lib -lgthread-2.0 -pthread -lglib-2.0
-L../deps/gtk-binaries/ubuntu16/x86_64/lib -lgio-2.0 -lgobject-2.0 -lglib-2.0
-L../deps/gtk-binaries/ubuntu16/x86_64/lib -lgio-2.0 -lgobject-2.0 -lglib-2.0
-L../deps/gtk-binaries/ubuntu16/x86_64/lib -lffi
-L../deps/gtk-binaries/ubuntu16/x86_64/lib -lsoup-2.4 -lgio-2.0 -lgobject-2.0 -lglib-2.0
-L../deps/gtk-binaries/ubuntu16/x86_64/lib -lsasl2
-L../deps/gtk-binaries/ubuntu16/x86_64/lib -lportaudio -lasound -lm -lpthread
-L../deps/gtk-binaries/ubuntu16/x86_64/lib -lopus
-lssl -lcrypto
-L../deps/gtk-binaries/ubuntu16/x86_64/lib -lturbojpeg
-L../deps/gtk-binaries/ubuntu16/x86_64/lib -ljpeg
-L../deps/gtk-binaries/ubuntu16/x86_64/lib -llz4
-L../deps/gtk-binaries/ubuntu16/x86_64/lib -lavcodec
-L../deps/gtk-binaries/ubuntu16/x86_64/lib -lswscale
-L../deps/gtk-binaries/ubuntu16/x86_64/lib -lavutil
-L../deps/gtk-binaries/ubuntu16/x86_64/lib -lx264
-L../deps/gtk-binaries/ubuntu16/x86_64/lib -lprotobuf-c
-lpcsclite
-L../deps/gtk-binaries/ubuntu16/x86_64/lib -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0
```

**Comment by nirbheek** [comment]
The basic issue seems to be that relative paths in `-L` arguments are interpreted differently by meson compared to a compiler in the builddir.

**Comment by nacho** [comment]
@nirbheek can you give me some pointer on where to look to try to fix this issue myself?

**Comment by nirbheek** [comment]
This patch should fix it:

```diff
--- a/mesonbuild/dependencies/base.py
+++ b/mesonbuild/dependencies/base.py
@@ -684,7 +684,11 @@ class PkgConfigDependency(ExternalDependency):
         raw_link_args = self._convert_mingw_paths(shlex.split(out_raw))
         for arg in raw_link_args:
             if arg.startswith('-L') and not arg.startswith(('-L-l', '-L-L')):
-                prefix_libpaths.add(arg[2:])
+                path = arg[2:]
+                if not os.path.isabs(path):
+                    # Resolve the path as a compiler in the build directory would
+                    path = os.path.join(self.env.get_build_dir(), path)
+                prefix_libpaths.add(path)
         system_libpaths = OrderedSet()
         full_args = self._convert_mingw_paths(shlex.split(out))
         for arg in full_args:
```

I don't have the time right now to also write a test for it, but if you could write a unit test (see: `run_unittests.py:LinuxlikeTests.test_pkgconfig*`), I'm sure we can either get it into the release (happening on Sunday) or in the next stable release.

This should be quite low-risk since relative paths in pkg-config files are very rare, and they were broken.

**Comment by nacho** [comment]
Thanks a lot! I'll get to it either today or tomorrow

**Comment by nacho** [comment]
I just tested this and it seems to work. I will now check if I manage to make an unit test.

**Comment by nacho** [comment]
The pull request is here: https://github.com/mesonbuild/meson/pull/5057
