### ISSUE TITLE
runpath stripped on ninja install

### ISSUE THREAD

**Issue by mbiebl** [mesonbuild/meson#4136]
Version: 0.47.2-1

gnome-boxes uses subprojects: https://gitlab.gnome.org/GNOME/gnome-boxes/tree/master/subprojects
In Debian, gtk-frdp and libovf-glib are not packaged as system libraries yet, so when building gnome-boxes the internal subprojects are used.
The binary in the build dir has
```
RUNPATH              $ORIGIN/../subprojects/gtk-frdp/src:$ORIGIN/../subprojects/libovf-glib/govf
```
The two libraries are installed into pkglibdir and required by the binary:
```
  NEEDED               libgtk-frdp-0.1.so
  NEEDED               libgovf-0.1.so
```
After a ninja install, the runpath is gone from the binary. The result is, that the binary crashes, as it can't find the libraries.

**Comment by mbiebl** [comment]
Is this a bug in gnome-boxes then in how it uses subprojects?

**Comment by mbiebl** [comment]
@felipeborges bringing you into the loop here

**Comment by jpakkane** [comment]
FWICT Debian guidelines seem to indicate that each package is responsible for installing non-public shared libraries to a secret location _and_ is also responsible for adding rpaths. This would seem to indicate that if gnome-boxes builds subprojects, it should set this up properly.

**Comment by jpakkane** [comment]
Something like:

```meson
if dep_object.type_name() == 'internal'
  # set up rpath
else
  # deps comr from the system, no need for rpathing
endif
```

**Comment by mbiebl** [comment]
Thanks @jpakkane 
I've filed https://gitlab.gnome.org/GNOME/gnome-boxes/issues/242
