### ISSUE TITLE
python 3.5+ dependency

### ISSUE THREAD

**Issue by mittorn** [mesonbuild/meson#4142]
I just want to build meson-depended package. Why i need to build python 3.5 for this?
It is just a build system!
Ubuntu 14.04 armhf does not have python 3.5 in repo

**Comment by nirbheek** [comment]
The last version of Meson that supported Python 3.4 was 0.44. You can install it with `pip3 install meson==0.44.1`

**Comment by amitdo** [comment]
Any reason to not close this issue?
