### ISSUE TITLE
[QUESTION] How to retrieve the Meson project version within the (C++) source code

### ISSUE THREAD

**Issue by kelson42** [mesonbuild/meson#4144]
I want to get that number (the project "version" in `meson.build`)  printed if I call:
```
$ my_soft --version
```

I failed so far to get the documentation explaining how to get that number from Meson?

**Comment by xclaesse** [comment]
Pass it in your cpp_args: executable('app', sources, cpp_args : '-DVERSION=@0@'.format(meson.project_version()))

Then in cpp file you can use VERSION define.

**Comment by kelson42** [comment]
@xclaesse Thank you, I will try this

**Comment by boazsegev** [comment]
I find it a very poor idea to have the version controlled by the `mason.build` file, especially in projects that supports multiple build systems (make, CMake, mason...).

Is there any way for mason to dynamically read the version number from an external file?

**Comment by wszqkzqk** [comment]
> Pass it in your cpp_args: executable('app', sources, cpp_args : '-DVERSION=@0@'.format(meson.project_version()))
> 
> Then in cpp file you can use VERSION define.

But vala doesn't support this🥲

**Comment by dcbaker** [comment]
Valac has a -D/—define option, you should be able to pass that to `vala_args`

**Comment by wszqkzqk** [comment]
> Valac has a -D/—define option, you should be able to pass that to `vala_args`

But Vala cannot define a value, it can only used in conditional compiling

**Comment by wszqkzqk** [comment]
I can only write a `version.vala.in` to do this.

**Comment by dcbaker** [comment]
Ah, yeah. vcs_tag() might be what you want then
