### ISSUE TITLE
Documentation request: what does "project name" mean?

### ISSUE THREAD

**Issue by tanuk** [mesonbuild/meson#415]
The reference manual doesn't explain how the first argument (the project name) to project() should be formatted. Is the project name used e.g. in tarball file names, or should it be the human readable name? For example, a project called "Awesome Thing" probably wants to use the string "awesome-thing" in some contexts, like in tarball file names.

**Comment by ignatenkobrain** [comment]
We don't do any tarballs from meson.

**Comment by jpakkane** [comment]
The ref manual has been updated with some info. There is no real established practice yet so the answer is a bit general but should hopefully be sufficiently useful for the moment.

**Comment by tanuk** [comment]
Awesome, thanks for the quick fix!
