### ISSUE TITLE
Can't use `-Dsubproject:option` format for `default_library`

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#4155]
Running `meson -Dgstreamer:default_library=static` yields:
```
|WARNING: In subproject gstreamer: Unknown options: "gstreamer:default_library"
```

I thought this already worked. @xclaesse, any ideas? :)

**Comment by xclaesse** [comment]
You cannot set built-in options on subprojects, they are global, IIRC. But the error message is clearly not helping at all.

**Comment by nirbheek** [comment]
Ah, we should probably move that builtin option to a per-subproject option. It's a pretty common use-case to only build a specific subproject as static.

**Comment by xclaesse** [comment]
I see, it makes sense, but that's something new we never supported before.

As workaround, maybe you should build with default_library=both so the master project can pick static libs from subprojects and still build a shared library?

**Comment by xclaesse** [comment]
btw, do you think it should be defined by the user with `-Dgstreamer:default_library=static` or by the master project with `subproject('foo', default_options = ['default_library=static'])`? Probably both?

**Comment by nirbheek** [comment]
Probably both, yes. The problem with `--default-library=both` is two-fold:

1) The default library for linking will still be shared

2) Some projects don't support static linking at all, f.ex., glib can't be linked statically on Windows because it does resource initialization through the `DllMain()` entry point which is only called when the DLL load. It does, however, support that on UNIX platforms
