### ISSUE TITLE
Question: "Python module" vs "Python 3 module"

### ISSUE THREAD

**Issue by martingkelly** [mesonbuild/meson#4168]
From the documentation, I can't tell when I should use the "Python module" (which supports both Python 2 and Python 3) vs. the "Python 3 module". It looks like the "Python module" is much newer. They both have very similar methods and descriptions.

Is the "Python 3" module deprecated? If so, should it be removed in favor of the more generic "Python module"?

Links to the relevant documentation here:
https://mesonbuild.com/Python-module.html
https://mesonbuild.com/Python-3-module.html

**Comment by MathieuDuponchelle** [comment]
@xclaesse yes, the previous module should IMHO be deprecated, I did not however want to make that a part of the discussion regarding the newer one :)
