### ISSUE TITLE
RFC: support a dictionary as the configuration parameter of configure_file?

### ISSUE THREAD

**Issue by axxel** [mesonbuild/meson#4218]
I like dictionaries. Any support for the following idea?
```
configure_file(output: 'config.h', configuration: {'version': '1.0'})
```

Or as a more cluttered alternative (but still better than was is available right now): give the `configuration_data()` constructor an optional dictionary argument:
```
configure_file(output: 'config.h', configuration: configuration_data({'version': '1.0'}))
```

**Comment by jpakkane** [comment]
Passing the configuration as a dictionary could be supported. The former syntax is nicer, though.

**Comment by axxel** [comment]
That sounds good. Even though I asked the question, maybe there is someone who knows the way around the source code (I have not looked at it for about 3 years) and is therefore more suited to actually implement that idea. My gut feeling is, that the changeset for this feature would only be a couple of lines?
