### ISSUE TITLE
Tests honoring environment LD_LIBRARY_PATH if set, built library not tested

### ISSUE THREAD

**Issue by csaavedra** [mesonbuild/meson#4228]
I noticed this today with libsoup's tests. If `LD_LIBRARY_PATH` is set in the environment, then the tests are run against libsoup's installed version in `LD_LIBRARY_PATH`. If unset, then tests are run against the built library.

I had to work this around like this:

```
diff --git a/tests/meson.build b/tests/meson.build
index 3ddd9707..38e1c133 100644
--- a/tests/meson.build
+++ b/tests/meson.build
@@ -96,6 +96,7 @@ endif
 env = environment()
 env.set('G_TEST_SRCDIR', meson.current_source_dir())
 env.set('G_TEST_BUILDDIR', meson.current_build_dir())
+env.prepend('LD_LIBRARY_PATH', meson.build_root() + '/libsoup')
 env.set('G_DEBUG', 'gc-friendly')
 env.set('MALLOC_CHECK_', '2')
 # This is set by Meson if empty
```

**Comment by nirbheek** [comment]
Duplicate of https://github.com/mesonbuild/meson/issues/1383

**Comment by nirbheek** [comment]
See also: https://github.com/mesonbuild/meson/issues/1635
