### ISSUE TITLE
Meson fails with "Directory already configured." when it should ignore and continue recompiling.

### ISSUE THREAD

**Issue by Valmar33** [mesonbuild/meson#4247]
In the past, Meson would just complain and then ignore, instead of failing, when attempting to setup a directory that was already setup.

The usecase here is when recompiling Mesa master with an Arch PKGBUILD which builds against precompiled and installed LLVM master packages which are updated every 6 hours. I prefer to avoid compiled Mesa from scratch everytime.

Previously, it would just recompile the relevant files, on average 100. But, now, I would be forced to wait for all 2250 or so files to be compiled from scratch.

If I add `|| true` to the end of `meson setup`, nothing gets recompiled. If I remove `build/meson-private/coredata.dat`, at least 450 files get recompiled every time, without fail. Which is annoying.

Does Meson really have to fail with an error if the directory is already setup? Can it just not continue to issue a warning like before, and then just continue?

**Comment by Valmar33** [comment]
PKGBUILD I build with: https://paste.kde.org/p0euvsgxu

**Comment by Valmar33** [comment]
I should also have added that it last worked with 0.47.2, but is failing with 0.48.0.

**Comment by Valmar33** [comment]
Oh, right `--reconfigure` exists... nevermind...

**Comment by Valmar33** [comment]
I guess this was a regression, after all! I couldn't see what was wrong with the code, so I just gave up. :/

Good thing I noticed this, anyways. :)

**Comment by Valmar33** [comment]
Okay, it turns out the problem is still there...

I installed Meson master, tried running `meson setup`, and it still exits complaining. I'm unsure as to what the problem actually is, now.

**Comment by Valmar33** [comment]
Oh, wait, that might be because it actually hasn't been committed yet. Ignore this...

**Comment by xclaesse** [comment]
Right, the PR is waiting for @nirbheek and/or @jpakkane to review it first. But if you can, please apply it so you can confirm it fix your issue.
