### ISSUE TITLE
In case any test fails, let it run in terminal

### ISSUE THREAD

**Issue by agauniyal** [mesonbuild/meson#425]
As title says, atleast when a test fails, either execute it on terminal or let the output run on terminal instead of just capturing output and showing it afterwords. I'm requesting this because when you use capture and display, many test frameworks disable colouring/other formatting, because they're not directly outputting to a terminal. And when errors are in big numbers, non-formatted errors are hard to read compared to some nicely formatted errors.

My current workaround is to directly execute the generated binaries in test directory to see the output.

**Comment by jpakkane** [comment]
It's not possible to grab the output afterwards. The only way to get the output to both screen and log is to run the test twice. This becomes very confusing if the test behaves nondeterministically.

Many frameworks have command line switches to always force coloring on, you might want to check if yours does and, if not, file a bug on the framework in question.
