### ISSUE TITLE
regression: mesa x86_64 -> x86 compilation broken with meson 0.48

### ISSUE THREAD

**Issue by dcbaker** [mesonbuild/meson#4254]
Commit 16fa65730469dacbdb9374858c090fe59c1aa70c adds code that checks that if a compiled file is used as a generator that it is either native to the build_machine or there is an exe wrapper. There are some cases where the build machine can run host machine binaries without an emulation layer, such as when building x86 code on an x86_64 machine of the same OS.

**Comment by rossburton** [comment]
Can you entirely rely on that?  If cross-building from x86 to x86 it's perfectly possible that the actual binaries are not really usable (loader not available, use of instructions that are not on the host, etc).

**Comment by nirbheek** [comment]
That's why we have the `needs_exe_wrapper` property in the cross file. You would set it to `true` in that case.

**Comment by devurandom** [comment]
#3327 refers to the same issue.

**Comment by nirbheek** [comment]
The fix for this was accidentally not added to 0.48.1 because the PR that fixes it wasn't in it. Adding to a new 0.48.2 milestone.
