### ISSUE TITLE
Meson does not properly uses CXXFLAGS in compiler test

### ISSUE THREAD

**Issue by ePirat** [mesonbuild/meson#4272]
Meson should use CXXFLAGS env variable for compiler tests, it does for some but not for others.

Here the `has_library` test (remove some unnecessary info):

```
Running compile:
Command line:  c++ -I/Users/epirat/Projects/Misc/plprefix/include -L/Users/epirat/Projects/Misc/plprefix/lib /var/folders/rw/l97gj1cd6vd_wrf_zjcbycjc0000gn/T/tmpnho14245/testfile.cpp -pipe -o /var/folders/rw/l97gj1cd6vd_wrf_zjcbycjc0000gn/T/tmpnho14245/output.exe -O0 -fpermissive -lSPVRemapper -Wl,-undefined,dynamic_lookup 
```

As can be seen, meson properly uses the `CXXFLAGS` `-I/Users/epirat/Projects/Misc/plprefix/include`.

Here the `get_define`:

```
Running compile:
Command line:  c++ /var/folders/rw/l97gj1cd6vd_wrf_zjcbycjc0000gn/T/tmph8m3486_/testfile.cpp -pipe -E -P -O0 -fpermissive 
```

As can be seen, it lacks the `CXXFLAGS`.

This is very inconsistent, and leads to weird bugs, even worse than before as now it finds the library but fails with a (for the user) inexplicable other error because headers of that library are not properly found.

**Comment by nirbheek** [comment]
That function only reads `CPPFLAGS` since it only runs the C preprocessor. However, I've changed my mind on this subject and I agree that we should get rid of the distinction, and read `CFLAGS` and `CXXFLAGS` even for preprocess-only compiler functions.

**Comment by ePirat** [comment]
Ah thanks, will try to use the `CPPFLAGS` env variable then for now!
