### ISSUE TITLE
need 'wayland-protocols' ['>= 1.12'] found '1.7'. but (1.13-1) Installed

### ISSUE THREAD

**Issue by MasterCATZ** [mesonbuild/meson#4290]
aio@aio:/mnt/Install/gitclone/gtk$ meson _build .
The Meson build system
Version: 0.48.999
Source dir: /mnt/Install/gitclone/gtk
Build dir: /mnt/Install/gitclone/gtk/_build
Build type: native build
Project name: gtk+
Project version: 3.94.0
Native C compiler: ccache cc (gcc 7.3.0 "cc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Has header "crt/externs.h": NO
Has header "dev/evdev/input.h": NO
Has header "dlfcn.h": YES
Has header "ftw.h": YES
Has header "inttypes.h": YES
Has header "linux/input.h": YES
Has header "linux/memfd.h": YES
Has header "locale.h": YES
Has header "memory.h": YES
Has header "stdint.h": YES
Has header "stdlib.h": YES
Has header "strings.h": YES
Has header "string.h": YES
Has header "sys/mman.h": YES
Has header "sys/param.h": YES
Has header "sys/stat.h": YES
Has header "sys/sysinfo.h": YES
Has header "sys/systeminfo.h": NO
Has header "sys/time.h": YES
Has header "sys/types.h": YES
Has header "unistd.h": YES
Library m found: YES
Checking for function "dcgettext" : YES
Checking for function "getpagesize" : YES
Checking for function "getresuid" : YES
Checking for function "lstat" : YES
Checking for function "mmap" : YES
Checking for function "nearbyint" : YES
Checking for function "posix_fallocate" : YES
Checking for function "_lock_file" : NO
Checking for function "flockfile" : YES
Checking for function "mkstemp" : YES
Checking for function "mallinfo" : YES
Checking for function "round" : YES
Checking for function "rint" : YES
Checking for function "log2" : YES
Checking for function "exp2" : YES
Checking for function "sincos" : YES
Header <math.h> has symbol "isinf": NO
Header <math.h> has symbol "isnan": NO
Compiler for C supports arguments -fno-strict-aliasing: NO
Compiler for C supports arguments -Wpointer-arith: NO
Compiler for C supports arguments -Wmissing-declarations: NO
Compiler for C supports arguments -Wimplicit-function-declaration: NO
Compiler for C supports arguments -Wformat=2: NO
Compiler for C supports arguments -Wformat-nonliteral: NO
Compiler for C supports arguments -Wformat-security: NO
Compiler for C supports arguments -Wstrict-prototypes: NO
Compiler for C supports arguments -Wmissing-prototypes: NO
Compiler for C supports arguments -Wnested-externs: NO
Compiler for C supports arguments -Wold-style-definition: NO
Compiler for C supports arguments -Wundef: NO
Compiler for C supports arguments -Wunused: NO
Compiler for C supports arguments -Wcast-align: NO
Compiler for C supports arguments -Wmissing-noreturn: NO
Compiler for C supports arguments -Wmissing-format-attribute: NO
Compiler for C supports arguments -Wmissing-include-dirs: NO
Compiler for C supports arguments -Wlogical-op: NO
Compiler for C supports arguments -Wswitch-default: NO
Compiler for C supports arguments -Wswitch-enum: NO
Compiler for C supports arguments -Wignored-qualifiers: NO
Compiler for C supports arguments -Werror=redundant-decls: NO
Compiler for C supports arguments -Werror=implicit: NO
Compiler for C supports arguments -Werror=nonnull: NO
Compiler for C supports arguments -Werror=init-self: NO
Compiler for C supports arguments -Werror=main: NO
Compiler for C supports arguments -Werror=missing-braces: NO
Compiler for C supports arguments -Werror=sequence-point: NO
Compiler for C supports arguments -Werror=return-type: NO
Compiler for C supports arguments -Werror=trigraphs: NO
Compiler for C supports arguments -Werror=array-bounds: NO
Compiler for C supports arguments -Werror=write-strings: NO
Compiler for C supports arguments -Werror=address: NO
Compiler for C supports arguments -Werror=int-to-pointer-cast: NO
Compiler for C supports arguments -Werror=pointer-to-int-cast: NO
Compiler for C supports arguments -Werror=empty-body: NO
Compiler for C supports arguments -Werror=write-strings: NO
Checking if "-Wl,-Bsymbolic" links: YES
Checking if "-Wl,-z,relro" links: YES
Checking if "-Wl,-z,now" links: YES
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Dependency glib-2.0 found: YES 2.56.2
Dependency gobject-2.0 found: YES 2.56.2
Dependency gio-unix-2.0 found: YES 2.56.2
Dependency gmodule-2.0 found: YES 2.56.2
Dependency cairo found: YES 1.15.10
Dependency cairo-gobject found: YES 1.15.10
Dependency pango found: YES 1.42.3
Dependency pangoft2 found: YES 1.42.3
Dependency freetype2 found: YES 21.0.15
Dependency pangocairo found: YES 1.42.3
Dependency gdk-pixbuf-2.0 found: YES 2.36.11
Dependency epoxy found: YES 1.4.3
Dependency atk found: YES 2.28.1
Dependency harfbuzz found: YES 1.7.2
Dependency xkbcommon found: YES 0.8.0
Dependency graphene-gobject-1.0 found: YES 1.8.0
Dependency iso-codes found: YES 3.79
Dependency cairo-xlib found: YES 1.15.10
Dependency cairo found: YES (cached)
Dependency wayland-client found: YES 1.15.0
Dependency wayland-protocols found: NO found '1.7' but need: '>= 1.12'
Dependency wayland-protocols found: NO 

meson.build:467:2: ERROR:  **Invalid version of dependency, need 'wayland-protocols' ['>= 1.12'] found '1.7'.**

A full log can be found at /mnt/Install/gitclone/gtk/_build/meson-logs/meson-log.txt
aio@aio:/mnt/Install/gitclone/gtk$ sudo apt install  wayland-protocols
Reading package lists... Done
Building dependency tree       
Reading state information... Done
**wayland-protocols is already the newest version (1.13-1).**
0 to upgrade, 0 to newly install, 0 to remove and 59 not to upgrade.
aio@aio:/mnt/Install/gitclone/gtk$ meson -v
**0.48.999**
aio@aio:/mnt/Install/gitclone/gtk$

**Comment by jon-turney** [comment]
Please can you show the output of `pkg-config --debug --modversion wayland-protocols` ?

**Comment by yartem** [comment]
On Arch, installing package `wayland` solved the problem: `yay -Sy wayland`. So maybe installing [ubuntu's](https://packages.ubuntu.com/source/bionic/wayland) package will help for you.

**Comment by ericonr** [comment]
Can this be closed? Reporter is inactive.
