### ISSUE TITLE
Add dependency('dl') or export_dynamic for shared library

### ISSUE THREAD

**Issue by StidOfficial** [mesonbuild/meson#4297]
Hello,

I have a `shared_library()` can open dynamic library with `dlopen()` on my C++ project.

I use `dl_dep = meson.get_compiler('c').find_library('dl', required : true)` for enable `-ldl` argument on my compile.
And add this `dl_dep` on `shared_library(..., dependencies: [dl_dep], ...)`, because the `export_dynamic` is not available on `shared_library()`.

It's possible to add `dependency('dl')` like `dependency('threads')` or add `export_dynamic` on `shared_library` ?

Edit : I use a plugins system and plugins is manager by my `shared_library()`. My plugins is internal and external `shared_module()` is not necessarily included to my main `shared_library()`.

**Comment by NickeZ** [comment]
I think you might want to look at shared module instead of shared library: http://mesonbuild.com/Reference-manual.html#shared_module

**Comment by StidOfficial** [comment]
> I think you might want to look at shared module instead of shared library: http://mesonbuild.com/Reference-manual.html#shared_module
> 
> Edit: or actually, is the problem that you want to call functions in your shared library from your shared module?

Yes, excuse me i use `shared_module`. The problem is than i hava a plugin system and the plugin is not specially register on my `shared_library()`. Because my project have a possibility to compile a custom plugin outside of my main project.



> Also note that this is transitory, because glibc developers have decided to move dl, pthread, lm et al to glibc proper so it will work out of the box just like on every other platform.
> 
> In the mean time you should use `dl_dep = cc.find_library('dl', required : false)` which is portable.

A version as release on glibc to contains all of this ?

**Comment by a-vrma** [comment]
> Also note that this is transitory, because glibc developers have decided to move dl, pthread, lm et al to glibc proper so it will work out of the box just like on every other platform.

Seems to still be an issue on glibc 2.32 released this August.

> In the mean time you should use dl_dep = cc.find_library('dl', required : false) which is portable.

This works but gives a confusing message on a OS like OpenBSD, which doesn't
even have a dummy libdl. There, the user gets a confusing `Library dl found: NO`. Is there any better workaround?

**Comment by eli-schwartz** [comment]
What is confusing here? It correctly stated it didn't find a library by this name, but then continued, indicating it doesn't need the library.

You could use `build_machine.system()` to only check for this on OSes likely to need this.

If you need something that works as a dependency object, you can use this (does no logging):
```
dependency('', required: false)
```

**Comment by a-vrma** [comment]
I was thinking about a specific case where a feature requires `dlopen`/`dlsym`
or `LoadLibraryExA` on Windows and I was passing a feature object as the
`required` kwarg. Now that I think about it, it makes more sense to use
`summary` to show which features are enabled or not. I will have to go back to
using boolean Meson options, though.

> You could use build_machine.system() to only check for this on OSes likely to need this.

Did you mean something like this:

    if host.machine.system() == 'linux'
        dl_dep = cc.find_library('dl', required: false)
    else
        dl_dep = dependency('', required: false)
    endif

That seems like a pretty good solution.

**Comment by dcbaker** [comment]
Here's the problem, it's not Linux that has a separate libdl, it's glibc. So you need that for gnu/kfreebsd, but you might not when using Linux with bionic c. The best solution is really just the find library with required set to false, without exception. Solaris with the Oracle compatible libc doesn't have libdl, btw.

**Comment by eli-schwartz** [comment]
The point of my suggestion for the OS check is, if it's bothersone to *log to the console* "Library dl found: NO" then one could skip the logging on non-Linux OSes, and only check on Linux, but even on Linux if using non-glibc it would produce "confusing" logs.

I don't really think this is worth caring about, but it's theoretically possible.

**Comment by dcbaker** [comment]
In Mesa we do it the other way, we do:
Have dlopen?
If no; have libdl, have dlopen with libdl?

Sorry, I'm on my phone

**Comment by Tachi107** [comment]
I think that this issue could be closed
