### ISSUE TITLE
Different project languages for native vs cross build 

### ISSUE THREAD

**Issue by cgimenez** [mesonbuild/meson#4310]
Hi, I'm doing some experiments with a project that is ['cpp', 'objc', 'objcpp'] language based on OSX but ['cpp'] only when cross compiled.

Leaving 'objc', 'objcpp' when cross compiling obviously produces a fatal error because no such compilers are availables in the cross configuration.

I naively tried to enclose the project() statement in a conditional block but this is not allowed because project() must be the first statement in a meson.build file.

There is certainly something I'm am missing, but I wonder if it could be a Meson's limitation ?

**Comment by tp-m** [comment]
This might help: http://mesonbuild.com/Reference-manual.html#add_languages

**Comment by cgimenez** [comment]
Thanks a lot ! Spent hours reading documentation but I missed this one ;-)
