### ISSUE TITLE
Support for "C++20" modules

### ISSUE THREAD

**Issue by gdelazzari** [mesonbuild/meson#4314]
I was wondering if there's someone else interested (or even working) on a first implementation to support the upcoming C++20 modules (not sure if they're actually part of the upcoming C++20, but seems like so). Clang is already supporting some of the syntax and stuff, I can actually compile a module and a program that imports it using such a Makefile:

```Makefile
program: program.cpp stuff.pcm
	clang++ -fmodules-ts -std=c++17 -fmodule-file=stuff.pcm -o program program.cpp stuff.pcm

stuff.pcm: stuff.cppm
	clang++ -fmodules-ts -std=c++17 --precompile -o stuff.pcm stuff.cppm
```

with `import stuff;` in program.cpp and `export` statements in stuff.cppm.

As you can see by the Makefile it's a bit cumbersome to manually handle the compilation. I know this is not yet a final implementation/feature, but I think it's something it would be cool to experiment with for small projects. A build system like Meson handling it would be amazing, build times should also improve (that's one of the promoted reasons for modules in C++).

Is there anyone else interested or someone that wants to share its opinion?

**Comment by gdelazzari** [comment]
Thanks for the information. If I may ask, what's the problem with the current syntax/what syntax would be better? I mean, what are your points?

**Comment by jpakkane** [comment]
The tl/dr version is that the model as currently defined does the same thing as FORTRAN, which is a nightmare to support in a build system.

**Comment by diegor8** [comment]
any updates ? has the module system proposal already been stabilized ?

**Comment by diegor8** [comment]
there is an ongoing discussion at
https://github.com/mesonbuild/meson/issues/5024 , this thread can be closed now

**Comment by dcbaker** [comment]
I'm going to go ahead and close this so we can keep all of the modules discussion in the other issue.
