### ISSUE TITLE
Incorrect warning: Output file "@BASENAME@" for configure_file() overwrites configure_file() output

### ISSUE THREAD

**Issue by 1ace** [mesonbuild/meson#4323]
#3814 introduced a warning if two `configure_file()` output to the same file.

However, it looks like it does this check before performing the necessary substitutions, such as `@BASENAME@`, resulting in this incorrect warnings:
```
WARNING: Output file "@BASENAME@" for configure_file() at meson.build:268 overwrites configure_file() output at meson.build:251
```

To reproduce:
```meson

configure_file(
￼   input: 'foo.in',
￼   output: '@BASENAME@',
￼   configuration: conf
￼ )
configure_file(
￼   input: 'bar.in',
￼   output: '@BASENAME@',
￼   configuration: conf
￼ )
```
(Should probably be added to `test cases/common/16 configure file/meson.build` by the PR that fixes this bug)

**Comment by nirbheek** [comment]
Hah, that's funny. Good thing it was a warning and not an error!

**Comment by behlec** [comment]
I will fix it.
