### ISSUE TITLE
Greater-than comparison of an unknown version yields true

### ISSUE THREAD

**Issue by ernestask** [mesonbuild/meson#4329]
Trying to build tracker-miners with some dependencies missing results in rather interesting errors. I’m missing libcue-devel in my Fedora installation, but the support for it is optional, depending on whether it was found and which version was found: https://gitlab.gnome.org/GNOME/tracker-miners/blob/f9e7de0fe0549b009defc68ba37ba2516a03f49c/meson.build#L317, however, the code ends up trying to include one of the headers anyway.

Adding a debug print for `libcue.version()` yields “unknown”, but then printing `libcue.version() >= '2.0.0'` results in “True”.

**Comment by ernestask** [comment]
I guess one could argue that there should be another `libcue.found()` check, but I’m thinking that “unknown” version comparisons should always be false.

**Comment by ernestask** [comment]
I forgot to mention that the version I’m using right now is 0.48.0.

**Comment by jon-turney** [comment]
```
conf.set('HAVE_LIBCUE2', libcue.version() >= '2.0.0')
```

This is a string comparison. I guess `libcue.version().version_compare('>=2.0.0')` is what's meant, but I'm not sure that will work as expected.

> but I’m thinking that “unknown” version comparisons should always be false.

Yeah, I agree.  That's implemented for `dependency(version:)` constraints (6a4c2d63), but I don't think `version_compare` does the right thing for`unknown` yet.

**Comment by ernestask** [comment]
It seems to do the right thing, thanks! And sorry for the noise.

**Comment by jon-turney** [comment]
> It seems to do the right thing, thanks!

I think `version_compare()`  only happens to work here because it compares the first element of the versions (`unknown` and `2`) and considers alphabetic elements less than numeric ones.

This won't work as expected ('“unknown” version comparisons should always be false') if the comparision was the other way round e.g. `'unknown'.version_compare('<=2.0.0')`, or when applied to a version where the first element is alphabetic.  e.g. `'unknown'.version_compare('>=alpha')`.

> And sorry for the noise.

No problem.  Thanks for raising this issue.

**Comment by ernestask** [comment]
> I think `version_compare()` only happens to work here because it compares the first element of the versions (`unknown` and `2`) and considers alphabetic elements less than numeric ones.

Yeah, I see it now:
https://github.com/mesonbuild/meson/blob/646a073e36fb273f3267ecd424502c4d8480c0bb/mesonbuild/mesonlib.py#L442

> This won't work as expected ('“unknown” version comparisons should always be false') if the comparision was the other way round e.g. `'unknown'.version_compare('<=2.0.0')`, or when applied to a version where the first element is alphabetic. e.g. `'unknown'.version_compare('>=alpha')`.

Was there ever a discussion about such cases and whether `version()` on a dependency that hasn’t been found should return a value? Seems easier than making sure that version comparison works intuitively 100% of the time.

**Comment by ernestask** [comment]
Maybe a special `Version` object could be returned that unconditionally returns false in `__cmp__()` et al.
