### ISSUE TITLE
install_man should allow specifying compression type (or none)

### ISSUE THREAD

**Issue by hanetzer** [mesonbuild/meson#4330]
Various distros have their own rules for installing compressed man files. For example, gentoo
uses bzip2. One should be able to specify which compression type to use, or none at all, both
in the meson.build file itself or via the meson call (`meson --man-compress=[none|gzip|bzip2|...]`
or the like.

**Comment by jpakkane** [comment]
I'm starting to think that the entire compression thing was a mistake. Every distro already has code to compress man pages in the exact way that they want to. There is little point in adding a gazillion toggle switches to Meson then there already is a mechanism that works reliably.

**Comment by hanetzer** [comment]
@jpakkane sure, that's valid as well.

**Comment by SoapGentoo** [comment]
@jpakkane yes please, let's remove it. Man page compression is a system integration task, and not a build system task. Every package manager does it slightly different, and it just makes distro work so much harder.

**Comment by mgorny** [comment]
@jpakkane do you need us to make a pull request for this? (it seems relatively simple to do but I might be mistaken)

**Comment by jpakkane** [comment]
On Fri, Oct 19, 2018 at 10:51 AM Michał Górny <notifications@github.com> wrote:

> @jpakkane do you need us to make a pull request for this? (it seems relatively simple to do but I might be mistaken)

By all means.
