### ISSUE TITLE
cross compile: c_args provided by cross file cannot obtained by get_option()

### ISSUE THREAD

**Issue by yuwata** [mesonbuild/meson#4331]
When cross file contains the following,
```
[properties]
c_args = ['-I/path/to/something/include', '-I/path/to/different/include']
```
the value cannot be obtained by `get_option('c_args')`.

Please also see the discussion in https://github.com/systemd/systemd/issues/10288.

**Comment by jpakkane** [comment]
`c_args` contains the native build flags. Cross args should be in `cross_c_args` but that seems to be not done yet (or at least they are not visible in `meson configure`).

**Comment by floppym** [comment]
I think it would make more sense to have a single way to get build flags for the host compiler. Otherwise, you would need logic like this:
```
if cross_compling
   args = get_option('cross_c_args')
else
   args = get_option('c_args')
fi
```
It seems like it would make more sense to access them via some method on the compiler object.

**Comment by bredelings** [comment]
Sometimes a single project uses both a native compiler and a cross-compiler in a build, so that you need both sets of flags.  For example if you build a tool natively (`c_args`) and then run it to generate some code, and then compile that code with the cross compiler (`cross_c_args`).  I think any solution has to handle that use case.

**Comment by floppym** [comment]
> Sometimes a single project uses both a native compiler and a cross-compiler in a build, so that you need both sets of flags.

I was thinking something like this, which would satisfy that use case.
```
native_cc = meson.get_compiler('c', native : true)
native_cc_args = native_cc.args()

host_cc = meson.get_compiler('c')
host_cc_args = host_cc.args()
```

**Comment by bredelings** [comment]
Hmm... I haven't thought about this very deeply or carefully, but that seems to be somewhat consistent with other uses of the `native` flag...

**Comment by Ericson2314** [comment]
#5263 will fix this. `c_args` provides the host machine arguments, and `build.c_args` provides the build machine arguments. Both of these work in native and cross builds so you don't have to special-cases those in your `meson.build` file.

**Comment by Ericson2314** [comment]
Should be closed? I guess we might need a new test.

**Comment by yuwata** [comment]
Thanks.
