### ISSUE TITLE
Separate parsing of cross file from downstream logic

### ISSUE THREAD

**Issue by Ericson2314** [mesonbuild/meson#4332]
This picks up where #3993 left off, doing for the rest of the file what that did for `[host_machine]`. Firstly, it is good engineering practice to have a clean pipeline by separating parsing from other logic (in code, if not at run time as interleaving can still be achieved via laziness). Secondly, this will do a large portion of the work of abstracting over the cross-vs-native-dependent portions of the code base. Third, this allows easier modifying of the surface syntax, as proposed in e.g. #3972 or #3282 

Here's an incomplete TOOD:

- [x] `[host_machine]` `[target_machine`] `MachineInfo` abstracts over cross file vs environment detection.
  - ~~#3993~~

- [x] `[binaries]` Should abstract over cross file vs environment variable vs default sources of truth. #4326 is convenient for the `PerMachine` abstraction which will allow us to conveniently store tools per machine. Unclear if due to dependence on other platform inference this can happen up front or it needs to happen lazily so as to take place after the former. `_get_compiler` in `environment.py` is a good guide. Unclear whether overlaps with the various lists compilers are stored.
  - ~~#4338~~
  - ~~#4445~~

- [x] `[properties]` Unfortunately defined as open-ended so not much we can do for structure. But we should use `PerMachine` to open the door to differentiating the build host and target machines' additional properties. The compiler options should all be added to per_machine option maps, so everything is taken from `coredata.compiler_options.*` and never `environment.properties` directly. #4626 and #4772 address this last bit.
  - ~~#4445~~
  - ~~#4626~~
  - ~~#4772~~

After all is complete, `self.cross_info` should no longer exist to make ad-hoc inspection impossible. This wasn't attempted in https://github.com/mesonbuild/meson/pull/4010 but in conjunction with that will finish the job of making cross not special. I actually now think it is better to do this before most of that, hence why I am writing this issue now.

CC @nirbheek

**Comment by jpakkane** [comment]
>  which will allow us to conveniently store tools per machine

This would indicate that there can be up to three different versions of any tool:

 - build machine tool
 - host machine tool
 - target machine tool

When would this be useful? The current model has only two types of tools, those you run natively and those that don't (i.e. are built with the native compiler vs the cross compiler) and it seems to work well in practice.

**Comment by Ericson2314** [comment]
So right now meson doesn't really do anything with the target machine. That's fine, the target machine is very niche. If we just do build and host we stick with two, and no new functionality is added.

The target machine becomes more important when one wishes to distinguish between a cross compiler and a cross compiler compiler. The libraries run on the target platform, while the compiler runs on the host platform. Cross compiler is build = host != target, while cross compiled compiler is build != host = target. So there's still only one native compiler and one cross compiler, but the 2 compilers fit in the 3 "slots" differently based on what the user wants to build.

The target platform becomes most useful in the Canadian cross case, where build != host != target, and one needs two different cross compilers and can't conflate any of the 3 slots.

My personal take:

1. is that canadian cross isn't useful, but it's so easy to support 3 (or more!) Bootstrapping stages / machines with these sorts of refactors (essentially free) we might as well do so say we can do everything autotools can.

2. Since we have some but unfinished support for the target platform, it's better to go all or nothing lest people get confused or worse complain they were duped.

3. I want to do a little demo of buding GCC with Meson after I finish the cross changes I've planned, and I don't want any old timer GCC person to complain X or Y isn't possible anymore. :)

**Comment by Ericson2314** [comment]
#4445 does the rest of this.

**Comment by Ericson2314** [comment]
Yay! This is finally all done!
