### ISSUE TITLE
Feature Request: compiler.compute_int()

### ISSUE THREAD

**Issue by tp-m** [mesonbuild/meson#435]
Need the ability to extract the int values of certain defines that can be determined at compile time, basically a more generic variant of what the compiler.sizeof() check does.

If we're not cross-compiling, the code is pretty much exactly the same.

If we're cross-compiling we'd have to do something slightly different, but it should still be possible. The current code just tries to compile code with values from 1 to 1024 in a loop in such a way that compilation will fail if it's not the value, but it's probably not a good idea to try all values from 0 to MAXINT. It should be possible to bisect though by using code such as

```
#if FOO > 144
#error "larger"
#endif
```

One could check what AC_COMPUTE_INT() does if one can find the actual implementation.

**Comment by nirbheek** [comment]
I don't think we need to use the same mechanism as `sizeof()`. For defines we can write the preprocessed output to a file and search for the value in the output.

**Comment by ieei** [comment]
Maybe it would be nice to have both `compute_int()` and `define_value()`/`macro_value()` ? As `AC_COMPUTE_INT()` isn't restricted to defines.
