### ISSUE TITLE
pot command outputs to srcdir instead of builddir

### ISSUE THREAD

**Issue by jbicha** [mesonbuild/meson#4352]
The _pot_ command outputs its `.pot` to the source directory instead of to the build directory. This is annoying for people who want to keep their source directory clean.

Documentation
------------------
https://mesonbuild.com/Localisation.html

Test Case
------------
```
git clone https://gitlab.gnome.org/GNOME/gnome-mines
meson builddir
ninja -C builddir gnome-mines-pot
```

What Happens
-------------------
`po/gnome-mines.pot` is created

What I Expected
---------------------
`builddir/po/gnome-mines.pot` is created

System Info
--------------
* meson 0.47.2
* Ubuntu 18.10

**Comment by eli-schwartz** [comment]
Isn't this kind of literally the entire purpose of the command? Its purpose is to be used by upstream maintainers checking in new versions before release.
