### ISSUE TITLE
cc.has_function() requires correct includes

### ISSUE THREAD

**Issue by tp-m** [mesonbuild/meson#437]
In autoconf this just works (for example):

    AC_CHECK_FUNCS(setenv unsetenv)

whereas in meson this doesn't work:

    cc.has_function ('setenv')

but this does:

    cc.has_function ('setenv', prefix : '#include <stdlib.h>')

which is a bit unfortunate, because (a) it's more tedious especially if there are multiple includes and things like _GNU_SOURCE need to be defined, and (b) the required includes are not necessarily the same on all platforms.

**Comment by tp-m** [comment]
In addition, there may also be something wrong (or at least different) with how autotools and meson check for a function.  ```cc.has_function('lchmod', prefix : '#include <sys/stat.h>\n#include <unistd.h>')``` works in meson but ```AC_CHECK_FUNC(lchmod)``` fails because the test program fails to compile because of

    #if defined __stub_lchmod || defined __stub___lchmod
    choke me
    #endif

Maybe this warrants a different bug, but I think the fix may be the same for both.

**Comment by jpakkane** [comment]
Why is the `__stub_lchmod` there and is this specific to lchmod or are there corresponding defines for other functions as well?

**Comment by nirbheek** [comment]
__stub_.* symbols are defined in <gnu/stubs.h> and pulled in by <features.h> . The purpose is to have stubs for syscalls that aren't supported by the underlying kernel (but glibc needs to export those symbols anyway). They're supposed to just return failure and set errno to ENOSYS.

So, to actually test if a glibc syscall is available on the system, you need to check that __stub functions aren't defined. Contents of stubs-64.h for me:

```
/* This file is automatically generated.
   It defines a symbol `__stub_FUNCTION' for each function
   in the C library which is a stub, meaning it will fail
   every time called, usually setting errno to ENOSYS.  */

#ifdef _LIBC
 #error Applications may not define the macro _LIBC
#endif

#define __stub_bdflush
#define __stub_chflags
#define __stub_fattach
#define __stub_fchflags
#define __stub_fdetach
#define __stub_getmsg
#define __stub_gtty
#define __stub_lchmod
#define __stub_putmsg
#define __stub_revoke
#define __stub_setlogin
#define __stub_sigreturn
#define __stub_sstk
#define __stub_stty
```
