### ISSUE TITLE
Proxy targets

### ISSUE THREAD

**Issue by yshui** [mesonbuild/meson#4371]
When you have a bunch of `build_by_default: false` targets, it can be useful if you can build all of them by building a proxy target that has dependency on all of them.

This could probably be done with `custom_target` and its `depends` argument, but since it `command` is required, it feels hacky to put some random command there.

**Comment by dcbaker** [comment]
a pretty easy way to handle this already is with an option, add an option like `build-optional`, make it bool, set it to false by default, and then set the `build_by_default` flag to `get_option(build-optional)`

**Comment by yshui** [comment]
@dcbaker Advantage of having proxy targets is that you don't need to re-configure.

**Comment by eli-schwartz** [comment]
Implemented in #5606 as `alias_target()`.
