### ISSUE TITLE
meson test --gdb: allow other programs than plain gdb

### ISSUE THREAD

**Issue by gerion0** [mesonbuild/meson#4373]
`meson test --gdb` is really useful. However, I'd like to use [cgdb](https://cgdb.github.io/) that has exactly the same command line arguments like gdb but also a nice curses interface. I assume that there exist a bunch of other gdb wrappers, that also behave like gdb w.r.t the command line.

Could you add an argument to `meson test` to accept arbitrary paths (or additional options) for the "gdb"-binary, like `meson test --gdb --gdb-path /usr/bin/cgdb`?

**Comment by jpakkane** [comment]
Sure, that would also be convenient for people who want to use a custom gdb (like one they have built from Git trunk). Resources are sadly limited, but patches are welcome.

**Comment by gerion0** [comment]
The referenced commit fixes this bug.
