### ISSUE TITLE
Visual Studio 2015 support

### ISSUE THREAD

**Issue by nioncode** [mesonbuild/meson#439]
While playing around with #429 I noticed that there are a few subtle differences between how Visual Studio 2010 and 2015 handle project / solution files.

I want to bring in vs2015 support for meson and discuss the best way for doing this.
Should I add it as a separate backend (sharing most of the code in a super class, of course) like CMake does or just control the version with backend options, once I implemented those? I feel like a separate backend is cleaner.

BTW: Is there any reason why meson started with vs2010 in the first place and did not use vs2015 right away?

**Comment by jpakkane** [comment]
Meson supports vs2010 because the only Windows I have is a crappy old XP in a vm. The newest you can run on it is 2010.

The separate backend seems nicer. I would imagine 2010 goes away at some point and dropping the entire class is easier than surgically removing if/elses.
