### ISSUE TITLE
/permissive- support on MSVC

### ISSUE THREAD

**Issue by ubsan** [mesonbuild/meson#4391]
I'd really like to get rid of this hack: https://github.com/ubsan/ublib/blob/master/meson.build#L14

**Comment by jpakkane** [comment]
When it comes to compiler flags and such, eventually when you get to flags that are rare enough, it does not make sense to add a full option for those, but instead have people add them manually with compiler flags.

That being said we have not had _that_ many Windows users and especially developers so we don't really have a good grasp on which VS flags would be important enough to add and especially if there are similar options for other compilers so we could have only one option that works cross platform.

In this particular case it would seem that `/permissive-` is roughly the same as `-Wpedantic` on GCC, which we add on warning level 3. Would that make sense as a default on VS also or should we do something different?

**Comment by ubsan** [comment]
It's a breaking change, but I might even add `vc++1n` options, for similarity with `gnu++` options, which don't set `/permissive-`; then, the `cpp_std` options would set `/permissive-` by default.

**Comment by ubsan** [comment]
@nioncode this was fixed by #4403

**Comment by nioncode** [comment]
Sweet, thanks.
