### ISSUE TITLE
Unknown CPU family 'powerpc'

### ISSUE THREAD

**Issue by pkubaj** [mesonbuild/meson#4397]
I'm using meson to build a program.

I'm getting this warning:
`WARNING: Unknown CPU family 'powerpc', please report this at https://github.com/mesonbuild/meson/issues/new with theoutput of `uname -a` and `cat /proc/cpuinfo``

uname -a:
`FreeBSD XXX 12.0-BETA1 FreeBSD 12.0-BETA1 #7 r339445M: Sat Oct 20 02:36:21 CEST 2018     root@:/usr/obj/usr/src/powerpc.powerpc64/sys/GENERIC64  powerpc`

Since this is FreeBSD, there's no `/proc/cpuinfo`.

Excerpt from dmesg:
```
cpu0: IBM POWER9 revision 2.2, 2700.00 MHz
cpu0: Features dc007182<PPC32,PPC64,ALTIVEC,FPU,MMU,SMT,ISNOOP,ARCH205,ARCH206,VSX,TRUELE>
cpu0: Features2 eee00000<ARCH207,HTM,DSCR,ISEL,TAR,VCRYPTO,ARCH300,IEEE128,DARN>
```

**Comment by jpakkane** [comment]
Could you answer a few more questions so we can get the detection logic working [and documented](https://mesonbuild.com/Reference-tables.html#cpu-families) properly.

Is `powerpc` the same on FreeBSD as `ppc32/64` is on Linux?

Are there cases where FreeBSD returns `ppc32` as the architecture? As an example it might return `ppc` for old ppc chips and `powerpc` for newer ones?

Does FreeBSD always return `powerpc` as the architecture, both on 32 and 64 bit architectures? If yes, is there a way to tell which one we are currently using apart from checking the size of `void *`?

**Comment by pkubaj** [comment]
Yes, `powerpc` on FreeBSD can be either `ppc32` (then it's just `powerpc`) or `ppc64` (in that case it's often referred to as `powerpc64`, but can be just `powerpc` too, similar to people using `x86` and `x86_64` interchangeably).

No, FreeBSD doesn't use `ppc32` name.

Yes, FreeBSD always uses the `powerpc` name. To check whether it's 32 bit or 64 bit, you can check `uname -p`. Note that there's also a third subarchitecture - `powerpcspe`. This is for Freescale's and IBM e500 CPUs.

**Comment by jpakkane** [comment]
It would seem that the most portable approach would be to detect `power` and expose it as either `ppc32` or `ppc64` in Meson scripts. Does this seem reasonable?

**Comment by pkubaj** [comment]
Yes, you can expose `powerpc` and `powerpcspe` as `ppc32` and `powerpc64` as `ppc64`.

**Comment by jpakkane** [comment]
Can you test if the linked MR works for you?

**Comment by jpakkane** [comment]
Also, the discussion above had a bug. 32 bit PowerPC processors are called just `ppc`.

**Comment by barracuda156** [comment]
@jpakkane So `cpu_family` for `ppc32` is `ppc` and for `ppc64` is `ppc64`, right?

**Comment by jpakkane** [comment]
{Yes](https://mesonbuild.com/Reference-tables.html#cpu-families).

**Comment by barracuda156** [comment]
@jpakkane Thank you. Do you know how to make `meson` recognize `ppc7400` as `ppc`? It fails on some builds otherwise complaining about "wrong" arch. Example: https://trac.macports.org/ticket/64787

**Comment by barracuda156** [comment]
@jpakkane Nevermind, I fixed it:

```
--- mesonbuild/mesonlib/universal.py.orig	2022-03-15 17:29:03.000000000 +0800
+++ mesonbuild/mesonlib/universal.py	2022-04-06 06:59:05.000000000 +0800
@@ -710,6 +710,8 @@
     # Convert from lipo-style archs to meson-style CPUs
     stdo = stdo.replace('i386', 'x86')
     stdo = stdo.replace('arm64', 'aarch64')
+    stdo = stdo.replace('ppc7400', 'ppc')
+    stdo = stdo.replace('ppc970', 'ppc64')
     # Add generic name for armv7 and armv7s
     if 'armv7' in stdo:
         stdo += ' arm'
```

**Comment by barracuda156** [comment]
> Please file a MR to fix this properly in Meson core.

Submitted PR: https://github.com/barracuda156/meson/pull/1

**Comment by eli-schwartz** [comment]
Hmm, that PR seems to have accidentally gotten submitted to your fork instead of to this repository.

**Comment by barracuda156** [comment]
> Hmm, that PR seems to have accidentally gotten submitted to your fork instead of to this repository.

Oops, thanks for pointing out.
