### ISSUE TITLE
error while loading shared libraries on msys2

### ISSUE THREAD

**Issue by albfan** [mesonbuild/meson#4398]
There's a extrange error building libgit2-glib on msys2:

https://github.com/Alexpux/MINGW-packages/pull/4560#issuecomment-431647264

I'm sure is related with CI, as Azure do not have the problem, while appveyor has it, but want to ask how to get more info about error (if that's something meson can provide)

**Comment by lazka** [comment]
If I remember correctly this turned out to be a mix of old DLLs in the system path on appveyor and an incompatible pacman repo providing an old openssl on your side.

Can this be closed?

**Comment by albfan** [comment]
Not sure if someone fixed it, all my pipelines were accepted manually, failing on appveyor. Will close then
