### ISSUE TITLE
pkgconfig do not generate correct files for c#

### ISSUE THREAD

**Issue by marcelhollerbach** [mesonbuild/meson#4409]
Lets take something like the following:
```
my_lib = library('a', 'a.cs')
pkgconfig.generate(my_lib)
```
This will generate a pkgconfig that will have a -L and -l flag. However a -r argument should be added.

**Comment by nirbheek** [comment]
Yep, you're right. Would you like to attempt a patch that fixes this? The relevant code is in `mesonbuild/modules/pkgconfig.py`

**Comment by marcelhollerbach** [comment]
This is now implemented :)
