### ISSUE TITLE
access to exe_wrapper from test scripts

### ISSUE THREAD

**Issue by dcbaker** [mesonbuild/meson#4427]
igt has some tests (in meson) that are shell scripts, but they need to invoke built binaries. So it needs some way to get at the exe_wrapper.

**Comment by nirbheek** [comment]
We could set `MESON_EXE_WRAPPER` to a value that is [shell-quoted](https://docs.python.org/3/library/shlex.html#shlex.quote). We already do this for `MESONINTROSPECT`, for instance.

**Comment by dcbaker** [comment]
in IGT's case the binaries are passed as arguments to the scripts, would it work to just wrap the binary in the exe_wrapper in that case?

**Comment by nirbheek** [comment]
We could allow you to get the `exe_wrapper` as a `ExternalProgram` object (which is represented as an array of strings), then the test target should see that in the list of args for the test and expand it correctly. So, f.ex.,

```meson
exe_wrapper = ['qemu-system-arm', '-vga', 'virtio']
```

```meson
exewrap = meson.get_exe_wrapper()
test('name', exe, args : [exe_wrapper, '-foo', '-bar'])
```

This will pass to `exe` the following arguments: `['qemu-system-arm', '-vga', 'virtio', '-foo', '-bar']`.

Would this work?

**Comment by dcbaker** [comment]
I think so. It would just be nice if it was transparent to avoid having to do:
```meson
exe_wrapper = []
if meson.has_exe_wrapper()
  exe_wrapper = meson.get_exe_wrapper()
endif
```
And then discovering that no one has added that to their meson script because they don't care about cross compiling. But doing it transparently would be hard to get right in every case I suspect.

**Comment by nirbheek** [comment]
Ah, so you want to detect when a built executable is passed to a test as an argument and automatically add the exe wrapper to it? That sounds like a good idea, and the implementation would be the same as the suggestion I commented above.

We should include a way to disable it somehow, though.

**Comment by nirbheek** [comment]
Another option is to always return the empty array in `get_exe_wrapper()` so you don't need to have that if condition.

**Comment by dcbaker** [comment]
yeah, but it still means that you have to write tests as:

```meson
test('foo', [meson.get_exe_wrapper(), binary])
```
to be cross safe. If we can we should make the barrier to writing tests that work with the exe_wrapper as low as we can safely.

**Comment by nirbheek** [comment]
> test('foo', [meson.get_exe_wrapper(), binary])

You don't need to do that, though. We automatically run cross binaries with the exe wrapper while running tests.

**Comment by dcbaker** [comment]
Err, there should have bine a `foo.sh` in there :)

**Comment by nirbheek** [comment]
Ah, yes, well we could make automatic exe wrapper addition a thing, yes. I think we should have a way to opt-in to changes like that, and a deprecation warning for people who don't opt-in, and then after a few releases we flip over.

**Comment by dcbaker** [comment]
Do we key things off minimum meson version? It would be very handy for deprocations

**Comment by dcbaker** [comment]
ie, opt in if minimum version >= version when this feature was added.

**Comment by nirbheek** [comment]
We could indeed do that. Now that I think of it, I suggested something like this a year ago but we never implemented it...

**Comment by ptomato** [comment]
This would also be useful when using `add_test_setup()` or `meson test --wrap` while having tests that are invoked from a shell script (for example, I have a shell script that checks the exit code of my built binary is a certain value, if I wrap the tests with valgrind then I want to check for leaks in my built program and not my shell)

**Comment by ptomato** [comment]
(Although we'd also need some way to tell Meson "don't wrap this test, I'll apply the wrapper inside my script", maybe an optional argument to `test()`)
