### ISSUE TITLE
Meson Visual Studio C++17

### ISSUE THREAD

**Issue by jehugaleahsa** [mesonbuild/meson#4455]
I feel like I am missing something very basic, so sorry if I'm bothering you over something simple. I am trying to use the Ninja backend to compile a VC++ program. I installed meson and ninja using `pip install`.

My `meson.build` file is really straight-forward:
```
project('file-spider', 'cpp', version: '0.1', default_options: ['cpp_std=c++17'])
executable('file-spider', 'src/main.cpp')
```

This is essentially a "Hello, World" app to familiarize myself with using meson to build a VS2017 C++17 project. Even though I have included the `cpp_std=c++17` option, it seems like the `cl` compiler isn't being passed the right options. It's still trying to use C++14 versions of the msvc standard headers.

I have to switch to using `std::experimental::filesystem` in order for the code to compile. It looks like the `_HAS_CXX17` macro must not be getting set.

Here's the code I am trying to compile:

```C++
#include <iostream>
#include <algorithm>
#include <iterator>
#include <filesystem>

using namespace std;
using namespace std::filesystem;

int main(int, char**) {
    using DirIter = recursive_directory_iterator;

    path current{"."};
    current = absolute(current);
    DirIter begin{current};
    DirIter end;
    ostream_iterator<DirIter::value_type> out{cout, "\n"};
    copy(begin, end, out);
    return 0;
}

```

**Comment by jehugaleahsa** [comment]
Here's is the generated build rules in the `build.ninja` file:
```
# Build rules for targets

build file-spider@exe/src_main.cpp.obj: cpp_COMPILER ../src/main.cpp
 DEPFILE = file-spider@exe\\src_main.cpp.obj.d
 ARGS = "-Ifile-spider@exe" "-I." "-I.." "/MDd" "/nologo" "/showIncludes" "/W2" "/EHsc" "/ZI" "/Ob0" "/Od" "/RTC1" "/Fdfile-spider@exe\\src_main.cpp.pdb"

build file-spider.exe: cpp_LINKER file-spider@exe/src_main.cpp.obj
 LINK_ARGS = "/nologo" "/DEBUG" "/PDB:file-spider.pdb" "/SUBSYSTEM:CONSOLE" "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "comdlg32.lib" "advapi32.lib"
```

The `-std:c++17` flag isn't being passed as an arg here. This is what makes me think I am missing something.

**Comment by jehugaleahsa** [comment]
For now, I am just doing this, I guess:

```
if meson.get_compiler('cpp').get_id() == 'msvc'
    extra_args = ['-std:c++17']
else
    extra_args = []
endif
executable('file-spider', 'src/main.cpp', cpp_args: extra_args)
```

Let me know if that's what's expected. The [How do I do X in meson](http://mesonbuild.com/howtox.html#set-default-cc-language-version) page makes it sound like that should be unnecessary.

**Comment by mensinda** [comment]
When you run `meson configure build` meson prints the current configuration options. Is `cpp_std` set to the correct version in this output and is `c++17` in the list of Possible Values?

As far as I know, the `default_options` are only applied when the build directory is first created (I am not 100% sure though). So if you have added `default_options: ['cpp_std=c++17']` *after* first initialising the build directory, the `cpp_std` option is not applied. This happened to me with some other variable.

If this is the case you should be able to fix this with `meson configure -Dcpp_std=c++17 build`.

**Comment by dcbaker** [comment]
I'm fairly sure this is a known issue fixed in meson git but not in any release yet. Your only option for the moment is to do what you're doing already. for 0.49.0 setting the cpp_std should work.

**Comment by jehugaleahsa** [comment]
@mensinda I thought maybe a reconfiguration was needed, too. So I've tried wiping out the build directory entirely and recreating it several times now. I also found an SO post suggesting `meson configure -Dcpp_std=c++17 build` and tried it. However, I get an error saying `WARNING: Unknown options: "cpp_std"` which seems odd to me.

**Comment by mensinda** [comment]
@jehugaleahsa In this case, this should be a bug. Maybe keep the workaround until 0.49.0 is released?

**Comment by jpakkane** [comment]
Yes, C++ language version selection is only in Git, not in any release version. The easy way to check what possible things you can toggle is to run this in your build directory:

   meson configure

It will list all options and their possible values.

**Comment by nioncode** [comment]
Should we close this since this is fixed in master?
