### ISSUE TITLE
Allow adding to the rpath of libraries and executables.

### ISSUE THREAD

**Issue by DragoonX6** [mesonbuild/meson#446]
In some cases we want to be able to set the rpath of our program to folders where external libraries are located. Cases like having a program built with libc++ and external libraries, which also need to be built with libc++. In such a case adding the folder to LD_LIBRARY_PATH will break other applications, like it looks to be running well and once an exception is thrown it crashes, or you get other subtle problems.
On Windows this has to be implemented as a copy operation of the libraries, or something similar to that, as Windows has no rpath.

**Comment by nirbheek** [comment]
Can't you use per-target [`link_args`](https://github.com/mesonbuild/meson/wiki/Reference%20manual#executable) for this with toolchains/platforms that support `rpath`? Something like `link_args : ['-Wl,-rpath', somedir]`. This won't work on Windows anyway (copying external libraries is out of scope for Meson), so I don't think we can add a cross-platform option for this.

**Comment by nirbheek** [comment]
You can already do this with the `install_rpath:` keyword argument. Closing.
