### ISSUE TITLE
Passing .full_path() to meson.add_install_script() gives the not-install-ready file

### ISSUE THREAD

**Issue by 1ace** [mesonbuild/meson#4523]
Install scripts are given the build-time files, which have *not* gone through meson's install process (such as rpath stripping).

Example to reproduce the issue:
```
libFOO = shared_library('FOO', 'foo.c')
meson.add_install_script(install_script, libFOO.full_path(), install_path)
```

In our usecase, the install script is essentially this:
```
master=$1
installpath=$2
ln $master $installpath/foo.so
ln $master $installpath/bar.so
rm $master
```

Currently, this results in foo.so and bar.so not being processed and still having their build rpath.

**Comment by 1ace** [comment]
Looking at it a bit more, I think `run_install_script()` in https://github.com/mesonbuild/meson/blob/master/mesonbuild/minstall.py#L409 should do a substring replacement of its scripts' args from builddir paths to install paths

**Comment by dcbaker** [comment]
I'd like to solve this by allowing build_targets to be passed directly to the `meson.add_install_script` method, and have meson create a copy of said target, run depfixer on it, and then pass that as the string to the install script. @jpakkane, does that seem like a reasonable interface?

**Comment by jpakkane** [comment]
The correct solution to this is to use `meson introspect`. That is why we expose it explicitly [with an envvar](https://mesonbuild.com/Reference-tables.html) when install scripts are run. That should give you all the info you need for your custom install logic. If something is missing let us know and we'll add it to introspection output.

**Comment by dcbaker** [comment]
how does `meson introspect` strip the rpath from the binary?

**Comment by jpakkane** [comment]
It doesn't, but it gives you the installed path for the lib so you can symlink to it rather than symlinking to a file inside the build directory.

**Comment by dcbaker** [comment]
the problem we have is that we never install the built binary, because we want all of the links to be hard links. so we copy the built binary, then hardlink X many copies of that binary. I don't really want to install it, because there isn't a good way to give the installed binary a sensible name without making the meson build definition much more complicated (it needs to be <vender>_dri.so), but the list of vendor names is configurable (and may be length 1)
