### ISSUE TITLE
Get current subdir name

### ISSUE THREAD

**Issue by alexiynew** [mesonbuild/meson#4526]
I have a project with a structure like that:
<pre>
root
  | - src
  | | - ...
  | - tests
    | - test_group
      | - test_name
        | - main.cpp
        | - meson.build
</pre>

In all test_name directories meson.build are pretty much the same, except some test specific settings:
<pre>
test_name = meson.current_source_dir().split('/').get(-1)
test_sources = files('main.cpp')

test = executable(test_name, test_sources)
test(test_name, test, suite: test_group_name, timeout: 60)
</pre>
So I can easily move tests in another place, rename it and so on.
The problem is I can't get current subdirectory name in a cross-platform way, because of slashes. 
It would be nice to have a function to get the current dir name. 
In CMake I can do it like this 
`get_filename_component(TEST_NAME ${CMAKE_CURRENT_LIST_DIR} NAME)`.

**Comment by alexiynew** [comment]
In that case in the parent directory's meson.build would look like this:
<pre>
test_group_name = meson.current_source_dir().split('/').get(-1)

message('\tAdd tests: ' + test_group_name )

test_name = 'vector_constructor'
subdir(test_name)

test_name = 'vector_operators'
subdir(test_name)

test_name = 'vector_common'
subdir(test_name)
...
</pre>

And it feels unpleasant to me.
If I could use the foreach to wrap all subdir includes, it would be great.
I'll try it. Thanks.

**Comment by pal666** [comment]
why can't you check build_machine.system() and select correct slash?

**Comment by nirbheek** [comment]
You could also define your tests in the parent directory. Then all your tests could be defined by a single `foreach` loop.

**Comment by alexiynew** [comment]
Yea. foreach works fine.

**Comment by rulatir** [comment]
> For what it's worth, you could probably work around this by having the parent directory's `meson.build` set a variable before calling `subdir()` that's then used by the subdirs' `meson.builds`?

This is completely wrong. The project root holds the application that is assembled *from* components living in subdirs. Those are "pre-existing" with respect to the application. Whenever a workaround is necessary that forces the root to provide stuff for subdirs, it reveals how Meson's opinionatedness harms the ability to do things the right way. Subdirs should be able to manage their own matters. It's a screeching, green mucus squirting shame that Meson subdirs literally don't know **what** they are.

**Comment by mensinda** [comment]
This should be easy to solve with the upcomming (meson 0.53.0) [fs module](https://mesonbuild.com/Fs-module.html):

```meson
fs = import('fs')
fs.name(meson.current_source_dir())
```

It is not as nice as having a dedicated function that returns the subdir, but it should be a good enough replacement with a bit of documentation (maybe a new entry in [_How do I do X in Meson?_](https://mesonbuild.com/howtox.html))

**Comment by tp-m** [comment]
> This is completely wrong.

Hey, I was just offering a possible workaround not providing any opinion on whether this could or should be added. Doesn't seem a big deal to me either way seeing that we already have it as part of `meson.current_source_dir()`.
