### ISSUE TITLE
Import third-party meson build scripts or modules

### ISSUE THREAD

**Issue by yshui** [mesonbuild/meson#4533]
Using cmake, a project can install cmake scripts into the system, to provide configuration support of that project (e.g. finding libraries provided by that project, etc.). To use a third party cmake script, one use `find_package()` in cmake.

In meson, however, there is no way to include an external meson script. The only ways to include meson script are `subdir()` and `subproject()` (`import()` seems to only import python scripts), and none of them are suitable for external scripts.

What is the consensus in this area? Will there be a stable python API in the future so projects can install python scripts that meson can use?

**Comment by jpakkane** [comment]
[Pkg-config](https://mesonbuild.com/Pkgconfig-module.html).

**Comment by yshui** [comment]
pkg-config does not cover all use cases. First example comes to mind is Qt, which has its own modules. 

It's not like meson does not keep a list of "modules" for itself. It has modules to handle llvm, gnome, etc. Is meson just going to maintain a module for every project that requires one? I don't think this is sustainable.

**Comment by jpakkane** [comment]
Qt works just fine with pkg-config. All distros ship .pc files and Meson has used them successfully for years.

But more imporantly we _don't_ want to provide a dependency system that only works with Meson projects. We feel that the installed libraries we produce (and which other build systems produce as well) should work with _any_ build system. The problem with e.g. CMake's script file approach is that it really only works with CMake consumers. This leads into a monoculture, which is unhealty in the long term. We'd rather support build system agnostic approaches (such as pkg-config and others) for these kinds of problems so different systems can cooperate easily.

**Comment by yshui** [comment]
OK, I think that make sense and I agree.

So is meson going to help extend pkg-config and related tool to slowly phase out the modules it has?

**Comment by jpakkane** [comment]
There are some modules that do more than just look up dependencies like the Python modules for example. But yes, the less special case code we have the better off everyone is.

**Comment by yshui** [comment]
> But more imporantly we don't want to provide a dependency system that only works with Meson projects.

How do you defend Meson wrap then?

**Comment by nirbheek** [comment]
Meson wraps are not for consuming installed dependencies, they're for building another meson project as if it were a part of your own project. Contrast with `.cmake` files.

**Comment by yshui** [comment]
@nirbheek That's arguably even worse. Since developers might use wraps to bypass the host package manager. Imagine if upstream developers stop using pkg-config files, ship a wrap file instead and force downstream to use meson.

**Comment by dcbaker** [comment]
That's a culture problem, not a technical problem. By the same token they could just vendor the code and say "You have to used the bundled version of X!"

**Comment by yshui** [comment]
@dcbaker True, but meson is making it easier. Previously, bundling library not supported by distros was painful, no matter which method you choose. With Meson Wrap, it's much much easier to do similar things. The result is there will be less incentive to push the distros to package bundled libraries.

**Comment by dcbaker** [comment]
there's a switch to disable wraps and error if you're forced to use them. All distros I know of (debian, fedora, arch, gentoo) set that swtich.
