### ISSUE TITLE
vim syntax highlighting doesn't allow overriding shiftwidth and softtabstop

### ISSUE THREAD

**Issue by pinchartl** [mesonbuild/meson#4557]
The vim syntax indentation rules are stored in data/syntax-highlighting/vim/indent/meson.vim. This file sets

setlocal shiftwidth=2
setlocal softtabstop=2

As the file is loaded last, after ~/.vim/after/ftplugin/meson.vim (when present), this prevents overriding the default values for shiftwidth and softtabstop in a local configuration.

The correct place to set shiftwidth and softtabstop is in ftplugin/meson.vim. See for instance the way python indentation rules are split between ftplugin/python.vim and indent/python.vim in upstream vim. The rest of the indentation rules can, to the best of my knowledge, stay in indent/meson.vim.

When fixing this, the data/syntax-highlighting/vim/README file should also be updated, as it currently refers to a non-existing plugin directory.

**Comment by jpakkane** [comment]
I know nothing about vim, but patches are welcome.
