### ISSUE TITLE
Prioritize custom include directories over platform defaults

### ISSUE THREAD

**Issue by mokafolio** [mesonbuild/meson#4560]
Hi,

I have a use case where some older versions of libraries are installed in `/usr/local/lib` and the headers in `/usr/local/include`. The item I am trying to build provides newer versions of the libraries/headers in a subproject. In order to add the included directories to the subproject libraries, I do something along these lines:

`incDirs = include_directories('subprojects/Foo')`

Which I pass to the target. On Ubuntu 18.04, this unfortunately still prioritizes the _Foo_ headers installed at `/usr/local/include` instead of the subproject one. Is there any way to fix this? Is there a way to remove  `/usr/local/include` from the include directories?

Thanks!

**Comment by QuLogic** [comment]
> `incDirs = include_directories('subprojects/Foo')`

That just defines a variable referencing some directories; do you actually use it somewhere?

**Comment by mokafolio** [comment]
Yes, I am using it, sorry I left that out:

```
    foo = shared_library('Foo',
        fooSrc, 
        dependencies: fooDeps, 
        include_directories : incDirs,
        install: true) 
```

**Comment by QuLogic** [comment]
It is probably better to define a dependency in the subproject and use that when linking, as in [the subproject example](https://mesonbuild.com/Subprojects.html#a-subproject-example).

**Comment by mokafolio** [comment]
In the end, the problem actually was that my git submodules/subprojects were not properly setup. Sorry for the confustion, thanks for the help!
