### ISSUE TITLE
export-dyamic repeated for static libraries with deps of other static libraries

### ISSUE THREAD

**Issue by chergert** [mesonbuild/meson#4567]
I've been working on an app that has a lot of static libraries for all the subsystems and plugins, and links them together at the end. However, due to how meson is duplicating export-dynamic in the build commands, I'm hitting the 128kb argv limit.

```
[1/365] Generating ide-build-ident.h with a custom command.
fatal: No names found, cannot describe anything.
[1/4] Linking target src/gnome-builder.ninja: fatal: posix_spawn: Argument list too long
```

[build.ninja.snip.txt](https://github.com/mesonbuild/meson/files/2632112/build.ninja.snip.txt)

**Comment by jpakkane** [comment]
I tried to replicate this but could not. Could those --export-dynamic and -pthread args come from somewhere outside originally? Like possibly from pkg-config?

**Comment by chergert** [comment]
The only place I had export_dynamic:true was on the final executable() (and doing that manually with link args previously).

**Comment by chergert** [comment]
I should mention that many of the libraries depend on others, and the plugins depend on many of the static libraries (for include paths mostly). So there should be a pretty heavy dependency tree.

**Comment by chergert** [comment]
Here is the commit in my prototype repo where I switched from lots of `.a` static libraries to a single large static library for all the plugins (in case you want to look at the previous layout). https://gitlab.gnome.org/chergert/round2/commit/f18ec51a868fd51e235ab79d26f5cb6749daac6
