### ISSUE TITLE
meson misdetects build machine cpu (family) on armhf when run with arm64 kernel

### ISSUE THREAD

**Issue by mbiebl** [mesonbuild/meson#4586]
Version: 0.48.2-1
Distribution: Debian sid

This was originally filed as https://github.com/systemd/systemd/issues/11022

During a test build on https://tests.reproducible-builds.org/ the systemd package failed to build reproducibly on armhf https://tests.reproducible-builds.org/debian/rb-pkg/unstable/armhf/systemd.html

If you look at the diff between the two builds at https://tests.reproducible-builds.org/debian/logdiffs/unstable/armhf/systemd_239-13.diff.gz one noticable difference is

```
-Build machine cpu family: aarch64
-Build machine cpu: aarch64
+Build machine cpu family: arm
+Build machine cpu: armv7l
```
bootctl needs to know what name to give to the EFI binary when it copies it to /boot. This file name varies depending on the CPU architecture.
The systemd build system uses ```host_machine.cpu_family()``` to set EFI_MACHINE_TYPE_NAME which is then embedded into the bootctl binary.

One of the two builds runs on a arm64 CPU + kernel with an armhf userland.
As meson utilizes ```uname``` (via Python's ```platform.machine()```) it misdetects the host machine architecture as arm64, when it should be armhf.

Asking the compiler might be a more robust way to detect the host architecture.  E.g. in debian, ```dpkg-architecture``` uses ```gcc -dumpmachine```: https://manpages.debian.org/unstable/dpkg-dev/dpkg-architecture.1.en.html

**Comment by mbiebl** [comment]
https://git.dpkg.org/cgit/dpkg/dpkg.git/tree/scripts/Dpkg/Arch.pm#n153

**Comment by floppym** [comment]
Generally, using `gcc -dumpmachine` is probably not sufficient. The cpu_family really needs to change based on the ABI the compiler is targeting. For example:
```
% gcc -m64 -dumpmachine
x86_64-pc-linux-gnu

% gcc -m32 -dumpmachine
x86_64-pc-linux-gnu
```
In the first case, we want `cpu_family = 'x86_64'`. In the second case, we want `cpu_family = 'x86'`.

**Comment by nirbheek** [comment]
@mbiebl could you try https://github.com/mesonbuild/meson/pull/4590 please?

**Comment by mbiebl** [comment]
Would love to. Unfortunately I don't have root access on an arm64 system where I can easily create an armhf chroot.

**Comment by mbiebl** [comment]
thanks @nirbheek. I'll keep an eye on this issue and once a meson version with that patch hits Debian, will report back with the results.

**Comment by nirbheek** [comment]
If you find any issues, we'll fix it in the .1 release, thanks for testing :)
