### ISSUE TITLE
Meson leaks subprojects, in particular when statically linking

### ISSUE THREAD

**Issue by haasn** [mesonbuild/meson#4598]
I have a [meson project that uses subprojects](https://code.videolan.org/videolan/libplacebo/blob/master/src/meson.build) for helper libraries internal to the project. These libraries are **not** supposed to be installed system-wide, and indeed, meson does not install them. They are built as static libraries and linked into the resulting `.so`, and this works out fine.

However, when `--default-library` is `static`, the generated `libplacebo.a` does *not* include the symbols from the internal helper libraries `libxtalloc.a` and `libbstr.a`, which is a problem - it effectively means static libraries with internal subprojects are impossible to build properly.

A solution would be either installing the internal libraries system-wide (yeah, no); producing a `combined` .a that includes the internal static libraries (preferable), or perhaps switching to an approach where the internal libraries are not even treated as libraries (but instead, perhaps, just linked in as raw object files).

## pkg-config issues

Additionally, even when using dynamic linking, the `.pc` file leaks the linker flags for these hidden/internal libraries:

```
prefix=/usr/local
libdir=${prefix}/lib64
includedir=${prefix}/include

Name: libplacebo
Description: Reusable library for GPU-accelerated video/image rendering
Version: 1.7.0
Requires.private: lcms2 >= 2.6, vulkan >= 1.0.42
Libs: -L${libdir} -lplacebo
Libs.private: -pthread -pthread -L${libdir} -lxtalloc -lbstr -lm -lglslang -lHLSL -lOGLCompiler -lOSDependent -lSPIRV -lSPVRemapper -lpthread -lshaderc_shared
Cflags: -I${includedir}
```

Note the presence of `-lxtalloc` and `-lbstr` in the `Libs.private` section, which are not supposed to be publicly visible at all.

**Comment by nirbheek** [comment]
This sounds like https://github.com/mesonbuild/meson/pull/3939, can you try that branch and see if that helps?

**Comment by haasn** [comment]
That branch does appear to fix this issue, however it causes another one due to duplicated symbols in my test executables (I use `lib.extract_all_objects()` to add the objects from the main library to the test executables).

However, I can work around this regression in a different way (by omitting the subprojects from the `dependencies:` of the test `executable()`, and instead adding the include path manually).

**Comment by haasn** [comment]
Hmm, actually, I take that back - I'm not sure how to easily work around the regression w.r.t test executables. The problem is that I effectively need to, at the same time:

1. `link_with: lib` in order to resolve `lib`'s link dependencies
2. add the extracted objects from `lib` to `objects:`, in order to get access to internal symbols

Possibly the concrete bug here is that `link_with: lib` still pulls in the internal subprojects of `lib` as dependencies, even though `lib` already contains those symbols?

**Comment by haasn** [comment]
Okay, turns out I can vastly simplify a few things in my test framework building code. I've pushed an update to my master branch that fixes the build with both current master and with your PR branch.

So from my point of view, your PR branch is good to go, and it will solve this issue. I'll close this as a duplicate of #3937 and #3934.
