### ISSUE TITLE
WARNING: Unknown CPU family 'rl78'

### ISSUE THREAD

**Issue by ApplidyneMH** [mesonbuild/meson#4606]
I was trying to setup a meson cross build environment for the RL78 microprocessor family from Renesas.

Technically it comes in 3 variants RL78-S1, RL78-S2, RL78-S3 that differ somewhat in their instruction set (e.g. hardware multiply support in S3) but the GCC compiler generally refers to it as RL78.

Actual implementations of these cores are like:
  RL78-S1 core: RL78/G10 
  RL78-S2 core: RL78/G12, RL78/G13, RL78/G1A, RL78/G1E, RL78/G1C, RL78/I1A, RL78/F12,  RL78/D1A, RL78/L12, and RL78/L13 
  RL78-S3 core: RL78/G14 

In GCC again, these processors are selected with -mcpu=g13 or -mg13

Recognised options in GCC are g10, g13 and g14 for each of the 3 cores with option rl78 a synonym for g14 which is also the default.

See also https://en.wikipedia.org/wiki/RL78

**Comment by jpakkane** [comment]
Are you cross compiling from a different platform (most likely x86_64) or are you running the compilers directly on the platform? This message should only be printed when doing the latter.

**Comment by ApplidyneMH** [comment]
This is a bare metal cross compile. Here is the meson output that I get:

> WARNING: Unknown CPU family 'rl78', please report this at https://github.com/mesonbuild/meson/issues/new
> The Meson build system
> Version: 0.48.2
> Source dir: C:\project
> Build dir: C:\project\build
> Build type: cross build
> Project name: something
> Project version: 0.0.0
> Native C compiler: gcc (gcc 4.9.2 "gcc (tdm-1) 4.9.2")
> Cross C compiler: rl78-elf-gcc (gcc 4.9.2)
> Host machine cpu family: rl78
> Host machine cpu: g13
> Target machine cpu family: rl78
> Target machine cpu: g13
> Build machine cpu family: x86
> Build machine cpu: x86
> Build targets in project: 6
> Found ninja-1.8.2 at 'C:\Program Files\Meson\ninja.EXE'

**Comment by jpakkane** [comment]
Can you test if the linker MR fixes this for you?
