### ISSUE TITLE
run_target improperly handles command if 'python' is in meson's installation path

### ISSUE THREAD

**Issue by plexik** [mesonbuild/meson#4614]
My build environment is RHEL 7.6 with the python 3.6 Red Hat software collection enabled in my .bashrc.  Meson was installed by running ``pip3.6 install .`` as root in the ``meson-0.49.0/`` folder from a fresh download.  (This issue also happens in meson 48.)

I was setting up a custom run_target to run cppcheck with the command
```
run_target('cppcheck', command : ['cppcheck', '--project=' + join_paths(meson.build_root(), 'compile_commands.json')])
```
but noticed that it was failing to run with the following error message:
```
Could not execute command "--project=[build dir]/compile_commands.json". File not found.
FAILED: meson-cppcheck
/opt/rh/rh-python36/root/usr/bin/meson --internal commandrunner [src dir] [build dir] '' /opt/rh/rh-python36/root/usr/bin/meson cppcheck --project=[build dir]/compile_commands.json
ninja: build stopped: subcommand failed
```

I traced the issue for a bit and it the issue appears to be in ``commandrunner.py`` line 61 (ironically the line with the comment "Hack." haha): it looks for the presence of the string ``python`` in the meson path, presumably to catch instances of meson being launched with a ``python3 meson`` call.  However it ignores the possibility that python is simply a part of the path to the meson executable.  When this happens, the commandrunner script grabs the fifth argument and assumes that it's part of the meson command, which is wrong.

I'm currently working around the issue by inserting an empty argument into the run_target command, like this:
```
run_target('cppcheck', command : ['', 'cppcheck', '--project=' + join_paths(meson.build_root(), 'compile_commands.json')])
```

**Comment by jpakkane** [comment]
Can you test if the linked MR fixes it for you?

**Comment by plexik** [comment]
Yep, it appears to work properly now, thanks. :slightly_smiling_face: 
I removed the empty argument in ``command`` and it runs cppcheck as expected.
