### ISSUE TITLE
setup.py: Install scripts without extensions on UNIX-like platforms

### ISSUE THREAD

**Issue by LastAvenger** [mesonbuild/meson#462]
Because of issue #394 , meson install scripts as `xxx.py` , but in linux, install script with a extension name is no a good practice. And change the installed script name also break some package depend on meson.

Could you deal with it for different platform?

thx.

**Comment by jpakkane** [comment]
The case of Python's script suffixes is neverending pain. No matter what you set it to, someone's setup will be broken.

We're going to stick with the current one which seems the least broken unless someone can come up with a scheme that works for everybody.

**Comment by ignatenkobrain** [comment]
I think we should install with suffix on windows and without on other (normal) systems.

**Comment by Sean1708** [comment]
Has anyone considered using [`entry_points`](https://pythonhosted.org/setuptools/setuptools.html#automatic-script-creation)? Obviously it would mean that setuptools would become a requirement, but is it particularly common no to have setuptools installed nowadays?

**Comment by nirbheek** [comment]
Automatic script creation in `setuptools` seems to be our best option. I think it's ok to require setuptools if you're building or installing since you can run uninstalled if you want to anyway.

**Comment by Sean1708** [comment]
New link is [here](https://setuptools.readthedocs.io/en/latest/setuptools.html#automatic-script-creation) btw, looks like they've changed where their docs are hosted.
