### ISSUE TITLE
meson-0.49.0 Windows installation misses most of the /scripts

### ISSUE THREAD

**Issue by yuriy-pavlovsky** [mesonbuild/meson#4621]
```Meson\lib\mesonbuild\scripts``` contains only two files:
```
depfixer.pyc
__init__.pyc
```
Every other script is missing. This happens both on x86 and x64 installations.

**Comment by jpakkane** [comment]
Thanks, the linker MR should fix the issue. I have made two testing packages, can you try if they work for you, thanks.

[32 bit version](https://www.dropbox.com/s/9nw9s7jn7v2q2jz/meson-0.49.0.1-32.msi?dl=0).

[64 bit version](https://www.dropbox.com/s/br7lit3kkc1gaf5/meson-0.49.0.1-64.msi?dl=0)

**Comment by yuriy-pavlovsky** [comment]
Tested both versions just in case, everything seems to be working fine, thanks for the quick fix.

**Comment by sompen** [comment]
@jpakkane 
I am facing this issue with meson-0.49.1.
I tried with both 32-bit and 64-bit versions of the msi and seeing that only two files are existing in mesonbuild/scripts/ directory.

**Comment by jpakkane** [comment]
Argh, the fix was not picked up for the bugfix release. Creating new packages...
