### ISSUE TITLE
Support project-provided lcovrc script for lcov coverage

### ISSUE THREAD

**Issue by pwithnall** [mesonbuild/meson#4628]
lcov has various options for excluding certain lines, directories and functions. In particular, I would like to be able to exclude certain function calls from branch coverage since they are assertions which it makes no sense to test. This uses the `lcov_excl_br_line` option ([example in GLib](https://gitlab.gnome.org/GNOME/glib/blob/master/.gitlab-ci/lcovrc)).

Since that kind of configuration is quite highly project dependent, and needs to be repeated in all the `lcov` commands, I think it might make sense to allow the project to provide an `lcovrc` file which would get passed to all the `coverage.py` `lcov` commands using `--config-file path/to/lcovrc`.

Failing that, it would be useful to be able to pass custom arguments to `lcov` so that projects could at least pass `--config-file` (or excl options) themselves.

**Comment by eli-schwartz** [comment]
I think I've implemented automatic detection of .lcovrc in the PR I just submitted, please give it a try.

**Comment by pwithnall** [comment]
Thanks, I’ve put a PR together to take advantage of it in GLib: https://gitlab.gnome.org/GNOME/glib/-/merge_requests/2630
