### ISSUE TITLE
CFLAGS interleaved with spaces

### ISSUE THREAD

**Issue by kjeldflarup** [mesonbuild/meson#4634]
I have a build which fails with.
meson.build:1:0: ERROR:  Compiler arm-cortexa7hft-linux-gnueabi-gcc can not compile programs.

looking into meson-log.txt this has a cause:
```
Running test binary command: /home/user/tmp/work/machine/arm-cortexa7hft-linux-gnueabi.awc500pcm52/gssdp-1.1.1/src/gssdp-1.1.1/builddir/meson-private/sanitycheckc.exe
Sanity testing C compiler: arm-cortexa7hft-linux-gnueabi-gcc
Is cross compiler: True.
Sanity check compiler command line: arm-cortexa7hft-linux-gnueabi-gcc     - O 2   - f e x p e n s i v e - o p t i m i z a t i o n s   - f o m i t - f r a m e - p o i n t e r   - f r e n a m e - r e g i s t e r s     / h o m e / u s e r / t m p / w o r k / m a c h i n e / a r m - c o r t e x a 7 h f t - l i n u x - g n u e a b i . a w c 5 0 0 p c m 5 2 / g s s d p - 1 . 1 . 1 / s t a g e / m a c h i n e / u s r / i n c l u d e / g l i b - 2 . 0 -c /home/user/tmp/work/machine/arm-cortexa7hft-linux-gnueabi.awc500pcm52/gssdp-1.1.1/src/gssdp-1.1.1/builddir/meson-private/sanitycheckc.c -o /home/user/tmp/work/machine/arm-cortexa7hft-linux-gnueabi.awc500pcm52/gssdp-1.1.1/src/gssdp-1.1.1/builddir/meson-private/sanitycheckc_cross.exe
Sanity check compile stdout:
```
Right before running meson I read these two variables out
```
MACHINE_CFLAGS_OPT=-O2 -fexpensive-optimizations -fomit-frame-pointer -frename-registers
CFLAGS_OPT_SPEED=-O2 -fexpensive-optimizations -fomit-frame-pointer -frename-registers
```
Why, does meson expand the commands in this variable?
The host cc runs fine.

my crossfile.txt:
```
[binaries]
c = 'arm-cortexa7hft-linux-gnueabi-gcc'
cpp = 'arm-cortexa7hft-linux-gnueabi-gcc -E'
ar = 'arm-cortexa7hft-linux-gnueabi-ar'
nm = 'arm-cortexa7hft-linux-gnueabi-nm'
ld = 'arm-cortexa7hft-linux-gnueabi-ld'
readelf = ''
strip = 'arm-cortexa7hft-linux-gnueabi-strip'
pkgconfig = 'pkg-config'

[host_machine]
system = 'build_unknown'
cpu_family = 'x86_64'
cpu = 'x86_64-build_unknown-linux-gnu'
endian = 'little' # TODO

[target_machine]
system = 'cortexa7hft'
cpu_family = 'arm'
cpu = 'cortex-a7'
endian = 'little' # TODO

[properties]
needs_exe_wrapper = true
c_args = '  -O2 -fexpensive-optimizations -fomit-frame-pointer -frename-registers  /home/user/tmp/work/machine/arm-cortexa7hft-linux-gnueabi.awc500pcm52/gssdp-1.1.1/stage/machine/usr/include/glib-2.0'
c_link_args = ' -Wl,-O1 -Wl,--hash-style=gnu -Wl,-rpath,/home/user/tmp/work/machine/arm-cortexa7hft-linux-gnueabi.awc500pcm52/gssdp-1.1.1/install/usr/lib -Wl,-rpath,/home/user/tmp/work/machine/arm-cortexa7hft-linux-gnueabi.awc500pcm52/gssdp-1.1.1/install/lib '
cpp_args = '  '
cpp_link_args = ' -Wl,-O1 -Wl,--hash-style=gnu -Wl,-rpath,/home/user/tmp/work/machine/arm-cortexa7hft-linux-gnueabi.awc500pcm52/gssdp-1.1.1/install/usr/lib -Wl,-rpath,/home/user/tmp/work/machine/arm-cortexa7hft-linux-gnueabi.awc500pcm52/gssdp-1.1.1/install/lib '
```

**Comment by nirbheek** [comment]
> c_args = ' -O2 -fexpensive-optimizations -fomit-frame-pointer -frename-registers /home/user/tmp/work/machine/arm-cortexa7hft-linux-gnueabi.awc500pcm52/gssdp-1.1.1/stage/machine/usr/include/glib-2.0' > > c_link_args = ' -Wl,-O1 -Wl,--hash-style=gnu -Wl,-rpath,/home/user/tmp/work/machine/arm-cortexa7hft-linux-gnueabi.awc500pcm52/gssdp-1.1.1/install/usr/lib -Wl,-rpath,/home/user/tmp/work/machine/arm-cortexa7hft-linux-gnueabi.awc500pcm52/gssdp-1.1.1/install/lib '
> cpp_args = ' '
> cpp_link_args = ' -Wl,-O1 -Wl,--hash-style=gnu -Wl,-rpath,/home/user/tmp/work/machine/arm-cortexa7hft-linux-gnueabi.awc500pcm52/gssdp-1.1.1/install/usr/lib -Wl,-rpath,/home/user/tmp/work/machine/arm-cortexa7hft-linux-gnueabi.awc500pcm52/gssdp-1.1.1/install/lib '

This is incorrect. As noted in the [cross compilation guide](https://mesonbuild.com/Cross-compilation.html#defining-the-environment), these are lists, not strings.

However, we should error out when a string is passed for args instead of a list instead of parsing the string as an iterable.

**Comment by kjeldflarup** [comment]
Thanks  
The example I cloned from from assigned c_args to a variable, so I didn't think of it as being an array.
