### ISSUE TITLE
automatically call `--wipe` when the version changes instead of printing an error

### ISSUE THREAD

**Issue by dcbaker** [mesonbuild/meson#4635]
we have an option `meson configure --wipe` for rebuilding across meson version changes. It would be nice if calling ninja after a version update just called `meson configure --wipe`

**Comment by xclaesse** [comment]
It is already implemented like that, but it needs to be configured with meson 0.49 because it needs a file with options. We'll see if that works with 0.50 release.

**Comment by dcbaker** [comment]
ah, that makes sense. I'll go ahead an close this then.
