### ISSUE TITLE
Get headers from generator object

### ISSUE THREAD

**Issue by jml1795** [mesonbuild/meson#4638]
When building a library using generated C++ headers and source, from e.g. `idl` files, there does not appear to be a way to get the list of generated headers to easily reference from other locations using that library (other libraries, executables, or dependencies). It is possible I am missing something in the reference or API as I am new to meson.

For example, if I use a generator object as follows

```py
# meson.build for libsrc.a
# libsrc.a is autogenerated from a _lot_ of idl

gen = generator(genexe,
                output  : ['@BASENAME@.cpp', '@BASENAME@.hpp'],
                arguments : ['@INPUT@', '@BUILD_DIR@'])

# there could be hundreds of these...
src1 = gen.process('file1.idl')
src2 = gen.process('file2.idl')
# ...
srcN = gen.process('fileN.idl')

src_lib = static_library('src', [src1, src2, ...])

# some other build file
executable('main', ['main.cpp', ??????, link_with : src_lib)
```
Placing `[src1, src2, ...]` inside the executable command appears to trigger a duplicate build of the source and there doesn't look like a way to get just the headers for the library without explicitly listing them all.

Is it possible do something like the following?
```py
gen = generator(genexe,
                output  : ['@BASENAME@.cpp', '@BASENAME@.hpp' ],
                arguments : ['@INPUT@', '@BUILD_DIR@'])

# there could be hundreds of these...
src1 = gen.process('file1.idl')
src2 = gen.process('file2.idl')
# ...
srcN = gen.process('fileN.idl')

src_hdrs = files(src1[1], src2[1], ..., srcN[1])
src_cpps = files(src1[0], src2[0], ..., srcN[0]) 

src_lib = static_library('src', src_cpps)
src_dep = declare_dependency( sources: src_hdrs, link_with: src_lib)

# some other build file
executable('main', ['main.cpp'], dependencies: [src_dep])
```
What is the best way to get the header files to specify in the lib, exe, etc in a way that doesn't involve a lot of duplication? 

When generating multiple files at a time with `custom_target`, we can index into the returned array to get the headers since we know the order, however, `custom_target` appears to require a lot of duplication for each invocation. The `generator` mechanism allows a much cleaner syntax but does not seem to have a way to reference subsets of the generated output.

Thanks for your help and apologize if I just missed something in the docs that would meet the same goal. Let me know if there is a better place to ask the question. I am really enjoying working with meson so far!

The above is an excerpt from a larger project that I hope shows the question clearly. I can try to put together a standalone MWE if needed.

```sh
$ meson --version
0.49.999
```

**Comment by jpakkane** [comment]
This should work if you get the static library's private target dir and add it to the include list. Something like this:

```meson
src_dep = declare_dependency(include_directories: src_lib.private_dir_include(),
  link_with: src_lib)
```

Meson should make sure that all generated headers are fully built before sources belonging to a target linking against `src_lib` is built. (I say "should", because there may be bugs but I do remember people doing exactly this for Protobuf generation so it should indeed work.)

**Comment by jml1795** [comment]
@jpakkane That worked perfectly. Did exactly what I was looking for. Going to close this issue. Greatly appreciate your help!

For completeness, the implementation looks something like:

```py
gen = generator(genexe,
                output  : ['@BASENAME@.cpp', '@BASENAME@.hpp' ],
                arguments : ['@INPUT@', '@BUILD_DIR@'])

src1 = gen.process('file1.idl')
src2 = gen.process('file2.idl')
srcN = gen.process('fileN.idl')

src_lib = static_library('src', [src1, src2, ..., srcN])

src_dep = declare_dependency(
   link_with: src_lib,
   include_directories: src_lib.private_dir_include()
)

# some other build file
executable('main', ['main.cpp'], dependencies: [src_dep])
```

**Comment by jml1795** [comment]
@jpakkane That makes it even cleaner. Thanks again for your help
