### ISSUE TITLE
0.49.0 fails to find Qt5 using qmake

### ISSUE THREAD

**Issue by z3ntu** [mesonbuild/meson#4641]
My CI fails on both macOS and Windows:
https://travis-ci.org/z3ntu/razer_test/jobs/468630035
https://ci.appveyor.com/project/z3ntu/razer-test/builds/21043013/job/5upak41rvyneo2qu

`meson.build:20:0: ERROR:  Dependency "qt5" not found, tried pkgconfig, qmake-qt5 and qmake`

On those platforms, meson used the `qmake` detection with earlier versions

**Comment by z3ntu** [comment]
The culprit is aa04147a4a2a37aee197ebc0ed179c6fb582b3e9. CC @dcbaker
![image](https://user-images.githubusercontent.com/3768500/50053954-f5804300-013c-11e9-8686-32c8426ff5c3.png)

**Comment by dcbaker** [comment]
It also seems that using pkg-config is just plain broken (and has been for some time), at least the brew install.
