### ISSUE TITLE
Qt5 module complains when the (previously) optional lrelease program isn't found

### ISSUE THREAD

**Issue by z3ntu** [mesonbuild/meson#4654]
New behavior in 0.49.0:
`meson.build:47:0: ERROR:  Program(s) ['lrelease'] not found or not executable`
On quite many distributions the `lrelease` tool is only in the `qt5-tools` (or similarly named) package while the base parts of Qt are in `qt5-base` (which was previously enough to use Qt5 with meson).

**Comment by dcbaker** [comment]
I'm not entirely convinced that qt requiring lrelease is a bad thing, as some qt module helper will fail to work and crash in odd ways without it, but it is a behavioral change that wasn't documented.

**Comment by z3ntu** [comment]
It's really only necessary when you use the `compile_translations ` method which many Qt projects don't use.

**Comment by dcbaker** [comment]
My concern is more that we don't have nice error messages for this case, you just get a stack trace, but that's a separate bug and I'll file it as such.
