### ISSUE TITLE
Unable to append sources from a subdir with meson.current_source_dir() with Vala

### ISSUE THREAD

**Issue by astavale** [mesonbuild/meson#4655]
I have a simple project layout:

```
├── hello
│   ├── hello.vala
│   └── meson.build
├── main.vala
└── meson.build
```

The top level meson.build file:

```meson
project( 'subdir test', 'vala', 'c' )

dependencies = [
    dependency( 'glib-2.0' ),
    dependency( 'gobject-2.0' ),
]

sources = []

subdir( 'hello' )

sources += [ 'main.vala' ]

executable( 'hello-test', sources, dependencies: dependencies )
```

The intention is to append source files in sub-directories, so `hello/meson.build` is:

```meson
sources += [
   'hello/hello.vala',
]
```

This works, but it would be nice to have a way of the full path being worked out so I tried:

```meson
sources += [
   'hello.vala',
]
```
This comes back with a file not found error. That's fair enough, there is no special `sources` collector in Meson that works out paths.

So I tried:

```meson
sources += [
    join_paths(meson.current_source_dir(), 'hello.vala'),
]
```
Now this works as far as `meson setup my_build_dir` but when building Ninja comes back with a no input files error:

[2/4] Compiling C object 'hello-test@exe/meson-generated_hello.c.o'.
FAILED: hello-test@exe/meson-generated_hello.c.o 
ccache cc -Ihello-test@exe -I. -I.. -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -w 
g  -MD -MQ 'hello-test@exe/meson-generated_hello.c.o' -MF 'hello-test@exe/meson-generated_hello.c.o.d' -o 'hello-test@exe/meson-generated_hello.c.o' 
c 'hello-test@exe/hello.c'
cc: error: hello-test@exe/hello.c: No such file or directory
cc: fatal error: no input files
compilation terminated.

Now I've come across #1358 and #1376 that make it clear paths should be relative. This is fine, but it would be nice if there was a more elegant way of doing this in Meson.

**Comment by dcbaker** [comment]
Don't use `join_paths` use `files()`
do something like:
meson.build:
```meson
my_sources = files('main.vala')
subdir('subdir')
```
subdir/meson.build:
```meson
my_sources += files('hello.vala')
```
When you use `files()` meson can figure out relative directories for you automatically.

**Comment by astavale** [comment]
Works great! Thanks. I'll try and update the documentation at some point, at least the Vala documentation.
