### ISSUE TITLE
ImportError: No module named mesonbuild

### ISSUE THREAD

**Issue by agauniyal** [mesonbuild/meson#466]
After #465, I tried doing it this way : 

```
  # meson
  - wget https://github.com/mesonbuild/meson/releases/download/0.30.0/meson_0.30.0.tar.gz
  - tar -xvf meson_0.30.0.tar.gz
  - cd meson-0.30.0
  - sudo python3 setup.py install --prefix=/usr
  - sudo ln -s /usr/bin/meson.py /usr/bin/meson
```

and when executing `meson build` command on my project directory, it results in error -

```
$ meson build

Traceback (most recent call last):

  File "/usr/bin/meson", line 17, in <module>

    from mesonbuild import mesonmain

ImportError: No module named mesonbuild
```

**Comment by agauniyal** [comment]
To reproduce, you can see - https://github.com/agauniyal/rang

**Comment by jpakkane** [comment]
Don't ever install anything to `/usr` without using system packages. It is highly unlikely to work and can break stuff unexpectedly.

If you just want Meson installation, clone the Git repo (possibly doing `git checkout 0.30.0` or equivalent) and run Meson directly from that.

**Comment by agauniyal** [comment]
I guess travis won't let me do that, it will jump to my directory as soon as build step is encountered.
