### ISSUE TITLE
keyword "default_options" of dependency() doesn't work

### ISSUE THREAD

**Issue by Hi-Angel** [mesonbuild/meson#4661]
Initially I was trying to disable warnings for `gtest` dependency, so I found `dependency()` method [accepts `default_options` argument](https://github.com/mesonbuild/meson/blob/47b9c1a564756ac48a55da9a7c4d91787399c645/mesonbuild/interpreter.py#L1871). Unfortunately `default_options` doesn't seem to work. It accepts anything, and have no influence on build configuration.

# Steps to reproduce

1. create a file `test.cpp` with content

	```c++
	int main() {}
	```

	and a file `meson.build` with content:

	```bash
	project(
	  'project',
	  'cpp',
	  version: '0.1.0',
	)

	THREADS = dependency('threads', default_options: 'foobar')

	executable(
	  'foo',
	  'test.cpp',
	  install: false,
	  dependencies: THREADS
	)
	```
2. run `meson build && ninja -C build`

## Expected

Configuration fails, because meson has no option called `foobar`

## Actual

It successfully configures directory, then compiles the code.

# Additional information

meson version 0.48.2

**Comment by jpakkane** [comment]
This is perhaps not explained all that well [in the documentation](https://mesonbuild.com/Reference-manual.html#dependency) but what `default_options` means is that "if the dependency is looked up from a subproject, then pass the value of  `default_options` to that `subproject` invocation". That is if you have something like this:

```meson
d = dependency('foo', fallback: ['foo', 'foo_dep'], default_options: 'bob=baz')
```

Then it is roughly equivalent to this:

```meson
d = dependency('foo', required: false)
if not d.found()
  foo_sp = subproject('foo', default_options: 'bob=baz')
  d = foo_sp.get_variable('foo_dep)
endif
```

**Comment by Hi-Angel** [comment]
Oh, thanks, I guess it makes sense to close this.

I wonder, is there any way to pass compiler flags to a `dependency()`? Or even better, to make the header `dependency()` to be included with `-isystem` option, i.e. to suppress warnings coming from there?

**Comment by Hi-Angel** [comment]
> Or even better, to make the header dependency() to be included with -isystem option, i.e. to suppress warnings coming from there?

For that one there's a report https://github.com/mesonbuild/meson/issues/963
