### ISSUE TITLE
Regression: 'meson introspect --projectinfo' doesn't list subprojects with 0.49.0

### ISSUE THREAD

**Issue by gdesmott** [mesonbuild/meson#4662]
Running `meson introspect --projectinfo build/` in [gst-build](https://gitlab.freedesktop.org/gstreamer/gst-build) no longers lists the subprojects with 0.49.0 while it does with 0.48.2

```
# meson introspect --projectinfo build/
{"version": "1.15.0.1", "descriptive_name": "All GStreamer modules", "subprojects": []}
[root@zynq gst-build]# meson --version
0.49.0

# meson introspect --projectinfo build/
{"name": "All GStreamer modules", "version": "1.15.0.1", "subprojects": [{"name": "gstreamer", "version": "1.15.0.1"}, {"name": "gl-headers", "version": "0.0.0"}, {"name": "gst-plugins-base", "version": "1.15.0.1"}, {"name": "gst-plugins-good", "version": "1.15.0.1"}, {"name": "dssim", "version": "1.3.2.1"}, {"name": "gst-plugins-bad", "version": "1.15.0.1"}, {"name": "gst-plugins-ugly", "version": "1.15.0.1"}, {"name": "gst-omx", "version": "1.15.0.1"}, {"name": "gst-rtsp-server", "version": "1.15.0.1"}, {"name": "gst-devtools", "version": "1.15.0.1"}, {"name": "gst-editing-services", "version": "1.15.0.1"}]}
[root@zynq gst-build]# 
[root@zynq gst-build]# meson --version
0.48.2
```
This breaks https://gitlab.freedesktop.org/gstreamer/gst-build/blob/master/checkout-branch-worktree which relies on this output.

**Comment by jpakkane** [comment]
@mensinda could this be caused by one of the introspect refactorings?

**Comment by mensinda** [comment]
I am currently looking into it but I doubt it (most of it is not merged). The introspection code itself does not seem to be broken, but `Build.subprojects` (or `builddata.subprojects`) is an empty dict [here](https://github.com/mesonbuild/meson/blob/master/mesonbuild/mintro.py#L232).

**Comment by mensinda** [comment]
@gdesmott Could you test if #4666 correctly fixes the issue for you? There is an additional `descriptive_name` key for each subproject since 0.49.0.

**Comment by gdesmott** [comment]
Yes that fixed it. Thanks!
