### ISSUE TITLE
Using meson with pybind11

### ISSUE THREAD

**Issue by richardgedwards** [mesonbuild/meson#4677]
The pybind11 website indicates that to compile with pybind11 one should issue the following:

c++ -O3 -Wall -shared -std=c++11 -fPIC `python3 -m pybind11 --includes` example.cpp -o example`python3-config --extension-suffix`

How would one get this from the meson-build system?

**Comment by germandiagogomez** [comment]
El El mié, 26 dic 2018 a las 11:53, richardgedwards <
notifications@github.com> escribió:

> The pybind11 website indicates that to compile with pybind11 one should
> issue the following:
>
> c++ -O3 -Wall -shared -std=c++11 -fPIC python3 -m pybind11 --includes
> example.cpp -o examplepython3-config --extension-suffix
>
> How would one get this from the meson-build system?
>
I think there us a wrapdb package. Add it to your subproject and it should
work.

**Comment by germandiagogomez** [comment]
El El mié, 26 dic 2018 a las 23:28, richardgedwards <
notifications@github.com> escribió:

> Hi, thanks for the quick response. pybind11 is a header only library, so
> adding it to my project is not a problem. As far as I understand, using the
> wrapdb package as a subproject only helps with adding the pybind11 header
> to my existing project and does not provide details on how to compile it.
> Please correct me if I am wrong.
>
> The problem I am having is getting the correct name of my static library
> after it is compiled.
>
> Here is my meson.build file:
>
> project('pybindtest', 'cpp', default_options : ['cpp_std=c++14',])
> deps = [dependency('python3')]
> src = ['example.cpp']
> shared_library('example', sources : src, dependencies : deps)
>
>
If you want a python module I think you need to use shared_module from
reference manual. Try and tell me if it works for you.

https://mesonbuild.com/Reference-manual.html#shared-module

You can compose the name detecting the python version and so on with the
python module but do not know the details.

**Comment by richardgedwards** [comment]
After some research I found the following `meson.build` works to build pybind11 shared modules.

`project('pybindtest', 'cpp', default_options : ['cpp_std=c++11',])`
`pymod = import('python')`
`py = pymod.find_installation('python3')`
`py.extension_module('example', sources : 'example.cpp', dependencies : dependency('python3'))`

**Comment by fishbotics** [comment]
I know it's been a while since this closed, but @richardgedwards do you have an example repo with how you set everything up to work? 

Thanks!

**Comment by liveck** [comment]
> I know it's been a while since this closed, but @richardgedwards do you have an example repo with how you set everything up to work?
> 
> Thanks!

since pybind is header-only, all you need is include_dir

```
project('pybindexample', 'cpp', default_options : ['cpp_std=c++17',])

py3_inst = import('python').find_installation('python3')

pybind11_config = find_program('pybind11-config')
pybind11_config_ret = run_command(pybind11_config, ['--includes'])
pybind11 = declare_dependency(
    include_directories: [pybind11_config_ret.stdout().split('-I')[-1].strip()],
)

python3 = dependency('python3', ) 


py3avlw = py3_inst.extension_module('example',
    sources: ['example.cc',], 
    dependencies : [python3,pybind11],
    link_language : 'cpp',
    override_options: [
        'cpp_rtti=true',
    ]
)
```

**Comment by Nic30** [comment]
Explicit add of pybind11 include directory works only partly.
https://github.com/Nic30/meson-python-pybind11-example
```
pip3 install -e . --no-build-isolation \
  -Csetup-args="-Dbuildtype=debug"  \
  -Csetup-args="-Db_coverage=true"  \
  -Ccompile-args="--verbose" \
  -Cbuild-dir=build-dbg
```

```
  ../meson.build:16:15: ERROR: Tried to form an absolute path to a dir in the source tree.
      You should not do that but use relative paths instead, for
      directories that are part of your project.
      
      To get include path to any directory relative to the current dir do
      
      incdir = include_directories(dirname)
```
