### ISSUE TITLE
Meson should expose a way to detect if a specific compiler type is present.

### ISSUE THREAD

**Issue by jameshilliard** [mesonbuild/meson#4678]
It would be useful if meson exposed a way to determine if a specific functional compiler is present, for example it would be good to have a `meson.has_compiler('cpp')` method that functions similar to how `meson.get_compiler('cpp')` works but instead just returns a true/false. This is useful for c applications that have optional cpp features where we don't want to have cpp as a hard build requirement.

**Comment by xclaesse** [comment]
```
if add_languages('cpp', required : false)
endif
```

**Comment by jameshilliard** [comment]
Thanks, that seems to work.
