### ISSUE TITLE
Various PCH inconsistencies

### ISSUE THREAD

**Issue by nioncode** [mesonbuild/meson#4682]
While fixing a msvc PCH issue, I found a few inconsistencies in the handling of PCH between Ninja and VS backends and wanted to reach out to discuss these before I work on fixing this.

For GCC, I think everything is well understood and should work correctly.
For MSVC, however, there are a few requirements to be met in order to have correct PCH support:
1. Source files must include the pch header as very first include. This is handled by adding ForceIncludes to the compiler invocation. No problems at all. Note: the path to the pch header does not have to be correct and does not have to be in the include directories of the target, since msvc simply does a string comparison on the include file and does not look up the file in the include directories at all.
2. There has to be an implementation file that includes the pch header and thus creates the pch file. The include directive in this file must use the exact same path as the pch header file that gets included in 1), no matter in which directory the pch header actually lives. This creates a problem if the pch header is in a different directory than the implementation, because unlike to 1), msvc actually DOES look up the header in the target's include directories in order to successfully parse and compile it.

A few questions that arise from this:
- Do we want to support having pch headers in a different folder than their implementation?
  - If yes, then we should add a test case that enforces that this works (it currently breaks for Ninja + msvc).
  - If not, then we should enforce that both files are in the same directory when generating the build files and not wait for the compiler to decide if it works or not.
- Why don't we create the implementation file for msvc automatically? This would remove the requirement for the user to have the correct pch include path in their pch.c, which might be different from the relative path from pch.c to pch.h. We would then simply create a dummy pch.c for msvc targets that includes the correct pch header. A user thus only has to provide a pch.h just like for GCC and we will create the correct implementation automatically if needed.

/cc @john-preston who reached out to me via email to tell me about the original issue of the VS backend failing to compile a project that uses pch headers with include guards.

**Comment by john-preston** [comment]
Generating the required .cpp / .c files automatically looks really interesting.

Also one more workflow was broken for me: if the project uses two languages (and has both .c and .cpp), but has pch only for one (for example .cpp). The ForcedInclude is generated globally in this case and .c files have it too, trying to use pch prepared for .cpp file, resulting in an error.

If this workflow should be supported (for example, if it works in GCC) then the files of language without pch should have explicit empty ForcedInclude in generated .vcxproj (I didn't test that with Ninja).

If it shouldn't be supported (for example, if it doesn't work in GCC), it should be caught while generating the project.

**Comment by nioncode** [comment]
While we're at it, configuration should also fail if the pch file does not exist, just like it fails for non-existing source files.

**Comment by jpakkane** [comment]
> Do we want to support having pch headers in a different folder than their implementation?

That just complicates things for no real gain. All the documentation we have puts them in the same dir (and in fact I thought that we already enforce this but apparently don't).

**Comment by nioncode** [comment]
@john-preston I'm now implementing all of this. Could you attach an example setup that is broken for you when you have .c and .cpp sources, but only c_pch which fails? Then I'll check if this is possible in ninja and VS backends.

**Comment by nioncode** [comment]
Everything should be fixed now with #4833, #4860, #4903 being merged. Please re-open if you have any further issues.
