### ISSUE TITLE
Generate CMake and Autotools build scripts

### ISSUE THREAD

**Issue by DemiMarie** [mesonbuild/meson#4695]
This is a feature request for generation of CMake and Autoconf build scripts from Meson build files.  The generated scripts should not require Meson or Ninja to be installed.

**Comment by jpakkane** [comment]
I'm sorry but this will not be done. The coding and maintenance burden would be too big and nobody has volunteered to do it. To build Meson projects you need Meson. That's just the way it is.

**Comment by xclaesse** [comment]
FWIW, you can use cmake's ExternalProject feature to build meson code: https://cmake.org/cmake/help/latest/module/ExternalProject.html. And I have a PR for Meson that does the other way around (building cmake code from a Meson project): https://github.com/mesonbuild/meson/pull/4321.

It's not ideal, but that can help when you're forced to build pieces with multiple build systems.
