### ISSUE TITLE
In cross builds looks at host system for default library path

### ISSUE THREAD

**Issue by rossburton** [mesonbuild/meson#4713]
default_libdir() looks at the host paths to determine the default value of libdir:

- if /etc/debian_version exists
- if /usr/lib/lib64 exists

For native builds this is acceptable, but in cross builds these paths have no relevance.  I believe these checks should be done only if the build isn't being cross-compiled.

**Comment by QuLogic** [comment]
Seems a dupe of #2535.

**Comment by rossburton** [comment]
Yes, thanks.
