### ISSUE TITLE
meson test fails if LANG variable contains characters not valid in the current locale

### ISSUE THREAD

**Issue by ocrete** [mesonbuild/meson#4718]
To reproduce:

Add an environment variable with an accent:
`export BLOB=éêà`
Set LANG to a something that doesn'T contain the characters
`export LANG=POSIX`

Run meson test
`meson test -C build/`

See surrogates error:
```
root@276e4c1f828a libnice]# meson test -C build/
ninja: Entering directory `/root/libnice/build'
ninja: no work to do.
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 111, in run
    return options.run_func(options)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/mesonbuild/mtest.py", line 805, in run
    return th.doit()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/mesonbuild/mtest.py", line 555, in doit
    self.run_tests(tests)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/mesonbuild/mtest.py", line 686, in run_tests
    self.open_log_files()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/mesonbuild/mtest.py", line 656, in open_log_files
    self.logfile.write('Inherited environment: {}\n\n'.format(inherit_env))
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 1658-1659: surrogates not allowed
```

**Comment by ocrete** [comment]
Suggestion: Add "LANG=POSIX" to the meson test environment.

**Comment by lazka** [comment]
An alternative would be to print a big warning if there is a non-unicode locale active an just not support that case.

**Comment by xclaesse** [comment]
> An alternative would be to print a big warning if there is a non-unicode locale active an just not support that case.

That would be my suggestion too, unless @ocrete can show there are important platforms that cannot support unicode... in 2019...

**Comment by ocrete** [comment]
My platform is just a plain docker with CentOS 7, which has Python 3.6 as the most recent. I'd even be OK if meson had a hack to force the encoding to be C.utf8 if the default one is not utf8 ?

**Comment by ocrete** [comment]
I changed the content of the pull request, now on Python < 3.7 if the locale isn't UTF-8, we just close the codec that python chose and replace it forcefully with a UTF-8 one, matching the Python 3.7 behaviour I think.

We still need to do the encoding manually for the log files, as those are about surrogates, not locale.

Also last, I removed the Popen_safe_legacy code as the codec is always UTF-8 now.

**Comment by lazka** [comment]
> My platform is just a plain docker with CentOS 7

Try adding `ENV LANG en_US.utf8` to the docker file

**Comment by lazka** [comment]
I've opened #4729 for this

**Comment by lazka** [comment]
You can't change the encoding from inside a Python program, so this wont help much.
