### ISSUE TITLE
new find_library() broken for special shared objects

### ISSUE THREAD

**Issue by becm** [mesonbuild/meson#472]
Testing for libraries which need explicit `RPATH` fails but can be fixed.
There is however no feasible solution for using a **must link** approach with shared objects like `LUA` modules or similar widespread incomplete linked library types.

Additional `Keyword Argument` to fall back to old approach (no compiling/linking) may solve this problem while keeping new style for compatible libraries.

Fixes for bad error message and `RPATH` problem are available but general problem with approach may make them irrelevant (comment if desired anyway).

**Comment by jpakkane** [comment]
When you do a `find_library` the only thing you can use the result on is linking with a a target. How would you use modules like these in a build then? Can you link them to something if you link all their deps (presumably some sort of `liblua`) manually?

**Comment by becm** [comment]
The test for a library tries to create an executable, so all referenced symbols must be resolved for the test so succeed.
A call to `dosomething()` in a shared library does not mean this function is in one of the libraries it links against (or must be in the static library you tried to find).
A standard `main()` (or `_start()`) executable will always fail to link against such a shared library (or any static library which does not include all its required symbols).

Supplying further libraries when running `find_library()` is (at the moment) impossible and also not a valid solution: The missing symbol may be in the target you are trying to build **at this moment**.

Try to build an executable which hosts the `LUA` runtime and also links in a `LUA` module library. It is impossible to **find** the library the current way:
-  Runtime functions are loaded/supplied by the interpreter or (other) embedding executable.
-  No available resolution of `LUA` environment (`lua_*` and `luaL_*`) inside module libraries.

The same approach is used in many numerical libraries: A shared object has a runtime dependency on functions which can be supplied by different math libraries.
Only the executable must then link against a library supplying these symbols in an optimized version for the current platform (e.g. `LAPACK`/`BLAS` interfaces).

A good solution (and compromise) may be an option to create a shared object instead of an executable (e.g.: `…link_library('mylib', shared : true)` defaulting to `false`).
This should check all explicit dependencies a library has while not failing when additional (runtime) symbols are referenced.

**Comment by becm** [comment]
An `RPATH` option/fallback for the new style `find_library()` is still needed:

The library to find depends on another library in a **non-standard** location.
Even if the `RPATH` in the first library is set correctly (dynamic loading works), the (GNU) linker fails to not find the second library while linking against the first.

Should this be addressed in a separate issue?

**Comment by nirbheek** [comment]
Right now `cc.find_library()` will successfully find the library even if you can't link to it without special flags, so I think this bug is fixed.  Please reopen this issue if that doesn't happen for you!

I think for handling cases like these without having to think about it, you should use a pkg-config file since that allows you to specify cflags and libs + paths to use while linking to it. The alternative to a pkg-config file is to add the `RPATH` manually while linking to the library in each target.

**Comment by becm** [comment]
The `pkg-config` files for Lua modules are "bad" for this task, they include linking the (in some cases WRONG) Lua runtime library  (Debian 8).

The problem on the `meson`-side "shifted" to the global-only option `b_lundef` which I did not find any way/documentation to set on a per-target basis or even (suboptimal) for a whole project from within the build file (only via `mesonconf`).
Needed for targets with intentionally [unresolved symbols](https://gist.github.com/becm/370e415a3060c9124f63a04ed852a203) at link time.
Is there a way or are there plans to address this?

**Comment by jpakkane** [comment]
You can set the default with project():

    project(...,
      default_options : ['b_lundef=false'])

Note that this only applies for new build trees, existing ones keep the old value.

**Comment by becm** [comment]
Thanks for the quick reply, seems I overlook this option in the documentation.
Is this setting relevant for anything except a partially linked shared library?
Are there a problems making this a per-target option?

**Comment by nirbheek** [comment]
That option is also relevant while linking plugins that expect the main binary to provide critical symbols, and on some platforms like BeOS that use it as a feature (although I don't know anyone who uses Meson on BeOS!).

I don't know if a per-target option for this makes sense. Especially because it would not be clear whether you are referring to undefined symbols in the objects of the target you are building or in the shared library you are linking with.

In your case, you can pass `--allow-shlib-undefined` manually in `link_args` while linking to lua.

**Comment by becm** [comment]
Are these plugins not just shared libraries with (some) unresolved symbols (same as Lua modules)?

The meaning of a boolean flag would be the same as with the current implementation (symbols in current target).
Currently if there is ONE target which needs this option we have to give up on checks for normal libraries in the same project (set global `b_lundef=false`). Making this a target option would mark a target as "special" while preserving symbol checks on normal shared libraries (on platforms where this is feasible).
An ugly workaround is to create separate projects for the the special targets, which has some strong limitations given the current `subproject()` implementation (global subproject path instead of per-subproject option (no `subproject('mysub', dir : 'mydir')`).

The Option `-Wl,--allow-shlib-undefined` would only help if the target links against libraries with undefined symbols (and is used by default), not when creating a module/plugin library.
This is in fact a way better argument to make this option target-specific and shows that `true/false` is not a sufficient representation.

A per-target option could be (with flags for Linux/ELF):
- `sym_undef : ['target']` (`-Wl,--no-allow-shlib-undefined`)
- `sym_undef : []` (`-Wl,--no-undefined -Wl,--no-allow-shlib-undefined`)
- `sym_undef : ['lib']` (default, mirror `b_lundef = true`, `-Wl,--no-undefined -Wl,--allow-shlib-undefined`)
- `sym_undef : ['target', 'lib']` (mirror `b_lundef = false`, `-Wl,--allow-shlib-undefined`)

and be mapped on Darwin/Windows to the according linker flags to make it portable.
On BeOS/HPPA/… the option can be ignored (or whatever is most appropriate).
Abbreviations can be `[] -> false, ['target', 'lib'] -> true, ['lib'] -> 'lib'`.

There is furthermore no portable way to export symbols from a executable, which is needed to build a binary which can use such plugin libraries (no `sym_export` option for executables).

**Comment by jpakkane** [comment]
If you have a target that you know always needs undefined libraries you can do this:

    link_args : ['-Wl,--undefined']

Per target link args are placed after global ones so they override the default settings.

**Comment by becm** [comment]
These jumble the the linker arguments on my primary platform (Linux, GNU toolchain), leading to mishandling the following `-Wl,-rpath,…`.

Even in its *correct* form as e.g. `link_args : ['-Wl,--undefined=lua_tolstring']` the symbol `lua_tolstring` is still reported as unresolved. This does furthermore not scale for many undefined symbols.

A *working* [solution](https://github.com/becm/mpt-base/commit/09dc2bbbac4550d96550b808a87978aa5d4ceeba) was to use `link_args : ['-Wl,--unresolved-symbols=ignore-in-object-files']`.
This is also a better 4-choice-argument to be used in my proposal for implementing a per-target option when run on an ELF platform with GNU toolchain.
