### ISSUE TITLE
Multiline statements give a syntax error

### ISSUE THREAD

**Issue by Twey** [mesonbuild/meson#4720]
In Meson 0.48.2, a multiline statement of the form

```meson
foo = bar \
  + baz
```
or
```meson
foo = bar + \
  baz
```
will give an error:
```
meson.build:1:10: ERROR:  Expecting eof got eol_cont.
foo = bar \
          ^
```

This seems to be in contravention of https://github.com/mesonbuild/meson/blob/master/docs/markdown/Syntax.md , which says:
> Function and method calls' argument lists can be split over multiple lines. Meson will autodetect this case and do the right thing. In other cases you can get multi-line statements by ending the line with a `\`.
This implies to me that the above statement should be syntactically valid.

Am I misunderstanding the documentation, or does the implementation not match the specification?

**Comment by xclaesse** [comment]
It seems to be the intention, but that seems to have never worked, I tested with older meson versions. It seems that `\` works when it's after a coma in a function call, but in that case you don't even need it.

This definitely need a unit test.
