### ISSUE TITLE
non-consistent handling of non-registered extensions

### ISSUE THREAD

**Issue by zpgaal** [mesonbuild/meson#473]
For vs2010 backend it is good if you don't have to leave the IDE. There should be a way to add all the generator scripts and meta files to the project/solutions. For VS2010 it works, but the same meson.build script fails for ninja backend as it triggers exception indicating that no compiler was found in get_compiler_for_source.

It'd be even better if these files could be added to the custom_target project.

**EDIT**
It is not working for vs either as it tries to compile them as C/C++ file

**Comment by nioncode** [comment]
Please post an example `meson.build` and what you expect in the IDE.

**Comment by zpgaal** [comment]
As a starting point I wish it were working for non-custom targets:
ex: 
lib_engine = shared_library(
    'engine',
    ['engine.cpp','gen_engine.py'],
)
The generated project should add gen_engine.py as it does now, but it's ItemType should be something like "Does not participate in build".

For custom_target it should enlist the inputs in the same way as the sources and headers are listed for other targets but compilation should be disabled. I'm not sure if it can be set project-wild or have to be done for each input independently.

Note, I'm using VS2015 with some minor meson modification to be able to load projects without conversion:
 - added toolsversion = 14.0
 - added PlatformToolset = v140 under each PropertyGroup / Configuration
[patch.zip](https://github.com/mesonbuild/meson/files/189762/patch.zip)

**Comment by nioncode** [comment]
Did you test with the current `master`? The vs2010 backend does exactly that for build targets.

For `custom_target`s and `generator`s we could add all input (and even output?) files to the project to make them visible and editable in the IDE.

**Comment by jpakkane** [comment]
And if there are extra files that are not part of the build itself but which you want to show up as part of the target, there's the `extra_files` keyword argument.

**Comment by nioncode** [comment]
#488 now adds the `extra_files` to the VS project.

**Comment by nirbheek** [comment]
@nioncode Do we still not add input and output files from `custom_target` and `generator` to the VS project files or can we close this bug?

**Comment by nioncode** [comment]
@nirbheek I don't remember actually. Just checked the code and it looks like everything gets properly added. I don't have a Windows machine available to test it, though.

**Comment by nirbheek** [comment]
We use custom targets and generators in a bunch of places in gstreamer, and it's all worked fine for me with the VS backends. Let's close this and open new issues for any problems we see.
