### ISSUE TITLE
New point release?

### ISSUE THREAD

**Issue by pkgw** [mesonbuild/meson#4741]
Hello,

I'm affiliated with the [conda-forge](https://conda-forge.org/) packaging project, and we currently have [a package upgrade](https://github.com/conda-forge/gobject-introspection-feedstock/pull/9) that can't proceed because we need the change implemented in Meson PR #4187, which hasn't yet made it into a release yet.

Are there any plans to make a point release in the near future? We'd appreciate if that happened sooner rather than later, if it's not too inconvenient.

Thanks,

Peter

**Comment by lazka** [comment]
@pkgw you could also backport https://gitlab.gnome.org/GNOME/gobject-introspection/commit/a6f2c00c0c414a85

**Comment by jpakkane** [comment]
The point release manager is @nirbheek, hopefully he will comment on the plans for that.

**Comment by pkgw** [comment]
@lazka Yes, we will definitely consider a backport, but if there's a good prospect of there being a point release in, say, a week or two, I'd prefer to stick to official releases.

**Comment by pkgw** [comment]
This must be in by now. I'm too lazy to actually verify that, though!
