### ISSUE TITLE
qt dep regression: unable to find qt libraries

### ISSUE THREAD

**Issue by wberrier** [mesonbuild/meson#4742]
I have a project attempting to find qt with:

```
dependency('qt5', modules : ['...'], method : 'qmake')                                                                                                                                            
```

It's coming back with:
```
ERROR:  Dependency "qt5" not found, tried qmake-qt5 and qmake
```

qmake-qt5 is in the path.

So far, I've only narrowed it down to this commit: aa04147a (dependencies/ui: Allow qt compilers and qmake to be specified in native file), but haven't looked any further yet.

**Comment by z3ntu** [comment]
Duplicate of #4641 ?

**Comment by wberrier** [comment]
@z3ntu Shoot, yes, you are correct, this is a duplicate, sorry for the noise (I was positive I tested master :( )
