### ISSUE TITLE
generator() with multiple outputs doesn't print output name

### ISSUE THREAD

**Issue by jml1795** [mesonbuild/meson#4760]
When using a generator with multiple outputs, nothing is printed to the console when invoking ninja; when invoking ninja to use a generator with a single output, the output is printed to the console.

For example:
```sh
gen = generator(
  command,
  output : [
    '@BASENAME@.cpp',
    '@BASENAME@.hpp',
  ],
  arguments : [
    '@INPUT@',
    '@BUILD_DIR@',
    '@CURRENT_SOURCE_DIR@'
  ],
)

src = gen.process([ 'File1' ])
```

yields

![image](https://user-images.githubusercontent.com/45511331/51006436-33d90a00-1511-11e9-994d-02b4264ed069.png)

I am not sure if this is a ninja issue due to command line being too long, or something in meson not handling multiple outputs. Its also not clear to me what the intended behavior should be, since you could generate numerous outputs from each input, causing message spam at the console. Maybe it should print the name of the input file. Something like: `Generating from: 'File1.idl'` for example

@jpakkane I'm happy to make a merge request for this if you think it should be fixed and can point me in the correct direction.

**Comment by germandiagogomez** [comment]
Confirmed it happened to me as well in version 0.49

**Comment by jml1795** [comment]
I am running 0.49 as well.

It looks like there are explicit checks for `len(generator.outputs) == 1:` at `ninjabackend.py:1715` on commit `c208e81e`.

Looks like this was a conscious decision to only handle outputs of length 1. Any ideas on an improvement here?

**Comment by jml1795** [comment]
@jpakkane Thanks for the response. I had this as a snippet from a larger project. I am passing the generated output from the process call to a `shared_library` rule. I have about 500 generated files and a shared library + a test app linking against the `.so` through a `dependency object`. Everything is being generated / linked correctly, it is just that ninja doesn't display what it is working on when the generator rule has more than one file as the `output` from the generator.

More complete snippet:
```py
gen = generator(
  command,
  output : [
    '@BASENAME@.cpp',
    '@BASENAME@.hpp',  # problem resolved if only one output file from generator
  ],
  arguments : [
    '@INPUT@',
    '@BUILD_DIR@',
    '@CURRENT_SOURCE_DIR@'
  ],
)

gen_src = gen.process([ 'File1' ])

gen_lib = shared_library(
  'gen', [
    gen_src,
  ],
  cpp_args : [
    '-Wno-unused'
  ],
  dependencies : [some_dep],
  install : true
)

gen_dep = declare_dependency(
  link_with: [gen_lib],
  include_directories: gen_lib.private_dir_include(),
)

app = executable('driver', 'main.cpp', dependencies: gen_dep)
```

**Comment by jml1795** [comment]
I updated the linked test to show the same issue. The `protoc` compiler is quick enough when acting on the test files that the issue isn't apparent. See [here](https://github.com/jml1795/meson/commit/bb883c2d9de4fbd207802cd570cddccfbb8ecb8b) for a demonstration of the issue.

**Comment by nirbheek** [comment]
Closed in https://github.com/mesonbuild/meson/pull/4941
