### ISSUE TITLE
Meson not detecting Apple linker with standard Clang

### ISSUE THREAD

**Issue by jtojnar** [mesonbuild/meson#4784]
We [wanted](https://github.com/NixOS/nixpkgs/pull/54007) to link `glib` against Mac libraries but the build failed with:

```
FAILED: gio/libgio-2.0.0.dylib
cc  -o gio/libgio-2.0.0.dylib 'gio/6ae6c9e@@gio-2.0@sha/meson-generated_.._gioenumtypes.c.o' […] 'gio/kqueue/9c7395d@@kqueue@sta/dep-list.c.o' -Wl,-O1 -shared -fPIC -Wl,-soname,libgio-2.0.dylib.0 -Wl,-framework,CoreFoundation -Wl,-framework,Carbon -Wl,-framework,Foundation -Wl,-framework,AppKit glib/libglib-2.0.0.dylib gobject/libgobject-2.0.0.dylib gmodule/libgmodule-2.0.0.dylib /nix/store/rfdg8nclvfhv4pcyqx0iaqk27173p0gm-zlib-1.2.11/lib/libz.dylib -Wl,--start-group -lresolv -Wl,--end-group -Wl,-headerpad_max_install_names -Wl,-rpath,@loader_path/../glib -Wl,-rpath,@loader_path/../gobject -Wl,-rpath,@loader_path/../gmodule -Wl,-rpath,/nix/store/y09iv91qmr970jz8yqg08vsjjf190phx-pcre-8.42/lib -Wl,-rpath,/nix/store/hq8zhb906blq4kw3q1p283yfzmyynhiy-libffi-3.2.1/lib -Wl,-rpath,/nix/store/rfdg8nclvfhv4pcyqx0iaqk27173p0gm-zlib-1.2.11/lib -Wl,-rpath-link,/private/tmp/nix-build-glib-2.58.2.drv-0/glib-2.58.2/build/glib:/nix/store/y09iv91qmr970jz8yqg08vsjjf190phx-pcre-8.42/lib:/private/tmp/nix-build-glib-2.58.2.drv-0/glib-2.58.2/build/gobject:/nix/store/hq8zhb906blq4kw3q1p283yfzmyynhiy-libffi-3.2.1/lib:/private/tmp/nix-build-glib-2.58.2.drv-0/glib-2.58.2/build/gmodule:/nix/store/rfdg8nclvfhv4pcyqx0iaqk27173p0gm-zlib-1.2.11/lib
ld: unknown option: -O1
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
```

The linker flag apparently comes from

https://github.com/mesonbuild/meson/blob/bbcf80d7348135e0590622a7b85c30429f005c07/mesonbuild/compilers/compilers.py#L177-L183

which is selected in

https://github.com/mesonbuild/meson/blob/bbcf80d7348135e0590622a7b85c30429f005c07/mesonbuild/compilers/compilers.py#L1477-L1479

The Objective-C compiler returns the following output for `--version`

```
clang version 5.0.2 (tags/RELEASE_502/final)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /nix/store/frq6nffl9iszwlznlha23jyv2p1rrgc9-clang-5.0.2/bin
```

and when I pass it `-Wl,-v`, I get

```
@(#)PROGRAM:ld  PROJECT:ld64-274.2
configured to support archs: armv6 armv7 armv7s arm64 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em (tvOS)
Library search paths:
        […]
Framework search paths:
        […]
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
```

This means the compiler object will be instantiated with `CompilerType.CLANG_STANDARD` instead of `CompilerType.CLANG_OSX`

https://github.com/mesonbuild/meson/blob/0.49.0/mesonbuild/environment.py#L801

even though we use the Apple linker (actually ld64 from https://github.com/tpoechtrager/cctools-port).

C compiler works fine since it [detects](https://github.com/mesonbuild/meson/blob/0.49.0/mesonbuild/environment.py#L671) Darwin with `mesonlib.for_darwin(want_cross, self)`.

As a stopgap, we could add the same check to `detect_objc_compiler` but in the long term, Meson should probably check the linker name for determining whether `gnulike_buildtype_linker_args` should be used.

Encountered on Meson 0.49.0.

**Comment by jpakkane** [comment]
Can you post the output of  `cc --version`? On my macOS machine it starts with `Apple LLVM` which means it should be recognized as CLANG_OSX.

**Comment by jtojnar** [comment]
Sorry, I should have been clearer, it is the following, already included in the opening post:

```
clang version 5.0.2 (tags/RELEASE_502/final)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /nix/store/frq6nffl9iszwlznlha23jyv2p1rrgc9-clang-5.0.2/bin
```

I think we use regular Clang we built, not the `Apple LLVM`. cc @LnL7 @matthewbauer

**Comment by Akaricchi** [comment]
I just ran into the same problem today. In my case, I'm using [a cross-compiling toolchain](https://github.com/tpoechtrager/osxcross) on Linux targeting macOS, with the stock clang and the Darwin linker. You really shouldn't assume the linker's properties based on the compiler.

**Comment by zhangyoufu** [comment]
And by the way, Meson cannot detect Apple clang as well.

Here is the output of `clang --version` for Command Line Tools for Xcode 11 Beta.
```
Apple clang version 11.0.0 (clang-1100.0.20.17)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

As you can see, Apple has changed from `Apple LLVM` to `Apple clang`.
