### ISSUE TITLE
`ninja install` is slow

### ISSUE THREAD

**Issue by rhd** [mesonbuild/meson#480]
Hey Jussi, doing `ninja install` has seemed slow to me for a while so I finally wrote a script that does the same thing as meson does when the installer is executed. There are around 30 things that get copied. I basically converted `Installing apps/app1/app1 to /install/bin/app1` to `cp apps/app1/app1 /install/bin/app1` to compare.

```
time ninja -C build-gcc install
ninja: Entering directory `build-gcc'
[1/1] Installing files.
....
real	0m4.258s
user	0m3.213s
sys	0m0.900s
```

vs

```
./installtest.sh 

real	0m1.014s
user	0m0.015s
sys	0m0.375s
```

Over a 4x penalty. This is repeatable even with hot disk cache.

**Comment by jpakkane** [comment]
Python invocation has some perf penalty but it should not be that big. Could you try the following.

The installer script preservers file attributes. On Linux you should achieve the same with the `--preserve=all` argument to cp. Does that have an effect?

Can you run the installer script manually under pdb to see what part of the Python script is consuming the time?

**Comment by rhd** [comment]
I've added `--preserve=all` to my test script and the speed didn't really change.

```
$ time ./installtest.sh 

real	0m1.024s
user	0m0.019s
sys	0m0.389s
$ time ./installtest.sh 

real	0m1.011s
user	0m0.018s
sys	0m0.358s
$ time ./installtest.sh 

real	0m1.008s
user	0m0.010s
sys	0m0.375s
```

I'll look into running the script manually and report back. I'm a `pdb` noob.

Thanks!

**Comment by rhd** [comment]
`python3 -m cProfile -s tottime /opt/meson/meson --internal install /path/to/build-gcc/meson-private/install.dat`

produces:

```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       50    3.431    0.069    3.431    0.069 {method 'poll' of 'select.poll' objects}
    15416    0.245    0.000    0.245    0.000 {method 'write' of '_io.BufferedWriter' objects}
       29    0.189    0.007    0.603    0.021 shutil.py:90(copyfile)
    15446    0.093    0.000    0.093    0.000 {method 'read' of '_io.BufferedReader' objects}
      112    0.061    0.001    0.061    0.001 {built-in method io.open}
       30    0.026    0.001    0.026    0.001 {built-in method posix.waitpid}
       29    0.023    0.001    0.023    0.001 {built-in method _posixsubprocess.fork_exec}
       29    0.016    0.001    0.353    0.012 shutil.py:70(copyfileobj)
      105    0.013    0.000    0.013    0.000 {built-in method posix.read}
       83    0.012    0.000    0.012    0.000 {built-in method marshal.loads}
  476/474    0.009    0.000    0.022    0.000 {built-in method builtins.__build_class__}
       16    0.006    0.000    0.006    0.000 {built-in method _imp.create_dynamic}
     93/1    0.005    0.000    4.226    4.226 {built-in method builtins.exec}
```

**Comment by nirbheek** [comment]
The installer also needs to invoke the linker to rewrite rpaths in binaries and libraries from the builddir to the install dir. Have you tried disabling that in Meson to see if it's faster? If it does, there might be room for a "fast install" mode where Meson never sets rpaths.

**Comment by rhd** [comment]
I'm not explicitly using meson to set rpath anywhere. I'll do more poking around tomorrow.

**Comment by rhd** [comment]
@nirbheek You're right. The installer executes the `depfixer` for each target. That is what's most likely causing the slowdown.

**Comment by rhd** [comment]
If I comment out [this](https://github.com/mesonbuild/meson/blob/master/mesonbuild/scripts/meson_install.py#L205) if block, the install process approximates the script that simply uses `cp`.

Jussi, I'd love an explanation about what meson does re: rpath and the depfixer. Is it possible to short circuit this so it can be fast?

Thanks!

**Comment by jpakkane** [comment]
Meson sets up the rpath so that the binaries can be run directly from the build dir. The way it does this is basically swiped directly from CMake. When installing these custom rpath entries need to be removed, otherwise they will cause things to break massively.

The script itself should be fast, it does not relink but just edits the elf files directly. The slowdown is probably caused by the extra Python invocation. If this is the case then it should be easy to change the script so that rather than invoking depfixer as an external binary, it imports it and calls the function directly.

**Comment by rhd** [comment]
Just as a test I did just called `fix_rpath()` directly and the performance good... a touch slower than the `cp` only script.

```diff
--- /opt/meson/mesonbuild/scripts/meson_install.py.bak	2016-03-29 16:29:46.472203335 -0700
+++ /opt/meson/mesonbuild/scripts/meson_install.py	2016-03-29 16:33:17.483329329 -0700
@@ -16,6 +16,7 @@
 
 import sys, pickle, os, shutil, subprocess, gzip, platform
 from glob import glob
+from .depfixer import Elf
 
 def do_install(datafilename):
     ifile = open(datafilename, 'rb')
@@ -199,15 +200,8 @@
                     print("Symlink creation does not work on this platform.")
                     printed_symlink_error = True
         if is_elf_platform():
-            p = subprocess.Popen(d.depfixer + [outname, install_rpath],
-                                 stdout=subprocess.PIPE,
-                                 stderr=subprocess.PIPE)
-            (stdo, stde) = p.communicate()
-            if p.returncode != 0:
-                print('Could not fix dependency info.\n')
-                print('Stdout:\n%s\n' % stdo.decode())
-                print('Stderr:\n%s\n' % stde.decode())
-                sys.exit(1)
+            e = Elf(outname)
+            e.fix_rpath(install_rpath.encode('utf8'))
 
 def run(args):
     if len(args) != 1:
```

This produces noise though so is not an optimal solution. Lots of these:
```
File does not have rpath. It should be a fully static executable.
```

Anyway, hopefully a proper fix can be implemented. :)
