### ISSUE TITLE
cc.get_define doesn't support subprojects

### ISSUE THREAD

**Issue by emersion** [mesonbuild/meson#4800]
I try to call `cc.get_define('WLR_HAS_XWAYLAND', prefix: '#include <wlr/config.h>', dependencies: wlroots)`. `wlroots` is either an external dependency or a subproject. The latter case fails with:

```
ERROR:  Dependencies must be external dependencies
```

**Comment by xclaesse** [comment]
That's by design, because how those tests are implemented is by compiling a small code snippet, at configure time. But that cannot be done when a dependency of that code is only built at build time.

You have to move your get_define() in a if-block only if it's not subproject case.

**Comment by emersion** [comment]
Ah, that does make sense. Thanks!
