### ISSUE TITLE
CMake ZLIB detection does not work  on some machines

### ISSUE THREAD

**Issue by jpakkane** [mesonbuild/meson#4812]
For some reason `linuxlike/13 cmake dependency` fails to work for me on Kubuntu 18/04 and 18/10. It does work on a different machine with Ubuntu 18/04. I have CMake and stuff installed and `FindZLIB.cmake` is in the `/usr/share`.

Attached is a log of the output of CMake trace as it is run.
[cmakelookup.txt](https://github.com/mesonbuild/meson/files/2780319/cmakelookup.txt)

**Comment by mensinda** [comment]
This seems to be a CMake issue:

From the trace output:
```
/usr/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake(255):  set(ZLIB_FOUND FALSE )
```
With this line the `ZLIB_FOUND` variable is set to `FALSE`. This means that Zlib was not found.

Also, the trace ends with the line:
```
/home/jpakkane/workspace/meson/build/meson-private/cmake_ZLIB/CMakeLists.txt(22):  if(ZLIB_FOUND OR ZLIB_FOUND )
```
Because the content of the if block is not evaluated, the condition (`ZLIB_FOUND OR ZLIB_FOUND`) was not met.

To verify that CMake can't find Zlib try running:
```bash
cmake --find-package -DCOMPILER_ID=GNU -DLANGUAGE=CXX -DMODE=EXIST -DNAME=ZLIB
```

Since, this seems to be a CMake issue, this command should also fail on the systems in question.

**Comment by jpakkane** [comment]
```
cmake --find-package -DCOMPILER_ID=GNU -DLANGUAGE=CXX -DMODE=EXIST -DNAME=ZLIB 
ZLIB not found.
CMake Error: Problem processing arguments. Aborting.
```

**Comment by mensinda** [comment]
In this case, this is (almost certainly) a CMake issue:

Output for __found__ dependency:

```bash
~ cmake --find-package -DCOMPILER_ID=GNU -DLANGUAGE=CXX -DMODE=EXIST -DNAME=ZLIB
ZLIB found.
```

Output for __not found__ dependency:

```bash
~ cmake --find-package -DCOMPILER_ID=GNU -DLANGUAGE=CXX -DMODE=EXIST -DNAME=DoesNotExist
DoesNotExist not found.
CMake Error: Problem processing arguments. Aborting.

```

**Comment by mensinda** [comment]
On further digging in the trace:
```
/usr/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake(242):  foreach(_CURRENT_VAR ZLIB_LIBRARY;ZLIB_INCLUDE_DIR )
/usr/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake(243):  if(NOT ZLIB_LIBRARY )
/usr/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake(244):  set(FPHSA_FOUND_ZLIB FALSE )
/usr/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake(245):  string(APPEND MISSING_VARS  ZLIB_LIBRARY )
/usr/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake(243):  if(NOT ZLIB_INCLUDE_DIR )
/usr/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake(246):  else()
```
From these lines I conclude that the ZLIB header was found, but the library itself was not (one if is executed, the other isn't). Thus both `find_library` calls in the `FindZLIB.cmake` fail for some reason. Unfortunately, I have no idea why this happens.

**Comment by jpakkane** [comment]
This is bog standard CMake installed from Ubuntu repos. There's nothing to break it. The only possible culprit I can think of is multiarch support but even that should work.

**Comment by mensinda** [comment]
The only other thing you could try is to create this `CMakeLists.txt`:

```cmake
cmake_minimum_required(VERSION 3.5)

find_package(ZLIB REQUIRED)
```

Then run `cmake .`. If this also fails it is definitely a CMake issue. This would be (probably) impossible to fix in meson.

**Comment by jpakkane** [comment]
```
-- The C compiler identification is GNU 8.2.0
-- The CXX compiler identification is GNU 8.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Configuring done
-- Generating done
```

**Comment by mensinda** [comment]
This is strange. Would you mind attaching a trace (`--trace --trace-expand`) of the successful CMake run?

**Comment by jpakkane** [comment]
[cmaketrace.txt](https://github.com/mesonbuild/meson/files/2780691/cmaketrace.txt)

**Comment by mensinda** [comment]
Thanks. I will try to figure out what is going wrong. In the meantime, commenting out [these lines](https://github.com/mesonbuild/meson/blob/master/mesonbuild/dependencies/base.py#L1405-L1406) should solve the problem. However, this will significantly increase the execution time of CMake.

**Comment by jpakkane** [comment]
I can verify that removing those lines fixes the issue.

**Comment by mensinda** [comment]
Then this behavior is caused by the fake CMake cache created by those functions. The purpose of this fake build directory is to trick CMake to skip a lot of (what I thought was) unnecessary initialization and compiler verification. I will set up a Kubuntu VM and check if it is possible to fix the fake build directory.

I am personally against removing the build directory initialization because it does significantly speed up CMake.

**Comment by jpakkane** [comment]
This is a multilib issue somehow. If I install `zlib1g-dev:i386` then the test works. The problem seems to be that CMake for some reason does the check with the 32 bit toolchain rather than the 64 bit one.

**Comment by cocofish** [comment]
`yum install zlib-devel  `

**Comment by magjac** [comment]
Related to https://gitlab.kitware.com/cmake/cmake/-/issues/20127?
