### ISSUE TITLE
Crash when running subprograms, in Windows, Python < 3.7, non-UTF8 locale.

### ISSUE THREAD

**Issue by pkgw** [mesonbuild/meson#4827]
[This AppVeyor build log](https://ci.appveyor.com/project/conda-forge/gobject-introspection-feedstock/builds/21899507) of building gobject-introspection on Windows in Python 3.6 shows a crash in meson:

```
[79/97] "C:/bld/gobject-introspection_1548453994599/_h_env/python.exe" "C:/bld/gobject-introspection_1548453994599/_h_env/Scripts/meson" "--internal" "exe" "C:/bld/gobject-introspection_1548453994599/work/forgebuild/meson-private/meson_exe_g-ir-compiler_56d218805e907ae4b0ce4fe93fbe50440d2cc399.dat"
FAILED: gir/libxml2-2.0.typelib 
"C:/bld/gobject-introspection_1548453994599/_h_env/python.exe" "C:/bld/gobject-introspection_1548453994599/_h_env/Scripts/meson" "--internal" "exe" "C:/bld/gobject-introspection_1548453994599/work/forgebuild/meson-private/meson_exe_g-ir-compiler_56d218805e907ae4b0ce4fe93fbe50440d2cc399.dat"
Traceback (most recent call last):
  File "C:/bld/gobject-introspection_1548453994599/_h_env/Scripts/meson", line 12, in <module>
    sys.exit(main())
  File "%PREFIX%\lib\site-packages\mesonbuild\mesonmain.py", line 209, in main
    return run(sys.argv[1:], launcher)
  File "%PREFIX%\lib\site-packages\mesonbuild\mesonmain.py", line 198, in run
    return run_script_command(args[1], args[2:])
  File "%PREFIX%\lib\site-packages\mesonbuild\mesonmain.py", line 146, in run_script_command
    return module.run(script_args)
  File "%PREFIX%\lib\site-packages\mesonbuild\scripts\meson_exe.py", line 99, in run
    return run_exe(exe)
  File "%PREFIX%\lib\site-packages\mesonbuild\scripts\meson_exe.py", line 85, in run_exe
    sys.stdout.buffer.write(stdout)
  File "%PREFIX%\lib\codecs.py", line 376, in write
    data, consumed = self.encode(object, self.errors)
TypeError: utf_8_encode() argument 1 must be str, not bytes
```

The build succeeds on other platforms and in Python 3.6.

I think that what's going on here is that [run_exe](https://github.com/mesonbuild/meson/blob/master/mesonbuild/scripts/meson_exe.py#L44) assumes that `sys.stdout.buffer` is a stream that accepts bytes rather than Unicode. However, in this particular configuration, that is not the case.

I believe that the culprit is [mesonmain.py:ensure_stdout_accepts_unicode()](https://github.com/mesonbuild/meson/blob/master/mesonbuild/mesonmain.py#L154-L163):

```python
def ensure_stdout_accepts_unicode():
    if sys.stdout.encoding and not sys.stdout.encoding.upper().startswith('UTF-'):
        if sys.version_info >= (3, 7):
            sys.stdout.reconfigure(errors='surrogateescape')
        else:
            sys.stdout = codecs.getwriter('utf-8')(sys.stdout.detach(),
                                                   errors='surrogateescape')
            sys.stdout.encoding = 'UTF-8'
            if not hasattr(sys.stdout, 'buffer'):
                sys.stdout.buffer = sys.stdout.raw if hasattr(sys.stdout, 'raw') else sys.stdout
```

In AppVeyor, I added a debugging line and found that `sys.stdout.encoding = '1252'` in my build, so the `codecs.getwriter()` branch seems to be responsible. (And we can see why Python 3.7 is unaffected). I'm not sure exactly what object is getting returned, but apparently the object returned by `sys.stdout.detach()` is a stream that still wants Unicode rather than bytes.

This all may be related to [PEP 528, introduced in Python 3.6](https://www.python.org/dev/peps/pep-0528/).

I can work around the problem by futzing with the environment:

```
set "PYTHONLEGACYWINDOWSSTDIO=1"
set "PYTHONIOENCODING=UTF-8"
```

But ideally Meson would work out-of-the-box in this circumstance.

**Comment by lazka** [comment]
@ocrete

**Comment by ocrete** [comment]
I hate Python's Unicode handling, and I know nothing about Windows sadly. We need to write some kind of unit test for this.

**Comment by lazka** [comment]
You could just disable the code on Windows. Python supports Unicode for stdout since 3.6 there as long as stdout isn't redirected.

(also Windows uses surrogatepass not surrogateescape as filename error handler)

**Comment by amitdo** [comment]
Python < 3.7 is no longer supported.
