### ISSUE TITLE
Feature Request to Add C17/C18/ISO-9899:2018 Support

### ISSUE THREAD

**Issue by jrl64** [mesonbuild/meson#4842]
ISO-9899:2018 (C17/C18) came out last year. Although it's a non-feature corrections release, folks are going to be wanting to specify it in compiler options.

As a first shot at scoping the issue, I simply hacked a local copy of mesonbuild/compilers/c.py to add 'c17', 'c18', 'gnu17', and 'gnu18' to the list of the supported standards in class GnuCCompiler, and added 'c17' and 'gnu17' in class ClangCCompiler. Passing c_std=c17 to project(), my test compiles using GCC 8 and Clang 7 were successful.

There's a lot more to it than that, but maybe it won't be too tough.

**Comment by mcatanzaro** [comment]
Yeah this would be nice. C17 has been the default since GCC 8 so it's a bit sad the best we can get from Meson using its `c_std` feature is C11.

From `gcc(1)`:

```
           c17
           c18
           iso9899:2017
           iso9899:2018
               ISO C17, the 2017 revision of the ISO C standard (expected to
               be published in 2018).  This standard is same as C11 except for
               corrections of defects (all of which are also applied with
               -std=c11) and a new value of "__STDC_VERSION__", and so is
               supported to the same extent as C11.
```

**Comment by jrl64** [comment]
Yes, it would be nice. Since I have control of all the meson.build files I currently use, I can simply include '-std=c17' in the c_args argument to executable() instead of including 'c_std=c17' in the default_options argument to project(), as I did in the past, or passing it to add_global_arguments() or add_project_arguments(), which I've never tried.

But it will trip up someone before too long if it hasn't already.

**Comment by jrl64** [comment]
I have a PR prepared and uploaded to my jrl/64/meson/ fork. Since I'm a github novice, I'm waiting to see if my procedure on a different issue #5033 is correct. Once I think I know what I'm doing, I'll send a PR for this one.
