### ISSUE TITLE
Support setting project-wide options such as -Dwerror only on a specific (sub)project

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#4854]
Some project-wide options such as `-Dwerror=true` should sometimes not be inherited by subprojects, esp if they are external projects. We should allow setting them per-(sub)project by doing `-Dprojname:werror=true`.

CC: @ebassi, needed by GTK+ CI.

**Comment by xclaesse** [comment]
For reference, this is similar to https://github.com/mesonbuild/meson/pull/4157.

**Comment by nirbheek** [comment]
I should've known you already had a PR open for it! I'm leaving this to you then, great :wink:

**Comment by TheQwertiest** [comment]
It's really strange that this feature does not get much traction. Is using 3rd party dependencies such an uncommon case?

For example, for us it's a huge show-stopper for using Meson, since we want to have -Werror and --std=c++14 in our project, but we can't take the burden of continuously patching 3rd party dependencies to fix warnings and\or compile errors, that come from inherited compile flags.

**Comment by Ricardicus** [comment]
I was about to start writing an issue about this. 
Luckily someone had already recognized this issue.

Are we going to see a fix for this? A project I am working on needs to use subprojects with project that may have warnings in them, I though that setting default option werror=false within the subprojects wrapped meson.build file would to the trick, but it didn't!

**Comment by Ricardicus** [comment]
I am struggling with a subproject with warnings I want to be included in my meson build. 
I want all code except the subprojects to be affected by the werror=true option.

I saw a suggestion: 

`X_dep = dependency('X', fallback: [...], ...,
  default_options : ['werror=false'] )`

However, this did not work. 

I **really like** meson and whished I was involved enough to fix this myself. 

What is the plan, will there be a fix for this in the future?

**Comment by TheQwertiest** [comment]
@Ricardicus , there's some work being done in https://github.com/mesonbuild/meson/pull/6729, I'm not sure if @xclaesse is currently working on it though.

**Comment by Ricardicus** [comment]
Ok, thank you!

**Comment by xclaesse** [comment]
werror was an easy and popular one, done there now: https://github.com/mesonbuild/meson/pull/6795
