### ISSUE TITLE
failing test_introspect_json_dump on new OS (=Solaris)

### ISSUE THREAD

**Issue by chincheta0815** [mesonbuild/meson#4866]
I get a rare issue concerning the test_introspect_json_dump:

>
>======================================================================
FAIL: test_introspect_json_dump (__main__.AllPlatformTests)
>----------------------------------------------------------------------
>Traceback (most recent call last):
>  File "./run_unittests.py", line 3319, in test_introspect_json_dump
>    self.assertPathListEqual(res['buildsystem_files'], bs_files)
>  File "./run_unittests.py", line 1256, in assertPathListEqual
>    self.assertPathEqual(i[0], i[1])
>  File "./run_unittests.py", line 1247, in assertPathEqual
>    self.assertEqual(PurePath(path1), PurePath(path2))
>AssertionError: PureP[37 chars]on.git/test cases/unit/52 introspection/staticlib/meson.build') != PureP[37 chars]on.git/test cases/unit/52 introspection/sharedlib/meson.build')
>
>

Looking into the respective lines of code show that in the assertPathListEqual test there is an element change. All three elements are there and the same, but the parts with "sharedlib" and "staticlib" are vice versa. Meaning ('pseudo code for simplicity'):
> bs_files = ['meson.build', 'sharedlib/meson.build', 'staticlib/meson.build']
> buildysystem_files = ['meson.build', 'staticlib/meson.build', 'sharedlib/meson.build']

The content in buildsystem_files is as it is extracted by the test, inside the respective meson-info-file the order of the paths is "['meson.build', 'staticlib/meson.build', 'sharedlib/meson.build']". So the paths seems to be scrambled on their way into that file.

As I do not know what the test shall to since it did not pass yet (is the order needed or not) I would appreciate to get some help on this. When this is done I am a way further on running meson on Solaris.

**Comment by mensinda** [comment]
Yes, the order of the build system files is not important. Could you test if #4868 (really) fixes the issue?

**Comment by chincheta0815** [comment]
Fixed it. Thanks.
Any hints on #4869 ?

**Comment by chincheta0815** [comment]
Well, the weird thing is, that doing as you describe it, everything works!?
That's why I am puzzled.
The error I get when checking the return code is "Permission denied." by the subprocess call.
