### ISSUE TITLE
Feedback and issues encountered while migrating from waf

### ISSUE THREAD

**Issue by arteymix** [mesonbuild/meson#487]
I am in the process of migrating Valum's build from waf to Meson and I noticed a couple of hitches:

 - lack of support for `Requires` in pkg-config module (`Requires.private` as well)
 - `add_global_arguments` is broken for the Vala language

Is there any cleaner way of using `include_directories` when linking a shared library against another that the following?

```
valum = shared_library('valum', valum_sources,
                       dependencies: [glib, gobject, gio, soup],
                       include_directories: [include_directories('../vsgi')],
                       link_with: vsgi,
                       install: true)
```

Meson is really well designed and I really enjoyed its simplicity and expressiveness.

**Comment by nioncode** [comment]
If you build the `vsgi` library yourself, you can use the `declare_dependency` method.
You can than add the result directly in your `dependencies` array of `valum`.

**Comment by arteymix** [comment]
@nioncode Thanks, it's exactly what I've been looking for!

Is it planned to lower the Python version? at least 3.2 to support Ubuntu 12.04?

**Comment by rhd** [comment]
> Is there any cleaner way of using include_directories when linking a shared library against another that the following?

This is how I structure my `meson.build` files for libraries - and it has worked well and keeps everything nice and clean.

```
vsgi_inc = include_directories('.')
vsgi = shared_library('vsgi', src,
    include_directories: vsgi_inc,
)
vsgi_dep = declare_dependency(
    include_directories: vsgi_inc,
    link_with: vsgi,
)
```

Then your `valum` line becomes:
```
valum = shared_library('valum', valum_sources,
                       dependencies: [glib, gobject, gio, soup, vsgi_dep],
                       install: true)
```

**Comment by arteymix** [comment]
@rhd That's exactly what I did (see here: https://github.com/valum-framework/valum/blob/meson-build/src/valum/meson.build)

**Comment by jpakkane** [comment]
> lack of support for Requires in pkg-config module (Requires.private as well)

Can you give an example of how and why you would use this?

> add_global_arguments is broken for the Vala language

I'll get this fixed soon.

> Is it planned to lower the Python version? at least 3.2 to support Ubuntu 12.04?

No. That is way too old, the Meson project itself is younger than that.

**Comment by arteymix** [comment]
> Can you give an example of how and why you would use this?

If your project require another library which provide a pc file, you can state it in the `Requires`. I know that you are not much into implicit dependencies, but other build tool (notably `valac`) expect that.

For instance, Valum uses `glib-2.0`, `gobject-2.0`, `gio-2.0`, `libsoup-2.4` and `vsgi`, so if I type:

```bash
pkg-config --cflags --libs valum
```

I can expect the following output:

```
-pthread -I/usr/include/valum -I/usr/include/vsgi -I/usr/include/libsoup-2.4 
-I/usr/include/libxml2 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -lvalum 
-lvsgi -lgthread-2.0 -pthread -lsoup-2.4 -lgio-2.0 -lgobject-2.0 -lglib-2.0
```

`Requires` is used for other pkg-config library and `Libraries` is used for *legacy* libraries. Their `private` equivalents are used for dependencies you don't want exposed (external stuff now shown in your API).

What Meson could do is resolving all these libraries from `dependency` and `find_library` and provide a mean to mark some of them as private.

Hope that's clear enough!

>> add_global_arguments is broken for the Vala language

> I'll get this fixed soon.

That would be very kind of you! I typically put `--enable-experimental` and `--fatal-warnings` as well as some definitions based on available dependencies.

**Comment by jpakkane** [comment]
Global args should work now and you can specify requires and requires_private as keyword arguments. They are currently just strings with no checking. We might add something fancier later.

**Comment by arteymix** [comment]
@jpakkane Thanks! Don't forget `libraries_private` :)

**Comment by arteymix** [comment]
@jpakkane in terms of fancier and explicit, I suggest that we can pass `dependency`objects into `requires` and `requires_private`

Also, is it possible to process `Libraries.private` the same way `Libraries` is (imply some code duplication)?
