### ISSUE TITLE
Linkage errors due to malformed ninja script

### ISSUE THREAD

**Issue by Ev1lbl0w** [mesonbuild/meson#4879]
Using meson to build my project generates a ninja file that fails to link at the final stage. Downgrading to version `0.47.2-1` fixes the problem.

Upon further investigation it seems the culprit is this line in my ninja file:

`LINK_ARGS = -L=-L-L/usr/lib// -L=-L-lgtkd-3 -L=-L-ldl`

It looked odd that the arguments had the `-L` argument duplicated. And in fact, removing the extra argument allowed ninja to successfully link my project:

`LINK_ARGS = -L=-L/usr/lib// -L=-lgtkd-3 -L=-ldl`

@FFY00

**Comment by FFY00** [comment]
@GoaLitiuM and @ximion I don't have the time to search for the patch that broke this right now, maybe you could look into this. I can still answer questions, I just can't do extensive research/testing since I still have a few exams left.
