### ISSUE TITLE
Arguments and include directories are not passed to precompiled headers

### ISSUE THREAD

**Issue by madebr** [mesonbuild/meson#4900]
When using precompiled headers, arguments and include directories of the executable are not passed to the precompiled header.

example:
**meson.build**:
```project('pchtest', 'cpp', version: '1.0')
prog = executable(
    'pchtest',
    ['main.cpp'],
    cpp_args: ['-DSOME_DEFINE'],
    cpp_pch: ['pch/stdafx.h', 'pch/stdafx.cpp'],
    include_directories: include_directories('./pch'),    
)
```
**main.cpp**:
```
#include "pch/stdafx.h"

int main() {
    std::cout << C::VALUE << std::endl;
    return 0;
}
```
**pch/stdafx.h**:
```#ifndef HEADER_H
#define HEADER_H
struct C {
#ifdef SOME_DEFINE
    static const int VALUE = 1;
#else
    static const int VALUE = 0;
#endif
};
#include <iostream>
#endif
```
**pch/stdafx.cpp**:
```
#include "stdafx.h"
```

The generated **compile_commands.json** contains the following command to generate the precompiled header:
```
  {
    "directory": "C:\\Users\\maarten\\source\\repos\\pchtest2\\pchtest2\\build",
    "command": "cl \"/nologo\" \"/showIncludes\" \"/W2\" \"/EHsc\" \"/ZI\" \"/Ob0\" \"/Od\" \"/RTC1\" \"/Ycstdafx.h\" \"/Fppchtest@exe\\\\stdafx.pch\" \"/Fopchtest@exe\\\\stdafx.obj\" \"/FS\" \"/FdC:\\\\Users\\\\maarten\\\\source\\\\repos\\\\pchtest2\\\\pchtest2\\\\build\\\\pchtest.pdb\"    /c ../pch/stdafx.cpp",
    "file": "../pch/stdafx.cpp",
    "output": "pchtest@exe/stdafx.pch"
  },
```
As you can see, there is no include directory or cpp argument present.
It should contain `"-I..\\./pch"` and `"-DSOME_DEFINE"`.
The executable argument also does not support a `pch_args` argument.

Running the executable should print `1` but it prints `0`.

Using:
- Visual Studio 15 2017 on Windows 10.
- meson 0.49.2
- ninja 1.8.2

**Comment by nioncode** [comment]
I cannot reproduce this with current `master` (both, Linux and Windows). I fixed some pch things recently, so please try if you can reproduce this with the latest `master` revision.

**Comment by madebr** [comment]
Indeed. Current master fixes this issue.
Many thanks!
