### ISSUE TITLE
Link against custom targets

### ISSUE THREAD

**Issue by jpakkane** [mesonbuild/meson#4908]
For integration with custom toolchains and other such stuff. Basically if you put the output of custom_target to the `link_with` line of a build target it will:

 - add a dependency in the usual way
 - add the output file to the link line
 - assumes that this is enough to make it work, if not, then that is the build definition writer's developer's problem

This can probably only be done reasonably for static libraries. Dependencies of dependencies also don't really work, because to do so would mean having to replicate Meson's entire dependency resolution chain for custom targets.

I was going to do this today but am mostly been in bed suffering from the seasonal flu. Feel free to implement this if you wish.

**Comment by TheQwertiest** [comment]
Any chance for this to be implemented in 0.50? Since, AFAIK, there is currently no way to make a dependency relation for libs produced by `custom_target`, thus it's impossible to integrate subprojects based on non-meson build systems.

**Comment by jpakkane** [comment]
Feature freeze for 0.50.0 was last Sunday, so sadly no.

**Comment by TheQwertiest** [comment]
That's a shame =(
Do you think this feature will be implemented in the trunk any time soon?

**Comment by phillipjohnston** [comment]
That is a shame :(
