### ISSUE TITLE
Meson always fails with "Could not determine vs dep dependency prefix string."

### ISSUE THREAD

**Issue by Arvamer** [mesonbuild/meson#491]
System - Archlinux, python - 3.5.1.

I have bisected it to c86ee8158a5a4dd6603eab9350c71739800b7f73.

My locale is mix of en_US and pl_PL but it also doesn't work with locale set only to en_US.

**Comment by jpakkane** [comment]
That piece of code should only be called on Windows, it is Visual Studio specific. Do you have an executable called `cl` in your path and if yes, what is it?

**Comment by Arvamer** [comment]
It's cliquer.
