### ISSUE TITLE
Cuda Tests fail when werror=true

### ISSUE THREAD

**Issue by jml1795** [mesonbuild/meson#4911]
When building a project containing cuda code, if the default_options are set to have werror=true, the build fails with
```sh
  File "/usr/local/lib/python3.6/dist-packages/meson-0.49.999-py3.6.egg/mesonbuild/backend/backends.py", line 569, in generate_basic_compiler_args
    commands += compiler.get_werror_args()
AttributeError: 'CudaCompiler' object has no attribute 'get_werror_args'
```
This can be seen in the tests, particularly `test cases/cuda/1 simple`

I am running off `627d0d1f3e`. Thank you.

**Comment by jpakkane** [comment]
Can you test if the linked PR fixes it for you?
