### ISSUE TITLE
run_command returns a run result without compiled()

### ISSUE THREAD

**Issue by emersion** [mesonbuild/meson#4916]
Attempting to use `compiled()` on `run_command`'s return value fails:

```meson
git_branch = run_command([git.path(), 'rev-parse', '--abbrev-ref', 'HEAD'])
git_branch.compiled()
```

```
meson.build:135:20: ERROR:  Unknown method "compiled" in object.
```

`returncode` works as expected.

This isn't specified in [the docs](http://mesonbuild.com/Reference-manual.html#run-result-object). We could either update the docs or add `compiled` (which returns true if return code is zero).

**Comment by jpakkane** [comment]
That documentation is just wrong. It should say `compiled` is only valid for compilation result calls, not run_commands.
