### ISSUE TITLE
subprojects with inter-dependencies

### ISSUE THREAD

**Issue by mokafolio** [mesonbuild/meson#4936]
Hi,

When using CMake, my library repositories used to have a folder with git submodules of other libraries of mine that the current project depends on which could optionally be build in place (i.e. so that you could just clone one repo instead of having to get every item separately).

I got the basic version of this working in meson using subprojects and build options so that you can optionally pass in a flag to meson to build using the subprojects. That said I am stuck for projects where there are inter-dependencies between any of the subprojects, i.e. let's say lib `Baz` has two subprojects `Foo` and `Bar`. `Bar` depends on `Foo`, too (and has it as a submodule/-project in it's repo, too). Let's assume the build flag for building from subprojects is called `buildSubmodules` and is consistent across all those. If I set it on the main project, it never get's set on the subprojects which I think is related to this: https://github.com/mesonbuild/meson/issues/2289. This might in a way be good, because I don't want to build `Foo` twice, anyways. The best thing would be if I could somehow pass along the `Foo` dependency that was build by `Baz` to `Bar`, so it can use it. The order should be something like this:

1. build `Foo`
2. build `Bar` using the `Foo` from step 1
3. build `Baz` using `Foo` and `Bar`

What is the best way to achieve this in meson? Thank you!

EDIT: I think this one is related, too: https://github.com/mesonbuild/meson/issues/2844

**Comment by mokafolio** [comment]
Okay, after some more testing I realized that `subproject` will always retrieve from the main projects subproject folder so that is great. So now my only problem remaining is that the `buildSubmodules` flag does not propagate down to `Bar` and `Foo`. What can I do about that?

**Comment by xclaesse** [comment]
You can add `buildSubmodules` option in `meson_options.txt` of both the subproject and the parent project, with the keyword argument `yield : true`. That way the value set to that option in the parent project will be set on the subproject too.

**Comment by mokafolio** [comment]
Awesome, that's exactly what I was looking for, thank you!
