### ISSUE TITLE
Feature Request: Add Flang Support

### ISSUE THREAD

**Issue by jrl64** [mesonbuild/meson#4937]
Flang is the in-development Fortran front-end for Clang/LLVM.  While it's a work-in-progress, it would be very helpful to use Meson to build Flang programs.

Here's what I'm using so far. Paths are relative to the installed mesonbuild package directory. Diffs are with respect to Meson 0.49.2 installed modules on Debian Sid (Unstable).

$ diff environment.py-0.49.2 environment.py
43a44
>     ClangFortranCompiler,
773a775,776
>                 if 'clang' in out:
>                     return ClangFortranCompiler(compiler, version, is_cross, exe_wrap, full_version=full_version)

$ diff compilers/__init__.py-0.49.2 compilers/__init__.py
49a50
>     'ClangFortranCompiler',
150a152
>     ClangFortranCompiler,

$ diff compilers/fortran.py-0.49.2 compilers/fortran.py
26a27
>     ClangCompiler,
409a411,429
>
>
> class ClangFortranCompiler(ClangCompiler,FortranCompiler):
>     def __init__(self, exelist, version, is_cross, exe_wrapper=None, **kwags):
>         FortranCompiler.__init__(self, exelist, version, is_cross, exe_wrapper, **kwags)
>         ClangCompiler.__init__(self, CompilerType.CLANG_STANDARD)
>         default_warn_args = ['-Wall', '-Winvalid-pch']
>         self.warn_args = {'1': default_warn_args,
>                           '2': default_warn_args + ['-Wextra'],
>                           '3': default_warn_args + ['-Wextra', '-Wpedantic']}
>
>     def get_module_incdir_args(self):
>         return ('-module', )
>
>     def get_no_warn_args(self):
>         return ['-w']
>
>     def openmp_flags(self):
>         return ['-fopenmp']

I'll attempt to attach compressed archive flang-support.tar.gz here:

[flang-support.tar.gz](https://github.com/mesonbuild/meson/files/2871060/flang-support.tar.gz)

First time I've done that. Let me know if it's not usable.

The ClangFortranCompiler class is just what you'd expect. It inherits from ClangCompiler and FortranCompiler.  Most methods needed are already in its superclasses.  My testing has all been done using flang-7 version 20181226-2_amd64 in Debian Sid (Unstable).

**Comment by jrl64** [comment]
Good news I downloaded a copy of the flang-support.tar.tgz file, and it's identical to my upload.

**Comment by jrl64** [comment]
Yeah, the formatting of the diffs I pasted in didn't work out well. I recommend just extracting the old & new sources from the tarball.

**Comment by scivision** [comment]
Flang was added in https://github.com/mesonbuild/meson/pull/4792
I have been using it since. However if there is something missing please let us know.

**Comment by scivision** [comment]
For instance, maybe it would be more consistent to use the naming scheme you did instead of the one I did. I don't think anyone would be bothered by a renaming. 

I added several other Fortran features recently that have been merged to master.

https://github.com/mesonbuild/meson/pulls?q=is%3Apr+author%3Ascivision

**Comment by jrl64** [comment]
Oh, this is really embarassing. I could have sworn I searched for Flang in previous issues, but obviously I didn't.

I've had a chance to look at your changes in #4792, and they look great. You covered everything my changes did, plus more.  My choice of naming ClangFortranCompiler was more a matter of minimalism than any logic.  In fact, in the future Flang will probably become less closely identified with Clang.

The only problem I spotted is that in the get_no_warn_args() method of class FlangCompiler, the  '-silent' flag isn't accepted by flang-7 7.0.1 in Debian Sid. My changes  in #4937 return ['-w'], since '-w' is what 'flang -7 --help' spits out.  I just posted a comment to that effect in #4792.

Thank you so much for speaking up quickly. I don't feel I wasted time, since I learned more about Meson internals.  I'm glad I didn't invest effort into building a PR, which would have been my first ever.  Looking forward to using your new feature.

**Comment by jrl64** [comment]
Issue 4792 has already supplied the Flang support. My apologies for wasting anyone's time.

**Comment by jrl64** [comment]
Oh, never mind about the '-silent'. I was looking at an early revision that defined class FlangCompiler.

**Comment by scivision** [comment]
OK I didn't extensively test every option, so let us know if there is something missing.

Re: naming, I suppose Flang does make the most sense as it has an entirely different source code origin from Clang/Clang++. I don't think the internal naming scheme would be of importance to end users, and it would be straightforward to rename at any point, preserving both names. However my vote would be for naming it as is internally--Flang.
