### ISSUE TITLE
RFC: Add a generic variable getter method for dependencies

### ISSUE THREAD

**Issue by dcbaker** [mesonbuild/meson#4957]
We now have 4 different kinds of dependencies, cmake, pkg-config, config-tool, and declare_dependency. pkg-config and config-tool have a method that allow getting arbitrary variables, cmake might but I haven't looked closely. Some dependencies can be found multiple ways (cmake or config-tool for example). Because of that it would be nice to have a generic getter method, such as

```meson
dep = dependency('dep')
use_thing = dep.get_variable(cmake : 'CMakeVariable', pkg-config : 'pkg-config-variable', config-tool : 'config-tool-argument')
```
Which would be implemented such that each kind of dependency would respect the proper keyword.

@jpakkane, opinions?

**Comment by dcbaker** [comment]
then you'd get an error, the same as calling one of the specific methods on the wrong dependency type.

**Comment by jpakkane** [comment]
Should it also have a `default` or something similar for a variable name to try if the dependency type is not one of the listed ones?

**Comment by dcbaker** [comment]
That might be a good idea it could have behavior such that if `default` is provided it returns that, otherwise error.
