### ISSUE TITLE
link_whole with a static library does not add dependencies to pkg-config target

### ISSUE THREAD

**Issue by eli-schwartz** [mesonbuild/meson#4984]
Given a meson.build that contains:
- a `libfoo_a = static_library()` with dependencies,
- a `libfoo = library()` that uses `link_whole : [libfoo_a]`
- a `pkgconfig.generate(libfoo, ...)`

The resulting pkg-config file does not contain the dependencies from the static library. One workaround is to list the dependencies in both `*library()` calls, just to make pkgconfig detect the dependency and add it as `Requires.private`.

One example where this is used is in the pacman project: https://git.archlinux.org/pacman.git/tree/meson.build?id=ba7a41031c201b20d26cb69aa8b25acfb55c56bd#n358

**Comment by xclaesse** [comment]
I believe this should be fixed by https://github.com/mesonbuild/meson/pull/5936. Can you please test again with meson master and reopen if it still fails?
