### ISSUE TITLE
Support dependency and library declination

### ISSUE THREAD

**Issue by arteymix** [mesonbuild/meson#499]
Some libraries (like `liblua`) come with various declination (alternative names) depending on what distribution has packaged it.

Let's say that if/else is a little tricky here because you have to assign the dependency conditionally and handle the case where alternatives have all been tried.

It would be very handy to have an array of declination that would be tried before the fallback.

```meson
dependency('lua', declination: ['lua5.2', 'lua5.1'])
```

The same would apply for `find_library`.

**Comment by eternaleye** [comment]
I've never seen 'declination' used this way. Your usage is vaguely like [declension](https://en.m.wikipedia.org/wiki/Declension)'s meaning, but honestly neither is remotely clear - from the title, my first thought was that this ticket was about `-Wl,--as-needed`.

A more evocative term might be `variants` (possibly with a `permit_` or `accept_` prefix), but this also feels like a codesmell to me. It encouragea distorting the general buildsystem for the sake of specific distros.

Moreover, the example is poor. Lua's _interface_ differs between 5.1 and 5.2.

**Comment by arteymix** [comment]
You're right, it's not a widespread issue as I thought and for the specific cases, it is better to just use branching.
