### ISSUE TITLE
Make Qt includes is_system by default

### ISSUE THREAD

**Issue by fiesh** [mesonbuild/meson#5002]
Right now, importing `qt5` leads to its include directories being included as non-system includes.

This leads to tons of warnings for us in the Qt headers.  For this reason, before meson we used to handle Qt as system includes.

I don't see any reason why anybody would *not* want this.  If you're using your system's installed Qt, you most likely do not want to fix problems in its header files.

In fact, this might apply to other module imports as well?

I'd suggest making this the default for `import`.  If this is deemed unreasonable, maybe allow specifying `is_system` with `import`?

**Comment by jpakkane** [comment]
Import is only for loading the internal Qt helper module. It does not deal with include paths at all. That is done by `dependency`. Which platform is this on? We usually just grab the system default (such as pkg-config) and use the flags it lists directly. Converting arguments from "the outside" from -I to -isystem can lead to nasty and hard to decipher bugs, unfortunately.

**Comment by fiesh** [comment]
Oh I see.  This here is a gentoo system.  `pkg-config --cflags-only-I Qt5Core` returns `-I/usr/include/qt5/QtCore -I/usr/include/qt5`.

For reference, I checked Ubuntu under

https://packages.ubuntu.com/bionic/qtbase5-dev

There `Qt5Core.pc` also uses `-I`.  So I suppose this comes from Qt directly?

Before meson, with CMake we had the option to label all Qt includes as `SYSTEM`, making them included in the command line with `-isystem`.  This came in really handy.  I think it would be great if the includes weren't treated as opaque flags coming from `pkg-config` or whatever, but rather as actual directories that could be appened via `-I` but also `-isystem` or anything else that might play a role later on.

**Comment by fiesh** [comment]
Or asking differently, is there anything I can do myself to change this?  A simple `s/-I/-isystem /` would be better for me than the alternatives (disabling certain warnings or wrapping *every* `#include` directive for Qt in a warning ignore GCC pragma).

**Comment by fiesh** [comment]
A *really really* hacky way around this for me for now is to do
```
include_hack = [
	'-isystem/usr/include/qt5',
	'-isystem/usr/include/qt5/QNetwork',
	'-isystem/usr/include/qt5/QtGui',
	'-isystem/usr/include/qt5/QtCore',
	'-isystem/usr/include/qt5/QtPrintSupport',
	'-isystem/usr/include/qt5/QtWidgets',
	'-isystem/usr/include/qt5/QtSvg',
	'-isystem/usr/include/qt5/QtOpenGL',
	'-isystem/usr/include/x86_64-linux-gnu/qt5',
	'-isystem/usr/include/x86_64-linux-gnu/qt5/QNetwork',
	'-isystem/usr/include/x86_64-linux-gnu/qt5/QtGui',
	'-isystem/usr/include/x86_64-linux-gnu/qt5/QtCore',
	'-isystem/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport',
	'-isystem/usr/include/x86_64-linux-gnu/qt5/QtWidgets',
	'-isystem/usr/include/x86_64-linux-gnu/qt5/QtSvg',
	'-isystem/usr/include/x86_64-linux-gnu/qt5/QtOpenGL',
]
include_hack_dep = declare_dependency(compile_args : include_hack)
```
(I cannot use `include_directories` since meson will check the directories exist, and this should attempt to cover typical directories.)

Then appending this helps because GCC will still treat directories as system if they're listed with `-isystem` after having been listed with `-I`.

**Comment by fiesh** [comment]
OK this of course fails when the build environment isn't located in `/usr`, like when cross-compiling. :-(

Any suggestions?

**Comment by fiesh** [comment]
OK so this is a slightly less hacky workaround:

```qt5dep = dependency('Qt5Core', method : 'pkg-config')
qt5prefix = qt5dep.get_pkgconfig_variable('prefix')
# Potential prefixes in the include directory
qt5include_prefixes = ['', 'qt5']
qt5modules = ['QtCore', 'QtNetwork', 'QtGui', 'QtPrintSupport', 'QtWidgets', 'QtSvg', 'QtOpenGL']
wsqtbase_include_hack = []
foreach p : qt5include_prefixes
	foreach m : qt5modules
		include_hack += '-isystem' + join_paths(qt5prefix, 'include', p, m)
	endforeach
endforeach


include_hack_dep = declare_dependency(compile_args : include_hack)
```

**Comment by xiannox** [comment]
With the recent release of gcc 9.1.0, as well as with clazy, I run into this problem.

Basically, it boils down to pkg-config returns includes with -I instead of -isystem. Solutions would be to either:
- patch pkg-config's Qt*.pc files to say -isystem instead of -I, and get upstream to fix this; or
- introduce a new flag to dependency, for example system, so that:
```
dep_qt5 = dependency('qt5', modules: [ 'Core' ], system: true)
```
would _s/-I/-isystem/g_.

If I were to do the second, where should I look for the dependency implementation?

**Comment by jpakkane** [comment]
This is not really the responsibility of the dependency function. There are many other ways of creating dependency objects and it would be nice if it worked on all of them. Something like `partial_depencency` on the dep object but making it convert includes to regular to system includes.

**Comment by gerion0** [comment]
#963 basically requests the same, so leaving this here as reference.

**Comment by Tachi107** [comment]
Can this be closed? With `[include_type](https://mesonbuild.com/Reference-manual.html#dependency)` (0.52.0) users can use Qt with `-isystem`.

**Comment by fiesh** [comment]
> Can this be closed? With [`include_type`](https://mesonbuild.com/Reference-manual.html#dependency) (0.52.0) users can use Qt with `-isystem`.

Yes, `include_type` is great!  Thanks for pointing it out.
