### ISSUE TITLE
Request for comments: Demystifying search_version() in environment.py

### ISSUE THREAD

**Issue by jrl64** [mesonbuild/meson#5020]

**Comment by jrl64** [comment]
Has anyone else stared at the regex definition in function search_version() in module environment.py
until your eyes go blurry?  I have to agree with the comments -- it is somewhat magical. What if we
demystify it a bit by compiling a verbose-mode definition? Now even I can understand it.

I'm uploading a demo Python program that shows the demystified variant as search_version2().

Apologies, but I still haven't learned to use git. It's at the top of my wishlist, honest. If a 
git-literate person gets exited about using this, and does a PR, then you certainly deserve all the credit.

Okay, here's the demo program:

[search_version.py.txt](https://github.com/mesonbuild/meson/files/2927166/search_version.py.txt)

**Comment by jrl64** [comment]
Here's an updated version of my Python demo program, with a number of cosmetic changes.

[search_version.py.txt](https://github.com/mesonbuild/meson/files/2931232/search_version.py.txt)

**Comment by jrl64** [comment]
My PR for this issue is Issue #5033.

I'm now a git novice.  Git/Github are so easy to get started with, I feel silly for putting it off. Maybe I should wait ultil my PR is merged before I start celebrating.

**Comment by jpakkane** [comment]
We are currently in release freeze so only bug fixes are merged to master. We'll get this sorted out after the release, which is on Sunday.
