### ISSUE TITLE
timestamp of copied configuration_file is not reproducible

### ISSUE THREAD

**Issue by keszybz** [mesonbuild/meson#5027]
I'm building glib2, and it uses `configuration_file(..., copy: true)` to copy some python .py files to installation root. The files  end up having different modification timestamps. This file is then bytecompiled, the timestamp is embedded in the header, and the result becomes unreproducible.

Meson tries to preserve timestamps when installing files, so it'd be great if it could also preserve timestamps when doing internal copies.

Simplified test case:
```python
# meson.build
project('copy-timestamp-test')

configure_file(input : 'bar',
               output : 'bar',
               install : true,
               install_dir : '/foo/',
               copy : true)
```
```console
$ touch bar
$ meson build
$ DESTDIR=/var/tmp/inst1 ninja -C build install
$ DESTDIR=/var/tmp/inst2 ninja -C build install
$ stat bar build/bar /var/tmp/inst?/foo/bar
  File: bar
  Size: 4         	Blocks: 8          IO Block: 4096   regular file
Device: fd03h/64771d	Inode: 699931      Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1000/ zbyszek)   Gid: ( 1000/ zbyszek)
Context: unconfined_u:object_r:user_home_t:s0
Access: 2019-03-06 13:02:03.244669514 +0100
Modify: 2019-03-06 13:02:01.131648469 +0100   <----------------------
Change: 2019-03-06 13:02:01.131648469 +0100
 Birth: -
  File: build/bar
  Size: 4         	Blocks: 8          IO Block: 4096   regular file
Device: fd03h/64771d	Inode: 699932      Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1000/ zbyszek)   Gid: ( 1000/ zbyszek)
Context: unconfined_u:object_r:user_home_t:s0
Access: 2019-03-06 13:02:18.099817487 +0100
Modify: 2019-03-06 13:02:03.244669514 +0100   <----------------------
Change: 2019-03-06 13:02:03.244669514 +0100
 Birth: -
  File: /var/tmp/inst1/foo/bar
  Size: 4         	Blocks: 8          IO Block: 4096   regular file
Device: fd01h/64769d	Inode: 533115      Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/ zbyszek)   Gid: ( 1000/ zbyszek)
Context: unconfined_u:object_r:user_home_t:s0
Access: 2019-03-06 13:02:18.099817487 +0100
Modify: 2019-03-06 13:02:03.244669514 +0100   <----------------------
Change: 2019-03-06 13:02:18.099817487 +0100
 Birth: -
  File: /var/tmp/inst2/foo/bar
  Size: 4         	Blocks: 8          IO Block: 4096   regular file
Device: fd01h/64769d	Inode: 533116      Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/ zbyszek)   Gid: ( 1000/ zbyszek)
Context: unconfined_u:object_r:user_home_t:s0
Access: 2019-03-06 13:02:18.099817487 +0100
Modify: 2019-03-06 13:02:03.244669514 +0100   <----------------------
Change: 2019-03-06 13:02:21.400850373 +0100
 Birth: -
```
The timestamp is *preserved* in the installation step, but *changed* in the earlier copy step.

**Comment by eli-schwartz** [comment]
I don't think this is a generally practical thing to solve. e.g. what should be the timestamp of a file that is created using a custom_target?

The example use case of glib2 has a bunch of python files copied using configure_file, some with configuration data and some with `copy: true`. Making the latter preserve the timestamp while the former continue to use a modified timestamp (because they are updated versions of the file! their contents depend on the configuration data) doesn't seem like it will help out much.

For reproducible builds purposes, the trend has been to use hashed bytecode, rather than timestamped bytecode.

**Comment by keszybz** [comment]
Hmm, I'm not sure if I accept the reasoning. There will be cases where the timestamp should be changed during the build, but the particular case of copying of a file is not that.

Let's keep it closed. If it turns out to be an actual problem for reproducible builds, I think this should be reconsidered.
