### ISSUE TITLE
0.50.0 regression: gnome test does not install gresource file

### ISSUE THREAD

**Issue by heftig** [mesonbuild/meson#5046]
As of 0.50.0, the `test cases/frameworks/7 gnome` project no longer installs the `simple-resources.gresource` file, causing the test to fail.

Building the same project (from the 0.50.0 tarball) with meson 0.49.2 installs the file, as expected.

**Comment by heftig** [comment]
glib 2.60.0<br>
Arch Linux

**Comment by heftig** [comment]
With an older 2.58 glib it's fine as well, so this is a regression introduced by https://github.com/mesonbuild/meson/pull/4222.

**Comment by mensinda** [comment]
Seems like with #4222 the `simple-resources.gresource` target is generated twice. If I move the [second](https://github.com/mesonbuild/meson/blob/master/test%20cases/frameworks/7%20gnome/resources/meson.build#L23) before `compile_resources` the [first](https://github.com/mesonbuild/meson/blob/master/test%20cases/frameworks/7%20gnome/resources/meson.build#L11) `compile_resources` the test passes with glib 2.60.0.
