### ISSUE TITLE
Install file generated during the build with `install_data`

### ISSUE THREAD

**Issue by arteymix** [mesonbuild/meson#505]
It seems to be supported with the `in_sourcetree` option, but it does not seem exposed.

It would be great, however, to have a fallback on the build directory if a file is not in the source directory or the opposite.

**Comment by jpakkane** [comment]
Which file, generated during which operation, where should it be installed to by default?

**Comment by arteymix** [comment]
In short, I would like the following snippet to work:

```python
project('valatest', 'vala', 'c')

valadeps = [dependency('glib-2.0'), dependency('gobject-2.0')]

shared_library('foo', 'foo.vala', dependencies : valadeps) # generates foo.vapi
install_data('foo.vapi', install_dir: 'share/vala/vapi')
```

In this case, `foo.vapi` end-up in the build directory. I think it would be nice to first check if a file has been generated and then fallback on the source directory.

**Comment by jpakkane** [comment]
The design guideline of Meson has been that everything is explicit and refers only to things that already exist (as opposed to e.g. Make where you can refer to targets by name, even if they have not been declared yet).

This issue is a subproblem of how to install targets that have more than one output file. There are several options, such as:

    lib = shared_library(...)
    install_data(lib.outfile('foo.vapi', install_dir : 'share/vala/vapi')

or:

    shared_library(..., vapi_install_dir : 'share/vala/vapi')

and so on. There is not a single approach that would immediately jump up and feel like the "correct" solution to this problem.

**Comment by arteymix** [comment]
I like the idea of accessing the output file of a target.

It would generalize to other interesting outputs of valac (and other compilers) like a GIR #185 a dependency file or a generated C header.

Also, it would become possible to install custom target output with some granularity instead of all in `install_dir`.

So :+1: on your first suggestion!

**Comment by arteymix** [comment]
Just want to add that since the target name for `library` (see #594) is used to generate the VAPI, we an have explicit output that should be installable with `install_data`.

That, and as proposed already in #634, we can have explicit GIR output with `vala_gir` option that should as well be installable.

That would pretty much get rid of install scripts for Vala.

**Comment by nirbheek** [comment]
@arteymix Are you working on implementing your proposals from #634? It would be great to have user-friendly Vala support out of the box. :)

**Comment by arteymix** [comment]
@nirbheek I'll look into that today

It would be also nice to have a `vala_deps` option to list dependencies to add to the `@NAME@.deps` file rather than having to keep track of it.

I just figure one can install VAPIs using `meson.current_build_dir() + '/package.vapi'` and it works just fine. I will update the test case and look into GIR now.

**Comment by nirbheek** [comment]
I'm closing this for now since this discussion is happening elsewhere.

**Comment by gquintard** [comment]
Hi,

Sorry to update a closed (and old) issue, but I've been unable to find the answer in the linked issues and in the docs.

I have a file, that once processed outputs four files, only one of them needs to be installed. Here's what I came up with (yes, I'm tainted by years of `make` abuse):

```
for reference, the original project is here: https://github.com/varnish/libvmod-digest
# only tell meson about 3 output files
vtool_output = custom_target('vcc_if.[ch] and RSTs',
                        input : 'src/vmod_digest.vcc',
                        output : ['vcc_if.c', 'vcc_if.h', 'vmod_digest.man.rst'],
                        command : [vmod_tool,  '@INPUT@', '-o', 'vcc_if'])
# fake the generation of the last one
noop = find_program('true')
rst = custom_target('fake target to isolate the installable file',
			input : vtool_output,
			output: [ 'vmod_digest.rst' ],
			command: [noop],
			install: true,
			install_dir: join_paths(get_option('datadir'), 'doc/libvmod_digest'))
```

It works, but feels hackish. As my goal is to offer `meson` as a replacement to `autotools` for vmods (and later Varnish), I'd rather have a clean proposal.

**Comment by jpakkane** [comment]
[This can be found on the manual's install page](https://mesonbuild.com/Installing.html#finer-control-over-install-locations).

**Comment by gquintard** [comment]
dang, I missed that. Thank you so much for the fast reply, and sorry for the noise.

**Comment by gerion0** [comment]
> [This can be found on the manual's install page](https://mesonbuild.com/Installing.html#finer-control-over-install-locations).

I have the same problem currently. However, the link is half dead: It leads only the installing page, the subsection is gone.
What was the solution and is it still valid?

**Comment by dcbaker** [comment]
You have a target producing multiple outputs, and you only want to install one? You can set install_dir to an array, like `install_dir : [false, false, “some/path”]`, which will install only and third output into some/path

**Comment by gerion0** [comment]
Thank you, that was what I searched for. I see that it is now mentioned directly in the [Reference Manual](https://mesonbuild.com/Reference-manual_functions.html#custom_target) (Section `install_dir`).
