### ISSUE TITLE
0.50.0 regression/feature: ERROR: Subdir keyword must not be an absolute path

### ISSUE THREAD

**Issue by ignatenkobrain** [mesonbuild/meson#5050]
Mutter is failing to configure with following error:

```
cogl/cogl/meson.build:513:0: ERROR: Subdir keyword must not be an absolute path.
```

I just did not see this in release-notes. If this is intentional, please add entry in release notes.

**Comment by QuLogic** [comment]
It's intentional: #5015

**Comment by nirbheek** [comment]
This should be a warning when the absolute path is also in the include dir.
