### ISSUE TITLE
llvm dependency fails to locate llvm-config on fedora 30

### ISSUE THREAD

**Issue by chergert** [mesonbuild/meson#5059]
```
llvm-config found: NO need '>= 3.5'
Dependency LLVM found: NO (tried config-tool)

src/plugins/clang/meson.build:47:0: ERROR: Dependency "llvm" not found, tried config-tool
```

Apparently, the tool has been named something rather odd now, 'llvm-config-64', which seems to differ from other naming schemes in `dependencies.py`.

```
rpm -q --whatprovides /usr/bin/llvm-config-64 
llvm-devel-8.0.0-0.4.rc3.fc30.x86_64
```

**Comment by chergert** [comment]
Further more, older llvm-config have been named even wackier.

```
rpm -q --whatprovides /usr/bin/llvm-config-7.0-64 
llvm7.0-7.0.1-4.fc30.x86_64
llvm7.0-devel-7.0.1-4.fc30.x86_64
```

**Comment by dcbaker** [comment]
sigh, I really wish people would stop being clever.

**Comment by nirbheek** [comment]
@chergert aside from this autodetection (which will be fixed), you can also set `llvm-config` in the native file.
