### ISSUE TITLE
cuda_root is reserved

### ISSUE THREAD

**Issue by arteymix** [mesonbuild/meson#5068]
I've been using this for a while but it appears to now be a reserved option name.

What are the proposed alternative for linking against CUDA runtime?

**Comment by obilaniu** [comment]
@arteymix All options with the name `langname_`+suffix are reserved. Since 0.50.0 adds support for `cuda`, options `cuda_...` are now reserved.

You might instead switch to `toolkit_root`, or any other name you like. There are currently no standards.

**Comment by nirbheek** [comment]
Yes, unfortunately we need to reserve all `langname_` suffix options. You'll need to update your build files. Perhaps we should make this a warning for a few releases, though, instead of breaking things.

**Comment by arteymix** [comment]
It's okay. I just have a hard time coming up with a good name. It would be nice to have `cuda_root` built-in to specify the location of the toolkit.

**Comment by jpakkane** [comment]
Linking against the Cuda runtime should be automatic when you have Cuda files in a target. If it does not work, please file bugs.

**Comment by arteymix** [comment]
I use the high-level CUDA API directly from C.

Also, I just noticed that they ship proper pkg-config files in standard locations: I don't even need the option in the first place!
