### ISSUE TITLE
[wiki] Edit 'Manual' page

### ISSUE THREAD

**Issue by amitdo** [mesonbuild/meson#507]
>This is the user manual for Meson. It currently tracks the state of Git head, which will eventually become version 0.30. If you are using an older version, some of the information here might not work for you.

0.30 has been released recently, so this paragraph should be updated.

**Comment by jpakkane** [comment]
Fixed, thanks.

**Comment by amitdo** [comment]
Again...

Maybe you need a bot for this :)

**Comment by jpakkane** [comment]
We plan on overhauling the doc system entirely soon.
