### ISSUE TITLE
ERROR: Cannot find frameworks with non-clang compiler

### ISSUE THREAD

**Issue by khaledhosny** [mesonbuild/meson#5070]
Building [ots](https://github.com/khaledhosny/ots) with meson 0.50.0 is failing with non-clang compilers, giving the following error:
```
meson.build:29:0: ERROR: Cannot find frameworks with non-clang compiler
```

The respective `meson.build` line has this:
```
coretext = dependency('appleframeworks', modules: 'applicationservices',        
                      required: false)
```

which used to work before with non-clang compilers (not find anything of course, which is fine). I don’t know why this was changed, but it looks like a breaking change to me.

**Comment by nirbheek** [comment]
The error should not be fatal when `required: false`. Will be fixed for the stable release.

**Comment by jpakkane** [comment]
Can you test if the linked MR fixes this for you?
