### ISSUE TITLE
Future version of gcovr requires updated syntax

### ISSUE THREAD

**Issue by kjerstadius** [mesonbuild/meson#5089]
In testing the gcovr provided solution that was discussed in #4801 I discovered that the syntax for calling gcovr has changed slightly since the last release. I can see that this has happened before since there's handling for different root directory expectations already in coverage.py. 

Now there's yet another syntax, which is further different from the two already supported. Basically, in order to be compatible with the next version of gcovr we now need to call gcovr like this (note that both the build root and the source root are being passed):

`gcovr_base_cmd = [gcovr_exe, '-r', source_root, build_root]`

This complicates things as there will be three different ways of handling directories passed to gcovr based on the installed version, with the new version syntax being more of a departure compared to the currently supported versions.

Since I've already figured out how the command needs to be updated I would be happy to submit a PR to update the necessary parts once I've figured out a nice way of doing it with via detect_gcovr(). I'm creating this issue though to ensure that people are aware that this will be a problem once the new version of gcovr is released. I don't know exactly when that will happen, but anyone interested can simply follow [this ticket](https://github.com/gcovr/gcovr/issues/297).

**Comment by perror** [comment]
Is there anything new about the possibility to exclude the tests itselves from the code coverage process ?
