### ISSUE TITLE
cc.sizeof() does not work on stdint.h types

### ISSUE THREAD

**Issue by Akaricchi** [mesonbuild/meson#5094]
I realize that checking size of something like `int32_t` might sound pointless, however, I'm currently porting a CMake build system that is riddled with such checks (along with non-silly ones), and it uses them to generate a config header, which I'd rather not modify for compatibility's sake. Furthermore, it might be useful to know the actual size of `intX_fast_t`, etc., and finally, I just see no good reason why this should not work.

**Comment by QuLogic** [comment]
Does passing `prefix: '#include <stdint.h>'` as in the [example](http://mesonbuild.com/Compiler-properties.html#expression-size) not work?

**Comment by Akaricchi** [comment]
Oh damn, sorry for wasting your time. I missed the `prefix` kwarg in the reference manual at first, but now that I've checked again I found it. I really shouldn't be opening issues at 4 am... Thanks.
