### ISSUE TITLE
Translate meson into a language with smaller runtime

### ISSUE THREAD

**Issue by KOLANICH** [mesonbuild/meson#5096]
Meson currently requires python. basel requires JVM. These runtimes are large, so all of these dependencies are grave issues. Dependency on JVM makes basel unsutable for any projects not targeting JVM languages. Dependency on python makes meson unsuitable for any projects not targeting python. One may argue that python is already required in linux distros. It is not a valid argument: CI images are usually heavily stripped because CI builds must be fast and cheap. In Windows python is not required, requiring python to build a program for Windows will make Windows users mad.

So the project probably should switch to less bulky runtime, like lua, JS  (using some lightweight engines like duktape, node and npm should not be used) or even glibc++.

**Comment by eli-schwartz** [comment]
https://mesonbuild.com/FAQ.html#why-is-meson-implemented-in-python-rather-than-programming-language-x

Python is a perfectly suitable general-purpose programming language in common use on both Windows and Linux, and has thus far failed to make Windows users mad.

There are extremely small Windows .MSI installers for meson, if you really feel you need them.

**Comment by nirbheek** [comment]
This is already answered in the FAQ as @eli-schwartz stated. Closing.
