### ISSUE TITLE
Rust doesn't compile on windows, 

### ISSUE THREAD

**Issue by ubsan** [mesonbuild/meson#5099]
"AssertionError: Could not get a dynamic linker for build target 'bitvec'"

I can't tell why this isn't working, but here's the repo: https://github.com/ubsan/bitvec

**Comment by jpakkane** [comment]
Did you run the configuration step from the Visual Studio developer tool prompt? (or alternatively try using something like MinGW)

**Comment by ubsan** [comment]
Yes. A C++ project works fine.

Also, the Rust `test cases` don't work, either, with the same error.

**Comment by jpakkane** [comment]
Can you try adding `c` or `cpp` in the language list? The bug may be that it needs to have a C-like toolchain detected to find a system dynamic linker.

**Comment by ubsan** [comment]
Doesn't look like that does anything, no matter if you do it before or after `'rust'` in the argument list.

**Comment by ubsan** [comment]
Also, all of the variables in `get_clink_dynamic_linker_and_stdlibs`:

```
self.is_cross: False
all_compilers: OrderedDict([('c', <VisualStudioCCompiler: v19.16.27027.1 `cl`>), ('rust', <RustCompiler: v1.35.0-nightly `rustc`>)])
clink_langs: ('d', 'cuda', 'objcpp', 'cpp', 'objc', 'c', 'fortran')
self.compilers: ('d', 'cuda', 'objcpp', 'cpp', 'objc', 'c', 'fortran')
dep_langs: []
```

**Comment by jpakkane** [comment]
This should have been closed by a MR because it has been fixed. Closing.
