### ISSUE TITLE
Rust: add_project_arguments doesn't seem to work?

### ISSUE THREAD

**Issue by ubsan** [mesonbuild/meson#5101]
See repo: https://github.com/ubsan/bitvec/blob/ffi/meson.build

Changing from using `bitvec_args` to `add_project_arguments('stuff', language: 'rust')` results in the rustc invocation:

```
rustc --crate-type dylib --crate-name bitvec -g --emit dep-info=bitvec.d --emit link -o libbitvec.so -C prefer-dynamic ../src/lib.rs
```

which is missing all of those arguments that I passed.

**Comment by jpakkane** [comment]
Can you test if the linked PR fixes it for you?

**Comment by ubsan** [comment]
@jpakkane it doesn't do anything, afaict. The bug also exists in non-ninja backends.

**Comment by ubsan** [comment]
yup, that works! thanks!
