### ISSUE TITLE
Make possible to set install mode for directories when install_subdir()

### ISSUE THREAD

**Issue by pmod** [mesonbuild/meson#5107]
install_mode argument allows only to set permissions and ownership for files in sub-directory, but it's not possible to set ownership and permissions of sub-directory itself.

**Comment by MartinSchwarzbauer** [comment]
Is this still not possible in meson file? 
Currently the only way is to create an install-sh file!

**Comment by eli-schwartz** [comment]
https://mesonbuild.com/Reference-manual_functions.html#install_emptydir

The `install_emptydir()` function allows you to guarantee that a directory exists in the install tree, with an attached mode. It is processed before `install_subdir()` is processed, so even though the latter will have the side effect of creating all directories in the parent hierarchy as well, you can still use both in the event that you want to guarantee specific install modes for the directory itself.

```
install_emptydir('/var/lib/myproject', install_mode: 'rwx------')
install_subdir('datafiles', install_mode: 'rwx------', install_dir: '/var/lib/myproject', strip_directory: true)
```

**Comment by eli-schwartz** [comment]
It was added in meson 0.60.0 (October 24, 2021), for context.
