### ISSUE TITLE
Script found by find_program() does not end up in dependencies

### ISSUE THREAD

**Issue by bonzini** [mesonbuild/meson#5108]
If `find_program()` returns a file from the source directory, anything that uses it should add the file to the dependencies, so that they are rebuilt whenever the script changes.

**Comment by nirbheek** [comment]
I'm surprised we don't already do this. It should be really easy to implement.

**Comment by bonzini** [comment]
Oh actually we do. But there is a similar issue with generators, as they don't allow `files()` in their arguments.
