### ISSUE TITLE
Suggestion: Rename set10() method

### ISSUE THREAD

**Issue by amitdo** [mesonbuild/meson#511]
This name is ugly and confusing (I read it as 'set ten').

Alternatives:

* set_boolean_int()
* set_int_from_boolean()

**Comment by jpakkane** [comment]
Set10 comes from CMake where there is a corresponding `#cmakedefine10`, so we do this due to consistency. We could maybe rename it to `set_10`, but it's not sure if that is worth the effort.

**Comment by amitdo** [comment]
Your project, your choice...

But I want to use beautiful Meson, not ugly CMake, so why should I care about this CMake ugliness ('#cmakedefine10')?

'set_10()' is still ugly and unclear.

Thanks anyway :-)

**Comment by nirbheek** [comment]
I guess we can close this now?
