### ISSUE TITLE
How can I set assembler flags?

### ISSUE THREAD

**Issue by phillipjohnston** [mesonbuild/meson#5121]
I'm migrating an embedded project to meson. How can I set flags for the assembler?

**Comment by phillipjohnston** [comment]
I guess a more general question is desired: is the assembler supported, or do I need a custom target to assemble code?

**Comment by jpakkane** [comment]
If you are using gcc or clang, the C and C++ compilers can compile .s files natively. Otherwise you need a custom target.

**Comment by dcbaker** [comment]
we have nasm support as well, right?

**Comment by phillipjohnston** [comment]
Great, thanks for the clarification. Will the assembler use the c_args that are defined for a cross compilation?

**Comment by dcbaker** [comment]
IIRC it uses the flags for the compiler that invokes it, if you use gcc/clang then yes, if you use g++/clang++ then it'll use the cpp_args

**Comment by phillipjohnston** [comment]
Thanks for the help @dcbaker and @jpakkane, I appreciate it.
