### ISSUE TITLE
Errors should report full path to the meson.build

### ISSUE THREAD

**Issue by Akaricchi** [mesonbuild/meson#5130]
Since *all* of the build files have the same name and there may be many of them, this message tells me virtually nothing:

```
meson.build:32:7: ERROR: If clause <Holder: <mesonbuild.coredata.UserFeatureOption object at 0x7f3f6a6b6780>> does not evaluate to true or false.
```

On a side note, maybe user-facing classes should override their `__repr__` with something nicer.

**Comment by nirbheek** [comment]
That message should always start with `subdir/meson.build` or `meson.build` if there's no subdir. If that error refers to a file in a subdir, that should be fixed.

**Comment by Akaricchi** [comment]
Ah you're right, that error was indeed at the root dir. I've just verified that errors at subdirs are indeed reported with the correct prefix. Sorry for the confusion; I blame lack of sleep...
