### ISSUE TITLE
Test case "85 gtest dependency with version" unexpectedly succeeds

### ISSUE THREAD

**Issue by heftig** [mesonbuild/meson#5153]
The expected-fail test case `test cases/failing/85 gtest dependency with version` succeeds on Arch Linux, so to get the test suite to pass, we move this test into `test cases/frameworks`.

The way our gtest is built: https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/gtest

**Comment by jon-turney** [comment]
Thanks for pointing this out.

I think that test should probably have an explicit `method: 'system'`, just like `83 gl dependency with version`
