### ISSUE TITLE
How to configure the compiler?

### ISSUE THREAD

**Issue by yechaoGitHub** [mesonbuild/meson#5156]
meson.build:1:0: ERROR:  Unknown compiler(s): ['cl', 'cc', 'gcc', 'clang', 'clang-cl']
The follow exceptions were encountered:
Running "cl /?" gave "[Errno 2] No such file or directory: 'cl': 'cl'"
Running "cc --version" gave "[Errno 2] No such file or directory: 'cc': 'cc'"
Running "gcc --version" gave "[Errno 2] No such file or directory: 'gcc': 'gcc'"
Running "clang --version" gave "[Errno 2] No such file or directory: 'clang': 'clang'"
Running "clang-cl /?" gave "[Errno 2] No such file or directory: 'clang-cl': 'clang-cl'"

I want to compile file with cl.exe on Windows. How to set the environment ?

**Comment by yechaoGitHub** [comment]
I have solved it, just add the envirment variable

**Comment by tarun253** [comment]
could you please elaborate how to set?
