### ISSUE TITLE
Using b_sanitize=memory with Clang

### ISSUE THREAD

**Issue by mmoanis** [mesonbuild/meson#5162]
I am using Meson to build with MSAN enabled using clang -since its not available in gcc. 

`CC=clang-6.0 CXX=clang++-6.0  meson build_msan/ -Db_sanitize=memory `

This gives me undefined references to multiple msan builtins, to name a few:
```
FAILED: src/mapi/shared-glapi/libglapi.so.0.0.0 
clang-6.0  -o src/mapi/shared-glapi/libglapi.so.0.0.0 'src/mapi/shared-glapi/glapi@sha/.._entry.c.o' 'src/mapi/shared-glapi/glapi@sha/.._mapi_glapi.c.o' 'src/mapi/shared-glapi/glapi@sha/.._stub.c.o' 'src/mapi/shared-glapi/glapi@sha/.._table.c.o' 'src/mapi/shared-glapi/glapi@sha/.._u_current.c.o' 'src/mapi/shared-glapi/glapi@sha/.._u_execmem.c.o' -fsanitize=memory -Wl,--no-undefined -Wl,--as-needed -shared -fPIC -Wl,--start-group -Wl,-soname,libglapi.so.0 -Wl,--end-group -pthread -Wl,--gc-sections  
src/mapi/shared-glapi/glapi@sha/.._entry.c.o: In function `entry_get_public':
build_msan/../src/mapi/entry_x86-64_tls.h:78: undefined reference to `__msan_param_tls'
build_msan/../src/mapi/entry_x86-64_tls.h:80: undefined reference to `__msan_retval_tls'
```

This is not the case when I set `-Db_lundef=false`.

Would you please elaborate on how to use memory sanitization with clang?

**Comment by jpakkane** [comment]
That is exactly what you should do. There should even be a message printed during configuration if you use Clang and a sanitizer but have not set `b_lundef` to `false`.

**Comment by QuLogic** [comment]
I thought they fixed that; maybe in clang 7?

**Comment by mmoanis** [comment]
Thanks! I will close this and maybe give clang7 a try.

Just to understand, this build option will mask the errors or it will resolve them?

**Comment by jpakkane** [comment]
Resolve.
