### ISSUE TITLE
dependancy not found while configuring even if've I installed it.

### ISSUE THREAD

**Issue by LaurentDuroisin** [mesonbuild/meson#5164]
Hi! I would like to recompile mesa to fix a bug, but, I have a problem with a dependency, meson tells me that the dependency is not present even if I've installed it :

Message: libdrm 2.4.97 needed because amdgpu has the highest requirement

meson.build:1171:4: ERROR: Native dependency 'libdrm_intel' not found

A full log can be found at /home/laurent/GitMesa/mesa/builddir/meson-logs/meson-log.txt
laurent@laurent-K52Je:~/GitMesa/mesa$ dpkg -l | grep libdrm-intel
ii libdrm-intel1:amd64 2.4.97-1 amd64 Userspace interface to intel-specific kernel DRM services -- runtime

**Comment by QuLogic** [comment]
On Debian derivatives, you generally need the `*-dev` packages as well.
