### ISSUE TITLE
Missing documentation for built-in options

### ISSUE THREAD

**Issue by TheQwertiest** [mesonbuild/meson#5165]
https://mesonbuild.com/Builtin-options.html is missing quite a few options like `buildtype`, `optimization`, `strip` and etc. All these options are present in the example output though https://mesonbuild.com/Configuring-a-build-directory.html.

**Comment by TheQwertiest** [comment]
Should I open a PR that rectifies this?

**Comment by jpakkane** [comment]
By all means.

**Comment by nirbheek** [comment]
There's also some unit tests for this that should probably be updated.
