### ISSUE TITLE
MSVC does not always support /ZI, leading to noise in the build process (D9038) in these cases with --buildtype=debug

### ISSUE THREAD

**Issue by andlabs** [mesonbuild/meson#5183]
Right now `--buildtype=debug` uses `/ZI` with MSVC, meaning to enable PDB files with Link and Continue. However, this is not supported on all configurations, and `cl` will warn about that and treat the flag as if it was `/Zi` instead:

```
Z:\src\github.com\andlabs\libui>meson setup build
The Meson build system
Version: 0.50.0
Source dir: Z:\src\github.com\andlabs\libui
Build dir: Z:\src\github.com\andlabs\libui\build
Build type: native build
Project name: libui
Project version: undefined
Native C compiler: cl (msvc 18.00.30723)
Native C++ compiler: cl (msvc 18.00.30723)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Windows resource compiler: Microsoft (R) Windows (R) Resource Compiler Version 6.3.9600.17200
Library user32 found: YES
Library kernel32 found: YES
Library gdi32 found: YES
Library comctl32 found: YES
Library uxtheme found: YES
Library msimg32 found: YES
Library comdlg32 found: YES
Library d2d1 found: YES
Library dwrite found: YES
Library ole32 found: YES
Library oleaut32 found: YES
Library oleacc found: YES
Library uuid found: YES
Library windowscodecs found: YES
Dependency threads found: YES
Build targets in project: 11
Found ninja-1.8.2 at 'C:\Program Files\Meson\ninja.EXE'
WARNING: This version of MSVC does not support cpp_std arguments
WARNING: This version of MSVC does not support cpp_std arguments

Z:\src\github.com\andlabs\libui>ninja --version
1.8.2

Z:\src\github.com\andlabs\libui>ninja -C build
ninja: Entering directory `build'
[1/76] Compiling C object ui@sha/common_attrlist.c.obj.
cl : Command line warning D9038 : /ZI is not supported on this platform; enabling /Zi instead
[2/76] Compiling C object ui@sha/common_attribute.c.obj.
cl : Command line warning D9038 : /ZI is not supported on this platform; enabling /Zi instead
(snipped; imagine this pattern repeating, interspersed with the various actual compiler warnings)
```

In this case, this is Visual Studio 2013 on 64-bit Windows 7 in the x64 Native Tools command line prompt.

[`/ZI` is not supported on 64-bit builds in Visual Studio 2013](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2013/958x11bc%28v%3dvs.120%29); this was added in VS2015. However, this warning likely will appear for anyone using meson to target Windows 10 Desktop for ARM64, as `/ZI` [still is not supported there, even in VS2019](https://docs.microsoft.com/en-us/cpp/build/reference/z7-zi-zi-debug-information-format?view=vs-2019).

Given the `WARNING: This version of MSVC does not support cpp_std arguments` warning, I imagine it shouldn't be too hard to add a check to see if `/ZI` is supported on a `debug` build and, if not, fall back to `/Zi`.

**Comment by agurtovoy** [comment]
Another case where defaulting to `/ZI` is problematic is mixed C++/CUDA projects; `nvcc` doesn't support "Edit and Continue" PDB format and forces `/Zi` when compiling `.cu` files; linking `.cpp` files compiled with `/ZI`  into a library/exe with the `.cu`-derived object files then produces `warning LNK4075: ignoring '/EDITANDCONTINUE' due to '/INCREMENTAL:NO' specification`.

Generally speaking, "Edit and Continue" as a feature is somewhat quirky and IMHO shouldn't be a default, even for debug. I'd like to add an option for the PDB format similar to `b_vscrt` and default it to something more neutral, e.g. `/Zi`. Thoughts?

**Comment by jpakkane** [comment]
This is now fixed in master.

**Comment by andlabs** [comment]
Cool, thanks!
