### ISSUE TITLE
clang-format: Also format header files

### ISSUE THREAD

**Issue by z3ntu** [mesonbuild/meson#5184]
Currently the code
```python
suffixes = set(lang_suffixes['c']).union(set(lang_suffixes['cpp']))
```
in `mesonbuild/scripts/clangformat.py` just takes all `*.c` and `*.cpp` files and formats them but ignores all `*.h` (or `*.hpp`) files in the source.

**Comment by jpakkane** [comment]
.h files are broken but .hpp files should not be. `lang_suffixes['c']` does contain `.hpp`.
