### ISSUE TITLE
Issues in 0.50+ while building GLib using Visual Studio (CPU family detection issues)

### ISSUE THREAD

**Issue by fanc999** [mesonbuild/meson#5189]
Hi,

In 0.50, I was getting an error like the following when building the GResources test program in gio/tests:

<code>
[57/64] Generating test.gresource with a meson_exe.py custom command.
FAILED: gio/tests/test.gresource
"c:/python36/scripts/meson" "--internal" "exe" "d:/glib.build/meson-private/meson_exe_glib-compile-resources_ba4f4ea9d1aa482734c0fa57b2940dbee865d365.dat"
../git_repos/glib/gio/tests/test.gresource.xml: Failed to execute helper program (Invalid argument).
[58/64] Compiling C object gio/tests/4076ad8@@libresourceplugin@sha/meson-generated_.._plugin-resources.c.obj.
</code>

Where things built normally for 0.49.2.

With blessings, thank you!

**Comment by fanc999** [comment]
Hi,

It seems that this problem still exists for 0.50.1.  Is there a way that I can obtain the full command line that is being run when building a custom_target, so I might be able to find out why ('ninja -v' didn't produce anything useful in this case)?

Note that if I previously configured the builddir with 0.49.2 and re-configured in that same builddir without deleting it, this problem does not show, so this looks like a regression to me.

With blessings, thank you

**Comment by nirbheek** [comment]
> Is there a way that I can obtain the full command line that is being run when building a custom_target, so I might be able to find out why ('ninja -v' didn't produce anything useful in this case)?

Currently the only way to do so is to add a print statement in `mesonbuild/scripts/meson_exe.py`. I've been meaning to fix that forever...

**Comment by fanc999** [comment]
Hi @nirbheek,

Thanks for the info!

BTW, when I ran the tests for GLib, many more tests failed because of the same reason (Failed to execute helper program (Invalid argument))...

**Comment by lazka** [comment]
I guess this can be closed now with #5314 merged?

**Comment by fanc999** [comment]
Hi @lazka,

Apparently I did not have cues in the commit message that would trigger the closing of this issue, which I thought I did...

Sorry!

With blessings, thanks for the reminder!
