### ISSUE TITLE
built-in python find_installation failure using msi package on windows

### ISSUE THREAD

**Issue by bruce-richardson** [mesonbuild/meson#5217]
The following meson.build file:

```
project('test',` 'c')

pymod = import('python')
python3 = pymod.find_installation()
```
gives the following error output when run on windows using the MSI package (tested with both 0.49.2 and 0.50)

```
> meson build
The Meson build system
Version: 0.50.0
Source dir: c:\cygwin64\home\bricha3\meson-test
Build dir: c:\cygwin64\home\bricha3\meson-test\build
Build type: native build
Project name: test
Project version: undefined
Native C compiler: clang (clang 7.0.1 "clang version 7.0.1 (tags/RELEASE_701/final)")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Using meson's python ['C:\\Program Files\\Meson\\meson.exe', 'runpython']

meson.build:4:0: ERROR: <ExternalProgram 'python3' -> ['C:\\Program Files\\Meson\\meson.exe', 'runpython']> is not a valid python

A full log can be found at c:\cygwin64\home\bricha3\meson-test\build\meson-logs\meson-log.txt

```

The log file indicates no further information:

```
Build started at 2019-04-05T11:04:13.179697
Main binary: C:\Program Files\Meson\meson.exe
Python system: Windows
The Meson build system
Version: 0.50.0
Source dir: c:\cygwin64\home\bricha3\meson-test
Build dir: c:\cygwin64\home\bricha3\meson-test\build
Build type: native build
Project name: test
Project version: undefined
Sanity testing C compiler: clang
Is cross compiler: False.
Sanity check compiler command line: clang c:\cygwin64\home\bricha3\meson-test\build\meson-private\sanitycheckc.c -o c:\cygwin64\home\bricha3\meson-test\build\meson-private\sanitycheckc.exe
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: c:\cygwin64\home\bricha3\meson-test\build\meson-private\sanitycheckc.exe
Native C compiler: clang (clang 7.0.1 "clang version 7.0.1 (tags/RELEASE_701/final)")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Using meson's python ['C:\\Program Files\\Meson\\meson.exe', 'runpython']

meson.build:4:0: ERROR: <ExternalProgram 'python3' -> ['C:\\Program Files\\Meson\\meson.exe', 'runpython']> is not a valid python
```

**Comment by bruce-richardson** [comment]
When I run the latest meson code manually with python, I do not see this issue - only with the MSI package.

```
Using meson's python ['C:\\Users\\bricha3\\AppData\\Local\\Programs\\Python\\Python37-32\\python.exe'] 
```

**Comment by nirbheek** [comment]
CCing @MathieuDuponchelle who wrote that code.

**Comment by bruce-richardson** [comment]
Further follow-up - the python in the package seems to work fine when called through meson. When I create a simple one-liner python test file, it runs perfectly through meson:

```
c:\....>meson runpython test.py
Hello, world!
```

Therefore it looks like some internal check in meson itself is failing to recognise the valid python.

**Comment by bruce-richardson** [comment]
The issue appears to be with the call to "links_against_libpython()" call in the "INTROSPECT_COMMAND" used to check the python. If I copy that introspect command to a test python file, and run it through meson runpython, I get the following error output:

```
print (json.dumps ({
  'variables': sysconfig.get_config_vars(),
  'paths': sysconfig.get_paths(),
  'install_paths': install_paths,
  'version': sysconfig.get_python_version(),
  'platform': sysconfig.get_platform(),
  'is_pypy': '__pypy__' in sys.builtin_module_names,
  'link_libpython': links_against_libpython(),
}))
```

Removing the final line of the print statement gives:

```
{"variables": {"prefix": ".", "exec_prefix": ".", "py_version": "3.6.8", "py_version_short": "3.6", "py_version_nodot": "36", "installed_base": ".", "base": ".", "installed_platbase": ".", "platbase": ".", "projectbase": "C:\\Program Files\\Meson", "abiflags": "", "LIBDEST": "Lib", "BINLIBDEST": "Lib", "INCLUDEPY": "Include", "EXT_SUFFIX": ".pyd", "EXE": ".exe", "VERSION": "36", "BINDIR": "C:\\Program Files\\Meson", "SO": ".pyd", "userbase": "C:\\Users\\bricha3\\AppData\\Roaming\\Python", "srcdir": "C:\\Program Files\\Meson"}, "paths": {"stdlib": "Lib", "platstdlib": "Lib", "purelib": "Lib\\site-packages", "platlib": "Lib\\site-packages", "include": "Include", "platinclude": "Include", "scripts": "Scripts", "data": "."}, "install_paths": {"stdlib": "\\lib\\python3.6", "platstdlib": "\\lib\\python3.6", "purelib": "\\lib\\python3.6\\site-packages", "platlib": "\\lib\\python3.6\\site-packages", "include": "\\include\\python3.6", "platinclude": "include\\python3.6", "scripts": "\\bin", "data": "."}, "version": "3.6", "platform": "win-amd64", "is_pypy": false}
```
This is just missing the "link_libpython: true" bit at the end, which I get if I run the full introspection command through python normally.

**Comment by MathieuDuponchelle** [comment]
this function was added in https://github.com/mesonbuild/meson/pull/4187/ , CC @lazka :)

**Comment by bruce-richardson** [comment]
I can make this particular error go away by copying over the following files to the distutils folder in the meson installation folder (c:\Program Files\Meson\lib\distutils). They probably should be included in the MSI installation package.

archive_util.py
cmd.py
config.py
core.py
debug.py
dep_util.py
dir_util.py
dist.py
errors.py
extension.py
fancy_getopt.py
file_util.py
spawn.py
util.py

Is there a reason not all the distutils files are packaged? Are other parts of the standard python library omitted similarly, because if so, it reduces the usefulness of the python module, since we can't rely on having a complete python installation available?

**Comment by bruce-richardson** [comment]
Error message running that introspection code is now:

```
Traceback (most recent call last):
  File "mesonbuild\mesonmain.py", line 122, in run
  File "mesonbuild\mesonmain.py", line 91, in run_runpython_command
  File "C:\python\lib\runpy.py", line 263, in run_path
  File "C:\python\lib\runpy.py", line 96, in _run_module_code
  File "C:\python\lib\runpy.py", line 85, in _run_code
  File "test.py", line 28, in <module>
    'link_libpython': links_against_libpython(),
  File "test.py", line 17, in links_against_libpython
    cmd = Distribution().get_command_obj('build_ext')
  File "C:\Program Files\Meson\lib\distutils\dist.py", line 857, in get_command_obj
    klass = self.get_command_class(command)
  File "C:\Program Files\Meson\lib\distutils\dist.py", line 843, in get_command_class
    raise DistutilsModuleError("invalid command '%s'" % command)
distutils.errors.DistutilsModuleError: invalid command 'build_ext'
```

**Comment by bruce-richardson** [comment]
copying over the build_ext file, or the rest of the .py files in the command subfolder, does not appear to fix this issue for me, so not sure what else is going on here.

**Comment by lazka** [comment]
> this function was added in #4187 , CC @lazka :)

I think it's a fair assumption that we require a complete Python install, so the error looks correct to me. We could extend the msi installer to include distutils.

**Comment by bruce-richardson** [comment]
+1 for including a more complete python.

Documenting here my current workaround for anyone else who hits this issue...

What I'm doing for now is using "required: false" when searching for python 3, and then for the custom_target commands to call pythos scripts using it I put in ["meson" "runpython"] directly in them if python3.found() is false. Works well enough for me now at the cost of extra "if" statements.

**Comment by jpakkane** [comment]
The problem here is that both cx_freeze and pyinstaller try to be clever and only bundle the minimal set of things you actually include (even for your own code which seems a bit stupid). This makes sense for most programs but not for us since we want _everything_. Both of them require extra command line arguments to add modules they don't detect automatically.

And even if you do that for all the missing things, you overflow Window's maximum command line length.
