### ISSUE TITLE
Cross-compiling for iOS Simulator not possible from a macOS host

### ISSUE THREAD

**Issue by oleavr** [mesonbuild/meson#5219]
Meson conflates the build and host machines as both have the same `system`, i.e. `darwin`, and also same CPU, endian, etc. This means it uses the build machine's toolchain instead of the host machine's.

**Comment by dcbaker** [comment]
Is this a duplicated of #5102?

**Comment by oleavr** [comment]
@dcbaker Oops this is indeed a duplicate of #5102 – sorry for the spam!

**Comment by dcbaker** [comment]
no worries, just wanted to make sure we didn't have two separate bugs :)
