### ISSUE TITLE
Documentation: Environment variables

### ISSUE THREAD

**Issue by amitdo** [mesonbuild/meson#523]
I suggest you to write a reference to all the environment variables that Meson consumes and produces.

Here is what I found so far in the source code:

[Compiler]
`CC` - C compiler
`CXX` - C++ compiler
`OBJCC` - Objective-C compiler
`OBJCXX` - Objective-C++ compiler
`FC` - Fortran compiler

`AR` - Archiver Program. Used to create and update static library files that the  linker uses

`CPPFLAGS` - C preprocessor flags
`LDFLAGS` - linker flags

`CFLAGS` - C flags
`CXXFLAGS` - C++ flags

`FFLAGS` - Fortran flags
`FCFLAGS` - Fortran flags

`OBJCFLAGS` - Objective-C flags
`OBJCXXFLAGS` - Objective-C++ flags

`DESTDIR`

`MESON_SOURCE_ROOT`
`MESON_BUILD_ROOT`
`MESON_INSTALL_PREFIX`
`MESON_TESTTHREADS`
`MESON_PRINT_TEST_OUTPUT`

**Comment by amitdo** [comment]
I accidentally :+1: myself... :)

**Comment by jpakkane** [comment]
I guess we could add these to the ref manual. Some of those are not really meant for regular people and/or need to be replaced with something saner.

**Comment by amitdo** [comment]
Maybe you want to add a 'Documentation' label here?

**Comment by amitdo** [comment]
More environment variables:
 
`PKG_CONFIG`
`READELF`
`NM`

https://github.com/mesonbuild/meson/wiki/Release-notes-for-0.37.0#overriding-more-binaries-with-environment-variables

**Comment by jpakkane** [comment]
Once we get our new documentation system going anyone can submit documentation fixes via pull requests. That should make the these sorts of fixes easier to do.

**Comment by amitdo** [comment]
http://mesonbuild.com/Release-notes-for-0-40-0.html#running-mesonintrospect-from-scripts

`MESONINTROSPECT`
`MESON_SOURCE_ROOT`

https://github.com/mesonbuild/meson/commit/627190faf397
`MESON_FORCE_BACKTRACE`
