### ISSUE TITLE
Can't use an expression as a dict key?

### ISSUE THREAD

**Issue by Akaricchi** [mesonbuild/meson#5231]
```meson
wtf = 'wtf'
wtf = { wtf : wtf }
```

I would expect this code to be equivalent to:

```meson
wtf = { 'wtf' : 'wtf' }
```

Instead, it raises a parsing error:

```
meson.build:67:8: ERROR: Key must be a string.
wtf = { wtf : wtf }
```

Seems like an unreasonable limitation?

**Comment by nirbheek** [comment]
This is a known limitation and it's documented too: [`Keys are required to be literal strings, values can be objects of any type.`](https://mesonbuild.com/Syntax.html#dictionaries)

IIRC this was done because it was easier to implement at the time. I'm sure we'd be happy to accept patches to enable any object to be inserted as a key since almost all objects are immutable in Meson anyway.

**Comment by xclaesse** [comment]
Already fixed by this PR,I think: https://github.com/mesonbuild/meson/pull/6166

**Comment by marc-h38** [comment]
> Already fixed by this PR,I think: #6166

Almost, see PR #6279 above (tagging @scivision)

In the mean time and for people with meson_version <= 0.52, re-sharing a smart workaround @eli-schwartz shared on IRC:
```python
str_keys = [['one', '1'], ['two', '2'], ['three', '3']]
foreach key in str_keys: do_things(key[0], key[1])
```
This is basically re-implementing a dict manually with a multidimensional list. A bit tedious, but nowhere near as tedious as "unrolling" the `foreach` loop and Duplicating and Diverging a large `do_things`.

**Comment by eli-schwartz** [comment]
Oh, cool, I can drop my multidimensional lists soon. \o/

**Comment by xclaesse** [comment]
oh wait, actually `+=` operator got fixed, not normal assignation.

```meson
k = 'somekey'
d = {k:1}
message(d[k])
```

-> ERROR: Key somekey is not in dict

**Comment by xclaesse** [comment]
Ok, I did a real refactor of dict: https://github.com/mesonbuild/meson/pull/6281

There was too much code duplication for my taste, and I found a few inconsistencies like:
```meson
# This was not raising error
k = 'a'
d = {k:1, 'a':2}
# This was not allowed, as well as any function call that returns string
d = {'a' / 'b':1}
```

**Comment by scivision** [comment]
I believe #6281 fixed this issue
