### ISSUE TITLE
Emscripten cross-build gets stuck in an endless reconfigure loop

### ISSUE THREAD

**Issue by Akaricchi** [mesonbuild/meson#5257]
This is a 0.51 regression introduced in 65e59c84a198062f21ab68fdae41b3e5de8d8480

I frankly have no idea what is actually causing it, and so far I've been only able to reproduce it with an Emscripten toolchain.

These steps, I believe, should reproduce the bug:

1) Install the latest Emscripten as instructed [here](https://emscripten.org/docs/getting_started/downloads.html). Make sure to source the `emsdk_env.sh` script as well.
2) Create a cross file as follows:
```ini
[binaries]
c='/path/to/emscripten/emcc'
cpp='/path/to/emscripten/em++'
ar='/path/to/emscripten/emar'
ranlib='/path/to/emscripten/emranlib'
pkgconfig=['/path/to/emscripten/emconfigure', 'pkg-config']
file_packager=['/usr/bin/python3', '/path/to/emscripten/tools/file_packager.py']

[properties]
root='/path/to/emscripten/system'
needs_exe_wrapper=true

[host_machine]
system='emscripten'
cpu_family='wasm'
cpu='wasm32'
endian='little'
```
(Some of these fields might be extraneous for the purpose of testing. I kept it as similar to my local configuration as possible.)

3. Create and build a minimal project: `echo "project('fail', 'c')" > meson.build && meson --cross-file emscripten builddir && ninja -C builddir`
4. Hit Ctrl+C when you've had enough.

**Comment by Akaricchi** [comment]
Relevant PR: #5083 
cc @rossburton

**Comment by dcbaker** [comment]
https://github.com/mesonbuild/meson/pull/5224 should fix it.

**Comment by dcbaker** [comment]
I'll rebase it
