### ISSUE TITLE
Simple example fails with boost under windows msvc2013 due to bad 64 bit detection? 

### ISSUE THREAD

**Issue by germandiagogomez** [mesonbuild/meson#526]
*EDIT*: The original problem was not correct, I replace at the top level what happens so that it does not confuse anyone and will leave the original message below after the new one. I also edited the title and changed for a more meaningful description.

==============================CURRENT PROBLEM=======================
I plan to adopt meson as my default soon. I will discard cmake finally I think. FWIW I found a few problems also on my side:

    I was using boost 64 bits but I opened a toolchain window for 32 bits (my bad).
    I tried with a 64 bits toolchain: things still did not work, seems that the boost detection for the libs tried to use lib32* instead of lib64* in BoostDependency.

So I think the issue is not what I originally reported: the problem is that the detection is wrong and my machine is detected as 32 bits. LIBPATH: is empty when generating the ninja file because there is not libpath detected by the globbing pattern in the python code in BoostDependency.

    I renamed my folder to lib32, that is cheating but it works.

=========================ORIGINAL MESSAGE I POSTED IS BELOW ======

With windows and ninja, Microsoft Visual C++ 2013 I tried to compile the attached example and failed with this error:

[hello.zip](https://github.com/mesonbuild/meson/files/241897/hello.zip)

```
The Meson build system                                                           
Version: 0.31.0                                                                  
Source dir: C:\Users\x\Desktop\hello                                             
Build dir: C:\Users\x\Desktop\hello\build                                        
Build type: native build                                                         
Build machine cpu family: amd64                                                  
Build machine cpu: amd64                                                         
Project name: hello                                                              
Native cpp compiler: cl (msvc 18.00.40629)                                       
Dependency Boost (regex) found: YES (1.51, C:\boost_1_51_2013)                   
Build targets in project: 1                                                      
                                                                                 
C:\Users\x\Desktop\hello\build>ninja                                             
[1/2] Compiling cpp object hello@exe/hello.cpp.obj                               
Unknown compiler version - please run the configure tests and report the results 
[2/2] Linking target hello.exe                                                   
FAILED: hello.exe                                                                
link @hello.exe.rsp                                                              
Microsoft (R) Incremental Linker Version 12.00.40629.0                           
Copyright (C) Microsoft Corporation.  All rights reserved.                       
                                                                                 
LINK : fatal error LNK1146: no argument specified with option '/LIBPATH:'        
ninja: build stopped: subcommand failed.
```

**Comment by germandiagogomez** [comment]
By the way, my library naming used:

libboost_regex-vc120-mt-gd-1_51.lib
libboost_regex-vc120-mt-1_51.lib

I have libraries in boost under BOOST_ROOT/lib.

**Comment by nirbheek** [comment]
I think the problem is likely in `mesonbuild/dependencies.py`:`detect_lib_modules_win()`. Most likely, `self.libdir` is `None` or `''` because the globbing is broken. Someone would need to debug this and figure out the best way to fix it.

@germandiagogomez want to take a crack at providing a patch? :)

**Comment by germandiagogomez** [comment]
> @germandiagogomez want to take a crack at providing a patch? :)

I plan to adopt meson as my default soon. I will discard cmake finally I think. FWIW I found a few problems also on my side:

1. I was using boost 64 bits but I opened a toolchain window for 32 bits (my bad).
2. I tried with a 64 bits toolchain: things still did not work, seems that the boost detection for the libs tried to use lib32* instead of lib64* in BoostDependency.
3. I renamed my folder to lib32, that is cheating but it works.

So I think the issue is not what I originally reported: the problem is that the detection is wrong and my machine is detected as 32 bits.

I do not have much free time, but everytime I find problems in meson I will keep fixing as they get in the way, so expect maybe some small contributions from me from time to time. But I do not commit, just in case, lol, because this is part of my free time and have little.

**Comment by jpakkane** [comment]
The Boost module has detection logic for 32/64 bit. The check is done with this Python snippet

    not(sys.maxsize > 2**32)

Could you run the following snippet in the interactive Python terminal on your machine and post the result:

    import sys
    print(sys.maxsize)

Thanks

**Comment by germandiagogomez** [comment]
This was done in a terminal for Windows with MSVC for x64 in Windows 10 running in a VM in MacBooc Pro Late 2013 with El Capitan:

```
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print(sys.maxsize)
2147483647
```

**Comment by nirbheek** [comment]
So the issue is that we should not assume that the installed Python is always going to correspond to the "native" architecture. Need a way to detect it from the toolchain environment.
