### ISSUE TITLE
In meson 0.50.0, executables using gnome.compile_resources now require executable memory

### ISSUE THREAD

**Issue by mcatanzaro** [mesonbuild/meson#5268]
Since b4f04a67de3dd13027be523d1c14e6e7485a9af5 programs that use `gnome.compile_resources` now require executable stack (verify with `execstack -q`). This is a Fedora 30 release blocker because SELinux prevents gnome-initial-setup from doing any mmaps, as all mmaps are now requests for executable memory, crashing gnome-initial-setup and bringing down the first boot experience: https://bugzilla.redhat.com/show_bug.cgi?id=1699099

This problem was already fixed in meson master by reverting 5dc613d61824fc1ebb92b188086134c84158b4eb, but stuff built with 0.50.0 and using `gnome.compile_resources` is going to need to be rebuilt. You might want to close this issue immediately, because it really is already fixed, but an upstream issue report seemed advisable since the current stable version is affected and this doesn't seem to have been noticed by developers yet.

This change to the linker invocation fixes the issue:

```
$ git diff
diff --git a/mesonbuild/modules/gnome.py b/mesonbuild/modules/gnome.py
index 4473bcbf..e73bda30 100644
--- a/mesonbuild/modules/gnome.py
+++ b/mesonbuild/modules/gnome.py
@@ -287,7 +287,7 @@ class GnomeModule(ExtensionModule):
             objcopy = None
 
         o_kwargs = {
-            'command': [ld, '-r', '-b', 'binary', '@INPUT@', '-o', '@OUTPUT@'],
+            'command': [ld, '-r', '-b', 'binary', '-z', 'noexecstack', '@INPUT@', '-o', '@OUTPUT@'],
             'input': target_g,
             'output': args[0] + '1.o'
         }
```

but that suggested change is probably not correct because sometimes you legitimately do need execmem. According to `execstack(8)`:

>        To avoid breaking binaries and shared libraries
>        which need executable stack, ELF binaries and shared libraries now  can
>        be  marked  as  requiring  executable  stack or not requiring it.  This
>        marking is done through the p_flags field in the  PT_GNU_STACK  program
>        header entry.  If the marking is missing, kernel or dynamic linker need
>        to assume it might need executable stack.  The marking is done automat‐
>        ically  by  recent GCC versions (objects using trampolines on the stack
>        are marked as requiring executable stack, all other newly built objects
>        are marked as not requiring it) and linker collects these markings into
>        marking of the whole binary or shared library.

So if gnome.py is going to call ld manually it's going to have to be smarter about it.

CC @Ninja-Koala @ignatenkobrain

**Comment by nirbheek** [comment]
This has already been reverted in https://github.com/mesonbuild/meson/pull/5144 and will be in the 0.50.1 stable release.

**Comment by mcatanzaro** [comment]
Yes, note:

> You might want to close this issue immediately, because it really is already fixed, but an upstream issue report seemed advisable since the current stable version is affected and this doesn't seem to have been noticed by developers yet.

**Comment by mcatanzaro** [comment]
I mean: please don't un-revert it without thinking about this. :)

**Comment by nirbheek** [comment]
> I mean: please don't un-revert it without thinking about this. :)

Ah right, makes sense. Just going to drop here that https://github.com/mesonbuild/meson/pull/4222 was the original PR for this, so the two are linked.

**Comment by AdamWill** [comment]
Yeah, and I'd further note that the revert seems to have been done because this change introduced an API break, and the discussion clearly implies an expectation that it would be added back later somehow:

* ["I'd leave it for 0.51 as is (and noting it in breaking changes) and just revert it for 0.50..."](https://github.com/mesonbuild/meson/pull/5144#issuecomment-476884921)
* ["I think we need to enable this via an opt-in kwarg in 0.51."](https://github.com/mesonbuild/meson/pull/5144#issuecomment-477171536)

Even if you make it an opt-in kwarg, this needs to be fixed, right?

**Comment by nirbheek** [comment]
> Even if you make it an opt-in kwarg, this needs to be fixed, right?

Yes, it does.
