### ISSUE TITLE
Shitty error message when building a project that uses a new user option type with an old version of meson

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#5281]
```
$ cat meson.build
project('test', 'c', meson_version : '>= 0.58.0')
$ cat meson_options.txt
option('some-option', type: 'foo', value: '')
```

```
$ meson _build
The Meson build system
Version: 0.50.1
Source dir: C:\projects\repos\test.git
Build dir: C:\projects\repos\test.git\_build
Build type: native build

meson_options.txt:1:0: ERROR: Unknown type foo.
```

This happens because we're parsing `meson_options.txt` ~~before the first line of `meson.build`~~ before checking the required meson version to figure out if we can even parse it, which leads to an unhelpful error message.

I've seen a lot of people run into this, most recently at https://gitlab.gnome.org/GNOME/glib/issues/1752.

**Comment by nirbheek** [comment]
I have a fix for this, just need to write a test.

**Comment by jon-turney** [comment]
Duplicate of #3480?

**Comment by nirbheek** [comment]
Duplicate of #3480
