### ISSUE TITLE
Unable to pass -Wno-overlength-strings when building source file generated with gnome.compile_resources().

### ISSUE THREAD

**Issue by martin-ejdestig** [mesonbuild/meson#5283]
I recently started getting a warning when compiling glib-compile-resource generated source files:

error: string length ‘42864’ is greater than the length ‘4095’ ISO C99 compilers are required to support [-Werror=overlength-strings]

I want to build with -Wpedantic so tried to pass -Wno-overlength-strings to target using the generated sources by using cpp_args in executable(). It seems like the -Wno-overlength-strings flag is not used when compiling the generated source files though. It is used for all other source files in the target.

That the -Wno-* flag is not used together with the fact that it looks like glib is not going to fix it upstream makes it... problematic... to build with -Wpedantic and -Werror. See links in https://gitlab.gnome.org/GNOME/glib/issues/1743 .

**Comment by martin-ejdestig** [comment]
Asked in the glib issue if a pragma could be added to disable -Woverlength-strings. It is still weird to me that Meson does not pass along the flags though.

**Comment by martin-ejdestig** [comment]
OK, sorry figured out what the issue was. Specifying -Wno-* in `c_args` as well as `cpp_args` makes to warning go away. Sorry for the noise.

**Comment by nirbheek** [comment]
Just to clarify in case there's any confusion: `cpp_args` is for C++ code, not for the C Pre-processor.

**Comment by martin-ejdestig** [comment]
Hum, C pre-processor? One would think this limitation applies more in the compilation stage...

Anyway, yes. The problem was that I added it to cpp_args (executable() with C++ sources except for generated glib stuff) while the generated resource file is a C file.
