### ISSUE TITLE
meson_options.txt vs meson.options

### ISSUE THREAD

**Issue by agurtovoy** [mesonbuild/meson#5288]
Was just wondering for the rationale of having the options file name be what it is (`meson_options.txt`) rather than, say, `meson.options`. It's obviously a rather minor concern, but having a naming consistency between `meson.build` and the options file would allow for more precise wildcards for querying/copying build spec files (`meson.*` vs `meson*`). 

Thanks!

**Comment by marc-h38** [comment]
BTW anyone knows why `meson.build` as opposed to a more usual `build.meson`?

**Comment by jpakkane** [comment]
It seemed like a good idea at the time.
