### ISSUE TITLE
dependency('appleframeworks') should work on Linux (but fail)

### ISSUE THREAD

**Issue by chergert** [mesonbuild/meson#5295]
Currently, I have to put this in a `'darwin'` check, because it fails to run on Linux. I think it's reasonable for it to be outside a darwin check, so long as `required:false`.

```
cocoa_dep = dependency('appleframeworks', modules: 'Cocoa', required: false)
```

**Comment by jon-turney** [comment]
See also https://github.com/mesonbuild/meson/pull/4453#issuecomment-434661768
