### ISSUE TITLE
Broken meson after 60969d9

### ISSUE THREAD

**Issue by TheQwertiest** [mesonbuild/meson#5326]
`meson` is totally broken after https://github.com/mesonbuild/meson/commit/60969d99d33001317c569a9b37d3b9efae08d387: every meson call triggers the following error
https://paste.ofcode.org/yFytL9HLtXJQEKz8WYfVKN

meson.sh:
```bash
#!/bin/bash
/usr/bin/python3 /home/theqwertiest/meson_trunk/meson.py "$@"  
```

Python version:
```
> python3 --version
> Python 3.5.2
```

**Comment by TheQwertiest** [comment]
Ping @dcbaker (related https://github.com/mesonbuild/meson/pull/5265)

**Comment by dcbaker** [comment]
I'll look at it, it probably means we need to make some type annotation a string.
