### ISSUE TITLE
support clcache or equivalent on windows

### ISSUE THREAD

**Issue by yoava333** [mesonbuild/meson#533]
on *nix machines meson automatically detects and incorporates ccache in the build.
on windows there's an equivalent named clcache (https://github.com/frerich/clcache/), I suggest adding support for it.

**Comment by eli-schwartz** [comment]
clcache appears to be abandoned by its original author, the repository is archived and it hasn't seen any activity since February 2019.

In git master, #9428 has added support for https://github.com/mozilla/sccache which does support MSVC, so I am going to close this ticket as implemented.
