### ISSUE TITLE
0.50.1: Requires.private is propagated when no static libraries are used

### ISSUE THREAD

**Issue by kloczek** [mesonbuild/meson#5334]
I'm not 100% sure where is the problem however it is related to propagating Requires.private in .pc files but looks like it maybe more than one bug/issue.
Case:
latest libwnck in meson.build has:

<pre><span style="background-color:#1C1C1C"><font color="#BCBCBC">pc_conf = configuration_data()</font></span>
<span style="background-color:#1C1C1C"><font color="#BCBCBC">pc_conf.set(&apos;prefix&apos;, get_option(&apos;prefix&apos;))</font></span>
<span style="background-color:#1C1C1C"><font color="#BCBCBC">pc_conf.set(&apos;exec_prefix&apos;, &apos;${prefix}&apos;)</font></span>
<span style="background-color:#1C1C1C"><font color="#BCBCBC">pc_conf.set(&apos;libdir&apos;, &apos;${exec_prefix}/&apos; + get_option(&apos;libdir&apos;))</font></span>
<span style="background-color:#1C1C1C"><font color="#BCBCBC">pc_conf.set(&apos;includedir&apos;, &apos;${prefix}/&apos; + get_option(&apos;includedir&apos;))</font></span>
<span style="background-color:#1C1C1C"><font color="#BCBCBC">pc_conf.set(&apos;STARTUP_NOTIFICATION_PACKAGE&apos;, STARTUP_NOTIFICATION_PACKAGE)</font></span>
<span style="background-color:#1C1C1C"><font color="#BCBCBC">pc_conf.set(&apos;X11_PACKAGE&apos;, X11_PACKAGE)</font></span>
<span style="background-color:#1C1C1C"><font color="#BCBCBC">pc_conf.set(&apos;XRES_PACKAGE&apos;, XRES_PACKAGE)</font></span>
<span style="background-color:#1C1C1C"><font color="#BCBCBC">pc_conf.set(&apos;VERSION&apos;, meson.project_version())</font></span>

<span style="background-color:#1C1C1C"><font color="#BCBCBC">foreach pc: [PACKAGE_NAME, PACKAGE_NAME + &apos;-uninstalled&apos;]</font></span>
<span style="background-color:#1C1C1C"><font color="#BCBCBC">  DoInstall = true</font></span>
<span style="background-color:#1C1C1C"><font color="#BCBCBC">  if pc.contains(&apos;-uninstalled&apos;)</font></span>
<span style="background-color:#1C1C1C"><font color="#BCBCBC">    DoInstall = false</font></span>
<span style="background-color:#1C1C1C"><font color="#BCBCBC">  endif</font></span>
<span style="background-color:#1C1C1C"><font color="#BCBCBC">  configure_file(input: pc + &apos;.pc.in&apos;,</font></span>
<span style="background-color:#1C1C1C"><font color="#BCBCBC">    output: pc + &apos;.pc&apos;,</font></span>
<span style="background-color:#1C1C1C"><font color="#BCBCBC">    configuration: pc_conf,</font></span>
<span style="background-color:#1C1C1C"><font color="#BCBCBC">    install: DoInstall,</font></span>
<span style="background-color:#1C1C1C"><font color="#BCBCBC">    install_dir: join_paths(libdir, &apos;pkgconfig&apos;))</font></span>
<span style="background-color:#1C1C1C"><font color="#BCBCBC">endforeach</font></span>
</pre>

It causes that it is generated .pc file:
<pre><span style="background-color:#1C1C1C"><font color="#BCBCBC">prefix=/usr</font></span>
<span style="background-color:#1C1C1C"><font color="#BCBCBC">exec_prefix=${prefix}</font></span>
<span style="background-color:#1C1C1C"><font color="#BCBCBC">libdir=${exec_prefix}/lib64</font></span>
<span style="background-color:#1C1C1C"><font color="#BCBCBC">includedir=${prefix}/include</font></span>

<span style="background-color:#1C1C1C"><font color="#BCBCBC">Name: libwnck</font></span>
<span style="background-color:#1C1C1C"><font color="#BCBCBC">Description: Window Navigator Construction Kit library</font></span>
<span style="background-color:#1C1C1C"><font color="#BCBCBC">Version: 3.31.4</font></span>
<span style="background-color:#1C1C1C"><font color="#BCBCBC">Requires: glib-2.0 gobject-2.0 gtk+-3.0</font></span>
<span style="background-color:#1C1C1C"><font color="#BCBCBC">Requires.private: x11 pango cairo libstartup-notification-1.0 xres</font></span>
<span style="background-color:#1C1C1C"><font color="#BCBCBC">Libs: -L${libdir} -lwnck-3</font></span>
<span style="background-color:#1C1C1C"><font color="#BCBCBC">Cflags: -I${includedir}/libwnck-3.0</font></span>
</pre>
Issues:
1) xres dependency is added despite fact that I'm building libwnck on system without xres and it it is nothing wrong with that as in meson.build is:
<pre><span style="background-color:#1C1C1C"><font color="#BCBCBC"> {&apos;name&apos;: XRES_PACKAGE, &apos;required&apos;: false},</font></span>
</pre>
For that I have already opened https://gitlab.gnome.org/GNOME/libwnck/issues/138

2) .pc files are with propagated libwnck Requires.private despite fact that during building libwnck I'm not generating static libraries which could be used later.

3) I see on my system that a lot of other projects which are using meson based .pc files generators have Requires.private and none of them have been build to build static libraries

4) Issue seems is as well with pkgconfig as on using PKG_CHECK_MODULES() aclocal macro it checks  Requires and Requires.private dependencies.

**Comment by eli-schwartz** [comment]
> xres dependency is added despite fact that I'm building libwnck on system without xres and it it is nothing wrong with that as in meson.build is:

Downstream issue as their meson.build hardcodes `XRES_PACKAGE = 'xres'` rather than null'ing this if the dependency is not found, and then configures their .pc file using that text string.

> .pc files are with propagated libwnck Requires.private despite fact that during building libwnck I'm not generating static libraries which could be used later.

The .pc files are not propagated with anything. libwnck contains a .pc.in that contains "Requires.private", and meson is not responsible for adding these at all.

> I see on my system that a lot of other projects which are using meson based .pc files generators have Requires.private and none of them have been build to build static libraries

This is correct and proper. When using these .pc files, if you use `pkg-config --libs libwnck`, you only get "Libs" and "Requires". In order for pkg-config to also depend on and emit the "Requires.private", you must use `pkg-config --static --libs libwnck`.

Most .pc files that are generated by autotools, or finely crafted in a text editor, also have Requires.private as needed.

> Issue seems is as well with pkgconfig as on using PKG_CHECK_MODULES() aclocal macro it checks  Requires and Requires.private dependencies.

This is incorrect and it does not check "Requires.private" on my system. However, `PKG_CHECK_MODULES_STATIC()` will check it. Also, if you `export PKG_CONFIG="pkg-config --static"` before executing `./configure` it will check "Requires.private".

**Comment by kloczek** [comment]
You are right about template .pc.in file in libwnck. Yes, it has Requires.private line.
My mistake :/

**Comment by kloczek** [comment]
I've added in libwnck package workaround in rpm package %install section by execute `%__sed -i 's/ xres//' %{buildroot}%{_libdir}/pkgconfig/*.pc` however still somethimg something is wrong even a bit deepper.
libwnck-3.0.pc has line:
`Requires: glib-2.0 gobject-2.0 gtk+-3.0
`
And that is OK because libwnck libraruy header files are using those three packages header files.
However looking on `--libs` and `--libs --statc` output I think that --libs output is to long:

```
[tkloczko@domek ready]$ pkg-config --libs libwnck-3.0
-lwnck-3 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lpixman-1 -lfontconfig -lfreetype -lpng16 -lz -lxcb-shm -lxcb -lxcb-render -lXrender -lX11 -lXext -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 
[tkloczko@domek ready]$ pkg-config --static --libs libwnck-3.0
-lwnck-3 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lz -lz -lXau -lxcb -lXau -lxcb -lXau -lX11 -lX11 -lz -lz -lXau -lxcb -lXau -lxcb -lXau -lX11 -lX11 -lz -lz -lXau -lxcb -lXau -lxcb -lXau -lX11 -lX11 -latk-1.0 -lz -lz -lXau -lxcb -lXau -lxcb -lXau -lX11 -lX11 -lcairo-gobject -lz -lz -lXau -lxcb -lXau -lxcb -lXau -lX11 -lX11 -lX11 -lgdk_pixbuf-2.0 -lgio-2.0 -lpango-1.0 -lcairo -lgobject-2.0 -lglib-2.0 -lpixman-1 -lfontconfig -lz -lfreetype -lbz2 -lpng16 -lz -lxcb-shm -lXau -lxcb -lXau -lxcb-render -lxcb -lXau -lXrender -lX11 -lX11 -lXext -lX11 -lstartup-notification-1 

```
Theoretically --libs as it is only for shared libraries linking should return just `-lwnck-3`.
Looks like Requires affects --libs output which is causing linking DSO with to many libraries.
Above is with:
```
$ pkg-config --version
1.6.1

```
I'm almost sure that 1.5.x have been generating shorter/proper list.

**Comment by eli-schwartz** [comment]
> Theoretically --libs as it is only for shared libraries linking should return just `-lwnck-3`.

No.

> Looks like Requires affects --libs output which is causing linking DSO with to many libraries.

Requires is strictly defined. Its entire purpose is in order to cause DSO with many libraries. Any pc file which contains Requires, is stating that it needs to link to all these dependencies even when it is a shared library. This happens when a project, like gtk3, exports all of its dependencies as part of its public ABI.

...

This is all coming from pkg-config, so it has nothing to do with meson. Maybe report further questions to the pkg-config project at https://www.freedesktop.org/wiki/Software/pkg-config/

**Comment by kloczek** [comment]
Yes I think that we can close this ticket.
Thanks for your time :)
