### ISSUE TITLE
meson cant detect clang-cl

### ISSUE THREAD

**Issue by RedSkotina** [mesonbuild/meson#534]
clang-cl is an alternative command-line interface to Clang driver, designed for compatibility with the Visual C++ compiler, cl.exe.
he has command options like `cl.exe /?`, but meson try use `clang-cl.exe --version` and failed.
So he need included to check for cl in mesonbuild/environment.py:230

```
if basename == 'cl' or basename == 'cl.exe':
                    arg = '/?'
                else:
                    arg = '--version'
```

**Comment by jpakkane** [comment]
This requires bigger changes as we need to feed msvc-type compiler flags to Clang if it is called clang-cl.exe (I think, not tested).

**Comment by nirbheek** [comment]
It's probably simpler to derive from `VisualStudioCCompiler` etc. Another problem is what to report clang-cl as.

If we report it as `'clang'`, then build files that add `c_args` or `link_args` based on `compiler.get_id()` will fail.

If we report it as `'msvc'` projects that build different sources depending on the compiler will fail. Even Meson itself has code that's conditional on that.

We should probably report it as `'clang-msvc'`. Build files that assume not-msvc is GNU syntax will break but at least they have a way of detecting this case and being fixed accordingly.

**Comment by XVilka** [comment]
So, any resolution on this one? Seems like forgotten.

**Comment by XVilka** [comment]
Would be nice to be able do something like this on Windows: http://blog.llvm.org/2018/03/clang-is-now-used-to-build-chrome-for.html

**Comment by nirbheek** [comment]
This is not forgotten, just needs someone to work on it. GNOME (gtk+ in particular) is also looking into this for [g_autoptr](https://blogs.gnome.org/desrt/2015/01/30/g_autoptr/) support when building with MSVC.

**Comment by dcbaker** [comment]
@jon-turney, this should be closed now, right?

**Comment by jon-turney** [comment]
Yup
