### ISSUE TITLE
Function checking fails on newest sid

### ISSUE THREAD

**Issue by jpakkane** [mesonbuild/meson#535]
Here's the log:

     Running compile:
     Command line:  ccache cc /tmp/tmp8lpdrvql.c -o /tmp/tmpnp00uh46
     Code:
      
             #define lchmod meson_disable_define_of_lchmod
             #include <sys/stat.h>
                                                         #include <unistd.h>
             #undef lchmod
             
             #ifdef __cplusplus
             extern "C"
             #endif
             char lchmod ();
             
             #if defined __stub_lchmod || defined __stub___lchmod
             fail fail fail this function is not going to work
             #endif
             
             int
             main ()
             {
               return lchmod ();
             }
     Compiler stdout:
      /tmp/tmp8lpdrvql.c:13:9: error: unknown type name ‘fail’
              fail fail fail this function is not going to work
              ^
     /tmp/tmp8lpdrvql.c:13:19: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘fail’
              fail fail fail this function is not going to work
                        ^
     /tmp/tmp8lpdrvql.c:13:19: error: unknown type name ‘fail’

**Comment by nirbheek** [comment]
lchmod is not available on Linux and this is supposed to fail in exactly that way. What is the issue here?

**Comment by jpakkane** [comment]
I copypasted the wrong bit.

    Command line:  ccache cc /tmp/tmpsoqb7tg5.c -O0 -o /tmp/tmpq3q_0ygi
    Code:
     #include <sys/stat.h>
                                                    #include <unistd.h>
    int main() { lchmod; }
    Compiler stdout:
 
    Compiler stderr:
 
    Checking for function "lchmod": YES

    Meson encountered an error in file meson.build, line 25, column 2:
    Assert failed: "lchmod" check should have failed

**Comment by jpakkane** [comment]
This also happens on latest Fedora.

**Comment by nirbheek** [comment]
This rather obvious patch fixes it for me. I should've taken care of that in #531. :) 

https://github.com/mesonbuild/meson/pull/537
