### ISSUE TITLE
How to prevent creating shared library alias?

### ISSUE THREAD

**Issue by twaik** [mesonbuild/meson#5359]
Hi! I need to know a way to prevent library aliases creating.
```
libexample.so -> libexample.so.0
libexample.so.0 -> libexample.so.0.0.1
libexample.so.0.0.1
```
I did not find it in user's manual.

**Comment by twaik** [comment]
I think I found it. I need to use shared_module instead of shared_library.

**Comment by jpakkane** [comment]
That's not the right way to do it (or rather is has probably unwanted side effects). The correct way is to not specify `version` or `soversion` in the target definition.

**Comment by twaik** [comment]
Thanks.
