### ISSUE TITLE
Function for add global linker arguments.

### ISSUE THREAD

**Issue by RedSkotina** [mesonbuild/meson#536]
I use clang with option `--target=i686-w64-mingw32`  (Generate code for the given target)
I add this option at build stage with
`add_global_arguments('--target=i686-w64-mingw32', language : 'cpp') `
but cant add at link stage
from target_test.exe.rsp:
```
build target_test@exe/hello.cpp.obj: cpp_COMPILER ../hello.cpp
 DEPFILE = target_test@exe\\hello.cpp.obj.d
 ARGS = "-Itarget_test@exe" "-I.." "-I." "-Wall" "-Winvalid-pch" "-Wnon-virtual-dtor" "--target=i686-w64-mingw32"  "-O0" "-g"

build target_test.exe: cpp_LINKER target_test@exe/hello.cpp.obj
 LINK_ARGS = "-Wl,--no-undefined"
```
Without this option at link stage i take errors:
```
hello.cpp.obj : error LNK2019: unresolved external symbol ___main referenced in
function _main
```

I can add this option to link_args in target definition, but maybe we can take function for add global link arguments like `add_global_arguments` ?

**Comment by nirbheek** [comment]
Shouldn't this be done with a cross-file anyway?
