### ISSUE TITLE
lib32-mesa-git error "'LLVM' is not a config-tool dependency" bisected to 1fba945b61619a344c21468eb2bb36604f1cb975

### ISSUE THREAD

**Issue by Valmar33** [mesonbuild/meson#5365]
LLVM is found:

`Dependency LLVM (modules: amdgpu, asmparser, bitreader, bitwriter, ipo, mcdisassembler, mcjit, native) found: YES 9.0.0`

But, meson-git borks out with:

`meson.build:1274:14: ERROR: 'LLVM' is not a config-tool dependency`

First bad commit is:

1fba945b61619a344c21468eb2bb36604f1cb975 ~ "cmake: LLVM better modules handling"

**Comment by dcbaker** [comment]
Actually, this is a mesa bug. I've submitted an MR for mesa:
https://gitlab.freedesktop.org/mesa/mesa/merge_requests/830
