### ISSUE TITLE
Google groups "mesonbuild" mailing list not accessible

### ISSUE THREAD

**Issue by krader1961** [mesonbuild/meson#5373]
This [project's web UI for the mailing list](https://groups.google.com/forum/#!forum/mesonbuild) listed on the project's [main page](http://mesonbuild.com/) returns "This group either doesn't exist, or you don't have permission to access it." This same issue was recently discussed on the golang-dev mailing list. The problem was apparently fixed by changing the configuration of the mailing list so that "List this group in the directory" was checked (i.e., enabled).

I'm bringing this up because I've been trying to figure out how to use compiler flags added by `add_global_arguments()` in `meson.get_compiler('c').compiles()` invocations and wanted to search the mailing list and/or post a new message with my question.

**Comment by jpakkane** [comment]
This should be fixed now, thanks.

> how to use compiler flags added by add_global_arguments() in meson.get_compiler('c').compiles() invocations

There is no automatic way to do that. You need to track the arguments yourself and pass them with the `args` kwarg to the compile test method.

**Comment by krader1961** [comment]
> This should be fixed now, thanks. 

Confirmed. I can now view the mailing list via the Google Groups web UI.

> There is no automatic way to do that. You need to track the arguments yourself and pass them with the args kwarg to the compile test method.

Thanks for confirming that. It is in fact what I've been doing. But it's error prone. Whenever a `add_global_arguments()` is done  we also have to remember to update the `feature_test_flags` array we pass via the compiles `args` keyword. I can appreciate that many projects would not want global flags to be automatically added to a feature test performed via the `compiles()`, `links()` or `runs()` methods. So the existing behavior makes sense. Would a PR that implements a method for extracting the global args be accepted?

**Comment by jpakkane** [comment]
Under which circumstances do you need to combine args? Almost all args that I can think of work in isolation, especially since the most common ones (optimization, exceptions, language std) come from builtin options and those are used in tests automatically.

**Comment by krader1961** [comment]
As an example, we want `-std=gnu99` and `-D_GNU_SOURCE` when doing feature tests and when building libast and ksh (the main code). On the other hand we add `-fsanitize=address` to the global compiler args if the user enables ASAN. But it doesn't really make sense to add those flags to feature test compiles (although doing so shouldn't hurt). So now that I've thought about this more I think I'll just stick with the current scheme.  Especially since we can't use a new Meson feature since we need to be able to build ksh on distros that have a relatively old version of Meson; e.g., 0.44.

Thanks for asking for clarification as it forced me to think more about why we're using (a subset of) global args in feature tests.

**Comment by QuLogic** [comment]
Meson has a built in option for sanitizers (`b_sanitize`); you should not need to handle that yourself.
