### ISSUE TITLE
Ternary if

### ISSUE THREAD

**Issue by RedSkotina** [mesonbuild/meson#538]
Im really want see ternary IF in meson.
1. This is readable
2. This is widespread common operation
3. Reduce size of script

I prefer c ternary if form:
`variable =  (condition) ? true : false`
but are be happy with python form
`variable = true if condition else false`

**Comment by jpakkane** [comment]
Ternary operator is nice, but on the other hand it seems to always invite abuse which is not particularly nice. Also the Python form is just plain confusing, especially to newcomers but also to seasoned developers.

**Comment by RedSkotina** [comment]
maybe disable recursion definition ? all the evil of the construction like `a = x?x:y?z:z?b:c`

**Comment by nirbheek** [comment]
```
variable = true if condition else false
```

Would be quite nice, I think. It's a very common idiom in build files. I have hundreds of lines of:
```
if condition
  conf.set('FOOBAR', true)
endif
```
or
```
if condition
  conf.set('FOOBAR', true)
else
  conf.set('FOOBAR', false)
endif
```

I think removing recursion in this would be a good idea too. It would get rid of all the anti-patterns associated with ternary operators and simplify the implementation.
