### ISSUE TITLE
Google test source build question

### ISSUE THREAD

**Issue by andersdellien** [mesonbuild/meson#5383]
I noticed that when Meson builds Google test from source, it generates object files instead of a  library. This will then result in a linker error if the object file containing the test code provides its own `main()`. (I have some unit test files containing a `main()` function, some without).

Would it make sense to:

- Add an option to `dependency()` (for example 'force-prebuilt') that only looks for prebuilt libraries? (This wouldn't actually resolve the problem, but maybe make the error easier to understand/resolve)

- Modify the Google Test build steps to create a library and then link with that? (That would give the exact same results as linking with the prebuilt library)

Any other ideas/comments? Maybe this is expected behavior?

I'd be happy to submit patches related to this issue if that would be considered useful.

**Comment by jpakkane** [comment]
You can get the dependency with or without main [as explained in the docs](https://mesonbuild.com/Dependencies.html#gtest-and-gmock):

```meson
gtest_nomain_dep = dependency('gtest', main: false)
gtest_withmain_dep = dependency('gtest', main: true)
```

And then use the suitable dependency on the build target depending on whether you want `main` or not.

You can also build your own helper library and dependency and use that. Something like this (not actually tested but should work with some tweaking):

```meson
my_gtest_lib = static_library(dependencies: gtest_dep) # Might need a dummy .cpp file
my_gtest_dep = declare_dependency(link_with: my_gtest_lib,
    dependencies: gtest_dep.partial_dependency(includes: true))
```

GTest is a bit special as a dependency. The reason it is set up like this is that upstream insists (or at least did when the packaging was written) that GTest _must_ be compiled from source every time and that it does _not_ work as a prebuilt library.

**Comment by andersdellien** [comment]
Thanks for the answer.

I read about the `main`-flag and it would certainly be possible to use two dependencies like you describe, however that means I need to match each unit test object file with the correct dependency to avoid problems whereas it "just works" when I link with the prebuilt library.

Your second suggestion looks promising - would it work with both prebuilt/built-from-source GTests?

**Comment by jpakkane** [comment]
It might not work out of the box but could be made to work with some tweaking. Unfortunately "the Google way" is not to make things easy or usable in any environment that does not exactly match their internal workflow. There's not much we can do about that. Sorry.

**Comment by andersdellien** [comment]
I'll try it out - thanks for the support.
