### ISSUE TITLE
Set and get for builtin option 'cargs' and 'cppargs' dont work.

### ISSUE THREAD

**Issue by RedSkotina** [mesonbuild/meson#539]
When i try set `cargs` and `cppargs` via `meson -D` option it is not apply.
http://imgur.com/j1FB9xE

When i take get value of builtin option  `cargs` and `cppargs` via
`message(get_option('cppargs'))` and `message(get_option('cargs'))` i take error :
`Tried to access unknown option "cppargs".`
Probably same for `clinkargs` and `cpplinkargs`

**Comment by rhd** [comment]
Try `c_args` and `cpp_args`

**Comment by RedSkotina** [comment]
same with `-Dcpp_args=-v` and `get_option('cpp_args')`

**Comment by jpakkane** [comment]
#569 fixes the other parts but you still can't define them at `meson` time because it is a bit more complex.

**Comment by nirbheek** [comment]
Isn't the recommended way of doing this with the `CFLAGS` and `CXXFLAGS` environment variables?

**Comment by Hi-Angel** [comment]
> Isn't the recommended way of doing this with the `CFLAGS` and `CXXFLAGS` environment variables?

IMO this looks inconsistent, because `CFLAGS` works in `meson` time, but not in `meson configure` time. `-Dc_args` in turn does not work in `meson` time, but does in `meson configure` time.

**Comment by dcbaker** [comment]
The recommended way is to *not* use `CFLAGS` and `CXXFLAGS`, for that reason and others. However, `meson builddir/ -Dc_args=-v` does work now, so I'm going to close this.
