### ISSUE TITLE
Add a werror: (true|false) kwarg to cc.compiles

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#5399]
Sometimes we need to test if a particular piece of code spews a compiler warning that will be an error with `-Werror` or `/WX` (msvc). Would be nice to have a kwarg for this so that build files don't need to have compiler-specific code.

Was discussed at https://gitlab.gnome.org/GNOME/glib/issues/1777#note_512409.

**Comment by jpakkane** [comment]
Makes sense.

**Comment by xclaesse** [comment]
Made a PR: https://github.com/mesonbuild/meson/pull/10387

**Comment by anarazel** [comment]
This is awesome! I've had to write pretty ugly versions of this for postgres...
