### ISSUE TITLE
Issues with windows defender, esp cloud protection

### ISSUE THREAD

**Issue by barcharcraz** [mesonbuild/meson#5418]
Meson does a few things that make running it on a machine with windows defender cloud delivered protection turned on difficult. Firstly it outputs it's test binaries in %tmp% instead of in the build directory, this seems to bother defender more than outputting in the build directory.

Secondly it builds separate test binaries for each check that it does (as far as I can tell). This means that not only does it have to start a separate process for each build and each test (which is slow on windows), but that each binary ends up being _uploaded to the cloud_ for analysis before meson can run it. This takes on the order of _seconds_. Also because the binaries are small (since they do only one test), they are more likely to be flagged as false positives.

CMake deals with these issues by building just one test binary (in the build directory) with all the checks it needs to do built in. Then it can run it once and get the result of all its tests.

I know this is a situation where the problem is pretty self-inflicted, and I suspect that just changing the directory where the binaries are output could help make it easier to teach windows defender that they are OK.

**Comment by lazka** [comment]
Why can't you add your dev environment directory to the windows defender exclusion list?

**Comment by barcharcraz** [comment]
because meson does not output test executables into the build directory, but rather into %TMPDIR%. I really don't want to add %tempdir% to the exclusions.

**Comment by lazka** [comment]
Ah, good point.

**Comment by scivision** [comment]
A possible least code change option is to use `asyncio-subprocess` within Meson to do this. I have seen network-bound tasks go from O(N) to nearly O(1) for ~1000 operations. Likewise I have seen big speedups for calling FFmpeg's `ffprobe` executable via asyncio-subprocess.

Jussi has previously indicated he would be open to the idea. It would be compatible with Python >= 3.5, using no external modules (no prereqs).

@barcharcraz what compiler / language are you being impacted by the most with the slow down on Windows? A proposal would be to create a simple benchmark, not using Meson, but just calling the compiler many times like Meson does, to measure how much speedup asyncio can give.

**Comment by scivision** [comment]
I made an example of using `asyncio` to call compiler many times. I haven't fully tested it yet, and it needs a little tweaking for Python 3.5. But the concept is shown, as would possibly be useful for Meson in general on any OS platform for possible speedup.

https://github.com/scivision/asyncio-subprocess-examples

**Comment by barcharcraz** [comment]
this might work. Although moving the test executable output into the build directory would also help (I can exclude that).

I noticed this just building glibc. I have no idea what the specific defender policy is that triggers this, but it's one enforced by our IT department.
