### ISSUE TITLE
meson does not detect if python3 distutils.core is missing

### ISSUE THREAD

**Issue by linussn** [mesonbuild/meson#5422]
Running meson on a system without the python3 distutils module, results in:
ERROR: <ExternalProgram 'python3' -> ['/usr/bin/python3']> is not a valid python

It would be nice if meson could detect that.

My ubuntu 19.04 machine did not have python3-distutils installed by default.

**Comment by scivision** [comment]
Knowing exactly which stdlib Meson depends on is useful in general in light of [PEP 594](https://www.python.org/dev/peps/pep-0594/), which focuses on removing some of stdlib.

I wonder what an easy way to reproduce is?  

* Conda
* virtualenv
* python3-minimal

I think it's good to know that in general to help anticipate similar problems in the future if Python stdlib does get stripped down.

**Comment by eli-schwartz** [comment]
Current versions of the `import('python')` module report the error: "is not a valid python or it is missing setuptools".

... Which is admittedly incorrect info. That could be tweaked a bit...

**Comment by eli-schwartz** [comment]
Wording tweaked in #9196

> Knowing exactly which stdlib Meson depends on is useful in general in light of [PEP 594](https://www.python.org/dev/peps/pep-0594/), which focuses on removing some of stdlib.

Not really relevant, that PEP is about removing "dead batteries", which will then no longer exist at all. They're removed because supposedly no one uses them, and really it has nothing to do with the python module specifically --if we used such modules anywhere, meson would fail on new versions of python and we'd need to adapt.

**Comment by lygstate** [comment]
What's this error
```
CMake binary for 1 is cached.
Preliminary CMake check failed. Aborting.
Run-time dependency tizilheaders found: NO (tried pkgconfig and cmake)
Pkg-config binary for 1 is cached.
Determining dependency 'libva' with pkg-config executable '/usr/bin/pkg-config'
env[PKG_CONFIG_PATH]:
Called `/usr/bin/pkg-config --modversion libva` -> 1

CMake binary for 1 is cached.
Preliminary CMake check failed. Aborting.
Run-time dependency libva found: NO (tried pkgconfig and cmake)
Program python3 found: YES (/usr/bin/python3)
Could not introspect Python (['/usr/bin/python3', '/tmp/tmpbvgxrbbn.py']): exit code 1
Program stdout:


Program stderr:

RuntimeError: Permission denied by kysec


../meson.build:1009:0: ERROR: <PythonExternalProgram 'python3' -> ['/usr/bin/python3']> is not a valid python or it is missing distutils

```
