### ISSUE TITLE
How to compile .c files as c++ without "option valid for C/ObjC but not for C++" warning

### ISSUE THREAD

**Issue by justyn** [mesonbuild/meson#5446]
I have a cross-compiled embedded c library which uses the CppUTest unit testing framework.

This framework relies on compiling the c sources as c++ for the tests.

I build the library twice, the second time for the tests using the 'native' option, and pass it the `c_arg '-xc++'`, to force compilation of the .c sources as cpp.

However, this means the library is compiled with an argument for the c standard rather than cpp and so I get the warning:

`cc1plus: warning: command line option ‘-std=gnu99’ is valid for C/ObjC but not for C++`

Can I stop meson passing the c standard to the compiler? Or is there some other approach?

I've tried setting the c_std for the native library to `c++11` but this leads to the error:

ERROR: Value c++11 not one of accepted values

**Comment by dcbaker** [comment]
You have to compile the .c files as c++ or link them with the c++ linker? meson will automatically select the c++ linker when linking c and c++ sources.

**Comment by justyn** [comment]
The library under test (.c files) is built as a native static library.
 
If I allow it to be built as c then at the linking stage the test executable (c++) throws up lots of `undefined reference` errors because it cannot find the library functions.

Prior to using meson, I would use g++ to build the library under test and it would therefore compile the .c sources as c++.

**Comment by QuLogic** [comment]
> If I allow it to be built as c then at the linking stage the test executable (c++) throws up lots of `undefined reference` errors because it cannot find the library functions.

This sounds like you might be missing:
```
#ifdef __cplusplus
extern "C" {
#endif
```
and
```
#ifdef __cplusplus
}
#endif
```
around your C function prototypes.

**Comment by justyn** [comment]
You are right that is a solution, however it is ugly and unfortunate to have to pollute the sources in such a way when in fact they can simply be compiled as c++ for testing, as I have with other build systems.

As I say passing `-xc++` to the c compiler works fine but I need a way to prevent meson from setting the `-std=X` option for c.

**Comment by QuLogic** [comment]
Perhaps it is ugly, perhaps not. You only need to modify the headers (declarations), not the sources (definitions). And it is the correct solution.

Unless you are very careful, C is _not_ a subset of C++ anymore. Compiling as C++ may work now, but it might not work in the future, depending on what changes in the code or what changes in the standards.

**Comment by justyn** [comment]
This is the kind of consideration that is more relevant if actually using a c library as c++.

In this case, we're talking about testing only, under no other circumstances would the library be compiled as c++. It is simply that this common unit test framework for embedded systems, CppUTest, designed explicitly for testing c, is written in c++ and requires the sources to be compiled in this way.

Were the code standards to change, the testing framework would presumably need to be updated to account for this.

**Comment by QuLogic** [comment]
> In this case, we're talking about testing only, under no other circumstances would the library be compiled as c++. It is simply that this common unit test framework for embedded systems, CppUTest, designed explicitly for testing c, is written in c++ and requires the sources to be compiled in this way.

No, it does not. It requires that the C and the C++ sides agree on naming of functions. And the way to tell the C++ side that the C side is using C naming (as opposed to C++ name mangling) is to wrap prototypes in `extern "C"`.

And I think you may have misunderstood me; I was not referring to linking. I was stating that compiling C _source code_ as C++ is not portable, and depending on how it's written, impossible.

**Comment by jpakkane** [comment]
If you only have a few of these files, one solution is to do:

```
--- somefile.cpp ---
#include<somefile.c>
```

**Comment by justyn** [comment]
Thanks both of you for the tips/ideas, I'll consider both.

**Comment by zajo** [comment]
I also need Meson to be able to pass `.c` files through the C++ compiler. My use case is Lua, which is written in C, but if built with a C++ compiler, automatically switches its internal error-handling to `throw`/`catch` instead of `setjmp`/`longjmp`. Without this Lua is unable to properly clean-up in case a C++ callback throws.

In this use case whether or not the `.c` files are compiled as C++ should depend on the main project. The default should be to use the C compiler, but a C++ project should be able to request Meson to use the C++ compiler for that specific dependency.

How do I get this to work with Meson?

**Comment by paulabrudanandrei** [comment]
@justyn Hi, how did you manage to fix this if you remember? I have no control whatsoever over the c files I must use, so I cannot modify them, the build system I have is complex and I can only modify my makefile, where I added
CPPFLAGS  += -fno-permissive
for debugging purposes, but I'm getting this error when it tries to compile some c files

**Comment by justyn** [comment]
I'm sorry @paulabrudanandrei but I cannot remember how/whether I solved this.

**Comment by paulabrudanandrei** [comment]
> I'm sorry @paulabrudanandrei but I cannot remember how/whether I solved this.

I understand, thanks for the reply!
