### ISSUE TITLE
Autotools extensions?

### ISSUE THREAD

**Issue by powerwaremediacore** [mesonbuild/meson#545]
Autotools is good for multiplatform, but requires some infrastructure to run; most of them present in Windows, now with Ubuntu for Windows,  an OSX, but may we want to use their native tools, to develop.

What about to have Autotools macros to call meson commands  to build MSVC or XCode projects files.

This kind are really useful this days.

This kind of Autotools integration will help on help to transit to Mason, and more importantly, will help to be adopted by almost all projects requiring multiplatform project files on native tools; may in the future replacing Autotools.

Most of us, may just wnat

**Comment by powerwaremediacore** [comment]
Most of us don't  want to expend time on learn/rewrite our build system, but extended it to get more and better multiplatform integration with native tools.

**Comment by jpakkane** [comment]
We do not plan to provide any Autotools macros in the foreseeable future.
