### ISSUE TITLE
testlog.json for more than one test is not valid json

### ISSUE THREAD

**Issue by aduskett** [mesonbuild/meson#5458]
Currently, the file testlog.json, which is produced by `meson test` does not create a valid JSON file if there is more than one test.
The current format produced is shown below:

```
{
	"name": "test1",
	"stdout": "test1_stdout\n",
	"result": "OK",
	"duration": 0.4834,
	"returncode": 0,
	"command": ["test_1command"],
	"env": {
            "test1_env": "test1_env"
	},
	"stderr": "test1_stderr\n"
} {
       "name": "test2",
	"stdout": "test2_stdout\n",
	"result": "OK",
	"duration": 0.4834,
	"returncode": 0,
	"command": ["test_2command"],
	"env": {
            "test2_env": "test2_env"
	},
	"stderr": "test2_stderr\n"
}

```

The above code isn't valid JSON. To make this valid JSON, one would have to enclose both tests in brackets and put a comma between each entry. IE:

```
[{
	"name": "test1",
	"stdout": "test1_stdout\n",
	"result": "OK",
	"duration": 0.4834,
	"returncode": 0,
	"command": ["test_1command"],
	"env": {
		"test1_env": "test1_env"
	},
	"stderr": "test1_stderr\n"
}, {
	"name": "test2",
	"stdout": "test2_stdout\n",
	"result": "OK",
	"duration": 0.4834,
	"returncode": 0,
	"command": ["test_2command"],
	"env": {
		"test2_env": "test2_env"
	},
	"stderr": "test2_stderr\n"
}]
```

This can be verified using jsonlint.com.

The invalid JSON makes converting the file to another standard format (such as JUnit) incredibly difficult because standard tools such as pythons json.loads will throw an exception when loading the testlog.json file.

I believe I have tracked down the function `write_json_log` in the file mtest.py:

```
def write_json_log(jsonlogfile: typing.TextIO, test_name: str, result: TestRun) -> None:
    jresult = {'name': test_name,
               'stdout': result.stdo,
               'result': result.res.value,
               'duration': result.duration,
               'returncode': result.returncode,
               'env': result.env,
               'command': result.cmd}  # type: typing.Dict[str, typing.Any]
    if result.stde:
        jresult['stderr'] = result.stde
    jsonlogfile.write(json.dumps(jresult) + '\n')
```

Which does seem to write a valid JSON chunk per write, but doesn't make the distinction between a single test or when writing multiple tests, thus, while each test would be valid JSON when writing multiple tests, the testlog.json file no longer valid.

Hopefully, it's an easy fix, but I am not sure the best way to go about implementing the logic.

Thanks!

Adam

**Comment by aduskett** [comment]
Any eyes on this? It would be helpful if this was fixed.

**Comment by nirbheek** [comment]
I think changing the format would break existing users, but we can start writing out `testlog2.json` which is valid JSON. I'd be happy to review a PR for that.

**Comment by ppaalanen** [comment]
Why not write out JUnit directly?

**Comment by aduskett** [comment]
> Why not write out JUnit directly?

I'm not against it, although non-valid json is bad. At the very least it should be documented.

**Comment by QuLogic** [comment]
If it were one one line each and separated, it _could_ be valid [JSON Lines](http://jsonlines.org/) instead.
