### ISSUE TITLE
No way to build subproject with different warning level?

### ISSUE THREAD

**Issue by strega-nil** [mesonbuild/meson#5466]
I might be wrong, but as far as I can tell, there's no way to build a subproject with different warning levels -- this is unfortunate, since in some cases a subproject might not build under `/W4 /Wx` (`warning_level=3, werror=true`), but I still want to build my main project with those all the warnings, but use a library. In this case, I'm doing advent of code, and depending upon PCRE (which doesn't compile due to conversion warnings).

Thanks!

**Comment by TheQwertiest** [comment]
Related issues/discussions: https://github.com/mesonbuild/meson/issues/5590, https://github.com/mesonbuild/meson/issues/1889, https://github.com/mesonbuild/meson/issues/3001

Regretfully, despite everyone(?) agreeing that the ability to control subproject options is something that is needed in meson, no work has being done on this feature =(
AFAIK, the only person who was willing to work on it was @Ericson2314, but it seems he is no longer participating in meson development :/

**Comment by xclaesse** [comment]
I did most of the work to get per subproject options: https://github.com/mesonbuild/meson/pull/4157

**Comment by TheQwertiest** [comment]
Ugh, sorry >_< 
My memory have let me down...

**Comment by tprk77** [comment]
Well I just got bit by this. I thought I could turn off subproject warning with something like:

```
quazip_proj = subproject('quazip', default_options : ['warning_level=0', 'werror=false'])
```

But that didn't help. Not really sure what I can do here beside turn off warning errors in the parent project, which is very undesirable to me.

Related: mesonbuild/quazip#2

**Comment by meme** [comment]
I tried to same approach as @tprk77 described and here I am. What work needs to be done to resolve this?

**Comment by CairX** [comment]
Was reading the [release notes for 0.56.0](https://mesonbuild.com/Release-notes-for-0-56-0.html) yesterday saw that it should be supported, "Per subproject warning_level option". Tracked it to commit c016401f95bce461a9acefc86bb75884684d9a5f.

I haven't tried it myself yet though.

**Comment by xclaesse** [comment]
It has been fixed a while ago indeed.
