### ISSUE TITLE
xcode 11's clang not recognized

### ISSUE THREAD

**Issue by dankegel** [mesonbuild/meson#5474]
Xcode 11 beta 1 (e.g. on Mac OS 10.15) has changed its spots.

The meson.build
```
project('simple', 'objc')
```
fails with
```
meson.build:1:0: ERROR: Unknown compiler(s): ['cc']
```
in both oldish and latest meson.  Fix easy, coming shortly.

**Comment by dcbaker** [comment]
Fixing this before the release would be nice.
