### ISSUE TITLE
How to regenerate a file, but only if other files have changed?

### ISSUE THREAD

**Issue by phillipjohnston** [mesonbuild/meson#5480]
Hello,

I have written some code that auto-generates a version.c file. Currently, this runs for every compilation attempt b/c of the `build_always_stale` flag (which I mostly want - if I didn't have that, the build timestamp would be out of date after the first one).

I'm curious if there are suggested patterns that can be used to regenerate that file, but only if *other* files have changes (i.e. trigger a regenerate once we determine a need to link). I found a pattern that works for CMake (https://gitlab.com/wolframroesler/version/blob/master/CMakeLists.txt) using a custom "pre-link" command, but haven't been able to figure out a good way to do this in Meson.

**Comment by phillipjohnston** [comment]
For reference, the current approach:

```
version_source = custom_target('gen-version',
	output: 'version.c',
	command: [meson.source_root() + '/build/scripts/make_version.sh', '@OUTPUT@'],
	build_always_stale: true
)

version_subsystem_dep = declare_dependency(
	include_directories: include_directories('.'),
	sources: version_source,
)
```

**Comment by dcbaker** [comment]
I think the easiest way to do this is to make your shell script not write anything if the version hasn't changed, ninja will then not mark `version.c` as dirty, and no compilation will be done. But I might be missing something.

**Comment by phillipjohnston** [comment]
I write a timestamp into the version string, so I do want it to run more often than when the git tag representing my version number changes.

**Comment by dcbaker** [comment]
You can use the `depend_files` keyword argument to `custom_target`, but that would require keeping the list of files up to date. I'm not sure if that's a trade you're willing to make.

**Comment by phillipjohnston** [comment]
Yeah, that's not feasible based on the nature of the project. I can just live with the existing `build_always_stale` behavior.

**Comment by phillipjohnston** [comment]
Thanks for your suggestions @dcbaker
