### ISSUE TITLE
Using nested subprojects without promotion

### ISSUE THREAD

**Issue by jpakkane** [mesonbuild/meson#5487]
There are cases where you'd reasonably want to use a subproject from within a different subproject. This main reason why this is problematic is that if there are multiple versions of the dependency scattered about your source tree, it might pick up the wrong thing by accident. Promotion works but is a bit cumbersome. However suppose we add, say, a new wrap file type that looks something like this (`dep.wrap`):

```
[wrap_sp]
read_from = ['foo', 'bar']
```

This would mean that the dependency dep will be read from `subprojects/foo/subprojects/bar`. This way the used version is unambiguous and, more importantly, will not change by accident, only when changed explicitly. 

For better usability we could add a new command like `meson wrap promote-every-embedded-subproject` that would go through the full directory tree, find all nested subprojects and bring them to the top project. The output would be something like:

```
promoted ['foo', 'bar']
promoted ['baz', 'bub', 'bob']

Conflicts

Subproject 'dupe' is provided by multiple paths:

['foo', 'dupe']
['bar', 'dupe']

To select which version to promote use the command 'XXX YYY ZZZ'.
```

**Comment by eli-schwartz** [comment]
We now (since 0.56) automatically promote for you (with an option toggle for this behavior), and promotion == a special wrap file type called "wrap-redirect" pointing to the real wrap, which seems to be exactly what was proposed.

Closing as solved.
