### ISSUE TITLE
Allow configuration_file() without config.h.meson (or input file)

### ISSUE THREAD

**Issue by tp-m** [mesonbuild/meson#549]
It would be great if we could make it so that we can write config.h files without manually maintaining a config.h.meson input file, which is error prone. Also, autoconf doesn't make us do that ;)

Case in point: defines that determined symbol visibility weren't written into config.h because the config.h.meson file wasn't fully up-to-date, and meson users then wondered what went wrong during linking of some tests that symbols didn't show up etc. But usually such things fail in much more subtle ways.

**Comment by jpakkane** [comment]
How would you define what to write in the file? Suppose you set `FOOBAR` to `"abc"`. What should go in the config file? `#define FOOBAR abc`? `#define FOOBAR "abc"`? `#define HAVE_FOOBAR 1`? If it is missing, how would you know to write `#undef FOOBAR` or `#define FOOBAR 0` or what have you? There seem to be a ton of different ways to do this which are all slightly incompatible with each other.

Also doesn't Autoconf determine a config.h.in by scanning all the sources as the first step? That is humongously slow, we won't be doing that (and parsing C/C++ reliably is a nightmare to boot).

**Comment by nirbheek** [comment]
I don't think we should ever scan sources to generate the `config.h`. That was a terrible idea in the first place. I think we can define the behaviour of `configure_file()` for all  ambiguities:

> Suppose you set FOOBAR to "abc".

If you do `conf.set('FOOBAR', '"abc"')`, then the config file should have `#define FOOBAR "abc"`. i.e., if it's a string, just literally put the string there. This is what we already do anyway. I think this is a full list:

`conf.set('FOOBAR', '"string"')` should become `#define FOOBAR "string"`

`conf.set('FOOBAR', 'string')` should become `#define FOOBAR string`

`conf.set('FOOBAR', true)` should become `#define FOOBAR`

`conf.set('FOOBAR', false)` should become `#undef FOOBAR`

`conf.set('FOOBAR', 1)` should become `#define FOOBAR 1`

`conf.set('FOOBAR', 0)` should become `#define FOOBAR 0`

`conf.set('FOOBAR', "1")` should become `#define FOOBAR "1"` (and so on)

I think that covers all cases?

**Comment by jpakkane** [comment]
Seems quite sensible. How should we expose this? Ideas that come to mind from most favorite to least:

 - `configure_file` without an input file
 - ´cdata.to_header('config.h')`
 - `generate_header(cdata)`

**Comment by nirbheek** [comment]
I personally had imagined it being implemented as the first option: 

>  `configure_file` without an input file

It's quite elegant to do this.
