### ISSUE TITLE
detect_c_or_cpp_compiler cl compiler check return wrong result on non-english windows

### ISSUE THREAD

**Issue by binsys** [mesonbuild/meson#5491]
detect_c_or_cpp_compiler cl compiler check return wrong result on non-english windows

https://github.com/mesonbuild/meson/blob/fa431dddbc45fa539373c932dec650e1e26a9a5c/mesonbuild/environment.py#L779

hardcode ' for (.*)$', in non-english windows,its depend system lcid(1033,2052).
For example, in zh-CHS chinese env,it is "用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.16.27030.1 版".

So we can't compile x86_64,because it force return "x86" if can't find ' for (.*)$' string.

**Comment by binsys** [comment]
workaround
replace ' for (.*)$' with '(:x86|x64|ARM|ARM64)'

**Comment by dcbaker** [comment]
Your workaround is probably a better solution than what we have now anyway.
