### ISSUE TITLE
c_std and cpp_std are not honored when compiling Objective-C/C++ files

### ISSUE THREAD

**Issue by andlabs** [mesonbuild/meson#5495]
```
$ echo 'int main(void){return 0;}' > x.m
$ cat > meson.build
project('test', 'objc', default_options: ['c_std=c99'])
executable('testexe', 'x.m')
```

If you set this up and build with `ninja -v`, you'll see

```
[1/2] cc -Itestexe@exe -I. -I.. -pipe -Wall -Winvalid-pch -g -MD -MQ 'testexe@exe/x.m.o' -MF 'testexe@exe/x.m.o.d' -o 'testexe@exe/x.m.o' -c ../x.m
```

Notice how the c99 flag is not properly applied.

I see `objc_args` was a thing, but changing to `objc_std` does not fix it.

The same happens with `cpp_std` and Objective-C++. This is causing build errors for me as I'm using C++11-only features. (And that project also uses `add_language()` to add `objc` and `objcpp` on macOS only.)

Currently using meson 0.50.1 (through MacPorts) on macOS Sierra with Xcode 9.2.

**Comment by andlabs** [comment]
Oh, forgot to mention: I didn't notice this before because apparently my version of clang automatically defaults to C99 for Objective-C code, but it appears not to for Objective-C++, or even to C++11 (maybe it does to C++03? IDK).

**Comment by andlabs** [comment]
Still happening on 0.51.0. Here's an Objective-C++ reproducer.

```
pietros-mbp:mesonobjcpptest pietro$ echo 'int main(void){return ([]()->int{return 0;})();}' > x.mm
pietros-mbp:mesonobjcpptest pietro$ cat > meson.build
project('test', 'objcpp', default_options: ['cpp_std=c++11'])
executable('testexe', 'x.mm')
```

And the output:

```
pietros-mbp:mesonobjcpptest pietro$ meson setup build
The Meson build system
Version: 0.51.0
Source dir: /private/tmp/mesonobjcpptest
Build dir: /private/tmp/mesonobjcpptest/build
Build type: native build
Project name: test
Project version: undefined
Objective-C++ compiler for the build machine: c++ (clang 9.0.0)
Objective-C++ compiler for the host machine: c++ (clang 9.0.0)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Build targets in project: 1
Found ninja-1.9.0 at /opt/local/bin/ninja
pietros-mbp:mesonobjcpptest pietro$ ninja -v -C build
ninja: Entering directory `build'
[1/2] c++ -Itestexe@exe -I. -I.. -pipe -Wall -Winvalid-pch -Wnon-virtual-dtor -g -MD -MQ 'testexe@exe/x.mm.o' -MF 'testexe@exe/x.mm.o.d' -o 'testexe@exe/x.mm.o' -c ../x.mm
FAILED: testexe@exe/x.mm.o 
c++ -Itestexe@exe -I. -I.. -pipe -Wall -Winvalid-pch -Wnon-virtual-dtor -g -MD -MQ 'testexe@exe/x.mm.o' -MF 'testexe@exe/x.mm.o.d' -o 'testexe@exe/x.mm.o' -c ../x.mm
../x.mm:1:25: error: expected expression
int main(void){return ([]()->int{return 0;})();}
                        ^
../x.mm:1:30: error: expected unqualified-id
int main(void){return ([]()->int{return 0;})();}
                             ^
2 errors generated.
ninja: build stopped: subcommand failed.
```

**Comment by jpakkane** [comment]
If you run `meson configure` in the build dir, does it print an entry for `objcpp_std`?

**Comment by andlabs** [comment]
Nope. All that shows up are

```
  objcpp_args      []            Extra arguments passed to the Objective-C++ compiler
  objcpp_link_args []            Extra arguments passed to the Objective-C++ linker  
```

**Comment by jpakkane** [comment]
Seems like a bug. Either we should make `objc<X>_std` match the corresponding ´<X>_std` or add a std option for Objective-C/C++. Do Objective-C/C++ standards always match the corresponding C/C++ standards or do they have their own version strings? And if yes, is there ever a need to compile Objective-C with a different language version than plain C (and the same for C++)?

**Comment by andlabs** [comment]
Not really; Objective-C and Objective-C++ themselves don't really have concrete compile-time versions, and just inherit whatever versions of C and C++ you ask for. The ideal approach would be to just reuse `c_std` and `cpp_std` with that in mind, but I'll ask a bunch of other Mac coders to comment as well.

**Comment by ePirat** [comment]
@andlabs I would agree that using `c_std` and `cpp_std` seems like what I would expect to happen.

**Comment by alex-tee** [comment]
I think this broke my build on macos: https://dev.azure.com/alex0266/5d39a0cf-3c43-4666-958d-d10497d6b905/_apis/build/builds/2185/logs/8

```
2021-05-14T22:12:13.6630430Z Executing subproject ztoolkit 
2021-05-14T22:12:13.6631210Z 
2021-05-14T22:12:13.6632270Z ztoolkit| Project name: ztoolkit
2021-05-14T22:12:13.6633450Z ztoolkit| Project version: 0.1.2
2021-05-14T22:12:13.6635180Z ztoolkit| C compiler for the host machine: cc (clang 12.0.0 "Apple clang version 12.0.0 (clang-1200.0.32.29)")
2021-05-14T22:12:13.6636500Z ztoolkit| C linker for the host machine: cc ld64 609.8
2021-05-14T22:12:13.6638050Z ztoolkit| Run-time dependency cairo found: YES 1.16.0
2021-05-14T22:12:13.6639190Z ztoolkit| Library m found: YES
2021-05-14T22:12:13.6639950Z 
2021-05-14T22:12:13.6642980Z subprojects/ztoolkit/meson.build:68:2: ERROR: Value "gnu11" (of type "string") for combo option "C language standard to use" is not one of the choices. Possible choices are (as string): "none", "c89", "c99", "c11", "c17".
```

see my comment here: https://github.com/mesonbuild/meson/commit/c54dd63547b030e3d9feee694ec6f49c434f0df8#r50842919
