### ISSUE TITLE
0.51.0 incorrectly thinks arm-none-eabi-gcc can not compile programs due to missing _exit

### ISSUE THREAD

**Issue by mon** [mesonbuild/meson#5496]
I'm using arm-none-eabi-gcc (8-2018-q4-major) with nanolib for an embedded project. As of 0.51.0, the sanitycheckc.c compilation fails (I assume it was never attempted before) due to missing builtins such as `_exit`, `_isatty` etc.

For my actual build, stubs containing these impls are linked in with the final project, but the sanity check doesn't use them, for obvious reasons.

Reproducing on your end _should_ be as simple as running `arm-none-eabi-gcc sanitycheckc.c -o sanitycheckc_cross.exe` and seeing the relevant error.

Am I going about this the wrong way, or is there a way to temporarily disable the sanity check?

**Comment by mon** [comment]
Just went back to 0.50.0 for a triage - it's because 0.51.0 now tries to link the executable, whereas before the sanity check merely compiled. (0.50.0 used `-c`)

Considering my user link flags are missing from the sanity check compile command, I suspect this might not be intentional.

**Comment by avdgrinten** [comment]
As far as I am aware (even though I am not a Meson contributor), this can be fixed by supplying the appropriate link_args in a cross file.

**Comment by mon** [comment]
@avdgrinten unfortunately not - even if link_args _were_ being pulled in (they're not), you cannot provide any link args to find the stubs for the stdlib. They must be compiled in, thus compile only (`-c`) is the versatile solution.

**Comment by jpakkane** [comment]
> 0.51.0 now tries to link the executable, whereas before the sanity check merely compiled. (0.50.0 used -c)

This is an unwanted change. We specifically did not link cross compiled binaries because of this reason. Probably fallout from the build/host changed by @Ericson2314.

**Comment by Ericson2314** [comment]
Hmm I thought took specific steps to ensure we *didn't* link things. Can you try master? https://github.com/mesonbuild/meson/pull/5483/files#diff-330c05ce33750cfbd6229f700e0506bcR472 fixes some other issues with these "configure steps", and in general we can further deduplicate/systematize the code to help prevent bugs.

**Comment by Ericson2314** [comment]
Hmm looking at master between my earlier changes and @dcbaker's changes some stuff might have been lost. I'm hoping https://github.com/mesonbuild/meson/issues/5485 will better allow us to assess what's up.

**Comment by Ericson2314** [comment]
@jpakkane you can assign this one to me.

**Comment by jpakkane** [comment]
Don't you have the powers to assign it yourself? You should, at least.

**Comment by Ericson2314** [comment]
@jpakkane no i don't have that power.

**Comment by jpakkane** [comment]
How about now?

**Comment by mon** [comment]
Just for clarity, yeah master is a no-go too (though I think you've worked that out yourself too...). Version printed to console is `0.51.999` so I assume I pip installed from git correctly.

**Comment by Ericson2314** [comment]
@jpakkane all good!

**Comment by sebastianpfischer** [comment]
Cool! I also look forward for this fix :)
