### ISSUE TITLE
gnome.gtkdoc does not reuse existing files

### ISSUE THREAD

**Issue by ebassi** [mesonbuild/meson#550]
gtk-doc will generate all the files it needs when run first, but if it finds the files it needs it'll use them. This allows library developers to have custom changes to files `$MODULE-sections.txt` and commit them to the repository.

Currently, given the out-of-tree build nature of Meson, the various gtk-doc scripts always start from scratch. It would be good to be able to supply to `gnome.gtkdoc` a list of files that should be used when generating the documentation, so that they get added to the build directory.

**Comment by jpakkane** [comment]
So would that work by having something like a keyword argument `copy_files : 'foobar.txt' which would cause Meson to copy the file from the source dir to the corresponding build dir? Would it need to do anything else?

**Comment by ebassi** [comment]
Something like `copy_files` or `scan_files` (since these are files generatee by `gtkdoc-scan`) would work for that.

There are another couple of missing features in the gtkdoc module, but I'll open separate issues for them — mostly because I want to have a go at fixing them myself. :-)

**Comment by jpakkane** [comment]
There has been some need for a function that copies a given file to the current build directory. Basically a `configure_file` with an empty configuration data. We might add that first and then make gtkdoc use that if it is still deemed a useful shortcut.

**Comment by ebassi** [comment]
This has already been mostly fixed:

 * `$DOC_MODULE-docs.xml` is copied into builddir, if found in srcdir
 * `$DOC_MODULE-sections.txt` is copied into builddir, if found in srcdir
 * `gobject_typesfile` is available for custom `$DOC_MODULE.types`
 * `content_files` and `html_assets` are available for populating HTML results

There's a still a missing bit for `$DOC_MODULE-overrides.txt`, which is used by GLib and GTK+ (among others), but I have a PR for it.

**Comment by ebassi** [comment]
No, I think we can safely close it.
