### ISSUE TITLE
file generated with configure_file() doesn't get recreated

### ISSUE THREAD

**Issue by andy5995** [mesonbuild/meson#5504]
This may be a dup of #1656

* Debian 10
* Ninja 1.8.2
* meson 0.51.0

After I run `ninja clean` and then manually remove the .pc file, it does not get re-created after I run `ninja` again.

It will only get re-generated if I remove the builddir and run `meson builddir`... `ninja`

```
pkgconf = configuration_data()
pkgconf.set('VERSION', meson.project_version())
pkgconf.set('prefix', get_option('prefix'))
pkgconf.set('libdir', get_option('libdir'))
pkgconf.set('includedir', get_option('includedir'))

configure_file(
	input : 'deckhandler.pc.in',
	output : 'deckhandler.pc',
	configuration : pkgconf)
```

**Comment by ePirat** [comment]
I think this is expected as ninja clean removes build files, not files created a configure-time, like the .pc file or other files generated with `configure_file`.

(BTW, you probably know that, but in case you don't: there is a meson pkgconfig module which makes it easy to generate .pc files)

**Comment by andy5995** [comment]
> (BTW, you probably know that, but in case you don't: there is a meson pkgconfig module which makes it easy to generate .pc files)

Yeah, I was helped in IRC regarding that. Thanks @Pirat

**Comment by andy5995** [comment]
Also I notice if you change an option, config.h doesn't get re-created. For example, when using code like

```
if get_option('enable-nls')
  conf.set('ENABLE_NLS', 1)
endif
```
If the config.h file already exists, and the option is changed with

`meson configure -Denable-nls=false`

The config file doesn't get rewritten to reflect the change.

**Comment by andy5995** [comment]
> ~Also I notice if you change an option, config.h doesn't get re-created. For example, when using code like~

Disregard that. operator error.

**Comment by dcbaker** [comment]
When are you expecting it to get recreated? I would expect it to get recreated if meson reconfigures itself possibly, but not otherwise.

**Comment by andy5995** [comment]
ok, yeah, that makes sense. Thanks @dcbaker

**Comment by p3732** [comment]
I ran into this issue too, and I disagree that this behavior makes sense. In my case it means that trying to rebuild a project after running `ninja clean` will fail, as a required input file for a custom target is missing.

Could `configure_file` become a build edge that depends on it's in and output?

**Comment by eli-schwartz** [comment]
The initial report:

> After I run `ninja clean` and then manually remove the .pc file, it does not get re-created

@p3732,

The behavior you are talking about isn't what was reported here. In fact, the behavior you are talking about was explicitly denied by the original report here, which claims that configure_file outputs are NOT removed by `ninja clean`.

I pointed out in the cross-referenced ninja bug report that this should not even be able to happen.

**Comment by p3732** [comment]
You are right Eli, missed that in the initial report, sorry :)
