### ISSUE TITLE
Meson 0.51 breaks Mesa build

### ISSUE THREAD

**Issue by Oschowa** [mesonbuild/meson#5505]
Configuring Mesa (https://gitlab.freedesktop.org/mesa/mesa) with meson 0.51 causes `ninja`
to regenerate the build files in an infinite loop.
Mesa was configured like this, which works fine in earlier meson version:

```
meson "$build_dir" \
    --strip \
    -D buildtype=release \
    -D prefix="$install_dir" \
    -D b_lto=true \
    -D b_ndebug=true \
    -D platforms=drm,x11 \
    -D dri-drivers= \
    -D gallium-drivers= \
    -D vulkan-drivers=amd \
    -D gles1=false \
    -D gles2=false \
    -D opengl=false \
    -D valgrind=false
```

This was tested on Arch Linux, which just recently updated meson to 0.51.

**Comment by dcbaker** [comment]
(mesa dev here), I can't reproduce this. Is the time on your system correct? A lot of ninja reconfigure loops are caused by the system time being in the future.

**Comment by Oschowa** [comment]
Sorry, I seem to have overlooked something in my inital report.
I additionally specified a `--native-file` configure argument to build against a specific version of LLVM.
This is what seems to cause problems only with meson 0.51, my system time is set correctly and it works without the `--native-file` parameter. Using either
```
--native-file <(printf "[binaries]\nllvm-config = '${HOME}/builds/llvm/bin/llvm-config'")
```
or
```
--native-file <(printf "") # use system's llvm
```
causes the reconfigure loop with meson 0.51, but works correctly with earlier versions.

**Comment by dcbaker** [comment]
let me check with a native file

**Comment by Oschowa** [comment]
I just checked, if I use an actual native file, it works fine. It's just the subshell redirection with `<()` which doesn't work anymore.

**Comment by dcbaker** [comment]
Ah, it's using the bash process substitution causing the problem.

It's likely related to 94ba53c6b6eb44f32e4d155b3f7eeb5a68bfec83, which creates a proper ninja dependency on the native file. The same problem has existed for cross files for longer. We'd have to special case when the cross/native file is not a "real" file. I think there are other caveats here too, we'd like need to write the contents of the pipe into meson's private store and rely on that.

**Comment by shmerl** [comment]
@jpakkane: can you please make an updated release with this fix? Thanks!
