### ISSUE TITLE
meson.build:620:2: ERROR: Unknown compiler(s): [['clang']] on Mac OS when building glib

### ISSUE THREAD

**Issue by albertmichaelj** [mesonbuild/meson#5506]
I am using Homebrew on Mac OS to try to upgrade glib which using meson in the build process. I had to cancel the upgrade partway through, and now it won't build with the following error:
```
meson.build:620:2: ERROR: Unknown compiler(s): [['clang']]
```
I've opened an issue at homebrew/homebrew-core, but they suggested I open an issue here as well. The issue there (which has more information) is [here](https://github.com/Homebrew/homebrew-core/issues/41071#issue-457470583)

**Comment by jpakkane** [comment]
What does `clang` resolve to in that broken case and how is it different from the working case?

**Comment by albertmichaelj** [comment]
`clang` resolves to `/use/bin/clang` as expected in both cases. I cannot tell how it is different in between the two cases. Something happened with the cancellation that has broken things in a way I can't determine.

**Comment by ggeorgieev** [comment]
I am also experiencing that problem, same error appears.
My installation is in custom directory (my user directory).

**Comment by albertmichaelj** [comment]
It's not a custom directory thing (I confirmed this because I set up a new homebrew installation in a different directory). Up to this point, I believe it's because I had to cancel the installation of `glib`. Did you cancel the installation as well @ggeorgieev?

I'm pretty sure it's not a conflict with an existing package because I reinstalled everything into a new homebrew installation that I had in the previous installation, and I can still install glib just fine.

**Comment by albertmichaelj** [comment]
@ggeorgieev Just to give you a path forward, I think the only solution that seems to work is going to be reinstalling all of homebrew which is what I'm going to do. I opened an issue with homebrew/brew pointing out this bug, but a maintainer there was extremely hostile and dismissive. I do not think that this is fundamentally a problem with meson, and I think it's a bug somewhere in brew. However, my issue has been closed and locked over there by the maintainer, so I have no path forward to help with an official fix. I wish you all the best if you choose to open a bug report with them.

@jpakkane Given that I think this is likely a brew bug and not a meson bug (given that a fresh homebrew installation works just fine), I am fine if you close this issue. I will leave it open since you may view it as something you would like to look into, and I'm happy to debug in any way that is helpful to you. However, if you don't think it's likely to be productive for meson, please close the issue.

**Comment by albertmichaelj** [comment]
meson upgraded today to 0.51.0, and the build error went away. It looks like I was wrong about this being a brew issue (though I don't know why the build was successful on a fresh install). I have found this issue to be very perplexing.

I'm going to close this.
