### ISSUE TITLE
gnome.gtkdoc does not support installing additional images

### ISSUE THREAD

**Issue by ebassi** [mesonbuild/meson#551]
If the API reference we're building has images that have to be installed alongside the HTML, we have to do:

```
html_images = [
  ...
]

install_data('images', sources: html_images, install_dir: 'share/gtk-doc/html/graphene-1.0')
```

Which requires knowing the installation directory for gtk-doc files. Since `gnome.gtkdoc()` already knows the location, having an additional `html_images` key would avoid manual installation.

**Comment by jpakkane** [comment]
So something like this:

    gnome.gtkdoc(..., extra_install_files : ['bob.png', 'other.png'])

Which would go to the root of the html dir (`html/graphene-1.0`)? Is there need to put files in a subdir or is root always ok?

**Comment by ebassi** [comment]
Yep, the root html dir is okay.

**Comment by jpakkane** [comment]
Thinking about this further, people might have a need to do other stuff with the output dir. Maybe we could add a method to tell the directory so you could do something like this:

    install_data('images',
      sources: html_images,
      install_dir: gnome.get_gtkdoc_html_dir('graphene-1.0'))

This would probably be simpler to implement to boot.

**Comment by ebassi** [comment]
Sounds good to me.
