### ISSUE TITLE
No dependency if comment follows fortran module statement

### ISSUE THREAD

**Issue by sujona** [mesonbuild/meson#5513]
Meson 0.51.0. If there is a comment after the fortran module declaration like
```
module nice !
```
this module is not added as a dependency for another source-file with `use nice`.

**Comment by QuLogic** [comment]
cc @scivision

**Comment by scivision** [comment]
Thank you @sujona I was not able to reproduce this issue on Meson master branch. I did add a test case for this in #5516

**Comment by scivision** [comment]
@sujona if you could give more details, perhaps we could reproduce the issue. Thanks

**Comment by sujona** [comment]
Hi, I thought it was that simple but the error only comes up when the preprocessor is also involved and there are a few files to compile in parallel. I managed to make minimal non-working example. It will work once in a while just because of a "lucky" compile order. 

src/program.f90:
```
program h
    use help
    implicit none
    call ROUTINE
end
```
src/help.f90:
```
module help !
    implicit none
contains
subroutine test
    print*, STRING
end subroutine
end module
```
meson.build:
```
project('qtip','fortran',default_options : ['bindir=bin'], version : '0')
ff = meson.get_compiler('fortran')
subdir('src')
executable('run1.x',src,fortran_args : ['-cpp','-DSTRING="HEJ1"','-DROUTINE=TEST','-fopenmp'])
```
src/meson.build:
```
src = ['src/help.f90', 'src/fak1.f90', 'src/program.f90', 'src/fak2.f90', 'src/fak3.f90']
```
Then there are the empty files src/fak?.f90 as listed.

**Comment by sujona** [comment]
Even if the compile works multiple time which it has done now for me, you can check in build.ninja that "| run1.x@exe/help.mod" is not present as a dependency for program.f90 when the "!" is present.

**Comment by sujona** [comment]
Actually judging only from the presence of "| run1.x@exe/help.mod" in build.ninja all of the "complexity" in the example is unimportant but adds enough "disorder" for the build to fail, only the "!" seem to matter for the dependency. In the below example the compile always goes through, as far as I have tested, but the dependency is absent: 

program.f90:
```
program h
    use help
    implicit none
    call test
end
```
help.f90:
```
module help ! this is the comment
    implicit none
contains

subroutine test
    print*, "test"
end subroutine
end module
```
meson.build:
```
project('qtip','fortran')
src = ['src/program.f90', 'src/help.f90']
executable('run1.x',src)
```

**Comment by sujona** [comment]
@scivision I added some more detail above.

**Comment by sujona** [comment]
@scivision And since the build.ninja is written by Meson I  did `rm -r build` and `meson build` between attempts at compiling with `ninja` or checking the `build.ninja` for the dependency.

**Comment by scivision** [comment]
Thank you, I should have looked at build.ninja as the problem was apparent for even a trivial example.  Sorry about that! I updated #5516 to fix this issue by correcting the regex patterns.

Thanks again @sujona

**Comment by sujona** [comment]
No problem @scivision, thanks for taking care of it!
