### ISSUE TITLE
Are docs on libdir's bugginess outdated?

### ISSUE THREAD

**Issue by federicomenaquintero** [mesonbuild/meson#5514]
[Builtin-options.md](docs/markdown/Builtin-options.md) mentions,

> libdir is automatically detected based on your platform, but the implementation is currently buggy on Linux platforms.

It links to #2038 which is now closed.  I'm not sure if this means the bug is gone and the docs should be updated :)

**Comment by dcbaker** [comment]
Ah, yes they are slightly outdated. I should have updated that when I fixed that bug :)

**Comment by federicomenaquintero** [comment]
Perfect, this makes a lot more sense now.  Thanks!
