### ISSUE TITLE
Convenience operators for the array type

### ISSUE THREAD

**Issue by ebassi** [mesonbuild/meson#552]
Porting Graphene I noticed that the array type is lacking a couple of operators that would reduce the amount of code:

  * a `join()` function/operator/method, to turn an array into a single string — e.g. the pythonesque
```
# this
graphene_simd = [ 'sse2', 'gcc', 'neon', 'scalar' ]
conf.set('GRAPHENE_SIMD', ' '.join(graphene_simd))

# instead of
graphene_simd = [ 'sse2', 'gcc', 'neon' ]
simd = ''
foreach s: graphene_simd
  simd += '@0@ '.format(simd)
simd += 'scalar' # add the last element
conf.set('GRAPHENE_SIMD', simd)
```

 * an `in` operator, to find an element in an array — e.g.
```
# this
has_sse = 'sse2' in graphene_simd
has_gcc = 'gcc' in graphene_simd

# instead of
has_sse = false
has_gcc = false
foreach s: graphene_simd
  if s == 'sse2'
    has_sse = true
  endif
  if s == 'gcc'
    has_gcc = true
  endif
endforeach
```

**Comment by tp-m** [comment]
+1 for both (esp. the _in_ operator)

**Comment by jpakkane** [comment]
The latter we already have, arrays have a `.contains()` method. I'll add the join thingy soon.
