### ISSUE TITLE
IDE Backends are not working in Meson release 0.51.0

### ISSUE THREAD

**Issue by squidfarts** [mesonbuild/meson#5521]
I tried to use the Xcode backend after updating to using the latest version of Meson and it doesn’t work anymore, I also tried it on my Windows computer for Visual Studio 2017 and same result.  The ninja backend works.

**Comment by dcbaker** [comment]
The xcode backend is known to be incomplete. At this point I wonder if it would be better to delete it or at least print a really big warning.

What error are you seeing for VS?

**Comment by squidfarts** [comment]
Something like this:

Microsoft Windows [Version 10.0.17134.829]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\Mike>cd Developer\templates\c\c-example

C:\Users\Mike\Developer\templates\c\c-example>meson setup build --backend vs2017
The Meson build system
Version: 0.51.0
Source dir: C:\Users\Mike\Developer\templates\c\c-example
Build dir: C:\Users\Mike\Developer\templates\c\c-example\build
Build type: native build
Project name: c-example
Project version: 0.1.0
C compiler for the build machine: gcc (gcc 8.2.0 "gcc (MinGW.org GCC-8.2.0-3) 8.2.0")
C compiler for the host machine: gcc (gcc 8.2.0 "gcc (MinGW.org GCC-8.2.0-3) 8.2.0")
Build machine cpu family: x86
Build machine cpu: x86
Build targets in project: 1
Traceback (most recent call last):
  File "C:\Users\Mike\AppData\Roaming\Python\Python37\site-packages\meson-0.51.0-py3.7.egg\mesonbuild\mesonmain.py", line 127, in run
    return options.run_func(options)
  File "C:\Users\Mike\AppData\Roaming\Python\Python37\site-packages\meson-0.51.0-py3.7.egg\mesonbuild\msetup.py", line 240, in run
    app.generate()
  File "C:\Users\Mike\AppData\Roaming\Python\Python37\site-packages\meson-0.51.0-py3.7.egg\mesonbuild\msetup.py", line 158, in generate
    self._generate(env)
  File "C:\Users\Mike\AppData\Roaming\Python\Python37\site-packages\meson-0.51.0-py3.7.egg\mesonbuild\msetup.py", line 210, in _generate
    intr.backend.generate(intr)
  File "C:\Users\Mike\AppData\Roaming\Python\Python37\site-packages\meson-0.51.0-py3.7.egg\mesonbuild\backend\vs2010backend.py", line 179, in generate
    projlist = self.generate_projects()
  File "C:\Users\Mike\AppData\Roaming\Python\Python37\site-packages\meson-0.51.0-py3.7.egg\mesonbuild\backend\vs2010backend.py", line 413, in generate_projects
    self.gen_vcxproj(target, str(projfile_path), proj_uuid)
  File "C:\Users\Mike\AppData\Roaming\Python\Python37\site-packages\meson-0.51.0-py3.7.egg\mesonbuild\backend\vs2010backend.py", line 771, in gen_vcxproj
    vscrt_type = self.environment.coredata.base_options['b_vscrt']
KeyError: 'b_vscrt'

C:\Users\Mike\Developer\templates\c\c-example>Microsoft Windows [Version 10.0.17134.829]
'Microsoft' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Mike\Developer\templates\c\c-example>(c) 2018 Microsoft Corporation. All rights reserved.
2018 was unexpected at this time.

C:\Users\Mike\Developer\templates\c\c-example>
C:\Users\Mike\Developer\templates\c\c-example>C:\Users\Mike>cd Developer\templates\c\c-example
'C:\Users\Mike' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Mike\Developer\templates\c\c-example>
C:\Users\Mike\Developer\templates\c\c-example>C:\Users\Mike\Developer\templates\c\c-example>meson setup build --backend vs2017
'C:\Users\Mike\Developer\templates\c\c-example' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Mike\Developer\templates\c\c-example>The Meson build system
'The' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Mike\Developer\templates\c\c-example>Version: 0.51.0
'Version:' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Mike\Developer\templates\c\c-example>Source dir: C:\Users\Mike\Developer\templates\c\c-example
'Source' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Mike\Developer\templates\c\c-example>Build dir: C:\Users\Mike\Developer\templates\c\c-example\build
'Build' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Mike\Developer\templates\c\c-example>Build type: native build
'Build' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Mike\Developer\templates\c\c-example>Project name: c-example
'Project' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Mike\Developer\templates\c\c-example>Project version: 0.1.0
'Project' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Mike\Developer\templates\c\c-example>C compiler for the build machine: gcc (gcc 8.2.0 "gcc (MinGW.org GCC-8.2.0-3) 8.2.0")
'C' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Mike\Developer\templates\c\c-example>C compiler for the host machine: gcc (gcc 8.2.0 "gcc (MinGW.org GCC-8.2.0-3) 8.2.0")
'C' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Mike\Developer\templates\c\c-example>Build machine cpu family: x86
'Build' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Mike\Developer\templates\c\c-example>Build machine cpu: x86
'Build' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Mike\Developer\templates\c\c-example>Build targets in project: 1
'Build' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Mike\Developer\templates\c\c-example>Traceback (most recent call last):
'Traceback' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Mike\Developer\templates\c\c-example>  File "C:\Users\Mike\AppData\Roaming\Python\Python37\site-packages\meson-0.51.0-py3.7.egg\mesonbuild\mesonmain.py", line 127, in run
C:\Users\Mike\AppData\Roaming\Python\Python37\site-packages\meson-0.51.0-py3.7.egg\mesonbuild\mesonmain.py,: cannot open `C:\Users\Mike\AppData\Roaming\Python\Python37\site-packages\meson-0.51.0-py3.7.egg\mesonbuild\mesonmain.py,' (No such file or directory)
line:                                                                                                        cannot open `line' (No such file or directory)
127,:                                                                                                        cannot open `127,' (No such file or directory)
in:                                                                                                          cannot open `in' (No such file or directory)
run:                                                                                                         cannot open `run' (No such file or directory)

C:\Users\Mike\Developer\templates\c\c-example>    return options.run_func(options)
'return' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Mike\Developer\templates\c\c-example>  File "C:\Users\Mike\AppData\Roaming\Python\Python37\site-packages\meson-0.51.0-py3.7.egg\mesonbuild\msetup.py", line 240, in run
C:\Users\Mike\AppData\Roaming\Python\Python37\site-packages\meson-0.51.0-py3.7.egg\mesonbuild\msetup.py,: cannot open `C:\Users\Mike\AppData\Roaming\Python\Python37\site-packages\meson-0.51.0-py3.7.egg\mesonbuild\msetup.py,' (No such file or directory)
line:                                                                                                     cannot open `line' (No such file or directory)
240,:                                                                                                     cannot open `240,' (No such file or directory)
in:                                                                                                       cannot open `in' (No such file or directory)
run:                                                                                                      cannot open `run' (No such file or directory)

C:\Users\Mike\Developer\templates\c\c-example>    app.generate()
'app.generate' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Mike\Developer\templates\c\c-example>  File "C:\Users\Mike\AppData\Roaming\Python\Python37\site-packages\meson-0.51.0-py3.7.egg\mesonbuild\msetup.py", line 158, in generate
C:\Users\Mike\AppData\Roaming\Python\Python37\site-packages\meson-0.51.0-py3.7.egg\mesonbuild\msetup.py,: cannot open `C:\Users\Mike\AppData\Roaming\Python\Python37\site-packages\meson-0.51.0-py3.7.egg\mesonbuild\msetup.py,' (No such file or directory)
line:                                                                                                     cannot open `line' (No such file or directory)
158,:                                                                                                     cannot open `158,' (No such file or directory)
in:                                                                                                       cannot open `in' (No such file or directory)
generate:                                                                                                 cannot open `generate' (No such file or directory)

C:\Users\Mike\Developer\templates\c\c-example>    self._generate(env)
'self._generate' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Mike\Developer\templates\c\c-example>  File "C:\Users\Mike\AppData\Roaming\Python\Python37\site-packages\meson-0.51.0-py3.7.egg\mesonbuild\msetup.py", line 210, in _generate
C:\Users\Mike\AppData\Roaming\Python\Python37\site-packages\meson-0.51.0-py3.7.egg\mesonbuild\msetup.py,: cannot open `C:\Users\Mike\AppData\Roaming\Python\Python37\site-packages\meson-0.51.0-py3.7.egg\mesonbuild\msetup.py,' (No such file or directory)
line:                                                                                                     cannot open `line' (No such file or directory)
210,:                                                                                                     cannot open `210,' (No such file or directory)
in:                                                                                                       cannot open `in' (No such file or directory)
_generate:                                                                                                cannot open `_generate' (No such file or directory)

C:\Users\Mike\Developer\templates\c\c-example>    intr.backend.generate(intr)
'intr.backend.generate' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Mike\Developer\templates\c\c-example>  File "C:\Users\Mike\AppData\Roaming\Python\Python37\site-packages\meson-0.51.0-py3.7.egg\mesonbuild\backend\vs2010backend.py", line 179, in generate
C:\Users\Mike\AppData\Roaming\Python\Python37\site-packages\meson-0.51.0-py3.7.egg\mesonbuild\backend\vs2010backend.py,: cannot open `C:\Users\Mike\AppData\Roaming\Python\Python37\site-packages\meson-0.51.0-py3.7.egg\mesonbuild\backend\vs2010backend.py,' (No such file or directory)
line:                                                                                                                    cannot open `line' (No such file or directory)
179,:                                                                                                                    cannot open `179,' (No such file or directory)
in:                                                                                                                      cannot open `in' (No such file or directory)
generate:                                                                                                                cannot open `generate' (No such file or directory)

C:\Users\Mike\Developer\templates\c\c-example>    projlist = self.generate_projects()
'projlist' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Mike\Developer\templates\c\c-example>  File "C:\Users\Mike\AppData\Roaming\Python\Python37\site-packages\meson-0.51.0-py3.7.egg\mesonbuild\backend\vs2010backend.py", line 413, in generate_projects
C:\Users\Mike\AppData\Roaming\Python\Python37\site-packages\meson-0.51.0-py3.7.egg\mesonbuild\backend\vs2010backend.py,: cannot open `C:\Users\Mike\AppData\Roaming\Python\Python37\site-packages\meson-0.51.0-py3.7.egg\mesonbuild\backend\vs2010backend.py,' (No such file or directory)
line:                                                                                                                    cannot open `line' (No such file or directory)
413,:                                                                                                                    cannot open `413,' (No such file or directory)
in:                                                                                                                      cannot open `in' (No such file or directory)
generate_projects:                                                                                                       cannot open `generate_projects' (No such file or directory)

C:\Users\Mike\Developer\templates\c\c-example>    self.gen_vcxproj(target, str(projfile_path), proj_uuid)
'self.gen_vcxproj' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Mike\Developer\templates\c\c-example>  File "C:\Users\Mike\AppData\Roaming\Python\Python37\site-packages\meson-0.51.0-py3.7.egg\mesonbuild\backend\vs2010backend.py", line 771, in gen_vcxproj
C:\Users\Mike\AppData\Roaming\Python\Python37\site-packages\meson-0.51.0-py3.7.egg\mesonbuild\backend\vs2010backend.py,: cannot open `C:\Users\Mike\AppData\Roaming\Python\Python37\site-packages\meson-0.51.0-py3.7.egg\mesonbuild\backend\vs2010backend.py,' (No such file or directory)
line:                                                                                                                    cannot open `line' (No such file or directory)
771,:                                                                                                                    cannot open `771,' (No such file or directory)
in:                                                                                                                      cannot open `in' (No such file or directory)
gen_vcxproj:                                                                                                             cannot open `gen_vcxproj' (No such file or directory)

C:\Users\Mike\Developer\templates\c\c-example>    vscrt_type = self.environment.coredata.base_options['b_vscrt']
'vscrt_type' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Mike\Developer\templates\c\c-example>KeyError: 'b_vscrt'
'KeyError:' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Mike\Developer\templates\c\c-example>

**Comment by dcbaker** [comment]
Yeah, that seems really bad.

**Comment by dcbaker** [comment]
I'm assigning this to myself to help me remember to look at it tomorrow. I'm running out of time today and I don't have time to get out my windows machine now.

**Comment by squidfarts** [comment]
Anything on what the problem is with Visual Studio backends?

**Comment by dcbaker** [comment]
Oh, oh, oh. You're trying to use GCC with the visual studio backend. That isn't supported (yet), is that what you're actually trying to do?

**Comment by squidfarts** [comment]
Not relay what I was trying to do, i'm new to Windows 10 and I am moving projects over from Mac.  I thought that by passing vs2017 it would generate a Visual Studio 2017 solution.  Was it assuming to use the GCC compiler that hole time?
How can make the backend work.

**Comment by jpakkane** [comment]
On Windows you need to launch the configuration process from the Visual Studio developer command prompt. VS requires a bunch of envvar & other settings to work, they are only set in the dev tool command terminal.

**Comment by dcbaker** [comment]
You have a couple of choices. if you install ninja the ninja backend is supported with all windows compilers (clang, gcc, clang-cl, intel, and MSVC). If you want to use MSVC with the visual studio backend then the easiest thing to do is open a cmd prompt for the visual studio you want and run meson in that. They're usually named something like "x64 Native Tools for Visual Studio 2017"

**Comment by dcbaker** [comment]
I think we've narrowed this down to a support ticket, and it's been answered. I'm going to go ahead and close this, but feel free to reopen if you have more questions.
