### ISSUE TITLE
Trying to get Meson to work on Raspberry Pi 3 

### ISSUE THREAD

**Issue by squidfarts** [mesonbuild/meson#5533]
I tried to use Meson on my Raspberry pi 3 and it builds, but Meson printed something about that CPU family not being recognized and Ninja does not know what to do.  Ninja tries to build my simple example one hundred times and the result is nothing but a normal "failed to build message".

**Comment by dcbaker** [comment]
did you get a message like:
```
Unknown CPU family {!r}, please report this at
https://github.com/mesonbuild/meson/issues/new with the
output of `uname -a` and `cat /proc/cpuinfo`
```
what version of meson do you have and what OS are you running?

**Comment by squidfarts** [comment]
Yes that one.

**Comment by dcbaker** [comment]
which meson do you have, and what does `uname -a` say and what is `cat /proc/cpuinfo` say?

**Comment by squidfarts** [comment]
On raspberry i'm using Meson version 49.999 I am going to upgrade it around lunch time.

![image1](https://user-images.githubusercontent.com/42789598/59945283-f95a8e00-941b-11e9-9c2d-91d41fe85a77.jpeg)

**Comment by dcbaker** [comment]
hmmmm. I only have a Pi2---somewhere. that looks like it's probably just returning some value we're not expecting.

**Comment by scivision** [comment]
I have most of the Raspberry Pi models. I have worked with this section of the Meson code before as well. I will try to take a look.

**Comment by squidfarts** [comment]
So found time to up-grade to Meson 0.51.0 and now things are working on Raspberry pi3.  Was previously using 0.49.999.

**Comment by scivision** [comment]
OK great there was recently work done by me and others in that section, so glad the issue is resolved. Please reopen if issues arise.
