### ISSUE TITLE
D Language method 'dub' for decencies not working.

### ISSUE THREAD

**Issue by squidfarts** [mesonbuild/meson#5534]
I am trying to integrate Dub projects with my Meson D projects so I don't have to write Meson support for all D libraries I com-across and this happens.  

NOTE: This is with a more complex example that depends 'urld'.

Last login: Fri Jun 21 00:08:31 on ttys000
Michaels-MacBook-Pro:~ shnitzel$ cd Developer/templates/d/project/
Michaels-MacBook-Pro:project shnitzel$ meson setup build
The Meson build system
Version: 0.51.0
Source dir: /Users/shnitzel/Developer/templates/d/project
Build dir: /Users/shnitzel/Developer/templates/d/project/build
Build type: native build
Project name: d_project
Project version: 0.1.0
D compiler for the build machine: dmd (dmd 2.086.1 "DMD64 D Compiler v2.086.1")
D compiler for the host machine: dmd (dmd 2.086.1 "DMD64 D Compiler v2.086.1")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found DUB: /usr/local/bin/dub (DUB version 1.15.0, built on Jun 15 2019)
ERROR: urld found but it wasn't compiled with dmd
Run-time dependency urld found: NO 

meson.build:57:0: ERROR: Dependency "urld" not found

A full log can be found at /Users/shnitzel/Developer/templates/d/project/build/meson-logs/meson-log.txt
Michaels-MacBook-Pro:project shnitzel$

**Comment by jpakkane** [comment]
Are you sure your dub deps are built with `dmd`? The error message claims they are not. (Dub may default to gdc or ldc on some platforms)

**Comment by squidfarts** [comment]
I’m not sure what Dub is or isn’t doing.  How can I make it use dmd?

**Comment by Elronnd** [comment]
Pass dub the flag `--compiler=dmd`

**Comment by squidfarts** [comment]
Tried passing the compiler flag and I still got an error.
