### ISSUE TITLE
Trying to set c_std to 18 and got an error

### ISSUE THREAD

**Issue by squidfarts** [mesonbuild/meson#5539]
I am trying to set ‘c_std’ to version 18 and it printed an error about that version not being valid.  The document on built-in options states that it is.

However the value “c17” is working.

Would this be fixed at some point?

**Comment by scivision** [comment]
Hi @squidfarts I get the same error with Meson v0.50. However, it has been fixed with Meson &ge; v0.51
Try upgrading to the latest Meson release and please reopen this issue if it's still a problem. Thanks!

**Comment by scivision** [comment]
Here was the MWE:

meson.build
```meson
project('C18 Standard', 'c', default_options: ['c_std=c18'])

exe = executable('C18program', 'main.c')
test('C18program', exe)
```

main.c
```c
int main(void){ return 0; }
```

**Comment by squidfarts** [comment]
But way do I get this?

Michaels-MacBook-Pro:~ shnitzel$ cd Developer/templates/c/
.DS_Store       example.zip     executable.zip  project.zip
Michaels-MacBook-Pro:~ shnitzel$ cd Developer/templates/c/example/
Michaels-MacBook-Pro:example shnitzel$ meson setup build
The Meson build system
Version: 0.51.0
Source dir: /Users/shnitzel/Developer/templates/c/example
Build dir: /Users/shnitzel/Developer/templates/c/example/build
Build type: native build
Project name: c_example
Project version: 0.1.0
C compiler for the build machine: cc (clang 10.0.1 "Apple LLVM version 10.0.1 (clang-1001.0.46.4)")

meson.build:39:0: ERROR: Value "c18" for combo option is not one of the choices. Possible choices are: "none", "c89", "c99", "c11", "c17", "gnu89", "gnu99", "gnu11", "gnu17".

A full log can be found at /Users/shnitzel/Developer/templates/c/example/build/meson-logs/meson-log.txt
Michaels-MacBook-Pro:example shnitzel$ 

I used this:
https://github.com/squidfarts/c-example.git

**Comment by scivision** [comment]
OK! Sorry about that I should have asked more about the setup. Thanks!

**Comment by scivision** [comment]
Yes, this initially appears to be particular to Clang compiler (not a compiler bug, just doesn't happen with GCC). With Windows and Clang 8.0 and the MWE above I get error:

> C compiler for the build machine: clang (clang 8.0.0 "clang version 8.0.0 (tags/RELEASE_800/final)")
> meson.build:1:0: ERROR: Value "c18" for combo option is not one of the choices. Possible choices are: > "none", "c89", "c99", "c11", "c17", "gnu89", "gnu99", "gnu11", "gnu17".

**Comment by scivision** [comment]
@squidfarts I believe #5560 will solve this issue. Thanks again.

**Comment by squidfarts** [comment]
Your welcome 🙂

**Comment by squidfarts** [comment]
Sorry to bother you again but the c_std=18 is still showing an error.  The same one.

**Comment by scivision** [comment]
OK so you have AppleClang 10.0.1 there were some suggested changes to #5590 to streamline logic. Maybe I accidentally didn't cover this case with the present logic. Thanks!
