### ISSUE TITLE
gettext() does not allow keywords to be specified

### ISSUE THREAD

**Issue by LRN** [mesonbuild/meson#554]
If one uses helpers or wrappers for gettext library, one needs to tell `xgettext` about the keywords.

For example, if i use glib gettext helpers, i need to pass `--keyword=_', '--keyword=N_', '--keyword=C_:1c,2', '--keyword=NC_:1c,2', '--keyword=g_dngettext:2,3'` (`intltoolize` adds appropriate magic to autotools-based buildsystem, so with autotools you don't need to add these yourself) to `xgettext` for it to be able to find all the macro and function invocations.

One should probably read [xgettext man](https://www.gnu.org/software/gettext/manual/html_node/xgettext-Invocation.html) and see which commandline arguments should be supported by `gettext()` in meson. Or maybe it's easier to just allow flags to be passed to `xgettext` as-is (the same way CFLAGS are passed to C compiler). Note that `xgettext` is not a compiler- or platform-specific tool (AFAIK; though its counterpart gettext *library* *can* be part of libc, IIRC; Wikipedia mentions Sun gettext, but i don't know whether anyone uses its tools anymore, if it had any; it might not have supported .pot/.po/.mo at all and used different file formats altogether, for all i know), so abstracting away all of its arguments doesn't make much sense, not for portability reasons (i.e. there's no MSVC- or Windows-specific gettext program that expects `/kw foo` instead of `--keyword=foo`). IMHO.

**Comment by jpakkane** [comment]
Allowing raw args to be passed directly seems like the most feasible solution.

**Comment by jpakkane** [comment]
Can you try #557 to see if it works for you?

**Comment by LRN** [comment]
It works for me (there's another problem, but i'll file a separate issue for it).

Someone should probably update the manual to reflect that `gettext()` is in `i18n` module and that it has `args` argument.
