### ISSUE TITLE
Custom file dependencies?

### ISSUE THREAD

**Issue by Elronnd** [mesonbuild/meson#5548]
Hello.

I want to be able to say "recompile file A whenever file B has changed."  How can I do that?

**Comment by dcbaker** [comment]
Can you give a more specific use case? We already do this automatically in some cases.

**Comment by scivision** [comment]
Do you mean like CMake add_dependencies()?

Where foo.c and bar.c are not linked or built together, but nonetheless foo.c must be built before bar.c

**Comment by Elronnd** [comment]
@scivision I'm not sure; that looks like it does something slightly different

@dcbaker think of it like a header file.  When foo.h gets modified, foo.c has to be rebuilt.  I have a language (d) that can load arbitrary files as data at compile-time, and also I have it so that every build the git commit hash gets written to a file.  So, every time the file with the commit hash is changed, the file that includes it should get rebuilt.

**Comment by dcbaker** [comment]
how are you generating the git hash? If you're using a `custom_target` or `vcs_tag` you can add that as a source dependency and meson should do what you want.

**Comment by Elronnd** [comment]
Ahh, I wasn't aware of those; I was using `run_command`.  `vcs_tag` looks like a can of worms that I'd rather not open, but it looks like I can do `custom_target('git-commit', output: ['src/.commit_hash.txt', 'src/file_loading_hash.d'], command: ['sh', '-c', 'git rev-parse --short HEAD > src/.commit_hash.txt'])`; so then it'll recompile file_loading_hash.d?

**Comment by dcbaker** [comment]
that custom target will only create one file, but you're output has two, but otherwise basically yes. I'd avoid the use of shell redirects and use `capture` instead:

```meson
git_txt = custom_target(
  'git-sha',
  command : [find_program('git'), 'rev_parse', '--short', 'HEAD'],
  output : ['git-sha.txt'],
  capture : true,
)

library(
  'mylib',
  ['lib.d', git_txt],
)
```

**Comment by Elronnd** [comment]
Ahh, I see.  I don't want the whole thing to be rebuilt when the hash changes, though, just that one file; how do I do that?

**Comment by dcbaker** [comment]
Meson doesn't have per-file dependency granularity. You either get to live with the whole target being rebuilt or use a `static_library`

**Comment by Elronnd** [comment]
Ok

**Comment by eli-schwartz** [comment]
>  I have a language (d) that can load arbitrary files as data at compile-time

gcc can output "depfiles" for .c files which depend on .h files, using Makefile syntax. ninja supports reading those depfiles and converting them to ninja's internal dependency format, and meson lets you specify a "depfile" argument to e.g. custom_target() or generator().

Does the D programming language support generating depfiles which reference the arbitrary compile-time data you mention? If so, meson could/should use this and you won't need to do anything, if not, that sounds like a feature request for the dlang compiler.

**Comment by Elronnd** [comment]
I just checked - it looks like it *does* support that.  It would be slightly inefficient, though; if any dependency of file X has changed, then you have to recompute *all* dependencies of file X.  Imagine this: file X depends on file Y, and file Y tells X to import file Z.  So X depends on Y and Z.  Now Y changes to tell X to import Q, which means that now if Q has changed, X has to be  recompiled.


Also it currently segfaults if I run it on my project but that can be fixed.

**Comment by eli-schwartz** [comment]
How is that inefficient? Isn't that the textbook case where you *want* to recompile X?

Inefficient would be if due to all that, you suddenly need to recompile the unrelated files A, C, F, G, and M.
