### ISSUE TITLE
'c_std=c18' is not working!

### ISSUE THREAD

**Issue by squidfarts** [mesonbuild/meson#5559]
I am using Meson version 0.51.0 was previously using version 0.50.0 and both version print an error like this:
The test was ran on Mac.

Michaels-MacBook-Pro:~ shnitzel$ cd Developer/templates/c/example/
Michaels-MacBook-Pro:example shnitzel$ meson setup build
The Meson build system
Version: 0.51.0
Source dir: /Users/shnitzel/Developer/templates/c/example
Build dir: /Users/shnitzel/Developer/templates/c/example/build
Build type: native build
Project name: c_example
Project version: 0.1.0
C compiler for the build machine: cc (clang 10.0.1 "Apple LLVM version 10.0.1 (clang-1001.0.46.4)")

meson.build:39:0: ERROR: Value "c18" for combo option is not one of the choices. Possible choices are: "none", "c89", "c99", "c11", "c17", "gnu89", "gnu99", "gnu11", "gnu17".

A full log can be found at /Users/shnitzel/Developer/templates/c/example/build/meson-logs/meson-log.txt
Michaels-MacBook-Pro:example shnitzel$

I used this:
https://github.com/squidfarts/c-example.git

**Comment by scivision** [comment]
Thanks! Continuing the discussion on #5539
