### ISSUE TITLE
sdl2 wrap does not provide opengl on Windows

### ISSUE THREAD

**Issue by janesma** [mesonbuild/meson#5562]
SDL provides a platform abstraction for window systems, enabling cross-platform implementations using OpenGL.

I used Meson's SDL wrap to download and compile SDL, which solved a nice dependency problem for my project.  It links against the built library and runs correctly on Linux.

On Windows, the compile-time dependencies are satisfied by the SDL built with Meson's wrap.  However, the resulting DLL does not provide the OpenGL run-time dependency.  When calling SDL_CreateWindow, SDL returns the following error:

    No OpenGL support in video driver

My project runs correctly on Windows when I replace Meson's wrap-built DLLs with the DLLs from http://libsdl.org/download-2.0.php

Minimal project that can be used to reproduce the bug:

    https://gitlab.freedesktop.org/majanes/simple-triangle

**Comment by QuLogic** [comment]
Seems like something that should be reported on [the SDL wrap repo](https://github.com/mesonbuild/sdl2).

**Comment by janesma** [comment]
thanks for the pointer!
