### ISSUE TITLE
cross compiler needs_exe_wrapper is ignored

### ISSUE THREAD

**Issue by dcbaker** [mesonbuild/meson#5567]
I tried to compile mesa with meson 0.51 with an x86_64 -> x86 cross compile, and it fails because one of our generators is host compiled, which will run just fine but meson asserts and dies instead. Looks pretty trivial, I'll fix it.

Related to #5509

**Comment by facorreia** [comment]
I am using the latest version and I am still having this issue cross-compiling glib

My cross_file.txt
####################################################
[binaries]
c = 'linux-gnueabi-gcc'
cpp = 'linux-gnueabi-g++'
ar = 'linux-gnueabi-ar'
nm = 'linux-gnueabi-nm'
ld = 'linux-gnueabi-ld'
strip = 'linux-gnueabi-strip'

[host_machine]
system = 'linux'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'


[properties]
sizeof_int = 4
sizeof_wchar_t = 4
sizeof_void* = 4

alignment_char = 1
alignment_void* = 4
alignment_double = 4

has_function_printf = true

needs_exe_wrapper = 'true'

c_args = ['-Dlibmount=false','-Dselinux=false']
c_link_args = []

**Comment by dcbaker** [comment]
Please open a new bug with the error message.

**Comment by facorreia** [comment]
#5818
