### ISSUE TITLE
Meson 0.51.0 Xcode backend is not working.

### ISSUE THREAD

**Issue by squidfarts** [mesonbuild/meson#5570]
The backend for Xcode doesn’t work for some reason.

I’m using Meson version 0.51.0.
![A331EFB7-3CAC-4949-8B24-E7C3FA00FEFF](https://user-images.githubusercontent.com/42789598/60283549-3e6c3d80-98be-11e9-8d84-91364a16e373.jpeg)

**Comment by dcbaker** [comment]
I've figured out what's going on. Patch incoming.

**Comment by dcbaker** [comment]
@squidfarts can you try the linked MR?

**Comment by squidfarts** [comment]
I’m am away from my computer for two days, up North with the fam will absolutely try out the merge request as soon as I get back!

Thank you.

**Comment by squidfarts** [comment]
Tried the Xcode back end and it works again.  Cant whait for Meson 0.51.1.
