### ISSUE TITLE
Run CI tests on an older distribution

### ISSUE THREAD

**Issue by shoogle** [mesonbuild/meson#5576]
Meson's CI tests currently [run on Ubuntu 18.10](https://github.com/mesonbuild/meson/blob/3f280a81fde8a7771924159d6e1bda7ec364970c/ciimage/Dockerfile#L1). This has caused problems for[ people using Meson on older systems](https://github.com/AppImage/AppImageKit/issues/205#issuecomment-495994235), as they run into issues specific to their system that were not picked up in the CI tests.

For maximum compatibility, it would be better to test on an older distribution.

- __Testing a program on a new system does not tell you if it will work on older systems.__
    - The program might use features that are not available on old systems.
- __But if you test on an old system it is usually safe to assume it will work on newer systems too.__
    - New systems aim to preserve backwards compatibility with old systems.

This means you should **test on the oldest system that you want to support**, and restrict yourself to only using features that are available on that system.

Ideally, the CI tests would run on the oldest version of Ubuntu that is still supported by Canonical, which is currently Ubuntu 16.04 LTS. This is the version that is [used by default](https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment) for continuous integration services like Travis CI, so it would be good if Meson used what everybody else is using.

If it's too much effort to get Meson working on 16.04 then perhaps you could switch to Ubuntu 18.04 (the most recent LTS) and just not upgrade for a while.

**Comment by jpakkane** [comment]
> restrict yourself to only using features that are available on that system

Well yes and no. We also need to support all the latest features of the tools that we have. For example many Gnome tools have added new features and functionality (often at our request) to make things faster, smoother and more reliable. If we were to only support functionality that is available on the oldest LTS, it would mean that we could only support functionality that has existed for 5-7 years in the wild. This is neither reasonable nor acceptable.

In the ideal world we would run our test suite both on an LTS distro as well as a new one. Unfortunately we don't have the resources for that, our CI pipeline is already fairly monstrous.

**Comment by shoogle** [comment]
> We also need to support all the latest features of the tools that we have.

That's true.

> In the ideal world we would run our test suite both on an LTS distro as well as a new one. Unfortunately we don't have the resources for that, our CI pipeline is already fairly monstrous.

How about a core subset of the tests? Would you accept a PR to set up such a test, or would you reject that too on the grounds that it would create expectation for you to maintain it?

**Comment by jpakkane** [comment]
Our test suite should run as-is without any changes on modern distros as well as on LTS ones. It should detect which features are available and either downgrade features or skip the test. If this is not happening that is a bug and we welcome patches fixing those.

**Comment by jon-turney** [comment]
Closed by #6500?

**Comment by mensinda** [comment]
Essentially yes. I also plan to add an old Debian at some point. So closing.
