### ISSUE TITLE
Meson 0.51 overwrites source folder and fails

### ISSUE THREAD

**Issue by rom1v** [mesonbuild/meson#5579]
Since 0.51, meson does not find `subdir` project:

    meson.build:7:4: ERROR: Non-existent build file 'app/meson.build'

(this is possibly related to https://github.com/mesonbuild/meson/issues/5502)

But the worst is that it totally removes the content of `app/` to write `config.h` (instead of writing into `builddir/app/`).

See https://github.com/Genymobile/scrcpy/issues/627#issuecomment-507044876

**Comment by jpakkane** [comment]
I tried to replicate this but could not. What are the exact steps you take to make this occur?

**Comment by rom1v** [comment]
Thank you for your attempt to replicate.

So I tried to replicate it by myself after cloning the current master of meson repo (I initially reported the problem based on logs reported by a user on Mac OS), but I could not reproduce either.

Now, it seems it [works](https://github.com/Genymobile/scrcpy/issues/627#issuecomment-507059496) for them, so I am not sure there is a problem with meson at all. So for now, I'm closing.

Sorry for the inconvenience.
