### ISSUE TITLE
Qt5 modules should not always require uic

### ISSUE THREAD

**Issue by michaelolbrich** [mesonbuild/meson#5582]
Qt5 can be built without `uic` (if widgets are disable). This is quite common for embedded use-cases with QtQuick only applications.

Currently meson fails because it always requires `uic`. I'm not sure what the correct fix is.
Maybe handle this like `lrelease`?

**Comment by jpakkane** [comment]
It should probably only try to look up uic once the build definition contains an ui build rule.

**Comment by terjr** [comment]
Is there a workaround for this?

**Comment by xclaesse** [comment]
This could be a nice little contribution, lrelease is already optional. See https://github.com/mesonbuild/meson/blob/master/mesonbuild/modules/qt.py#L40 and https://github.com/mesonbuild/meson/blob/master/mesonbuild/dependencies/ui.py#L225
