### ISSUE TITLE
ccache cannot work on dist builds

### ISSUE THREAD

**Issue by zmike** [mesonbuild/meson#5583]
Due to how the dist build is implemented in Meson, it will always result in ccache being unable to work.

The reason for this is the forced use of `mkdtemp` for directories within the `check_dist` function (in `dist.py`). The source is unpacked into `$tmpdir/tmp$string` which is random and thus unable to produce cache hits for subsequent builds. If I am trying to do e.g., a CI dist build, this is not ideal since it makes the build very long.

There are two possible solutions I've come up with which could solve the issue:
* Add a `DISTBUILDDIR` (or similar) environment variable which is used instead of `mkdtemp` during a dist build; this directory would take the place of the `mkdtemp` directories and would not be deleted when the build stopped
* Add a `TMPBUILDSTRING` (or similar) environment variable which is used in place of the random part of the tempdir string (resulting in e.g., /tmp/tmp$string); this directory can still be created and deleted normally, or even deleted if it already exists since we can assume this should only be used for meson dist builds

Other solutions would be great too, as long as ccache becomes usable.

**Comment by jpakkane** [comment]
A simpler solution would be to always do the test in a specific directory under `meson-private`.

**Comment by zmike** [comment]
Er do you maybe mean do the dist in a specific directory in `meson-private`? This would also work as long as it was a consistent path.

I had thought that using `mkdtemp` was intentional/fundamental for this build.

**Comment by jpakkane** [comment]
Can you test if the linker MR fixes it for you?

**Comment by zmike** [comment]
Yup, back to 100% hit rate. Thanks!
