### ISSUE TITLE
llvm is always linked as static, even when dynamic requested and available

### ISSUE THREAD

**Issue by dcbaker** [mesonbuild/meson#5586]
This appears to be a regression between 0.50.1 and 0.51.0

**Comment by dcbaker** [comment]
It looks like this might actually be more serious, I think dependency caching is broken.

**Comment by dcbaker** [comment]
Nope, not as bad, the cmake finder method seems to ignore the static keyword and always return a static link.

**Comment by dcbaker** [comment]
This seems to only happen when the cmake finder is used, not with the config-tool one. I'd like to switch the order for 0.51.1 so that config-tool is the default and fix the cmake finder for 0.52 Does that sound reasonable?

**Comment by mensinda** [comment]
Wouldn't that cause problems with multiple installed LLVM versions? For instance, if the config tool dependency can't find the newest LLVM version but an older version exists? I only vaguely remember the exact problems with the config tool dependency backend, so sorry if I am wrong here.

I will try to add static / dynamic support to the CMake backend, but I am not sure if CMake even supports switching between the static and dynamic versions. I am not sure if this will ever be supported...

**Comment by dcbaker** [comment]
Linking against libllvm-X.Y is a hard requirement for mesa, so we either need to figure it out, or not use cmake when dynamic linking is requested.

I did some looking last night, and I think for dynamic linking we need a completely separate path (if you have libllvm and not separate shared libraries like gentoo builds).

I gotta say, I'm even less impressed by LLVM's dependency story than I was when we were only wrapping llvm-config. I'm almost to the point of trying to get pkg-config files into llvm so we can just make all of this go away.

**Comment by dcbaker** [comment]
I think cmake and llvm-config both have the same problem (in regards to multiple versions installed), upstream really expects one of two scenarios: 1) you vendor llvm into your project, 2) you have a single system wide version (android, apple, etc)

**Comment by jpakkane** [comment]
There was a PR about this that was merged IIRC. Is this now fixed for 0.51.1 or does it need more work?

**Comment by nirbheek** [comment]
Specifically https://github.com/mesonbuild/meson/pull/5589.

**Comment by nirbheek** [comment]
Fixed in https://github.com/mesonbuild/meson/commits/0.51
