### ISSUE TITLE
0.51: Cross Compilation Suddenly Broken for Previously Working Project

### ISSUE THREAD

**Issue by phillipjohnston** [mesonbuild/meson#5588]
After updating to 0.51.0, I cannot cross-compile my project. No other changes have been made.

```
The Meson build system
Version: 0.51.0
Source dir: /Users/pjohnston/src/ea/embedded-framework/src/stdlibs/libcpp
Build dir: /Users/pjohnston/src/ea/embedded-framework/src/stdlibs/libcpp/buildresults
Build type: cross build
Project name: libcpp
Project version: undefined
C++ compiler for the build machine: c++ (clang 10.0.1 "Apple LLVM version 10.0.1 (clang-1001.0.46.4)")

meson.build:1:0: ERROR: Compiler arm-none-eabi-c++ can not compile programs.

A full log can be found at /Users/pjohnston/src/ea/embedded-framework/src/stdlibs/libcpp/buildresults/meson-logs/meson-log.txt
```

Here's the log:

[meson-log.txt](https://github.com/mesonbuild/meson/files/3347606/meson-log.txt)

Here's the cross file:

[nrf52840.txt](https://github.com/mesonbuild/meson/files/3347608/nrf52840.txt)

**Comment by phillipjohnston** [comment]
It seems that I was previously relying on this behavior to skip the `_exit` sanity check problem:

```
# Keep this set, or the sanity check won't pass
needs_exe_wrapper = true
```

I don't see any mention to that changing in the release notes. Did I miss something else?

**Comment by dcbaker** [comment]
This is a regression in 0.51, it should be fixed in #5510 in 0.51.1

**Comment by phillipjohnston** [comment]
Great, thank you.

**Comment by phillipjohnston** [comment]
Confirmed that top of tree got me past this issue.

**Comment by dcbaker** [comment]
cool. 0.51.1 is due out very soon. I'm going to go ahead and close this issue.
