### ISSUE TITLE
Verbose mode for install step

### ISSUE THREAD

**Issue by Jehan** [mesonbuild/meson#5631]
I had a case where the `ninja install` step failed but it did not write on which line it failed. It looks like the `Installing XXX to YYY` line is written after the installation succeeds. Also it doesn't even write what command was run to install (if any?).

Note: I know this is a call to `ninja`, but I have been told `ninja install` calls meson internally. If mistaken, sorry!

Anyway conclusion: it was hard to diagnose what part failed and why and I had to guess from meson files. Could there be a verbose mode for the install step? I want to run for instance `ninja install -v` or something (similar to a `make install V=1`) which tells what it was trying to do and how before failing, to help debug build/install issues.

**Comment by Salamandar** [comment]
As a start, `meson install` should report every info it has when `meson install` fails : which file, which target directory, and the stderr if the error comes from a subprocess.

**Comment by scopatz** [comment]
This would be great to have!

**Comment by eli-schwartz** [comment]
`ninja install` runs a python program, specifically `meson install`, which handles all installation. No subprocesses are run, other than custom `meson.add_install_script()` content which should print failing script logs as needed.

From a quick look at mesonbuild/minstall.py I cannot see any particular things which are lacking good explanations for failure cases. If you can think of any, please re-open.
