### ISSUE TITLE
Support CMake Interface libraries

### ISSUE THREAD

**Issue by mcneish1** [mesonbuild/meson#5634]
[Some](https://github.com/skypjack/entt) header-only C++ projects use CMake [interface libraries](https://cmake.org/cmake/help/latest/command/add_library.html#interface-libraries), which [do not currently appear to be supported by meson](https://github.com/mesonbuild/meson/blob/5bd21a96b89efc5fe96025398151dcbce34345ac/mesonbuild/cmake/interpreter.py#L71).

It would be nice if they were supported.

Adding `'INTERFACE_LIBRARY': 'static_library',` to `target_type_map` works, but creates an extra empty library.

`build_target` or `declare_dependency` seem like better choices than `static_library`, but neither work as just a one-line edit. `build_target` requires `target_type`, which is some effort to plumb in and doesn't have a `none` option, and `declare_dependency` gets passed the normal name and (empty) sources, which it can't use.

**Comment by mensinda** [comment]
Yeah, a one-line edit will definitely not be enough to support header-only subprojects. The problem is that the `0.50.*` CMake subprojects implementation only relies on the CMake server introspection API. However, CMake doesn't expose anything besides the name of the library.

Thus, supporting interface libraries will require a similar solution to `add_custom_command` (see #5574), but supporting them should be possible.

**Comment by mensinda** [comment]
Now, looking at [entt](https://github.com/skypjack/entt) specifically, supporting interface libraries alone won't solve the problem here. This is because entt uses [generator expressions](https://github.com/skypjack/entt/blob/master/CMakeLists.txt#L75), which are a real pain to parse in meson.

**Comment by samvv** [comment]
Too bad this is so difficult to resolve. I was planning to add [fmtlib](https://github.com/fmtlib/fmt/) to my meson build system and this has forced me to switch back to (ugly) CMake.

**Comment by mensinda** [comment]
It is already resolved in master (basic generator expressions and interface libraries). I haven't tested it with fmtlib, but it should work. If it doesn't, then it is a bug :smiley: .

**Comment by samvv** [comment]
Sorry for the late response, but I just wanted to say how awesome this is! Thank you @mensinda!
