### ISSUE TITLE
C++ project is not linking with Unity.

### ISSUE THREAD

**Issue by squidfarts** [mesonbuild/meson#5649]
[Unity](https://github.com/ThrowTheSwitch/Unity) is a testing framework written in C.  I was previously using it for both C and  C++ and now it’s having problems.  I upgraded to Meson version 0.51.1 release.

Refrains [Project ](https://github.com/squidfarts/cpp-project.git).

**Comment by QuLogic** [comment]
It would help if you actually stated what the error was.

**Comment by squidfarts** [comment]
I just solved the issue.  Turns-out I forgot `library()` we'll build a shared library by default.  Now it works for both C and C++ projects.
