### ISSUE TITLE
Possible issue in installation documentation

### ISSUE THREAD

**Issue by buphomet** [mesonbuild/meson#5651]
From [Getting meson here ](https://mesonbuild.com/Getting-meson.html) the below is indicated

"
Meson is available in the Python Package Index and can be installed with pip3 install meson which requires root and will install it system-wide.

Alternatively, you can use pip3 install --user meson which will install it for your user and does not require any special privileges. This will install the package in ~/.local/, so you will have to add ~/.local/bin to your PATH.
"
On my system:

`
Linux metal 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u3 (2019-06-16) x86_64 GNU/Linux
`
The second installation method seems to work while the first does not.

**Comment by scivision** [comment]
This is probably normal. If one is using system Python on a Unix-like system, admin/sudo/root is typically required. So therefore the `--user` pip option allows install to the user's home directory

**Comment by buphomet** [comment]
> This is probably normal. If one is using system Python on a Unix-like system, admin/sudo/root is typically required. So therefore the --user pip option allows install to the user's home directory

It is pretty obvious that admin/sudo/root is required. In fact, this quite clear just from my quote above why someone has to repeat that is quite question-able.

In fact, your whole comment is redundant and does nothing to solve the issue where these instructions do not install meson on debian.

`
buphomet@metal:~$ sudo pip3 install meson
[sudo] password for buphomet: 
Collecting meson
  Using cached https://files.pythonhosted.org/packages/18/ba/0f3d6aef4ba484f59e4d3a00678c4322295976ec1db35c5929a8c1901099/meson-0.51.1.tar.gz
Building wheels for collected packages: meson
  Running setup.py bdist_wheel for meson ... done
  Stored in directory: /root/.cache/pip/wheels/56/ce/4f/5ed3e8d6a5e2b826d3625bfe32c7205e4c67043817d955cc00
Successfully built meson
Installing collected packages: meson
Successfully installed meson-0.51.1
buphomet@metal:~$ meson

ERROR: Must specify at least one directory name.
buphomet@metal:~$ whereis meson
meson: /usr/local/bin/meson
buphomet@metal:~$ 
`
The only reported installation is that that had been done by with `--user` specified.

Thanks for closing the issue, nonetheless, you are the best!

**Comment by jpakkane** [comment]
Based on that log it did install it just fine. Perhaps the error message is not the greatest but it should work. Can you try `meson --help`?

The problem with writing installation instructions on Linux is that there are so many different distributions each of which does things differently. Unfortunately there is not, or indeed can not, be a single step guidance of "do X and it will work".

**Comment by buphomet** [comment]
It honestly would not be surprising if this issue was routed in the repo itself.

It held me up for several hours hence my thought that reporting/posting it here would be worthwhile.

**Comment by jpakkane** [comment]
Meson is available in Debian so you can get it with `sudo apt install meson`. This is the recommended and easiest way to get it. Unfortunately if you are using something older than buster, the version is probably too old to be useful. :(

**Comment by buphomet** [comment]
The looks like stretch, yes and again, yes, the package they have was too old to be useful.
