### ISSUE TITLE
Meson CMake dependency lookup ignores CMAKE_PREFIX_PATH after recent changes

### ISSUE THREAD

**Issue by solson** [mesonbuild/meson#5666]
After upgrading from 0.49.2 to 0.50.1, my build which relies on a CMake dependency lookup started failing to find the dependency. By using `git bisect` on the Meson repo I found that the lookup starts failing with [this PR](https://github.com/mesonbuild/meson/pull/4914), specifically [this commit](https://github.com/mesonbuild/meson/pull/4914/commits/cdc338b74337e29c903bb73b61dc6f22877208e7) (cc @mensinda). I've also tested on 0.51.0 and master and the problem persists.

As per that PR, Meson now checks if the expected CMake modules exist before actually invoking CMake, except I believe it fails to consider all the places CMake itself would look. Specifically, as I understand it, CMake looks in the paths of the [`CMAKE_PREFIX_PATH`](https://cmake.org/cmake/help/latest/variable/CMAKE_PREFIX_PATH.html) environment variable, which I believe is automatically set by my dependency handling system and was key to finding the dependencies when I used 0.49.2. In newer versions, Meson bails out and never gives CMake the chance to run and check those paths.

I can seemingly work around this by configuring with `-Dcmake_prefix_path=$(echo "$CMAKE_PREFIX_PATH" | tr : ,)`, but this feels a bit redundant. It's unclear to me whether it's intended design, given that Meson is happy to read other env vars like CXX/LDFLAGS without passing them through `-D` flags, for example. Previously, Meson's CMake support was really "plug and play" and didn't require any thought beyond what would make CMake itself work in the normal way, and I think it would be ideal to preserve that property.

Let me know if you need any more specific details.

**Comment by mensinda** [comment]
No, this wasn't a design decision, I just forgot to add it. This should probably also go into 0.51.2.

**Comment by mensinda** [comment]
Should be fixed with #5673

**Comment by nirbheek** [comment]
Fixed with #5673

**Comment by c72578** [comment]
> 
> I can seemingly work around this by configuring with `-Dcmake_prefix_path=$(echo "$CMAKE_PREFIX_PATH" | tr : ,)`

@solson, do you need the colon ':' as a list separator in `CMAKE_PREFIX_PATH`?

**Comment by solson** [comment]
@c72578 I'm not very experienced with CMake, but that is the format I observed on my machine. Weirdly, checking the CMake docs now, they describe it as a semicolon-separated list, but I checked again and it's colon-separated in my situation.

**Comment by c72578** [comment]
@solson, thanks for checking. A related PR has been prepared (#6126).
