### ISSUE TITLE
Cherry Pick Fortran fixes for 0.51.2?

### ISSUE THREAD

**Issue by scivision** [mesonbuild/meson#5668]
PR #5542  fixes several Fortran projects for me, by correcting the faulty Fortran module/submodule scan regexes.

Broken:
```sh
git checkout 0.51.1
```
is fixed by:
```sh
git cherry-pick 9c337465e37 
```
is it possible to consider this for inclusion in 0.51.2?

**Comment by nirbheek** [comment]
LGTM, I've added the PR to 0.51.2
