### ISSUE TITLE
Meson Boost detection x64 in windows 10 searches for x32 in Meson 0.51

### ISSUE THREAD

**Issue by germandiagogomez** [mesonbuild/meson#5675]
**Steps to reproduce**

1. Open x64 Native tools command prompt in windows 10
2. set BOOST_ROOT=C:\path\to\boost
3. Issue a meson build in the root of your project.

**Expected result**

Search for libraries with ABI boost_xxxx_...x64-mt...

**Actual result**

What is being searched is the x32 boost libraries.

**Notes**

I am using meson installed from pip and python 3.7 64 bits in Windows Home

**Comment by nirbheek** [comment]
I tested this with `test cases/frameworks/1 boost` and this is what I see in the logs:

```
Couldn't find library 'boost_thread-vc141-mt-gd-x64-1_70' for boost module 'thread'  (ABI tag = '-vc141-mt-gd-x64-1_70')
Couldn't find library 'boost_system-vc141-mt-gd-x64-1_70' for boost module 'system'  (ABI tag = '-vc141-mt-gd-x64-1_70')
Couldn't find library 'boost_thread-mt' for boost module 'thread'  (ABI tag = '-mt')
Couldn't find library 'boost_system-mt' for boost module 'system'  (ABI tag = '-mt')
Boost library directory is C:\local\boost_1_70_0\lib64-msvc-14.1
```

I'm using the x64 native tools prompt for VS2017 on Windows 10, and I `set BOOST_ROOT=C:\local\boost_1_70_0`.

**Comment by germandiagogomez** [comment]
The error disappeared after upgrading to 0.51.1 (I was using 0.51.0). It does not use c++17 though even if I give default arguments to the project
