### ISSUE TITLE
type annotations in meson - possible performance issue

### ISSUE THREAD

**Issue by amitdo** [mesonbuild/meson#5677]
https://github.com/mesonbuild/meson/search?q=annotations&type=Commits

https://docs.python.org/3/whatsnew/3.7.html#pep-563-postponed-evaluation-of-annotations

>The advent of type hints in Python uncovered two glaring usability issues with the functionality of annotations added in PEP 3107 and refined further in PEP 526:
>  *  annotations could only use names which were already available in the current scope, in other words they didn’t support forward references of any kind; and
>  * annotating source code had adverse effects on startup time of Python programs.

**Comment by xclaesse** [comment]
Interesting, and invocation time could be pretty critical, given that for each script, ninja re-invoke meson. I personally also find it a LOT more difficult to read the code, but it's probably just me because I'm not really used to "modern" python.

**Comment by nirbheek** [comment]
Is there an easy way to have strip-hints run during `setup.py` installation?

**Comment by amitdo** [comment]
@nirbheek, I don't know. I found this package after a quick Google search.

Here's the GitHub repo:
https://github.com/abarker/strip-hints

**Comment by nirbheek** [comment]
I measured the impact of hints before and after by running `strip-hints` on meson. There is no difference at all. Other sources say that the overhead is merely in doing `import typing`, which on my system measures to 8ms. This is completely negligible.
