### ISSUE TITLE
Some dependencies are not checked correctly when version change

### ISSUE THREAD

**Issue by arteymix** [mesonbuild/meson#568]
To enable some specific features, I check various version of the same library and issue preprocessor definitions. It seems like Meson only evaluate the first `dependency` and assume that all other are already satisfied.

In the following build definition, if the system satisfies `gio-2.0 (>=2.34)`, but not `gio-2.0 (>=2.44)`, the latter will be satisfied anyway, generating incorrect flags.

```python
vala_defines = []

# provide 'GLib.ApplicationCommandLine.get_stdin'
if dependency('gio-2.0', version: '>=2.34', required: false).found()
vala_defines += '--define=GIO_2_34'
endif

# support parsing of CLI arguments
if dependency('gio-2.0', version: '>=2.40', required: false).found()
vala_defines += '--define=GIO_2_40'
endif

# provide 'OutputStream.write_all_async'
if dependency('gio-2.0', version: '>=2.44', required: false).found()
vala_defines += '--define=GIO_2_44'
endif
```

Here's the Travis build that fail https://travis-ci.org/valum-framework/valum/builds/133612286

It corresponds to the following tree: https://github.com/valum-framework/valum/commit/c08cce5642bd7ce082ddd3a813238e248d4b0942

**Comment by jpakkane** [comment]
You should not use the version requirement to determine what the system has available. Newest trunk has now version number exposed as well as version compare string operators. Docs updated soon, but tl/dr:

    gio_dep = dependency('gio-2.0', version : '>=minimum required')

    if gio_dep.version().version_compare('>=2.3.4')
      do_something
    endif

**Comment by arteymix** [comment]
:+1: 

I look forward for the 0.32 then :)

**Comment by nirbheek** [comment]
Alternatively, you can do a version compare in the reverse order:
```
vala_defines = []

# provide 'OutputStream.write_all_async'
if dependency('gio-2.0', version: '>=2.44', required: false).found()
  vala_defines += ['--define=GIO_2_44']
# support parsing of CLI arguments
elif dependency('gio-2.0', version: '>=2.40', required: false).found()
  vala_defines += ['--define=GIO_2_40']
# provide 'GLib.ApplicationCommandLine.get_stdin'
elif dependency('gio-2.0', version: '>=2.34', required: false).found()
  vala_defines += ['--define=GIO_2_34']
endif
```

**Comment by arteymix** [comment]
@nirbheek That could be a temporary solution, but still, flags must be repeated in your example

**Comment by nirbheek** [comment]
How so? There's no repetition of flags in the defines array that I can see. You'd have to do something like this with `version_compare()` anyway.

**Comment by arteymix** [comment]
@nirbheek It would be essentially the same, but my example is broken and Meson does not seem to reevaluate `dependency` expressions when it's already satisfied.

To obtain the same behaviour, you have to repeat flags as follow:

```
vala_defines = []

# provide 'OutputStream.write_all_async'
if dependency('gio-2.0', version: '>=2.44', required: false).found()
  vala_defines += ['--define=GIO_2_44', '--define=GIO_2_40', '--define=GIO_2_34']
# support parsing of CLI arguments
elif dependency('gio-2.0', version: '>=2.40', required: false).found()
  vala_defines += ['--define=GIO_2_40', '--define=GIO_2_34']
# provide 'GLib.ApplicationCommandLine.get_stdin'
elif dependency('gio-2.0', version: '>=2.34', required: false).found()
  vala_defines += ['--define=GIO_2_34']
endif
```

**Comment by nirbheek** [comment]
Ah, I see what you mean. Makes sense then. :)

But perhaps you can use this redundant-flags implementation till a new release of Meson is available!

**Comment by arteymix** [comment]
@nirbheek If it works, yes :)

**Comment by arteymix** [comment]
It's has the exact same issues: https://travis-ci.org/valum-framework/valum/builds/133767851

**Comment by arteymix** [comment]
It works, I had to move the initial dependency evaluations after the conditions though. I look forward `version_compare` now!
