### ISSUE TITLE
Question: on windows, how to detect 32 vs 64 bit build ?

### ISSUE THREAD

**Issue by boxerab** [mesonbuild/meson#5692]
I have a gstreamer meson file for Intel MSDK toolkit, which has both 32 bit and 64 bit libraries.

Currently, I have the following line in my meson file:

`mfx_libdir = [mfx_root + '/lib/lin_x64', mfx_root + '/lib/x64', mfx_root + '/lib64', mfx_root + '/lib']`

I would like to change '/lib/x64' to '/lib/win32' if I am running from the x86 visual studio command prompt.

**Comment by nirbheek** [comment]
It's the same on all platforms; you look at [`host_machine.cpu_family()`](https://mesonbuild.com/Reference-manual.html#host_machine-object).

**Comment by boxerab** [comment]
Thanks. And what about cross compile ? If host machine differs from compile target ?

**Comment by boxerab** [comment]
Oh, never mind :) host_machine is the compile target.

**Comment by boxerab** [comment]
Worked very nicely, thanks!
