### ISSUE TITLE
Pass custom_target to moc_headers

### ISSUE THREAD

**Issue by deepbluev7** [mesonbuild/meson#5693]
I have some dbus files, that are generated with qdbusxml2cpp. I defined a custom target, that calls qdbusxml2cpp and outputs a header and a source file. When I try to pass the header to qt5.preprocess, I get the following error:

`meson.build:41:0: ERROR: Qt5 moc header arguments must be strings or files not <Holder: <CustomTargetIndex: <CustomTarget gen-output@cus: ['/usr/bin/qdbusxml2cpp', '@INPUT@', '-a', '@OUTPUT0@:@OUTPUT1@']>[0]>>.`

What is the correct way to pass the result of a custom target as a header argument to qt5.preprocess? For reference, I tried the following, which produces the above mentioned error:

```
qdbusxml2cpp = find_program('qdbusxml2cpp')
gen_src = custom_target('gen-output',
                        input : ['dbus/com.example.spoon.xml'],
                        output : ['spoonadaptor.h', 'spoonadaptor.cpp'],
                        command : [qdbusxml2cpp, '@INPUT@',
                                   '-a', '@OUTPUT0@:@OUTPUT1@'])

moc_files = qt5.preprocess(moc_headers :
	[
		'src/client.h',
                gen_src[0]
	],
	moc_extra_arguments: defines, include_directories: inc,
	dependencies: deps)
```

gen_src.full_path() also doesn't work as it can't find the file and also #5618 would be an issue, if I didn't reorder the output files.

I'm using meson 0.50.1 currently.

Thank you in advance for your help!

**Comment by ximion** [comment]
This should be fixed by the linked commit (that for some reason was duplicated way too often for this PR...).

**Comment by deepbluev7** [comment]
Thank you! <3
