### ISSUE TITLE
Using CustomTarget as kconfig load() argument

### ISSUE THREAD

**Issue by elmarco** [mesonbuild/meson#5698]
Hi,

I would like to write something like:

```
kconfig = import('unstable-kconfig')
ct = custom_target()
config = kconfig.load(ct)
```
It currently fails with:
ERROR: List item must be one of (<class 'str'>, <class 'mesonbuild.mesonlib.File'>)

**Comment by elmarco** [comment]
hmm, perhaps this is not possible because kconfig.load() is only meant for meson/configure-time.

**Comment by xclaesse** [comment]
Because custom_target() will run at build time, and kconfig needs it at configure time, I think. Try with configure_file() instead.

**Comment by elmarco** [comment]
I managed to use configure_file(), but I would need #5701 #5702 & #5703
