### ISSUE TITLE
ImportError: DLL load failed: %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by AntumDeluge** [mesonbuild/meson#5699]
I can't decrypt the following error. I believe the issue is happening because I am using 32-bit Python but it is trying to load a 64-bit DLL library on my system path. The error occurs when trying to load the `pyexpat` library, but there is no other information, so I don't know how to find the DLL that is causing the problem:

```
Traceback (most recent call last):
  File "C:\Development\MSYS2\mingw32\bin\meson-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "C:/Development/MSYS2/mingw32/lib/python3.7/site-packages\pkg_resources\__init__.py", line 35, in <module>
    import plistlib
  File "C:/Development/MSYS2/mingw32/lib/python3.7\plistlib.py", line 65, in <module>
    from xml.parsers.expat import ParserCreate
  File "C:/Development/MSYS2/mingw32/lib/python3.7\xml\parsers\expat.py", line 4, in <module>
    from pyexpat import *
ImportError: DLL load failed: %1 is not a valid Win32 application.
```

I am trying to build the [Pixman library](http://www.pixman.org/) on Windows under the [MSYS2/MinGW-w64](https://www.msys2.org/) environment. I have no problems building a 64-bit library. So it leads me to believe the issue has something to do with a 64-bit DLL interfering with the 32-bit meson build environment. Please let me know if there is any other information that I might be able to provide.

**Edit:** I can circumvent the error by explicitly calling the meson executable from the 64-bit environment (*/mingw64/bin/meson*), but would be nice if I didn't have to do so, so that I didn't have to manually edit the MSYS2/MinGW-w64 build configuration files.

**Comment by AntumDeluge** [comment]
The error appears to be related to my MSYS2/MinGW-w64 environment. I can get around it by using meson from my System's Python installation instead of the one from MSYS2's package manager.

**Comment by brechtsanders** [comment]
I'm also getting the error `ninja: fatal: CreateProcess: %1 is not a valid Win32 application`
when using meson 0.54.0 with MSYS2/MinGW-w64, where version 0.53.2 and lower didn't have this issue.
