### ISSUE TITLE
Add project option for API version

### ISSUE THREAD

**Issue by arteymix** [mesonbuild/meson#570]
It would be very handy to have an `api_version` option in `project` as well as a getter in the `meson` object. That would be used to name Vala bindings, GIR files, header folders, etc...

```python
project('project', 'c', version: '0.2.3', api_version: '0.2')

install_header('project.h', install_dir: 'project-' + meson.get_project_api_version())
```

It should default to the `MAJOR.MINOR` part of the project version.

**Comment by nirbheek** [comment]
Is there anything you'd miss out by defining a variable called `api_version` right after the `project()` definition that stores that value?
```
project('project', 'c', version: '0.2.3')
api_version = '0.2'
install_header('project.h', install_dir: 'project-' + api_version)
```

With this you can even derive it from the project version itself if you so wish:
```
project('project', 'c', version: '0.2.3')
version_array = meson.project_version().split('.')
api_version = '@0@.@1@'.format(version_array[0], version_array[1])
```
(or whatever other versioning scheme you use)

**Comment by arteymix** [comment]
You're right, it's probably better to use a variable for that purpose, especially since a project is likely to version multiple APIs.

What kind of string processing is available in Meson? I did not see that in the documentation :(

**Comment by nirbheek** [comment]
There's some docs here:

https://github.com/mesonbuild/meson/wiki/Syntax#strings

But it's a bit incomplete. I'll fix that now.
