### ISSUE TITLE
meson test --verbose doesn't write out testlog.txt

### ISSUE THREAD

**Issue by leio** [mesonbuild/meson#5710]
If running tests with --verbose option, meson doesn't write out testlog.txt (or apparently .json neither). That seems to be undesired behaviour and it should still be written out (it seems they contain more information than what gets outputted verbosely).

**Comment by nirbheek** [comment]
Specifically, `--print-errorlogs` information is not outputted, and also not written out, so it's lost. We should always write those files out, IMO. It's useful for CI to have the verbose output and also have it in the artifacts.

**Comment by eli-schwartz** [comment]
Fixed in #8200
