### ISSUE TITLE
`shlex.split` eats up backslashes on Windows

### ISSUE THREAD

**Issue by agurtovoy** [mesonbuild/meson#5726]
`shlex.split` is [not suitable for splitting command line on Window](https://bugs.python.org/issue1724822). It looks like people have ran into this a couple of times (#3565, https://github.com/mesonbuild/meson/blob/487fdfcd1191a7a6cb4190a1fed5549c5b41b3c9/mesonbuild/dependencies/base.py#L493), and worked around the issue locally. 

There ~25 calls of `shlex.split` in the codebase, though, and the majority of them are prone to trigger issues on Windows any time the string that is being split contains a backslash. For example, if you run the following on Windows:

```
set LDFLAGS=-LIBPATH:C:\.conan\dc6596\1\lib
cd "meson\test cases\common\1 trivial\"
meson build
cd build
findstr ".conan" build.ninja
```

... you'll get this:

```
 LINK_ARGS = "/LIBPATH:IBPATH:C:.conandc65961lib" "/nologo" "/DEBUG" "/PDB:trivialprog.pdb" "/SUBSYSTEM:CONSOLE" "kernel32.lib" "user32.lib" "gdi32.lib" "winsp
ool.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "comdlg32.lib" "advapi32.lib"
```

`"/LIBPATH:IBPATH:C:.conandc65961lib"` is problematic.

I'd like to submit a PR that replaces all `shlex.split` calls with something like `mesonlib.split_args`. Thoughts?

**Comment by agurtovoy** [comment]
Ideas on how to write a good test case for this would also be highly appreciated.

**Comment by agurtovoy** [comment]
Reported `/LIBPATH:IBPATH` anomaly as a separate issue: #5727.

**Comment by nirbheek** [comment]
I'd be happy to review a PR that does that, it makes sense :)

A test case would go under `run_unittests.py:InternalTests`. There are other examples there of internal functions being tested.

**Comment by agurtovoy** [comment]
`shlex.quote` is similarly problematic; replacing it with `mesonlib.quote_arg`.

**Comment by ishandutta2007** [comment]
`posix=False` might be what you need

```
shlex.split(raw_args, posix=False)
```
