### ISSUE TITLE
`NinjaBackend.guess_external_link_dependencies` issues with LDFLAGS on Windows

### ISSUE THREAD

**Issue by agurtovoy** [mesonbuild/meson#5727]
[`NinjaBackend.guess_external_link_dependencies`](https://github.com/mesonbuild/meson/blob/master/mesonbuild/backend/ninjabackend.py#L2384) assumes that `commands` will contain only canonical link args (`-L`, `-l`), but this is not always the case on Windows. 

In particular, when flags are coming from the environment (say from `LDFLAGS`), they are likely to be platform/compiler-specific (`/LIBPATH:`, `-LIBPATH:`); depending on whether it's `/LIBPATH:` or `-LIBPATH:`, `guess_external_link_dependencies` will either ignore the search path. or mangle it along the lines of `/LIBPATH:IBPATH:C:\\.conan\\dc6596\\1\\lib`.

**Comment by dankegel** [comment]
I just ran into this with meson 0.51.1.

I have a .pc file that contains -libpath.  Standalone pkgconfig outputs:
```
$ PKG_CONFIG_PATH=c:/opt/oblong/g-speak5.1/lib/pkgconfig /cygdrive/c/pkg-config-lite/bin/pkg-config.exe --libs libBasement
Basement.lib Plasma++.lib Loam++.lib C:/opt/oblong/deps-64-13/lib/boost_filesystem-vc141-mt-x64-1_67.lib C:/opt/oblong/deps-64-13/lib/boost_regex-vc141-mt-x64-1_67.lib C:/opt/oblong/deps-64-13/lib/boost_system-vc141-mt-x64-1_67.lib -libpath:C://opt/oblong/deps-64-13/lib icuin.lib icuuc.lib Plasma.lib -libpath:C://opt/oblong/deps-64-13/lib yaml.lib ssleay32.lib libeay32.lib -libpath:C:/opt/oblong/g-speak5.1/lib Loam.lib
```
but ninja mangles this to "ibpath:C://opt/oblong/deps-64-13/lib.lib":
```
$ cat btmp-RelWithDebInfo/listener-drome.exe.rsp
 /MACHINE:x64 /OUT:listener-drome.exe listener-drome@exe/src_listener-drome.cpp.obj "/nologo" "/DEBUG" "/PDB:listener-drome.pdb" "Basement.lib" "Plasma++.lib" "Loam++.lib" "C:/opt/oblong/deps-64-13/lib/boost_filesystem-vc141-mt-x64-1_67.lib" "C:/opt/oblong/deps-64-13/lib/boost_regex-vc141-mt-x64-1_67.lib" "C:/opt/oblong/deps-64-13/lib/boost_system-vc141-mt-x64-1_67.lib" "icuin.lib" "icuuc.lib" "Plasma.lib" "yaml.lib" "ssleay32.lib" "libeay32.lib" "Loam.lib" "ibpath:C://opt/oblong/deps-64-13/lib.lib" "ibpath:C:/opt/oblong/g-speak5.1/lib.lib" "/SUBSYSTEM:CONSOLE" "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "comdlg32.lib" "advapi32.lib"
```

Meson supports -L, needs to also support the msvc equivalent -libpath: as well.  Looks like master doesn't yet:
```
buildbot@rbb-win10-4 ~/src/meson
$ find . -type f -print0 | xargs -0 grep libpath:

buildbot@rbb-win10-4 ~/src/meson
$ git describe
0.51.0-288-g80ef6fd6
```

**Comment by dankegel** [comment]
I found an, um, workaround for a related problem https://github.com/mesonbuild/meson/pull/5812 
Perhaps a similar workaround would do for $LDFLAGS?

**Comment by nirbheek** [comment]
FWIW, meson automatically converts `-L` to `/LIBPATH:` internally when using the MSVC compiler, so you can always use `-L` when passing compiler arguments to meson.

**Comment by agurtovoy** [comment]
I should mention that #5881 doesn't address the `-LIBPATH:` case. I'm not sure it's needed, but if anyone runs into a valid use case, please comment/tag me.
