### ISSUE TITLE
Extra return line in environment.py

### ISSUE THREAD

**Issue by LynnKirby** [mesonbuild/meson#5746]
Just a little error. :cat2: 

There's an extra return in:

https://github.com/mesonbuild/meson/blob/5d9a1558c2e1041b1149fca6b2bceba447b6823e/mesonbuild/environment.py#L761-L766

Which is a duplicate of the return in the if block directly above:

https://github.com/mesonbuild/meson/blob/5d9a1558c2e1041b1149fca6b2bceba447b6823e/mesonbuild/environment.py#L752-L760

**Comment by nirbheek** [comment]
Could you please open a pull request for this? It's definitely worth fixing :)

I'm surprised our linter didn't catch this already.

**Comment by scivision** [comment]
From what I can see, flake8 doesn't catch `W0101 Unreachable code`. I didn't immediately see any flake8 plugins that do this. Pylint does catch this error.

Meson Sider config appears to only use flake8 at the moment.

Example (unreachable.py)

```python
def foo():
    return 1
    return 2


foo()
```

```sh
$ flake8   # no output

$ pylint unreachable.py

...
unreachable.py:3:4: W0101: Unreachable code (unreachable)
```

**Comment by scivision** [comment]
Here is what catches this error (complete output given below):

```sh
$ pylint mesonbuild --disable=all --enable=W0101

************* Module mesonbuild.environment
mesonbuild\environment.py:766:16: W0101: Unreachable code (unreachable)
************* Module mesonbuild.scripts.depfixer
mesonbuild\scripts\depfixer.py:418:8: W0101: Unreachable code (unreachable)
```

@nirbheek I think pylint for W0101 unreachable code would be worthwhile to add. Do you have a preference how to add this to CI e.g. Sider?

**Comment by scivision** [comment]
...and thank you so much @LynnKirby for raising this issue. I had blindly assumed that flake8 would catch these!

**Comment by nirbheek** [comment]
> @nirbheek I think pylint for W0101 unreachable code would be worthwhile to add. Do you have a preference how to add this to CI e.g. Sider?

Currently we add it to `setup.cfg` in the root of the repository since that gets picked up for both CI and commit hooks that many folks have.

**Comment by nirbheek** [comment]
Ah, wait, you said pylint catches it but there's no way to catch it with flake8? That's disappointing. I have no preference for how pylint support is added, but it seems worthwhile to have both flake8 and pylint since the overhead is negligible in CI.
