### ISSUE TITLE
Cannot directly sum arrays and include_directories()

### ISSUE THREAD

**Issue by leogermond** [mesonbuild/meson#5748]
# Test setting
This bug has been reproduced in meson 0.50.1 on MacOS X High Sierra 10.13.6

# Summary
Cannot directly sum arrays and include_directories(''):

# Reproduce
## This Works
```meson
ic = []
ic += include_directories('.')
```

## This Fails
```meson
ic = [] + include_directories('.')
```
With error `fails/meson.build:1:0: ERROR: Invalid use of addition: can only concatenate list (not "IncludeDirsHolder") to list`

# Run example

You can find one at https://github.com/leogermond/meson_bug_array_sum_incdir/tree/master

Run `meson build` and the following happens

```
➜  bug_include_directories git:(master) meson build      
The Meson build system
Version: 0.50.1
Source dir: /Users/leogermond/Lab/meson/bug_include_directories
Build dir: /Users/leogermond/Lab/meson/bug_include_directories/build
Build type: native build
Project name: a
Project version: undefined
Native C compiler: cc (clang 10.0.0 "Apple LLVM version 10.0.0 (clang-1000.10.44.4)")
Build machine cpu family: x86_64
Build machine cpu: x86_64

fails/meson.build:1:0: ERROR: Invalid use of addition: can only concatenate list (not "IncludeDirsHolder") to list

A full log can be found at /Users/leogermond/Lab/meson/bug_include_directories/build/meson-logs/meson-log.txt
```

**Comment by xclaesse** [comment]
I think that's the expected behaviour, even if it seems a bit counter-intuitive. In meson, `list += item` is an appending operation, and `list1 + list2` is a concatenating operation.

My guess is this won't work neither:
```meson
ic = []
ic = ic + include_directories('.')
```

**Comment by scivision** [comment]
I agree with @xclaesse , here is an example. First two cases are legal, third case is not legal.

```meson
project('syntax')

i = []
i += include_directories('.')

i = []
i = i + [include_directories('.')]

# illegal syntax
i = []
i = i + include_directories('.')
```

**Comment by scivision** [comment]
Thanks for reaching out @leogermond please feel free to reopen if something further arises.

**Comment by leogermond** [comment]
It works for `files()` (and arrays obviously), so `+` and `+=` are the same operators except for `include_directories()`. I think it goes against the principle of less surprise, and I don't see "it's not legal" as a justification. The main implementation difference is that include_directories can be system or not, and both should not be mixed, but in that case we use only non-system directories, so I guess it's more of an oversight than a design decision.

**Comment by xclaesse** [comment]
`files()` actually returns an array object, that's why. It's not only include_directories, same with string, number I guess. Speaking of least surprise, try list+=string and list+string in Python... I think the meson behavior actually makes sense.

**Comment by alavalas1** [comment]
The Meson build system
Version: 0.53.2
Source dir: /hdd1/Projects/Sommelier_clang_16/platform2/vm_tools/sommelier
Build dir: /hdd1/Projects/Sommelier_clang_16/platform2/vm_tools/sommelier/build-clang
Build type: native build
Project name: sommelier
Project version: undefined
C compiler for the host machine: /hdd1/llvm_new_16.0/llvm-project/build/bin/clang (clang 16.0.0 "clang version 16.0.0 (https://github.com/llvm/llvm-project.git ed342d9d29898952e2d1fcd40716e83ed5b9f202)")
C linker for the host machine: /hdd1/llvm_new_16.0/llvm-project/build/bin/clang ld.bfd 2.39
C++ compiler for the host machine: /hdd1/llvm_new_16.0/llvm-project/build/bin/clang++ (clang 16.0.0 "clang version 16.0.0 (https://github.com/llvm/llvm-project.git ed342d9d29898952e2d1fcd40716e83ed5b9f202)")
C++ linker for the host machine: /hdd1/llvm_new_16.0/llvm-project/build/bin/clang++ ld.bfd 2.39
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program wayland-scanner found: YES (/usr/bin/wayland-scanner)
Program gen-shim.py found: YES (/hdd1/Projects/Sommelier_clang_16/platform2/vm_tools/sommelier/gen-shim.py)
Library m found: YES
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency gbm found: YES 21.2.6
Run-time dependency libdrm found: YES 2.4.107
Run-time dependency pixman-1 found: YES 0.38.4
Run-time dependency wayland-client found: YES 1.18.0
Run-time dependency wayland-server found: YES 1.18.0
Run-time dependency xcb found: YES 1.14
Run-time dependency xcb-composite found: YES 1.14
Run-time dependency xcb-shape found: YES 1.14
Run-time dependency xcb-xfixes found: YES 1.14
Run-time dependency xkbcommon found: YES 0.10.0
Run-time dependency GTest found: YES 1.10.0
Run-time dependency GMock found: YES (building self)
Dependency pixman-1 found: YES 0.38.4 (cached)

**meson.build:201:2: ERROR: Invalid use of addition: can only concatenate list (not "IncludeDirsHolder") to list**

Please help out the above error
