### ISSUE TITLE
MESON_SOURCE_ROOT points to build dir in vs2019 backend when executing run_target

### ISSUE THREAD

**Issue by germandiagogomez** [mesonbuild/meson#5782]
Hi guys,

Steps to reproduce:

    1. create a project with a run_target
    2. use --backend=vs2019 when configuring
    3. use run_target

expected_result:

    MESON_SOURCE_ROOT should point to the root of the project

Actual result:

    MESON_SOURCE_ROOT points to the build directory

**Comment by xclaesse** [comment]
I believe I fixed it already in master: https://github.com/mesonbuild/meson/commit/d8b3af00aca3a2825d199367d588a4b24e5ab779#diff-00dec39b9ff0a99a9b1db4aea40024c6

**Comment by germandiagogomez** [comment]
It seems that MESON_SOURCE_ROOT and MESON_BUILD_ROOT are swapped inside the script when it is invoked with the backend for Visual Studio.

If I pass these variables from meson.build as parameters to the script, then it works

**Comment by germandiagogomez** [comment]
@xclaesse In fact, it was that. So I will close it :)

**Comment by nirbheek** [comment]
Commit manually cherry-picked to 0.51.2
