### ISSUE TITLE
Meson cross compiling CUDA

### ISSUE THREAD

**Issue by kpeace** [mesonbuild/meson#5791]
Short version: What is the best way to cross compile a CUDA program using meson.

Here is my code:

``` c++
#include <iostream>
#include <cuda_runtime.h>

__global__
void hello(int *b)
{
    *b = 42;
}

int main(){
    int *pd;
    cudaMalloc(&pd, sizeof(int));
    hello<<<1, 1>>>(pd);
    cudaDeviceSynchronize();

    int res = 0;
    cudaMemcpy(&res, pd, sizeof(int), cudaMemcpyDeviceToHost );
    cudaFree(pd);

    std::cout << "hello world: " << res << std::endl;
    return 0;
}
```

I installed my gcc cross compiler in /opt/cross and the needed CUDA libs in /opt/cross/lib/cuda

This command works.
```
nvcc -ccbin /opt/cross/bin/aarch64-linux-g++ -std=c++14 -I/usr/local/cuda/include -L/opt/cross/lib/cuda --gpu-architecture=compute_72 --gpu-code=sm_72 src/hello.cu
```

But with meson it fails.

`meson build src --cross-file arm_build.txt`
```
The Meson build system
Version: 0.51.1
Source dir: /home/shalom/cuda-workspace/meson-cuda-hello-world/src
Build dir: /home/shalom/cuda-workspace/meson-cuda-hello-world/build
Build type: cross build
Project name: hello-cuda
Project version: undefined
C++ compiler for the build machine: c++ (gcc 8.3.0 "c++ (Ubuntu 8.3.0-6ubuntu1) 8.3.0")
Cuda compiler for the build machine: nvcc (nvcc 10.1.168)
C++ compiler for the host machine: /opt/cross/bin/aarch64-linux-g++ (gcc 8.3.0 "aarch64-linux-g++ (GCC) 8.3.0")                                                                       

meson.build:1:0: ERROR:

A full log can be found at /home/shalom/cuda-workspace/meson-cuda-hello-world/build/meson-logs/meson-log.txt
```

Here is my meson.build file:
```
project('hello-cuda', 'cpp', 'cuda')

cuda_comp = meson.get_compiler('cuda')
cuda = import('unstable-cuda')
nvcc_flags = cuda.nvcc_arch_flags(cuda_comp, 'Common')
executable('hello-cuda', 'hello.cu', cuda_args : nvcc_flags)
```

Here is my arm_build.txt cross file:
```
[binaries]
c = '/opt/cross/bin/aarch64-linux-gcc'
cpp = '/opt/cross/bin/aarch64-linux-g++'
ar = '/opt/cross/bin/aarch64-linux-ar'
as = '/opt/cross/bin/aarch64-linux-as'
strip = '/opt/cross/bin/aarch64-linux-strip'
ranlib = '/opt/cross/bin/aarch64-linux-ranlib'
ld = '/opt/cross/bin/aarch64-linux-ld'
objdump = '/opt/cross/bin/aarch64-linux-objdump'
objcopy = '/opt/cross/bin/aarch64-linux-objcopy'
size = '/opt/cross/bin/aarch64-linux-size'
pkgconfig = 'aarch64-linux-gnu-pkg-config'
cuda = '/usr/local/cuda/bin/nvcc -ccbin /opt/cross/bin/aarch64-linux-g++ -std=c++14'

[properties]
needs_exe_wrapper = true
#c_link_args = ['--target=arm-linux-gnueabihf']

[host_machine]
system = 'linux'
cpu_family = 'arm'
cpu = 'aarch64'
endian = 'little'
```

What am I doing wrong? What do I need to change to get the cross compile to work?

**Comment by Ericson2314** [comment]
Please fix your markdown

> A full log can be found at /home/shalom/cuda-workspace/meson-cuda-hello-world/build/meson-logs/meson-log.txt`

I think that has more information than what you pasted?

**Comment by kpeace** [comment]
I fixed the markdown. Sorry about that...

Looking at the project I removed the cpp declearation of the project. So this:
`project('hello-cuda', 'cpp', 'cuda')`
changed to this:
`project('hello-cuda', 'cuda')`

I also added the include paths into my cross file. So this:
`cuda = '/usr/local/cuda/bin/nvcc -ccbin /opt/cross/bin/aarch64-linux-g++ -std=c++14'`
changed to this:
`cuda = '/usr/local/cuda/bin/nvcc -ccbin /opt/cross/bin/aarch64-linux-g++ -std=c++14 -I/usr/local/cuda/include -L/opt/cross/lib/cuda'`

I still get the same failure. Here is my messon-log.txt:
```
Build started at 2019-08-13T09:50:16.425212
Main binary: /usr/bin/python3
Python system: Linux
The Meson build system
Version: 0.51.1
Source dir: /home/shalom/cuda-workspace/meson-cuda-hello-world/src
Build dir: /home/shalom/cuda-workspace/meson-cuda-hello-world/build
Build type: cross build
Project name: hello-cuda
Project version: undefined
No CUFLAGS in the environment, not changing global flags.
No LDFLAGS in the environment, not changing global flags.
Sanity testing Cuda compiler: nvcc
Is cross compiler: None.
Sanity check compiler command line:  nvcc -w -cudart static /home/shalom/cuda-workspace/meson-cuda-hello-world/build/meson-private/sanitycheckcuda.cu -o /home/shalom/cuda-workspace/meson-cuda-hello-world/build/meson-private/sanitycheckcuda.exe
Sanity check compile stdout:

Sanity check compile stderr:

Sanity check run command line:  nvcc --run "/home/shalom/cuda-workspace/meson-cuda-hello-world/build/meson-private/sanitycheckcuda.exe"                                               
Sanity check run stdout:

Sanity check run stderr:
100

cudaGetDeviceCount() returned 100

Cuda compiler for the build machine: nvcc (nvcc 10.1.168)

meson.build:1:0: ERROR:

```

**Comment by Ericson2314** [comment]
> Cuda compiler for the build machine: nvcc (nvcc 10.1.168)

You are cross compiling cude so it should be for the host machine. I recall there might have been some cuda exception in the code?

**Comment by kpeace** [comment]
My apologies, but I didn't fully understand your reply.

I am trying to cross compile cuda, so I expect the output code to run on the aarch64 machine. My assumption is that if I specify the gcc cross compiler and send the correct flags to nvcc it would output an executable for the aarch64 machine.

It worked as expected when I ran the command line manually. (The command is stated in the first message of this issue).

But when I try to use Meson for invoking nvcc with my cross compiler, Meson seams to get confused and fail without stating what is the problem it has encountered (as seen in the attached log).

> I recall there might have been some cuda exception in the code?

In what code? In the Meson code base? because Meson states that they support cuda since 0.50 and I am using 0.51....
