### ISSUE TITLE
ViM indent and syntax files link in documentation points to 404.

### ISSUE THREAD

**Issue by kierun** [mesonbuild/meson#5794]
The [documentation link points](https://mesonbuild.com/Release-notes-for-0-37-0.html#vim-indent-and-syntax-files) to `https://github.com/mesonbuild/meson/tree/master/syntax-highlighting/vim` which returns 404.

It should be: `https://github.com/mesonbuild/meson/tree/master/data/syntax-highlighting/vim`

**Comment by kierun** [comment]
In case anyone is as dyslexic as me, there is a `data` missing in the documentation URL.

**Comment by nirbheek** [comment]
Fixed in https://github.com/mesonbuild/meson/commit/275c493cafb6df15d8655574013cb599c7728c0b, thanks!

**Comment by kierun** [comment]
You are most welcome.
