### ISSUE TITLE
Support installing library in subdirectory

### ISSUE THREAD

**Issue by arteymix** [mesonbuild/meson#580]
In some cases (e.g. plugins), it's useful to install shared library in a subdirectory. For instance, libgda install its database providers in `/usr/lib64/libgda-5.0/providers`.

This is already supported for `install_headers`, so I suggest that we use the same `subdir` option.

**Comment by nirbheek** [comment]
You can do this with `install_dir`. The path is relative to the `prefix` option. Something like this would work for your case:

`install_dir : '@0@/lib@1@-@2@/providers'.format(get_option('libdir'), name, version)`

If you have multiple places where you want to use it, you can store it in a variable and reuse it.

**Comment by arteymix** [comment]
This can work for now, but you should really consider a `subdir` option to avoid that kind of hack.

**Comment by arteymix** [comment]
I'm happy :) :+1:

**Comment by nirbheek** [comment]
I've added it to the documentation so that people don't have to guess how this works. If we get more bug reports asking for this, we can look into adding this.

**Comment by arteymix** [comment]
Unrelated, but how do you build the path with GModule to refer to library in subfolder like that?

**Comment by nirbheek** [comment]
I'm not sure I understand the question. `g_module_open` takes a filename argument (full path), so you can use that. Or you can use `g_module_build_path`.

**Comment by arteymix** [comment]
The absolute path (eg. `/usr/lib64/libgda-5.0/providers` has to be hard-coded during the build? This does not look easily feasible in Vala.. :(

**Comment by arteymix** [comment]
Does Meson write the `libdir` option in a configuration header? And does it support `--use-header`?

**Comment by arteymix** [comment]
Nevermind, I can always use `vala_args` for the latter.

**Comment by nirbheek** [comment]
In GStreamer we use an environment variable `GST_PLUGIN_PATH` which can contain a list of paths to look for additional plugins. `GST_PLUGIN_SYSTEM_PATH` is for overriding the 'system' path, so it will ignore plugins in `/usr/lib/gstreamer-1.0`. See: https://cgit.freedesktop.org/gstreamer/gstreamer/tree/gst/gstregistry.c#n1585

**Comment by arteymix** [comment]
I might introduce an environment variable for the purpose of loading server implementation.

How do you define `PLUGINDIR` with Meson?

**Comment by tp-m** [comment]
In config.h:
https://github.com/centricular/gstreamer/blob/meson/meson.build#L62

**Comment by arteymix** [comment]
@tp-m I was essentially building a config header, but then I saw that one can use relative RPATH, which is considerably more convenient

Thanks! It has been really helpful for https://github.com/valum-framework/valum/pull/182 :)
