### ISSUE TITLE
Sporadic CI failures for "common/13 pch" on msys2

### ISSUE THREAD

**Issue by NNemec** [mesonbuild/meson#5807]
Recent CI builds on master (e.g.#3475) failed due to seemingly unrelated problems in the msys2 builds. The same error appeared sporadically on other branches.

**Comment by jpakkane** [comment]
This happened at the same time as MinGW updated from GCC 9.1 to GCC 9.2 so this is probably a GCC or a MinGW packaging bug.

**Comment by NNemec** [comment]
It seems to be just that specific test. Perhaps that could be temporarily disabled for msys2 until the issue is resolved, to keep the CI builds clean?

**Comment by nirbheek** [comment]
The problem with that is that we might forget to re-enable it. Maybe we can check whether it's on Azure CI, Windows, and the compiler is exactly GCC 9.2, and skip the test.

**Comment by NNemec** [comment]
In my experience, keeping the CI green has higher priority than any individual issue. I would suggest disabling the test now on master, and writing a ticket for fixing the issue and re-enabling the test. Are that, you can still discuss the priority of that ticket.

**Comment by jpakkane** [comment]
The upstream bug is probably this: https://github.com/msys2/MINGW-packages/issues/5719

It should be fixed so maybe it will sort itself out once mingw updates their packages?

**Comment by nirbheek** [comment]
x86 seems to be fixed, magically. x86_64 is still failing, but lets wait a couple of days. If it's still broken we can add a workaround.

**Comment by NNemec** [comment]
Beware the term "sporadic" in the title: There were sometimes builds where either x86 or x64 or even both would run successfully, only to break again at a later build. "fixed magically" sounds just like that...
