### ISSUE TITLE
simplify working with system directories

### ISSUE THREAD

**Issue by Flow-It** [mesonbuild/meson#5810]
I wonder if there already exists a clean way to get the full paths to bindir, datadir, etc.
In my meson.build files I often have situations where I need to do something like:

```
bin_install_dir = join_paths(get_option('prefix'), get_option('bindir'))
data_install_dir = join_paths(get_option('prefix'), get_option('datadir'), meson.project_name())
```

This could be much more readable if there is an automatic way to resolve the full path.

Of course there may be various issues here: When do I append the project name to the path and when not? Do I always use the same prefix?

So please read this issue not as a feature request but more of a starting point for a discussion about best practises.

**Comment by QuLogic** [comment]
Can be:
```
bin_install_dir = get_option('prefix') / get_option('bindir')
data_install_dir = get_option('prefix') / get_option('datadir') / meson.project_name()
```
in more recent Meson.

**Comment by Flow-It** [comment]
That's good enough for me. Closing to clean up for now.
