### ISSUE TITLE
meson does not add "-pthread" from cmake-based dependency

### ISSUE THREAD

**Issue by FelixSchwarz** [mesonbuild/meson#5821]
I tried to use build a simple http client using Microsoft's [cpprestsdk](https://github.com/Microsoft/cpprestsdk/). The cpprest library is installed system-wide (Fedora 30 x86_64, cpprest 2.10.13-1.fc30).

However meson 0.51.1 fails to link the code while a cmake-based project works fine:

    $ meson . build
    The Meson build system
    Version: 0.51.1
    Source dir: …/httptest
    Build dir: …/httptest/build
    Build type: native build
    Project name: httptest
    Project version: undefined
    C++ compiler for the build machine: c++ (gcc 9.1.1 "c++ (GCC) 9.1.1 20190503 (Red Hat 9.1.1-1)")
    C++ compiler for the host machine: c++ (gcc 9.1.1 "c++ (GCC) 9.1.1 20190503 (Red Hat 9.1.1-1)")
    Build machine cpu family: x86_64
    Build machine cpu: x86_64
    Found CMake: /usr/bin/cmake (3.14.5)
    Run-time dependency cpprestsdk (modules: cpprestsdk::cpprest) found: YES 
    Build targets in project: 1
    Found ninja-1.9.0 at /usr/bin/ninja

    $ ninja -C build
    ninja: Entering directory `build'
    [2/2] Linking target httptest.
    FAILED: httptest 
    c++  -o httptest 'httptest@exe/src_test.cpp.o' -Wl,--no-undefined -Wl,--as-needed -Wl,--start-group /usr/lib64/libcpprest.so.2.10 /usr/lib64/libcrypto.so /usr/lib64/libssl.so -Wl,--end-group
    /usr/bin/ld: httptest@exe/src_test.cpp.o: undefined reference to symbol 'pthread_join@@GLIBC_2.2.5'
    /usr/bin/ld: //usr/lib64/libpthread.so.0: error adding symbols: DSO missing from command line
    collect2: Fehler: ld gab 1 als Ende-Status zurück
    ninja: build stopped: subcommand failed.

The problem is that the `c++` invocation is missing `-pthread`. When I add this manually or force it via `export CXXFLAGS=-pthread` everything works fine. This is my [meson.build](https://github.com/mesonbuild/meson/files/3524203/meson.build.txt) file (source code for test.cpp is copied from the [cpprest tutorial](https://github.com/Microsoft/cpprestsdk/wiki/Getting-Started-Tutorial) and also included in my `cmake.zip` below).

The cpprest library declares the pthread dependency correctly as far as I can tell. On my system there the file `/usr/lib64/cmake/cpprestsdk/cpprestsdk-targets.cmake` contains:

    set_target_properties(cpprestsdk::cpprest PROPERTIES
      INTERFACE_COMPILE_DEFINITIONS "CPPREST_FORCE_HTTP_CLIENT_ASIO;CPPREST_FORCE_HTTP_LISTENER_ASIO"
      INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
      INTERFACE_LINK_LIBRARIES "-lpthread;cpprestsdk::cpprestsdk_boost_internal;cpprestsdk::cpprestsdk_openssl_internal;cpprestsdk::cpprestsdk_boost_internal;cpprestsdk::cpprestsdk_openssl_internal;cpprestsdk::cpprestsdk_boost_internal;cpprestsdk::cpprestsdk_openssl_internal"
    )

I created a trivial cmake project which works fine ([cmake.zip](https://github.com/mesonbuild/meson/files/3524181/cmake.zip)) so somehow meson misses the linker arguments.

I hope it is easy to reproduce the issue. cpprest should be easily installable on most systems. If necessary I can also try building a minimal cmake-based library so you don't need cpprest but I hope that won't be necessary.

Also as a workaround I'd be interested if it is possible to force meson to link to with pthread (and declare this in meson.build).

**Comment by mensinda** [comment]
Should be fixed with #5824.

**Comment by FelixSchwarz** [comment]
Thank you very much for fixing this so quickly. I can confirm that the pull request resolves the issue.

**Comment by basedtho** [comment]
I ran into this issue when linking with libtorrent

```meson
project('bathory5', 'cpp')
dep = [dependency('libtorrent-rasterbar')]
dep += [dependency('boost', modules : ['system'])]
executable('bathory5', 'src/main.cpp', dependencies : dep)
```

```
 builddir ninja
[0/1] Regenerating build files.
The Meson build system
Version: 0.54.3
Source dir: /home/tho/dev/cpp/bathory5
Build dir: /home/tho/dev/cpp/bathory5/builddir
Build type: native build
Project name: bathory5
Project version: undefined
C++ compiler for the host machine: ccache c++ (gcc 10.1.0 "c++ (GCC) 10.1.0")
C++ linker for the host machine: c++ ld.bfd 2.34.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Dependency libtorrent-rasterbar found: YES 1.2.7 (cached)
Dependency boost found: YES 1.72.0 (cached)
Build targets in project: 1

Found ninja-1.10.0 at /usr/bin/ninja
[2/2] Linking target bathory5
FAILED: bathory5
c++  -o bathory5 'bathory5@exe/src_main.cpp.o' -Wl,--as-needed -Wl,--no-undefined -Wl,--start-group /usr/lib/libtorrent-rasterbar.so /usr/lib/libboost_system.so /usr/lib/libboost_system.so.1.72.0 -Wl,--end-group
/usr/bin/ld: bathory5@exe/src_main.cpp.o: undefined reference to symbol 'pthread_join@@GLIBC_2.2.5'
/usr/bin/ld: /usr/lib/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

real	5.075
mem	389KB
```

**Comment by mensinda** [comment]
@basedtho, please open a new issue with more detailed instructions and check if this issue is still present with 0.55.0.

**Comment by basedtho** [comment]
@mensinda it builds fine with meson-git! (an AUR package, I'm on arch linux)
