### ISSUE TITLE
AttributeError: module 'typing' has no attribute 'NoReturn'

### ISSUE THREAD

**Issue by elmarco** [mesonbuild/meson#5822]
>  def get_search_args(self, dirname: str) -> typing.NoReturn:
> 
> AttributeError: module 'typing' has no attribute 'NoReturn'

According to:
https://github.com/marshmallow-code/webargs/issues/366#issuecomment-459991329

it was fixed in python 3.5.4rc1. They replaced the typing expression with a string.

**Comment by dcbaker** [comment]
of course the 3.5.4 is the oldest version of python that I have installed on my system... Sigh.
