### ISSUE TITLE
boost: Framework test fails because of -L argument without following path

### ISSUE THREAD

**Issue by mensinda** [mesonbuild/meson#5825]
The test ran on Arch Linux with the default boost package.

Full test log: https://pastebin.com/eVksKq0D
Meson log: https://pastebin.com/xQ903yck

**Comment by mensinda** [comment]
I can no longer reproduce this bug on the current master or the original commit. Not sure what went wrong.

I am closing this issue for now until the bug reappears or I know how to reproduce it.

**Comment by naav** [comment]
I am now hitting this bug with meson 0.52.0 from Debian sid repositories.
