### ISSUE TITLE
Add compiler flags detection method

### ISSUE THREAD

**Issue by ebassi** [mesonbuild/meson#583]
This is especially important for C/C++ compilers, but I assume that other compilers that expose particular flags on the command line would benefit from it.

Currently, if I wanted to select a set of compiler arguments to pass to my projects I need to write something like this:

```
test_args = [
  '-ffast-math',
  '-fstrict-aliasing',
  '-Wpointer-arith',
  '-Wformat=2',
  '-Wstrict-prototype',
  '-Werror=init-self'
]
test_args_prog = '''
int someVariableJustForFun;
'''
foreach arg: test_args
  if cc.compiles(c_test_prog, name: 'check for ' + arg, c_args: [ arg ])
    common_c_args += arg
  endif
endforeach
```

This does not really work, because `cc.compiles()` does not have a `c_args` argument.

(translate to other, non-C languages for other compilers)

Since the `compiler` object already has various discovery methods, a `has_flag` or `has_argument` method would allow a more compact syntax:

```
foreach arg: test_args
  if cc.has_flag(arg)
    common_c_args += [ arg ]
  endif
endforeach
```

as well as ensuring portability.

**Comment by ebassi** [comment]
Another option would be to have a:

```
array_of_found_flags = compiler.has_flags(array_of_flags)
```

method that tests all the flags in the array and returns an array containing all the found compiler flags.

**Comment by nirbheek** [comment]
Most Meson API that takes arrays of strings also takes a single string (or several strings) for convenience, so it makes sense so have this.

**Comment by ebassi** [comment]
Trying to compile would work for me, and it would be similar to how header files are checked.

**Comment by jpakkane** [comment]
Something like this has been planned but not implemented due to some open questions:

 - can we do this reliably across compilers, that is are there compilers that swallow unknown args (`-fdonothing`) or where the check depends on the code being compiled
- is is sufficient to just compile or do people want to test linker flags too, the latter is complicated because when cross compiling linking sometimes does not work (see the sanity check tests inside `compilers.py` for an example)
- what should we use for the compile test? Is a plain `int foo;` sufficien

**Comment by ebassi** [comment]
The way I usually do this on autotools is to have a m4 macro that checks a list of flags, and stops at the first successful check, so I can do something like:

```
  check_TESTSET_CFLAG([CFLAGS], [-Wformat=2], [-Wformat])
```

which adds either `-Wformat=2` or `-Wformat` to the `CFLAGS` variable, depending on which one is found first; this can also be used to pass equivalent flags for multiple compilers, e.g. first pass a GCC argument, then pass a MSVC argument, etc. without have to deal with different branches matching the compiler name.

Looking at the various m4 macros I've used and shared among projects, `AC_COMPILE_IFELSE` is deemed enough to check for a compiler flag; see, for instance: http://git.savannah.gnu.org/cgit/autoconf-archive.git/tree/m4/ax_check_compile_flag.m4

 The source code for the test program can be limited to `int i;`

**Comment by jpakkane** [comment]
And if none of the flags are supported it should return empty array instead of erroring out?

**Comment by ebassi** [comment]
I'm not sure I've ever encountered a case of a required compiler flag, so erroring out if none compiler flags are found sounds a bit harsh to me.

Returning an empty array would allow simpler constructs, like:

```
# Enable formating warnings on GCC-like compilers only
common_cflags += compiler.has_flags([ '-Wformat=2', '-Wformat-y2k' ])
```

instead of:

```
if compiler.get_id() == 'gcc' or compiler.get_id() == 'clang':
  common_cflags += compiler.has_flags([ '-Wformat=2', '-Wformat-y2k' ])
endif
```

But that's a minor issue.
