### ISSUE TITLE
pkgconfig libs.private generation rules include non-installed static libraries

### ISSUE THREAD

**Issue by kaniini** [mesonbuild/meson#5836]
I am porting Audacious to use Meson.

Audacious builds several static libraries as part of the process to build `libaudcore`.  They are not meant to be exposed to the public as they are just internal components inside the `libaudcore` amalgamation.  Unfortunately, the pkg-config generator includes them in Libs.private anyway even though they are not declared with `install: true`.

To make things worse, there is no way to override this behaviour.  Please make it possible to override everything the generator guesses.

**Comment by xclaesse** [comment]
I don't think we need an override mechanism here, but simply skip uninstalled static libraries.

**Comment by nirbheek** [comment]
> Unfortunately, the pkg-config generator includes them in Libs.private anyway even though they are not declared with `install: true`.

This was covered by https://github.com/mesonbuild/meson/pull/3939, which was never merged. We should split out the pkg-config bits at least and get that merged.

**Comment by xclaesse** [comment]
> > Unfortunately, the pkg-config generator includes them in Libs.private anyway even though they are not declared with `install: true`.
> 
> This was covered by #3939, which was never merged. We should split out the pkg-config bits at least and get that merged.

Right, that's actually a more clever fix than relying on `install` kwarg.

**Comment by kaniini** [comment]
to be clear, I'm sure there's better ways to handle it than depending on `install: true`, but either way, Libs.private should never contain libraries that don't exist in the final image.

**Comment by kaniini** [comment]
any update on this one?

**Comment by xclaesse** [comment]
Should be already fixed in latest release, I think.

**Comment by orbea** [comment]
@xclaesse Do you know what commit(s) it was fixed in?
