### ISSUE TITLE
Compiles method for compiler object does not have a <lang>_args argument

### ISSUE THREAD

**Issue by ebassi** [mesonbuild/meson#584]
It would be good to have the ability to supply compiler arguments when running a `compiler.compiles()` check.

**Comment by nirbheek** [comment]
You can already do so with the `args` keyword argument as documented in the [reference manual](https://github.com/mesonbuild/meson/wiki/Reference%20manual#compiler-object). Does it not work for you?

**Comment by ebassi** [comment]
Indeed, you're right.
