### ISSUE TITLE
Commit 1ea3ddc6 breaks the compile command

### ISSUE THREAD

**Issue by krader1961** [mesonbuild/meson#5847]
Prior to commit 1ea3ddc6 the *compile_commands.json* output from the config phase looks like this:

```
"command": "cc -Isrc/lib/libast/e416224@@ast@sta -Isrc/lib/libast -I../src/lib/libast -I. -I../
```

I've omitted the subsequent args because they aren't relevant.  With commit 1ea3ddc6 that same command looks like this:

```
"command": "cc -Isrc/lib/libast/e416224@@ast@sta -Isrc/lib/libast -I../src/lib/libast -I -I../
```

**Notice that `-I.` has become `-I`**

This breaks our build because a dynamically constructed header placed in the build root dir is no longer found.

**Comment by jpakkane** [comment]
This should be fixed by #5832.

**Comment by krader1961** [comment]
Confirmed. PR #5832 fixes this for me.

**Comment by krader1961** [comment]
Closing since there is a fix in the pipeline.

**Comment by dcbaker** [comment]
This is fixed, I just didn't like the fix to it.
