### ISSUE TITLE
Dlang ldc compiler uses wrong libphobos

### ISSUE THREAD

**Issue by jdarnold** [mesonbuild/meson#5860]
On Linux, the ldc2 compiler's Phobos library name is *libphobos2-ldc-shared.so*, not *libphobos2.so*, so the -defaultlib parameter should be

`-defaultlib=phobos2-ldc`

**Comment by jpakkane** [comment]
I tested this on latest Ubuntu and at least test case 1 works without problems. The defaultlib argument is not used with ldc, because the method is in the DmdCompiler class, not in LdcCompiler.

Can you post more info about your setup, how you are triggering the issue and the exact output.

**Comment by jdarnold** [comment]
Oh wow, how embarrassing! I have the tiniest little meson.build file and I forgot I had added the -defaultlib line myself for Linux builds. 

In the immortal words of [Emily Litella](https://en.wikipedia.org/wiki/Emily_Litella) ... "Nevemind". Sorry about wasting your time.
