### ISSUE TITLE
True cross compile WITHOUT native compiler should be supported

### ISSUE THREAD

**Issue by mrneo240** [mesonbuild/meson#5862]
Hello, 

It's incredibly inconvenient there is not a proper way to have Meson not check for a native compiler that is running Meson.

This would be very handy when using docker or any other tailored toolchain solution for cross compiling.

I heard the argument that "oh you might need to compile generators", that's fine but let me declare that I don't need that functionality and continue.

Forcing a cross compile to have a native compiler is anti user

**Comment by QuLogic** [comment]
Duplicate of #2392.

**Comment by mrneo240** [comment]
So, after 2 years this is still a known issue?

**Comment by xclaesse** [comment]
Issues don't fix themself magically. Did you write a fix we can reviews and merge?

**Comment by mrneo240** [comment]
I would be happy to write one, if we can have a discussion with the maintainers to allow a user explicitly stating they won't be using or needing a local compiler.

**Comment by ViliusSutkus** [comment]
> user explicitly stating they won't be using or needing a local compiler.

Shouldn't this be a default? CMake, Autotools (and others?) do not need local compilers.

**Comment by jpakkane** [comment]
The simple solution is that the build definition is processed as usual, and if any sort of attempt is made to do something native (look up deps, define a native target etc) the build is immediately aborted.
