### ISSUE TITLE
STRIP not working with cross-compile

### ISSUE THREAD

**Issue by InuSasha** [mesonbuild/meson#5863]
when cross-compiling, meson uses the strip from the STRIP-environment variable, instead of the defined strip in the cross-file.

affected meson version: 0.51.2

setting the STRIP environment variable results in:
1. meson is warning, about using cross-compiler in local env
2. cross builded libs and executables are striped

unset STRIP environment results in:
1. cross builded binaries are no striped at all

meson.conf
```
[binaries]
c = '/home/inu/LibreELEC/mesonbuild2/build.LibreELEC-RPi2.arm-9.80-devel/toolchain/bin/armv7ve-libreelec-linux-gnueabi-gcc'
cpp = '/home/inu/LibreELEC/mesonbuild2/build.LibreELEC-RPi2.arm-9.80-devel/toolchain/bin/armv7ve-libreelec-linux-gnueabi-g++'
ar = '/home/inu/LibreELEC/mesonbuild2/build.LibreELEC-RPi2.arm-9.80-devel/toolchain/bin/armv7ve-libreelec-linux-gnueabi-ar'
strip = '/home/inu/LibreELEC/mesonbuild2/build.LibreELEC-RPi2.arm-9.80-devel/toolchain/bin/armv7ve-libreelec-linux-gnueabi-strip'
pkgconfig = '/home/inu/LibreELEC/mesonbuild2/build.LibreELEC-RPi2.arm-9.80-devel/toolchain/bin/pkg-config'
llvm-config = '/home/inu/LibreELEC/mesonbuild2/build.LibreELEC-RPi2.arm-9.80-devel/toolchain/armv7ve-libreelec-linux-gnueabi/sysroot/usr/bin/llvm-config-host'
libgcrypt-config = '/home/inu/LibreELEC/mesonbuild2/build.LibreELEC-RPi2.arm-9.80-devel/toolchain/armv7ve-libreelec-linux-gnueabi/sysroot/usr/bin/libgcrypt-config'

[host_machine]
system = 'linux'
cpu_family = 'arm'
cpu = 'armv7ve'
endian = 'little'

[properties]
root = '/home/inu/LibreELEC/mesonbuild2/build.LibreELEC-RPi2.arm-9.80-devel/toolchain/armv7ve-libreelec-linux-gnueabi/sysroot/usr'
c_args = ['-march=armv7ve', '-mtune=cortex-a7', '-mabi=aapcs-linux', '-Wno-psabi', '-Wa,-mno-warn-deprecated', '-mfloat-abi=hard', '-mfpu=neon-vfpv4', '-fomit-frame-pointer', '-Wall', '-pipe', '-O2', '-fno-sc
hedule-insns', '-fno-schedule-insns2', '-Wno-format-truncation']
c_link_args = ['-march=armv7ve', '-mtune=cortex-a7', '-Wl,--as-needed', '-fuse-ld=gold']
cpp_args = ['-march=armv7ve', '-mtune=cortex-a7', '-mabi=aapcs-linux', '-Wno-psabi', '-Wa,-mno-warn-deprecated', '-mfloat-abi=hard', '-mfpu=neon-vfpv4', '-fomit-frame-pointer', '-Wall', '-pipe', '-O2']
cpp_link_args = ['-march=armv7ve', '-mtune=cortex-a7', '-Wl,--as-needed', '-fuse-ld=gold']
```

**Comment by InuSasha** [comment]
for clarification: while striping cross-builded binaries, meson uses the strip from host and ignores the strip entry in the cross-file.

**Comment by jpakkane** [comment]
Unrelated, but you should not use `-O2`, `-g`, '-Wl,--as-needed` or `-pipe` in arguments, but instead set the corresponding options. `-pipe` is especially useless because Meson will already add that automatically whenever it is supported by the compiler.

That being said I could not reproduce this in master. I tried to set STRIP in various ways but it always used the cross strip (except when I forgot to add `-Dstrip=true` :laughing: to the Meson invocation).

Here is what I used:

```
./meson.py test\ cases/common/8\ install build --cross-file cross/ubuntu-armhf.txt -Dstrip=true
DESTDIR=/tmp/foo ninja -C build install 
```

Can you try these on latest master and report if it works for you?

**Comment by InuSasha** [comment]
Thanks @jpakkane

with the `-Dstrip=true` is it working, now.
Where is it documented, i haven't found it.
