### ISSUE TITLE
Mention MESON_DIST_ROOT in description of add_dist_script()

### ISSUE THREAD

**Issue by kjellahl** [mesonbuild/meson#5865]
How do you know the search path to the distribution directory (a.k.a. staging directory)
in a script called from meson.add_dist_script()? I guess it's not safe to assume
that it's the current directory when the script is called.

By looking at the source code of Meson, I found that the environment variable
MESON_DIST_ROOT is created before the script is called. But that's not mentioned
in the description of meson.add_dist_script() in
https://github.com/mesonbuild/meson/blob/master/docs/markdown/Reference-manual.md.
No other environment variables are mentioned, either. Are MESON_SOURCE_ROOT and
MESON_BUILD_ROOT available in a dist script?

Available MESON_* environment variables should be listed in the description, as is
done in the description of meson.add_install_script().

**Comment by jpakkane** [comment]
This information is available [on the reference table page](https://mesonbuild.com/Reference-tables.html#script-environment-variables).

**Comment by kjellahl** [comment]
Sorry for not having read the documentation well enough.

It's inconsistent, though, that some script environment variables
(e.g. MESON_INSTALL_DESTDIR_PREFIX) are described only in the reference manual,
others in both the ref manual and the ref tables (e.g. MESON_SOURCE_ROOT),
and MESON_DIST_ROOT only in the ref tables.
