### ISSUE TITLE
meson git CI tests are running on documenation markdown update

### ISSUE THREAD

**Issue by dundir** [mesonbuild/meson#5869]
I recently submitted [PR#5868](https://github.com/mesonbuild/meson/pull/5868), upon submission the full range of python CI tests began for what was solely a documentation markdown update. 

It appears either the CI tests are incorrectly triggering, and one possible solution is to move the documentation markdown to a separate git-project (RFC, meson-docs?)

**Comment by mensinda** [comment]
You should put `[skip ci]` in the commit message for documentation only changes. This is documented in the [Contributing to Meson](https://mesonbuild.com/Contributing.html#documentation) section of the documentation.

Unfortunately, this is the only way to avoid running all the tests, but it is better than nothing.

**Comment by jpakkane** [comment]
The docs are in the same repo on purpose. If they are in separate repos, it is all too easy to update one and not the other.
