### ISSUE TITLE
ninja hangs on certain environments when declaring dependencies

### ISSUE THREAD

**Issue by sandervalstar** [mesonbuild/meson#5875]
Hello, 

First off I want to thank the maintainers of this project for creating a C++ build system that is actually user friendly! Your tool has saved me a lot of time so far 😃 

However, I am currently experiencing the following issue. I am preparing a student assignment which consists of 2 parts. Part A and part B, where part B depends on part A.

I've set up my meson build as follows (all source files are in the same directory currently):

```python
inc = include_directories('.')

part_a_lib = library('part_a', sources : ['PartA.hpp', 'PartASomething.hpp', 'PartASomethingElse.hpp'])
part_a = declare_dependency(include_directories : inc, link_with : part_a_lib)

part_b_lib = library('part_b', sources : ['PartB.hpp'], dependencies: part_a)
part_b = declare_dependency(include_directories : inc, link_with : part_b_lib, dependencies: part_a)
```

Now on my local system my project compiles perfectly fine. However the project will have to be compiled on a different environment (gradescope) and ninja hangs on that environment (specifically it hangs on `Generating symbol file for libpartb.so.symbols`). If I remove the dependency on `part_a` from `part_b_lib` and `part_b` as illustrated below, the project does compile successfully in the remote environment.

```python
inc = include_directories('.')

part_a_lib = library('part_a', sources : ['PartA.hpp', 'PartASomething.hpp', 'PartASomethingElse.hpp'])
part_a = declare_dependency(include_directories : inc, link_with : part_a_lib)

part_b_lib = library('part_b', sources : ['PartB.hpp', 'PartA.hpp', 'PartASomething.hpp', 'PartASomethingElse.hpp'])
part_b = declare_dependency(include_directories : inc, link_with : part_b_lib)
```

However I don't really like this as I think it would be cleaner to reuse `part_a` for constructing `part_b` instead of adding the source files manually. Am I misunderstanding something here about how meson.build files are supposed to be written or is there indeed a bug in meson that causes this? I realize this may be hard to reproduce as I only encounter this issue on my remote build environment, but any help is appreciated.

Thank you!

<br/>

<sub>
Software versions 

(I'm running docker with ubuntu 18.04 locally as well as on gradescope with these software versions installed)

```
meson: 0.51.2
ninja: 1.9.0.git.kitware.dyndep-1.jobserver-1
c++: 7.4.0-1ubuntu1~18.04.1
```

Meson config

```
default_options : ['warning_level=3',
                     'b_coverage=true',
                     'cpp_std=c++14']
```
</sub>

**Comment by jpakkane** [comment]
The fact that it freezes is most likely a bug, but you are also doing things slightly incorrectly. You don't need to define a library for header only libraries. In Meson a library is always a "thing", that is, it has sources that produce an static or shared ilbrary.

Header only libraries can be defined directly like this:

```meson
part_a = declare_dependency(include_directories: include_directories('.'))
```

**Comment by sandervalstar** [comment]
Thank you for clarifying that! 
Unfortunately that did not fix my issue. However, I found it was so unpredictable when the build would hang vs succeed that I suspect it is a concurrency issue with ninja. So now I'm running ninja with `-j 1` and that seems to work so far.
