### ISSUE TITLE
meson instrospect without configured directory broken by b72b5365afe319e576e254f12437aeff899eb03e

### ISSUE THREAD

**Issue by dcbaker** [mesonbuild/meson#5884]
Before said commit `meson introspect --buildoptions meson.build` would return something, now it returns nothing.

**Comment by dcbaker** [comment]
This seems to be related to having a `build_by_default : array.contains('foo')`. Still haven't figured it all out yet.

**Comment by mensinda** [comment]
I am unable to reproduce this bug on the current master?

What project are you using?

**Comment by dcbaker** [comment]
Mesa in this case. I've pushed https://github.com/dcbaker/meson/tree/reproduce-5884, which has a patch to the introspect test that reproduces the problem

**Comment by mensinda** [comment]
Should be fixed with #5885.
