### ISSUE TITLE
cmake config generator doesn't support `check_and_set`

### ISSUE THREAD

**Issue by dcbaker** [mesonbuild/meson#5889]
According to https://cmake.org/cmake/help/v3.2/module/CMakePackageConfigHelpers.html?highlight=set_and_check, it's a best practice to use `set_and_check` instead of plain `set`. `set_and_check` is of course not normally defined, but is generated as part of the replacement of @PACKAGE_INIT@.

I would like to share a single .in file between a legacy cmake build system and a new meson build system, without giving up cmake best practice in the mean time.

**Comment by mensinda** [comment]
Is this related to [configure_package_config_file](https://mesonbuild.com/CMake-module.html#cmakeconfigure_package_config_file), CMake subprojects, or the CMake dependency backend?

Also, do you have a public repo with this problem?

**Comment by dcbaker** [comment]
the Cmake module, so `configure_package_config_file`. The repo in question is [here](https://gitlab.freedesktop.org/mesa/waffle), there's a pull request to add the cmake file to the meson build.

**Comment by mensinda** [comment]
Should be fixed with #5949
