### ISSUE TITLE
objc freestanding sanitycheck failed

### ISSUE THREAD

**Issue by yakiro-nvg** [mesonbuild/meson#5898]
Header stdio.h isn't available on the freestanding environment,

https://github.com/mesonbuild/meson/blob/7b9c348102792030859ed0001a51416506a0a092/mesonbuild/compilers/objc.py#L44

https://en.cppreference.com/w/cpp/freestanding

**Comment by kayakMike** [comment]
seems reasonable;  other sanity checks for the C-Like compilers don't include anything
