### ISSUE TITLE
Pkg-Config dependency uses library file name in linker args and not library name

### ISSUE THREAD

**Issue by nathanblair** [mesonbuild/meson#5908]
For instance, for a .pc file that looks like:

```
prefix=/usr
libdir=${prefix}/lib
includedir=${prefix}/include

Name: OAuth
Description: A C++ OAuth implementation using Qt
URL: https://github.com/nathanblair/OAuth
Version: 0.2.0
Requires: Qt5Network
Requires.private: Qt5Core
Libs: -L${libdir} -lOAuth
Cflags: -I${includedir}/oauth -I${includedir}/oauth/Google -I${includedir}/oauth/Consent -I${includedir}/oauth/Consent/Servers
```

The linker command that is invoked uses:

```
/usr/bin/ld ..... yadda yadda ... --start-group -soname libGamerSaver.so.0 /usr/lib/libOAuth.so /usr/lib/libQt5Network.so /usr/lib/libQt5Core.so ......yadda yadda ....
```

When it should use the Libs field value from the .pc file and look like:

```
/usr/bin/ld ..... yadda yadda ... --start-group -soname libGamerSaver.so.0 -lOAuth -lQt5Network -lQt5Core ......yadda yadda ....
```

I tried looking around in the source but didn't have enough time to dedicate to finding the section that handles this (premably in the PkgConfigDependency class of the Dependency class?

**Comment by QuLogic** [comment]
This is on purpose; leaving it to `-L` paths would be non-deterministic depending on what other pkgconfig / LDFLAGS you happened to set.

**Comment by nathanblair** [comment]
Understood. That makes sense. I was able to write code that worked for my needs by being able to assume since the code was found with pkg-config, using the external `run_command` with appropriate arguments (--libs and --cflags) to 'pkg-config' to get back values that could  be directly used in the kwargs
