### ISSUE TITLE
cannot use disabler() with set_variable

### ISSUE THREAD

**Issue by bruce-richardson** [mesonbuild/meson#5922]
The following code demonstrates the problem: 
```

d = disabler()
set_variable('varx', d)

message('is_variable(varx) = @0@'.format(is_variable('varx')))

```
Output is "Message: is_variable(varx) = false"

and similarly calling get_variable('varx') triggers a fatal error.

This is unexpected behaviour since if one can assign a disabler variable normally, one should also be able to assign it using set_variable() too.

**Comment by jameshilliard** [comment]
I thought we had at least fixed `set_variable` in #5725 which would be in release `0.52.0`, see #5764 for details.

**Comment by jameshilliard** [comment]
I think we can close this now, we've added test coverage for everything I can think of relating to this issue in #7042 along with a bug fix for `get_variable` when working with fallbacks that are potentially disablers. @bruce-richardson if you are still running into this issue in master please provide a reproducer for the issue.

**Comment by bruce-richardson** [comment]
Thanks. No issue on my end with closing this, as I don't see the problem when I do a quick test with the above code using latest meson release.
