### ISSUE TITLE
Website documentation out of sync with git repo

### ISSUE THREAD

**Issue by dundir** [mesonbuild/meson#5926]
It looks like the website is now several weeks out of sync with the git repo. If this is expected (i.e. on a set schedule), please feel free to close the issue.

**Comment by tp-m** [comment]
Thanks for the bug report, but could you be more specific?

Which website exactly? (Just to make sure we're talking about the same thing; direct links ideally)

In what respect is it out of date?

**Comment by jpakkane** [comment]
It is updated manually by me every now and then due to access control reasons. I just updated it so this should be fixed now.
