### ISSUE TITLE
benchmark() doesn't support same options as test()

### ISSUE THREAD

**Issue by elmarco** [mesonbuild/meson#5945]
benchmark() doesn't support same options as test(), 

In particular, it is lacking 'protocol' and 'depends'.

**Comment by dcbaker** [comment]
Does it actually not support them, or is this a problem with documentation. They actually share a codepath, with the only divergence I can see being at the very end when tests are benchmarks are grouped separately.

**Comment by elmarco** [comment]
you get WARNING: Passed invalid keyword argument "depends". for ex

**Comment by dcbaker** [comment]
Does protocol even make sense for benchmarks?
