### ISSUE TITLE
Do not search (or search smartly) for specific '*-config' tools when cross compiling

### ISSUE THREAD

**Issue by Jehan** [mesonbuild/meson#5948]
So say a project has this common option:

> wmf = dependency('libwmf', version: '>=0.2.8', required: get_option('wmf'))

And you crossbuild this project. Yet libwmf is not installed for the target platform. No worry, you just expect the check to fail. Unfortunately it succeeds because after pkg-config check, meson looks for the specific `libwmf-config` executable.

`pkg-config` works as expected since you can just have a specific crossbuild `pkg-config` which only looks through the target libraries (e.g. `x86_64-w64-mingw32-pkg-config`). But the search for a `libwmf-config` just fails horribly as there is no good way to forbid meson to look into the native PATH (many cross-compilation tools are installed in native path, or even platform-agnostic tools).
And anyway if meson managed to find `libwmf-config`, it would likely be built for the target platform (for instance a win32 binary `libwmf-config.exe` when cross-building for Windows) and you could not run it unless you set up an `exe_wrapper`).

My proposition for now would be that `dependency()` should not look at all for these specific `*-config` tools when cross-compiling. It should only do pkg-config, cmake search and alike (methods we are able to control better). Well… unless you set an explicit `libwmf-config` entry in your toolchain file, I guess.

And if really you want to allow these alternative search methods, the logics should be a bit smarter (like checking the executable type and using exe_wrapper, and such), though I am really not sure if this is worth it. These specific `*-config` tools have been on the way out for years anyway. Nowadays projects are expected to just have a `*.pc` file.

**Comment by NickeZ** [comment]
I think you can choose pkg-config only with the `method` option.

> method defines the way the dependency is detected, the default is auto but can be overridden to be e.g. qmake for Qt development, and different dependencies support different values for this (though auto will work on all of them)

**Comment by dcbaker** [comment]
You might be able to add `libwmf-config = ''` to the `[binaries]` section of your cross file to force it not to find libwmf-config.

This is exactly why no one likes *-config files, unfortunately we have to deal with them. It does seem worthwhile to not search for them when cross compiling and only use them if the user has specified one in the cross file.

**Comment by Jehan** [comment]
> This is exactly why no one likes *-config files, unfortunately we have to deal with them. It does seem worthwhile to not search for them when cross compiling and only use them if the user has specified one in the cross file.

Yes this is what I proposed in my original description and seems like a sensible default behaviour. When cross-compiling, I would only look for `libwmf-config` if set in the cross file (same for other `*-config` specific tools).

**Comment by Jehan** [comment]
P.S.:

> I think you can choose pkg-config only with the method option.

Yeah indeed I discovered this later on. A change of default behavior still makes sense though. :-)

**Comment by dcbaker** [comment]
I think this has been fixed, we only allow binaries for the host machine when they are specified in the cross file in a host != build configuration now, so I'll go ahead and close this.
