### ISSUE TITLE
Unknown CPU family riscv

### ISSUE THREAD

**Issue by crus-thenry** [mesonbuild/meson#5950]
WARNING: Unknown CPU family riscv, please report this at https://github.com/mesonbuild/meson/issues/new

add riscv?

**Comment by scivision** [comment]
Hi @crus-thenry thanks for letting us know. Could you try adding `riscv` to these files like in https://github.com/mesonbuild/meson/pull/3889/files

Are you using Qemu or how are you running Meson for RISCV?

**Comment by crus-thenry** [comment]
The warning doesn't seem to hurt anything, I just noticed it and reported it.
I build inside of MSYS2 MINGW64.
I use a cross file to build for RiscV.


[binaries]

c = 'riscv64-unknown-elf-gcc'

cpp = 'riscv64-unknown-elf-g++'

ar = 'riscv64-unknown-elf-ar'

strip = 'riscv64-unknown-elf-ar'



[properties]

c_args = ['-march=rv32imc', '-mabi=ilp32', '-mcmodel=medlow']

cpp_args = ['-march=rv32imc', '-mabi=ilp32', '-mcmodel=medlow']



[host_machine]

system = 'baremetal'

cpu_family = 'riscv'

cpu = 'rv32imc' # M = integer mul/div, C = compressed (16-bit) instructions

endian = 'little'




On 9/24/19, 11:01 AM, "Michael Hirsch, Ph.D." <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @crus-thenry<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_crus-2Dthenry&d=DwMCaQ&c=O3LcjD-V2Iepl5V0N1424A&r=mnJQQz8D5zLA6y1hklx4iinq8u-k9LPnOSEv9U6iazE&m=ts_7NmJdZnEZExTxMofyd4dNDsgU7_KtLd_H08kVwHA&s=-gPwbxdkX73C-M8b5TIb0tAT-BAS3ButHWk4SjNRZ0o&e=> thanks for letting us know. Could you try adding riscv to these files like in https://github.com/mesonbuild/meson/pull/3889/files<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mesonbuild_meson_pull_3889_files&d=DwMCaQ&c=O3LcjD-V2Iepl5V0N1424A&r=mnJQQz8D5zLA6y1hklx4iinq8u-k9LPnOSEv9U6iazE&m=ts_7NmJdZnEZExTxMofyd4dNDsgU7_KtLd_H08kVwHA&s=nb5LHIeNfKck3pcu1mkdvpWGrRdbbKB7eV944ZcPnzc&e=>

Are you using Qemu or how are you running Meson for RISCV?

**Comment by scivision** [comment]
OK thanks good to know it's not stopping your work. This info should be enough to make the change. Thanks again

**Comment by Akaricchi** [comment]
You should specify `riscv32` or `riscv64` instead (both of which are already in the table).

**Comment by crus-thenry** [comment]
aha! ok, thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
