### ISSUE TITLE
meson-logs/meson-log.txt should tell how we configured a project

### ISSUE THREAD

**Issue by Jehan** [mesonbuild/meson#5956]
The first lines of the meson-log.txt should list the non-default options set during either the first `meson $src $build` step or the successive `meson configure -Dbla=plop` calls.

This is extremely useful when you come back to a built project after a while and don't remember how you configured it. In autotools for instance, the configuration command is in the first lines of the `config.log`. Of course for meson, it would not be just the initial command of course, since you can configure in several steps. But just a list of options explicitly set would be nice.

For instance:

```
Configured with:
-Dintrospection=false
-Dvapi=false
-Dprefix=/some/prefix/
```

**Comment by xclaesse** [comment]
That info is already in `meson-private/cmd_line.txt`. But I agree we could print that somehow into the logs.

**Comment by Jehan** [comment]
Oh actually the info in `meson-private/cmd_line.txt` looks good to me. It's indeed not so discoverable though because the info is spread everywhere. But maybe just an info message in the first lines of `meson-logs/meson-log.txt` telling that configuration info can be found in `meson-private/cmd_line.txt` is enough.

For instance:

```
Build started at 2019-09-25T12:51:57.807453
Main binary: /usr/bin/python3
Python system: Linux
The Meson build system
Version: 0.51.1
Source dir: /home/jehan/dev/src/gexiv2
Build dir: /home/jehan/dev/crossbuild/w64/gexiv2
Build type: cross build
[…] *various other info* […]

Info: configuration information are in  meson-private/cmd_line.txt
```

**Comment by Jehan** [comment]
Ah actually I thought a bit more, and scrap the idea of just making an info message. It's better to duplicate the info from `meson-private/cmd_line.txt` into `meson-logs/meson-log.txt` because we can't be 100% sure that the contents of `cmd_line.txt` is the configuration used in the last `meson-log.txt` (we may have changed the configuration and not actually re-run it since this now happens in the `ninja` call).

Also if everything is self-contained in a single file, it makes it easier to just copy/save this single file to diagnose issues, and keep several copies, each containing their used configuration.

**Comment by xclaesse** [comment]
That file is updated when you do `meson configure -Dfoo=bar`, so it's up-to-date even if you did not reconfigure with ninja yet.

FYI, that file is used to reconfigure with `meson setup --wipe`. It basically `rm -rf` your build directory, and reconfigure from scratch with the options from that file.

**Comment by Jehan** [comment]
> That file is updated when you do meson configure -Dfoo=bar, so it's up-to-date even if you did not reconfigure with ninja yet.

Maybe I misunderstand, but I was thinking of such process for instance:

1. run `meson -Dfoo=true`
2. change configuration by running: `meson configure -Dfoo=false`

The `meson-log.txt` was generated at step 1. whereas `cmd_line.txt` was regenerated at step 2. They are now out-of-sync until you run `ninja` (if you looked at both files, you could think the meson-log was done with foo=false whereas this was not).

Or am I misunderstanding something?

**Comment by xclaesse** [comment]
Oh, yes, you're right. Indeed cmd_line.txt is more up to date with than the logs.

**Comment by xclaesse** [comment]
I still think it would be nice to have it in a place it's easier to copy/past, so I made a PR https://github.com/mesonbuild/meson/pull/5960 :-)
