### ISSUE TITLE
project() could use a None language specifier

### ISSUE THREAD

**Issue by dcantrell** [mesonbuild/meson#5964]
I have a support project where I want to just install data files, possibly with some string substitutions.  In the past I did this with a Makefile and shell commands.  I'd like to move over all of my projects to meson, but the way project() is defined requires me to specify a language as the second argument.  This isn't a big deal because I can just say 'c' and then not use it, but it does mean that downstream integrators (i.e., Linux distributions) will need to make sure a C compiler is present when building this package.

Something that lets me do:

project('project-name', None, ...)

Would be useful.  I'm also ok with adding a new language type called 'sh' or 'shell' wherein meson just provides a "compiler" that is a POSIX shell and PATH set.

**Comment by xclaesse** [comment]
Just `project('project-name')` with already works, AFAIK.

**Comment by dcantrell** [comment]
Ah, my mistake.  That's good then.  The documentation is a bit ambiguous on that:

https://mesonbuild.com/Reference-manual.html#project

The way I read "In versions before 0.40.0 you must have at least one language listed." meant to me that in versions after 0.40.0 you can specify more than one language, but it still requires at least one.  The syntax of the function alse implied to me that at least project name and a language are required before key:value arguments.

Thanks.

**Comment by xclaesse** [comment]
Indeed, I would have written something like `Since 0.40.0 the list of language is optional`. Feel free to open a PR with a better phrasing ;-)
