### ISSUE TITLE
Issues with 'meson configure' command

### ISSUE THREAD

**Issue by michaelbadcrumble** [mesonbuild/meson#5976]
I seem to be having issues with 'meson configure' command and after searching the meson documentation and internet for the proper way to use 'configure' command and nothing working I summated this issue because this feature is critical for Meson-ui update configure Meson option.
- My current version of Meson is 0.51.999 beta. But I also experienced the problem with version 0.50.0 and up.

```console
Michaels-MacBook-Pro:exe shnitzel$ meson configure builddir/ -Dbuildtype=minsize -Dwerror=true
Traceback (most recent call last):
  File "/Users/shnitzel/Library/Python/3.7/lib/python/site-packages/meson-0.51.999-py3.7.egg/mesonbuild/mesonmain.py", line 129, in run
    return options.run_func(options)
  File "/Users/shnitzel/Library/Python/3.7/lib/python/site-packages/meson-0.51.999-py3.7.egg/mesonbuild/mconf.py", line 231, in run
    mintro.update_build_options(c.coredata, c.build.environment.info_dir)
  File "/Users/shnitzel/Library/Python/3.7/lib/python/site-packages/meson-0.51.999-py3.7.egg/mesonbuild/mintro.py", line 465, in update_build_options
    write_intro_info(intro_info, info_dir)
  File "/Users/shnitzel/Library/Python/3.7/lib/python/site-packages/meson-0.51.999-py3.7.egg/mesonbuild/mintro.py", line 442, in write_intro_info
    with open(tmp_file, 'w') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/shnitzel/Desktop/meson-ui/tool/exe/builddir/meson-info/tmp_dump.json'
Michaels-MacBook-Pro:exe shnitzel$ 
```

**Comment by mensinda** [comment]
What project are you using? I can not reproduce this with the same command (both 0.51 and current master).

**Comment by michaelbadcrumble** [comment]
I was using a basic project template generated from Meson for testing and ran commands from within the project.  I just did a pip install of 0.51.2 release and it works again but you may need to look into the beta before the next release.

**Comment by mensinda** [comment]
Since I can not reproduce this bug in the current master, this shouldn't be an issue for the next release.

**Comment by michaelbadcrumble** [comment]
Issue seemed to be on my end.  The configure command was not formatted correctly.

**Comment by michaelbadcrumble** [comment]
So is it safe to close this issue?

**Comment by mensinda** [comment]
Yes, this issue can be closed.
