### ISSUE TITLE
Predefine variables

### ISSUE THREAD

**Issue by CreatorVilius** [mesonbuild/meson#5977]
Currently, we cannot predefine variables and therefore, compilers can get confused. For example, using custom declared dependency, you need to have executable variable to link with declared dependency, but you also need to add them as dependency in executable. So I propose `let`, which defines variables null, until variable gains value. Example:
```
let a
# ...
a = 10
```
We could also put static types in there:
```
let a: int
let b: dependency
# ...
a = 10
b = declare_dependency(...)
```

**Comment by jpakkane** [comment]
This will not happen. Meson does not have "null" types by design and they will not be added either.

**Comment by xclaesse** [comment]
I don't understand what you're trying to achieve here, type safety? Can you please be more specific to the problem you're trying to solve, because there could be other solutions, maybe.
