### ISSUE TITLE
meson test does not skip test that are passed a cross exectuable when an exe_wrapper is required

### ISSUE THREAD

**Issue by dcbaker** [mesonbuild/meson#5982]
Mesa has several tests that pass a compiled executable to a python script which calls the executable and compares its output to some expectation. This works great, except when cross compiling when no exe_wrapper is available, but one is needed, as meson doesn't flag these tests as skip due to having no exe_wrapper, and they fail.

**Comment by nwnk** [comment]
Instead of skipping them, is the path to the exe_wrapper in the test's environment? We could make the python script respect it if set.

**Comment by dcbaker** [comment]
nwnk, that's #4427.

Honestly I think we want both. If you say need an exe_wrapper and don't provide one then we should skip them, if you do provide an exe_wrapper then it should be up to the script to do the right thing.

**Comment by dcbaker** [comment]
After talking it over with Jussi, I'm not going to do this. There are some cases where it is okay to pass a cross compiled binary to a script, even without an exe wrapper. such as running a symbol check. For that reason we're not going to implement this, it's the script author's job to return 77 if the script needs to run the binary and can't
