### ISSUE TITLE
Executable built by Meson can't find library

### ISSUE THREAD

**Issue by CreatorVilius** [mesonbuild/meson#5999]
This is `./meson.build`
```meson
project(
  'SomeProj',
  'cpp',
  version : '0.3.1',
  default_options : ['warning_level=3']
)

subdir('something')
somethinginc = include_directories('something')
cpp = meson.get_compiler('cpp')
add_languages('cpp')
somethingdep = declare_dependency(link_with: somethinglib)
atomicdep = cpp.find_library('atomic')
proj = executable('SomeProj', 'main.cpp', install: true, include_directories: somethinginc, dependencies: [somethingdep, atomicdep], link_with: somethinglib)
// ...
```
And this is `./something/meson.build`
```meson
files = run_command('files.sh').stdout().strip().split('\n')

foreach f: files
        install_headers(f)
endforeach

cpp = meson.get_compiler('cpp')
atomicdep = cpp.find_library('atomic')
somethinglib = shared_library('something', files, install: true, version: '0.1', dependencies: atomicdep)
```
When I compile project it seems fine. But when I type `./build/SomeProj`, it gives me `CANNOT LINK EXECUTABLE: could not load library "libsomething.so.0" needed by "./build/SomeProj"; caused by library "libsomething.so.0" not found` error.

**Comment by jpakkane** [comment]
Why are you linking to the library twice? Once with a dependency and a second time with `link_with`. Similarly, why are you adding `cpp` twice? You don't need to do `add_languages`, since you have already added it in `project`?

Also, what language is `something` implemented in? If it is in C, then you need to add C as a required language in your `project` call.

**Comment by CreatorVilius** [comment]
`something` is in C++. Not linking in declare dependency causes linking errors that there is no reference to `x::Y` in `something`. Same with not linking in executable.

**Comment by QuLogic** [comment]
You need to provide a _complete_ example, because linking generally works.

**Comment by CreatorVilius** [comment]
What do you mean 'complete example'?

**Comment by CreatorVilius** [comment]
Fixed this by changing from `shared_library` to `static_library` and removing all `.o`, `.so`, `.a`, `.0` files in build dir.
