### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by kterhorst** [mesonbuild/meson#6]
I have the following simple meson build file on windows and the visual studio 2013 toolchain:

project('wintest', 'cpp')
lib = shared_library('hello', 'hello.cpp')
prog = executable('prog', 'prog.cpp', link_with : lib, link_args : 'user32.lib')

Executing "meson . obj" yields:

[...]
  File "C:\work\meson\ninjabackend.py", line 1242, in generate_link
    commands += linker.get_soname_args(target.name, abspath, soversion)
TypeError: get_soname_args() takes 3 positional arguments but 4 were given

I fixed this by adding the "soversion" parameter to the function "get_soname_args"
in the "CCompiler" class:

 def get_soname_args(self, shlib_name, path, soversion):
        return []

When I run ninja I get the following output:

[2/5] Compiling cpp object hello.dir\hello.cpp.obj
FAILED: cl "/nologo" "/showIncludes" "/W3" "/MDd" "/Zi" "/Ob0" "/Od" "/RTC1" "/L
D" "-Ihello.dir"  /Fohello.dir\hello.cpp.obj /c ..\hello.cpp
..\hello.cpp : fatal error C1041: cannot open program database 'c:\work\meson\my
test\obj\vc120.pdb'; if multiple CL.EXE write to the same .PDB file, please use
/FS

I suggest adding "/FS" to the default C/C++ flags for parallel builds on Visual Studio 2013 and above.

Then when I run ninja a second time it shows:

LINK : warning LNK4044: unrecognized option '/LD'; ignored
LINK : warning LNK4044: unrecognized option '/Wl,-rpath,C:\work\meson\mytest\obj
"'; ignored

The option "/LD" is a compiler flag and shouldn't be passed to the linker.

Obviously the second warning shows a gcc compiler flags that isn't handled by the visual studio compiler.
I fixed this by adding the following code to the "VisualStudioCCompiler" class:

def build_rpath_args(self, build_dir, rpath_paths, install_rpath):
        return []

I hope this helps.

**Comment by jpakkane** [comment]
Closing this as old. If there are still issues please file a new bug with details. Thanks.
