### ISSUE TITLE
 windows build broken with 0.52.0

### ISSUE THREAD

**Issue by borg323** [mesonbuild/meson#6000]
We get a: 
```meson.build:182:2: ERROR: Search directory \usr\local\lib\tensorflow_cc is not an absolute path.```
This is from: 
```tf_tensorflow_lib = cc.find_library('libtensorflow_cc', dirs: tensorflow_libdir, required: false)```
and tensorflow_libdir is initialized through an array option with default value `['/usr/local/lib/tensorflow_cc/']`.

**Comment by jpakkane** [comment]
Would it be possible for you to bisect the problematic commit?

**Comment by borg323** [comment]
Bisecting leads to https://github.com/mesonbuild/meson/commit/fd7e8c540063870391e6ce75aa0fb179180fa057

**Comment by scivision** [comment]
On Windows, a leading-slash `/foo/bar` directory is not absolute. This ambiguity is handled correctly by Python 3 `pathlib`. As a guess, perhaps for legacy reasons `os.path.isabs` allowed this relative path to be treated as absolute. 

This might be something to put in a Meson `if 'linux'... elif 'windows' ...` statement.

**Comment by borg323** [comment]
@scivision do you mean that we should work around this in our [meson.build](https://github.com/LeelaChessZero/lc0/blob/master/meson.build) file? Sure we can work around it, but we provide default paths for lots of dependencies in out [meson_options.txt](https://github.com/LeelaChessZero/lc0/blob/master/meson_options.txt) to reduce command line options on unix/macos builds and depend on the paths being unavailable on windows.

This used to work fine so far and I would rather avoid complicating our scripts further for no real gain.

**Comment by borg323** [comment]
Moreover, paths starting with `/` may not be absolute under windows, but the objective (as I understand it) is to disallow paths relative to the source code, which is certainly not the case here.

**Comment by scivision** [comment]
OK perhaps a sensible Meson-internal workaround is to say if the target machine is Windows, just disregard the leading "/" paths as that's a Unix convention. That would keep the benefits of Pathlib without requiring further awkward Meson internal or end-user workarounds.

Thanks for providing that feedback!

**Comment by scivision** [comment]
@dcbaker would you suggest I do if "host_machine" is_windows since we would be finding the library on the host instead of the target? I want to keep in mind cross builds too.

**Comment by borg323** [comment]
I tested #6018 and it fixes this issue. Thank you for the quick response.

**Comment by scivision** [comment]
OK great to hear thanks again
