### ISSUE TITLE
WARNING: Unknown CPU family 'sun4u'

### ISSUE THREAD

**Issue by PalleLyckegaard** [mesonbuild/meson#6006]
While building glib2 on a Solaris 11.3 sun4u system (using pkgsrc) the following warning is issued:

WARNING: Unknown CPU family 'sun4u', please report this at https://github.com/mesonbuild/meson/issues/new with theoutput of `uname -a` and `cat /proc/cpuinfo`      

Output from 'uname -a': 
SunOS gcc-solaris11 5.11 11.3 sun4u sparc SUNW,SPARC-Enterprise

Output from /proc/cpuinfo is not possible since this is not available on a Solaris 11 system.

Output from the Solaris isainfo command:
sparcv9 sparc

Output from the Solaris isalist command:
sparcv9+fmuladd sparcv9+vis2 sparcv9+vis sparcv9 sparcv8plus+vis2 sparcv8plus+vis sparcv8plus sparcv8 sparcv8-fsmuld sparcv7 sparc

**Comment by dcbaker** [comment]
I'm assuming based on this information and [our table](https://mesonbuild.com/Reference-tables.html#cpu-families), this should map to `sparc64`, does that sound right?

**Comment by PalleLyckegaard** [comment]
Technically both 32-bit and 64-bit executables can run on sun4u, but I think modern use of sun4u is 64-bit, so mapping to sparc64 seems ok to me.

**Comment by dcbaker** [comment]
technically i686 executables can run on x86_64 too; so lets go with sparc64

**Comment by dcbaker** [comment]
I've opened a pull request and asked someone from oracle to look at the patch.
