### ISSUE TITLE
meson 0.52.0 infinitely recurses in get_transitive_build_target_deps

### ISSUE THREAD

**Issue by anitazha** [mesonbuild/meson#6008]
Discovered by @mrc0mmand in https://github.com/systemd/systemd/issues/13742, the latest version of meson is now calling `get_transitive_build_target_deps()` on the custom targets where it wasn't before. This causes some custom targets to recurse indefinitely in the function.
I believe the blame is https://github.com/mesonbuild/meson/commit/f95c965043221b2fc0e40c9410bd9efa88f31832 which makes this change:
```
meson_exe_cmd = self.as_meson_exe_cmdline(target.name, target.command[0], cmd[1:],
                                          for_machine=target.for_machine,
                                          extra_bdeps=target.get_transitive_build_target_deps(),
                                          capture=ofilenames[0] if target.capture else None)
```
which calls `get_transitive_build_target_deps` every time it goes through this path, when the previous version of the code would only call it for Windows-like environments.

**Comment by jpakkane** [comment]
This turned out to be an issue in the upstream project definition, which has now been fixed. Closing.

**Comment by anitazha** [comment]
Thanks for your help looking into this @jpakkane
