### ISSUE TITLE
Will subprojects automatically use the host machine CPU family of parent ?

### ISSUE THREAD

**Issue by boxerab** [mesonbuild/meson#6020]
I am currently seeing this [issue](https://gitlab.freedesktop.org/gstreamer/gstreamer-sharp/issues/24) where subprojects build as `x86` while parent is `x86_64`

Here is the output I get from the parent:

```
.The Meson build system
Version: 0.52.0
Source dir: c:\Users\aaron\src\gstreamer-sharp
Build dir: c:\Users\aaron\src\gstreamer-sharp\build
Build type: native build
Project name: gstreamer-sharp
Project version: 1.17.0.1
C compiler for the host machine: cl (msvc 19.16.27034)
C linker for the host machine: link 19.16.27034
C sharp compiler for the host machine: csc (csc 2.10.0.0)
Host machine cpu family: x86_64
Host machine cpu: x86_64
```

**Comment by xclaesse** [comment]
Yes, it should. You can run `ninja -v` to see if there are wrongs args passed to the compiler, to be sure.

**Comment by boxerab** [comment]
@xclaesse thanks, it looks like the problem lies with the subproject.
