### ISSUE TITLE
CMake subproject with MSVC generate many warnings D9025

### ISSUE THREAD

**Issue by SkyMaverick** [mesonbuild/meson#6021]
I use the CMake subproject in a project with cl-compiler and the ninja build system. The meson automatically puts the **/ZI** argument, but when parsing a subproject, it puts the **/Zi** argument. This causes many warnings D9025.

**Comment by xclaesse** [comment]
I think this is part of a bigger issue: We should pass to cmake all external args (e.g. cflags), especially when cross compiling, because cmake could need them to run its checks, etc. But then all those flags will end into the generated `shared_library(c_args: ...)` and meson will duplicate them all.

I think the solution is to add a new feature to Meson, `shared_library(..., plain : true)` where meson won't add any other compiler arguments.

**Comment by jpakkane** [comment]
Adding flags for people to workaround issues is not scalable. Making it work automatically is.

**Comment by xclaesse** [comment]
@jpakkane doesn't have to be part of meson's public API, could be an internal feature just for the cmake module.

**Comment by mensinda** [comment]
I don't think we need a specific feature for this. I would rather continue with the current argument [blacklist](https://github.com/mesonbuild/meson/blob/master/mesonbuild/cmake/interpreter.py#L84) approach and let meson handle those flags. Especially in this case where [debug information is controlled](https://docs.microsoft.com/en-us/cpp/build/reference/z7-zi-zi-debug-information-format?view=vs-2019). This is also how normal subprojects usually function unless the cargs are manually overwritten.

**Comment by mensinda** [comment]
@SkyMaverick Could you please upload (Pastebin, etc.) `build/meson-logs/meson-log.txt` and `build/subprojects/<your subproject>/meson.build` if it exists? This would help me identify where I have to blacklist flags.

**Comment by SkyMaverick** [comment]
@mensinda Done. 
Used by libuv and libutf8proc as cmake-subprojects. [meson-log.txt](https://pastebin.com/iZ4LV6xN), [libutf8proc meson.build](https://pastebin.com/ArqANAgX), [libuv meson.build](https://pastebin.com/kQ7AzzRY). 
Also uploaded [build.ninja](https://pastebin.com/vdjixFLV) and [ninja stdout](https://pastebin.com/3CkDen8X), if need.

**Comment by mensinda** [comment]
Should be fixed with #6025.
