### ISSUE TITLE
-Wl,-rpath-link for secondary dependencies causes linking failure when there are two prefixes

### ISSUE THREAD

**Issue by lantw44** [mesonbuild/meson#6027]
This is a regression of Meson 0.52.0. https://github.com/mesonbuild/meson/pull/5647 breaks it and reverting 7b9c348102792030859ed0001a51416506a0a092 fixes the problem. Tag the author @SoapGentoo and reviewers @jpakkane, @dcbaker and @textshell .

It is typical for a development environment to have at least two prefixes, one for the development work under the home directory and one for libraries installed on the system. We have to ensure that libraries under the development prefix is always preferred to libraries under the system prefix. Otherwise, the linker may report undefined reference errors because the version provided by the system may be too old.

The way https://github.com/mesonbuild/meson/pull/5647 adds `-Wl,-rpath-link` breaks the development environment managed by JHBuild seriously because everything linking to GLib is likely to trigger undefined reference errors with GNU ld. LLVM lld isn't affected because it just ignores `-Wl,-rpath-link`. There are two problems in the current implementation of `-Wl,-rpath-link` in `PkgConfigDependency`:

1. It only adds `-Wl,-rpath-link` for `secondary_libpaths`. It is possible for a secondary dependency to come from `prefix_libpaths`, so it should add `-Wl,-rpath-link` for `prefix_libpaths` as well. `prefix_libpaths` should come before `secondary_libpaths` because it should be preferred.
2. It appears on the command line too early. In file `mesonbuild/backend/ninjabackend.py`, class `NinjaBackend`, function `generate_link`, `linker.get_dependency_link_args` is called before `linker.build_rpath_args`. This means `-Wl,-rpath-link` arguments for external dependencies returned by `linker.get_dependency_link_args` come before `-Wl,-rpath-link` arguments for internal dependencies returned by `linker.build_rpath_args`, which is wrong because we should always prefer internal libraries to external libraries.

Let's see an example here. I was trying to build `pixman` with JHBuild.

 * The development prefix `/home/lantw44/gnome/devinstall/lib` has GLib, GTK, Pango, FriBidi.
 * The system prefix `/usr/local/lib` has PCRE, libintl, libiconv.

Here are the error messages:
```
FAILED: demos/gradient-test 
clang -B/home/lantw44/.local/bin  -o demos/gradient-test 'demos/03bf7ed@@gradient-test@exe/gradient-test.c.o' -L/home/lantw44/gnome/devinstall/lib -L/usr/local/lib -Wl,--as-needed -Wl,--no-undefined -march=corei7 -B/home/lantw44/.local/bin -pipe -g3 -Og -gz -fdebug-macro -B/home/lantw44/.local/bin -Wl,--compress-debug-sections=zlib -fuse-ld=bfd -Wl,--start-group demos/libdemo.a test/libtestutils.a pixman/libpixman-1.so.0.38.5 -Wl,-rpath-link,/usr/local/lib /home/lantw44/gnome/devinstall/lib/libglib-2.0.so -L/home/lantw44/gnome/devinstall/lib -lintl /home/lantw44/gnome/devinstall/lib/libgtk-x11-2.0.so /home/lantw44/gnome/devinstall/lib/libgdk-x11-2.0.so /home/lantw44/gnome/devinstall/lib/libpangocairo-1.0.so /home/lantw44/gnome/devinstall/lib/libatk-1.0.so /home/lantw44/gnome/devinstall/lib/libcairo.so /home/lantw44/gnome/devinstall/lib/libgdk_pixbuf-2.0.so /home/lantw44/gnome/devinstall/lib/libgio-2.0.so /home/lantw44/gnome/devinstall/lib/libpangoft2-1.0.so /home/lantw44/gnome/devinstall/lib/libpango-1.0.so /home/lantw44/gnome/devinstall/lib/libgobject-2.0.so /usr/local/lib/libintl.so /home/lantw44/gnome/devinstall/lib/libharfbuzz.so /usr/local/lib/libfontconfig.so /usr/local/lib/libfreetype.so -fopenmp -Wl,-rpath-link,/usr/local/lib -L/home/lantw44/gnome/devinstall/lib -lintl /usr/local/lib/libpng16.so /usr/lib/libz.so -lm -Wl,--end-group -fopenmp -fopenmp '-Wl,-rpath,$ORIGIN/:$ORIGIN/../test:$ORIGIN/../pixman' -Wl,-rpath-link,/home/lantw44/gnome/build/pixman/demos -Wl,-rpath-link,/home/lantw44/gnome/build/pixman/test -Wl,-rpath-link,/home/lantw44/gnome/build/pixman/pixman
/usr/local/bin/ld.bfd: /home/lantw44/gnome/devinstall/lib/libpango-1.0.so: undefined reference to `fribidi_get_par_embedding_levels_ex'
/usr/local/bin/ld.bfd: /home/lantw44/gnome/devinstall/lib/libpango-1.0.so: undefined reference to `fribidi_get_bracket'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Function `_set_libs` of class `PkgConfigDependency` calls `pkg-config` three times, and here are results under the JHBuild environment.

This is `out`.
```
$ PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 pkg-config --libs glib-2.0
-L/home/lantw44/gnome/devinstall/lib -lglib-2.0 -lintl
```

This is `out_raw`.
```
$ pkg-config --libs glib-2.0 
-L/home/lantw44/gnome/devinstall/lib -lglib-2.0 -lintl 
```

This is `out_all`.
```
$ pkg-config --libs glib-2.0 --static
-L/home/lantw44/gnome/devinstall/lib -lglib-2.0 -lintl -pthread -liconv -L/usr/local/lib -lpcre -D_THREAD_SAFE -pthread
```

We can see that `-L/usr/local/lib` only appers in `out_all`, so we have:
 * `prefix_libpaths = ['/home/lantw44/gnome/devinstall/lib']`
 * `secondary_libpaths = ['/usr/local/lib']`
 * `system_libpaths = []`

They get translated to command line arguments as `-Wl,-rpath-link,/usr/local/lib -L/home/lantw44/gnome/devinstall/lib`.

Assume that there is an executables which need both GLib and GTK. Meson processes GLib first and put `-Wl,-rpath-link,/usr/local/lib -L/home/lantw44/gnome/devinstall/lib` on the command line. Therefore, when the linker searches for direct dependencies, it finds `/home/lantw44/gnome/devinstall/lib` first. However, when the linker searches for secondary dependencies, it finds `/usr/local/lib` first. This means that the system prefix is now even more important than the project itself because it comes before `-Wl,-rpath-link,/home/lantw44/gnome/build/pixman/demos -Wl,-rpath-link,/home/lantw44/gnome/build/pixman/test -Wl,-rpath-link,/home/lantw44/gnome/build/pixman/pixman` added by `linker.build_rpath_args`.

This is obviously wrong. The result is that the linker finds FriBidi from the wrong directory and report undefined reference errors. GTK needs Pango, and Pango needs FriBidi. The linker finds both GTK and Pango correctly because they are direct dependencies, but it finds FriBidi wrongly because it is a secondary dependency. It should find the one installed in `/home/lantw44/gnome/devinstall/lib`, not `/usr/local/lib`.

I think the solution is to
1. Add `-Wl,-rpath-link` for both `prefix_libpaths` and `secondary_libpaths`.
2. Separate `-Wl,-rpath-link` from other arguments, so they can be added in the correct order.

**Comment by SoapGentoo** [comment]
Doing points 1. seems easy, how do you want to accomplish point 2.?

**Comment by lantw44** [comment]
I just thought of a case where point 1 might be insufficient. Assume that an executable needs two libraries. One is installed in `/usr/local/lib`, and the other one is installed in `/home/lantw44/gnome/devinstall/lib`. If the first one puts `-Wl,-rpath-link,/usr/local/lib` and the second one puts `-Wl,-rpath-link,/home/lantw44/gnome/devinstall/lib`, it may cause problems for secondary dependencies of the second library when `-Wl,-rpath-link,/usr/local/lib` appears first. Does meson know how to sort dependencies with `PKG_CONFIG_PATH`?

In a JHBuild environment, JHBuild controls the search order of direct dependencies with `LDFLAGS=-L/home/lantw44/gnome/devinstall/lib -L/usr/local/lib` and the search order of secondary dependencies with `LD_LIBRARY_PATH=/home/lantw44/gnome/devinstall/lib:/usr/local/lib`, so there was no `-Wl,-rpath-link` pointing to the outside of the build tree. Now it stops working because `-Wl,-rpath-link` added by meson overrides `LD_LIBRARY_PATH`.

For point 2, I think the least risky way is to tell `generate_link` to filter out `-Wl,-rpath-link` and move them to the bottom, but it will make the code of `generate_link` look ugly. Another possible way is to make `get_dependency_link_args` return a `(normal flags, rpath link flags)` tuple, so `generate_link` can decide how to use them.

**Comment by textshell** [comment]
I wonder in what situation rpath-link needs to be in an order that is different to normal runtime rpath. I.e. can we take some hints from rpath construction?

Sadly rpath-link is a mess. i still have the nagging feeling with should just `--allow-shlib-undefined` this from space to make this all go away.

You say lld does not trigger this. Can you try to find out why? I.e. does it just silently always use `--allow-shlib-undefined` semantics? Some thing different?

**Comment by lantw44** [comment]
> I wonder in what situation rpath-link needs to be in an order that is different to normal runtime rpath. I.e. can we take some hints from rpath construction?

I think yes, they should be the same, but currently meson only handles `-rpath` for internal libraries. External libraries found by `-L` flags returned by pkg-config are not added to `-rpath` (unless pkg-config only returns one `-l` flag, which I consider it as a bug: https://github.com/mesonbuild/meson/pull/4324). Users can set `LD_LIBRARY_PATH` to find external libraries, but doing so may trigger another bug: https://github.com/mesonbuild/meson/issues/1635.

If meson is going to use `-L` flags to construct `-rpath`, beware that pkgconf doesn't sort `-L` flags. This is probably a bug. I just reported it to pkgconf todayL https://todo.sr.ht/~kaniini/pkgconf/7. I also attempted to fix the order in meson by sorting `-L` by `PKG_CONFIG_PATH`: https://github.com/mesonbuild/meson/pull/4325. But this still doesn't help the issue I mentioned in https://github.com/mesonbuild/meson/issues/6027#issuecomment-541334015, which requires meson to find the order working for all dependencies instead of just one dependency.

> Sadly rpath-link is a mess. i still have the nagging feeling with should just `--allow-shlib-undefined` this from space to make this all go away.

But doing so does not help when building an executable, right?

> You say lld does not trigger this. Can you try to find out why? I.e. does it just silently always use `--allow-shlib-undefined` semantics? Some thing different?

lld ignores `-rpath-link`. It recognizes it for compatibility with GNU ld, but it does nothing when `-rpath-link` is used. https://reviews.llvm.org/D18269

**Comment by textshell** [comment]
I think the key take-away from that PR is this:
> I agree with your argument that we should ignore that option. gold completely ignores that option, and the GNU ld's behavior to try to resolve undefined symbols in all shared object files at (static-)link time seems broken to me.
(from https://reviews.llvm.org/D18269#378717)

What does meson loose if we just ask ld.bfd nicely to do the same thing as lld (and possibly ld.gold)? Is the build really in the business of trying to verify that system/prefix installed libraries' dependencies actually match? Can a build even really know?

**Comment by lantw44** [comment]
I ran `grep` on a few autotools and cmake build directories, and I didn't find any use of `-rpath-link` there. Probably they just assume users will set `LD_LIBRARY_PATH` themselves to satisfy the need of ld.bfd, but setting `LD_LIBRARY_PATH` can create problems for cmake and meson.
