### ISSUE TITLE
regression: nuisance warning for gfortran

### ISSUE THREAD

**Issue by scivision** [mesonbuild/meson#6050]
@mensinda git bisect reveals
b1b8a7a7e356297741c3c8e5996928ff244578c8 is the first bad commit  that introduced spurious warning:

```
WARNING: No include directory found parsing "gfortran -xfortran -E -v -" output
```

This occurs with Linux and Windows (at least) with at least Gfortran 7 and 9.

This occurs for any trivial Fortran target.

**Comment by mensinda** [comment]
Should be fixed with #6053
