### ISSUE TITLE
So. Anyone working on the "meson init" command?

### ISSUE THREAD

**Issue by michaelbadcrumble** [mesonbuild/meson#6056]
So. Anyone working on the "meson init" command?  Wondering because one I have not seen any new features added for that like can generate Dlang, Java or Rust projects for example and second I have a new tool in mine but need to know if the `meson init` command is being worked on first.

**Comment by jpakkane** [comment]
No-one is working on it as such, but if people want to submit e.g. new language projects, pull requests are welcome.

**Comment by michaelbadcrumble** [comment]
I would be happy to get working on the `meson init` command.  😋
But really quick question, do the templates have to be backward compatible with older versions of Meson, tack advantage of new features of Meson or just make them generic no matter what the language and platform?
