### ISSUE TITLE
Meson 0.52.0: ERROR: Unable to determine dynamic linker. (Dlang, MacOS)

### ISSUE THREAD

**Issue by michaelbadcrumble** [mesonbuild/meson#6075]
I'm not sure if anyone else is having this problem but I tried to build a Dlang project and got the following console output as my result.  Before we look at that I would like to inform you that I did some trouble shooting simply by getting a new `dmd` Dlang compiler after trying to use the one that was installed also this is on the Mac.   

```console
Build started at 2019-10-18T15:18:42.928969
Main binary: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7
Build Options: 
Python system: Darwin
The Meson build system
Version: 0.52.0
Source dir: /Users/shnitzel/Developer/templates/dlang/d-program
Build dir: /Users/shnitzel/Developer/templates/dlang/d-program/builddir
Build type: native build
Project name: d-exe
Project version: 0.1.0

meson.build:15:0: ERROR: Unable to determine dynamic linker.
```

**Comment by bioinfornatics** [comment]
Hi @michaelbadcrumble , I am not a meson developer. But i see your message and maybe we can try one two think.

If you use ldc compiler based on llvm, maybe somewhere on your system you have a tool named `<SOME_WHERE>/bin/lld`. In a such case try `export PATH=<SOME_WHERE>/bin/lld:$PATH`

Il you use another D compiler you have to search a tool named `ld` and edit the `PATH` accordingly.

Mac OS by default is llvm based so I think `lld` is installed somewhere on your system

good luck

**Comment by michaelbadcrumble** [comment]
Ok @bioinfornatics but what should I do if I use the provided `dmd` compiler for macOS with a .dmg file.

**Comment by baryluk** [comment]
@bioinfornatics `PATH` should list of directories, `/bin/lld` is not a directory.

You could try doing export `LD=lld` maybe?

**Comment by dcbaker** [comment]
I taught meson about different linkers in 0.52.0, and I didn't do a very good job with D. Right now I'm trying to improve a bunch of the shortcomings of that work for 0.53 (it's going to be too big of a set of changes for 0.52.x). This is on the list of things for me to fix for 0.53

**Comment by michaelbadcrumble** [comment]
Would this help?  #6249

**Comment by michaelbadcrumble** [comment]
Anything on the dynamic linker issue @dcbaker ?

**Comment by michaelbadcrumble** [comment]
So @dcbaker .  What is the current status on this issue?

**Comment by denizzzka** [comment]
Same issue for static bare metal compilation.

I want to use `arm-none-eabi-ld` linker with `ldc2` and isn't know how to setup this. Dynamic linker just isn't need for me.

**Comment by michaelbadcrumble** [comment]
I believed I viewed that issue, which seems important.  I would like to add that the `GDC` compiler is not working on Mac OS X, based on the results produced from my dummy D project.

This is with Meson 0.53.1.

**Comment by nawordar** [comment]
I use Meson 0.54.3 and still have this problem.

I am trying to cross compile a C++ project with D subproject with 64 bit Linux system as a build machine and 32 bit Windows as a host machine.

```
❯ meson build_win32 --cross-file=cross/lin64-win32.conf
The Meson build system
Version: 0.54.3
Source dir: /home/nawordar/projects/foodin
Build dir: /home/nawordar/projects/foodin/build_win32
Build type: cross build
Project name: foodin
Project version: 0.1
C++ compiler for the build machine: ccache c++ (gcc 10.1.0 "c++ (GCC) 10.1.0")
C++ linker for the build machine: c++ ld.bfd 2.34.0
C++ compiler for the host machine: i686-w64-mingw32.static-g++ (gcc 5.5.0 "i686-w64-mingw32.static-g++ (GCC) 5.5.0")
C++ linker for the host machine: i686-w64-mingw32.static-g++ ld.bfd 2.28
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86
Host machine cpu: i686
Target machine cpu family: x86
Target machine cpu: i686
WARNING: rcc dependencies will not work reliably until this upstream issue is fixed: https://bugreports.qt.io/browse/QTBUG-45460
Found pkg-config: /home/nawordar/clones/mxe/usr/bin/i686-w64-mingw32.static-pkg-config (0.28)
Run-time dependency qt5 (modules: Core, Gui, Sql, Widgets) found: YES 5.15.0 (pkg-config)
Detecting Qt5 tools
 moc: YES (/home/nawordar/clones/mxe/usr/i686-w64-mingw32.static/qt5/bin/moc, 5.15.0)
 uic: YES (/home/nawordar/clones/mxe/usr/i686-w64-mingw32.static/qt5/bin/uic, 5.15.0)
 rcc: YES (/home/nawordar/clones/mxe/usr/i686-w64-mingw32.static/qt5/bin/rcc, 5.15.0)
 lrelease: YES (/usr/bin/lrelease-qt5, 5.15.0)

|Executing subproject libfoodin method meson 
|
|Project name: libfoodin
|Project version: 0.0.1
|D compiler for the build machine: ldc2 (llvm 1.22.0 "LDC - the LLVM D compiler (1.22.0):")
|D linker for the build machine: ldc2 ld.gold 2.34.0

subprojects/libfoodin/meson.build:1:0: ERROR: Unable to determine dynamic linker

A full log can be found at /home/nawordar/projects/foodin/build_win32/meson-logs/meson-log.txt
```

`cross/lin64-win32.conf`:  
```
[properties]
sizeof_int = 4
sizeof_wchar_t = 4
sizeof_void* = 4

alignment_char = 1
alignment_void* = 4
alignment_double = 4

has_function_printf = true


[host_machine]
system = 'windows'
cpu_family = 'x86'
cpu = 'i686'
endian = 'little'


[binaries]
ar = 'i686-w64-mingw32.static-ar'
c = 'i686-w64-mingw32.static-gcc'
cpp = 'i686-w64-mingw32.static-g++'
d = '/home/nawordar/apps/ldc2/bin/ldc2'
ld = 'i686-w64-mingw32.static-ld.bfd'
pkgconfig = 'i686-w64-mingw32.static-pkg-config'
strip = 'i686-w64-mingw32.static-strip'
```
