### ISSUE TITLE
CMake subprojects ignore system include directories

### ISSUE THREAD

**Issue by Visse** [mesonbuild/meson#6079]
I recently tried adding a subproject using the cmake module in meson, but meson fails to compile it, while cmake compiles it fine.

The subproject in question uses the compile flags `-Wall` and `-Werror` and includes some files that emits warnings when compiled with `-Wall` - however the include directory is marked as `SYSTEM` in cmake, making the warnings suppressed.

But when compiling it as a cmake module under meson, the include directory is no longer marked as system and causing warnings to be emitted making the build fail (due to `-Werror`)

I created a simple project to reproduce the problem:
[meson-cmake-bug.zip](https://github.com/mesonbuild/meson/files/3746802/meson-cmake-bug.zip)
(note that in the "real" project, the system include is a subdirectory in `/usr/include`)

The cmake file:
```CMake
add_library(my_lib lib.cpp)
target_compile_options(my_lib PRIVATE "-Wall" "-Werror")
target_include_directories(my_lib SYSTEM PRIVATE "system-include/")
```
In meson I have:
```meson
cmake = import('cmake')
cmake.subproject('my-lib')
``` 

Output when building with cmake:
[cmake-build-output.txt](https://github.com/mesonbuild/meson/files/3746810/cmake-build-output.txt)

```console
$ cmake -S subprojects/my-lib/ -B cmake-build -G Ninja && ninja -C cmake-build
[...]
[1/2] Building CXX object CMakeFiles/my_lib.dir/lib.cpp.o
[2/2] Linking CXX static library libmy_lib.a
```

Output when building with meson:
[meson-build-output.txt](https://github.com/mesonbuild/meson/files/3746813/meson-build-output.txt)
```console
$ meson meson-build && ninja -C meson-build
[...]
[1/2] Compiling C++ object 'subprojects/my-lib/4511509@@my_lib@sta/lib.cpp.o'.
FAILED: subprojects/my-lib/4511509@@my_lib@sta/lib.cpp.o 
c++ -Isubprojects/my-lib/4511509@@my_lib@sta -Isubprojects/my-lib -I../subprojects/my-lib -I../subprojects/my-lib/system-include -Isubprojects/my-lib/__CMake_build -I../subprojects/my-lib/__CMake_build -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -g -Wall -Werror -MD -MQ 'subprojects/my-lib/4511509@@my_lib@sta/lib.cpp.o' -MF 'subprojects/my-lib/4511509@@my_lib@sta/lib.cpp.o.d' -o 'subprojects/my-lib/4511509@@my_lib@sta/lib.cpp.o' -c ../subprojects/my-lib/lib.cpp
In file included from ../subprojects/my-lib/lib.cpp:1:
../subprojects/my-lib/system-include/file-with-warnings.h: In function ‘int Bar(Foo)’:
../subprojects/my-lib/system-include/file-with-warnings.h:12:11: error: enumeration value ‘World’ not handled in switch [-Werror=switch]
     switch(foo) {
           ^
```

```console
$ meson --version
0.52.999
$ cmake --version
cmake version 3.13.4
$ gcc --version
gcc (Ubuntu 8.3.0-6ubuntu1) 8.3.0
```

**Comment by mensinda** [comment]
Unfortunately, CMake subprojects don't understand the concept of system includes currently. Until support for this is implemented, I recommend trying to disable the `-Werror` flag with a (hopefully existing) variable in the CMakeLists.txt. See `cmake_options` [here](https://mesonbuild.com/CMake-module.html).

Also, meson should probably filter out all warning related flags from CMake, since warnings are controlled project-wide anyway.

**Comment by mensinda** [comment]
@Visse your project should at least compile with #6081, even if system includes aren't handled yet.
