### ISSUE TITLE
wrong link instruction in D language

### ISSUE THREAD

**Issue by bioinfornatics** [mesonbuild/meson#6086]
Dear,

currently the shared_library statement generate this:
```
-L-soname,libFoo.so.1 
```

While at least with the ldc 2 compiler should be

```
-soname libFoo.so.1 
```

If you have a workaround until this issue is fixed it would be really appreciated

thanks

Known awesome D meson maintainer @dcbaker  @Ericson2314 @astavale  @ximion  @GoaLitiuM @jpakkane @mensinda @myfreeweb 

thanks for your contribution

**Comment by bioinfornatics** [comment]
To add additional information I see that soname is set from `linker.py` line [489](https://github.com/mesonbuild/meson/blob/b6af3f38102d57197fbd365d1b2fa57a56c5f457/mesonbuild/linkers.py#L489) and islinker.py line [114](https://github.com/mesonbuild/meson/blob/5dfd054c3204ec56aa3e10a632e8475a66a4bb30/mesonbuild/compilers/mixins/islinker.py#L114) and d.py line [391](https://github.com/mesonbuild/meson/blob/b6af3f38102d57197fbd365d1b2fa57a56c5f457/mesonbuild/compilers/d.py#L391)

**Comment by russel** [comment]
I tried manually running the link step with the -soname change but got:
```
Error: -soname can be used only when building a shared library
```
so I am assuming there is something else wrong as well.

**Comment by GoaLitiuM** [comment]
There seems to be a bigger issue with how the linker args are translated currently. Some of the new arguments like `/FORCE:UNRESOLVED` does not get correctly translated, resulting in errors like these:
```Error: module `FORCE:UNRESOLVED` is in file '\FORCE:UNRESOLVED.d' which cannot be read```
...and for shared libraries:
```LINK : fatal error LNK1561: entry point must be defined```

So much code has change since the last time I touched any of this, so I can't really even begin where to start to fix these issues.

**Comment by ximion** [comment]
Oh, Mesons D support has never really been tested on Windows and probably needs some serious work and testing to be useful.

**Comment by dcbaker** [comment]
Can someone retest this with latest master, I think this is resolved now.

**Comment by Cogitri** [comment]
@dcbaker At least in my D projects which use executables, shared- & static_library it works without problems with LDC, DMD and GDC now, thank you!

**Comment by dcbaker** [comment]
Awesome, I'm going to close this then.
