### ISSUE TITLE
Add a way for Meson to find “curses” generically 

### ISSUE THREAD

**Issue by michaelbadcrumble** [mesonbuild/meson#6096]
Add a way for Meson to find `curses` generically.

There are definitely different names for `curses` library but what about a generic `curses_dep = dependency(‘curses’)` for finding the correct `curses` libraries like what Meson does with threads.

**Comment by scivision** [comment]
This would most likely  have to be added in https://github.com/mesonbuild/meson/blob/master/mesonbuild/dependencies/misc.py

Here is a meson.build snippet I use to find various Curses libraries, including Ncurses and PDcurses:

```meson
curses = dependency('ncurses', required: false, disabler: true)
if not curses.found()
  curses_root = get_option('curses_root')
  curses_lib = cc.find_library('curses', dirs : curses_root, required : false, disabler: true)
  curses = declare_dependency(include_directories: curses_root, dependencies: curses_lib)
endif
```

The full program is at https://github.com/fortran-gaming/tetran/blob/master/meson.build

**Comment by scivision** [comment]
Note, I just made PDcurses buildable by Meson: https://github.com/wmcbrine/PDCurses/pull/78/files

I also updated my example [Tetran](https://github.com/fortran-gaming/tetran/) program to automatically use PDcurses as a Meson subproject if Curses isn't found on the system.
