### ISSUE TITLE
Add Xcode module.

### ISSUE THREAD

**Issue by michaelbadcrumble** [mesonbuild/meson#6107]
Add Xcode module.  This module should provide Xcode related functionality allows iOS, iPadOS, MacOS SDK’s to be found and used in any of apple’s projects built with Meson.

Not an absolute thing just a sketch of the Xcode module.
```meson
xcode_mod = import('xcode')

sdk_dep = xcode_mod.get_ios_sdk('ios sdk version')
xcode_mod.get_ios_arch(['ios device architecture')

executable('app name', ‘source files', dependencies: sdk_dep, ...)
```
The architecture method would be used to provide a value for what IOS Phone simulator to run.

The best support for this should probably go to Objective-c, Objective-c++ and Swift.

**Comment by jpakkane** [comment]
As a quick note, the device architecture should go in the cross file and be available via `host_machine`. There should be one, and only one, way of getting it and it should work the same on all platforms, not just ios.

**Comment by michaelbadcrumble** [comment]
I was not trying to say that iOS was only device.  Here is a clearer picture of what I was thinking, cross file information can still work but with Xcode module you can have a simulator for iOS Phone, iPadOS, WatchOS and TvOS.

```meson
xcode_mod = import('xcode')

xcode_mod.platform_arch(host_machine: 'apple device name')

executable('app name', ‘source files', dependencies: sdk_dep, ...)
```
