### ISSUE TITLE
Installing from source fails

### ISSUE THREAD

**Issue by er-cpp** [mesonbuild/meson#6117]
I followed the instruction in Readme.md, here's what I get:

```
~/src/meson $ sudo python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 24, in <module>
    from setuptools import setup
ModuleNotFoundError: No module named 'setuptools'

```

**Comment by scivision** [comment]
This should be fixed by #6119 

In the meantime, please try from the "meson" directory:

```sh
python3 -m pip install setuptools

python -m pip install .
```

**Comment by er-cpp** [comment]
>
> $ sudo apt install python3-pip
>


> ~/src/meson $ python3 -m pip install setuptools
> Collecting setuptools
>   Downloading
> https://files.pythonhosted.org/packages/d9/de/554b6310ac87c5b921bc45634b07b11394fe63bc4cb5176f5240addf18ab/setuptools-41.6.0-py2.py3-none-any.whl
> (582kB)
>     100% |████████████████████████████████| 583kB 1.2MB/s
> Installing collected packages: setuptools
> Successfully installed setuptools-41.6.0
>


> ~/src/meson $ sudo python -m pip install
> /usr/bin/python: No module named pip
>

~/src/meson $ sudo python3 setup.py install
>

~/src/meson $ meson --version
> 0.52.999
>

**Comment by scivision** [comment]
sorry, that should be

```sh
python3 -m pip install .
```

to ensure Python 3.x is used. Thanks
