### ISSUE TITLE
Warning: Unknown CPU family 'alpha'

### ISSUE THREAD

**Issue by cyborgyn** [mesonbuild/meson#6118]
Meson version 0.51.2

uname -a
Linux alfonse 4.19.66-gentoo-alfonse-21 #7 SMP Thu Oct 31 01:04:41 CET 2019 alpha EV68AL Tsunami GNU/Linux

cat cpuinfo
cpu                     : Alpha
cpu model               : EV68AL
cpu variation           : 7
cpu revision            : 0
cpu serial number       :
system type             : Tsunami
system variation        : Catamaran
system revision         : 0
system serial number    : AY40800422
cycle frequency [Hz]    : 833333333
timer frequency [Hz]    : 1024.00
page size [bytes]       : 8192
phys. address bits      : 44
max. addr. space #      : 255
BogoMIPS                : 1651.72
kernel unaligned acc    : 0 (pc=0,va=0)
user unaligned acc      : 0 (pc=0,va=0)
platform string         : COMPAQ AlphaServer DS20E 833 MHz
cpus detected           : 2
cpus active             : 2
cpu active mask         : 0000000000000003
L1 Icache               : 64K, 2-way, 64b line
L1 Dcache               : 64K, 2-way, 64b line
L2 cache                : 8192K, 1-way, 64b line
L3 cache                /a

Anyways, it builds and runs successfully, with gcc 8.3:
C compiler for the host machine: alpha-unknown-linux-gnu-gcc (gcc 8.3.0 "alpha-unknown-linux-gnu-gcc (Gentoo 8.3.0-r1 p1.1) 8.3.0")

Just reporting, since the configure phase asked so. :)
Best regards!

**Comment by scivision** [comment]
You're possibly in luck--this should have corrected this issue:
https://github.com/mesonbuild/meson/pull/6044

Could you try using Meson from the `master` Git branch?  Thanks for reaching out

**Comment by scivision** [comment]
@cyborgyn I didn't hear if Meson git master branch worked for you--i will assume so since Alpha CPU support was added there. 

To help declutter the issues I'll tentatively close this issue. Please reopen an issue if Alpha isn't working with Meson git master branch. Thanks
