### ISSUE TITLE
Arduino?

### ISSUE THREAD

**Issue by vinipsmaker** [mesonbuild/meson#612]
Is there a way to use Meson to build/send stuff to Arduino? In the plans? Do you think there is another project which is more appropriate than Meson to have this?

**Comment by jpakkane** [comment]
We do not yet have support for Arduino, so I went out and bought one. The WIP demo project is [here](https://github.com/jpakkane/mesonarduino). It currently compiles and uploads but the result does not work. Debugging tips are appreciated.

Note that currently it hardcodes my path in the upload command so you need to change that if you try it yourself. The proper fix requires some changes to `run_command` which I hope to get done soonish.

**Comment by jpakkane** [comment]
Once #618 lands it will work.

**Comment by vinipsmaker** [comment]
> Once #618 lands it will work.

Okay, I'll test on my Arduino Leonardo once it lands. Thanks for the fast response.

**Comment by jpakkane** [comment]
You can test that mr already if you want. Just checkout the branch in question. You will need to change the compiler arguments in the cross file to match your setup. The easiest way is to copy the cross file to a new name and change them. If you get it working, please send me the cross file so I can put it in the sample repo for other people to use.

Thanks,
