### ISSUE TITLE
Windows 10 / 64-bit fails linking (MSVC)

### ISSUE THREAD

**Issue by jfinkhaeuser** [mesonbuild/meson#6152]
**Environment**

1. Windows 10
1. MSVC (with Windows 10 SDK), activated via `vcvars64.bat`
1. Meson 0.52.0 installed via `pip`.
1. A C++ static library meson project.

**Expected**
Static library links.

**Actual**

1. Object files built for the `x64` machine type (as reported by `dumpbin /headers`)
1. The linker (`lib.exe`) errors out, complaining that it's trying to link `x64` objects into a `x86` target. Verifying the command line, `lib` gets run with `/MACHINE:x86`, which at least seems to make `lib` behave sensibly.

**Additional Information**

Running meson either via a 32- or 64-bit Python seems to make no difference. Either way, meson reports the build and host machine as `x86` where I'd expect `x86_64`. If that gets passed on to `lib`, that would possibly explain the issue.

**Comment by jfinkhaeuser** [comment]
Also, I'd be happy to know this is a usage error - but I'm running out of different ways to approach the situation. My last resort is to try an explicit cross compilation to 64 bit, but that seems to be a bit silly.

**Comment by lb90** [comment]
This seems to be a duplicate of #6128. Try setting the environment variable VSLANG=1033 before running Meson:

`> set VSLANG=1033`

**Comment by jfinkhaeuser** [comment]
Thanks! It doesn't seem to make any difference immediately, but it gives me a few things to try out.

**Comment by jfinkhaeuser** [comment]
I'll close this and continue over there - didn't find it while searching, though.
