### ISSUE TITLE
Link fails due to -rpath-link,/usr/lib

### ISSUE THREAD

**Issue by Salamandar** [mesonbuild/meson#6154]
I have `dir_a/libA.so` providing `symbol_a` and `dir_b/libB.so` linked with libA and using `symbol_a`.

When linking with libB, I have this error : 
```
/usr/bin/ld : dir_b/libB.so : référence indéfinie vers « symbol_a »
```

The linking cli contains `-Wl,-rpath-link,/project/_build/dir_a`, that's good. But it's specified AFTER the `dir_b/libB.so` linking argument. It should be BEFORE so that ld finds libA while linking with libB.

**Comment by Salamandar** [comment]
Actually what I say is not exact.

Here libgimpwidgets.so depends on libgimpconfig.so :

```
cc  \
  \
-o  \
libgimpwidgets/test-eevl  \
'libgimpwidgets/669d51a@@test-eevl@exe/test-eevl.c.o' \
-Wl,--as-needed \
-Wl,--no-undefined  \
-Wl,-O1 \
-Wl,--start-group \
libgimpwidgets/libgimpwidgets-3.0.so.0.0.1  \
/usr/lib/libglib-2.0.so \
-Wl,-rpath-link,/usr/lib/../lib \
/usr/lib/libgtk-3.so  \
/usr/lib/libgdk-3.so  \
/usr/lib/libz.so  \
/usr/lib/libpangocairo-1.0.so \
/usr/lib/libpango-1.0.so  \
/usr/lib/libharfbuzz.so \
/usr/lib/libatk-1.0.so  \
/usr/lib/libcairo-gobject.so  \
/usr/lib/libcairo.so  \
/usr/lib/libgdk_pixbuf-2.0.so \
/usr/lib/libgio-2.0.so  \
/usr/lib/libgobject-2.0.so  \
-Wl,--end-group \
'-Wl,-rpath,$ORIGIN/:$ORIGIN/../libgimpbase:$ORIGIN/../libgimpcolor:$ORIGIN/../libgimpconfig:$ORIGIN/../libgimpmath'  \
-Wl,-rpath-link,/home/felix/tmp/gimp/_build/libgimpwidgets  \
-Wl,-rpath-link,/home/felix/tmp/gimp/_build/libgimpbase \
-Wl,-rpath-link,/home/felix/tmp/gimp/_build/libgimpcolor  \
-Wl,-rpath-link,/home/felix/tmp/gimp/_build/libgimpconfig \
-Wl,-rpath-link,/home/felix/tmp/gimp/_build/libgimpmath \
```
does not work.

But removing the `-Wl,-rpath-link,/usr/lib/../lib` completely fixes the issue. It looks like it has broken a lot of things.

**Comment by jpakkane** [comment]
Can you test if #6156 fixes the issue for you?

**Comment by Salamandar** [comment]
I'll try that when I come back to work (wednesday). If you don't hear from me next week please ping me :)

**Comment by Salamandar** [comment]
I could test it today, and I confirm the PR works fine. I didn't read the linker line, though.
