### ISSUE TITLE
i18n.merge_file results in a confusing error with gettext missing

### ISSUE THREAD

**Issue by whot** [mesonbuild/meson#6165]
Where gettext is missing, use of `i18n.merge_file` results in
```
ERROR: Tried to assign an invalid value to variable.
```
This is a bit confusing, doubly so because it doesn't have a reference to why this is happening.

Turns out there is a "gettext is missing" warning but that warning may be a few miles off screen by the time the error is hit. I didn't actually notice the warning until I wrote the reduced meson.build for the bug report.

Minimal reproducer in a container:
```
$ podman run --rm -i -t  fedora:latest /bin/bash
$ dnf install -y --quiet meson
$ mkdir test && cd test
$ echo > meson.build <<EOF
project('test')

i18n = import('i18n')
foo = i18n.merge_file(input: 'input.in', output: 'output', type: 'desktop',
		      po_dir: 'po', install: true)
EOF
$ meson build
[...]
WARNING: Gettext not found, all translation targets will be ignored.
[...]
meson.build:4:0: ERROR: Tried to assign an invalid value to variable.
```
It'd be useful to have the error complain that the target was disabled or something.

**Comment by jon-turney** [comment]
It looks like #5758 tries to address this, but doesn't cover the case where the value of `i18n.merge_file()` is used (which doesn't appear anywhere in our test cases at the moment)

**Comment by caverym** [comment]
I'm still having this issue, with gcc and every "depends" libraries and packages, meson and ninja installed both in Python3 and in Homebrew, gettext installed in Homebrew.
I am trying to compile [Pulseeffects](https://github.com/wwmm/pulseeffects), I may have to put an issue there is there isn't one already, and if this isn't an issue with meson. The only thing that confuses me is that there's no `i18n.merge_fils()`

```Lavandula:pulseeffects avery$ meson _build
The Meson build system
Version: 0.54.0
Source dir: /Users/avery/Documents/git/pulseeffects
Build dir: /Users/avery/Documents/git/pulseeffects/_build
Build type: native build
Project name: pulseeffects
Project version: 4.7.2
C compiler for the host machine: cc (clang 11.0.3 "Apple clang version 11.0.3 (clang-1103.0.32.29)")
C linker for the host machine: cc ld64 556.5
C++ compiler for the host machine: c++ (clang 11.0.3 "Apple clang version 11.0.3 (clang-1103.0.32.29)")
C++ linker for the host machine: c++ ld64 556.5
Host machine cpu family: x86_64
Host machine cpu: x86_64
Configuring config.h using configuration
WARNING: Gettext not found, all translation targets will be ignored.

data/meson.build:45:0: ERROR: Tried to assign an invalid value to variable.

A full log can be found at /Users/avery/Documents/git/pulseeffects/_build/meson-logs/meson-log.txt```


[meson-log.txt](https://github.com/mesonbuild/meson/files/4457907/meson-log.txt)

**Comment by alex-tee** [comment]
+1 same error here when gettext is not installed. very confusing

**Comment by whot** [comment]
> It looks like #5758 tries to address this

just ftr, I just tried 0.56.2 from pip and the issue is still there.
