### ISSUE TITLE
Using cmake project subproject (capnproto-c++-0.7.0) fails

### ISSUE THREAD

**Issue by germandiagogomez** [mesonbuild/meson#6168]
Hello,

This seems to be almost working except some rough edge.

Basically, the problem I am having is:

1. my project uses some shared library
2. I try to use static libraries from capnproto
3. I get link errors

```
  cmake = import('cmake')
  capnp_subproj = cmake.subproject('capnproto-c++-0.7.0', cmake_options : ['-DBUILD_TESTING=OFF', '-DCMAKE_CXX_FLAGS=-fpic'])
``` 

I also tried with -fPIC (instead of fPIC) and with BUILD_SHARED_LIBS=ON (no need for fPIC in that case I think).

[capnproto_0.7.0.orig.tar.gz](https://github.com/mesonbuild/meson/files/3833304/capnproto_0.7.0.orig.tar.gz)

None of them worked.

## Steps to reproduce

1. Create a shared library **that consumes some capnproto library symbol**
2. Use capnproto as a cmake subproject and use the capnp dependency.
3. Try to use the dependency in your shared library. It does not work. Trying to use cmake_options: BUILD_SHARED_LIBS=ON *or* CMAKE_CXX_FLAGS=-fpic *or* CMAKE_CXX_FLAGS=-fPIC does not help.

Expected output: compiles fine.
Actual output link errors: link errors.

**Comment by mensinda** [comment]
Could you please provide more information (full error message, full `meson.build`, or even better, a link to your project or a minimal test case)?

I am unable to get any errors with this `meson.build` and `main.cpp`:

```meson
project('capnproto_test', ['c', 'cpp'])

cm = import('cmake')
subp = cm.subproject('capnproto-c++-0.7.0', cmake_options : ['-DBUILD_TESTING=OFF', '-DCMAKE_CXX_FLAGS=-fpic'])
dep = subp.dependency('capnp')

executable('main', ['main.cpp'], dependencies: [dep])
```

```cpp
#include <capnp/message.h>

int main() {
  return 0;
}
```

**Comment by germandiagogomez** [comment]
I will within this week, probably tonight or tomorrow. (+1:00 UTC here)

**Comment by mensinda** [comment]
Again, I don't get any errors with the following updated test case:

```meson
project('capnproto_test', ['c', 'cpp'])

cm = import('cmake')
subp = cm.subproject('capnproto-c++-0.7.0', cmake_options : ['-DBUILD_TESTING=OFF', '-DCMAKE_POSITION_INDEPENDENT_CODE=ON'])

deps = [
  subp.dependency('capnp'),
  subp.dependency('kj'),
]

# All targets
message(subp.target_list())

libA = shared_library('libA', ['libA.cpp'], dependencies: deps)
exe  = executable('main', ['main.cpp'], link_with: [libA])
```

main.cpp:
```cpp
#include "libA.hpp"

int main() {
  return getNum();
}
```

libA.hpp:
```cpp
#pragma once
int getNum();
```

libA.cpp:
```cpp
#include "libA.hpp"
#include <capnp/message.h>

int getNum() {
  capnp::MallocMessageBuilder b;
  (void)b;
  return 0;
}
```

**Comment by germandiagogomez** [comment]
@mensinda I will try your test case in my computer and give you further feedback within today.

**Comment by germandiagogomez** [comment]
@mensinda the problem was actually that transitive dependency is not encoded into the cmake project and I was missing some libraries. pkg-config did it correctly but not my embedded subrpoject. This lead me to confusion. Thanks for your help. I close this issue, since it is not related to what I originally suspected.
