### ISSUE TITLE
Infinite loop while building

### ISSUE THREAD

**Issue by crispy2606** [mesonbuild/meson#6176]
Hello,

I tried to compile my C++ project and got stuck while building.

I am using Meson and Ninja and I program on a Mac with macOS Catalina(if this changes something).

I can build everything without any problem, but can't compile... 10 min before everything worked fine.
I had the same issue yesterday, after commenting a section out, building and compiling (also infinite loop) and remove the comments(so i had the same code as before) it worked and dont know why?

Thanks in Advance

**Comment by scivision** [comment]
Hello, to be able to replicate this issue, we would need a simple example. Is your project on Github or can you make a simple example that reproduces this?

**Comment by scivision** [comment]
I see this has been made an upstream Ninja issue 1675. In either case, a minimal example that demonstrates would be needed. Thanks.
