### ISSUE TITLE
meson-logs.txt should contain information about cached dependencies

### ISSUE THREAD

**Issue by Jehan** [mesonbuild/meson#6181]
When a dependency is searched for the first time, `meson-logs/meson-log.txt` contains all relevant info, which are the commands run and their result. That's fine.

When retrieved from cache on successive runs, it just displays:

```
Dependency libheif found: YES (cached)
```

Even when cached, the logs should contain the cached version, as well as retrieved `--libs` and `--cflags` contents, otherwise there is not much for us to debug if there is a problem.

I had this case where I only discovered the wrong dependency was used because I had warnings in our meson file (#6180). Logs should contain more.
Thanks! :-)

**Comment by mensinda** [comment]
The version of cached dependencies will be logged with #6182. For ldflags, etc. I would recommend having a look at the [introspection API](https://mesonbuild.com/IDE-integration.html) (`meson introspect -i --dependencies` or `meson-info/intro-dependencies.json`).

**Comment by Jehan** [comment]
Nice, thanks. :-)
