### ISSUE TITLE
[Question] How to do the equivalent of building python package with setuptools and setup.py?

### ISSUE THREAD

**Issue by zhanggyb** [mesonbuild/meson#6184]
Hi,

Maybe this is a stupid question as I'm a beginner in Meson. I've searched on Google, this issue list and the test cases in the repo, but still don't know how to do this.

I have a python package under development and want to switch to meson build system.

Currently I am using `setuptools` and a config file 'setup.py' as recommended on https://docs.python.org/3/distributing. 

The example file tree is:

``` shell
.
├── demo
│   ├── cli
│   │   ├── __init__.pyx
│   │   └── launcher.pyx
│   └── __init__.py
└── setup.py
```

The 'setup.py' looks like:

``` python
setup(
    name="demo-cli",

    packages=[
        'demo',
        'demo.cli'
    ],

    ext_modules=cythonize(
         [
             "demo/cli/__init__.pyx",
             "demo/cli/launcher.pyx",
         ],
         language_level=3
     ),

     entry_points={
         'console_scripts': [
             'demo-cli = demo.cli.launcher:main',
         ],
     },

     package_data={
         'demo.cli': ['data/scripts/*.sh'],
     },
)
```

To build the python package I just need to run `python3 setup.py build` and `python3 setup.py install`.

How should I do the equivalent in meson?

I have an initial solution with `custom_target` and external script (`chdir` to the source dir and run `setup.py`), is there a better way in meson?

(The extension_module() function looks just compile c code to a single .so file.)

Thanks in advance!

**Comment by zhanggyb** [comment]
I found a good project using meson I can learn for this issue: https://gitlab.gnome.org/GNOME/gnome-music

I must misunderstand the design point of meson and python setuptools.

Close this issue.

**Comment by bool3max** [comment]
What did you end up doing in the end? I browsed the repo and meson.build file in the link you provided but I can't find anything relevant.
