### ISSUE TITLE
code coverage on macOS now failing with "

### ISSUE THREAD

**Issue by krader1961** [mesonbuild/meson#6191]
As recently as 2019-08-08 I was able to generate a code coverage report for the ksh (Korn shell) project using clang/LLVM and lcov on macOS. Since then I updated meson and macOS and now find that running `meson -Db_coverage=true --prefix=/tmp/ksh.$$` fails thusly:

```
ERROR: Linker APPLE ld doesn't implement coverage data generation.
```

Updating meson to the current master branch head (commit c6f93b6bf6) results in the same failure.

I rolled back the Meson version on my system to commit b0f4ee2f; i.e., just prior to the changes introduced by PR #5681. That version of meson is able to generate a coverage report. The first change to break things is commit 06dcbd50e.

I'm currently running macOS 10.15.1 (Catalina).

**Comment by QuLogic** [comment]
Duplicate of #6188.

**Comment by krader1961** [comment]
> Duplicate of #6188.

Yes, modulo my problem report includes more details about when the regression was introduced :smile: Still, this should be closed as a duplicate since I reported this after issue #6188 was opened.
