### ISSUE TITLE
Allow "import" before the project statement

### ISSUE THREAD

**Issue by pbor** [mesonbuild/meson#6205]
Today the first statment of `meson.build` must be `project`.

I was thinking that it would be cool to allow `import` before that. The main reason would be to support a use case like the following:

```
project(
  'myproj, 'c',
  version: run_command(meson.source_root() / 'get-version.py').stdout().strip(),
  meson_version: '>= 0.50.0'
)
```
This works today, but it would be nicer to be able to `python = import('python')` and then use the python interpreter used by meson to run the `get-version` script.

Additionally, having all imports at the top of the file, seems nice and consistent with many other languages (C, python, java, etc, etc)

**Comment by jpakkane** [comment]
No. This will not be done ever. Cmake has this and people abuse it to no end. The fact that you can't do anything before the project call is by design.

In this particular case there are two options:

- set your version in project's `version` and generate everything else from that
- use the simpler form of `run_command('get_version.py').stdout().strip()`

**Comment by scivision** [comment]
Hello, this topic comes up from time to time. It's actually a deliberate design decision to mandate `project()` as the first statement. The design intent is to keep meson.build human readable and understandable. Allowing too much dynamism without a specific build system need is usually not done in Meson.

Having more or dynamic metadata fields has also been discussed. These might be things one puts into a Meson-generated from pkg-config .pc file instead.

**Comment by pbor** [comment]
I understand the reasons, and I am fine with the restrictions, that is why I was only proposing `import` statements, not other generic things...

Setting the command in `version` and generate everything from it is not an option because we need to get the version dynamically from the CI environment. Also the same version generation script is shared with other projects that are not based on meson (for instance `js` frontend).

The second suggestion is not clear to me either: `run_command('get_version.py').stdout().strip()` is cleaner (so I will switch) but does not help with the fact that I would like to use the python interpreter from meson, does it? This is important on Windows

**Comment by jpakkane** [comment]
Meson autodetects shebang lines from script files (it needs to be in the format `#!/usr/bin/env python3`) and does the right thing even on Windows.

**Comment by pbor** [comment]
That's great!

I think it should be pointed out in https://mesonbuild.com/External-commands.html

**Comment by pbor** [comment]
I opened https://github.com/mesonbuild/meson/pull/6206 for the docs.

Closing
