### ISSUE TITLE
cmake: subproject with dependencies do not build

### ISSUE THREAD

**Issue by rilian-la-te** [mesonbuild/meson#6208]
**Describe the bug**
With CMake this project builds fine. 
But when I try to use it as Meson subproject it crashes on Meson side.

```
|Executing subproject jayatana method cmake 
|
|Found CMake: /usr/bin/cmake (3.15.5)
|
||Configuring the build directory with CMake version 3.15.5
||Running: /usr/bin/cmake -DCMAKE_C_COMPILER=cc -G Ninja -DCMAKE_INSTALL_PREFIX=/usr/local --trace --trace-expand
||
||Running with trace output on.
||Running with expanded trace output on.
||-- Could NOT find VCM (missing: VCM_DIR)
||-- Configuring done
||-- Generating done
||-- Build files have been written to: /home/rilian/Projects/vala-panel-appmenu/build/subprojects/jayatana/__CMake_build
|
|CMake configuration: SUCCEEDED
|CMake server handshake: SUCCEEDED
|CMake server configure: SUCCEEDED
|Generating build system files: SUCCEEDED
|Querying build system files: SUCCEEDED
|Querying the CMake code model: SUCCEEDED
|WARNING: CMake: path /usr/lib/jvm/default/include;/usr/lib/jvm/default/include/linux;/usr/lib/jvm/default/include does not exist. Ignoring. This can lead to build errors
|CMake project jayatana has 9 build targets.
|
||Processing generated meson AST
||Build file: /home/rilian/Projects/vala-panel-appmenu/build/subprojects/jayatana/meson.build
||
||Project name: jayatana
||Project version: undefined
||C compiler for the host machine: cc (gcc 9.2.0 "cc (GCC) 9.2.0")
||C linker for the host machine: GNU ld.bfd 2.33.1
||Program /usr/lib/python3.8/site-packages/mesonbuild/cmake/data/run_ctgt.py found: YES (/usr/lib/python3.8/site-packages/mesonbuild/cmake/data/run_ctgt.py)

subprojects/jayatana/meson.build:0:0: ERROR: Unknown variable "java-headers".

```

**To Reproduce**
Build [this project](https://gitlab.com/vala-panel-project/vala-panel-appmenu) with meson

**Expected behavior**
It should builds fine as in CMake alone.

**system parameters**
* Native build
* ArchLinux
* Python 3.8.0
* meson 0.52.0
* ninja 1.9.0

**Comment by mensinda** [comment]
Since there is an `add_custom_target` somewhere in the relevant `create_javah` function, this probably depends on #5989. However, even with that PR, I am still getting an error.

The current state of CMake subprojects is, that we want to support *most* CMake projects, however, there will always be cases where this won't be possible. That being said, projects like this should be supported (especially with #5989 being on the way), but, unfortunately, this won't happen before meson 0.53.0.

**Comment by rilian-la-te** [comment]
@mensinda this is not add_custom_target (maybe, it is, but in CMake machinery).
And we use `create_javah` only on old CMake, but on new we use jar api.

Error is same?

**Comment by mensinda** [comment]
Yes, the error is the same, but you are right, create_javah is not called. Guess it's time for me to figure out what's going wrong then.

**Comment by mensinda** [comment]
OK, with #6213, this sort of works now, but meson still won't be able to detect the correct internal dependency structure. At least #5989 for `add_dependency()` support will be required to do this.

However, I can compile your project if I manually force a compilation order for ninja:
```
ninja -C build subprojects/jayatana/java_class_filelist
ninja -C build subprojects/jayatana/c0_java_class_filelist
ninja -C build # All the other stuff
```

It would be nice if you could test #6213 (with the ninja workaround) on your system if you have the time.

**Comment by rilian-la-te** [comment]
I will try it on weekend

**Comment by mensinda** [comment]
With #6261, I can now build vala-panel-appmenu without any problems (and without the forced compilation order hack).
