### ISSUE TITLE
Using CMake variables defined from LLVM

### ISSUE THREAD

**Issue by BSFishy** [mesonbuild/meson#6211]
I am interested in moving my project from CMake to Meson, but one thing I am thinking about is using a variable that LLVM defines in my CMake build. I use the variable `${LLVM_TARGETS_TO_BUILD}` to get the LLVM components to include in my build, and I just want to check if there is any sort of functionality related to that in Meson or if it is planned.

My line in CMake looks like this:
```cmake
llvm_map_components_to_libnames(llvm_libs ${LLVM_TARGETS_TO_BUILD})
```
Is there anything similar in Meson, or will I have to define every single component I want to include?

**Comment by mensinda** [comment]
Meson already the [LLVM dependency](https://mesonbuild.com/Dependencies.html#llvm) with modules. We actually already use [`llvm_map_components_to_libnames` internaly](https://github.com/mesonbuild/meson/blob/master/mesonbuild/dependencies/data/CMakeListsLLVM.txt#L30).

If you want to extract variables explicitly, then you can have a look at [this](https://mesonbuild.com/Dependencies.html#arbitrary-variables-from-dependencies-that-can-be-found-multiple-ways)

**Comment by dcbaker** [comment]
I don't know what your build looks like but you can use the modules parameter to map exact modules you want in the dependency object.

```meson
dep_llvm = dependency('llvm', modules : ['amdgpu', 'ipo', 'bitwriter', 'bitreader'])
```

Our dependency is a little more complex than the cmake one because we can either use cmake to find llvm or llvm-config. Let me know if you run into any problems because AFAIK mesa is the only project using the LLVM dep right now.

**Comment by BSFishy** [comment]
Not sure if they changed it in LLVM 10, but I think you don't need to specify components. For whatever reason, I can use

```meson
llvm_dep = dependency('LLVM')
```

as my dependency and it will compile just fine. [The variable that I was talking about](https://llvm.org/docs/CMake.html#llvm-specific-variables) was just an alias to `all`, so I think if I do need to specify components in the future, I should be able to use that.
