### ISSUE TITLE
Using Antlr with Meson

### ISSUE THREAD

**Issue by BSFishy** [mesonbuild/meson#6224]
I am working on a project that uses Antlr's C++ target and I am looking to move to Meson from CMake. Right now, the method I am using to get Antlr isn't very nice, so I don't think I'll use an example from my code. They do, however, provide a tutorial to add it as a CMake dependency in the repository. The main method, to my knowledge, is to use an external project. They have a [CMake script](https://github.com/antlr/antlr4/blob/master/runtime/Cpp/cmake/ExternalAntlr4Cpp.cmake) that can be used as so:

```cmake
include(ExternalAntlr4Cpp)

include_directories(${ANTLR4_INCLUDE_DIRS})

add_executable(output main.cpp)
target_link_libraries(output antlr4_static)
```

In addition, to convert a grammar to actual C++ code, you need to call a macro like so:
```cmake
set(ANTLR_EXECUTABLE /home/user/antlr-4.7.2-complete.jar)
find_package(ANTLR REQUIRED)

antlr_target(SampleGrammarLexer TLexer.g4 LEXER
             PACKAGE antlrcpptest)
```

From my research, Meson doesn't provide access to include CMake scripts or call macros. They also provide a `FindANTLR` file, but in my testing, I couldn't get it to work. Any suggestions?

**Comment by scivision** [comment]
A possibility would be to setup a Meson CMake-subproject: https://mesonbuild.com/CMake-module.html#cmake-subprojects

That is, make your own CMakeLists.txt that calls the macros as above, and then using your CMakeLists.txt as a Meson CMake-subproject is a possibility.

**Comment by mensinda** [comment]
Unfortunately, this is a bit out of the scope of the "normal" meson dependency handling. From the looks of the `ExternalAntlr4Cpp` script, the runtime would be built from source. In that case, you could try your luck with including the runtime as a [CMake subproject](https://mesonbuild.com/CMake-module.html).

However, from the looks of it, you might have to patch the project to include a minimal, root `CMakeLists.txt` with the meson [wrap patch](https://mesonbuild.com/Wrap-dependency-system-manual.html) mechanism.

**Comment by BSFishy** [comment]
Sorry for taking a little bit of time. I have started working towards adding my Antlr files as a subproject. I created a subproject with a cmake file with the following contents:

```cmake
CMAKE_MINIMUM_REQUIRED(VERSION 3.7 FATAL_ERROR)

project(libparser)

list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/cmake)

include(ExternalAntlr4Cpp)

include_directories(${ANTLR4_INCLUDE_DIRS})

set(ANTLR_EXECUTABLE /usr/local/lib/antlr-4.7.2-complete.jar)

find_package(ANTLR REQUIRED)

antlr_target(parser Brill.g4
                LEXER
                PARSER
                VISITOR
                PACKAGE "Brill")

include_directories(${ANTLR_parser_OUTPUT_DIR})
add_library(parser SHARED ${ANTLR_parser_CXX_OUTPUTS})
target_link_libraries(parser antlr4_static)
```

I also added the necessary CMake files from Antlr and my grammar file. When I build using Meson, I get errors saying the files that should be generated by Antlr are not found. When looking into the file structure, I notice that not only has Antlr not been built, but the project hasn't even been cloned. I can go into that directory and run Ninja myself, but I get errors there complaining that cache cannot be found. When I try to add support for the Ninja generator to the `ExternalAntlr4Cpp` script, I then get errors saying a `build.ninja` file can't be found.

@mensinda Is this circumstance what you were talking about, with including the runtime itself as a subproject then adding my dependents using that subproject?

**Comment by mensinda** [comment]
I was referring to adding Antlr itself as a subproject. In this case by downloading and extracting the official source code in the subproject folder. Then adding a dummy `CMakeLists.txt` in the Antlr root, which only contains an `add_subdirectory` line, to the actual `CMakeLists.txt`.

Then, in meson, you get direct access to everything in the Antlr subproject and can translate the code from above to meson. Admittedly, this might require reverse engineering, what `antlr_target` does.

**Comment by BSFishy** [comment]
I believe I got the subproject working as a wrap and the `antlr_target` replicated for the most part, but there is one thing I am not sure about. The command to generate all of the source files outputs them all at once and I don't know if I have this setup correctly. Here is my code:

```meson
java = find_program('java')

parser_input = files('src/lang/Brill.g4')
parser_cxx_outputs = ['BrillLexer.h', 'BrillLexer.cpp',
        'BrillParser.h', 'BrillParser.cpp',
        'BrillBaseVisitor.h', 'BrillBaseVisitor.cpp',
        'BrillVisitor.h', 'BrillVisitor.cpp']
parser_outputs = ['BrillLexer.interp', 'Lexer.tokens']
parser_outputs += parser_cxx_outputs

parser = custom_target('gen-parser',
        input: parser_input,
        output: parser_outputs,
        command: [java, '-jar', '/usr/local/lib/antlr-4.7.2-complete.jar',
                '@INPUT@',
                '-o', '@OUTDIR@',
                '-no-listener',
                '-Dlanguage=Cpp',
                '-visitor',
                '-package', 'Brill',
                '-Xexact-output-dir'])
parser_lib = library('parser', parser, include_directories: [antlr_inc], dependencies: [antlr_dep])
parser_dep = declare_dependency(sources: [parser[2], parser[4], parser[6], parser[8]], link_with: [parser_lib])
```

That will build and everything if I add the `parser_dep` as a dependency to my other targets, but I think it is building all of the c++ files for each target rather than just building it once for the `parser_lib` library then linking all the targets to that library. Is this the correct way of doing this, or is there a better way?

**Comment by mensinda** [comment]
Your current solution looks correct to me. You could check what is actually going on by doing something like `ninja | cat` to force newlines. Alternatively, there is the `meson-info/intro-targets.json` file, where all sources are listed for all targets (though I would strongly recommend something like https://jsonformatter.curiousconcept.com/ to make it readable).

**Comment by BSFishy** [comment]
Taking a look at `meson-info/intro-targets.json`, I think it is all working correctly. Thanks for the help!
