### ISSUE TITLE
0.52.0: meson fails on using paralel build

### ISSUE THREAD

**Issue by kloczek** [mesonbuild/meson#6234]
As exampe you can use glib package.

Im using  Linux, Fedoira based but I'm building everything with LTO. Which seems is relared to that issue. I found that few other packages as long as they are enough big are failing as well in similar way. If ninja is started with `-j1` everything is fine.

* what Python version are you using e.g. 3.8.0
3.8.0

* what `meson --version`
0.52.0

* what `ninja --version` if it's a Ninja build
1.9.0

https://gitlab.gnome.org/GNOME/glib/issues/1905
In above ticket is attached full build log. Just tested that on new release of the glib 2.63.2 meson still fails.

Exact part which is failing looks like:
<pre>[986/1159] gcc  -o gobject/tests/signals &apos;gobject/tests/36a2d80@@signals@exe/meson-generated_.._marshalers.c.o&apos; &apos;gobject/tests/36a2d80@@signals@exe/signals.c.o&apos; -Wl,--as-needed -Wl,--no-undefined -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto=auto -flto-partition=none -DG_DISABLE_ASSERT -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto=auto -flto-partition=none -fuse-linker-plugin -Wl,--start-group glib/libglib-2.0.so.0.6302.0 gobject/libgobject-2.0.so.0.6302.0 -lm -Wl,--end-group -pthread &apos;-Wl,-rpath,$ORIGIN/../../glib:$ORIGIN/..&apos; -Wl,-rpath-link,/home/tkloczko/rpmbuild/BUILD/glib-2.63.2/x86_64-redhat-linux-gnu/glib -Wl,-rpath-link,/home/tkloczko/rpmbuild/BUILD/glib-2.63.2/x86_64-redhat-linux-gnu/gobject
FAILED: gobject/tests/signals 
gcc  -o gobject/tests/signals &apos;gobject/tests/36a2d80@@signals@exe/meson-generated_.._marshalers.c.o&apos; &apos;gobject/tests/36a2d80@@signals@exe/signals.c.o&apos; -Wl,--as-needed -Wl,--no-undefined -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto=auto -flto-partition=none -DG_DISABLE_ASSERT -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto=auto -flto-partition=none -fuse-linker-plugin -Wl,--start-group glib/libglib-2.0.so.0.6302.0 gobject/libgobject-2.0.so.0.6302.0 -lm -Wl,--end-group -pthread &apos;-Wl,-rpath,$ORIGIN/../../glib:$ORIGIN/..&apos; -Wl,-rpath-link,/home/tkloczko/rpmbuild/BUILD/glib-2.63.2/x86_64-redhat-linux-gnu/glib -Wl,-rpath-link,/home/tkloczko/rpmbuild/BUILD/glib-2.63.2/x86_64-redhat-linux-gnu/gobject
/usr/bin/ld: cannot find signals.lto.o: No such file or directory
/usr/bin/ld: error: could not unlink output file
collect2: error: ld returned 1 exit status
</pre>

**Comment by kloczek** [comment]
Any progress on that issue?

I found many other projects in which parallel build fails.
O maybe I can do something to deliver some diagnostics data?

**Comment by kloczek** [comment]
Just in case I'm using currently meson 0.52.1 and that issue still is present.

**Comment by eli-schwartz** [comment]
I can't reproduce this, and I'm not actually sure what or how the problem is supposed to work. The file that cannot be found, is AFAICT never intentionally created by meson or ninja.

This was cross-posted to https://sourceware.org/bugzilla/show_bug.cgi?id=25589 and the binutils team thinks it is a redhat bug in /usr/lib/rpm/redhat/redhat-hardened-ld
