### ISSUE TITLE
No specified compiler can handle file

### ISSUE THREAD

**Issue by CreatorVilius** [mesonbuild/meson#6235]
**Describe the bug**
I am trying to include object file into my meson project. However, it seems that it is not supported.

**To Reproduce**
1. Declare dependency with source file which is object file. `obj = declare_dependency(sources: 'a.o')`
2. Include declare dependency into executable `executable('...', ..., dependencies: [obj])`

**Expected behavior**
Object file included into meson project

**system parameters**
> **Ninja version:** 1.9.0
> **Meson version:** 0.51.2
> **Cross build:** No.
> **Python:** 3.7.4

**Comment by jpakkane** [comment]
Prebuilt objects are specified with the `objects` keyword argument. [Documentation here](https://mesonbuild.com/Reference-manual.html#executable), [example here](https://github.com/mesonbuild/meson/tree/master/test%20cases/unit/15%20prebuilt%20object).
