### ISSUE TITLE
[RFC] Overhaul of `.system()` to better suit cross-compilation and OS variants

### ISSUE THREAD

**Issue by ePirat** [mesonbuild/meson#6257]
## The problem

Currently the `.system()` function of `build_machine`, `host_machine` and `target_machine` returns incoherent results in some cases, for example when cross-compiling for iOS it can be either `darwin` which is what the reference table documents or it can be `ios`, depending on what the user has set in the crossfile.

This leads to the unfortunate situation that a check like:

```meson
host_machine.system() == 'darwin'
```
could be ambiguous. Depending how the cross-file is written it will be always true for all variants of Darwin (including iOS, tvOS, watchOS, …) or it will be true on macOS but false when cross-compiling for other Darwin-based OSes. Some projects rely on the former behavior, some on the latter.

This leads to the situation that it is impossible to have one “correct” cross-file as it might now work fine for some projects but not for others, depending what value they expect for `.system()`.
The same issue exists for Android.

## Solutions

The most trivial solution would be to normalize the system value to the values listed in the reference table. But given the broad meaning the term “system” could have one could argue that either the first or the second expectation for the value of it are correct, and no matter in which way we would normalize the value, it would break some projects that rely on either the broad (darwin) or more specific (ios, tvos, ...) values.

After some discussion with @nirbheek and @textshell on IRC the way to solve this with the least impact on existing projects would be to introduce two new functions:
- One to get the more generic variant of the system, like `linux`, `darwin`, `windows`, etc.
- And one to get the more specific one (if any), like `android`, `ios`, `tvos`, `watchos`, etc.

And then slowly deprecate the `.system()` function in favor of the new functions. And what should be the names for these two new functions?

**Comment by ePirat** [comment]
Somewhat related to issue #6233 about Android missing in the reference table.

**Comment by scivision** [comment]
This problem has parallels in CMake and Python itself. Some platforms don't fit generic categories, for example Haiku. Perhaps if we kept `.system()` to be more generic representations, and `.platform()` was the more specific name. Some unique platforms would be present in both .system() and .platform(), for example `haiku`. 

The distinction from CMake and Python itself is that usually the Windows/Unix divide is so generic and so obvious as to not warrant a specific options--just do `is_windows = .system() == 'windows'`. That is, keep .system() fine-grained enough to be actionable, not too generic.

## Example

* .system(): generic name: {windows, darwin, linux, bsd, haiku, ...}
* .platform(): specific name: {android, ios, macos, linux, freebsd, cygwin, msys2, wsl, haiku, ...}


## reference

### CMake

* [APPLE](https://cmake.org/cmake/help/latest/variable/APPLE.html) includes MacOS, tvos, etc.
* [CMAKE_HOST_SYSTEM_NAME](https://cmake.org/cmake/help/latest/variable/CMAKE_HOST_SYSTEM_NAME.html) is like `uname -s`

**Comment by ePirat** [comment]
@scivision The problem with this approach is that it means we would break existing projects that rely on `system` returning for example `ios` when cross-compiling for iOS, instead of `darwin`…

Hence the proposal for two new functions so we can properly deprecate and warn about using system().

**Comment by ePirat** [comment]
This is not an enhancement really but an important bug fix. The longer we keep the current, misleading behavior the more projects are going to rely on it and the messier everything will be…

**Comment by scivision** [comment]
Yes perhaps a new option name, or emit a deprecation warning with the current name when a "moved" option name is used.

**Comment by dcbaker** [comment]
I'd previously suggested https://github.com/mesonbuild/meson/issues/4852, which would give an additional `userland` field, with system being more equivalent to `kernel` or `os family`. I'm not sure what color to paint the barn yet, but it would be nice to have some finer knobs in regards to kernel vs os.

**Comment by dcbaker** [comment]
Closed in favor of #6361

**Comment by ePirat** [comment]
Not sure if its a good idea to close a issue that really is quite important to resolve in favor or some mega-issue that covers the other one too?

If there is plan to solve this together with the other rework, at least some quicker fix for it seems needed until things get more fragmented and even more projects will rely on the "wrong" behavior…

**Comment by nirbheek** [comment]
I think if we can come up with a solution that doesn't need to "fix everything" but can be done incrementally, we can merge the `.system()` fix first. It's the most glaring issue, IMO, because it is a requirement for cross-compilation.

I think it's fine to use that mega issue to discuss whether this can be done, or if it really does need a big overhaul like we did for compilers/linkers.
