### ISSUE TITLE
Ensure PKG_CONFIG_PATH persistence

### ISSUE THREAD

**Issue by tp-m** [mesonbuild/meson#626]
Encountered the following issue:

    $ PKG_CONFIG_PATH=/foo/pkgconfig meson

and everything builds fine, *but* one of the meson.build files has something like this:

    runcmd = run_command('pkg-config', '--variable=pluginsdir', 'gstreamer-1.0')

The problem is now that without an export the environment passed to meson is not inherited by subprocesses (I think that's the issue anyway, although I'm not sure why the dependency() detection via pkg-config works then, since it's also a subprocess), so it returns the pluginsdir of the installed gstreamer here, not the prefix I specified.

I think it's unreasonable to expect users to export this var, so I think whatever the issue is it needs to be worked around in meson somehow or we need specific functions to do the equivalent that will do the right thing.

**Comment by tp-m** [comment]
Hrm, I must be confused. Can't reproduce this now with a clean build. No idea why it picked up the other path yesterday then.

**Comment by 0x1997** [comment]
I'm facing the same issue with `BOOST_ROOT`. I think the better way to handle this is to use the cached value when the environment variable is not found and only clear or update it if it's value is the empty string or something different.

**Comment by nirbheek** [comment]
What if the environment contains a "default" value that you've overriden just when running `meson` by doing `BOOST_ROOT=/some/path meson`?

I think the default should be to always preserve certain variables whenever `meson` is invoked automatically via `ninja`. We can maintain a list, and append to it as people complain.

To overwrite that, you *must* run `meson` anew. If you want to overwrite existing `meson` files, you should be able to use a `--overwrite` flag to `meson` which will wipe `meson-private` and `meson-logs` (this will have to be implemented).
