### ISSUE TITLE
Enable LGTM for code analysis (GitHub Application)

### ISSUE THREAD

**Issue by XVilka** [mesonbuild/meson#6263]
Will help to eliminate obvious errors. See:
- https://lgtm.com/
- https://github.com/marketplace/lgtm

**Comment by scivision** [comment]
Yes LGTM pull request checks would be a helpful addition, along the lines of recent CI additions including MyPy, Pylint and Actions framework checks. 

The LGTM app would have to be enabled by @jpakkane

**Comment by scivision** [comment]
It looks like Jussi enabled LGTM for PR today, as I see LGTM starting on PR's in the last few hours. Thanks!

**Comment by XVilka** [comment]
@scivision amazing, thanks. You might also consider joining the free [Coverity Scan](https://scan.coverity.com/) program for the open source projects. To be honest, I don't know how it performs on the Python projects, but I have a quite good experience with C/C++. The integration of it is a bit trickier, but you can see how it is done with GitHub Actions for Ruby: https://github.com/ruby/actions-coverity-scan

https://community.synopsys.com/s/article/What-languages-are-supported-by-Synopsys-Static-Analysis-Coverity
