### ISSUE TITLE
Meson 5.2 fails on LeelaChessZero build ...

### ISSUE THREAD

**Issue by MichaelB7** [mesonbuild/meson#6309]
Simple solution for now is to revert to 5.1.2 until it gets fixed.

https://github.com/LeelaChessZero/lc0/issues/1036

**Comment by borg323** [comment]
This was already reported and bisected in <https://github.com/mesonbuild/meson/issues/6113>.

**Comment by mensinda** [comment]
Should be fixed with #6321

**Comment by mensinda** [comment]
@MichaelB7 did #6321 resolve the issue for you?

**Comment by MichaelB7** [comment]
I haven’t been able to check yet.

**Comment by eli-schwartz** [comment]
Duplicate of #6113
