### ISSUE TITLE
endless loop if /dev/stdout is an argument in run_command

### ISSUE THREAD

**Issue by pierre-labastie** [mesonbuild/meson#6315]
**Describe the bug**
If /dev/stdout is an argument of a `run_command()`  function, and stdout is redirected to
a file, then /dev/stdout is added to build_def_files (actually as a path relative to the
build directory). Before commit 3db6dcb3b85, this was not the case, because the
relative path contained`..`
The problem is that if stdout is also redirected to a file when running ninja, /dev/stdout mtime is always posterior to that of any build file, so ninja keeps calling meson for rebuilding files.

**To Reproduce**
The behavior is observed in mutter-3.34.1 build.
```bash
mkdir build && cd build
( meson --prefix=/usr -Dprofiler=false .. && ninja) > file.log
```
Note that the faulty `meson.build` files are in subdirectories of cogl/tests, and that passing `-Dcogl_tests=false` prevents the issue to happen (but disables the tests)

Note that you can try ninja -d explain, and you'll see:
```
ninja explain: output build.ninja older than most recent input ../../../dev/stdout (1575810741489216575 vs 1575810741569215608)
```

**Expected behavior**
/dev/stdout should never appear in the dependencies of build.ninja

**system parameters**
* native build
* tested on several linux distros
* Python from 3.7.5 to 3.8.0
* meson 0.52.x has the issue. meson-0.51.2 and below were OK.
* ninja 1.9.0

**Comment by xclaesse** [comment]
Ohh, that's interesting, didn't know redirect would have that effect:
```bash
$ cat test.py 
import os
print(os.path.isfile('/dev/stdout'))
$ python3 test.py 
False
$ python3 test.py > out && cat out
True
```

**Comment by jpakkane** [comment]
Regardless the script that looks up the deps is a bit convoluted. It it does not follow the standard pipeline behaviour of shell commands.

```
#!/bin/sh

inputdir="$1"
outputfile="$2"

echo > "$outputfile"

grep -h -r --include \*.c UNIT_TEST "$inputdir" | \
    sed -n -e 's/^UNIT_TEST *( *\([a-zA-Z0-9_]\{1,\}\).*/\1/p' > "$outputfile"
```

It would be a lot simpler if it printed the results to stdout by default:

```
#!/bin/sh

inputdir="$1"

grep -h -r --include \*.c UNIT_TEST "$inputdir" | \
    sed -n -e 's/^UNIT_TEST *( *\([a-zA-Z0-9_]\{1,\}\).*/\1/p'
```

Then the invocation becomes simpler, too:

```meson
cogl_unit_tests = run_command(
  find_program('meson/find-unit-tests.sh'), cogl_srcdir,
  check: true,
).stdout().strip().split('\n')
```

**Comment by xclaesse** [comment]
Not sure what's the proper fix here, simply exclude `/dev` ?

**Comment by jpakkane** [comment]
If it fixes the issue then go for it.

**Comment by xclaesse** [comment]
@pierre-labastie can you confirm that PR fix your issue please? https://github.com/mesonbuild/meson/pull/6317

**Comment by pierre-labastie** [comment]
@xclaesse yes it does, thanks, but it may be overkill to exclude anything in /dev (not sure, I have no idea of what could go wrong).
