### ISSUE TITLE
Shift the wiki to a new repo or possibly a docs directory

### ISSUE THREAD

**Issue by meghprkh** [mesonbuild/meson#632]
Currently there is no way to contribute to the docs. It would be better if we shift the docs to a new repo or to a `docs` directory so that users can fork that and file a PR and contribute easily. And also we can better structure the wiki (with sections and an order) by having subdirectories and using [gitbook](https://www.gitbook.com) or asciidoc

**Comment by jpakkane** [comment]
This is a known deficiency of Github. Hopefully they will fix it at some point. In the mean time you can clone the wiki with git (instructions are somewhere in Github doc pages) and send patches the old fashioned way.

**Comment by shoogle** [comment]
Or simply [change the permissions](https://help.github.com/articles/changing-access-permissions-for-wikis/) on the current wiki to allow non-collaborators to edit. Various other open source projects appear to have this enabled without problems, and if vandalism does occur you can just [revert the  edit](https://help.github.com/articles/viewing-a-wiki-s-history-of-changes/#reverting-previous-changes) via the [wiki history](https://help.github.com/articles/viewing-a-wiki-s-history-of-changes/). It is also possible to setup [edits notifications](http://stackoverflow.com/questions/8407917/how-can-you-track-or-be-notified-of-changes-to-github-wikis).

**Comment by nirbheek** [comment]
Steps are being taken to move to a different docs system. Having this bug open isn't helping though since we even forgot this bug existed!

Closing...
