### ISSUE TITLE
Compiling vala application fails when file with same name present in subdirectory

### ISSUE THREAD

**Issue by meghprkh** [mesonbuild/meson#633]
When trying to generate the ninja build it fails:

```
$ meson build
The Meson build system
Version: 0.31.0
Source dir: /home/megh/projects/gnome/mesonbug
Build dir: /home/megh/projects/gnome/mesonbug/build
Build type: native build
Build machine cpu family: x86_64
Build machine cpu: x86_64
Project name: valaprog
Native c compiler: cc (gcc 6.1.1)
Native vala compiler: valac (unknown 0.32.1)
Found pkg-config: /usr/bin/pkg-config (0.29)
Native dependency glib-2.0 found: YES 2.48.1
Native dependency gobject-2.0 found: YES 2.48.1
Build targets in project: 1

Meson encountered an error:
Multiple producers for Ninja target "valaprog@exe/test.c". Please rename your targets.
```

Sample application here https://github.com/meghprkh/meson-vala-bug

**Comment by nirbheek** [comment]
The relevant part is this:

```
executable('valaprog', ['main.vala', 'test.vala', 'subdir/test.vala'])
```

This creates two `test.c` files. Perhaps we should retain the subdir a source file is in while creating the output file. That would still create a conflict if a generated source is in the same subdir in the buildroot that a file in the source tree is in, but that is much rarer.

**Comment by tintou** [comment]
Fixed in #2413

**Comment by devnix** [comment]
What version supposedly fixed this issue? I'm suffering it right now

**Comment by devnix** [comment]
Sorry, was using Meson 0.41.1, I was assuming a more recent version. Seems to work correctly in Meson 0.50
