### ISSUE TITLE
meson 0.52 and newer adds /FORCE to link parameters on Windows with MSVC

### ISSUE THREAD

**Issue by peterh** [mesonbuild/meson#6342]
Meson 0.52 adds /FORCE to the link parameters on Windows with MSVC. This makes it annoying to use as a developer, because I can accidentally break a library and ninja will still complete successfully. I'll have all my binaries, but they won't run.

This issue is not reproducible with meson 0.51.2.

At first glance, the regression appears to have been caused by 06dcbd50eea47b3182081527ea1c0ada01d4d847 . (From that commit, it seems like I could disable /FORCE by setting b_lundef, but b_lundef is not settable from "meson configure" when using msvc)

**Comment by dcbaker** [comment]
I'm not sure why we even allow undefined symbols with link.exe, my understand is that PE dll's don't allow undefined symbols to be provided at run time like elf .so's do, or am I wrong about that?

**Comment by peterh** [comment]
Your understanding matches my understanding.

You can reference the dllexport'd symbols of an .exe from a .dll, but that's usually accomplished by linking with the import-only .lib file generated when the exe is compiled, which isn't at all like ELF. I'm pretty sure that doesn't work if you merely link with /FORCE instead.

**Comment by dcbaker** [comment]
I'm wondering why we even have code to allow FORCE:UNDEFINED in the first place. I'm thinking that the right solution is to remove it and return an empty list in that case.
