### ISSUE TITLE
Is there any way to set cmake CACHED variable?

### ISSUE THREAD

**Issue by mastermarkus** [mesonbuild/meson#6345]
**Describe the bug**
I tried to turn off glfw library tests, examples and docs, but they still keep building. Is there any way to turn them off through meson and how?

Is there any ways to specify these options through meson, the first part could be specified something like this:
```meson
add_global_arguments('-DGLFW_BUILD_EXAMPLES=0', language : ['c','cpp'])
add_global_arguments('-DGLFW_BUILD_TESTS=0', language : ['c','cpp'])
add_global_arguments('-DGLM_TEST_ENABLE=0', language : ['c','cpp'])
```

But since they are cached by cmake, is there way to turn that cache off like in glfw docs?
```cmake
set(GLFW_BUILD_DOCS OFF CACHE BOOL "" FORCE)
set(GLFW_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(GLFW_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
```

**Comment by mensinda** [comment]
Are you using glfw as a [CMake subproject](https://mesonbuild.com/CMake-module.html#cmake-subprojects)? If yes, there is the `cmake_options` key, which takes a list of strings that are passed directly to the CMake command line, so you should be able to add `'-DGLFW_BUILD_EXAMPLES=0'` there.

**Comment by mastermarkus** [comment]
I turned off tests successfully for glm library, but how can i do that for glfw, especially, how can i set the "CACHE BOOL "" FORCE" part? I tried something like this as you suggested, didn't work:
```meson
libglfw_proj = cmake.subproject('glfw-3.3',
cmake_options: ['GLFW_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE']
)
```

**Comment by mastermarkus** [comment]
Nvm it worked, i forgot to add "-D" prefix
