### ISSUE TITLE
_machine objects are insufficient for highly customizable architectures

### ISSUE THREAD

**Issue by dcbaker** [mesonbuild/meson#6353]
In particular arm (and I suspect risc-v has the same problem), don't fit nicely into the x86 or x86_64 categories that we have. There are lots of different ABI's that arm and risc-v can target.

Here's the bug report from glvnd that's prompting this:
https://gitlab.freedesktop.org/glvnd/libglvnd/issues/200

**Comment by scivision** [comment]
Maybe some overlap with Travis-CI's arm64 https://github.com/mesonbuild/meson/issues/6329 also IBM POWER just to keep things generic.

**Comment by dcbaker** [comment]
I think we're really starting to see the limits of the `host_machine` objects in general. We've got this issue (basically we need an `abi` field), then the long standing userland vs kernel problem with system(). I suspect we'll need to do something more fine grained soon.

**Comment by TheQwertiest** [comment]
Related: https://github.com/mesonbuild/meson/issues/6214

**Comment by dcbaker** [comment]
I think these are semi-related as well (in that we should do any overhauls in one big go):
 #6257
#4852

**Comment by dcbaker** [comment]
Closed in favor of #6361
