### ISSUE TITLE
Change the API of summary()

### ISSUE THREAD

**Issue by jpakkane** [mesonbuild/meson#6372]
Looking more closely at the `summary` function, it seems a bit suspect. Would it be better to instead change the "heading" entry to be a keyword argument rather than estimating it from argument count? So instead of:

```meson
summary('plugins', 'enabled', true)
``´

you'd have:

```meson
summary('enabled', true, category: 'plugins')
```

If this change is to be done, it has to be committed before 0.53.0

**Comment by xclaesse** [comment]
That would make sense, indeed.

You would still have 1 dict or 2 strings positional values. `summary(key, value)` is just small syntax helper for `summary({key: value})` and the `category` (or `section` since that's the word I'm using in the code already?) kwarg is optional.

**Comment by xclaesse** [comment]
@dcbaker @keszybz, since you were involved, what do you think?
