### ISSUE TITLE
D project setup leaves unwanted files behind

### ISSUE THREAD

**Issue by streaksu** [mesonbuild/meson#6389]
**Describe the bug**
When configuring a project with `meson <dir>` written in D, several files names `tmp*.o` will be left in the working directory.

**To Reproduce**
```
project('example', 'd')

source = files('example.d')

e = executable(
    meson.project_name().to_lower(),
    source,
    install: true
)
```

**Expected behavior**
A clean configuration with no unwanted files behind.

**system parameters**
* Its a native build using `ldc2`.
* The host OS is Void Linux (rolling release so no version).
* The python version is `3.8.1`.
* The meson version is `0.52.1`.
* The ninja version is `1.9.0`.

**Comment by jpakkane** [comment]
Can you test current master? This should be fixed there.

**Comment by streaksu** [comment]
It is fixed indeed, sorry for bothering
