### ISSUE TITLE
Docs: Meson & CLion

### ISSUE THREAD

**Issue by amitdo** [mesonbuild/meson#6400]
Some links I found that can help anyone working with Meson & CLion:

[Compilation Database](https://www.jetbrains.com/help/clion/compilation-database.html)

[Custom Build Targets and Applications](https://www.jetbrains.com/help/clion/custom-build-targets.html)

[CLion 2018.2 EAP: open project from Compilation Database](https://blog.jetbrains.com/clion/2018/05/clion-2018-2-eap-open-project-from-compilation-database/)

[CLion 2018.2.3: better compilation database integration](https://blog.jetbrains.com/clion/2018/09/clion-2018-2-3-update/)

Feel free to add this information to the docs. Note that I don't have any experience working with CLion.

**Comment by michaelbadcrumble** [comment]
I actually find this useful for developing a custom backend for CLine in Meson-UI, thanks.

**Comment by coelle** [comment]
This tip works great.

Drawback: The compile_commands.json resides in the build directory and opening this files as project, creates all CLion specific files (.idea/) in the same directory. So if you cleanup your build directory, the CLion files are deleted too!
Any suggestions how to handle this? Generate the compile_commands.json in an other directory? How?

**Comment by amitdo** [comment]
I don't know, but you can ask JetBrains/their community:

https://www.jetbrains.com/help/clion/getting-help.html

**Comment by coelle** [comment]
> This tip works great.
> 
> Drawback: The compile_commands.json resides in the build directory and opening this files as project, creates all CLion specific files (.idea/) in the same directory. So if you cleanup your build directory, the CLion files are deleted too!
> Any suggestions how to handle this? Generate the compile_commands.json in an other directory? How?

There is a ticket to handle this: https://youtrack.jetbrains.com/issue/CPP-13699

Workaround: Before opening the compile_commands.json as project, create a symlink in the project root directory, e. g. `ln -s build/compile_commands.json .`
When creating the _External Tool_ for the _Custom Build Target_, enter `$ProjectFileDir$` as _Working Directory_ (The symbolic link is resolved by CLion therefore $ProjectFileDir$/build points to the wrong location).

**Comment by nh2** [comment]
It's useful to know that meson already generates `compile_commands.json` into the build directory, but this is currently not obvious from the docs: https://github.com/mesonbuild/meson/issues/3545#issuecomment-588367563

**Comment by nh2** [comment]
> `ln -s build/compile_commands.json .`

Note for others: If you switch to that approach, best clean out related `.idea/` folders first, otherwise opening that symlink will continue to open the your `build` directory as the project root.

**Comment by amitdo** [comment]
More useful links:

https://blog.jetbrains.com/clion/2021/01/working-with-meson-in-clion-using-compilation-db/

https://www.jetbrains.com/help/clion/managing-makefile-projects.html

**Comment by michaelbrockus** [comment]
These would be fantastic in the Meson Reddit, MeWe and Facebook groups.

**Comment by amitdo** [comment]
Feel free to spread these links :-)

**Comment by amitdo** [comment]
>*** ****** commented 2 Dec  >... indeed, we have plans to support Meson in the near future.

https://youtrack.jetbrains.com/issue/CPP-4926/Support-Meson-build-system

**Comment by amitdo** [comment]
https://youtrack.jetbrains.com/issue/CPP-4926

>Sam Kolton commented 16 Jun 2023 11:28
>
>Hello, everyone! Here's a brief update on our progress: we are actively working on the Meson support. However, it is not yet ready to be shipped with the 2023.2 release. While we cannot provide a definite ETA, we are tentatively aiming to have it ready for the 2023.3 release. We acknowledge the importance of Meson and remain committed to its ongoing development.

**Comment by amitdo** [comment]
https://blog.jetbrains.com/clion/2023/12/clion-classic-2023-3-released-ai/#cpp_project_models


https://www.jetbrains.com/help/clion/meson.html#build-prj
