### ISSUE TITLE
Update Dockerfile to include missing components 

### ISSUE THREAD

**Issue by michaelbadcrumble** [mesonbuild/meson#6402]
I think the your Dockerfile is missing some components, Java-runtime, Rust compiler, Mono for C# for example, probably time to update.

**Comment by jpakkane** [comment]
Those are pulled in by `apt-get build-dep meson`.

**Comment by michaelbadcrumble** [comment]
😕 kinda hard to tell if that’s what it is.  Maybe a little note would help.
