### ISSUE TITLE
So. You changed the --force-object flag to --force-object-output 

### ISSUE THREAD

**Issue by michaelbadcrumble** [mesonbuild/meson#6403]
It was kinda scared when I thought something was wrong with Meson-UI scanner, than I got a look at Meson build 0.52.1-beta help command for introspection just as a sanity check and turned out you guys change it without leveling a note in the snippets.

**Comment by xclaesse** [comment]
git blame says it got renamed in 0.50.0 by this PR: https://github.com/mesonbuild/meson/pull/4547.

**Comment by xclaesse** [comment]
And that option was never released before, so I'm not sure what's the issue here... Closing since it's too late any way.

**Comment by mensinda** [comment]
`--force-object` should never have existed in a meson release. There was only `--force-new` temporarily in #4547. `--force-object-output` was added [in this diff](https://github.com/mesonbuild/meson/pull/4547/files?file-filters%5B%5D=.build&file-filters%5B%5D=.c&file-filters%5B%5D=.cpp&file-filters%5B%5D=.h&file-filters%5B%5D=.hpp&file-filters%5B%5D=.py#diff-cf623c407dc323907749b2a02ec4cde5R61).

Specifically `--force-new` was added [here](https://github.com/mesonbuild/meson/pull/4547/commits/a6034d1f198cd08a48026d2478c4e4539a3d9b36) and renamed to the final `--force-object-output` [here](https://github.com/mesonbuild/meson/pull/4547/commits/bd8bad46c3fad6e53e259f73408a73eeca920dc7)
