### ISSUE TITLE
[Question] finding packages 

### ISSUE THREAD

**Issue by richardbowden** [mesonbuild/meson#6405]
I am trying to workout why there are two methods to find installed libs during a build

dependency() vs compiler find_package()

in my testing. the following always works

```
cc = meson.get_compiler('c')
sqlite_dep = cc.find_library('SQLite3', required : true)
rb_dep = cc.find_library('rb', required: true)
```

but if I try and use the dependency() function like

```
sqlite_dep  = dependency('sqlite3')
rb_dep  = dependency('rb', required: true)
```

sqlite works, but the rb lib is not found and in cannot work out why.

What are the differences / the use cases for each function.

the rb lib / headers are installed in /usr/local/{lib, include} 

thanks

**Comment by mensinda** [comment]
The difference between `dependency` and `cc.find_library` is that with `dependency` standard mechanism such as `pkg-config` and the absolutely delightfull CMake `find_package` ecosystems are used (assuming pkg-config and/or CMake are installed on the system). This will also automatically add include directory paths and miscelaniuse compiler flags, required for using the library in question. For more information, see [the docs](https://mesonbuild.com/Dependencies.html).

In contrast, `cc.find_library` tries to find the library directly by trying if a dummy exe with `-l<your lib>` compiles and also [some other stuff](https://github.com/mesonbuild/meson/blob/master/mesonbuild/compilers/mixins/clike.py#L936).

If possible, the `dependency()` function should be preferred. I am not sure what `rb` is, but if there is are no `*.pc` files or it does not use CMake, then you have to fall back to `find_library`.

**Comment by scivision** [comment]
I not infrequently run into libraries with incomplete or incorrect pkg-config .PC files, at least for some OS. Typically this is handled like

```meson
foo = dependency (..., required: false)
if not foo.found()
  foo = cc.find_library(..., required: true)
endif
```

**Comment by xclaesse** [comment]
Even better: `cc.find_library('foo', has_header: 'foo.h')` to verify is has the library and needed headers.

**Comment by richardbowden** [comment]
the pc file that is generated for the rb lib is also built with meson and installed

the .pc file that was generated with meson:

```
[richard@3301] /usr/local/lib/pkgconfig
❯ cat rb.pc
prefix=/usr/local
libdir=${prefix}/lib
includedir=${prefix}/include

Name: rb
Description: useful functions
Version: 1.0.0
Libs: -L${libdir} -lrb
Cflags: -I${includedir}
```

so I am trying to figure out why one works over the other. Does the above .pc file look good ??

**Comment by richardbowden** [comment]
> I not infrequently run into libraries with incomplete or incorrect pkg-config .PC files, at least for some OS. Typically this is handled like
> 
> ```meson
> foo = dependency (..., required: false)
> if not foo.found()
>   foo = cc.find_library(..., required: true)
> endif
> ```

thanks for that, I am just wondering why use dependency if cc.find_.... alway works ?

**Comment by scivision** [comment]
find_library is a manual low-level way of doing it. For complex libraries it would be dozens of lines of nested if/elif and foreach. Dependency is automatic and much more powerful, except when some assumptions are broken (like bad pkg-config or FindFoo.cmake)
