### ISSUE TITLE
error: 'PACKAGE_VERSION' was not declared in this scope

### ISSUE THREAD

**Issue by pk-a** [mesonbuild/meson#6408]
Hi,

I have created Boilerplate from GStreamer Plugin Templates. Meson build is successful and gst-inspect command recognizes this new plugin.

I need c++ code features so I renamed the generated files from .c to .cpp of template. Not sure if this is the right way to do and I am not aware if boilerplate can generate .cpp files too. I have modified meson.build as below to support cpp
project('gst-template', 'cpp', version : '1.16.2.1', license : 'LGPL')
cc = meson.get_compiler('cpp')

This landed me into trouble. gstplugin.c -> gstplugin.cpp
I see below errors
error: 'PACKAGE_VERSION' was not declared in this scope
error: 'GST_LICENSE' was not declared in this scope; did you mean 'GST_TAG_LICENSE'?
error: 'GST_PACKAGE_NAME' was not declared in this scope; did you mean 'GST_PAD_NAME'?
error: 'GST_PACKAGE_ORIGIN' was not declared in this scope

To get past this issue, I tried hard-coding with appropriate strings for PACKAGE_VERSION, GST_LICENSE, GST_PACKAGE_NAME, GST_PACKAGE_ORIGIN, but this generates new error below

error: 'GST_PLUGIN_DEFINE' does not name a type

I am right now stuck at this point. Any suggestion on what could be the problem?
I have attached source code zip file for reference.

Thank you in advance !
[plugin-temp.zip](https://github.com/mesonbuild/meson/files/4024373/plugin-temp.zip)

**Comment by xclaesse** [comment]
This is a GStreamer issue/question, not Meson. You should report on https://gitlab.freedesktop.org/gstreamer/gstreamer.
