### ISSUE TITLE
clang-cl does not recognize /ZI flag (and so executables can't be debugged)

### ISSUE THREAD

**Issue by azmr** [mesonbuild/meson#6414]
**Describe the bug**
The build flags for a clang-cl native build include `/ZI` to generate PDB debug info. This does not seem to be recognized by clang-cl, which warns:
```
clang-cl: warning: argument unused during compilation: '/ZI' [-Wunused-command-line-argument]
```

PDBs are generated, but presumably without much information in them.
I have tried debugging the programs and can't get them to break inside my code. 
If I manually replace the `/ZI` in `build.ninja` with either `/Z7` or `/Zi`, the executables can then be debugged.

Debugging tested with:
* Microsoft Visual Studio Community 2017 v15.9.4
* [remedybg v0.2.9.2](https://remedybg.itch.io/remedybg)

MSDN/cl debug info: 
https://docs.microsoft.com/en-us/cpp/build/reference/z7-zi-zi-debug-information-format?view=vs-2017

**To Reproduce**
```
// main.c
int main() { int x = 0; return x; }
```
```
# native.meson
[binaries]
c='clang-cl'
```
```
# meson.build
project('demo', 'c')
executable('demo', 'main.c')
```
```
meson build --native-file=native.meson
ninja -C build
```
**Expected behavior**
* Default to /Z7 or /Zi (lowercase i) for clang-cl (both do the same thing in clang-cl but not cl).
* Some sort of override for debug info type (note that I don't think you can have unity builds and /Z7 on cl)?
Unfortunately this is made more difficult by clang-cl not quite copying all of cl's behaviour...

**system parameters**
* Native build
* Windows 7
* Python 3.8.1
* `meson --version` => `0.52.1`
* `ninja --version`  => `1.8.2`

**Comment by azmr** [comment]
As a workaround you can add `/Zi` to `c_args`, but this requires additional knowledge on the part of the user, the warning about `/ZI` remains (adding noise for the signal of real issues), and is an extra coupling to some details of the build process that have otherwise been abstracted by meson.

**Comment by azmr** [comment]
Brilliant, thanks @dcbaker for the quick response! :smiley:

**Comment by dcbaker** [comment]
Fortunately this was a rather easy problem to solve. We're about to make the 0.53 release so this will have to wait for that to land.
