### ISSUE TITLE
run_command() only updates after a "ninja reconfigure"

### ISSUE THREAD

**Issue by FlyingBBQ** [mesonbuild/meson#6420]
In my build I use a `r = run_command('git', 'describe', '--dirty')` of which I capture the output with `r.stdout().strip()`.

Throughout my build I use this "git version" in `configuration_data()` or just as string for the executable name, which works like a charm.

However, this `run_command()` appears to be only updated with a `ninja reconfigure` or by a change in a meson file (which triggers a reconfigure), even though the std output has changed.
This means that whenever I make changes in my source files, without committing them, `git describe --dirty` appends the -dirty flag, but this is not updated in Meson.

How can I execute the `run_command()` each time I compile?

I'm running Meson 0.52.1 on Linux.

**Comment by xclaesse** [comment]
In short; you can't do that. Even if that was possible, it would mean reconfiguring the whole project on each build.

run_command() is executed at configure time, if you want something executed at each build, you can use `custom_target(..., build_always_stale : true)`. But that means you can't have the output in your meson script. However, you can make a script that writes a `.h` header file, and then ninja will rebuild all modules that include that file.

**Comment by FlyingBBQ** [comment]
I did have a look at `custom_target()` as it does have a `capture : true` option, but this can only write to a file and does not keep the std output in my meson script as you mentioned.

Right now I use `configuration_data()` to generate the `.h` header file. I will change it to a script then so it updates every time.

**Comment by QuLogic** [comment]
> ` = run_command('git', 'describe', '--dirty')`

Please look at [`vcs_tag`](https://mesonbuild.com/Reference-manual.html#vcs_tag) instead.
