### ISSUE TITLE
meson 0.53.0 gives "TypeError: Forward references must evaluate to types. Got NotImplemented."

### ISSUE THREAD

**Issue by imphil** [mesonbuild/meson#6427]
With the newly-released 0.53.0 we get the following error on Ubuntu 16.04 with its default Python ~3.5.1~ 3.5.2 (for x86). The previous version of meson worked perfectly.

```
meson -Dtarget=sim-verilator -Dot_version=opentitan-snapshot-20191101-1-434-gb99db7f -Ddev_bin_dir=/home/vsts/work/1/a/build-bin/sw/device/sim-verilator -Dhost_bin_dir=/home/vsts/work/1/a/build-bin/sw/host --cross-file=/tmp/toolchain.dhA3HP.txt /home/vsts/work/1/a/build-out/sw/sim-verilator
Traceback (most recent call last):
  File "/usr/local/bin/meson", line 11, in <module>
    load_entry_point('meson==0.53.0', 'console_scripts', 'meson')()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/mesonmain.py", line 25, in <module>
    from . import mconf, mdist, minit, minstall, mintro, msetup, mtest, rewriter, msubprojects, munstable_coredata
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/mconf.py", line 16, in <module>
    from . import coredata, environment, mesonlib, build, mintro, mlog
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/environment.py", line 32, in <module>
    from . import compilers
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/compilers/__init__.py", line 102, in <module>
    from .compilers import (
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/compilers/compilers.py", line 389, in <module>
    class CompilerArgs(typing.MutableSequence[str]):
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/compilers/compilers.py", line 658, in CompilerArgs
    def __eq__(self, other: typing.Any) -> typing.Union[bool, 'NotImplemented']:
    "Forward references must evaluate to types.")
  File "/usr/lib/python3.5/typing.py", line 312, in _type_check
    raise TypeError(msg + " Got %.100r." % (arg,))
TypeError: Forward references must evaluate to types. Got NotImplemented.
```

You can also see the error in this CI build: https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=6916&view=logs&j=5df5adf8-3577-5927-f0b2-31afed2697ee&t=dcb8db2a-d944-5acc-e50e-bea93f2a14e9&l=31

To reproduce: All code is contained in https://github.com/lowRISC/opentitan. Get the code, then type `./meson_init.sh` (which is a wrapper around meson). Full docs are at https://docs.opentitan.org/doc/ug/getting_started_sw/

Let me know if the stacktrace is already sufficient for you to see what's going on, otherwise I can do a bisect.

**Comment by whot** [comment]
confirmed in [libwacom](https://github.com/linuxwacom/libwacom/pull/194) too.

easiest way to reproduce that I found is with a podman container:

```
$ podman run --rm -it  ubuntu:16.04
root@1234# apt-get update
root@1234# apt-get install -y apt-get install -y ninja-build python3-pip python3-setuptools git
root@1234# git clone https://github.com/mesonbuild/meson && cd meson
root@1234# ./meson.py --help
[above stacktrace]
```
`git bisect` led me to commit e88b3c802250feceaf5fb2950ce7847e6a91626f, cc @dcbaker 

python version is 3.5.2

**Comment by scivision** [comment]
I didn't see this error with Python 3.5.4. I know at least 3.5.2 is required. It may be that the requirement slipped up to 3.5.3 or 3.5.4.

**Comment by scivision** [comment]
The previous minimum was Python 3.5.2 since Meson 0.52. An issue with trying to go back on this is we need to get type annotation completed to increase the quality of Meson with so many compilers and libraries that would be excessively difficult to cover all combinations with CI.

**Comment by imphil** [comment]
Python 3.5.2 comes with Ubuntu 16.04 (at least on x86 targets; it's highly confusing as the package is actually named 3.5.1-xxx, see the list of files at https://packages.ubuntu.com/xenial/python3.5).

So if you increase the minimum version requirement to Python 3.5.3 you prevent using the latest meson on Ubuntu 16.04, which is still rather widely used.

**Comment by scivision** [comment]
I also didn't realize that Ubuntu 16.04 was actually Python 3.5.2 due to the confusing naming convention. Thanks.

**Comment by dcbaker** [comment]
We can probably get around this by defining the type inside a T.TYPE_CHECKING block. If not I guess we'll have to drop the return type annotations from those.

**Comment by dzhang-b** [comment]
Please continue to support ubuntu16.04 by removing whatever causes meson to break.

**Comment by scivision** [comment]
Thanks to everyone who reported this so quickly. It looks like #6438 is one potential pathway forward to improve Meson internals with recent Python version syntax while postprocessing source appropriate for older Python versions.
