### ISSUE TITLE
shared_library() kwarg vs_module_defs should trigger rebuild

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#643]
When the visual studio module definitions file is edited, the library that uses it should get re-linked.

**Comment by jpakkane** [comment]
So it should just set up link_depends properly? [Example](https://github.com/mesonbuild/meson/blob/master/test%20cases/linuxlike/3%20linker%20script/meson.build).

**Comment by nirbheek** [comment]
Oh, right. I forgot that it's available via that too.
