### ISSUE TITLE
regression in 0.53. meson cannot handle CheckCXXSourceRuns.cmake

### ISSUE THREAD

**Issue by umed** [mesonbuild/meson#6441]
Hi there,

**Describe the bug**

I'm trying to link with project that uses CMake and it checks supported CPU instructions via [CHECK_CXX_SOURCE_RUNS](https://cmake.org/cmake/help/v3.0/module/CheckCXXSourceRuns.html). Meson 0.52 were handling it without any problems, but 0.53 cannot.

Here is cmake file that causes issue [CPUID.cmake](https://github.com/opencv/dldt/blob/2019/inference-engine/src/extension/cmake/CPUID.cmake)

**To Reproduce**

You should install that project and use this meson.build:

```meson
project('mytestproject', ['c', 'cpp'])

inference_engine_dep = dependency('InferenceEngine', version: '>=2.0.0', required: true, method : 'cmake', modules: ['IE::inference_engine'])
```

**Expected behavior**

After running `meson build/` you must see following output:

```sh
Run-time dependency inferenceengine (modules: IE::inference_engine) found: YES 2.1.0
```

**system parameters**
* This is just a plain native build
* Operating system is Ubuntu 18.04
* Python version is 3.6.9
* meson version is 0.53.0

**Comment by mensinda** [comment]
Should be fixed by #6444
