### ISSUE TITLE
Solving the LD issue

### ISSUE THREAD

**Issue by dcbaker** [mesonbuild/meson#6442]
I think we (I) made a mistake with LD cross/native ld. We've caused a lot of regressions and our use of LD differs from what autotools does, which is confusing. I wonder if the best solutions is to (if IIRC) match autotools and go to a CCLD, CXXLD, etc environment variable, and remove LD. We could CCLD would only apply the C compiler, CXXLD would only apply to the C++ compiler, etc. If we want to go this route it would be a backwards incompatible change, and I'd like to land it for 0.53.1, with apologies. My plan would be that CCLD would work the same way the LD currently does, that is, if the C compiler is GCC like then the linker would be invoked with `$CC -fuse-ld=$CCLD`, for msvc it would be invoked as a binary, say `lld-link.exe`.

Is my understanding of autotools correct, and does this plan make sense? Are we willing to make a backwards incompatible change after the release?

Related #6413, #6431 

@eli-schwartz, @jpakkane, @textshell  (I think there was someone else on IRC who had opinions about this)

**Comment by eli-schwartz** [comment]
More specifically, autotools defines CCLD=$(CC), and also defines an LD variable... but linking binaries/libraries with gcc/g++ is always performed via libtool, by defining LINK as `libtool --tag=CC $(AM_LIBTOOLFLAGS)  $(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@` and then links with that.

libtool doesn't do anything with LD except for reload_cmds (ld -r). autotools expects you to define the linker via *FLAGS.

$CCLD doesn't do anything, it's overridden and internal to autotools so you cannot modify it AFAICT.

**Comment by dcbaker** [comment]
> $CCLD doesn't do anything via the environment, it's overridden and internal to autotools so you cannot modify it AFAICT.

So, either we don't need an env variable at all and just do this via config files (and you can do it by setting CFLAGS etc) or we can use CCLD without any fear of causing conflicts with autotools?

**Comment by Arfrever** [comment]
Are you planning only one variable or several separate variables (for consistency with [this](https://mesonbuild.com/Reference-tables.html#language-arguments-parameter-names) maybe `c_linker`, `cpp_linker`, `fortran_linker`, `objc_linker`, `objcpp_linker` etc.)?

**Comment by dcbaker** [comment]
A single one, in keeping with the way you set the compiler,

```sh
CC=clang CCLD=lld meson build
```
or
```ini
[binaries]
cc = '/usr/bin/clang'
ccld = 'lld'
```

**Comment by Arfrever** [comment]
In Gentoo, [`c` (not `cc`) and `cpp` are separately set in cross file](https://gitweb.gentoo.org/repo/gentoo.git/tree/eclass/meson.eclass?id=12688db23547abe05078bb4da81d2ec18a538c7f#n153).

If some project wanted to call linker directly (not through compiler driver and `-fuse-ld=`), what would be the way to select linker in Meson? `LD` environment variable or `ld` variable in cross file?

**Comment by jpakkane** [comment]
Sorry for the drive-by comment, but I'm currently traveling and have not had much sleep.

Anyway, an idea that came up is that we could keep the old approach by doing something like the following:

- choose linker based on LD or cross file, it points to an executable
- detect the linker type (`ld --version` etc)
- store that
- add a compiler getter to make that compiler use the given linker
- so for example gcc with bfd would return nothing, whereas gcc with gold would return `-fuse-ld=gold`
- if the compiler is given an impossible combination like VS compiler with Gold, error out

This would make the case where people do `find_program('ld')` to get the cross linker to do their own thing work.

**Comment by Arfrever** [comment]
>     * so for example gcc with bfd would return nothing, whereas gcc with gold would return `-fuse-ld=gold`

GNU Binutils can be [configured with `--enable-gold=default`](https://sourceware.org/git/?p=binutils-gdb.git;a=blob;f=configure.ac;h=544fab3d2097cb1e6bc572cc8c060baa9ec108b6;hb=HEAD#l307) which results in using GOLD linker by default, even without `-fuse-ld=gold`.
([Gentoo users can use above feature to decide which linker is used by default.](https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-devel/binutils/binutils-2.33.1-r1.ebuild?id=06a60cd676554f19aac444144f4375d998b1fb50#n186))

**Comment by dcbaker** [comment]
@Arfrever, you're right about the cc -> c typo, I've fixed my comment. Sorry for the confusion.

> GNU Binutils can be configured with --enable-gold=default which results in using GOLD linker by default, even without -fuse-ld=gold.

It's actually even more complicated than that, because you can configure gcc to use a linker other than gnu ld (solaris does this)

**Comment by dcbaker** [comment]
@jpakkane, I think the real problem here is that there are already a fair number of projects who want to invoke ld directly (ie, in a custom target), using `ld` in the binaries section for that. Which means when we started using it for choosing the dynamic linker we broke all of the projects.

**Comment by jmesmon** [comment]
As a data point: I've never seen using the environment variables like `LD` or `CCLD` to be anything other than a _program_ to be executed. If we want to specify a linker id, it should avoid using these.

**Comment by dcbaker** [comment]
I've opened a pull request  implementing my proposal, feedback welcome.

**Comment by jmesmon** [comment]
@Keruspe I don't know that this is exactly the same a linker flavor. In particular, it doesn't distinguish between `gcc -fuse-ld=bfd` and `gcc -fuse-ld=gold` (both are `LinkerFlavor::Gcc`).

**Comment by SantiagoMejia-Toptal** [comment]
To solve the error:
`./.build_env_vars.sh: line 427: declare: UID: readonly variable
<app-name>/platforms/ios/internal/nsld.sh failed with exit code 1`
Go to the file 
>
/platforms/ios/internal/nativescript-build.xcconfig
>
 inside your app project and change the line:
`LD = $SRCROOT/internal/nsld.sh` for `NS_LD = $SRCROOT/internal/nsld.sh` and run again.
