### ISSUE TITLE
Problems with wrap patches in 0.53

### ISSUE THREAD

**Issue by mikezackles** [mesonbuild/meson#6445]
**Describe the bug**

I'm storing `meson.build` files for third-party projects locally and generating wrap files along with the corresponding patch archives so that meson can download the sources and apply the patches.
Prior to 0.53 I could use `file://` urls for `patch_url`, but that now fails. The docs say `patch_filename` can be used to pull patches from `subprojects/packagecache`, but this *only* works if `patch_url` is set as well.

So, as a workaround, I generate my patches and put them in the cache folder and then set `patch_url` to a dummy URL. This works OK for me, but I can imagine this behavior being pretty confusing. I'd be interested in knowing if there is some other recommended way to handle this scenario.

**To Reproduce**

Worked before 0.53:
```
[wrap-file]
directory = function2-4.0.0

source_url = https://github.com/Naios/function2/archive/4.0.0.tar.gz
source_filename = function2-4.0.0.tar.gz
source_hash = 6bc62a300cc54586f5ba0a2a04118ddf88c1076bd0329b21d7bed78f838baa43

patch_url = file:///i/am/an/absolute/path/function2-4.0.0_patch.tar
patch_filename = function2-4.0.0_patch.tar
patch_hash = af17f322d6f1d622f61f4ca3fdc470a8a1e01bd315ab32846aeba259a345d3cf
```

After 0.53, with `function2-4.0.0_patch.tar` in `subprojects/packagecache`:
```
[wrap-file]
directory = function2-4.0.0

source_url = https://github.com/Naios/function2/archive/4.0.0.tar.gz
source_filename = function2-4.0.0.tar.gz
source_hash = 6bc62a300cc54586f5ba0a2a04118ddf88c1076bd0329b21d7bed78f838baa43

patch_url = https://pointless.url.com
patch_filename = function2-4.0.0_patch.tar
patch_hash = af17f322d6f1d622f61f4ca3fdc470a8a1e01bd315ab32846aeba259a345d3cf
```

**Expected behavior**
Either `file://` works or `patch_filename` works without `patch_url`

**system parameters**
* both regular and cross compile
* Arch Linux
* Python 3.8.1
* meson 0.53.0
* ninja 1.9.0

**Comment by xclaesse** [comment]
This is a regression introduced by https://github.com/mesonbuild/meson/pull/6238.
@scivision ^
