### ISSUE TITLE
link_language has no effect

### ISSUE THREAD

**Issue by burp** [mesonbuild/meson#6453]
A patch from issue 1534 introduced link_language, but I believe that it is not working and the introduced test case does not test link_language, see https://github.com/mesonbuild/meson/issues/1534

The introduced patch does not seem to work and the supplied test case does not seem to be a proper test of the functionality. This is because the C component is only supplied as a library and it will therefore select the Fortran compiler for linking. From a discussion in #mesonbuild we figured out that "as far as executable() can tell, it is fortran-exclusive code, and shared libraries don't have a language type."

A minimal example is:

project('tproj', ['fortran','cpp'])
executable('run', ['test.f90','test.cpp'], link_language: 'fortran')

then it generates rule cpp_LINKER with the gcc command instead of gfortran

**Comment by dcbaker** [comment]
just to be clear, the cpp_LINKER rule *should* be generated with g++, however there should also be a fortran_LINKER rule with gfortran (or whatever), and your target should be using the fortran_LINKER, not the cpp_LINKER.

@scivision, you're probably interested

**Comment by scivision** [comment]
OK I thought it did work for some cases, but maybe I fooled myself or it was not really that general.

**Comment by freddy77** [comment]
I'm trying to do a similar thing forcing a C linker with some C++ sources using `both_libraries` but Meson is going a warning that `link_language` is not a valid keyword despite documentation states should be.

**Comment by dcbaker** [comment]
`link_language` is only valid for executables. It should only be necessary for executables because meson cannot always figure out which language implements the main() function.

What are you trying to achieve by using the C linker instead of the C++ linker?

**Comment by freddy77** [comment]
To make sure I don't depend on C++ libraries. It's supported by autoconf so why you need to limit this feature? Shared libraries are not much different from executables, usually there's a flag/number in the binary to change it. From documentation (https://mesonbuild.com/Reference-manual.html)

```
Executable supports the following keyword arguments. Note that just like the positional arguments above, these keyword arguments can also be passed to shared and static libraries.
```

**Comment by ebraminio** [comment]
FWIW we like to have this in HarfBuzz also, we were able to choose our linker like this https://github.com/harfbuzz/harfbuzz/blob/748e1cf/src/Makefile.am#L120-L129 in autotools and implement the same in cmake https://github.com/harfbuzz/harfbuzz/blob/e860000/CMakeLists.txt#L481-L488 but not in meson apparently.
