### ISSUE TITLE
Changes to the release process to avoid breakages in finalized interface

### ISSUE THREAD

**Issue by dcbaker** [mesonbuild/meson#6456]
I'd like to propose that we make release candidates before the .0 release. As the mesa maintainer we've had a *lot* of success with using rcs to get feedback from users and developers who wont track git, but will upgrade to -rc1 immediately. It also gives distros a signal that we'd like their feedback, as they can put those in their bleeding edge repos and start building with that version.

@mesonbuild/core-maintainers

**Comment by jpakkane** [comment]
Seems good to me.

**Comment by xclaesse** [comment]
We currently freeze one week before the release, it would make sense to do an -rc1 at that moment, and if regressions are found we could have to postpone the release for one week and thus do a -rc2, etc.

**Comment by mensinda** [comment]
+1 for rc releases from me.

I think we should also expand our test setup. Maybe we could also add some nightly tests (via [GitHub actions on.schedule](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#scheduled-events-schedule)) with more distributions / environments / compilers. We could also include some external meson projects as "integration tests".

**Comment by dcbaker** [comment]
@xclaesse, that's how mesa does -rc1, so that makes sense to me. We open an X.Y milestone when we make the release, when that milestone is completely resolved we make the X.Y.0 release. Does that process make sense for meson too?

**Comment by amitdo** [comment]
@mensinda,

>We could also include some external meson projects as "integration tests".

https://github.com/jon-turney/meson-corpus-test
https://github.com/jon-turney/meson-corpus-test-update
