### ISSUE TITLE
wrapdb.mesonbuild.com down?

### ISSUE THREAD

**Issue by vincent-picaud** [mesonbuild/meson#6460]
I cannot reach wrapdb.mesonbuild.com anymore. Is the site down?

Symptoms: 
> 
> Version: 0.52.1
> Source dir: /home/picaud/GitHub/LinearAlgebra
> Build dir: /home/picaud/GitHub/LinearAlgebra/build
> Build type: native build
> Project name: LinearAlgebra
> Project version: 0.0.1
> C++ compiler for the host machine: ccache c++ (gcc 9.2.1 "c++ (Debian 9.2.1-22) 9.2.1 20200104")
> C++ linker for the host machine: GNU ld.bfd 2.33.1
> Host machine cpu family: x86_64
> Host machine cpu: x86_64
> Using gtest source from cache.
> Downloading gtest patch from https://wrapdb.mesonbuild.com/v1/projects/gtest/1.8.0/5/get_zip
> SSL connection failed. Falling back to unencrypted connections.
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 129, in run
>     return options.run_func(options)
>   File "/usr/lib/python3/dist-packages/mesonbuild/msetup.py", line 245, in run
>     app.generate()
>   File "/usr/lib/python3/dist-packages/mesonbuild/msetup.py", line 159, in generate
>     self._generate(env)
>   File "/usr/lib/python3/dist-packages/mesonbuild/msetup.py", line 192, in _generate
>     intr.run()
> etc...

It is not the first time I encountered the problem. Maybe it would be nice to have some kind of mirror site on GitHub, or something like that?

Beside that, Meson is great, I use it everyday, thank a lot!
--Vincent

**Comment by gregsskyles** [comment]
Definitely a known issue, see #6446 and others...

**Comment by xclaesse** [comment]
Closing as dup.

**Comment by vincent-picaud** [comment]
Oh, sorry for the repeated "issue" message, I did not see the one of your link before posting.
Thank for the feedback.

**Note:**
Maybe useful for others, gtest as example. 

The last time it happened I forked gtest in my own github, manually added the wrapdb meson.build files and replaced the initial gtest.wrap (that uses wrapdb)
```
[wrap-file]
directory = googletest-release-1.8.0

source_url = https://github.com/google/googletest/archive/release-1.8.0.zip
source_filename = gtest-1.8.0.zip
source_hash = f3ed3b58511efd272eb074a3a6d6fb79d7c2e6a0e374323d1e6bcbcc1ef141bf

patch_url = https://wrapdb.mesonbuild.com/v1/projects/gtest/1.8.0/5/get_zip
patch_filename = gtest-1.8.0-5-wrap.zip
patch_hash = 7eeaede4aa2610a403313b74e04baf91ccfbaef03203d8f56312e22df1834ec5

```
by this one (redirecting to my github repo)
```
[wrap-git]
directory = gtest
url = https://github.com/vincent-picaud/googletest.git
revision = head
```

**Comment by xclaesse** [comment]
You can replace the link with github indeed, but we are not doing that automatically because we don't want to be locked in github. URLs must be on a domain we control.

**Comment by vincent-picaud** [comment]
I understand and agree.
My post was just an exposition of the trick I use for my projects when wrapdb is down.
