### ISSUE TITLE
Cross build linker detection regression

### ISSUE THREAD

**Issue by sdonnan** [mesonbuild/meson#6473]
## Issue ##

meson version 0.53 no longer detects `arm-none-eabi-gcc` toolchain. Fails to detect the linker

    meson.build:35:0: ERROR: Unable to determine dynamic linker  

## Reproduce ##

On Ubuntu 18.04 (tested in Docker) building `picolibc`

```
apt install git gcc-arm-none-eabi ninja-build
git clone https://github.com/keith-packard/picolibc.git
cd picolibc
mkdir build
cd build
../do-arm-configure
```
Result:

```
Version: 0.53.0
Source dir: /tmp/picolibc
Build dir: /tmp/picolibc/build
Build type: cross build
Project name: picolibc
Project version: 1.3
C compiler for the build machine: cc (gcc 7.4.0 "cc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0")
C linker for the build machine: cc GNU ld.bfd 2.30

meson.build:35:0: ERROR: Unable to determine dynamic linker
```

## Expected Behavior ##

Configures project successfully. This works with version 0.52.1

## System Parameters ##

* Cross build for `arm-none-eabi-gcc` (6.3.1 and 9.2.1 tested)
* Ubuntu 18.04
* Python 3.6.9
* meson version 0.53.0
* ninja version 1.8.2

## Additional Information ##

Running the build through `strace` shows the reported error when meson is calling to `arm-none-eabi-gcc` 

    arm-none-eabi-gcc: error: unrecognized command line option '-fuse-ld=arm-none-eabi-ld'

**Comment by ckrzen** [comment]
Confirming that downgrade to 52.1 works while building NetworkManager(networkmanager) in CRUX 3.5 using this build recipe: https://crux.nu/ports/crux-3.5/contrib/networkmanager/Pkgfile

**Comment by dcbaker** [comment]
This is related to having an `ld` entry in the `binaries` section of your cross file, this is being tracked in #6442

**Comment by keith-packard** [comment]
I've pushed a fix for this to the picolibc repository (removing the 'ld' entries). Thanks so much!
