### ISSUE TITLE
subproject options can't be set if project is added after initial configure

### ISSUE THREAD

**Issue by ocrete** [mesonbuild/meson#6477]
**Describe the bug**

If I configure a project with a subproject, but the subproject is disabled somehow. Then I want to add it (how gst-build works), then I can't access the subproject's options..

**To Reproduce**
```
git clone https://gitlab.freedesktop.org/gstreamer/gst-build.git
meson build
ninja -C build
```
Then either of the following commands fail:
```
meson configure build -Domx=enabled
meson configure build -Domx=enabled -Dgst-omx:target=generic
```

**Expected behavior**
I expect meson to see that I've enabled a subproject somehow and let me specify options for it... It possibly means tying the option somehow to the subproject...

**Comment by xclaesse** [comment]
After setting options, Ninja should trigger in reconfigure. It doesn't?

**Comment by ocrete** [comment]
With the first command, the reconfigure fails because the default option (none) causes an abort of the configure.. And I can,t use the second option because meson refuses option it doesnt already know about!

**Comment by xclaesse** [comment]
This should work: `meson build --reconfigure -Domx=enabled -Dgst-omx:target=generic`

**Comment by tp-m** [comment]
I thought there was an issue somewhere about this already (unless it's supposed to have been fixed and I missed it).

**Comment by ocrete** [comment]
This --reconfigure does work.. I guess meson configure should return a "maybe try setup --reconfigure as I dont know this option for this subproject" ... ? ;)
