### ISSUE TITLE
[Suggestion] A semi-official repository for trial conversions

### ISSUE THREAD

**Issue by AndersonTorres** [mesonbuild/meson#6502]
Hello, Meson guys! And anticipated apologies for my bad English skills...

I am studying the Meson build system in order to use it in my toy projects and like.

Cutting to the chase: what about to create a place for the [trial conversions](https://mesonbuild.com/Trial-conversions.html) in a Git repo?

First of all, some of those trial conversions are now broken links links to Dropbox files (I could download only SDL2). It is a bit frustrating, because I wanted to look at them and learn something. The tutorials and official docs are good, no problem with that, but looking at a real-life project adds a sense of matureness, like "awesome, it can compile Mesa!".

In that sense, a git repo could shelter those trial conversions. And better, it could shelter other future conversions as well (personally, I wanna try Meson on [MPV Player](https://mpv.io), just for fun).

That way, I want to suggest a community-driven repository for them. 

Certainly, it will be detached from main repo, something like "meson-community/trial-conversions" (or maybe even "mesonbuild/trial-conversions", why not?). I know the main developers are already busy with Meson, then the "trial conversions" repo would be managed independently by the community itself.

And, on the long run, the trial conversions repo will be a good source for testing Meson.

What do you think, people?

Thanks in Advance!

Anderson

**Comment by jpakkane** [comment]
Those trial conversion come from a long time ago, when Meson did not have many users. We should probably remove that page, because it is no longer needed. A better approach today would be to go to the page listing existing projects that use Meson and examine their build definitions:

https://mesonbuild.com/Users.html

**Comment by AndersonTorres** [comment]
Oh, my bad :/ Well, seizing the opportunity: do you have those lost files yet, @jpakkane ?

**Comment by jpakkane** [comment]
IIRC all the Dropbox links went to my personal DB instance. If they no longer work it's because I have deleted them as no longer needed. They are probably not stored anywhere else any more (if they ever were).

**Comment by eli-schwartz** [comment]
Entirely removed in #6508
