### ISSUE TITLE
Automatically generated .gitignore / cvsignore / ? in the build directory

### ISSUE THREAD

**Issue by Salamandar** [mesonbuild/meson#6509]
As the build directory is a newly created directory, it could safely contain a `.gitignore` that ignores itself.

I don't know how other vcs work, but meson may/should try to detect which vcs is used (by checking existence of .git ?)

```
# Meson generated .gitignore
*
```

**Comment by jpakkane** [comment]
Or, more simply, just write blocker files for all possible vcs:s.

This may be problematic if there are people who want to put their build directories in revision control. I don't know why anyone would, but every single time I have said that someone has come up and claimed that they need it.

**Comment by Salamandar** [comment]
Yes, that would probably be cheaper (less code, better performance) than checking which vcs is used.

**Comment by Salamandar** [comment]
> This may be problematic if there are people who want to put their build directories in revision control. I don't know why anyone would, but every single time I have said that someone has come up and claimed that they need it.

That's weird.

It can be a meson project configuration : `-Dvcs_ignore=false`

**Comment by jpakkane** [comment]
Yes, but one of the main design points of Meson is, and has always been, to minimize the number of toggle options. This issue is not serious enough to warrant an option.

**Comment by michaelbadcrumble** [comment]
This seems better suited for the `meson init` command. Not the automatic part but a new option for adding `.gitignore`.

**Comment by Salamandar** [comment]
@michaelbadcrumble meson init does not create a build directory, right ?

**Comment by michaelbadcrumble** [comment]
Will if `--build` is passed then yes it does.

**Comment by eli-schwartz** [comment]
> I don't know why anyone would, but every single time I have said that someone has come up and claimed that they need it.

They should use `git add --force`, which might also remind them of why it's a terrible idea to commit it.

Given the files in question embed absolute paths to the build directory, it's unacceptably wrong to do so either way, and we should not feel afraid to tell them that.

**Comment by Salamandar** [comment]
Looks like those people are trying to commit useful generated files. As Meson does not allow to write in the source directory, I can understand the motivation.
For example, Gimp needs to re-generate huge indexes, and generated source files that need to be committed for easier debug. That's really hard to set up with Meson.

**Comment by jpakkane** [comment]
Maybe we could do something like this:

- generate the gitignore file on init
- add a comment to the file that says something like "this file has been autogenerated by Meson, if you don't want it you can delete it and it won't be regenerated"

This should do the right thing 99% of the time and the last 1% can do their own thing without needing to add options or switches to Meson.

**Comment by eli-schwartz** [comment]
> Looks like those people are trying to commit useful generated files. As Meson does not allow to write in the source directory, I can understand the motivation.
> For example, Gimp needs to re-generate huge indexes, and generated source files that need to be committed for easier debug. That's really hard to set up with Meson.

Related: https://github.com/mesonbuild/meson/issues/7156

I'm sympathetic for `meson dist`, which should not be checked into git, and unsympathetic for committing generated artifacts on every commit. Seems like the latter is the case in question.

Either way, git committing the *builddir/* is totally wrong, but the recommendation there was to have a custom generation script that wrote out two copies of the file, once to the source tree.

**Comment by Salamandar** [comment]
> Either way, git committing the _builddir/_ is totally wrong

100% agree, I was just trying to find an explanation about why that would be "needed".
