### ISSUE TITLE
Documentation site out-of-date

### ISSUE THREAD

**Issue by hexchain** [mesonbuild/meson#6510]
**Describe the bug**
The current documentation site is out-of-date. I found this by wasting some time to find out that `LD` environment variable no longer works, and has been split into language-specific ones. The page in question is [this page](https://mesonbuild.com/howtox.html).

<details>
<summary>Screenshot taken on Fri 24 Jan 2020 11:25:31 PM UTC</summary>

![image](https://user-images.githubusercontent.com/529520/73111052-28ccfe00-3f09-11ea-97ba-60768b5b182a.png)
</details>

**Comment by dcbaker** [comment]
@hexchain, That page is out of date compared to what I'm seeing, but there are some typos in the docs so I've opened a PR.

**Comment by hexchain** [comment]
I've checked that page again and now it does reflect the `*_LD` name changes, so the original issue is gone. Thanks!
