### ISSUE TITLE
Getting unwanted files in root directory (Swift project template):

### ISSUE THREAD

**Issue by michaelbrockus** [mesonbuild/meson#6514]
**Describe the bug**
I started on a new batch of Meson sample templates for Java, Objective-c++, Swift, Cuda, and hit a snag when I was getting unwanted files being generated in the root directory of the generated swift project, I also tested this with a swift project that already exists in Meson test cases, as a sanity check and got same results.  It seems similar to when D projects were generating those files.

**To Reproduce**
This is the zip file with all the required information for the recreation of the issue.
[swift-exe-issue.zip](https://github.com/mesonbuild/meson/files/4112966/swift-exe-issue.zip)

**Expected behavior**
I expected a nationally generated sample project for the Swift programming language, so I may add this as part of my PR for adding more template definitions to the Meson project template library.

**system parameters**
* just a plain native build?
* Mac OSX
* Python version 3.8.0
* meson version 0.53.1
* ninja version 1.9.0

**Comment by michaelbadcrumble** [comment]
Has anyone fixed this issue yet?
