### ISSUE TITLE
[D] crosscompile: ldc2 isn't knows appropriate machine architecture

### ISSUE THREAD

**Issue by denizzzka** [mesonbuild/meson#6522]
While building cross-compile project what uses D and C both:

ldc2 compiler is not knows about target architecture, appropriate options is not passed to it. As result, it produces binaries for build machine arch.
Nonetheless C compiler (clang) works fine.

ninja output:
```
[...]
Project version: v0.0.1
C compiler for the build machine: cc (gcc 9.2.1 "cc (Debian 9.2.1-23) 9.2.1 20200110")
C linker for the build machine: cc GNU ld.bfd 2.33.50.20200115
C compiler for the host machine: clang (clang 8.0.1-4 "clang version 8.0.1-4 (tags/RELEASE_801/final)")
C linker for the host machine: clang GNU ld.bfd 2.33.50.20200115
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: arm
Host machine cpu: cortex-m3
Target machine cpu family: arm
Target machine cpu: cortex-m3
[...]
D compiler for the build machine: ldc2 (llvm 1.18.0 "LDC - the LLVM D compiler (1.18.0):")
D linker for the build machine: ldc2 GNU ld.gold 2.33.50.20200115
D compiler for the host machine: ldc2 (llvm 1.18.0 "LDC - the LLVM D compiler (1.18.0):")
D linker for the host machine: ldc2 GNU ld.gold 2.33.50.20200115
Build targets in project: 5
[...]
```

**Expected behavior**
ldc2 should cross compile without setting up additional args in cross.txt file:
```ini
[host_machine]
system = 'bare metal'
cpu_family = 'arm'
cpu = 'cortex-m3'
endian = 'little'

[properties]
d_args = ['-march=thumb', '-mcpu=cortex-m3'] # <--- temporary fix for this issue
```

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
Cross build

* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
Debian Linux

* what Python version are you using e.g. 3.8.0
3.7.3

* what `meson --version`
0.53.1

* what `ninja --version` if it's a Ninja build
1.8.2

**Comment by jpakkane** [comment]
If LDC does not provide a prefixed binary but instead requires specifying the target architecture with command line arguments (which is what I think most LLVM based tools do), then adding the necessary arguments to `d_args` is the correct and expected way to handle this. If it does provide a prefixed binary, then your d compiler should be specified in the cross file with something like:

    d = '/usr/bin/arm-none-ldc2`

or whatever the name of the binary is.

**Comment by denizzzka** [comment]
> If LDC does not provide a prefixed binary 

Yes

Ok, thanks!
