### ISSUE TITLE
Please explain in the documentation how to use options

### ISSUE THREAD

**Issue by haferburg** [mesonbuild/meson#653]
On https://github.com/mesonbuild/meson/wiki/Build-options it says:

>  They have to be set externally. The easiest way to change them is to use the Meson GUI or command line tools.

I couldn't find much about the Meson GUI, so I'm guessing it was discontinued. Why "tool**s**", are there more than one (meson.py)?

On https://github.com/mesonbuild/meson/wiki/Running%20Meson a bold claim is made:

> Meson comes with extensive command line help

I did not find this to be true, but maybe I'm missing something. Maybe there is a feature like the very useful `svn help` and `svn help <command>`, and I couldn't find it. If there is not I would humbly request that the word "extensive" is removed.

Anyways. What is the syntax for `meson -D`? It would be great is there was explained in the documentation or in the `meson --help`.

**Comment by jpakkane** [comment]
Updated. Thanks.
