### ISSUE TITLE
Adding an option to an existing meson project that causes the configure step to fail

### ISSUE THREAD

**Issue by haferburg** [mesonbuild/meson#654]
My goal is to add an option to configure where libraries reside. Unfortunately that means that the default value is going to cause the build to fail.

Now, when I call `mesonconf` it says that it doesn't know that the option exists. I'm not allowed to run `meson -D` to set the option because the build dir already exists and it's telling me "If you want to build it, just run your build command". So I'm guessing the only way that's left is to delete the entire build dir, and build from scratch. And I think that means the values of all the other options are lost as well, which is not good. So I'd at least have to set the options that would cause the configure step to fail on the meson command line in order to be able to use mesonconf again.

`mesonconf` knows the source dir, so it knows how to find meson_options.txt. Couldn't it simply parse that file and allow the user to configure the value even though meson never ran successfully after the option was added?

**Comment by jpakkane** [comment]
You can change your build options file so that the default value does not fail and after running it once change it back. This is not perfect but this is a rare case and fixing it properly would require changing a lot of code.

**Comment by nirbheek** [comment]
This is fixed now; you should run `ninja reconfigure` in such a situation.
