### ISSUE TITLE
get_option(localstatedir,, sharedstatedir and sysconfdir) are relative

### ISSUE THREAD

**Issue by Salamandar** [mesonbuild/meson#6546]
Those options should be `/var` and `/etc` according to existing/closed issues, merge requests and documentation, but i've had for ages relative values `var` and `etc`.

I need to pass the absolute paths to configuration_data(), but i can neither pass the value given by get_option(), nor concatenate with get_option('prefix').

What should be done ?

**Comment by Salamandar** [comment]
Also, my prefix is `/usr/local` so I expected to get at least localstatedir=var/local, and that's not the case.

**Comment by jon-turney** [comment]
Yeah, this seems to have broken somewhere between #2511 and now:

``` meson
project('o')
foreach o : ['prefix', 'localstatedir', 'sharedstatedir']
  message('@0@ is @1@'.format(o, get_option(o)))
endforeach
```
```
$ rm -r _build ; meson setup _build
[...]
Message: prefix is /usr/local
Message: localstatedir is var
Message: sharedstatedir is com
```

works as expected when prefix is explicitly specified, though:

```
$ rm -r _build ; meson setup _build --prefix=/usr/local
[...]
Message: prefix is /usr/local
Message: localstatedir is /var/local
Message: sharedstatedir is /var/local/lib
```

**Comment by Salamandar** [comment]
@jpakkane Is it possible to fix old version of Meson too ? Github tells me the first bad commit is present since 0.51.0.

**Comment by jon-turney** [comment]
I suggest this should be tagged for 0.53.2, since it is a regression.

**Comment by jpakkane** [comment]
Added.
