### ISSUE TITLE
meson cannot download http://ijg.org/files/jpegsrc.v9c.tar.gz source file

### ISSUE THREAD

**Issue by fzwoch** [mesonbuild/meson#6571]
Not sure whether this is a bug in this particular wrap or a problem with meson in general or with this host. Using other wraps like libpng, expat etc works fine.

Simply trying to use this wrap as a subproject results in an error while downloading the source .tar.gz file.

```
$ meson --version
0.53.1
```

When the subproject is supposed to be build it errors:

```
Downloading libjpeg source from http://ijg.org/files/jpegsrc.v9c.tar.gz

meson.build:63:0: ERROR: could not get http://ijg.org/files/jpegsrc.v9c.tar.gz is the internet available?
```

However manually downloading the URL seems to be okay:

```
curl http://ijg.org/files/jpegsrc.v9c.tar.gz -o subprojects/packagecache/jpegsrc.v9c.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1004k  100 1004k    0     0   934k      0  0:00:01  0:00:01 --:--:--  934k
```

Re-running the build then succeeds as expected.

**Comment by scivision** [comment]
To avoid hard-coding a user agent, would it be feasible to add UserAgent as a parameter in the .wrap file? That way, over time as user agent filters are updated, the Meson .wrap users/authors can simply update that parameter in their .wrap file for their particular server. As this is really a server-by-server issue.

**Comment by legeana** [comment]
This approach sounds quite sensible. I am just wondering if we are supposed to be doing it in the first place. Maybe these websites don't like scripts to access them and these wraps should not be allowed. Point is it feels as a deliberate block and circumventing it is questionable.

**Comment by jpakkane** [comment]
Yeah. It's strange for people to put source code up for downloading and then block people when they do.

**Comment by scivision** [comment]
There are a number of scientific computing libraries that hide behind JavaScript license clickwrap to download source or binary. I suppose it's up to end-users to comply. I think there's just a disconnect between institutional policy and usability. Like institutional policies to only release source code on defunct sites or obsolete server security practice for source code release.

**Comment by legeana** [comment]
I tested the ijg website specifically and it blocks Python but doesn't block other custom User-Agents. What I am thinking now is to run a script over all of our wraps and try to download them with different user agents.

My idea is that we can put a custom one, say `Mesonbuild-Client/1` or something and if the website blocks that it's pretty much on purpose. If they block a generic Python script then maybe they protect against random scripters.

**Comment by legeana** [comment]
Seems libjpeg issue is fixed for now by the website owner.

**Comment by eli-schwartz** [comment]
In #7381 I implemented a custom mesonbuild user agent because this was an issue again. I think this is the right approach -- if sites want to block meson, that is their right, but it shouldn't happen by accident just because they tried to blanket-ban people running random generic scripts.

**Comment by scivision** [comment]
CMake `file(DOWNLOAD ...)` allows specifying HTTP headers. Hopefully just not having the generic Python useragent will suffice as in #7381.
