### ISSUE TITLE
Override `prefix` in pkgconfig generated files

### ISSUE THREAD

**Issue by Salamandar** [mesonbuild/meson#6576]
In some (rare) cases, we need to override the prefix in the pkgconfig file.

Meson doesn't allow that. It should.

**Comment by dcbaker** [comment]
In what case are you talking about, you can do `dep.get_variable(pkgconfig : 'foo', pkgconfig_define : ['path', '/'])`, I dont know if that solves your issue though.

**Comment by Salamandar** [comment]
`dbus` needs to generate a custom `pkgconfig` file with a *relative* prefix (precisely, `'${pcfiledir}/../..'`), because Windows builds may be relocatable (i.e non-constant prefix).

**Comment by xclaesse** [comment]
Could you paste dbus PC file to understand what they do? I don't see why dbus would have deferent needs than everyone else.

**Comment by Neumann-A** [comment]
@Salamandar 
Can you use the environment?. I use the following in CMake: 
`set(ENV{PKG_CONFIG} "$ENV{PKG_CONFIG} --define-variable=prefix=${SOME_OTHER_PREFIX}")`

**Comment by fluidparadigms** [comment]
I would also like to be able to set `prefix` to `'${pcfiledir}/../..'`. It would be very helpful in for generating a pre-built binary package that users could "install" wherever they want by just copying the directory to their specific computer. This is especially true if the target computer isn't connected to a network.

**Comment by Salamandar** [comment]
> @Salamandar
> Can you use the environment?. I use the following in CMake:

No because I need to generate 2 pkg-config files : 
* One normal one
* One with the custom pkg-config prefix.

**Comment by eli-schwartz** [comment]
This was implemented as a special case in #10277. There's now a `meson setup builddir/` option to create pkg-config files with the special pcfiledir relative path.

I don't think there's an actual need to override it to *arbitrary* values, the use case for pcfiledir is highly specific so specially handling it seems correct. But feel free to comment if you think you have another use case.

In the meantime I am optimistically closing this as implemented. ;)
