### ISSUE TITLE
Sanity check always trying to run a binary when cross building

### ISSUE THREAD

**Issue by makise-homura** [mesonbuild/meson#6594]
**Describe the bug**

After starting a cross build of any project, when crosstool does not have an exe wrapper, I can't make meson avoid running a binary built while checking cross compiler sanity, whatever I set in cross file for `exe_wrapper` (tried: no `exe_wrapper` line at all; `exe_wrapper = ''`; `exe_wrapper = None`; `exe_wrapper = []`).

**To Reproduce**

`hello.c`

```
#include <stdio.h>
int main() { printf("Ok\n"); return 0; }
```

`meson.build`

```
project('hello', 'c')
executable('hello', 'hello.c')
```

`meson.cross`

```
[binaries]
c = '/usr/src/meson-cross-bug/lcc/bin.toolchain/e2k-linux-gcc'
cpp = '/usr/src/meson-cross-bug/lcc/bin.toolchain/e2k-linux-g++'
ld = '/usr/src/meson-cross-bug/lcc/bin.toolchain/e2k-linux-ld'
ar = '/usr/src/meson-cross-bug/lcc/bin.toolchain/e2k-linux-ar'
strip = '/usr/src/meson-cross-bug/lcc/bin.toolchain/e2k-linux-strip'
pkgconfig = ''
exe_wrapper = ''

[properties]
sizeof_int = 4
sizeof_wchar_t = 4
sizeof_void* = 4

alignment_char = 1
alignment_void* = 4
alignment_double = 4

has_function_printf = true

c_args = []
c_link_args = []
sys_root = ''
pkg_config_libdir = ''

[host_machine]
system = 'linux'
cpu_family = 'x86_64'
cpu = 'amd64'
endian = 'little'

[target_machine]
system = 'linux'
cpu_family = 'e2k'
cpu = 'e8c'
endian = 'little'
```

Running:

`mkdir -p cross; cd cross; meson --cross-file ../meson.cross ..`

Note:

I used Elbrus cross compiler on the x86_64 machine placed in `/usr/src/meson-cross-bug/lcc`; but I expect the same behavior with any other toolchain without existing exe wrapper.

**Expected behavior**

Expecting meson running normally and generating `ninja.build`.

Instead of it, meson fails while trying to run binary built by cross compiler, which is obviously impossible:

```
suika /usr/src/meson-cross-bug/helloworld/cross # ../../meson/meson.py --cross-file ../meson.cross ..
The Meson build system
Version: 0.53.999
Source dir: /usr/src/meson-cross-bug/helloworld
Build dir: /usr/src/meson-cross-bug/helloworld/cross
Build type: cross build
Project name: hello
Project version: undefined
C compiler for the build machine: cc (gcc 8.3.0 "cc (Ubuntu 8.3.0-6ubuntu1~18.10.1) 8.3.0")
C linker for the build machine: cc GNU ld.bfd 2.31.1

meson.build:1:0: ERROR: Could not invoke sanity test executable: [Errno 8] Exec format error: '/usr/src/meson-cross-bug/helloworld/cross/meson-private/sanitycheckc_cross.exe'.

A full log can be found at /usr/src/meson-cross-bug/helloworld/cross/meson-logs/meson-log.txt
```

`meson-log.txt`:

```
Build started at 2020-02-06T17:09:27.224225
Main binary: /usr/bin/python3
Build Options: '--cross-file ../meson.cross'
Python system: Linux
The Meson build system
Version: 0.53.999
Source dir: /usr/src/meson-cross-bug/helloworld
Build dir: /usr/src/meson-cross-bug/helloworld/cross
Build type: cross build
Project name: hello
Project version: undefined
No CFLAGS in the environment, not changing global flags.
No LDFLAGS in the environment, not changing global flags.
No CPPFLAGS in the environment, not changing global flags.
Sanity testing C compiler: cc
Is cross compiler: False.
Sanity check compiler command line: cc /usr/src/meson-cross-bug/helloworld/cross/meson-private/sanitycheckc.c -o /usr/src/meson-cross-bug/helloworld/cross/meson-private/sanitycheckc.exe -pipe -D_FILE_OFFSET_BITS=64
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /usr/src/meson-cross-bug/helloworld/cross/meson-private/sanitycheckc.exe
C compiler for the build machine: cc (gcc 8.3.0 "cc (Ubuntu 8.3.0-6ubuntu1~18.10.1) 8.3.0")
C linker for the build machine: cc GNU ld.bfd 2.31.1
Sanity testing C compiler: /usr/src/meson-cross-bug/lcc/bin.toolchain/e2k-linux-gcc
Is cross compiler: True.
Sanity check compiler command line: /usr/src/meson-cross-bug/lcc/bin.toolchain/e2k-linux-gcc /usr/src/meson-cross-bug/helloworld/cross/meson-private/sanitycheckc.c -o /usr/src/meson-cross-bug/helloworld/cross/meson-private/sanitycheckc_cross.exe -pipe -D_FILE_OFFSET_BITS=64
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /usr/src/meson-cross-bug/helloworld/cross/meson-private/sanitycheckc_cross.exe

meson.build:1:0: ERROR: Could not invoke sanity test executable: [Errno 8] Exec format error: '/usr/src/meson-cross-bug/helloworld/cross/meson-private/sanitycheckc_cross.exe'.
```

**system parameters**
* It is a cross build obviously.
* OS is Linux (reproducible on Ubuntu 18.10, OS Elbrus 4.0-rc3)
* Checked on Python 3.5.5, 3.6.7
* meson is current master, commit dc8d2415836953a8e7fbb06931d34caab1bb2bfb
* ninja version does not matter, because we even fail before ninja is to be invoked

**Investigation**

Note the following place in `mesonbuild/compilers/mixins/clike.py`:

```
        if self.is_cross:
            if self.exe_wrapper is None:
                # Can't check if the binaries run so we have to assume they do
                return
            cmdlist = self.exe_wrapper + [binary_name]
        else:
            cmdlist = [binary_name]
```

So, running cross-built binary is avoided only when `is_cross = True` and `exe_wrapper = None`.

I added this line before this check:

` mlog.debug('Checking: is_cross="' + str(self.is_cross) + '", exe_wrapper="' + str(self.exe_wrapper) + '", None = "' + str(None) + '"')`

and got the following in log (while checking cross-compiler sanity):

`Checking: is_cross="True", exe_wrapper="[]", None = "None"`

Note that when checking native compiler sanity, it's ok there:

`Checking: is_cross="False", exe_wrapper="None", None = "None"`

So, I expect that this thing fails because of `exe_wrapper` being `[]`, not `None`.

This is reproducible in two cases: when I specify `exe_wrapper` in `meson.cross` as `''` or `[]`, and when I don't specify it at all. When I try to set `exe_wrapper = None`, meson fails with this message:
`ERROR: Malformed value in cross file variable exe_wrapper.`

**Quick fix**

I changed this line:

`if self.exe_wrapper is None:`

to this:

`if self.exe_wrapper is None or self.exe_wrapper == []:`

After this, everything worked successfully.

But I consider this fix quite dirty, and I'm not ready to make a PR with that fix unless I receive a confirmation it's OK.

**Proposition**

Instead of applying this dirty fix, I suggest a discussion what shall we do with this; probably figure out where `exe_wrapper` becomes `[]` instead of `None`, and force it to become `None` in very that place? Because I'm not sure there's no other comparison like that, and they will also fail when `exe_wrapper` is `[]`.

Or even maybe `exe_wrapper` might be set some specific way to become `None` after meson reads it from cross file?

**Comment by r3d9u11** [comment]
I'm trying to cross-compile gobject-introspection for arm and have got same trouble
Any news?

**Comment by dcbaker** [comment]
Do you have:
```ini
[properties]
needs_exe_wrapper = true
```
in your cross file?

**Comment by r3d9u11** [comment]
Yes, here is my cc file:

```
[host_machine]
system = 'linux'
cpu_family = 'arm'
cpu = 'arm'
endian = 'little'

[build_machine]
system = 'linux'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little' 

[binaries]
c = 'arm-linux-gnueabihf-gcc'
cpp = 'arm-linux-gnueabihf-g++'
ar = 'arm-linux-gnueabihf-ar'
strip = 'arm-linux-gnueabihf-strip'
pkgconfig = ''
exe_wrapper = ''

[properties]
needs_exe_wrapper = true
sys_root = "/home/user/Desktop/arm-device/sysroot"
```

**Comment by dcbaker** [comment]
try remove removing `exe_wrapper = ''` and see if that works.

**Comment by r3d9u11** [comment]
@dcbaker unfortunately same result (I tried to clean gst sources at all, nothing changes):

```
[host_machine]
system = 'linux'
cpu_family = 'arm'
cpu = 'arm'
endian = 'little'

[build_machine]
system = 'linux'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little' 

[binaries]
c = 'arm-linux-gnueabihf-gcc'
cpp = 'arm-linux-gnueabihf-g++'
ar = 'arm-linux-gnueabihf-ar'
strip = 'arm-linux-gnueabihf-strip'

[properties]
needs_exe_wrapper = true
sys_root = "/home/user/Desktop/arm-device/sysroot"
```

```
The Meson build system
Version: 0.52.0
Source dir: /home/user/gst-src/gstreamer-1.16.2
Build dir: /home/user/gst-src/gstreamer-1.16.2/build
Build type: cross build
Project name: gstreamer
Project version: 1.16.2
Appending CFLAGS from environment: ' --sysroot=/home/user/sysroot'
Appending LDFLAGS from environment: ['--sysroot=/home/user/sysroot', '-Wl,-rpath-link,/home/user/sysroot/lib/arm-linux-gnueabihf', '-Wl,-rpath-link,/home/user/sysroot/usr/lib/arm-linux-gnueabihf']
Appending CPPFLAGS from environment: ' --sysroot=/home/user/sysroot'
/lib/ld-linux-armhf.so.3: No such file or directory

meson.build:1:0: ERROR: Executables created by c compiler /home/user/gst-src/gcc-linaro-5.5.0-2017.10-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc are not runnable.

A full log can be found at /home/user/gst-src/gstreamer-1.16.2/build/meson-logs/meson-log.txt
```

What I'm doing wrong?

**Comment by makise-homura** [comment]
I see in meson 0.54.2 this issue is not reproduced, so I consider this fixed.
Checked with both `exe_wrapper = ''` and no `exe_wrapper` line at all, both ways work.
As issue reporter, I'm closing it.
