### ISSUE TITLE
Meson incorrectly detects loop in CMake custom target

### ISSUE THREAD

**Issue by conte91** [mesonbuild/meson#6632]
**Describe the bug**
 If a CMake subproject contains a custom target in which the basename of the output file is the same as the basename of the input file, importing it into meson will incorrectly generate the following error:
```
meson.build:3:0: ERROR: Cycle in CMake inputs/dependencies detected.
```
Building the same project in CMake works as expected.

**To Reproduce**
* Clone the example repository at https://github.com/conte91/meson_cmake_cycle_issue
* Run `meson build`

**Expected behavior**
The `test.txt` target is correctly detected to be an output file, depending on the input file at `subprojects/test_cmake/test.txt`.

**system parameters**
* Native build
* Arch Linux
* Python 3.8.1
* `meson --version` 0.53.0

**Comment by conte91** [comment]
FYI I've tracked this down to being something wrong in how target names are handled in `class OutputTargetMap`. 
When the following is executed in `ConvertedCustomTarget::postprocess`:
```Python3
             gen = output_target_map.generated(i)                                             
```

The resulting `gen` has the same name as the input file, without any additional path information added to it.

**Comment by mensinda** [comment]
Should be fixed with #6635.

**Comment by jpakkane** [comment]
Can you test if the linked MR fixes the issue for you?

**Comment by conte91** [comment]
> Can you test if the linked MR fixes the issue for you?

Sure, probably tomorrow.

**Comment by conte91** [comment]
Just tested on 6e2ab44b3. This indeed partially solves the issue:

FYI the code I'm adding to my meson project is https://github.com/Yubico/libfido2, and the failure happens at https://github.com/Yubico/libfido2/blob/495ab37da871ddba69297da6ae19a69ca6e8751c/man/CMakeLists.txt#L190 .

I think the core remaining problem here is that in a line like
```CMake
add_custom_command(OUTPUT ${f}
	COMMAND cp -f ${f} .
	DEPENDS ${f})
```
The relative path in the `DEPENDS` option is relative to `${CMAKE_CURRENT_SOURCE_DIR}`, while the relative path in the `OUTPUT` option is relative to `${CMAKE_CURRENT_BINARY_DIR}`.

Note that if I change the former to `DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/${f})`, this now works as expected (and is broken on `master`). 

Changing the `OUTPUT` line to `OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/${f}` has no effect instead (compilation fails), so I assume right now meson thinks both `OUTPUT` and `DEPENDS` paths are relative to `CMAKE_CURRENT_BINARY_DIR`?

**Comment by mensinda** [comment]
Should be fixed with the latest commit in the PR.

**Comment by conte91** [comment]
If I test the test code I attached to this issue on fc5caa7b, it fails to run with the following (but I've played a bit too much with my packages, so this might just be a configuration issue on my machine):

```
The Meson build system
Version: 0.53.999
Source dir: /home/simo/meson_cmake_cycle_issue
Build dir: /home/simo/meson_cmake_cycle_issue/build
Build type: native build
Project name: meson_test
Project version: undefined
C++ compiler for the host machine: c++ (gcc 9.2.1 "c++ (Arch Linux 9.2.1+20200130-2) 9.2.1 20200130")
C++ linker for the host machine: c++ GNU ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64

|Executing subproject test_cmake method cmake 
|
|Found CMake: /usr/bin/cmake (3.16.4)
|
||Configuring the build directory with CMake version 3.16.4
||Running: -DCMAKE_CXX_COMPILER=c++ -G Ninja -DCMAKE_INSTALL_PREFIX=/usr/local
||  - build directory:          /home/simo/meson_cmake_cycle_issue/build/subprojects/test_cmake/__CMake_build
||  - source directory:         /home/simo/meson_cmake_cycle_issue/subprojects/test_cmake
||  - trace args:               --trace --trace-expand --no-warn-unused-cli --trace-redirect=cmake_trace.txt
||  - preload file:             /usr/lib/python3.8/site-packages/mesonbuild/cmake/data/preload.cmake
||  - disabled policy warnings: [CMP0025, CMP0047, CMP0056, CMP0060, CMP0065, CMP0066, CMP0067, CMP0082, CMP0089]
||
||Running with trace output on.
||Running with expanded trace output on.
||Not searching for unused variables given on the command line.
||Trace will be written to cmake_trace.txt
||CMake Warning (dev) in CMakeLists.txt:
||  No project() command is present.  The top-level CMakeLists.txt file must
||  contain a literal, direct call to the project() command.  Add a line of
||  code such as
||
||    project(ProjectName)
||
||  near the top of the file, but after cmake_minimum_required().
||
||  CMake is pretending there is a "project(Project)" command on the first
||  line.
||This warning is for project developers.  Use -Wno-dev to suppress it.
||
||-- The C compiler identification is GNU 9.2.1
||-- The CXX compiler identification is GNU 9.2.1
||-- Check for working C compiler: /usr/bin/cc
||-- Check for working C compiler: /usr/bin/cc -- works
||-- Detecting C compiler ABI info
||-- Detecting C compiler ABI info - done
||CMake Warning (dev) at /usr/share/cmake-3.16/Modules/CMakeDetermineCompilerABI.cmake:95 (cmake_parse_implicit_include_info):
||  Syntax error in cmake code when parsing string
||
||    ^\.\.[\/]\.\.[\/](.*)$
||
||  Invalid escape sequence \.
||
||  Policy CMP0010 is not set: Bad variable reference syntax is an error.  Run
||  "cmake --help-policy CMP0010" for policy details.  Use the cmake_policy
||  command to set the policy and suppress this warning.
||Call Stack (most recent call first):
||  /usr/share/cmake-3.16/Modules/CMakeTestCCompiler.cmake:74 (CMAKE_DETERMINE_COMPILER_ABI)
||This warning is for project developers.  Use -Wno-dev to suppress it.
||
||-- Detecting C compile features
||-- Detecting C compile features - done
||-- Check for working CXX compiler: /usr/bin/c++
||-- Check for working CXX compiler: /usr/bin/c++ -- works
||-- Detecting CXX compiler ABI info
||-- Detecting CXX compiler ABI info - done
||CMake Warning (dev) at /usr/share/cmake-3.16/Modules/CMakeDetermineCompilerABI.cmake:95 (cmake_parse_implicit_include_info):
||  Syntax error in cmake code when parsing string
||
||    ^\.\.[\/]\.\.[\/](.*)$
||
||  Invalid escape sequence \.
||
||  Policy CMP0010 is not set: Bad variable reference syntax is an error.  Run
||  "cmake --help-policy CMP0010" for policy details.  Use the cmake_policy
||  command to set the policy and suppress this warning.
||Call Stack (most recent call first):
||  /usr/share/cmake-3.16/Modules/CMakeTestCXXCompiler.cmake:67 (CMAKE_DETERMINE_COMPILER_ABI)
||This warning is for project developers.  Use -Wno-dev to suppress it.
||
||-- Detecting CXX compile features
||-- Detecting CXX compile features - done
||CMake Error in CMakeLists.txt:
||   could not find file:
||    /usr/lib/python3.8/site-packages/mesonbuild/cmake/data/preload.cmake
||
||
||CMake Warning (dev) in CMakeLists.txt:
||  No cmake_minimum_required command is present.  A line of code such as
||
||    cmake_minimum_required(VERSION 3.16)
||
||  should be added at the top of the file.  The version specified may be lower
||  if you wish to support older CMake versions for this project.  For more
||  information run "cmake --help-policy CMP0000".
||This warning is for project developers.  Use -Wno-dev to suppress it.
||
||-- Configuring incomplete, errors occurred!
||See also "/home/simo/meson_cmake_cycle_issue/build/subprojects/test_cmake/__CMake_build/CMakeFiles/CMakeOutput.log".
|
|CMake configuration: FAILED

meson.build:3:0: ERROR: Failed to configure the CMake subproject
```

Attaching the `CMakeOutput.log`. 
[CMakeOutput.log](https://github.com/mesonbuild/meson/files/4227720/CMakeOutput.log)

**Comment by mensinda** [comment]
Have you tried building with a new build directory? Also, does this CMake error also occur with the previous commit / on master? Specifically, the `No project() command is present.` part looks really suspect, (unless you don't have a project call in your test project, which is now required for the code injection via [`CMAKE_PROJECT_INCLUDE`](https://cmake.org/cmake/help/latest/variable/CMAKE_PROJECT_INCLUDE.html) to work).

**Comment by conte91** [comment]
> Have you tried building with a new build directory? 

Yes, removing the build directory before build makes 31eb41ec work as before (i.e. success in the test project, cycle detected error in the real one), but fc5caa7b fails with the error above.

I think the fatal part here is
```
||CMake Error at CMakeLists.txt:8 (project):
||  project could not find file:
||
||    /usr/lib/python3.8/site-packages/mesonbuild/cmake/data/preload.cmake
```
It looks like `preload.cmake` is not installed by the setup script! Adding it in https://github.com/conte91/meson/commit/b4219d0fe24969cad16f0f8209ad68da5a6b66ff fixes the issue in both cases for me.

> No project() command is present.` part looks really suspect, (unless you don't have a project call in your test project, which is now required for the code injection via [`CMAKE_PROJECT_INCLUDE`](https://cmake.org/cmake/help/latest/variable/CMAKE_PROJECT_INCLUDE.html) to work).

I do have a project call in the real project, so that doesn't seem to make a difference unfortunately!

**Comment by mensinda** [comment]
Thanks, fixed the missing entry in the `setup.py`.

> Adding it in conte91@b4219d0 fixes the issue in both cases for me.

Does that mean your issue your project works now with 113ec96, or are there still issues left?

**Comment by conte91** [comment]
> Does that mean your issue your project works now with [113ec96](https://github.com/mesonbuild/meson/commit/113ec96626fe7cd2edc0bc4815ae2fc21cfb0546), or are there still issues left?

Works like a charm!
