### ISSUE TITLE
CMake subproject fails with "Tried to form an absolute path to a source dir"

### ISSUE THREAD

**Issue by shdnx** [mesonbuild/meson#6640]
**Describe the bug**
I have a simple Meson project that uses a CMake subproject. I pass an additional CMake option in using `cmake_options`, specifying `BOOST_ROOT`.

When configuring, I see the subproject getting configured with CMake correctly, but as soon as the configuration succeeds, Meson quits with an error:

> subprojects/mySubproject/meson.build:0:0: ERROR: Tried to form an absolute path to a source dir. You should not do that but use relative paths instead.

(The error message is followed by an explanation on how to use `include_directories`.)
Note that the error message points to a nonexistent file `subprojects/mySubproject/meson.build` in line 0.

**To Reproduce**

Here's my `meson.build`:

```
project(
    'myApp',
    'cpp',
    version : '0.0.1'
)

cmake = import('cmake')

boost_root = meson.source_root() + '/myBoost'

message('Configuring mySubproject with BOOST_ROOT = ' + boost_root)
proj = cmake.subproject('mySubproject', cmake_options : [ '-DBOOST_ROOT=' + boost_root ])
```

**Expected behavior**
It should either provide better diagnostics, or not fail.

**system parameters**
* Native build
* OS: Oracle Linux 7.7 (based on CentOS)
* Python: 3.7.4
* Meson version: 0.53.1
* Ninja version: 1.9.0

**Comment by mensinda** [comment]
This use case is not supposed to work since subprojects are not allowed to access anything from the root project or other subprojects. The only thing I can "fix" here, is to ignore all paths that are inside the project root but not inside the subproject. However, this will likely cause your build to fail.

The propper fix would be to distribute yout boost root seperately, outside your main project.

**Comment by shdnx** [comment]
@mensinda Thank you for picking this up so quickly!

1) To confirm, if I were to move Boost outside of the project hierarchy, then this should work? If I understand this right, I believe the biggest thing Meson could be improved on is better diagnostics, to explain the failure.
2) In general, what is the supported way for providing dependencies of dependencies (i.e. dependencies of subprojects)?

I also just wanted to take a moment to thank you for your awesome work on Meson! It's an amazing project, and a true joy to use after all the years with CMake. :)

**Comment by mensinda** [comment]
Yes, it should work once you move boost outside your project. Also, the diagnostics should be a little better with #6641 :)

You can generally have subprojects that depend on subprojects. The trick here is to put all subprojects into the `subprojects` folder of your root project. So if you have a root project `root` that depends on `sA` and `sB` and `sA` also depends on `sB`, then you put both `sA` and `sB` into the `subprojects` folder of `root`. This way, you only have one version of `sB`, which is used for both `root` and `sA`.

However, this only works for meson based subprojects. CMake subprojects can't depend on other subprojects. Implementing such a feature would require extensive changes to CMake itself.
