### ISSUE TITLE
unknown cpu family 'mips64el'

### ISSUE THREAD

**Issue by linkslice** [mesonbuild/meson#6655]
Sent here by a configure message on OpenBSD running on a loongson.

$ uname -a
OpenBSD hackbookpro.attlocal.net 6.6 GENERIC#18 loongson
$ machine -a
mips64el

**Comment by dcbaker** [comment]
I've opened an MR to fix this, but I don't have any mips systems (or access to any running OpenBSD), could you test this for me and let me know if it works correctly?

**Comment by linkslice** [comment]
seems ok to me! Thanks!
