### ISSUE TITLE
find_program version regex can match program name instead of version number

### ISSUE THREAD

**Issue by gdmoore** [mesonbuild/meson#6659]
Meson 0.53.1, Windows.

```
Program sphinx-build found: YES (C:\Program Files\Python38\Scripts\sphinx-build.EXE)
Running command: C:\Program Files\Python38\Scripts\sphinx-build.EXE --version
--- stdout ---
sphinx-build.EXE 2.4.1

--- stderr ---


Program sphinx-build found: NO found '.' but need: '>=2.4.0'

docs\meson.build:2:0: ERROR: Invalid version of program, need 'sphinx-build' ['>=2.4.0'] found '.'.
```

It looks like the version parsing sees "sphinx-build.EXE" and interprets that '.' as a version marker and ends up with nothing but the dot, instead of parsing the '2.4.1'.

This would be a problem with anything that was invoked with the trailing extension which prints its' invoked name instead of a fixed string.

**Comment by nirbheek** [comment]
I think this was fixed with https://github.com/mesonbuild/meson/pull/6626 already. I will include it in 0.53.2.

**Comment by gdmoore** [comment]
Agreed it does look like this is addressed there. Thanks.
