### ISSUE TITLE
[trivial] CLI help message

### ISSUE THREAD

**Issue by denizzzka** [mesonbuild/meson#6667]
`meson --help` returns:
```
usage: meson [-h] {setup,configure,dist,install,introspect,init,test,wrap,subprojects,help,rewrite} ...
```
But if I call `meson -h setup` it reverts same screen again.

`meson setup -h` works fine

* what `meson --version`

0.53.1

**Comment by gerion0** [comment]
This is a standard behavior in most CLI programs. Optional arguments always refer to the next subcommand that comes before this argument.

For example see the different output of:
```
git --version commit
git commit --version
```
(Nevertheless, git seems to break this rule for the --help argument. However, git also handles `-h` and `--help` differently and opens the man page for you.)

*argparse* (the standard Python cli argument parsing library) also behave this way, but I'm not sure, if meson use the subcommands functionality of argparse.

**Comment by xclaesse** [comment]
> but I'm not sure, if meson use the subcommands functionality of argparse.
Yes it does, with a few hacks.

Note that you also have `meson help setup` that does what you want.

**Comment by xclaesse** [comment]
TBH, I don't think this is a bug.

**Comment by nirbheek** [comment]
This behavior is definitely not a bug, this is exactly how every other tool with sub-commands behaves, and we _do_ use argparse's subcommand feature.

We could definitely improve the help message, though. I can see how it can be confusing to read the current output.

**Comment by michaelbadcrumble** [comment]
Hey @denizzzka just read the issue and definitely not a bug. To get help from any of Meson builds commands you must end with ether `-h` or `--help`.

Example of getting help information from `meson setup`:

```consol
meson setup --help
```

**Comment by denizzzka** [comment]
@michaelbadcrumble It's just a sort of typo, yes. But this is very confusing for a beginner when he/she just starting to use Meson.

**Comment by michaelbadcrumble** [comment]
Will that is a good argument. I will see what I can do about adding a page
in the Meson build tips  notebook project.

**Comment by michaelbadcrumble** [comment]
Ok @denizzzka I had some time to write the Meson build tip notebook project. Would this help?

https://github.com/michaelbadcrumble/mesonbuild_tips/blob/master/notebook/011-readme.md

**Comment by denizzzka** [comment]
>  Would this help?

help message can't just be fixed? :-)

**Comment by michaelbadcrumble** [comment]
At the moment it kinda is. Best I can do for that is writing something with helpful information explaining what the subject is and how it works. 🙂

**Comment by denizzzka** [comment]
> At the moment it kinda is. Best I can do for that is writing something with helpful information explaining what the subject is and how it works. slightly_smiling_face

So much time has passed, but I still don't understand why it is impossible to fix message by change it to:
```
usage: meson {setup,configure,dist,install,introspect,init,test,wrap,subprojects,help,rewrite} [-h]
```
?

**Comment by eli-schwartz** [comment]
Because the message is implemented by Python's argparse module, which AFAIK does not provide an option for this.

**Comment by xclaesse** [comment]
Technically we could, we already do some preprocessing before passing argv to argparse: https://github.com/mesonbuild/meson/blob/master/mesonbuild/mesonmain.py#L212. @denizzzka if you think it's important, feel free to open a PR ;-)

**Comment by denizzzka** [comment]
At one time, I was greatly embarrassed by described issue for a ~hour

> Because the message is implemented by Python's argparse module, which AFAIK does not provide an option for this.

So it is need to at least write this quote at first cli output lines and surrender in disgrace :-)

>  feel free to open a PR ;-)

I don't know Python. Maybe someone else can do it.

**Comment by xclaesse** [comment]
> What does preprocessing of argv have to do with changing the order that argparse prints out the usage message?

You can rewrite `['-h', 'setup']` to `['setup', '-h']` before handling argv to argparse.

**Comment by eli-schwartz** [comment]
As mentioned above,

> This behavior is definitely not a bug, this is exactly how every other tool with sub-commands behaves

Do we really want to do fiddly argument rewriting because of something that isn't a bug? How do you propose to handle invalid commands which should not have the -h moved after them, because we *should* show the main help message listing out the different subcommands?

**Comment by xclaesse** [comment]
Just saying it's technically possible, not that we should do it :P In any case, @denizzzka is the only one wanting the change and cannot write a PR... so it won't happen.

**Comment by eli-schwartz** [comment]
Weeeell... okay then. :p

**Comment by denizzzka** [comment]
Is there still no way to fix this? Meson is more popular now and this may become important

I forgot about this problem and again got into a situation where help didn't work until I swapped the arguments (not as written in the help message)
