### ISSUE TITLE
pass variable from child meson.build to root meson.build

### ISSUE THREAD

**Issue by agauniyal** [mesonbuild/meson#667]
I've a directory structure like this - 

```
meson.build
include/
  - a.hpp
  - b.hpp ... so on
src/
  - a.cpp
  - b.cpp ... so on
  - meson.build
test/
  - test1.cpp // needs access to both include/*.hpp src/*.cpp
  - meson.build
```

Now I can easily compile `src/` by setting `include_directories('include')` and then using it in `src/meson.build` executables. But now my tests require access to `src/` cpp files during link. I can access the include directory fine, but to access `src/*.cpp` files, I need to pass that array to root meson.build somehow, which will be taken by `test/` meson.build. Is this even the right way to do this?

**Comment by nirbheek** [comment]
Ideally, you build a library from your sources that your tests then link to.

See:

https://github.com/centricular/gstreamer/blob/meson-1.8/libs/gst/base/meson.build#L76
https://github.com/centricular/gstreamer/blob/meson-1.8/tests/check/meson.build#L126
https://github.com/centricular/gstreamer/blob/meson-1.8/meson.build#L254

**Comment by agauniyal** [comment]
@nirbheek say I have a.hpp and a.cpp files, compiled along with main.cpp which uses functions defined in them. This should be different than creating a static library out of a.hpp + a.cpp and then linking it to main.cpp executable, right? I've limited knowledge in regards with static/shared libraries so I'm slightly biased towards simply creating object files and linking them together, atleast for now.

**Comment by nirbheek** [comment]
There's no difference between the two if you're using a static library. A static library is just an `ar` archive of object files, so the linker will extract the objects, then find the symbols you need and link those in. The end result is identical.

There might be a difference if you plan to use LTO, but that will also work the same way with a static library if you use `gcc-ar` instead of `ar`.

**Comment by agauniyal** [comment]
ah okay. I'll research more into this topic and proceed forward with your approach if there's no other way to do it through meson itself 😄

**Comment by jpakkane** [comment]
There is if you really want to. In subdir 1 do this:

    some_files = files('file1.cpp', 'file2.cpp')

And then in a different subdir do this:

    executable('foo', 'foo.c', some_files, <other args>)
