### ISSUE TITLE
[Feature request] Add `meson compile` command

### ISSUE THREAD

**Issue by TheQwertiest** [mesonbuild/meson#6670]
Proposal:
Backend-agnostic build command `meson compile` - counterpart of `cmake --build`.

Reasoning:
- Simplifies `meson` usage and integration: the same `meson` commands could be invoked for all backends.
- Reduces the amount of knowledge required to use `meson` out-of-the-box (i.e. with default `ninja` backend). Since user won't have to know anything about ninja (apart from the fact that it's needed).

Proposed interface (based on `cmake --build):
```
usage: meson compile [-h] [-C WD] [--clean] [--backend-args ARGS] [args [args ...]]

positional arguments:
  args                            optional list of targets to build

optional arguments:
-h, --help                      show this help message and exit
-C WD                          directory to cd into before running
--clean                          invokes clean command of the native tool.
--backend-args ARGS    arguments to pass to the native tool.
```

**Comment by TheQwertiest** [comment]
Note: most of the implementation code might be directly lifted from the test runner: https://github.com/mesonbuild/meson/blob/d8faf9b7062e2278adddb3b107ea58784fe544d4/run_tests.py#L211

**Comment by xclaesse** [comment]
Makes sense to me, we added 'meson install' recently too. Are you working on a patch?

**Comment by TheQwertiest** [comment]
Replaced `--target` with positional `[args]` for consistency with `meson test` and `meson test`.

**Comment by TheQwertiest** [comment]
>  Are you working on a patch?

Not yet, since my free time is currently pretty lacking. I will, however, take this on if nobody starts working on it in next month or so.

**Comment by marc-h38** [comment]
As the person developing the meson.build file itself, I would also like to have a single command `meson setup_and_compile --wipe_ignore_missing`. Would save writing wrapper scripts on top of meson (on top of ninja). See https://github.com/mesonbuild/meson/issues/6434#issuecomment-572290358

And a poney.

**Comment by Salamandar** [comment]
`meson build` would make more sense IMHO. Meson does not always **compile** (if you have a project with only installed files, and a python-only project when it will be supported, i.e).

**Comment by xclaesse** [comment]
> `meson build` would make more sense IMHO. Meson does not always **compile** (if you have a project with only installed files, and a python-only project when it will be supported, i.e).

The reason we picked 'compile' is because 'meson build' is too common to use 'build' as build directory.

**Comment by TheQwertiest** [comment]
^ What he said =)
Quote from IRC discussion:
>**jpakkane:** The "correct" solution would be to add a new command "meson compile" that does all the magic and call that. (It can't be called "meson build" because that is in common use for creating a build dir.)

**Comment by marc-h38** [comment]
The documentation should be adjusted accordingly https://mesonbuild.com/Overview.html#terminology

> Meson follows the overall structure of other popular build systems, such as CMake and GNU Autotools. This means that the build is divided into two discrete steps: configure step and build step.

**Comment by xclaesse** [comment]
> > (... because that is in common use for creating a build dir.)
> 
> Curious where.

GStreamer CI for instance: https://gitlab.freedesktop.org/gstreamer/gst-ci/-/blob/master/gitlab/ci_template.yml#L120
