### ISSUE TITLE
Feature request: Add CMake backend or tools to export CMakeLists

### ISSUE THREAD

**Issue by Geequlim** [mesonbuild/meson#668]
As a lot of IDEs natively support CMake to organize projects (e.g CLion, QtCreator, KDevelop ...) so I believe that would be cool to make meson support these tools.

I have read the FAQ about [`Why is there not a Make backend`?](https://github.com/mesonbuild/meson/wiki/FAQ#why-is-there-not-a-make-backend)` and I don't think they are the same question even CMake may use Make to build codes.

Which build system to use with CMake is the choice of developers(Or decided by the IDEs, CLion use Make and QtCreator use ninja).

I would be glad to join to develop the backend or tools for meson if you agree with me :)

**Comment by jpakkane** [comment]
A CMake backend was thought about but never implemented. One of the design goals of Meson was to take all the things that are wrong or broken in CMake and build a system from the ground up that does not have those issues

These include:

- Meson's project format is richer so converting that to CMake will be tricky (especially when generating sources during build)
- making pch work reliably in CMake is plain impossible
- CMake will reinitialise itself when project files are changed but it should instead reinvoke Meson to regenerate cmakefiles
- CMake's syntax is just as unpleasant as Make's, just in a different way

**Comment by nirbheek** [comment]
I think such a backend would likely not work for anything but simple projects, and even if it did, it would not be maintainable. I'm going to close this for now, but if there's a lot of demand for this for some reason, we can revisit it.

You are welcome to work on other parts of Meson in the meantime! We'd love the help. :)

**Comment by amitdo** [comment]
I don't use CLion but I've found these links:

https://www.jetbrains.com/help/clion/compilation-database.html

https://www.jetbrains.com/help/clion/custom-build-targets.html
