### ISSUE TITLE
Add "run" command to "meson"

### ISSUE THREAD

**Issue by michaelbadcrumble** [mesonbuild/meson#6683]
As a Meson build user, I would love to have `run` for Meson. This would kinda be like `cargo run` were first you build, then test, and finally run executable all in one command.

Example command:
```console
meson builddir
meson run builddir
```

It can be the same as the following.
```console
meson builddir
ninja -C builddir
meson test -C builddir
./prog
```

**Comment by dcbaker** [comment]
I don't think we're going to add a build and test command, you could already just call `meson test` to do the build and test, there is https://github.com/mesonbuild/meson/issues/6670, which would add a `meson compile` command.

I'm not sure that this really makes sense for meson, as a lot of meson users aren't building an executable, they're building libraries.

**Comment by michaelbadcrumble** [comment]
Will ok.  I will check out the `meson compile` proposal and see if I need to add that to Meson-UI.

**Comment by xclaesse** [comment]
I agree with @dcbaker, with `meson compile` all you need is defining your own bash alias if you want try to exec all steps in one go.

**Comment by joxoby** [comment]
"Adding an alias" is never the answer. Having a `run` verb would make a lot of sense for the users that are building executables or just want to run `run_targets`. You don't want to run a target by typing `meson compile`, which is absolutely ridiculous. Bazel, for example, implements the `run` command.

**Comment by eli-schwartz** [comment]
So what would the difference be, between a "compile verb" that triggers a build rule for a run_target, and a "run verb" that triggers a build rule for a run_target?

TBH I could live with `meson compile` being ridiculous, because I think it's ridiculous anyway and I don't like `meson compile` at all. All it does is run `ninja`. Ninja is a much better verb. What about `make` as a verb? ;)

**Comment by xclaesse** [comment]
We would have to add an API to define which executable to run by default, and run it within `meson devenv`. This is actually something I wanted to investigate if we can hook in vscode plugin for the "play" button most IDEs have.

**Comment by eli-schwartz** [comment]
Anyway the original ticket was asking for a command that built an executable and then ran the executable. Not for a command that runs a run_target (which may be anything of course, and the majority of the time isn't even running a program that was built by meson).

**Comment by xclaesse** [comment]
I see in cargo they added `default-run = "foo"` for this, dunno what others think, but I personally think it would make sense to have something lilke:

```meson
exe = executable()
default_run(exe)
```

Probably would have to make it an error if called more than once per project, and ignore if it's in a subproject.

**Comment by xclaesse** [comment]
Maybe `meson.devenv_default_run()` to emphasis that it's related to `meson.add_devenv()`.

**Comment by Managor** [comment]
I personally found an ok solution. Make the executable into a test
First create a a variable out of executable() and put it into a test
```
exe = executable('name', 'name.c')
test('running', exe, timeout: 0)
```
and then you  just run `meson test` and meson will compile things as needed.
