### ISSUE TITLE
Wish: please add include_files()

### ISSUE THREAD

**Issue by denizzzka** [mesonbuild/meson#6695]
It is possible to add `include_files()` that will work as `include_directories()` but with individual header files?

`include_files` keyword argument may be renamed/aliased to "include"

**Comment by QuLogic** [comment]
What would that do? Compilers can only set search paths to directories.

If you just need an object that will give the correct relative path like `include_directories`, then there `files`.

**Comment by denizzzka** [comment]
> What would that do? Compilers can only set search paths to directories.

To force adding multiple headers at single object compilation "disguised" as src files.

My case briefly:
I want to compile file what includes directory what also contains wrong headers, which I want to replace by another files.

**Comment by QuLogic** [comment]
I still don't understand what you mean. The compiler does not work that way, you can only set include directory search paths.

**Comment by denizzzka** [comment]
> The compiler does not work that way

Something like:
```
gcc dir/file.c dir/file.h -o a.out
```
will not work for C?

If it is true this issue wrong and can be closed.

**Comment by gregsskyles** [comment]
The docs at [https://gcc.gnu.org/onlinedocs/gcc-9.1.0/gcc/Overall-Options.html#Overall-Options](url) say:

file.h-
C, C++, Objective-C or Objective-C++ header file to be turned into a precompiled header (default), or C, C++ header file to be turned into an Ada spec (via the -fdump-ada-spec switch).

So you can specify a .h file to gcc, however it appears only for the purpose of generating a PCH or working with Ada.

**Comment by denizzzka** [comment]
> So you can specify a .h file to gcc, however it appears only for the purpose of generating a PCH or working with Ada.

Ok, actually my idea is using this with Dlang. Its compilers accept this behaviour too.
I just decided to give an example of C as being better known to everyone. Sorry.

**Comment by gregsskyles** [comment]
Don't be sorry, this has been interesting. I had no idea you could specify a .h file to gcc; I assumed as @QuLogic said, that it only took directories in which .h files can be found. So I've learned something.
I don't know enough about D to be able to comment on how you could use what you are proposing with that, however.

**Comment by denizzzka** [comment]
> I don't know enough about D to be able to comment on how you could use what you are proposing with that, however.

If I include directory of headers (by the way, what usually it is same as source files in D) I also unwittingly include some code what I am want to replace by my own implementations. And "original" code will be used by these included files if I pass whole include dir.

If I be able to use only needed files and pick another files (with same module names inside!) from another source I will be able to change functionality of original sources.

**Comment by QuLogic** [comment]
OK, since this is about D, can someone add the "D language" label?

**Comment by denizzzka** [comment]
Not sure about what this issue is D-only

**Comment by andreaskem** [comment]
GCC or, more specifically, its preprocessor `cpp`, [accepts](https://gcc.gnu.org/onlinedocs/gcc/Preprocessor-Options.html#Preprocessor-Options) a `-include` flag.
>-include file
>
>    Process file as if #include "file" appeared as the first line of the primary source file. However, the first directory searched for file is the preprocessor’s working directory instead of the directory containing the main source file. If not found there, it is searched for in the remainder of the #include "…" search chain as normal.
>
>    If multiple -include options are given, the files are included in the order they appear on the command line.

**Comment by denizzzka** [comment]
Addition: it seems it is impossible to use generated D files as headers without this functionality.

**Comment by denizzzka** [comment]
> Addition: it seems it is impossible to use generated D files as headers without this functionality.

...because it is impossible to extract directory part of generated file path and pass it trough usual -I option into compiler

**Comment by eli-schwartz** [comment]
Any generated file path can have `meson.current_build_dir()` in the same meson.build which generated the file.

Or just `include_directories('.')` which adds both the current source dir and the current build dir as include directories.

**Comment by eli-schwartz** [comment]
Which languages do you want this for, and what compiler options should it be translated to? It's not clear to me what the objective is here.

**Comment by denizzzka** [comment]
> Which languages do you want this for,

Dlang

> and what compiler options should it be translated to?

`-i`

>It's not clear to me what the objective is here.

For example, I want to use generated D module. Generator output is a one file.
Generator:

```meson
project('d++ preprocessor')

dub = find_program('dub', native: true)

dpp_preprocessor = generator(
    dub,
    arguments : [
        'run', 'dpp', '--',
        '--preprocess-only',
        '--source-output-path=@BUILD_DIR@',
        '@EXTRA_ARGS@',
        '@INPUT@',
    ],
    output: '@BASENAME@.d',
)
```

Now I call it:
```meson
freertos_binding = dpp.process(
    files(
        'freertos_dpp_bindings/freertos.dpp',
    ),
    extra_args: [
        '--include-path=' + subprojects_dir / 'freertos' / 'include',
        '--include-path=' + subprojects_dir / 'freertos' / 'portable/GCC/ARM_CM3',
        '--include-path=' + root_dir, #for FreeRTOSConfig.h
    ]
)
```

Ok, `freertos_binding` now contains result of generation. But I can't pass it to other Meson directives as header because these directives accept only directories or `include_directories` objects.

**Comment by eli-schwartz** [comment]
> and what compiler options should it be translated to

**Comment by denizzzka** [comment]
Probably, I do not understand what you mean (I'm not a native speaker)

**Comment by eli-schwartz** [comment]
Please show an example meson.build that uses `include_file(freertos_binding), and explain which command line argument to the Dlang compiler will be written to build.ninja, e.g.

```
gdc -someflag freertos.d
```

**Comment by denizzzka** [comment]
Something like:

```meson
some_useful_dep = declare_dependency(
    sources: [
        'source/app.d',
        'source/drivers/max7219.d',
    ],
    include_files(
         libopencm3_binding,
         freertos_binding,
    ),
    include_directories: [
        'source',
    ],
)
```

```
gdc -I./source/ mesongendir/libopencm3_binding.d mesongendir/freertos_binding.d source/app.d source/drivers/max7219.d
```

**Comment by eli-schwartz** [comment]
So that is just adding those files as sources.

I don't understand how include_files() helps here.

```
some_useful_dep = declare_dependency(
    sources: [
        'source/app.d',
        'source/drivers/max7219.d',
         libopencm3_binding,
         freertos_binding,
    ],
    include_directories: [
        'source',
    ],
)
```

**Comment by denizzzka** [comment]
> I don't understand how include_files() helps here.

You can't use `some_useful_dep` as dependency for some another dependency - freertos_binding will not be accessible as header for it.

**Comment by eli-schwartz** [comment]
But it's not acting like a header, it is being passed on the command line to gdc as the file itself just like a source file.

Therefore as far as meson is concerned, it is in fact a source file and you may list it as one without adding a new function to the meson language.

**Comment by denizzzka** [comment]
> But it's not acting like a header,

Wrong - it will act as header, with templates and symbols declaration, same as C++ header

> it is being passed on the command line to gdc as the file itself just like a source file.

Technically D language isn't makes difference between headers and sources (but in D we have `.di` extension for headers, just for distinguish)

But D headers still important for libraries (and for using all other Meson dependencies from another dependencies)

**Comment by eli-schwartz** [comment]
That has nothing to do with meson.

I reiterate: from meson's perspective, it is not a "header", it is a "source input file which the compiler internally treats as having declarations without function code".

The distinction is that from meson's perspective, it is passed on the command line as... an input.

If it is passed on the command line as an input, then you list it in the meson sources in order to make meson pass it on the command line as an input.

You do not need a special function to pass it on the command line as a source input and do nothing different from any other "source input".

This is exactly the reason why I asked above:
> explain which command line argument to the Dlang compiler will be written to build.ninja

Because I wanted to know why you need include_files() and listing it as a source is not enough.

Since, based on all the explanation you have provided, I am 100% convinced that the existing meson language facilities already cover your use case, I am going to close this ticket. However, if you can describe something that the meson language cannot currently do, which your proposal adds the ability to do, feel free to comment further and the ticket can be re-opened.

**Comment by denizzzka** [comment]
> That has nothing to do with meson.
> I reiterate: from meson's perspective, it is not a "header", it is a "source input file which the compiler internally treats as having declarations without function code".

I just want to say here what I have a different opinion: I disagree with this. This is wrong approach for D and maybe for another languages except C/C++

C and C++ is not a "measure of all things". (Authors of the specific C++ compilers, as shown above by other contributors, seems have same opinion and have added appropriate options into compilers.)
