### ISSUE TITLE
Adding Language Support?

### ISSUE THREAD

**Issue by remexre** [mesonbuild/meson#672]
I'm working on a project using an obscure language, which isn't supported by meson. Is there a way to add support from within `meson.build`, or would it require changes to meson's source?

**Comment by jpakkane** [comment]
That depends on how the program is compiled and how integrated you want it to be. All languages that compile in a c-like manner (sources -> object files and then link) should be doable with a combination of a `generator` and `custom_target`. For languages that compile into another language (such as C) you generate the sources with a generator and then pass them to an `executable` target or similar.

If you want deep integration and Meson *understanding* the system then you need to patch the source.

**Comment by remexre** [comment]
The language's compile process is something like:

```
Sources
  |
  +------------+
  v            |
Objects        |
  |            |
  |            |
  v            v
Executables   Other Stuff
```

At this stage, I don't really care about the "other stuff", but would it be possible to get those as well with `generator` and `custom_target`? Also, where are these functions documented? Is there something like CMake's [giant list of functions](https://cmake.org/cmake/help/v3.5/manual/cmake-commands.7.html), or  is the Wiki the only documentation?

**Comment by jpakkane** [comment]
[Reference manual](https://github.com/mesonbuild/meson/wiki/Reference%20manual). Unit tests are also a good source of information.

**Comment by remexre** [comment]
Okay, thanks!

**Comment by nirbheek** [comment]
I will just add that as long as the language is publicly available, we'd be happy to merge support for it even if it is an obscure language. :)

**Comment by remexre** [comment]
It's not (yet?), but if I can get the codebase sane and efficient (honestly, the latter more than the former), then it might be eventually.
