### ISSUE TITLE
Wish: add ability to use local patch files

### ISSUE THREAD

**Issue by denizzzka** [mesonbuild/meson#6732]
It is impossible to use cmake projects if they placed not in root directory of subproject.

For example look into LLVM project repository:
https://github.com/llvm/llvm-project/
Each of its subdir is cmake projects but it is impossible to use them from Meson if llvm-project will be wrapped as subproject.

**Comment by mensinda** [comment]
You can work around this limitation by creating a dummy `CMakeLists.txt` that calls `add_subdirectory` and patch them with the [wrap patch mechanism](https://mesonbuild.com/Wrap-dependency-system-manual.html#wrapfile-with-meson-build-patch).

**Comment by denizzzka** [comment]
Uhh. Yes... But I prefer to avoid it by all means - wrap patch mechanism is hard to maintain: it assumes strict URL to archieve with original source and set up my own storage for patch URL. Each change will cause also changing hashes of source and/or patch files.

In general patching is a good thing, but since we have a cmake module and cmake system itself allows such kind of subdirectories it will be better to have native support for this.

**Comment by xclaesse** [comment]
I more generally think we should allow subprojects anywhere in the source tree, as long as that's code checked-in the main git tree and not something downloaded by a .wrap. But that idea got strongly rejected by @jpakkane so I got discouraged to work on it. I still believe that should be done.

**Comment by jpakkane** [comment]
Being able to have subprojects anywhere is one of those things that is easy and "fun" in the immediate short term but which becomes a complete maintenance nightmare in the long term. The main advantage of the current approach is that no matter which Meson project you use, you _know_ where the external deps are. They are always in the same place. You can rely on that. It reduces the time you need to understand any given code base noticeably.

In practice what happens is that every project of non-trivial size that has external dependencies comes up with their own rules of where to put things. These rules are pretty much arbitrary, you just have to pick one and stick with it. Since this will pretty much always happen, Meson has made the choice already and sticks with it. This is the only way to get consistency among projects, which is the true end goal.

**Comment by xclaesse** [comment]
@jpakkane external dependencies gets pulled by wrap files, that always must go to subprojects/ I totally agree. But here we are not talking about that. There are cases where a single project is split into independant parts, which is litterally sub-projects. Just like GStreamer has gst-plugins-good, gst-plugins-bad, etc. There are parts of the same project, not external dependencies.

**Comment by xclaesse** [comment]
At least that's what I understand from the LLVM project, it is split into sub-projects that are not external.

**Comment by mensinda** [comment]
> Uhh. Yes... But I prefer to avoid it by all means - wrap patch mechanism is hard to maintain: it assumes strict URL to archieve with original source and set up my own storage for patch URL. Each change will cause also changing hashes of source and/or patch files.

In that case, would adding an (official, non-hacky) way to specify local patch archives work for you?

**Comment by xclaesse** [comment]
@denizzzka one work around would be to have a patch in your llvm.wrap that would only add a meson.build file at the top source dir. That way llvm becomes a *meson* subproject. In that meson.build you do:
```meson
foreach sub : ['llvm', ...]
  # See https://gitlab.freedesktop.org/gstreamer/gst-build/-/blob/master/meson.build#L78
  run_command(<python script to create symlink to subprojects/>)
  cmake.subproject('llvm')
endforeach
```

**Comment by mensinda** [comment]
@xclaesse This does not solve the main problem of having to patch the SP. And if you are patching the SP, it is *far* easier to add a dummy `CMakeLists.txt` with `add_subdirectory`.

**Comment by xclaesse** [comment]
@mensinda ah, misunderstood then, I though that it would have to change each CMakeLists.txt in subdirs which is not acceptable because wrap patch are replacing files, so you would have to regen the patch for each upstream change.

**Comment by denizzzka** [comment]
@mensinda 
> In that case, would adding an (official, non-hacky) way to specify local patch archives work for you?

Yes

**Comment by denizzzka** [comment]
@mensinda According to this, do we need to replace this issue title and badges?

**Comment by mensinda** [comment]
@denizzzka Yes. Maybe something like "add ability to use local patch files".
