### ISSUE TITLE
CMake install target fails for capnproto-c++-0.7 cmake subproject

### ISSUE THREAD

**Issue by germandiagogomez** [mesonbuild/meson#6737]
**Describe the bug**

When you run install and use capnproto in subprojects/, installation will fail.

**To Reproduce**

Use the attachment (attachment tested under windows) and:

1. meson build
2. ninja -C build install

[CapnpCMakeSubprojectInstallFails.zip](https://github.com/mesonbuild/meson/files/4292873/CapnpCMakeSubprojectInstallFails.zip)

**Expected behavior**

`ninja -C build install` should install correctly the dependencies.

**Actual output**

The installation step fails, I suspect because it is trying to install a dependency that has not been compiled but has been identified as a target when CMake configuration is done. 
It seems that version 0.53.0 lazily compiles only needed dependencies for cmake subprojects? I saw some generated meson.build from an AST and CMake server running to gather this information. I guess this was not what version 0.52.0 of Meson did.

**system parameters**

Tested in Ubuntu 19.10

* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? Native

* what operating system -> Ubuntu 19.10, Windows 10

* what Python version are you using e.g. 3.8.0 -> pre-packaged python3 version (no access at this moment)
* what `meson --version` 0.53.2 (in fact, this bug does not happen in 0.52.0)

* what `ninja --version` if it's a Ninja build -> the one packaged with Ubuntu 19.10

**Comment by mensinda** [comment]
Actually this is a general meson bug/problem. It is the combination of `install: true` and `build_by_default: false` that causes meson install to fail. You can reproduce this with a simple example:

```meson
project('test_project', 'c')

executable('exe1', 'main.c', build_by_default: false, install: true)
```

**Comment by mensinda** [comment]
I think we should rethink how `build_by_default: false, install: true` should work in general, but generating these options together in CMake subprojects doesn't make sense anyway. Thus, this should be fixed with #6741.

**Comment by germandiagogomez** [comment]
Well, I am not sure of the inner workings, but what I am sure is that it broke something that worked before for packaging some software for me :(

**Comment by mensinda** [comment]
Yeah, #6741 should fix the issue regardless.
