### ISSUE TITLE
[Feature request] Add ability to specify target(/s) to `meson compile`

### ISSUE THREAD

**Issue by TheQwertiest** [mesonbuild/meson#6740]
Proposal:
Add ability to specify target(/s) to `meson compile`.

Reasoning:
- Removes most of the cases where direct invocation of `ninja`/`msbuild` is needed.
- (relative) Feature parity with `cmake --build`.

Proposed interface:
```
usage: meson compile [args [args...]]

positional arguments:
  args                            optional list of targets to build
```

Extracted from #6670.

**Comment by TheQwertiest** [comment]
Note: I'm not sure what these `target`s should be in case of each back-end though.
Cmake uses it's internally defined target names (`add_library`/`add_executable`) for this argument (equivalent of `library`/`executable`/etc in meson).
It would be probably not ideal to just use `ninja` targets as argument values, since it would not be backe-end agnostic.

**Comment by Akaricchi** [comment]
All build targets take a `name` parameter, can we use that? Or are collisions possible?

**Comment by TheQwertiest** [comment]
AFAIK target names are unique project-wide (subproject targets are namespaced).

**Comment by dcbaker** [comment]
Those names are guaranteed to be unique.

**Comment by jpakkane** [comment]
Actually no, you can have two `executable('foo', ..)`s in a single project, as long as they are defined in different subdirectories. Similarly you can have `static_library('foo', ...)` and `shared_library('foo', ...)` in the same subdirectory. Subdir + target name + type is unique.

For IDE integration purposes at least specifying the unique id (that you get from introspection data) is the most reliable way.

**Comment by TheQwertiest** [comment]
@jpakkane , introspections unique id is not really human friendly though. What do you think about this solution?
`compile [PATH/]FOO[:TARGET_TYPE]`:
- `compile FOO` - works if there is only a single instance of FOO in introspection.
- `compile FOO[:TARGET_TYPE]` - works if there is only a single instance of FOO in introspection with TARGET_TYPE.
- `compile [PATH/]FOO[:TARGET_TYPE]` - always works
