### ISSUE TITLE
-Dbuildtype silently overwites setting from -Doptimization

### ISSUE THREAD

**Issue by bredelings** [mesonbuild/meson#6742]
**Describe the bug**
When specifying both -Dbuildtype=plain and -Doptimization=3, meson selects buildtype=plain and optimization=0.  No warning is given.  Also, the order of the arguments appears not to matter.

**Expected behavior**
I expect that when specifying -Doptimization=3 _after_ -Dbuildtype=plain, that the optimization level would be 3.

If this behavior is not acceptable, then I expect a message like "You specified both -Doptimization and -Dbuildtype.  Ignoring -Doptimization".

**Comment by bredelings** [comment]
This bug report is wrong.  The order _does_ matter.  I think I was confused, because I did not think of that at first.

**Comment by xclaesse** [comment]
I think the order is kind of undefined, -D options goes into a python dict which only guarantee order with python >=3.6, and we depend on 3.5. So it could be working by chance most of the time.

In any case, I don't like depending on the ordering, I think we should apply buildtype first, then override with debug/optimization. This is a case that always bothered me because it's undocumented what happens AFAIK.

**Comment by bredelings** [comment]
Hmm... how about if you give two different values for the same option, such as -Dbuildtype=plain -Dbuildtype=release?  Currently debian packages automatically supply -Dbuildtype=plain, so the ability to override by specifying -Dbuildtype=release afterwards is important.

**Comment by xclaesse** [comment]
Good point. I think we would need to double check if we always put this key:Val in an OrderedDict.

**Comment by bredelings** [comment]
Along these same lines, the list of options as reported in meson-log.txt does not match the order they are given on the command line.

**Comment by nirbheek** [comment]
I recently found a different bug in the same code: `buildtype` set in project `default_options` was overriding `debug` and `optimization` values passed on the command line. I have a WIP fix for that and the bug described in this issue.

**Comment by nirbheek** [comment]
> This is a case that always bothered me because it's undocumented what happens AFAIK.

I've partially documented it in https://github.com/mesonbuild/meson/pull/6717

**Comment by nirbheek** [comment]
https://github.com/mesonbuild/meson/pull/6753

**Comment by bredelings** [comment]
ANother issue is that I think setting -Doptimization=3 sets -Db_ndebug=true
I might be wrong about that, but it that is right, then a warning about that would also be good.
