### ISSUE TITLE
Rust: allow better selection of crate-type

### ISSUE THREAD

**Issue by sdroege** [mesonbuild/meson#675]
Currently we always do bin or rlib, but for many cases it is required to select something else. dylib or cdylib for example.

There should be a way to select this per target.

**Comment by sdroege** [comment]
Also what seems to be missing is to compile C and RS source files together into the same target.

For my use case I basically need the Rust compiler to compile the Rust code as cdylib and link in some C code into the same shared library file.

**Comment by acfoltzer** [comment]
I implemented the first part of this in #1922, but not the ability to automatically mix sources of different languages in the same target.

**Comment by TingPing** [comment]
I'm not sure magic happening when mixing sources is ideal, better to be explicit about it simply building a static lib and linking it.

**Comment by sdroege** [comment]
> I'm not sure magic happening when mixing sources is ideal, better to be explicit about it simply building a static lib and linking it.

You need to get all the required linker flags from Rust for generating the static lib dep though, otherwise linking to it later will become quite annoying.

**Comment by dcbaker** [comment]
This issue as requested is fixed. Mixing sources in a single target call is a different issue (and considerably complicated due to backwards compatibility). We can discuss that elsewhere.
