### ISSUE TITLE
buildtype set in project() default_options overrides -Doptimization and -Ddebug set via command-line args

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#6752]
So, f.ex., if you have:

```meson
project('foobar')
```

And you configure with: `meson setup _builddir -Doptimization=2 -Ddebug=true`, you get:

```meson
get_option('buildtype') == 'debugoptimized'
get_option('debug') == true
get_option('optimization') == '2'
```

*However*, if you have this:

```meson
project('foobar', default_options: ['buildtype=debug'])
```

And you again configure with: `meson setup _builddir -Doptimization=2 -Ddebug=true`, you get:

```meson
get_option('buildtype') == 'debug'
get_option('debug') == true
get_option('optimization') == '0'
```

This happens because we start with a dict containing the command-line arguments, then use `dict.setdefault()` to set default values from the native file and `default_options`. This works fine for options which only have one 'name'. Unfortunately, for buildtype arguments, this ends up being equivalent to: `-Doptimization=2 -Ddebug=true -Dbuildtype=debug`. The fix is to reverse the order in which things are set, working on a PR for this.

**Comment by xclaesse** [comment]
I'm tempted to instead apply `buildtype` first regardless of the order the user uses, just like we do for `prefix`.

**Comment by nirbheek** [comment]
> I'm tempted to instead apply `buildtype` first regardless of the order the user uses, just like we do for `prefix`.

I'm not sure I like that. I do agree that setting both buildtype and optimization/debug on the command-line is a suboptimal configuration. I suggest that we warn about it.

**Comment by xclaesse** [comment]
Or even abort on it like we do for `--buildtype foo -Dbuildtype=bar`.
