### ISSUE TITLE
Add optional flag to include_directories

### ISSUE THREAD

**Issue by kaimast** [mesonbuild/meson#6767]
Hi,

Sorry if this is already possible. I was hoping to make meson not fail if some of my include directories do not exist. Ideally there would be an `optional` flag for `include_directories` or some way to create a folder if it does not exist yet.

Any ideas how to do this? If not, consider this a feature request.

**Comment by TheQwertiest** [comment]
You can use `fs` module to check folder existence: https://mesonbuild.com/Fs-module.html
