### ISSUE TITLE
Dependency between two custom_target

### ISSUE THREAD

**Issue by sartymowski** [mesonbuild/meson#6773]
Hello,
I am having the hardest time with making dependency between two custom_target build. I am using meson with visual studio, so basically every custom_target is making visual studio project which will be build only when I launch VS solution and manually build it. 
What I am trying to achieve is generating a file with one custom_target - that I am able to do already - and copy that file to different subproject, which will need it. so let's say that I have those two custom_target(s):
```meson
some_file = custom_target('some_file',
	output : 'new_file.txt',
    input : ['old_file.txt],
    command : [python, some_python_program],
    install : true,
    install_dir : get_option('bindir'),
    )

custom_target('some_file2',
	output : 'new_file.txt',
	input : 'new_file.txt',
	command : [configure_file(input : 'new_file.txt',, output : 'subprojects/some_path/build/', copy: true)],
	depends: some_file,
	)
```
so as you can see I put some_file - which is returned object from first custom_target to second custom_target dependency but what I got is "Input can only be strings or file objects".

The only thing I could print from some_file object is full_path() which I can't use in input or output because at this point this file doesn't exist. What am I missing here? also I couldn't use indexes, like some_file[0] or some_file[1] - all what I got are exceptions.

Is something not working, or am I not understanding it at all?

**Comment by sartymowski** [comment]
Also, in second custom target - as yuou can see - I want to would like to have input as output of first custom_target, but when I have put some_file there I got error that it needs string, and when I put "new_file.txt" I got an error that new_file.txt doesn't exist - which is true - at this point python script in first custom_target wasn't launched

**Comment by dcbaker** [comment]
I updated your message with syntax highlighting.

You're trying to break subproject boundaries, which isn't supported. If you need a file in your subproject your subproject needs to generate that file itself, or you need to provide it externally. We explicitly don't support the root project sending things into subprojects, only the other way around.

Why do you need to push something into the subproject?

**Comment by sartymowski** [comment]
@dcbaker thank you for your updating my question. Well we have two separates modules where one have interesting file for second one. Both of them are subprojects,and I thought that it is possible to set dependency between file. As I wrote I can perfectly generate this custom target but I need to be able to generate second custom target that depends on first one. Isn't possible? I can of course run command with python but it seems to be ugly way.

**Comment by sartymowski** [comment]
I mean both custom targets are in same meson build, so it's only dependency in one subproject. It would be easier if custom target were executed immediately, because creating one Vs project for each custom target with comand seems to be problematic

**Comment by dcbaker** [comment]
You can pretty easily create a dependency between two custom targets by using the output from the first as an input to the second. This is a fairly silly example, but it does work:

```meson
project('foo')

f = custom_target(
  'f',
  output : 'f',
  command : [find_program('curl'), 'www.google.com', '-o', '@OUTPUT@'])

custom_target(
  'q',
  input : f,
  output : 'q',
  command : [find_program('xmllint'), '--html', '@INPUT@'],
  capture : true
)
```

The problem you have is that `configure_file` is run at configure time (ie, `meson builddir --backend vs`), while `custom_target` is run at buildtype `msbuild builddir/<project>.sln>`. But more importantly you're running up against two design goals of meson. 1) the root project cannot give anything to a subproject, only take things from it, and 2) the build directory layout is a private implementation detail. You've got a layering violation if the root project needs to push a file into a subproject.

What is your subproject doing with the text file you're providing?

**Comment by sartymowski** [comment]
Ok, do i have 3 different subprojects,where sub C is depend on sun B and sub B is depend on sub A. In meson build file for sub B I am calling find program, which is python script located in sub A, then I run custom target - similar to the first one in my example - and then in second custom target I want to copy it to sub A which need it for UT. All subprojects are c++ projects but that is irrelevant. I can't do anything with this design, since i am not an architect. I don't want to sound grunpy but it would be great to have more examples in documentations. Meson system looks really good!

**Comment by sartymowski** [comment]
So I end with something like that:

```meson
some_file = custom_target('some_file',
	output : 'new_file.txt',
    input : ['old_file.txt],
    command : [python, some_python_program],
    install : true,
    install_dir : get_option('bindir'),
    )

custom_target('some_file2',
	output : '@PLAINNAME@',
	input : some_file,
	command : ['xcopy', '/Y', 'new_file.txt', 'some_path'],
	depends: some_file,
	)
```

and it generates two VS projects, so so far so good. but what I would like to achieve is to run first one when second one is building. I thought that depents: some_file does that work, but apparently it doesn't. Is there a way to do that? Just to be clear, after trigger building in VS some_file2 project I would like to trigger automatically some_file project.

**Comment by Kagetsuki** [comment]
I'd say this issue is stale but I feel like there's been a regression. Running meson 1.2.1 the following fails:

```
nettle_autoreconf = custom_target(
  'nettle_autoreconf',
  build_by_default: true,
  output: 'configure',
  command: ['autoreconf', meson.current_build_dir()]
)

nettle_configure = custom_target(
  'nettle_configure',
  build_by_default: true,
  input: nettle_autoreconf,
  output: 'Makefile',
  command: [nettle_autoreconf.full_path()]
)
```

Running meson setup points out that 'configure' can't be found, but it can't be found because autoreconf isn't being run and generating it from the nettle_autoreconf custom target. If I comment out all custom targets past nettle_autoreconf the actual autoreconf is run fine, so the issue is that nettle_configure is being evaluated before autoreconf is run despite requiring input from autoreconf.

**Comment by dcbaker** [comment]
Can you open a new issue, include this, and also both targets from the build.ninja file?

**Comment by eli-schwartz** [comment]
This actually seems like totally correct behavior from the meson side of things. You told meson that the command to run is `command: [nettle_autoreconf.full_path()]` so meson lost all information about the fact that the command to run is a built file.

**Comment by dcbaker** [comment]
@eli-schwartz but it's passed as `input`, so shouldn't that create the dependency?

**Comment by eli-schwartz** [comment]
This isn't about creating a dependency, it's about passing a string value to the `command:` kwarg which must be converted to a runnable program. If you pass a built file as the kwarg, meson will simply resolve the filename in the backend. If you pass a string as the kwarg, meson tries to resolve it as input to `find_program()` and this cannot work if the custom_target() output is nonexistent at *configure* time.

**Comment by Kagetsuki** [comment]
@eli-schwartz OK that makes perfect sense. It also explains why it worked for me before because I only got the idea to use the objects returned from custom_target calls recently - I must have just used strings before. The errors I was getting were misleading - if something other than a string is being passed as input maybe displaying a warning would be a good idea? Some documentation would be nice too - if I can make some time next week I'll try and get this to work and write something out.

Aside from that, I'm wondering if maybe this issue should be closed?

**Comment by eli-schwartz** [comment]
> if something other than a string is being passed as input maybe displaying a warning would be a good idea

If something other than a string is passed, it "should" always either work fine, or raise a type error: `keyword argument 'command' was of type XXX but should have been XXXXX`

**Comment by eli-schwartz** [comment]
> Aside from that, I'm wondering if maybe this issue should be closed?

It does indeed look like the original support question was answered.

**Comment by Kagetsuki** [comment]
> > if something other than a string is being passed as input maybe displaying a warning would be a good idea
> 
> If something other than a string is passed, it "should" always either work fine, or raise a type error: `keyword argument 'command' was of type XXX but should have been XXXXX`

Right, but in this case, as you pointed out, it's not that it's a type that can't be handled; it's that it's a type that can be handled but will not have the necessary data at setup/configuration time. I don't have the error that was displayed right this moment but I recall it as being misleading. Perhaps a better error, and some documentation added to the custom targets section on how to do this correctly would be helpful. If I can make the time next week I'll try and make a working sample and add a description to the documentation on how to chain custom targets.

**Comment by eli-schwartz** [comment]
Additional documentation is rarely a bad thing, to be sure. :)

I'll be happy to look at your suggested improvements whenever you have time available to implement them.

**Comment by Kagetsuki** [comment]
I'm opening up an issue relating to custom_target and executable/library dependencies now but just let me leave a comment to clean up confusion: dependencies between custom_targets doesn't work *by design* according to [this bit](https://mesonbuild.com/Custom-build-targets.html#details-on-command-invocation) of the documentation. The issue I'm posting now does not refute this decision - so as far as I know everyone coming here looking for a solution to chain custom_targets and make a custom_target pipeline:

The "correct" way to make a custom_target pipeline
========================================
You have two choices:
1. Make a single custom_target that calls a script.
2. Create multiple build files which each declare_dependency and create a dependency chain between them.

Do whatever feels cleaner for your project.
