### ISSUE TITLE
Feature request: Assembler support through nasm/yasm

### ISSUE THREAD

**Issue by hyronx** [mesonbuild/meson#678]
Hello, 
I need nasm support for a project because everything else has failed or was hard to maintain.

I tried to use custom_target for that but it didn't work out as hoped and my current solution with a shell script has problems dealing with directory changes...

To be a general purpose build system Meson might also support low level languages and linking to C or other high level languages.

**Comment by jpakkane** [comment]
Could you give an example of what you are doing? What are the names of the input and output files and what command do you run to do the compile if you do it manually?

**Comment by hyronx** [comment]
Unfortunately, I can post my commands only tomorrow.
What I'm playing with is a custom kernel system but assembler could be useful for kernel driver/module and real time code developers, too. 

Another example are microcontrollers which often need some assembler. This is a different section but Meson could address these one day, too.

**Comment by hyronx** [comment]
I have fixed it today by using the following code:
```text
src_asm = [
  '../system/src/x86-64/boot.asm',
  '../system/src/x86-64/ap_init.asm',
  '../system/src/x86-64/cpu_functions.asm',
  '../system/src/x86-64/enable_64bit.asm',
  '../system/src/x86-64/init.asm',
  '../system/src/x86-64/system_isr.asm'
]

objs_asm = []
foreach src : src_asm
  output = meson.current_build_dir() + '/' + src.underscorify() + '.o'

  run_command(
    'nasm',
    '-f elf64',
    src,
    '-o',
    output
  )

  objs_asm +=  output
endforeach
```

`objs_asm` is then added as `objects : objs_asm` but it still isn't a nice solution because all sources have to be in the same directory. 

An addition of a `first` and `last` method to the array object would make my life easier here.

**Comment by jpakkane** [comment]
What you probably want instead of that is a generator:

    nasm = find_program('nasm')

    gen = generator(nasm,
     output  : '@BASENAME@.obj',
     arguments : ['-f', 'elf64', '@INPUT@', '@OUTPUT@'])

     nasmobjs = g.generate(['file1.asm', 'file2.asm', 'file3.asm', ...)

And then using nasmobjs in your target.

**Comment by hyronx** [comment]
Thank you! This looks like the better solution. I've completely forgot the generator...

Anyway assembler support may be worth considering..

**Comment by hyronx** [comment]
Well... The resulting object of `gen.process` seems to be a source file or something else which the executable parameter `objects` doesn't accept.

The error is: `Bad object in target kernel.`

**Comment by jpakkane** [comment]
Strange, [we have a test case for exactly this](https://github.com/mesonbuild/meson/tree/master/test%20cases/common/59%20object%20generator). It should work. Please check that you are doing the same as in that test. If not, please post your Meson config.

**Comment by nirbheek** [comment]
@hyronx You're using it incorrectly. Add it as a 'source' instead of as an argument to the `objects` kwarg. That's supposed to be used for pre-built (such as proprietary) objects that are in the source tree.

> objects list of prebuilt object files (usually for third party products you don't have source to) that should be linked in this target, never use this for object files that you build yourself.

See how the test works. I'll improve the error message that `gen.process` prints.
