### ISSUE TITLE
common/39 has function fails on Linux

### ISSUE THREAD

**Issue by ernestask** [mesonbuild/meson#6784]
**Describe the bug**
Seems that glibc has grown an lchmod implementation that breaks the test:
https://sourceware.org/bugzilla/show_bug.cgi?id=14578
https://sourceware.org/git/?p=glibc.git;a=commit;h=6b89c385d8bd0700b25bac2c2d0bebe68d5cc05d

**To Reproduce**
Try to build https://src.fedoraproject.org/rpms/meson/blob/master/f/meson.spec with tests enabled in the Rawhide chroot with Mock. Just booting the latest Rawhide compose and running the test there should work as well, I imagine (will try now).

**Expected behavior**
test cases/common/39 has function passes.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? Native build
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.): Fedora Rawhide
* what Python version are you using e.g. 3.8.0: 3.8.2
* what `meson --version`: 0.53.999 (88e40c7081b9bf8a337022ad2f12efe485fa8021)
* what `ninja --version` if it's a Ninja build: N/A

**Comment by ernestask** [comment]
And indeed you can reproduce this in a regular Rawhide environment.

**Comment by DimStar77** [comment]
openSUSE Tumbleweed is also in progress uppgrading to glibc 2.32 and is thus now also affected

Link to a build log of the meson test suite: https://build.opensuse.org/package/live_build_log/openSUSE:Factory:Staging:C/meson:test/standard/x86_64
