### ISSUE TITLE
Link Phobos dynamically for D shared libraries

### ISSUE THREAD

**Issue by Cogitri** [mesonbuild/meson#6786]
**Describe the bug**
Right now meson doesn't specify these flags for D compilers:

* LDC: `-link-defaultlib-shared`
* GDC: `-shared-libphobos`
* DMD: `-defaultlib=phobos2 -debuglib=phobos2`

Due to that a static copy of phobos is linked into the shared lib (AFAIK). This causes the following error when building a shared lib and linking an executable against it:

```
Aborting from rt/sections_elf_shared.d(506) Only one D shared object allowed for static runtime. Link with shared runtime via LDC switch '-link-defaultlib-shared'.
'corectl list' terminated by signal SIGABRT (Abort)
```

At least the executable shouldn't be linked with the static libphobos.

**To Reproduce**
Here's a repo to reproduce it: https://github.com/Cogitri/meson-bug-reproducer

Clone it, then run `meson build && ninja -C build`. Afterwards try to execute './build/tester`.

**Expected behavior**
Meson should pass the right flag to link phobos dynamically. I'm not sure if this should be done automatically or if there should be some flag to meson, but this should definitely be built into meson since many upstreams just add `link_args: '-link-defaultlib-shared'` to their buildtargets, which only works with LDC as compiler.

CC @dcbaker

**Comment by dcbaker** [comment]
Interestingly enough gentoo patches ldc to include `-link-defaultlib-shared` in most cases, and dmd is set up with those by default as well. What distro are you running on?

**Comment by Cogitri** [comment]
This is on Alpine Linux. I'll probably change the default there too, but since the official ldc tarballs link phobos statically by default I feel like meson needs to so something about this.

**Comment by dcbaker** [comment]
Yeah, we probably should.

**Comment by GoaLitiuM** [comment]
Yes, D runtime is expected to be statically linked on Windows in most if not all cases.
