### ISSUE TITLE
Unexpected libdir value

### ISSUE THREAD

**Issue by chouquette** [mesonbuild/meson#6809]
**Describe the bug**
The default generated value for libdir is unexpected.
```$> meson build
The Meson build system
Version: 0.53.1
...
Found ninja-1.8.2 at /usr/bin/ninja
$> cd build
$> meson configure | grep libdir
  libdir              lib/x86_64-linux-gnu                                                               Library directory
```

While I'd expect it to be set to `lib/`

**To Reproduce**
https://github.com/videolabs/libmicrodns/blob/master/meson.build (I realize there is some probably unrequired boilerplate related to pkg-config, but libdir is only fetched from the configuration data)

`meson build` is enough for me to reproduce the issue

**Expected behavior**
I'd expect libdir to default to `lib/` to match the autoconf behavior

**system parameters**
* Native build
* `Linux bender 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux`
* Python 3.7.3
* meson 0.53.1
* ninja 1.8.2

**Comment by dcbaker** [comment]
That is the correct value, debian installs it's libraries into `lib/<host-triple>` (x86_64-linux-gnu, i686-linux-gnu, etc). If you really want to change that you can set `-Dlibdir` on the command line.
