### ISSUE TITLE
"Unreachable code" is vague (and incorrect) error

### ISSUE THREAD

**Issue by remexre** [mesonbuild/meson#682]
https://github.com/mesonbuild/meson/blob/master/mesonbuild/backend/backends.py#L264

If you specify a language you don't use, you get told that there's `Unreachable code`... Maybe change this to "unused language" or smth?

**EDIT** Actually, I'm getting this when specifying that a project uses `c` and `rust`, and later (in a subdir) creating an executable from a Rust file. It occurs whenever I specify `rust`, but the ninja file doesn't execute if I don't specify `rust`.

**Comment by jpakkane** [comment]
If you remove the C part and only build the Rust target, does it work?

**Comment by remexre** [comment]
Yes, with either both `c` and `rust` or just `rust` specified.

**Comment by jpakkane** [comment]
Weird. Could you post your repo somewhere public so we can take a look.

**Comment by remexre** [comment]
https://github.com/remexre/parallisp/tree/rust-v2

**Comment by jpakkane** [comment]
I'll take a look hopefully tomorrow. In the mean time you might want to fix this line:

    add_global_arguments('-std=c11', '-Wall', '-Wextra', '-Werror',

We have native, portable support for all of these. Do this instead:

    project(...,
            default_options : ['c_std=c11', 'warnlevel=2, 'werror=true'])

Being able to unset werror is especially useful when debugging.

**Comment by remexre** [comment]
Okay, thanks! I'm new to meson, so I'm not 100% sure how things are "supposed to be done."

**Comment by jpakkane** [comment]
This is hard to debug since it needs a prebuilt `parallispc` binary...

**Comment by remexre** [comment]
Oh, duh. If you have go, `go get github.com/remexre/go-parallisp/cmd/parallispc` will do it. If not, I can put binaries on Dropbox.

**Comment by remexre** [comment]
Okay, the bug still occurs if you change `find_program('parallispc')` to `find_program('cat')`, so it's (probably?) not related to the `parallispc` binary.

**Comment by nirbheek** [comment]
This specific bug is already fixed. Please file new bugs if you have issues with mixed Rust and C projects. Thanks! :)
