### ISSUE TITLE
declare_dependency() and language specific arguments

### ISSUE THREAD

**Issue by deviator** [mesonbuild/meson#6821]
For example is no way to specify `d_import_dirs` in `declare_dependency` by now (only through `compiler_args: ['-J../neededpath']` with relative path from build directory). It's by design or it is can be implemented? I think it can be useful.

**Comment by dcbaker** [comment]
It can be added.

**Comment by denizzzka** [comment]
Made test for this issue:
https://github.com/denizzzka/meson/tree/d_import_dirs_test

**Comment by denizzzka** [comment]
Probably, solved in https://github.com/mesonbuild/meson/pull/10061

**Comment by dcbaker** [comment]
I’m going to declare its fixed and we can reopen if that isn’t true
