### ISSUE TITLE
meson problem because of inconsistent working directory

### ISSUE THREAD

**Issue by mfxmfx** [mesonbuild/meson#683]
The behaviour of

`mkdir -p build && cd build && meson .. .`

is different from  

  `mkdir -p build && meson . build`

I stumbled across this issue when using run_command() triggered by "--internal regenerate".

As all files in meson.build are releative to the source directory it would seem consistent that meson does a chdir() to the source dir at the beginning of the generate/regenerate step. I'm not sure about possible implications, though.

**Comment by nirbheek** [comment]
The directory from which `run_command()` is run is unspecified on purpose. Your scripts should do a `chdir()` into `MESON_SOURCE_ROOT` or `MESON_BUILD_ROOT` as appropriate before running.
