### ISSUE TITLE
meson fails on the call to symbolextractor.py

### ISSUE THREAD

**Issue by keszybz** [mesonbuild/meson#6850]
With systemd master and meson meson-0.53.2-1.git88e40c7.fc32.noarch (0.53.999):
```
$ ninja -C build
...
[2/1174] /usr/bin/meson --internal symbolextractor libsystemd.so.0.28.0 'systemd@sha/libsystemd.so.0.28.0.symbols' 
FAILED: systemd@sha/libsystemd.so.0.28.0.symbols 
/usr/bin/meson --internal symbolextractor libsystemd.so.0.28.0 'systemd@sha/libsystemd.so.0.28.0.symbols' 
symbolextractor.py <shared library file> <import library> <output file>
ninja: build stopped: subcommand failed.
```

Fedora 32, Python 3.8.2, meson 0.53.999, ninja 1.10.0.

**Comment by ernestask** [comment]
Hm, weird, it works for me with the same setup.

**Comment by keszybz** [comment]
Maybe it's caused by the data files created by an older version of meson? I'll see if it reproduces with a clean build directory.

**Comment by keszybz** [comment]
Hmm, I can't reproduce it now at all. Maybe it was some funky state because of repeated rebuilds.
