### ISSUE TITLE
CMake inputs/dependencies cycle error with libzmq subproject.

### ISSUE THREAD

**Issue by llm96** [mesonbuild/meson#6857]
**Describe the bug**

Attempting to use [libzmq 4.3.2](https://github.com/zeromq/libzmq/releases/tag/v4.3.2) as a CMake subproject results in an error.

```
||-- Configuring done
||-- Generating done
||-- Build files have been written to: /home/llm96/zmqtest/build/subprojects/libzmq/__CMake_build
|
|CMake configuration: SUCCEEDED
|WARNING: CMake: path /home/llm96/zmqtest/subprojects/libzmq/../include does not exist.
|WARNING:  --> Ignoring. This can lead to build errors.
|WARNING: CMake: path /home/llm96/zmqtest/subprojects/libzmq/../include does not exist.
|WARNING:  --> Ignoring. This can lead to build errors.
 ... repeats several times ...
|WARNING: CMake: path /home/llm96/zmqtest/subprojects/libzmq/../include does not exist.
|WARNING:  --> Ignoring. This can lead to build errors.
|WARNING: CMake: path /home/llm96/zmqtest/subprojects/libzmq/../include does not exist.
|WARNING:  --> Ignoring. This can lead to build errors.
|CMake project ZeroMQ has 119 build targets.

meson.build:5:0: ERROR: Cycle in CMake inputs/dependencies detected
```

**To Reproduce**

[With this example project:](https://github.com/mesonbuild/meson/files/4395533/zmqtest.zip)
```
$ meson build
```

**Expected behavior**

Configuration runs without errors.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?

> Native, but the same happens using the default [linux-mingw-w64-64bit](https://github.com/mesonbuild/meson/blob/master/cross/linux-mingw-w64-64bit.txt) cross-file.

* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
> Arch Linux

* what Python version are you using e.g. 3.8.0
> Python 3.8.2

* what `meson --version`
> 0.53.2

* what `ninja --version` if it's a Ninja build
> 1.10.0

**Comment by mensinda** [comment]
Should be fixed with #6859.
