### ISSUE TITLE
meson complains that "it Could not detect Ninja v1.5 or newer" even though it looks for ninja-1.7

### ISSUE THREAD

**Issue by evverx** [mesonbuild/meson#6867]
Since meson was updated it has been failing to build `systemd` on Travis CI with
```
$ meson --version
0.54.0

$ ninja --version
1.5.1

$ meson build
...
ERROR: Could not detect Ninja v1.5 or newer
...
```
I'll update ninja there but it would be great if the error message was a little bit more specific.

**Comment by michaelbadcrumble** [comment]
Is this issue active?

**Comment by evverx** [comment]
As far as I can tell, it was fixed in https://github.com/mesonbuild/meson/commit/e04b0ae6b6220381b4aa493289960a3555201717#diff-a66a8f5d37d3492fc951e272fca392e7.

**Comment by devkenante** [comment]
> As far as I can tell, it was fixed in [e04b0ae#diff-a66a8f5d37d3492fc951e272fca392e7](https://github.com/mesonbuild/meson/commit/e04b0ae6b6220381b4aa493289960a3555201717#diff-a66a8f5d37d3492fc951e272fca392e7).

Still getting the same issue  on meson -v 0.54.1

**Comment by devkenante** [comment]
> > As far as I can tell, it was fixed in [e04b0ae#diff-a66a8f5d37d3492fc951e272fca392e7](https://github.com/mesonbuild/meson/commit/e04b0ae6b6220381b4aa493289960a3555201717#diff-a66a8f5d37d3492fc951e272fca392e7).
> 
> Still getting the same issue on meson -v 0.54.1

Solved by installing ninja by pip3

> pip3 install ninja meson

**Comment by andlabs** [comment]
@devkenante that commit is not yet in any stable version of meson

**Comment by estatistics** [comment]
installing bookworm sid 12 on bullseye 11, ERROR: Could not detect Ninja v1.8.2 or newer sudo meson _build  for glib,  ninja --version 1.11.1
