### ISSUE TITLE
name_prefix not always used

### ISSUE THREAD

**Issue by taz-007** [mesonbuild/meson#689]
When building a shared_library with a custom name_prefix set, the default prefix ("lib") is used (instead of the one set) for the following arguments (at link time):

-Wl,-soname,libfoo.so
-Wl,--out-implib=libfoo.dll.a

(the -o argument is correctly using the custom prefix)

**Comment by nirbheek** [comment]
So the `-Wl,-soname,libfoo.so` part is wrong even without `name_prefix` because it's wrong on, for instance, on Windows, but I'm not entirely sure what it should be.

The implib should always be called `libfoo.dll.a` though because otherwise GCC cannot find it via `-lfoo`

**Comment by nirbheek** [comment]
This was fixed in f0fee2e54260a4d227d282da3435f129c6b54687. The soname now always uses the prefix.
