### ISSUE TITLE
Using subproject feature when adopting already existing projects

### ISSUE THREAD

**Issue by dzhang-b** [mesonbuild/meson#6894]
From the documentation, I know `subproject` feature has a few limitations that make it hard to use.
1. subproject folder cannot be named differently. (we are using `submodules` name)
2. subproject has to follow specific path layout. `root_dir/subprojects/xxx`

The existing project has a lot of other small subprojects exists recursively, and a lot of scripts (tools, build CI, etc) are depended on these paths. 

In order to use meson right now, I have to manually prepare a `./configure` script that configure each meson project recursively, which I am not sure if it is ideal. 

Why can't we allow subproject declared in the root `meson.build` file using whatever path we want?
```meson
# root repo
subproject('path..',..)

# under subprojects 
if project.root
  subproject('path..',..)...
else
  // subproject must defined in the root meson.build..
endif
```

**Comment by phillipjohnston** [comment]
You can use this argument in the `project()` declaration:

```
subproject_dir: 'submodules',
```

**Comment by phillipjohnston** [comment]
I should note that in the project I adapted to meson, the subproject directory is `src/external`, so it is not necessarily a "top level directory".

**Comment by dzhang-b** [comment]
@phillipjohnston Thanks!, This definitely a great start for using subprojects in meson.

**Comment by dzhang-b** [comment]
additional new meson functions can be add like this?
```meson
# the function can only be used in top level `meson.build` file.
subproject_set('name', 'path')

# the function can check if a subproject is set in the top level project
subproject_get('name', 'path') # the path is relative, meson can check if top level and subproject definition are the same
```

then a sample use case can be:
```meson
if is_subproject() # include as subproject in other projects
   # p = subproject_get('xxxx', path) # report error if no match meson.build
else
  # p = subproject_set('xxxx', path) # include the subproject like as a top level meson.build
endif
```

**Comment by dzhang-b** [comment]
During the process of porting existing projects,

I found that dependencies between subprojects is not allowed. all inter-dependencies must bring up to the master project using `subproject.get_variables()`.

If meson can support `subproject.get_variables()`, why can not meson support subprojects hierarchy as long as same level subprojects cannot talk to each other?

```
     A
   /    \
 B    C
       /  \
     D   E
```
In the above graph, B cannot talk to D or E or C directly for example, every symbol must be resolved at A for B and D/E works together.
--------------

Other issues is that existing source expect to use header files from installed directory.  while `include_directory` only specify the source. Is it possible to have `include_directories` to prepend the `install_dir` string?

**Comment by xclaesse** [comment]
B can do subproject(D).get_variable().

**Comment by dzhang-b** [comment]
@xclaesse can meson does this now?

**Comment by xclaesse** [comment]
It always could, AFAIK.

**Comment by dzhang-b** [comment]
@xclaesse It tells me that D.wrap file is not found, but where should I put the wrap file and what content I need to put into it?

**Comment by xclaesse** [comment]
@dzhang-b wrap files must be in A's subprojects/ directory. They describe how to download code for B, C, D, E. So you'll have `A/subprojects/{B,C,D,E}` but you cannot have `A/subprojects/C/subprojects/{D,E}`, which is a limitation we should probably fix.

**Comment by xclaesse** [comment]
https://mesonbuild.com/Wrap-dependency-system-manual.html

**Comment by dzhang-b** [comment]
I will close this issue, as I find out that using a package manager like `spack` is a better way to manage multiple projects/components than using build system.
