### ISSUE TITLE
fPIC flag is on for MSYS2/Cygwin

### ISSUE THREAD

**Issue by ryanisaacg** [mesonbuild/meson#690]
MSYS2 and Cygwin are Unix-like environments that run on Windows. This means that meson presumably assumes it is running under a Unix and turns on the -fPIC flag for C(++) shared libraries. However, since it is actually a windows system, a warning about the flag is generated.

**Comment by jpakkane** [comment]
Can you test if the linked MR fixes it for you?

**Comment by ryanisaacg** [comment]
It's all good now, thanks.
