### ISSUE TITLE
Required ninja version is inconsistent

### ISSUE THREAD

**Issue by tbodt** [mesonbuild/meson#6918]
https://github.com/mesonbuild/meson/blob/00104b1081cd5076451d83524f4f9bfa75750cf6/mesonbuild/backend/ninjabackend.py#L297
https://github.com/mesonbuild/meson/blob/00104b1081cd5076451d83524f4f9bfa75750cf6/mesonbuild/backend/ninjabackend.py#L306
https://github.com/mesonbuild/meson/blob/8bdc5c2dd564fc685e82f67480ad0adc43c823b2/mesonbuild/environment.py#L154
Is it 1.5, 1.5.1, or 1.7?

**Comment by xclaesse** [comment]
At least for Meson >=0.54 the minimum required version is 1.7, according to changelog. We should indeed update all those places, ideally storing the minimum version requires in a single place.

**Comment by eli-schwartz** [comment]
Fixed in #6993...
