### ISSUE TITLE
Version constraint in generated pkg-config file influenced by subproject order

### ISSUE THREAD

**Issue by chewi** [mesonbuild/meson#6923]
**Describe the bug**
If a subproject pulls in the same dependency as the parent but with a different version constraint, the version that was requested first is written into the parent's generated pkg-config files.

**To Reproduce**
Build the following project and check the result in `meson-uninstalled/foo-uninstalled.pc`. Then swap the commented `subproject` lines, run `meson --wipe && ninja` and check the result again. Notice how the zlib version changes.

*meson.build:*
```
project('foo', 'c')

subproject('subproject') # Produces zlib >= 1.1

dep = dependency('zlib', version : '>= 1.2')
lib = library('foo', dependencies : dep)

pkg = import('pkgconfig')
pkg.generate(lib)

# subproject('subproject') # Produces zlib >= 1.2
```
*subprojects/subproject/meson.build:*
```
project('bar', 'c')

dep = dependency('zlib', version : '>= 1.1')
```

The real world example of this is in [this merge request for SPICE](https://gitlab.freedesktop.org/spice/spice/-/merge_requests/75).

**Expected behavior**
I'm not sure whether it should simply honour the parent project or pick the greater of the two versions. Probably the former.

**system parameters**
* Plain native build.
* Gentoo Linux.
* Python 3.7.7.
* Meson 0.54.999 @ e034ebd1537a72d550a699c0d155f19f4791bdc0.
* Ninja 1.10.0.

**Comment by xclaesse** [comment]
I think that's the expected behaviour. There are a few subtle cases like this where the order of dependencies matters. The general answer is the parent is responsible to manage the order by checking the dep before calling the subprojects.

**Comment by chewi** [comment]
I can live with it but that seems odd to me. I'll leave this open for further comments.

**Comment by xclaesse** [comment]
The thing is if both the main project and the subproject check the same dependency with a different version, and both generate a pkgconfig file, one of them will have the wrong version...

We could track the version requirement per-subproject, but I think it's getting too complicated for something not that important.

Another option is to pic the greater version, but then that still depend on ordering. By the time we generate the first pkgconfig file, we could not have checked for the that dependency with greater version requirement yet. Again that's getting complicated.

That being said, one easier workaround is to add an arg to `pkg.generate()` to just omit the version requirements completely, it's not that important information.

**Comment by chewi** [comment]
Fair enough. I figured separate tracking would be needed but didn't know if it would be difficult.
