### ISSUE TITLE
Meson find_program fails to find python when installed from the Windows Store in 0.54.0

### ISSUE THREAD

**Issue by jenatali** [mesonbuild/meson#6927]
**Describe the bug**
In 0.54.0, a change was committed (`64432e94481dbd55bedf92f21610bc5ed6b52655`) to ignore the Windows 10 "Execution Aliases" directory, to prevent finding e.g. python.exe when it's just a redirect to the Store. But once you install Python from the store, that redirect actually becomes the program that's run. So, running python.exe from the execution alias, in order to run meson.py, then fails to find a program named python.exe.

**To Reproduce**
1. Install Python from the Windows store.
2. Install/clone meson.
3. Run meson on a script including `find_program("python")`.

**Expected behavior**
Python is found.

Consider checking whether the current meson instance is being run from the execution alias before excluding that directory from program search. People setting up new development machines now that this exists may actually *want* to use the Windows Store version of python, to prevent similar issues with other tools finding the dummy python.exe instead of the real installation.

**Comment by jpakkane** [comment]
The only real Windows install I have is an old Windows 7 I use for playing games, so unfortunately I can't really fix this (and even if I could I would not be able to properly test it). Patches are welcome, though.
