### ISSUE TITLE
cmake@ substitutions fail in 0.54.0, they worked in 0.53.0

### ISSUE THREAD

**Issue by Alan-R** [mesonbuild/meson#6932]
**Describe the bug**
Latest version stopped supporting **cmake@** subsitutions in 0.54.0. It now finishes with an assert failure:
                                                                                                                       
```
  File "/usr/local/lib/python3.6/site-packages/mesonbuild/mesonlib.py", line 880, in do_replacement                                                                                                  
    assert variable_format == 'meson'                                                                                                                                                                
AssertionError
```

**To Reproduce**
```
# Create project_common.h from project_common.h.in
common = configure_file(input: 'include/projectcommon.h.in',
                        output: 'projectcommon.h',
                        configuration: config_data,
                        format: 'cmake@',
                        )

```
**Expected behavior**
It should do the substitutions like it did in 0.53.0.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? **Native**
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) **Ubuntu**
* what Python version are you using e.g. 3.8.0: **3.6.10**
* what `meson --version`: **0.54.0**
* what `ninja --version` if it's a Ninja build
**It didn't get that far.**

I discussed this with @dcbaker on IRC. You need a cmake@ regression test.

**Comment by dcbaker** [comment]
There's an assert in `mesonlib.do_replacement` that is just bogus; but more importantly we don't have a test for this and clearly need on.

**Comment by mensinda** [comment]
@dcbaker In case you have missed it, there is already  #6917.
