### ISSUE TITLE
Several GNU directory options are not available

### ISSUE THREAD

**Issue by QuLogic** [mesonbuild/meson#694]
I see several [predefined directory options](https://github.com/mesonbuild/meson/blob/master/mesonbuild/coredata.py#L202), but several of the [GNU Coding Standard directories](https://www.gnu.org/prep/standards/html_node/Directory-Variables.html) are missing, notably `sysconfdir` being the main one.

**Comment by jpakkane** [comment]
We have not added all of them because we don't really know which ones are actually used and which ones are legacy. If you list which ones your project need, we can add those.

**Comment by QuLogic** [comment]
For the moment, I think only `sysconfdir` is the missing one.

**Comment by jpakkane** [comment]
Can you test #699 to see if it does what you expect?
