### ISSUE TITLE
`meson_options.txt` cannot be used to specify negative integer values

### ISSUE THREAD

**Issue by jfinkhaeuser** [mesonbuild/meson#6948]
*Actual:*
When trying to specify a negative number in `meson_options.txt`, I get the error `Arguments may only be string, int, bool, or array of those.`.

*Expected:*
No error is raised, and negative values are accepted.

*Rationale:*
These options are ideal for setting defaults for build configuration via `#mesondefine`. It's fairly common for integer options to treat zero and negative values as having special meanings. And even if not, sometimes you'd like to have negative values as options.

*Workaround:*
- Add a second option for the special meaning (ugh!)
- Pass the option as a string, and use `#define` instead of `#mesondefine` (ugh!)

*Details:*
The error is raised here:
https://github.com/mesonbuild/meson/blob/6e865fc08d0d13b3846d00e80c9f3ea090645fb8/mesonbuild/optinterpreter.py#L170

The culprit looks like it may be here: https://github.com/mesonbuild/meson/blob/6e865fc08d0d13b3846d00e80c9f3ea090645fb8/mesonbuild/mparser.py#L107

**Comment by mensinda** [comment]
Should be fixed with #6948.

**Comment by jfinkhaeuser** [comment]
Vielen Dank!

**Comment by mensinda** [comment]
Kein Problem.
