### ISSUE TITLE
[RFC] normalize build file and option file name

### ISSUE THREAD

**Issue by pynixwang** [mesonbuild/meson#6951]
meson.build            -> build.meson
meson_options.txt ->options.meson

unified file extension

**Comment by pynixwang** [comment]
meson developer is very "free" for naming.

**Comment by eligt** [comment]
I strongly agree with this convention. File extensions are used in many places to determine a file's purpose, including for instance automatic syntax highlighting in editors. The ".build" extension is already abused while ".meson" is unique enough to be uniquely associated to the Meson build system.

**Comment by bruchar1** [comment]
Related to #11179

**Comment by eli-schwartz** [comment]
Duplicate of #11176
