### ISSUE TITLE
cmake.configure_package_config_file generates CMake path with OS-specific directory separators, diffenrtly from CMake

### ISSUE THREAD

**Issue by traversaro** [mesonbuild/meson#6955]
**Describe the bug**
While not strictly a bug, I wanted to report that the the `cmake.configure_package_config_file` function generates the relative path containing OS-specific directory separators, i.e. for example as:
~~~
get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/..\..\.." ABSOLUTE)
~~~
on Windows and 
~~~
get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
~~~
on Linux/macOS. This is because in meson the relative path is obtained via the [`os.path.relpath`](https://github.com/mesonbuild/meson/blob/73ddc014774102b378bb89bf9d4801d7b231b745/mesonbuild/modules/cmake.py#L271), that returns path with OS-specific directory separators. 

This behavior is different from CMake's configure_package_config_file, where the relative path is obtained via the [`file(RELATIVE_PATH ...)`](https://gitlab.kitware.com/cmake/cmake/-/blob/v3.16.6/Modules/CMakePackageConfigHelpers.cmake#L261) CMake function, that returns a relative path always with CMake-style path, i.e. with slash as directory separator. Furthermore on CMake the relative path always ends with `/`, while the one generated with Meson do not end with `/`.

**To Reproduce**
Configure a meson project that uses the `cmake.configure_package_config_file` function on both Windows on Linux, and insect the file generated by it.

**Expected behavior**
For consistency with CMake, it would be great if also on Windows the generated file contained a CMake-style path and ending with `/`.
~~~
get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../" ABSOLUTE)
~~~

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? 
  * plain native build
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
  * Windows 10 and  Ubuntu 18.04 
* what Python version are you using e.g. 3.8.0
  * Python 3.8.0
* what `meson --version`
  * 0.5.4
* what `ninja --version` if it's a Ninja build
  * 1.8.2

**Comment by traversaro** [comment]
Just to clarify, both ways of generating the relative path are actually ok, but this small difference with CMake may break the workflows that rely exactly on the structure of the `PACKAGE_PREFIX_DIR` definition, in particular the `vcpkg_fixup_cmake_targets` script from vcpkg: https://github.com/microsoft/vcpkg/blob/2020.01/scripts/cmake/vcpkg_fixup_cmake_targets.cmake#L152 .

**Comment by traversaro** [comment]
Thanks @eli-schwartz !

**Comment by eli-schwartz** [comment]
You should thank @fcx-mrogez instead. :)

**Comment by traversaro** [comment]
> You should thank @fcx-mrogez instead. :)

Thanks @fcx-mrogez !
