### ISSUE TITLE
Bad command name on run_command error message 

### ISSUE THREAD

**Issue by adalessandro** [mesonbuild/meson#6969]
Calling `run_command` with a non-found program returned by `find_program`, returns an ugly error message.

`meson.build` file:
```
project('test', 'c')

foo_program = find_program('foo_program', required : false)
run_command(foo_program)
```
Log:
```
$ python --version
Python 3.8.2

$ meson build
The Meson build system
Version: 0.54.999
[...]
Build type: native build
Project name: test
Project version: undefined
C compiler for the host machine: ccache cc (gcc 9.3.0 "cc (Arch Linux 9.3.0-1) 9.3.0")
C linker for the host machine: cc ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program foo_program found: NO

meson.build:4:0: ERROR: command <NonExistingExternalProgram 'nonexistingprogram' -> [None]> not found or not executable
[...]
```

System details are described in the code snippet above.

**Comment by adalessandro** [comment]
After chatting about this issue in the PR [0], I think that the proper solution would be storing the program's name in the `NonExistingExternalProgram` instances, and showing it in the current error message.

I'll submit a patch for this soon.

[0] https://github.com/mesonbuild/meson/pull/6970

**Comment by adalessandro** [comment]
This patch prints the program's name on the error message:
https://github.com/adalessandro/meson/commit/bcd8b0473ebf50920a5759d4a2b24db3c106e084

Same test setup as before:

```
$ meson build
The Meson build system
Version: 0.54.999
[...]
Build type: native build
Project name: test
Project version: undefined
C compiler for the host machine: ccache cc (gcc 9.3.0 "cc (Arch Linux 9.3.0-1) 9.3.0")
C linker for the host machine: cc ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program foo_program found: NO

meson.build:3:0: ERROR: command 'nonexistingprogram' not found or not executable
[...]
```

**Comment by adalessandro** [comment]
This patch modifies `find_program()` to store the program's name even if it's not found:
https://github.com/adalessandro/meson/commit/4f7d62bcee76e2b78ba2b753f5742a27dcdbae6c

This way, the `NonExistingExternalProgram` will have the target program's name stored instead of the default name `nonexistingprogram`, as printed in the previous comment.

Example test with a single program name argument:

```
$ cat meson.build 
project('test', 'c')
foo_program = find_program('foo_program', required : false)
run_command(foo_program)

$ python --version
Python 3.8.2

$ meson build/
The Meson build system
Version: 0.54.999
[...]
Build type: native build
Project name: test
Project version: undefined
C compiler for the host machine: ccache cc (gcc 9.3.0 "cc (Arch Linux 9.3.0-1) 9.3.0")
C linker for the host machine: cc ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program foo_program found: NO

meson.build:3:0: ERROR: command 'foo_program' not found or not executable
[...]
```

Example test with multiple program name arguments:

```
$ cat meson.build 
project('test', 'c')
foo_program = find_program('foo_program', '/usr/bin/foo_program', required : false)
run_command(foo_program)

$ python --version
Python 3.8.2

$ meson build/
The Meson build system
Version: 0.54.999
[...]
Build type: native build
Project name: test
Project version: undefined
C compiler for the host machine: ccache cc (gcc 9.3.0 "cc (Arch Linux 9.3.0-1) 9.3.0")
C linker for the host machine: cc ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program foo_program found: NO
Program /usr/bin/foo_program found: NO

meson.build:3:0: ERROR: command 'foo_program /usr/bin/foo_program' not found or not executable
[...]
```

**Comment by adalessandro** [comment]
@xclaesse, have any comments on this?

**Comment by xclaesse** [comment]
@adalessandro Looks good to me, can you open a pull request please? I would just add coma between program names, what do you think?

**Comment by adalessandro** [comment]
> @adalessandro Looks good to me, can you open a pull request please? I would just add coma between program names, what do you think?

I based the `join()` format on this `log()` call from `find_program()`: https://github.com/mesonbuild/meson/blob/master/mesonbuild/interpreter.py#L3248
I'm fine in either case, although I'd rather keep the same formatting.

**Comment by adalessandro** [comment]
Merged. Closing.
