### ISSUE TITLE
Enhancement: Generate testlog.junit as well as testlog.json and testlog.txt

### ISSUE THREAD

**Issue by nickbroon** [mesonbuild/meson#6972]
Currently meson generates `testlog.txt` and an [invalid json file `testlog.json`](https://github.com/mesonbuild/meson/issues/5458) with the results of tests.

It would be extremely useful if it also produced a testlog.junit file in the very widely support (particularly by many CI systems) JUnit format, as this would facilitate its easy integration into CI builds.

**Comment by dcbaker** [comment]
This has been on my list of things to do for a while, just haven't gotten there yet.
