### ISSUE TITLE
gnome.compile_resources does not support --manual-register

### ISSUE THREAD

**Issue by baedert** [mesonbuild/meson#698]
As is used in e.g. gdk.

**Comment by ignatenkobrain** [comment]
From man page it looks like it is needed only for some compilers. I think we should find names of those compilers and set this option only there.

I guess GDK uses it to be sure that it will compile everywhere

**Comment by jpakkane** [comment]
It can't be done automatically because it also needs changes in C code. We should add possibility to have extra arguments to the resource compiler just like for gir scanner.

**Comment by ignatenkobrain** [comment]
@jpakkane why?
