### ISSUE TITLE
compile_commands.json contains files that aren't really compiled later

### ISSUE THREAD

**Issue by tsdgeos** [mesonbuild/meson#6992]
**Describe the bug**
When compiling mesa with meson under Linux, the generated compile_commands.json file has entries about compiling ../src/glx/apple/apple_cgl.c will create the src/glx/apple/d788b7c@@glxapple@sta/apple_cgl.c.o file.

Once you run ninja, that file is correctly never compiled since this is only for apple systems.

But since the generated compile_commands.json contains that file, if you try to run clang-tidy it all fails because clang-tidy tries to analize that file and it can't because headers is missing because this is not an apple system.

**To Reproduce**
run meson in mesa (sorry this is a bit complicated use case)

**Expected behavior**
The compile_commands.json file should only contain compile commands for the file that will be compiled when running ninja

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
native build
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
ArchLinux
* what Python version are you using e.g. 3.8.0
3.8.2
* what `meson --version`
0.54.0
* what `ninja --version` if it's a Ninja build
1.10.0

**Comment by jpakkane** [comment]
This is strange, because that is exactly what should be happening, given that we use Ninja to generate the compilation commands db. Can you check if the file and its compilation commands are listed in the Ninja file?

**Comment by tsdgeos** [comment]
It indeed seems to be in the ninja file, maybe the thing is that since apple_cgl.c.o is only used to build libglxapple.a and libglxapple.a is not used to build anything, then ninja just doesn't build that apple_cgl.c.o file (nor libglxapple.a).

Meh

So i guess everything is "right" and you can close this bug :/

But i still have no way to know over which files i should run clang-tidy :(

**Comment by jpakkane** [comment]
That should be fairly easy to test. If you do `ninja -v path/to/libglxapple.a`, what happens?

If it fails to build, you might consider filing a bug report upstream.

**Comment by tsdgeos** [comment]
Yes that fails to build.

How would you word that issue?

**Comment by jpakkane** [comment]
I don't know, but I can summon @dcbaker, who should be able to tell.

**Comment by eli-schwartz** [comment]
This doesn't seem to be a meson issue...

(Hopefully it did get reported to mesa in the end?)
