### ISSUE TITLE
fail to install gamemode. help pls!

### ISSUE THREAD

**Issue by Samuka90** [mesonbuild/meson#6997]
hey guys, i am new to Ubuntu. I tried to install gamemode on my Lenovo Laptop to have a better performance while playing games. i followed the instructions on this website: https://www.fosslinux.com/24209/enabling-gamemode-on-linux-for-best-gaming-performance.htm
After Step 6 running ~/gamemode$ ./bootstrap.sh i get this. I  have no idea what i am doing wrong. Please give some advice. Probably its very simple...

+ meson --prefix=/usr build --buildtype debugoptimized -Dwith-systemd-user-unit-dir=/etc/systemd/user
The Meson build system
Version: 0.45.1
Source dir: /home/samu/gamemode
Build dir: /home/samu/gamemode/build
Build type: native build
Project name: gamemode
Native C compiler: cc (gcc 7.5.0 "cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Compiler for C supports argument -Waggregate-return: YES
Compiler for C supports argument -Wunused: YES
Compiler for C supports argument -Warray-bounds: YES
Compiler for C supports argument -Wcast-align: YES
Compiler for C supports argument -Wclobbered: YES
Compiler for C supports argument -Wempty-body: YES
Compiler for C supports argument -Wformat=2: YES
Compiler for C supports argument -Wformat-nonliteral: YES
Compiler for C supports argument -Wformat-signedness: YES
Compiler for C supports argument -Wignored-qualifiers: YES
Compiler for C supports argument -Wimplicit-function-declaration: YES
Compiler for C supports argument -Winit-self: YES
Compiler for C supports argument -Wmissing-format-attribute: YES
Compiler for C supports argument -Wmissing-include-dirs: YES
Compiler for C supports argument -Wmissing-noreturn: YES
Compiler for C supports argument -Wmissing-parameter-type: YES
Compiler for C supports argument -Wnested-externs: YES
Compiler for C supports argument -Wno-discarded-qualifiers: YES
Compiler for C supports argument -Wno-missing-field-initializers: YES
Compiler for C supports argument -Wno-suggest-attribute=format: YES
Compiler for C supports argument -Wno-unused-parameter: YES
Compiler for C supports argument -Wold-style-definition: YES
Compiler for C supports argument -Woverride-init: YES
Compiler for C supports argument -Wpointer-arith: YES
Compiler for C supports argument -Wredundant-decls: YES
Compiler for C supports argument -Wreturn-type: YES
Compiler for C supports argument -Wshadow: YES
Compiler for C supports argument -Wsign-compare: YES
Compiler for C supports argument -Wstrict-aliasing=3: YES
Compiler for C supports argument -Wstrict-prototypes: YES
Compiler for C supports argument -Wstringop-overflow: YES
Compiler for C supports argument -Wstringop-truncation: NO
Compiler for C supports argument -Wtype-limits: YES
Compiler for C supports argument -Wundef: YES
Compiler for C supports argument -Wuninitialized: YES
Compiler for C supports argument -Wunused-but-set-variable: YES
Compiler for C supports argument -Wwrite-strings: YES
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency libsystemd found: YES 237
Native dependency dbus-1 found: YES 1.12.2
Dependency threads found: YES
Library dl found: YES
Checking for function "pidfd_open": NO
Configuring build-config.h using configuration
Submodule 'subprojects/inih' (https://github.com/benhoyt/inih.git) registered for path 'inih'
Cloning into '/home/samu/gamemode/subprojects/inih'...
Submodule path 'inih': checked out '351217124ddb3e3fe2b982248a04c672350bb0af'

Executing subproject inih.

Also couldn't find a fallback subproject in subprojects/inih for the dependency inih 
Reason: Meson version is 0.45.1 but project requires >= 0.46.0.

Dependency inih not found but it is available in a sub-subproject.
To use it in the current project, promote it by going in the project source
root and issuing the following command.

meson wrap promote subprojects/inih

meson.build:160:4: ERROR: Native dependency 'inih' not found

A full log can be found at /home/samu/gamemode/build/meson-logs/meson-log.txt

Thanks for any help.

**Comment by dcbaker** [comment]
Unless you really want to install gamemode from source, all modern versions of ubuntu (and if you're gaming you really want the latest version, not an LTS) are packed already. running:

```console
apt install gamemode
```

should be all you need.

**Comment by DMGPage** [comment]
And what, if I really want to try latest version? I'm stuck with the same error. How can I fix that?

**Comment by DMGPage** [comment]
Ok, I found a solution, if someone else will stuck at this:
sudo add-apt-repository ppa:team-xbmc/ppa
sudo apt-get update
sudo apt-get install meson
./bootstrap.sh

Now "gamemoded -v" should show "gamemode version: v1.5.1".
