### ISSUE TITLE
Unknown CPU family mipsel

### ISSUE THREAD

**Issue by jayanta525** [mesonbuild/meson#6998]
Came over this error while compiling openwrt for mipsel.

environment.py has

 `elif trial in {'mipsel', 'mips64el'}:
trial = trial.rstrip('el')`

But evconfig.py is being used.

**Comment by dcbaker** [comment]
Are you setting 'mipsel' in a cross file, or is this coming from your OS?

**Comment by jayanta525** [comment]
I'm compiling on an x86 system for MIPS little endian.

**Comment by dcbaker** [comment]
This is a difference between meson and other build systems, we don't put the `el` on the end of little endian architectures, the arcitecture is just `mips`, the endianness is set in the separate endian field. for example, here's my ppc64le cross file:

```ini
[binaries]
c = '/home/dylan/.local/cross/ppc64le/bin/powerpc64le-buildroot-linux-gnu-gcc'
cpp = '/home/dylan/.local/cross/ppc64le/bin/powerpc64le-buildroot-linux-gnu-g++'
ar = '/home/dylan/.local/cross/ppc64le/bin/powerpc64le-buildroot-linux-gnu-ar'
strip = '/home/dylan/.local/cross/ppc64le/bin/powerpc64le-buildroot-linux-gnu-strip'
pkgconfig = '/home/dylan/.local/cross/ppc64le/bin/pkg-config'

[host_machine]
system = 'linux'
cpu_family = 'ppc64'
cpu = 'ppc64'
endian = 'little'
```

Note that the cpu and cpu family are just `ppc64`, as they'd be for ppc64 big endian, but the `endian` value is set to little.

We should probably update the docs with this information...
