### ISSUE TITLE
meson: error: unrecognized arguments: --default_library build-shared

### ISSUE THREAD

**Issue by dota17** [mesonbuild/meson#7004]
**Describe the bug**

When I use `default_library` to run like this:

`meson --buildtype ${BUILD_TYPE} --default_library ${LIB_TYPE} . build-${LIB_TYPE}`

it tells me that:
> meson: error: unrecognized arguments: --default_library build-shared

So, I think it should be `default-library`, but not `default_library`

**system parameters**

* what `meson --version`
0.51.1
* what `ninja --version` if it's a Ninja build
1.9.0

**Comment by dcbaker** [comment]
Yes, the argument should be:
```console
meson --default-library shared
```

You can use `meson setup --help` to see all of the builtin options.

**Comment by norihiro** [comment]
I'm reading [HTML document](https://mesonbuild.com/Builtin-options.html) but it is not clearly mentioned. Do you have a plan to update the document?
