### ISSUE TITLE
[RFC] Install-level tags

### ISSUE THREAD

**Issue by lb90** [mesonbuild/meson#7007]
It would be nice if installed files could be tagged in order to support selective installing. For example, installed headers could be tagged with `tags: '#dev'`, installed doc-related files tagged with `tags: '#doc'`, . Then the user could select the install level with `meson install --tags base,i18n`.

Why is that useful?

The use case I'm thinking of here is deployment of applications, where development files are not needed. But that would also be useful for distro packagers to create split packages.

**Comment by eli-schwartz** [comment]
This is something I've pondered would be nice too, but I'd instead suggest letting the "install" kwarg which appears in various places, instead of only being boolean true/false, also be a string, and if it's a string e.g. `install: 'foo'`, then it would be added to a target `install-foo` which is also installed by the toplevel install.

meson install --tags seems like it should be a non-starter, that just forwards to ninja install and meson cannot arbitrarily add a --tags flag to ninja.

**Comment by jpakkane** [comment]
> meson install --tags seems like it should be a non-starter, that just forwards to ninja install 

It's actually the other way around. `ninja install` calls `meson install` with default arguments. That is the same as `ninja test` etc. The default target does the default action, fine tuning is done by calling the Meson command and passing whatever extra args you need.

**Comment by lb90** [comment]
Is it ok if I implement it?

**Comment by jpakkane** [comment]
Thinking out loud some:

- No hashtags, these should be plain strings.
- `tags` is not a very good kwarg name, as it does not specify much, maybe something like `install_groups`?
- There should probably be a way to not install some groups, such as `meson install --no-groups devtools`

**Comment by xclaesse** [comment]
I made a similar proposal there: https://github.com/mesonbuild/meson/issues/7246. It can be seen as a special-case of this tag/group proposal. What I like about special casing a "runtime" group is that for small projects it will often do the right thing by default without having to tag manually every target.

**Comment by dcbaker** [comment]
@xclaesse, that could be made to work by default by making the default install_group/tag/whatever `runtime` for `install_header`, `install_man`, `pkgconfig.generate`, `cmake.generate`, etc, right?

**Comment by eli-schwartz** [comment]
We could go even further and automatically generate targets similar to the ones autotools would classically do.

install-binPROGRAMS
install-binSCRIPTS
install-dist_binSCRIPTS
install-includeHEADERS
install-libLTLIBRARIES
install-nodist_includeHEADERS
install-pkgconfigDATA

Admittedly we can probably choose better names than the ones autotools chose.

**Comment by dankegel** [comment]
I realized today I wanted to have an 'ninja install-tests' target for something, and that meson didn't support that yet.  Glad to hear the feature's being discussed.

I like Eli's original idea of accepting a string for the 'install' kwarg, having
'ninja install' depend on all the 'install-foo' targets, and supporting both
'ninja install-foo' and 'meson install-foo' (or something similar, like meson install [target...]).

**Comment by xclaesse** [comment]
I've taken a quick look at how I would implement this, and I've got a few comments:
- I would go with adding `install_groups` kwarg (array of strings) pretty much everywhere we have `install` and `install_dir` kwargs.
- `meson install` would get `--groups` arguments that take comma separate list of strings.
- Should we have different groups for each subproject? For example to install everything from main project but only runtime from subprojects?
- What about secondary outputs of some targets (e.g. implib, debug, custom_target() with more than one output)?

**Comment by xclaesse** [comment]
I made a PR to add installation tags: https://github.com/mesonbuild/meson/pull/9110. Meson tags installable files with well known tags like `devel`, `runtime`, `doc`, etc... and you can set your own tag with the new `install_tag: 'foo'` keyword argument. To install only files with given tags: `meson install --tags runtime,foo`.

**Comment by lb90** [comment]
That's great!!! Thank you @xclaesse ! 👏
