### ISSUE TITLE
find_program().path() returns a list, not a string

### ISSUE THREAD

**Issue by QuLogic** [mesonbuild/meson#701]
According to the [wiki](https://github.com/mesonbuild/meson/wiki/Reference-manual#external-program-object), the `.path()` method should return a string with the path, but if you print it with `message()`, you get a list. Or try to use it somewhere a string is expected (e.g. add to another string), and it fails because it's really a 1-element list.

**Comment by jpakkane** [comment]
Wiki updated. Thanks.
