### ISSUE TITLE
configure_file assertion failure with format cmake@

### ISSUE THREAD

**Issue by dankegel** [mesonbuild/meson#7011]
Porting a config.h.in expansion from cmake, I tried using configure_file with format: 'cmake@'.
This triggered an assertion failure in meson 0.54.0 (installed via 'pip3 install meson' using python 3.7 on windows 10 or ubuntu 19.10).

  File "c:\python37\lib\site-packages\mesonbuild\mesonlib.py", line 964, in do_c
onf_file
    line, missing = do_replacement(regex, line, variable_format, confdata)
  File "c:\python37\lib\site-packages\mesonbuild\mesonlib.py", line 880, in do_r
eplacement
    assert variable_format == 'meson'
AssertionError

To reproduce: create config.h.cmake.in containing
```
#define FOO "@FOO@"
```
and meson.build containing
```
project('mbug', 'c')
cdata = configuration_data()
configure_file(
  format: 'cmake@',
  input: 'config.h.cmake.in',
  output: 'config.h',
  configuration: cdata)
```

Bonus bug while you're mucking about in there: if config.h.cmake.in contains the single line
```
#cmakedefine BAR 1
```
you get a different and somewhat misleading error, despite that syntax being accepted by cmake.

**Comment by mensinda** [comment]
Both should be fixed in #6917. Closing.
