### ISSUE TITLE
Test suite fails when using GCC 10

### ISSUE THREAD

**Issue by DimStar77** [mesonbuild/meson#7017]
**Describe the bug**
GCC10 is nearing release and various distros are sarting preparation work. Meson's test suite has been identified as a component that is failing when using gcc19

```
[  873s] Running compile:
[  873s] Working directory:  /home/abuild/rpmbuild/BUILD/meson-0.54.0/b 536484cc32/meson-private/tmpsv_1caih
[  873s] Command line:  gfortran /home/abuild/rpmbuild/BUILD/meson-0.54.0/b 536484cc32/meson-private/tmpsv_1caih/testfile.f90 -pipe -cpp -E -P -D_FILE_OFFSET_BITS=64 -cpp -P -O0 
[  873s] 
[  873s] Code:
[  873s]  
[  873s]         #ifdef __has_include
[  873s]          #if !__has_include("omp.h")
[  873s]           #error "Header 'omp.h' could not be found"
[  873s]          #endif
[  873s]         #else
[  873s]          #include <omp.h>
[  873s]         #endif
[  873s] Compiler stdout:
[  873s]  
[  873s] 
[  873s] 
[  873s]         #ifdef 0
[  873s]          #if !0("omp.h")
[  873s]           #error "Header 'omp.h' could not be found"
[  873s]          #endif
[  873s]         #else
[  873s]          #include <omp.h>
[  873s]         #endif
[  873s] 
[  873s] Compiler stderr:
[  873s]  /home/abuild/rpmbuild/BUILD/meson-0.54.0/b 536484cc32/meson-private/tmpsv_1caih/testfile.f90:2:0:
[  873s] 
[  873s]     2 |         #ifdef __has_include
[  873s]       | 
[  873s] Error: "__has_include" used outside of preprocessing directive
[  873s] /home/abuild/rpmbuild/BUILD/meson-0.54.0/b 536484cc32/meson-private/tmpsv_1caih/testfile.f90:2:0: Error: missing '(' before "__has_include" operand
[  873s] /home/abuild/rpmbuild/BUILD/meson-0.54.0/b 536484cc32/meson-private/tmpsv_1caih/testfile.f90:2:0: Error: operator "__has_include" requires a header-name
[  873s] /home/abuild/rpmbuild/BUILD/meson-0.54.0/b 536484cc32/meson-private/tmpsv_1caih/testfile.f90:3:0:
[  873s] 
[  873s]     3 |          #if !__has_include("omp.h")
[  873s]       | 
[  873s] Error: "__has_include" used outside of preprocessing directive
[  873s] /home/abuild/rpmbuild/BUILD/meson-0.54.0/b 536484cc32/meson-private/tmpsv_1caih/testfile.f90:3:0: Error: missing '(' before "__has_include" operand
[  873s] /home/abuild/rpmbuild/BUILD/meson-0.54.0/b 536484cc32/meson-private/tmpsv_1caih/testfile.f90:3:0: Error: operator "__has_include" requires a header-name
[  873s] 
```

**Expected behavior**
A passing test suite - irrespective of the use of gcc100

**system parameters**
* Tested on openSUSE Tumbleweed Staging (i.e. 'packages to integrate into future openSUSE Tumbleweed snapshots); the only change is the switch from gcc9.3.1 to gcc 10

Always latest build log available at: https://build.opensuse.org/build/openSUSE:Factory:Staging:N/standard/x86_64/meson:test/_log

**Comment by lazka** [comment]
The MSYS2 jobs in CI show this error now since the update to GCC 10.

**Comment by lazka** [comment]
since it affects fortran @scivision do you have any idea what's wrong here?

**Comment by scivision** [comment]
The code put in testfile.f90 isn't a full test if OpenMP is truly linkable. GCC 10 and in particular Gfortran 10 got a lot stricter about invalid code, and this appears ripe for updating anyway.

A Fortran-specific stanza for detecting if OpenMP is available and linkable is:

```fortran
use omp_lib  ! tests that OpenMP is included
implicit none
!$ integer :: N  ! OpenMP reads lines starting like this
N = omp_get_num_threads() ! tests that OpenMP is linked
```

if you don't want to test that OpenMP is linkable, a test more akin to the original Meson code here is the Fortran stanza

```fortran
use omp_lib
```

**Comment by scivision** [comment]
If this is suitable, one would slightly modify the Meson code to slip this stanza in if the language is Fortran. I can do this if others agree.

**Comment by lazka** [comment]
From what I see this is just the output of the generic has_header, maybe called from https://github.com/mesonbuild/meson/blob/402f7afdb03fa59b28e1c01b490b9673382f1ba4/mesonbuild/dependencies/misc.py#L98 so not easy to replace.

**Comment by nirbheek** [comment]
The main bug to solve is that `compiler.has_header()` does not work if `compiler` is gfortran >= 10.

**Comment by nirbheek** [comment]
https://github.com/mesonbuild/meson/pull/7136 fixes it.
