### ISSUE TITLE
Confusion about the meaning of the -L parameter with D compilers

### ISSUE THREAD

**Issue by ximion** [mesonbuild/meson#702]
Hi!
The dmd and ldc D compilers define the `-L` flag as "pass the next command to the linker", while gdc/gcc define it as "set linker search path".

So I thought I was smart when translating a passed-in `-L` to a ldc/dmd compiler to `-L-L`, since this will make it work expected from a gcc compiler (= `-L` always sets the linker search path).
Unfortunately it now turns out that many people use the `-L` flag as "pass to linker" and even use it in existing pkg-config files, which makes it really hard to change

So, I wonder whether I should do some black magic to detect this in the DCompiler classes, or whether we could somehow utilize `get_linker_search_args()` to set linker search paths in a way all compilers understand, and make the to_native argument translation simply not-deal with an already existing `-L` flag (= have the compiler interpret it as it sees fit).

Possible uses for `-L` for setting the linker search path is to search for local, precompiled shared or static libraries, e.g. `-Lpath/to/libraries -lfoo` (to find a `libfoo.a` or `libfoo.so` file which doesn't exist system-wide). For using `-L` directly, people use it to e.g. pass linker arguments to a compiler if they expect the compiler to be LDC/DMD. E.g. `-L-lfoo` to link against libfoo.

I would prefer to just leave the `-L` flag alone in meson and utilize the `get_linker_search_args` command somehow to allow for a compiler-agnostic way to set linker search paths.

**Comment by jpakkane** [comment]
Do people use pkg-config files for D currently? Do they actually work? It would seem that you can only make it work on GDC or LDC...

**Comment by ximion** [comment]
Yes and yes. But they can work with both systems easily, if people would just use one kind of flag... (the one without `-L` prefix).
But ideally, I would like to get rid of this special-casing alltogether..

**Comment by jpakkane** [comment]
Okay so what are the current sources for -L arguments?

 - pkg-config?
 - link_args : ['-Lfoofoo']?
 - something we ourselves generate (what)?
 - others?

**Comment by ximion** [comment]
AFAIK only the first two, pkg-config and manual, explicitly set arguments.

**Comment by jpakkane** [comment]
In that case the thing to do is to just pass them on directly. There is no way to reliably know what the user meant. They just have to do something like this

    link_flags = dc.get_id() == 'gdc' ? ['-gdc_arg'] : ['-ldc_or_dmd_arg']

Or equivalent thereof.
