### ISSUE TITLE
Better error message for test()

### ISSUE THREAD

**Issue by fryeb** [mesonbuild/meson#7029]
Hi, 
I'm fairly new to meson, and while adding tests to my project I ran into the following error message:
```
..\tests\meson.build:2:0: ERROR: Incorrect number of arguments
```
After a bit of research I was able to narrow down the issue: `test` expects two arguments, not one. I might've solved the issue sooner had the error message read something like:
```
..\tests\meson.build:2:0 ERROR: test() expects 2 arguments but only 1 was given.
```
Admittedly this is a small issue, but I imagine it shouldn't be hard to fix and could help new users a fair bit.

**Comment by xclaesse** [comment]
PR welcome :-)
