### ISSUE TITLE
Could you give a guide to how to build the meson from the last codes?

### ISSUE THREAD

**Issue by zeerd** [mesonbuild/meson#7039]
Hello!

Hope you can add those guid into the README.md. 

I need some newest changes of the codes that I could find on the github, but the version from pip3 is 0.53.2.

[You said](https://mesonbuild.com/Getting-meson.html) :

```
Meson releases can be downloaded from the GitHub release page, and you can run ./meson.py from inside a release or the git repository itself without doing anything special.
```

But:

```bash
~/meson-0.54.0$ ./meson.py

ERROR: Must specify at least one directory name.
~/meson-0.54.0$ ./meson.py build

ERROR: Neither directory contains a build file meson.build.

```

**Comment by eli-schwartz** [comment]
The `meson.py` program you tried running behaved exactly the way meson installed from pip would.

But you ran meson.py from within the mesonbuild clone, not the project you wanted to build.

`./meson.py --help` works

`./meson.py ../myotherproject/ ../myotherproject/builddir/` works

```
cd ../myotherproject/
../meson/meson.py builddir/
```

also works.

I'm not sure why this is confusing?

You can also use pip to install from a github repo, or from a local directory -- not just from releases. See the pip documentation! https://pip.pypa.io/en/stable/reference/pip_install/#pip-install

**Comment by zeerd** [comment]
Thank you for your reply.

I got the point, now.

The clone of the meson build is the meson it-self. I don't need to install it into the system to replace the one installed from pip3.

Sorry, I am not a python developer. In my mind, a software need to be installed into the system to work. Just like make && sudo make install , then use it.

That 's the confusing.

**Comment by eli-schwartz** [comment]
Sure, I'm just saying that it told you you could use meson.py as your meson command :) so just use it.

Pip installation instructions are admittedly something you might not understand if you haven't used it before, but that's just an alternative install method I personally think is useful. And hence the direction to its documentation.

**Comment by zeerd** [comment]
Thansk again. At least I know how to use this now. :)

To the developer of meson:

I am not a English speaker , so I won't pull a request for this. But hope you can re-write the sentence I quoted at the topic, to let the reader know, the user need to run meson.py from the folder of the project which he/she want to build , but not the folder of the mesonbuild.

**Comment by michaelbadcrumble** [comment]
Hello @zeerd.

I'm not sure if this issue is active but I think this [page](https://github.com/michaelbadcrumble/mesonbuild_tips/blob/master/notebook/01-getting_started/01-getting_setup.md) would be helpful.

**Comment by zeerd** [comment]
this page give a way to install from pip,but not the last code from github.

**Comment by michaelbadcrumble** [comment]
Hey @zeerd sorry may have misunderstood the issue but now there is a section dedicated to using git to clone and get the latest version of Meson build system from GitHub.

**Comment by eli-schwartz** [comment]
The current https://mesonbuild.com/Getting-meson.html#installing-meson-with-pip mentions using pip install on the cloned meson sources.

**Comment by jianhe-fun** [comment]
> Hello @zeerd.
> 
> I'm not sure if this issue is active but I think this [page](https://github.com/michaelbadcrumble/mesonbuild_tips/blob/master/notebook/01-getting_started/01-getting_setup.md) would be helpful.

link invalid at the moment.
