### ISSUE TITLE
Need a way to have the path as string of a generated build target

### ISSUE THREAD

**Issue by taz-007** [mesonbuild/meson#704]
I would like to know the path of a built target (a shared_library for example) to use it as argument to a test program. (I do _not_ want to link the test program with the library)
I've tried this :  test(p.get(0), exe, args: p.get(2))
with p.get(0) : the name of the test,
exe : the executable for the test,
myshared_library : a shared_library() object
p.get(2) the [myshared_library] or directly myshared_library
but neither work as the args parameter is expecting a string (exact error is : "Command line arguments must be strings").
Maybe a new method "get_path" for the object type "build target" ?

**Comment by nirbheek** [comment]
You can actually do this by using a `custom_target` or `run_target`. The command list for those accepts all `build_target`s including `shared_library`. Your command will get the full path to the library in `argv`.
