### ISSUE TITLE
CLikeCompiler.run() ignores 'needs_exe_wrapper' property

### ISSUE THREAD

**Issue by floppym** [mesonbuild/meson#7041]
**Describe the bug**

When building a project using a cross file with `needs_exe_wrapper = false`, meson emits an error like this:
```
../glib-2.64.2/meson.build:865:4: ERROR: Can not run test applications in this cross environment.
```

**To Reproduce**

Attempt to configure glib with a cross file containing `needs_exe_wrapper = false`.

Here is the cross file I used.

[i686.txt](https://github.com/mesonbuild/meson/files/4536788/i686.txt)

**Expected behavior**

meson setup should succeed. This worked fine with meson 0.53.1.

**system parameters**

* Technically a cross-compile (i686 on an x86_64 machine), though the resulting binaries can be executed natively without emulation.
* Gentoo Linux
* Python 3.8.2
* meson 0.54.0 or 0.54.1
* ninja 1.10.0

Downstream bug report: https://bugs.gentoo.org/719382

**Comment by nirbheek** [comment]
Fixed with https://github.com/mesonbuild/meson/pull/6933.
