### ISSUE TITLE
Can't build projects dynamically linked to boost.log

### ISSUE THREAD

**Issue by scontini76** [mesonbuild/meson#7046]
Since this change:

https://github.com/mesonbuild/meson/blob/7c68fe80083fd72a100998578417b223e3704af5/mesonbuild/dependencies/boost.py#L791

I can't compile anymore some applications dynamically linked to boost.log:

```
/usr/include/boost169/boost/log/detail/config.hpp:225: error: "BOOST_LOG_DLL" redefined [-Werror]
 #       define BOOST_LOG_DLL

<command-line>: note: this is the location of the previous definition
```

I think that `-DBOOST_LOG_DLL` should not specified (see https://www.boost.org/doc/libs/1_72_0/libs/log/doc/html/log/rationale/namespace_mangling.html) but only `-DBOOST_LOG_DYN_LINK=1`

Tested with boost from 1.69 to 1.72 on CentOS and MacOS.

If you confirm that `-DBOOST_LOG_DLL` can be removed I can provide a PR, just let me know .

**Comment by mensinda** [comment]
Since this is only a warning, you should still be able to build the projects if you disable `werror` in meson (which is admittedly not ideal) until the next release.

But I can confirm that this is a meson issue, since this define is not specified in the `usage-requirements`: https://github.com/boostorg/log/blob/develop/build/Jamfile.v2#L493

**Comment by scontini76** [comment]
Hi @mensinda,

I know, but you guessed that it is not ideal indeed (my development policy is to have zero warning/errors, and I cannot silent selectively only this kind of error on some compiler).

So I'm not going to wait for the next release (even because there are other issues with the 0.54.0 solved on the master). I'm going to fix the thing for me and use the fork. If you agree with my change (since we agree on the solution), I'll be very happy to open the PR, it's just a little removal, isn't? 

Thank you for your answer!

**Comment by mensinda** [comment]
Yes and no. The code in question was automatically generated by [boost_names.py](https://github.com/mesonbuild/meson/blob/master/tools/boost_names.py), so I would rather fix this properly by fixing the code generator. If removing it in your fork works better for you than disabling `werror` go for it.

So, in short, I won't accept a PR that just removes `-DBOOST_LOG_DLL`. That being said, I am looking into the underlying issue right now.

**Comment by scontini76** [comment]
Sorry, I didn't realize there was a code generator here! No hurry, in the meanwhile I'll manage in some way!

**Comment by mensinda** [comment]
For reference, here is the fix with the code generator: #7047

Let's hope that this doesn't break anything else :)

**Comment by scontini76** [comment]
Great job! Don't worry I'm going to test it soon! ;)

**Comment by scontini76** [comment]
Your branch seems fine to me! Thank you!
