### ISSUE TITLE
boost dependency fails for werror=true, no longer uses -isystem (after v 0.54.0)

### ISSUE THREAD

**Issue by itldo** [mesonbuild/meson#7053]
**Describe the bug**
Starting with v 0.54, the  boost dependency no longer references include paths with -isystem
to prevent compiler warnings from failing a -Werror build.

The following functionality was dropped in v 0.54.0:

```
    def get_compile_args(self):
        args = []
        include_dir = self.incdir

        # Use "-isystem" when including boost headers instead of "-I"
        # to avoid compiler warnings/failures when "-Werror" is used

        # Careful not to use "-isystem" on default include dirs as it
        # breaks some of the headers for certain gcc versions

        # For example, doing g++ -isystem /usr/include on a simple
        # "int main()" source results in the error:
        # "/usr/include/c++/6.3.1/cstdlib:75:25: fatal error: stdlib.h: No such file or directory"

        # See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70129
        # and http://stackoverflow.com/questions/37218953/isystem-on-a-system-include-directory-causes-errors
        # for more details

        if include_dir and include_dir not in self.clib_compiler.get_default_include_dirs():
            args.append("".join(self.clib_compiler.get_include_args(include_dir, True)))
        return args
```

**To Reproduce**

* Use BOOST_INCLUDEDIR and BOOST_LIBRARYDIR to refer to a Boost installation outside 
of the system include dirs.
* Use boost::format to trigger compiler warnings.
* Specify werror=true as a project option.

```
$ cat meson.build
project('systeminc', 'cpp',
  default_options : ['warning_level=3',
                     'werror=true',
                     'cpp_std=c++11'])

boost_dep = dependency('boost')

exe = executable(
  'systeminc', 'systeminc.cpp',
  dependencies: [boost_dep],
  install : true)

$ cat systeminc.cpp
#include <iostream>

#include "boost/format.hpp"

int main(int argc, char **argv) {
    std::cout << boost::format("hello\n");
    return 0;
}
```

**Expected behavior**

Boost include directory command line options should start with -isystem instead of -I

**system parameters**

$ g++ --version
g++ (Debian 4.7.2-5) 4.7.2
$ python --version
Python 2.7.17 :: Anaconda, Inc.
$ uname -a
Linux osslab01 3.2.0-4-amd64 #1 SMP Debian 3.2.54-2 x86_64 GNU/Linux
$ ninja --version
1.8.2
$ meson --version
0.54.1

**Comment by mensinda** [comment]
You should be able to toggle `-isystem` with `include_type: 'system'` (see [the dependency doc](https://mesonbuild.com/Reference-manual.html#dependency)).

**Comment by itldo** [comment]
That works for me, I'm happy to close this. 
Thanks for the quick response.

A few observations:

* I tried to break this by mixing a boost dependency defined without 'system' (inherited indirectly from a subproject dependency) with a boost dependency defined with 'system' to see which would "win". Both the `-I` and `-isystem` arguments appeared on the compile command but, at least with gcc, the `-isystem` took precedence and  warnings were ignored.

* `dependency(include_type: 'system', fallback: [...])` does not appear to be applied to include_directories(direct or indirect)  on a returned `fallback` object.  For example, suppose you add a subproject 'a' that brings along a boost dependency not marked with `system`. And then through your use, you trigger a warning deep in the bowels of the boost.
You can't correct this by pulling 'a' in with `include_type: system`. Instead, the author of 'a' needs to declare their dependency on boost with `system`. Or you can declare your own redundant direct dependency on boost with `system` and, as mentioned above, `-isystem` will win.

* I suspect using `include_type: 'system'` will be standard practice with the boost dependency.

Thank you again for meson.

-tim

**Comment by mensinda** [comment]
Maybe adding a new meson option (although we do our best to keep the number of options low) to control the default dependency `include_type` could also work. This would automatically benefit all dependencies and might be necessary to build old subprojects with `werror` in the future.

I am personally against adding `-isystem` to any dependency directly since it is fragile (see the removed code from your first comment) and having everything in one place helps a lot in this regard.
