### ISSUE TITLE
header-only boost dependencies conflict with static boost dependencies

### ISSUE THREAD

**Issue by itldo** [mesonbuild/meson#7056]
**Describe the bug**
Starting with v 0.54.0:
Using a header-only boost dependency in combination with a static boost dependency results in
 conflicting BOOST_XXX_DYN_LINK and BOOST_XXX_STATIC_LINK preprocessor defines.

For example:
`error: #error Must not define both BOOST_SYSTEM_DYN_LINK and BOOST_SYSTEM_STATIC_LINK 
`
The boost dependencies might come from different, unrelated subprojects.
The header-only dependency introduces the *DYN_LINK, despite (I'm assuming here)
that header-only dependencies should be dynamic or static neutral.

**To Reproduce**

Introduce a header-only boost dependency and a static boost dependency in the same project,
possibly, but not necessarily, coming from different subprojects.

`$ cat meson.build
project('static_headonly', 'cpp',
  default_options : ['warning_level=3',
                     'cpp_std=c++11'])

boost_headers_dep = dependency('boost')

boost_fs_dep = dependency('boost', modules: ['filesystem', 'system'], static: true)

exe = executable(
  'static_headonly', 'static_headonly.cpp',
  dependencies: [boost_headers_dep, boost_fs_dep],
  install : true)

$ cat static_headonly.cpp
#include <iostream>
#include <iterator>

#include "boost/filesystem.hpp"

int main() {

    std::cout << "directory entries: "
        << std::distance(boost::filesystem::directory_iterator("."),
                boost::filesystem::directory_iterator())
        << "\n";
}
`

`error: #error Must not define both BOOST_SYSTEM_DYN_LINK and BOOST_SYSTEM_STATIC_LINK 
`

**Expected behavior**

The build should succeed.

I would expect a header-only dependency to not define a
*DYN_LINK preprocessor name. 

**system parameters**

$ g++ --version
g++ (Debian 4.7.2-5) 4.7.2
$ python --version
Python 2.7.17 :: Anaconda, Inc.
$ uname -a
Linux osslab01 3.2.0-4-amd64 #1 SMP Debian 3.2.54-2 x86_64 GNU/Linux
$ ninja --version
1.8.2
$ meson --version
0.54.1

**Comment by mensinda** [comment]
Should be fixed with #7069.
