### ISSUE TITLE
boost dependency static libs require static: true (instead of missing) even when dynamic libs are absent

### ISSUE THREAD

**Issue by itldo** [mesonbuild/meson#7057]
**Describe the bug**
I have a Boost instance that contains only static libraries.
Until v 0.54.0, the boost dependency would find them without requiring me to specify `static: true`.

**To Reproduce**

Call a boost dependency for a module against a Boost installation without dynamic libraries.
Don't use the `static` keyword.

The dependency will fail to locate the static library.

**Expected behavior**
As long as I don't specify a static keyword, the boost dependency should first search for dynamic 
libraries, and then search for static libraries. If I don't care whether I match static or dynamic,
I should be able to pick up static libraries if dynamic libs don't exist.

If this expected behavior is wrong, then update the dependency documentation to describe the default behavior and rationale for when a dependency static keyword is missing.

**system parameters**
v 0.54.0, 0.54.1

Thanks!

**Comment by mensinda** [comment]
Should be fixed with #7108. Could you please check?
