### ISSUE TITLE
[DPDK][meosn >= 0.54.0] meson doesn't find libs pointed by PKG_CONFIG_PATH in a cross build

### ISSUE THREAD

**Issue by alialnu** [mesonbuild/meson#7062]
**Description**
Meson does not set `PKG_CONFIG_PATH` internally and so it fails to find libraries pointed by the env variable in a cross build.

The cause is [Revert "Naturally use env vars a bit more to match Autoconf" ](https://github.com/mesonbuild/meson/commit/7924e5f).

**To Reproduce for DPDK**
```
git clone git://dpdk.org/dpdk; cd dpdk
export PKG_CONFIG_PATH=/path/to/lib/pkgconfig
meson --werror --cross-file config/arm/arm64_armv8_linux_gcc build
```

Contents of `config/arm/arm64_armv8_linux_gcc`:
```
[binaries]
c = 'aarch64-linux-gnu-gcc'
cpp = 'aarch64-linux-gnu-cpp'
ar = 'aarch64-linux-gnu-gcc-ar'
strip = 'aarch64-linux-gnu-strip'
pkgconfig = 'aarch64-linux-gnu-pkg-config'
pcap-config = ''

[host_machine]
system = 'linux'
cpu_family = 'aarch64'
cpu = 'armv8-a'
endian = 'little'
...
```

Meson calls `/usr/bin/aarch64-linux-gnu-pkg-config --modversion lib` to find the lib but it doesn't because it sees `PKG_CONFIG_PATH` as empty.

I noticed that meson warns about a bunch of unset env variables. Is this expected? Do I need to rename the variable names under `[binaries]` in my cross file?:
```
None of 'PKG_CONFIG_PATH_FOR_BUILD' are defined in the environment, not changing global flags.
None of  are defined in the environment, not changing global flags.
Project name: DPDK
Project version: 20.05.0-rc1
None of 'CC_FOR_BUILD' are defined in the environment, not changing global flags.
None of 'CFLAGS_FOR_BUILD' are defined in the environment, not changing global flags.
None of 'LDFLAGS_FOR_BUILD' are defined in the environment, not changing global flags.
None of 'CPPFLAGS_FOR_BUILD' are defined in the environment, not changing global flags.
None of 'CC_LD_FOR_BUILD' are defined in the environment, not changing global flags.
```
I tried setting the env variable `PKG_CONFIG_PATH_FOR_BUILD`, but it produced the same issue.

**Expected behavior**
Meson is expected to find the libs, but it no longer does.

**System parameters**
* Is this a cross build: Yes
* Operating system: 18.04.4 LTS
* Python version: 3.6.9
* Meson version: 0.54.1

**EDIT**
With `-Dpkg_config_path`, the build works as expected.

**Comment by dcbaker** [comment]
I can verify this (after noticing that gentoo's wrappers unset PKG_CONFIG_PATH in cross situations, and expect CROSS_PKG_CONFIG_PATH to be set...)

**Comment by alialnu** [comment]
Thanks @dcbaker @jpakkane
