### ISSUE TITLE
Wish: add ability to patch wrap-git subprojects

### ISSUE THREAD

**Issue by denizzzka** [mesonbuild/meson#7063]
Currently only wrap-file supports patching. Why not to add ability to patch other wrap types?
I faced with git repositories what does not maintain its HTTP archieves.

**Comment by xclaesse** [comment]
I did a PR 2 years ago for that: https://github.com/mesonbuild/meson/pull/4382.

**Comment by phillipjohnston** [comment]
I would love this. Sad to see it languish so long :(

**Comment by phillipjohnston** [comment]
Excited to see the PR merged!

**Comment by denizzzka** [comment]
tested, works
