### ISSUE TITLE
How do you specify that the static library should be loaded rather than the shared?

### ISSUE THREAD

**Issue by Jkmcameron** [mesonbuild/meson#7066]
I have a subproject that I load with a `wrap-git`. In my `meson.build` I load the subproject as a dependency with `glfw = subproject('glfw').get_variable('glfw_dep')`. This works because the `meson.build` supplied by the git repo defines:

```
glfw_library = library('glfw',
                       sources,
                       version: meson.project_version(),
                       c_args: ['-D_GLFW_USE_CONFIG_H'],
                       dependencies: dependencies,
                       include_directories: [include_directories('../include'),
                                             include_directories('.')])
glfw_dep = declare_dependency(link_with: glfw_library,
                              include_directories:
                                    [include_directories('../include'),
                                     include_directories('.')])
```

Issue is, when the project is built the subproject builds both static and shared libraries (due to the git author using the `library` function rather than `static_library` or `shared_library`), and for whatever reason the shared library is automatically linked against by meson rather than the static library. I want to link against the static library. As it stands I don't see a way to tell meson to load the static version rather than the shared version, and the only solution I've found is to edit the subproject's `meson.build` and replace `library` with `static_library` which isn't ideal

**Comment by dcbaker** [comment]
this is a known issue of both libraries. I think there's work going into 0.55 to specify this in the subproject() call. @xclaesse has been working on that.

**Comment by xclaesse** [comment]
With meson 0.54 you can pass `default_options:  ['defauly_library=static']` to subprojects()

**Comment by Jkmcameron** [comment]
> With meson 0.54 you can pass `default_options: ['defauly_library=static']` to subprojects()

Am I doing this correctly? I tried `glfw = subproject('glfw', default_options: ['defauly_library=static']).get_variable('glfw_dep')` but it didn't work, my executable is still searching for the shared library at runtime

**Comment by xclaesse** [comment]
Cool, wrote on my phone :package:
