### ISSUE TITLE
How to create a subfolder in the build folder via `run_command`?

### ISSUE THREAD

**Issue by Jkmcameron** [mesonbuild/meson#7067]
I have the following block in my `meson.build` that compiles glsl shaders into spir-v compiled shaders:
```
shaders = [

	'triangle.vert',
	'triangle.frag'
]

foreach shader : shaders
	run_command('glslangvalidator', '-V', join_paths(meson.current_source_dir(), 'src', 'main', 'resource', 'shaders', shader) + '.glsl', '-o', join_paths(meson.current_build_dir(), 'shaders', shader + '.spv'))
endforeach
```

This command only works if the "shaders" folder in the build directory already exists because `glslangvalidator.exe` apparently doesn't know how to create folders. I tried using `run_command` to call "mkdir" on Windows but that throws the error "..\..\meson.build:24:0: ERROR: Program or command 'mkdir' not found or not executable". Not sure why. 

Is there an already existing means of creating a generic folder/directory in meson?

**Comment by gregsskyles** [comment]
Probably because `mkdir` is a directive or 'internal command' of `cmd.exe` and `run_command` instantiates a separate process, requiring a standalone .exe to install in said process. Not knowing too much about `run_command` I'd guess that if you passed it something like `"cmd.exe -c \"mkdir C:\\blah\\blah\\foobar\""` it would work. (By 'something like' I mean I have no idea how `run_command` actually expects you to protect back-slash and quote characters.)

**Comment by Jkmcameron** [comment]
Internet says that "cmd \C <command>" spawns a new command line instance, runs the specified commands in that instance, and closes that instance. I've tried this ut it doesn't do anything. From my log:

```
Running command: C:\Windows\system32\cmd.EXE \C mkdir "C:/Users/jkmca/Workspace/Adventum/build/default/shaders"
--- stdout ---
Microsoft Windows [Version 10.0.18363.592]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\jkmca\Workspace\Adventum>
```

It spawns the new instance but doesn't do anything. It just ignores the command.

**Comment by jpakkane** [comment]
If you need to do anything more complex than calling one program, the recommended way is to write your logic in a Python script instead. It is the only reliable way, especially if you to support multiple platforms.

**Comment by gregsskyles** [comment]
I think you have your slashes reversed; the c option needs a forward slash, and the path you are trying to create needs back slashes.

```
C:\Users\GregSkyles>C:\Windows\system32\cmd.EXE \C mkdir "C:/Users/jkmca/Workspace/Adventum/build/default/shaders"
Microsoft Windows [Version 10.0.19041.208]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\GregSkyles>C:\Windows\system32\cmd.EXE /C mkdir "C:\Users\jkmca\Workspace\Adventum\build\default\shaders"
The directory or file cannot be created.

C:\Users\GregSkyles>
```

**Comment by Jkmcameron** [comment]
I eventually figured out that first slash was reversed, as for the slashes in the file path, that path is what `current_build_dir()` spit out so I don't have an easy way of swapping thise. Even still, running that coomand from the command line works but doesn't work when passed through `run_command`, I eventually gave up on that approach anyways and did what was suggested [here](https://github.com/mesonbuild/meson/issues/7071#issuecomment-622599482)

**Comment by gregsskyles** [comment]
Got it; as I said before, I wasn't too sure about what `run_command` does in the middle. I'd definitely follow Dylan's advice, though.

**Comment by eli-schwartz** [comment]
Question has been answered, closing.

P.S. I advise using a custom_target not a run_command since that will create a proper rule, that updates when your source shader is updated.

**Comment by nh2** [comment]
I made the dir like this:

```meson
my_dir = custom_target( # this is a plain `mkdir`
  'my_dir',
  output: 'my-dir',
  command: ['mkdir', '-p', '@OUTPUT@'],
  install: false,
)
```

One can then get e.g. the full path to it using [`my_dir.full_path()`](https://mesonbuild.com/Reference-manual_returned_custom_tgt.html#custom_tgtfull_path).
