### ISSUE TITLE
Rethink test targets

### ISSUE THREAD

**Issue by jpakkane** [mesonbuild/meson#708]
There are many different ways of running unit tests:
- all vs all-except-subproject vs just one suite vs just one test
- repeat 1, 10 or infinite times
- run under Valgrind or not
- run under GDB or not
- run under some unknown test runner binary (Valgrind clones etc)

The problem is that this requires a top level Ninja target for each possible combination of options. This is unfeasible. Something better and usable needs to be available. IDEs and the like can do these themselves with introspection data but perhaps they should be available directly on the cli as well.

One potential solution is to have just `ninja test` (and possibly `ninja test-with-subprojects`) and in addition provide a `mesontestrunner` script that allows parametrizing tests with command lines like this:

```
mesontestrunner --valgrind --repeat=10 test_32
mesontestrunner --repeat=inf --gdb test_case_101
mesontestrunner --wrapper=valgrind_clone --suite=somesuite
```

And so on.

**Comment by nirbheek** [comment]
This is already fixed with the implementation of `mesontest`.
