### ISSUE TITLE
Should meson specifiy -release for DLang projects with the `plain` buildtype?

### ISSUE THREAD

**Issue by Cogitri** [mesonbuild/meson#7082]
Right now meson doesn't specify `-release` on the compiler command line when compiling with the `plain` buildtype. This is problematic, since the `-release` flag doesn't do unwanted optimizations distros want to avoid, it disables asserts, quoting the LDC docs: `-release | Disables asserts, invariants, contracts and boundscheck` [0]. Since distros usually use the `plain` buildtype, but don't want debug asserts, contracts (input validation for functions, also via asserts) etc. in their binaries it'd make sense to specify `-release` even with the `plain` buildtype IMHO.

**Comment by dcbaker** [comment]
It sounds like `-release` should be tied t the badly named `b_ndebug` flag then.

**Comment by Cogitri** [comment]
Ah yes, that's probably the right course of action.
