### ISSUE TITLE
What is the process for adding new programming languages?

### ISSUE THREAD

**Issue by michaelbrockus** [mesonbuild/meson#7087]
I’m wondering what the process is for adding new programming languages to Meson build system, I happen to have some in mined.

The following are `scala`, `kotlin`, `julia`, and `go`.

**Comment by dcbaker** [comment]
You need to create a compiler (and possibly linker, though I don't think so for those languages) representation, which means wiring up the various methods (has_header, has_argument, etc), you need to write tests for those features.

For JVM languages you can look at the java representation and go from there. There are some holes in our java support.

Unless something has changed recently, Julia only supports JIT, right?

**Comment by michaelbadcrumble** [comment]
Will @dcbaker unfortunately `julia` has not changed. So I will focus on the JVM languages and go.

What holes does Meson have in Java support?

**Comment by michaelbadcrumble** [comment]
Is anyone working on that?

**Comment by jpakkane** [comment]
There is no JNI support, for example. JDK does not ship a .pc file and looking up the C API dependency bits is nasty to do portably.

**Comment by michaelbadcrumble** [comment]
Is someone working on JNI support?

Would it affect the new JVM languages support?
