### ISSUE TITLE
Run meson build  failed（dependency  sdbusplus not found）

### ISSUE THREAD

**Issue by zzhuang-cancon** [mesonbuild/meson#7092]
Hi,eveyone:
  When i am running the command: meson build i get this error message:
Run-time dependency sdbusplus found: NO (tried pkgconfig and cmake)
meson.build:45:0: ERROR: Dependency "sdbusplus" not found, tried pkgconfig and cmake

![image](https://user-images.githubusercontent.com/56622764/81275580-77e80a80-9084-11ea-88b1-f8ab9c1860ce.png)
  I am doing this test:  OpenBMC Hello World in SDK 
 following the guidence : https://github.com/openbmc/docs/blob/master/development/sdk-hello-world.md  
follow is the details:
**system parameters**
* operating system ( Ubuntu 18.04.)
* Python version 2.7.17
* `meson --version` 0.54.0
* `ninja --version` 1.8.2
![image](https://user-images.githubusercontent.com/56622764/81276536-bb8f4400-9085-11ea-9781-cdadbd4f9509.png)
Could i get some suggestions?

**Comment by dcbaker** [comment]
You're missing a dependency, sdbusplus in this case. you may be able to install it with `apt install sdbusplus-dev` (not sure, I don't use ubuntu). or you may need to build it from source (it appears to be another openbmc project).

**Comment by zzhuang-cancon** [comment]
Yeah！ you are right,  i change my system default python version , from 2.7 to 3.5 , and then it causes many errors, and then, i get the sdbusplus source code package, and do follow steps:
   cmd:
               ./bootstrap.sh
              ./configure
In fact, i even do not konw what these cmds means, i do it and it works. 
after the above operations, i get other points, it tells me that i miss dependency, it can not found ‘_sqlite3’ and  load curses python module.
then i do operations like these:
（1）sudo apt-get install  libsqlite3-dev
  (2)   sudo apt-get install libncurses5-dev 
  (3) in the end  i need to reinstall python.

**Comment by eli-schwartz** [comment]
User environment  based issue, sounds like it was solved?
