### ISSUE TITLE
disabler() objects convert arrays into non-arrays

### ISSUE THREAD

**Issue by keszybz** [mesonbuild/meson#7107]
When an array is used to contain a bunch of built objects, e.g. executable()s , if any of those objects becomes a disabler() object, the array stops being an array, and syntactic breakage occurs.

For example:
```python
project('list-of-disablers', 'c',
        version : '2.35-rc2',
        license : 'GPLv2+')
exes = []

exes += executable(
  'foo',
  'foo.c')

exes += executable(
  'foo2',
  'foo.c',
  dependencies : disabler())

exes += executable(       #here
  'foo3',
  'foo.c')
```
This fails with:
```
../meson.build:16:0: ERROR: The += operator currently only works with arrays, dicts, strings or ints 
```
because fails because `exes` is suddenly not an array any more, but a disabler() object. This is just not terribly useful. Instead of changing the types, disabled object need to keep their type, but just get disabled.

meson-0.54.0-1.fc32.noarch

**Comment by dcbaker** [comment]
Ooof, that's bad. We really should still get a list of objects, which include a `disabler()` at that point.

**Comment by jpakkane** [comment]
This is not a regression, that is how things have always worked. Removing this from 0.55.1.
