### ISSUE TITLE
Expose target triplet (and vendor substring) in *_machine

### ISSUE THREAD

**Issue by ignatenkobrain** [mesonbuild/meson#7112]
By default autotools have this thing autodetected and I am working on porting project to meson which uses information from host_machine's triplet during compilation (to generate file configuration).

Unfortunately meson seems to expose only the machine (.cpu()) and operating system (.system()), but not the vendor and not the whole triplet.

I would appreciate if you could add those.

**Comment by jpakkane** [comment]
We don't do triplets by design, as having 2, 3 or 4 pieces of information in one untyped string is not a particularly good way to do data management. As for exposing more data, you might want to comment on #6361 instead.
