### ISSUE TITLE
mingw: has_function() MSYS2 workaround no longer works with gcc 10

### ISSUE THREAD

**Issue by lazka** [mesonbuild/meson#7113]
**Describe the bug**

has_function for stpcpy and posix_memalign now return true on Windows with gcc 10

My guess is that this is because the workaround here:

https://github.com/mesonbuild/meson/blob/39ca178d21a72a8f7560b657b517fb73f81b4a89/mesonbuild/compilers/mixins/clike.py#L738

no longer works because gcc 10 now supports __has_builtin.

**To Reproduce**

```meson
project('glib', 'c', 'cpp',
  version : '2.65.0',
)

cc = meson.get_compiler('c')
cc.has_function('posix_memalign', prefix : '#include <stdlib.h>')
```

```meson
The Meson build system
Version: 0.54.1
Source dir: C:/msys64/home/user/foo
Build dir: C:/msys64/home/user/foo/_build
Build type: native build
Using 'PKG_CONFIG_PATH' from environment with value: 'C:\\msys64\\mingw64\\lib\\pkgconfig;C:\\msys64\\mingw64\\share\\pkgconfig'
Using 'PKG_CONFIG_PATH' from environment with value: 'C:\\msys64\\mingw64\\lib\\pkgconfig;C:\\msys64\\mingw64\\share\\pkgconfig'
Project name: glib
Project version: 2.65.0
C compiler for the host machine: ccache cc (gcc 10.1.0 "cc (Rev1, Built by MSYS2 project) 10.1.0")
C linker for the host machine: cc ld.bfd 2.34
C++ compiler for the host machine: ccache c++ (gcc 10.1.0 "c++ (Rev1, Built by MSYS2 project) 10.1.0")
C++ linker for the host machine: c++ ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64
Checking for function "posix_memalign" : YES
Build targets in project: 0

Found ninja.EXE-1.10.0 at C:\msys64\mingw64\bin/ninja.EXE
```

**Expected behavior**

```meson
Checking for function "posix_memalign" : NO
```

**Comment by lazka** [comment]
I'm working on a PR for this.

In related news, gcc10 also broke ninja as you can see in the MSYS2 CI job. The ninja progress can be seen here: https://github.com/ninja-build/ninja/pull/1774

**Comment by xantares** [comment]
so what happens for gcc<10 now ?

I find it even questionable that has_function checks for builtins in the first place, cf
https://github.com/mesonbuild/meson/issues/4501

**Comment by lazka** [comment]
My PR shouldn't change the behavior for gcc < 10
