### ISSUE TITLE
Unknown linker: gcc-ar-8 and gcc-ar-7

### ISSUE THREAD

**Issue by phillipjohnston** [mesonbuild/meson#7124]
**Describe the bug**

I have native files to test different versions of GCC on my projects. For `gcc-9`, I can successfully use `gcc-ar-9` as the `ar` binary.

However, `gcc-ar-7` and `gcc-ar-8` both report:

```
meson.build:1:0: ERROR: Unknown linker(s): [['gcc-ar-7']]
```

These are found in the same location, so it's not that they're missing:

```
04:01:45 {master} project-skeleton$ which gcc-ar-7
/usr/local/bin/gcc-ar-7
04:02:24 {master} project-skeleton$ which gcc-7
/usr/local/bin/gcc-7
```

**To Reproduce**

I installed GCC-7 with brew on OS X:

```
$ brew install gcc@7
```

Here is the native file I'm using:

```
[binaries]
c = 'gcc-7'
cpp = 'g++-7'
# You could also use 'ar' from binutils
ar = 'gcc-ar-7'
strip = 'strip'
```
**Expected behavior**

`gcc-ar-7` should work, or I should get a more descriptive error message saying what doesn't work.

**system parameters**
* Native, but with an alternate toolchain
* OS X 10.14.6
* Python 3.7.7
* Meson 0.54.1

**Comment by nirbheek** [comment]
Can you attach your `meson-logs/meson-log.txt`?

**Comment by phillipjohnston** [comment]
Here ya go: [meson-log.txt](https://github.com/mesonbuild/meson/files/4629407/meson-log.txt)

**Comment by phillipjohnston** [comment]
Hm, this seems tied to OS X in some way. I tried gcc-ar-7 and gcc-ar-8 on Linux and do not get the error.

**Comment by phillipjohnston** [comment]
This is also happening for me with avr-gcc-ar:

```
C compiler for the build machine: cc (clang 10.0.1 "Apple LLVM version 10.0.1 (clang-1001.0.46.4)")
C linker for the build machine: cc ld64 450.3
C++ compiler for the build machine: c++ (clang 10.0.1 "Apple LLVM version 10.0.1 (clang-1001.0.46.4)")
C++ linker for the build machine: c++ ld64 450.3
C compiler for the host machine: avr-gcc (gcc 4.8.1 "avr-gcc (GCC) 4.8.1")
C linker for the host machine: avr-gcc ld.bfd 2.23.2

meson.build:1:0: ERROR: Unknown linker(s): [['avr-gcc-ar']]
```

**Comment by dcbaker** [comment]
what is the returncode of `gcc-ar-7`? on Linux it returns 0 and we go down a path for return 0, but I'm guessing that it doesn't return that on macOS.

**Comment by phillipjohnston** [comment]
Aha, thanks for the pointer. For some reason, gcc-7 and gcc-8 are complaining about `liblto_plugin.so` being missing, while gcc-9 doesn't. It seems like this is a general long-standing issue on OS X... but I haven't found any information to explain why gcc-9 succeeds.

**Comment by phillipjohnston** [comment]
I'm going to close this because it seems like a legitimate error.
