### ISSUE TITLE
glib build failure after moving from meson 0.53.1 to 0.54.1

### ISSUE THREAD

**Issue by cpackham** [mesonbuild/meson#7125]
**Describe the bug**
We have an in-house build system for our embedded targets. We also have example x86/x86_64 targets that are built as cross targets even though the build machine is x86_64. When building with meson 0.53.1 every thing is fine. When using meson 0.54.1 we get the following error from glib-2.60.7

```
...
x86_64,glib: Checking for function "mkostemp" : YES
x86_64,glib: Checking if "futex(2) system call" links: YES
x86_64,glib: Checking if "eventfd(2) system call" links: YES
x86_64,glib: Checking if "clock_gettime" links: YES
x86_64,glib: Checking if "number of arguments to statfs() (n=2)" compiles: YES
x86_64,glib: Checking if "open() option O_DIRECTORY" compiles: YES
x86_64,glib:
x86_64,glib: meson.build:811:4: ERROR: Can not run test applications in this cross environment.
x86_64,glib:
x86_64,glib: A full log can be found at /usr/src/buildsys-base/output/x86_64/glib/work/glib-2.60.7/build/meson-logs/meson-log.txt
x86_64,glib: Error Running sh (path = output/x86_64/glib/work/glib-2.60.7, return code = 256)
x86_64,glib: Path: output/x86_64/glib/work/glib-2.60.7
x86_64,glib: Arg[0] = 'sh'
x86_64,glib: Arg[1] = '-c'
x86_64,glib: Arg[2] = '/usr/src/buildsys-base/output/x86_64/glib/staging/local/python/bin/meson build --cross-file=/usr/src/buildsys-base/output/x86_64/glib/staging/cross-compile.conf --prefix=/usr -Dinternal_pcre=true -Dgtk_doc=false -Dman=false -Ddtrace=false -Dxattr=false -Dfam=false -Dinstalled_tests=false -Dtests=false -Dnls=disabled -Dselinux=disabled -Dsystemtap=false'
x86_64,glib: Building failed
x86_64,glib: Finished (0 others running)
```

**To Reproduce**

Unclear. Will update when I have a simple repro.

**Expected behavior**
glib builds successfully

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
  * cross (but host arch == build arch)
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
  * debian buster-slim based container
* what Python version are you using e.g. 3.8.0
  * Python 3.7.3
* what `meson --version`
  * 0.54.1
* what `ninja --version` if it's a Ninja build
  * 1.8.2

**Comment by cpackham** [comment]
I think the reason for the new failure is due to a change in behaviour of `meson.has_exe_wrapper()`

**Comment by cpackham** [comment]
> I think the reason for the new failure is due to a change in behaviour of `meson.has_exe_wrapper()`

Nope that's the same between meson versions

**Comment by cpackham** [comment]
I think the `has_exe_wrapper()` thing is on the right track. glib uses this to decide if it can use `cc.run()` if I replace that test with `not meson.is_cross_build()` then it skips the test an the compilation continues. So the change in behaviour is `cc.run()` which now refuses to run the tests code.

**Comment by cpackham** [comment]
For internet searchers ...

I can avoid the problem by adding
```
[properties]
needs_exe_wrapper = true
```
to the cross-file that our build system provides at build time.

**Comment by nirbheek** [comment]
Duplicate of https://github.com/mesonbuild/meson/issues/7041?

**Comment by cpackham** [comment]
> Duplicate of #7041?

looks likely, certainly the same ball-park
