### ISSUE TITLE
No way to add project specific warning flags

### ISSUE THREAD

**Issue by hughsie** [mesonbuild/meson#713]
In appstream-glib we have:

    GNOME_COMPILE_WARNINGS([maximum],[
        -Wmissing-declarations
        -Wcast-align
        -Wwrite-strings
        -Wreturn-type
        -Wformat-nonliteral
        -Wmissing-format-attribute
        -Wclobbered
        -Wempty-body
        -Wignored-qualifiers
        -Wsign-compare
        -Wtype-limits
        -Wuninitialized
        -Waggregate-return
        -Wdeclaration-after-statement
        -Wshadow
        -Wno-strict-aliasing
        -Winline
        -Wmissing-parameter-type
        -Woverride-init
        -Wno-discarded-qualifiers
        -Wconversion
        -Wformat-signedness
    ])

This macro tests if the warning flag is supported by the compiler (some are not on clang) and if so it adds it to a define that is used for compiling each object.

I'm aware of things like `--warnlevel=3` but this isn't fine grained enough; some of my projects need to disable certain warnings (e.g. where we use legacy included code) and some others need to be much stricter in some cases as they are dealing with hardware and are security sensitive. For instance, I'm using `-Wconversion` in fwupd as it's running as root.

Any ideas on how to do the same with meson? Thanks.

**Comment by nirbheek** [comment]
As discussed on IRC, this can be done by per-target `c_args` or with `add_global_arguments`. You can check which flags are valid with `cc.has_argument` and `cc.first_supported_argument`. See: https://github.com/mesonbuild/meson/wiki/Reference-manual#compiler-object

**Comment by le-jzr** [comment]
> You can check which flags are valid with `cc.has_argument` and `cc.first_supported_argument`

This doesn't seem to be the case (any more?) . In my project, `cc.has_argument` returns true, but later the compilation fails...

> Compiler for C supports argument -Wall: YES
Compiler for C supports argument -Wextra: YES
Compiler for C supports argument -Wmissing-prototypes: YES
Compiler for C supports argument -Wwrite-strings: YES
Compiler for C supports argument -Werror-implicit-function-declaration: YES
Compiler for C supports argument -Werror: YES
Compiler for C supports argument -Wno-unused-parameter: YES
Compiler for C supports argument -Wno-missing-field-initializers: YES
Compiler for C supports argument -Wno-typedef-redefinition: YES
Compiler for C supports argument -Wno-unused-command-line-argument: YES
Compiler for C supports argument -Wno-clobbered: YES

> cc1: error: unrecognized command line option '-Wno-unused-command-line-argument' [-Werror]
cc1: error: unrecognized command line option '-Wno-typedef-redefinition' [-Werror]

**Comment by nirbheek** [comment]
That's because of https://github.com/mesonbuild/meson/pull/2284. Basically, gcc is dumb.
