### ISSUE TITLE
gnome.generate_gir(): add 'fatal_warnings' argument

### ISSUE THREAD

**Issue by gdesmott** [mesonbuild/meson#7130]
When building with `werror=enabled` `gnome.generate_gir()` should pass `--warn-error` to the gir generator so its own warnings are fatal as well.

**Comment by tp-m** [comment]
I'm very wary of this, not sure this is a good idea at all to link this to the global meson `--werror` option.

It's pretty difficult in a complex code base to make `g-ir-scanner` warning-free even more so whilst supporting a range of gobject-introspection versions.

Maybe we should look into adding either module options, or a new kwarg (which projects could then link to a custom option)?

**Comment by gdesmott** [comment]
We can already do it manually by passing `--warn-error` to the `extra_args` kwarg. I was considering how to do that in GStreamer when I figured it may be useful to have it directly into meson.

Maybe this could be gated with a specific `warning-level`?

**Comment by tp-m** [comment]
> Maybe this could be gated with a specific `warning-level`?

Right, but my concern was basically the ability to do the normal `-Wall -Werror` for C/C++ compilers.

Maybe one could have something like `--werror-domains=c,cpp,introspection`?

Or maybe I'm just worried unnecessarily, but I just don't feel g-i has the same kind of maturity level as a proper compiler and we'll need to be able to work around wrong warnings or it otherwise getting confused (e.g. it's pure luck that [your trick in gst-plugins-base](https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/-/merge_requests/661#note_498130) worked and g-i didn't pick up on the types being different, isn't it? What do we do if it starts warning about that in the next version?)

**Comment by gdesmott** [comment]
Can't users just workaround warnings by annotating the symbol with `(skip)`? If most errors lead to the gir to be generated with `introspectable=0` it doesn't change anything for gir users and will force developers to acknowledge those problems.

**Comment by tp-m** [comment]
Maybe, I don't know if all/most warnings lead to `introspectable=0`. If yes then that seems reasonable.

**Comment by gdesmott** [comment]
[Looks like silenting those warnings](https://gitlab.gnome.org/GNOME/gobject-introspection/-/issues/311) is actually not that easy. So I agree with you, using `werror` is not a good idea in the current gir state.

What about adding a `fatal_warning` kwars to `gnome.generate_gir()` which would accept either a boolean or a feature option? So projects could just do something like this:

```
gnome.generate_gir(...
  fatal_warning : get_option('gir-fatal-warnings')
)
```

**Comment by tp-m** [comment]
> What about adding a `fatal_warning` kwars to `gnome.generate_gir()` which would accept either a boolean or a feature option? So projects could just do something like this:

I like that.

**Comment by tp-m** [comment]
> adding a `fatal_warning` kwarg

Maybe plural though - `fatal_warnings`? That matches use elsewhere I think (e.g. `G_DEBUG=fatal_warnings`)

**Comment by xclaesse** [comment]
> What about adding a `fatal_warning` kwars to `gnome.generate_gir()` which would accept either a boolean or a feature option? So projects could just do something like this:

Why would it be a feature option? "auto" would make no sense here...

> Maybe plural though - `fatal_warnings`? That matches use elsewhere I think (e.g. `G_DEBUG=fatal_warnings`)

+1, we have `meson setup --fatal-meson-warnings` already, which itself is inspired from glib.

**Comment by gdesmott** [comment]
> Why would it be a feature option? "auto" would make no sense here... If it's a feature option in your project for whatever reason, you can just pass `get_option('gir-fatal-warnings').enabled()`, or `not get_option('gir-fatal-warnings').disabled()`, depending on the meaning you want to give to `auto`.

Can we do `fatal_warning : get_option('gir-fatal-warnings')` with a boolean option? Then I think it's fine then.
As long as we can enable/disable it easily I'm happy. :)

**Comment by xclaesse** [comment]
Yes that works

**Comment by tp-m** [comment]
> Why would it be a feature option? "auto" would make no sense here.

`auto` would simply mean "I don't care one way or another and will leave it up to circumstances", it provides space for doing different things by default later.

Not very important in this case though.
