### ISSUE TITLE
Pass argument to ar binary in native file

### ISSUE THREAD

**Issue by plattfot** [mesonbuild/meson#7139]
**Describe the bug**
Having an issue with trying to linking a static lto library. At my work we are stuck on an aging gcc and binutils version (4.4.7 and 2.20.51) on our system image. Therefore we have built a newer version of gcc and binutils at a non standard location. And use them to build our code. To make it work with `meson` we use a native file that setup the correct paths. It looks something like this:

```
[binaries]
c = '/tools/package/gcc/9.3.0/bin/gcc'
cpp = '/tools/package/gcc/9.3.0/bin/g++'

[properties]
c_args = ['-B/tools/package/binutils/2.29.1/bin']
cpp_args = ['-B/tools/package/binutils/2.29.1/bin', '-D_GLIBCXX_USE_CXX11_ABI=0']
c_link_args = ['-B/tools/package/binutils/2.29.1/bin']
cpp_link_args = ['-B/tools/package/binutils/2.29.1/bin']
```
When linking a lto static libraries `gcc-ar` needs to be used for it to generate the library properly. So I added `ar = '/tools/package/gcc/9.3.0/bin/gcc-ar'` to the `binaries` entry in the native file. The issue is however, it needs to pass `-B/tools/package/binutils/2.29.1/bin` to `gcc-ar`. Otherwise it will pick up the old `binutils` installed at the system level. Which does not support plugins.

The error I get is:
```
meson.build:1:0: ERROR: Unknown linker(s): [['/tools/package/gcc/6.4.0/bin/gcc-ar']]
```
It doesn't seem to be any option that let me pass the arguments it needs for it to work. Did I just missed it?

**To Reproduce**
Install CentOS 6.4, then compile `gcc-9.3.0` and `binutils-2.29.1`.
binutils is built with the options:
```
--disable-werror
--with-system-zlib
--enable-plugins
--enable-lto
--enable-gold=yes
--enable-ld=default
```
gcc built with the options:
```
--enable-checking=release
--enable-languages=c,c++,fortran
--enable-threads=posix
--disable-multilib
--enable-ld=yes
--enable-gold=yes
--enable-lto
--with-build-time-tools=/tools/package/binutils/2.29.1/bin
```
No patches applied to neither of them.

Then setup any meson.build with
```
meson --native-file=gcc.ini
```
where gcc.ini is:
```
[binaries]
c = '/tools/package/gcc/9.3.0/bin/gcc'
cpp = '/tools/package/gcc/9.3.0/bin/g++'
ar = '/tools/package/gcc/9.3.0/bin/gcc-ar'

[properties]
c_args = ['-B/tools/package/binutils/2.29.1/bin']
cpp_args = ['-B/tools/package/binutils/2.29.1/bin', '-D_GLIBCXX_USE_CXX11_ABI=0']
c_link_args = ['-B/tools/package/binutils/2.29.1/bin']
cpp_link_args = ['-B/tools/package/binutils/2.29.1/bin']
```
Assuming gcc has been installed to `/tools/package/gcc/9.3.0` and binutils to `/tools/package/binutils/2.29.1`
**Expected behavior**
That it should be able to use `gcc-ar` from the custom built without any issues.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
native build
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
CentOS 6.4 with custom built gcc-9.3.0 and binutils 2.29.1
* what Python version are you using e.g. 3.8.0
3.7.4
* what `meson --version`
0.54.0
* what `ninja --version` if it's a Ninja build
1.9.0

Thanks

**Comment by nirbheek** [comment]
Have you already tried using:

```
ar = ['/tools/package/gcc/9.3.0/bin/gcc-ar', '-B/tools/package/binutils/2.29.1/bin']
```

All binaries can be lists or strings. If this doesn't work, it should be fixed.

**Comment by plattfot** [comment]
Oh, completely missed that the binaries can be a list of strings. That's awesome.
Using
```
ar = ['/tools/package/gcc/9.3.0/bin/gcc-ar', '-B/tools/package/binutils/2.29.1/bin']
```
fixed the issue.
Closing this.
Thanks!
