### ISSUE TITLE
Subproject files might be built before some dependency with generated headers is built

### ISSUE THREAD

**Issue by thiblahute** [mesonbuild/meson#714]
I pushed a testcase [here](https://github.com/thiblahute/meson/commits/subproject_dependencies_order_failure) demonstrating the following issue:

* I have a main project with 2 subprojects:
  * `A`: has a target depending on `B` (the dependency is setup thanks to a fallback subproject) and `a.c` includes the generated `b.h` header
  * `B`: has a generated `b.h` file

In that context we should make sure that `B` is built before `A` otherwise it will fail building `a.c` because `b.h` has not been generated yet.

Currently we build `a.c` first and fail at doing so for obvious reason.

**Comment by jpakkane** [comment]
We already have this. If you put the generated header in the source list for A, it will make sure that the header is rebuilt before any source of A is built. The simple way is to put it in the source list of B's `declare_dependency`.

**Comment by thiblahute** [comment]
Why would A put a header generated in its `B` subproject in its list of header? Those are 2 different projects.

**Comment by thiblahute** [comment]
Real word case is GStreamer itself, where the target is declared [here](https://cgit.freedesktop.org/gstreamer/gstreamer/tree/gst/meson.build#n247) and still in some targets declared in Gst plugins I am _sometimes_ getting:

```
[4/1675] Compiling c object 'subprojects/gst-plugins-base/gst-libs/gst/rtsp/gstrtsp-1.0@sha/subprojects_gst-plugins-base_gst-libs_gst_rtsp_gstrtsp-enumtypes.c.o'
FAILED: subprojects/gst-plugins-base/gst-libs/gst/rtsp/gstrtsp-1.0@sha/subprojects_gst-plugins-base_gst-libs_gst_rtsp_gstrtsp-enumtypes.c.o 
cc  '-Isubprojects/gst-plugins-base/gst-libs/gst/rtsp/gstrtsp-1.0@sha' '-fdiagnostics-color=always' '-I../subprojects/gst-plugins-base/gst-libs/gst/rtsp' '-Isubprojects/gst-plugins-base/gst-libs/gst/rtsp' '-Isubprojects/gst-plugins-base/.' '-I../subprojects/gst-plugins-base/.' '-Isubprojects/gst-plugins-base/gst-libs' '-I../subprojects/gst-plugins-base/gst-libs' '-Isubprojects/gstreamer/.' '-I../subprojects/gstreamer/.' '-pipe' '-Wall' '-Winvalid-pch' '-DHAVE_CONFIG_H' '-O0' '-g' '-fPIC' '-I/usr/include/glib-2.0' '-I/usr/lib/glib-2.0/include' '-I/usr/include/glib-2.0' '-I/usr/lib/glib-2.0/include' '-pthread' '-I/usr/include/glib-2.0' '-I/usr/lib/glib-2.0/include' '-pthread' '-I/usr/include/glib-2.0' '-I/usr/lib/glib-2.0/include' '-Isubprojects/gst-plugins-base/gst-libs/gst/rtsp' '-Isubprojects/gstreamer/gst' '-MMD' '-MQ' 'subprojects/gst-plugins-base/gst-libs/gst/rtsp/gstrtsp-1.0@sha/subprojects_gst-plugins-base_gst-libs_gst_rtsp_gstrtsp-enumtypes.c.o' '-MF' 'subprojects/gst-plugins-base/gst-libs/gst/rtsp/gstrtsp-1.0@sha/subprojects_gst-plugins-base_gst-libs_gst_rtsp_gstrtsp-enumtypes.c.o.d' -o 'subprojects/gst-plugins-base/gst-libs/gst/rtsp/gstrtsp-1.0@sha/subprojects_gst-plugins-base_gst-libs_gst_rtsp_gstrtsp-enumtypes.c.o' -c subprojects/gst-plugins-base/gst-libs/gst/rtsp/gstrtsp-enumtypes.c
In file included from ../subprojects/gst-plugins-base/gst-libs/gst/rtsp/gstrtspmessage.h:46:0,
                 from ../subprojects/gst-plugins-base/gst-libs/gst/rtsp/gstrtspconnection.h:51,
                 from ../subprojects/gst-plugins-base/gst-libs/gst/rtsp/gstrtsp.h:24,
                 from ../subprojects/gst-plugins-base/gst-libs/gst/rtsp/rtsp.h:25,
                 from subprojects/gst-plugins-base/gst-libs/gst/rtsp/gstrtsp-enumtypes.c:6:
../subprojects/gstreamer/./gst/gst.h:31:30: fatal error: gst/gstenumtypes.h: No such file or directory
 #include <gst/gstenumtypes.h>
```

**Comment by jpakkane** [comment]
Maybe it fails if there is a dep of a dep? So you have C->B->A and A uses a header generated in C and which is in C's `declare_dependency` but not in B and A only uses B in its dependency definition?

**Comment by nirbheek** [comment]
This is exactly what https://github.com/mesonbuild/meson/issues/676 is about. Sorry for not putting in a more complete summary there; it slipped my mind. I showed this bug to @jpakkane at GUADEC. 

What's happening is that while generating `gstrtsp-enumtypes.c` using the corresponding `custom_target`, we require `gstenumtypes.h` from the gstreamer subproject. However, that won't get built first because there's no direct or indirect dependency on it.

What we want is to be able to add `gst_dep` (from a subproject) as a dependency of the `custom_target` that builds `gstrtsp-enumtypes.c` so that `gstenumtypes.h` is always guaranteed to be built first.

**Comment by nirbheek** [comment]
Ah, forgot to add that we can't add `gst_dep` from a subproject as a `depends` to a `custom_target` because then we get:

```
Meson encountered an error in file gst-libs/gst/rtsp/meson.build, line 33, column 0:
Can only depend on toplevel targets.
```

**Comment by thiblahute** [comment]
OK, now I kind of understand the problem, thanks nirbheek for the explanation, what is you plan for solving it? :)

**Comment by nirbheek** [comment]
We fix this by allowing `gst_dep` to be added to `depends` in `custom_target`. There are probably also other types of objects that it should be able to depend on.

We might also want to force that all the `declare_dependency`s in a subproject are all built before the project that requires it is built, but that is a bit hacky (requires fake rules and such).

**Comment by nirbheek** [comment]
So I looked at this again, and it's not a Meson bug.

`gstrtsp-enumtypes.c` is built as part of a library called `libgstrtsp-1.0`. This pulls in `gstenumtypes.h` via `gst/gst.h`, which is provided by the subproject dependency `gst_dep`, so it's that which should ensure that `gstenumtypes.h` is available at use-time. Just adding that dependency fixes this issue.

https://cgit.freedesktop.org/gstreamer/gstreamer/commit/?id=cfc565e2d88a8e7d656b68c5c2a1b7acb08cdb7f

**Comment by nirbheek** [comment]
Okay, my testing was being messed up by `.ninja_deps` which stores header dependency information as reported by the compiler. You can't trust `ninja clean`; you have to also remove that file.

The actual issue seems to be that while building sources for a library or executable target, the `sources` kwarg (in `declare_dependency`) of subproject dependencies aren't added to the list of dependencies of the compilation target.
