### ISSUE TITLE
meson create filename longer than 255

### ISSUE THREAD

**Issue by braindevices** [mesonbuild/meson#7159]
**Describe the bug**
When work with project have deep folders, meson tend to create very long filename. For example the gst-build projects. The ccache report `Failed to create temporary file for ... File name too long`
https://gitlab.freedesktop.org/gstreamer/gst-build/-/issues/97
**To Reproduce**

**Expected behavior**
meson should check the filename and path length. When it exceed 255 use hash value of it instead.

**system parameters**
* plain native build 
* ubuntu 19.10
* Python 3.7.5
* `meson --version` 0.54.1
* `ninja --version` 1.9.0.git.kitware.dyndep-1.jobserver-1

**Comment by dabrain34** [comment]
I confirm the issue with both 0.54.1 and 0.54.99 building gstreamer with gst-build and ccache does not like it.

**Comment by braindevices** [comment]
@dabrain34 maybe you can check if my branch actually work in your cases.

**Comment by dabrain34** [comment]
Ok I'll give it a try tomorrow and let you know, thx

**Comment by braindevices** [comment]
@dabrain34 can you post the exact error message you had? I think you probably encountered a different bug than mine. If your filename is not longer than 255, it is another problem.
my ccache version is 3.7.3

**Comment by xclaesse** [comment]
The problem in https://gitlab.freedesktop.org/gstreamer/gst-build/-/issues/97 is GStreamer pass an absolute path to a source file within its own source tree. And Meson always replace `/` with `_` when creating the `.o` filename.

1) Meson could be smart and detect abs path within source tree and either warn or make it relative.
2) When replacing `/` with `_` it would minify the name with a hash like we already do for folders.

**Comment by braindevices** [comment]
@xclaesse gst guys should fix that. But I guess we can try to be smarter on the abs path.

**Comment by xclaesse** [comment]
Yep, classical case of "they should not do it, but we should be resilient to it".

**Comment by eli-schwartz** [comment]
I rediscovered the issue in https://github.com/mesonbuild/meson/pull/10788 and fixed it by unconditionally switching to hash prefixes, but only when the depth is >5 and hashing the additional components reduces the length. This shouldn't be a problem anymore.
