### ISSUE TITLE
Dlang: -Dbuildtype=minsize invokes -Os instead of -Oz for LDC

### ISSUE THREAD

**Issue by denizzzka** [mesonbuild/meson#7176]
`-Dbuildtype=minsize` invokes `-Os` instead of `--Oz` for LDC

As result compiler produces binaries about 10% larger.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
Cross build
* what `meson --version`
Current ~master

**Comment by RossSmyth** [comment]
This also occurs in GCC.

**Comment by eli-schwartz** [comment]
Fallout from 4761e4cad946b42daa8723672957e9c1eaeaa5be I guess?
