### ISSUE TITLE
shared vs static as default for library call

### ISSUE THREAD

**Issue by agauniyal** [mesonbuild/meson#719]
> Builds a library that is either static or shared depending on the value of default_library user option. You should use this instead of shared_library or static_library most of the time. This allows you to toggle your entire project (including subprojects) from shared to static with only one option.

I could not find more on *default_library* user option. So when using library call like this 
```
uWSlib = library('uWS', prog_sources, include_directories: inc,
		dependencies : [zlib_dep, ssl_dep, uv_dep, thread_dep])
```

```
echoexe = executable('echo', 'echo.cpp',
        include_directories : inc,
        link_with : uWSlib)
```

is this building a static or shared library(when linking against executable)?

**Comment by jpakkane** [comment]
That depends on the value of option `default_library`. It defaults to shared.

**Comment by agauniyal** [comment]
@jpakkane how should I set value of `default_library` then? I searched in [reference](https://github.com/mesonbuild/meson/wiki/Reference%20manual) but couldn't find it.

**Comment by agauniyal** [comment]
`--default-library=static`. I was confused with `default_library`. I still believe default should be static library though.
