### ISSUE TITLE
meson_options.txt don't allow splitting long strings nicely

### ISSUE THREAD

**Issue by vinipsmaker** [mesonbuild/meson#7199]
Currently `meson_options.txt` don't provide a way to split long strings in multiple lines. If I try to use the `+` operator, the syntax is rejected. My use case is the `description` value. Descriptions can be long to be useful, but I don't like writing anything beyond the 80-column barrier and would rather break this long line.

**Comment by mensinda** [comment]
Will be fixed by #7202.

**Comment by vinipsmaker** [comment]
Thank you.
