### ISSUE TITLE
linking shared modules against BOOST fails

### ISSUE THREAD

**Issue by bredelings** [mesonbuild/meson#7206]
**Describe the bug**

Linking shared modules against boost now fails because static boost libs are used.  I believe that previous versions of meson would use the boost shared libraries, and so avoided this failure.

The obvious thing would be to somehow specify that `dependency('boost')` would select dynamic libs, but I don't see such an option.  Ideally `shared_module( )` would be able to check that the dependency is either a dynamic lib or compiled with -fPIC, but I'm not sure what kind of infrastructure that would require.

$ ninja
[2/4] Linking target liblinkboost.so
FAILED: liblinkboost.so 
c++  -o liblinkboost.so 'linkboost@sha/linkboost.cpp.o' -Wl,--as-needed -Wl,--allow-shlib-undefined -shared -fPIC -Wl,--start-group -Wl,-soname,liblinkboost.so /usr/lib/x86_64-linux-gnu/libboost_system.a /usr/lib/x86_64-linux-gnu/libboost_program_options.a /usr/lib/x86_64-linux-gnu/libboost_chrono.a /usr/lib/x86_64-linux-gnu/libboost_filesystem.a -Wl,--end-group
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libboost_filesystem.a(operations.o): relocation R_X86_64_PC32 against symbol `_ZN5boost6detail15sp_counted_base7destroyEv' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**To Reproduce**
Please include your `meson.build` files, preferably as a minimal toy example showing the issue.
[linkboost.tar.gz](https://github.com/mesonbuild/meson/files/4684202/linkboost.tar.gz)

**Expected behavior**
I expected that the linking step would succeed.

**system parameters**
Debian unstable
python version 3.8.3
meson version 0.54.2
ninja version 1.10.0

**Comment by mensinda** [comment]
Could you please try the current meson master and check if it still uses the static boost libs? This sounds like a duplicate #7171 of and should be fixed by #7179.

**Comment by bredelings** [comment]
Yes, this is fixed on master!
