### ISSUE TITLE
Unsure how to set options for cmake "subproject"

### ISSUE THREAD

**Issue by annacrombie** [mesonbuild/meson#7211]
I cannot figure out how to set options like warning level and c standard for a cmake subproject.  My project's default options include: 'c_std=c11', and 'warning_level=3'.  I tried building the cmake subproject with no options, and then trying to set things with combinations of '-DC_STANDARD=c11' and '-DCMAKE_C_FLAGS=-std=c11'.  The resulting override options in the generated meson.build were all this though: `override_options : ['c_std=c11', 'c_std=gnu99']`, so my attempts were effectively ignored.

My end goal is to remove compilation errors for the subproject entirely, since it is a 3rd party library (glfw).

The repo I am trying this on is [here](https://github.com/annacrombie/crts)

This is where I am setting up the subproject: [client/meson.build](https://github.com/annacrombie/crts/blob/c62560fb58087bc31856de86f5bc6cdbe254b371/client/meson.build#L92)

**Comment by mensinda** [comment]
Sadly, there is currently no way to manually influence the generated `meson.build` directly (though this is definitely a TODO for me). The only way to do this currently is by passing `-DSTUFF=stuff` in `cmake_options` (like you have already tried). The downside with this is that you are entirely dependent on the subprojects `CMakeLists.txt` and if it includes stuff like `set_target_properties(glfw PROPERTIES C_STANDARD 99)` you are out of luck currently.

**Comment by annacrombie** [comment]
I see.  I will just learn to live with the errors for now 😄 , thank you!

**Comment by mensinda** [comment]
Should be fixed/implemented with #7231

**Comment by annacrombie** [comment]
I'm not actually using this feature at the moment, but feel free to close this issue if it is fixed!
