### ISSUE TITLE
Response files needed sometimes even on non-windows systems

### ISSUE THREAD

**Issue by dankegel** [mesonbuild/meson#7212]
A user porting www.flintlib.org to meson ran into a commandline length limit
when it tried to link > 3300 files into a single library, with error
```
ninja: fatal: posix_spawn: Argument list too long
```
https://www.in-ulm.de/~mascheck/various/argmax/ 
says cygwin has the tightest limit on commandline length, but FreeBSD also has a smallish limit.
I was able to reproduce the error on FreeBSD with the following script:
```
#!/bin/sh
set -ex
n=1
echo "project('toolong', 'c')" > meson.build
echo "srcs = [" >> meson.build
while test $n -lt 12000
do
    echo "int f$n(int x) { return x + $n; }" > foo$n.c
    echo " 'foo$n.c'," >> meson.build
    n=$(expr $n + 1)
done
echo "]" >> meson.build
echo "library('toolong', srcs)" >> meson.build
meson . btmp
cd btmp
ninja -v
```

CMake successfully avoids the problem by using a response file, and meson should, too.
(Though ideally it should avoid them when not needed, as they do make debugging a little harder.)

**Comment by dankegel** [comment]
That script also reproduces the problem on ubuntu 20.04, and probably many other flavors of linux.
Evidently 12000 is enough files to make trouble more places.

**Comment by dankegel** [comment]
This hack fixes it for me:
```
--- a/mesonbuild/linkers.py
+++ b/mesonbuild/linkers.py
@@ -331,7 +331,7 @@ class DynamicLinker(LinkerEnvVarsMixin,
metaclass=abc.ABCMeta):
     def get_accepts_rsp(self) -> bool:
         # rsp files are only used when building on Windows because we want to
         # avoid issues with quoting and max argument length
-        return mesonlib.is_windows()
+        return True;  # mesonlib.is_windows()
```

'Course, nobody wants response files on Linux unless they're really needed,
so meson may need to learn a third value for get_accepts_rsp: accepts-rsp-but-no-small-ones-please.

**Comment by maiphi** [comment]
I can confirm that the hack works in the case of FLINT. Note that
- the rsp file is deleted after linking, and
- the fix does not work if the long list of object files is generated manually, e.g. by concatenating extract_all_objects() of several static libs and linking all objects into a single library or executable.

**Comment by dankegel** [comment]
You can run ninja with -d keeprsp to inhibit deletion of rsp files.

Is the extract_all_objects case common enough to worry about for starters?

**Comment by maiphi** [comment]
> You can run ninja with -d keeprsp to inhibit deletion of rsp files.

Ok.
> Is the extract_all_objects case common enough to worry about for starters?

I don't think so. I just stumbled over it, because this is how I switch between my workaround (creating static libs and link them with `link_whole` into a shared lib) and reproducing the issue in my FLINT build system. The only use case I know is to combine several static libs into one.

**Comment by dankegel** [comment]
https://github.com/mesonbuild/meson/pull/7227/ is ready for first review.  Does it solve all the use cases you mentioned above?

**Comment by dankegel** [comment]
https://github.com/mesonbuild/meson/pull/7245 is merged, this should be fixed now.
