### ISSUE TITLE
Meson does not find valac on Gentoo by default

### ISSUE THREAD

**Issue by mensinda** [mesonbuild/meson#7222]
Gentoo only provides versioned vala binaries (`valac-0.46`, `vapigen-0.46`, etc.) without any symlinks to them. This causes meson to not find vala on gentoo.

See https://bugs.gentoo.org/513658 for instance.

Do we care about this or do we require users to set `VALAC` or use a native file?

**Comment by dcbaker** [comment]
As a gentoo user, this isn't meson's bug, it's gentoo's bug, they need to provide an eselect-vala just like they do for python, and ruby, and rust.

**Comment by dcbaker** [comment]
I've also commented on that bug :)

**Comment by mensinda** [comment]
In that case, I am going to close this, since we both agree that this is a Gentoo bug.

**Comment by mensinda** [comment]
I know that this is a bit offtopic, but do all meson tests (as in `run_tests.py` with `CI=1 SKIP_SCIENTIFIC=1`) work for you? I am currently trying to get add a Gentoo image to our OS Comp CI and I am running into errors. This is my current progress so far: https://github.com/mensinda/meson/blob/ciGentoo/ci/ciimage/gentoo/install.sh

I have already given up on automatically regenerating the image with GitHub actions since compiling GCC alone (for ObjC support) would put us well above the 6h timeout.

**Comment by gentoo90** [comment]
As a workaround you can add your versioned `valac` to the [native config file](https://mesonbuild.com/Native-environments.html) in your `~/.local/share/meson/native/` folder:
```ini
[binaries]
vala = 'valac-0.52'
```
and then pass the config to `meson`:
```bash
meson builddir/ --native-file=my_native.ini
```
