### ISSUE TITLE
SRT library not found when GStreamer compiling.

### ISSUE THREAD

**Issue by faio1230** [mesonbuild/meson#7236]
Hello.
I tried to cross-compile GStreamer using gst-build for using SRT protocol.
https://gitlab.freedesktop.org/gstreamer/gst-build
But srt module can't be compiled due to library not found.

I installed libsrt-dev, can't resolve this problem.
How to recognize SRT library to meson?

I'm sorry that I'm not good at English.
Thanks.

```
|Run-time dependency srt found: NO (tried pkgconfig and cmake)
|Header <srt/srt.h> has symbol "srt_startup" : NO 

subprojects/gst-plugins-bad/ext/srt/meson.build:17:2: ERROR: Problem encountered: srt plugin enabled, but srt library not found
```

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? : Yes.
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) : I using Ubuntu 20.04 on VMware
* what Python version are you using e.g. 3.8.0 : Python 3.8.2
* what `meson --version` : 0.54.999
* what `ninja --version` if it's a Ninja build : 1.10.0

**Comment by kishcs** [comment]
I have same issue while building gstreamer with SRT enabled on Ubuntu 20.04
`ERROR: Problem encountered: srt plugin enabled, but srt library not found`

How to find and install SRT library?

**Comment by xclaesse** [comment]
You can check builddir/meson-logs/meson-log.txt to see if why it failed to find the pkg-config file. All you need is libssl-dev and libsrt-dev AFAIK.

**Comment by kishcs** [comment]
@xclaesse I checked the log file. Issue is as below:
```
Determining dependency 'srt' with pkg-config executable '/usr/bin/pkg-config'
env[PKG_CONFIG_PATH]:
Called `/usr/bin/pkg-config --modversion srt` -> 1
stderr:
Package srt was not found in the pkg-config search path.
Perhaps you should add the directory containing `srt.pc'
to the PKG_CONFIG_PATH environment variable
No package 'srt' found
```

**Comment by kishcs** [comment]
I installed this `libsrt-dev`. Its building now.
