### ISSUE TITLE
RFC: meson install --runtime

### ISSUE THREAD

**Issue by xclaesse** [mesonbuild/meson#7246]
Meson currently makes no difference between files installed for developers SDK and those for the runtime package. Distributions and packaging system often have to know the list of installed files beforehand to split stuff that typically goes into -dev package (headers, pkgconfig, static libs).

Would be nice if projects could define themself what they know are needed at runtime and what is for devs.

Suggestion: by default `meson install --runtime` would install only shared libraries and executables, a new boolean kwarg `runtime` (or `install_runtime`?) would then allow the project to opt-in our opt-out some targets. 

Examples:
- `executable('glib-compile-ressources', ..., runtime : false)` would not install that exe when running `meson install --runtime`.
- `both_libraries(..., runtime : true)` would still only install the shared library because it never makes sense to have static libraries in runtime.

**Comment by eli-schwartz** [comment]
This ties into #7007

**Comment by xclaesse** [comment]
Let's close this, I think it's better to add support for a more generic installation groups, and add shared libraries and executables by default in a predefined `runtime` group.
