### ISSUE TITLE
python.install_sources() doesn't create metadata like setup.py does

### ISSUE THREAD

**Issue by hongquan** [mesonbuild/meson#7251]
**Describe the bug**

`python.install_sources` doesn't create and install metadata (_*.dist-info_ files).

**To Reproduce**

https://github.com/hongquan/CoBang/blob/e8a75a5a7aba1a3913942f5cc533bb8095442177/cobang/meson.build

**Expected behavior**

The "cobang" Python package is installed to "site-packages", with its metadata, so that Python "[importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html)" util can discover it.
On the other hand, this code should work:

```py
>>> from importlib.metadata import version  
>>> version('cobang')  
'0.3.0'
```

**system parameters**
* plain native build (for the same computer)
* Ubuntu 20.04
* Python 3.8.0
* Meson 0.53.2
* Ninja 1.10.0

**Comment by eli-schwartz** [comment]
meson never claimed it did any such thing, so it's unsurprising that it failed to do so.

You're looking for something like https://gitlab.com/thiblahute/mesonpep517/

**Comment by hongquan** [comment]
@eli-schwartz `mesonpep517` is to tell `pip` to use `meson` to build the source, it doesn't help generate metadata.

**Comment by hongquan** [comment]
Workaround: Tell Meson to run the `./setup.py` script instead.

```meson
meson.add_install_script('setup.py', 'install', '--prefix', get_option('prefix'))
```
