### ISSUE TITLE
(ninja install,Ubuntu20.04)ModuleNotFoundError: No module named 'mesonbuild' 

### ISSUE THREAD

**Issue by mrkapqa** [mesonbuild/meson#7258]
Hello,

i tried to install this "dav1d" on Ubuntu 20.04

https://code.videolan.org/videolan/dav1d/-/wikis/compilation-guide

when after *ninja* i am supposed to run *ninja install* the error would be

ModuleNotFoundError: No module named 'mesonbuild'
ninja: build stopped: subcommand failed.

**Comment by mrkapqa** [comment]
`ninja install
[1/2] Installing files.
Installation failed due to insufficient permissions.
Attempting to use polkit to gain elevated privileges...
Traceback (most recent call last):
  File "/home/rich/.local/bin/meson", line 5, in <module>
    from mesonbuild.mesonmain import main
ModuleNotFoundError: No module named 'mesonbuild'
FAILED: meson-install 
/home/rich/.local/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
`

**Comment by eli-schwartz** [comment]
meson is installed on the user PYTHONPATH, and invoking sudo ninja will try to rerun meson in order to do the actual install process. But sudo doesn't share your PYTHONPATH, so it fails to import.

So essentially, meson's install stage only supports root-installed versions of meson.

**Comment by jpakkane** [comment]
Or you can set PYTHONPATH to point to your point to your custom Meson install when using sudo. This may have security implications.

**Comment by mrkapqa** [comment]
sorry, i had mixed up .bashrc with something like "alias python=python3"
after removing it; the ninja install would succeed.

however, the mpv-build would still complain of no dav1d as in

` ERROR: dav1d >= 0.4.0 not found using pkg-config `

**Comment by jiapei100** [comment]
Same issue here.... How did you solve that?

**Comment by AntoniosHadji** [comment]
I solved this by installing pip and meson as root.
```
sudo -i
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python3 get-pip.py
python3 -m pip install meson
```

**Comment by Mithil467** [comment]
On Fedora, I installed ninja from system package manager -
`sudo dnf install ninjabuild`
Again, I have tried doing `sudo pip install ninja` still it gives me the same errors.

```
[0/1] Installing files.
Traceback (most recent call last):
  File "/home/mithil/.local/bin/meson", line 5, in <module>
    from mesonbuild.mesonmain import main
ModuleNotFoundError: No module named 'mesonbuild'
```
Now it doesn't matter how I install meson, be it in root or in user, it always looks for meson in user for some reason.
So `sudo pip install meson` does install meson in root but then ninja will complain -
```
/usr/bin/python3: can't open file '/home/mithil/.local/bin/meson': [Errno 2] No such file or directory
```
And of course, meson works correctly when I call `from mesonbuild.mesonmain import main` from python repl, so that is not an issue.

No matter what I try, it just doesn't work.

**Comment by dcbaker** [comment]
@Mithil467 if you install with sudo it will install to /usr, if you want a user install `pip install --user meson` is what you want

**Comment by Mithil467** [comment]
Thanks @dcbaker. But the issue is not about what way to install, no matter what I try, the above error persists.

**Comment by eli-schwartz** [comment]
Why do you try to install ninja using pip? ninja is a C program.

If *ninja* complains it cannot find /home/mithil/.local/bin/meson this is because you need to regenerate the build directory after switching to a different install of meson.

**Comment by Mithil467** [comment]
Thank you @eli-schwartz! Now I understand. This worked for me.

**Comment by AsongnaBrilan** [comment]
> I solved this by installing pip and meson as root.
> 
> ```
> sudo -i
> curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
> python3 get-pip.py
> python3 -m pip install meson
> ```

This worked for me. I was trying to install libcamera

**Comment by ram469** [comment]
Since the regular PATH contents are not available in sudo, we should make them available using the below extra arguments to sudo. This way meson/ninja will get know the paths and the installation should succeed.
sudo -E env "PATH=$PATH" ninja install -C builddir

**Comment by eli-schwartz** [comment]
Nope. meson is a python program and looks for additional files besides the one in $PATH by opening the user-specific python user-site-packages.

That is the actual problem, that's what doesn't transfer to sudo, and it's not very practical to pass this through sudo.

**Comment by link89** [comment]
> I solved this by installing pip and meson as root.
> 
> ```
> sudo -i
> curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
> python3 get-pip.py
> python3 -m pip install meson
> ```

Besides of install meson for root user, another tip is to use `--no-rebuild` options for install command, e.g.
```bash
sudo meson install -C build/ --no-rebuild
```

Or else, you may get the following error if you are using conda env:

```bash
sudo meson install -C build/
Dropping privileges to 'henry' before running ninja...
ninja: Entering directory `/home/henry/src/lxcfs/build'
ninja: error: rebuilding 'build.ninja': stat(/opt/miniconda3/bin/python3.11): Permission denied
```
