### ISSUE TITLE
ENH: Access to pkg-config variables

### ISSUE THREAD

**Issue by QuLogic** [mesonbuild/meson#726]
With pkg-config, packages can define custom variables containing whatever build information they like. For example, Qt4 includes `moc_location` which points to its metaobject compiler. On Fedora, this executable is _not_ on the default path, so there is no way to find it (`find_program` fails, and there don't appear to be any paths associated with the `dependency` object.)

Having some method to access the pkg-config variables (i.e., run `pkg-config --variable=moc_location QtCore` in the above case) would be very helpful. I'm sure there are other variables that might be useful to capture in the same manner.

**Comment by QuLogic** [comment]
So it turns out that this does exist, as the `get_variable` method on a `PkgConfigDependency`. However, it does not appear to be documented. Additionally, the `qt4` and `qt5` modules do not query it for the correct `moc` location.

**Comment by tp-m** [comment]
Nice! I've been wanting/needing this as well :)

**Comment by QuLogic** [comment]
Unfortunately, I don't think the method is exposed to the `meson.build` side of things.

**Comment by jpakkane** [comment]
If memory serves the reason it is not exposed is that a) nobody needed it yet and (more importantly) b) it is pkgconfig specific. Other dependency methods might have something similar so it would be nice to get one unified interface to all of them if possible.

**Comment by tp-m** [comment]
On @sdroege's debian box, a simple ```import('qt5')``` fails fatally already with:
```
Detecting Qt tools.

Meson encountered an error in file subprojects/gst-plugins-base/tests/examples/overlay/meson.build, line 11, column 4:
Moc preprocessor is not for Qt 5. Output:

moc: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/moc': No such file or directory
```
after uninstalling qt5-defaults (or if it's not installed in the first place).

That's pretty unfortunate, I think an import statement should never fail.

This affects gst-plugins-base, we'll have to comment out all qt5 stuff for now.

**Comment by sdroege** [comment]
Note that when installing the qt4 moc, it will report some 4.x version when run there and still fail the import. The problem is *not* that moc falls apart completely, but that any moc (or other) check in there during import is fatal if it fails.

**Comment by fpaquet** [comment]
When writing Glade plugins, installdirs must be queried via pkg-config variables:

catalogdir = run_command(
    'pkg-config', '--variable', 'catalogdir', 'gladeui-2.0'
    ).stdout().strip()

moduledir = run_command(
    'pkg-config', '--variable', 'moduledir', 'gladeui-2.0'
    ).stdout().strip()

pixmapdir = run_command(
    'pkg-config', '--variable', 'pixmapdir', 'gladeui-2.0'
    ).stdout().strip()

Is there any support for querying variables in the pkg-config dependency object ?
Browsing the documentation yesterday, I could not find any hint in the documentation.

**Comment by nirbheek** [comment]
> Is there any support for querying variables in the pkg-config dependency object ?
> Browsing the documentation yesterday, I could not find any hint in the documentation.

You're looking for [`get_pkgconfig_variable(varname)`](https://mesonbuild.com/Reference-manual.html#dependency-object)

**Comment by fpaquet** [comment]
Works like a charm:
```
dep_glade = dependency('gladeui-2.0', version: '>= 3.10')
catalogdir = dep_glade.get_pkgconfig_variable('catalogdir')
moduledir = dep_glade.get_pkgconfig_variable('moduledir')
pixmapdir = dep_glade.get_pkgconfig_variable('pixmapdir')
```
thank you

**Comment by realh** [comment]
The docs say get_pkgconfig_variable has been deprecated. Why is that. What are we supposed to do now, run commands like @fpaquet did?

**Comment by dcbaker** [comment]
@realh use [`dependency.get_variable`](https://mesonbuild.com/Reference-manual_returned_dep.html#depget_variable), which allows you to handle dependencies with multiple providers in a single call. Meson will tell you that at runtime, but apparently the docs don't mention it.

**Comment by realh** [comment]
@dcbaker Thanks, that works. It would be a good idea if the documentation always specified what you should use instead of a deprecated feature.
