### ISSUE TITLE
debian package: add dependency to install dpkg-architecture

### ISSUE THREAD

**Issue by fphammerle** [mesonbuild/meson#7270]
**Describe the bug**

Meson's debian package currently does not depend on [dpkg-dev](https://packages.debian.org/sid/all/dpkg-dev/filelist).
https://packages.debian.org/sid/meson

However, `default_libdir()` tries to run `dpkg-architecture`.
https://github.com/mesonbuild/meson/blob/0.54.2/mesonbuild/mesonlib.py#L717

Consequence: `meson` will install libraries to `$PREFIX/lib64` instead of expected `$PREFIX/lib/x86_64-linux-gnu`

**To Reproduce**
1. `docker run --rm -it debian:sid-slim`
2. `apt-get update && apt-get install meson`
3. `dpkg-architecture -qDEB_HOST_MULTIARCH` prints 
    > bash: dpkg-architecture: command not found

**Expected behavior**
```
$ dpkg-architecture -qDEB_HOST_MULTIARCH
x86_64-linux-gnu
```

**Suggested fix**

Add `dpkg-dev` to `Recommends: ` header of meson's debian packge.

**Comment by eli-schwartz** [comment]
Shouldn't this be directed to https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=meson;dist=unstable

**Comment by fphammerle** [comment]
> Shouldn't this be directed to https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=meson;dist=unstable

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=977051
