### ISSUE TITLE
Meson will find build machine binaries for host if the build machine and host machine are the same

### ISSUE THREAD

**Issue by dcbaker** [mesonbuild/meson#7276]
If you have a case where the build machine == host machine (say x86_64-linux and x86_64-linux) then meson will try to use binaries from the build machine for the host unconditionally. There are however cases where this isn't safe, such as with cmake. When building chromeos this exact situation happens, and the default /usr/bin/cmake is selected, which in turn finds dependencies on the build machine, and tries to use them in the host machine, which obviously will compile, but results in an unusable system.

**Comment by Gcenx** [comment]
Is it possible to disable this change in some manner without needing to patch meson?

Say I want to use a cross file that builds for darwin but I’m running darwin and rather use the native pkg-config/cmake etc instead of specifying these binaries within the cross file?

**Comment by dcbaker** [comment]
No, there isn't a way to do that currently. What exactly are you doing, cross compiling from macOS to iOS or similar?

**Comment by Gcenx** [comment]
Some meson based projects using macports had issues compiling, for some reason using a cross file got the projects building correctly for the desired architecture namely i386.

I’d assume adding all required utility’s into the cross files is desired, but would patching allow_default_for_cross=False to True break cross-compilation that’s not darwin?
