### ISSUE TITLE
build machine CC and CXX ignored when cross compiling.

### ISSUE THREAD

**Issue by baryluk** [mesonbuild/meson#7284]
Meson  0.54.2, from Debian testing, running on Linux amd64.

I am using cross build to build from x86_64 linux to x86_64 linux (build == host). In general it works, but it does ignore the build machine C and C++ compiler settings:

```
$ cat llvm.ini 
[binaries]
c = '/usr/bin/x86_64-linux-gnu-gcc-10'
cpp = '/usr/bin/x86_64-linux-gnu-g++-10'
llvm-config = '/home/user/llvm-installdir/bin/llvm-config'
strip = '/usr/bin/x86_64-linux-gnu-strip'
```

```
Configuring and building 64-bit Mesa ...
+ '[' x1 '!=' x ']'
+ echo 'Configuring and building 64-bit optimized build ...'
Configuring and building 64-bit optimized build ...
+ CC=gcc-10
+ CXX=g++-10
+ PKG_CONFIG=x86_64-linux-gnu-pkg-config
+ meson /home/user/mesa-git/builddir/build-amd64-opt/ --prefix=/home/user/mesa-git/installdir/build-amd64-opt/install --cross-file=llvm.ini -Dplatforms=x11,drm,surfaceless,wayland '-Ddri-drivers=[]' -Ddri3=true -Dgallium-extra-hud=true -Dvulkan-drivers=amd -Dshader-cache=true -Dvulkan-overlay-layer=true -Dopengl=true -Dgles1=true -Dgles2=true -Degl=true -Dllvm=true -Dlmsensors=true -Dtools=glsl,nir -Dopencl-spirv=true -Dgallium-vdpau=true -Dgallium-xvmc=false -Dgallium-va=true -Dgallium-omx=disabled -Dglvnd=true -Dgbm=true -Dglx=dri -Dlibunwind=true -Dosmesa=gallium -Dgallium-nine=true -Dgallium-drivers=radeonsi,r600,zink,virgl,swrast,swr -Dswr-arches=avx,avx2,knl,skx -Dvalgrind=true -Dgallium-opencl=icd -Dopencl-spirv=true --buildtype=plain -Db_ndebug=true '-Dc_args=-pipe -march=native -O3 -ftree-vectorize -flto -g0' '-Dcpp_args=-std=c++17 -pipe -march=native -O3 -ftree-vectorize -flto -g0'
The Meson build system
Version: 0.54.2
Source dir: /home/user/mesa-git
Build dir: /home/user/mesa-git/builddir/build-amd64-opt
Build type: cross build
Program python found: YES (/usr/bin/python)
Project name: mesa
Project version: 20.2.0-devel
C compiler for the build machine: cc (gcc 9.3.0 "cc (Debian 9.3.0-13) 9.3.0")
C linker for the build machine: cc ld.bfd 2.34
C++ compiler for the build machine: c++ (gcc 9.3.0 "c++ (Debian 9.3.0-13) 9.3.0")
C++ linker for the build machine: c++ ld.bfd 2.34
C compiler for the host machine: /usr/bin/x86_64-linux-gnu-gcc-10 (gcc 10.1.0 "x86_64-linux-gnu-gcc-10 (Debian 10.1.0-3) 10.1.0")
C linker for the host machine: /usr/bin/x86_64-linux-gnu-gcc-10 ld.bfd 2.34
C++ compiler for the host machine: /usr/bin/x86_64-linux-gnu-g++-10 (gcc 10.1.0 "x86_64-linux-gnu-g++-10 (Debian 10.1.0-3) 10.1.0")
C++ linker for the host machine: /usr/bin/x86_64-linux-gnu-g++-10 ld.bfd 2.34
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
```

As you can see the environment variables `CC` and `CXX` are ignored, and meson uses `cc` and `c++`, which on my system symlinks to `gcc` and `g++`, which symlink to `gcc-9` and `g++-9`, and that is not what I want.

This is a part of the script that sets this up and is responsible for the meson call above:

```
...

GCCVERSION=10

...

# Use our own LLVM build.
cat > llvm.ini <<EOF
[binaries]
c = '/usr/bin/x86_64-linux-gnu-gcc-${GCCVERSION}'
cpp = '/usr/bin/x86_64-linux-gnu-g++-${GCCVERSION}'
llvm-config = '/home/user/llvm-installdir/bin/llvm-config'
strip = '/usr/bin/x86_64-linux-gnu-strip'
EOF


set -e
set -x

if [ "x${BUILDOPT}" != "x" ]; then
echo "Configuring and building 64-bit optimized build ..."
CC="gcc-${GCCVERSION}" \
CXX="g++-${GCCVERSION}" \
PKG_CONFIG="x86_64-linux-gnu-pkg-config" \
  meson "${BUILDDIR}/build-amd64-opt/" \
  --prefix="${INSTALLDIR}/build-amd64-opt/install" \
  --cross-file=llvm.ini \
  "${COMMON_OPTS[@]}" "${COMMON_OPTS_64[@]}" "${COMMON_OPTS_OPT[@]}"
# meson configure ${BUILDDIR}/build-amd64-opt/ "${COMMON_OPTS[@]}" "${COMMON_OPTS_64[@]}" "${COMMON_OPTS_OPT[@]}"
ninja -C ${BUILDDIR}/build-amd64-opt/ # or cd build-amd64-opt && ninja
ninja -C ${BUILDDIR}/build-amd64-opt/ install
fi

```

I tried putting

```ini
[build_machine]
c = gcc-10
cpp = g++-10
cpu_family, cpu, system, endian ...
```

in llvm.ini, and also mess with host_machine, and nothing helps.

**Comment by dcbaker** [comment]
This looks like a bug (and based on my experience with host == build cross compiles this is probably pretty legitimate. However, could you try creating a second ini file (lets call it native.ini):
```ini
[binaries]
cc = 'gcc-10'
cxx = 'g++-10'
```

and including that file in your command line with `--native-file=native.ini`

That should override the compilers for the build machine.

**Comment by baryluk** [comment]
@dcbaker 

That did fix it the issue for both x86_64 to x86_64 cross-compile, and x86_64 to i686 cross-compile:

x86_64 build machine, x86_64 host machine:

```
The Meson build system
Version: 0.54.2
Source dir: /home/user/mesa-git
Build dir: /home/user/mesa-git/builddir/build-amd64-opt
Build type: cross build
Program python found: YES (/usr/bin/python)
Project name: mesa
Project version: 20.2.0-devel
C compiler for the build machine: /usr/bin/x86_64-linux-gnu-gcc-10 (gcc 10.1.0 "x86_64-linux-gnu-gcc-10 (Debian 10.1.0-3) 10.1.0")
C linker for the build machine: /usr/bin/x86_64-linux-gnu-gcc-10 ld.bfd 2.34
C++ compiler for the build machine: /usr/bin/x86_64-linux-gnu-g++-10 (gcc 10.1.0 "x86_64-linux-gnu-g++-10 (Debian 10.1.0-3) 10.1.0")
C++ linker for the build machine: /usr/bin/x86_64-linux-gnu-g++-10 ld.bfd 2.34
C compiler for the host machine: /usr/bin/x86_64-linux-gnu-gcc-10 (gcc 10.1.0 "x86_64-linux-gnu-gcc-10 (Debian 10.1.0-3) 10.1.0")
C linker for the host machine: /usr/bin/x86_64-linux-gnu-gcc-10 ld.bfd 2.34
C++ compiler for the host machine: /usr/bin/x86_64-linux-gnu-g++-10 (gcc 10.1.0 "x86_64-linux-gnu-g++-10 (Debian 10.1.0-3) 10.1.0")
C++ linker for the host machine: /usr/bin/x86_64-linux-gnu-g++-10 ld.bfd 2.34
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
```

x86_64 build machine, x86 host machine:

```
The Meson build system
Version: 0.54.2
Source dir: /home/user/mesa-git
Build dir: /home/user/mesa-git/builddir/build-i386-opt
Build type: cross build
Program python found: YES (/usr/bin/python)
Project name: mesa
Project version: 20.2.0-devel
C compiler for the build machine: /usr/bin/x86_64-linux-gnu-gcc-10 (gcc 10.1.0 "x86_64-linux-gnu-gcc-10 (Debian 10.1.0-3) 10.1.0")
C linker for the build machine: /usr/bin/x86_64-linux-gnu-gcc-10 ld.bfd 2.34
C++ compiler for the build machine: /usr/bin/x86_64-linux-gnu-g++-10 (gcc 10.1.0 "x86_64-linux-gnu-g++-10 (Debian 10.1.0-3) 10.1.0")
C++ linker for the build machine: /usr/bin/x86_64-linux-gnu-g++-10 ld.bfd 2.34
C compiler for the host machine: /usr/bin/i686-linux-gnu-gcc-10 (gcc 10.1.0 "i686-linux-gnu-gcc-10 (Debian 10.1.0-3) 10.1.0")
C linker for the host machine: /usr/bin/i686-linux-gnu-gcc-10 ld.bfd 2.34
C++ compiler for the host machine: /usr/bin/i686-linux-gnu-g++-10 (gcc 10.1.0 "i686-linux-gnu-g++-10 (Debian 10.1.0-3) 10.1.0")
C++ linker for the host machine: /usr/bin/i686-linux-gnu-g++-10 ld.bfd 2.34
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86
Host machine cpu: i686
Target machine cpu family: x86
Target machine cpu: i686

```


I actually do like this approach, but the fact that the meson ignores the env variables `CC` and `CXX` (and uses some meson defaults hardcoded in meson), but doesn't ignore some others, when doing cross build is a bit weird and not super user friendly.

**Comment by dcbaker** [comment]
That feels like a bug, and like a regression (I feel like this used to work). @Ericson2314, I think you were doing some work with these environment variables recently?

**Comment by Ericson2314** [comment]
I don't think there is a bug, `CC` is (now, matching autoconf) the *host* machine C compiler, and the cross file takes precedence. They should use `CC_FOR_BUILD` if they rather use env vars than machine files. (They can use `CC_FOR_BUILD` and `CC`, if they like.)

**Comment by Ericson2314** [comment]
Also if they turn on the debug output it will say what env vars are read, in order to help debug how the "ambient information" that is environment variables effects the configuration.

**Comment by baryluk** [comment]
@Ericson2314 Who are they?

**Comment by baryluk** [comment]
https://mesonbuild.com/Reference-tables.html#compiler-and-linker-selection-variables doesn't document `CC_FOR_BUILD` et al.

**Comment by Ericson2314** [comment]
Oh thanks for the link, I added some cross docs and release notes, but missed that section of the docs. will update now.

**Comment by baryluk** [comment]
You are saying meson does in fact support `CC_FOR_BUILD` ?

**Comment by Ericson2314** [comment]
Yes. We finally use the legacy vars in the correct way!

**Comment by Ericson2314** [comment]
https://github.com/mesonbuild/meson/pull/7285 should fix the docs.

**Comment by baryluk** [comment]
Oh, I see it now in release notes:

https://mesonbuild.com/Release-notes-for-0-54-0.html#environment-variables-with-cross-builds

and this note:

https://mesonbuild.com/howtox.html#set-compiler

That kind of explains everything, and is a good change indeed. It also probably explains why I didn't notice the issue before or it was hiding in older meson version.

The Reference table for env variables still should be updated to mention these variables, and maybe   https://mesonbuild.com/Feature-autodetection.html#ccache should also be edited to say `CC` and/or `CC_FOR_BUILD`, ditto for `CXX` and `CXX_FOR_BUILD`.


I will drop use of environment variable for my project, and will use `--native-file`, I didn't know you can have both --native-file and --cross-file at the same time. And when I tried to set `[build_machine]` things in cross file, it seemed not to work. In general I prefer explicit control than somehow-implicit environment that can propagate to some other unknown commands by environment.

**Comment by baryluk** [comment]
But, yes, my initial issue is not a bug. CC does work correctly, I just didn't know, and it was not obvious from normal diagnostic why.

**Comment by Ericson2314** [comment]
Glad to hear everything works for now, and that you like the change despite the breakage it caused you. We'll be sure to update the docs---thanks again for pointing those deficiencies out.
