### ISSUE TITLE
ifstream doesn't read file

### ISSUE THREAD

**Issue by G0drlc** [mesonbuild/meson#7298]
When using meson I can't get ifstream to read a file and return its contents.
I have tested this with a simple project using cmake and ninja with both clang and gcc and works fine until I try using meson

build file
```
project('debug', 'cpp',
  version : '0.1',
  default_options : ['cpp_std=c++17'])

executable('test',
           'test.cpp'
)
```

code

```
#include <iostream>
#include <fstream>

using namespace std;

int main()
{
    ifstream file;
    file.open("test.txt", ifstream::in);
    
    char c = file.get();

    while (file.good()) 
    {
        cout << c;
        c = file.get();
    }
    
    file.close();

    return 0;
}
```

linux
meson 0.54.2-1
python 3.8.3-1
ninja 1.10.0-1

**Comment by dcbaker** [comment]
I copied your meson.build and your .cpp file (`test` is a reserved name in meson, so I called it `prog`). and it works fine. It reads a file I created called `test.txt` and prints each line.

**Comment by G0drlc** [comment]
Sorry I figured out my issue
