### ISSUE TITLE
need to run ninja twice for vcs_tag to work

### ISSUE THREAD

**Issue by laolux** [mesonbuild/meson#7311]
**Describe the bug**
I try to add git version information by using the vcs_tag command in the meson.build.
However, whenever I run ninja I get an error

    ../main.cpp:2:10: fatal error: vcs_version.h: No such file or directory
        2 | #include "vcs_version.h"
          |          ^~~~~~~~~~~~~~~
When I run ninja again, then everything compiles just fine as expected.

**To Reproduce**
Use the following meson.build

    project('example program for packaging', 'cpp')
    vcs_tag(command: ['git', 'rev-parse', 'HEAD'], input: 'vcs_version.h.in', output: 'vcs_version.h')
    executable('example_program', 'main.cpp', install : true)

and main.cpp

    #include<iostream>
    #include "vcs_version.h"

    int main(){
        std::cout << "Hello World, this program is a great example." << std::endl;
        std::cout << "Git id is: " << GIT_VERSION << std::endl;
        return 0;
    }

and vcs_version.h.in

    #define GIT_VERSION "@VCS_TAG@"

Then run `meson build`, `cd build`, `ninja` (I get the error message, compile fails), `ninja` (compiles just fine, no error message.

**Expected behavior**
`ninja` runs successfully on the first try.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? plain native build
* what operating system? Fedora 32 
* what Python version: 3.8.3
* what `meson --version`: 0.54.2
* what `ninja --version` if it's a Ninja build: 1.10.0

**Comment by TheQwertiest** [comment]
```meson
project('example program for packaging', 'cpp')
vcs_src = vcs_tag(command: ['git', 'rev-parse', 'HEAD'], input: 'vcs_version.h.in', output: 'vcs_version.h')
executable('example_program', ['main.cpp'] + vcs_src, install : true)
```

See <https://mesonbuild.com/FAQ.html#how-do-i-tell-meson-that-my-sources-use-generated-headers> for more info.

I.e. not a bug.

**Comment by laolux** [comment]
Thanks for pointing that out! However, I still have trouble, albeit a different one. With your example I now get

    meson.build:3:0: ERROR: Invalid use of addition: can only concatenate list (not "CustomTargetHolder") to list

Also trying to use `custom_target` from the FAQ did not help, but I guess that is a different bug.

I guess I should be more careful about updating software like meson where breaking changes may occur. My above example works with meson `0.37` if i specify a `fallback` in `vcs_tag`.

Note to self: Check release notes more carfully.

**Comment by TheQwertiest** [comment]
> I still have trouble, albeit a different one

Right, it should be probably smth like (I'm writing this code w/o verifying it):

```meson
project('example program for packaging', 'cpp')
tag = vcs_tag(command: ['git', 'rev-parse', 'HEAD'], input: 'vcs_version.h.in', output: 'vcs_version.h')
executable('example_program', ['main.cpp'] + tag.to_list(), install : true)
```

0.37 is a really old version and you shouldn't use it =)

**Comment by TheQwertiest** [comment]
Or maybe just `executable('example_program', ['main.cpp', tag], install : true)`.

**Comment by laolux** [comment]
> 0.37 is a really old version and you shouldn't use it =)

Yeah, I know, but I did not have the need to use meson in a while and when things did not work as expected I looked at some old code of mine. And discovered that it does not work with recent versions of meson any more.

Your latest example works great and is easy to implement even in my old project, so thanks a lot!
