### ISSUE TITLE
[CMake] subproject panic when including non "C:\" libraries

### ISSUE THREAD

**Issue by p01arst0rm** [mesonbuild/meson#7322]
**Describe the bug**
CMake subprojects will panic when trying to include libraries
not installed to the `C:` drive

**To Reproduce**
build a CMake subproject, make sure it has a dependency
not on the `C:` drive. Discovery of bug included building `LibKF5Attica`
as a subproject, with `QT5` as a dependency on drive `D:`. 
Native CMake build completed successfully with this setup.

**Expected behavior**
Build the subproject.

**system parameters**
native build
Windows 10 (Current latest patch KB4538461)
python version 3.7.1
meson version 0.54.1
ninja Not Applicable.

**Comment by p01arst0rm** [comment]
specifically, the panic is in `mesonbuild/cmake/interpreter.py` ;- line 892

`self.bs_files = [os.path.relpath(x, self.env.get_source_dir()) for x in self.bs_files]`

**Comment by TheQwertiest** [comment]
@mensinda , sounds like the same issue as `test 2` from https://github.com/mesonbuild/meson/issues/7307

**Comment by mensinda** [comment]
Yes, it most likely is. However, I don't want to just fix that line, since this might also happen in other places. I would rather replace all path handling with `pathlib` and make everything exception-safe. I am aiming for the next big release for this.

**Comment by mensinda** [comment]
Should be fixed with #7798.

@p01arst0rm could you please test the linked PR if you have time?
