### ISSUE TITLE
[RFC] allow the passing of "find files" to cmake dependency searches

### ISSUE THREAD

**Issue by p01arst0rm** [mesonbuild/meson#7324]
It is common for CMake projects to include files that are used
by cmake to assist in finding dependencies

 instead of creating a dummy install within the meson build to
check for a dependency, why not also create a dummy build
with one of these files?

it could allow users to specify how they want cmake to search
for a dependency that meson requires.

Possibly something like:
```
dependency(
    'foo',
    method : 'cmake',
    cmake_search_file : 'CMakeModules/FindFoo.cmake')
```

Just a thought, dont know how feasible it is

**Comment by mensinda** [comment]
There is already [`cmake_module_path`](https://mesonbuild.com/Dependencies.html#cmake).

So you could put your `FindFooHelper.cmake` into your `cmake_dir` and use it in meson with:

```meson
dependency(
    'FooHelper',
    method : 'cmake',
    cmake_module_path : 'cmake_dir'
)
```

**Comment by p01arst0rm** [comment]
ah! RTFM i guess 🙃

**Comment by mensinda** [comment]
Closing then :)
