### ISSUE TITLE
Need Emacs mode for Meson files in MELPA

### ISSUE THREAD

**Issue by russel** [mesonbuild/meson#733]
Meson scripts are not Python scripts and so Python mode will not suffice. Therefore need an Emacs mode for Meson files uploaded to MELPA.

**Comment by jpakkane** [comment]
[Now here](https://github.com/wentasah/meson-mode).

**Comment by fabio-porcedda** [comment]
The issue was closed but i don't see it in MELPA, is already uploaded to MELPA?

Thanks

**Comment by russel** [comment]
There is no entry in the MELPA database, and I cannot see a pull request for one. If this meson-mode repository is the official Meson mode for Emacs, I can add an entry in the MELPA database and send in a pull request.

**Comment by fabio-porcedda** [comment]
That would be great!

Thanks
Fabio

**Comment by jpakkane** [comment]
It's not official but community contributed. The author is planning to submit to MELPA. More info [here](https://groups.google.com/forum/#!topic/mesonbuild/qDjLFHhjxN4).

**Comment by russel** [comment]
I will leave it to the author to submit to MELPA. In the interim I have cloned the repository and will use the mode via that route.
