### ISSUE TITLE
Spam in output when checking for ObjC compiler that doesn't exist

### ISSUE THREAD

**Issue by tp-m** [mesonbuild/meson#7344]
**Describe the bug**
When checking whether an ObjC compiler is available Meson prints this if none is found:
```
|C++ linker for the host machine: c++ ld.bfd 2.34
cc: fatal error: cannot execute ‘cc1obj’: execvp: No such file or directory
compilation terminated.
|Compiler for language objc for the host machine not found.
```

That will look pretty disconcerting to users even though there's no problem here.

Is it supposed to be outputting this or is that just a forgotten redirect to `/dev/null` somewhere?

**To Reproduce**
```
project('foo', 'c')
add_languages('objc', native: true, required: false)
```
on a system that does not have an ObjC compiler installed.

**Expected behavior**
It should output just this:
```
|C++ linker for the host machine: c++ ld.bfd 2.34
|Compiler for language objc for the host machine not found.
```

**system parameters**
* Meson 0.54.2 (but also happens with latest from git)

**Comment by xclaesse** [comment]
`ObjCCompiler.sanity_check()` uses `subprocess.Popen` without redirecting stdout/stderr. From a quick grep in compilers that same mistake has been copy/paster in many places.
