### ISSUE TITLE
Having someway to identify the git commit a release tarball refers to

### ISSUE THREAD

**Issue by ebraminio** [mesonbuild/meson#7354]
Raised [here](https://github.com/harfbuzz/harfbuzz/issues/2472), for a meson based release we like to drop our [ChangeLog generation script](https://github.com/harfbuzz/harfbuzz/blob/8571b35/Makefile.am#L47-L62) anyway yet having someway for being able to identify which commit hash a release tarball was based on feels something more of less good to have.

Thanks!

**Comment by xclaesse** [comment]
I think you can use `vcs_tag()`, and `add_dist_script()` to include the generated file into tarball. Not sure we have other ways to include generated files into dist.

**Comment by ebraminio** [comment]
oooh, thank you very much :)
