### ISSUE TITLE
Documentation should stand alone.

### ISSUE THREAD

**Issue by swestrup** [mesonbuild/meson#7357]
Currently the Meson documentation refers heavily to the Python language. This is ONLY helpful to python programmers. As a C programmer I find it a barrier that I am expected to learn Python to transition a C project from Autotools to Meson. By all means continue to state that some string feature works as 'in python' for those who know it, but then follow with the FULL DOCUMENTATION. You can go and cut-and-paste it from the python documentation on that feature, since you presumably already know the language and know where to find the information easily.

**Comment by denizzzka** [comment]
> Currently the Meson documentation refers heavily to the Python language.

As Dlang programmer I did not notice that. Can you provide example?

**Comment by eli-schwartz** [comment]
@swestrup 

This is already the case.

> One important difference in how variables work in Meson is that all objects are immutable. This is different from, for example, how Python works.

> As in python and C, up to three octal digits are accepted in `\ooo`.

```
# Similar to the Python str.strip(). Removes leading/ending spaces and newlines
define = ' -Dsomedefine '
stripped_define = define.strip()
# 'stripped_define' now has the value '-Dsomedefine'
```

```
# Similar to the Python str.split()
components = 'a b   c d '.split()
# components now has the value ['a', 'b', 'c', 'd']
components = 'a b   c d '.split(' ')
# components now has the value ['a', 'b', '', '', 'c', 'd', '']

# Similar to the Python str.join()
output = ' '.join(['foo', 'bar'])
# Output value is 'foo bar'
pathsep = ':'
path = pathsep.join(['/usr/bin', '/bin', '/usr/local/bin'])
# path now has the value '/usr/bin:/bin:/usr/local/bin'
```

In all these cases, the meson implementation is described and contrasted to python, usually with examples. In one case it's additionally compared to C.

Outside of the Syntax page it doesn't really mention python except to heavily promote it as the best language to write in-tree helper scripts for cross-platform availability.
