### ISSUE TITLE
Allow 'master' projects handle subprojects configuration

### ISSUE THREAD

**Issue by thiblahute** [mesonbuild/meson#736]
Basically in a project like GStreamer, where we have many subprojects we started to create [gst-all](https://github.com/thiblahute/gst-all) that handles all those for us. It would be useful if from there we could have, for example a `disable-gtk-doc` or `disable-gi` options that will then take care of making sure that it is done in each subprojects.

I came up with [this](https://github.com/mesonbuild/meson/pull/734) logical straight forward solution but it looks like it might not to be what we want.

Also in a project like `gst-libav`, we will in the future want to build libav as a subproject (building it statically inside the GStreamer plugin), but we need to make sure to have it built with our own options (the same way as we are currently doing [here](https://phabricator.freedesktop.org/diffusion/GSTLIBAV/browse/master/configure.ac;df3e278b4c9abc2e78dff3ce97444d914df0be35$364))

**Comment by jpakkane** [comment]
The simple way to do this is to have a wrapper script housing all your configuration settings that looks something like this:

    #!/bin/sh

    mkdir mybuilddir
    meson mybuilddir -Dsub1:opt1=2 -Dsub1:opt2=foo -Dsub2:opt1=false

and so on.

**Comment by thiblahute** [comment]
Yeah, I thought about using that workaround but it does not look as friendly, also that does not solve the `gst-libav` use case afaict.

**Comment by jpakkane** [comment]
Why not? You can specify the default args in the same way with both methods.

**Comment by thiblahute** [comment]
Eu, it does not fix the problem in the standard context of someone building
gst-libav outside gst-all.

**Comment by jpakkane** [comment]
For standalone use gst-libav would have its own configuration script. It would probably need one anyway and the flags there could be different (in the general case anyway).

**Comment by thiblahute** [comment]
I am not really convinced not coming up with a generic solution like what I proposed and telling people to write their own script to work around it (and tell users that they can not actually use the normal meson CLI) is the way forward, but if you strictly think we can not do that, so be it.

**Comment by jpakkane** [comment]
This is an important design thing. How do we make it possible to set default options for projects as top level projects, subprojects and subsubprojects (possibly included many times)? Having some usable mechanism for this is useful, it just can't be done by making option values changeable inside project definitions. Design ideas for achieving both of these goals at the same time are gladly accepted.

**Comment by thiblahute** [comment]
OK, perfect, so this task should be about designing a way for a project to override subproject default options in a sensible way.

The big issue here I think is that we can not allow overriding an option default value at several places in a whole project, but as I already stated, I think that the first overriding it should 'win', if another (sub)project tries to re override, that will not be taken into account and we should notify the user about it.

Also no project can ever expect a subproject option to be what it wants it to be, but this will anyway always be the case as the user will always have the final word here.

It looks like you do *not* want to have those override happen in the `meson.build` so where else would you expect it to be doable? In the meson_options.txt having a special `override_option_default` function or something and allowing linking an `option` to it?

I have no design here but am just trying to figure out if you have a potential design in mind :)

**Comment by jpakkane** [comment]
I don't have anything particular in mind at the moment. When `default_options` was being added it was originally going to be a standalone file but people thought that to be too confusing.

A whole different question is whether we can tackle this problem in another way. Such as the parent project being able to check if the subproject was built shared or static and erroring out, or possibly even converting a shared library into a static one.

**Comment by thiblahute** [comment]
> A whole different question is whether we can tackle this problem in another way. Such as the parent project being able to check if the subproject was built shared or static and erroring out, or possibly even converting a shared library into a static one.

You mean to fix the problem about getting `gst-libav` us a subproject? We will need to find a way to fix that but that won't allow us to get it built with our own options would it?

**Comment by iainlane** [comment]
Let me try to write down my case, which I think is an instance of this bug.

I have a subproject called `libmo`, which is included in `appstream-generator`. Now, `libmo` is written in C with GObject and `appstream-generator` in D, so I'm spitting out GObject introspection bindings to use.

I want the submodule to not be installed where a system-wide version would be, so that there's no collision in the event that two projects end up embedding `libmo` or if I ever actually release it. `appstream-generator` needs to be able to (ideally easily) handle the fact that it might use an internal copy of `libmo`, by setting up the right build flags and environment variables for `g-i`. So from the 'outside' of the subproject I need to somehow be able to change install directories, and I need to get these locations to pass into my build as build flags and defines.

At first glance (bear with me, I'm new to meson) the `meson -Dsub1:foo=bar` thing doesn't quite work, because it's not accessible to the master project, and so I can't add the right flags to my build, unless I also pass the same value in as one of its options - which isn't very DRY. It also doesn't seem possible to pass libdir and/or datadir in this way, so I have to define an option and override all targets - and overriding isn't even possible for `generate_gir` currently (maybe just a bug), so I'm a bit stuck there.

**Comment by jpakkane** [comment]
How about something similar to the original proposal:

    subproject('foo', default_options : ['foo=bar', 'bob=bob'])

Which would be semantically equivalent to having those default options in the subproject `project()` invocation (if both specify a same option, the master project's one is chosen).

**Comment by thiblahute** [comment]
That definitely works for and I am happy to rework my patch to fit that.

**Comment by czyba** [comment]
Has there been any progress on this issue? If not, where should I start looking to add this feature?

**Comment by thiblahute** [comment]
heu, this seems to be implemented since:

```
commit d716d53b3204bab94894f26adab84840e4ba4a53
Author: Jussi Pakkanen <jpakkane@gmail.com>
Date:   Thu Dec 29 20:34:13 2016 +0200

    Can override project option default values in subproject().
```

**Comment by nirbheek** [comment]
Yep, we're all done here. Going to close this now.

**Comment by tp-m** [comment]
I thought this only allowed specifying a different directory for the subprojects (e.g. "external/contrib").

Does it actually allow gst-build to put the subprojects at the top-level?

**Comment by nirbheek** [comment]
That's not what this bug was about, was it? I read it as meaning that gst-build should be able to control `enable-gtk-doc` etc in subprojects.

**Comment by tp-m** [comment]
Oh yes, sorry. Misread.
