### ISSUE TITLE
Version_compare doesn't know how to compare '3.6' and '3.6.0'

### ISSUE THREAD

**Issue by Salamandar** [mesonbuild/meson#7376]
Here is an example :

```
project('test')
message('@0@'.format('3.6'.version_compare('>=3.6.0')))
```

You'd expect it to print `true`, right ? 
Well, no. It prints `false.`

Meson 0.54.3.

**Comment by scivision** [comment]
This is also the case on master branch. 

```meson
'3.7'.version_compare('>=3.6.0')
```
works as expected.

**Comment by scivision** [comment]
Hmm, looking at meson/run_unittests.py:test_version_compare there is a test

```python
("1.0", "1.0.0", operator.lt),
```

which implies the current behavior is desired. What do we think, is this surprising or is this desired semantic versioning behavior?

**Comment by scivision** [comment]
Python itself behaves how I expected:

```python
import pkg_resources

 pkg_resources.parse_version('3.6') == pkg_resources.parse_version('3.6.0') == True
```

**Comment by dcbaker** [comment]
The version checking we do is based on rpm, I refactored it a long time ago, but I don't remember who implemented it originally. I agree that this behavior is odd to say the least.

**Comment by scivision** [comment]
I suppose now the issue is backward compatibility. Maybe the best choice remaining is to clearly document this as different communities have different expectations, that it's better to be explicit than implicit with version comparison.

**Comment by eli-schwartz** [comment]
Same logic as used by Arch Linux `vercmp` (part of pacman). "Fixing" it would, I believe, mean special-casing the number 0.

**Comment by jon-turney** [comment]
> The version checking we do is based on rpm, I refactored it a long time ago, but I don't remember who implemented it originally. I agree that this behavior is odd to say the least.

Hi :) Yeah, you can read this same discussion back in #4017.

The principle articulated there is that we should compare versions in the same way as `pkg-config` does.  I hope that the case highlighted here ('3.6.0' > '3.6') is in accordance with that.

That PR also links to a commit with some work towards letting a different version comparison scheme be specified for a particular comparison, if the need for that should be demonstrated.
