### ISSUE TITLE
pkgconfig support for header-only libraries

### ISSUE THREAD

**Issue by fluidparadigms** [mesonbuild/meson#7402]
Right now the pkgconfig module requires a library object to generate a .pc file, but what if you'd like to generate one for a header-only c+++ dependency? Is there currently a work-around for this? Could a dependency object be used as an input to pkgconfig.generate()?

Here is an example:
```
project('mystuff', 'cpp', version : '1.1.1')

mystuff_dep = declare_dependency(include_directories : 'include')

install_subdir('include/mystuff', install_dir : 'include')
install_headers('include/mystuff.hpp')

pkg = import('pkgconfig')
pkg.generate(mystuff_dep)
```
Which would generate the following mystuff.pc:
```
prefix=[prefix]
includedir=${prefix}/include

Name: mystuff
Description: mystuff
Version: 1.1.1
Cflags:-I${includedir}
```

**Comment by xclaesse** [comment]
The first argument is optional, can you try instead: `pkg.generate(libraries: mystuff_dep)` ?

**Comment by fluidparadigms** [comment]
Ah, thanks! I didn't realize that it was optional. The documentation isn't super clear. It turns out that if you pass in a library object, the `name` and `description` arguments are optional. If you **don't** give it a library object, `name` and `description` are required.

**Comment by xclaesse** [comment]
Right. Feel free to propose a patch to improve the doc wording ;-)
