### ISSUE TITLE
Meson build type invalid

### ISSUE THREAD

**Issue by taozuhong** [mesonbuild/meson#7403]
**Describe the bug**
![image](https://user-images.githubusercontent.com/13451009/86310989-f19a1000-bc51-11ea-9198-cb6bc64bc376.png)

**To Reproduce**
meson build
ninja -C build

**Expected behavior**
the build type should be one of them: release / plain / debug / minsize / custom / ....

**system parameters**
OS: Windows 7 (6.1.7600 x64)
Python: 3.8.2
version: 0.54.3

**Comment by taozuhong** [comment]
I don't know what kind of build type is performed.

**Comment by eli-schwartz** [comment]
>  the build type should be one of them: release / plain / debug / minsize / custom / ....

This is just syntactic sugar for -Ddebug= and -Doptimization= and the part of the log you are looking at isn't intended to describe this. It is, instead, stating whether you are doing a build for the current system or cross compiling for a different system.

You can use message() or summary() to print this anyway, but I'm not sure there is especial value in printing specifically the -Dbuildtype= value and not anything else.
