### ISSUE TITLE
Use unknown argument `-C` when calling older version `git`

### ISSUE THREAD

**Issue by li-xin-yi** [mesonbuild/meson#7416]
I didn't install  `glib` properly when I used `meson` to build `pango`. So it will automatically download the dependencies for me before actual building. But my older version `git` (1.8.3.1, I know it is really old enough, but the server is provided by my campus, I have no privilege to update it) cannot recognize the flag `-C`, which is specified in [mesonlib.py#L70)](https://github.com/mesonbuild/meson/blob/7ab0090d2afd8e7301d1ee5d60dd63148ffff607/mesonbuild/mesonlib.py#L70). Can you replace it with a more flexible way?

**Comment by scivision** [comment]
Older Git could be accommodated here with the `cwd=` argument to subprocess. I am not aware of any downside to this. As a personal choice, I generally avoid using cwd= to make the command self-contained--that's just a syntax preference with no technical justification that i know of.

**Comment by eli-schwartz** [comment]
It shouldn't be hard to build a newer git version and install it to `$HOME`.

Are there other new features of git which are being used in meson, that this old version doesn't support? If meson wants to be backwards-compatible with git 1.8 it should make sure everything works there...

**Comment by eli-schwartz** [comment]
This was fixed as a side effect of #7564, see commit 552432e50731b3803d7d637dd4bf38c4f52ecf08
