### ISSUE TITLE
Error using CMake subprojects for libzmq

### ISSUE THREAD

**Issue by HamboLagos** [mesonbuild/meson#7434]
**Describe the bug**
This may be a duplicate of #6857, which was closed with #6859.

Building libzmq as a cmake subproject outputs errors that the parsed include path does not exist.

```
||-- Configuring done
||-- Generating done
||-- Build files have been written to: /home/vagrant/zmqtest/build/subprojects/libzmq/__CMake_build
|
|CMake configuration: SUCCEEDED
|CMake server handshake: SUCCEEDED
|CMake server configure: SUCCEEDED
|Generating build system files: SUCCEEDED
|Querying build system files: SUCCEEDED
|Querying the CMake code model: SUCCEEDED
|WARNING: Unknown cpp_std "gnu++11" -> Ignoring. Try setting the project-level cpp_std if build errors occur. Known cpp_stds are:
|WARNING: CMake: path /home/vagrant/zmqtest/subprojects/libzmq/../include does not exist.
|WARNING:  --> Ignoring. This can lead to build errors.
|WARNING: CMake: path /home/vagrant/zmqtest/subprojects/libzmq/../include does not exist.
|WARNING:  --> Ignoring. This can lead to build errors.
|WARNING: CMake: path /home/vagrant/zmqtest/subprojects/libzmq/../include does not exist.
|WARNING:  --> Ignoring. This can lead to build errors.
|WARNING: CMake: path /home/vagrant/zmqtest/subprojects/libzmq/../include does not exist.
|WARNING:  --> Ignoring. This can lead to build errors.
|WARNING: CMake: path /home/vagrant/zmqtest/subprojects/libzmq/../include does not exist.
|WARNING:  --> Ignoring. This can lead to build errors.
|WARNING: CMake: path /home/vagrant/zmqtest/subprojects/libzmq/../include does not exist.
|WARNING:  --> Ignoring. This can lead to build errors.
...
```

**To Reproduce**
Download this test project: [zmqtest.zip](https://github.com/mesonbuild/meson/files/4907730/zmqtest.zip) (copied from #6857).

```
unzip zmqtest.zip -d zmqtest
cd zmqtest
meson builddir
```

**Expected behavior**
Configuration runs without errors.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
native
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
```
❯ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```
* what Python version are you using e.g. 3.8.0
```
❯ python3.8 --version
Python 3.8.0
```
* what `meson --version`
```
❯ meson --version
0.54.3
```
* what `ninja --version` if it's a Ninja build
```
❯ ninja --version
1.8.2
```

**Comment by mensinda** [comment]
These warnings and not errors. I am also still able to build the zmqtest package without any errors on my machine. Are there any problems with actually building/configuring your project / zmqtest?

If this is just about the warnings then this issue is a won't fix, since the `subprojects/libzmq/../include` path (notice the `..` in the middle) does not exist.

**Comment by mensinda** [comment]
Closing since there were no updates in over a month and the warnings are intended and are no errors.
