### ISSUE TITLE
With 0.55 msvc builds with -Ddefault_library=static use /MD instead of /MT

### ISSUE THREAD

**Issue by borg323** [mesonbuild/meson#7438]
This is with the vs2017 backend. Version 0.54.3 used /MT as expected.

**Comment by jpakkane** [comment]
I tried to replicate this with VS2019 and could not. Can you post a full command line that sets demonstrates the problem using one of Meson's tests. So something like:

    python meson.py --backend=vs --default-library=static "test cases\common\1 trivial" build

On my machine this sets it up to use `/MDd`. At least according to the solution explorer's project properties page.

**Comment by borg323** [comment]
Unfortunately I don't have a windows development environment set up at the moment. However your example shows the problem, it should have been /MTd instead of /MDd - this was OK until 0.54.3 (starting from 0.52 if my notes are accurate).

**Comment by jpakkane** [comment]
I get the same value whether I use `--default-library=static` or not.

The vscrt to use depends on the `b_vscrt` variable whose default value is  `from_buildtype`. That defaults to `debug` so `MDd` seem to be the correct value (based on reading msd docs at least, don't have actual development experience). If you want `MTd` that can be achieved with `-Db_vscrt=mtd`.

**Comment by borg323** [comment]
The issue is not whether the debug version is used or not, this seems to work correctly according to buildtype. However previous versions used the statically linked msvcrt (/MT or /MTd) with `--default-library=static` while with 0.55 only the dll version is used. I didn't find anything in the commits or the release notes to indicate this is an intended change.

**Comment by jpakkane** [comment]
I tried this with 0.52.0 and 0.54.0 and both of them also give me `/MDd` (using VS2019, though, as that is the only one I have).

**Comment by borg323** [comment]
Strange - I'll do more testing from my side and get back to you, but it will take a few days.

**Comment by nirbheek** [comment]
Any updates here?

**Comment by borg323** [comment]
Finally did a `git bisect` and tracked the behavior change to <https://github.com/mesonbuild/meson/commit/f1d00e86f1a83e2fed301c59d22f1415222b29e2#diff-83d2dd519bdd705fcfb785865bfa4020>. However, looking back, my assumption that this has something to do with `-Ddefault_library=static` was wrong. I'll update my build scripts to explicitly set `b_vscrt`.

I see the documented behavior now is that '/MD' is used, however it was not always this way (but was not documented as far as I can tell): prior to version 0.51 `/MD` was used by default, then `/MT` and after the above commit back to `/MD`. Please consider documenting the behavior change.

**Comment by nirbheek** [comment]
This is already documented here: https://mesonbuild.com/Builtin-options.html#b_vscrt-from_buildtype. That commit was fixing an inconsistency in the VS backend, but I guess that should've been in the release notes.
