### ISSUE TITLE
add support for single file wraps

### ISSUE THREAD

**Issue by agauniyal** [mesonbuild/meson#744]
**FEATURE REQUEST**

Currently only zip files are supported, however a lot of projects(atleast single header ones) do releases/ or provide sources with single file only. eg of notable projects: 
- catch testing framework - https://github.com/philsquared/Catch
- json - https://github.com/nlohmann/json
- easyloggingpp - https://github.com/easylogging/easyloggingpp
- rang - https://github.com/agauniyal/rang

and many others. Instead of downloading the full zip, which sometimes is quite large in size, we can download the single files provided by them and include them. This would prove beneficial for several header only c++ projects.

**Comment by agauniyal** [comment]
This should be fairly easy to implement, any progress on this?

**Comment by jpakkane** [comment]
You don't need a release and zip to use a subproject. You can also specify a git repo in your wrap file and Meson will check that out automatically. For reliability we want to encourage people to use upstream releases with as few changes as possible (optimally none). If you want to absolutely minimize space then create a new repo with just the header + Meson files (you need to do equivalent work to create the single file zip in any case).

**Comment by agauniyal** [comment]
I was talking about the releases that are done with single files. Checking out a git repo will almost result in same size as checking out the release since most github releases are archive of the repo themselves.

>If you want to absolutely minimize space then create a new repo with just the header + Meson files (you need to do equivalent work to create the single file zip in any case).

I'll do this for now.
