### ISSUE TITLE
Update to 0.55 breaks two ports in VCPKG with "ModuleNotFoundError: No module named 'pkg_resources'"

### ISSUE THREAD

**Issue by Neumann-A** [mesonbuild/meson#7443]
Error:
```
Traceback (most recent call last):
  File "D:/downloads/tools/meson/meson-0.55.0/meson.py", line 26, in <module>
    from mesonbuild import mesonmain
  File "D:\downloads\tools\meson\meson-0.55.0\mesonbuild\mesonmain.py", line 25, in <module>
    from . import mconf, mdist, minit, minstall, mintro, msetup, mtest, rewriter, msubprojects, munstable_coredata, mcompile
  File "D:\downloads\tools\meson\meson-0.55.0\mesonbuild\mconf.py", line 16, in <module>
    from . import coredata, environment, mesonlib, build, mintro, mlog
  File "D:\downloads\tools\meson\meson-0.55.0\mesonbuild\build.py", line 26, in <module>
    from . import dependencies
  File "D:\downloads\tools\meson\meson-0.55.0\mesonbuild\dependencies\__init__.py", line 15, in <module>
    from .boost import BoostDependency
  File "D:\downloads\tools\meson\meson-0.55.0\mesonbuild\dependencies\boost.py", line 25, in <module>
    from .base import DependencyException, ExternalDependency, PkgConfigDependency
  File "D:\downloads\tools\meson\meson-0.55.0\mesonbuild\dependencies\base.py", line 32, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```
CI link: https://github.com/microsoft/vcpkg/pull/12393/checks?check_run_id=863306764

Any Ideas how to fix it?

**Comment by Voskrese** [comment]
witch pkg-config

**Comment by Neumann-A** [comment]
@Voskrese: pkgconfig set via env variable `PKG_CONFIG`. And it schould be `<Msysroot>/usr/bin/pkg-config.exe`.

**Comment by mensinda** [comment]
This might be due to #6829, where we switched to `pkg_resources` (which is part of `setuptools`). The reasoning for using this was that we already depend on `setuptools` for the meson entry point, so using this here shouldn't cause any errors. What does your current meson setup look like? Did you install it via pip?

cc @dcbaker

**Comment by Voskrese** [comment]
hmm.. deps setuptools ? why?

**Comment by Neumann-A** [comment]
> Did you install it via pip?

No direct download from github + extract. Nothing more. If I need to pip install something I could try that.

**Comment by mensinda** [comment]
I see. In that case `pip install setuptools` should work. It is unfortunate that we also need setuptools now at runtime, but it does fix other [data file related issues](https://github.com/mesonbuild/meson/issues/6801) (especially on Windows).

**Comment by Voskrese** [comment]
@mensinda 
portable ver python

https://www.python.org/ftp/python/3.8.3/python-3.8.3-embed-amd64.zip

+

https://github.com/mesonbuild/meson/releases/download/0.55.0/meson-0.55.0.tar.gz

script `meson.py` error

`python meson.py`

**Comment by mensinda** [comment]
@Voskrese could you please explain your problem in a bit more detail? It is not 100% clear what you are trying to say in your previous post.

**Comment by Voskrese** [comment]
@mensinda 
the portable version of python does not work with version 55, the older version worked like clockwork

**Comment by mensinda** [comment]
OK, thanks for clarifying. However, there is currently no way to work around this, since `setuptools` is (currently) a hard dependency. Is it possible to install/add `setuptools` with the portable python version? Unfortunately, I am not very familiar with this setup.

**Comment by Voskrese** [comment]
![2020-07-13_190735](https://user-images.githubusercontent.com/10104740/87298115-39ffda80-c53c-11ea-841d-e4b09a40a3f0.png)

**Comment by Neumann-A** [comment]
Ok installing pip and than setuptools seems to fix the issue. Will closing.

**Comment by thiblahute** [comment]
I got the same issue on an internal project, if meson depends on setuptool `pip install meson` should install setuptools, that is a bug to me and it should be fixed!
