### ISSUE TITLE
Q on how to notify meson to use custom kernel header

### ISSUE THREAD

**Issue by JohnRama** [mesonbuild/meson#7456]
**Problem Description**
Hi I'm struggling to make following code works in my environment.

```
***meson.build***
project('helloworld', 'c')
executable('hello', 'hello.c')

cc = meson.get_compiler('c')
message(cc.has_header('linux/net_tstamp.h'))
message(cc.has_type('struct sock_txtime', prefix : '#include <linux/net_tstamp.h>'))
```

```
$meson build 
....
Has header "linux/net_tstamp.h" : YES 
message: true
....
Checking for type "struct sock_txtime" : NO 
message: false
....
```
I want to make 'Checking for type "struct sock_txtime"' to Yes.

default compiler inlcude path is as followings
```
$cc -E  -v -                                                                                      
...                                                                                             
 #include <...> search starts here:                             
/usr/lib/gcc/x86_64-linux-gnu/6/include          
/usr/local/include                                                                               
/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed         
/usr/include/x86_64-linux-gnu        
/usr/include   
End of search list.  
```

I'm using the custom build kernel of 4.19.0 and it's headers are installed at /usr/src/linux-headers-4.19.0/

/usr/include/linux/net_tstamp.h does not have struct sock_txtime, 
but /usr/src/linux-headers-4.19.0/include/linux/net_tstamp.h has it.

```
$ grep -r "struct sock_txtime" /usr/include/linux/*
$ echo $?
1
$ grep -r "struct sock_txtime" /usr/src/linux-headers-4.19.0/include/linux/*
/usr/src/linux-headers-4.19.0/include/linux/net_tstamp.h: * SO_TXTIME gets a struct sock_txtime with flags being an integer bit
/usr/src/linux-headers-4.19.0/include/linux/net_tstamp.h:struct sock_txtime {
```
So, question is how can I tell meson to look for /usr/src/linux-headers-4.19.0/include ??
Thanks for the help.

**What I tried**                                                                                         
  I tried followings, but meson could not detect "strut sock_txtime" in "linux/net_tstamp.h".             
  1. export C_INCLUDE_PATH="/usr/src/linux-headers-4.19.0/include"                                        
     to add /usr/src/linux-headers-4.19.0/include for default search path.                                
      $cc -E  -v -                                                                                      
        ...                                                                                             
        #include <...> search starts here:                                                              
       /usr/src/linux-headers-4.19.0/include                                                              
       /usr/lib/gcc/x86_64-linux-gnu/6/include                                                          
       /usr/local/include                                                                               
       /usr/lib/gcc/x86_64-linux-gnu/6/include-fixed                                                    
       /usr/include/x86_64-linux-gnu                                                                    
       /usr/include                                                                                     
      End of search list.                                                                               
  2.  add following line in meson.build
      - include_directories('/usr/src/linux-headers-4.19.0/include') 
      - c_args = ['-I/usr/src/linux-headers-4.19.0/include']
  3. put CFLAGS
      CFLAGS='-I/usr/src/linux-headers-4.19.0/include' meson build 

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
   plain native build
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
    $cat /etc/debian_version
    9.4
    (debian jessie)
* what Python version are you using e.g. 3.8.0
    $python --version
    Python 3.5.3
* what `meson --version`
    $meson --version
    0.53.2
   (I also tried the latest version 0.55, but the same result)
* what `ninja --version` if it's a Ninja build
    $ninja --version
    1.7.2

**Comment by nirbheek** [comment]
As I've explained [in my reply to your gstreamer mailing list question](https://lists.freedesktop.org/archives/gstreamer-devel/2020-July/075577.html), meson is doing the right thing here and adding CFLAGS to the compiler check. Closing.
