### ISSUE TITLE
Python 3.6 regression for as_system() on cmake subproject dependency objects

### ISSUE THREAD

**Issue by waltsteverson** [mesonbuild/meson#7457]
**Describe the bug**
I need to change the include_type for cmake subproject dependencies to 'system'.  Meson 0.54.3 using Python3.6 (Centos 7) this worked correctly.  However after upgrading to Meson 0.55 I get a "TypeError: cannot deepcopy this pattern object" exception.  If I upgrade to Python 3.7 this goes away.  However, Meson is stated to be supported in Python 3.5+.

**To Reproduce**
meson.build
```
project('cmake_dep_regression','cpp')
cmake = import('cmake')
xerces_dep = cmake.subproject('xerces-c').dependency('xerces-c').as_system('system')
exe1 = executable('main', ['main.cpp'], dependencies: [xerces_dep])
```
main.cpp
```
#include <iostream>
#include <cmMod.hpp>

using namespace std;

int main(void) {
  cmModClass obj("Hello");
  cout << obj.getStr() << endl;
  return 0;
}
```
xerces-c.wrap
```
[wrap-git]
url = https://github.com/apache/xerces-c.git
revision = v3.2.2
```

**Expected behavior**
I expect the build to be successful (no traceback) and for the xerces header files to be -isystem included in the main.cpp compile step (see compile_commands.json).

**system parameters**
* Plain native build
* CentOS 7.8
* Python 3.6.8 (fails) and Python 3.7.6 (works)
* meson 0.55.0
* ninja 1.9.0

**Comment by mensinda** [comment]
Should be fixed with #7460.
