### ISSUE TITLE
Request for comments on the patch to support Qualcomm Snapdragon Clang ARM toolchain

### ISSUE THREAD

**Issue by antonysigma** [mesonbuild/meson#7482]
Dear meson authors,

I really enjoy using the Meson build system. Thank you for creating such an exciting tool!

Unfortunately we hit some errors when we tried to configure a Meson project to cross-compile on Qualcomm Snapdragon ARM chipsets. So we have to patch the Meson build system in order for it to detect the toolchain correctly.

I have created a draft PR at #7481 , I would appreciate if you could review it, and to merge it if you see fit. Please also feel free to provide feedback to us to improve the patch.

Regards,
Antony Chan
Camera framework engineer, Truepic
La Jolla, San Diego

In essense, Meson with the above patch will be able to recognize the following example `cross_file.ini`:
```ini
[binaries]
c = '/pkg/qct/software/llvm/release/arm/8.0.12/bin/clang'
c_ld = 'qcld'
ld = '/pkg/qct/software/llvm/release/arm/8.0.12/bin/ld.qcld'

cpp = '/pkg/qct/software/llvm/release/arm/8.0.12/bin/clang++'
cpp_ld = 'qcld'

llvm-config = '/pkg/qct/software/llvm/release/arm/8.0.12/bin/llvm-config'
ar = '/pkg/qct/software/llvm/release/arm/8.0.12/bin/llvm-ar'
strip = '/pkg/qct/software/llvm/release/arm/8.0.12/bin/llvm-strip'

[host_machine]
system = 'linux'
cpu_family = 'aarch64'
cpu = 'cortex-a53'
endian = 'little'

...
```

Quoted from #7481:
> Meson calls path/to/clang++ --version to guess which build toolchain the
user has picked to build the source code. For the Qualcomm LLVM toolchain,
the outputs (stdout or stderr) have an unusual output as shown below:

```
clang version 8.0.12
Snapdragon LLVM ARM Compiler 8.0.12 (based on llvm.org 7.0+)
Target: arm-unknown-linux-gnueabi
Thread model: posix
Repository: (ssh://git-hexagon-aus.qualcomm.com:...)
InstalledDir: /pkg/qct/software/llvm/release/arm/8.0.12/bin
```

> Another unusual pattern is the output of path/to/ld.qcld --version:

```
ARM Linker from Snapdragon LLVM ARM Compiler Version 8.0.12
ARM Linker based on LLVM version: 8.0
The Meson logic is modified accordingly so that Meson can correctly
determine toolchain as "LLVM aarch64 cross-compiler on GNU/Linux64 OS".
```

> This is the expected output of
`meson --native-file native_file.ini --cross-file cross_file.ini build/aarch64-debug/`:

```
...
C++ compiler for the host machine: ... (clang 8.0.12 "clang version 8.0.12")
C++ linker for the host machine: ... ld.lld 8.0.12
...
```

Reference: https://developer.qualcomm.com/software/snapdragon-llvm-compiler-android

**Comment by dcbaker** [comment]
I'm looking at your commits now, so I'm going to close this.
