### ISSUE TITLE
Add support for ThinLTO when using Clang and LLD

### ISSUE THREAD

**Issue by Sonicadvance1** [mesonbuild/meson#7493]
**Describe the bug**
ThinLTO has significant improvements under the "Full" LTO path.
It scales incredibly well from a memory consumption point of view and gives incremental and threaded linking to a project.
ThinLTO has long been stable with other build systems also supporting it now.
https://clang.llvm.org/docs/ThinLTO.html

**To Reproduce**
Easy enough to reproduce,
`CC=clang CC_LD=lld meson -Db_lto=true <remaining options>`

Meson will only set `-flto` for the compile args in this instance

**Expected behavior**
I expect meson to check which version of clang and lld is being used, and if it is above a certain version (ThinLTO was supported back with clang 3.9, but probably shouldn't be enabled there) then by default enable the thin lto option with `-flto=thin`

Additionally a nice feature might be an option to set LTO flavour. This way people can still build with `-flto=full` for their final releases but keep thin around for their development and regression testing.
`-Db_lto_flavor=full, -Db_lto_flavor=thin`

**system parameters**
* This isn't a cross-building problem
* Linux at the very least effected, MacOS might matter as well, unsure if thinlto is supported under Windows
* Python version doesn't matter
* `git HEAD` for meson, checked the source tree and it isn't supporting thinlto
* Ninja doesn't matter here.

**Comment by jpakkane** [comment]
The commit had to be reverted due to backwards compatibility breaking, so reopening.
