### ISSUE TITLE
Regression in 0.55: Compiling Vala requires C.

### ISSUE THREAD

**Issue by tim77** [mesonbuild/meson#7495]
**Describe the bug**
Since Meson 0.55 update we got error during build for Vala projects:
```
ERROR: Compiling Vala requires C. Add C to your project languages and rerun Meson.
```

**To Reproduce**
- [Koschei state](https://koschei.fedoraproject.org/package/gradio?collection=f33)
- [Build log](https://kojipkgs.fedoraproject.org/work/tasks/7138/47667138/build.log)
- [meson.build](https://github.com/haecker-felix/Gradio/blob/master/meson.build)

**Expected behavior**
Should successfully compiles as before.

**system parameters**
* plain native build
* Fedora 32
* Python 3.8.5
* meson 0.55.0
* ninja 1.10.0

Look like something similar already happened before https://github.com/mesonbuild/meson/issues/631.

**Comment by jon-turney** [comment]
I suspect that perhaps the regression here is that the order the languages appear in `project()` is now significant.

**Comment by xclaesse** [comment]
The language name is case-sensitive, with lower-case 'c' it works in my testing.

**Comment by xclaesse** [comment]
But I can confirm it was working with Meson 0.54.0 somehow...

**Comment by xclaesse** [comment]
Wondering why meson error on that instead of just adding 'c' language implicitly...

**Comment by xclaesse** [comment]
Ok, `add_languages_for()` used to check if 'c' lang has been added after `lang = lang.lower()` but now it does it before.

**Comment by tim77** [comment]
@jpakkane @jon-turney Thank you! It works with lowercase `c`.
