### ISSUE TITLE
nested subprojects fail 

### ISSUE THREAD

**Issue by p01arst0rm** [mesonbuild/meson#7497]
**Describe the bug**
declared subprojects with nested subprojects inside them fail to build
on windows. the resulting error is below. both projects build successfully,
but the child project fails when nested in a parent project.

```
subprojects\foo\meson.build:5:0: ERROR: Subproject directory not found and bar.wrap file not found
```

**To Reproduce**
- exctract [mesontest.zip](https://github.com/mesonbuild/meson/files/4973801/mesontest.zip)
- run `meson setup build`

**Expected behavior**
- find subproject foo
- when running foo subproject, find subproject bar.

**system parameters**
* native build
* windows 10 Home 2004 (19041.388)
* Python version 3.8.0
* meson version 0.55.999
* ninja not applicable

**Comment by xclaesse** [comment]
Currently wrap files of nested subprojects must be copied to main project, see `meson wrap promote` command. This will change when we merge that PR: https://github.com/mesonbuild/meson/pull/6968.

**Comment by Qix-** [comment]
See #422. Meson does not support nested submodules, nor will it ever.

**Comment by p01arst0rm** [comment]
> See #422. Meson does not support nested submodules, nor will it ever.

i dont see how you need to "support nested submodules" couldnt there just be a meson function to promote a subproject; atm you can do it with run command inside a build file
