### ISSUE TITLE
Dependency include_type doesn't seem to work with fallback

### ISSUE THREAD

**Issue by tprk77** [mesonbuild/meson#7503]
**Describe the bug**

This results in `-I` in the compile command:

```
date_dep = dependency(
  'date',
  fallback : ['date', 'date_dep'],
  include_type : 'system'
)
```

E.g.: `-I../subprojects/date/include`

This results in `-isystem` in the compile command:

```
date_dep = dependency(
  'date',
  fallback : ['date', 'date_dep'],
  include_type : 'system'
)
date_dep = date_dep.as_system('system')
```

E.g.: `-isystem../subprojects/date/include`

**To Reproduce**

Have a dependency on a subproject using `fallback`. Make sure that the dependency *is not* installed on the system, to trigger the fallback to `subprojects`. Build and examine the contents of `compile_commands.json`.

**Expected behavior**

I would expect `include_type : 'system'` to always use `-isystem`. I would expect the two example above to be equivalent.

**system parameters**
* Meson 0.55.0
* Python 3.6.9
* Ninja 1.8.2
* Ubuntu 18.04
* Native build

**Comment by rhd** [comment]
I ran into this today - spent a while digging through the source to make sure I was doing everything correctly. Turns out I was and then realized it was because of the `fallback`.

The workaround is easy but it wasn't easy figuring this out (for me, at least).
