### ISSUE TITLE
clarification regarding adding projects to wrapdb

### ISSUE THREAD

**Issue by agauniyal** [mesonbuild/meson#752]
The wiki says - 

```
tar xzf libfoo_1.0.0.tar.gz
git clone -b 1.0.0 git@github.com:yourusername/libfoo.git tmpdir
mv tmpdir/.git libfoo-1.0.0
rm -rf tmpdir
cd libfoo-1.0.0
git reset --hard
emacs upstream.wrap meson.build
<verify that your project builds and runs>
git add upstream.wrap meson.build
git commit -a -m 'Created wrap files for libfoo-1.0.0.'
git push origin 1.0.0
```

When I perform `git reset --hard` everything would be resetted to its initial state in the original repo, so why mentioning the steps above it that add to confusion?

At the end I just need to supply meson.build and upstream.wrap, right? And if you won't mind, how are `source_hash = ae4a5eb2d660515eb191bfe3e061f2b8ffe94dce73d32cfd0de090ddcc0ddb01
` calculated for writing inside upstream.wrap file. `sha256`?

**Comment by koponomarenko** [comment]
I was searching for the same question.
From the meson source code, it is **sha256** which is used for `source_hash`.
