### ISSUE TITLE
Multiple targets with different configuration files in same meson.build

### ISSUE THREAD

**Issue by Muffo** [mesonbuild/meson#7530]
My C application can be built with different *modes* that behaves differently depending on the content of `config.h`.
In my meson.build file, I generate this header using the function `configure_file()`.

Now I'd like to improve the process and compile binaries for multiple *modes* in a single build. That means I'll have to manage different versions of `config.h` side by side.

My plan was to create different versions of `config.h` and save them in different folders. Then, customize the include directories for each Meson target to select the header for the *mode* I am building.

Unfortunately, I discovered that you cannot specify a subfolder in the `output` option of `configure_file()` (see #2320). The file will always be created in the same location as the `meson.build` currently being executed.

This means I always have to include `'.'` and cannot differentiate between the different *modes*. Note: changing the `#include` directives in the C source files is not an option.

Is there a way to work around this in Meson?

**Comment by eli-schwartz** [comment]
> Now I'd like to improve the process and compile binaries for multiple _modes_ in a single build. That means I'll have to manage different versions of `config.h` side by side.

So, different build configurations to build one project several times? or...

**Comment by dcbaker** [comment]
Why not use a #define to select which mode you're going to build and pass the name of the header via a -D option?

**Comment by Muffo** [comment]
Here is a simplified code example of what I am trying to do.
My C code looks like this:
```
#include <stdio.h>
#include <config.h>

int main() {
#ifdef FEATURE_A
    printf("Feature A is enabled\n");
#else
    printf("Feature A is disabled\n");
#endif /* FEATURE_A */
}
```
The file config.h is generated by Meson.

Within the same meson.build, I'd like to define two targets: one with FEATURE_A defined, and one with FEATURE_A not defined.
I know I could do this with some Meson option to control whether FEATURE_A is used or not, but that requires running Meson multiple times to configure and build the different use-cases.

My goal here is to do hard-code all the variants in the Meson file and do everything in one step. That is, I'd like run `meson compile` only once and both targets are compiled in the same go.

**Comment by eli-schwartz** [comment]
> that requires running Meson multiple times to configure and build the different use-cases

So that's a yes, then.

The current design of meson is intended that you use two different builddirs, one for each use case. Why do you need both at the same time? Are you distributing multiple installers?

**Comment by Muffo** [comment]
Thanks for confirming that!

My project is organized in units and many of them are used unchanged in multiple use cases. That is, some units don't depend on the config.h and they are always built in the same way. The idea of compiling multiple targets was to avoid re-building these units multiple times, although ccache partially alleviate this.

Also, it would provide an easy way for developer to validate that their changes are not breaking the build of any use case with a single command, as opposed to configuring and building multiple builddirs.

**Comment by eli-schwartz** [comment]
You can use native files to store configurations for each build and reuse them in a single option to meson, and/or a simple for loop or CI environment matrix to test each potential configuration. I'm not sure I buy the logic that meson should provide a single builddir to do both at the same time. It also means that running ninja to bud the default target would presumably build every configuration even if you only need one of them, and you couldn't tell `meson install` to only install the one you actually want.

Saving the work when recompiling is an interesting thought, but I think ccache is probably the best solution there. That, or factoring out some code into a common, global utility library that is linked to as a dependency (but this may only make sense if that code is usable standalone, and of sufficient complexity to make it worth it).

**Comment by Muffo** [comment]
Thanks for the answer, this makes sense. 

Managing the build of multiple configuration is probably outside the scope of Meson, right?

Would you recommend any standalone tool (i.e. not bound to a CI service like Travis) that I can use to manage and execute the matrix of tests?

**Comment by eli-schwartz** [comment]
As I said, meson can store info for one build in https://mesonbuild.com/Machine-files.html (native files, specifically). I'm not familiar with options for actually driving the build matrix, though. I guess you could use a custom script at worst. Or an extremely simple Makefile with one target running meson/ninja per build configuration, since Make can do parallelism. (You can actually do that with a custom build.ninja too, come to think of it.)

**Comment by jpakkane** [comment]
> This means I always have to include '.' 

Meson does that automatically. Whenever you specify a build target, the current source and build directories are added to the header search path.

You can achieve what you want with something like:

- put all files that do not require rebuilding when things change either in a static library or in `files()` that you then pass to the build targets
- set up all common configuration in a dict: `common_conf = {'foo': 'bar', ...}`
- put each of the configuration binaries in their own subdirectories
- configure the header with `configure_file(input: '../config.h.in', output: 'config.h', configuration: common_conf + {'FEATURE_A': true}`
- define build target per each directory

This should build all the different configurations in one go.

**Comment by Muffo** [comment]
Thanks for all the inputs! This will require some refactoring of the code, but now I have a better understanding of the problem and possible solutions.
