### ISSUE TITLE
Dependencies that share a fallback subproject should always look in the system first

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#7534]
This is a regression, I am pretty sure this worked correctly in the past.

Let's say you have a subproject called `gst-plugins-base` that has multiple pkgconfig libraries which are dependent on feature options, say: `gstreamer-gl-x11-1.0`, `gstreamer-gl-wayland-1.0`, `gstreamer-gl-egl-1.0`.

If there's a project that consumes this as follows:

```meson
gst_gl_x11 = dependency('gstreamer-gl-x11-1.0', required: false, fallback: ['gst-plugins-base', 'gst_gl_x11_dep'])
gst_gl_wayland = dependency('gstreamer-gl-wayland-1.0', required: false, fallback: ['gst-plugins-base', 'gst_gl_wayland_dep'])
gst_gl_egl = dependency('gstreamer-gl-egl-1.0', required: false, fallback: ['gst-plugins-base', 'gst_gl_egl_dep'])
```

If `gstreamer-gl-x11-1.0.pc` is not found, and the fallback subproject is not available, then meson won't look for the remaining ones either:

```
Run-time dependency gstreamer-gl-x11-1.0 found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency gstreamer-gl-x11-1.0
Subproject directory not found and gst-plugins-base.wrap file not found
Subproject  subprojects/gst-plugins-base is buildable: NO (disabling)
Dependency gstreamer-gl-x11-1.0 from subproject subprojects/gst-plugins-base found: NO
Dependency gstreamer-gl-wayland-1.0 from subproject subprojects/gst-plugins-base found: NO
Dependency gstreamer-gl-egl-1.0 from subproject subprojects/gst-plugins-base found: NO
```

FWICT, this is happening because of this code in `dependency_impl()`:

```python
# If the dependency has already been configured, possibly by
# a higher level project, try to use it first.
if has_fallback:
    dirname, varname = self.get_subproject_infos(kwargs)
    if dirname in self.subprojects:
        return self.get_subproject_dep(name, display_name, dirname, varname, kwargs)
```

CC: @xclaesse via `git blame` 😉

**Comment by xclaesse** [comment]
I think it has always been like that, but I changed so much code in latest release that it could have regressed.

I guess it would make sense to add a condition there: if subprojects[dirname].fount()

**Comment by xclaesse** [comment]
Note the reason we have that code is if we fallback for one dep of a subprojects we must fallback for all its does, to not mix system version with subprojects version of the same project. But if the subproject failed to configure I see no reason to not look on the system.

**Comment by nirbheek** [comment]
> Note the reason we have that code is if we fallback for one dep of a subprojects we must fallback for all its does, to not mix system version with subprojects version of the same project

Yes, I understand that. As a side-note that this is not fool-proof either, because you might pick up a library from the system via another library. F.ex., cairo on the system will always pull in a system glib. But then again in that case there's nothing we can do :smile:

**Comment by nirbheek** [comment]
> Note the reason we have that code is if we fallback for one dep of a subprojects we must fallback for all its deps

Also, this is likely when this regressed..

**Comment by xclaesse** [comment]
> As a side-note that this is not fool-proof either, because you might pick up a library from the system via another library. F.ex., cairo on the system will always pull in a system glib. But then again in that case there's nothing we can do smile

I fixed that case in already. If gstreamer gets glib from subproject, cairo will get the subproject too even if it does `dependency('glib-2.0')` without specifying a fallback.

**Comment by nirbheek** [comment]
> I fixed that case already. If gstreamer gets glib from subproject, cairo will get the subproject too even if it does `dependency('glib-2.0')` without specifying a fallback.

Even if cairo is picked up via `cairo.pc` which picks up `glib-2.0.pc` and adds its flags directly? We now lookup subproject deps while parsing pkgconfig and other deps?

**Comment by xclaesse** [comment]
ah, right, that case... yes it's still an issue :(

**Comment by xclaesse** [comment]
I tested 0.53 and 0.54 and this is not a regression, always has been like this. Removing 0.55.1 tag, but this remains an issue we need to fix.
