### ISSUE TITLE
[Suggestion] has_function should accept 'required' keyword

### ISSUE THREAD

**Issue by jscott0** [mesonbuild/meson#7541]
has_header_symbol accepts the required keyword so it can error when a symbol is missing. has_function is more robust since it checks that it's able to link, but doesn't accept the required keyword.
Since they're similar in purpose and usage, I see no reason has_function shouldn't offer the required keyword for convenience as well.

Checked against Meson 0.55 on Debian Bullseye GNU/Linux.
```
project('f', 'c')
cc = meson.get_compiler('c')
cc.has_function('puts', required : true)
```

**Comment by xclaesse** [comment]
Would be a nice contribution if you can submit a PR. Could be added to all those check functions IMHO.
