### ISSUE TITLE
warning_level=0 is not respected when using cl.exe

### ISSUE THREAD

**Issue by Apache-HB** [mesonbuild/meson#7548]
**Describe the bug**
passing `warning_level=0` does not result in `/W0` or `/w` being passed to cl.exe

**To Reproduce**

meson.build
```py
project('warn-me', 'c',
    default_options : [ 'warning_level=0' ]
)

exe = executable('exe', 'example.c')
```

example.c
```py
int main(void) { return 0xFFFFFFFFFFFFFFFFULL; }
```

**Expected behavior**
Builds without a narrowing warning.

**system parameters**
* Native build
* Windows 10, 2004, build 19041.388
* python 3.8.4
* 0.53.0
* 1.9.0

**Comment by xclaesse** [comment]
Already fixed: https://github.com/mesonbuild/meson/pull/7492.
