### ISSUE TITLE
compiler.has_argument doesn't work with clang for warnings

### ISSUE THREAD

**Issue by iainlane** [mesonbuild/meson#755]
Try this meson.build (github wouldn't let me upload directly here) https://gist.github.com/iainlane/2935fba6bdd02214eb2de4212573aa3b with `CC=gcc` and then `CC=clang`. The option is unknown, and yet the test passes with clang.

In `meson-log.txt` we can see why:

```
Running compile:
Command line:  clang /tmp/tmph4afoz0x.c -Wzzzzzzzz -c·

Code:
 int i;

Compiler stdout:
 warning: unknown warning option '-Wzzzzzzzz' [-Wunknown-warning-option]
1 warning generated.

Compiler stderr:
·
Compiler for c supports argument -Wzzzzzzzz: YES

Meson encountered an error in file meson.build, line 6, column 8:
Error encountered: buggy
```

clang is only outputting this as a warning. There's a clang-specific flag `-Werror=unknown-warning-option`, which meson could pass. It's clang-specific because it makes gcc error. Or meson could pass `-Werror` for `has_argument`, which I hope works for all compilers, but maybe it's less safe to do so for `has_argument` for some reason I haven't thought of yet - like a value a user could pass that generates a warning but is actually okay (deprecations?).

**Comment by jpakkane** [comment]
Can you test the linked MR to see if it works for you?

**Comment by iainlane** [comment]
Yes, thanks - I tested it on my real project and it works

```
Compiler for c supports argument -Wunused-but-set-variable: NO
Compiler for c supports argument -Wno-suggest-attribute=format: NO
```

before they were both `YES`.

You might want a testcase for this, but otherwise thanks for the fast response. :)
