### ISSUE TITLE
run_command('git') fails when using MSYS2: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte

### ISSUE THREAD

**Issue by SRombauts** [mesonbuild/meson#7552]
**Describe the bug**
meson run_command('git') fails when using MSYS2 MINGW64 on Windows: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte

```
sebas@ASUS-i7 MINGW64 /c/Users/sebas/workspace/siril
$ meson _build/
The Meson build system
Version: 0.54.3
Source dir: /c/Users/sebas/workspace/siril
Build dir: /c/Users/sebas/workspace/siril/_build
Build type: native build
Using 'PKG_CONFIG_PATH' from environment with value: '/mingw64/lib/pkgconfig:/mingw64/share/pkgconfig'
Using 'PKG_CONFIG_PATH' from environment with value: '/mingw64/lib/pkgconfig:/mingw64/share/pkgconfig'
Project name: siril
Project version: 0.99.3
C compiler for the host machine: cc (gcc 10.2.0 "cc.exe (Rev1, Built by MSYS2 project) 10.2.0")
C linker for the host machine: cc ld.bfd 2.34
C++ compiler for the host machine: c++ (gcc 10.2.0 "c++.exe (Rev1, Built by MSYS2 project) 10.2.0")
C++ linker for the host machine: c++ ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64

meson.build:53:0: ERROR: Program or command 'git' not found or not executable
```

I think it's a return of the bug that was fixed 2 years ago https://github.com/mesonbuild/meson/pull/3399 Fix encoding bug on Windows

And/or the same as reported here https://code.videolan.org/videolan/dav1d/-/issues/267 Build fails on Windows when using MSYS2

**To Reproduce**
Follow the steps from my bug report on Siril: https://gitlab.com/free-astro/siril/-/issues/519 Meson fails on Windows: ../meson.build:53:0: ERROR: Program or command 'git' not found or not executable

**system parameters**
* plain native build (for the same computer) but using MSYS2 MINGW64
* Windows 10
* Python 3.8.5
* meson 0.54.3
* (ninja 1.10.0)

Best regards,
Sébastien

**Comment by nirbheek** [comment]
The relevant part from [the downstream issue](https://gitlab.com/free-astro/siril/-/issues/519) is:

```
Build started at 2020-08-06T00:13:36.455561
Main binary: /usr/bin/python.exe
Build Options: 
Python system: MINGW64_NT-10.0-19041
The Meson build system
Version: 0.54.3
[...]
C++ compiler for the host machine: c++ (gcc 10.2.0 "c++.exe (Rev1, Built by MSYS2 project) 10.2.0")
C++ linker for the host machine: c++ ld.bfd 2.34
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte
Unusable script '/usr/bin/git'

meson.build:53:0: ERROR: Program or command 'git' not found or not executable
```

So it's actually failing in executable detection:

```python
    @staticmethod
    def _shebang_to_cmd(script):
        """
        Check if the file has a shebang and manually parse it to figure out
        the interpreter to use. This is useful if the script is not executable
        or if we're on Windows (which does not understand shebangs).
        """
        try:
            with open(script) as f:
                first_line = f.readline().strip()
```

Which means `self._is_executable()` returns `False`:

```
        if os.path.exists(trial):
            if self._is_executable(trial):
                return [trial]
            # Now getting desperate. Maybe it is a script file that is
            # a) not chmodded executable, or
            # b) we are on windows so they can't be directly executed.
            return self._shebang_to_cmd(trial)
```

The fix is, I think, to open the file in binary mode.

**Comment by nirbheek** [comment]
Well, that will get rid of the exception, but git won't be usable anyway. That's some other issue ;)

**Comment by lazka** [comment]
Likely not related, but you are using a cygwin based meson/python to build in a mingw environment. Is that on purpose?

**Comment by SRombauts** [comment]
> Likely not related, but you are using a cygwin based meson/python to build in a mingw environment. Is that on purpose?
How can you tell if it's cygwin based?

I was using the "meson" packet from MSYS2/pacman, and got rid of the error after uninstalling it and installing **mingw-w64-x86_64-meson** instead, in case it helps.

**Comment by lazka** [comment]
The problem is that in MSYS2 `platform.system()` will contain a string that gets generated from the `MSYSTEM` environment variable. This variable contains "MINGW" when run in a mingw environ, which meson looks for, so you end up with a cygwin meson that thinks it runs under native Windows.

Should meson support running under a cygwin Python and then building with a mingw toolchain? If not I'd suggest to make the platform checks stricter and check `sys.platform` instead of `platform.system()`. I can provide a PR.

**Comment by nirbheek** [comment]
Using MSYS2 Meson with MinGW64 has caused a lot of confusion to people: https://discourse.gnome.org/t/build-gtk3-with-meson-using-msys2-on-windows-fails/4015

I think I've seen this with gstreamer too, on the mailing lists. I think we should indeed do what you say, @lazka.

**Comment by lazka** [comment]
Yeah, you even tried to prevent users running it, but we had to patch that out so we can use meson in MSYS2 (we build pacman with it now!) :) https://github.com/msys2/MSYS2-packages/blob/c2f3b924586191f89cc4f6e2b73a8d3de8b2d0f1/meson/cygwin-disguise.patch#L35

I'll look into creating a PR.

**Comment by lazka** [comment]
I've made my downstream patch stricter to prevent bug reports like these in the future: https://github.com/msys2/MSYS2-packages/pull/2138
