### ISSUE TITLE
meson 0.55.0 not generating coverage reports, 0.54.2 does

### ISSUE THREAD

**Issue by williamfgc** [mesonbuild/meson#7553]
**Describe the bug**
0.55.0 doesn't generate coverage report, worked with 0.54.2. Both versions installed with pip3 on Ubuntu 18.04.

**To Reproduce**
`ninja coverage-xml` in any project results in:

version 0.55.0:
```
> ninja coverage-xml
[1/1] Generates XML coverage report
```
`meson-logs/coverage.xml` does not exist

**Expected behavior**
version 0.54.2
```
> ninja coverage-xml
[1/1] Generates XML coverage report

Xml coverage report can be found at file:///home/xxxx/build/meson-logs/coverage.xml
```

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? Plain
* what operating system: Ubuntu 18.04
* what Python version are you using: 3.6.9
* what `meson --version`:   see above 
* what `ninja --version` if it's a Ninja build: 1.8.2

Using gcovr from pip3, version 4.2

**Comment by nirbheek** [comment]
https://github.com/mesonbuild/meson/pull/7598 should fix it.

**Comment by williamfgc** [comment]
@nirbheek great job, thanks!
