### ISSUE TITLE
The CMake target wxWidgets does not exist

### ISSUE THREAD

**Issue by kirawi** [mesonbuild/meson#7567]
**Describe the bug**
When trying to use wxWidgets source as a cmake.subproject, `ninja` will fail and output the error in the title.

**To Reproduce**
```
Example:
│   meson.build
│
├───libs
│   ├───wxWidgets
│   └───zip
└───src
        main.c
```
meson.build
```
project(
	'example',
	'cpp',
	'c',
	version: '1.0.0',
	subproject_dir: 'libs'
)

cmake = import('cmake')

# zip
zip = cmake.subproject('zip')
zip_dep = zip.dependency('zip')

# wxWidgets
wx = cmake.subproject('wxWidgets')
wx_dep = wx.dependency('wxWidgets')


executable(
	'example',
	['src/main.c'],
	dependencies: [zip_dep, wx_dep]
)
```

Then, try to compile. It will give you this error.

**Expected behavior**
Compile/link without any errors.

**system parameters**
* Windows 10 Home 64-bit
* Python 3.8.5
* Ninja-ver: 1.10.0 | Meson-ver: 0.55.0 | wxWidgets-ver: 3.1.4

**Comment by mensinda** [comment]
This is because there is no `'wxWidgets'` CMake target. You can use `message(wx.target_list())` to list all availiable targets.

**Comment by mensinda** [comment]
#7569 will print a better error message. You will also need #7570 for wxWidgets.
