### ISSUE TITLE
[bisected] Can no longer override subproject defaults in superproject's project() statement

### ISSUE THREAD

**Issue by Akaricchi** [mesonbuild/meson#7573]
**Describe the bug**
In Meson 0.55.0 and below, it was possible to override a subproject's default options inside the superproject's `project()` statement, like so:
```meson
project('superproject', 'c',
  default_options : [
      'subproject:test_option=false'])
```

In current git master, this is broken. Configuring such a project for the first time results in the following (irrelevant output omitted):
```
$ grep test_option subprojects/subproject/meson_options.txt 
option('test_option', type : 'boolean', value : true, description : 'Test option. Superproject overrides default to "false"')

$ meson setup build

... omitted ...

WARNING: Unknown options: "subproject:test_option"
The value of new options can be set with:
meson setup <builddir> --reconfigure -Dnew_option=new_value ...

... omitted ...

|Executing subproject subproject method meson 
|
|WARNING: In subproject subproject: Unknown options: "subproject:subproject:test_option"
|The value of new options can be set with:
|meson setup <builddir> --reconfigure -Dnew_option=new_value ...

... omitted ...

Option subproject:test_option is: true [default: false]

$ meson configure build | grep test_option
  subproject:test_option     true           [true, false]       Test option. Superproject overrides default to "false"
```

It seems to recognize `false` as the new "default", however it still applies the old default value to a fresh build directory, as if `-Dtest_option=true` was passed explicitly. If an old build directory is `--wipe`d, any such options are also reverted to their subproject defaults, unless they have been explicitly overriden at any point during the build dir's lifetime.

There is also a new spurious warning
```
|WARNING: In subproject subproject: Unknown options: "subproject:subproject:test_option"
```

This seems to happen for *every* option overriden via the `project()` statement.

**To Reproduce**
Here is a minimal test case: 
[meson-test-subproject-option-override-from-superproject.zip](https://github.com/mesonbuild/meson/files/5046588/meson-test-subproject-option-override-from-superproject.zip)

**Expected behavior**
After configuring a build directory for the attached test case, `subproject:test_option` should be `false`. There should not be any warnings about missing options.

**system parameters**
* meson 0.55.999 (1ddd2b4cb)

**Comment by Akaricchi** [comment]
Bisected to `591e6e94b9fccfc49ee7093cb21735a27fd64005`, part of #6597. CC @dcbaker

**Comment by xclaesse** [comment]
Thanks for testing master! I didn't know we could have `subprojects:foo` in project. I fixed this regression in https://github.com/mesonbuild/meson/pull/7574 and added a unit test for that.

**Comment by Akaricchi** [comment]
> I didn't know we could have subprojects:foo in project()

I believe this isn't actually documented, and might've even been allowed by accident (correct me if I'm wrong). But this is useful, has worked for a while, and some projects depend on it, so I'd say it's worth promoting to an official feature. Pretty sure this used to be the only working way to override subproject defaults at some point; not sure whether it still is.

**Comment by dcbaker** [comment]
I'm not sure we meant to enable this. Since we have support for setting default arguments to subprojects in the `subproject()` call I'd prefer to deprecate this and keep the one in the subproject call.

**Comment by Akaricchi** [comment]
But what if you don't call `subproject()`?  It's common and encouraged to just use `dependency()` with a fallback instead, and in 0.55.0 the fallback can even be implicit. I don't think you can specify subproject options in that way, can you? Besides, having it all in one place is just more readable and maintainable. I'd rather deprecate `subproject(default_options:)`, especially considering that it used to be broken for a while.
