### ISSUE TITLE
Automatic insertion of prefer-dynamic for rust dynamic libs problematic

### ISSUE THREAD

**Issue by hjones2199** [mesonbuild/meson#7576]
I'm trying to build a mixed C++/Rust project, and having issues with meson presumptuously inserting command line arguments I  cant seem to disable. In particular, the assumption that --crate-type=cdylib implies -C prefer-dynamic causes issues when the user of the library does not "bring along" its own rust standard lib (like when C++ code is trying to link against the rust lib).

I'm not sure if theres a way to disable the prefer-dynamic flag and keep the crate type as a cdylib in meson, from browsing the ninja backend handling code it seemed to be a hard-coded option. When I edit the rustc definition in the ninja.build manually to remove the dynamic flag everything links fine.

**Comment by rusty-snake** [comment]
I come here because `-C prefer-dynamic` breaks `-C panic=abort`.

I see two possible solutions:

1. `rust_prefer_dynamic` kwarg which defaults to true
2. `-C prefer-dynamic` is inserted before `rust_args` so you can override it use `rust_args: ['-C', 'prefer-dynamic=no'],`

**Comment by rusty-snake** [comment]
The only way to workaround this issue without editing `build.ninja` (which is rather unreliable) that I could find was to write a wrapper and use `RUSTC="$PWD/rustc" meson _builddir`.

<details><summary><code>rustc</code>-wrapper</summary>

```py3
#!/usr/bin/python3

# Copyright © 2021 rusty-snake
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

"""
A wrapper around ``rustc`` which replaces ``-C prefer-dynamic`` with ``-C prefer-dynamic=no``.
Workaround for https://github.com/mesonbuild/meson/issues/7576
"""

import subprocess
import sys

try:
    subprocess.run(
        [
            "rustc",
            *(
                arg if arg != "prefer-dynamic" else "prefer-dynamic=no"
                for arg in sys.argv[1:]
            ),
        ],
        check=True,
    )
except subprocess.CalledProcessError as e:
    sys.exit(e.returncode)
```

</details>

**Comment by sdroege** [comment]
While probably not a full solution, https://github.com/mesonbuild/meson/pull/11676 and https://github.com/mesonbuild/meson/pull/11693 improve the automatic usage of `-C prefer-dynamic`

**Comment by alyssais** [comment]
Indeed not a full solution.

Easy reproduction:

```diff
diff --git i/test cases/rust/18 proc-macro/meson.build w/test cases/rust/18 proc-macro/meson.build
index 01c4cbe17..2958df1af 100644
--- i/test cases/rust/18 proc-macro/meson.build	
+++ w/test cases/rust/18 proc-macro/meson.build	
@@ -13,7 +13,8 @@ pm = shared_library(
 main = executable(
   'main',
   'use.rs',
-  link_with : pm
+  link_with : pm,
+  rust_args : ['-C', 'panic=abort'],
 )
 
 test('main_test', main)
```

Interestingly, Meson now behaves in the exact opposite way to Cargo.  Cargo uses prefer-dynamic for the proc macro, but not for the executable, while Meson does the exact opposite.
