### ISSUE TITLE
add linker version-script helpe

### ISSUE THREAD

**Issue by gdesmott** [mesonbuild/meson#7578]
Similarly to the [executable(gnu_symbol_visibility)](https://mesonbuild.com/Reference-manual.html#executable) argument, it would be useful to have one called `version_script` taking a file object and passing [a version script](https://www.gnu.org/software/gnulib/manual/html_node/LD-Version-Scripts.html) to the linker.

We need something a bit smarter than a flat flag as we'd want to rebuild the target when this file is modified.

**Comment by dabrain34** [comment]
I would say passing it as a linker_args should be enough dont you think as -Wl,-gc-sections ?

**Comment by xclaesse** [comment]
The version script file can be passed to `link_depends`, and it will re-link the target when the file is modified.

**Comment by gdesmott** [comment]
Yep that's what I'm doing atm. Was wondering if we'd want a higher API for that or not.

**Comment by jpakkane** [comment]
Duplicate of #4747.
