### ISSUE TITLE
Include order issue with include_directories

### ISSUE THREAD

**Issue by randy408** [mesonbuild/meson#7579]
**Describe the bug**
Meson does not order include directories from the `include_directories` kw ahead of `.`, this means that in a source tree with a header at `.` may conflict with any other header of the same name in subdirectories.

For a real-world example see https://github.com/SanderMertens/flecs where `./flecs.h` is an amalgamated version of everything under `include/` which contains `include/flecs.h`.

**To Reproduce**
`meson.build`
```meson
project('include_path', 'c')

lib_inc = include_directories('include')

lib_src = files('src/lib.c')

library('inc',
	lib_src,
	include_directories : lib_inc
)
```
`include/lib.h` - empty

`src/lib.c`
```c
#define LIB_INTERNAL

#include <lib.h>
```
`lib.h`
```c
#ifdef LIB_INTERNAL
    #error wrong header
#endif
```
```
In file included from ../src/lib.c:3:
../lib.h:2:6: error: #error wrong header
     #error wrong header
```

**Expected behavior**
The header from `include` should be first in the search path.

**system parameters**
* Reproducible on windows msvc/mingw, linux
* python 3.8.1
* 0.55.0 and 0.54.3
* ninja 1.10.0

**Comment by dcbaker** [comment]
Naming your local headers the same as a system wide header is asking for trouble, and always has been, that's just the nature of C (and it's relatives). You have two options.  The best option is to rename the local header so it doesn't clash. The second option (in this case): is set the `implicit_include_directories` argument to false:

```meson
project('include_path', 'c')

lib_inc = include_directories('include')

lib_src = files('src/lib.c')

library('inc',
	lib_src,
	include_directories : lib_inc,
       implicit_include_directories : false,
)
```

**Comment by randy408** [comment]
Using `implicit_include_directories` fixes this issue, thanks!
