### ISSUE TITLE
gnome.mkenums_simple() doesn't work if implicit_include_directories : false

### ISSUE THREAD

**Issue by ystreet** [mesonbuild/meson#7582]
The crux of the problem is that meson generates includes assuming that the source directory is part of the include list like so:

```
#include "gstvkapi.h"
```

with this code:

```
for hdr in sources:
    fhead += '#include "%s"\n' % os.path.basename(str(hdr))
```

One potential fix is to generate a build to source directory path and prepend that to each included file or even determine that mapping at runtime for built sources passed to `mkenums_simple()`.

**Comment by QuLogic** [comment]
This also breaks the case of source files in subdirectories of the target. Those would normally not have the subdirectory in the include path, regardless of where `mkenums_simple` was called.  Meson usually uses relative paths to the source directory, so using a plain base name is unusal.

**Comment by matthiasclasen** [comment]
Also see https://github.com/mesonbuild/meson/issues/2969

**Comment by xclaesse** [comment]
Made a PR: https://github.com/mesonbuild/meson/pull/10855, but you still need to have the subdir where you call mkenum_simple() in your include directories. But it does not have to be the same directory than where you compile the generated .c file.
