### ISSUE TITLE
json package is not showing up in wrapdb

### ISSUE THREAD

**Issue by agauniyal** [mesonbuild/meson#759]
- https://wrapdb.mesonbuild.com/
- https://github.com/mesonbuild/json
- https://github.com/mesonbuild/json/tree/2.0.2

**Comment by jpakkane** [comment]
There are some technical problems with wrapdb machine. Sorry. In the mean time you can use the very unofficial `ghwt.py` that is in git repo (but not in releases).

**Comment by agauniyal** [comment]
I hope it gets resolved soon.
