### ISSUE TITLE
external commands runtime directory 

### ISSUE THREAD

**Issue by agauniyal** [mesonbuild/meson#760]
```
r = run_command('command', 'arg1', 'arg2', 'arg3')
if r.returncode() != 0
  # it failed
endif
output = r.stdout().strip()
errortxt = r.stderr().strip()
```

Is this command run from the directory of project, or the current directory of meson.build file or somewhere else?

**Comment by jpakkane** [comment]
The behaviour is the same as for `run_target`. That is, it is not defined (and may be different for different backends). [The wiki](https://github.com/mesonbuild/meson/wiki/Reference-manual#run_command) has been updated with information.
