### ISSUE TITLE
Feature wish: Option to force static:true for all dependency() calls

### ISSUE THREAD

**Issue by rgpublic** [mesonbuild/meson#7621]
I don't have much experience with build systems etc. I've currently been confronted with meson for the first time, trying to create a static binary of imagemagick. Many dependencies like glib and pango seem to have switched to meson. So far, the experience is great and much better than with other systems (Makefile, CMake etc.) which I often found way more confusing and less readable. I found, though, that to successfully compile some libraries as static, I needed to patch their meson.build files and add a "static: true" to their dependencies. For example to compile a static pango with a static cairo, I needed to add static:true to the dependency('cairo') call. Surprisingly, simply specifiying "-Ddefault_library=static" wasn't sufficient, but probably this option is about sth. different. Nevertheless, I think it would be very nice to have an option to always prefer the static version for all dependencies if it is available. Sth. like "-Dforce_static=true". Hope it makes sense ;-)

**Comment by xclaesse** [comment]
That's indeed an annoying limitation, we don't have a flexible way to define what should be linked static and what should be shared.

**Comment by dreamer** [comment]
It seems like Meson projects are coming up with their own option names to cover this usecase:

Generic options covering several dependencies:

- pacman: [`-Dbuildstatic=<boolean>`](https://git.archlinux.org/pacman.git/tree/meson_options.txt#n4)
- dosbox-staging: [`-Dtry_static_libs=<choices>`](https://github.com/dosbox-staging/dosbox-staging/blob/master/meson_options.txt#L68)
- mesonbuild/fluidsynth: [`-Dtry-static-deps=<boolean>`](https://github.com/mesonbuild/fluidsynth/blob/2.1.7/meson_options.txt#L54)
- zrythm: [`-Dstatic_deps=<boolean>`](https://git.zrythm.org/cgit/zrythm/tree/meson_options.txt#n179)
- libzim: [`-Dstatic-linkage=<boolean>`](https://github.com/openzim/libzim/blob/master/meson_options.txt#L15)

Specific names for a single dependency:

- libspng: [`-Dstatic_zlib=<boolean>`](https://github.com/randy408/libspng/blob/master/meson_options.txt#L4)
- radare2: [`-Dstatic_sys_openssl=<boolean>`](https://github.com/radareorg/radare2/blob/master/meson_options.txt#L36)

*Out of Meson repositories I browsed, it seems like ~20% have this kind of option.*


It seems like adding an officially-supported option (e.g generated per-dependency), or at least coming up with a naming convention would be beneficial.

**Comment by alex-tee** [comment]
+1 for this. i believe it's common for projects to want to build the whole thing statically and a simple way to do it would help

**Comment by dcbaker** [comment]
I'd proposed on IRC that we do something like using a command line option `-Ddependency-linkage=(static|shared|prefer-static|prefer-shared)` (we actually have the semantics for the prefer- variants internally already), and then be able to override specific dependencies using the machine file, something like:
```ini
[dependency linkage]
zlib = 'prefer-static'
glib = 'static'
```

I think that since static vs shared is such an end user specific option it may even make sense to deprecated the `static` keyword in the dependency()/find_library() calls
