### ISSUE TITLE
[Windows|MSVC] Adding additional library search paths?

### ISSUE THREAD

**Issue by Neumann-A** [mesonbuild/meson#7630]
What is the trick to add additional library search paths while configuring?

I tried` /LIBPATH:<path>`, `(-XLinker) -L<PATH>` passed via `c(pp)_linker_args` or `c(pp)_args`. It seems like it is completly ignoring `<lang>_linker_args` while configuring and even removing those arguments in `<lang>_args`
I had to resort to `ENV{LIB}` to make it find the library in question. 
(and i had to use [properties] section instead of [built-in options] to even pass those arguments)

**Comment by nirbheek** [comment]
MSVC works in exactly the same way as any other linker. `c_link_args` can be set. You are doing a typo, it seems?

You should always use `-L -l`. Meson will translate to the appropriate compiler-specific syntax.

**Comment by Neumann-A** [comment]
thx for spotting that. Would be nice if meson would warn about unused properties in native files. 

>You should always use -L -l. Meson will translate to the appropriate compiler-specific syntax.

That did not work. It did not transform -LSomepath to /LIBPATH:somepath 
it also does not check `ar` for `lib.exe`

**Comment by nirbheek** [comment]
> That did not work. It did not transform -LSomepath to /LIBPATH:somepath

That's a bug, because it works for me. I've been using that while cross-compiling gstreamer to UWP.

```python
c_link_args = ['-Lc:/projects/repos/cerbero.git/build/dist/uwp_universal/arm64/lib', '-APPCONTAINER', 'WindowsApp.lib']
```

becomes

```
build intl-8.dll | intl-8.pdb: c_LINKER intl@sha/libintl.c.obj^M
 LINK_ARGS = "/LIBPATH:c:/projects/repos/cerbero.git/build/dist/uwp_universal/arm64/lib" "/nologo" "/release" "/nologo" "/DEBUG" "/PDB:intl-8.pdb" "/DLL" "/IMPLIB:intl.lib" "-APPCONTAINER" "WindowsApp.lib" "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "comdlg32.lib" "advapi32.lib"
```

**Comment by Neumann-A** [comment]
I am using buildtype custom/plain so that meson doesn't try stupid things.

Furthermore uwp apps should **only** link against `WindowsApp.lib` and not those other libraries you have in the list there. Use `c(pp)_winlibs` to set it to only `WindowsApp.lib`.
