### ISSUE TITLE
[meson|cmake] Unable to select _DEBUG configuration for other platforms 

### ISSUE THREAD

**Issue by Neumann-A** [mesonbuild/meson#7631]
due to #7546 there is currently no way to select `_DEBUG` configurations for other platforms than windows if buildtype is set to `custom` or `plain `or for windows if `b_vscrt='none'` 

**cc:** @mensinda @nirbheek 

maybe meson should get it things together what `debug` means and maybe decided that there is need for another option which is called `debuginfo` instead of the current convoluted mess of options. Or simply let the user provide a cmake configuration mapping via a native_file or builtin-option

**Comment by nirbheek** [comment]
Hm, that's true. We should only do the above magic when the `b_vscrt` option is available. On other platforms, we should just use the `debug` option.
