### ISSUE TITLE
Passing base options in non -D-style fashion fails

### ISSUE THREAD

**Issue by blu-base** [mesonbuild/meson#7633]
**Describe the bug**

The the `--option=value` and `--option value` argument styles are not recognized for the base options. Only `-Doption=value` works.

However, the manual states that all three options should work for options (and it does in most cases).

I found this Stackoverflow question, which reported this behavior: https://stackoverflow.com/questions/63549328
Since i can confirm this SO issue, i had the impression, this behavior is not intended. A brief search did reveal similar reports.

**To Reproduce**

To reproduce, use any meson build setup. It shows even in the default, try this:

```
mkdir optiontest && cd optiontest
meson init
meson build --b_lto=true
```
```
usage: meson [-h] {setup,configure,dist,install,introspect,init,test,wrap,subprojects,help,rewrite,compile} ...
meson: error: unrecognized arguments: --b_lto=true
```

Moreover, ` meson build  --b_lto true` does not recognize the argument as well.

However, `meson build -Db_lto=true` works as intended, and configured successfully.

This issue does not just occur with b_lto.
   
  
**Expected behavior**

The following three commands should have the same result:

- `meson build --b_lto=true`
- `meson build --b_lto true`
- `meson build -Db_lto=true` 

**system parameters**

* OpenSUSE Tumbleweed
* python: 3.8.5
* meson 0.55.1
* ninja 1.10.0

-----

Alternatively, if `-D option` is the intended way to specify options, then the manual at this [location](https://mesonbuild.com/Builtin-options.html) might be changed to point out the suggested way, and the other styles only might work.  `meson setup --help` is showing only `[-D option]` for general use as well.

**Comment by xclaesse** [comment]
`--option` only applies to built-in options. So the first 2 tables: directories and core options.

**Comment by blu-base** [comment]
I see, i did not notice the same head levels of Universial options and Base options.

Would it be reasonable to propose a change in https://github.com/mesonbuild/meson/blob/master/docs/markdown/Builtin-options.md to point this out?

Since some options have a different label in `--option` and `-D option`, considering the labels with underscores (in the tables).
compare the specified arguments of `meson setup --help` with the table in https://github.com/mesonbuild/meson/blob/master/docs/markdown/Builtin-options.md


I would propose something like this:

> A list of these options can be found by running `meson --help`. All these can be set by passing to meson (aka meson setup) in this way `-Doption=value`, or by setting them inside `default_options` of `project()` in your `meson.build`. Some options can also be set by `--option=value`, and `--option value` as shown in `meson --help`


Moreover, it might be worth to add a similar information to the sections `Base options` and `Compiler options`.

**Comment by xclaesse** [comment]
The doc could be clarified indeed, I agree it's not clear that applies only to some options and not all.

**Comment by xclaesse** [comment]
btw, the reason it does not apply to other options is because python's argparse needs to know the list of --option in advance, but base/compiler/project options are only known later when adding compilers, etc.

**Comment by blu-base** [comment]
Thanks for letting me know!

I created a PR which adds hints to maybe avoid the misunderstanding i had.
