### ISSUE TITLE
do not show a warning after version compare

### ISSUE THREAD

**Issue by noah1510** [mesonbuild/meson#7635]
if you set the minimum required version to eg. 0.50.0 and use `meson.override_dependency('test', test_dep)` after `if meson.version().version_compare('>=0.54.0')` you still get a warning that a feature newer than the minimum version is used.

I think that either the warning should not be enabled if it is inside of an if version_compare that meets the required version.
If that is too difficult as a workaround a function to allow version specific parts to be enabled would be nice.

**Comment by xclaesse** [comment]
There is already a fix waiting for review: https://github.com/mesonbuild/meson/pull/7594.

**Comment by noah1510** [comment]
I didn't see that one.
In that case I will clone this issue.
