### ISSUE TITLE
WAF build system compatibility

### ISSUE THREAD

**Issue by pwnorbitals** [mesonbuild/meson#7638]
As a follow-up to CMake / make subprojects compatibility, I would like to issue a feature request to be able to use WAF projects as subprojects (https://waf.io/). 

For example in my case, I need to use libCSP (https://github.com/libcsp/libcsp) and sadly I'm stuck. Afaik, my only option would be to re-create the entire build using `meson.build` files

**Comment by mensinda** [comment]
#6920 could be made to work with WAF (cc @xclaesse)

**Comment by xclaesse** [comment]
What are the commands to configure and build? Especially to pass prefix, libdir, etc.

**Comment by mensinda** [comment]
From the looks of https://github.com/libcsp/libcsp/blob/master/wscript and https://waf.io/book/ there is only `--prefix` and building is done by `waf configure <opts>` and `waf build`.

Note: I didn't know WAF existed before reading this issue and I only spent a few minutes glancing over the docs and trying to understand the libcsp wafscript.

**Comment by xclaesse** [comment]
What's not clear is whether is supports out of tree build.

**Comment by rubyFeedback** [comment]
> What's not clear is whether is supports out of tree build.

I think many waf users do not know either. ;-)

The more momentum meson/ninja has, the better, IMO, because for me as a user
it is simpler to work with meson/ninja than with e. g. waf or scons (mpv is still using
waf; right now they seem to consider contemplating to moving a custom build 
system since waf is not so ideal. Custom build systems are also not great, so you
sort of trade-in and trade-out different disadvantages. So the smoother it may be
to transition into meson/ninja, the better IMO for people who rather prefer to 
work with meson. There are not that many waf-based projects, so knowledge 
about it and online documentation is more limited than compared to, say, 
GNU configure, cmake or meson).

**Comment by xclaesse** [comment]
The minimum requirement to use the approach from #6920 are:
- Out of tree build.
- Separate configure/build steps (currently build must be `make` but that can be easily extended)
- Take common directories in configure command line: prefix/libdir/etc
- Read basic env as CFLAGS, CC (if needed I can extend to pass them in command line).
- Remember those env passed at configure step when doing build step (if needed I can extend to set that env at build time too).
- Build step should be able to reconfigure itself when needed.

Any half sane build system would do that, no idea if waf does. I'm not really interested in digging myself, but if someone who knows waf can give me example command lines to configure/build out of tree, I can give it a try.

**Comment by averne** [comment]
Bumping this following conversation yesterday on the IRC.
> * Out of tree build.

Yes, with `waf configure -o <directory>`. The build command (`waf build`) must be run from the specified directory.

> * Separate configure/build steps (currently build must be `make` but that can be easily extended)

Yes, `waf configure`/`waf build`/`waf install`.

> * Take common directories in configure command line: prefix/libdir/etc

Yes, `--prefix=`, `--libdir=`, `--includedir=`.

> * Read basic env as CFLAGS, CC (if needed I can extend to pass them in command line).

Yes, tried CC and CFLAGS.

> * Remember those env passed at configure step when doing build step (if needed I can extend to set that env at build time too).

Yes.

> * Build step should be able to reconfigure itself when needed.

Yes, if the wscript (the file waf takes to generate the project) is modified.

***

Example for building [mpv](https://github.com/mpv-player/mpv) in a custom directory, with clang and some custom flags:
 ```
$ git clone git@github.com:mpv-player/mpv.git && cd mpv
$ ./bootstrap.py # Install waf, could be done from meson run_command
$ CC=clang CXX=clang++ CFLAGS=-Weverything ./waf configure -o custom-build-directory
$ cd custom-build-directory
$ ../waf build # can add --verbose
....
[263/263] Linking mpv
Waf: Leaving directory `/home/averne/Documents/mpv/custom-build-directory'
'build' finished successfully (22.736s)
```

**Comment by xclaesse** [comment]
@averne Hmm, I see mpv has a bootstrap script that downloads waf, the we have to run that local copy? Is that the common way waf works?

**Comment by averne** [comment]
@xclaesse Yes, as far as I know waf is more or less meant to be part of the repo, in order to avoid API breaks. In the case of mpv it's downloaded from another server, but they request a specific version and checksum it.

**Comment by eli-schwartz** [comment]
Interestingly for the mpv case specifically, there is https://github.com/mpv-player/mpv/pull/8840
