### ISSUE TITLE
b_sanitize=address requires b_lundef=false?

### ISSUE THREAD

**Issue by rhd** [mesonbuild/meson#764]
If I don't specify `-Db_lundef=false` at the same time I specify `-Db_sanitize=address` I get linker errors when building shared objects.

```
CC=clang CXX=clang++ meson.py -Db_sanitize=address -Db_lundef=false --buildtype=debugoptimized build-clang-asan
```

This caught me by surprise and took a while to figure out why the linker was failing.

Is it reasonable to automatically set `b_lundef` to false if `b_sanitize` is set to address (and possibly others)?

**Comment by jpakkane** [comment]
I tested this on Ubuntu and GCC works fine with `undef` but Clang does not. This makes things complicated we don't know if this is a gcc/clang behavioural mismatch or if gcc has been patched in Ubuntu to allow missing sanitizer symbols or to make `-fsanitize` link in the necessary symbols. The latter seems like the most sensible thing to me.

A good start would probably be to file a Clang bug about this difference. IMHO it should not complain about missing asan symbols if linker flag `-fsanitize=address` is passed (which we do).

**Comment by rhd** [comment]
My environment is centos 7 with gcc 4.8.5 and clang 3.4.2. It works fine with gcc but not clang - same as you on ubuntu.

**Comment by jpakkane** [comment]
[Reported upstream](https://llvm.org/bugs/show_bug.cgi?id=30333).

**Comment by rhd** [comment]
It seems like there is no resolution in sight to this in the upstream bug report. 

One guys says:
> Perhaps the easiest thing would be to make Clang ignore -Wl,--no-undefined (with a warning) when compiling with a sanitizer enabled. Presumably non-sanitized builds will perform the checks the user is looking for.

Then someone says:
> I've gone down that path previously and it breaks some people using -z defs as part of their configure checks.

Which meson doesn't have to care about - right? So maybe it's safe to have meson remove the `-Wl,--no-undefined` if a ASAN is specified?

**Comment by jpakkane** [comment]
Meson does not have functionality to set the default value of an option based on another option. Adding it would take a fair bit of work.

**Comment by rhd** [comment]
Maybe output a warning or info string then? It took a fair bit of googling to figure out what was happening when I came across this issue.

**Comment by NickeZ** [comment]
setting `LDFLAGS=-lasan` seems to be a workaround for this issue.
