### ISSUE TITLE
Instructions to run scan-build are broken

### ISSUE THREAD

**Issue by mcatanzaro** [mesonbuild/meson#7644]
**Describe the bug**
https://mesonbuild.com/howtox.html#use-clang-static-analyzer says that this should work:

```
$ meson compile scan-build
```

But it doesn't work. When running that command in a build directory, meson 0.55.0 prints:

```
$ meson compile scan-build
Found runner: /usr/bin/ninja

ERROR: Can't invoke target `scan-build`: target not found
```

Now, meson really has generated a usable scan-build target. Executing `ninja scan-build` works perfectly fine. I have no clue why `meson compile` doesn't see the target.

**To Reproduce**
I think this bug occurs for every meson project. I've tested epiphany and glib-networking.

**Expected behavior**
`meson compile` should be able to do a scan-build.

**system parameters**
* native build
* Fedora 32
* Python 3.8.5
* meson 0.55.0
* ninja 1.10.0

**Comment by Volker-Weissmann** [comment]
Same here.
