### ISSUE TITLE
WINDRES environment variable not respected in Ninja build

### ISSUE THREAD

**Issue by francesco-st** [mesonbuild/meson#7645]
## Problem statement

When setting the WINDRES environment variable Meson does not actually use its value in the Ninja build file.

For example when using the variable:

```sh
export WINDRES="windres -F pe-i386"
```
the arguments `-F pe-i386` does not appear in the ninja build file and windres is not called with the `-F pe-i386` arguments as requested.

Please note that when the command `meson setup` is given Meson acknowledges the WINDRES variable. Here an excerpt from the output:
```
Using 'WINDRES' from environment with value: 'windres -F pe-i386'
Windows resource compiler: GNU windres (GNU Binutils) 2.33.1
```

## Reproduce the problem

Please find in attachment a minimal test case to illustrate the problem. If the variable WINDRES is set and exported, it is ignored by Meson in the ninja build file.

[windres-test.tar.gz](https://github.com/mesonbuild/meson/files/5095774/windres-test.tar.gz)

## Expected behavior

the WINDRES environment variable should be used to call windres in the ninja build file.

## system parameters

- plain native build
- the OS is Windows 10 on x64 using MSYS2
- Meson 0.55.1 (provided by the MSYS package mingw32/mingw-w64-i686-meson)
- Python version is 3.8.5 (provided by the MSYS package mingw32/mingw-w64-i686-python)
- Ninja version is 1.10.0 (provided by the MSYS package mingw32/mingw-w64-i686-ninja)

**Comment by nirbheek** [comment]
This is a regression in 0.55.
