### ISSUE TITLE
Support excluding some targets from some sanitizers

### ISSUE THREAD

**Issue by Nikratio** [mesonbuild/meson#7646]
I have a project where a few binaries are incompatible with some of the sanitizers (`b_sanitize=<..>`). As far as I can tell, these options are all or nothing, i.e. I can't compile the project with sanitization enabled for all but a few targets.

It would be great to have some facility to support this. Currently I have to temporarily comment out the corresponding target definitions.

**Comment by jpakkane** [comment]
You can already override any option for individual targets with the `override_options` kwarg. So something like:

```meson
executable(..., override_options: ['b_sanitize=none'])
``´

**Comment by Nikratio** [comment]
Yeah, but that would overwrite the sanitizer unconditionally, wouldn't it?

I would like semantics of the form "compile this binary with default options (including sanitizer), unless the specified sanitizer is `address`". In other words, the binary should still be compiled with e.g. the thread sanitizer if this is set with `meson configure`.

**Comment by jpakkane** [comment]
In that case you could do something like:

```meson
if get_option('b_sanitize') == 'address'
    overrides = ['b_sanitize=none']
else
    overrides = []
endif

executable(..., override_options: overrides)
```

**Comment by Nikratio** [comment]
That works nicely, thanks!
