### ISSUE TITLE
Feature, the genearted build.ninja are the same size but not stable.

### ISSUE THREAD

**Issue by lygstate** [mesonbuild/meson#7649]
**Describe the bug**
When the same copy of code using meson to genearting the build.ninja file twice,
these two build.ninja file have the same size, but the content are not exactly the same.
The genearted rules are not orderd.

I suggest to genearte those rules in a sorted way to keep build.ninja stable

**To Reproduce**
Please include your `meson.build` files, preferably as a minimal toy example showing the issue.
You may need to create simple source code files (don't include private/proprietary code).

**Expected behavior**

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
* what Python version are you using e.g. 3.8.0
* what `meson --version`
* what `ninja --version` if it's a Ninja build

**Comment by xclaesse** [comment]
Why does it matter?

**Comment by lygstate** [comment]
easy testing and debugging

**Comment by eli-schwartz** [comment]
What precisely are you trying to test and debug?
