### ISSUE TITLE
clang and install_rpath

### ISSUE THREAD

**Issue by rhd** [mesonbuild/meson#765]
I'm using clang 3.4.2 and from what I can tell `install_rpath` doesn't seem to be working correctly.

I have it set like this:
```
executable('app', 'main.cpp',
    dependencies: [platform_dep, cli_dep],
    install: true,
    install_rpath: '$ORIGIN/../lib64',
)
```

This works when I build/install with gcc . It doesn't work when I build/install with clang.

After install with clang, ldd shows:
```
	common/MDP/libcommon.so => not found
```

After install with gcc, ldd shows:
```
	libcommon.so => /path/to/currentdir/./dist/bin/../lib64/libcommon.so (0x00007f076864b000)
```

See anything obvious I'm screwing up?

**Comment by jpakkane** [comment]
What is the output of running ldd on the shared library while it is still in the build dir?

**Comment by rhd** [comment]
That's interesting. `app` as it lives in the build-clang directory is also unable to find the shared libraries.

```
12:13 $ ldd ./build-clang/app
<snip>
	common/MDP/libcommon.so => not found
<snip>
```

Compared to the gcc version which looks ok.

libcommon is built like this:

```
common = library('common', src,
    include_directories: [platform_inc, infrastructure_inc],
    dependencies: [boost_dep],
    install: true,
)

common_dep = declare_dependency(
    link_with: common,
    include_directories: [common_inc, platform_inc, infrastructure_inc],
    dependencies: [boost_dep],
)
```

**Comment by jpakkane** [comment]
What is the RPATH in that binary on GCC vs Clang? You can get this by running `python3 path/to/meson/mesonbuild/scripts/depfixer.py path/to/bin`.

**Comment by rhd** [comment]
The RPATH for the gcc vs clang binary is identical (except for the build dir) - it looks good.

```
13:47 $ objdump -x build-clang/ECS/MDP/Main/app | grep RPATH
  RPATH                /path/to/build-clang/ECS/MDP/Main:/path/to/build-clang/common/MDP:/path/to/build-clang/ECS/MDP/Main/libcli
```

The difference is that the ldd shows the clang version of the binary is using relative paths vs the gcc version is using full paths.

Can you think of any reason why the search rpath is different? relative vs absolute...

**Comment by rhd** [comment]
just confirmed that `depfixer.py` shows the same thing

**Comment by jpakkane** [comment]
What is the rpath set to in the command invocation? You can see it with 'ninja -v'.

**Comment by rhd** [comment]
After install, the rpath is set to:

gcc vs clang:
```
14:10 $ objdump -x dist-gcc/bin/app |grep RPATH
  RPATH                $ORIGIN/../lib64
14:10 $ objdump -x dist-clang/bin/app |grep RPATH
  RPATH                $ORIGIN/../lib64
```

but `ldd` shows
gcc vs clang:
```
14:11 $ ldd dist-gcc/bin/app
<snip>
	libcommon.so => /full/path/to/dist-gcc/bin/../lib64/libcommon.so (0x00007f61c3ff8000)

14:10 $ ldd dist-clang/bin/app
<snip>
	common/MDP/libcommon.so => not found
```

Notice the difference? One has `common/MDP` and one doesn't.

Ninja is doing this:
```
[61/66] clang++    -o MDP/Main/app 'MDP/Main/app@exe/main.cpp.o' '-Wl,--no-undefined'  'common/MDP/libcommon.so' <snip other .so> '-pthread' '-lboost_system' '-lboost_system' '-lrt' '-lcrypt' '-Wl,-rpath,/path/to/build-clang/MDP/Main:/path/to/build-clang/Shared/Infrastructure:/path/to/build-clang/common/MDP:/path/to/build-clang/MDP/Main/libcli' 
```

Is there a max size for the rpath line?

**Comment by jpakkane** [comment]
Paste also GCC's linker invocation line for comparison.

**Comment by rhd** [comment]
```
[65/66] ccache c++    -o MDP/Main/app 'MDP/Main/app@exe/main.cpp.o' '-Wl,--no-undefined' 'common/MDP/libcommon.so' <snip .so list> '-pthread' '-lboost_system' '-lboost_system' '-lrt' '-lcrypt' '-Wl,-rpath,/path/to/build-gcc/MDP/Main:/path/to/build-gcc/Shared/Infrastructure:/path/to/build-gcc/common/MDP1:/path/to/build-gcc/MDP/Main/libcli' 
```

**Comment by rhd** [comment]
Here is a diff that demos the problem. When built with clang, the .so can't be found.

```diff
diff --git a/test cases/common/6 linkshared/cpplib.cpp b/test cases/common/6 linkshared/cpplib.cpp
deleted file mode 100644
index 8b3e0d2..0000000
--- a/test cases/common/6 linkshared/cpplib.cpp	
+++ /dev/null
@@ -1,9 +0,0 @@
-#if defined _WIN32
-    #define DLL_PUBLIC __declspec(dllexport)
-#else
-    #define DLL_PUBLIC __attribute__ ((visibility ("default")))
-#endif
-
-int DLL_PUBLIC cppfunc() {
-    return 42;
-}
diff --git a/test cases/common/6 linkshared/foo/cpplib.cpp b/test cases/common/6 linkshared/foo/cpplib.cpp
new file mode 100644
index 0000000..8b3e0d2
--- /dev/null
+++ b/test cases/common/6 linkshared/foo/cpplib.cpp	
@@ -0,0 +1,9 @@
+#if defined _WIN32
+    #define DLL_PUBLIC __declspec(dllexport)
+#else
+    #define DLL_PUBLIC __attribute__ ((visibility ("default")))
+#endif
+
+int DLL_PUBLIC cppfunc() {
+    return 42;
+}
diff --git a/test cases/common/6 linkshared/foo/meson.build b/test cases/common/6 linkshared/foo/meson.build
new file mode 100644
index 0000000..01c864d
--- /dev/null
+++ b/test cases/common/6 linkshared/foo/meson.build	
@@ -0,0 +1 @@
+cpplib = shared_library('mycpplib', 'cpplib.cpp')
diff --git a/test cases/common/6 linkshared/meson.build b/test cases/common/6 linkshared/meson.build
index 846b4a0..cf5121c 100644
--- a/test cases/common/6 linkshared/meson.build	
+++ b/test cases/common/6 linkshared/meson.build	
@@ -7,6 +7,7 @@ exe = executable('prog', 'main.c', link_with : lib, install : true)
 
 test('runtest', exe)
 
-cpplib = shared_library('mycpplib', 'cpplib.cpp')
+subdir('foo')
+
 cppexe = executable('cppprog', 'cppmain.cpp', link_with : cpplib)
 test('cpptest', cppexe)
```

**Comment by rhd** [comment]
Here are the results from the `6 linkshared` test with the above patch (which basically moves `cpplib.cpp` into a `foo` directory).

#### clang
```
ldd build-clang/cppprog
	linux-vdso.so.1 =>  (0x00007ffca8383000)
	foo/libmycpplib.so => not found
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd80b03a000)
	/lib64/ld-linux-x86-64.so.2 (0x000055ea5419d000)
```

#### gcc
```
ldd build/cppprog
	linux-vdso.so.1 =>  (0x00007ffdebed2000)
	libmycpplib.so => /tmp/meson/test cases/common/6 linkshared/build/foo/libmycpplib.so (0x00007fc72cfc3000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc72cbcd000)
	/lib64/ld-linux-x86-64.so.2 (0x0000561f98c6d000)
```

**Comment by jpakkane** [comment]
Dunno if related but the link args above are different. The relevant bit:

    clang: :/path/to/build-clang/common/MDP:
    gcc:    :/path/to/build-gcc/common/MDP1:

Should it have the 1 or not? Which one is correct?

**Comment by rhd** [comment]
It's not related - the `1` got chopped when I was cleaning up the line.

I'd focus on the test case that shows the same problem but in a way you can reproduce. Let me know if that diff isn't good enough.

Thanks!

**Comment by rhd** [comment]
Hi Jussi,

I just tested this again with the latest master. The issue is still there. Is there anything else you'd like me to try? As it stands, building an exe with clang that uses shared objects is completely broken for some reason :/

**Comment by jpakkane** [comment]
Sorry, this week has been busy in a conference. However we have worked on a new class of tests that allows us to test that installed rpath is correct. Hope to work on this this weekend or early next week.

**Comment by jpakkane** [comment]
I wrote a test for install_rpath and it seems to be working correctly. You can test this with the currently unmerged unittest branch.

During this I found a different bug where sonames were not being set up correctly. This is MR #848. Feel free to try that one as well.

**Comment by rhd** [comment]
Thanks Jussi, it looks good. :+1:
