### ISSUE TITLE
NINJA variable requires .exe suffix unless path searching is done

### ISSUE THREAD

**Issue by bonzini** [mesonbuild/meson#7659]
Under Windows, if a full path is included in the `NINJA` variable it must include the .exe suffix:

* NINJA=ninja - works
* NINJA=C:/msys64/mingw64/bin/ninja - fails
* NINJA=C:/msys64/mingw64/bin/ninja.exe - works

**Comment by bonzini** [comment]
We should also check if `find_program` has the same limitation.

On MSYS, `command -v foo` does not include a .exe extension so it's possible to get an environment variable without .exe extension that way.

**Comment by nirbheek** [comment]
> We should also check if `find_program` has the same limitation.

We have a fairly verbose test for `find_program()` that already checks this: https://github.com/mesonbuild/meson/blob/master/run_unittests.py#L5446, so we could 'just' change `detect_ninja()` to use `ExternalProgram`.
