### ISSUE TITLE
Argument is not an external dependency

### ISSUE THREAD

**Issue by agauniyal** [mesonbuild/meson#766]
```
Meson encountered an error in file src/meson.build, line 3, column 0:
Argument is not an external dependency
```

On using `json` dependency as -

in **`meson.build`**
```
....
json_sp = subproject('json')
json_dep = json_sp.get_variable('json_dep')
....
```

and in **`src/meson.build`**
```
prog_sources = ['one.cpp', 'two.cpp', 'three.cpp']

corelib = library('myAwesomeLib', prog_sources,
		include_directories: inc,
		dependencies: ['someOtherFine_dep', 'json_dep'])
```

and I've[1] myself defined `declare_dependency` in json's meson.build as - 

```
inc = include_directories('src')

json_dep = declare_dependency(include_directories:inc)
```

What's wrong here?

[1] https://github.com/mesonbuild/meson/wiki/Wrap%20dependency%20system%20manual#using-wrapped-projects

**Comment by jpakkane** [comment]
I just updated the error message that gets printed when you do this. Please pull master and try again.

**Comment by rhd** [comment]
The other issue is `dependencies: ['someOtherFine_dep', 'json_dep']` - those shouldn't be strings.

**Comment by agauniyal** [comment]
Ah yes, I'm always confusing b/w variables and strings with meson. This would be it definitely 😆 .
