### ISSUE TITLE
[cmake module] custom target arguments are merged, producing errors

### ISSUE THREAD

**Issue by w0xel** [mesonbuild/meson#7665]
**Describe the bug**
When using CMake subprojects with custom targets using generated sources, meson sometimes merges the arguments creating failing custom_targets within the generated meson.build file.

I created a repository showing the bug in a minimal example here: https://github.com/w0xel/meson_cmake_module_bug_example

**To Reproduce**
See linked repository above

**Expected behavior**
The meson CMake module should produce correct custom_targets for the CMake custom commands

**system parameters**
* native build
* Ubuntu 20.04
* Python 3.8.2
* meson 0.55.1 (meson git doesn't work either as of 6fc06734)
* ninja 1.10.0

**Comment by mensinda** [comment]
What CMake version are you using? If it is <3.17, could you please test again with CMake >=3.17? See #7601.

**Comment by w0xel** [comment]
Works with CMake 3.18.1
