### ISSUE TITLE
Extend Python module to allow building python packages (alternative to setuptools)

### ISSUE THREAD

**Issue by igo95862** [mesonbuild/meson#7695]
Package in this context is as defined in https://docs.python.org/3.8/reference/import.html#packages aka directory with \_\_init\_\_.py and *.py files

Currently Python module can only build C extensions. (unless I missed something)

I suggest adding functions that will create python package build target

    shared_module py_installation.python_module(module_name, ...)

The arguments could be byte code compilation (optimization level etc.)

This should not take a lot of implementation code as Python standard library has a lot of utilities for this task. compileall module for compiling byte code, pkgutil to discover packages and modules.

This should allow meson to become self hosting. Currently meson depends on setuptools for building which is not a part of python standard library.

I can create a pull request with implementation but I need OK before implementing it as it can be out of scope of the project.

**Comment by FRidh** [comment]
```meson
# Pure Python sources
python_sources = [
    '__init__.py', 
    '__main__.py', 
]

# Install pure Python
python.install_sources(
    python_sources,
    pure: false, # Will be installed next to binaries (this was for an example of mine)
    subdir: 'greetpkg'  # Folder relative to site-packages to install to
)
```
See https://github.com/FRidh/mesonpep517examples.

**Comment by igo95862** [comment]
> site-packages folder

Yes but Python only packages. Your example mixed C extension.  Currently making pure python installations involves too much busy work. For example, why should the package directory `subdir: 'greetpkg'` be given when it already is in the directory 'greetpkg'

This is how I would do it in your example. (also rename the greetpkg top folder to src because it contains the source not the actual package)
```
src -
    meson.build
    greet.c
    greetpkg -
         __init__.py
        __main__.py
```

meson.build would something like this roughly
```
module = python.extension_module(
    'greet', # Name of the module
    [  # List of sources
        'greet.c' 
    ],
)

python_package = python.python_module('greetpkg', include_extension_modules: module)
```

Also make 'python' should be a valid project language.

**Comment by igo95862** [comment]
The issue is that setuptools were not created with linux packaging in mind.


[Look at how meson installs its man.](https://github.com/mesonbuild/meson/blob/master/setup.py#L43) This method is actually [deprecated](https://setuptools.readthedocs.io/en/latest/setuptools.html#new-and-changed-setup-keywords). So setuptools provide no way to install man pages, desktop entries or any other file in to file system. I also have an issue with how entry points are generated (never using optimized byte code or isolated mode) but this could be fixed by creating your own executable script. (that you can't install with setuptools)

**Comment by igo95862** [comment]
I ported my project to meson. https://github.com/igo95862/bubblejail/tree/0.3


Byte code is compiled with script that is passed with `add_install_script` So building occurs in install phase which is a bit not how the stages are supposed to be done.

**Comment by igo95862** [comment]
If you are interested I created a mini bytecode compiler to use with `custom_target` for my project.

https://github.com/igo95862/bubblejail/blob/master/bytecode_compiler.build

```
#!/usr/bin/python3 -IOO

from argparse import ArgumentParser
from compileall import compile_dir
from pathlib import Path
from pprint import pp
from shutil import copy
from sys import argv
from typing import List


def compiler(build_dir: Path, prefix: Path) -> None:
    compile_dir(
        dir=str(build_dir),
        optimize=0,
        workers=0,
        ddir=str(prefix),
    )

    compile_dir(
        dir=str(build_dir),
        optimize=2,
        workers=0,
        ddir=str(prefix),
    )


def copy_files(source_files: List[Path], output_dir: Path) -> None:
    for x in source_files:
        copy(x, output_dir)


def compiler_main() -> None:
    parser = ArgumentParser()

    parser.add_argument(
        '--input-files',
        action='store',
        required=True,
        type=Path,
        nargs='*',
    )
    parser.add_argument(
        '--output-dir',
        action='store',
        required=True,
        type=Path,
    )

    parser.add_argument(
        '--lib-prefix',
        action='store',
        required=True,
        type=Path,
    )

    names = parser.parse_args()
    pp(names)
    copy_files(names.input_files, names.output_dir)
    compiler(names.output_dir, names.lib_prefix)


if __name__ == "__main__":
    pp(argv)
    compiler_main()

```

This is how meson file looks like:

https://github.com/igo95862/bubblejail/blob/master/bubblejail/meson.build

```

source_files = [
   '__init__.py',
   'bubblejail_cli.py',
   'bubblejail_directories.py',
   'bubblejail_gui_qt.py',
   'bubblejail_helper.py',
   'bubblejail_instance.py',
   'bubblejail_seccomp.py',
   'bubblejail_utils.py',
   'bwrap_config.py',
   'exceptions.py',
   'services.py',
]

bubblejail_package_dir = get_option('libdir') / 'bubblejail/python_packages/bubblejail'

bubblejail_lib_package = custom_target(
    'bubblejail_lib_package',
    build_by_default : true,
    input : source_files,
    output : source_files + ['__pycache__'],
    install : true,
    install_dir : bubblejail_package_dir,
    command : [bytecode_compiler,
               '--input-files', '@INPUT@',
               '--output-dir', '@OUTDIR@',
               '--lib-prefix', get_option('prefix') / bubblejail_package_dir,
               ],
)
```

**Comment by igo95862** [comment]
Looks like it is someone already doing exactly what I described: https://github.com/mesonbuild/meson-python
