### ISSUE TITLE
Linking python extensions against libpython is broken

### ISSUE THREAD

**Issue by tschoonj** [mesonbuild/meson#7712]
**Describe the bug**

Meson has been able to detect [for some time](https://github.com/mesonbuild/meson/issues/4117) if python extensions should be linked against libpython or not. However, this only works if python was found as a `PythonDependency` and not as as `PkgConfigDependency`.

The problem in the code is here:

https://github.com/mesonbuild/meson/blob/efb86088bcf8960db440eadcd11c0e073c80ab52/mesonbuild/modules/python.py#L327-L337

This obviously doesn't work when I add a print statement dumping the dependencies:

```
new_deps=[<Holder: <PkgConfigDependency gstreamer-1.0: True ['>= 1.18.0']>>, <Holder: <PkgConfigDependency python-3.8-embed: True ['>=3']>>, <Holder: <PkgConfigDependency pygobject-3.0: True ['>= 3.8']>>]
```

**To Reproduce**
Just try building a Python extension against a python that ships pkg-config files: the resulting binary will always be linked against libpython.

**Expected behavior**
Linking against libpython should also work when python was detected through its pkg-config file.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? native
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) macOS Catalina
* what Python version are you using e.g. 3.8.0: 3.8, installed with homebrew
* what `meson --version`: 0.55.1
* what `ninja --version` if it's a Ninja build: 1.10.1

@nirbheek @lazka

**Comment by lazka** [comment]
Python has two pkg-config files, one or extensions on for embedding:

```bash
> pkg-config --libs python3

> pkg-config --libs python3-embed
-lpython3.8
```

If you build an extension you should use `python3` which doesn't link.

**Comment by tschoonj** [comment]
The project that is causing problems is [gst-python](https://gitlab.freedesktop.org/gstreamer/gst-python).

There are two plugins being built there, and they seem to enforce using the [embedded python](https://gitlab.freedesktop.org/gstreamer/gst-python/-/blob/master/meson.build#L32-37) for both, while I think only one of them ([the Gst python plugin](https://gitlab.freedesktop.org/gstreamer/gst-python/-/tree/master/plugin)) needs it. The other one is a [PyGobject module](https://gitlab.freedesktop.org/gstreamer/gst-python/-/tree/master/gi/overrides), so should be fine without it.

What do you think @lazka ?

Either way, clearly not a bug in Meson, so closing.

**Comment by lazka** [comment]
> What do you think @lazka ?

I think your assessment is correct.
