### ISSUE TITLE
Forwarding link_args within dependencies causes duplications

### ISSUE THREAD

**Issue by rhd** [mesonbuild/meson#7744]
I'm getting linker errors when I use `link_args` in a `declare_dependency()` because the `link_args` gets duplicated.

**To Reproduce**

```
# meson.build

project('test', 'cpp', default_options: ['buildtype=debugoptimized'])

dep_base = declare_dependency(
    compile_args: ['-Dfoo'],
    link_args : ['-Xlinker', '-Map=/path/to/output.map', '-Wl,-T', '-Wl,/foo/bar'],
)

dep1 = declare_dependency(

    dependencies: [dep_base],
)

dep2 = declare_dependency(
    dependencies: [dep1],
)

executable('main1', 'main.cpp',
    dependencies: [dep1],
)

executable('main2', 'main.cpp',
    dependencies: [dep2],
)
```

```
# cross.txt
[binaries]
c='gcc'
cpp='g++'
strip='strip'

[properties]
cpp_link_args = ['-lm']
```

**Expected behavior**

I'd expect `-Xlinker -Map=/path/to/output.map` to appear on the gcc command line once. But it appears twice - once in the middle somewhere near all the libs getting linked in and once again at the end of the linker line.

If I do this, it only appears once

```
executable('foo', 'foo.cpp',
  dependencies: [dep1],
)
```

So by forwarding the `link_args`, it's causing it to be duplicated from what I can tell.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? `cross`
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) `CentOS7`
* what Python version are you using e.g. 3.8.0 - `3.6`
* what `meson --version` - `0.55.1`
* what `ninja --version` if it's a Ninja build - `1.7.2`

**Comment by rhd** [comment]
I'm unable to create a small project that duplicates the issue I'm seeing with the larger project. I've updated the 1st post with my test `meson.build` and `cross.txt` files.

I'm going to close it until I figure out a way to reproduce.

**Comment by maureeungaro** [comment]
I'm having this exact issue, was it ever addressed?
