### ISSUE TITLE
Subproject defined subproject directory not found

### ISSUE THREAD

**Issue by michaelbrockus** [mesonbuild/meson#7768]
**Describe the bug**
I'm building a Game with SDL2 and SDL2_ttf. Suddenly when I start building the project and have the dependencies downloaded with WrapDB magic SDL2_ttf subproject with custom-defined as `external` was not found. But if I add its dependency wrap file `freetype2.wrap` in my projects subprojects directory it just works.

I am not sure but I shouldn’t have to add a sub-dependency from dependency when that sub-dependency
should live in the package I’m trying to use in the first place.

Error message in question.

```console
|Executing subproject sdl2_ttf method meson 
|
|Project name: sdl2_ttf
|Project version: 2.0.12
|C compiler for the host machine: cc (clang 11.0.3 "Apple clang version 11.0.3 (clang-1103.0.32.62)")
|C linker for the host machine: cc ld64 556.6
|Library m found: YES

subprojects/SDL2_ttf-2.0.12/meson.build:10:0: ERROR: Subproject directory not found and freetype2.wrap file not found

A full log can be found at /Users/mike/Desktop/github/paper_rock_scissors/build/meson-logs/meson-log.txt
mike@Michaels-MBP paper_rock_scissors %                                
```

**To Reproduce**

This is a visual map of how this is structured. [MAP](https://github.com/michaelbrockus/cpp_project_template) 

`./meson.build`
```meson
project('app', 'cpp',
    meson_version : '>=0.55.0',
    version : '0.1.0',
    license : 'apache-2.0',
    default_options : ['layout=flat', 'strip=true', 'werror=true', 'cpp_std=c++2a'])

subdir('modules')
```

`modules/meson.build`
```meson
subdir('code')
subdir('main')

if get_option('with_tests') == true
    subdir('test')
endif
```

`modules/test/meson.build`
```meson
unity = subproject('unity')

test_exe = executable('test-prog',
    files('test_runner.cc', 'test_cases.cc'),
    dependencies : [unity.get_variable('unity_dep'), code_dep])

test('Running: Project unit test', test_exe)
```

`modules/main/meson.build`
```meson
executable('prog', files('main.cc'), dependencies: code_dep, install: true)
```

`modules/code/meson.build`
```meson
sdl2_dep = subproject('sdl2', default_options : ['werror=false'])
sdl2_ttf_dep = subproject('sdl2_ttf')

code_lib = library('code-lib', files('project.cc'),
    cpp_args: '-DBUILDING_PROJECT',
    dependencies: [
        sdl2_dep.get_variable('sdl2_dep'),
        sdl2_ttf_dep.get_variable('sdl2_ttf_dep')],
    include_directories: '.',
    install: true)

code_dep = declare_dependency(
    link_with: code_lib,
    dependencies: [
        sdl2_dep.get_variable('sdl2_dep'),
        sdl2_ttf_dep.get_variable('sdl2_ttf_dep')],
    include_directories: '.')
```

**Expected behavior**
I expect that a subproject with a custom subproject directory should be able to
to find its subproject directory with no trouble.

**system parameters**
* Plain native build (for the same computer)
* MacOS Catalina
* what Python version 3.8.5
* what `meson 0.55.3`
* what `ninja 1.10.0.post2`

**Comment by xclaesse** [comment]
I think this is the kind of situation fixed by https://github.com/mesonbuild/meson/pull/6968

**Comment by michaelbrockus** [comment]
Ok well that means I need to re wrap SDL2_ttf this time using the provides section. Thanks.
