### ISSUE TITLE
Lack tests for msys2 msys2-x64 CI tests

### ISSUE THREAD

**Issue by lygstate** [mesonbuild/meson#7778]
**Describe the bug**
The CI only tests msys2 mingw32/mingw64, there is no testing
of msys2-x64

**To Reproduce**
Please include your `meson.build` files, preferably as a minimal toy example showing the issue.
You may need to create simple source code files (don't include private/proprietary code).

**Expected behavior**

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
* what Python version are you using e.g. 3.8.0
* what `meson --version`
* what `ninja --version` if it's a Ninja build

**Comment by lazka** [comment]
The msys2 cygwin subsystem isn't really intended for developing, just for providing tools the can be used to build mingw packages, so not sure how useful that is.

(also x86 msys doesn't exist anymore)

**Comment by lygstate** [comment]
> The msys2 cygwin subsystem isn't really intended for developing, just for providing tools the can be used to build mingw packages, so not sure how useful that is.
> 
> (also x86 msys doesn't exist anymore)

Ah, you means there is no msys2 package need meson? Then we can skip it totally.

**Comment by lazka** [comment]
> Ah, you means there is no msys2 package need meson? Then we can skip it totally.

There is, pacman for one, but we don't want MSYS2 users to build things with meson there. The subsystem is mostly like cygwin anyway, so testing with cygwin should be enough.
