### ISSUE TITLE
run target fails

### ISSUE THREAD

**Issue by agauniyal** [mesonbuild/meson#778]
In primary `meson.build`
```
....
run_target('emulate', command : 'scripts/emulate_rasp.sh')
```

In scripts/emulate_rasp.sh
```
#!/bin/sh

cd "${MESON_BUILD_ROOT}"

emulateGpio(){
	mkdir -p $1/debug/raspi/path/gpio$2
	touch $1/debug/raspi/path/export
	touch $1/debug/raspi/path/unexport
}

emulateGpio "app" "4"
emulateGpio "app" "8"
emulateGpio "test" "2"
emulateGpio "test" "3"
emulateGpio "test" "4"
emulateGpio "test" "7"
emulateGpio "test" "8"
```

build ❯ ninja emulate 
[0/1] 'Running external command emulate.'
Could not execute command "s".
FAILED: emulate 
'/usr/bin/python' '/usr/bin/meson' '--internal' 'commandrunner' '/home/agauniyal/projects/isaac-core' '/home/agauniyal/projects/isaac-core/build' '' 's' 'c' 'r' 'i' 'p' 't' 's' '/' 'e' 'm' 'u' 'l' 'a' 't' 'e' '_' 'r' 'a' 's' 'p' '.' 's' 'h'
ninja: build stopped: subcommand failed.
```

**Comment by jpakkane** [comment]
There is a bug, which will be fixed soon. However note that this is not guaranteed to work. The directory the `run_target` is executed in is not specified and can be arbitrary. You should use `find_program` to get your script and the pass that to the command argument.

**Comment by agauniyal** [comment]
@jpakkane I'm doing `cd "${MESON_BUILD_ROOT}"` in my script first. and every operation after it is relative to build directory. Still wouldn't work?

**Comment by jpakkane** [comment]
No, because your script might never get invoked. When Ninja invokes `scripts/emulate.sh` it only works if it is done in the parent directory of that script. If it is being invoked in, say, the build dir then `scripts/emulate.sh` will lead to a command not found error.

**Comment by agauniyal** [comment]
well `ninja` would be executed only in `build dir` since it contains the build targets. and run target is another build target, so why should I call ninja in `root dir` and not `build dir`. I guess I'm going to use simple shell script to do this now.

**Comment by jpakkane** [comment]
If your script is in `{src_root}/scripts/emulate.sh` and you run the command `scripts/emulate.sh` in `{build_root}` (which is what Ninja does) it will fail regardless of whether it is invoked by Ninja or by hand. The script is simply not there. Assuming that the build dir is at the top level of your source tree, the command needed to invoke it is `../scripts/emulate.sh`. `find_program` works this out for you.

**Comment by agauniyal** [comment]
Ah okay, I clearly misunderstood. Thanks :+1:
