### ISSUE TITLE
https://codecov.io/gh/mesonbuild/meson/branch/master are not up to date.

### ISSUE THREAD

**Issue by lygstate** [mesonbuild/meson#7784]
**Describe the bug**
The code coverate are three years ago result
https://codecov.io/gh/mesonbuild/meson/branch/master

**To Reproduce**
Please include your `meson.build` files, preferably as a minimal toy example showing the issue.
You may need to create simple source code files (don't include private/proprietary code).

**Expected behavior**

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
* what Python version are you using e.g. 3.8.0
* what `meson --version`
* what `ninja --version` if it's a Ninja build

**Comment by eli-schwartz** [comment]
codecov.io is properly updated these days.
