### ISSUE TITLE
Difficulty promoting wraps that use patch_directory

### ISSUE THREAD

**Issue by nnooney** [mesonbuild/meson#7788]
**Describe the bug**
I have a Meson project (let's call it project A) that contains the following wrap definition:

```
[wrap-git]
directory = googletest
url = https://github.com/google/googletest.git
revision = head
patch_directory = googletest
```

I want to include project A in another Meson project (let's call it project B). I use the following wrap definition in project B in order to include project A:

```
[wrap-git]
directory = project-a
url = https://github.com/nnooney/project-a.git
revision = head
```

When I try to build project B, Meson tells me that I need to promote the dependency on googletest:

```
|../subprojects/project-a/src/meson.build:4: WARNING: Dependency googletest not found but it is available in a sub-subproject.
|To use it in the current project, promote it by going in the project source
|root and issuing the following command: 
|meson wrap promote subprojects/project-a/subprojects/googletest.wrap
```

I promote the wrap as described, and then I get the following error when trying to build:

```
../subprojects/project-a/src/meson.build:4:0: ERROR: patch directory does not exists: googletest
```

**To Reproduce**
See description above

**Expected behavior**
It seems like wrap file promotion also should promote the packagefiles directory in order for the build to succeed, or Meson should provide a different instruction in order to include the subproject (such as copying `subprojects/project-a/subprojects/*` to `subprojects/`).

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? **native build**
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) **WSL using Debian**
* what Python version are you using e.g. 3.8.0 **3.8.5**
* what `meson --version` **0.55.1**
* what `ninja --version` if it's a Ninja build **1.10.1**

**Comment by xclaesse** [comment]
Hmm, that's true that promoting the wrap file does not copy the patch directory with it. I have a PR that eliminate the need of promoting wraps: https://github.com/mesonbuild/meson/pull/6968.

**Comment by ilsme** [comment]
Same problem here. 

Currently, I decided to commit all wraps for dependencies with packagefiles directory to the main project as there is no other way to promote such dependencies, especially for CI driven builds.

IMO promoting should be performed automatically and silently if there is no ambiguity.

@xclaesse I tried to install your PR version but it works the same way for me, should I specify some additional flags for meson setup?

**Comment by phillipjohnston** [comment]
Just started playing around with this and ran into the same issue myself. I also ran into a problematic case where using local archives instead of cloning the URL, because the .tgz file I have stored in the subproject isn't promoted or searched. Storing multiple copies of all of these files across repositories (and eventually having to update them) is *extremely* problematic. I think that #6968 will be a massive improvement.

```
WARNING: Dependency cmsis-5 not found but it is available in a sub-subproject.
|To use it in the current project, promote it by going in the project source
|root and issuing the following command:
|meson wrap promote subprojects/arm-architecture/subprojects/cmsis-5.wrap

../subprojects/arm-architecture/meson.build:91:0: ERROR: Subproject directory not found and cmsis-5.wrap file not found
```

After promotion:

```
File "/Users/phillip/src/ea/framework/nordic/subprojects/packagefiles/CMSIS_5-5.7.0.tgz" does not exist
```

**Comment by phillipjohnston** [comment]
This should be closed now, IMO. New forwarding wrap file feature works great.

**Comment by xclaesse** [comment]
Happy to hear that, thanks. Closing \o/
