### ISSUE TITLE
Tutorial is broken

### ISSUE THREAD

**Issue by fukanchik** [mesonbuild/meson#7793]
**Describe the bug**
When I follow this tutorial I get an error instead of the build: https://mesonbuild.com/Tutorial.html

**To Reproduce**
Copy paste the C source from the "humble beginning" section and  save it as main.c
Copy paste the meson source and save it in the same directory.
Execute `meson builddir`
Output:
$ meson builddir
The Meson build system
Version: 0.45.1
Source dir: /tmp/0/x
Build dir: /tmp/0/x/builddir
Build type: native build
Project name: tutorial
Native C compiler: cc (gcc 7.5.0 "cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Build targets in project: 1
Found ninja-1.8.2 at /usr/bin/ninja

Execute `cd builddir && meson compile`
Output:
$ cd builddir/
$ meson compile
Error during basic setup:

Neither directory contains a build file meson.build.

**Expected behavior**
A built hello world binary.

**system parameters**
* native build
* ubuntu 18.04
* meson version: 0.45.1
* ninja version: 1.8.2

**Comment by QuLogic** [comment]
> meson version: 0.45.1

Your meson version is too old. Use `ninja build` instead of `meson compile`.

**Comment by michaelbrockus** [comment]
Also don’t forget to add `-C` followed by the build directory name.

**Comment by fukanchik** [comment]
I can build my app with no problem, thank you very much. This ticket is about the tutorial, not the build system itself.

As you saw meson version on my machine is `0.45.1`. In tutorial they use `0.13.0-research`, so I _assume_ mine is much newer than the one required to complete the tutorial successfully.

Having on that page the required meson version for completing tutorial successfully would be helpful.
