### ISSUE TITLE
pkexec logic is a bad idea

### ISSUE THREAD

**Issue by cgwalters** [mesonbuild/meson#7809]
This is a bit related to https://github.com/mesonbuild/meson/issues/4758

Basically, what you're doing with polkit doesn't make sense.  You're allowing to execute arbitrary code (in the Meson build logic) as root; the permission isn't actually limited in any way.  So rather than having meson contain logic to run `pkexec` it's just much saner to tell people to do `sudo meson install` (or `pkexec meson install`) etc.

IOW you should just delete the polkit rules and print an error message telling people how to use `sudo/pkexec` (this is quite commonly documented for other build systems of course).

**Comment by eli-schwartz** [comment]
I agree, but this concern is already raised in #7345 (without however mentioning the keyword "pkexec", only "polkit").

**Comment by smurfix** [comment]
Workaround: `export PKEXEC_UID=99999`.
