### ISSUE TITLE
meson does not support parallel linking for lto enabled builds

### ISSUE THREAD

**Issue by manojkiraneda** [mesonbuild/meson#7820]
As per GCC documentation, it supports -flto[=n], and If you specify the optional n, the optimization and code generation done at link time is executed in parallel using n parallel jobs by utilizing an installed make program. The environment variable MAKE may be used to override the program used. 

As per meson built-in options b_lto can either be true or a false, and it would be great if meson supports passing "n" as well.

**Comment by manojkiraneda** [comment]
@dcbaker fyi ^^^

**Comment by manojkiraneda** [comment]
@dcbaker, just wanna know when are you planning to fix this issue ?

**Comment by dcbaker** [comment]
It's on my list for 0.57.0, I've got some more pressing stuff I need to get done first though

**Comment by manojkiraneda** [comment]
sure @dcbaker , that should work for me. Thanks !

**Comment by nickbroon** [comment]
clang has similar but different parallel LTO flags.
https://clang.llvm.org/docs/ThinLTO.html#controlling-backend-parallelism

It would great if anything enhancement supported both.

**Comment by nickbroon** [comment]
GCC 10 and later also has  -flto=auto which auto detects the number of cores to use.

**Comment by manojkiraneda** [comment]
> GCC 10 and later also has -flto=auto which auto detects the number of cores to use.

Probably i guess auto would deduce number of procs using `nproc` command ?

**Comment by nickbroon** [comment]
> > GCC 10 and later also has -flto=auto which auto detects the number of cores to use.
> 
> Probably i guess auto would deduce number of procs using `nproc` command ?

It doesn't use `nproc` but calculates the number directly in C code. See https://github.com/gcc-mirror/gcc/commit/200b0e7e82c8dce95aa9afeec23579b8a7e19dce

**Comment by nickbroon** [comment]
The following snippet worked in autoconf to use parallel LTO.
meson's LTO support is great, but extending it to include parallel LTO would really help with build times.
```
AC_ARG_WITH([lto], AS_HELP_STRING([--without-lto], [Build without link time optimisation]))
AS_IF([test "x$with_lto" != "xno"],
      # Do parallel LTO if the compiler supports it as it's quicker
      [AX_CHECK_COMPILE_FLAG([-Werror -flto=1], 
                                                        [AC_SUBST(DATAPLANE_LTO_FLAG, '-flto=$(shell nproc)')],
                                                        [AC_SUBST(DATAPLANE_LTO_FLAG, '-flto')])
])
```
