### ISSUE TITLE
CUDA compiler header check support

### ISSUE THREAD

**Issue by zzzoom** [mesonbuild/meson#7825]
I'm trying to detect the presence of CUB in the CUDA toolkit with something similar to:

```meson
if not meson.get_compiler('cuda').has_header('cub/version.cuh')
    cuda_includes += include_directories('cub-1.8.0')
endif
```
However, using `has_header` or `has_header_symbol` on a CUDA compiler with Meson 0.55.3 results in:

`ERROR: Language Cuda does not support header symbol checks.`

Is this due to an `nvcc` limitation or just because nobody has implemented it yet?

**Comment by jpakkane** [comment]
Probably the latter.

**Comment by zzzoom** [comment]
The cuda compiler has a [definition of `has_header_symbol`](https://github.com/mesonbuild/meson/blob/e36f713a7f5cc10d3f8adc7ae1c73ef6cce51082/mesonbuild/compilers/cuda.py#L169), however it calls `super().has_header_symbol` in Compiler, which always throws.

**Comment by dcbaker** [comment]
It looks like the `has_header_symbol` has been broken since it landed :(

It looks like it just needs the call to super() and the check of super()'s return value to be removed. But I don't have an machine that runs cuda to check on. If you can test and want to send an MR I'll review it for you.
