### ISSUE TITLE
Meson disregards exported LDFLAGS in makepkg.conf and doesn't support explicit linking with CC_LD ="xild" (Intel ICC toolchain)

### ISSUE THREAD

**Issue by ms178** [mesonbuild/meson#7826]
**Describe the bug**

While trying to compile Mesa-git with the Intel ICC compiler toolchain through makepkg on Manjaro, I get the following error if I specify CC_LD to be xild (with Method 1 from https://wiki.archlinux.org/index.php/Intel_C%2B%2B):

mesa/meson.build:21:0: ERROR: Unsupported linker, only bfd, gold, and lld are supported, not xild.

Meson will also disregard my custom exported environment variable which I set for LDFLAGS in makepkg.conf and will use the standard LDFLAGS in makepkg.conf and succeeds in building Mesa.

The outcome is a bit different with Method 2 from https://wiki.archlinux.org/index.php/Intel_C%2B%2B, with this method it honors the exported LDFLAGS from the amended Mesa PKGBUILD file, but I also hit the same error from above if I try to specify CC_LD explicitly (that is if I change the Mesa PKGBUILD entry from `export LD="xild"` to `export CC_LD="xild"`).

**To Reproduce**

Method 1 in the ARCH wiki for ICC recommends to ammend the makepkg.conf file with the following entries after CXXFLAGS (except for the CC_LD part which I added due to meson's weird behavior regarding LDFLAGS, standard is `export LD="xild"`):

`
_CC=icc
if [ $_CC = "icc" ]; then
export CC="icc"
export CXX="icpc"
export CFLAGS="-O3 -march=native -mtune=native -qopenmp -qopenmp-simd -qopt-dynamic-align -qopt-mem-layout-trans=2 -qopt-prefetch=5 -parallel -par-loops=new -ipo12 -auto-ilp32 -auto-p32 -fast"
export CXXFLAGS="${CFLAGS}"
export LDFLAGS="-Wl,-O2,--as-needed"
export AR="xiar"
export CC_LD="xild"
fi
LDFLAGS="-Wl,-O2,--as-needed,-ipo12" 
`
[The last LDFLAGS settings is not part of setting up ICC anymore and -ipo12 is not meant to be envoked here at all, but I want to illustrate the problem that acccording to the logs meson sets the LDFLAGS from here, even though it should only take my exported and correct LDFLAGS from above into account]

Here is the output of the log file which I get with Method 1 and the settings above:

```
Build started at 2020-10-10T09:30:18.672891
Main binary: /usr/bin/python
Build Options: -Db_ndebug=true -Db_lto=true -Dc_std=c11 -Dcpp_std=c++14 -Dbuildtype=plain -Dprefix=/usr -Dsysconfdir=/etc -Dplatforms=x11,wayland -Ddri-drivers= -Dgallium-drivers=radeonsi -Dvulkan-drivers=amd -Ddri3=enabled -Degl=enabled -Dgallium-extra-hud=true -Dgallium-nine=false -Dgallium-omx=bellagio -Dgallium-va=enabled -Dgallium-vdpau=disabled -Dgallium-xa=disabled -Dgallium-xvmc=disabled -Dgbm=enabled -Dgles1=disabled -Dgles2=enabled -Dglvnd=true -Dglx=dri -Dlibunwind=enabled -Dllvm=enabled -Dlmsensors=enabled -Dosmesa=none -Dshared-glapi=enabled -Dgallium-opencl=icd -Dvalgrind=disabled -Dvulkan-overlay-layer=true -Dvulkan-device-select-layer=true '-Dtools=[]' -Dzstd=enabled -Dwrap_mode=nofallback
Python system: Linux
The Meson build system
Version: 0.55.3
Source dir: /home/marcus/Downloads/mesa-git/src/mesa
Build dir: /home/marcus/Downloads/mesa-git/src/_build
Build type: native build
Program python found: YES
Running command: /usr/bin/python bin/meson_get_version.py
--- stdout ---
20.3.0-devel
--- stderr ---


None of 'PKG_CONFIG_PATH' are defined in the environment, not changing global flags.
None of 'PKG_CONFIG_PATH' are defined in the environment, not changing global flags.
Project name: mesa
Project version: 20.3.0-devel
Using 'CC' from environment with value: 'icc'
Using 'CFLAGS' from environment with value: '-O3 -march=native -mtune=native -qopenmp -qopenmp-simd -qopt-dynamic-align -qopt-mem-layout-trans=2 -qopt-prefetch=5 -parallel -par-loops=new -ipo12 -auto-ilp32 -auto-p32 -fast'
Using 'LDFLAGS' from environment with value: '-Wl,-O2,--as-needed,-ipo12'
Using 'CPPFLAGS' from environment with value: ''
Using 'CC_LD' from environment with value: 'xild'

mesa/meson.build:21:0: ERROR: Unsupported linker, only bfd, gold, and lld are supported, not xild.
```

**Expected behavior**
I would expect meson to honor my exported LDFLAGS with Method 1 and to also work with both Methods if I explicitly use the CC_LD environment variable to use xild.

**system parameters**
* native build
* Manjaro 20.1.1
* Python version: 3.8.5-2
* meson --version: 0.55.3
* ninja --version: 1.10.1
* ICC version: 19.1.2.254 (gcc version 10.2.0 compatibility)

**Comment by dcbaker** [comment]
As far as I can tell, icc always uses xild, but xild hands of to the linker you pick when it doesn't need xild to do something specific (like lto)

**Comment by ms178** [comment]
By the way, while experimenting with different compiler arguments and methods how to evoke them (e.g. through the PKGBUILD file with c_args and cpp_args), I also hit the error which was mentioned in #6431 quite regularly. I could try to reproduce my steps if it would be of help - at least it doesn't seem to be fixed completely (but the error could also be due to me trying strange novice things which are not supposed to work).

**Comment by dcbaker** [comment]
Master (what will become 0.56) does have a change to give more specific information on what went wrong

**Comment by ms178** [comment]
As using ICC is no longer a thing, I will close this issue as obsolete.
