### ISSUE TITLE
automated package submission/updates and/or approval to wrapdb

### ISSUE THREAD

**Issue by agauniyal** [mesonbuild/meson#784]
There should be some kind of automated process to submit and update new packages to wrapdb so that it becomes easier for us to get it done in time. Even if we already have the required changes, we can't open a PR unless a new version branch is created on original repo.

You can keep the approval as a manual process if you think wrong packages might slip in or something. Also I wanted to ask - the wrapdb is open to public projects right, it isn't some kind of internal db that only you use and we're fine to use it..?

**Comment by jpakkane** [comment]
Wrapdb is public and meant to accept as many packages as possible, yes. The problem is that it is currently a bit short-staffed (basically just me).
