### ISSUE TITLE
Support libboost_<module>-mt-<arch>.a for mingw-w64

### ISSUE THREAD

**Issue by fiesh** [mesonbuild/meson#7850]
Alas `b2`'s `tagged` layout now (I believe since boost 1.69, but not entirely sure) also includes the Windows-style `x86` / `x64` tags in their library naming when building for `mingw-w64`.

This means that `dependencies/boost.py`'s

```python
# Note that we should also try to support:
# mingw-w64 / Windows : libboost_<module>-mt.a            (location = <prefix>/mingw64/lib/)
#                       libboost_<module>-mt.dll.a
```

is now insufficient, we have to check for `libboost_<module>-mt-<arch>.a` and `libboost_<module>-mt-<arch>.dll.a`.

I guess always checking both would be the most robust?

**Comment by mensinda** [comment]
Really, only boost can get away with this ridiculus tag layout without any working dependency system...

@jpakkane This issue should not block the `-rc[0-9]+` releases, but should be resolved before the final 0.56.0 release since I would classify this as a bug fix.

**Comment by mensinda** [comment]
@fiesh is there actually an issue? Did you run into any problems? We are actually currently parsing all / most tags since my boost dep rewrite in #6602. The comments are apparently no longer up to date.

**Comment by mensinda** [comment]
The code actually handles all tags defined in https://www.boost.org/doc/libs/1_74_0/more/getting_started/windows.html#library-naming, which includes the `-x64` tag. I am taking this off the milestone until it is confirmed that there is an issue.

**Comment by fiesh** [comment]
Oh sorry,  yes I do run into an actual issue.  When building MXE and replacing its boost 1.60 with boost 1.74, as explained the naming scheme changes.  CMake still finds boost then, but meson aborts with

```
Run-time dependency Boost (filesystem) found: NO 
meson.build:37:0: ERROR: Dependency "boost" not found
```

Maybe I jumped to a wrong conclusion here.  Should I set up a `Dockerfile` showing the issue, or would you like some additional information?

**Comment by mensinda** [comment]
A `Dockerfile` would be great. However, the `meson-log.txt` could also provide a bit of insight.

**Comment by fiesh** [comment]
Ok, I'm sorry, that was my stupidity.  It turns out I screwed up the meson update and was actually using an older version -- and then was misled by the comments indicating an older check than what was actually done.  Now updating meson *properly* resolves the issue.

I'm sorry about this!
