### ISSUE TITLE
run meson.py with bug in _pathlib.py

### ISSUE THREAD

**Issue by zyy98** [mesonbuild/meson#7899]
I am working on Windows10 and I downloaded the code from github. I also run the pip install meson with python 3.9 before. But neither works.
I was hoping to use meson setup builddir. However it seems I cannot use meson at all. Whenever I run it, it just shows that the line below has invalid syntax, it is line38 in mesonbuild/_pathlib.py
```
def resolve(self, strict: bool = False) -> 'Path':
```

**Comment by mensinda** [comment]
The `_pathlib.py` module/feature is new and should only be in master. So if you install meson with pip you shouldn't get this error. Could you also please double-check that you are using python >= 3.6? The code path that produces this error will only be executed for python <= 3.5. The absolute minimum required version for meson is python 3.5.2.

Also, please provide the full error message if this problem presists.

**Comment by zyy98** [comment]
I am using python 3.9 as I said before. 
Here is the message I get.
![log](https://user-images.githubusercontent.com/45323482/97149577-e726f780-17a7-11eb-8cdb-4d99cb8536f8.png)

**Comment by mensinda** [comment]
Again, this shouldn't be possible when you are using 3.9: This code path is behind an if that checks the current python version and will thus only ever be used for python <= 3.5: https://github.com/mesonbuild/meson/blob/master/mesonbuild/_pathlib.py#L29

Is it possible that you also have an old python install (3.4, or 2.x) that could be accidentally used when launcing meson?

**Comment by zyy98** [comment]
I had python 2.7 but when I type in ```which python``` it shows python 3.9

**Comment by mensinda** [comment]
Also, the invalid syntay is witth 99% certainty due to the type hints (which are new in 3.5), so this is another indication that an old python version is used accidentally.

can you try `python --version` and check `which meson` and post the code? Also please try to run meson with `python /absoulte/path/to/meson.py`

**Comment by zyy98** [comment]
when I type in ```which meson``` it just shows no meson. 
Also when I run meson with absolute path, it always shows ```ERROR: Must specify at least one directory name.```
Is it because I have not install meson properly?
meson.py only exists in the file downloaded from github. I cannot find it in site-packages where I used pip install to install meson.

**Comment by mensinda** [comment]
The error you get with the absolute path is intended and differenr from the _pathlib.py error (which indicates that you/windows/visual studio somehow managed to select an older python install).

The syntax configuring a build directory is `meson path/to/builddir`. You usually just run `meson build` from your root source directory. See the docs for more informatiom: https://mesonbuild.com/Quick-guide.html#compiling-a-meson-project

**Comment by eli-schwartz** [comment]
Disregarding the confusion about python versions, the relevant code got dropped in f6672c7a1923c3e052af3ad223d6075b86378bfc anyway.
