### ISSUE TITLE
Making spdlog available in wrapdb

### ISSUE THREAD

**Issue by agauniyal** [mesonbuild/meson#790]
I need another repo under mesonbuild org, have already worked for the PR.

**Source**: https://github.com/gabime/spdlog

**Comment by agauniyal** [comment]
Also the build needs a folder `logs` inside the build directory, since it is required by the tests written by original author. How should I go on about it, should I make one in wrapdb's repo or create a .sh file with `cd ${Build_dir_var} && mkdir -p logs` and then use run_command?

**Comment by jpakkane** [comment]
Repo created.

To create a dir the simplest approach is this:

    run_command('mkdir', '-p', meson.build_root() + '/rest/of/the/path')
