### ISSUE TITLE
Recommend to use licence identifiers from the SPDX license list

### ISSUE THREAD

**Issue by primeos** [mesonbuild/meson#7905]
Since #2942 the `project()` function supports declaring a license (or multiple licenses), which is quite useful. However, currently there is no recommended format for specifying licenses:

https://mesonbuild.com/Reference-manual.html#project
> `license:` takes a string or array of strings describing the license(s) the code is under. Usually this would be something like `license : 'GPL2+'`, but if the code has multiple licenses you can specify them as an array like this: `license : ['proprietary', 'GPL3']`. **Note that the text is informal and is only written to the dependency manifest. Meson does not do any license validation, you are responsible for verifying that you abide by all licensing terms.** You can access the value in your Meson build files with `meson.project_license()`.

Unfortunately some license identifiers are ambiguous. E.g. `GPL3` can mean "GNU General Public License v3.0 only" or "GNU General Public License v3.0 or later".

Therefore I propose to update the Meson documentation and all examples to recommend using a license identifier form the [SPDX license list](https://spdx.org/licenses/). For the previous example this would resolve the ambiguity by using either `GPL-3.0-only` or `GPL-3.0-or-later`.

The Software Package Data Exchange® (SPDX®) is a Linux Foundation Project and describes itself as:
> An open standard for communicating software bill of material information, including components, licenses, copyrights, and security references. SPDX reduces redundant work by providing a common format for companies and communities to share important data, thereby streamlining and improving compliance.

More information (advantages, details, etc.) can be found here:
- https://spdx.dev/resources/use/#identifiers
- https://spdx.dev/ids/

If you agree that the SPDX short-form license identifiers would be a good fit I would also offer to make a PR if you want.

**Comment by jpakkane** [comment]
Seems like a reasonable idea.

**Comment by dcbaker** [comment]
I like this idea too.

**Comment by xclaesse** [comment]
> If you agree that the SPDX short-form license identifiers would be a good fit I would also offer to make a PR if you want.

Yes please, that would be appreciated.

**Comment by primeos** [comment]
Apologies for the huge delay, I messed that up :o Anyway, I just opened #7939.

I also noticed one more thing:
> [...] but if the code has multiple licenses you can specify them as an array like this: `license : ['proprietary', 'GPL-3.0-only']`.

But as https://spdx.dev/ids/#why states this is also somewhat unclear:
> Saying “this file is MPL/MIT” is ambiguous, and leaves recipients unclear about their compliance requirements. Saying “MPL-2.0 AND MIT“ or “MPL-2.0 OR MIT“ specifies precisely whether the licensee must comply with both licenses, or
either license, when redistributing the file.

We could also recommend/enforce using "AND"/"OR" instead of an array though I'm not sure if it's really worth it (e.g. if a part of a project uses a different license one could still use "AND" but it wouldn't really accurately describe the situation either).
