### ISSUE TITLE
extract_all_objects malfunctions with respect to vala files

### ISSUE THREAD

**Issue by Skrylar** [mesonbuild/meson#791]
`extract_all_objects` seems to malfunction when used on Vala projects. The extracted objects use the naming scheme of `object.vala.o`, while the generated ninja files are `object.c.o`. Attempting to use extracted objects with vala builds therefore fails.

**Comment by bonzini** [comment]
This is broken again, because `'.vala'` is not included in mesonbuild.compilers.compilers.clike_langs and therefore `is_source('prog.vala')` returns False. I'm including a fix in PR 3683, since otherwise the tests fail.

**Comment by nirbheek** [comment]
> This is broken again, because '.vala' is not included in mesonbuild.compilers.compilers.clike_langs and therefore is_source('prog.vala') returns False. I'm including a fix in PR 3683, since otherwise the tests fail.

That's strange, why doesn't the test fail?

Also, please open a separate PR for fixing this bug, and fix the test as well.

**Comment by bonzini** [comment]
I think the test succeeds but the static library it generates is broken.
