### ISSUE TITLE
`meson subprojects update` should reapply any patch files after updating.

### ISSUE THREAD

**Issue by nnooney** [mesonbuild/meson#7923]
**Describe the bug**
I'm updating a few of my wrap-git subprojects to checkout the latest revisions, and I need to update the patch files to fix changes. Note that I'm using a local `patch_directory` to maintain my patches, so they live in the `subprojects/packagefiles` directory. When I run the command `meson subprojects update`, changes in my patch files are not applied to the updated project.

**To Reproduce**
Here is the wrap file:
```
[wrap-git]
directory = protobuf
url = https://github.com/protocolbuffers/protobuf.git
revision = master
patch_directory = protobuf
```

**Expected behavior**
Calling `meson subprojects update` will update the subproject via `git`, and then reapply the patch_directory with the latest revision of the patch files.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? **Native Build**
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) **Debian Unstable (running inside WSL)**
* what Python version are you using e.g. 3.8.0 **3.8.6**
* what `meson --version` **0.55.3**
* what `ninja --version` if it's a Ninja build **1.10.1**

Also, thank you maintainers for making such a wonderful tool to use.

**Comment by eli-schwartz** [comment]
`meson subprojects update --reset` will now reapply the patch_directory. By default it isn't applied, because the "update" subcommand is about fetching new versions of the subproject source code, not necessarily the packagefiles.

There is also now a subcommand `meson subprojects packagefiles --apply` that just applies the packagefiles, nothing else.

Implemented in #9354

**Comment by felixf4xu** [comment]
```
meson subprojects update --help
```
>usage: meson subprojects update [-h] [--rebase] [--reset] [--sourcedir SOURCEDIR] [--types TYPES] [-j NUM_PROCESSES] [--allow-insecure] [subprojects ...]
>
>options:
    --reset               Checkout wrap's revision and hard reset to that commit. (git only)

but the document says the opposite way. `--reset` seems to be like `git reset --hard`, it does not mention it will **apply** the diff_files.

**Comment by felixf4xu** [comment]
one more question, then meson subprojects update --reset should be an additional step?
```sh
meson setup build .
meson subprojects update --reset    <-???
meson compile -C build
```

**Comment by felixf4xu** [comment]
I tested that, `meson subprojects packagefiles --apply` does not work, at least for `wrap-git` and git diff_files.
