### ISSUE TITLE
meson 0.56.0 feature qt5.compile_translations(qt5.compile_translations:...) does not work

### ISSUE THREAD

**Issue by qwertzui11** [mesonbuild/meson#7925]
according to the changelog https://github.com/mesonbuild/meson/blob/master/docs/markdown/Release-notes-for-0.56.0.md#qt5-compile_translations-now-supports-qresource-preprocessing for 0.56.0 there should be the ability to write
```cpp
qt5.compile_translations(qresource: 'i18n.qrc')
```

the `i18n.qrc` looks like:
```
<RCC>
    <qresource>
        <file>de.ts</file>
    </qresource>
</RCC>
```

however, when running meson it results in the following error:
```
ERROR: qt.compile_translations: qresource can only contain ts files, found de.ts
```
whiiiich is a contradiction.

In my opinion there is a bug along these lines. meson should compile from `ts` to `qm` and not vice-versa.
https://github.com/mesonbuild/meson/blob/d4eec9664bb96a093b92c3e1f565806686ea0ccb/mesonbuild/modules/qt.py#L236

There seem to be no tests about this.

Am I getting something wrong? Thx for your time!

By the way, thx for this great tool! :laughing:

**Comment by eli-schwartz** [comment]
Right, the error message is misleading and should say "can only contain qm files". Sorry for that...

**Comment by qwertzui11** [comment]
No problem at. Ur right. Because of that error message I followed a wrong path and couldn't get it to work. With the new knowledge it finally works. Thx!

U may wanna close this issue

**Comment by eli-schwartz** [comment]
It's not going to be closed until the linked PR is merged to fix the error message. :)

**Comment by eli-schwartz** [comment]
My terrible documentation is now fixed in git master, and the error message will be correct in the 0.56.1 bugfix release.
