### ISSUE TITLE
Allow passing python_installation objects as test() arguments.

### ISSUE THREAD

**Issue by michaelcadilhac** [mesonbuild/meson#7987]
**Describe the bug**
This is a variant of https://github.com/mesonbuild/meson/issues/3552.  The return value of `find_installation()` from the Python module is not accepted as a `test()` argument, although it is (similar to) a external program.

**To Reproduce**
`meson.build`:
```
project ('test-test')
echo_exe = find_program ('echo')
py = import('python').find_installation()
test ('test', echo_exe, args : [ py ])
```
This fails with

`meson.build:4:0: ERROR: Command line arguments must be strings, files or targets.`

**Expected behavior**

I'd expect that the executable is silently converted to a string.

**system parameters**
* Native build
* Arch Linux
* Python 3.8.6
* meson 0.56.0

**Comment by eli-schwartz** [comment]
It is not silently converted to a string, just like find_program() from the linked bug is not silently converted to a string. Both of them need .path(), and a find_installation is actually a subclass of a find_program.

The other bug does not seem to have actually been resolved
