### ISSUE TITLE
Xcode backend is broken again!

### ISSUE THREAD

**Issue by michaelbrockus** [mesonbuild/meson#7992]
**Describe the bug**
Ok. I was gonna use Xcode to work on a Turing-Machine when suddenly the backend gave me the error at the end of this output snippet.

```console
mike@Michaels-MBP turing_machine % meson setup builddir --backend xcode 
The Meson build system
Version: 0.56.0
Source dir: /Users/mike/Desktop/turing_machine
Build dir: /Users/mike/Desktop/turing_machine/builddir
Build type: native build
Project name: Turing Machine
Project version: 0.1.0
C compiler for the host machine: ccache cc (clang 12.0.0 "Apple clang version 12.0.0 (clang-1200.0.32.27)")
C linker for the host machine: cc ld64 609.7
Host machine cpu family: x86_64
Host machine cpu: x86_64
Build targets in project: 2

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/mesonmain.py", line 140, in run
    return options.run_func(options)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/msetup.py", line 253, in run
    app.generate()
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/msetup.py", line 161, in generate
    self._generate(env)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/msetup.py", line 223, in _generate
    intr.backend.generate()
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/backend/xcodebackend.py", line 102, in generate
    self.generate_pbx_build_file()
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/backend/xcodebackend.py", line 271, in generate_pbx_build_file
    idval = self.buildmap[s]
KeyError: 'modules/code/modules/code/project.c'
mike@Michaels-MBP turing_machine % 
```

**To Reproduce**
This is the link to the general structure of the project with those needed Meson build scripts.

[project link](https://github.com/michaelbrockus/c_meson_program).

**Expected behavior**
I expect that the backend to not blow up and produce an Xcode project.

**system parameters**
* This is just a plain native build (for the same computer)?
* MacOS Big Sur
* `python 3.9`
* `meson 0.56.0`
* `ninja NA`

**Comment by ekmecic** [comment]
Getting the same error on Mojave, meson 0.56.0, python 3.9.

**Comment by eli-schwartz** [comment]
The xcode backend got a lot of changes and fixes since then. The code that broke on you doesn't even exist anymore since commit 0b50c5705f6e7abc12155f2ecdb6acc4730a5922.

Can you verify whether this works now?

**Comment by eli-schwartz** [comment]
Assuming this was fixed since the broken code has been refactored out of existence as part of a general "fix xcode" cleanup.
