### ISSUE TITLE
Fail to build meson to a custom location on Python 3.8

### ISSUE THREAD

**Issue by xq114** [mesonbuild/meson#7999]
**Describe the bug**
When I'm trying to build meson to a custom location, I find it not working with `meson --version`. However, if I change the python version to 3.7, it works.

**To Reproduce**
[On windows]

1. Download meson-0.56.0.tar.gz and extract it somewhere
2. Install Python 3.7 or 3.8
3. Open powershell and change the directory to meson folder
4. Type
```powershell
$env:PYTHONPATH = "${PWD}/../build/Lib/site-packages"
python setup.py install --prefix="../build"
../build/Scripts/meson.exe --version
```
5. If Python version is 3.7, it returns 0.56.0 which is correct; But if Python version is 3.8, it just fails.

Error message:
```
importlib.metadata.PackageNotFoundError: meson
```

**Expected behavior**
output 0.56.0

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? No cross build
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) Windows 10
* what Python version are you using 3.8.6 and 3.7.0
* what `meson --version` failed :)
* what `ninja --version` if it's a Ninja build No ninja.

**Comment by eli-schwartz** [comment]
This is not really a meson issue. It is best asked on the setuptools project issues.

You can install meson using meson's own methods (offered as alternatives to setuptools), by e.g. running `./packaging/create_zipapp.py` and installing the resulting zipapp to whatever directory you like, and having it open with your choice of python interpreter.
