### ISSUE TITLE
Underscore detection broken on darwin x64

### ISSUE THREAD

**Issue by knopp** [mesonbuild/meson#8004]
output.obj contains both the `_meson_uscore_prefix` and `meson_uscore_prefix` strings and `meson_uscore_prefix` is first so `symbols_have_underscore_prefix` returns `false`.

**Comment by ePirat** [comment]
Is this a duplicate of #5482? Or is it a distinct issue unrelated to debug symbols?

**Comment by knopp** [comment]
Indeed it seems to be.
