### ISSUE TITLE
Shouldn't b_colorout be auto by default

### ISSUE THREAD

**Issue by anonyno** [mesonbuild/meson#8018]
**Describe the bug**
`b_colorout` is not equal to auto by default. Redirecting to a log file, like with `ninja > build.log` strips colors only because ninja includes code for that. [samurai](https://github.com/michaelforney/samurai), a Ninja-compatible build tool which is the implementation of Ninja used in Alpine Linux (and maybe other Linux distros) does not strip colors. This makes it hard to redirect output from samurai to a log file when using the default Meson options.

I'm sure you had a reason for choosing `always` as the default. Maybe it can be added to the FAQ?

**Comment by a-vrma** [comment]
The Ninja FAQ says this:

> Because Ninja runs commands in parallel, it buffers their output to prevent it from interleaving. Commands will detect that their output is not directed to a terminal, assume they're going to a log file, and turn off their colored output. To fix this, pass flags to the subcommand (like -fdiagnostics-color=always to gcc and -fcolor-diagnostics to clang) to force color on. Ninja itself will detect if it's writing to a terminal and escape color codes from commands if it isn't.
>
> Ninja could use pseudo ttys to work around this further, but different systems have different limits on the number of ptys available. I also worry that commands like svn up would assume they can interact with the user.

Testing it now, it seems that if one uses b_colorout=auto with samurai, there is no color because the compiler detects that its output is being directed to samurai, not the terminal.
