### ISSUE TITLE
Using project c_args causes CFLAGS env to be ignored

### ISSUE THREAD

**Issue by 3v1n0** [mesonbuild/meson#8037]
**Describe the bug**

In a project were we're defining `c_args` in `default_options` we get builds without symbols when configuring with

```bash
env CFLAGS='-g -O2' meson _build -Dbuildtype=plain
```

**To Reproduce**

See a test case here https://github.com/3v1n0/meson-broken-cflags

The point is to use:

```meson
project('broken-args', 'c',
    default_options: [
        'buildtype=debugoptimized',
        'warning_level=3',
        'c_std=gnu99',
        'c_args=' + ' '.join([
            '-Wunused', # Any value here is enough to fail
        ]),
    ],
    meson_version: '>= 0.50.0')
```

**Expected behavior**

In such case we require in CFLAGS a binary with debug symbols, but `-g` is completely ignored.
While we'd expect to get a binary with `.debug_info` section.

**system parameters**
* Native build
* Ubuntu 20.10 and Fedora 33
* Python version 3.8.6
* `meson --version`: 0.55.3
* `ninja --version`: 1.10.0

**Comment by dcbaker** [comment]
This is behaving as expected. Don't put c_args in your default_options. It's almost certainly not portable to do so, instead do something like:
```meson
cc = meson.get_compiler('c')
add_project_arguments(
  cc.get_supported_arguments(
    ...),
  language : 'c')
```
Which is portable

**Comment by benzea** [comment]
Still feels confusing to me. I guess one can argue that the default `c_flags` is build based on the path, so we are explicitly overriding it. And then we are not overriding the linking step flags, which means that this then does get called with `CFLAGS` passed:

```
$ ninja -C _build/ --verbose
ninja: Entering directory `_build/'
[1/2] cc -Ihello.p -I. -I.. -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -std=gnu99 -fno-strict-aliasing -Wmissing-noreturn -Wundef -Wunused -MD -MQ hello.p/hello.c.o -MF hello.p/hello.c.o.d -o hello.p/hello.c.o -c ../hello.c
[2/2] cc  -o hello hello.p/hello.c.o -Wl,--as-needed -Wl,--no-undefined -g -O2
```

**Comment by jlevon** [comment]
Could we at least get some documentation on this behaviour?

**Comment by tristan957** [comment]
@jlevon interested in submitting a PR?

**Comment by jlevon** [comment]
Sure: https://github.com/mesonbuild/meson/pull/11457

**Comment by rgommers** [comment]
This issue can be closed, the doc update with the explanation was merged.
