### ISSUE TITLE
override_dependency and dependency(..., static: true) broken

### ISSUE THREAD

**Issue by textshell** [mesonbuild/meson#8050]
When using `override_dependency` and a `dependency(...)` call that uses `static: true` the overridden dependency seems to be completely ignored.

Reproducer:

main project:

```
project('parent', 'c')
dependency('sub', static: true)
```

sub project:
```
project('sub', 'c')
dep = declare_dependency()
meson.override_dependency('sub', dep)
```

This yields the following output:
```
Run-time dependency sub found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency sub

|Executing subproject sub method meson 
|
|Project name: sub
|Project version: undefined
|C compiler for the host machine: ccache cc (gcc 8.3.0 "cc (Debian 8.3.0-6) 8.3.0")
|C linker for the host machine: cc ld.bfd 2.31.1
|Build targets in project: 0
|Subproject sub finished.

Dependency sub from subproject subprojects/sub found: NO

meson.build:4:0: ERROR: Subproject subprojects/sub did not override dependency sub
```

This should at least give a hint, that and how the overriding was found to be incompatible. I had to resort to adding debug prints to meson to understand why my override seemed to be completely ignored, so think trying to understand this will be frustrating to other users of meson as well.

But i think if the overriden dependency contains a static lib it should just work.

Tested using meson master from 24.11.2020 (0fa808f7066d)

/CC @xclaesse

**Comment by ntonnaett** [comment]
This is still a problem. Is the underlying problem that there is default_library for subprojects and static: bool for dependencies?
Maybe default_library shouldn't be used at all for this. I would like to have a way to specify easily what part of my dependency chain is linked statically or shared. Right now there is no way to have a dependency that should be linked statically but all dependencies of that should be linked shared. Or I am not aware of that.

What do you think about automatically adding dependency options?

**Comment by xclaesse** [comment]
There are 2 issues here:
- `dependency('sub', static: true)` is not going to pass `default_library=static` to the fallback. So your subproject is going to build shared libraries, unless you also add `default_options:['default_library=static']`. IMHO, `static: true` should implicitly set the `default_library=static` option on fallback subproject.
- `meson.override_dependency('sub', dep)` meson has no way to know if dep is static or shared. It could even be both, it can be a dep object that links to multiple libs, some static, some shared. We could add `static` kwarg to `override_dependency()`, just like we have `native` and it would be user's responsibility to set it according to the value of `default_library`. Or we could set it by implicitly which would be what user wants 99% of time, I guess we would still need to add the kwarg to let the remaining 1% override the default value.

**Comment by xclaesse** [comment]
Tried to tackle this issue there: https://github.com/mesonbuild/meson/pull/9061.
