### ISSUE TITLE
custom_target: make 'command' argument optional

### ISSUE THREAD

**Issue by gdesmott** [mesonbuild/meson#8059]
I have [a script](https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/blob/master/cargo_wrapper.py) generating my library files hooked as a [custom_target](https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/blob/master/meson.build#L148). This works well enough and I'm [extending this script](https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/merge_requests/439) to also generate pkg-config files for those libraries.
Those files need to be installed to a different directory than the libraries so I created [another custom_target](https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/merge_requests/439#note_713213) depending on the first one.
This second `custom_target` does not need a `command` as it re-uses the result of the command run by the first one, but I'm currently forced to pass it a dump `command` argument. Making it optional would make this use case easier to implement.

cc @xclaesse

**Comment by eli-schwartz** [comment]
So you have a custom_target that returns multiple unrelated build outputs, but does not tell meson it is doing so. Then you want to create another custom_target that outputs a file, but never creates it, because a different build rule created it.

Am I understanding this correctly?

**Comment by gdesmott** [comment]
Yes, kind of hacky, I agree, but it's all glue between `cargo` and `meson`.

**Comment by eli-schwartz** [comment]
`s/kind of//`

IMO custom_target() should not be changed to something only needed by a hack that is non-mesonic. If you need to generate multiple files in one custom_command, name them all as outputs and install them one by one... or propose a helper function that natively understands one target producing both a library and a pkg-config file. There is existing interest in a rust module...

**Comment by gdesmott** [comment]
> If you need to generate multiple files in one custom_command, name them all as outputs and install them one by one

I'd be happy to but I didn't manage to do so while installing the files in different directories (like `/usr/lib` for libs and `/usr/lib/pkg-config` for pc files). How can I do that?

**Comment by xclaesse** [comment]
If your first script returns the path where the pc files have been generated, maybe you can use install_data() or install_subdir() to install them?

**Comment by gdesmott** [comment]
> But then we need install_data() to have depends kwarg

Yeah adding `depends` to those would solve my problem as well.

**Comment by xclaesse** [comment]
Thinking again, actually we don't need to add depends, because it's done at install step, after build step, so there is no ordering issue.

From a quick look, install_data() can install built files one by one, but install_subdir() only accepts directory from source tree. However install_subdir() implementation does support installing directory from build directory, I added that for external_project module, so it's just a matter to add API to tell if the subdir path is relative to source dir or build dir.

**Comment by eli-schwartz** [comment]
> I'd be happy to but I didn't manage to do so while installing the files in different directories (like `/usr/lib` for libs and `/usr/lib/pkg-config` for pc files). How can I do that?

Apologies for overlooking this and never responding.

You can do this by listing the value of `install_dir: ` as an array of different directories, e.g.

```
install_dir: [plugins_install_dir, pkgconfig_install_dir, pkgconfig_install_dir, pkgconfig_install_dir, ...]
```

You may want to build that array in your earlier foreach loop.

**Comment by eli-schwartz** [comment]
I still think it's strange to do all the work in a single script, you could just move:

```python
    # Copy generated pkg-config files
    for f in glob.glob(os.path.join(cargo_target_dir, target, '*.pc')):
        shutil.copy(f, meson_build_dir)
```

to a second script (or a `--pkgconfig-copy` argument in that one script to reduce duplication), and run that script -- and thereby do the copying -- in a second custom_target with its own unified install_dir.

Also meson's `import('pkgconfig')` module would correctly install to libdata on FreeBSD. :p
