### ISSUE TITLE
Incorrect subsystem flag output under Windows Clang (and lld-link)

### ISSUE THREAD

**Issue by TheMadHau5** [mesonbuild/meson#8060]
**The bug**
Meson (on Windows, native) with Clang (and lld-link) adds `"-Wl,--subsystem,console"` instead of `"-Wl,/SUBSYSTEM:CONSOLE"`, causing the build to fail.
Manually editing the `build.ninja` and changing the flag allows the build to complete successfully.

**To Reproduce**
Install Meson (with Ninja included) and Clang (at `C:\Meson` and `C:\LLVM` in my case, respectively) with both added to PATH.
Follow [this section of the Meson Tutorial](https://mesonbuild.com/Tutorial.html#the-humble-beginning).
(Note: `cmd.exe` was used as the shell, and all commands are identical except `./demo` which becomes `demo.exe`)

**Expected behaviour**
I expect the build to compile successfully, and running `demo.exe` should output "Hello there."
The expected behaviour occurs when I manually fix `build.ninja`

**System parameters**
* Native build
* Windows 10
* Python isn't installed
* Meson 0.56.0
* Ninja 1.10.1

**Comment by dcbaker** [comment]
We currently have really bad support for mixing gcc-style clang and a non-gnu linker. I'm not surprised this doesn't work. I *think* that clang + ld.lld will work on windows (though we don't test plain clang on windows so it may be broken as well).

**Comment by TheMadHau5** [comment]
When `CC_LD` is set to `lld`, there are other issues, in addition to the previous one:
```
"clang"  -o demo.exe demo.exe.p/main.c.obj "-Wl,--allow-shlib-undefined" "-fuse-ld=lld" "-Wl,--subsystem,console" "-Wl,--start-group" "-lkernel32" ... "-ladvapi32" "-Wl,--end-group"
lld-link: warning: ignoring unknown argument '--allow-shlib-undefined'
lld-link: warning: ignoring unknown argument '--subsystem'
lld-link: warning: ignoring unknown argument '--start-group'
lld-link: warning: ignoring unknown argument '--end-group'
lld-link: error: could not open 'console': no such file or directory
```
And if I attempt to set `CC_LD` to `ld.lld`, Meson claims that Clang simply cannot compile programs.
(I'm assuming the sanity checks fail)

I've also been running into the `lld: error: unknown argument: --allow-shlib-undefined` issue when trying to use lld in MinGW (MSYS2) but this one isn't a warning like in `lld-link` and it causes build failure, until the flag is removed from `build.ninja`

**Comment by dcbaker** [comment]
Ah yes, the --allow-shlib-undefined issue. I need to fix that one, it just requires a bit of tinkering, we really need to test that it works, because it's an issue of the output format. mach-o (apple) and elf (unix) allow this, but neither coff nor pe (the two most common windows formats) do.

**Comment by TheMadHau5** [comment]
Yeah. I'm aware of that and I was thinking that a check could be added such that if Meson is being run under Windows (natively or via any of MinGW, MSYS, or Cygwin) and if so, that argument would simply not be output. Maybe something like:
```
        self.has_allow_shlib_undefined = not (mesonlib.is_windows() or mesonlib.is_cygwin() or 'unknown argument: --allow-shlib-undefined' in e)
```

**Comment by e820** [comment]
I believe this should have been fixed by #8071? Would be appreciated if you could test this on a native Windows build to verify.

**Comment by TheMadHau5** [comment]
I currently have exams, so will test a bit later. Thanks for helping!

**Comment by Vincent-P** [comment]
I just cloned and tried with a C++ Hello World and it works!
Can't wait to try this on my bigger projects to replace CMake 😃

**Comment by dcbaker** [comment]
I'm going to close this then as fixed. If it's not then please reopen.
