### ISSUE TITLE
-Dcpp_std is not honoured

### ISSUE THREAD

**Issue by jormundgand** [mesonbuild/meson#8063]
When using -Dcpp_std=c++14 (for example), the result is a warning that the option does not exist. This (in combination with not being able to set a default option for the same), forces all C++ projects to be stuck with C++03 when building with meson, making meson useless for C++ projects.

**Comment by dcbaker** [comment]
Which version of meson and compiler are you using? cpp_std=c++14 works fine for me here with meson 0.56.0 and gcc and clang.

**Comment by jormundgand** [comment]
I'm running 0.55.1 with gcc 10. Updating this to 0.56.0, did fix the problem.
