### ISSUE TITLE
Half complete sentence in the documentation 

### ISSUE THREAD

**Issue by Volker-Weissmann** [mesonbuild/meson#8077]
[In the documentation](https://mesonbuild.com/Machine-files.html) you say:

> An integer must be either an unquoted numeric constant;

This is a half complete sentence.

**Comment by z3ntu** [comment]
This has been fixed in commit https://github.com/mesonbuild/meson/commit/0f5a136c40cfe521e7080460c316609468d4433b

**Comment by xclaesse** [comment]
Thanks.
