### ISSUE TITLE
Typos in Reference Manual

### ISSUE THREAD

**Issue by radioactiveman** [mesonbuild/meson#8097]
**Describe the bug**
The docs for [message()](https://mesonbuild.com/Reference-manual.html#message) and [warning()](https://mesonbuild.com/Reference-manual.html#warning) in the reference manual contain a typo (more more).

> (since 0.54.0) Can take more **[more]** than one argument that will be separated by space.

Thanks for Meson, it's a great tool. :+1:

**Comment by eli-schwartz** [comment]
Thank you for the report!

Would you like to go the extra mile and submit a PR to modify this? https://github.com/mesonbuild/meson/blob/master/docs/markdown/Reference-manual.md

**Comment by radioactiveman** [comment]
Not necessarily, it's easier / faster if you fix it.
By the way, I remember you from the Arch forum. :smile:

**Comment by eli-schwartz** [comment]
All right. :)
