### ISSUE TITLE
Meson unable to detect linker after version upgrade

### ISSUE THREAD

**Issue by njpau** [mesonbuild/meson#8098]
I've recently upgraded from meson 0.51 to meson 0.56, and it seems like the linker detection feature introduced in 0.53 is working against me. Meson complains that it is unable to detect the linker for my compiler.

My crossfile:
```[binaries]
c = ['/opt/sdk/sysroots/ppc/ppc-gcc', '-mtune=e300c3', '--sysroot=/opt/sdk/sysroots/ppc/ppc_linux']
cpp = ['/opt/sdk/sysroots/ppc/ppc-g++', '-mtune=e300c3', '--sysroot=/opt/sdk/sysroots/ppc/ppc_linux']
ar = '/opt/sdk/sysroots/ppc/ppc-ar'
pkgconfig = 'opt/sdk/sysroots/i686/pkg-config'

[properties]
cpp_args = ['fno-exceptions', '-c', '-g', '-gsplit-dwarf', '-DLINUX']
cpp_link_args = ['-fuse-ld=bfd', '-Wl,--no-keep-memory']
c_args = ['fno-exceptions', '-c', '-g', '-gsplit-dwarf', '-DLINUX']
c_link_args = ['-fuse-ld=bfd', '-Wl,--no-keep-memory'] 

[host_machine]
system = 'linux'
cpu_family = 'ppc'
cpu = 'e300c3'
```

In /opt/sdk/sysroots/ppc, lives the following:
* ppc-gcc
* pcc-g++
* ppc-ar
* ppc-ld
* ppc-ld.bfd
* ppc-ld.gold

Prior to the upgrade, i.e., on 0.51, this was working fine for me. I used the same crossfile as above and the correct linker was invoked for linking with the correct arguments. After the upgrade, meson setup throws out this error:
```
meson.build:2:0: ERROR: Unable to detect linker for compiler "/opt/sdk/sysroots/ppc/ppc-gcc -mtune=e300c3 --sysroot=/opt/sdk/sysroots/ppc/ppc_linux -Wl,--version -fno-exceptions -c -g -gsplit-dwarf -DLINUX"
```

However, if I remove the \<lang\>_args and \<lang\>_link_args section from my crossfile, meson does not have any complaints. I'm unable to understand why my \<lang\>_args are also being used to detect the linker.

Things I have tried:
* Putting \<lang\>_args and \<lang\>_link_args under a [built-in options] section in the cross-file
* Adding ld = "bfd" in the [binaries] section of the cross-file 
* Adding ld = "bfd" in the [binaries] section of the cross-file and swapping out \<lang\>_link_args for just ld_args in the [built-in options] section
* Adding c_ld = "bfd" and cpp_ld = "bfd" in the [binaries] section of the cross-file

None of these worked. My current fix involves putting my \<lang\>_args and \<lang\>_link_args under a set of  different variable names in the properties section of the cross-file and pulling them out using meson.get_cross_property() in my build definitions to insert the manually into the executable() and library() functions. Looking for some guidance here on how to do things better.

Build System Parameters:
* Running cross-builds on a Debian Buster machine
* Python 3.5 on the machine
* meson --version = 0.56.0
* ninja --version = 1.8.2

**Comment by dcbaker** [comment]
If you have any invalid options in your `<lang>_args` or `<lang>_link_args`, that will cause this to fail. I think in master you get a better error message. I see one thing off the bat that looks suspicious, and a couple of improvements improvement:
```ini
[binaries]
c = ['/opt/sdk/sysroots/ppc/ppc-gcc', '-mtune=e300c3', '--sysroot=/opt/sdk/sysroots/ppc/ppc_linux']
c_ld = 'bfd'
cpp = ['/opt/sdk/sysroots/ppc/ppc-g++', '-mtune=e300c3', '--sysroot=/opt/sdk/sysroots/ppc/ppc_linux']
cpp_ld = 'bfd'
ar = '/opt/sdk/sysroots/ppc/ppc-ar'
pkgconfig = 'opt/sdk/sysroots/i686/pkg-config'

[built-in options]
cpp_args = ['-fno-exceptions', '-gsplit-dwarf', '-DLINUX']
cpp_link_args = ['-Wl,--no-keep-memory']
c_args = ['-fno-exceptions', '-gsplit-dwarf', '-DLINUX']
c_link_args = ['-Wl,--no-keep-memory']
debug = true

[host_machine]
system = 'linux'
cpu_family = 'ppc'
cpu = 'e300c3'
```
You absolutely should not need to put `-c` in the compiler arguments, meson will do that for you. You can (as of meson 0.56.0) use the `[built-in options]` section to set any option you might on the command line, so instead of adding `-g` you can set `debug = true`, which will do the same thing. You're also missing a `-` on your `-fno-exceptions`. That might just be a copy and paste problem though. You may also be interested in the `[constants]` section, which you could use to de-duplicate some of your cross file.

Let me know if that helps (or not).

**Comment by njpau** [comment]
Wow it looks like the -c compiler argument was the troublemaker. Leaving everything else as is and taking the -c argument out of c_args and cpp_args solved the issue for me. Thanks for your advice, will definitely take heed of the additional points you mentioned. Would you be able to help me understand why the "-c" argument prevented my linker from being detected? Just to improve my own understanding of the meson build system.

**Comment by dcbaker** [comment]
Because all `c_args` and `c_link_args` are passed to the compiler when we try to detect the linker, in case you've put `--target` (clang) or `-fuse-ld=` in those arguments. `-c` prevents any arguments from being proxied to the linker, so when we call `gcc -c -Wl,--version` nothing is returned.

**Comment by dcbaker** [comment]
I'm going to go ahead and close this as resolved then.
