### ISSUE TITLE
Incorrect name of optional dependency if it was not found

### ISSUE THREAD

**Issue by radioactiveman** [mesonbuild/meson#8114]
**Describe the bug**
If an optional dependency is not found, the method name() returns "not-found".
But the [documentation](
https://mesonbuild.com/Reference-manual.html#dependency-object) states something different.
> returns the name of the dependency that was searched.

This is obviously wrong, I was not searching for a dependency named "not-found".
See the example below.

**To Reproduce**
```meson
foo_dep = dependency('foo', required: false)

if not foo_dep.found()
  message('Plugin foo disabled due to missing dependency: ' + foo_dep.name())
endif
```

**Actual behavior**
> Plugin foo disabled due to missing dependency: not-found

**Expected behavior**
> Plugin foo disabled due to missing dependency: foo

**System parameters**
* Meson 0.56.0

**Comment by eli-schwartz** [comment]
This was fixed in the above linked PR, but the cross reference didn't contain the correct closing keywords.
