### ISSUE TITLE
Running meson from static binary?

### ISSUE THREAD

**Issue by niansa** [mesonbuild/meson#8129]
Hi,

how do I run meson from a static binary that has 0 dependencies? I am trying to get meson to work on a pretty weird system where it's simply impossible to install the dependencies.
So basically I just need a static build of meson but I wasn't able to find the cmake/make/whatever file

**Comment by eli-schwartz** [comment]
Meson has no dependencies other than python3.

https://mesonbuild.com/Getting-meson.html#downloading-meson

**Comment by niansa** [comment]
I need a single binary that contains everything, also all libraries required.

**Comment by jpakkane** [comment]
The actual question is whether it is possible to create a single exe version of Python + some scripts. The solution for that is the same as for Meson, as it is just a bunch of Python code. There are some tools that do something like this like cx_freeze or easy_install but some of them are not maintained and I'm not sure if any of them can do the thing you need.

I'd recommend you to seek help from the Python community. If you can get a statically linked single exe Python that run any script then adding Meson files to that should be simple. Note that you do need a statically linked Ninja as well.

**Comment by niansa** [comment]
Maybe you should get rid of some big dependencies like that, it's usually better for low footprint systems anyways – it takes meson like 10-20 seconds to print its first message in `--help` on many of my SBCs (that I like to use as little workers to do tests and since I have so many they can do it in parallel really well).
Ninja on the same system is absolutely unusable because of this, it seems to take these 10-20 seconds for every single file it compiles unlike make which seems to not have this delay.

So some dependency used in meson and ninja must be at fault.

**Comment by eli-schwartz** [comment]
I'm pretty skeptical that ninja should behave like this -- especially if you're fingering dependencies as the problem, since ninja is written in C++ and has no dependencies other than the C++ standard library.

But you can try [samurai](https://github.com/michaelforney/samurai), it is written in c99 instead of C++11.

**Comment by eli-schwartz** [comment]
See also https://mesonbuild.com/FAQ.html#but-i-really-want-a-version-of-meson-that-doesnt-use-python

There's a c99 reimplementation of Meson, which has robust support for C/C++, custom targets, etc. and support for some of meson's modules system (patches welcome for not yet implemented functionality). It compiles down to a 4.5mb statically linked binary and is capable of building many projects.

It's very cool, and it may do what you need. :)

**Comment by niansa** [comment]
Thank you!
