### ISSUE TITLE
dist failure with relative submodule paths

### ISSUE THREAD

**Issue by scop** [mesonbuild/meson#8144]
**Describe the bug**

dist fails with git submodules using relative paths.

**To Reproduce**

The entire tree is at https://gitlab.freedesktop.org/xdg/shared-mime-info/-/tree/40db4c7adba8a5cc586e24f5b4b5aff0b2a81bcc, see .gitlab-ci.yml there for how it's built in CI. The xdgmime submodule is defined as `../xdgmime.git`

CI failure log is at https://gitlab.freedesktop.org/xdg/shared-mime-info/-/jobs/6403481 -- essentially it seems meson is trying to checkout the submodule from a directory relative to the main project working dir, whereas it should treat relative submodule path as relative to the superproject's default remote repo; https://git-scm.com/docs/git-submodule#Documentation/git-submodule.txt-add-bltbranchgt-f--force--nameltnamegt--referenceltrepositorygt--depthltdepthgt--ltrepositorygtltpathgt

**Expected behavior**

Working submodule checkout during dist.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
* what Python version are you using e.g. 3.8.0
* what `meson --version`
* what `ninja --version` if it's a Ninja build

**Comment by eli-schwartz** [comment]
I have linked a PR which should fix this.
