### ISSUE TITLE
Turing Completeness proof

### ISSUE THREAD

**Issue by Volker-Weissmann** [mesonbuild/meson#8145]
[Some guy on github](https://github.com/xorvoid/meson-brainfuck) claims to have proven the Turing completeness of meson.build files by writing a brainfuck interpreter in meson.
Is this proof correct? I thought meson does not want to be Turing complete.

**Comment by jpakkane** [comment]
See the first issue reported on that repo. :)

**Comment by Volker-Weissmann** [comment]
Oh, I did not see that it only executes a finite amount of brainfuck-interpreter steps.
You are right, I added a comment on that issue.
