### ISSUE TITLE
Request a C subproject to use the C++ compiler

### ISSUE THREAD

**Issue by zajo** [mesonbuild/meson#8147]
Is there anything in Meson to allow the main project to request a C subproject to be built with C++?

When building Lua (which is written in C) as part of a C++ project, it is desirable to use the C++ compiler to build the Lua sources. This switches the internal error handling in the Lua interpreter to use C++ exceptions rather than `setjmp`/`longjmp` to handle errors.

**Comment by jpakkane** [comment]
No, because the language to be used is specified uniquely by the file extension. In this case the "correct" solution would be to add a project option to Lua to build it as C++. For Lua it might be sufficient to create a file `lua.cpp` with the following content:

```cpp
#include<file1.c>
#include<file2.c>
// etc etc
```

and building that instead of the C sources themselves. So something like:

```meson
if get_option('build_with_cpp')
    add_languages('cpp')
    src = files('lua.cpp')
else
    src = ... # The individual C files
endif

lualib = library('lua', src, ...)
```

**Comment by zajo** [comment]
I can't just include all 29 `.c` files in, say, `all.cpp`, because it does not compile. For example, one of the headers defines a macro `getline`, which is not compatible with the `getline` function in `<stdio.h>`, which another `.c` file uses -- and this isn't the only issue. You understand the problem in general, you can't just dump a bunch of sources into one and expect it will work.

I can find a workaround but I think that it would be in the spirit of Meson to "know" that this C-C++ compatibility is a thing and support it natively (it probably is not a good idea to support such remapping in general).

**Comment by jpakkane** [comment]
Most compilers have command line switches to compile with a different languages. For example with GCC and Clang you can do

```meson
lualib = library(..., c_args: ['-x', 'c++'], ...)
```

**Comment by zajo** [comment]
Hm, I had forgotten about that. MSVC also has `/TP`. This is reasonable, thanks.

**Comment by zajo** [comment]
Sorry one more thing, is there a way to force this from the main project?

**Comment by jpakkane** [comment]
Only with `add_global_arguments` but you probably don't want that.
