### ISSUE TITLE
does not compile .vala file from configure_file()

### ISSUE THREAD

**Issue by benwaffle** [mesonbuild/meson#815]
if you add `configure_file(input: 'config.vala.in', output: 'config.vala', configuration: conf)` to sources, config.vala is not compiled and we get a ninja error `cc: error: app@exe/config.c: No such file or directory`

**Comment by QuLogic** [comment]
Did you add the result of `configure_file` to the source for `app`?

**Comment by benwaffle** [comment]
yep

**Comment by nirbheek** [comment]
I can't reproduce this. Could you put your project up somewhere? Or perhaps a reduced version that still reproduces this.

**Comment by benwaffle** [comment]
Hmm, it seems to only break with subdirectories. Here is a test case: 
[bug.zip](https://github.com/mesonbuild/meson/files/491757/bug.zip)

**Comment by benwaffle** [comment]
The error is happening again. bug.zip above doesn't build

**Comment by ztefn** [comment]
@benwaffle I just stumbled on this error using version **0.44.0** on Arch Linux. That same build worked just fine with version **0.40.1** on Ubuntu 16.04.

I was luckily able to fix (or work around) the error by [moving everything to do with source compilation over to the /src subdirectory](https://github.com/ztefn/haguichi/commit/24d17006bf564a4f29a184d219264c41505f48e0).

**Comment by astavale** [comment]
Probably regressed because of #2413 That added --basedir to the valac flags so the output files follow the directory structure relative to the given base directory in the source. Could try reverting 1e3d03c as a starting point?

**Comment by nirbheek** [comment]
This only happens when the build directory is a subdir of the source tree. Annoying.
