### ISSUE TITLE
dependency() on a macOS framework cannot be found while cross-compiling.

### ISSUE THREAD

**Issue by UncombedCoconut** [mesonbuild/meson#8165]
**Describe the bug**
I'm attempting to build a Meson project in an "[osxcross](https://github.com/tpoechtrager/osxcross)" setting (build system: Linux; host system: Darwin).
I've hit what looks like an obvious mistake in Meson's programming, so I'd like to run that by folks before providing a complete reproduction (see below). (However, depending on what Meson needs, I'll see whether it's possible to get a reduced test case.)

The meson.build file has a dependency() on Apple's "Foundation" framework, among others.
In the cross environment, what's reported is: `ERROR: Dependency "Foundation" not found, tried pkgconfig"`
On an actual Mac, the log shows Meson doing something reasonable:
```
Finding framework path by running:  cc -v -E - -pipe

Looking for framework physfs in /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks
```
Meson has a cross file available, so the same strategy ought to work for my osxcross build, but it doesn't bother.
The code responsible for this decision is one of these snippets in `mesonbuild/dependencies/base.py`
```
        # On OSX, also try framework dependency detector  
        if mesonlib.is_osx():
            candidates.append(functools.partial(ExtraFrameworkDependency, name, env, kwargs))
```
The implementation in `mesonbuild/mesonlib.py` is
```
def is_osx() -> bool:
    return platform.system().lower() == 'darwin'
```
As far as I can tell, it's impossible for this to succeed in a cross-compilation environment, because it's checking the **build's** platform rather than the host's.
I am able to get past this error by editing these scripts in `/usr/local/lib/python3.9/dist-packages/mesonbuild/`.

**To Reproduce**
So far, my answer is nasty, along the lines of "download an enormous Docker image, clone a 1GB git repo into it, and run Meson setup."
I'm sorry.
What are your needs in terms of reduced test cases?

**Expected behavior**
I would expect Meson to perform the same search "ExtraFrameworkDependency" search anytime the host system makes it appropriate to do so.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
Yes.
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
Ubuntu 20.04 (Docker image).
* what Python version are you using e.g. 3.8.0
3.9.1
* what `meson --version`
0.56.0
* what `ninja --version` if it's a Ninja build
1.10.0

**Comment by dcbaker** [comment]
I think this is actually an easy one, can you try this patch and let me know if it works: https://github.com/dcbaker/meson/commit/7760177531dd8f48d8007547169c63349abf2974?

**Comment by UncombedCoconut** [comment]
Thank you, I just tested your patch and it looks good.
(My build isn't quite across the finish line, but the problem is probably my mistake and definitely not this issue anymore.)

**Comment by dcbaker** [comment]
Thanks, I've cleaned up everything else, and opened an MR for this.
