### ISSUE TITLE
Meson not working within MSYS2 environment

### ISSUE THREAD

**Issue by radioactiveman** [mesonbuild/meson#8173]
**Describe the bug**
Meson does not work for me within a MSYS2 environment. Any command fails with an error about a wrong Python installation.
According to the [documentation](https://mesonbuild.com/Getting-meson.html#msys2-python3-quirks), Meson should work after installing the MinGW Python. What am I missing here?

**To Reproduce**
Run the commands below in a MinGW shell (MSYS2 MinGW 32-bit):

```sh
$ pacman -Syu
$ pacman -S meson
$ pacman -S mingw-w64-i686-python3
$ meson --version
ERROR: This python3 seems to be msys/python on MSYS2 Windows, which is known to have path semantics incompatible with Meson
ERROR: Please install and use mingw-w64-i686-python3 and/or mingw-w64-x86_64-python3 with Pacman
```

```sh
$ command -v python
/mingw32/bin/python

$ python --version
Python 3.8.7
```

**Expected behavior**
Meson should use the Python which works as exptected.

**System parameters**
* Windows 10 1809
* Python 3.8.7
* Meson 0.56.0

**Comment by radioactiveman** [comment]
Hello @lazka, @nirbheek,

are you able to reproduce this?
What else needs to be done besides installing mingw-python?

Thanks.

**Comment by lazka** [comment]
you need to install mingw meson and be in a mingw shell.

**Comment by radioactiveman** [comment]
```sh
$ pacman -S mingw-w64-i686-meson mingw-w64-i686-pkg-config
```
Thanks, Meson is working fine now. :+1:

**Comment by dtromb** [comment]
> you need to install mingw meson and be in a mingw shell. https://packages.msys2.org/base/mingw-w64-meson

So in other words, MSYS2 is not supported by meson at all?  Is there no way to run meson in a build process from an MSYS2 shell?

**Comment by lazka** [comment]
> So in other words, MSYS2 is not supported by meson at all? Is there no way to run meson in a build process from an MSYS2 shell?

No, everything should work. If something doesn't, file a bug and feel free to ping me.
