### ISSUE TITLE
[Feature Request] print(var) command for debugging

### ISSUE THREAD

**Issue by Volker-Weissmann** [mesonbuild/meson#8177]
Hello,

for easier debugging of meson.build files, it would be nice if the meson dsl had a print(var) command that would print the value of the variable when you run `meson setup build`.

**Comment by eli-schwartz** [comment]
What's the advantage of this over:
```
message(var)
```

**Comment by Volker-Weissmann** [comment]
Sorry, I did not know that the message command did exist.
