### ISSUE TITLE
i18n: gettextname-pot target requires po/POTFILES in source directory

### ISSUE THREAD

**Issue by tp-m** [mesonbuild/meson#818]
In an autotools setup you usually have `po/POTFILES.in` from which `po/POTFILES` is created at configure time. Why I'm not sure, I've never seen anything in a POTFILES.in that looked like it would be substituted. Maybe it's for the timestamp, who knows.

In any case, `ninja gettextname-pot` currently has `po/POTFILES` hard-coded and looks for it in the source directory. That is suboptimal for projects who want to have meson and autotools build in parallel.

Possible solutions:
 * add option to `i18n.gettext()` to pass the name of the `POTFILES` files (then we could just use the `POTFILES.in` from the source dir; optionally support a configure_file() too
 * look for `$topsrcdir/po/POTFILES.in` automatically if `$topsrcdir/po/POTFILES` does not exist.
 * anything else?

**Comment by jpakkane** [comment]
I wondered about this when writing the gettext module, too. Timestamp is the probable answer but now that we have reproducible builds timestamps of any kind are very much frowned upon.

Does gettext work if it is given `POTFILES.in` instead of `POTFILES`? Checking which one of these exists and then using it seems like the simplest thing to do.

**Comment by eli-schwartz** [comment]
> In an autotools setup you usually have `po/POTFILES.in` from which `po/POTFILES` is created at configure time. Why I'm not sure, I've never seen anything in a POTFILES.in that looked like it would be substituted. Maybe it's for the timestamp, who knows.

This is because the generated POTFILES is not a valid xgettext input at all, and only POTFILES.in may be used. The generated POTFILES is actually a Makefile snippet that is then inlined into the Makefile by the `./configure` script.

See #5145 for more details.
