### ISSUE TITLE
meson introspect example doesn't seem to work

### ISSUE THREAD

**Issue by gregsskyles** [mesonbuild/meson#8182]
**Describe the bug**
Following the example for `meson introspect` at https://mesonbuild.com/Commands.html#introspect leads to `No command specified`.

**To Reproduce**
Create a toy project as per the Absolute Beginner's Guide:
```
mkdir testproject
cd testproject
meson init --name testproject --build
```
This works swimmingly; no errors or warnings with the build nor when running the resulting executable. Then attempt `meson introspect` as per the documented example:
`meson introspect build`

**Expected behavior**
I would have expected a '[d]isplay [of] basic information about a configured project in `build`.'

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? Plain native build.
* what operating system: Windows 10 using the x64 Native Tools Command Prompt for VS 2019
* what Python version are you using: I'm hoping the version packaged with the Meson `.msi` file; my `C:\PRogram Files\Meson` directory contains `python39.dll`. `python --version` reports 2.7.18, which can't be what's being used by Meson as it wouldn't work at all. As a test, I cleared the path of any python and conda related directories, and retried, with the same result.
* what `meson --version`: 0.56.2
* what `ninja --version`: 1.10.2

**Comment by mensinda** [comment]
Seems like there are some issues with the `Commands` section in the docs. All relevant information about our introspection is in https://mesonbuild.com/IDE-integration.html

**Comment by eli-schwartz** [comment]
`meson introspect --help` does not indicate that one of `[--ast] [--benchmarks] [--buildoptions] [--buildsystem-files] [--dependencies] [--scan-dependencies] [--installed] [--projectinfo] [--targets] [--tests]` is actually required. I'm not sure how to actually indicate this in the help text, given that argparse generally considers `--option`s to be optional and operands to be required, and fully controls the emitted help text.

It's possible to mark one `--option` as required, but not (AFAIK) to mark a set of `--option`s as "at least one is needed". To be fair, that's a bit unusual even for a non-posix-compatible argument parser.

**Comment by eli-schwartz** [comment]
https://mesonbuild.com/Commands.html#examples4 does still suck though, and should mention `--projectinfo`.

**Comment by mensinda** [comment]
Ideally, we would update `Commands.md` (or rather the template/generator) to add some additional information for introspection and maybe even links to the actual documentation.

**Comment by eli-schwartz** [comment]
The generator just inserts the output of each command's --help text.

I agree the Commands.md template could use some better manual description of the way it works, beyond just "help text" and "no-longer-broken example".

**Comment by dnicolodi** [comment]
Could the `introspect` command be made to work similarly to the `wrap` command, ie with sub-commands instead than options? Namely `meson introspect targets`  instead than `meson introspect --targets`. In this way it is easy to mark the subcommands as required. The options could be kept for a while for backward compatibility.

**Comment by eli-schwartz** [comment]
One problem is, it currently uses operands (i.e. subcommands) for the name of the configured `builddir/`. It's similar to but not entirely like the problem where we accept `meson builddir/` as implicitly the `meson setup builddir/` command, and it's not clear how to safely deprecate this.

The other problem is, you can use `meson introspect builddir/ --tests --targets` to list both.

**Comment by dnicolodi** [comment]
It would need to use the `-C` option like `compile` then: `meson introspect tests targets -C builddir/`. I think the deprecation of valid commands is not an issue, it is easy to understand that `meson introspect build --tests` is an old style call and `meson introspect tests -C build` is a new style call. Invalid commands are a bit harder, and some cases cases will be misunderstood, but they are invalid anyhow...

**Comment by mensinda** [comment]
The main problem with changing the syntax is that the introspection API is an actual API with stability requirements that is already used by other projects. So we can't just go and break it without a good reason (and I personally don't think that a slightly better syntax is a valid argument here). We would also have to deprecate the old logic (since we definitely can't just remove it) and would have to maintain APIs which means more code, more room for error, and a higher maintenance burden.

I agree that `meson introspect targets -C build` is way nicer, however, it already had the current syntax before I started working on meson and it probably stays like that until the end of time :(

**Comment by gregsskyles** [comment]
The example at [https://mesonbuild.com/Commands.html#examples4](https://mesonbuild.com/Commands.html#examples4) is now functional; sorry, I should have checked and closed this sooner.
