### ISSUE TITLE
Executables with DLL deps passed to add_install_script() can't run on Windows

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#8187]
If you have an `executable()` that has DLL deps in other builddir sub-dirs, then it can't be run by `meson.add_install_script()` on Windows because we do not do the same magic that we do for `custom_target()`, `test()`, etc to setup `PATH` to all the DLL dependencies of that executable.

Specifically, in `mesonbuild/backend/backends.py` we need to edit `Backend.generate_custom_install_script()` and have it do the same magic as `Backend.generate_custom_target()`. That is, it needs to call `self.as_meson_exe_cmdline()` which contains the necessary machinery, for instance it calls `self.determine_windows_extra_paths()`.

**Comment by tp-m** [comment]
This causes issue on Windows with fontconfig's `fc-cache` tool running as part of the install procedure (where it then can't find the libs it needs), see https://gitlab.freedesktop.org/fontconfig/fontconfig/-/issues/260 (or https://gitlab.freedesktop.org/gstreamer/gst-build/-/issues/144)

**Comment by Neumann-A** [comment]
I can also confirm this being also a problem in GTK running glib parts in a post install script. My solution currently is running it manually.
