### ISSUE TITLE
Linux: -bash: _meson-init: command not found

### ISSUE THREAD

**Issue by mhw0** [mesonbuild/meson#8202]
**Describe the bug**
I'm trying to view the available options using the command: `$ meson init -<TAB>`. But I'm getting this error: `-bash: _meson-init: command not found`

![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/69183283/104597198-d7c49580-5696-11eb-93b0-7778d9377774.gif)

**system parameters**

* OS: Manjaro Linux 20.2 Nibia. Kernel: x86_64 Linux 5.4.80-2-MANJARO
* Python version: `3.8.6`
* Meson version: `0.56.2`
* Ninja version: `1.10.1`

**Comment by dcbaker** [comment]
The bash completions seem to be really out of date. I updated the zsh ones not too long ago, and it looks like the bash ones need similar treatment. I'm not a bash user, so maybe someone who uses bash wants to look at it?

**Comment by eli-schwartz** [comment]
I can take a look at it as I'm a bash user and have authored bash-completion files in the past.

**Comment by 4h7l** [comment]
@eli-schwartz ping ?

**Comment by tristan957** [comment]
@lukester1975 would your PR fix this?

**Comment by tristan957** [comment]
Oh wait. I can't even reproduce this anymore. Can be closed.
