### ISSUE TITLE
Python 3.9 in Meson-0.56.2-64.msi does not work in windows 7

### ISSUE THREAD

**Issue by nihlete** [mesonbuild/meson#8208]
**Describe the bug**
Python 3.9 is not supporting Win7, in particularly `python39.dll relies` on `api-ms-win-core-path-l1-1.0.dll`

https://bugs.python.org/issue40740 -- similar error
https://www.python.org/downloads/windows/ -- direct version restriction

The `meson-0.56.2-64.msi` brings python 3.9 while https://mesonbuild.com/Release-notes-for-0-56-0.html only warning about 
python 3.6 dependency in next release.

**To Reproduce**
- Install `meson-0.56.2-64.msi` on windows 7.
- Call from cmd `meson`

*Meson directory structure*
<details>
  <summary>Spoiler</summary>

```
C:\Program Files\Meson>tree /F
Структура папок
Серийный номер тома: 4E04-CFAB
C:.
│   base_library.zip
│   libcrypto-1_1.dll
│   libffi-7.dll
│   libssl-1_1.dll
│   meson.exe
│   meson.exe.manifest
│   ninja.EXE
│   pyexpat.pyd
│   python39.dll
│   select.pyd
│   unicodedata.pyd
│   VCRUNTIME140.dll
│   _asyncio.pyd
│   _bz2.pyd
│   _ctypes.pyd
│   _decimal.pyd
│   _elementtree.pyd
│   _hashlib.pyd
│   _lzma.pyd
│   _multiprocessing.pyd
│   _overlapped.pyd
│   _queue.pyd
│   _socket.pyd
│   _ssl.pyd
│   _uuid.pyd
│
└───Include
        pyconfig.h

```

</details>

*Output:*
```
C:\Users\WS-0001>meson
Error loading Python DLL 'C:\Program Files\Meson\python39.dll'.
```

*Popup:*
![Безымянный](https://user-images.githubusercontent.com/9762164/104734785-d310e780-5751-11eb-85a4-bad243e3853c.png)

**Expected behavior**
Successful start of meson.

**system parameters**
Windows 7.

**Comment by eli-schwartz** [comment]
> Sorry, Windows 7 is no longer supported in Python 3.9.

That's pretty problematic for shipping frozen binaries.

**Comment by nihlete** [comment]
Unfortunately, 0.57.0 release have same issue.

As I understand, [script](https://github.com/mesonbuild/meson/blob/master/packaging/createmsi.py) should be called from `python < 3.9` environment. There is no need to fix something in script itself.

*PyInstaller* [doc](https://pyinstaller.readthedocs.io/en/stable/operating-mode.html) fragment: 
![image](https://user-images.githubusercontent.com/9762164/107932208-58c0c680-6f8e-11eb-91b5-3e638b14fe4b.png)

**Comment by nihlete** [comment]
Release 0.57.1 have same issue.
@eli-schwartz may you know somebody related to release packaging? It would be great if you call them here.

**Comment by jpakkane** [comment]
It is intentiontionally Win 10 only as Windows 7 is officially out of support by Microsoft. The package is built with the newest Python for simplicity.

Note that anyone can build their own msi packages on older Pythons or OSs by doing the following:

- install Wix tools
- start a VS developer tools shell
- cd into meson source root
- run `python packaging\createmsi.py`

**Comment by eli-schwartz** [comment]
IMO the current behavior is broken at least because the .msi installer doesn't declare the required windows version.

**Comment by nihlete** [comment]
> The package is built with the newest Python for simplicity.

Is it really harder to change python version in release prep, than make life harder for 20% global market share ([link](https://www.theverge.com/2021/1/6/22217052/microsoft-windows-7-109-million-pcs-usage-stats-analytics))? 

With all due respect to your right to pursue a policy that you consider reasonable.

P.s. https://mesonbuild.com/
> Meson is an open source build system meant to be both extremely fast, and, even more importantly, as user friendly as possible.
>The main design point of Meson is that every moment a developer spends writing or debugging build definitions is a second wasted. So is every second spent waiting for the build system to actually start compiling code.

**Comment by eli-schwartz** [comment]
#8437 adds a Windows version check to the .msi installer in order to require Windows 10. I'm sorry that this isn't the solution you want ;) but this will make the support status clear and users trying to use the .msi on Windows 7 will no longer get confusing DLL errors after they successfully ran the installer.
