### ISSUE TITLE
Cannot run meson.py from source on Windows

### ISSUE THREAD

**Issue by marstaik** [mesonbuild/meson#8209]
**Describe the bug**
When attempting to run meson.py from windows, you get this error:

```bash
PS D:\Projects\kenos\godot\build> C:\Dev\Python36\python D:\Projects\meson\meson.py --reconfigure -Dtarget=release_debug
Traceback (most recent call last):
  File "D:\Projects\meson\mesonbuild\mesonmain.py", line 132, in run
    return options.run_func(options)
  File "D:\Projects\meson\mesonbuild\msetup.py", line 275, in run
    app.generate()
  File "D:\Projects\meson\mesonbuild\msetup.py", line 180, in generate
    if env.coredata.options[mesonlib.OptionKey('backend')].value == 'xcode':
AttributeError: 'CoreData' object has no attribute 'options'
```

I am experiencing this with both python3.8 and python3.6.
I was attempting to use source to make submit a patch, and could not even test any changes locally.

Adding a `print(dir(env.coredata))` before line 180 in `msetup.py` indeed shows that the `options` variable isn't defined, despite it being defined in the `init` constructor.

**Comment by dcbaker** [comment]
`coredata.options` is relatively new (my code, merged a week ago), did you create the original meson checkout with a released version? if so try `meson $builddir --wipe`.

**Comment by marstaik** [comment]
That seems to have worked, thanks.
