### ISSUE TITLE
i18n: detect if required tools are available and add --disable/enable-nls options

### ISSUE THREAD

**Issue by tp-m** [mesonbuild/meson#821]
Currently, when the i18n module is used, but the various gettext tools are not available, the meson configure runs just fine but then `ninja install` just errors out:

```
FileNotFoundError: [Errno 2] No such file or directory: 'msgfmt'
Failed to run install script: /usr/bin/python3 /usr/bin/../share/meson/meson.py --internal gettext install po gstreamer-1.0 share/locale af az be bg ca cs da de el en_GB eo es eu fi fr gl hr hu id it ja lt nb nl pl pt_BR ro ru rw sk sl sq sr sv tr uk vi zh_CN zh_TW
```

This seems suboptimal. I don't think every meson project should have to check first whether those tools are available or not before importing the i18n module. That defeats the points of the module a little.

I also think the i18n module should expose standard options to enable/disable i18n, and automatically turn its targets into no-ops or errors if disables.

I can see three modes:
1. auto = check if tools are installed and disable if required tools not there (default)
2. enable = check if tools are installed and error out if required tools not there
3. disable = skip

**Comment by jpakkane** [comment]
The simplest solution would probably be that the gettext script checks if the tools exist. If they do, great, and if not just print a message saying that this operation did nothing because the tools are not available, please install them.

**Comment by rossburton** [comment]
Another +1 for this.

**Comment by dylanaraps** [comment]
Any updates on this issue? I'm building a Linux distribution without `gettext` and am now forced to include it for anything which requires `meson` to build. If there's a method of bypassing `gettext` at build time for each project that would work too.

**Comment by mikecrowe** [comment]
This is causing problems for OpenEmbedded[1] too where compilation without NLS support is a feature.

Removing the subdir('po') line from meson.build appears to be sufficient to work around the problem[2], but some sort of standard way to do this would be much less brittle.

[1] http://lists.openembedded.org/pipermail/openembedded-core/2019-February/279344.html
[2] http://lists.openembedded.org/pipermail/openembedded-core/2019-July/285157.html

**Comment by jpakkane** [comment]
The simplest solution is to detect if gettext is not available, print a warning and then make gettext based operations no-ops. Would that work?

**Comment by mikecrowe** [comment]
> The simplest solution is to detect if gettext is not available, print a warning and then make gettext based operations no-ops. Would that work?

That sounds like it would be great. Thanks.

**Comment by dhewg** [comment]
On NLS-less OpenWrt and meson 0.52.0, `ninja install` errors out due to missing `itstool`: https://5919-20307838-gh.circle-artifacts.com/0/home/build/build_dir/logs/package/feeds/packages/grilo-plugins/compile.txt
Does that need to be handled on the meson side as well?
