### ISSUE TITLE
Add a Java system dependency for facilitating JNI development

### ISSUE THREAD

**Issue by tristan957** [mesonbuild/meson#8227]
I am working on Java bindings for a project. Java installations typically come with an `include` folder that has various headers for interacting with the JVM or the JNI. The `include` directory isn't symlinked into a default header location by default, no does it typically reside in the same location across systems (Fedora, Ubuntu, Windows, Mac, etc.).

I want to propose a Java system dependency that hooks up any libraries and include directories to your project.

I am interested in creating a PR for this myself.

**Comment by dcbaker** [comment]
Are you sure you need a module and not a dependency()?

**Comment by tristan957** [comment]
Good point. Java doesn't install a .pc file is seems, so how would you resolve `dependency('java')`. I know right now it seems like Meson looks through CMake and pkg-config to find the dependency you are looking for. In this case, the jdk as a subproject seems like overkill.

**Comment by MathieuDuponchelle** [comment]
there are 'hardcoded' dependency names, eg `threads` I think is one

**Comment by dcbaker** [comment]
I've written a ton of those, they're called `system` dependencies.

I've never written any java of consequence, let alone anything using JNI, but usually these things go find the correct paths and just set them up manually. So I guess you'd read `$JAVA_HOME`, then set the `compile_args` attribute to include `$JAVA_HOME/include` and link the necessary libraries from `$JAVA_HOME/lib`.

**Comment by dcbaker** [comment]
the `zlib` system dependency is in the current style, and is pretty simple if you wanted to look at some code. Also feel free to ping me, I know entirely too much about that code...

**Comment by tristan957** [comment]
Oh in that case, yea a `dependency('java')` would solve my problem. I think checking for version is a little bit more difficult. Is that going to be a problem? Right now the only think I can think of is JAVA_HOME/bin/java -version. But tying that to command output seems nasty because it's not like output is API that is guaranteed to be stable.

**Comment by tristan957** [comment]
Where can I read about system dependencies? I never knew about this feature.

**Comment by dcbaker** [comment]
We have a terrifying pile of regex for that :) `environment.search_version`.

The documentation seems to be rather lacking. I can fix that.

**Comment by tristan957** [comment]
Oh boy am I excited to look into that haha. I will see what I can do today after work. Should be a fun intro into the codebase.

**Comment by jpakkane** [comment]
As a dependency name `jni` is probably better than `java`. I looked into adding this  ages ago but the need for it evaporated. From what I can remember it would have needed to do something like this (on Linux):

- detect currently used JVM
- trawl the file system for headers and libs (which are _not_ under `/usr/include` but somewhere else, maybe under `lib` or `share`
- build up the corresponding compile and link args

Another thing I remember pondering was that there are two different ways of doing JNI, one required compiling the source with `javah` or something while the newer one worked in some easier way. It would be nice to not have to support the former but I don't know how widespread its usage is nowadays.

**Comment by dcbaker** [comment]
Here's my attempt to add some docs on writing system dependencies: https://github.com/mesonbuild/meson/pull/8228

**Comment by tristan957** [comment]
Closing because it was implemented for 0.58.
