### ISSUE TITLE
Applying git patches on top of subproject using patch_directory

### ISSUE THREAD

**Issue by CoffeeFlux** [mesonbuild/meson#8230]
I've ported a project of nontrivial complexity (LuaJIT) to Meson, and I'm storing the `meson.build` files in `packagefiles` and using `patch_directory` in the wrap.

The ability to store the files directly is a godsend for a sufficiently complex wrap, since then I no longer have to maintain a separate patch file, but I'd also like to be able to apply a small, fixed git patch to existing files in the source.

Is there any way to do this without writing an extra Python script? It seems I can't have both a `patch_filename` and `patch_directory` defined.

Currently on Meson 0.56.1

**Comment by xclaesse** [comment]
I would rather recommend hosting a git branch with the patches, but I know it's not always possible. I agree this would be a nice feature to add.

Let's close a dup of https://github.com/mesonbuild/meson/pull/4570.
