### ISSUE TITLE
cpp_eh=none wrongly documented

### ISSUE THREAD

**Issue by Neumann-A** [mesonbuild/meson#8233]
Docs state:
> When using MSVC, cpp_eh=none will result in no exception flags being passed,

but I see:
```
cl : Command line warning D9025 : overriding '/EHs-' with '/EHs'
cl : Command line warning D9025 : overriding '/EHc-' with '/EHc'
```
so it is actively trying to deactivate exception flags

**Comment by eli-schwartz** [comment]
Changed in #6116

https://github.com/mesonbuild/meson/blob/f24307e55943f08e1a505a24112ee62d127c0900/docs/markdown/Builtin-options.md?plain=1#L283-L287

@jpakkane
