### ISSUE TITLE
--output=@OUTPUT@ fails to expand

### ISSUE THREAD

**Issue by TingPing** [mesonbuild/meson#824]
This only works if `@OUTPUT@` is a lone argument which doesn't work with some tools.

**Comment by jpakkane** [comment]
You can specify individual output items with `@OUTPUT0@`, `@OUTPUT1@` etc.

**Comment by nirbheek** [comment]
I think what @TingPing means is that it won't work with tools that don't accept `--output @OUTPUT@` and require it to be `--output=@OUTPUT@`.

**Comment by jpakkane** [comment]
Hmmm, weird. It should work because [we even have test for it](https://github.com/mesonbuild/meson/blob/master/test%20cases/common/98%20gen%20extra/meson.build):

**Comment by TingPing** [comment]
Just a basic test:

```python
custom_target('testing',
    input: 'plain.c',
    output: 'something.c',
    command: ['echo', ['--input=@INPUT@', '--output=@OUTPUT@']],
)
```

Results: `--input=@INPUT@ --output=@OUTPUT@`

**Comment by TingPing** [comment]
> You can specify individual output items with @OUTPUT0@, @OUTPUT1@ etc.

Also at a glance I don't see that in the reference manual? Any other variables supported because it would be nice to expose `@BUILD_DIR@` and similar as a convenience.

**Comment by nirbheek** [comment]
Yeah, our documentation of `custom_target` and `generator` needs updating.

The build dir should be available as the `MESON_BUILD_DIR` environment variable. If it isn't, that's a bug.

**Comment by nirbheek** [comment]
I can't remember; was this resolved? `@OUTPUT@` is working fine right?

**Comment by TingPing** [comment]
Nope.
