### ISSUE TITLE
Meson automatic reconfigure before compile does not work for all backends

### ISSUE THREAD

**Issue by jmoguillansky-gpsw** [mesonbuild/meson#8241]
When compiling using meson, can it first reconfigure automatically by checking if the meson.build timestamp is newer?

Currently meson requires the user to manually run reconfigure.

**Comment by eli-schwartz** [comment]
This is already the case. The generated `build.ninja` contains a rule, whereby `build.ninja` itself depends on every `meson.build` or `configure_file()` input and if those inputs are newer, runs the rule `REGENERATE_BUILD`

```
$ ninja -C builddir
ninja: Entering directory `builddir'
ninja: no work to do.
$ touch meson.build
$ ninja -C builddir
ninja: Entering directory `builddir'
[0/1] Regenerating build files.
The Meson build system
Version: 0.56.2
[...]
```

**Comment by jmoguillansky-gpsw** [comment]
How about with visual studio backend or xcode backend?

It might be better if this logic is handled in meson instead of in the backend (when running meson compile) so it will work across backends?

**Comment by eli-schwartz** [comment]
I have no idea about other backends. Can they emit the same kind of dependency information?

**Comment by jmoguillansky-gpsw** [comment]
I don't think the visual studio project files can handle this logic, they're just an XML file with various properties.  
I think it would be easier if Meson handles this at a higher level

**Comment by eli-schwartz** [comment]
That would only work when using the `meson compile` wrapper, but that's definitely better than nothing.

It would be slightly inconsistent...

**Comment by jpakkane** [comment]
The VS backend does the regeneration already. Always has. I think XCode does as well but it's sadly quite undermaintained.

**Comment by eli-schwartz** [comment]
@jmoguillansky-gpsw Which backend are you using that isn't being regenerated?

**Comment by jmoguillansky-gpsw** [comment]
sorry you're right, it works for xcode and visual studio backend.
