### ISSUE TITLE
[Discussion] Update Meson in Ubuntu 18.04 to a newer version

### ISSUE THREAD

**Issue by dreamer** [mesonbuild/meson#8247]
*I am creating this report in meson repo only because I noticed @jpakkane is a package maintainer for meson in Ubuntu; if it's more appropriate to have this discussion in Ubuntu mailing list then let me know or just close this report*.

#### Background
In [dosbox-staging](https://github.com/dosbox-staging/dosbox-staging) project, we are migrating away from autotools to Meson and so far it's going great - thank you so much to the whole Meson team for creating such robust and well-designed tool :) We still encounter some quirks and edge cases here and there - I will be reporting them once I will be 100% sure they are meson problems.

The biggest problem we're facing during migration is: we strongly prefer to use `meson` provided by OS rather than downloading from pip - it makes packager's lifes easier and we avoid problems when running builds in Docker, where pip sometimes fails (for various reasons).

*Context: for our testers we provide cross-distro builds (binaries packaged in tarballs - they work in any distro because we are very careful about ABIs we depend on) - the key for having those builds working is making them on *the oldest* stable distribution. In the past it meant targeting Debian Stable, later we moved on to Ubuntu 16.04 LTS, but it's closing to EOL so we moved on to Ubuntu 18.04 recently (which we'll likely to target for several years now)*.

This means we are bound to the Meson features available in version 0.45.1… Some very useful features that are missing from this version are:

- dictionaries (meson >= 0.47.0)
- support for `in` operator for lists and dictionaries (meson >= 0.49.0)
- support for `break` and `continue` statement in loops  (meson >= 0.49.0)
- support for `not_found_message` keyword for dependencies (not documented when this feature was added)
- support for `ppc64` machine cpu family (it's named `ppc64le` - this might be a bug, I'm not sure - it contradicts [documentation](https://mesonbuild.com/Reference-tables.html#cpu-families)).

#### Wider context

At the moment, Ubuntu 18.04 LTS provides meson 0.45.1 - with exception of 16.04 this seems to be the oldest generally available version. In a few months, Ubuntu 16.04 LTS (using meson 0.29.0 ATM) will reach EOL and 18.04 LTS will become the oldest free offering by Canonical. Subsequently, we can expect 18.04 will soon be the oldest Linux image picked by various CI providers (it already is the default e.g. on GitHub CI), and will likely be the base for numerous other Linux distributions. 

I think updating Meson in Ubuntu 18.04 to a newer version would be very valuable throughout the whole ecosystem:

- Large and important projects like Mesa, systemd, or Gnome could start using features from newer Meson versions, and people working on backports to older distros would have a much easier time.
- Having features like dictionaries and break/continue keywords available in practically any installation out there makes it easier for new projects to migrate to Meson.
- People extending/upgrading existing meson buildsystems could probably replace complicated if-else logic with more readable use of loop+dictionary+break

[Meson versions in various "stabler" repositories as of January 2021](https://repology.org/project/meson/versions)

- CentOS 8: meson 0.49.3
- Debian Stable (and various derivatives like Raspbian Stable): meson 0.49.2
- EPEL 7: meson 0.55.1
- Fedora 31 (soon reaching EOL): meson 0.51.2
- openSUSE Leap 15.2 (15.1 is reaching EOL): meson 0.54.2

**I do not suggest going straight to the newest version**, but rather sticking to the older, stable one - 0.49 seems to be a good candidate. I bet @jpakkane will know the best which version would be the most appropriate in this context.

**Comment by eli-schwartz** [comment]
jpakkane is not the Ubuntu maintainer AFAIK, only the Debian maintainer.

As for Ubuntu, they copy lots of packages from Debian without changing the maintainer info, but have their own release cycle not tied to Debian -- and Debian package maintainers do not generally have the influence to update things in Ubuntu in my experience, to their dismay.

**Comment by dreamer** [comment]
@eli-schwartz Thank you; I guess the appropriate place for discussion is Ubuntu devel mailing list then…

**Comment by xclaesse** [comment]
Let's close this issue then, it's for downstream.

**Comment by dreamer** [comment]
@xclaesse Thank you for closing this report :) I just posted the request/question to Ubuntu.

Discussion continues in here: https://answers.launchpad.net/ubuntu/+source/meson/+question/695168

**Comment by neheb** [comment]
If you want a newer meson with Ubuntu 18.04, install it with pip3.

**Comment by dreamer** [comment]
@neheb I already explained in original post.

Installing meson using pip3 is an option for end-developers, but it's not a good option for CI builds or packagers - we had issues with using pip3 when building inside a docker container, and packagers need an option have fully offline build, using meson version provided by their OS.

**Comment by eli-schwartz** [comment]
> support for `not_found_message` keyword for dependencies (not documented when this feature was added)

https://mesonbuild.com/Reference-manual.html#dependency
`not_found_message (since 0.50.0): an optional string that will be printed as a message() if the dependency was not found.`

> support for `ppc64` machine cpu family (it's named `ppc64le` - this might be a bug, I'm not sure - it contradicts [documentation](https://mesonbuild.com/Reference-tables.html#cpu-families)).

https://mesonbuild.com/Reference-tables.html#cpu-families
Those porting from autotools should note that meson does not add endianness to the name of the cpu_family. For example, autotools will call little endian PPC64 "ppc64le", meson will not, you must also check the `.endian()` value of the machine for this information.

**Comment by dreamer** [comment]
For `not_found_message` the situations is "ok-ish" in old Meson. We use this feature (because it's really neat :) ) and simply ignore warnings generated by Meson 0.45.1:
```
meson.build:154: WARNING: Passed invalid keyword argument "not_found_message".
WARNING: This will become a hard error in the future.
```
About `ppc64`:

> Those porting from autotools should note that meson does not add endianness to the name of the cpu_family. For example, autotools will call little endian PPC64 "ppc64le", meson will not, you must also check the .endian() value of the machine for this information.

We do follow value returned by machine's `.endian()` function - it's very convenient :)

However, on Ubuntu 18.04, when building for PPC64 target, value returned by `host_machine.cpu_family()` is `ppc64le` (not `ppc64` as documentation suggests). I decided to handle both names the same way. If someone is interested here's our code: https://github.com/dosbox-staging/dosbox-staging/blob/7b4ab66c47706e4d2d4c58f8e921523254393db0/src/cpu/meson.build

Should I report this as a bug?

**Comment by eli-schwartz** [comment]
#3846 changed this with the rationale "no one is depending on the `el` but some people are depending on it not being there". :/ It was only documented to return ppc64le on 0.47, then changed in 0.47.2 to return ppc64 -- if you need to support versions where ppc was not described in the docs, using .startswith() should work.

**Comment by dreamer** [comment]
@eli-schwartz Thanks! I will just update comment in my code to point out that `ppc64le` is for meson < 0.47.2 and when we'll eventually require newer meson version for compiling dosbox-staging, I'll drop the line entirely.

For the context: we don't have / know about any users of 64-bit PPC big-endian. Keeping the architecture name clean and avoiding `le` suffix was a good choice IMHO (after all there's no `mipsle`, so why there should be `ppc64le`).
