### ISSUE TITLE
Meson cannot cross compile libraries to windows with clang

### ISSUE THREAD

**Issue by dpassens** [mesonbuild/meson#8255]
When setting the compiler to `['clang', '--target=x86_64-unknown-windows']`, meson passes the `-fPIC` option for library source files, even if the entire project is compiled with `b_pie = false`.  As clang doesn't support `-fPIC` when compiling for windows, this makes the build fail.

When I compile [this simple project](https://github.com/mesonbuild/meson/files/5873818/test.zip) on linux (arch), I get the following:
```
$ meson build --cross-file windows.cross && ninja -Cbuild
The Meson build system
Version: 0.56.2
Source dir: /home/david/Projects/test
Build dir: /home/david/Projects/test/build
Build type: cross build
Project name: example
Project version: undefined
C compiler for the host machine: clang --target=x86_64-unknown-windows (clang 11.0.1 "clang version 11.0.1")
C linker for the host machine: clang --target=x86_64-unknown-windows ld.lld 11.0.1
C compiler for the build machine: cc (gcc 10.2.0 "cc (GCC) 10.2.0")
C linker for the build machine: cc ld.bfd 2.35.1
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
Build targets in project: 1

Found ninja-1.10.2 at /usr/bin/ninja
ninja: Entering directory `build'
[1/2] Compiling C object libexample.so.p/hello.c.o
FAILED: libexample.so.p/hello.c.o 
clang --target=x86_64-unknown-windows -Ilibexample.so.p -I. -I.. -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -g -fPIC -MD -MQ libexample.so.p/hello.c.o -MF libexample.so.p/hello.c.o.d -o libexample.so.p/hello.c.o -c ../hello.c
clang-11: error: unsupported option '-fPIC' for target 'x86_64-unknown-windows-msvc'
ninja: build stopped: subcommand failed.
```

I only attached a cross file for amd64 but the issue also exists on i386.

**Comment by dcbaker** [comment]
what does your cross file look like?

**Comment by dcbaker** [comment]
This shouldn't be happening, we have code that specifically checks if the machine being compiled for is windows and doesn't emit `-fPIC` in that case

**Comment by dpassens** [comment]
The cross file is in the zip I linked.

**Comment by dcbaker** [comment]
you have `host_system`, but that should be `host_machine`

**Comment by dpassens** [comment]
Oh, I didn't notice that wasn't the right section.  Thanks for your help and sorry for wasting your time.

**Comment by dcbaker** [comment]
No worries. There's a lot of bugs with cross compiling with clang, so I thought you'd found yet another one, but it's nice to have some easy fixes :)
