### ISSUE TITLE
Need dependency(..., headers_only : true) and so on for use with Valgrind

### ISSUE THREAD

**Issue by tp-m** [mesonbuild/meson#826]
Similar to #726 but not the same.

Use case: I want to detect valgrind via pkg-config and pass the right includes for valgrind/valgrind.h to my build, but not link to the valgrind libs (which fails because they're static libs and not built with -fPIC, but is also unnecessary because everything we need is in the headers via magic macros).

I know of other use cases where this is needed, e.g. where glib headers are used for portable typedefs but no linking is done.

`cflags = run_command('pkg-config', '--cflags', 'dep').stdout().strip().split()` is not cross-compile friendly, so doesn't seem like a good solution.

**Comment by tp-m** [comment]
I'm wondering if we actually need these getters, or if something like this wouldn't be better:
```valgrind_dep = dependency('valgrind', headers_only : true)```

**Comment by nirbheek** [comment]
I actually really like the idea of a `headers_only` kwarg here, and it's quite easy to implement too.
