### ISSUE TITLE
meson setup does not fail on bogus arguments (while meson configure does)

### ISSUE THREAD

**Issue by rmader** [mesonbuild/meson#8261]
**Describe the bug**
This came up in https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1597#note_1017341 - in short:
`meson configure -Dbuiltype=debugoptimized` fails (mind the missing `d` in `builtype`), while `meson . build -Dbuiltype=debugoptimized` doesn't

**Expected behavior**
Both options should behave the same, with failing being strongly preferred.

**system parameters**
* plain native
* Linux
* 3.9 but also older (3.5?)
* 0.55.3
* 1.10.2

**Comment by eli-schwartz** [comment]
Neither one fails. Both exit 0, both log the following warning in yellow:

```
WARNING: Unknown options: "builtype"
The value of new options can be set with:
meson setup <builddir> --reconfigure -Dnew_option=new_value ...
```

**Comment by eli-schwartz** [comment]
You can catch problems like this by running with the option `meson setup --fatal-meson-warnings`
