### ISSUE TITLE
VS backend uses /O2 optimization with debug build type

### ISSUE THREAD

**Issue by vvainola** [mesonbuild/meson#8279]
**Describe the bug**
In #8218 /Od was removed from debug buildtype flags. The comment states that /Od is default in MSVC but either the comment is wrong or the default optimization is somehow configurable. Fresh VS installations still defaults to /O2 when no optimization flags are specified.
![devenv_1TN41rYnOh](https://user-images.githubusercontent.com/20504548/106384930-32b7f580-63d6-11eb-850e-a7f4f74dd14e.png)

**To Reproduce**
Any meson.build with backend=vs and optimization=0 or buildtype=debug

**Expected behavior**
Optimizations are disabled in debug.

**system parameters**
Native build
Windows 10
Python 3.8.3
master branch
Visual Studio 16.8.4

**Comment by vvainola** [comment]
Can you add regression tag as this is now in 0.57 and 0.57.1 releases?

**Comment by jpakkane** [comment]
I tried to verify this with current Git head and could not. This is how it shows up for me.
![vsopt](https://user-images.githubusercontent.com/4079821/110205901-6aa5d300-7e83-11eb-86f5-a871911be3ab.png)

**Comment by vvainola** [comment]
Thanks for testing. It looks like it is using /O2 because I had set b_vscrt=md. With mdd it indeed defaults to no optimizations. Looks like I should have specified a meson.build with example after all. Sorry about that.
