### ISSUE TITLE
Bad test for empty options in generated configure script

### ISSUE THREAD

**Issue by whuji** [mesonbuild/meson#8290]
**Describe the bug**
The configure script generated by meson test if an option is set like this : 
`if test -n "$zlib_CFLAGS"; then`
But if the option is set to an empty value, and if the resulting behavior should be different from an unset option, this test is buggy. It should be : 
`if test "${zlib_CFLAGS+set}" = set; then`

Doing that, one can implement a differentiated behavior if : 
1. the option is unset
2. the option is set to an empty value
3. the option is set to a non empty value

**To Reproduce**
Build the JOSE lib with zlib_CFLAGS="" for example and it will behave as I did not specify the zlib_CFLAGS option at all.

**Expected behavior**
See the bug description

**Comment by dcbaker** [comment]
I'm not sure what you're try to file a bug about, meson itself never generates shell scripts, so I'm not sure where the zlib_CFLAGS is coming from.

**Comment by whuji** [comment]
My bad, wasn't meson related. Sorry
