### ISSUE TITLE
CMake toolchain file does not define CMAKE_C*_COMPILER_ABI

### ISSUE THREAD

**Issue by jpalus** [mesonbuild/meson#8293]
**Describe the bug**
meson fails to find cmake dependencies on Linux with x32 ABI. It appears to be caused by toolchain file created by meson which contrary to CMake own mechanism does not set compiler's ABI ie CMAKE_C_COMPILER_ABI or CMAKE_CXX_COMPILER_ABI. and at the same time sets CMAKE_C*_COMPILER_FORCED.

**To Reproduce**
Any meson file with cmake dependency, however cmake file needs to be in /usr/libx32/cmake directory.

**Expected behavior**
cmake dependency should be found

**system parameters**
* Plain build
* PLD Linux (arch x32)
* Python 3.8.7
* meson 0.56.2

**Comment by mensinda** [comment]
Should be fixed with #8812
