### ISSUE TITLE
TAP protocol with junit reports loses human-readable test names

### ISSUE THREAD

**Issue by ppaalanen** [mesonbuild/meson#8316]
I use Meson junit output to load the test suite report to Gitlab. This works fine when my test suite is using the `exitcode` protocol: each test has the proper name.

When I change my test suite to use TAP in Meson, all sub-tests will be present in the junit output too and Gitlab shows them. However, all test names are lost, they are just numbers (counter values), making it impossible to see in Gitlab which test or sub-test is which. The output from `meson test` command is good in any case, so I think the problem is with generating junit XML.

Junit results with `exitcode`:
https://gitlab.freedesktop.org/pq/weston/-/pipelines/267505/test_report

Junit results with TAP:
https://gitlab.freedesktop.org/pq/weston/-/pipelines/267525/test_report
(Mind, there are few tests in between that still do not use TAP, hence they get proper names.)

I would expect that with TAP protocol, the junit file would contain proper test names.

With TAP, here are the first few lines of the junit XML file:
```
<?xml version='1.0' encoding='utf-8'?>
<testsuites errors="0" failures="0" tests="313"><testsuite errors="0" failures="0" name="weston.alpha-blending" skipped="0" tests="2"><testcase classname="0" name="0" /><testcase classname="1" name="1" /><system-out>1..2
ok 1 fixture 1 alpha_blend_monotonic/1
ok 2 fixture 2 alpha_blend_monotonic/1</system-out><system-err>Iterating through 2 fixtures.
```

Here I would expect the test name (suite) is "alpha-blending" and the sub-test names (name) are "fixture 1 alpha_blend_monotonic/1" and "fixture 2 alpha_blend_monotonic/1" or something in that direction.

Meson version is 0.56.2.

The Weston MR where I produced this: https://gitlab.freedesktop.org/wayland/weston/-/merge_requests/550

**Comment by bonzini** [comment]
Please try 0.57-rc1 (plus possibly the #8322 pull request to fix bugs), it should work.

**Comment by ppaalanen** [comment]
Thanks for the quick reply, I tested your mtest-fixes branch in https://gitlab.freedesktop.org/wayland/weston/-/merge_requests/550 and it is better but not perfect.

In the Gitlab test reports, the "suite" column is always empty. Maybe that's intentional, maybe not, I'm not sure how that should map to Meson test definitions.

The "name" column in Gitlab test report has entries like `1 fixture 1 alpha_blend_monotonic/1` which is much more useful than before, but it seems the test name is still replaced with a number. I would expect the Meson test name to be `alpha-blending`, not `1`. The sub-test name is the rest of it: `fixture 1 alpha_blend_monotonic/1`

For reference, this is how Meson reports the test results:
```
 1/32 alpha-blending                         OK              0.94s   2 subtests passed
 2/32 bad-buffer                             OK              0.48s   1 subtests passed
 3/32 buffer-transforms                      OK              3.71s   48 subtests passed
 4/32 devices                                OK              2.64s   10 subtests passed
 5/32 drm-smoke                              OK              0.39s   1 subtests passed
 6/32 event                                  OK              0.51s   2 subtests passed
 7/32 internal-screenshot                    OK              0.40s   1 subtests passed
 8/32 keyboard                               OK              0.40s   4 subtests passed
 9/32 linux-explicit-synchronization         OK              0.69s   10 subtests passed
10/32 output-transforms                      OK              8.58s   56 subtests passed
11/32 plugin-registry                        OK              0.40s   1 subtests passed
12/32 pointer                                OK              0.57s   14 subtests passed
13/32 presentation                           OK              0.41s   1 subtests passed
14/32 roles                                  OK              0.58s   2 subtests passed
15/32 string                                 OK              0.08s   1 subtests passed
16/32 subsurface                             OK              1.65s   23 subtests passed
17/32 subsurface-shot                        OK              1.18s   2 subtests passed
18/32 surface                                OK              0.39s   1 subtests passed
19/32 surface-global                         OK              0.39s   1 subtests passed
20/32 text                                   OK              0.41s   1 subtests passed
21/32 touch                                  OK              0.41s   3 subtests passed
22/32 vertex-clip                            OK              0.08s   16 subtests passed
23/32 viewporter                             OK              2.08s   76 subtests passed
24/32 viewporter-shot                        OK              0.97s   2 subtests passed
25/32 yuv-buffer                             OK              1.01s   3 subtests passed
26/32 xwayland                               OK              1.17s   1 subtests passed
27/32 ivi-layout-client                      OK              0.43s   25 subtests passed
28/32 ivi-layout-internal                    OK              0.42s   1 subtests passed
29/32 ivi-shell-app                          OK              0.62s   1 subtests passed
30/32 config-parser                          OK              0.09s
31/32 timespec                               OK              0.08s
32/32 zuc                                    OK              0.11s
Ok:                 32  
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0
```
and that is really cool! Thank you very much for this work!

**Comment by bonzini** [comment]
The suite name is there in the XML file (see [here](https://pq.pages.freedesktop.org/-/weston/-/jobs/7212222/artifacts/build-weston-build-native-meson-default-options/meson-logs/testlog.junit.xml)):

```
<testsuite errors="0" failures="0" name="weston.alpha-blending" skipped="0" tests="2" time="0.9397590160369873">
<testcase name="1 fixture 1 alpha_blend_monotonic/1"/>
<testcase name="2 fixture 2 alpha_blend_monotonic/1"/>
<system-out>
</system-out>
<system-err>
</system-err>
</testsuite>
```

So it seems to be a problem in GitLab's generation of the test reports. I'll see if I can find the source code for that (help welcome :smiley:) so that we can tune Meson's generated XML.

**Comment by bonzini** [comment]
Ok, looks like the suite name is the "class name" (see HTML/JS mix [here](https://gitlab.com/gitlab-org/gitlab-foss/-/blob/master/app/assets/javascripts/pipelines/components/test_reports/test_suite_table.vue)). I updated the mtest-fixes branch.

**Comment by ppaalanen** [comment]
Oh indeed! And even running time is there.

Nice find, I kicked the CI again, but building the image takes a moment.

In `<testcase name="1 fixture 1 alpha_blend_monotonic/1"/>` I don't like the leading `1 `. I guess I should stop printing it into the TAP report, right? I didn't realize before that the number is optional.

In `<testsuite errors="0" failures="0" name="weston.alpha-blending" skipped="0" tests="2" time="0.9397590160369873">`, where does the `weston.` part come from? Meson project name? To differentiate from/between sub-projects?

Btw. funnily enough, Gitlab's documenation in https://gitlab.freedesktop.org/help/ci/unit_test_reports.md points to https://www.ibm.com/support/knowledgecenter/en/SSQ2R2_14.1.0/com.ibm.rsar.analysis.codereview.cobol.doc/topics/cac_useresults_junit.html as the Junit specification, which does not say anything about class name.

**Comment by bonzini** [comment]
> And even running time is there.

Yes, however it's just the duration of the whole suite, not of the single testcases.

> In `<testcase name="1 fixture 1 alpha_blend_monotonic/1"/> I don't like the leading 1`

If it works, you can remove it indeed. It's just a matter of taste.

> where does the weston. part come from? Meson project name? To differentiate from/between sub-projects?

Yeah, something like that. I didn't touch that part, it could be improved using `get_pretty_suite` but I didn't want to do any other aesthetic changes for 0.57, only adding the missing classname attribute.

**Comment by ppaalanen** [comment]
Much better! This works for me!

**Comment by dcbaker** [comment]
Yes, the "weston" is to make subtests work correctly, if you didn't have that and you had a subproject that also and a suite called "alpha-blending" that would be an error, suite names have to be unique in JUnit.
