### ISSUE TITLE
PDB files shipped with Boost/MSVC releases from sourceforge trigger ERROR when using dependency('boost')

### ISSUE THREAD

**Issue by andrzejc** [mesonbuild/meson#8325]
Binary Boost releaases downloaded from https://sourceforge.net/projects/boost/files/boost-binaries/ include debbuging information in separete .pdb files stored alongside .lib and .dll files in `lib<32|64>-msvc-<version>` directories. 

The error visible in the log looks like this:

`meson.build:13:0: ERROR: Unable to process library extension "pdb" (C:\opt\moonlight-deps\boost_1_75_0\lib32-msvc-14.1\boost_atomic-vc141-mt-gd-x32-1_75.pdb)`

which hints at the following code location:

https://github.com/mesonbuild/meson/blob/2a8d6690f73ec6415c2ee592e856b3b6de7cfb02/mesonbuild/dependencies/boost.py#L155

I think the official binary releases for MSVC should be consumable in the form they are shipped.
Workaround: currently I need to move .pdb files to separate directory, which requires write access to the lib... directory - not always available on CI systems with boost preinstalled.

**Comment by nanthony21** [comment]
I'm running into this same issue.

**Comment by nanthony21** [comment]
Maybe the cleanest solution is to add a case here to exclude certain file suffixes?
https://github.com/mesonbuild/meson/blob/2a8d6690f73ec6415c2ee592e856b3b6de7cfb02/mesonbuild/dependencies/boost.py#L620

Or maybe the `BoostLibraryFile` class should have a static `is_file_valid(fileName: Path) -> bool:` method which is used to ignore unsupported files?

**Comment by insunaa** [comment]
> I have the same issue. What really should happen is Meson should start using the official way of detecting boost libraries, i.e. via CMake. See #8801.

Forgive my ignorance: I use meson specifically so I can avoid the need for CMake. What is the point of Meson if it only calls CMake in the end, anyway?

**Comment by intractabilis** [comment]
> Forgive my ignorance: I use meson specifically so I can avoid the need for CMake. What is the point of Meson if it only calls CMake in the end, anyway?

Not all third-party libraries support Meson. If authors of library X use CMake, Meson must use CMake to know how to find and compile library X with your code.

**Comment by eli-schwartz** [comment]
Meson doesn't "must" any such thing, because as we see it can do this with just python, therefore we have a happy case where it turns out cmake is not needed. ;)

**Comment by intractabilis** [comment]
> Meson doesn't "must" any such thing, because as we see it can do this with just python, therefore we have a happy case where it turns out cmake is not needed. ;)

Reimplementing CMake in Python is a non-starter. Meson must, and it does call CMake behind the scene for other libraries. Regarding boost in particular, the way Meson stubbornly refuses the officially supported way to find boost libraries causes maintenance problems, does have bugs, and will have more bugs in the future.

**Comment by mensinda** [comment]
You are free to try to implement it using CMake and submit a PR. However, be warned that I **did** try implementing this way and it turned out tob be even more buggy and unmaintainable.

On 10 May 2022 06:26:37 CEST, intractabilis ***@***.***> wrote:
>> Meson doesn't "must" any such thing, because as we see it can do this with just python, therefore we have a happy case where it turns out cmake is not needed. ;)
>
>Reimplementing CMake in Python is a non-starter. Meson must, and it does call CMake behind the scene for other libraries. Regarding boost in particular, the way Meson stubbornly refuses the officially supported way to find boost libraries causes maintenance problems, does have bugs, and will have more bugs in the future.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/mesonbuild/meson/issues/8325#issuecomment-1121904143
>You are receiving this because you modified the open/close state.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by intractabilis** [comment]
> However, be warned that I **did** try implementing this way and it turned out tob be even more buggy and unmaintainable.

As far as I remember, the bug was someone was trying to do something very weird that even CMake doesn't support for boost. I am not certain, why Meson should support weird, not officially supported by the boost team scenarios, for the cost of normal, supported scenarios. It goes against the core of Jussi's philosophy, which Jussi reiterated himself many times. Meson should support what boots officially supports, no more, which is currently CMake files. I would encourage you to resurrect your implementation, but reevaluate what you consider a "bug".

**Comment by jpakkane** [comment]
Note that there is a very partial implementation that [builds Boost with Meson as a subproject](https://github.com/jpakkane/core/tree/master/subprojects/miniboost). If someone wants to polish that a bit we could put it in WrapDB and that would simplify things a lot (for some people at least).
