### ISSUE TITLE
Custom install script ignored when using "install : true"

### ISSUE THREAD

**Issue by rezahousseini** [mesonbuild/meson#8328]
When adding a custom installation script as in the following script:

```
project('demo',  'c')

meson.add_install_script('install_demo.sh')
executable('demo', 'main.c', install : true)
```

And calling meson via `meson install -C build` an error message appears about missing permission in `/usr/local/bin`. Removing `install : true` solves this problem.
This indicates to me that adding `install : true` ignores the install script.

**Comment by jpakkane** [comment]
If you install to `/usr/local` then you must have root privileges. Does `sudo meson install -C build` work?

**Comment by eli-schwartz** [comment]
I don't see what this error has to do with install scripts. You tested that the permission error disappeared when you stopped trying to use permissions in `executable()`, but nowhere did you say one word about your install script and whether *it* worked or not.

**Comment by rezahousseini** [comment]
Sorry I was not entirely clear about the problem.
The issue is not the permission but the fact that it will install it in the default location (`/usr/local/bin`) when in fact my install script should perform a copy over a serial line.
So the issue is real and definitively a bug, please reopen.

**Comment by jpakkane** [comment]
In Meson terminology "install" means the copying of files on disk. This is what pretty much all build systems do. If you want to upload binaries to an external piece of hardware, then you should use a run target instead. See this sample project for how to set it up (line 24 and on):

https://github.com/mesonbuild/meson/blob/master/test%20cases/common/52%20run%20target/meson.build

**Comment by eli-schwartz** [comment]
Your install script does whatever you scripted it to do. However, it is run by the same context that performs a program installation to /usr/local, so I strongly advise you not to try scripting an install script for something other than, in fact, installing.

As with other build systems, this is the equivalent of `make install`, and as @jpakkane pointed out, you ***want*** the meson equivalent of `make flash`, which is to define a meson `flash` target that doesn't try to overload the meaning of the built-in `install` concept.

**Comment by rezahousseini** [comment]
You are missing my point. Lets simplify the MWE:

meson.build
```
project('demo',  'c')

meson.add_install_script('install_demo.sh')
executable('demo', 'main.c', install : true)
```

main.c
```
int main() {}
```

install_demo.sh
```
#!/bin/sh
cp demo /bin/
```

when running `meson build` followed by `sudo meson install -C build` I expect my executable to end up in `/bin/demo`. But it ends up in `/usr/local/bin/demo`.
Removing `install : true` in `meson.build` and running `sudo meson install -C build` the executable ends up in `/bin/demo`.
Is my expectation wrong or is this a feature?

**Comment by jpakkane** [comment]
> when running meson build followed by sudo meson install -C build I expect my executable to end up in /bin/demo. But it ends up in /usr/local/bin/demo.

You need to set the install dir then:

```meson
executable('demo', 'main.c', install : true, install_dir: '/bin')
```

**Comment by eli-schwartz** [comment]
>  The issue is not the permission but the fact that it will install it in the default location (`/usr/local/bin`) when in fact my install script should perform a copy over a serial line.



> You are missing my point.
> [...]
> when running `meson build` followed by `sudo meson install -C build` I expect my executable to end up in `/bin/demo`. But it ends up in `/usr/local/bin/demo`.
> Removing `install : true` in `meson.build` and running `sudo meson install -C build` the executable ends up in `/bin/demo`.
> Is my expectation wrong or is this a feature?

If you have a different "point" each time, it's not surprising we missed it.

Since **you yourself noted in the first place** that /usr/local/bin is the default location for `install: true`, it should not be surprising that irrespective of the actions of your `meson.add_install_script()`, one copy gets copied to /usr/local/bin.

If your install script creates a second copy, that is on you. If you don't want meson to install it, but only for your script to do so, then... don't tell meson to install it?

If you expect meson to know your custom install script ***happens*** to also install it, and then refrain from installing it too (in accordance with `install: true`), then... you obviously think we've achieved fully sentient AI here. We have not.

meson will continue to do what you have programmatically stated via the meson.build language for it to do.
