### ISSUE TITLE
Can't extract objects form custom_target()

### ISSUE THREAD

**Issue by elmarco** [mesonbuild/meson#8333]
While trying to add a custom_target() to a plugin in qemu, I reached the following error:

ERROR: Object extraction arguments must be strings or Files.

Here is a small example:

```
project('object extraction', 'c')

ct = custom_target('custom target', output: ['test.c'], command: ['echo', ''], capture: true)
lib1 = shared_library('somelib', ct)
obj1 = lib1.extract_objects(ct)
```

help welcome!

**Comment by dcbaker** [comment]
Yet another place where a CustomTarget doesn't work when used to compile a library.

**Comment by kvtb** [comment]
wow.
just hit the problem and it is fixed just 4 days ago
thank you!
