### ISSUE TITLE
Unable to link simple CUDA project

### ISSUE THREAD

**Issue by andrzejc** [mesonbuild/meson#8337]
**Describe the bug**

Following the advice from https://github.com/mesonbuild/meson/issues/8334, I decided to convert my project to use built-in CUDA support rather than `generator()`. I was using meson testcases (https://github.com/mesonbuild/meson/tree/master/test%20cases/cuda) as an example how to do that.
When building a simple project (see the attachment) using built-in CUDA support, which includes `dependency('threads')`, the linking fails with the following output:

```
  [6/6] Linking target cuda-linking-bug
  FAILED: cuda-linking-bug 
  /usr/local/cuda-10.0/bin/nvcc  -o cuda-linking-bug cuda-linking-bug.p/test_main.cpp.o cuda-linking-bug.p/test_cuda.cu.o libcuda-linking-bug.a -Xlinker=-no-pie -Xlinker=-pthread -Xlinker=/usr/lib/x86_64-linux-gnu/libboost_thread.a -Xlinker=/usr/lib/x86_64-linux-gnu/libboost_system.a -Xlinker=/usr/lib/x86_64-linux-gnu/libboost_filesystem.a -Xlinker=-pthread -lcudart -lcublas -lcurand -Xlinker=-pthread -Xlinker=-pthread -lcudart -lcublas -lcurand -lstdc++ -lstdc++
  /usr/bin/ld: unrecognized option '-pthread'
  /usr/bin/ld: use the --help option for usage information
  collect2: error: ld returned 1 exit status
  ninja: build stopped: subcommand failed.
```

As it seems that meson is trying to pass `-pthread` compiler flag to `ld` invocation via `-Xlinker=` nvcc argument, I tried to workaround it by writing `nvcc-wrapper` script (included in the tarball) which removes this argument (or rather replaces it with `-Xcompiler=-pthread`, this doesn't matter for the linking phase). When using the wrapper the linking still fails:

```
  [6/6] Linking target cuda-linking-bug
  FAILED: cuda-linking-bug 
  /home/aciarkowski/cuda-linking-bug/nvcc-wrapper /usr/local/cuda-10.0/bin/nvcc  -o cuda-linking-bug cuda-linking-bug.p/test_main.cpp.o cuda-linking-bug.p/test_cuda.cu.o libcuda-linking-bug.a -Xlinker=-no-pie -Xlinker=-pthread -Xlinker=/usr/lib/x86_64-linux-gnu/libboost_filesystem.a -Xlinker=/usr/lib/x86_64-linux-gnu/libboost_thread.a -Xlinker=/usr/lib/x86_64-linux-gnu/libboost_system.a -Xlinker=-pthread -lcudart -lcublas -lcurand -Xlinker=-pthread -Xlinker=-pthread -lcudart -lcublas -lcurand -lstdc++ -lstdc++
  /usr/bin/ld: cannot find -lcudart
  /usr/bin/ld: cannot find -lcublas
  /usr/bin/ld: cannot find -lcurand
  /usr/bin/ld: cannot find -lcudart
  /usr/bin/ld: cannot find -lcublas
  /usr/bin/ld: cannot find -lcurand
  /usr/local/cuda-10.0/bin/../targets/x86_64-linux/lib/libcudart_static.a(libcudart_static.a.o): In function 
  `cudart::globalState::loadDriverInternal()':
  (.text+0x23382): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
  collect2: error: ld returned 1 exit status
  ninja: build stopped: subcommand failed.
```

This hints at at least two problems:

- `dependency('cuda')` is disfunctional, it doesn't provide libraries directory to the linker, as seen in the linker invocation command (or maybe it's the responsibility of `nvcc` to do so?);
- `dependency('cuda')` doesn't give me a way of controlling how I want to link `cudart` into the executable, my preferred way is to use the shared .so, which I am able to specify when using the `generator()` approach.

A completly unrelated issue is that in the native file I cannot specify path of the `cuda` binary relative to the location of the native file or project root. 

Another unrelated (or maybe not?) issue is that when setting up the project I'm seeing warning:
```
  WARNING: The default CUDA Toolkit as designated by the '/usr/local/cuda' symbolic link (/usr/local/cuda-11.2) doesn't match the current nvcc version 10.0 and will be ignored.
```
This is caused by the fact that my system has multiple CUDA toolkits installed side-by-side, however for this example I need to use the compiler which supports `arch=compute_30,code=sm_30`, therefore I specify the path of compiler explicitly in the native file and don't add any CUDA toolkit paths to PATH variable, relying on the meson't ability to choose the toolkit based on my version specification in `dependency('cuda', version: '==10.0')` invocation. I don't think this should cause any warnings because ignoring the default CUDA toolkit is exactly what I want.

Please help me understand what I'm doing wrong and how to rework the project to make it linkable. This is just a minimal reproducible example based on much larger project that was until now being successfully built with meson using nvcc as a generator. 

[cuda-linking-bug.tar.gz](https://github.com/mesonbuild/meson/files/5975457/cuda-linking-bug.tar.gz)

**To Reproduce**

```
  cd cuda-linking-bug
  meson setup build --native-file linux.build
  cd build
  ninja
```

**Expected behavior**
I'd like my minimal example to be linked and runnable, just like the project where I use nvcc as a generator is.

**system parameters**
* Native build
* Ubuntu 18.04, `gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0`, Ubuntu packages: cuda-10-0, libboost-all-dev
* Python 3.6.9
* meson 0.56.1
* ninja 1.8.2

**Comment by jpakkane** [comment]
I don't have much experience with Cuda, unfortunately. Maybe someone like @obilaniu can give pointers?

**Comment by obilaniu** [comment]
@andrzejc there does not seem to be a native file (`linux.build` is absent from the tarball). I also have to confess that NVCC is such a kludge-upon-a-kludge by NVIDIA that I prefer manually constructing commands with `generator()`.

Nevertheless, I am able to reproduce on Meson 0.56.2, without a native file and with just one CUDA Toolkit installed, so perhaps those elements were red herrings.

---

```bash
$ wget https://github.com/mesonbuild/meson/files/5975457/cuda-linking-bug.tar.gz
$ tar -xf cuda-linking-bug.tar.gz
$ cd cuda-linking-bug/
# ... (I did some patching of meson.build here to link dynamically to Boost and to CUDA 10.2)
$ PATH=/usr/local/cuda/bin:$PATH meson setup build
$ cd build
$ PATH=/usr/local/cuda/bin:$PATH ninja
[6/6] Linking target cuda-linking-bug
FAILED: cuda-linking-bug 
nvcc  -o cuda-linking-bug cuda-linking-bug.p/test_main.cpp.o cuda-linking-bug.p/test_cuda.cu.o libcuda-linking-bug.a -Xlinker=-no-pie -Xlinker=-pthread -Xlinker=/usr/lib64/libboost_thread.so.1.66.0 -Xlinker=/usr/lib64/libboost_system.so.1.66.0 -Xlinker=/usr/lib64/libboost_filesystem.so.1.66.0 -Xlinker=-pthread -lcudart -lcublas -lcurand -Xlinker=-pthread -Xlinker=-pthread -lcudart -lcublas -lcurand -lstdc++ -lstdc++
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: unrecognized option '-pthread'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: use the --help option for usage information
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

---

The problem seems pretty clear - `dependency('thread')` is being seriously mishandled by `nvcc`. Four times (!), an `-Xlinker` linker flag is supplied to `nvcc`, but `nvcc` hands down this flag to `ld`, which does not accept `-pthread`.

## Failed Link Line, Verbose Mode

```
$ /usr/local/cuda/bin/nvcc  -o cuda-linking-bug cuda-linking-bug.p/test_main.cpp.o cuda-linking-bug.p/test_cuda.cu.o libcuda-linking-bug.a -Xlinker=-no-pie -Xlinker=-pthread -Xlinker=/usr/lib64/libboost_thread.so.1.66.0 -Xlinker=/usr/lib64/libboost_system.so.1.66.0 -Xlinker=/usr/lib64/libboost_filesystem.so.1.66.0 -Xlinker=-pthread -Xlinker=--verbose -lcudart -lcublas -lcurand -Xlinker=-pthread -Xlinker=-pthread -Xlinker=--verbose -lcudart -lcublas -lcurand -lstdc++ -lstdc++ -v
#$ _NVVM_BRANCH_=nvvm
#$ _SPACE_= 
#$ _CUDART_=cudart
#$ _HERE_=/usr/local/cuda/bin
#$ _THERE_=/usr/local/cuda/bin
#$ _TARGET_SIZE_=
#$ _TARGET_DIR_=
#$ _TARGET_DIR_=targets/x86_64-linux
#$ TOP=/usr/local/cuda/bin/..
#$ NVVMIR_LIBRARY_DIR=/usr/local/cuda/bin/../nvvm/libdevice
#$ LD_LIBRARY_PATH=/usr/local/cuda/bin/../lib:~/.local/lib64:~/.local/lib:~/.local/lib64:~/.local/lib
#$ PATH=/usr/local/cuda/bin/../nvvm/bin:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/bin:~/.local/bin:~/.local/bin
#$ INCLUDES="-I/usr/local/cuda/bin/../targets/x86_64-linux/include"  
#$ LIBRARIES=  "-L/usr/local/cuda/bin/../targets/x86_64-linux/lib/stubs" "-L/usr/local/cuda/bin/../targets/x86_64-linux/lib"
#$ CUDAFE_FLAGS=
#$ PTXAS_FLAGS=
#$ nvlink --arch=sm_30 --register-link-binaries="/tmp/tmpxft_00005bc7_00000000-2_cuda-linking-bug_dlink.reg.c"  -m64 -lcudart -lcublas -lcurand -lcudart -lcublas -lcurand -lstdc++ -lstdc++   "-L/usr/local/cuda/bin/../targets/x86_64-linux/lib/stubs" "-L/usr/local/cuda/bin/../targets/x86_64-linux/lib" -cpu-arch=X86_64 "cuda-linking-bug.p/test_main.cpp.o" "cuda-linking-bug.p/test_cuda.cu.o" "libcuda-linking-bug.a"  -o "/tmp/tmpxft_00005bc7_00000000-4_cuda-linking-bug_dlink.sm_30.cubin"
#$ fatbinary -64 -link "--image3=kind=elf,sm=30,file=/tmp/tmpxft_00005bc7_00000000-4_cuda-linking-bug_dlink.sm_30.cubin" --embedded-fatbin="/tmp/tmpxft_00005bc7_00000000-3_cuda-linking-bug_dlink.fatbin.c" 
#$ rm /tmp/tmpxft_00005bc7_00000000-3_cuda-linking-bug_dlink.fatbin
#$ gcc -c -x c++ -DFATBINFILE="\"/tmp/tmpxft_00005bc7_00000000-3_cuda-linking-bug_dlink.fatbin.c\"" -DREGISTERLINKBINARYFILE="\"/tmp/tmpxft_00005bc7_00000000-2_cuda-linking-bug_dlink.reg.c\"" -I. -D__NV_EXTRA_INITIALIZATION= -D__NV_EXTRA_FINALIZATION= -D__CUDA_INCLUDE_COMPILER_INTERNAL_HEADERS__  "-I/usr/local/cuda/bin/../targets/x86_64-linux/include"    -D__CUDACC_VER_MAJOR__=10 -D__CUDACC_VER_MINOR__=2 -D__CUDACC_VER_BUILD__=89 -m64 "/usr/local/cuda/bin/crt/link.stub" -o "/tmp/tmpxft_00005bc7_00000000-5_cuda-linking-bug_dlink.o" 
#$ g++ -m64 -Wl,--start-group "/tmp/tmpxft_00005bc7_00000000-5_cuda-linking-bug_dlink.o" "cuda-linking-bug.p/test_main.cpp.o" "cuda-linking-bug.p/test_cuda.cu.o" "libcuda-linking-bug.a" -Xlinker -no-pie -Xlinker -pthread -Xlinker /usr/lib64/libboost_thread.so.1.66.0 -Xlinker /usr/lib64/libboost_system.so.1.66.0 -Xlinker /usr/lib64/libboost_filesystem.so.1.66.0 -Xlinker -pthread -Xlinker --verbose -Xlinker -pthread -Xlinker -pthread -Xlinker --verbose -lcudart -lcublas -lcurand -lcudart -lcublas -lcurand -lstdc++ -lstdc++   "-L/usr/local/cuda/bin/../targets/x86_64-linux/lib/stubs" "-L/usr/local/cuda/bin/../targets/x86_64-linux/lib"  -lcudadevrt  -lcudart_static  -lrt -lpthread  -ldl  -Wl,--end-group -o "cuda-linking-bug" 
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: unrecognized option '-pthread'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: use the --help option for usage information
collect2: error: ld returned 1 exit status
# --error 0x1 --
```

## Patched Link line, Verbose Mode

We have the following changes:
  - `-Xcompiler=-pthread`
  - `-Xcompiler=-DDUMMY_FLAG`
  - ~`-Xlinker=-no-pie`~

Which make the compile successful:

```
$ /usr/local/cuda/bin/nvcc  -o cuda-linking-bug cuda-linking-bug.p/test_main.cpp.o cuda-linking-bug.p/test_cuda.cu.o libcuda-linking-bug.a -Xcompiler=-pthread -Xlinker=/usr/lib64/libboost_thread.so.1.66.0 -Xlinker=/usr/lib64/libboost_system.so.1.66.0 -Xlinker=/usr/lib64/libboost_filesystem.so.1.66.0 -Xcompiler=-pthread -Xlinker=--verbose -lcudart -lcublas -lcurand -Xcompiler=-pthread -Xcompiler=-pthread -Xlinker=--verbose -lcudart -lcublas -lcurand -lstdc++ -lstdc++ -Xcompiler=-DDUMMY_FLAG -v
#$ _NVVM_BRANCH_=nvvm
#$ _SPACE_= 
#$ _CUDART_=cudart
#$ _HERE_=/usr/local/cuda/bin
#$ _THERE_=/usr/local/cuda/bin
#$ _TARGET_SIZE_=
#$ _TARGET_DIR_=
#$ _TARGET_DIR_=targets/x86_64-linux
#$ TOP=/usr/local/cuda/bin/..
#$ NVVMIR_LIBRARY_DIR=/usr/local/cuda/bin/../nvvm/libdevice
#$ LD_LIBRARY_PATH=/usr/local/cuda/bin/../lib:~/.local/lib64:~/.local/lib:~/.local/lib64:~/.local/lib
#$ PATH=/usr/local/cuda/bin/../nvvm/bin:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/bin:~/.local/bin:~/.local/bin
#$ INCLUDES="-I/usr/local/cuda/bin/../targets/x86_64-linux/include"  
#$ LIBRARIES=  "-L/usr/local/cuda/bin/../targets/x86_64-linux/lib/stubs" "-L/usr/local/cuda/bin/../targets/x86_64-linux/lib"
#$ CUDAFE_FLAGS=
#$ PTXAS_FLAGS=
#$ nvlink --arch=sm_30 --register-link-binaries="/tmp/tmpxft_00005cbd_00000000-2_cuda-linking-bug_dlink.reg.c"  -m64 -lcudart -lcublas -lcurand -lcudart -lcublas -lcurand -lstdc++ -lstdc++   "-L/usr/local/cuda/bin/../targets/x86_64-linux/lib/stubs" "-L/usr/local/cuda/bin/../targets/x86_64-linux/lib" -cpu-arch=X86_64 "cuda-linking-bug.p/test_main.cpp.o" "cuda-linking-bug.p/test_cuda.cu.o" "libcuda-linking-bug.a"  -o "/tmp/tmpxft_00005cbd_00000000-4_cuda-linking-bug_dlink.sm_30.cubin"
#$ fatbinary -64 -link "--image3=kind=elf,sm=30,file=/tmp/tmpxft_00005cbd_00000000-4_cuda-linking-bug_dlink.sm_30.cubin" --embedded-fatbin="/tmp/tmpxft_00005cbd_00000000-3_cuda-linking-bug_dlink.fatbin.c" 
#$ rm /tmp/tmpxft_00005cbd_00000000-3_cuda-linking-bug_dlink.fatbin
#$ gcc -c -x c++ -DFATBINFILE="\"/tmp/tmpxft_00005cbd_00000000-3_cuda-linking-bug_dlink.fatbin.c\"" -DREGISTERLINKBINARYFILE="\"/tmp/tmpxft_00005cbd_00000000-2_cuda-linking-bug_dlink.reg.c\"" -I. -D__NV_EXTRA_INITIALIZATION= -D__NV_EXTRA_FINALIZATION= -D__CUDA_INCLUDE_COMPILER_INTERNAL_HEADERS__  -pthread -pthread -pthread -pthread -DDUMMY_FLAG "-I/usr/local/cuda/bin/../targets/x86_64-linux/include"    -D__CUDACC_VER_MAJOR__=10 -D__CUDACC_VER_MINOR__=2 -D__CUDACC_VER_BUILD__=89 -m64 "/usr/local/cuda/bin/crt/link.stub" -o "/tmp/tmpxft_00005cbd_00000000-5_cuda-linking-bug_dlink.o" 
#$ g++ -pthread -pthread -pthread -pthread -DDUMMY_FLAG -m64 -Wl,--start-group "/tmp/tmpxft_00005cbd_00000000-5_cuda-linking-bug_dlink.o" "cuda-linking-bug.p/test_main.cpp.o" "cuda-linking-bug.p/test_cuda.cu.o" "libcuda-linking-bug.a" -Xlinker /usr/lib64/libboost_thread.so.1.66.0 -Xlinker /usr/lib64/libboost_system.so.1.66.0 -Xlinker /usr/lib64/libboost_filesystem.so.1.66.0 -Xlinker --verbose -Xlinker --verbose -lcudart -lcublas -lcurand -lcudart -lcublas -lcurand -lstdc++ -lstdc++   "-L/usr/local/cuda/bin/../targets/x86_64-linux/lib/stubs" "-L/usr/local/cuda/bin/../targets/x86_64-linux/lib"  -lcudadevrt  -lcudart_static  -lrt -lpthread  -ldl  -Wl,--end-group -o "cuda-linking-bug"
```

# Conclusion

The "useless" `-Xcompiler=-DDUMMY_FLAG` on a link line was added purely to trace what `nvcc` does when compiling and linking. It appears that:

  - `-Xcompiler=-A` arguments to `nvcc` are *unwrapped* and given as `-A` to the host compiler `g++`, which then consumes it, whereas
  - `-Xlinker=-B` arguments to `nvcc` are *passed through* as `-Xlinker=-B` to the host compiler `g++`, which (per its manpage) hands it down to `ld` as `-B`.

Noteworthy is that flags supplied with `-Xcompile` are given both to the compilation of the `_dlink.o` object and the final link proper, whereas `-Xlinker` flags are only suppplied to the invocation for the final link.

The semantics seem clearer now:

- `-Xcompiler` is a flag to pass an argument to the underlying host compiler, here `g++`, *whether it is _compiling_ or _linking_*.
- `-Xlinker` is a flag to pass an argument to the underlying host compiler's host linker, here `ld`, and because `g++` .supports `-Xlinker` flags with the same syntax, `nvcc` gives them unchanged to `g++`.

---

That being so, I suspect that for Meson, the `-Xlinker` flag is of relatively little use. Meson prefers to use the host compiler for linking rather than interfacing with `ld` directly, so control over the underlying link with `g++` should be exercised almost exclusively with  `-Xcompiler`.

**Comment by andrzejc** [comment]
> @andrzejc there does not seem to be a native file (`linux.build` is absent from the tarball). 

My bad, it should have been `linux.conf`, sorry.

@obilaniu Thank you for the detailed analysis. I'm slightly confused, because I did very similar changes to yours while investigating this issue and replacing `-Xlinker=-pthread` with  `-Xcompiler=-pthread` didn't seem to help - I was still having issues related to ld not being able to find `-lcublas`, `-lcurand`. I'll repeat your steps to see how this works on my machine.

**Comment by obilaniu** [comment]
@andrzejc Do I understand right that my PR in the other thread closed this issue for you?

**Comment by andrzejc** [comment]
> @andrzejc Do I understand right that my PR in the other thread closed this issue for you?

Yes, and as I see it's merged, I'm closing this issue. Thank you again!
