### ISSUE TITLE
unable to evaluate meson version

### ISSUE THREAD

**Issue by asartori86** [mesonbuild/meson#8341]
**Describe the bug**
What's wrong with this statement? (meson-0.56.2)

```
    if(meson.version() >= '0.47')
        ....
```
I get this error message 
```
examples/env-ctmrg/meson.build:30:13: ERROR: Values of different types (MesonVersionString, str) cannot be compared using >=.
```

**To Reproduce**
```
project('foo','c')

if (meson.version() >= '0.47')
  message('bar')
endif
```
**Expected behavior**
It should evaluate to True or False

**system parameters**
```
$ meson --version
0.56.2
```

**Comment by jpakkane** [comment]
Strings can not be compared directly. You need to use the `version_compare` method instead: https://mesonbuild.com/Reference-manual.html#string-object. So something like this

```meson
if meson.version().version_compare('>=0.47')
``´

**Comment by eli-schwartz** [comment]
As a general rule of thumb, you won't be able to do this in other programming languages either. String greater/less than comparisons are different from version numbers which are different from floats.
