### ISSUE TITLE
Wheels For Meson

### ISSUE THREAD

**Issue by naveen521kk** [mesonbuild/meson#8349]
I would like to have wheels for meson published to PyPI.
Creating it should be as simple as
```sh
python setup.py bdist_wheel
```
Wheels are pre-build, which means pip simply copies files, and those are faster than, pip creating a new virtual environment(`pyproject.toml`), install `setuptools` and `wheel` in that venv, and then using setuptools to build meson, and finally create a wheel, cache it and then copy files.

Also, it simply handles console scripts on Windows also.

**Comment by eli-schwartz** [comment]
I'm not sure I understand your second point.... The console scripts should be handled exactly the same regardless of whether pip downloads a wheel or builds one.

**Comment by naveen521kk** [comment]
yeah, that's what I meant, and there should be no problem in publishing a wheel.

Btw, there is a slight difference, only on windows, when pip downloads a wheel and when it download's a tar archive, and it seems offtopic to explain it here.

**Comment by jpakkane** [comment]
This is more of a Python issue. There are people working on it: https://pypi.org/project/mesonpep517/

**Comment by eli-schwartz** [comment]
mesonpep517 helps users use meson.build to publish their projects as wheels.

This ticket is about uploading meson releases to https://pypi.org/project/meson/#files as a wheel.

(I'm still not sure what the functional difference is supposed to be though... I agree that wheels would be slightly *faster* to install.)

**Comment by naveen521kk** [comment]
@jpakkane I only meant to publish wheels for Meson itself and not anything else. It is only that you or anyone who releases should run the command
```sh
python setup.py bdist_wheel sdist
```
rather than just creating source archives and publish them to PyPI also.

@eli-schwartz Another thing, I noticed was the test suite being included in source archives. In wheels, they won't be there, so there would be some reduce in size of things downloaded.

**Comment by tristan957** [comment]
mesonpep517 has a *lot* of rough edges. Would be interesting to see it folded into Meson somehow if Python support improves.

**Comment by naveen521kk** [comment]
This ticket isn't about `mesonpep517`. This ticket is for uploading wheels while releasing meson itself, https://pypi.org/project/meson/#files

**Comment by tristan957** [comment]
Apologies about the miscommunication on my end.

**Comment by naveen521kk** [comment]
@jpakkane you could have published wheels also in the release 30 minutes back.

**Comment by eli-schwartz** [comment]
As far as I can tell this has not been implemented yet. What am I missing? Why did you close the ticket?

**Comment by naveen521kk** [comment]
I was looking over the old issues I have opened, and I was in the assumption(as this is simple) that this was fixed but this issue wasn't closed. I could this isn't implemented yet, so reopening.

**Comment by rth** [comment]
Having wheels at https://pypi.org/project/meson/#files would certainly be nice. The easiest way to build  wheels for most platforms is probably using https://github.com/pypa/cibuildwheel in CI.

**Comment by eli-schwartz** [comment]
After discussion and reminders from me in IRC:

All releases uploaded since October, i.e. since 0.60.0rc1 and backported to 0.59.3, now come with wheels, and this is part of the release process going forward. Thank you for the report, and for your persistence.

**Comment by naveen521kk** [comment]
Thanks :)
