### ISSUE TITLE
Regression: AssertionError: build.b_vscrt

### ISSUE THREAD

**Issue by Neumann-A** [mesonbuild/meson#8351]
```
Traceback (most recent call last):
  File "E:\vcpkg_cache\downloads\tools\meson\meson-5d651e76b5b6dba5dd03ffec609719b02d703bb7\mesonbuild\mesonmain.py", line 132, in run
    return options.run_func(options)
  File "E:\vcpkg_cache\downloads\tools\meson\meson-5d651e76b5b6dba5dd03ffec609719b02d703bb7\mesonbuild\msetup.py", line 275, in run
    app.generate()
  File "E:\vcpkg_cache\downloads\tools\meson\meson-5d651e76b5b6dba5dd03ffec609719b02d703bb7\mesonbuild\msetup.py", line 176, in generate
    env = environment.Environment(self.source_dir, self.build_dir, self.options)
  File "E:\vcpkg_cache\downloads\tools\meson\meson-5d651e76b5b6dba5dd03ffec609719b02d703bb7\mesonbuild\environment.py", line 643, in __init__
    self._load_machine_file_options(config, properties.build, MachineChoice.BUILD)
  File "E:\vcpkg_cache\downloads\tools\meson\meson-5d651e76b5b6dba5dd03ffec609719b02d703bb7\mesonbuild\environment.py", line 772, in _load_machine_file_options
    key = OptionKey.from_string(k).evolve(subproject=subproject, machine=machine)
  File "E:\vcpkg_cache\downloads\tools\meson\meson-5d651e76b5b6dba5dd03ffec609719b02d703bb7\mesonbuild\mesonlib\universal.py", line 2061, in evolve
    return OptionKey(
  File "E:\vcpkg_cache\downloads\tools\meson\meson-5d651e76b5b6dba5dd03ffec609719b02d703bb7\mesonbuild\mesonlib\universal.py", line 1959, in __init__
    _type = _classify_argument(self)
  File "E:\vcpkg_cache\downloads\tools\meson\meson-5d651e76b5b6dba5dd03ffec609719b02d703bb7\mesonbuild\mesonlib\universal.py", line 1913, in _classify_argument
    assert key.machine is MachineChoice.HOST, str(key)
AssertionError: build.b_vscrt
```
Used native files:
[meson-nativ-x64-windows.log](https://github.com/mesonbuild/meson/files/5982364/meson-nativ-x64-windows.log)
[meson-nativ-x64-windows-debug.log](https://github.com/mesonbuild/meson/files/5982365/meson-nativ-x64-windows-debug.log)

Meson command (glib 2.66.4 build ):
`E:/vcpkg_cache/downloads/tools/python/python-3.9.0-x64/python.exe E:/vcpkg_cache/downloads/tools/meson/meson-5d651e76b5b6dba5dd03ffec609719b02d703bb7/meson.py -Dbuild_tests=false -Dinstalled_tests=false -Dselinux=disabled -Diconv=external -Dinternal_pcre=false --buildtype plain --backend ninja --wrap-mode nodownload --native E:/vcpkg_folders/master/buildtrees/glib/meson-nativ-x64-windows.log --default-library shared --libdir lib --native E:/vcpkg_folders/master/buildtrees/glib/meson-nativ-x64-windows-debug.log -Ddebug=true --prefix E:/vcpkg_folders/master/packages/glib_x64-windows/debug --includedir ../include -Dcmake_prefix_path=['E:/vcpkg_folders/master/installed/x64-windows/debug','E:/vcpkg_folders/master/installed/x64-windows','E:/vcpkg_folders/master/installed/x64-windows/share'] E:/vcpkg_folders/master/buildtrees/glib/src/glib-2-b84205c786.clean`

known working git commit: f5871f434a5b768ad9fcafa797a6db0286421842 (used by vcpkg)

**Comment by jpakkane** [comment]
Bisect says that the broken commit is one of these two:

30ec7612c87676e541c924995feb476bf4254eab
615686fd6dc39c517952c0f9f5fb208e913d8887

One of those fails with an unrelated issue so had to be skipped.

**Comment by dcbaker** [comment]
I'm guessing it's the second one, I've cleared my schedule today to get all of these regressions I introduced cleared up.

**Comment by xclaesse** [comment]
@Neumann-A We are trying to catch those regressions earlier by doing RC releases, we would appreciate if more people could test future Meson releases in advance to avoid this kind of issue. If you wish to help us, please follow @mesonbuild on twitter to be notified about RC releases, test your projects, and report issues before final release. Thanks.

**Comment by dcbaker** [comment]
This is kinda an odd issue, because we did allow this, but it's always been completely ignored, as builtin options are not allowed per-machine. That's actually kinda silly, since there's pretty good reason you might want per-machine builtins (like you don't want to LTO your code generators.

**Comment by Neumann-A** [comment]
@xclaesse: I don't have a single meson project. If you want to test your releases consider doing a `vcpkg install` with every meson based port in vcpkg or even have a port-overlay for even more meson based projects. 
Furthermore https://github.com/microsoft/vcpkg/pull/13100 switches the gtk stack to meson so it should have some decent amount of coverage. 
The only two things which need to be changed is: update: https://github.com/microsoft/vcpkg/blob/0ebdff50fc07d797a6b06a39cd8c6c79f26c360f/scripts/cmake/vcpkg_find_acquire_program.cmake#L254-L266 to whatever git commit you want to test 
and change https://github.com/microsoft/vcpkg/blob/0ebdff50fc07d797a6b06a39cd8c6c79f26c360f/ports/tool-meson/CONTROL#L2 to whatever string you want to have there (mainly needed to trick the hashing, so it only needs to be changed.)

**Comment by Neumann-A** [comment]
> This is kinda an odd issue, because we did allow this, but it's always been completely ignored, as builtin options are not allowed per-machine. That's actually kinda silly, since there's pretty good reason you might want per-machine builtins (like you don't want to LTO your code generators.

@dcbaker: So what is the intended way to pass `b_vscrt` via cross/native file?

**Comment by dcbaker** [comment]
You can set it in your cross or native file, but ATM we only accept a single `b_vscrt` and apply it to both the host and build machine. I think that's a strange limitation, and we should fix it though.

**Comment by Neumann-A** [comment]
@xclaesse about https://github.com/mesonbuild/meson/issues/8351#issuecomment-780069744. You could also open up a PR to vcpkg updating meson to an RC for CI coverage. vcpkg maintainers will probably not complain if meson maintainers update meson in vcpkg itself.

**Comment by eli-schwartz** [comment]
@Neumann-A Can we follow up on vcpkg testing at #8379
