### ISSUE TITLE
Validation fails when overriding default_option `c_std`

### ISSUE THREAD

**Issue by archi** [mesonbuild/meson#8360]
**Describe the bug**

Hi, when bumping our internal meson git to the latest version, I noticed that meson now enforces the `c_std` set by a project.

The CompCert support I added only claims `c89` and `c99`, which is close enough to the truth (there are some exceptions, see https://compcert.org/compcert-C.html if curious). However, when building the picolibc I now get into trouble because it sets the `c_std` to `gnu99` in the `default_options`. Generally speaking, this is also quite true, but at least for our config I removed all GNU-isms.

So I now end up with this:

> ../src/meson.build:35:0: ERROR: Value "gnu99" (of type "string") for combo option "C language standard to use" is not one of the choices. Possible choices are (as string): "none", "c89", "c99".

And can't override it. I tried `-Dc_std=c99`, but then it just fails at a later point (seems like after running the whole "configure" script):

> ERROR: Validation failed for option c_std: Value "gnu99" (of type "string") for combo option "C language standard to use" is not one of the choices. Possible choices are (as string): "none", "c89", "c99".

Same for the minimal, native example below. I suppose this might be a bug?

OTOH, if I'm doing it wrong I'm happy to be pointed out on how to achieve my goal :)

**To Reproduce**

Consider this simple project, `meson.build` file:
```
project('testproject', 'c',
  version : '0.1',
  default_options : ['warning_level=3', 'c_std=foobar99'])

executable('testproject',
           'hello.c',
           install : true)
```

source in `hello.c` (doesn't matter):

```
#include <stdio.h>
int main (void) { printf("Hello World!\n"); return 0; }
```

Calling only `meson $project_src`, I get the following error:

```
The Meson build system
Version: 0.57.999
Source dir: /local/hdd/meyer/tmp/c_std/project
Build dir: /local/hdd/meyer/tmp/c_std/project/build
Build type: native build
Project name: testproject
Project version: 0.1

../meson.build:1:0: ERROR: Value "foobar99" (of type "string") for combo option "C language standard to use" is not one of the choices. Possible choices are (as string): "none", "c89", "c99", "c11", "c17", "c18", "c2x", "gnu89", "gnu99", "gnu11", "gnu17", "gnu18", "gnu2x".

```

This is expected, as my system GCC (10.2.0, x86_64) doesn't support the non-existent C language standard `foobar99`.

However, when overriding the value by calling ``meson $project_src -Dc_std=c99`, I get more output - but it still fails:

```
The Meson build system
Version: 0.57.999
Source dir: /local/hdd/meyer/tmp/c_std/project
Build dir: /local/hdd/meyer/tmp/c_std/project/build
Build type: native build
Project name: testproject
Project version: 0.1
C compiler for the host machine: cc (gcc 10.2.0 "cc (GCC) 10.2.0")
C linker for the host machine: cc ld.bfd 2.35.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Build targets in project: 1


ERROR: Validation failed for option c_std: Value "foobar99" (of type "string") for combo option "C language standard to use" is not one of the choices. Possible choices are (as string): "none", "c89", "c99", "c11", "c17", "c18", "c2x", "gnu89", "gnu99", "gnu11", "gnu17", "gnu18", "gnu2x".
```

Hence the title, _Validation fails when overriding default_option `c_std`_.

**Expected behavior**
The hello world project is build.

**system parameters**
* native build (only originally stumbled on cross build)
* Manjaro (kernel 5.10.2-2-MANJARO)
* Python 3.9.1
* Meson 0.57.999 (commit 11045754)
* Ninja 1.10.2

**Comment by dcbaker** [comment]
This is one of those, danged whatever you do situations. What happened was that we enforced the c standard options for *some* compilers, but not *all* compilers. We're now enforcing it for all compilers.

The second part though, that setting the default value to something invalid, then overriding it something valid and that not working  is not good, and I can replicate that.

**Comment by archi** [comment]
Aah, the first part was just flavour to point out the use case - I think the better enforcement for all compilers makes sense. Thanks for looking into the regression :)
