### ISSUE TITLE
meson can't be rerun to detect changes in the system build environment

### ISSUE THREAD

**Issue by csoriano89** [mesonbuild/meson#838]
At least with DLang it's not possible to run meson build twice, since it says "already configured, changes will be detected automatically".
Of course the change of computer where the software is built is not detected :)

**Comment by ignatenkobrain** [comment]
why don't you do just `ninja-build`?

**Comment by csoriano89** [comment]
I do, and it fails because it was configured already with different parameters.

**Comment by ignatenkobrain** [comment]
@csoriano89 I think you can just wipe build directory and rerun meson.

**Comment by csoriano89** [comment]
Yes, that's not the point of the bug report though.

**Comment by nirbheek** [comment]
This is not specific to the D support. You cannot run `meson` on a build directory more than once. As for why this was added, I'll let @jpakkane explain that since I'm not privy to all the details.

**Comment by jpakkane** [comment]
The point is reliability and ease of use. I had to help many people with CMake and for some reason they kept rerunning CMake on their build dirs over and over after doing changes. When I told them that it is not necessary they usually replied with "maybe, but I don't trust it". Meson's usability goal was to never need this. When you type `ninja` you will always either get a fully up to date build or abort with an error.

The downside is that there are some pathological cases, such as switching computers, that become problematic. But if you change computers a _lot_ of things probably change too, such as the compiler version used. It is highly recommended that you do no try to share a build dir between two machines. If will only work by accident and is _not_ supported.

**Comment by TingPing** [comment]
> such as the compiler version used

To be fair that can change any update, so ideally could be handled.

**Comment by csoriano89** [comment]
Yeah exactly, I must be unlucky, both things happened to me in my first tries of meson, switching computers and switching compilers, so that's why it is necessary to run meson build. Of course meson can just do nothing in case nothing changed if it can detect that.

Although I understand the reasoning behind it, I'm afraid as long as those cause issues vs a harmless command line option that is forbidden for just to avoid the user doing extra work, there is not real option but to require running "meson build" always, rather than just being optional or, the current state, not allowed.

**Comment by nirbheek** [comment]
We now have `ninja reconfigure` which does this. Closing.
