### ISSUE TITLE
Undefined references to UBSan when linking CUDA project with `b_sanitize=undefined`

### ISSUE THREAD

**Issue by andrzejc** [mesonbuild/meson#8394]
**Describe the bug**
Hi, as a follow-up to https://github.com/mesonbuild/meson/issues/8337, I've noticed that when I enable UBSan for my project (`-Db_sanitize=undefined`), nvcc is fails to link the executables, producing lots of error about undefined references from libubsan. My current workaround is to add the followin snippet to meson.build:

```
  if get_option('b_sanitize') == 'undefined'
    add_project_link_arguments('-lubsan', language: 'cuda')
  endif
```

This isn't sth that is a blocker for me or very problematic because the workaround is very simple, just giving you a heads up; @obilaniu would you care to take a look? 

**To Reproduce**
Use the same project that was included with https://github.com/mesonbuild/meson/issues/8337, just add `-Db_sanitize=undefined` to `meson setup` invocation.

**Expected behavior**
Project linking without errors.

**system parameters**
* Native build
* Ubuntu 18.04, gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, Ubuntu packages: cuda-10-0, libboost-all-dev
* Python 3.6.9
* meson 0.56.1
* ninja 1.8.2

**Comment by obilaniu** [comment]
@andrzejc I was able to reproduce. The fix is so simple (+4 lines of code at `mesonbuild/compilers/cuda.py:628`) that you might be able to apply it immediately manually, test it and report back here on results. For me it works well.

**Comment by andrzejc** [comment]
> @andrzejc I was able to reproduce. The fix is so simple (+4 lines of code at `mesonbuild/compilers/cuda.py:628`) that you might be able to apply it immediately manually, test it and report back here on results. For me it works well.

Thank you I'll try testing it on Monday, if time allows
