### ISSUE TITLE
run_target() waits for background processes to finish since 0.57

### ISSUE THREAD

**Issue by Garzet** [mesonbuild/meson#8407]
Consider a `run_target` that starts a server as a background process and another target that starts a client. Before 0.57, I was able to do `ninja server && ninja client` to build and run my code.

Running `ninja tgt` on the minimal example below returns immediately with 0.56, but blocks for 10secs on 0.57:
```meson
project('testproj')
run_target('tgt', command: [find_program('test.sh')]) # test.sh below
```
```shell
#!/bin/sh
sleep 10 &
```

**Comment by xclaesse** [comment]
Hmmm, that behavior was not documented and it's surprising. IMHO that was a bug that got fixed.

**Comment by xclaesse** [comment]
Actually gave it a try and it does block until the commands returns with 0.56. The old code was waiting on the subprocess, see https://github.com/mesonbuild/meson/blob/0.56/mesonbuild/scripts/commandrunner.py#L75.

**Comment by xclaesse** [comment]
ohh, no sorry, finally understood what you mean with `sleep 10 &`, I was testing with a python script that sleep() instead.

I have no idea why that behaved like that with 0.56, that seems even undocumented in the python subprocess.wait() API... How does that work?

IMHO you were relying on undefined and super weird behavior, you should rather use `ninja server& ninja client`.

**Comment by Garzet** [comment]
Ok, thx... I thought it might not be a bug, but just me relying on something I really should not.
