### ISSUE TITLE
`meson test` regression fail in v0.57.1

### ISSUE THREAD

**Issue by williamfgc** [mesonbuild/meson#8408]
**Describe the bug**
This is a regression failure. `meson test` v0.57.1 from pip3 can't find test target, while `ninja test` works fine.
meson v0.53.2 on Ubuntu 20.04 works fine. Using flat hierarchy (executables in `meson-out`), but `meson test` looks for regular hierarchy.

```
$ meson test
meson test
ninja: Entering directory `/home/wgodoy/workspace/ncio/build'
ninja: error: unknown target 'testing/functional/bindings/CXX17/functionaltest-cxx17-DataDescriptor'
Could not rebuild /home/wgodoy/workspace/ncio/build
```

**To Reproduce**
Just the typical steps with the main branch of my project (I'm using a flat layout) see [meson.build](https://github.com/ORNL/ncio/blob/main/meson.build)

```
$ git clone https://github.com/ORNL/ncio.git
$ mkdir ncio-build
$ cd ncio-build
$ meson ../ncio
$ ninja
$ meson test
```

**Expected behavior**
`meson test` in v0.57.1 should run the tests, just like previous versions (v0.53.2 Ubuntu 20.04)

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? Plain native build
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) Ubuntu 20.04
* what Python version are you using? Python 3.8.5
* what `meson --version`  v0.57.1
* what `ninja --version` if it's a Ninja build  v1.10.0

**Comment by bonzini** [comment]
Seems like a problem with introspection data and `layout=flat`. The `filename` in `meson introspect --targets` is `/home/pbonzini/ncio/build/testing/ci/unit/unittest-helper-ncioHelperString`but the executable is actually in `/home/pbonzini/ncio/build/meson-out/unittest-helper-ncioHelperString`.

**Comment by bonzini** [comment]
Working on it.
