### ISSUE TITLE
How does DESTDIR work in relation to `--prefix`?

### ISSUE THREAD

**Issue by smac89** [mesonbuild/meson#8409]
**Describe the bug**
[Reading](https://mesonbuild.com/Commands.html#examples5) the [documentations](https://mesonbuild.com/Installing.html#destdir-support) seems to suggest that configuring a project with `--prefix` is an alternative to setting the `DESTDIR` environment variable during `install`.

I am having a hard time replicating this behavior.

In my case, I notice that meson simply ignores the value of `--prefix` and seems to depend solely on `DESTDIR`. In the absence of `DESTDIR`, `meson install` attempts to gain root privileges (similar to https://github.com/mesonbuild/meson/issues/7345) even though the values configured with `--prefix` do not belong to the root user.

**To Reproduce**
This is my minimal `meson.build` file:

```meson
# install icons
install_data('data/icons/desktop/scalable/xdg-internet-shortcut.svg',
    install_dir: join_paths(get_option('datadir'), '/icons/hicolor/scalable/apps'),
    install_mode: 'rw-r--r--')

foreach size : [16, 24, 32, 48, 64, 128, 256]
  install_data('data/icons/mimeicons/@0@/application-x-internet-shortcut.png'.format(size),
      install_dir: join_paths(get_option('datadir'), '/icons/hicolor/@0@x@0@/mimetypes'.format(size)),
      install_mode: 'rw-r--r--')
endforeach
```

These are the commands I use to install:

```sh
meson --buildtype=plain ./build --prefix ~/ --datadir .local/share
meson configure ./build
meson install -C ./build
```

**Expected behavior**
`meson install` should be able to install the files to `~/` without requesting root privileges. However, only when I use `DESTDIR=$HOME meson install -C ./build`, does meson not request root privilege, but even this option does not respect the `--datadir` option I set in the `configure` step.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? **Plain**
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.): **ArcoLinux**
* what Python version are you using e.g. 3.8.0: **3.9.1**
* what `meson --version`: **0.57.1**
* what `ninja --version` if it's a Ninja build

**Comment by smac89** [comment]
After posting, I immediately realized a mistake with `join_path`.

The correct build instructions are:

```meson
# install icons
install_data('data/icons/desktop/scalable/xdg-internet-shortcut.svg',
    install_dir: join_paths(get_option('datadir'), 'icons/hicolor/scalable/apps'),
    install_mode: 'rw-r--r--')

foreach size : [16, 24, 32, 48, 64, 128, 256]
  install_data('data/icons/mimeicons/@0@/application-x-internet-shortcut.png'.format(size),
      install_dir: join_paths(get_option('datadir'), 'icons/hicolor/@0@x@0@/mimetypes'.format(size)),
      install_mode: 'rw-r--r--')
endforeach
```

The arguments I used with `join_path` will create an absolute path starting from the root, which explains why meson is always trying to gain root privileges when installing.

Also it now makes sense to me why it was only when I changed `DESTDIR` that the installation path changed.

**Comment by eli-schwartz** [comment]
So this is solved then?

Also consider using `meson install --dry-run` to debug what it's actually doing without getting root prompts.

**Comment by smac89** [comment]
Yep solved
