### ISSUE TITLE
'ninja pot' is not found.

### ISSUE THREAD

**Issue by csoriano89** [mesonbuild/meson#842]
Reading https://github.com/mesonbuild/meson/wiki/Localisation it says:
> If you are using the Ninja backend, this is how you would invoke the rebuild.
> 
> ninja pot

However, when using   i18n.gettext('test', languages: langs) the generated build rule in build.ninja is named test-pot. So what works is
`ninja test-pot`.

Either the wiki is wrong or the code to generate the build rule is wrong.

**Comment by csoriano89** [comment]
also a small nitpick in the wiki, should use i18n.gettext instead of bare gettext since the 
`i18n = import('i18n') `
is needed afaics.

**Comment by jpakkane** [comment]
That page was written before the i18n modularisation and had not been updated. Fixed now, thanks.

**Comment by csoriano89** [comment]
thanks a lot
