### ISSUE TITLE
Adding a subproject with library() makes meson Error

### ISSUE THREAD

**Issue by viric** [mesonbuild/meson#8421]
**Describe the bug**
If you have a configured build directory for a project, and you add a subproject with a library inside it, meson fails with this error:
    ERROR: Tried to get unknown builtin option newproject:default_library

The only solution is to delete the build directory and start over.

**To Reproduce**
Configure a build directory and add subproject with a library() or get_option('default_library'). @xclaesse is aware, from an irc conversation, saying it was a regression from 0.56

**Expected behavior**
Reconfigure fine.

**system parameters**
* native build
* windows 10 64-bit, linux-x86_64
* python 3.8.5
* meson 0.57.0 and 0.57.1
* ninja 1.10.2

**Comment by dcbaker** [comment]
I have a pretty good idea what's going wrong.

**Comment by dcbaker** [comment]
I have a test, and I know what's wrong. I'm just not sure what the best way to fix it is.

**Comment by dcbaker** [comment]
I think I have a fix too
