### ISSUE TITLE
feature object shoud be treated a boolean

### ISSUE THREAD

**Issue by The-King-of-Toasters** [mesonbuild/meson#8430]
Similar to #8426, features should be treated as booleans in many places:

```meson
option('library', type: 'feature', value: 'auto')
...
conf.set('HAVE_LIBRARY', get_option('library'))

if get_option('library')
	# stuff
endif
```

You can get around this by adding `.enabled()` everywhere.

**Comment by xclaesse** [comment]
But what would be the value auto?

**Comment by The-King-of-Toasters** [comment]
Since auto is the same as setting `required: false`, we could just check if the feature is enabled.

**Comment by xclaesse** [comment]
No you can't, you should define HAVE_LIBRARY only if the lib is found, and in the auto case you don't know.

**Comment by eli-schwartz** [comment]
I agree with @xclaesse, feature options are fundamentally intended to be post-processed, as it were, by `dependency()` or similar in order to find out their "real" value. As such, you should never pass one to a configuration_data (and not `.enabled()` either), but instead use it in a method that attempts to perform some sort of lookup and has a `.found()` method. Then pass `thing.found()` as a boolean.

**Comment by eli-schwartz** [comment]
Actually I think #8426 is of somewhat questionable use too, since you'll generally want to report via a summary, about the features you detected and compiled into the project... not the current value of the command line `-Dfeature=auto` flag.

**Comment by The-King-of-Toasters** [comment]
Yeah that makes sense. So you would declare a dependency and then use use .found() on the object later on?

**Comment by eli-schwartz** [comment]
Right.

**Comment by The-King-of-Toasters** [comment]
Got it. For my own reference this is what I should use:

```meson
option('feat', type: 'feature', value: 'auto')
...
project('My Project', version : '1.0')

dep = dependency('x11', required: get_option('feat'))

if dep.found()
  # do stuff
endif

conf.set('HAVE_DEP', dep.found())

summary({
  'feature': dep
})

```

I took another look at #8426, and I'm not sure it's worth keeping. I remember there was some global UserOption that could be printed, but I can't remember it.

**Comment by eli-schwartz** [comment]
```
summary({
  'feature': dep.found()
})
```

You could also do
```
summary({
  'feature': conf.get('HAVE_DEP')
})
```

I'd recommend

```
summary({
  'feature': dep.found()
}, bool_yn: true)
```

for the pretty colors.

**Comment by xclaesse** [comment]
@eli-schwartz IIRC we already special case dependency object for yes/no, no need to use .found()

**Comment by eli-schwartz** [comment]
Oh hmm...

(I'm using conf.get() though due to needing to detect either openssl or nettle for HAVE_SSL.)

**Comment by eli-schwartz** [comment]
I think we basically all agreed that this should be left as-is...
