### ISSUE TITLE
Problems building gtk4 on windows with 'msi meson'

### ISSUE THREAD

**Issue by matthiasclasen** [mesonbuild/meson#8431]
**Describe the bug**

We've got this bug report that describes a failure to build gtk4 on windows using meson from the msi installer:

https://gitlab.gnome.org/GNOME/gtk/-/issues/3701

**To Reproduce**

- git clone https://gitlab.gnome.org/GNOME/gtk.git
- cd gtk
- meson setup . ..\gtk-build

```
Traceback (most recent call last):
  File "mesonbuild\mesonmain.py", line 132, in run
  File "mesonbuild\mesonmain.py", line 100, in run_runpython_command
  File "runpy.py", line 268, in run_path
  File "runpy.py", line 97, in _run_module_code
  File "runpy.py", line 87, in _run_code
  File "C:\Users\Aleksandr\gtk\gdk\gen-gdk-gresources-xml.py", line 8, in <module>
    import filecmp
ModuleNotFoundError: No module named 'filecmp'
```

**Expected behavior**
successful build, as with pip installed meson

**Comment by eli-schwartz** [comment]
PyInstaller likes to cut down on the size of a distributed application by stripping out stdlib modules which it heuristically detects are not being used. The script to create the .msi already overrides and forces inclusion for a bunch of modules that those heuristics get wrong for meson itself. https://github.com/mesonbuild/meson/blob/b86ef3f85020eb8ed0e464a7653fa9e57cd527c2/packaging/createmsi.py#L121-L144

Unfortunately that means it's very... suboptimal... for the case where the PyInstaller-installed application intends to additionally ship a full python interpreter capable of running arbitrary external scripts. And meson does try to use its own python interpreter to run .py programs used in a project build.

I think this means the approach to packaging the .msi needs to be re-evaluated. Maybe there's some way to force PyInstaller to just bundle the entire python stdlib? Alternatively, pass a list of every single module in the stdlib to the current --hidden-imports code. Which does seem a bit meh for maintainability...

**Comment by eli-schwartz** [comment]
#8437 would add filecmp "on request" basically, which fixes the problem for now.

**Comment by amezin** [comment]
Shouldn't Gtk use `python.find_installation()` instead of relying on shebangs? I am surprised that Meson handles them on Windows. `find_installation()` with `modules: ['filecmp']` automatically finds other (full) Python installation https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/3243

**Comment by eli-schwartz** [comment]
And the linked PR means find_installation will find the .msi copy of python *first*, detect that it has filecmp available, and prefer it.

The shebang detection and rewriting on meson's side is supposed to make it easier for people to write cross-platform scripts without having to think too much about it, since it works out of the box even on Windows where shebangs don't generally work but meson guarantees that some version of python definitely has to exist.

**Comment by jpakkane** [comment]
Created a new MSI version 0.57.1.1 which should fix this issue.
