### ISSUE TITLE
i18n module only checks for gettext and misses xgettext

### ISSUE THREAD

**Issue by grimmy** [mesonbuild/meson#8436]
**Describe the bug**
We have a configure file in our build that uses `i18n.merge_file`.  In the users log we saw

```
Program gettext found: YES (/usr/bin/gettext)
```

But when Meson reached the `i18n.merge_file` this error was spit out.

```
WARNING: Gettext not found, all translation targets will be ignored.
```

**To Reproduce**

It took some time to figure out, but the user is on Debian stable, but the issue was that they had `gettext-base` installed that contains `/usr/bin/gettext` but `xgettext` that `i18n.merge_file` requires is actually in the `gettext` package.

**Expected behavior**

It would have been awesome if when detecting the gettext binary, meson would check for xgettext as well if `i18n.merge_file` is in use.  If it couldn't find it, it would be much nicer if it would mention the executable it was looking for as I had to dig through the meson source to figure out what it was complaining about as the user already verified that they had `/usr/bin/gettext` installed.

**system parameters**

The user was on Debian stable with meson 0.56.2, but their system isn't relevant here out side of the `gettext-base` was installed but `gettext` was not installed scenario.

**Comment by eli-schwartz** [comment]
meson only ever looks for the xgettext program as a sentinel for "the Gettext project's development tools are installed". The `gettext` program is a runtime program which is generally not used (it is only needed by shellscripts which need a compiled binary to accept arguments for forwarding to the `*gettext` family of C functions).

Personally I think it's rather terrible that it disables these targets anyway... I can understand disabling built .mo files, but disabling desktop targets seems not great...

We do have module options for this these days.

**Comment by inigomartinez** [comment]
It would also be nice if there could an option to throw an error instead of a warning if any of the necessary `gettext` files are missing.

**Comment by eli-schwartz** [comment]
Quite frankly, it shouldn't be an option. Desktop files should not be automatically disabled if the consequences are a totally broken runtime installation. Disabling built .mo files "kind of" makes sense since they could be optional at runtime (maybe you only need English support).

**Comment by inigomartinez** [comment]
> Quite frankly, it shouldn't be an option. Desktop files should not be automatically disabled if the consequences are a totally broken runtime installation. Disabling built .mo files "kind of" makes sense since they could be optional at runtime (maybe you only need English support).

I also agree that without any option it should throw an error to avoid any cases where files are disabled and not installed. The current behavior caused [an issue in ModemManager](https://gitlab.freedesktop.org/mobile-broadband/ModemManager/-/issues/517).

**Comment by eli-schwartz** [comment]
I opened a PR which fixes this in two ways:
- it actually checks for each tool which is actually used, and logs whether it is found. The `WARNING: Gettext not found [...]` is still printed, but immediately beforehand it also mentions the exact tool name it is looking for, so that should presumably be easy to interpret.
- merge_file is actually required to work now, because it's unreasonable to expect it to be able to be disabled.

**Comment by inigomartinez** [comment]
Thanks!
