### ISSUE TITLE
gnome.genmarshal() generates empty files on Windows if Meson is installed from .msi

### ISSUE THREAD

**Issue by amezin** [mesonbuild/meson#8439]
**Describe the bug**

`gnome.genmarshal()` generates empty files on Windows if Meson is installed from `.msi`
If I install Meson using pip and Python from python.org - it works correctly.

Seems that there is another module from Python standard library missing.

Also I don't like that `genmarshal` fails silently.

**To Reproduce**

For example, try to build gdk-pixbuf.
In `X64 Native Tools Command Prompt for VS 2019`:

```
> git clone https://gitlab.gnome.org/GNOME/gdk-pixbuf.git
> cd gdk-pixbuf
> mkdir build
> cd build
> meson
> ninja gdk-pixbuf/gdk-pixbuf-marshal.c
```

Now `build/gdk-pixbuf/gdk-pixbuf-marshal.c` is empty. If I simply run `ninja`, it will end with:

```
[645/1218] Compiling C object gdk-pixbuf/gdk_pixbuf-2.0-0.dll.p/gdk-pixbuf-loader.c.obj
FAILED: gdk-pixbuf/gdk_pixbuf-2.0-0.dll.p/gdk-pixbuf-loader.c.obj
"cl" "-Igdk-pixbuf\gdk_pixbuf-2.0-0.dll.p" "-Igdk-pixbuf" "-I..\gdk-pixbuf" "-I." "-I.." "-Igdk-pixbuf\pixops" "-I..\gdk-pixbuf\pixops" "-Isubprojects\glib" "-I..\subprojects\glib" "-Isubprojects\glib\glib" "-I..\subprojects\glib\glib" "-Isubprojects\proxy-libintl" "-I..\subprojects\proxy-libintl" "-Isubprojects\glib\gobject" "-I..\subprojects\glib\gobject" "-Isubprojects\glib\gmodule" "-I..\subprojects\glib\gmodule" "-Isubprojects\glib\gio" "-I..\subprojects\glib\gio" "/MD" "/nologo" "/showIncludes" "/W2" "/O2" "/Zi" "-D_POSIX_C_SOURCE=200809L" "-D_DEFAULT_SOURCE" "-D_XOPEN_SOURCE=700" "-utf-8" "-DGDK_PIXBUF_RELOCATABLE" "-DHAVE_CONFIG_H=1" "-utf-8" "-DG_LOG_STRUCTURED=1" "-DG_LOG_DOMAIN=\"GdkPixbuf\"" "-DGDK_PIXBUF_COMPILATION" "-DGDK_PIXBUF_PREFIX=\"c:/\"" "-DGDK_PIXBUF_LOCALEDIR=\"c:/share/locale\"" "-DGDK_PIXBUF_LIBDIR=\"c:/lib\"" "-DGDK_PIXBUF_BINARY_VERSION=\"2.10.0\"" "-DGDK_PIXBUF_ENABLE_BACKEND" "-DPIXBUF_LIBDIR=\"c:/lib/gdk-pixbuf-2.0/2.10.0/loaders\"" "-DBUILT_MODULES_DIR=\"C:\\Users\\Aleksandr\\gdk-pixbuf\\build\\gdk-pixbuf\"" "/Fdgdk-pixbuf\gdk_pixbuf-2.0-0.dll.p\gdk-pixbuf-loader.c.pdb" /Fogdk-pixbuf/gdk_pixbuf-2.0-0.dll.p/gdk-pixbuf-loader.c.obj "/c" ../gdk-pixbuf/gdk-pixbuf-loader.c
../gdk-pixbuf/gdk-pixbuf-loader.c(146): error C2065: '_gdk_pixbuf_marshal_VOID__INT_INT': undeclared identifier
../gdk-pixbuf/gdk-pixbuf-loader.c(146): warning C4047: 'function': 'GSignalCMarshaller' differs in levels of indirection from 'int'
../gdk-pixbuf/gdk-pixbuf-loader.c(146): warning C4024: 'g_signal_new': different types for formal and actual parameter 7
../gdk-pixbuf/gdk-pixbuf-loader.c(166): error C2065: '_gdk_pixbuf_marshal_VOID__VOID': undeclared identifier
../gdk-pixbuf/gdk-pixbuf-loader.c(166): warning C4047: 'function': 'GSignalCMarshaller' differs in levels of indirection from 'int'
../gdk-pixbuf/gdk-pixbuf-loader.c(166): warning C4024: 'g_signal_new': different types for formal and actual parameter 7
../gdk-pixbuf/gdk-pixbuf-loader.c(189): error C2065: '_gdk_pixbuf_marshal_VOID__INT_INT_INT_INT': undeclared identifier
../gdk-pixbuf/gdk-pixbuf-loader.c(189): warning C4047: 'function': 'GSignalCMarshaller' differs in levels of indirection from 'int'
../gdk-pixbuf/gdk-pixbuf-loader.c(189): warning C4024: 'g_signal_new': different types for formal and actual parameter 7
../gdk-pixbuf/gdk-pixbuf-loader.c(211): error C2065: '_gdk_pixbuf_marshal_VOID__VOID': undeclared identifier
../gdk-pixbuf/gdk-pixbuf-loader.c(211): warning C4047: 'function': 'GSignalCMarshaller' differs in levels of indirection from 'int'
../gdk-pixbuf/gdk-pixbuf-loader.c(211): warning C4024: 'g_signal_new': different types for formal and actual parameter 7
```

**Expected behavior**
`build/gdk-pixbuf/gdk-pixbuf-marshal.c` should contain code.

**system parameters**
* plain native build
* Windows 10
* Python - from .msi installer
* meson 0.57.1

**Comment by eli-schwartz** [comment]
> ```
> > meson
> > ninja gdk-pixbuf/gdk-pixbuf-marshal.c
> ```ninja gdk-pixbuf/gdk-pixbuf-marshal.c

How about `ninja -v gdk-pixbuf/gdk-pixbuf-marshal.c` and check the command being run to see what that program is trying to do?

**Comment by amezin** [comment]
```
>ninja -v gdk-pixbuf/gdk-pixbuf-marshal.c
[1/1] "C:\Program Files\Meson\meson.exe" "runpython" "C:/Users/Aleksandr/gdk-pixbuf/build/subprojects/glib/gobject/glib-genmarshal" "--prefix" "_gdk_pixbuf_marshal" "--output" "gdk-pixbuf/gdk-pixbuf-marshal.c" "--body" "../gdk-pixbuf/gdk-pixbuf-marshal.list" "--include-header" "gdk-pixbuf-marshal.h"
INFO: Reading ../gdk-pixbuf/gdk-pixbuf-marshal.list...

```

no `subcommand failed` from ninja

`build/subprojects/glib/gobject/glib-genmarshal` is https://gitlab.gnome.org/GNOME/glib/-/blob/master/gobject/glib-genmarshal.in

**Comment by eli-schwartz** [comment]
So, let's follow that logic to the inevitable conclusion:

You assert that "there is another module from Python standard library missing", which import in that file do you think is the missing one? sys, os, re, or argparse?

(This is a trick question.)

I would venture to say something else is the problem there. The first thing I'd recommend doing is running that command while passing the --verbose command-line option to it. If that doesn't help you narrow down the problem, try inserting strategic print() statements into the program.

...

I don't really see how meson could be at fault for this command producing the wrong output. And even if it was a missing module and thus meson's fault, a missing import would not be silent, and would cause the script to fatally error.

**Comment by amezin** [comment]
This happens only when Meson is installed from .msi package, that's why I reported the issue here.

Yes, it seems to be a bug in `glib-genmarshal`: the output stream, opened by argparse's `FileType` is never closed/flushed

**Comment by eli-schwartz** [comment]
> This happens only when Meson is installed from .msi package, that's why I reported the issue here.

Sure, but I just really wanted to know what it was fundamentally doing different. :p It should not be a simple matter of "embedded python missing modules"...

> Yes, it seems to be a bug in `glib-genmarshal`: the output stream, opened by argparse's `FileType` is never closed/flushed

Fascinating. I assume if you re-run the same command using an existing python instead of `"C:\Program Files\Meson\meson.exe" "runpython"`, it works again?

**Comment by eli-schwartz** [comment]
Interesting: https://bugs.python.org/issue13824

**Comment by amezin** [comment]
Yes, only happens with `meson runpython`, and only when installed from .msi package.

And that script is written ~3 years ago. At least relevant parts of it were never touched since then https://gitlab.gnome.org/GNOME/glib/-/blame/master/gobject/glib-genmarshal.in

**Comment by amezin** [comment]
Similar issue with libepoxy: https://github.com/anholt/libepoxy/issues/242 And again, it's only with meson .msi. With python installer from https://www.python.org/ and meson from pip, files get written completely even w/o being closed explicitly.

**Comment by eli-schwartz** [comment]
I really do wonder why this matters here, though :/ is there something that ordinary python.exe exiting does, which `meson runpython` does not?

Internally, it's just the runpy module, which is returned into the main function, and thereafter sys.exit is called.

And the interpreter itself should be a pretty simple python.exe from the official python redistributable...
