### ISSUE TITLE
Temporary directory handling in meson 0.57.1 for MSYS2 on MS Windows is unsafe

### ISSUE THREAD

**Issue by LigH-de** [mesonbuild/meson#8447]
**Describe the bug**
Meson 0.57.1 creates a temporary directory to compile configuration test builds (e.g. in harfbuzz compiled by the media-autobuild suite) but fails to clean up the content in time, possibly because a file monitoring process in Windows locks the generated output.exe for a little while before allowing to delete it. I suspect "Search Everything" or "Tortoise Git" in my case.

During the configuration step of building harfbuzz, a call to `_rmtree_unsafe` in Python 3.8 returns that the directory is not empty after an attempt to remove it (Windows file system error 145). Following attempts to generate new output.exe files fails because access is denied (Windows file system error 5).

**To Reproduce**
Unfortunately, I am not able to create a minimal example. I am no developer. I can only provide log files gathered by the media-autobuild suite.
[logs.zip](https://github.com/mesonbuild/meson/files/6067884/logs.zip)
See path `harfbuzz-git/build-32bit` inside.

**Expected behavior**
Meson should either use a function which waits for the successful removal of temporary files/directories before reusing them with the same name, or use new random names for every attempt in a script.

**system parameters**
* meson 0.57.1 for MSYS2/MinGW
* Windows 7 SP1
* Python 3.8.8-2 for MSYS2/MinGW

**Comment by lazka** [comment]
```

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/MABS/msys64/mingw32/lib/python3.8/site-packages/mesonbuild/mesonlib/universal.py", line 1564, in __exit__
    super().__exit__(exc, value, tb)
  File "E:/MABS/msys64/mingw32/lib/python3.8/tempfile.py", line 827, in __exit__
    self.cleanup()
  File "E:/MABS/msys64/mingw32/lib/python3.8/site-packages/mesonbuild/mesonlib/universal.py", line 1572, in cleanup
    windows_proof_rmtree(self.name)
  File "E:/MABS/msys64/mingw32/lib/python3.8/site-packages/mesonbuild/mesonlib/universal.py", line 1527, in windows_proof_rmtree
    _make_tree_writable(f)
  File "E:/MABS/msys64/mingw32/lib/python3.8/site-packages/mesonbuild/mesonlib/universal.py", line 1517, in _make_tree_writable
    os.chmod(fpath, os.stat(fpath).st_mode | stat.S_IWRITE | stat.S_IREAD)
PermissionError: [WinError 5] {{Access denied}}: 'E:/MABS/build/harfbuzz-git/build-32bit/meson-private/tmpp1a_c1s1/output.exe'
...
```

Either `_make_tree_writable` needs to be dropped, or moved into the retry loop.

**Comment by LigH-de** [comment]
So, what is missing to implement this suggested solution?

**Comment by grindhold** [comment]
i am stuck on this. is there any workaround?

**Comment by xclaesse** [comment]
Could be already fixed? https://github.com/mesonbuild/meson/pull/8576

**Comment by LigH-de** [comment]
MSYS2 provided meson 0.57.1-2, which works for me.

**Comment by eli-schwartz** [comment]
Reported to have been fixed...
