### ISSUE TITLE
cross compilation pkg-conf and path prefixing

### ISSUE THREAD

**Issue by qwertzui11** [mesonbuild/meson#8448]
**Describe the bug**
I got a sysroot folder (an armv7 host) with some dependencies for pkg-conf to find. Eg `x11.pc`. And I've got another folder with dependencies that are NOT inside the sysroot, eg. `webrtc.pc`. So currently I got the following meson cross file:

```ini
[binaries]
cpp = 'clang++'
ar = 'llvm-ar'
strip = 'llvm-strip'

[built-in options]
cpp_args = [
  '--sysroot', '<absolute>/sysroot',
  '-target', 'arm-linux-gnueabihf',
  ]
cpp_link_args = [
  '--sysroot', '<absolute>/sysroot',
  '-Wl,-rpath=/usr/lib/arm-linux-gnueabihf',
  '-Wl,-rpath=/lib/arm-linux-gnueabihf',
  '-latomic',
  '-target', 'arm-linux-gnueabihf',
  ]

[properties]
# sets PKG_CONFIG_SYSROOT_DIR
sys_root = '<absolute>/sysroot'
# sets PKG_CONFIG_LIBDIR
pkg_config_libdir = [
  '<absolute>/sysroot/usr/share/pkgconfig',
  '<absolute>/sysroot/usr/lib/arm-linux-gnueabihf/pkgconfig',
  '<absolute>/sysroot/usr/lib/pkgconfig',
  '<absolute>/dependencies' # <-- PROBLEM!!!!
  ]

[host_machine]
system = 'linux'
cpu_family = 'arm'
cpu = 'armv7'
endian = 'little'
```

Now the issues is, that pkgconf PREFIXES every path in the `*.pc` files inside `dependencies` with the sysroot defined in `sys_root`.

However the paths defined pc files in the folder `dependencies` MUST not be prefixed. Else the `#include` and linking will fail.

However the prefixing is needed for the pc files found inside the sysroot.

How do I resolve this? Any tips or hints?

**system parameters**
* linux
* `meson --version`: 0.57.1

**Comment by xclaesse** [comment]
That's a limitation of pkg-config and pkgconf that I suggested to fix using PKG_CONFIG_SYSROOT_MAP:
- https://todo.sr.ht/~kaniini/pkgconf/20
- https://gitlab.freedesktop.org/pkg-config/pkg-config/-/merge_requests/7

**Comment by qwertzui11** [comment]
got it! thx! for know I just could rename my `webrtc.pc` file inside the `dependenies` folder to `webrtc-uninstalled.pc` and it should work, correct?

**Comment by qwertzui11** [comment]
renaming the `pc` file did not do the expected effect. while meson is able to find the package, it still gets prefixed.

**Comment by qwertzui11** [comment]
got it, thx for the feedback! Annoyingly the issues are un-commented and unresolved for 6 months. How can I resolve this today?

Backstory: I'm using conan for package management, which creates `.pc` files for meson to find.

**Comment by xclaesse** [comment]
pkg-config project is long dead, I don't think it will ever pick up that feature. You can reach pkgconf devs in `#pkgconf` on freenode. I discussed that issue a while ago but it got lost I think.

**Comment by xclaesse** [comment]
I also tried to implement pkgconfig directly in Meson instead of relying on external tool, but that require more work and I don't have that time atm: https://github.com/mesonbuild/meson/pull/7650.

**Comment by qwertzui11** [comment]
Yeah, looks like it!

Okay, I'm gonna hack a solution by adding softlinks into the sysroot. So the prefix becomes valid. I'm gonna wait for #7650 and refactor afterwards.

No wonder cmake did the `<package>-config.cmake` stuff, combined with three variables on how to interpret these.

Thx for your feedback and time.
