### ISSUE TITLE
How do I include an introspection gir file from a subproject as an include in the main project?

### ISSUE THREAD

**Issue by jtm94** [mesonbuild/meson#8465]
Appologies if this has been asked elsewhere, but I can't find the answer:
We have a dependency that we want to include as a subproject but I can't figure out how to include the generated gir in the main project gnome.generate_gir() definition.

Thanks

**Comment by xclaesse** [comment]
Add the return value of `gnome.generate_gir()` to your subproject's `declare_dependency(..., sources: gir)`.

Yes, it's obscure and probably undocumented trick :(

**Comment by jtm94** [comment]
That's what I thought - I assumed that the dependency object for the subproject is added to the `dependencies:` kwarg for `gnome.generate_gir` in the master project but I am still getting `unresolved type` warnings that I do not get when the dependency is installed as a standalone project.
