### ISSUE TITLE
gnome.generate-gir() - setting include_directories: kwarg to string causes meson to crash

### ISSUE THREAD

**Issue by jtm94** [mesonbuild/meson#8471]
**Describe the bug**
In `gnome.generate-gir()` - setting the `include_directories`: kwarg to a string causes meson to crash with the message:

```
...
File "/home/jay/.local/lib/python3.8/site-packages/mesonbuild/modules/gnome.py", line 837, in generate_gir
    inc_dirs = self._scan_inc_dirs(kwargs)
  File "/home/jay/.local/lib/python3.8/site-packages/mesonbuild/modules/gnome.py", line 585, in _scan_inc_dirs
    if not isinstance(incd.held_object, (str, build.IncludeDirs)):
AttributeError: 'str' object has no attribute 'held_object'
```

**system parameters**
* Native build
* Ubuntu 20.04 LTS
* Python 3.8.5
* meson 0.57.1

**Comment by eli-schwartz** [comment]
It seems this is no longer a problem since the refactoring in commit 34c28dc92cb4f28e32e633297e4b8a737228aae5.

Moreover, since commit 566c2c9a9c98d13f85ccef624e9ac584f64c6a4a we typecheck this directly in the function decorator, which is... a lot simpler and more predictable to do.
