### ISSUE TITLE
Specify ar flags

### ISSUE THREAD

**Issue by circutrider21** [mesonbuild/meson#8483]
Is there a way to pass arguments to the archiver like you can to the linker?

**Comment by jpakkane** [comment]
No. What flags would you need to pass and why?

**Comment by circutrider21** [comment]
I would like to pass --target=melf_i386

**Comment by circutrider21** [comment]
I am writing a kernel
and I need ar to emulate the i386 arch instead of i386-pe

**Comment by jpakkane** [comment]
In that case you are probably cross compiling and you can put something like this in your cross file:

`´`
ar = ['/path/to/your/ar', '--target=melf_i386']
``´

Though the cross-ar might not even need that, but I have no experience with that.

**Comment by circutrider21** [comment]
Thanks, That did the trick!
