### ISSUE TITLE
Changes to project default_options don't take effect during ninja regen

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#849]
Steps to reproduce:

```
project('trivial test', 'c',
  meson_version : '>=0.27.0',
  default_options : 'b_asneeded=true')

sources = 'trivial.c'

exe = executable('trivialprog', sources : sources)
```

```
$ mkdir build
$ meson build
$ ninja -C build
$ vim meson.build
```

Change `b_asneeded` to `false`.

```
$ ninja -C build
```

Still passes `-Wl,--as-needed` while linking.

**Comment by jpakkane** [comment]
This is by design. They are default values, after all. They are only used to set up values that are not yet set. Once Meson is run the first time they value is set. After that they need to be changed with mesonconf.

**Comment by MathieuDuponchelle** [comment]
Would be neat to allow resetting to factory defaults :)
