### ISSUE TITLE
how to get qt5 pkg-config variable?

### ISSUE THREAD

**Issue by goulf-3m** [mesonbuild/meson#8490]
In `/usr/lib64/pkgconfig/Qt5.pc`, there are variables like:

```
libexecdir=/usr/lib64/qt5/libexec
moc=/usr/lib64/qt5/bin/moc
plugindir=/usr/lib64/qt5/plugins
qmake=/usr/lib64/qt5/bin/qmake
```

I need to get the value of `plugindir` in the build system.
But `qt5_dep.get_variable(pkgconfig: 'plugindir')` does not work:

```
../source/gather/meson.build:35:0: ERROR: No default provided for dependency <Qt5Dependency qt5: True>, which is not pkg-config, cmake, or config-tool based.
```

**Comment by dcbaker** [comment]
Unfortunately qt has not been updated to use the new factory mechanism for dependencies with multiple ways to be found, which means there's no way to get the pkg-config variables. I've looked at it and tried a few times to convert it, but it's a dense bit of code and I've never been able to get it successfully converted.

**Comment by goulf-3m** [comment]
Very quick response! Thanks!

Here is some samples for this variable:

```
# Fedora
pkg-config --variable=plugindir Qt5
qmake-qt5 -query QT_INSTALL_PLUGINS
# Fedora/MinGW64
x86_64-w64-mingw32-qmake-qt5 -query QT_INSTALL_PLUGINS
# MSYS2/MinGW64
qmake.exe -query QT_INSTALL_PLUGINS
```

I've read some of meson's code.
Can overloading `get_variable` for `QtBaseDependency` solve this?
The interface will become `qt5_dep.get_variable(pkgconfig: 'plugindir', qmake: 'QT_INSTALL_PLUGINS')`.
