### ISSUE TITLE
Combining default_options : ['cpp_std=c++2a', 'cuda_std=c++17'] breaks nvcc

### ISSUE THREAD

**Issue by drewrobson** [mesonbuild/meson#8523]
I'm trying to compile a project where the host code (*.cpp) uses c++20, but the device code (*.cu) uses c++17, since that is the latest version currently supported by nvcc.

**Describe the bug**
In `meson.build`, I tried this:
```
project('C++ std', 'cpp', 'cuda', version : '1.0.0', default_options : ['cpp_std=c++2a', 'cuda_std=c++17'])
```
but `nvcc` fails because it was called with `--std=c++17 -std=c++2a`:

```
meson compile -v
ninja: Entering directory `.'
[1/2] nvcc -Xcompiler=-Wall -Xcompiler=-Winvalid-pch -Xcompiler=-Wnon-virtual-dtor --std=c++17 -std=c++2a -g -G -g -I.. -I. -Iprog.p -Iprog.p -o prog.p/main.cu.o -c ../main.cu
FAILED: prog.p/main.cu.o 
nvcc -Xcompiler=-Wall -Xcompiler=-Winvalid-pch -Xcompiler=-Wnon-virtual-dtor --std=c++17 -std=c++2a -g -G -g -I.. -I. -Iprog.p -Iprog.p -o prog.p/main.cu.o -c ../main.cu
nvcc fatal   : Value 'c++2a' is not defined for option 'std'
ninja: build stopped: subcommand failed.
```

**To Reproduce**
Start with cuda example [6 std](https://github.com/mesonbuild/meson/tree/master/test%20cases/cuda/6%20std), but use this:
```project('C++ std', 'cpp', 'cuda', version : '1.0.0', default_options : ['cpp_std=c++2a', 'cuda_std=c++17'])```

**Expected behavior**
I expected that `gcc` would be invoked with c++2a and `nvcc` would be invoked with c++17.

If I manually remove the spurious `-std=c++2a` then `nvcc` succeeds.

**system parameters**
This is a native build on 5.4.101-1-MANJARO with Meson 0.57.1.

**Comment by obilaniu** [comment]
@drewrobson Can you have a try at my solution? It solves it on my end (except with c++17 and 14; I don't have c++2a)

**Comment by drewrobson** [comment]
Yep, that solves it on my end as well, with c++2a and c++17. Thank you for fixing this so quickly!
