### ISSUE TITLE
`meson test` hangs if the write side of the stdout/stderr pipes is left open

### ISSUE THREAD

**Issue by bonzini** [mesonbuild/meson#8533]
If a test spawns a runaway subprocess and therefore the stdout or stderr pipe is left open, the test should timeout. Instead, Meson notices that the test has finished and just waits for the `stdo_task` and `stde_task` to finish, causing a hang. Worse, the hang cannot be cured with Ctrl-C.

**Comment by hadess** [comment]
(This happened, coupled with a bug in the tests, with a version of [this MR](https://gitlab.freedesktop.org/hadess/power-profiles-daemon/-/merge_requests/46) which I've kept locally in a branch called `wip/hadess/meson-hang-bug`, let me know if it's needed for debugging in the future)
