### ISSUE TITLE
meson dist not including hidden folders

### ISSUE THREAD

**Issue by Tachi107** [mesonbuild/meson#8541]
**Describe the bug**
`meson dist` seems to exclude hidden directories from the generated tarball. In particular, it doesn't include the `.github` folder.

**To Reproduce**
- `git clone https://github.com/Tachi107/pistache.git --branch=meson`
- `cd pistache`
- `meson setup build --buildtype=release --wrap-mode=nodownload`
- `meson dist -C build --no-test`

**Expected behavior**
All source code should be included in the tarball.

**system parameters**
* Build type: native
* Operating system: Debian Testing
* Python version: 3.9.1
* Meson version: 0.57.1
* Ninja version: 1.10.1

**Comment by eli-schwartz** [comment]
It's not "hidden folders".

It's "anything in the repository root that starts with `.git`". Like .gitignore, .gitmodules, .github/

This is by design, since you don't need those for dist tarballs.

**Comment by Tachi107** [comment]
Thanks for the response, I thought it was some kind of bug since it wasn't documented. I agree with the fact that you don't need git files, but `.github` is not a directory created by git itself, but gets manually created by the owner of the repository, and is indeed needed for dist tarballs. For example, take a look at [Debian's packaging repo of simdjson](https://salsa.debian.org/debian/simdjson); `meson dist` would create an invalid tarball since it would exclude the `.github` directory, part of the upstream source.

**Comment by eli-schwartz** [comment]
Why is this an invalid dist tarball? The contents of that directory are not needed, they only provide info to github.com -- generally, one would be excluding files like this via .gitattributes `export-ignore` (and also export-ignore'ing .circleci, .appveyor.yml, .cirrus.yml, .travis.yml, .drone.yml), but IMO the fact that this glob pattern (`.git*`) matches the .github/ directory is a happy coincidence. There are open issues for meson to support export-ignore.

Is this actually a problem for Debian packaging? Why do the salsa.debian.org sources need the github.com-specific issue templates and stuff?

**Comment by Tachi107** [comment]
Yes, it is a problem because in Debian packaging the source tarball has to be identical to the upstream repository, even if not all the files are needed; if the tarball differs from the upstream source `debhelper` interprets the difference as a modification by the Debian maintainer... In short, a mess.
I agree with you with the fact that those files are useless, but stripping them automatically can cause issues, and should not be the default behavior.

**Comment by eli-schwartz** [comment]
So it strips .gitignore too, is that also debhelper interpreting the difference as a modification by the Debian maintainer?

Because meson is NOT going to stop stripping out the .gitignore file just because debhelper requires it.

How does debhelper know that, anyway?
- Is it scanning the upstream VCS? Why doesn't debhelper auto-import it then?
- Is it not scanning the upstream VCS? Then when importing the dist tarball, how does it know the upstream didn't decide to remove this file?

--
Signed, a very confused developer of a package manager that uses `source=("https://dist.example.com/foo-1.0.tar.gz")` and applies patches as additional source files, rather than requiring to soft-fork the project and modify the upstream sources in order to add a debian/ directory and then check whether maybe it got mysteriously modified

**Comment by jpakkane** [comment]
> Yes, it is a problem because in Debian packaging the source tarball has to be identical to the upstream repository, even if not all the files are needed; if the tarball differs from the upstream source debhelper interprets the difference as a modification by the Debian maintainer

Wait, that can't be right. Tarballs created by autotools have many files that are not in revision control.

**Comment by Tachi107** [comment]
No, it doesn't need git files, but `.github` is not a git file. What if someone creates a file named .git-my-important-file for whatever reason? 

As for your questions, normally this wouldn't be a problem, since the tarball is automatically fetched from the upstream repository. This can became a problem when the owner of the repository is also the "Debian maintainer" and keeps the `debian` directory in the source tree. 

For example, Pistache nightly builds follow this workflow:
- a tarball gets generated from a script inside the `debian` directory by `meson dist`
- debhelper checks the tarball against the upstream source (that is in the `..` directory)
- if the tarball is identical to the source, it creates the package.

And when using `meson dist` the tarball lacks the `.github` directory, so packaging fails.

**Comment by eli-schwartz** [comment]
And they *also* don't have many files that are in revision control, since autotools only distributes files that are explicitly sources/data referenced in some Makefile.am, or otherwise autotools knows about e.g. because it got hardcoded into EXTRA_DIST

**Comment by jpakkane** [comment]
> This can became a problem when the owner of the repository is also the "Debian maintainer" and keeps the debian directory in the source tree.

If memory servers, Debian documentation explicitly says that maintainers should not do this, even when the maintainer and upstream are the same person.

**Comment by Tachi107** [comment]
> > This can became a problem when the owner of the repository is also the "Debian maintainer" and keeps the debian directory in the source tree.
> 
> If memory servers, Debian documentation explicitly says that maintainers should not do this, even when the maintainer and upstream are the same person.

That's right, I should ask the maintainers to change that... Anyway, the `.git-my-important-file` could still be an issue, since not everything starting with `.git` has to be generated by git
