### ISSUE TITLE
Uninstall does not remove installed folders

### ISSUE THREAD

**Issue by tank-trax** [mesonbuild/meson#8543]
Apparently `meson-uninstall` will only remove files but will leave created folders 

Referencing this [issue](https://github.com/DISTRHO/DISTRHO-Ports/issues/83) and [this](https://github.com/mesonbuild/meson/pull/2033)

**Comment by eli-schwartz** [comment]
It works fine for me. meson will only remove it if that directory did NOT exist during meson install, and therefore meson actually created the directory.

`ninja uninstall` might also report that it tried and failed to remove the directory, if it was not empty at the time.

**Comment by tank-trax** [comment]
I am still encountering this issue... meson/ninja does not appear to be removing folders that have had more than one file put in them (specifically LV2 plugins), it removes the files but not the folder for multiple LV2 instances
