### ISSUE TITLE
"meson --wipe" fails when used with --native-file 

### ISSUE THREAD

**Issue by john5342** [mesonbuild/meson#8560]
**Describe the bug**
When using `meson --wipe` meson looks for the native file in the wrong place. The file that should be used is still located in the same place in `/home/user/.local/share/meson/native/clang-13.ini`.

Upon further inspection it seems the incorrect path is stored in `meson-private/cmd_line.txt`. Python is not my native language, but it looks like `__load_config_files` in coredata.py searches for files under `~/.local/meson/...` but `write_cmd_line_file` simply takes the original option and uses `os.path.abspath` on it.

**To Reproduce**
```
$ meson setup --native-file clang-13.ini ..
[...]
```

is successful, but:

```
$ meson --wipe
Could not find any valid candidate for native files: /home/user/project_foo/build/clang-13.ini

ERROR: Cannot find specified native file: /home/user/project_foo/build/clang-13.ini
```

**Expected behavior**
Successfully nuke everything in the directory and then reconfigure with the same options.

**system parameters**
* Plain native build, but in my case using native-file to specify an alternative native compiler.
* Ubuntu (20.10) and Arch Linux
* Python 3.8.6 and 3.9.2
* Meson version 0.57.1 (latest from pip)
* Ninja 1.10.0 and 1.10.2

**Comment by xclaesse** [comment]
@dcbaker I had a fix already, hope we did not both worked on this :/

**Comment by dcbaker** [comment]
Nope, I didn't work on it, your patch looks good to me. I kicked the CI, when it's green lets get it merged.
