### ISSUE TITLE
wrap fallback works only for lower case names

### ISSUE THREAD

**Issue by gheift** [mesonbuild/meson#8564]
**Describe the bug**
In https://github.com/mesonbuild/meson/blob/master/docs/markdown/Wrap-dependency-system-manual.md#provide-section
it is described, that if I want to use a dependency, meson will autmatically fall back to a wrap file with this name or if a wrap file provides this name in `dependency_names` if it is not found. This does only work for lower case names. If I want to use a dependency with an upper case, this will fail.

**To Reproduce**
create a project:
```
project('wrap-uppercase-fallback')
foo = dependency('foo')
Bar = dependency('Bar')
```
create two subprojects with the following wrap file (name replaced with `foo` or `Bar`) 
```
[wrap-file]
directory = name
[provides]
# dependency_names = name
```
create a `meson.build` file in the corresponding subdirectories:
```
project('name')
meson.override_dependency(meson.project_name(), declare_dependency())
```
[wrap-uppercase-fallback.zip](https://github.com/mesonbuild/meson/files/6177912/wrap-uppercase-fallback.zip)

**Expected behavior**
`meson builddir` should succeed, but it fails.

This example works with 0.56.2. I did a bisect and the first bad commit is ca30550e065991f9b2438e2a6fabc64fd2248806

**Comment by tristan957** [comment]
@xclaesse @eli-schwartz I can't remember exactly, but I think one of you fixed this?

**Comment by xclaesse** [comment]
> [wrap-uppercase-fallback.zip](https://github.com/mesonbuild/meson/files/6177912/wrap-uppercase-fallback.zip)

I works for me with meson master, so I guess it got fixed at some point. Probably by https://github.com/mesonbuild/meson/pull/8143

**Comment by xclaesse** [comment]
> Probably by #8143

Oops, that's the PR bisected...

> This example works with 0.56.2. I did a bisect and the first bad commit is [ca30550](https://github.com/mesonbuild/meson/commit/ca30550e065991f9b2438e2a6fabc64fd2248806)

well... testcase pass anyway. If this is still a problem please update test case.

**Comment by xclaesse** [comment]
ah, must be https://github.com/mesonbuild/meson/pull/10585.
