### ISSUE TITLE
pkgconfig files from pkg.generate() with dataonly: true doesn't contain prefix variable

### ISSUE THREAD

**Issue by jadahl** [mesonbuild/meson#8583]
**Describe the bug**

When using `pkg.generate()`, with `dataonly:`, the `prefix=/the/prefix` is missing from the resulting `.pc` file.

**To Reproduce**

```
project('test')

pkg = import('pkgconfig')

pkg.generate(
  name: 'test',
  description: 'Test',
  dataonly: true,
  install_dir: join_paths(get_option('datadir'), 'pkgconfig')
)
```

results in

```

Name: test
Description: Test
Version: undefined
```

**Expected behavior**

I expected

```
prefix=/the/prefix

Name: test
Description: Test
Version: undefined
```

**system parameters**
* Fedora 34
* Python 3.9.2
* meson 0.56.2
* ninja 1.10.2

**Comment by xclaesse** [comment]
I think that was intentional, you can do `pkg.generate(..., variables: {'prefix': get_option(prefix)})`

**Comment by xclaesse** [comment]
Ah, that could be the solution, prefix should not be restricted when dataonly is true?
