### ISSUE TITLE
Meson using libstdc++ with Clang

### ISSUE THREAD

**Issue by brad0** [mesonbuild/meson#8592]
I noticed when updating QEMU that Meson was utilizing libstdc++ when building with Clang. OpenBSD and FreeBSD use libc++. Pretty odd assumption for Clang.

**Comment by dcbaker** [comment]
What platform are you using? And we're you around that shard coded value you're seeing, or are you looking at the final linked library?

**Comment by brad0** [comment]
OpenBSD, but this also pertains to FreeBSD.

Meson passes on libstdc++ on the command line when linking C++ binaries which is wrong.

The issue is in mesonbuild/compilers/cpp.py with this section. The last two lines.

```
class ClangCPPCompiler(ClangCompiler, CPPCompiler):
    def __init__(self, exelist: T.List[str], version: str, for_machine: MachineChoice, is_cross: bool,
                 info: 'MachineInfo', exe_wrapper: T.Optional['ExternalProgram'] = None,
                 linker: T.Optional['DynamicLinker'] = None,
                 defines: T.Optional[T.Dict[str, str]] = None,
                 full_version: T.Optional[str] = None):
        CPPCompiler.__init__(self, exelist, version, for_machine, is_cross,
                             info, exe_wrapper, linker=linker, full_version=full_version)
        ClangCompiler.__init__(self, defines)
        default_warn_args = ['-Wall', '-Winvalid-pch', '-Wnon-virtual-dtor']
        self.warn_args = {'0': [],
                          '1': default_warn_args,
                          '2': default_warn_args + ['-Wextra'],
                          '3': default_warn_args + ['-Wextra', '-Wpedantic']}

    def get_options(self) -> 'KeyedOptionDictType':
        opts = CPPCompiler.get_options(self)
        key = OptionKey('key', machine=self.for_machine, lang=self.language)
        opts.update({
            key.evolve('eh'): coredata.UserComboOption(
                'C++ exception handling type.',
                ['none', 'default', 'a', 's', 'sc'],
                'default',
            ),
            key.evolve('rtti'): coredata.UserBooleanOption('Enable RTTI', True),
        })
        opts[key.evolve('std')].choices = [
            'none', 'c++98', 'c++03', 'c++11', 'c++14', 'c++17', 'c++1z',
            'c++2a', 'c++20', 'gnu++11', 'gnu++14', 'gnu++17', 'gnu++1z',
            'gnu++2a', 'gnu++20',
        ]
        if self.info.is_windows() or self.info.is_cygwin():
            opts.update({
                key.evolve('winlibs'): coredata.UserArrayOption(
                    'Standard Win libraries to link against',
                    gnu_winlibs,
                ),
            })
        return opts

    def get_option_compile_args(self, options: 'KeyedOptionDictType') -> T.List[str]:
        args = []
        key = OptionKey('std', machine=self.for_machine, lang=self.language)
        std = options[key]
        if std.value != 'none':
            args.append(self._find_best_cpp_std(std.value))

        non_msvc_eh_options(options[key.evolve('eh')].value, args)

        if not options[key.evolve('rtti')].value:
            args.append('-fno-rtti')

        return args

    def get_option_link_args(self, options: 'KeyedOptionDictType') -> T.List[str]:
        if self.info.is_windows() or self.info.is_cygwin():
            # without a typedict mypy can't understand this.
            key = OptionKey('winlibs', machine=self.for_machine, lang=self.language)
            libs = options[key].value.copy()
            assert isinstance(libs, list)
            for l in libs:
                assert isinstance(l, str)
            return libs
        return []

    def language_stdlib_only_link_flags(self) -> T.List[str]:
        return ['-lstdc++']
```

**Comment by dcbaker** [comment]
Yeah, that's just wrong. It would be wrong on some Linux setups too.

**Comment by brad0** [comment]
> Yeah, that's just wrong. It would be wrong on some Linux setups too.

Any other OS that utilizes libc++ instead of libstdc++ as their C++ library would be affected. I just don't know of a Linux based OS that does at the moment, though I am sure there must be some.

**Comment by dcbaker** [comment]
Android does I think, and wouldn't be at all surprised if ChromeOS does. And you can never count out someone running Gentoo, lol.

**Comment by jpakkane** [comment]
Is this happening every time? That flag should only be used if you link an exe whose main is in C, but it links with C++ code.

**Comment by brad0** [comment]
> Is this happening every time? That flag should only be used if you link an exe whose main is in C, but it links with C++ code.

Not sure what you mean by every time. AFAIK QEMU is almost all C code with a tiny bit of C++ mixed in. From the logs it is only adding in libstdc++ when linking binaries, even though the compiler would do the right thing AFAIK even when not specified.

**Comment by Ella-0** [comment]
> > Yeah, that's just wrong. It would be wrong on some Linux setups too.
> 
> Any other OS that utilizes libc++ instead of libstdc++ as their C++ library would be affected. I just don't know of a Linux based OS that does at the moment, though I am sure there must be some.

I use Iglunix which uses libc++ and doesn't have libstdc++; I haven't encountered any problems with meson and C++ libraries.

**Comment by katrinafyi** [comment]
Has this been fixed now? The cpp.py file seems to have a more robust StdCPPLibMixin. https://github.com/mesonbuild/meson/blob/master/mesonbuild/compilers/cpp.py
