### ISSUE TITLE
How to pass this compilation option (add_compile_options(-fPIC) ) to the cmake subproject ?

### ISSUE THREAD

**Issue by zuowanbushiwo** [mesonbuild/meson#8594]
Hi  team
   I want to use the static library files of the open source library and combine the code developed by myself into a dynamic library，the  open source is a cmake project.   and a error occurred：can't link non-PIC static library into shared library， so I need to compile cmake sub-projects to generate static libraries with -fpic。I  know below cmake options can do this，But I don't know how to pass to the sub-project through meson syntax? I didn't find any relevant cases in the test case of cmake,thanks!
   1、
      add_compile_options(-fPIC)
2、 
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS}  -fpic")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}  -fpic")

**Comment by Tachi107** [comment]
Not sure if I understood correctly, but I think that the [cmake options](https://mesonbuild.com/CMake-module.html#cmake-options-object) object could be what you need. 

This is how I usually use it:

```meson
mylibrary_dep = dependency('mylibrary', required: false)
if not mylibrary_dep.found()
	cmake = import('cmake')
	mylibrary_options = cmake.subproject_options()
	mylibrary_options.append_compile_args(
		'cpp',
		'-fPIC'
	)
	mylibrary_dep = cmake.subproject('mylibrary', options: mylibrary_options).dependency('mylibrary')
endif
```

If this is what you needed, please search in the docs before opening an issue :)

**Comment by zuowanbushiwo** [comment]
thanks！
