### ISSUE TITLE
Error: No Package found for meson

### ISSUE THREAD

**Issue by gitlky9** [mesonbuild/meson#8600]
dear friends:
  I'm building this at-spi2-core-2.28.0-1.el7.src.rpm meed things, and get out "Error: No Package found for meson", whom  from  Centos7.6 operation system.

 this is a lot of info:
-------------------------------------------------------------------------------------------------------------------------------------------
            Error: No Package found for meson
            Finish: build setup for at-spi2-core-2.28.0-1.el7.src.rpm
            Finish: build phase for at-spi2-core-2.28.0-1.el7.src.rpm
            ERROR: Exception(/root/build_os/at-spi2-core-2.28.0-1.el7.src.rpm) Config(centos-7-x86_64) 1 minutes 40 seconds
            INFO: Results and/or logs in: /var/lib/mock/centos-7-x86_64/result
            ERROR: Command failed: 
             # /usr/bin/systemd-nspawn -q -M aed41021294f4111a865355f7b212bd5 -D /var/lib/mock/centos-7-x86_64-bootstrap/root -a --capability=cap_ipc_lock --bind=/tmp/mock-resolv.xj7gp7n9:/etc/resolv.conf --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/var/lib/mock/centos-7-x86_64/root/installation-homedir --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin --setenv=PROMPT_COMMAND=printf "\033]0;<mock-chroot>\007" --setenv=PS1=<mock-chroot> \s-\v\$  --setenv=LANG=C.UTF-8 --setenv=LC_MESSAGES=C.UTF-8 /usr/bin/yum-builddep --installroot /var/lib/mock/centos-7-x86_64/root/ --releasever 7 /var/lib/mock/centos-7-x86_64/root//builddir/build/SRPMS/at-spi2-core-2.28.0-1.el7.src.rpm
            Failed to create directory /var/lib/mock/centos-7-x86_64-bootstrap/root//sys/fs/selinux: Read-only file system
            Failed to create directory /var/lib/mock/centos-7-x86_64-bootstrap/root//sys/fs/selinux: Read-only file system
            Failed to set locale, defaulting to C
            base                                                                                                                 | 3.6 kB  00:00:00     
            centos-sclo-rh                                                                                                       | 3.0 kB  00:00:00     
            centos-sclo-sclo                                                                                                     | 3.0 kB  00:00:00     
            extras                                                                                                               | 2.9 kB  00:00:00     
            updates                                                                                                              | 2.9 kB  00:00:00     
            Getting requirements for at-spi2-core-2.28.0-1.el7.src
             --> 1:dbus-devel-1.10.24-15.el7.x86_64
             --> gettext-0.19.8.1-3.el7.x86_64
             --> glib2-devel-2.56.1-8.el7.x86_64
             --> gobject-introspection-devel-1.56.1-1.el7.x86_64
             --> gtk-doc-1.28-2.el7.x86_64
             --> libXtst-devel-1.2.3-1.el7.x86_64
             --> libXi-devel-1.7.9-1.el7.x86_64
             --> Already installed : systemd-219-78.el7_9.3.x86_64
            Error: No Package found for meson
-------------------------------------------------------------------------------------------------------------------------------------------

**Comment by eli-schwartz** [comment]
https://mesonbuild.com/Getting-meson.html

Sorry, we can't provide any specific guidance on why your distro might or might not have distro packages available. Please speak to your distribution vendor for guidance, or use one of the other installation methods listed at the above link.

**Comment by gitlky9** [comment]
thanks your info, and I'm selected epel source that It's hasn't problem.
