### ISSUE TITLE
Using the abseil-cpp WrapDB version  error,  on the windows platform

### ISSUE THREAD

**Issue by zuowanbushiwo** [mesonbuild/meson#8602]
meson.build :
absl_libs = [
  'absl_base',
  'absl_flags',
  'absl_strings',
  'absl_synchronization',
  'absl_types',
]

absl_deps = []
foreach lib : absl_libs
  absl_deps += dependency(lib)
endforeach

|Executing subproject abseil-cpp method meson
|
|Project name: abseil-cpp
|Project version: 20200923.2
|C++ compiler for the host machine: cl (msvc 19.28.29913 "���� x64 �� Microsoft (R) C/C++ �Ż������� 19.28.29913 ��")
|C++ linker for the host machine: link link 14.28.29913.0
|Compiler for C++ supports arguments -Wno-sign-compare: NO
|Checking if "GCC atomic builtins" links: NO

subprojects\abseil-cpp-20200923.2\meson.build:27:2: ERROR: C++ shared or static library 'atomic' not found

![image](https://user-images.githubusercontent.com/3354428/112976425-708f8b00-9187-11eb-82fc-542a97f955e1.png)

**Comment by nazar-pc** [comment]
Same here, running on GitHub Actions:
```
abseil-cpp| Project name: abseil-cpp
abseil-cpp| Project version: 20210324.1
abseil-cpp| C++ compiler for the host machine: cl (msvc 19.29.30038.1 "Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30038.1 for x64")
abseil-cpp| C++ linker for the host machine: link link 14.29.30038.1
abseil-cpp| Compiler for C++ supports arguments -Wno-sign-compare: NO
abseil-cpp| Compiler for C++ supports arguments -maes: NO
abseil-cpp| Compiler for C++ supports arguments -msse4.1: NO
abseil-cpp| WARNING: msvc does not support C++11; attempting best effort; setting the standard to C++14
abseil-cpp| Checking if "GCC atomic builtins" links: NO

subprojects\abseil-cpp-20210324.1\meson.build:36:2: ERROR: C++ shared or static library 'atomic' not found
```

Maybe `atomic` library needs to have some special case handling on MSVC?

**Comment by jpakkane** [comment]
These sort of issues should be reported against the WrapDB, not Meson itself. In any case [this should fix it](https://github.com/mesonbuild/wrapdb/pull/116).
