### ISSUE TITLE
find_library usage?!

### ISSUE THREAD

**Issue by WarShoe** [mesonbuild/meson#8615]
I have a library located in /usr/local/lib which I want to use in my project. I can easily create an executable with:

`g++ a.cpp -lsomelibname`

I informed meson build system that I want to use the library with:

```
compiler = meson.get_compiler('cpp')
somelibname = compiler.find_library('somelibname')
myprog = executable('myprog', 'myprog.cpp', dependencies : [somelibname])
```

The library is found, but the executable is not linked against it. I have unresolved symbol errors.

Is it a bug? Or a feature? Or did I miss something in the documentation?

Thanks in advance,
Alexander.

**Comment by xclaesse** [comment]
Can you check the link command with ninja -v, to see if the library is passed, please?

**Comment by WarShoe** [comment]
I made a fresh build of my project, and now it does work as expected. So the misconfiguration was somehow related to the fact that I added the lines (see above) on already existing build. And it did not work well.

Sorry for the spam :(

**Comment by WarShoe** [comment]
close
