### ISSUE TITLE
generated "-uninstalled.pc" files missing `CFlags`

### ISSUE THREAD

**Issue by nanthony21** [mesonbuild/meson#8651]
I have a large collection of pre-built libraries which are dependencies for project `A`. Rather than  include all the logic for selecting linker/include paths in project `A` I would like to create a subproject `B` which does no compiling but instead just generates the appropriate `.pc` files to so that project `A` can find it's dependencies using `dependency('my3rdPartySDK')`.

I had initially hoped to be able to do this as something like:
```
pkg = import('pkgconfig')
SDK_lib = compiler.find_library('MySDKLibFileName`, dirs: meson.current_source_dir() / 'pathtolib')
SDK_dep = declare_dependency(include_directories: SDK_include_dir, dependencies: SDK_lib)
pkg.generate(SDK_dep)
```
but as far as I can tell `generate` will only take objects from `library()`, `shared_library()`, etc. so there is no way to do this for libraries that are pre-built.

I am now doing this instead:
```
SDK_lib = compiler.find_library('MySDKLibFileName`, dirs: meson.current_source_dir() / 'pathtolib')
pkg.generate(
    name: 'MySDKName',
    libraries: SDK_lib,
    description: 'My SDK Description',
    version: '0.1')
```

The resulting `-uninstalled.pc` file looks like this:
```
prefix=C:/absolute_path_to_meson_build_dir
srcdir=C:/absolute_path_to_meson_source_dir
libdir=${prefix}/lib
includedir=${prefix}/include

Name: MySDKName
Description: My SDK Description.
Version: 0.1
Libs: absolute_path_to_SDK_lib/MySDKLibFileName.lib
```

This obviously causes problems at compile time in project `A` because the header files are not found.

I tried adding something to the `subdirs` kwarg of `pkg.generate` but it had no effect on the final output. The only way I got the `Cflags` section to appear was with the `extra_cflags` kwarg, so I could potentially manually insert the correct include path with this kwarg.

It's also worth noting that the generated `includedir` variable doesn't point to the correct location. Is there a possibility of adding an `includes` kwarg to the generator that will set the `includedir` variable and then use it in `CFlags`?

Also, if there's a smarter way for me to achieve what I'm trying to do please let me know.

**Comment by eli-schwartz** [comment]
I don't understand the goal here. pkg.generate is used to export information about your build outputs to non-meson build systems, but this doesn't seem to be a build output plus you're using it to export information out of a subproject to the superproject.

Why don't you just do `subproject('B').get_variable('SDK_dep')` in project A and use the returned dependency object as is?

**Comment by xclaesse** [comment]
This is a job for `meson.override_dependency()`:

In the subproject:
```
SDK_lib = compiler.find_library('MySDKLibFileName`, dirs: meson.current_source_dir() / 'pathtolib')
SDK_dep = declare_dependency(include_directories: SDK_include_dir, dependencies: SDK_lib)
meson.override_dependency('my3rdPartySDK', SDK_dep)
```

In the main project:
```
dependency('my3rdPartySDK', fallback: 'sdk-subproject-name')
```

**Comment by nanthony21** [comment]
@eli-schwartz You're right that in my particular case doing it like this would be simpler since I'm using Meson in both projects. I was hoping to make things as modular as possible so that if another project wants to use the binaries in project `B` but doesn't use Meson for its build system it can just build project `B` with whichever build options it needs (architecture, OS, compiler version) in order to generate `.pc` files it can use.

Thanks @xclaesse, I wasn't familiar with `meson.override_dependency`. I like how it would allow me to reference the dependency without needing knowing the variable name within the subproject.

Aside from the issue of what the best way to do this within Meson, it is a bug for the the generated files to not have any `CFlags` section, right?

**Comment by eli-schwartz** [comment]
Maybe?

If you use a library() that has an include_directories kwarg, the generated -uninstalled.pc is correct. `compiler.find_library()` wasn't really intended for this use case though. As you can see from the fact that `pkg.generate(declare_dependency(...))` apparently does not (currently?) work.

**Comment by nanthony21** [comment]
I'm way too new to Meson to have an educated opinion on this but I don't see a reason why `pkg.generate(declare_dependency(...))` shouldn't be made to work, I think all of the requisite information for `pkg.generate` would be present in the dependency object . It would definitely suit my purposes well even if it isn't the most common use case.

This isn't currently described at https://mesonbuild.com/Pkgconfig-module.html but it looks like in the case that kwargs are used rather than passing a library to `pkg.generate` the `name` and `description` kwargs are required while the rest are optional. It seems to me like a new `include_directories` kwarg should also be required.  Currently the include directory in the generated file is:
 - Nonexistent in the case of `-uninstalled.pc` files
 - Assumed to be `${prefix}/include/${subdirs}` for installed `.pc` files.

**Comment by xclaesse** [comment]
>  I was hoping to make things as modular as possible so that if another project wants to use the binaries in project `B` but doesn't use Meson for its build system it can just build project `B` with whichever build options it needs (architecture, OS, compiler version) in order to generate `.pc` files it can use.

Note that using [`unstable_external_project`](https://mesonbuild.com/External-Project-module.html) module meson will set PKG_CONFIG_PATH pointing to `<builddir>/meson-uninstalled` automatically when calling external project's configure script. In that case indeed the broken generated -uninstalled.pc file is going to be problematic.

> Aside from the issue of what the best way to do this within Meson, it is a bug for the the generated files to not have any `CFlags` section, right?

Yes that sounds like an issue indeed, even if in this particular case you should be able to work around it easily.

> As you can see from the fact that `pkg.generate(declare_dependency(...))` apparently does not (currently?) work.

That's intentional, the positional argument is optional for the case you generate a pc file for a library, where it can guess default values for all other fields. In this case you would have to use `pkg.generate(libraries: declare_dependency(...), ...)`.

**Comment by xclaesse** [comment]
Note there is already special code for -uninstalled.pc files to have proper include directories: https://github.com/mesonbuild/meson/blob/master/mesonbuild/modules/pkgconfig.py#L417. That code takes `include_directories` from Library objects but miss those from InternalDependency objects.

**Comment by eli-schwartz** [comment]
@nanthony21 correct, this would have to be "made to work", i.e. it's an enhancement request rather than being broken per se.

**Comment by nanthony21** [comment]
Sounds good, I may give this a try at some point, though probably not any time soon. 

Would there be any objection to adding type annotations to this module? Just makes it a little easier for someone who isn't already familiar with the various internal classes understand the flow of the functions a bit better.

**Comment by eli-schwartz** [comment]
Type annotations are being continually added to old code whenever people have time and are working on that section of the code already.

**Comment by anarazel** [comment]
I just hit this issue...

> Note there is already special code for -uninstalled.pc files to have proper include directories: https://github.com/mesonbuild/meson/blob/master/mesonbuild/modules/pkgconfig.py#L417. That code takes include_directories from Library objects but miss those from InternalDependency objects.

Looks that, at least today, the problem is that dependencies aren't tracked in `DependenciesHelper.pub_libs/priv_libs`, because `_process_libs` doesn't append them to `processed_libs`, just their dependencies. A quick hack suggests that it doesn't require many changes to do so and adjust a few checks.  Does that seem like the right approach?

**Comment by xclaesse** [comment]
> I just hit this issue...
> 
> > Note there is already special code for -uninstalled.pc files to have proper include directories: https://github.com/mesonbuild/meson/blob/master/mesonbuild/modules/pkgconfig.py#L417. That code takes include_directories from Library objects but miss those from InternalDependency objects.
> 
> Looks that, at least today, the problem is that dependencies aren't tracked in `DependenciesHelper.pub_libs/priv_libs`, because `_process_libs` doesn't append them to `processed_libs`, just their dependencies. A quick hack suggests that it doesn't require many changes to do so and adjust a few checks. Does that seem like the right approach?

Made a fix there: https://github.com/mesonbuild/meson/pull/10452.

**Comment by vinipsmaker** [comment]
I'd appreciate an explicit option to set extra include directories. I'm using pkg-config to generate a plugin API. However my project only builds an executable, and plugins (shared modules) don't link against the executable. I had to create a dummy unused library just to make sure the include directories would be generated. Here's the isolated changeset to illustrate the issue: https://gitlab.com/emilua/emilua/-/commit/ae65b890076bced83fa428535fc6f667ece40f78
