### ISSUE TITLE
Treating Cython like a language?

### ISSUE THREAD

**Issue by rgommers** [mesonbuild/meson#8693]
Context: I'm working on building SciPy with Meson. SciPy is a mixed-language library (Python, Cython, C, C++, Fortran), for more details of Meson + SciPy see https://github.com/scipy/scipy/issues/13615. 

I'd like to get your feedback on a design question on how to integrate tools like Cython, but later perhaps also f2py and Pythran. I'm combining all of these because they interact with a build system in the same way:
- They all generate C or C++ code.
- The can be invoked as a command-line tool to generate only C/C++ (e.g., `cython somefile.pyx`)
- They can be used like a compiler to generate a Python extension module (e.g. `cythonize -a -i somefile.pyx`).
- They have build system integration with `numpy.distutils` and `setuptools`, so you can do something like `setup(ext_modules = cythonize("somefile.pyx"))` in a `setup.py` file to obtain a Python extension module.

None of the three is supported in Meson directly; Cython is by far the most widely used one and is tested in Meson's test cases (e.g, [from here](https://github.com/mesonbuild/meson/blob/master/test%20cases/python/3%20cython/libdir/meson.build)):

```python
pyx_c = custom_target('storer_pyx',
  output : 'storer_pyx.c',
  input : 'storer.pyx',
  command : [cython, '@INPUT@', '-o', '@OUTPUT@'],
)

slib = py3.extension_module('storer',
  'storer.c', pyx_c,
  dependencies : py3_dep)

pydir = meson.current_build_dir()
```

The `custom_target` and then `py3.extension_module` approach should work for all these tools I think, but it's going to be very verbose. It takes 9 lines per extension module in `meson.build` compared to 1-2 lines with the current `setup.py` approach. Some of this (`'@INPUT@', '-o', '@OUTPUT@'`, `dependencies : py3_dep`) is only boiler-plate.

There are compiler directives (e.g. `--fast-fail`, `--language-level=3`, `--cplus`, for Cython; `-fopenmp`, `-DUSE_XSIMD` for Pythran) that one may want to set by default or switch around easily, as well as include file types (`.pxi`) and a templating format (`.pyx.in`) that may make the difference in verbosity even larger. In SciPy right now, the approach is to use a separate pre-build script ([tools/cythonize.py](https://github.com/scipy/scipy/blob/master/tools/cythonize.py)) to do that for all Cython sources. That seems like a bad idea (e.g., it needs to maintain its own ad-hoc build cache).

Therefore, given that Cython is an actual language that just happens to transpile to C (or, optionally, C++), and has a relatively large user base, I wonder if it makes sense to treat it like a supported language in Meson rather than as an external tool one must use `custom_target` for? So one could just write:

```python
# cython is now treated like a compiler, so `cython = find_program('cython')`
# is also not needed.
project('projname', 'cython')

slib = py3.extension_module('storer',
  'storer.pyx',
  dependencies : py3_dep)  # this line also seems like boiler plate, it's always needed to build a Python extension module?
```

I'm wondering if this makes sense to support, and if not if there's anything else you can recommend to make creating Python modules from Cython more ergonomic?

**Comment by eli-schwartz** [comment]
One possibility would be to teach `py3.extension_module()` to natively recognize e.g. the .pyx files and handle all the cython stuff for you.

**Comment by rgommers** [comment]
Thanks @eli-schwartz. 

> Although I don't believe it would be tied to project languages as I think that is more tied to executable().

I thought it was related to compiler. If you give a `.c` file to `py3.extension_module()` then it knows it needs a C compiler, and compiler flags can then be controlled with other Meson functions.

So say we teach `py3.extension_module('storer', 'storer.pyx', dependencies : py3_dep)` that it needs a C compiler, then it will work with the default `cython` behavior. But how do we pass flags to Cython itself?

There's probably multiple ways of implementing that, and my (inexperienced) impression it could be something like
```
project('projname', 'cython', default_options=[...])
```
I'm happy to give this a try, just want to make sure I don't run off in the completely wrong direction.  I guess another way is something like:
```
project('projname', 'c')

conf_data = configuration_data()
conf_data.set('cython_flags', ['-a', '--fast-fail'])

py3.extension_module('storer', 'storer.pyx', configuration : conf_data, :  dependencies : py3_dep)
```
Or maybe it should use build options, and then feed `get_option()` to `py3.extension_module`?

**Comment by dcbaker** [comment]
I've thought about this before as well, I think you'd want to handle it much like we do Vala, which similarly uses C as its assembly language. You'd have a two step "compilation", one step would convert the pyx files to C or C++, and a second would compile the C to an object file.

The only interesting part is deciding whether to use C or C++, especially if you want to mix C and C++ in a single target, ie:
foo.pyx -> foo.cpp and bar.pyx => bar.c in library('foo', 'foo.pyx', 'bar.pyx')

**Comment by dcbaker** [comment]
I decided to take a bit and writing something, here's what I came up with: https://github.com/mesonbuild/meson/pull/8706

It's not complete at all, but hopefully it points you in the right direction.

**Comment by rgommers** [comment]
That is super helpful, thanks @dcbaker! I'll try and push that forward on the weekend.

> The only interesting part is deciding whether to use C or C++, especially if you want to mix C and C++ in a single target, ie:
> foo.pyx -> foo.cpp and bar.pyx => bar.c in library('foo', 'foo.pyx', 'bar.pyx')

That should be rare, so if it doesn't fit nicely into the Meson design then saying that in that case you have to use `custom_target` plus `library('foo', 'foo.cpp', 'bar.c')` seems perfectly reasonable.

**Comment by dcbaker** [comment]
I think we can probably handle this with a command line option, something like `-Dcython_language=(c|cpp)`, if you want to mix C and C++ then you get to play tricks with `static_library` and `override_options`

**Comment by tristan957** [comment]
This is a great suggestion. I am using Cython in a Meson project as well. Workflow isn't great at the moment, but gets the job done. Would love to be able to test this feature @rgommers when you get a PR up.

**Comment by rgommers** [comment]
> Would love to be able to test this feature @rgommers when you get a PR up.

@dcbaker already did, see gh-8706. It's working pretty well for me so far. Still need to get to the more complex codegen'ed cases in SciPy though.

**Comment by dcbaker** [comment]
ATM anything generated is going to be silently ignored. I think I need to sit down and write my structured input proposal to make that work, which I need to do for Rust anyway.

**Comment by tristan957** [comment]
Python `__doc__` and type stub files/language servers don't play nice together, so I have to generate my Cython files to insert `__doc__` comments and I have to generate my type stub files for doc comments on hover in editors/IDEs. The Python ecosystem is so fun to work in.

**Comment by dcbaker** [comment]
Right, I have the same problem with some Rust code, actually. (in my case I'm using bindgen to create a wrapper around a C library, but it's the same problem)

I'm currently writing the structured input idea. See if it works out.

**Comment by tristan957** [comment]
@dcbaker is the work done for this issue? Seems like it is now that Cython is a recognized language in Meson.

**Comment by dcbaker** [comment]
Yeah. There’s still improvements to be made, but those cam live in their own issues

**Comment by Freed-Wu** [comment]
Not all cython files are treated as cython language.

cython support two extensions: py and pyx. The difference:

```cython
# foo.pyx
from XXX cimport xxx
```

```python
# foo.py
from cython.cimports.XXX import xxx
```

However, the latter is not supported:

```meson
py.extension_module(
  '__init__',
  ['__init__.py'],
  dependencies: deps,
  subdir: 'XXX',
  install: true,
  cython_args: ['-3I' + meson.project_source_root()]
```

> ERROR: No specified compiler can handle file src/XXX/__init__.py

**Comment by rgommers** [comment]
@Freed-Wu that is a bit too magical and not backwards compatible (`.py` files are Python not Cython normally, and treated as order dependencies now I think if you pass them as sources). If you want to run `cython` over `.py` files, you can use a `custom_target` or a `generator`, e.g. (extracted from SciPy code):
```meson
cy = meson.get_compiler('cython')
# generator() doesn't accept compilers, only found programs - cast it.
cython = find_program(cy.cmd_array()[0])

cython_gen = generator(cython, output : '@BASENAME@.c')

py.extension_module(
  '__init__',
  cython_gen.process('__init__.py'),
  dependencies: deps,
  subdir: 'XXX',
  install: true,
  cython_args: ['-3I' + meson.project_source_root()]
```

Also, for next time: note that it's better to open a new issue rather than comment on an old closed issue.
