### ISSUE TITLE
wxWidgets runtime error with using wx-config on Arch Linux.

### ISSUE THREAD

**Issue by apoorv569** [mesonbuild/meson#8722]
**Describe the bug**
wxWidgets throws a runtime error when both `wxgtk2` and `wxgtk3` are installed on the system, as `wxgtk2` uses `wx-config` and `wxgtk3` uses `wx-config-gtk3` on Arch Linux. Here is the error when trying to run the binary,
```
(SampleHive:997080): Gtk-ERROR **: 07:34:03.946: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported
zsh: trace trap (core dumped)  ./SampleHive
```

**To Reproduce**
Here is the link to my current `meson.build` file that does has this issue - https://gitlab.com/samplehive/sample-hive/-/blob/testing/meson.build

**Things I have tried to fix this**
I tried adding a few parameters in my meson file to fix this for the moment here is the link with the changes - https://pastebin.com/vzsRMx3U

**Expected behavior**
It should detect both and use `wx-config` or `wx-config-gtk3` appropriately.

**system parameters**
* Native build
* Arch Linux
* Python version - 3.9.4
* Meson version - 0.57.2
* Ninja version - 1.10.2

**Comment by tristan957** [comment]
@eli-schwartz closeable

**Comment by apoorv569** [comment]
> @eli-schwartz closeable

I think this is fixed for me. I'll go ahead and close this.

**Comment by eli-schwartz** [comment]
Probably, setting it via the machine file would work to disambiguate them anyway. :)

**Comment by apoorv569** [comment]
> Probably, setting it via the machine file would work to disambiguate them anyway. :)

What's a `machine` file?

**Comment by tristan957** [comment]
https://mesonbuild.com/Machine-files.html
