### ISSUE TITLE
[0.58.0] test() fails with nested environment variables

### ISSUE THREAD

**Issue by jbeich** [mesonbuild/meson#8727]
**Describe the bug**
Regressed by 598e968993da58 (found [downstream](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=255550#c2)). At least [libglvnd](http://www.ipv6proxy.net/go.php?u=http://package18.nyi.freebsd.org/data/122amd64-default-foo/2021-05-03_09h14m29s/logs/libglvnd-1.3.2.log), [libvirt](http://www.ipv6proxy.net/go.php?u=http://package18.nyi.freebsd.org/data/122amd64-default-foo/2021-05-03_09h14m29s/logs/libvirt-7.2.0.log), [nautilus](http://www.ipv6proxy.net/go.php?u=http://package18.nyi.freebsd.org/data/122amd64-default-foo/2021-05-03_09h14m29s/logs/nautilus-3.36.3.log) fail with `ERROR: List item must be one of <class 'str'>, not <class 'list'>`

**To Reproduce**
```meson
project('test', 'c')

runutf8 = [ 'LC_ALL=', 'LANG=C', 'LC_CTYPE=en_US.UTF-8' ]

add_test_setup(
  'access',
  env: [
    'VIR_TEST_FILE_ACCESS=1',
    runutf8,
  ],
  exe_wrapper: [ 'true' ],
)
```

**Expected behavior**
Build passes or maybe docs updated.

**system parameters**
* native build
* FreeBSD 11.4 / 12.2 / 13.0 / -CURRENT
* Python 3.8.9 / 3.9.4
* Meson 0.58.0
* Ninja 1.10.2

**Comment by dcbaker** [comment]
@xclaesse

**Comment by xclaesse** [comment]
Should be fixed by https://github.com/mesonbuild/meson/pull/8761.
