### ISSUE TITLE
Documentation: How to build both static library unconditionally while still having `-Ddefault_library=both` work

### ISSUE THREAD

**Issue by nh2** [mesonbuild/meson#8729]
The gtk4 project's usage of `-Ddefault_library` usage broke as `libgtk = library('gtk-4', ...)` was split into explicit

```meson
libgtk = shared_library(..)
libgtk_static = static_library(..)
```

in order to facilitate testing of internal APIs, see:

* https://gitlab.gnome.org/GNOME/gtk/-/commit/14f0a0addb9a195bad2f8651f93b95450b186bd6
* https://gitlab.gnome.org/GNOME/gtk/-/issues/3774#note_1099438
* https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/3107/diffs

It seems currently unclear how such a use case can be supported while not breaking `-Ddefault_library=both` for the user that wants to build the project.

It would be excellent if Meson developers could provide a recommendation on how this could be best accommodated.

Thanks!

**Comment by xclaesse** [comment]
Why not simply:
```
libgtk_static = static_library(...)
libgtk = library(..., link_with: libgtk_static, install: true)
```

**Comment by eli-schwartz** [comment]
https://git.archlinux.org/pacman.git/tree/meson.build?h=v5.2.2#n319

In pacman, we build an object library "libalpm_objlib.a" via static_library('alpm_objlib') and link that into libalpm.so/libalpm.a as needed via library()

**Comment by xclaesse** [comment]
@nh2 that should work: https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/3519.
