### ISSUE TITLE
Appleframeworks not detected with gcc-10 (homebrew installation) in Mac

### ISSUE THREAD

**Issue by germandiagogomez** [mesonbuild/meson#8733]
Steps to reproduce:

1. create a project with a dependency on 'appleframeworks'.
2.  see it fail.

Gcc path does show the framework path:

```
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks
```

Also, adding `-framework Appkit` via link_args in replacement of real meson detection to target does find the framework and it works (workaround).

**Comment by dcbaker** [comment]
Real GCC (and vanilla clang) on macOS is currently a "best effort" situation, so this doesn't surprise me at all.

**Comment by germandiagogomez** [comment]
Which are supported in MacOS?

**Comment by dcbaker** [comment]
Apples clang fork is the only one in ci, so it's the only ones that has official support ATM. I'd be happy to review fixes for vanilla clang and gcc on macos, and add CI support of course
