### ISSUE TITLE
shared_module() builds a module with SONAME field while it is not a shared_library()

### ISSUE THREAD

**Issue by MichaelJTokarev** [mesonbuild/meson#8746]
For an ELF targets (eg gcc on linux), shared_module() meson function builds a module with SONAME field (using -Wl,-soname argument). This is wrong, - only the shared_library() needs SONAME, while shared_module() does not. More, some tools - e.g. debian's dpkg-shlibdeps - uses presence of SONAME field as an indicator that this is shared _library_ (as opposed to shared module - for the module it is okay to have unresolved symbols which are imported from the executable which loads the module, while a library should have all symbols resolved).

It'd be very nice if meson will not use -soname when building shared_module(), -soname should be used only for shared_library().

**Comment by dcbaker** [comment]
We should only be setting soname if an explicit version is set, at the very least. So I'm calling this a bug
