### ISSUE TITLE
Enable  Disabled Auto  python 3.9 

### ISSUE THREAD

**Issue by Drakeo** [mesonbuild/meson#8749]
From the the looks of your commits you have a broken release.
Had nothing but issues with this in slackware64-current .
Glib GTK+2 ATK   only  =auto is working when wanting to build static 
PulseAudio 14.2 -Dorc=enabled   not recognize,  enable or auto just "disabled"  that gives a false enabled. 
from the looks of your commits you have changed the way  parses these variables.
revert back to 0.57.2 
works in all the systems python 2.7 to 3.9.
~~~
   27 #include "adrian-aec.h"
   28 
   29 #ifndef DISABLE_ORC
   30 #include "adrian-aec-orc-gen.h"
   31 #8186 
~~~

**Comment by eli-schwartz** [comment]
I don't know what this means, and it is full of vague statements that aren't definable.

Also I don't know what the references to python 2.7 mean, since this project doesn't support python 2.7.
