### ISSUE TITLE
meson.build:1:0: ERROR: Compiler g++ can not compile programs.

### ISSUE THREAD

**Issue by bogen85** [mesonbuild/meson#8751]
**Describe the bug**
Meson prohibits the use a c++ compiler for C, even when an existing code base compiles and runs fine for each.
`CC=g++` and `CC=clang++` both fail. (`CC=gcc` and `CC=clang` both succeed)

The issue is that my project uses nested functions.
These are supported on clang and gcc and c++ (I use macros to define them based on compiler).

Building on Linux/BSD/etc, no problem, clang and gcc are generally available.

On windows clang or gcc might not be available.

msvc C does not support nested functions (AFAIK), but msvc c++ does (recent standards, C++ lambdas).

So, when not using meson to build, the code can be compiled on more platforms, but with meson, it is limited to those with gcc and clang.

Yes, those are available on windows... but if msvc is available, it would be easier to use it's c++ compiler.

So without meson as the build system, clang or gcc would not be required on windows if msvc is available.

With meson as the build system, clang or gcc would be required on windows even if msvc is available.

sanitycheckc.c is valid C, but it is not valid C++, so the sanity check fails.
`c
int main(void) { int class=0; return class; }
`

Since the sanity check fails, meson gives up 

**To Reproduce**
my meson.build:
`
project(
    'sample',
    'c',
    version : '0.0.1',
    default_options : ['warning_level=3'],
    license: 'MIT',
)
`

**Expected behavior**

Meson to accept a C++ compiler as a C compiler (does not need to be via CC=, could be some other mechanism), as the needed options to force c++ for .c '-xc++' (for clang++ can g++) are added later. (And when just using make, the code base builds and runs fine with gcc, clang, g++, and clang++)

C++ is a superset of C, and can compile most C code that is not invalid C++ code. Obviously if one is to have a project work when compiled with C or C++, they must be aware of the intersection of the two languages, and know how to deal with any differences.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
Answer: **Native**

* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
Answer: **Arch Linux**
`
$ cat /etc/os-release 
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
`

* what Python version are you using e.g. 3.8.0
`
$ python --version
Python 3.9.4
`
* what `meson --version`
`
$ meson --version
0.58.0
`
* what `ninja --version` if it's a Ninja build
`
$ ninja --version
1.10.2
`

**Comment by bogen85** [comment]
So, I replaced the default sanitycheck.c  in `/usr/lib/python3.9/site-packages/mesonbuild/compilers/c.py`
and `/usr/lib/python3.9/site-packages/mesonbuild/compilers/mixins/clike.py` with valid c++ code.

was: `code = 'int main(void) { int meson=0; return meson; }\n'`

now: `code = 'int main(void) { int class=0; return class; }\n'`

After I did that, `CC=g++ meson build` and `CC=clang++ meson build` both work, and I can build my project, and it runs fine built with meson.

With that change clang, gcc, clang++, g++ are all supported for my project. Have not tried msvc c++ yet.

**Comment by eli-schwartz** [comment]
FWIW commit 221f175cfb9625e21a39794fb5488b54378c5e73 saw fit to intentionally break this use case.

**Comment by bogen85** [comment]
@jpakkane do you recall the rationale behind breaking this use case? I know it has been a while since that commit was made on Jan 1, 2013.

**Comment by bogen85** [comment]
Oh, I spoke too quickly. My testing was invalid and it was not actually switching compiles, seems like CC=g++ still chooses "gcc". 
I'll do some more digging.

**Comment by bogen85** [comment]
OK, if I check the CC environment variable (yes, I know, that is not supported directly, but it is not difficult to do so by invoking python) then I can set the build flags correct and it works as expected.

**Comment by bogen85** [comment]
`compiler.cmd_array()[0]` also returns the actual compiler, so no need to check the environment variable.

**Comment by bogen85** [comment]
So, to check for actual compiler to determine how to set arguments, I need to do:

```python
compiler = meson.get_compiler('c')

actual_cc = compiler.cmd_array()[0]
```

**Comment by jpakkane** [comment]
Setting CC to a C++ compiler rather than C is an easy mistake to make so we want to protect against it. Compiling C with a C++ compiler has nasty edge cases. For example the program gets a link-time dependency to the C++ standard library, which is unacceptable for many.

Your issue can be worked around by having a `foo_msvc.cpp` file that does the following:

    #include<foo.c>

and then adding either 'foo.c` or `foo_msvc.cpp` to the list of sources. This is not a super smooth automatic solution, sadly, but it is explicit and reliable. Unfortunately practice has shown that pretending that some files are in one language or the other depending on some dynamic condition is fragile and breaks in unexpected ways when you least expect it.

**Comment by eli-schwartz** [comment]
I guess in theory we could add a core option e.g. "compile_c_as_cpp".

**Comment by bogen85** [comment]
> Setting CC to a C++ compiler rather than C is an easy mistake to make so we want to protect against it. Compiling C with a C++ compiler has nasty edge cases. For example the program gets a link-time dependency to the C++ standard library, which is unacceptable for many.

This would only be for the instances when clang or gcc are not available on the given platform, but a C++ compiler is.

> 
> Your issue can be worked around by having a `foo_msvc.cpp` file that does the following:
> 
> ```
> #include<foo.c>
> ```

Not ideal, but that would be required for every c file in the project. Granted, these could be generated.

**Comment by jpakkane** [comment]
> I guess in theory we could add a core option e.g. "compile_c_as_cpp".

No we could not. Neither in practice or in theory. If someone tries to submit one, I will personally reject it.

**Comment by jpakkane** [comment]
Alternatively if you want to compile all C sources as C++ [VS has compiler flags for that](https://docs.microsoft.com/en-us/previous-versions/032xwy55(v=vs.140)?redirectedfrom=MSDN).

**Comment by bogen85** [comment]
Yes, but if I specify the project type as "cpp" then meson tells me something like:
```
meson.build:xx:0: ERROR: No host machine compiler for "src/somefile.c"
```

For now what I plan to do is have a provide a config file, and I'll have a meson.build.in template that I'll process with a python script and will generate the needed .cxx (or .cpp) wrappers.

**Comment by jpakkane** [comment]
You should do something like:

`´`meson
project('foo', 'c')

if meson.get_compiler('c').id() == 'msvc'
    add_languages('cpp')
endif
`´`

**Comment by bogen85** [comment]
Thanks. I'll figure something out. I'll close this  issue, but I'll follow up with what I came up with.

**Comment by bogen85** [comment]
Alright, got it working with `gcc/g++` and `clang/clang++`

I change my project to a 2 language project `['c', 'cpp']`

I'm auto generating the cxx c source wrappers to a separate cxx source directory

for clang and gcc: I'll always build both, only install the executable for the one compiled from c sources.
For libraries I'll always install both.

For msvc when I get to it I won't build from c sources, only from cxx sources.
