### ISSUE TITLE
[RFC] Simplified wrapdb

### ISSUE THREAD

**Issue by xclaesse** [mesonbuild/meson#8754]
I have been thinking and experimenting a bit with ways to improve our wrapdb workflow.

Current issues:
- The worflow to contribute new wraps requires manual steps that only @jpakkane can do (create new git repo, create releases).
- The namespace under github.com/mesonbuild/ is a mess with over a hundred projects.
- It requires running a (complex) python script server. It has to be hosted somewhere which has been an issue in the past. Even if it seems pretty stable now.
- For projects that has meson build system upstream we still have to create a git repo containing a single upstream.wrap file. Currently wrapdb force generating a patch tarball that contains erronous license file.

My proposal: https://github.com/xclaesse/wrapdb
- Move everything into a single git repository.
- All commits are preserved, I wrote a script that import git history from all individual repos we had.
- Contributing can be done with a simple PR, the CI takes care of creating release tarballs once merged. No more scripts manually run.
- All previous release tarballs have been imported, sha256 are still the same.
- No need of hosting a server, everything is just static files on github. However, we'll need to setup redirects to keep using https://wrapdb.mesonbuild.com domain.
- All wraps and their files are in `subprojects/` directory, so we can actually build them for testing.

Example workflow:
- Here is an example PR to add gtk4.wrap: https://github.com/xclaesse/wrapdb/pull/2
- When that PR has been merged, CI has run: https://github.com/xclaesse/wrapdb/runs/2546577289?check_suite_focus=true
- Release tag has been created automatically: https://github.com/xclaesse/wrapdb/releases/gtk_4.3.0-1
- Note that it does not contain a patch zip because upstream has meson build system already.

TODO:
- Change `meson wrap` command to use new system. We'll have keep old wrapdb server running for a while for people running older meson version.
- Add CI that actually build wrap subprojects, at least for those we can easily reproduce. It can be used for Meson RC validation maybe.

Needed redirects:
- Old patch URL must keep working, e.g. https://wrapdb.mesonbuild.com/v1/projects/zlib/1.2.11/5/get_zip -> https://github.com/xclaesse/wrapdb/releases/download/zlib_1.2.11-5/zlib_1.2.11-5_patch.zip
- We don't want to hardcode github.com URLs in meson. To access release list, we should add a redirect: https://wrapdb.mesonbuild.com/v2/releases.txt -> https://raw.githubusercontent.com/xclaesse/wrapdb/master/releases.txt.
- We don't want to hardcode github.com URLs in wrap files. To download patch zip files we should add a redirect: https://wrapdb.mesonbuild.com/v2/zlib_1.2.11-5/zlib_1.2.11-5_patch.zip -> https://github.com/xclaesse/wrapdb/releases/download/zlib_1.2.11-5/zlib_1.2.11-5_patch.zip

**Comment by jpakkane** [comment]
> Change meson wrap command to use new system.

What would this actually entail? Would it load its things from the wrapdb or directly from the Github url. The latter is not desirable as it is a big vendor lock-in think. Also we'll want to have a wrapdb web site as currently where people can browse available packages with a nicer UI than by spelunking inside Github repo pages.

**Comment by jpakkane** [comment]
Some random things that came to mind:

- that `releases.txt` file should probably have the provides info also somehow so you can do "which package provides libjpeg" type queries and find both libjpeg and libjpeg-turbo
- maybe JSON so we can add other stuff to it later if a use case presents itself
- CI should run the validation checks in `mesonwrap` as a prerequisite to merging
- Other endpoints like `meson wrap status` and `update` need to be supported

> I did not know we had a website for that, where is it?

Well, ... errr .... https://wrapdb.mesonbuild.com/

Granted, it could be snazzier, but even that beats Github repo browsing.

**Comment by xclaesse** [comment]
>     * that `releases.txt` file should probably have the provides info also somehow so you can do "which package provides libjpeg" type queries and find both libjpeg and libjpeg-turbo
> 
>     * maybe JSON so we can add other stuff to it later if a use case presents itself

I like the idea of having the `[provide]` section info available in that DB, it is something I've been thinking too, `dependency('glib-2.0')` could automatically tell you to run `meson wrap install glib` or even have a wrap_mode where it does it for you.

But to do that it means releases.txt would have to be generated by CI, but then...
- Where does the CI push the updated db? Can a CI itself make a new commit to update a file? That would be weird.
- Currently the CI detects the release it has to generate based on change in releases.txt that the PR does, but if that file is automatically generated, I'm not sure how the CI can tell which release to produce when a wrap file is modified. The wrap format could be modified to contain version/revision info. But that's more work.

What about:
- Change format to json because it's more future proof, we can easily add more info later, and it's still easy to hand write.
- Maintain the provide section manually for now.
- CI could validate that provide section match the wrap file.

Something like that?
```json
{
  'glib': {
    # Keep latest version first in list
    versions: ['2.68.0-2', '2.68.0-1', ...],
    provide: ['glib-2.0', ...],
  }
  'jpeg-turbo': {
    ...
  }
}
```

>     * CI should run the validation checks in `mesonwrap` as a prerequisite to merging

Yes that's definitely something we should do. Wanted to first agree on the solution before going further, because current system does not validate neither, so that's not a regression anyway.

>     * Other endpoints like `meson wrap status` and `update` need to be supported

Yes, that's pretty easy to do, just need to take info from `releases.txt` instead of using wrapdb server API.

> Well, ... errr .... https://wrapdb.mesonbuild.com/
> 
> Granted, it could be snazzier, but even that beats Github repo browsing.

Oh nice. Yeah, that's just a bit of HTML to expose the info from releases.txt if we extend it with json as suggested above. Wondering if that could be done with hotdoc somehow, to integrate better with mesonbuild.com.

**Comment by tp-m** [comment]
> Something like that?
> 
> ```js
> {
>   'glib': {
>     versions: ['2.68.0-2', '2.68.0-1', ...],
>     provide: ['glib-2.0', ...],
>   },
>   'jpeg-turbo': {
>   }
> }
> ```

Detail probably, but please make sure that the format can theoretically handle these things changing over time (e.g. different versions might contain different `provides`).

**Comment by xclaesse** [comment]
> Detail probably, but please make sure that the format can theoretically handle these things changing over time (e.g. different versions might contain different `provides`).

I initially thought about doing a map {version: provide} but I think it would be too verbose. IMHO it should be enough to only specify what the latest version provides.

**Comment by dcbaker** [comment]
I said it on IRC as well, but please use JSON (or TOML or YAML or …) not an ad hoc format called .txt (which usually means "A blob of text structured using natural language rules").

**Comment by xclaesse** [comment]
@dcbaker agreed, I'm changing that.

**Comment by tristan957** [comment]
Should a `version` string be separated out into version and release #?

**Comment by jpakkane** [comment]
I created a new repo: https://github.com/mesonbuild/wrapdb_v2test

This should be used to set up all CI confs et al for development. Once everything there is working we can do the switch. You should have all the necessary permissions to set it up. If not, let me know and I'll add them.

**Comment by xclaesse** [comment]
> I created a new repo: https://github.com/mesonbuild/wrapdb_v2test

Thanks, I ran the import script into that repo.

Notes:
- Release wraps now use https://wrapdb.mesonbuild.com/v2/<tag>/get_patch URL which redirects to github.
- I removed libjpeg because it is superseeded by libjpeg-turbo that works on Windows: https://github.com/mesonbuild/wrapdb_v2test/commit/00a53586b4c2ae90e27f039bc708c703eafe065c
- I removed sqlite because it was duplicated with sqlite3, not sure how we ended up with 3 wraps: https://github.com/mesonbuild/sqlite3/pull/1
- CI on pull requests does some sanity checks to ensure the releases.json and wrap files seems correct.
- post-merge CI will release new release tarballs.

**Comment by stephanlachnit** [comment]
> > Something like that?
> > ```js
> > {
> >   'glib': {
> >     versions: ['2.68.0-2', '2.68.0-1', ...],
> >     provide: ['glib-2.0', ...],
> >   },
> >   'jpeg-turbo': {
> >   }
> > }
> > ```
> 
> Detail probably, but please make sure that the format can theoretically handle these things changing over time (e.g. different versions might contain different `provides`).

What about:

```js
{
  'example-project': {
    provide: ['example-1.0', 'example-2.0', 'example-feature-2.0'],
    versions: {
      '2.1-1': {
        provide: ['example-2.0', 'example-feature-2.0'],
      },
      '2.0-2': {
        provide: ['example-2.0'],
      },
      '2.0-1': {
        provide: ['example-2.0'],
      },
      '1.0-1': {
        provide: ['example-1.0'],
      },
    },
  },
  'another-project': {
    provide: [...],
    versions: {...},
  },
}
```

The first provides lists all provides that appear in any version to make scanning for provides a bit easier (could also be removed technically), and versions still have their own provides section so that this can change over time. If it makes sense to do this is an entirely different question of course.

**Comment by tristan957** [comment]
or `versions: [{version: x, provides: y}]`

**Comment by jpakkane** [comment]
> CI on pull requests does some sanity checks to ensure the releases.json and wrap files seems correct.

Are these the same what `mesonwrap review` does? If not, they should be added, all of those checks are there because they were necessary.

Other than that, what does this still need for deployment? Does it need any changes in Meson itself?

Also, as an additional point, the readme says "DataBase", when the correct spelling would be "Database".

**Comment by mayl** [comment]
I'm quite excited to see this development.  Meson's dependency management foundation is already quite strong, and I think improving the usability of the `wrap-db` part of that is going to be a great development.

Hopefully this is not too derailing of a question, but do you think one of the outcomes of this will be that it's easier to self host a private or internal `wrap-db`?  I have use cases which we currently meet with `[wrap-git]` and `[wrap-file]` type dependencies but it would be nicer to be able to have users run `meson wrap add` against a self-hosted `wrap-db` vs manually searching for and copying `.wrap` files.  I know I _could_ self host the current `wrap-db`, but was always a little turned off by setting that up.  If that simplifies down to some static hosting and a CI job I personally would find that _very_ compelling!

Just 2c from a loyal Meson user, thanks for working on this I look forward to seeing where it ends up!

**Comment by jpakkane** [comment]
Having people run their own wrapdbs inside corporate firewalls is something we want to support. The main issues seem how to the collection of packages and the query API. The former is more work than the actual service API and the latter can not be done purely by static hosting (because otherwise you'd need to download the whole package list on a query).

**Comment by mayl** [comment]
I'm encouraged that running a private wrap-db is a desired use case!  

Just a couple related thoughts before I get out of the way:

I'm not fully versed in the internals, but I _believe_ APT works by downloading the package lists hosted [here](http://us.archive.ubuntu.com/ubuntu/).  Something on the scale of `wrap-db` might not be so bad to download a package list, especially if `meson` caches it.

There's also [this](https://phiresky.github.io/blog/2021/hosting-sqlite-databases-on-github-pages/) pretty cool technique for using `HTTP range` to query statically hosted `sqlite` databases but with a fraction of the traffic you might otherwise expect.  It'd be pretty cool to use that approach to allow static hosting of `wrap-db`'s but I also understand that re-implementing all that in `meson` to work with python's built in `sqlite` is probably a non-starter.

**Comment by xclaesse** [comment]
I never thought private wrapdb would be desired, weird use-case... but why not...

FWIW, this proposal is based on a static json file you download and contains all releases info. Yes if we ever get millions wraps that won't scale, but it's much easier and even faster at our current scale. Currently the json takes 20k, really not a problem. If it gets too big, we could also gzip and cache it on disk (like APT). But most importantly, if we ever reach that level of popularity, I would expect to also have gained more contributors who could design and maintain a more advanced system like crates.io.

With server side query like our current wrapdb, I am more concerned about server scalability, currently all requests goes through a single python app on a single machine... With a static json DB we have all of github datacenter power to deliver that file to millions users. Our own server only need to 403 redirect all queries on `wrapdb.mesonbuild.com`.

It's out of scope for this issue, but part of the larger plan is to have `dependency('something')` tell you it's in wrapdb if not found on the system, caching the DB locally would be needed IMHO if we want to be able to query for each not-found dependency lookup.

**Comment by mayl** [comment]
Maybe a bit weird yes, but also I don't think I'm the only one :)

I'm glad to hear that the current proposal would work with static hosting.  I think that sound simplest and agree with your take on the "scale-ability"  issue.  JSON also compresses very well - looks like the current database compresses down to 2.5k.
```
❯ du --apparent-size -h releases.*
19K	releases.json
2.5K releases.json.gz
```

**Comment by xclaesse** [comment]
> Are these the same what `mesonwrap review` does? If not, they should be added, all of those checks are there because they were necessary.

Didn't know about that command, I'll give it a look.

> Other than that, what does this still need for deployment? Does it need any changes in Meson itself?

Yes, https://github.com/mesonbuild/meson/pull/8796.

> Also, as an additional point, the readme says "DataBase", when the correct spelling would be "Database".

Fixed.

**Comment by xclaesse** [comment]
> > Are these the same what `mesonwrap review` does? If not, they should be added, all of those checks are there because they were necessary.
> 
> Didn't know about that command, I'll give it a look.

Done: https://github.com/mesonbuild/wrapdb_v2test/commit/56d54d6e4432bfaeef2c88becf37a553393e8cee
