### ISSUE TITLE
need an example(sample code) on how to use meson's devenv commad

### ISSUE THREAD

**Issue by nitinosiris** [mesonbuild/meson#8758]
I don't know how to use meson's devenv , so i need one example :)

**Comment by nitinosiris** [comment]
I want to use meson devenv for setting PATH, GI_TYPELIB_DIR, and LD_LIBRARY_PATH.

**Comment by nitinosiris** [comment]
don't know how to code for that :( thats why i need an example

**Comment by xclaesse** [comment]
You probably don't have anything to code:
- `GI_TYPELIB_DIR` is set automatically when using `gnome.generate_gir()`.
- `LD_LIBRARY_PATH` is set automatically to all places where you have an installed shared library.
- `PATH` is set automatically to all places where you have an installed executable.

Just type `meson devenv -C builddir`, and see the env that has been set for you.

**Comment by nitinosiris** [comment]
Ohh, okay .I will try it :) thanks!
