### ISSUE TITLE
is language agnostic the i18n module?

### ISSUE THREAD

**Issue by JeysonFlores** [mesonbuild/meson#8759]
Hi, I'm writing an app with moonscript and lua. I figured out how to compile the moonscript files into lua files and configure the shebang on the main script to be able to execute the app thru Luajit (After all there's documentation that teaches how to import non-supported compilers and run scripts) however I found almost no info about i18n with non-supported languages.

My wondering is if the i18n module is able to skimm thru all the files searching for _("some string") <- these kind of strings regardless of the programming language and replace the string with the translated one. It's my first time using Meson and all the examples I found are examples using C, C++ or Vala (which of course are supported languages)

**Comment by xclaesse** [comment]
As far as I know, the meson module is just a wrapper around gettex's msgfmt command. Seems to support LUA: https://www.gnu.org/software/gettext/manual/html_node/Lua.html.

**Comment by JeysonFlores** [comment]
I'll try it and make tests then. Thanks!
