### ISSUE TITLE
Missing CPU Family: csky

### ISSUE THREAD

**Issue by yatescr** [mesonbuild/meson#8770]
**Describe the bug**
Building an image under yocto produces an error:

randyy@Lubuntu-25316:build-csky-toolchain-kernel_5.12$ bitbake core-image-minimal -c populate_sdk
Loading cache: 100% |###############################################################################################################################################################################################################################################################################################| Time: 0:00:00
Loaded 1357 entries from dependency cache.
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION           = "1.48.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "universal"
TARGET_SYS           = "csky-poky-linux"
MACHINE              = "qemucsky"
DISTRO               = "poky"
DISTRO_VERSION       = "3.2.2"
TUNE_FEATURES        = " littleendian"
meta                 
meta-poky            
meta-yocto-bsp       
meta-csky            = "<unknown>:<unknown>"

Initialising tasks: 100% |##########################################################################################################################################################################################################################################################################################| Time: 0:00:01
Sstate summary: Wanted 730 Found 0 Missed 730 Current 463 (0% match, 38% complete)
NOTE: Executing Tasks
ERROR: xorgproto-2020.1-r0 do_configure: meson failed
ERROR: xorgproto-2020.1-r0 do_configure: Execution of '/edg/build-csky-toolchain-kernel_5.12/tmp/work/csky-poky-linux/xorgproto/2020.1-r0/temp/run.do_configure.18580' failed with exit code 1:

ERROR: Unknown CPU family csky, see https://wiki.yoctoproject.org/wiki/Meson/UnknownCPU for directions.
WARNING: exit code 1 from a shell command.

ERROR: Logfile of failure stored in: /edg/build-csky-toolchain-kernel_5.12/tmp/work/csky-poky-linux/xorgproto/2020.1-r0/temp/log.do_configure.18580
Log data follows:
| DEBUG: Executing python function extend_recipe_sysroot
| NOTE: Direct dependencies are ['/mnt/hdd/EDG/dachuan-research/gs500/poky/meta/recipes-core/glibc/glibc_2.32.bb:do_populate_sysroot', 'virtual:native:/mnt/hdd/EDG/dachuan-research/gs500/poky/meta/recipes-devtools/ninja/ninja_1.10.1.bb:do_populate_sysroot', 'virtual:native:/mnt/hdd/EDG/dachuan-research/gs500/poky/meta/recipes-devtools/patch/patch_2.7.6.bb:do_populate_sysroot', '/mnt/hdd/EDG/dachuan-research/gs500/poky/meta/recipes-devtools/gcc/gcc-runtime_10.3.bb:do_populate_sysroot', 'virtual:native:/mnt/hdd/EDG/dachuan-research/gs500/poky/meta/recipes-devtools/pseudo/pseudo_git.bb:do_populate_sysroot', '/mnt/hdd/EDG/dachuan-research/gs500/poky/meta/recipes-devtools/gcc/gcc-cross_10.3.bb:do_populate_sysroot', 'virtual:native:/mnt/hdd/EDG/dachuan-research/gs500/poky/meta/recipes-devtools/python/python3_3.8.5.bb:do_populate_sysroot', 'virtual:native:/mnt/hdd/EDG/dachuan-research/gs500/poky/meta/recipes-devtools/meson/meson_0.55.1.bb:do_populate_sysroot', '/mnt/hdd/EDG/dachuan-research/gs500/poky/meta/recipes-devtools/quilt/quilt-native_0.66.bb:do_populate_sysroot']
| NOTE: Installed into sysroot: []
| NOTE: Skipping as already exists in sysroot: ['glibc', 'ninja-native', 'patch-native', 'gcc-runtime', 'pseudo-native', 'gcc-cross-csky', 'python3-native', 'meson-native', 'quilt-native', 'linux-libc-headers', 're2c-native', 'libtool-native', 'attr-native', 'automake-native', 'autoconf-native', 'gnu-config-native', 'libgcc', 'util-linux-native', 'libffi-native', 'sqlite3-native', 'pkgconfig-native', 'libnsl2-native', 'xz-native', 'bzip2-native', 'zlib-native', 'openssl-native', 'gdbm-native', 'readline-native', 'libtirpc-native', 'python3-setuptools-native', 'flex-native', 'libmpc-native', 'binutils-cross-csky', 'mpfr-native', 'gmp-native', 'texinfo-dummy-native', 'gettext-minimal-native', 'm4-native', 'libpcre2-native', 'libcap-ng-native', 'ncurses-native', 'unzip-native']
| DEBUG: Python function extend_recipe_sysroot finished
| DEBUG: Executing shell function do_configure
| NOTE: Executing meson -Dlegacy=false...
| 
| ERROR: Unknown CPU family csky, see https://wiki.yoctoproject.org/wiki/Meson/UnknownCPU for directions.
| ERROR: meson failed
| WARNING: exit code 1 from a shell command.
| ERROR: Execution of '/edg/build-csky-toolchain-kernel_5.12/tmp/work/csky-poky-linux/xorgproto/2020.1-r0/temp/run.do_configure.18580' failed with exit code 1:
| 
| ERROR: Unknown CPU family csky, see https://wiki.yoctoproject.org/wiki/Meson/UnknownCPU for directions.
| WARNING: exit code 1 from a shell command.
| 
ERROR: Task (/mnt/hdd/EDG/dachuan-research/gs500/poky/meta/recipes-graphics/xorg-proto/xorgproto_2020.1.bb:do_configure) failed with exit code '1'
NOTE: Tasks Summary: Attempted 981 tasks of which 971 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /mnt/hdd/EDG/dachuan-research/gs500/poky/meta/recipes-graphics/xorg-proto/xorgproto_2020.1.bb:do_configure
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
randyy@Lubuntu-25316:build-csky-toolchain-kernel_5.12$ 

This occurs when the local.conf has MACHINE ??= "qemucsky" and the machine files specify DEFAULTTUNE ?= "csky". 
See e.g. the linux kernel arch/csky folder and https://c-sky.github.io/

**Comment by eli-schwartz** [comment]
Missing link to #8771
