### ISSUE TITLE
Detect MinGW host

### ISSUE THREAD

**Issue by albfan** [mesonbuild/meson#8776]
**Describe the bug**
Building under MinGW is a special case for windows so 

```
host_system = host_machine.system()
build_system = build_machine.system()
target_system = target_machine.system()
```

became insuficcient. All return `windows`

I see something related to platform `is_cygwin()` but not sure how to use it.

Adding an option to meson.build to manually build is the usual option, but is interesting for meson to detect MinGW?

I see some environments to detect it this way:

```
        {"win32unix",
#if defined(UNIX) && defined(__CYGWIN__)
```

**To Reproduce**
Build under MinGW is detected as windows.

**Expected behavior**
host_machine.system() returns mingw, winunix, cygwin or similar

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
Is MSYS2 (MinGW)
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
Windows 10
* what Python version are you using e.g. 3.8.0
```
$ python --version
Python 3.8.8
```
* what `meson --version`
```
$ meson --version
0.57.2
```
* what `ninja --version` if it's a Ninja build
```
$ ninja --version
1.10.2
```

**Comment by dcbaker** [comment]
The best you can really do right now is `host_machine.system() == 'windows' and meson.get_compiler('c').get_id() == 'gcc'`. This isn't perfect, but it does work in most cases. Cygwin is not identified as windows, so you don't have to worry about that.

**Comment by albfan** [comment]
Fair enough, don't think meson should be aware of any Frankenstein OS out there.
