### ISSUE TITLE
Cannot add include path for directory that exists only under build directory

### ISSUE THREAD

**Issue by mcatanzaro** [mesonbuild/meson#879]
func_include_directories in interpreter.py checks to be sure an include directory actually exists, and fails if not. But it checks only the source directory. This makes it awkward to add include paths for a directory that exists only as a subdirectory of the build directory, not the source directory. See, for instance, https://github.com/grindhold/libhttpseverywhere/pull/11/files which works around this by creating an unnecessary empty subdirectory inside the source directory, along with a little README file to explain this oddity (also because git doesn't allow committing empty directories).

Is this a meson bug? If not, what's the recommended approach to avoid this? We could just not generate files in this subdirectory, I suppose.

(@grindhold)

**Comment by ignatenkobrain** [comment]
I commented original pull request which probably should do the trick. basically when you do include_directories() it will include directory relative to the current source directory. So if you want to include builddir, then you have to specify this.

**Comment by ignatenkobrain** [comment]
Notabug. https://github.com/grindhold/libhttpseverywhere/commit/a8f008839658cbf44ee91055c6f24dcc20b2a0ce

**Comment by mcatanzaro** [comment]
It would be good to improve the documentation here, though.
