### ISSUE TITLE
Little Change.

### ISSUE THREAD

**Issue by jakobneufeld** [mesonbuild/meson#8797]
This may seem stupid, but when I look on the meson homepage, it says Rust as a supported language although, the rust module is unstable.
 
I am quite new to meson, so you can scream at me, if I am wrong :-)

**Comment by dcbaker** [comment]
Meson has two sepearate thing, support for compiling Rust targets, which is stable (though there were a lot of bugs before 0.57), you can achieve that with
```meson
exe = executable('name', 'main.rs')
```
or
```meson
lib = library('lib', 'lib.rs')
```

The module provides helpers to make some tasks in Rust easier. Currently, that means a convenience method for `bindgen` and a convenience method for building a target as a unit test.

All modules enter Meson as "unstable", this means that we can make backward incompatible API changes if necessary, and you've been warned you may have to do some `if meson.version() < x.y` checks if you use them.

I wrote that module, I don't expect the either of those functions to change in a backwards incompatible way.

**Comment by jakobneufeld** [comment]
Ahh, thanks so much. Sorry for wasting your time. Should I close the issue?

**Comment by dcbaker** [comment]
No worries, our documentation isn't always the best :)

I'll go ahead and close it.
