### ISSUE TITLE
yelp support

### ISSUE THREAD

**Issue by zeenix** [mesonbuild/meson#881]
To make it easy to port GNOME modules from autotools to meson, it'll be nice to have some convenience from meson for building/installing user help pages.

**Comment by TingPing** [comment]
I'll be needing this soon on my port of gnome-builder so I'll look into it.

**Comment by shaunix** [comment]
For reference, here's the M4 file that provides the autotools build rules we use:

https://git.gnome.org/browse/yelp-tools/tree/tools/yelp.m4

And here's some docs on how to use it:

http://yelp.io/tools/yelp.m4

Happy to help out on this if someone can give me some pointers.

**Comment by TingPing** [comment]
I think we would largely be duplicating the logic the [gnome.gtkdoc()](https://github.com/mesonbuild/meson/blob/b6b8d561b84eb950d1503e682ca2eab3b656efa9/mesonbuild/modules/gnome.py#L369-L418) function uses which has an install helper [gtkdochelper.py](https://github.com/mesonbuild/meson/blob/b6b8d561b84eb950d1503e682ca2eab3b656efa9/mesonbuild/scripts/gtkdochelper.py).

On top of that it doesn't integrate with normal translations so either we could reuse the [gettext.py](https://github.com/mesonbuild/meson/blob/b6b8d561b84eb950d1503e682ca2eab3b656efa9/mesonbuild/scripts/gettext.py) install helper or just duplicate part of that. Might have to expose a few extra targets to help manage these.

The api for it should be fairly simple like:

```python
gnome.yelp('your-id',
   sources: ['index.page', 'something.page],
   media: ['something.png'],
   languages: ['es', 'de'],
   install: true,
)
```

**Comment by TingPing** [comment]
@shaunix On a slightly unrelated note, could upstream yelp install an its file into `/usr/share/gettext/its` so in the future it *just works* with `xgettext`?

**Comment by TingPing** [comment]
Initial work on this is here: https://github.com/mesonbuild/meson/tree/wip/tingping/gnome-yelp
