### ISSUE TITLE
I want to use llvm-config-11 and how to tell meson? by some env?

### ISSUE THREAD

**Issue by ffgpu-org** [mesonbuild/meson#8816]
Hi, forks!
  There are some llvm version installed on my machine. (llvm-config llvm-config-10 llvm-config-11) The llvm-config soft link to llvm-config-10. I do not have permission to change this link to llvm-config-11.
  Is there any way to tell meson I want to use llvm-config-11 not the llvm-config. 
  LLVM_CONFIG env not work.

**Comment by dcbaker** [comment]
meson does this with configurations files:
```ini
[binaries]
llvm-config = '/usr/bin/llvm-config-11'
```
if that file is called `machine.ini`, then

```console
meson build --native-file machine.ini ${other_args}
```
should do what you want.

**Comment by ffgpu-org** [comment]
> meson does this with configurations files:
> 
> ```ini
> [binaries]
> llvm-config = '/usr/bin/llvm-config-11'
> ```
> 
> if that file is called `machine.ini`, then
> 
> ```
> meson build --native-file machine.ini ${other_args}
> ```
> 
> should do what you want.

Thans a lot! It works.

**Comment by dcbaker** [comment]
no problem!
