### ISSUE TITLE
'meson scan-build' is broken

### ISSUE THREAD

**Issue by mcatanzaro** [mesonbuild/meson#8818]
**Describe the bug**
From #8707, `meson scan-build` is broken since https://github.com/mesonbuild/meson/commit/e81acbd6069e8c1ae8e3be7bb83ddc239009d42d. ~~This commit should be reverted.~~ Sorry, I see the regression from that commit was already fixed, and the real commit that introduced this bug is hidden by that one....

**To Reproduce**
See #8707

**Expected behavior**
See #8707

**system parameters**
See #8707

**Comment by mcatanzaro** [comment]
[freedesktop-sdk tracking issue here](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1258)

**Comment by jpakkane** [comment]
Can you test #8823?

**Comment by mcatanzaro** [comment]
Yup, thanks!

**Comment by mcatanzaro** [comment]
I tested #8823 and found it fixed #8707, making it finally possible to debug this issue. The error is:

```
Build started at 2021-06-02T12:16:03.129061
Main binary: /usr/bin/python3
Build Options: -Dauto_features=auto -Db_asneeded=true -Db_colorout=always -Db_coverage=false -Db_lto=false -Db_lto_threads=0 -Db_lundef=true -Db_ndebug=false -Db_pch=true -Db_pgo=off -Db_pie=false -Db_sanitize=none -Db_staticpic=true -Dbackend=ninja -Dbackend_max_links=0 -Dbindir=bin '-Dbuild.c_args=[]' '-Dbuild.c_link_args=['"'"'-l/app/lib'"'"']' -Dbuild.c_std=gnu11 '-Dbuild.cmake_prefix_path=[]' '-Dbuild.pkg_config_path=['"'"'/app/lib/pkgconfig'"'"', '"'"'/app/share/pkgconfig'"'"', '"'"'/usr/lib/pkgconfig'"'"', '"'"'/usr/share/pkgconfig'"'"']' -Dbuildtype=debug '-Dc_args=[]' '-Dc_link_args=['"'"'-l/app/lib'"'"']' -Dc_std=gnu11 '-Dcmake_prefix_path=[]' -Ddatadir=share -Ddebug=true -Ddefault_library=shared -Ddeveloper_mode=false -Derrorlogs=true '-Dforce_fallback_for=[]' -Dgsb_api_key= -Dincludedir=include -Dinfodir=share/info -Dinstall_umask=0o22 -Dlayout=mirror -Dlibdir=lib64 -Dlibexecdir=libexec -Dlibportal=enabled -Dlocaledir=share/locale -Dlocalstatedir=/var/local -Dmandir=share/man -Dnetwork_tests=disabled -Doptimization=0 '-Dpkg_config_path=['"'"'/app/lib/pkgconfig'"'"', '"'"'/app/share/pkgconfig'"'"', '"'"'/usr/lib/pkgconfig'"'"', '"'"'/usr/share/pkgconfig'"'"']' -Dprefix=/usr/local -Dprofile= -Dsbindir=sbin -Dsharedstatedir=/var/local/lib -Dsoup2=enabled -Dstdsplit=true -Dstrip=false -Dsysconfdir=etc -Dtech_preview=false -Dunit_tests=enabled -Dunity=off -Dunity_size=4 -Dwarning_level=2 -Dwerror=false -Dwrap_mode=default
Python system: Linux
The Meson build system
Version: 0.58.999
Source dir: /home/mcatanzaro/Projects/epiphany
Build dir: /home/mcatanzaro/Projects/epiphany/_build/meson-private/tmpvonnb57r
Build type: native build
Project name: epiphany
Project version: 40.0
Sanity testing C compiler: /usr/bin/../libexec/ccc-analyzer
Is cross compiler: False.
Sanity check compiler command line: /usr/bin/../libexec/ccc-analyzer sanitycheckc.c -o sanitycheckc.exe -D_FILE_OFFSET_BITS=64 -l/app/lib
Sanity check compile stdout:

-----
Sanity check compile stderr:
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -l/app/lib
collect2: error: ld returned 1 exit status

-----

../meson.build:1:0: ERROR: Compiler /usr/bin/../libexec/ccc-analyzer can not compile programs.
```

Ouch, that explains why I was unable to reproduce outside flatpak. Of course /app does not exist in the flatpak build environment, it only exists in the final runtime environment....

**Comment by mcatanzaro** [comment]
Let me see how hard it is to do a bisect between e81acbd and f31ffaa, with e81acbd reverted to avoid hitting the "invalid literal for int() with base 8: '18'" issue. If there aren't difficult conflicts, then that should reveal which commit is to blame....

**Comment by mcatanzaro** [comment]
> Let me see how hard it is to do a bisect between e81acbd and f31ffaa, with e81acbd reverted to avoid hitting the "invalid literal for int() with base 8: '18'" issue. If there aren't difficult conflicts, then that should reveal which commit is to blame....

Too many conflicts. I will leave this for meson developers, sorry.

**Comment by nanonyme** [comment]
@mcatanzaro so is the issue here `-l/app/lib` instead of `-L/app/lib`?

**Comment by nanonyme** [comment]
In other words, we probably want /app/lib added to search path, not being declared as a lib to link against.

**Comment by mcatanzaro** [comment]
Oh wow, probably yes. I didn't even notice that.

**Comment by nanonyme** [comment]
So is this user error or Meson error?

**Comment by mcatanzaro** [comment]
> So is this user error or Meson error?

Meson error. I cherry-picked 4cd062a4d96a814804c2c4796159116ef9febb0e onto the last non-broken commit, 71db6b04a31707674ad776be1cf22f667056d56b, and got this log demonstrating meson's previous behavior:

```
Build started at 2021-06-13T18:48:59.067115
Main binary: /usr/bin/python3
Build Options: -Ddeveloper_mode=false -Dgsb_api_key= -Dlibportal=enabled -Dnetwork_tests=disabled -Dprofile= -Dsoup2=enabled -Dtech_preview=false -Dunit_tests=enabled
Python system: Linux
The Meson build system
Version: 0.56.99
Source dir: /home/mcatanzaro/Projects/epiphany
Build dir: /home/mcatanzaro/Projects/epiphany/_build/meson-private/tmpw_ljqqmy
Build type: native build
Project name: epiphany
Project version: 40.0
Using 'CC' from environment with value: '/usr/bin/../libexec/ccc-analyzer'
None of 'CFLAGS' are defined in the environment, not changing global flags.
Using 'LDFLAGS' from environment with value: '-L/app/lib '
None of 'CPPFLAGS' are defined in the environment, not changing global flags.
None of 'CC_LD' are defined in the environment, not changing global flags.
Sanity testing C compiler: /usr/bin/../libexec/ccc-analyzer
Is cross compiler: False.
None of 'CC_LD' are defined in the environment, not changing global flags.
Sanity check compiler command line: /usr/bin/../libexec/ccc-analyzer /home/mcatanzaro/Projects/epiphany/_build/meson-private/tmpw_ljqqmy/meson-private/sanitycheckc.c -o /home/mcatanzaro/Projects/epiphany/_build/meson-private/tmpw_ljqqmy/meson-private/sanitycheckc.exe -pipe -D_FILE_OFFSET_BITS=64 -L/app/lib
Sanity check compile stdout:
```

Notice there is no -l/app/lib anywhere, but plenty of -L/app/lib. I also notice that the build options line used to be much simpler than it is now.

**Comment by nanonyme** [comment]
@mcatanzaro it shows `-Dbuild.c_link_args=['"'"'-l/app/lib'"'"']'` at the end there. Where is this coming from? It has absolutely crazy amount of quoting in addition to having clearly wrong flag.

**Comment by mcatanzaro** [comment]
> it shows `-Dbuild.c_link_args=['"'"'-l/app/lib'"'"']'` at the end there in your first paste. Where is this coming from? It has absolutely crazy amount of quoting in addition to having clearly wrong flag.

That is coming from meson itself. After the bad revision, it adds that nonsense flag when it internally invokes itself to run scan-build. There are no changes to my environment between the logs I've shown above other than meson version.

**Comment by nanonyme** [comment]
@jpakkane does this contain enough information for Meson upstream to debug further or is a more fine-grained reproducer necessary?

**Comment by mcatanzaro** [comment]
Please note that if not fixed soon, freedesktop-sdk 21.08 (and therefore both GNOME 41 and GNOME 42) will likely ship with meson 0.56 instead of the latest and greatest.

> does this contain enough information for Meson upstream to debug further or is a more fine-grained reproducer necessary?

I can explain how to test things under flatpak if needed, but nothing else should be necessary as the reproducer is simply `meson scan-build` with any project.

**Comment by dcbaker** [comment]
I've gone ahead and added this to the 0.59 release blockers

**Comment by dcbaker** [comment]
@mcatanzaro what's the command line being passed to the original Meson invocation?

**Comment by dcbaker** [comment]
never mind, I know what's happening

**Comment by dcbaker** [comment]
@mcatanzaro can you test the linked PR and see if that fixes the issue for you?

**Comment by mcatanzaro** [comment]
> what's the command line being passed to the original Meson invocation?

From a build directory under the source directory: ` meson ..`. That's it. Followed by `ninja scan-build`.

The complexity here is that the bug apparently only occurs under flatpak, which we didn't realize at first....

> I can explain how to test things under flatpak if needed, but nothing else should be necessary as the reproducer is simply meson scan-build with any project.

I actually found a _much_ easier way to reproduce: fenv. This is an amazing tool, it's like jhbuild or toolbox, but for flatpak. To install fenv:

```
$ git clone https://gitlab.gnome.org/bilelmoussaoui/fenv.git
$ cd fenv
$ cargo build
$ cargo install --path .
```

At this point, I would rercommending adding ~/.cargo/bin to $PATH and restarting your shell.

The clone source code for some flatpak-based project that uses meson, and generate an fenv project using its flatpak manifest:

```
$ git clone https://gitlab.gnome.org/GNOME/epiphany.git
$ fenv gen epiphany/org.gnome.Epiphany.json
```

This will take a while to build.

Create build directory:

```
$ mkdir -p epiphany/_build
$ cd epiphany/_build
```

Set up `f` alias:

```
$ alias f="fenv exec --"
```

Now we have the flatpak environment all nicely set up, we can reproduce the bug:

```
$ f meson ..
$ f ninja scan-build
```

That will succeed, but only because the runtime was downgraded to meson 0.56.2. Let's delete and recreate the build directory, then try again with our own meson. We can use `meson setup --wipe` to clean the build directory for use with a different version of meson:

```
$ git clone https://github.com/mesonbuild/meson
$ f meson/meson.py setup --wipe ..
$ f ninja scan-build
```

Watch it fail (with the errors I posted above).

If you `git checkout 0.56.2` and repeat, it will succeed:

```
$ pushd meson
$ git checkout 0.56.2
$ popd
$ f meson/meson.py setup --wipe ..
$ f ninja scan-build
```

All good with 0.56.2!

**Comment by mcatanzaro** [comment]
>  can you test the linked PR and see if that fixes the issue for you?

Um yes. Done. Confirmed fixed. Nice, thanks!

Seems I wasted a lot of time typing up this intro to fenv, but that's fine.

**Comment by alatiera** [comment]
> Seems I wasted a lot of time typing up this intro to fenv, but that's fine.

It's alright, I am going to steal this for docs!
