### ISSUE TITLE
Rapid process creation when using generated file without first importing its library

### ISSUE THREAD

**Issue by IsaccBarker** [mesonbuild/meson#8850]
We have a program nettool. Foo relies of ProtoBuf. Nettool has the following generator to compile their .proto files:
```meson
proto_gen = generator(python3,
  output : ['@BASENAME@.pb.cc', '@BASENAME@.pb.h'],
  arguments : [join_paths(meson.source_root(), 'scripts', 'protoc'), # Call the wrapper
    meson.current_build_dir(), '@BASENAME@.pb.cc', # Give the warpper the info it needs
    '--proto_path=.', '--cpp_out=.', '@INPUT@'] # Pass it to the actual compiler
)

foo_gened = proto_gen.process('foo.proto')
```
The nettool executable then includes _foo_gened_ as a source. However, the author of nettool forgot to include _protobuf_dep_ as a dependency. As such, when building, it will stop at a seemingly random file, and start a lot of python processes (why I do not know). This file will _never_ compile. However, if you include _protobuf_dep_ then it will build just fine. This issue is not solved by using a single core.

The expected behaviour would be a message stating that something is wrong, not a system-crashing memory nightmare.

*System Specifications*
**Plain native build
Arch Linux 5.10.32-1-lts
Python 3.9.3
Meson 0.58.1
Ninja 1.10.2**

**Comment by IsaccBarker** [comment]
If you need the full code tree (where I first came across this issue), you can find it [here](https://github.com/IsaccBarker/CATNET/tree/fix-%2340), on the fix-#40 branch. Not sure if this is needed though. You can see the dependency list in _src/build.meson_ and the generator in _src/protot/build.meson_

**Comment by eli-schwartz** [comment]
Given that you quickly closed this issue yourself, can I assume you determined it was invalid?

**Comment by IsaccBarker** [comment]
Yeah. I noticed that I thought I had solved the issue, but I had accidentally commented out an entire line that stopped _foo.proto_ from compiling. Just got back from school, and I plan to create a new issue.

**Comment by eli-schwartz** [comment]
You're welcome to update this one, even.
