### ISSUE TITLE
Adding "--wrap-mode=forcefallback"  has no effect on a reconfigure

### ISSUE THREAD

**Issue by dabrain34** [mesonbuild/meson#8858]
**Describe the bug**
The project has been configured **without** `--wrap-mode=forcefallback` and after calling `meson build_dir --reconfigure --wrap-mode=forcefallback`, the fallback mode is not taken into account.

**To Reproduce**
in gst-build, start with the vanilla build:
```
$ meson build_dir
```
Then try to regenerate the build with 
```
meson build_dir --reconfigure --wrap-mode=forcefallback
````
The fallback are not used by the configure.

**Expected behavior**
To use the fallback instead of the system.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
  * no
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
  * Ubuntu
* what Python version are you using e.g.
  *  3.6.9
* what `meson --version`
  * 0.58.0
* what `ninja --version` if it's a Ninja build
  * 1.8.2

**Comment by xclaesse** [comment]
From a quick test it worked for me. Do you have more specific steps to reproduce?

**Comment by dabrain34** [comment]
I took a clean gst-build/master on docker Ubuntu 18.04, configure and build it, then I got this [issue](https://gitlab.freedesktop.org/gstreamer/gst-build/-/issues/166#note_951565) so I tried to reconfigure with `--wrap-mode=forcefallback`

I just gave it a try again with gst-build and I can reproduce with only the configure step:

Where there is much less subprojects to build with this steps:

```
$ meson build_dir
$ meson build_dir --reconfigure --wrap-mode=forcefallback
```
or

```
$ meson build_dir --wrap-mode=forcefallback
```

Same with master

**Comment by xclaesse** [comment]
Can you please attach logs in both cases so we can compare what differ?

**Comment by dabrain34** [comment]
```
$ meson build_dir --wrap-mode=forcefallback
```
[meson-log.txt](https://github.com/mesonbuild/meson/files/6630018/meson-log.txt)

```
$ meson build_dir 
$ meson build_dir --reconfigure --wrap-mode=forcefallback
```
[meson-log-reconfigure.txt](https://github.com/mesonbuild/meson/files/6630031/meson-log-reconfigure.txt)

**Comment by xclaesse** [comment]
ahh, I see, the problem is meson has a on-disk cache for dependencies lookups, to speed-up reconfigure. That bypass forcefallback.

**Comment by xclaesse** [comment]
@dabrain34 can you give a try to https://github.com/mesonbuild/meson/pull/8865 please?

**Comment by dabrain34** [comment]
working on my side
