### ISSUE TITLE
Force overwrite intermediate files when a source file is shared across multiple 'executable' ?

### ISSUE THREAD

**Issue by rivetchip** [mesonbuild/meson#8862]
**Describe the bug**

Using Meson and GCC on a personnal C11 project with GTK/GLib on Linux Fedora, I keep randomly getting the following error when compiling : 

```log
movie.s: Assembler messages:
movie.s:6916: Error: no such instruction: `te.gnu-stack,"",@progbits'
ninja: build stopped: subcommand failed.
```

After inspecting the faulty file, the generated ASM ending is malformed  : 

```asm
....

.LASF52:
    .string "GClassInitFunc"
    .ident  "GCC: (GNU) 10.3.1 20210422 (Red Hat 10.3.1-1)"
    .section    .note.GNU-stack,"",@progbits
te.GNU-stack,"",@progbits
```

As you can see the last line is at fault :

```asm
te.GNU-stack,"",@progbits
```

**To Reproduce**

I have two `executable` with different dependencies sharing a common file `movie.c`

```meson
depgtk = dependency('gtk4', version: '>= 4.0', required: true)
depglib = dependency('glib-2.0', version: '>= 2.66', required: true)
depgio = dependency('gio-2.0', version: '>= 2.66', required: true)
deplibcurl = dependency('libcurl', version : '>= 7.71', required: true)
```

- `main.c` dependencies : glib, gtk
- `movie.c` dependencies : gio
- `convert.c` dependencies : glib, gio

```meson
executable('app',
    sources: [
        'main.c',
        'movie.c',
    ],
    dependencies: [depglib, depgtk, deplibcurl],
)

executable('convert',
    sources: [
        'convert.c',
        'movie.c',
    ],
    dependencies: [depglib, depgio],
)
```

My guess is Meson only write onto the file and don't overwrite/replace it, so if the previous file is 100 lines and Meson had to write 90 lines, the last 10 will still be present.

Is this how Meson work internally ? 

**How to resolve**

Including the same dependencies for each `executable` seems to solve the problem, but obviously I don't want to include all dependencies to every project :smiley: 

**Expected behavior**

- Intermediates fiels to be completely overwritten 
- or if possible output intermediates files in different directories (example: `build/app1` for `executable('app1')`, `build/app2` for `executable('app2')`, etc )

**system parameters**
* Build : plain native build
* operating system : Linux Fedora 33 x86_64
* Python version  : Python 3.9.5
* Meson version : 0.58.1
* Ninja version : 1.10.2
* GCC version : 10.3.1 20210422 (Red Hat 10.3.1-1) (GCC) 

Thanks everyone ! :smiley:

**Comment by jpakkane** [comment]
Meson does not generate .s files. It only tells gcc & co to compile and link. That would indicate that the problem is not in Meson but rather in the toolchain itself.

Further, all intermediate files (object files and others if needed) are written to a target-unique directory.

**Comment by rivetchip** [comment]
> Meson does not generate .s files. It only tells gcc & co to compile and link. That would indicate that the problem is not in Meson but rather in the toolchain itself.

As I use GCC compiler, you suggest sending an issue to GCC directly ? 

> Further, all intermediate files (object files and others if needed) are written to a target-unique directory.

That's what I thought, thanks for your reply!

**Comment by eli-schwartz** [comment]
Does the error occur if you run ninja -j1 to prevent parallel compilation?

If you run ninja -v and check the generated command lines being executed, can you manage to reproduce the error by running gcc on your own without meson or ninja?

**Comment by rivetchip** [comment]
@eli-schwartz 
> Does the error occur if you run ninja -j1 to prevent parallel compilation?

The problem does not seems to occur with "-j1" option.

On the contrary : `ninja` without "-j1" option, sometimes trigger the error (but not always, around 3 to 4 times out of 10 tries). As you said, could be parallel compilation involved.

> If you run ninja -v and check the generated command lines being executed, can you manage to reproduce the error by running gcc on your own without meson or ninja?

Yes, `cc` (GCC in this case) compile just fine too.

**Comment by eli-schwartz** [comment]
If it's related to parallel compilation (only reproducible with ninja -j > 1) then my guess is on somehow gcc is writing the same tempfile for both compiler invocations. Which seems odd because I wouldn't assume that's how it would work.

**Comment by rivetchip** [comment]
> If it's related to parallel compilation (only reproducible with ninja -j > 1) then my guess is on somehow gcc is writing the same tempfile for both compiler invocations. Which seems odd because I wouldn't assume that's how it would work.

After some research with inotify / strace, found out it was GCC "-save-temps" option causing the issue (ironically need this to debug the ASM output); Anyway, when compiling with `meson compile`, option "-j1" is mandatory if "-save-temps" is enabled.

@eli-schwartz  Thanks for your time, really appreciate it! :heart: 

I think we can close here.

**Comment by eli-schwartz** [comment]
To be honest this should actually work fine. I think the default value for -save-temps is -save-temps=obj not -save-temps=cwd. See also -dumpdir.

One way or another, you should be able to have both.
