### ISSUE TITLE
default language is 'cs' on almost empty project

### ISSUE THREAD

**Issue by alex-tee** [mesonbuild/meson#8872]
**Describe the bug**
Meson seems to think that a project with just a COPYING and a README.md file is a C# project

**To Reproduce**
create a directory in `/tmp/aa` with the following files only:

README.md
```
# title

Paragraph
```

COPYING
```
test
```

then do `meson init .` and the language meson uses is `'cs'`:
```
Using "aa" (name of current directory) as project name.
Using "aa" (project name) as name of executable to build.
Detected language: cs
Generated meson.build file:

project('aa', 'cs',
  version : '0.1',
  default_options : ['warning_level=3'])

executable('aa',
           '.',
           install : true)
```

**Expected behavior**
Since no language is currently used in the project use the default (`'c'`)

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? N/A
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) Parabola (Arch Linux based)
* what Python version are you using Python 3.9.5
* what `meson --version`   0.58.1
* what `ninja --version` if it's a Ninja build 1.10.2

**Comment by eli-schwartz** [comment]
Your actual problem is you tried to tell `meson init` to consider the regular file `.` as a source file.

The linked PR stops detecting the regular file `.` or `foo.` or `s` or `c` as C#, and you'll then correctly get this error:

```
$ /home/eschwartz/git/meson/meson.py init .
Using "aa" (name of current directory) as project name.
Using "aa" (project name) as name of executable to build.
Can't autodetect language, please specify it with -l.
```
