### ISSUE TITLE
gnome.generate_gir incorrectly filters clang cflags like -W , passed to g-ir-scanner, and gcc fails

### ISSUE THREAD

**Issue by bootchk** [mesonbuild/meson#8876]
**Describe the bug**

The symptom is that, using clang, meson calls g-ir-scanner which calls gcc which fails with something like

```
 "gcc: error: unrecognized command-line option ... -Wsometimes-unitialized"
 ```

 It seems that gnome.generate_gir is passing clang specific c flags to generate warnings, but g-ir-scanner calls gcc,
 and gcc fails, not recognizing flags specific to clang compiler.

**To Reproduce**

The case is a meson build of the GIMP app v2.99, using clang, on Linux, Alpine or Ubuntu.

**Analysis and suggested fix**

In the code for gnome.generate_gir there is this:

```
def _get_scanner_cflags(cflags):
        'g-ir-scanner only accepts -I/-D/-U; must ignore all other flags'
        for f in cflags:
            if f.startswith(('-D', '-U', '-I')):
                yield f
```

So it seems that the intent is to filter out all the -W flags.

But later:

```
        cflags, internal_ldflags, external_ldflags = self._get_langs_compilers_flags(state, langs_compilers)
        ...omitted...
        dep_cflags, dep_internal_ldflags, dep_external_ldflags, gi_includes = \
            self._get_dependencies_flags(deps, state, depends, use_gir_args=True)
        cflags += list(self._get_scanner_cflags(dep_cflags))
```

In the above, cflags is initially an unfiltered list of cflags, and then the code appends more cflags
that are filtered by calls to _get_scanner_cflags().

I believe a fix is to add one line like so:

```
cflags, internal_ldflags, external_ldflags = self._get_langs_compilers_flags(state, langs_compilers)
cflags = list(self._get_scanner_cflags(cflags))
```

That is, immediately filter the initial contents of the variable cflag.

I tested this fix minimally, only to build GIMP.
The meson build of GIMP is "experimental", not used for releases.

**Comment by dcbaker** [comment]
That seems like a bug, it also seems like a bug that we're letting g-ir-scanner call GCC when Meson is using Clang for compilation. That might work out with GCC and clang (though I can come up with case that it wouldn't work)

**Comment by bootchk** [comment]
There are threads discussing the desire for g-ir-scanner to take a "compiler" argument so that the caller can explicitly say which compiler to use.  Loosely speaking, about the fact that g-ir-scanner (another Python program) uses the environment variable "CC" but meson doesn't set it and discourages relying on env variables.  Also about that g-ir-scanner uses disutils, which is falling out of favor or support, so its not ideal to use it.  Sorry to be fuzzy, I might be able to provide links.

Also, it might not be working, as you suggest.  Today I am trying to debug Python code that calls introspected GIMP, but simply crashes at the first introspected call ( in Python, the call is simply Gimp.version() )   The Python code seemed to work when gcc compiled GIMP and g-ir-scanner called gcc.  So the case that is not working is when clang compiled GIMP and g-ir-scanner calls gcc.  Its almost beyond my competency, so maybe I will just stop trying to use clang.

**Comment by dcbaker** [comment]
@nirbheek  or @xclaesse I think are the two most knowledgeable about this code, I only have a superficial knowledge unfortunately.

In *most* (almost every case) mixing GCC and clang will work fine, the cases I know where you can run into problems is with LTO (link time optimization) because each compiler inserts its own compiler specific information into the object files. It may still all work, but the linker my silent decide not to optimize. Having a `--compiler=` option would indeed solve that issue though.

**Comment by ebassi** [comment]
I've opened [an MR for gobject-introspection](https://gitlab.gnome.org/GNOME/gobject-introspection/-/merge_requests/281) that adds a `--compiler` command line to g-ir-scanner. Hopefully, it'll be available in the next gobject-introspection release in September.

**Comment by ebassi** [comment]
Just as a note: yes, the correct fix is `cflags = list(self._get_scanner_cflags(cflags))`—i.e. not to append the filtered list of compiler flags to the original compiler flags, but replace it entirely.

It would be nice if @bootchk could open a pull request with the fix, as I'm not sure @xclaesse and @nirbheek have the time to work on it.

**Comment by ebassi** [comment]
Well, turns out I had a few minutes to look at the code, and that we're also passing the linker flags unmodified, so I ended up opening #9041 with a full fix.

**Comment by cgrzemba** [comment]
It would desirable to pass here -m64(-m32) option too. On some platforms and eg. gcc 7 the compiler will still produce 32bit code if option -m64 is not set.

**Comment by ebassi** [comment]
@cgrzemba Please open a new issue, or a merge request.

**Comment by cgrzemba** [comment]
I have created #10875
