### ISSUE TITLE
Add load_file() function

### ISSUE THREAD

**Issue by ManuelAtWork** [mesonbuild/meson#8881]
We have a code generator that outputs

- A bunch of .c/.h files.
- An index.txt of all generated files.

The code generator is run before Meson is invoked. In our ```meson.build```, we load the index.txt into memory and create a list of source files:
```
if build_machine.system() == 'windows'
	kcg_files_txt = run_command('cmd', '/C type @0@'.format(join_paths(meson.source_root(), 'src/scade_application/kcg_files.txt').replace('/','\\'))).stdout().strip().split('\n')
else
	kcg_files_txt = run_command('cat', files('src/scade_application/kcg_files.txt')).stdout().strip().split('\n')
endif
```
This is platform dispatching written in Meson language. Python should have a portable way of loading files into memory. Could I have a function that loads a text file into a string variable please?

**Comment by mensinda** [comment]
This should already be possible with the [FS module](https://mesonbuild.com/Fs-module.html#read).

**Comment by ManuelAtWork** [comment]
Thank you for the quick answer! It works nicely.

I have added an [answer to the corresponding question](https://stackoverflow.com/a/67974123/4792058) on stackoverflow.
