### ISSUE TITLE
0.35.0 ignores a custom target.

### ISSUE THREAD

**Issue by grindhold** [mesonbuild/meson#890]
after patching my usual [buildscript](https://github.com/grindhold/libhttpseverywhere/blob/master/meson.build) with a quickfix, so the "Argument must be string"-bug of 0.35.0 doesn't trigger, i noticed that my custom target `apidocs` won't build.
it does however if i enter ```ninja devhelp```

in 0.34.0 the target builds on a regular ```ninja``` call, which is what i expect.

**Comment by nirbheek** [comment]
Do you mean `ninja apidocs`? This is because right now Meson thinks that it's not being used at all, since the output of that `custom_target` is not installed anywhere or used in any targets that are installed anywhere.

Looking at your build file, this is because you're using `install_subdir` to install the api docs from the build directory instead of using the `install` kwarg on `custom_target`.

**Comment by grindhold** [comment]
it won't work that straightforward, as valadoc outputs sth like '<outputdir>/<modulename>/<modulename> and meson tells me that i cannot have path segments in the output kwarg. is there any solution to this?

no . i tried ```ninja apidocs``` as well. won't work. ```ninja devhelp``` however will:
```
$ ninja apidocs
ninja: error: unknown target 'apidocs'

$ ninja devhelp
[1/1] 'Generating apidocs with a custom command.'
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 13: reading configurations from ~/.fonts.conf.d is deprecated. please move it to /home/grindhold/.config/fontconfig/conf.d manually
Succeeded - 0 warning(s)
```

**Comment by nirbheek** [comment]
I looked at your project, and there's several Meson bugs that you're working around in the build file:

1) Vapi files generated by Vala `library()` targets aren't installed

2) There is no integration for generating C headers using the `-H` argument to `valac` inside a `library()`, so they can't be installed by Meson.

2) Custom targets that generate a new directory with several files inside it can't install that directory:

```
Traceback (most recent call last):
  File "/home/nirbheek/projects/repositories/github/meson.git/meson.py", line 25, in <module>
    sys.exit(mesonmain.run(launcher, sys.argv[1:]))
  File "/home/nirbheek/projects/repositories/github/meson.git/mesonbuild/mesonmain.py", line 242, in run
    sys.exit(run_script_command(args[1:]))
  File "/home/nirbheek/projects/repositories/github/meson.git/mesonbuild/mesonmain.py", line 232, in run_script_command
    return cmdfunc(cmdargs)
  File "/home/nirbheek/projects/repositories/github/meson.git/mesonbuild/scripts/meson_install.py", line 251, in run
    do_install(datafilename)
  File "/home/nirbheek/projects/repositories/github/meson.git/mesonbuild/scripts/meson_install.py", line 54, in do_install
    install_targets(d)
  File "/home/nirbheek/projects/repositories/github/meson.git/mesonbuild/scripts/meson_install.py", line 205, in install_targets
    do_copy(fname, outname)
  File "/home/nirbheek/projects/repositories/github/meson.git/mesonbuild/scripts/meson_install.py", line 36, in do_copy
    shutil.copyfile(from_file, to_file)
  File "/usr/lib64/python3.5/shutil.py", line 114, in copyfile
    with open(src, 'rb') as fsrc:
IsADirectoryError: [Errno 21] Is a directory: 'devhelp'
FAILED: install 
```

4) There is no `valadoc` integration in Meson. It should be added along the same lines as the `gtk-doc` integration.

These are the actual issues that need to be fixed.

**Comment by grindhold** [comment]
ah lol. didn't consider most of those bugs. i guess, working with other buildsystem gets one used to dirty hacks ;) so. should we split those 4 items into single issues and close this one?

**Comment by nirbheek** [comment]
Yep, I'll do that now. Thanks for bringing our attention to this. :)
