### ISSUE TITLE
Allow installation of output header (-H) for Vala library targets

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#892]
Currently it is unconditionally named after the library itself, but this is not always what people want. For instance in #890, @grindhold names the library `libhttpseverywhere-0.2`, but the header is called `libhttpseverywhere.h`.

Found while investigating #890

**Comment by arteymix** [comment]
I already suggested that we add `vala_gir` (see #634), `vala_header` and `vala_vapi` to customize the generated files (beside naming them from the target).

Also, we typically want the header subdirectory to follow the target name, not its content.

**Comment by nirbheek** [comment]
We don't provide a way to install this yet, so this is only partially fixed.
