### ISSUE TITLE
HDF5 dependency includes unwanted compiler flags from h5cc

### ISSUE THREAD

**Issue by taw10** [mesonbuild/meson#8932]
**Describe the bug**
On CentOS 7.9.2009, with hdf5-devel 1.8.12-12.el7 installed from the CentOS repositories, the `h5cc` tool includes some strange flags:
```
$ h5cc -c -show
gcc -I/usr/include -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_BSD_SOURCE -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -c
```
These flags seem to arise from the CentOS packagers not taking into account that "private" compiler flags for building HDF5 should be set using `H5_CFLAGS` rather than `CFLAGS`.  Anything in the latter gets copied through to h5cc.  A similar problem was reported on IRC for the Arch package.  In contrast, the Fedora 33 package for HDF5 1.10.6 is 'clean' and only contains the include path and required linker libraries.

Meson copies all flags starting with `-I`, `-f` or `-D` through to the project, thereby including, in this case, `-D_BSD_SOURCE` which changes certain function prototypes (in my example, `getpgrp`), breaking builds which assume the POSIX prototypes.

This issue could be considered as a packaging issue for the affected distributions.  However, it seems that the HDF5 discovery would be more robust if it instead looked only at the include paths (`-I`).  Is there any reason not to filter out the `-D` and `-f` flags?  Perhaps using a whitelist of allowed flags?

**To Reproduce**
Minimal example meson.build:
```
project('hdf5-meson-test', 'c',
        version: '0.0.1')

hdf5dep = dependency('hdf5', language: 'c', required: true)

executable('hdf5-meson-test',
           ['hdf5-meson-test.c'],
           dependencies: [hdf5dep])
```
And hdf5-meson-test.c:
```
#include <stdio.h>
#include <sys/types.h>
#include <unistd.h>

int main(int argc, char *argv[])
{
        printf("%i\n", getpgrp());
        return 0;
}
```
Results:
```
$ meson build
The Meson build system
Version: 0.55.1
Source dir: /home/twhite/hdf5-meson
Build dir: /home/twhite/hdf5-meson/build
Build type: native build
Project name: hdf5-meson-test
Project version: 0.0.1
C compiler for the host machine: ccache cc (gcc 4.8.5 "cc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)")
C linker for the host machine: cc ld.bfd 2.27-44
Host machine cpu family: x86_64
Host machine cpu: x86_64
Run-time dependency HDF5 for c found: YES
Build targets in project: 1

Found ninja-1.10.2 at /usr/bin/ninja
$ ninja -C build/                                               
ninja: Entering directory `build/'
[1/2] Compiling C object hdf5-meson-test.p/hdf5-meson-test.c.o
FAILED: hdf5-meson-test.p/hdf5-meson-test.c.o 
ccache cc -Ihdf5-meson-test.p -I. -I.. -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -g -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_BSD_SOURCE -fexceptions -fstack-protector-strong -MD -MQ hdf5-meson-test.p/hdf5-meson-test.c.o -MF hdf5-meson-test.p/hdf5-meson-test.c.o.d -o hdf5-meson-test.p/hdf5-meson-test.c.o -c ../hdf5-meson-test.c
../hdf5-meson-test.c: In function ‘main’:
../hdf5-meson-test.c:7:2: error: too few arguments to function ‘getpgrp’
  printf("%i\n", getpgrp());
  ^
In file included from /usr/include/features.h:375:0,
                 from /usr/include/stdio.h:27,
                 from ../hdf5-meson-test.c:1:
/usr/include/unistd.h:639:16: note: declared here
 extern __pid_t __REDIRECT_NTH (getpgrp, (__pid_t __pid), __getpgid);
                ^
ninja: build stopped: subcommand failed.
$
```
Note the spurious parameters which are visible in the compiler command line.
The project compiles cleanly if `hdf5dep` is removed from the dependencies list.

**Expected behavior**
Above example compiles cleanly in both cases.

**System parameters**
* Native build
* CentOS Linux 7.9.2009
* Python 3.6.8
* Meson 0.55.1 (also reproducible with current Git revision d3d95d39beebb42, 0.58.999)
* Ninja 1.10.2

**Comment by eli-schwartz** [comment]
As mentioned on IRC, this isn't generally applicable -- the defines listed out by pkg-config should be assumed necessary by default. e.g. if you check Qt5 stuff, they define `-DQT_<COMPONENT>_LIB` which is presumably somehow needed before headers are read, for whatever internal reason.

The problem is thus specific to known bad upstream projects which add inappropriate flags. e.g. on Arch:

```
$ h5cc -c -show
gcc -I/usr/include -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -c
```

Less damaging perhaps, but still shouldn't be inserting the $CFLAGS used during the hdf5 build process.

So, I could foresee one solution being to special case hdf5 and filter out many types of flags on the grounds "they're not responsible enough to use this power for good".

**Comment by taw10** [comment]
To clarify, my proposal is that **only** the flags from h5cc (HDF5 dependency found by Meson with config-tool method) should be filtered, and then only if it's practical to do so.  It already filters out `-O2` and `-g`, for example.  The flags from pkg-config for HDF5 seem to be fine - I think mostly because a pkg-config file is only generated when using a completely different build system for HDF5 (CMake vs autotools) which doesn't give rise to the confusion between CFLAGS and H5_CFLAGS.

If there's no practical and safe way to do the filtering, then our only choice is to regard this solely as an HDF5 packaging problem.

**Comment by taw10** [comment]
It seems clear that the only proper way to fix this is by fixing the distribution package, so I've sent this issue on to the EPEL bugzilla. That's where the HDF5 package for CentOS comes from: https://bugzilla.redhat.com/show_bug.cgi?id=1980549

@eli-schwartz If you have the time and inclination, it would be great if you could do the same for Arch (with which I'm not familiar).  It's surely the same problem with exactly the same root cause.

**Comment by eli-schwartz** [comment]
It's not unreasonable to consider filtering on the meson side -- this will be easier to do once than fixing every distro plus the self-built installs which people use.
