### ISSUE TITLE
Argument <InternalDependency null: True> of type InternalDependency is not held by an ObjectHolder.

### ISSUE THREAD

**Issue by steffzahn** [mesonbuild/meson#8936]
**Describe the bug**
meson ( as of commit 84b371c6451344f032d2c6f550c2711ec0776ca8 ) applied to the efl lib 
( https://git.enlightenment.org/core/efl.git , commit ID 4ab074c4685e842dae4404fdbdb4fabef4e4b758 ), results in the mentioned error Argument <InternalDependency null: True> of type InternalDependency is not held by an ObjectHolder.

The build is performed in the Linux environment of ChromeOS. The bug is NOT present in Meson 0.58.1.

**To Reproduce**
See above.

**Expected behavior**
No internal error happens.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? no
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) Linux, ChromeOS, derived from Debian 10.10
* what Python version are you using e.g. 3.8.0:  python is present in several versions, it is unclear, which one meson will use. python points to version 2.7.16, python3 points to version 3.7.3
* what `meson --version` : what: command not found
* meson --version : 0.58.999
* what `ninja --version` if it's a Ninja build: what: command not found
* ninja --version : 1.10.2.git

**Comment by steffzahn** [comment]
[meson-log.txt](https://github.com/mesonbuild/meson/files/6722052/meson-log.txt)

**Comment by mensinda** [comment]
Should be fixed with #8940

**Comment by jpakkane** [comment]
Can you verify if the linked branch fixes it for you?

**Comment by steffzahn** [comment]
> Can you verify if the linked branch fixes it for you?

If this was addressed to me: I cannot for some reason fetch this branch. I tried git fetch --all , git pull --all . Still I cannot see the branch fixGetVariableDefault, nor can I checkout commit 1bb714f232fa08c5985467e0d14faf37166a9e6b .

**Comment by jpakkane** [comment]
Those are not in Meson repo, you need to branch the submitter's repo `https://github.com/mensinda/meson.git` branch `fixGetVariableDefault`

**Comment by mensinda** [comment]
@steffzahn You can also do it directly from the main repo with:

```bash
git fetch origin pull/8940/head:temp
git checkout temp
```

**Comment by steffzahn** [comment]
I can confirm, the problem is fixed with the above branch.
