### ISSUE TITLE
Use environment variables to search for external libraries on Windows

### ISSUE THREAD

**Issue by octowaddle** [mesonbuild/meson#8937]
**Describe the bug**
Meson is not able to find external libraries on Windows, even though the directory containing them is both in the `LIB` and the `PATH` environment variable. `LIB` is also the environment variable that libraries use in the Windows developer command prompt.

**To Reproduce**
* Choose a Meson project that uses external libraries
* Install the libraries on Windows and add the directory containing the `lib` or `dll` file to the `LIB` or `PATH` environment variable
* Try to configure the Meson project

**Expected behavior**
Meson should find the library files.

**system parameters**
* Operating system: Windows 10
* Meson version: `0.58.1`
* Ninja version: `1.10.2`

**Comment by jpakkane** [comment]
How are you looking up said libraries?

**Comment by octowaddle** [comment]
I was just using `dependency('...')`. But I just found out about accessing the compiler and then using `cc.find_library('...')`. This works (at least for the Microsoft `cl` compiler). I still think Meson should look these paths up automatically, as it makes things a bit clearer and easier.

**Comment by mensinda** [comment]
`dependency(...)` does *not* lookup any libraries in general. Instead, it uses backends like pkg-config or CMake to find a dependency definition. This includes include directories, compiler flags, the actual library file, etc. So if your library does not ship with `*.pc` or `*.cmake` files, you are out of luck with `dependency()`. In this case, using `cc.find_library('...')` *is* the intended way for finding these libraries (and you have to manually track compile flags, include dirs, etc.).
