### ISSUE TITLE
Wrong meson version is run

### ISSUE THREAD

**Issue by rtbo** [mesonbuild/meson#8938]
I have `meson-0.58.1` installed system wide in `/usr`. 
I have `meson-0.57.1` installed user wide in `~/.local`.

No matter what I do, the user wide version is always run.
```
$ /usr/bin/meson --version
0.57.1
```
This makes multiple installs impracticable.
The root script should try to reorder `sys.path` to run the correct version.

On my system, `sys.path` is like so:
```python
['', '/usr/lib/python39.zip', '/usr/lib/python3.9', '/usr/lib/python3.9/lib-dynload', '/home/remi/.local/lib/python3.9/site-packages', '/usr/lib/python3.9/site-packages']
```

It should not be too hard to detect the script prefix and determine that `/usr/lib/python3.9/site-packages` should come first.

**Comment by eli-schwartz** [comment]
I don't feel this is remotely valid. This is how all things python ever work -- you install meson into your python modules, then the /usr/bin/meson script is an alias for `python -m mesonbuild.mesonmain`.

If meson was written in C and installed as /usr/lib/libmesonbuild.so, but you installed another copy to /usr/local and your ld.so was searching there, it wouldn't be any surprise if /usr/bin/meson loaded the library from /usr/local/lib either.

If you want to install two editions of meson, you should not do it by installing them to different priorities on the system path, but rather, you should install them to a python venv -- or use `packaging/create_zipapp.py` to make a standalone `meson.pyz` executable. (You could then install this as /usr/bin/meson-0.57.1 and /usr/bin/meson-0.58.1 for convenience and proper labeling.)

The /usr/bin/meson script is created by setuptools/pip anyway -- there is nothing we can do to influence its contents.

**Comment by eli-schwartz** [comment]
FWIW, I put not inconsiderable effort into making create_zipapp.py work well, and it would be great if more people would use it... I think I suggested on IRC once or twice to add it to the releases page.

**Comment by rtbo** [comment]
That's good to know. I was not even aware of python's `zipapp` concept. :thumbsup:

**Comment by jpakkane** [comment]
Note that if you tried to use an existing build directory, Meson will remember the exact binary that was used to create a build directory and will keep using the same one regardless of what is your path.
