### ISSUE TITLE
Difficulty to use custom_target() to generate data files

### ISSUE THREAD

**Issue by Jairard** [mesonbuild/meson#8963]
I am trying to use `custom_target` to generate some data files via a `python` script. I am struggling on two points:
- I don't want to have to manually list all the output file in the `output` argument, since they depend on the content of the input file. I may have found a workaround though: I output all the files in a fixed folder and then reference this folder in `output`. Not sure if it has any negative implications.
- I would like the script to be only run when the `input` file changes, and I couldn't make this work: either the script never runs or it is run each time I build. I tried many combinations of `install` and `build_by_default`, and even tried to use the output files as dependencies with no success.

From what I understood of the manual, `custom_target()` should be the way to go here, but let me know if there is something more adapted for my use-case.

**To Reproduce**
A simplified version of my meson file (in this case, script never runs):
```
prog_python = import('python').find_installation('python3')

custom_target('my_target',
    input: 'input.json',
    output: 'out', # folder where the script will write the output files
    output_dir: out_dir,
    command: [prog_python, 'my_script.py', '@INPUT@', out_dir / 'out'],
    install: true,
    install_dir: out_dir,
    build_by_default: false,
)
```

**System parameters**
* windows 10
* python: 3.8.2
* meson: 0.58.0
* ninja: 1.10.2

**Comment by eli-schwartz** [comment]
Where did you make up the `output_dir` kwarg from?

```
meson.build:5: WARNING: Passed invalid keyword argument "output_dir".
WARNING: This will become a hard error in the future.
WARNING: Unknown keyword arguments in target my_target: output_dir

```

**Comment by eli-schwartz** [comment]
(Also your meson file doesn't form a reproducer testcase, as it is missing both the script you're using, and definitions for `out_dir`.)

**Comment by Jairard** [comment]
Here is a complete minimal case

1. create the following files in the same directory:

**meson.build**
```
project('cutrom_target_repro', 'cpp')

prog_python = import('python').find_installation('python3')

in_dir = meson.current_source_dir()
out_dir = meson.current_source_dir()

custom_target('my_target',
    input: 'input.json',
    output: ['out'], # folder where the script will write the output files
    command: [prog_python, in_dir / 'my_script.py', '@INPUT@', out_dir / 'out'],
    install: true,
    install_dir: out_dir,
    build_by_default: false,
)
```

**my_script.py**
```python
import json
import os
import pathlib
import sys

if __name__ == '__main__':
    print("running python script")

    out_dir = os.path.abspath(sys.argv[2])
    if not os.path.exists(out_dir):
        print("creating folder ", out_dir)
        os.mkdir(out_dir)

    json_data = json.loads(open(sys.argv[1], "r").read())
    for file in json_data:
        print("creating file ", os.path.join(out_dir, file))
        pathlib.Path(os.path.join(out_dir, file)).touch()

    print("done")
```

**input.json**
```json
[
    "foo.txt",
    "bar.log"
]
```

2. run the commands:
```
meson build
ninja -C build
```
You should notice that the script does not run.
If you remove the `build_by_default` argument from custom target, the script will run at each compilation, which seems "normal" since `install` will override `build_by_default` to `true` as the [documentation](https://mesonbuild.com/Reference-manual.html#custom_target) states.

What I am trying to achieve is running this script whenever `input.json` changes (or if it's the first compilation obviously).

**Comment by eli-schwartz** [comment]
```
out_dir = meson.current_source_dir()
```

With this context the problem becomes clear, when you originally tried passing `output_dir: out_dir,` you no doubt intended for meson to generate a build.ninja which generates rules targeting the source directory rather than the build directory.

meson does not support in tree builds, so trying to tell it to do so was futile... and since my_script.py never tried to generate the output which you specified (instead it created totally unrelated files in out_dir) the build rule notices on every single build that the output still hasn't been created, so it tries to rerun the rules which should create it.

Your install_dir argument is also nonsense -- if you fix the out_dir location, then run `ninja install`, it will install `builddir/out/foo.txt` to `$PWD/builddir/out/foo.txt`. It then fails, because installing a file will first remove the existing destination file, then install the source file to the destination.

**Comment by Jairard** [comment]
Ok, thanks to your explanations I managed to have the script run only when `input.json` changes.

This is my `meson.build` now:
```
project('cutrom_target_repro', 'cpp')

prog_python = import('python').find_installation('python3')

in_dir = meson.current_source_dir()
out_dir = meson.current_build_dir()

custom_target('my_target',
    input: 'input.json',
    output: ['foo.txt', 'bar.log'],
    command: [prog_python, in_dir / 'my_script.py', '@INPUT@', out_dir],
    install: true,
    install_dir: in_dir / 'out',
)
```

But as I mentioned before, I'd like to not have to specify each output files in `output` because this is given but `input.json`. Do you happen to know a way to do so or is it not possible ?

**Comment by eli-schwartz** [comment]
```
output: ['out']
command: [prog_python, in_dir / 'my_script.py', '@INPUT@', meson.current_build_dir() / 'out'],
install_dir: get_option('datadir') / 'myprog', # ends up in /usr/share/myprog/out/{foo.txt,bar.log}
```

If your output is a directory, ninja becomes a bit clueless about how it got generated, and meson is pretty fuzzy on how to install it so it simply copies over the entire directory. But it does only build when the input gets changed, which is the important bit.

You just need the out/ directory which the python program is told to use, to be in the current_build_dir() to correspond to the kwarg value of `output`.

In fact, you may just use `'@OUTPUT@'` directly.

**Comment by Jairard** [comment]
Thank you very much, it is very more clear now and I got it working :)
