### ISSUE TITLE
execute target command for every file

### ISSUE THREAD

**Issue by climbit** [mesonbuild/meson#8985]
Hi There,

I was wondering if it is possible to execute the command of a target not for all files at once but for each file separately. I know, it is recommended to use a wrapper script if multiple commands must be executed but I thought this is somehow a bit different.
And if it is not possible, maybe this is worth a feature request? I am not sure if this is just a corner case...

My use case is, to compile multiple plots with python matplotlib. The following code as it is will fail as the command executed will be `python3 plot1.py plot2.py` but `python3 plot1.py; python3 plot2.py` would solve this issue.
meson.build:
```
project('mpl test')
python3_exe = find_program('python3')

mpl_infiles = files('plot1.py', 'plot2.py')
mpl_in_fns = []
mpl_out_fns = []
foreach fil : mpl_infiles
  mpl_in_fns += configure_file(
    input : fil,
    output : '@PLAINNAME@',
    copy : true
  )
  mpl_out_fns += '@0@'.format(mpl_in_fns[-1]).split('/')[-1].replace('.py', '.png')
endforeach

matplotlib_target = custom_target(
  'matplotlib',
  input : mpl_in_fns,
  output : mpl_out_fns,
  command : [python3_exe, '@INPUT@'],
)
```
plot1.py and plot2.py are slightly modified versions of a script from the matplotlib homepage:
```
import os
import sys
import numpy as np
import matplotlib.pyplot as plt

x1 = np.linspace(0.0, 5.0)
x2 = np.linspace(0.0, 2.0)

y1 = np.cos(2 * np.pi * x1) * np.exp(-x1)
y2 = np.cos(2 * np.pi * x2)

fig, (ax1, ax2) = plt.subplots(2, 1)
fig.suptitle('A tale of 2 subplots')

ax1.plot(x1, y1, 'o-')
ax1.set_ylabel('Damped oscillation')

ax2.plot(x2, y2, '.-')
ax2.set_xlabel('time (s)')
ax2.set_ylabel('Undamped')

plt.savefig('{}.{}'.format(os.path.splitext(os.path.basename(__file__))[0],'png'))
```
compile with:
```
meson setup build && meson compile -v -C build matplotlib
```

This is the first time I use Meson, so beside the subject, if there are ideas how to improve the code, tips and tricks would be very welcome

Thank you very much,
Daniel

**Comment by eli-schwartz** [comment]
You need to make each one its own custom target inside the foreach loop.

You can use https://mesonbuild.com/Reference-manual.html#alias_target to make sure all the custom targets are run using 'ninja matplotlib'.

**Comment by climbit** [comment]
Hi Eli,

Thank you very much for your answer!

The code looks now like this and works perfectly:
```
project('mpl test')
python3_exe = find_program('python3')

mpl_infiles = files('plot1.py', 'plot2.py')
mpl_in_fns = []
mpl_out_fns = []
matplotlib_targets = []
foreach fil : mpl_infiles
  mpl_in_fns += configure_file(
    input : fil,
    output : '@PLAINNAME@',
    copy : true
  )
  mpl_out_fns += '@0@'.format(mpl_in_fns[-1]).split('/')[-1].replace('.py', '.png')
  matplotlib_targets += custom_target(
    'matplotlib_@0@'.format(mpl_in_fns[-1]),
    input : mpl_in_fns[-1],
    output : mpl_out_fns[-1],
    command : [python3_exe, '@INPUT@'],
  )
endforeach

matplotlib_target = alias_target(
  'matplotlib',
  matplotlib_targets
)
```

Thanks,
Daniel
