### ISSUE TITLE
[question] Is it possible to run a command before compiling per target?

### ISSUE THREAD

**Issue by Makogan** [mesonbuild/meson#8998]
I have read the documentation and I have read about run targets, custom targets and generators and declare_dependency and I am not sure any of them quite allow me to do what I need.

My build process is as follows, I have multiple potential targets which are visual demos, things like a house, a procedural terrain, some raytracers... and each one is it's own executable. Prior to compiling, a python script is run to analyze the demo directory and find if, for example, shader files have changed or new images have been added. The script then *modifies* multiple existing headers and cpp files that exist for the sole purpose of syncing cpp objects and definitions with declarations in a shader file. In other words no new files are generated, just edited.

The script *must* be run before compilation, almost every time, in terms of workflow it is rare that a demo doesn;t need preprocessing and weird bugs can occur if this is not run, so it is safer to just run it every time.

Right now with custom_targets I have a solution which is:

`meson compile <PreprocessDemo> && meson compile <Demo>`

This works, but it is not ideal, as mentioned, for security purposes I would rather it be impossible to build the demo without running the preprocessing. Moreover, to be compliant with meson's expectations I had to create a bunch of dummy files that serve absolutely no purpose.

I suspect I could achieve this by adding yet another custom_target that just executes the above command, but that requires yet more targets and yet more dummy files. 

Ideally I just want to declare a command as a prerequisite to compilation, sort of like a dependency. i.e. instruct meson to always run the specified command before compiling. But I am not sure if it is feasible with the current state of the project.

**Comment by eli-schwartz** [comment]
This sounds extraordinarily confusing.

Are the files being modified, files that are checked into git in the source tree? Or are they in the out-of-tree builddir?

**Comment by jpakkane** [comment]
There is a way to do what you want, but it probably takes some refactoring. You need to separate the existing source files that you modify so that all the "generated" bits are separate from whatever hand written code there is. Then:

- Create a custom target that runs your script and generates a source/header pair
- Mark that target with `build_always_stale: true` so it is run every time
- update the script so that if its output would be identical to the existing file, it does not overwrite it

This should do the correct thing automatically every time. The important thing is that you generate new source files in the build dir rather than trying to modify existing source files inside the source tree.

**Comment by Makogan** [comment]
@eli-schwartz Welcome to the world of real time interactive applications, where you juggle a bunch of conflicting constraints, such as ease of use, simplicity, speed, memory usage, ease of iterability...

This might not be the best solution to the problem, but it solved the problem of autosyncing glsl declarations with C++ code.

@jpakkane Thank you for the advice, I will try it.

**Comment by Makogan** [comment]
I am reopening this question, sorry.

I noticed that with the advice given my build doesn't really work (it just seemed to work before).

I did the following in my meson.build:

```python
pre_target = custom_target(
    'Preprocess',
    command : ['python3', '../Scripts/preprocessing.py'],
    output : [
        'UniformObjects.cpp',
        'UniformObjects.hpp'],
        build_always_stale : true)

core_lib = library('CoreNeverEngine',
    sources : sources,
    include_directories : all_includes,
    dependencies : linked_dependencies,
    build_by_default : true)
pkg.generate(core_lib)
```
So, as advised, the preprocessing script now outputs the header object pair. However, since the `UniformObjects.cpp` is not on sources, the core_lib library doesn't link to it, compilation fails. So then I tried the generated headers technique and did:


```python

pre_target = custom_target(
    'Preprocess',
    command : ['python3', '../Scripts/preprocessing.py'],
    output : [
        'UniformObjects.cpp',
        'UniformObjects.hpp'],
        build_always_stale : true)

sources += pre_target
core_lib = library('CoreNeverEngine',
    sources : sources,
    include_directories : all_includes,
    dependencies : linked_dependencies,
    build_by_default : true)
    ```
    
    However this results in:
    
    `c++: error: UniformObjects.cpp: No such file or directory`
    
    So it seems either meson is looking for the sources before executing the script or it is not finding the appropriate path. so I then try to do:
    
    ```
    output : [
        'Src/Engine/Renderer/Rendering/VulkanLayer/AutoGenerated/UniformObjects.cpp',
        'UniformObjects.hpp'],
        ```
   Which gives `../meson.build:97:0: ERROR: Output 'Src/Engine/Renderer/Rendering/VulkanLayer/AutoGenerated/UniformObjects.cpp' must not contain a path segment.`
   
   I then searched the custom_command documentation to see if there is a way to specify the path to the file, but I don;t see anything of the sort.
   
  Finally I tried to see if I could use `depend_file : 'Src/Engine/Renderer/Rendering/VulkanLayer/AutoGenerated/',` in core_lib to get it to wait for the file to appear but I just get the same linking errors, as the keyword does not exist for libraries.

It is honestly quite frustrating. This is a problem that could be solved by one of the following:

* Allow the user to specify a target priority, to deterministically ensure that target A is built before target B.
* Allow `declare_dependency` or `dependency` to take a target object as input, to allow the user to specify "please meson, don;t even try to build this thing until this one is built" by passing the generated dependency into the dependencies array as normal.
* Allow the user to specify a command in libraries and executables, similar to custom targets. Meson runs the specified command before building the target.


The last option would help in many other situations, such as exporting environment variables (which meson do by default), moving files around, for example copying serialized asset files (images, sound files) into the cpp files, which is a common trick to speed up loading time when debugging, editing configuration files if needed, touching files to trigger recompilation in certain cases (look up the library incbin to see a scenario where this is necessary). And almost any other use case that meson itself is not designed to solve.

**Comment by jpakkane** [comment]
You are not telling your script where it should output its files, so it probably ends up writing them in the wrong place. You should probably do something like this instead:

```meson
pre_target = custom_target(
    'Preprocess',
    output : [
        'UniformObjects.cpp',
        'UniformObjects.hpp'],
    build_always_stale : true,
    command : [find_program('../Scripts/preprocessing.py'), '@OUTPUT0@', '@OUTPUT1@', meson.current_source_dir()],
)
```

The last argument is to tell the script where it should do the scanning. so depending on how your script actually works you might need to modify it.

**Comment by Makogan** [comment]
@jpakkane Thank you very much for your help, I am still encountering some issue. For example if use the find program command as you usggested it it fails to find the file. So I tried using an absolute path instead:

`find_program(meson.source_root() / 'Scripts/preprocessing.py')`

This fails with error:
`ERROR: Program '/home/makogan/neverengine/Scripts/preprocessing.py' not found`

However :

```
$ realpath Scripts/preprocessing.py 
/home/makogan/neverengine/Scripts/preprocessing.py
```

The path is correct, I am not sure why meson fails to find the script.  

I also tried
`find_program('preprocessing.py', dirs : meson.source_root() / 'Scripts/')`

And I also tried it outside the custom_target command, but it never finds the file. : \

**Comment by jpakkane** [comment]
Meson detects runnable scripts either by them having the execute bit set or if they start with a shebang line.

**Comment by Makogan** [comment]
Thank you for your patience but I think you miss understand my problem, it is very likely I have not done a good job at explaining.

Currently, the paths in my script are hard coded, there is no need to pass the path as arguments.

Before trying to use meson the path was hard coded to: `Src/Engine/Renderer/Rendering/VulkanLayer/AutoGenerated`

But you cannot tell meson where to search for these files. Meson will, invariably, search for them in the `build` directory, meaning my script must be modified to output to `./build/` (the build directory).

i.e. I am outputing the files to  the correct place according to meson.  What I am saying is that being forced to output to `build` without even being able to specify a directory structure, e.g. `build/AutoGen/file1` is a problem. 

Said otherwise, currently I can compile using meson. I dislike the directory structure meson imposes on my autogen files, because I foresee a plethora of problems with it. (See my prior enumeration).

(I deleted my prior comment because I realized we were not talking about the same thing) : \

I am sorry if I sound rude, I think meson is a very cool project, and I thank you for your help with this issue.

**Comment by jpakkane** [comment]
This is a known thing about the design. Meson is _very_ strict about file generation. All source code is in the source tree and is immutable (it could be on a read-only file system even). _All_ generated code and files go in the build dir. No exceptions (though if someone wants to run their own commands that poke the source dir, we can't really stop them). This has both advantages and disadvantages:

- You can have as many build dirs with different configurations as you want and you are guaranteed that they won't interfere with each other
- You will know where the files in the build dir come from _for any Meson project_. When you encounter a project you have never seen before, you'll automatically know where its files come from, where they go, where in the `meson.build` files they are defined and so on.
- The downside (as you have experienced) is that converting existing projects that behave in a very different way might take some work.

> I dislike the directory structure meson imposes on my autogen files, because I foresee a plethora of problems with it.

These types of problems are fully feasible. However there are already existing projects using Meson that have dozens (maybe hundreds? I don't know for sure) of generated files and there have been no complaints over performance issues.

**Comment by Makogan** [comment]
If this is the design philosophy, then I guess I will stop being annoying. Hopefully none of the problems I described happen.
Thank you once more for your help.
