### ISSUE TITLE
Regression: CustomTarget no longer allowed for qt.preprocess in 0.59

### ISSUE THREAD

**Issue by ximion** [mesonbuild/meson#9007]
Hi!

A project I am working on currently fails to build with Meson 0.59 because output of the Qt DBus generator / Qt Remote Object compiler is passed to `qt.preprocess`, resulting in this new error:

```
ERROR: qt.preprocess keyword argument "moc_headers" contained a value of type "CustomTarget" but should have been one of: "File", "str"
```

This has worked fine before (Meson <= 0.58), and is probably a sideeffect of the Qt refactoring that has happened - maybe it's just a matter of allowing `CustomTarget` as a parameter, I will have a look at the code later :-)

**Comment by dcbaker** [comment]
It's probably pretty simple to fix, I'll have a look later today. So many of these interfaces are unfortunately badly documented as to what types they accept :/

**Comment by ximion** [comment]
Nice, thank you very much for the really quick fix! :-)
