### ISSUE TITLE
Error building glib with meson 0.59

### ISSUE THREAD

**Issue by jjardon** [mesonbuild/meson#9009]
Logs here: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/jobs/1439678151

**Comment by dcbaker** [comment]
Quickly, it looks like there's some caller of make_test not providing a timeout when it should. Probably party of the strict type checking changes

**Comment by xclaesse** [comment]
@dcbaker That's because the gnome module uses interpreter internal method directly instead of going through typed_kwargs decorator that sets defaults. We'll have to be more careful for that in the future.

**Comment by dcbaker** [comment]
I didn't realize that the gnome module wrapped the tests. It really should go through the internal methods, but without full type checking it's hard to make sure that everything is set correctly. :/
