### ISSUE TITLE
Compile Cython code to C++

### ISSUE THREAD

**Issue by michael-rapp** [mesonbuild/meson#9015]
Meson 0.59.0 introduced native support for [Cython](https://mesonbuild.com/Cython.html#cython). I am trying to compile an existing Cython project using Meson. The Cython code relies on functionality from the C++ standard library and therefore must be compiled to C++. I found some discussion on whether compilation from Cython to C++ can be supported in pull request #8706. Unfortunately, it remains unclear to me whether this functionality is already supported or not.

Is it possible to compile `.pyx` files to `.cpp` files using Meson? Either by globally defining the target language in the `meson.build` file, or by adding the compiler directive `# distutils: language = c++` to the `.pyx` files. I tried the latter, but Meson still produces `.c` files.

**Comment by dcbaker** [comment]
I have patches for this, there's just one issue i need to work out with it.

**Comment by michael-rapp** [comment]
Glad to here that support for this functionality is planned. Is there an issue/pull request where the progress is documented?

**Comment by dcbaker** [comment]
No, there isn't. I can probably open a wip or later

**Comment by dcbaker** [comment]
I went ahead and opened a draft PR for the issue. It works in the sense that the option allows you to control C vs C++ output, but there's still a few corners in the Meson's automatic addition of a C or C++ compiler if you override the options on a per-target basis.
