### ISSUE TITLE
Regression in Subproject Exception Handling from 0.58.2 to 0.59.0

### ISSUE THREAD

**Issue by nosracd** [mesonbuild/meson#9038]
**Describe the bug**
Subprojects failing to configure cause errors later on.

**To Reproduce**
Using the following meson.build:

```
project('foo', 'cpp')

dependency('bar',
    required: false,
    disabler: true,
    fallback: ['bar', ''])

python = import('python').find_installation('python3').dependency()
```
with the following purposely failing subproject at `subprojects/bar/meson.build`
```
project('bar', 'cpp')

python = import('python').find_installation('python3')

dependency('nonexistant-dependency')
```

attempt to configure using
```
meson build
```

**Expected behavior**
Using `0.58.2` results in the subproject failing but the rest of the project configuring successful and the command completing with a zero exit code 

**Expected behavior**
Using `0.59.0` results in the subproject failing as expected, but the rest of the project completing with nonzero exit code and the following error
```
meson.build:8:0: ERROR: Unknown method "dependency" in object <[ExternalProgramHolder] holds [PythonExternalProgram]: <PythonExternalProgram 'python3' -> ['/usr/bin/python3']>> of type ExternalProgramHolder.
```

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
    * This is a plain bare-metal build
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
    * Ubuntu 20.04
* what Python version are you using e.g. 3.8.0
    * Python 3.8.10
* what `meson --version`
    * `0.59.0`
* what `ninja --version` if it's a Ninja build
    * N/A

Potentially related to #9036

**Comment by dcbaker** [comment]
This sure looks like `find_installation` isn't getting holdered correctly, it should be using a special holder type, but is instaed getting the generic ExternalProgramHolder. @mensinda, ideas?

**Comment by mensinda** [comment]
Seems like an entry in [this list](https://github.com/mesonbuild/meson/blob/master/mesonbuild/interpreter/interpreter.py#L468) is missing for `PythonExternalProgram`. However, it is added to the interpreter [here](https://github.com/mesonbuild/meson/blob/master/mesonbuild/modules/python.py#L651).

So, in short, I currently have no idea until I have time to debug this.

**Comment by xclaesse** [comment]
@mensinda I can reproduce and I understood the problem. The python module is first instantiated by the subproject, so `append_holder_map()` is called on subproject's interpreter. When the subproject fails, holder_map is not updated on the parent interpreter, but the module won't be re-imported because both interpreters share the same self.modules list.

**Comment by jpakkane** [comment]
This fix may have broken something with VS2017 [as seen here](https://dev.azure.com/jussi0947/jussi/_build/results?buildId=10989&view=logs&j=c0dfc93a-5619-5146-04af-43b404cff11e&t=f3b41500-5392-55b4-1d21-64986175d7fa). This was probably masked by the Rust error.

**Comment by nirbheek** [comment]
> This fix may have broken something with VS2017 [as seen here](https://dev.azure.com/jussi0947/jussi/_build/results?buildId=10989&view=logs&j=c0dfc93a-5619-5146-04af-43b404cff11e&t=f3b41500-5392-55b4-1d21-64986175d7fa). This was probably masked by the Rust error.

This is only happening on vs2017 x86 because it needs 32-bit Python:

```
Program C:\Python38\python found: YES (C:\Python38\python.exe)
"python-3.8" could not be found in LIBPC (None), this is likely due to a relocated python installation
Pkg-config binary for MachineChoice.HOST is cached as not found.
"python-3.8" could not be found via fallback pkgconfig lookup in PKG_CONFIG_LIBDIR/PKG_CONFIG_PATH
Pkg-config binary for machine MachineChoice.HOST not found. Giving up.
Need python for 32-bit, but found 64-bit
Dependency python found: NO

meson.build:5:0: ERROR: Python dependency not found
```

This is available on the image, we just need to use it to run the tests or point Meson at it in some other way.

**Comment by nirbheek** [comment]
Moving discussion to https://github.com/mesonbuild/meson/pull/9122 since this PR is correct and it's actually a CI issue.
