### ISSUE TITLE
Unknown compiler(s): [['icc']]

### ISSUE THREAD

**Issue by JulioALH** [mesonbuild/meson#9040]
Hello!
I tried to use meson in Linux Mint 19.3, and got this error: `meson.build:1:0: ERROR: Unknown compiler(s): [['icc']]`
The full instruction and output was as follows:
```
bluedragon@BlueDragon:~/scrcpy$ meson build --buildtype release --strip -Db_lto=true  -Dprebuilt_server=../scrcpy-server-v1.18.jar
The Meson build system
Version: 0.59.0
Source dir: /home/bluedragon/scrcpy
Build dir: /home/bluedragon/scrcpy/build
Build type: native build
Project name: scrcpy
Project version: 1.18
meson.build:1:0: ERROR: Unknown compiler(s): [['icc']]
```
Some time I tried to install the Intel C compilers, so probably that is interfering. Should I tell meson to use the GNU C compilers? How do I tell him? or what could I do? I'm newbie to linux, so I'm not even sure if my question should be here, but could you please give me a hint?

Kind regards!

**Comment by dcbaker** [comment]
Do you have a broken `icc` still in your path, and do you have another c compiler (gcc or clang, for example)?

**Comment by JulioALH** [comment]
Dear dcbaker,
I think you are right, I have a broken icc in my path. And yes, I have gcc and clang compilers.

```
bluedragon@BlueDragon:~$ echo $PATH | tr ":" "\n"
/home/bluedragon/intel/compilers_and_libraries_2020.1.217/linux/mpi/intel64/libfabric/bin
/home/bluedragon/intel/compilers_and_libraries_2020.1.217/linux/mpi/intel64/bin
/home/bluedragon/intel/compilers_and_libraries_2020.1.217/linux/bin/intel64
/home/bluedragon/intel/compilers_and_libraries_2020.1.217/linux/bin
/home/bluedragon/intel/compilers_and_libraries_2020.1.217/linux/mpi/intel64/libfabric/bin
/home/bluedragon/intel/compilers_and_libraries_2020.1.217/linux/mpi/intel64/bin
/home/bluedragon/intel/debugger_2020/gdb/intel64/bin
/home/bluedragon/.local/bin
/home/bluedragon/bin
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/sbin
/bin
/usr/games
/usr/local/games
```

```
bluedragon@BlueDragon:~$ gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
bluedragon@BlueDragon:~$` clang --version
Intel(R) oneAPI DPC++ Compiler 2021.1-beta05 (2020.2.0.0304)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/bluedragon/intel/compilers_and_libraries_2020.1.217/linux/bin
```

What should I do? How can I safely remove the broken icc from my path?

I appreciate your help!!

**Comment by jpakkane** [comment]
The recommended way is to change your `PATH` variable so it no longer contains the problematic paths. If you can't do that for whatever reason, then you can specify which compiler to use when setting up the build dir like this:

    CC=gcc meson <other options>

**Comment by JulioALH** [comment]
Hello jpakkane, thanks for your answer,
My .bashrc has the following lines at the end. I wrote them when trying to install the Intel compilers.

```
# Agrega librerias de parallel_studio_xe_2020_update1_cluster_edition
source /home/bluedragon/intel/compilers_and_libraries_2020.1.217/linux/bin/compilervars.sh intel64
source /home/bluedragon/intel/compilers_and_libraries_2020.1.217/linux/mpi/intel64/bin/mpivars.sh
export FC=ifort
export CC=icc
export CXX=icpc
export FC=ifort
export F77=ifort
export F90=ifort
export CFLAGS='-O3 -xHost -ip'
export CXXFLAGS='-O3 -xHost -ip'
export FCFLAGS='-O3 -xHost -ip'
```
Are those lines the reason why my path variable is modified? I will comment those lines in the .bashrc fiel; hopefully that will solve my problem.

**Comment by JulioALH** [comment]
Yes! it worked! I finally could use Meson!
Thanks for your help dcbaker and jpakkane.
