### ISSUE TITLE
0.59 regression: array.contains() method fails for dependency objects

### ISSUE THREAD

**Issue by Akaricchi** [mesonbuild/meson#9047]
**Describe the bug**
The `contains()` method of arrays always returns false when given a dependency object, even if the array actually contains the object. This results in a nasty miscompilation in Taisei.

**To Reproduce**
```meson
project('mesonfail', 'c')
deps = []
dummy = declare_dependency()
deps += dummy
assert(deps.contains(dummy))
```

**Expected behavior**
The assertion in the above code snipped must not fail.

**system parameters**
* native build
* openSUSE tumbleweed
* Python 3.9.0
* meson 0.59.0
* ninja 1.10.2

**Comment by Akaricchi** [comment]
May be a duplicate of #9020

**Comment by dcbaker** [comment]
@mensinda

**Comment by mensinda** [comment]
Yes, this is almost certainly a duplicate. Could you please check if #9027 fixes this?

**Comment by Akaricchi** [comment]
Looks like it does.
