### ISSUE TITLE
Mesonbuild: add dependency using a path

### ISSUE THREAD

**Issue by aminya** [mesonbuild/meson#9050]
Copied from the StackOverFlow question, which did not get any answer.
https://stackoverflow.com/questions/68569635/mesonbuild-add-dependency-using-a-path

**Describe the bug**
I have a monorepo-like file structure in a project that is like this:
```
--src
 |__lib1
    |_meson.build
 |__lib2
    |_meson.build
```

`lib1` is built independently, but `lib2` depends on `lib1` (it should be linked to `lib1`).

I hoped that the `dependency` function accepts a `path` argument, but it doesn't support this.

```py
# lib2 meson.build
lib1_dep = dependency('lib1', path: '../lib1')
```

How can I do this in mesonbuild without breaking my project structure? 

I prefer not to use a top-level monolith mesonbuild file.

**To Reproduce**
`src/lib1/meson.build`
```py
lib1 = static_library(
    'lib1',
    ['./lib1.c'],
    include_directories: include_directories('.')
)
```

`src/lib2/meson.build`
```py
lib2 = static_library(
    'lib2',
    ['./lib2.c'],
    include_directories: include_directories('.')
	# I wish I could:
	# dependencies: [dependency('lib1', path: '../lib1')]
)
```

**Expected behavior**

Being able to add `lib1` as a dependency of `lib2`.

**system parameters**
All the configurations

**Comment by eli-schwartz** [comment]
dependency is equivalent to find_package in cmake, or PKG_CHECK_MODULES in autotools.

lib1 is a variable, add it to lib2 as `dependencies: lib1`

**Comment by aminya** [comment]
I get the following error.
```
meson.build:19:0: ERROR: Unknown variable "lib1".
```

How does the `./src/lib2/meson.build` file know that `lib1` is defined somewhere?

**Comment by xclaesse** [comment]
@aminya There is no scope for meson variables, you can access them from other files. But you have to call subdir('lib1') before subdir('lib2') so the variable lib1 is defined by the time meson goes into lib2.

**Comment by aminya** [comment]
@xclaesse Thanks for the help! 

Adding a `meson.build` file at the root of the project with this content fixes the issue:
```py
project(
    'myproject',
    ['d', 'c'],
    meson_version   : '>=0.55.0'
)

subdir('./src/lib1')
subdir('./src/lib2')
```

However, this would mean that I cannot compile `lib1` independently of the root `meson.build` file. 

Usually, in a mono-repo-like project, the individual projects should be compilable independently of the other subpackages.


Is there a way to make this work such that each package is compilable independently?

For example, suppose each folder is a project itself (if this is the way to achieve independence).
```
project(
    'lib1',
    ['d', 'c'],
    meson_version   : '>=0.55.0'
)

lib1 = static_library(
    'lib1',
    ['./lib1.c'],
    include_directories: include_directories('.')
)
```

**Comment by xclaesse** [comment]
Ah! So lib1 and lib2 are what we call subprojects. You have to place them into `subprojects/`directory and use subprojects() instead of subdir() in main project.
