### ISSUE TITLE
Should compile C code generated by valac with -w

### ISSUE THREAD

**Issue by mcatanzaro** [mesonbuild/meson#907]
valac generates C code that triggers a huge number of C compiler warnings. It should always be compiled with -w to silence the warnings, otherwise it's extremely difficult to notice warnings from valac itself. The only good reason not to use -w is if you a Vala developer trying to improve the code generation.

**Comment by QuLogic** [comment]
Same as #864?

**Comment by nirbheek** [comment]
Yes. We already have a PR for this too: #866 

Closing as duplicate.
