### ISSUE TITLE
[enhancement] patch overlaying independent from directories names

### ISSUE THREAD

**Issue by denizzzka** [mesonbuild/meson#9085]
If we want to maintain Meson overlay repository for any external package it is important that patch directory must be named as package directory.

But this is too hard to maintain because usually names of patch directories produced by 3rd party code (for example, github creates .zip files for each release which contain repository directory name in form `repo_name-1.2.3`)

And if we try to equalize directories by wrap `revision` directive then we broke versions.

In other side, it must be strictly one root directory of package and one root directory for overlaying patch. So, It will be handy if overlaying files will be added independenly from source and destination directory names.

Side effect: Meson will not create subprojects directories accidentally (or will not patch another subpackage which not described in current .wrap file :-) ) if bad names was used. It is make sense if we need to replace some files by patching instead of add - sometimes is too hard to find accidentally unpatched project.

**Comment by eli-schwartz** [comment]
I don't understand the issue. Aren't they already different names, depending on what `patch_directory` value you use?

**Comment by denizzzka** [comment]
As I remember, `patch_directory` is only for local dirs - it is name of dir inside of `subprojects/packagefiles`

**Comment by eli-schwartz** [comment]
Then I'm even more lost.

> because usually names of patch directories

Can you restate your issue from the beginning?

**Comment by denizzzka** [comment]
I want to maintain wrap patch repository for package by OSS-friendly facilities.

So, I just created Github repository and try to patch some another repository to be able to use it with Meson.
And I faced with fact what I can't to do this by using any .wrap file tricks

**Comment by eli-schwartz** [comment]
Why not? I can't imagine any reason you wouldn't be able to do so.

Could you explain what you've tried?

**Comment by denizzzka** [comment]
Main reason: I do not want to release overlays for each release of wrapped ("base") package.

But if I don't do that directory name of base package and directory name of my overlay will be different and patch system just creates another directory in subprojects/ except of adding my files to base package.

This is because directories and archives created by Github with its own naming principles and I can't control it.

**Comment by eli-schwartz** [comment]
You need to update the overlay in order to set the correct `project(..., version: <some-version>)`, and in the general case you'll need to perform general updates on the meson.build as projects evolve, too.

In the case of that particular project, upstream already has a meson.build, which includes a project version. Why do you need to add a patch overlay?

**Comment by denizzzka** [comment]
> You need to update the overlay in order to set the correct project(..., version: <some-version>),

As I understand, it is possible to maintain without changes in patch repository by using automatic git hooks.

> and in the general case you'll need to perform general updates on the meson.build as projects evolve, too.

Yes, but in general this isn't leads to any changes in meson.build files. Most of changes in the projects is tiny trivial fixes and changes.

> In the case of that particular project, upstream already has a meson.build, which includes a project version. Why do you need to add a patch overlay?

https://forum.dlang.org/post/joqbwcslymzwbxdstghg@forum.dlang.org

**Comment by denizzzka** [comment]
>> and in the general case you'll need to perform general updates on the meson.build as projects evolve, too.

> Yes, but in general this isn't leads to any changes in meson.build files. Most of changes in the projects is tiny trivial fixes and changes.

And in any case current Meson forces me to maintain two packages (base and patch) with same directory name

**Comment by eli-schwartz** [comment]
> As I understand, it is possible to maintain without changes in patch repository by using automatic git hooks.

I don't know what this means. git hooks are programs that run on the developer's machine during events such as `git commit`, and can e.g. modify the files being committed to git.

This doesn't help you upload a git repo once and then... have the version number automatically updated without interacting with the git repo at all?

> Yes, but in general this isn't leads to any changes in meson.build files. Most of changes in the projects is tiny trivial fixes and changes.

Tiny trivial fixes and changes are still changes. And even if there aren't any changes in meson.build files (except for updates to the project version!) you can just tag a new version with the same contents, but a different tag name for github's autogenerated tarball... or re-run a Makefile that tars up the meson.build and attaches it to a github release. Or however you release it in general.

> https://forum.dlang.org/post/joqbwcslymzwbxdstghg@forum.dlang.org

Why not contribute fixes upstream?

> And in any case current Meson forces me to maintain two packages (base and patch) with same directory name

They need the same directory name, because they get combined together, yes. I don't see the problem...

**Comment by denizzzka** [comment]
> Why not contribute fixes upstream?

Because nobody wants to learn and use Meson except few guys:
Basile.B:
> the main problem, at least for the packages maintained by the dlang-community entity, was that nobody cared about Meson

> I don't see the problem...

Malformed patch can:
* not patch anything (dir name mismatch)
* accidentally patch few packages at once (few dirs at one archive)

This proposal allows to avoid this

**Comment by eli-schwartz** [comment]
> not patch anything (dir name mismatch)

This is already an error, just like a patch overlay that doesn't contain any meson.build files.

> accidentally patch few packages at once (few dirs in one archive)

This can't possibly happen by mistake, and however it happened it will cause the other subprojects to be an error, I presume.

This all seems like theoretical reasons being used as a retroactive rationale. I still don't understand what practical problem the current model causes.

**Comment by denizzzka** [comment]
> This is already an error

No. This patch actually creates another dir inside of subprojects/
I catched this many times, including on current ~master

> I still don't understand what practical problem the current model causes.

How can I convey the essence of the problem differently?

**Comment by eli-schwartz** [comment]
> No. This patch actually creates another dir inside of subprojects/
> I catched this many times, including on current ~master

... and since it does not create the *correct* directory, the missing meson.build in the subproject it was supposed to patch will cause meson to error out that the subproject it wants is unusable.

**Comment by denizzzka** [comment]
Only if subproject isn't contains buggy `meson.build` file already (my case)

**Comment by eli-schwartz** [comment]
Since upstream is interested in meson support, you can submit your improvements upstream. The patch overlay is intended for adding meson support to something that doesn't have it -- it is not a general facility to patch out upstream content you disagree with.

And in general, any use case I can imagine or which got mentioned here or in #9086 can be handled by one of:
- take advantage of git support, and just point at your fork with meson.build added; regularly rebase on upstream as needed
- add the files in patch_directory, checked into the project that needs that wrap
- write a release script that generates and uploads the archive, and updates the hash in the .wrap file

**Comment by denizzzka** [comment]
> Since upstream is interested in meson support, you can submit your improvements upstream

**Upstream ISN'T interested in Meson support** - Meson was added "accidentally", nobody cares about it and CI was disabled for Meson recently after first Meson issues was become.

> The patch overlay is intended for adding meson support to something that doesn't have it -- it is not a general facility to patch out upstream content you disagree with.

This is strictly this case

> add the files in patch_directory, checked into the project that needs that wrap

Many projects needs same wraps, there is tree of D packages.

> eli-schwartz closed this 9 minutes ago

I am more disappointed than ever.

**Comment by eli-schwartz** [comment]
> **Upstream ISN'T interested in Meson support**

Then they should probably delete it, if it is known to not work.

> Many projects needs same wraps, this is tree of D packages.

They need the same exact meson.build, including project('name') and the list of files?

The wrapped meson.build at https://github.com/D-meson/taggedalgebraic_meson_overlay/blob/master/meson.build is very specific to one project, that being "taggedalgebraic" with corresponding:
- library() name
- executable() test name prefix
- install_headers() subdir
- names of files() added as sources

Or, do you mean many projects need to include a taggedalgebraic.wrap?

In that case, you could add them all to a project called "d-wraps-collection", and add the "d-wraps-collection" project as a subproject of any project that needs wraps. meson will then recursively resolve the wraps, and promote them from "d-wraps-collection" to the parent project.

This would allow you to use patch_directory and collect all projects in one git repo, but ***use*** them in multiple locations.

**Comment by xclaesse** [comment]
@denizzzka Can you please explain why you don't fork upstream git repository in github and make your wrap-git point to the fork? That seems a lot easier than maintaining an overlay in a git repository. Personally I always found overlays in wraps super weird, I would ditch the whole thing and rely purely on git branches if it was up to me.

**Comment by eli-schwartz** [comment]
(@xclaesse overlays are required for release archives, to make the wrapdb work nicely and to avoid the need to audit a fork. I agree they make no sense for wrap-git, which tends to be quite personal and limited to one project which may be contributing to the development of the wrapped subproject, but apparently "there was demand" so idk. It is kind of your fault, you're the author of `wrap: Apply patch even in VCS cases` :p)

**Comment by denizzzka** [comment]
@xclaesse
> Can you please explain why you don't fork upstream git repository in github and make your wrap-git point to the fork? That seems a lot easier than maintaining an overlay in a git repository.

My experience: average-sized project that takes about 20 commits per week and ~15 releases per year there are almost no changes - for more than one year it took only one intervention in meson.build.

> Personally I always found overlays in wraps super weird, I would ditch the whole thing and rely purely on git branches if it was up to me.

In any case, for Meson community this proposal does not break anything and improves user experience (https://github.com/mesonbuild/meson/issues/9085#issuecomment-895810451)

**Comment by denizzzka** [comment]
> Or, do you mean many projects need to include a taggedalgebraic.wrap?

This

> In that case, you could add them all to a project called "d-wraps-collection", and add the "d-wraps-collection" project

Wraps can contain different versions (revisions) for same repositories, depends of needings of each user. I can't assembly all possible versions of wrap files into one repository.

> as a subproject of any project that needs wraps. meson will then recursively resolve the wraps, and promote them from "d-wraps-collection" to the parent project.

> This would allow you to use patch_directory and collect all projects in one git repo, but use them in multiple locations.

Perhaps I explained something wrong

There are about a ~hundred D packages that I want to wrap.
And about 20 packages already have the wrong meson.build files on board

(The existing system already allow to maintain this by wrap subsystem, it is only need to accept discussed here enhancement)
