### ISSUE TITLE
IndexError with `custom_target(…, output: [], build_by_default: true)` in a `subdir()`

### ISSUE THREAD

**Issue by rusty-snake** [mesonbuild/meson#9096]
**Describe the bug**

`custom_target(…, output: [], build_by_default: true)` in a `subdir()` causes a `IndexError`.

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mesonbuild/mesonmain.py", line 227, in run
    return options.run_func(options)
  File "/usr/lib/python3.9/site-packages/mesonbuild/msetup.py", line 281, in run
    app.generate()
  File "/usr/lib/python3.9/site-packages/mesonbuild/msetup.py", line 184, in generate
    self._generate(env)
  File "/usr/lib/python3.9/site-packages/mesonbuild/msetup.py", line 246, in _generate
    intr.backend.generate()
  File "/usr/lib/python3.9/site-packages/mesonbuild/backend/ninjabackend.py", line 559, in generate
    self.generate_ending()
  File "/usr/lib/python3.9/site-packages/mesonbuild/backend/ninjabackend.py", line 3209, in generate_ending
    targetlist.append(os.path.join(self.get_target_dir(t), t.get_outputs()[0]))
IndexError: list index out of range
```

Omitting `build_by_default: true` or doing this in the project root does not cause a `IndexError`. However `ninja.build` seems to have a syntax error.

```
ninja: error: build.ninja:31: expected path
build : CUSTOM_COMMAND ../sub1/infile | /bin/true
      ^ near here
WARNING: Could not create compilation database.
ninja: Entering directory `_builddir'
ninja: error: build.ninja:31: expected path
build : CUSTOM_COMMAND ../sub1/infile | /bin/true
      ^ near here
```

**To Reproduce**

```console
$ mkdir -p test01/sub1
$ cd test01
$ touch sub1/infile
$ cat meson.build
project('test01')

subdir('sub1')
$ cat sub1/meson.build
custom_target('index-error', command: ['/bin/true'], input: 'infile', output: [], build_by_default: true)
$ meson setup _builddir && meson compile -C _builddir
```

**Expected behavior**

If `output` must not be empty a error message like `src/meson.build:42:0: ERROR: output must not be empty`.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
  native
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
  Fedora 34
* what Python version are you using e.g. 3.8.0
  3.9.6
* what `meson --version`
  0.59.0
* what `ninja --version` if it's a Ninja build
  1.10.2

**Comment by eli-schwartz** [comment]
I think I understand enough of how this works now, that I'm going to try tonight to switch to typed_kwargs and fix this.

**Comment by dcbaker** [comment]
@eli-schwartz I'm working on that right now actually.

**Comment by eli-schwartz** [comment]
Excellent, so I don't need to bother in that case.

(As mentioned in IRC, yours was already partially done from before, and I haven't even started. This means I get to be lazy again.)
