### ISSUE TITLE
"Cannot open XML file" with gnome.yelp targets

### ISSUE THREAD

**Issue by rmnvgr** [mesonbuild/meson#9105]
**Describe the bug**

When using the targets from [`gnome.yelp`](https://mesonbuild.com/Gnome-module.html#gnomeyelp), it only gives this error:

```
[0/1] Running external command help-project-pot (wrapped by meson to set env)
Error: cannot open XML file C/index.page
```

I checked that the file is at the right path, and that the permissions are correct. It not only happens on my project but also on other projects using `gnome.yelp`. I also tried in a clean VM to make sure it was not a problem with my setup. If I manually run `itstool`, it works fine.

**To Reproduce**

`meson.build`:

```meson
project('test')

import('gnome').yelp(
  'test',
  sources: ['index.page']
)
```

`C/index.page`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<page xmlns="http://projectmallard.org/1.0/" xmlns:its="http://www.w3.org/2005/11/its" type="guide">
	<title>Test</title>
</page>
```

Empty `LINGUAS` file.

Run `meson build && meson compile -C build help-test-pot`.

**Expected behavior**

The targets execute correctly and generate the translation files.

**System parameters**

* OS: Fedora 34
* Python version: 3.9.6
* `meson --version`: 0.59
* `ninja --version`: 1.10.2

**Comment by eli-schwartz** [comment]
This is reproducible in `test cases/frameworks/13 yelp/`, and I can verify that @pabloyoyoista's PR fixes it.
