### ISSUE TITLE
Response file needed for Fortran project on Linux

### ISSUE THREAD

**Issue by matcross** [mesonbuild/meson#9129]
Inspired by #7212.

A project with lots of Fortran source:

```sh
#!/bin/sh
set -eu
work_dir=meson_toolong
build_dir=b
n=12000
mkdir -p ${work_dir}
cd ${work_dir}
rm -rf ${build_dir}
{
  echo "project('toolong', 'fortran')"
  echo "srcs = ["
} > meson.build
for i in $(seq -w ${n})
do
  src_file=f${i}.f90
  {
    echo "Subroutine s${i}"
    echo "End"
  } > "${src_file}"
  echo " '${src_file}'," >> meson.build
done
{
  echo "]"
  echo "library('toolong', srcs)"
} >> meson.build
meson . ${build_dir}
cd ${build_dir}
ninja -v
```

gives

```
The Meson build system
Version: 0.59.0
Source dir: /home/mat_cross/documents/Meson/resp/meson_toolong
Build dir: /home/mat_cross/documents/Meson/resp/meson_toolong/b
Build type: native build
Project name: toolong
Project version: undefined
Fortran compiler for the host machine: gfortran (gcc 11.2.1 "GNU Fortran (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1)")
Fortran linker for the host machine: gfortran ld.bfd 2.35.2-4
Host machine cpu family: x86_64
Host machine cpu: x86_64
Build targets in project: 1

Found ninja-1.10.2 at /usr/bin/ninja
ninja: fatal: posix_spawn: Argument list too long
```

(Python is 3.9.6).

**Comment by dcbaker** [comment]
Are you generating a static library, or a shared library?

**Comment by matcross** [comment]
> Are you generating a static library, or a shared library?

As per the Meson default via my shell script above (so, shared?)
It seems like it's falling over during ninja dependency generation.

**Comment by dcbaker** [comment]
For me it falls over trying to do the depscan step, which is a python program we maintain.

**Comment by dcbaker** [comment]
I've opened a PR with a fix for this, it should be in the 0.60 release

**Comment by matcross** [comment]
> I've opened a PR with a fix for this, it should be in the 0.60 release

Thanks, that does help.
Unfortunately the subsequent .so creation indeed goes on to fail as well:

```
> ninja libtoolong.so
[0/1] Linking target libtoolong.so.ninja: fatal: posix_spawn: Argument list too long
```

**Comment by dcbaker** [comment]
What version of Meson do you have? that works fine for me on git master

**Comment by matcross** [comment]
Sorry, my fault. It's looking good from your submit/depscan-file-limit branch.
Thanks again for the fix.
