### ISSUE TITLE
Version require check should have a fallback solution since 0.59.1

### ISSUE THREAD

**Issue by nyfair** [mesonbuild/meson#9138]
https://github.com/mesonbuild/meson/blob/e2f4126e415abedf0af90a30332e5e72c98b3d9e/mesonbuild/dependencies/base.py#L363-L374

The commit description sounds reasonable. However, the version attribute is not always available from all `DependencyMethods`.
e.g. 
I build lua with visual studio, meson can't find lua's version and I have to create a fake pkg-config script for that.
This is quite inconvenient and it should have a fallback solution.

**Comment by xclaesse** [comment]
Just don't set a version requirement in the case the dependency does not define a version?

**Comment by nyfair** [comment]
> 
> 
> Just don't set a version requirement in the case the dependency does not define a version?

Meson are widely used today, It is impossible to inform all the project maintainers to do as you said

**Comment by xclaesse** [comment]
Note that before that commit it was inconsistent, if the dependency was required then it would abort and if it is not required it would return found dependency instead of not found.

Why does your project requires a specific version of Lua if their pkg-config does not specify a version?

**Comment by nyfair** [comment]
No, according to
https://github.com/mesonbuild/meson/blob/e2f4126e415abedf0af90a30332e5e72c98b3d9e/mesonbuild/dependencies/base.py#L153-L157
If the dependency was required, it will return found unknown version and pass the version check before this commit.

I was building another project with lua, the project require a specific version of lua and the project itself is no longer maintained.
This is a simple regression issue, please don't debate about `what is wrong/correct usage`

**Comment by eli-schwartz** [comment]
It was a bug that it ever claimed to be found, if you require a specific version and that version isn't found then your requirement constraints have failed.

It's not a regression. You are relying on behavior that is:
- buggy
- *explicitly* documented to not work

If you were arguing that you were relying on buggy behavior that was either documented to work, or wasn't documented one way or the other, then you would have valid grounds to call this a regression.

>  I build lua with visual studio, meson can't find lua's version and I have to create a fake pkg-config script for that.
> This is quite inconvenient and it should have a fallback solution.

This should not be so terribly inconvenient as all that, in fact I don't understand why it is inconvenient to begin with. How are you currently finding it, *without* a pkg-config file? Are you using cmake? The FindLua.cmake correctly detects the version for me, and thus, `dependency('Lua', version: '>=5.4', required: true, method: 'cmake')` logs this:

```
Found CMake: /usr/bin/cmake (3.21.1)
Run-time dependency lua found: YES 5.4.3
```

If you have no pkg-config file *and* you are not detecting it via cmake, then which dependency method are you using? We only offer the two of them, plus subproject wraps (which correctly set the version, see e.g. the wrapdb's lua.wrap).

**Comment by xclaesse** [comment]
> I was building another project with lua, the project require a specific version of lua and the project itself is no longer maintained.

Which project is that, and how do they lookup the lua dependency exactly? Also, what does your lua.pc file contain?

Seems to work for me at least:
```
$ pkg-config --modversion lua-5.3
5.3.3
```

**Comment by xclaesse** [comment]
>  If the dependency was required, it will return found unknown version and pass the version check before this commit.

I don't think so. But instead of speculating on what the code does, I would prefer having a concrete test-case that proves it :)

**Comment by xclaesse** [comment]
> https://github.com/mesonbuild/meson/blob/e2f4126e415abedf0af90a30332e5e72c98b3d9e/mesonbuild/dependencies/base.py#L153-L157

Note that `_check_version()` uses `self.version` and not `self.get_version()`, so it gets empty string and not `unknown`. AFAIK `get_version()` is the string to display.

**Comment by nyfair** [comment]
@xclaesse 
Build lua with visual studio, you will have lua.lib. Install neither cmake nor pkg-config, then create a dummy meson project and
```
dependency('lua', version: '>=5.1')
```

@eli-schwartz 
Plz don't debate about `what is correct/wrong usage`.
I just found this problem and I don't use meson on my project. Tell me how to use meson is pointless and I'm not concern about how other projects use meson.
Simply revert this commit and the problem gone away.

**Comment by xclaesse** [comment]
@nyfair how does it find lua at all if you don't have neither pkg-config nor cmake? Does it build it as a subproject? Maybe share the meson-logs with us. Before debating the solutions, I would like to be sure to understand the problem...

**Comment by nyfair** [comment]
@xclaesse 
https://github.com/mesonbuild/meson/blob/12e5bfbc1c1c387fc3ea7a1b12bac6ddd068c3f1/mesonbuild/dependencies/base.py#L47-L48

**Comment by eli-schwartz** [comment]
> Build lua with visual studio, you will have lua.lib



> `dependency('lua', version: '>=5.1')`

This doesn't make sense to me, since meson's dependency() function doesn't look up raw libraries -- if you want that, use `cc.find_library()`.

So I can only conclude that you're mistaken, and this never used to work.

>  Plz don't debate about `what is correct/wrong usage`.
> I just found this problem and I don't use meson on my project. Tell me how to use meson is pointless and I'm not concern about how other projects use meson.

So you're not interested in:
- using meson
- using meson correctly
- listening to meson developers explain how meson works
- listening to meson developers tell you that you were never able to do what you say you were able to do
- listening to meson developers suggest using the wrapdb to build lua, rather than using visual studio to build lua

The mechanism you used before to build lua.lib has never, ever, ever been supported by meson, and I don't understand how it could work either with or without this commit, since we've always documented that dependency() does not work to detect raw libraries, and meson contains no code to do so.

I listed 3 different ways meson has always supported finding lua, but you don't want to use any of them even though they are really easy.

Instead you want to revert a commit that has nothing to do with this at all.

P.S. The "SYSTEM" dependency method means that mesonbuild.dependencies.* contains a FooSystemDependency custom class, it does not mean that you can look up raw libraries.

**Comment by nyfair** [comment]
@xclaesse 
meson.log is quite simple
0.59.0
Dependency lua found: NO unknown version, but need: ['>=5.1']
Run-time dependency shaderc found: YES
0.59.1
Dependency lua found: NO unknown version, but need: ['>=5.1']
Run-time dependency shaderc found: NO

@eli-schwartz 
As I said, I already tried the pkg-config way for workaround before open this issue, why do you say that `I'm not interested in your suggesion?`
It is you that have no interesting to find a fallback solution.

**Comment by nyfair** [comment]
@xclaesse 
meson.log is quite simple
0.59.0
Dependency lua found: NO unknown version, but need: ['>=5.1']
Run-time dependency shaderc found: YES
0.59.1
Dependency lua found: NO unknown version, but need: ['>=5.1']
Run-time dependency shaderc found: NO

@eli-schwartz 
As I said, I already tried the pkg-config way for workaround before open this issue, why do you say that `I'm not interested in your suggesion?`
It is you that have no interesting to find a fallback solution.

**Comment by xclaesse** [comment]
I _think_ what happens here is VisualStudio does includes cmake and meson uses it to find lua library, and @nyfair wasn't aware of that. But would need to logs to be sure.

Again, it's better to explain the problem before coming with solutions. Depending on the problem there could be other ways to fix it ;-)

**Comment by xclaesse** [comment]
>  0.59.0
> Dependency lua found: NO unknown version, but need: ['>=5.1']
> Run-time dependency lua found: YES

Can you please attach builddir/meson-logs/meson-logs.txt, it should have more details how it found lua. I'm suspecting it's using cmake, but I'm not sure.

**Comment by eli-schwartz** [comment]
I mentioned above that I tested cmake, cmake correctly detects the version of lua and reports it to meson.

There is a caveat that you need to use `dependency('Lua')` because cmake supports `find_package(Lua)` but not `find_package(lua)`.

**Comment by nyfair** [comment]
@xclaesse 
No, I know the cmake way can also workaround this. If I tried this solution, the log will contain
(tried pkgconfig)

**Comment by xclaesse** [comment]
@nyfair ok, so it is even more important to share with us the detailed logs, because I have no idea how meson could find that dep at all.

**Comment by nyfair** [comment]
@xclaesse 
`meson.log` just provide the 2 lines about lua

meson found lua by pass -l flag to c compiler, according to
https://github.com/mesonbuild/meson/blob/e2f4126e415abedf0af90a30332e5e72c98b3d9e/mesonbuild/dependencies/base.py#L108-L113
Anyway, as eli-schwartz said, this is not suggested.

**Comment by eli-schwartz** [comment]
The -I flag to the c compiler is for header include paths, not libraries, and the function you linked to here, is a function for transforming header includes from -I to -isystem in case the dependency specifies `include_type: 'system'`.

> `include_type` (since 0.52.0): an enum flag, marking how the dependency flags should be converted. Supported values are `'preserve'`, `'system'` and `'non-system'`. System dependencies may be handled differently on some platforms, for instance, using `-isystem` instead of `-I`, where possible. If `include_type` is set to `'preserve'`, no additional conversion will be performed. The default value is 'preserve'.

**Comment by eli-schwartz** [comment]
>  `meson.log` just provide the 2 lines about lua

Robust bug reporting standards still means to post the entire log no matter what. As it is, we do not understand how lua could ever be found, even with an unknown version, which means we do not see how this could be a regression.

**Comment by nyfair** [comment]
> 
> 
> The -I flag to the c compiler is for header include paths, not libraries, and the function you linked to here, is a function for transforming header includes from -I to -isystem in case the dependency specifies `include_type: 'system'`.
> 
> > `include_type` (since 0.52.0): an enum flag, marking how the dependency flags should be converted. Supported values are `'preserve'`, `'system'` and `'non-system'`. System dependencies may be handled differently on some platforms, for instance, using `-isystem` instead of `-I`, where possible. If `include_type` is set to `'preserve'`, no additional conversion will be performed. The default value is 'preserve'.

I don't say it is for libraries, why do you always want to guess my thought?
I'm not member of meson project and just want to find a better solution for this.

**Comment by nyfair** [comment]
@eli-schwartz 
You're enough, I already find my solution before I open this issue.
If you have no interest to resolve this, me too.

**Comment by eli-schwartz** [comment]
> meson found lua by pass -I flag to c compiler, according to

But it didn't find lua by passing -I flag to the c compiler, due to the explanation I gave about what that function actually does.

>  I'm not member of meson project and just want to find a better solution for this.

The best way to do so, would be to ensure that the meson project understands your use case, i.e. how you used to use meson, and in what manner your meson-logs.txt claims lua got detected.

There is nothing we can do if you refuse to share the debug log.

**Comment by nyfair** [comment]
> But it didn't find lua by passing -I flag to the c compiler, due to the explanation I gave about what that function actually does.
Certainly It should found lua by passing -I and -L flags to compiler and linker if these files are already there. You can simply verify this by try using cl.exe or gcc.exe.

> There is nothing we can do if you refuse to share the debug log.
Have you tried to build lua with visual studio? There is also nothing I can do if you refuse to cooperate.

**Comment by eli-schwartz** [comment]
> Certainly It should found lua by passing -I and -L flags to compiler and linker if these files are already there. You can simply verify this by try using cl.exe or gcc.exe.

As I stated up above:

> meson's dependency() function doesn't look up raw libraries -- if you want that, use `cc.find_library()`.

`cc.find_library('lua')` looks for lua.lib

`dependency('lua')` does not, and instead looks for pkg-config or cmake ***PROJECT*** metadata, which is responsible for emitting -l and -L and -I and -isystem flags, which meson does not autodetect and never has.

in mesonbuild/dependencies/misc.py, it is possible to do the equivalent of FindFoo.cmake, and internally run cc.find_library(), then convert that into a dependency() satisfier. This is the only exception in which meson will autodetect -L and -l flags to see if these files are already there.

mesonbuild/dependencies/misc.py is not, and never has been, permitted to be extended by third-party sources. Every single autodetection class must be installed with the official meson installer. The list of custom autodetection classes does not include lua, though in theory someone could add a lua detection class in future versions of meson.

> Have you tried to build lua with visual studio? There is also nothing I can do if you refuse to cooperate.

I do not possess visual studio. You do possess the debug log.

I am physically unable to try your setup. Nevertheless, I've reviewed the meson codebase and gone out of my way to test various dependency satisfiers such as cmake, trying to figure out how your problem could have occurred. You are stubbornly unwilling to share the full debug log which you already have and posted the wrong 2 lines from.

I would like to help you, but you're not letting me.

**Comment by xclaesse** [comment]
> Have you tried to build lua with visual studio? There is also nothing I can do if you refuse to cooperate.

I could give it a try, I have a Windows machine with VisualStudio, but you haven't given steps how you built Lua and how your project is setup to find where you installed lua. We can't spend time on trying to guess, we need a clear step-by-step instructions that we can easily reproduce.

I understand you found that this is a regression in Meson, but we can't just revert a commit without understanding the root cause. It is possible the real bug is somewhere else. There could be something I don't know in Meson, but my understanding is `dependency('lua', version: '>=5.1')` cannot work without pkg-config or cmake. It should never have worked and that suggest there is something else going on.
