### ISSUE TITLE
[Enhancement of an existing ERROR message] "First statement must be a call to project"

### ISSUE THREAD

**Issue by rubyFeedback** [mesonbuild/meson#9144]
Hey meson folks,

Sorry if this already exists but I wanted to report it anyway.

I am trying meson on windows. Windows is annoying ...

... but I also fail syntax-wise. So now my noob-level comes through.

On linux I can use meson fine via:

    meson --prefix=/usr --libdir=/usr/lib BUILD_DIRECTORY

On windows, where I am using msys2 (which might be a reason
why the error message is shown), I get instead this:

    ERROR: First statement must be a call to project

With exactly the same code (atk, from gtk), and the same
content of that command. So it fails on windows with that
error.

The error does not tell me anything. What does "first statement"
mean? Why is the syntax wrong?

Would it be possible to add an extra line to this, perhaps
showing examples how to use it correctly? Because right now
I am confused why it works on linux but not on windows. Msys
may be the culprit, but even then I think the error message
should be better. Compiling a .c hello world works fine via
gcc by the way, on windows. I could run a.exe too just fine.
So I can compile stuff in general on that windows machine;
I just fail syntax-wise or something right now... but the
syntax is the same so ... odd error message. Not very
helpful error message! Googling for this didn't yield
tons of useful results... hopefully future people can find 
this issue tracker and know what to do better instead. Cheers!

**Comment by QuLogic** [comment]
Something that's different on Windows is line endings. Probably when you cloned/downloaded the code, it had one set of line endings, and Meson is reading it with a different type of line endings. I don't know whether msys2 prefers Windows line endings, or emulates Unix line endings preferences. But if Meson is reading with Windows line endings, and the files are all using Unix line endings, the entire file will appear to be on one line.

**Comment by eli-schwartz** [comment]
How is this different from #3426 which you already commented on? If it is just windows/unix line ending differences, surely this should be noticeable if you open the file to check whether the first line contains a project() function call.

(The error message has been clarified a bit there.)
