### ISSUE TITLE
alias_target that depends on a run_target is quite broken

### ISSUE THREAD

**Issue by eli-schwartz** [mesonbuild/meson#9175]
While testing #9174, I tried to create the target I alluded to, there.

In lib/libalpm/po/meson.build I added:

```
lib_mo = i18n.gettext(...) # this used to not be saved

alias_target('regenerate-all-pot', lib_mo[1])
```

In my build.ninja, I ended up with:

```
build regenerate-all-pot: phony  | lib/libalpm/po/libalpm-pot
```

This is plainly wrong!

It's reproducible with a simple meson.build

```
$ cat meson.build
project('foo', 'c')

subdir('in_subdir')
$ cat in_subdir/meson.build
r = run_target('run_a_target', command: ['echo', 'ran a target'])
alias_target('aliased_run_a_target', r)
```

However, it is not reproducible in released meson at all, because instead I get:

```
in_subdir/meson.build:2:0: ERROR: Depends items must be build targets.
```

This seems like a regression from commit 982973f303e3d0431d9b79f89cdf2c8f1ee67bc0 which removed that error message and made it accept any build.Target -- which I then assumed should work while testing my PR...
/cc @dcbaker 

I would actually sort of kind of like this to work properly as I'd like an alias_target that lets me run the i18n.gettext() pseudo-targets for multiple gettext domains in a single ninja invocation. Currently we have a 40-line shell script which spends most of its time trying to find the builddir.

**Comment by tristan957** [comment]
I remember trying this a while back and it being broken. Thanks for reporting it.

**Comment by xclaesse** [comment]
We cannot make a target that depends on a run_target(), because at the ninja level a target depends on the output file of another target, but run_target() has no output file.

The workaround you can do is replacing your run_target() by a custom_target() that generates a dummy file and make it always_stale.

**Comment by eli-schwartz** [comment]
Clearly we can and do right now, so I don't at all understand where you're getting this belief from.

It's a "phony" target, but of course it exists!

```
build libalpm-pot: phony meson-libalpm-pot

build meson-libalpm-pot: CUSTOM_COMMAND 
```

This is generated by the basic builtin functionality. The objective here is to get back some handle for that ninja target, which is *already* called `meson-libalpm-pot` but aliased as `libalpm-pot`, to add even more aliases.

> The workaround you can do is replacing your run_target() by a custom_target() that generates a dummy file and make it always_stale.

I can't replace my anything, the run_target is internally generated by import('i18n'). The only reason this ticket doesn't *already* work, is because the name yielded is broken due to containing the subdir path.

**Comment by eli-schwartz** [comment]
So I think I've figured this out, actually. This works locally, at least.

**Comment by eli-schwartz** [comment]
@dcbaker given that, do you think it makes sense to indeed accept any build.Target?

**Comment by eli-schwartz** [comment]
Yeah see the ninja manual's description of the special-cased nature of the rule target `phony`.

As I pointed out, meson's current implementation creates several such rules already, although not modeled as run_targets.

**Comment by xclaesse** [comment]
Another question is if we can do that on other backends too? If we document this behaviour it must work on all backends, otherwise it needs to be left UB.

**Comment by eli-schwartz** [comment]
I really have no idea about other backends... I assume if they don't support interdependencies for phony / build_always_stale rules then alias_target() in general is *probably* broken for them?

**Comment by xclaesse** [comment]
Let's ignore that for now, I noticed alias_target() unit test is already skipped for vs backend anyway...

**Comment by ManuelAtWork** [comment]
> Let's ignore that for now, I noticed alias_target() unit test is already skipped for vs backend anyway...

On backends that do not support phony targets, meson may create a dummy file by a regular target instead.
