### ISSUE TITLE
[Question / Roadmap] Meson 1.0?

### ISSUE THREAD

**Issue by rubyFeedback** [mesonbuild/meson#9220]
Yo there meson devs and meson users,

This is on the one hand an honest question: when will meson 1.0 be released?

The canonical answer will probably be "when it is ready".

But there is a second part to it, more along the lines of ... "is there a roadmap for
meson 1.0"? And I'll explain that second part a little bit so it is understood where
I am coming from.

I have quite some experience in compiling software from source from the user
point of view. That is, I download tarballs, let ruby extract them and compile
them for me.

As a result I know a little how GNU autoconf/configure works, cmake, meson,
waf, scons ... and I can compare. I can not say "this is best", because it all
depends on what you compare. To give a simple example: I think cmake
is better than GNU configure, but I love --disable-something in GNU
configure whereas in cmake we have to use something like
-DENABLE_THERE_BE_DRAGONS=on or something.

From all the build tools so far, I actually think meson/ninja is best, for
several reasons. This is the primary reason why I am asking for whether
there is a roadmap, and if so, what will have to happen for a 1.0 release.

I see more and more projects transition into meson and while GNU
configure is still used by the majority of programs that I compile from
source, both cmake and meson are taking over. 

For example, in my local database of 3735 programs (September 2021)
I have the following statistics:

    575 programs depend on cmake.  15.4% ( 575 / 3735)
    303 programs depend on ruby.    8.1% ( 303 / 3735)
    181 programs depend on python.  4.8% ( 181 / 3735)
    168 programs depend on meson.   4.5% ( 168 / 3735)
     62 programs depend on perl.    1.7% (  62 / 3735)
     14 programs depend on scons.   0.4% (  14 / 3735)
      3 programs depend on waf.     0.1% (   3 / 3735)

The rest use either GNU configure or simply "make" via
a Makefile. This is not 100% correct, and my view is 
biased because I don't track everything. Debian probably
can give a better overview that is more accurate. But!
Most of the software I track is recent and still active
or actively maintained (or has been in the last ~3 years
or so). And the trend I am seeing is that both cmake and
meson are growing in adoption whereas GNU configure 
stagnates, or loses out (because projects that are 
still maintained often switch into cmake or meson).

So this is mostly the point of view I am coming from -
I am interested in that long-term trend, and a 1.0 
milestone, even if arbitrary as a number, is still kind
of interesting to know when meson will reach 1.0 and 
how/if under which conditions.

Please feel free to close this issue at any moment in
time, but if done perhaps a few short comments could
be made pertaining to the question. Thank you.

**Comment by dcbaker** [comment]
I'm not sure what is really left before we get to 1.0, other than wanting to remove deprecated things. It might be time to have that discussion again.

**Comment by xclaesse** [comment]
IMHO the version number makes no difference, we should not remove deprecated stuff just for the pleasure of annoying our users. We should remove deprecated stuff after a while only if they are actively in the way of some bigger refactoring. That's what we have been doing so far and should continue to do after 1.0.

**Comment by xclaesse** [comment]
In other word, in my opinion we are already well past 1.0.

**Comment by jpakkane** [comment]
The one thing I would like to see done before 1.0 is better custom generation of stuff. There is a MR that was inspired by the needs of LibreOffice, but sadly that never really got anywhere.

**Comment by dcbaker** [comment]
I also think finishing the language type safety work would be nice, but once we hit 1.0 we have to decide if we're going to not remove features until 2.0, which is very common for projects to do

**Comment by taozuhong** [comment]
Could Meson collect build time to show after the final build step?

![image](https://user-images.githubusercontent.com/13451009/181428443-ebdc261c-d059-4873-8799-158b7a00a77e.png)

**Comment by jpakkane** [comment]
The actual build steps are executed by Ninja, not Meson. I don't think there is a way to make it tell the whole build time, though you can replicate the same by compiling with `time ninja`.

**Comment by tristan957** [comment]
@eli-schwartz seems like this can be closed since 1.0.0 was released?

**Comment by eli-schwartz** [comment]
Yesssssssssssss!

\o/
