### ISSUE TITLE
Feature Request: support meson `run` command just like cargo run 

### ISSUE THREAD

**Issue by shrkamat** [mesonbuild/meson#9231]
**Describe the bug**
It will be great if we can have a command to run generated binary in meson. Tools like cargo supports this.

**To Reproduce**
NA

**Expected behavior**
`meson run -C build_dir` should run generated binary.

It would further improve workflow with [plugins](https://github.com/igankevich/mesonic).

**Comment by xclaesse** [comment]
We already have it: https://mesonbuild.com/Commands.html#devenv

**Comment by shrkamat** [comment]
@xclaesse thanks for the update. I have now migrated to meson 0.59.1 and able to use `devenv`. There is one subtle difference between cargo `run` and meson `devenv`. 

`cargo run` does not need binary file to be mentioned in the command. While devenv needs the binary name.

I would have to use `meson devenv -C build_dir ./output_file_name`. I can always add this in my build file, but it will be great if an evn is exported as a standard from meson build file. Only challenge I see is there could be multiple binary files not sure how it should work in that case.

**Comment by eli-schwartz** [comment]
`meson devenv -C build_dir` will spawn an interactive shell with the devenv set up. What kind of exported env do you want to see?

**Comment by shrkamat** [comment]
> 
> 
> `meson devenv -C build_dir` will spawn an interactive shell with the devenv set up. What kind of exported env do you want to see?

`meson devenv -C build_dir ./$MESON_BIN_NAME` would be great

**Comment by eli-schwartz** [comment]
As you yourself mentioned in the previous comment, that works too.

Again, I do not understand what it is that you believe is missing.

**Comment by eli-schwartz** [comment]
BTW there is an obvious difference from cargo, in that meson can and does build multiple programs per project all the time, and obviously cannot just arbitrarily choose one of them to run by default. Cargo has a much more limited scope, by and large, and can make that assumption safely.

**Comment by shrkamat** [comment]
@eli-schwartz thanks I kind of get the difference between cargo and meson. I will ask my question in a bit different manner.

How would you propose for an ide to run binary generated by meson build assuming meson build will have only one binary generated.

**Comment by eli-schwartz** [comment]
Oh, IDEs you say? Thank you for clarifying that... that was not at all obvious from your initial question.

https://mesonbuild.com/IDE-integration.html#the-targets-section

Using the exported information designed to be available to IDEs, which provides a list of executable() build targets. And naming the one you want, even if there is only one to begin with.

**Comment by vpzomtrrfrt** [comment]
cargo also can build multiple targets, and in that case it requires the user to specify which to run by default
