### ISSUE TITLE
Value "gnu89" (of type "string") for combo option "C language standard to use" is not one of the choices. Possible choices are (as string): "none", "c89", "c99", "c11", "c17", "gnu99", "gnu11".

### ISSUE THREAD

**Issue by ryandesign** [mesonbuild/meson#9237]
Building glib2 2.62.6 with meson 0.59.1 fails:

```
Value "gnu89" (of type "string") for combo option "C language standard to use" is not one of the choices. Possible choices are (as string): "none", "c89", "c99", "c11", "c17", "gnu99", "gnu11".
```

With meson 0.58.1 there was no such error.

See https://trac.macports.org/ticket/63462

In #8766 gnu99 and gnu11 were added to the list of possible choices but for some reason gnu89 was not added? Could you add it, please?

**Comment by eli-schwartz** [comment]
Makes sense... the ones that were added got added due to https://github.com/mesonbuild/meson/commit/c54dd63547b030e3d9feee694ec6f49c434f0df8#r50842919

The request to add the GNU ones only called out some of the possible stds, and only those ones got added.

Would you like to submit a patch?

**Comment by ryandesign** [comment]
No, I would just like someone to fix it.

**Comment by eli-schwartz** [comment]
Done, and fixed a few more inconsistencies while I was at it.
