### ISSUE TITLE
Latest Meson + tags raises exception when used with dir created by prev. Meson version

### ISSUE THREAD

**Issue by Hi-Angel** [mesonbuild/meson#9260]
**Describe the bug**

Creating a `build` dir with previous version of Meson, and then using on that dir `meson install --tags foo` with newer Meson results in exception:

```
Traceback (most recent call last):
  File "/home/constantine/Projects/meson/mesonbuild/mesonmain.py", line 228, in run
    return options.run_func(options)
  File "/home/constantine/Projects/meson/mesonbuild/minstall.py", line 747, in run
    installer.do_install(datafilename)
  File "/home/constantine/Projects/meson/mesonbuild/minstall.py", line 538, in do_install
    self.install_targets(d, dm, destdir, fullprefix)
  File "/home/constantine/Projects/meson/mesonbuild/minstall.py", line 634, in install_targets
    if not self.should_install(t):
  File "/home/constantine/Projects/meson/mesonbuild/minstall.py", line 381, in should_install
    if self.tags and d.tag not in self.tags:
AttributeError: 'TargetInstallData' object has no attribute 'tag'
```

**To Reproduce**

In steps, I use `meson` of latest released version `0.59.1` and `~/Projects/meson/meson.py` which is the latest in-development Meson at commit 87e13af1c85c03

```
 λ cat meson.build
project(
  'test',
  ['c'],
)

subdir('bar/')
 λ cat bar/meson.build
executable(
  'bar',
  ['test.c'],
  install: true
)
 λ cat bar/test.c
int main() {}
 λ meson build
The Meson build system
Version: 0.59.1
Source dir: /tmp/foo
Build dir: /tmp/foo/build
Build type: native build
Project name: test
Project version: undefined
C compiler for the host machine: ccache cc (gcc 11.1.0 "cc (GCC) 11.1.0")
C linker for the host machine: cc ld.bfd 2.36.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Build targets in project: 1

Found ninja-1.10.2 at /usr/bin/ninja
 λ cd build
 λ ~/Projects/meson/meson.py install --tags foo
ninja: Entering directory `/tmp/foo/build'
[2/2] Linking target bar/bar
Traceback (most recent call last):
  File "/home/constantine/Projects/meson/mesonbuild/mesonmain.py", line 228, in run
    return options.run_func(options)
  File "/home/constantine/Projects/meson/mesonbuild/minstall.py", line 747, in run
    installer.do_install(datafilename)
  File "/home/constantine/Projects/meson/mesonbuild/minstall.py", line 538, in do_install
    self.install_targets(d, dm, destdir, fullprefix)
  File "/home/constantine/Projects/meson/mesonbuild/minstall.py", line 634, in install_targets
    if not self.should_install(t):
  File "/home/constantine/Projects/meson/mesonbuild/minstall.py", line 381, in should_install
    if self.tags and d.tag not in self.tags:
AttributeError: 'TargetInstallData' object has no attribute 'tag'
```

**Expected behavior**

No exception

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build ? Native
* OS: Archlinux
* Python version: 3.9.6
* `meson --version`: 0.59.1 and Meson at commit 87e13af1c85c03
* `ninja --version`: 1.10.2

**Comment by xclaesse** [comment]
Mixing meson versions has never been supported, after updating Meson you have to reconfigure your project with --wipe. Meson abort with a proper error message when major version differ, but since you're using git master the version is 0.59.99 which has same major version as 0.59.1. I don't think this is a use-case we should be supporting, so closing this issue.

**Comment by Hi-Angel** [comment]
> Meson abort with a proper error message when major version differ, but since you're using git master the version is 0.59.99 which has same major version as 0.59.1.

Shouldn't there be a check for that "99" version in place? I mean, usually project encourage their users to test non-released version and report any bugs. So that's what I did, and it turned out you and me both just wasted our time. If there was a check for `99` version to cause reconfiguration, current report would have never happened.

**Comment by eli-schwartz** [comment]
But then people will still have issues, because they originally used 0.59.99 and everything was fine, but then they `git pull`ed one more commit and the version was still 0.59.99 but it was a *different* `99` commit that was incompatible.

It's not feasible to track internal coredata compatibility during/inside the lifetime of git master, which is why we do not do so. If you use git master, then be prepared to manually reconfigure occasionally...

**Comment by xclaesse** [comment]
@Hi-Angel It's always appreciated when people test dev version of course! When using meson from git, you could often have to use `meson --wipe builddir` to reconfigure from scratch, it will preserve the option you have set when configuring your project but delete everything from your build directory.

We cannot track incompatible changes for each commit in meson master, but I made a PR to at least consider the dev version to be a major break, which should cover this specific niche case.

**Comment by eli-schwartz** [comment]
Detecting when people mix release and dev versions does indeed seem like an improvement on the status quo.
