### ISSUE TITLE
No installation happens when `install_tag` is used in `install_subdir`

### ISSUE THREAD

**Issue by Hi-Angel** [mesonbuild/meson#9263]
**Describe the bug**

Given this code:

```
install_subdir('.deb', install_dir : '/', strip_directory : true, install_tag: my_tag)
```

The subdirectory will not be installed when later used with `meson install --tags my_tag`

**To Reproduce**

Here I use latest development snapshot of `meson`, which is why it's run from local directory:

```bash
 λ cat meson.build
project(
  'test',
  ['c'],
)
install_subdir('.deb', install_dir : '/', strip_directory : true, install_tag: 'my_tag')
 λ find .deb
.deb
.deb/etc
.deb/etc/resolv.conf
 λ ~/Projects/meson/meson.py build
The Meson build system
Version: 0.59.99
Source dir: /tmp/foo
Build dir: /tmp/foo/build
Build type: native build
Project name: test
Project version: undefined
C compiler for the host machine: ccache cc (gcc 11.1.0 "cc (GCC) 11.1.0")
C linker for the host machine: cc ld.bfd 2.36.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Build targets in project: 0

Found ninja-1.10.2 at /usr/bin/ninja
 λ cd build
 λ mkdir /tmp/dst
 λ DESTDIR=/tmp/dst ~/Projects/meson/meson.py install --tags my_tag
ninja: Entering directory `/tmp/foo/build'
ninja: no work to do.
Nothing to install.
 λ find /tmp/dst
/tmp/dst
```

**Expected behavior**

The content of `.deb` directory should appear in `/tmp/dst`

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build ? Native
* OS: Archlinux
* Python version: 3.9.6
* `meson --version`: current development version at commit 87e13af1c85c03
* `ninja --version`: 1.10.2

**Comment by xclaesse** [comment]
Good catch, that function was not covered by the unit test, so of course it's broken... Should be fixed by https://github.com/mesonbuild/meson/pull/9265.
