### ISSUE TITLE
python string encoding woes

### ISSUE THREAD

**Issue by ystreet** [mesonbuild/meson#927]
The crux of the matter is (with print debugging):
'ascii' codec can't decode byte 0xc3 in position 91: ordinal not in range(128)

Meson encountered an error in file subprojects/gst-plugins-base/gst-libs/gst/pbutils/meson.build, line 20, column 0:
Could not read input file /home/matt/Projects/gst/gst-all/subprojects/gst-plugins-base/gst-libs/gst/pbutils/gstpluginsbaseversion.h.in.

The 91st character in that file is a ü.

The only difference between this build and all my previous builds is that I'm attempting to build over an ssh connection here.

I've worked around it for now by using codecs.open(, 'utf-8') instead of plain open() but this still begs the question, what are we going to do about this (and any other string encoding issue)?

We can replace all the instances of open() with codecs.open() which should cover the majority of use cases however there are probably some files that won't work with a utf-8 encoding.

**Comment by ignatenkobrain** [comment]
I think I should agree to do `open()` -> `codecs.open(..., 'utf-8')`
