### ISSUE TITLE
setup for Ninja with Virtual Studio fails if buildpath on different drive than cwd

### ISSUE THREAD

**Issue by rkuester** [mesonbuild/meson#9272]
When running `setup` using the Ninja backend and Visual Studio compiler, an unhandled exception is raised if the build directory is on a different drive than the working directory from which `setup` is run (often the source directory).

This occurs merely in service of formatting a relative path for a log message; the build works fine if the formatting is avoided. When `setup` creates a Visual Studio environment, a message is logged which contains a path to the build directory. Typically, this path is converted to a relative path prior to printing. If the path cannot be converted to a relative path (e.g., because buildpath is on a different drive from the cwd), it fails with an unhandled ValueError exception.

## To reproduce
hello.cpp
```
#include <iostream>

int main(int argc, char* argv[]) {
  std::cout << "Hello, world!\n";
  return 0;
}
```

meson.build
```
project('hello', 'cpp')
executable('hello', 'hello.cpp')
```

 command
```
PS C:\Users\rkues> cd p:\testsrc
PS p:\testsrc> meson c:\Users\rkues\build
Activating VS 16.10.4
The Meson build system
Version: 0.59.99
Source dir: \\callisto\share\testsrc
Build dir: C:\Users\rkues\build
Build type: native build
Project name: hello
Project version: undefined
C++ compiler for the host machine: cl (msvc 19.29.30040 "Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30040 for x64")
C++ linker for the host machine: link link 14.29.30040.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Build targets in project: 1

Found ninja-1.10.2 at C:\ProgramData\chocolatey\bin\ninja.EXE
Traceback (most recent call last):
  File "C:\Users\rkues\wrk\meson\mesonbuild\mesonmain.py", line 228, in run
    return options.run_func(options)
  File "C:\Users\rkues\wrk\meson\mesonbuild\msetup.py", line 290, in run
    app.generate()
  File "C:\Users\rkues\wrk\meson\mesonbuild\msetup.py", line 181, in generate
    self._generate(env)
  File "C:\Users\rkues\wrk\meson\mesonbuild\msetup.py", line 243, in _generate
    intr.backend.generate()
  File "C:\Users\rkues\wrk\meson\mesonbuild\backend\ninjabackend.py", line 518, in generate
    builddir = builddir.relative_to(Path.cwd())
  File "C:\Program Files\Python39\lib\pathlib.py", line 929, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"
ValueError: 'C:\\Users\\rkues\\build' is not in the subpath of 'p:\\testsrc' OR one path is relative and the other is absolute.
```

The expected behavior is, of course, for setup to succeed instead of fail.

* Python 3.9
* Meson 0.59.99 (e006e2ee9)
* Ninja 1.10.2

**Comment by rkuester** [comment]
I've attempted to solve this in PR #9273; however, I don't have a unit test to go along with that PR. I'm not sure how to set up a test for this considering it requires specifying directories with particular paths. Any suggestions?

**Comment by eli-schwartz** [comment]
Fixed in linked PR.
