### ISSUE TITLE
Incorrect behavior in Python module when the sysconfig paths aren't relative to the install prefix

### ISSUE THREAD

**Issue by FFY00** [mesonbuild/meson#9284]
**Describe the bug**
When calculating the install paths in the Python module, if a sysconfig path is not relative to install prefix, Meson will have the wrong path.

**To Reproduce**
Change the sysconfig paths on the Python interpreter to not be relative to the prefix, and try to install a Python module with meson.

Eg.
```
$ python -m sysconfig
Platform: "linux-x86_64"
Python version: "3.11"
Current installation scheme: "posix_prefix"

Paths:
	data = "/home/anubis/.virtualenvs/meson-cpython"
	include = "/usr/local/include/python3.11d"
	platinclude = "/usr/local/include/python3.11d"
	platlib = "/opt/custom/lib/python3.11/site-packages"
	platstdlib = "/home/anubis/.virtualenvs/meson-cpython/lib/python3.11"
	purelib = "/opt/custom/lib/python3.11/site-packages"
	scripts = "/home/anubis/.virtualenvs/meson-cpython/bin"
	stdlib = "/usr/local/lib/python3.11"

...
```

```meson
project(
    'pure',
    version: '1.0.0',
)

py_mod = import('python')
py = py_mod.find_installation()

py.install_sources('pure.py')
```

```
$ DESTDIR=destdir ninja install
[0/1] Installing files.
Installing /home/anubis/git/mesonpy/tests/packages/pure/pure.py to /home/anubis/git/mesonpy/tests/packages/pure/build/destdir/usr/local/opt/custom/lib/python3.11/site-packages
```

The file would get installed to `/usr/local/opt/custom/lib/python3.11/site-packages`, which is incorrect.

**Expected behavior**
As Meson cannot correctly calculate the correct path, it should error out. We could optionally bypass this for a set of known paths, like `/opt`, but I am a bit unsure about that.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? No
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
* what Python version are you using e.g. 3.8.0
* what `meson --version`? `master`
* what `ninja --version` if it's a Ninja build

**Comment by xclaesse** [comment]
Meson master should at least warn when this happens. I think the generate concensus was that it's impossible to get it always right, and we should add a Meson built-in option to set the python install path.

**Comment by eli-schwartz** [comment]
This should be fixed by #9788 which adds the ability to specify `-Dpython.install_env=auto`, causing Meson to not do prefix relocation but rather to directly install to the sysconfig locations (and prefer a venv if a venv is currently active).

**Comment by FFY00** [comment]
Meson will still generate obviously mangled and incorrect paths by default. Passing that option is just a work around.

**Comment by rgommers** [comment]
> Meson will still generate obviously mangled and incorrect paths by default. Passing that option is just a work around.

IIRC the plan for that is to make `-Dpython.install_env=auto` the default (please correct me if I'm wrong @eli-schwartz).
