### ISSUE TITLE
The `check` argument of `run_command` should be `True` by default

### ISSUE THREAD

**Issue by Volker-Weissmann** [mesonbuild/meson#9300]
The `run_command` argument takes a `check` bool-argument. If `check: true`, is given and the command fails, meson will error out.

May I ask, who thought that it was a good idea to let `check` default to `false`? Ignoring errors by default goes against everything I learned.

So essentially, I want something like this, (plus documentation updates)
```
diff --git a/mesonbuild/interpreter/interpreterobjects.py b/mesonbuild/interpreter/interpreterobjects.py
index fca371cbc..3b3218c54 100644
--- a/mesonbuild/interpreter/interpreterobjects.py
+++ b/mesonbuild/interpreter/interpreterobjects.py
@@ -163,7 +163,7 @@ class RunProcess(MesonInterpreterObject):
                  subdir: str,
                  mesonintrospect: T.List[str],
                  in_builddir: bool = False,
-                 check: bool = False,
+                 check: bool = True,
                  capture: bool = True) -> None:
         super().__init__()
         if not isinstance(cmd, ExternalProgram):
@@ -184,7 +184,7 @@ class RunProcess(MesonInterpreterObject):
                     subdir: str,
                     mesonintrospect: T.List[str],
                     in_builddir: bool,
-                    check: bool = False) -> T.Tuple[int, str, str]:
+                    check: bool = True) -> T.Tuple[int, str, str]:
         command_array = cmd.get_command() + args
         menv = {'MESON_SOURCE_ROOT': source_dir,
                 'MESON_BUILD_ROOT': build_dir,
```

**Comment by xclaesse** [comment]
I think it's like that for historical reasons, changing this would not be backward compatible. But I agree it's not ideal, we should warn when check argument is not set for a few releases, then so the flip eventually.

**Comment by Volker-Weissmann** [comment]
> I think it's like that for historical reasons, changing this would not be backward compatible.

I can understand that.

> we should warn when check argument is not set

Do you want me to write the PR?

**Comment by eli-schwartz** [comment]
I agree that this change would be nice and yes, if you would write the PR that would be great. ;)

**Comment by eli-schwartz** [comment]
Fixed via linked PR.

**Comment by xclaesse** [comment]
FWIW, I checked GStreamer and they have plenty of places where it assumes that check is false by default. I still agree the default should be true, but we'll probably need a long deprecation period because that seems a common thing.

**Comment by eli-schwartz** [comment]
Sure, baby steps for now though. :D

**Comment by keszybz** [comment]
Please, please, **always** include the source line in messages like this. In large projects, hunting for the right line to fix is a pita.

**Comment by eli-schwartz** [comment]
You're entirely correct and I apologize for not thinking of this during the review process.

It should be easy to fix -- the mlog functions take an optional `location=` parameter. Would you like to submit a PR?

**Comment by Volker-Weissmann** [comment]
> Please, please, **always** include the source line in messages like this. In large projects, hunting for the right line to fix is a pita.

You're right, sorry I forget.

**Comment by Volker-Weissmann** [comment]
> You're entirely correct and I apologize for not thinking of this during the review process.

Yeah, it was a real slip up of you to accept this crap. /s

**Comment by eli-schwartz** [comment]
It was a good PR :p it just could have used one specific touch-up.

**Comment by keszybz** [comment]
OK, OK, I'm sorry that I mentioned it. The change is good.

**Comment by Volker-Weissmann** [comment]
> OK, OK, I'm sorry that I mentioned it. The change is good.

No, No, it's good that you mentioned it.

Good error messages are important.
