### ISSUE TITLE
[Question] Is it possible to generate coverage files for `subprojects`?

### ISSUE THREAD

**Issue by MichaelJeiShen** [mesonbuild/meson#9311]
Hi,
I have an umbrella project that comprises several subprojects. And I’m trying to generate coverage files for each subproject by executing the build process in the top layer/the umbrella layer. (I had built each subproject individually to make sure that my `meson.build` is able to be generated coverage file correctly.)

However I found that the command `ninja -C build coverage-html` implicitly excludes `./subprojects` for generating coverage files. So in the end `lcov` removed all the entries and return an empty `coverage.info` to me.
(I think the command below is what ninja did underlying and the second argument behind `--html` is `exclude_dir`)
```
meson --internal coverage --html ${TOP_DIR} ${TOP_DIR}/subprojects ${TOP_DIR}/build ${TOP_DIR}/build/meson-logs
```
So my question is if there is a way to allow the code coverage feature working on the `subprojects`?
If I have any incorrect understanding please let me know.

Thanks!

**Comment by MichaelJeiShen** [comment]
My system parameters
OS: Debian 5.10.46
python: Python 3.9.7
meson: 0.59.1
ninja: 1.10.1

**Comment by eli-schwartz** [comment]
There is currently no way to do this. Although you could manually run this command and change `${TOP_DIR}/subprojects` to any pattern you don't care about (`/dev/null` or `thisisnotapattern`).

I have previously thought that subprojects as a concept is limiting for the use case you describe: "I have an umbrella project". A lot of the early design decisions for subprojects was guided by the needs of gst-build, which does the same thing, but at the same time subprojects tries to treat itself as an external code vendoring and fallback dependency management solution.

My thought was that we really should have an alternative to `project()` called `metaproject()` which, if used, disables various restrictions on subprojects such as needing to go in the subprojects/ directory, sane defaults for installation, or, one imagines, not excluding them from coverage. :)

**Comment by MichaelJeiShen** [comment]
Thanks for your detailed explanation!
Unfortunately manually running the command is not an option in my case.
Our build script runs in the top layer only and I don't think I can change the rule.

I will close this issue and thanks for your help again. :)
