### ISSUE TITLE
Automatically create build directory if it does not exist

### ISSUE THREAD

**Issue by bagage** [mesonbuild/meson#935]
Currently, invoking meson in a project root folder with a non created build folder leads to:

```
% meson build
Error during basic setup:

[Errno 2] No such file or directory: '/some/path/build'
```

Since meson can find that the current folder contains a `meson.build` file, and that it probably also knows that `build` is my expected build directory. Should not it create it itself? 
I personally don't see any value invoking `mkdir build && meson build` while `meson build` could do the trick. I can submit a PR for that if wished but I'd like to know your opinion on that first.

(in a second time I would also love to have some `meson --build` argument which would invoke backend automatically, so that you finally simply type `meson --build <buildfolder>`; bypassing always-the-same `mkdir` and `cd` commands).

**Comment by jpakkane** [comment]
I can see why this would be useful but on the other hand our command line/path detector already does a fair bit of magic and we don't want to end up like Git, which has a gazillion options for absolutely everything which is very confusing for everyone.

**Comment by bagage** [comment]
Yeah, I'm fine with no `--build` option (I'll do an alias anyway), but concerning the create directory issue I think it is *standard* to expect `meson` to build it instead of to warn that is does not exist.

**Comment by jpakkane** [comment]
I have been paying attention this for a while and at least for me I have fatfingered this several times (usually by typing `meson typodi<tab> + enter`. In this case you *don't* want the build system to create the directory but instead error out.

**Comment by nirbheek** [comment]
What's the harm if meson does create an incorrectly-named build directory though? The fix is a trivial `mv` command, and people usually just want any unused directory to be used for the configuration.

**Comment by TingPing** [comment]
I literally just keep this mess in my shell history and keep calling it `rm -r meson-build; and mkdir meson-build; and meson meson-build`

I would *love* if I could do that in a single command like `meson --force-clean meson-build`

**Comment by jpakkane** [comment]
Why do you need to do this so often? Meson should always be able to reconfigure itself just by running `ninja`. Every now and then nuking the build dir is fine but if you are doing it often, then that is probably the symptom of a bug.

**Comment by nirbheek** [comment]
This is necessary when you do Meson development or if you're changing environment outside of what Ninja keeps track of; specifically things on the system that affect the configuration step.

I do: `mkdir -p build && rm -rf build/* && meson build && ninja-build -C build`

It's particularly annoying on Windows when I want to test inside `cmd.exe`.

**Comment by TingPing** [comment]
Yea I was doing it because I was hacking on Meson itself.

**Comment by ebassi** [comment]
There's also the case of switching between branches with the `build` directory inside the top `srcdir`.

An interesting side effect of adding a `--builddir` argument would be that it allows things like:

    $ cd ~/sources/project
    $ meson --builddir ~/builds/project
    $ ninja -C ~/builds/project test

which allows keeping the sources tree completely pristine.

**Comment by nirbheek** [comment]
You can already do that:

```
$ cd ~/sources/project && mkdir -p ~/builds/project
$ meson ~/builds/project
$ ninja -C ~/builds/project test
```

The `test` target will build all its dependencies before running the tests. However, implicitly creating the builddir would indeed make it less rote work, and less rote work = more productivity. ;)

**Comment by msink** [comment]
Maybe invent some way to calculate `builddir` from options?
To ensure that all different sets of options will use different directory.

Something like this:

meson_options.txt:
```
option('platform', type: 'combo', choices: ['linux', 'windows', 'macosx'], value : 'linux')
option('arch', type: 'combo', choices: ['i386', 'x86_64', 'arm', 'arm64'], value : 'x86_64')
option('class_library', type: 'combo', choices: ['avian', 'openjdk', 'android'], value : 'avian')
```
meson.build:
```
project('avian', ['cpp', 'java'], default_options: ['cpp_std=c++11', 'warning_level=2'],
  builddir: 'build/'+get_option('platform')+'-'+get_option('arch')+'-'+get_option('class_library'))

```

**Comment by jpakkane** [comment]
Options can be changed with mesonconf. That would mean the builddir name would be wrong if that is done and renaming an existing builddir is not doable.

I don't want to force specific build dir names on users. > 90% of the time people just use `build`. Allowing people to choose their own naming scheme is more user friendly. Also, builddir needs to be specified before interpreting `meson.build` files even starts so it can't be set from within.

**Comment by msink** [comment]
> Options can be changed with mesonconf. That would mean the builddir name would be wrong if that is done and renaming an existing builddir is not doable.

Yes, sounds reasonable :)
Ok, in my specific case i can feed builddir and options from external script, and in `meson.build` just check for correctness and call something like `error('Wrong buiddir')` in case of errors.
Or even deduct options from builddir...
