### ISSUE TITLE
Error while Cross-Compiling: Unknown compiler(s): [['emcc']]

### ISSUE THREAD

**Issue by mistymoria** [mesonbuild/meson#9381]
I'm on 64 bit Windows 10, Meson version 0.59.2, trying to build a Raylib project using Meson. Everything works fine compiling natively. I have emcc installed and in the PATH, and using `emcc --version` on my computer runs perfectly. However, when I run 
`meson setup --cross-file cross-file/web.ini build/web`
I get the output,
```meson.build:1:0: ERROR: Unknown compiler(s): [['emcc']]
The following exception(s) were encountered:
Running "emcc --version" gave "[WinError 2] The system cannot find the file specified"
```

Web.ini looks like this:
```
[binaries]
ar = 'emar'
c = 'emcc'
cpp = 'em++'
strip = 'llvm-strip'
```

I've tried putting the full paths in web.ini, I've tried running it through Visual Studio, I'm not sure why it isn't working. Meson compiles the native build just fine - runs no problem.

In windows32.ini:
```
[binaries]
ar = 'i686-w64-mingw32-ar'
c = 'i686-w64-mingw32-gcc'
cpp = 'i686-w64-mingw32-g++'
strip = 'i686-w64-mingw32-strip'
```

I don't get how this works, but cross-file doesn't, when both `i686-w64-mingw32-gcc --version` and `em++ --version` function fine. Any input? Apologies if I'm just making a beginner mistake, this is my first time using Meson and I'm terrible at build stuff.

meson.build is basically unchanged from [this](https://github.com/gilzoide/raylib-meson-template/blob/main/meson.build) template, if that's needed.

**Comment by mistymoria** [comment]
okay, embarrassingly figured it out like five minutes after posting, but I apparently just needed to add '.bat' to all the paths in web.ini, even though that doesn't make sense to me, but fine.

**Comment by gregsskyles** [comment]
FWIW:
Windows has an environment variable called PATHEXT. This declares the file extensions (and search order thereof) to be tried in an attempt to find a file (via the PATH environment variable) to match a first token to cmd.exe that doesn't have an  
(explicit) extension. So I'd have to guess that in the environment of the 'python subprocess' mentioned above, PATHEXT wasn't defined, or didn't include the .BAT extension.
