### ISSUE TITLE
new  architecture to support

### ISSUE THREAD

**Issue by outyang** [mesonbuild/meson#9405]
there is a  architecture called loongarch64
here is  information of one of it named Loongson-3A5000LL
uname -a
Linux la 4.19.0-13-loongson-3 #1 SMP Sat Sep 18 06:32:17 UTC 2021 loongarch64 loongarch64 loongarch64 GNU/Linux
cat /proc/cpuinfo
system type             : generic-loongson-machine
processor               : 0
package                 : 0
core                    : 0
cpu family              : Loongson-64bit
model name              : Loongson-3A5000LL
CPU Revision            : 0x10
FPU Revision            : 0x00
CPU MHz                 : 2300.00
BogoMIPS                : 4600.00
TLB entries             : 2112
Address sizes           : 48 bits physical, 48 bits virtual
isa                     : loongarch32 loongarch64
features                : cpucfg lam ual fpu lsx lasx complex crypto lvz lbt_x86 lbt_arm lbt_mips
hardware watchpoint     : yes, iwatch count: 8, dwatch count: 8

processor               : 1
package                 : 0
core                    : 1
cpu family              : Loongson-64bit
model name              : Loongson-3A5000LL
CPU Revision            : 0x10
FPU Revision            : 0x00
CPU MHz                 : 2300.00
BogoMIPS                : 4600.00
TLB entries             : 2112
Address sizes           : 48 bits physical, 48 bits virtual
isa                     : loongarch32 loongarch64
features                : cpucfg lam ual fpu lsx lasx complex crypto lvz lbt_x86 lbt_arm lbt_mips
hardware watchpoint     : yes, iwatch count: 8, dwatch count: 8

processor               : 2
package                 : 0
core                    : 2
cpu family              : Loongson-64bit
model name              : Loongson-3A5000LL
CPU Revision            : 0x10
FPU Revision            : 0x00
CPU MHz                 : 2300.00
BogoMIPS                : 4600.00
TLB entries             : 2112
Address sizes           : 48 bits physical, 48 bits virtual
isa                     : loongarch32 loongarch64
features                : cpucfg lam ual fpu lsx lasx complex crypto lvz lbt_x86 lbt_arm lbt_mips
hardware watchpoint     : yes, iwatch count: 8, dwatch count: 8

processor               : 3
package                 : 0
core                    : 3
cpu family              : Loongson-64bit
model name              : Loongson-3A5000LL
CPU Revision            : 0x10
FPU Revision            : 0x00
CPU MHz                 : 2300.00
BogoMIPS                : 4600.00
TLB entries             : 2112
Address sizes           : 48 bits physical, 48 bits virtual
isa                     : loongarch32 loongarch64
features                : cpucfg lam ual fpu lsx lasx complex crypto lvz lbt_x86 lbt_arm lbt_mips
hardware watchpoint     : yes, iwatch count: 8, dwatch count: 8

**Comment by outyang** [comment]
i built version 0.56.2 from debian  11

**Comment by outyang** [comment]
yes ,the newly version support loongarch already,i try version 0.59.2 and it known my cpu

**Comment by eli-schwartz** [comment]
This was indeed added in #8300
