### ISSUE TITLE
Adding additional language support

### ISSUE THREAD

**Issue by wbehrens-on-gh** [mesonbuild/meson#9459]
I've seen a few issues regarding this on here but none really seem to go anywhere. I was wondering if someone could point me in the right direction for how to add new language support for meson. The two that I'd be most interested in working on would be [v](https://github.com/vlang/v) and [kotlin](https://kotlinlang.org/).

V seems more promising seeing as it has no real build system for it yet and according to some other threads the Java support its not fully worked out(and I see no way of using maven deps in any docs).

**Comment by dcbaker** [comment]
I've been thinking about this a bunch as lots of people have recently been asking about it, maybe I'll wire up Scala support and write a blog post on it.
