### ISSUE TITLE
gnome.yelp() documentation should indicate 'languages' is deprecated and suggest LINGUAS file instead

### ISSUE THREAD

**Issue by jmatthew** [mesonbuild/meson#9495]
While reviewing and testing meson build files for a project, I somehow deleted the LINGUAS file and then was wondering why the translated help files were not being installed. The documentation led me to think that using the languages arg to gnome.yelp() was the way to fix this, since it doesn't mention that it's deprecated, and it doesn't mention the LINGUAS file at all.

**Comment by dcbaker** [comment]
We should probably also warn/error if you don't set the `languages` argument and there is no LINGUAS file.

**Comment by jmatthew** [comment]
you should do something.
