### ISSUE TITLE
add_project_link_arguments silently ignored in some cases in projects with multiple languages

### ISSUE THREAD

**Issue by Dudemanguy** [mesonbuild/meson#9516]
**Describe the bug**
I am not sure if this occurred before, but with meson 0.60 I noticed that `add_project_link_arguments` is sometimes just completely ignored in a project with multiple languages.

**To Reproduce**
This is an example with `c` and `cpp`, but I was also able to reproduce the behavior with `c` and `objc`.

meson.build
```
project('link-test', 'c', 'cpp')
sources = ['main.c', 'test.cpp']
add_project_link_arguments('obviously-wrong-flag', language: 'c')
executable('link-test', sources)
```

main.c
```
#include <stdio.h>
int main(int argc, char **argv) {
	return 0;
}
```

test.cpp
```
#include <iostream>
int test_function(void) {
	return 0;
}
```

**Expected behavior**
This compilation should fail since there is a bogus flag passed in the build. However it passes. Within the `build.ninja` file, there is only `LINK_ARGS = -Wl,--as-needed -Wl,--no-undefined` for the link arguments.

For some extra weirdness, if you change the `language` of the `add_project_link_arguments` to `cpp`, then it correctly detects the passed link argument and the compilation fails as expected. The `build.ninja` shows: `LINK_ARGS = -Wl,--as-needed -Wl,--no-undefined obviously-wrong-flag`. For this example, it doesn't appear that specifying `cpp` before `c` matters with respect to `add_project_link_arguments`. The bug only occurs if you make the language `c`.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
Native Build
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
Artix Linux
* what Python version are you using e.g. 3.8.0
Python 3.9.7
* what `meson --version`
0.60.0
* what `ninja --version` if it's a Ninja build
1.10.2

**Comment by eli-schwartz** [comment]
I think that what is going on here, is that the executable contains both C and CXX files, so it is linked using cpp_LINKER and not c_LINKER. Hence the flags produced by `add_project_link_arguments(..., language: 'c')` won't get used except for pure C programs.

**Comment by eli-schwartz** [comment]
This can be generally solved by adding it for `language: ['c', 'cpp']`, I forget the exact rules for how meson chooses the correct linker for any given build target with source files in multiple languages other than that CXX always supersedes C.

**Comment by Dudemanguy** [comment]
Hmm that does indeed work. It would be nice to get a warning or something though.

**Comment by eli-schwartz** [comment]
You mean e.g. a warning if it is never going to actually get used by any targets since none of them use C as the link language?

Incidentally, I think you can just unconditionally use `language: ['c', 'objc']` and in the event there is no objc language added it will just be ignored too... this could simplify the mpv conditional from https://github.com/mpv-player/mpv/compare/a20254a50c9738b359f6d4810c5bf140e93c4ee7..e13e2f38851276ff395a109c5e4950c4c1691f61

**Comment by Dudemanguy** [comment]
>You mean e.g. a warning if it is never going to actually get used by any targets since none of them use C as the link language?

Yeah. I guess it took me a while to realize since I'm pretty ignorant of mac things but I guess what links in C everywhere else links with objc on macos.

>Incidentally, I think you can just unconditionally use language: ['c', 'objc'] and in the event there is no objc language added it will just be ignored too...

Yup that works.

**Comment by dcbaker** [comment]
@eli-schwartz is exactly correct on what's happening. The short of it is that we use c++ as the linker by default if any of the sources in your target are c++, or if any of the sources in a link_with target are c++. Same with objc

**Comment by dcbaker** [comment]
We should probably put that in the faq...

**Comment by Dudemanguy** [comment]
I see the FAQ-related commit so I'll go ahead and close this.
