### ISSUE TITLE
Cython: Specify language level

### ISSUE THREAD

**Issue by michael-rapp** [mesonbuild/meson#9525]
I am working on porting an existing Cython project to Meson. Compilation of the Cython code works well, but when executing a Python program that imports some Cython classes, I encounter the following error:
```
ImportError: dynamic module does not define module export function (PyInit_cython)
```
I suppose that the reason is that the extension module should be compiled for Python 3 instead of 2, which is the default if I am not mistaken. In order to specify the Python version, Cython provides the compiler directive [`language_level`](http://docs.cython.org/en/latest/src/userguide/source_files_and_compilation.html#compiler-directives). Is there a way to set this particular directive (and possibly other ones) when using Meson? I tried to add `#cython: language_level=3` to each `pyd`/`pyx` file, but this doesn't seem to work.

**Comment by eli-schwartz** [comment]
I would assume, rather, that this depends on (after the cython processing occurs) which set of python headers you compiled against.

What dependency object(s) did you pass as kwargs to the extension_module() method?

**Comment by michael-rapp** [comment]
The `meson.build` file looks like this:
```
project('projectname', 'cython', 'cpp', meson_version : '>= 0.60.0')

python = import('python').find_installation()
python_dep = python.dependency()
numpy_cmd = run_command('python3', ['-c', 'import numpy; print(numpy.get_include())'], check : true )
numpy_dep = declare_dependency(include_directories : include_directories(numpy_cmd.stdout().strip()))
source_dir = meson.current_source_dir()
cpp = meson.get_compiler('cpp')
lib = cpp.find_library('sharedlibrary', dirs : join_paths(source_dir, 'path/to/shared/library/'))
include = declare_dependency(include_directories : include_directories('path/to/header/files/'))
dependencies = [python_dep, numpy_dep, lib, include]
source_files = [ ... ]
python.extension_module('cython', source_files, dependencies : dependencies, override_options : ['cython_language=cpp'])
```
The Cython code is supposed to wrap a shared library that has been compiled beforehand using C++, i.e., I want to link against the resulting `libsharedlibrary.so` file. The Python installation that is returned by `find_installation()` corresponds to a Python 3.9 virtual environment into which Meson is installed via pip.

**Comment by eli-schwartz** [comment]
Well, this is odd because the default level in meson is already `3`, you can control this by also using `override_options: ['cython_version=3']`.

The verbose output of `ninja -v` might help here, you should see both the exact cython transpiler invocation (with either `-2` or `-3` being passed) and the C++ compiler invocation including e.g. header include paths.

The reason I thought there might be dependency version issues is because cythonized sources should be using header checks on PY_VERSION_HEX to determine whether to build the py2 or py3 versions of the code, because both versions are generated.

**Comment by michael-rapp** [comment]
Thank you, this answer is very informative. I checked the log and the `-3` argument is used as intended. So the language level is not the root of my problem, but my question has been answered. I will close this issue now. Nevertheless I would appreciate comments on the possible reasons for the error I encounter.

**Comment by eli-schwartz** [comment]
Well, that is why I tried theorizing about the dependency used, that was the first possible reason for the error I could think of. :)

Perhaps you can try checking with `nm -D builddir/mymodule.cpython-39-x86_64-linux-gnu.so | grep PyInit`, whether there is a python3-compatible export function defined, and if so, what is it instead?

**Comment by michael-rapp** [comment]
Yes, there are export functions for several modules (including the one mentioned by the `ImportError`), e.g., `0000000000009791 T PyInit_module_name`. So this doesn't seem to be the reason either.
