### ISSUE TITLE
Docs: find_program()'s serch oder list numbering

### ISSUE THREAD

**Issue by rusty-snake** [mesonbuild/meson#9528]
https://mesonbuild.com/Reference-manual_functions.html#find_program looks like

1. Program overrides set via meson.override_find_program()
2. [provide] sections in subproject wrap files, if wrap_mode is set to forcefallback
3. [binaries] section in your machine files
4. Directories provided using the dirs: kwarg (see below)
5. Project's source tree relative to the current subdir

- If you use the return value of configure_file(), the current subdir inside the build tree is used instead

1. PATH environment variable
2. [provide] sections in subproject wrap files, if wrap_mode is set to anything other than nofallback

but should look like

1. Program overrides set via meson.override_find_program()
2. [provide] sections in subproject wrap files, if wrap_mode is set to forcefallback
3. [binaries] section in your machine files
4. Directories provided using the dirs: kwarg (see below)
5. Project's source tree relative to the current subdir
   - If you use the return value of configure_file(), the current subdir inside the build tree is used instead
6. PATH environment variable
7. [provide] sections in subproject wrap files, if wrap_mode is set to anything other than nofallback

---

Maybe the sublist most be indented by one space more?

https://github.com/mesonbuild/meson/blob/1104b82137da55ecb4f13348bbb020d64e4fc78b/docs/yaml/functions/find_program.yaml#L15-L16

```diff
   1. Project's source tree relative to the current subdir
-    - If you use the return value of [[configure_file]], the
-      current subdir inside the build tree is used instead
+     - If you use the return value of [[configure_file]], the
+       current subdir inside the build tree is used instead
   1. `PATH` environment variable
```

**Comment by dcbaker** [comment]
Yes, that looks correct to me. I'd be happy to merge that patch.
