### ISSUE TITLE
[regression] String formatting has regressed since 0.60. ERROR: Format placeholder @9@ out of range.

### ISSUE THREAD

**Issue by ctrlcctrlv** [mesonbuild/meson#9530]
**Describe the bug**
There is a regression of as yet unknown cause in Meson's string formatting, as discovered by @alex3kov and diagnosed by myself at libsixel/libsixel#50. This regression causes previously building package to no longer build.

**To Reproduce**
https://github.com/libsixel/libsixel/blob/v1.10.3/meson.build

**Expected behavior**
Good build

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
    Plain build.
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
    Arch Linux
* what Python version are you using e.g. 3.8.0
    Python 3.9.7
* what `meson --version`
    Versions above 0.59.2 I confirm are affected.
* what `ninja --version` if it's a Ninja build
    We do not get to Ninja step, Meson is the cause.

**Comment by alex3kov** [comment]
0.59.3 works for me. 0.60.0 and 0.60.1 do not.

**Comment by eli-schwartz** [comment]
https://github.com/libsixel/libsixel/commit/803951016a3193160ddc1f12a3c15fe13e0728fb

pkg_config_path is a null list, and should never have been there to begin with (it makes no sense).

In this case it seems that it's being flattened?

Somewhat predictably, this bisects to commit d93d01b6c5c98a77e057b914e8d66b01d2a10771.

Simple test case:

```meson
project('issue 9530')

message('foo list: @0@'.format([]))
```

In meson 0.59.4, this prints:

```
Message: foo list: []
```

It is of debatable usefulness, but what about this?

```meson
project('issue 9530')

message('foo list: @0@, bar list: @1@'.format(['--foo', 'value'], ['--bar', 'value']))
```

0.59.4 output:
```
Message: foo list: ['--foo', 'value'], bar list: ['--bar', 'value']
```

0.60.1 output:
```
Message: foo list: --foo, bar list: value
```

**Comment by eli-schwartz** [comment]
IMHO the absolute last place we should *ever* be doing list flattening is in .format() and message().

**Comment by eli-schwartz** [comment]
(I am not even incredibly fond of list flattening everywhere, it's kind of weird and very prone to this sort of problem.)
