### ISSUE TITLE
Meson 0.60 missing RPATH for ExternalLibrary after static_library dependency propagation

### ISSUE THREAD

**Issue by blue42u** [mesonbuild/meson#9542]
**Describe the bug**
Build targets linking a `static_library` that itself depends on an external library found by `compiler.find_library(dirs: ...)` are missing the requisite RPATH arguments in the final link line. If the library provides an `SONAME` the resulting binaries will be unusable (without setting `LD_LIBRARY_PATH`).

This error is observable in 0.60.0 and the current master (5af556e2b85ce264bb7742261e68ef4347b316aa). It does not appear in 0.59.4.

**To Reproduce**
```meson
# meson.build
project('test', 'c')
foo_lib = meson.get_compiler('c').find_library('foo', dirs: meson.project_source_root())
main_lib = static_library('main', 'main.c', dependencies: foo_lib)
executable('main', link_with: main_lib)
```
```c
// foo.c
#include <stdio.h>
void foo() { printf("Foo\n"); }

// main.c
extern void foo();
int main() { foo(); return 0; }
```
```console
$ cc foo.c -o libfoo.so -shared -fPIC -Wl,-soname,libfoo.so
$ meson _builddir
The Meson build system
Version: 0.60.99
Source dir: /tmp/zzz
Build dir: /tmp/zzz/_builddir
Build type: native build
Project name: test
Project version: undefined
C compiler for the host machine: ccache cc (gcc 11.2.0 "cc (Debian 11.2.0-10) 11.2.0")
C linker for the host machine: cc ld.bfd 2.37
Host machine cpu family: x86_64
Host machine cpu: x86_64
Library foo found: YES
Build targets in project: 2

Found ninja-1.10.1 at /usr/bin/ninja
$ meson compile -C _builddir -v
ninja: Entering directory `/tmp/zzz/_builddir'
[1/3] ccache cc -Ilibmain.a.p -I. -I.. -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -g -fPIC -MD -MQ libmain.a.p/main.c.o -MF libmain.a.p/main.c.o.d -o libmain.a.p/main.c.o -c ../main.c
[2/3] rm -f libmain.a && gcc-ar csrDT libmain.a libmain.a.p/main.c.o
[3/3] cc  -o main  -Wl,--as-needed -Wl,--no-undefined -Wl,--start-group libmain.a /tmp/zzz/libfoo.so -Wl,--end-group
$ ./_builddir/main
./_builddir/main: error while loading shared libraries: libfoo.so: cannot open shared object file: No such file or directory
```

**Expected behavior**
RPATH arguments for the external library's directory would be present in the final link, as they are in 0.59.4:
```console
$ meson _builddir
The Meson build system
Version: 0.59.4
...
[3/3] cc  -o main  -Wl,--as-needed -Wl,--no-undefined '-Wl,-rpath,$ORIGIN/..' -Wl,-rpath-link,/tmp/zzz/_builddir/../ -Wl,--start-group libmain.a /tmp/zzz/libfoo.so -Wl,--end-group
$ ./_builddir/main
Foo
```

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? Native build
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.): Debian Unstable/Sid
* what Python version are you using e.g. 3.8.0: Python 3.9.7
* what `meson --version`: Meson 0.60.99
* what `ninja --version` if it's a Ninja build: Ninja 1.10.1

**Comment by eli-schwartz** [comment]
Bisected to commit f6f35aa906c8ebac21af07c17449df65d08aeaeb
