### ISSUE TITLE
2.16.0 Fails To Compile

### ISSUE THREAD

**Issue by 0pLuS0** [mesonbuild/meson#9553]
**Describe the bug**
I'm trying to compile 2.16.0 on Slackware 14.2, I've updated a lot of the system, but I believe I still have something outdated,  but not sure what.

I tried to compiled this with gcc-11.2.0 and meson 0.57.

**To Reproduce**
[meson-log.txt](https://github.com/mesonbuild/meson/files/7508619/meson-log.txt)

**Expected behavior**
Trying to compile...

**system parameters**
* Slackware 14.2 x86_64
* python-2.7.17 & python3-3.7.2
* Meson 0.57
* Ninja 1.10.2

THANKS

Here's the term output;

The Meson build system
Version: 0.57.1
Source dir: /tmp/sar/hexchat-2.16.0
Build dir: /tmp/sar/hexchat-2.16.0/build
Build type: native build
WARNING: Unknown options: "with-ssl, with-text"
The value of new options can be set with:
meson setup <builddir> --reconfigure -Dnew_option=new_value ...
Project name: hexchat
Project version: 2.16.0
C compiler for the host machine: /usr/local/bin/gcc (gcc 11.2.0 "gcc (GCC) 11.2.0")
C linker for the host machine: /usr/local/bin/gcc ld.bfd 2.26.20160125
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Run-time dependency gio-2.0 found: YES 2.46.2
Run-time dependency gmodule-2.0 found: YES 2.46.2
Run-time dependency libcanberra found: YES 0.30
Run-time dependency dbus-glib-1 found: YES 0.106
Run-time dependency openssl found: YES 1.0.2u
Checking for function "memrchr" : YES 
Has header "strings.h" : YES 
Checking for function "X509_get_signature_nid" with dependency openssl: YES 
Checking for function "SSL_CTX_get_ssl_method" with dependency openssl: YES 
Checking for function "DH_set0_pqg" with dependency openssl: NO 
Checking for function "DH_get0_key" with dependency openssl: NO 
Checking for function "DH_set0_key" with dependency openssl: NO 
Checking for function "ERR_remove_thread_state" with dependency openssl: YES 
Checking for function "ASN1_STRING_get0_data" with dependency openssl: NO 
Configuring config.h using configuration
Compiler for C supports arguments -funsigned-char: YES 
Compiler for C supports arguments -Wno-conversion: YES 
Compiler for C supports arguments -Wno-pointer-sign: YES 
Compiler for C supports arguments -Wno-padded: YES 
Compiler for C supports arguments -Wno-unused-parameter: YES 
Compiler for C supports arguments -Wno-missing-prototypes: YES 
Compiler for C supports arguments -Winline: YES 
Compiler for C supports arguments -Wstrict-prototypes: YES 
Compiler for C supports arguments -Werror=implicit-function-declaration: YES 
Compiler for C supports arguments -Werror=pointer-arith: YES 
Compiler for C supports arguments -Werror=init-self: YES 
Compiler for C supports arguments -Werror=format-security -Werror=format=1: YES 
Compiler for C supports arguments -Werror=missing-include-dirs: YES 
Compiler for C supports arguments -Werror=date-time: YES 
Compiler for C supports arguments -fstack-protector-strong: YES 
Compiler for C supports link arguments -Wl,-z,relro: YES 
Compiler for C supports link arguments -Wl,-z,now: YES 
Compiler for C supports link arguments -Wl,--nxcompat: NO 
Compiler for C supports link arguments -Wl,--dynamicbase: NO 
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Program glib-genmarshal found: YES (/usr/bin/glib-genmarshal)
Program make-te.py found: YES (/tmp/sar/hexchat-2.16.0/src/common/make-te.py)
WARNING: Project targeting '>= 0.47.0' but tried to use feature introduced in '0.50.0': install arg in configure_file.
Configuring org.hexchat.service.service using configuration
Program dbus-binding-tool found: YES (/usr/bin/dbus-binding-tool)
Run-time dependency gtk+-2.0 found: YES 2.24.31
Run-time dependency x11 found: YES 1.7.2
Run-time dependency iso-codes found: YES 3.67
WARNING: GLib compiled dependencies do not work reliably with 
the current version of GLib. See the following upstream issue: https://bugzilla.gnome.org/show_bug.cgi?id=774368
Program glib-compile-resources found: YES (/usr/bin/glib-compile-resources)
Program generate_header.py found: YES (/tmp/sar/hexchat-2.16.0/plugins/perl/generate_header.py)
Program perl found: YES (/usr/bin/perl)
Found CMake: /usr/bin/cmake (3.14.4)
Run-time dependency python3-embed found: NO (tried pkgconfig and cmake)
Run-time dependency python3 found: YES 3.7
Program generate_plugin.py found: YES (/tmp/sar/hexchat-2.16.0/plugins/python/generate_plugin.py)
Run-time dependency libpci found: YES 3.4.1
Configuring hexchat-plugin.pc using configuration
Program desktop-file-validate found: YES (/usr/bin/desktop-file-validate)
Program appstream-util found: NO
Configuring io.github.Hexchat.desktop.in using configuration
Configuring io.github.Hexchat.Plugin.Checksum.metainfo.xml using configuration
Configuring io.github.Hexchat.Plugin.Fishlim.metainfo.xml using configuration
Configuring io.github.Hexchat.Plugin.Perl.metainfo.xml using configuration
Configuring io.github.Hexchat.Plugin.Python.metainfo.xml using configuration
Configuring io.github.Hexchat.Plugin.Sysinfo.metainfo.xml using configuration
Configuring hexchat.1 using configuration
Program validate-textevent-translations found: YES (/tmp/sar/hexchat-2.16.0/po/validate-textevent-translations)
Program meson_post_install.py found: YES (/usr/bin/python3 /tmp/sar/hexchat-2.16.0/meson_post_install.py)
Build targets in project: 22
WARNING: Project specifies a minimum meson_version '>= 0.47.0' but uses features which were added in newer versions:
 * 0.50.0: {'install arg in configure_file'}

hexchat 2.16.0

  Directories
    prefix         : /usr
    bindir         : bin
    libdir         : lib64
    datadir        : share

  Features
    TLS (openssl)  : True
    Plugin Support : True
    DBus Support   : True
    libcanberra    : True

  Plugins
    Lua            : false
    Python         : python3
    Perl           : perl
    Perl Legacy API: False
    FiSH           : True
    Sysinfo        : True
    DCC Checksum   : True

Found ninja-1.10.2 at /usr/bin/ninja
[4/99] Compiling C object plugins/fishlim/tests/fishlim_tests.p/.._utils.c.o
FAILED: plugins/fishlim/tests/fishlim_tests.p/.._utils.c.o 
/usr/local/bin/gcc -Iplugins/fishlim/tests/fishlim_tests.p -Iplugins/fishlim/tests -I../plugins/fishlim/tests -Iplugins/fishlim -I../plugins/fishlim -I. -I.. -Isrc/common -I../src/common -Isrc/common/dbus -I../src/common/dbus -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu89 -O2 -g -funsigned-char -Wno-conversion -Wno-pointer-sign -Wno-padded -Wno-unused-parameter -Wno-missing-prototypes -Winline -Wstrict-prototypes -Werror=implicit-function-declaration -Werror=pointer-arith -Werror=init-self -Werror=format-security -Werror=format=1 -Werror=missing-include-dirs -Werror=date-time -fstack-protector-strong -DHAVE_CONFIG_H -pthread -MD -MQ plugins/fishlim/tests/fishlim_tests.p/.._utils.c.o -MF plugins/fishlim/tests/fishlim_tests.p/.._utils.c.o.d -o plugins/fishlim/tests/fishlim_tests.p/.._utils.c.o -c ../plugins/fishlim/utils.c
../plugins/fishlim/utils.c: In function 'foreach_utf8_data_chunks':
../plugins/fishlim/utils.c:124:16: error: implicit declaration of function 'strlen' [-Werror=implicit-function-declaration]
  124 |     data_len = strlen(data);
      |                ^~~~~~
../plugins/fishlim/utils.c:26:1: note: include '<string.h>' or provide a declaration of 'strlen'
   25 | #include "utils.h"
  +++ |+#include <string.h>
   26 | #include "fish.h"
../plugins/fishlim/utils.c:124:16: warning: incompatible implicit declaration of built-in function 'strlen' [-Wbuiltin-declaration-mismatch]
  124 |     data_len = strlen(data);
      |                ^~~~~~
../plugins/fishlim/utils.c:124:16: note: include '<string.h>' or provide a declaration of 'strlen'
cc1: some warnings being treated as errors
[10/99] Compiling C object plugins/fishlim/tests/fishlim_tests.p/tests.c.o
FAILED: plugins/fishlim/tests/fishlim_tests.p/tests.c.o 
/usr/local/bin/gcc -Iplugins/fishlim/tests/fishlim_tests.p -Iplugins/fishlim/tests -I../plugins/fishlim/tests -Iplugins/fishlim -I../plugins/fishlim -I. -I.. -Isrc/common -I../src/common -Isrc/common/dbus -I../src/common/dbus -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu89 -O2 -g -funsigned-char -Wno-conversion -Wno-pointer-sign -Wno-padded -Wno-unused-parameter -Wno-missing-prototypes -Winline -Wstrict-prototypes -Werror=implicit-function-declaration -Werror=pointer-arith -Werror=init-self -Werror=format-security -Werror=format=1 -Werror=missing-include-dirs -Werror=date-time -fstack-protector-strong -DHAVE_CONFIG_H -pthread -MD -MQ plugins/fishlim/tests/fishlim_tests.p/tests.c.o -MF plugins/fishlim/tests/fishlim_tests.p/tests.c.o.d -o plugins/fishlim/tests/fishlim_tests.p/tests.c.o -c ../plugins/fishlim/tests/tests.c
In file included from /usr/include/glib-2.0/glib.h:82,
                 from ../plugins/fishlim/tests/tests.c:24:
../plugins/fishlim/tests/tests.c: In function 'test_base64_len':
../plugins/fishlim/tests/tests.c:140:30: error: implicit declaration of function 'strlen' [-Werror=implicit-function-declaration]
  140 |             g_assert_cmpuint(strlen(b64), == , base64_len(message_len));
      |                              ^~~~~~
/usr/include/glib-2.0/glib/gtestutils.h:54:62: note: in definition of macro 'g_assert_cmpuint'
   54 |                                              guint64 __n1 = (n1), __n2 = (n2); \
      |                                                              ^~
../plugins/fishlim/tests/tests.c:28:1: note: include '<string.h>' or provide a declaration of 'strlen'
   27 | #include "utils.h"
  +++ |+#include <string.h>
   28 | 
In file included from /usr/include/glib-2.0/glib.h:82,
                 from ../plugins/fishlim/tests/tests.c:24:
../plugins/fishlim/tests/tests.c:140:30: warning: incompatible implicit declaration of built-in function 'strlen' [-Wbuiltin-declaration-mismatch]
  140 |             g_assert_cmpuint(strlen(b64), == , base64_len(message_len));
      |                              ^~~~~~
/usr/include/glib-2.0/glib/gtestutils.h:54:62: note: in definition of macro 'g_assert_cmpuint'
   54 |                                              guint64 __n1 = (n1), __n2 = (n2); \
      |                                                              ^~
../plugins/fishlim/tests/tests.c:140:30: note: include '<string.h>' or provide a declaration of 'strlen'
  140 |             g_assert_cmpuint(strlen(b64), == , base64_len(message_len));
      |                              ^~~~~~
/usr/include/glib-2.0/glib/gtestutils.h:54:62: note: in definition of macro 'g_assert_cmpuint'
   54 |                                              guint64 __n1 = (n1), __n2 = (n2); \
      |                                                              ^~
../plugins/fishlim/tests/tests.c: In function 'test_base64_fish_len':
../plugins/fishlim/tests/tests.c:162:30: warning: incompatible implicit declaration of built-in function 'strlen' [-Wbuiltin-declaration-mismatch]
  162 |             g_assert_cmpuint(strlen(b64), == , base64_fish_len(message_len));
      |                              ^~~~~~
/usr/include/glib-2.0/glib/gtestutils.h:54:62: note: in definition of macro 'g_assert_cmpuint'
   54 |                                              guint64 __n1 = (n1), __n2 = (n2); \
      |                                                              ^~
../plugins/fishlim/tests/tests.c:162:30: note: include '<string.h>' or provide a declaration of 'strlen'
  162 |             g_assert_cmpuint(strlen(b64), == , base64_fish_len(message_len));
      |                              ^~~~~~
/usr/include/glib-2.0/glib/gtestutils.h:54:62: note: in definition of macro 'g_assert_cmpuint'
   54 |                                              guint64 __n1 = (n1), __n2 = (n2); \
      |                                                              ^~
../plugins/fishlim/tests/tests.c: In function 'test_base64_ecb_len':
../plugins/fishlim/tests/tests.c:188:30: warning: incompatible implicit declaration of built-in function 'strlen' [-Wbuiltin-declaration-mismatch]
  188 |             g_assert_cmpuint(strlen(b64), == , ecb_len(message_len));
      |                              ^~~~~~
/usr/include/glib-2.0/glib/gtestutils.h:54:62: note: in definition of macro 'g_assert_cmpuint'
   54 |                                              guint64 __n1 = (n1), __n2 = (n2); \
      |                                                              ^~
../plugins/fishlim/tests/tests.c:188:30: note: include '<string.h>' or provide a declaration of 'strlen'
  188 |             g_assert_cmpuint(strlen(b64), == , ecb_len(message_len));
      |                              ^~~~~~
/usr/include/glib-2.0/glib/gtestutils.h:54:62: note: in definition of macro 'g_assert_cmpuint'
   54 |                                              guint64 __n1 = (n1), __n2 = (n2); \
      |                                                              ^~
../plugins/fishlim/tests/tests.c: In function 'test_base64_cbc_len':
../plugins/fishlim/tests/tests.c:214:30: warning: incompatible implicit declaration of built-in function 'strlen' [-Wbuiltin-declaration-mismatch]
  214 |             g_assert_cmpuint(strlen(b64), == , cbc_len(message_len));
      |                              ^~~~~~
/usr/include/glib-2.0/glib/gtestutils.h:54:62: note: in definition of macro 'g_assert_cmpuint'
   54 |                                              guint64 __n1 = (n1), __n2 = (n2); \
      |                                                              ^~
../plugins/fishlim/tests/tests.c:214:30: note: include '<string.h>' or provide a declaration of 'strlen'
  214 |             g_assert_cmpuint(strlen(b64), == , cbc_len(message_len));
      |                              ^~~~~~
/usr/include/glib-2.0/glib/gtestutils.h:54:62: note: in definition of macro 'g_assert_cmpuint'
   54 |                                              guint64 __n1 = (n1), __n2 = (n2); \
      |                                                              ^~
cc1: some warnings being treated as errors
[13/99] Generating marshal_h with a custom command (wrapped by meson to capture output)
ninja: build stopped: subcommand failed.

**Comment by eli-schwartz** [comment]
2.16.0 of what software? Buried inside your build log is the name of the hexchat software. This should have been in your issue title or main description.

And... as far as I can tell from the build logs, you have issues with the actual hexchat source code, so this has nothing to do with meson. Please report this to the hexchat project at https://github.com/hexchat/hexchat

**Comment by 0pLuS0** [comment]
I have no idea how this ended up here, I did report this over at Hexchat's Repo... hmm
