### ISSUE TITLE
Cython: Specify include directory

### ISSUE THREAD

**Issue by michael-rapp** [mesonbuild/meson#9562]
I am trying to compile Cython code that is organized in Meson subprojects as follows:

```
subprojects/
    first/
        a.pxd
        a.pyx
        meson.build
    second/
        b.pyx
        meson.build
meson.build
```

The file `b.pyx` cimports from `a.pxd`. An extension module for its compilation is defined in `subprojects/second/meson.build` as follows:
```
python.extension_module(
    'b', 'b.pyx', override_options : ['cython_language=cpp'],
    include_directories : include_directories('../first/'))
```
When trying to compile the subproject "second" the following error occurs:
```
subprojects/second/b.cpp 
/usr/bin/cython --cplus -3 --fast-fail ../subprojects/second/b.pyx -o subprojects/second/b.cpp

Error compiling Cython file:
------------------------------------------------------------
...
from a cimport foo
^
------------------------------------------------------------

subprojects/second/b.pyx:1:0: 'a.pxd' not found

```
This is because the Cython transpiler does only take into account the directory `subprojects/second/` when searching for the file `a.pxd`. Adding the `include_directories` argument to the extension module does not solve the problem, because the specified path is only passed to the C++ compiler once the Cython transpiler has finished successfully. The same applies, if the argument `dependencies` is used instead.

I found a workaround that circumvents the issue by defining the extension module in `subprojects/second/meson.build` as follows:
```
f = custom_target(
    'b', output : 'b.cpp', input : 'b.pyx',
    command : ['cython', '--cplus', '-3', '--fast-fail', '@INPUT@', '-o', '@OUTPUT@', '-I', '../first/'])
python.extension_module('b', f)
```
This works, because the `-I` argument is passed manually to the `cython` command. However, it is an ugly hack that does not allow to use Meson's native support for Cython. Is there a better solution to ensure that the `-I` argument is passed to the Cython transpiler?

**Comment by QuLogic** [comment]
>     include_directories : include_directories('../first/'))

I don't know how this works for Cython, but this isn't right in general. In `second`, you need to `subproject` first _also_, and then `get_variable` from there to put a real dependency into what it needs.

**Comment by michael-rapp** [comment]
> > ```
> > include_directories : include_directories('../first/'))
> > ```
> 
> I don't know how this works for Cython, but this isn't right in general. In `second`, you need to `subproject` first _also_, and then `get_variable` from there to put a real dependency into what it needs.

Yes, I am aware of this. But I wanted to keep the example as simple as possible. As I have written, when passing a dependency to the `dependencies` argument of the extension module it doesn't work either, because these arguments are only passed to the `cpp` compiler, not to the `cython` transpiler.

**Comment by michael-rapp** [comment]
I found a slightly more elegant solution that allows to use Meson's native support for Cython. It is based on specifying the additional arguments to be passed to the Cython transpiler via the `add_project_arguments` function as shown below:
```
add_project_arguments('-I', '../first', language : 'cython')
python.extension_module(
    'b', 'b.pyx', override_options : ['cython_language=cpp'])

```
This is good enough for me. I will therefore close this issue.
