### ISSUE TITLE
Passing files() in run_target() assumes working directory is the build root

### ISSUE THREAD

**Issue by rhd** [mesonbuild/meson#957]
I was a bit surprised when `files('foo.txt')` from a subdir returned a path like `'../common/MDP1/foo.txt'`

This made using `foo` defined as `foo = files('foo.txt')` almost useless. Is this expected? (I tried using it from the root dir.

I changed it to `foo = join_paths(meson.current_source_dir(), 'foo.txt')` and am now good but just wanted to share my experience.

**Comment by nirbheek** [comment]
The point of `files` is to be able to refer to a file (or files) in a source directory from anywhere else including another subdir without having to know where you are and where that file is.

What exactly are you trying to do?

**Comment by rhd** [comment]
Right, that is the point. But look at the result path from files(). It's
not usable from anywhere in the source tree.

I tried using it from the root directory, and the '..' messes things up.

Am I making sense?

**Comment by nirbheek** [comment]
The `'..'` is because it translates paths to the corresponding build directory.

**Comment by rhd** [comment]
Hmm... this is what I tried to do.

In the top level meson.build:
```
# add a top level target to generate an RPM
rpmbuild = find_program('rpmbuild.sh')
run_target('rpm',
    command: [rpmbuild, enumvalues],
)
```

`enumvalues` was defined in a subdir like this `enumvalues = files('enumvalues.txt')`.

This didn't work. I guess I was expecting either a full path or a smart relative path. But `..` from the top level source dir will never work.

Can you think of a better way?

**Comment by nirbheek** [comment]
`run_target`s are run from the build directory, so the `..` should indeed be needed to be able to refer to the `enumvalues.txt` file in the source tree. What am I missing?

**Comment by rhd** [comment]
Thank you @nirbheek for working this through with me.

My issue was in my `rpmbuild.sh` script, I had to `cd $MESON_BUILD_ROOT` for that relative path from `files()` to work correctly. :+1: 

I'm going to close this issue and try to remember this for the next time :)

**Comment by nirbheek** [comment]
What directory is the script run from by default?

**Comment by rhd** [comment]
Looks like it's run from the source dir. My script lives in the top level dir and that's what `pwd` reports.

**Comment by rhd** [comment]
This is the line in build.ninja.

```
build rpm: CUSTOM_COMMAND 
 COMMAND = '/usr/local/bin/python3' '/tmp/proj/ECS/MDP1/meson/meson.py' '--internal' 'commandrunner' '/tmp/proj' '/tmp/proj/build' '' '/tmp/proj/rpmbuild.sh' '../common/MDP1/EnumValues.txt'
```

**Comment by rhd** [comment]
Is this worth reopening as something that should be revisited?

**Comment by nirbheek** [comment]
Yes, `files()` not working as expected with run targets is a bug.
