### ISSUE TITLE
How to choose gcc compiler at my home directory?

### ISSUE THREAD

**Issue by zhajio1988** [mesonbuild/meson#9574]
I find meson.get_compiler('c', native: true), always return gcc which is under /usr/bin/gcc, but actually i want to use gcc under my home directory. 
Who can  tell me how to choose gcc compiler at my home directory?

**Comment by eli-schwartz** [comment]
The get_compiler() method will only let you look up the already configured compiler.

As for actually configuring the compiler, meson respects the industry standard `$CC` and `$CXX` variables, and will otherwise look in your `$PATH`.

**Comment by zhajio1988** [comment]
@eli-schwartz 
Thanks, i already set below environment variable：
export CC=gcc
export CXX=gcc
also i update my path set in bashrc, when i type gcc in terminal, gcc under my hone directroy return, but meson.get_compiler('c', native: true) return gcc version is /usr/bin/gcc version, i don't know why.

**Comment by eli-schwartz** [comment]
It does work in the general case. Did you try setting CC to the absolute path? Did you make sure you didn't configure over an existing build directory to eliminate caching issues?

**Comment by zhajio1988** [comment]
> 
> 
> It does work in the general case. Did you try setting CC to the absolute path?
> 
> > also i update my path set in bashrc,
> 
> Did you make sure you didn't configure over an existing build directory to eliminate caching issues?

Sorry, I don't know what you mean of configure over an existing build directory to eliminate caching issues?

**Comment by zhajio1988** [comment]
@eli-schwartz 
Already solve this issue， Could you close this ticket.

**Comment by eli-schwartz** [comment]
It is already closed. :)
