### ISSUE TITLE
I want a feature to show the value of a file object

### ISSUE THREAD

**Issue by Jason2013** [mesonbuild/meson#9575]
I work on a big project with meson but I find that I cannot show the value of a file object.
It is very hard to debug the meson.build file.

For example, I want to know the file object values in a file object list:

```
project('demo', 'c')

srcs = files('main.c', 'func.c')
foreach f : srcs
    warning(f) # this line cannot work
endforeach
executable('demoapp', srcs)
```

error message:

```
ERROR: Function accepts only strings, integers, lists, dictionaries and lists thereof.
```

https://mesonbuild.com/Reference-manual_returned_file.html

The file object is an opaque object which has no any method to show its value or property. I can just use a file object but I cannot know the value in it.

I hope the file object can have a `filename()` method to show its value.

**Comment by eli-schwartz** [comment]
```meson
warning('@0@'.format(f))
```

It's a bit of a hack but the format method essentially gives you the python `__repr__()` of objects that aren't directly describable. IIRC you should get something like "<File: main.c>".

**Comment by Jason2013** [comment]
Thanks!

**Comment by Hi-Angel** [comment]
You can use `fs` module to extract the name, or since v1.4.0 there is also `.full_path()` function on the `file` object.

Example:

```haskell
λ cat meson.build
project('foo', ['c'], version : '1.1')

f = files('test.c')

fs = import('fs')

message('path is '     + f[0].full_path()) # since v1.4.0
message('filename is ' + fs.name(f))
message('path is '     + fs.parent(f))
λ meson setup build
[…]
Message: path is /tmp/foo/test.c
Message: filename is test.c
Message: path is .
[…]
```
