### ISSUE TITLE
Open Discussions page for Meson

### ISSUE THREAD

**Issue by mscofield0** [mesonbuild/meson#9597]
It would be nice to have a place to ask questions about Meson since there isn't really a Discord or a Slack.

**Comment by eli-schwartz** [comment]
I don't have any objections to also enabling GitHub discussions, but note that there *is* an existing Google groups mailing list. Both are/can be places for people to post questions and have others answer them in an asynchronous manner.

Discord and Slack are synchronous (real-time chat) communications methods. Meson uses neither, because we use IRC / Matrix for that.

**Comment by mscofield0** [comment]
The Google mailing list thing, at least in my opinion, is a bit unintuitive to use, and rather ugly :/ 
But if everyone pays attention to the mailing list, then there's really no point in having the Discussions tab. 

Maybe we could try it out for a while and see how it goes?

**Comment by dcbaker** [comment]
@jpakkane, @xclaesse I'd be willing to set that up if others are interested (and I have the proper permissions to do so)

**Comment by dcbaker** [comment]
I actually always forget we have the google group. I don't think I've ever looked at it.

**Comment by eli-schwartz** [comment]
It's not the most active thing ever, but some people do ask questions there, and @jpakkane and I (at least) answer.

**Comment by dcbaker** [comment]
I assume it's about as active as stackoverflow (which I and one other person seem to answer all the questions for)

**Comment by jpakkane** [comment]
Email groups don't seem to be popular any more so yes this would make sense if if got more popular. I've never used Github discussions, how does it compare to something like discourse?

**Comment by mscofield0** [comment]
Well, for one, it'd be directly integrated into the main repository page (here). Also the UI is much more pleasant than Discourse in my opinion.

**Comment by dcbaker** [comment]
Since they're opened, I'll go ahead and close this
