### ISSUE TITLE
JDK system dependency: link against libjvm

### ISSUE THREAD

**Issue by sp1ritCS** [mesonbuild/meson#9601]
**Describe the bug**
`jni.h` does not only contain structures to run c(++) code from java, but also java from c(++). For this to work the resulting binary has to be linked against `libjvm.so` located in `$JAVA_HOME/lib/server/`. Otherwise if your code tries to call these, the linker will fail:
```
FAILED: mjvmtest 
cc  -o mjvmtest mjvmtest.p/jvm.c.o -Wl,--as-needed -Wl,--no-undefined
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: mjvmtest.p/jvm.c.o: in function `main':
/home/admin/workspace/cli/meson/mjvmtest/_build/../jvm.c:16: undefined reference to `JNI_CreateJavaVM'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

**To Reproduce**
I've taken the JNI Invokation Example: https://docs.oracle.com/en/java/javase/11/docs/specs/jni/invocation.html, ported it to C and made it actually do something.
```c
#include <jni.h>	/* where everything is defined */
#include <stdbool.h>

int main(int, char**) {
	JavaVM *jvm;	/* denotes a Java VM */
	JNIEnv *env;	/* pointer to native method interface */
	JavaVMInitArgs vm_args;	/* JDK/JRE 10 VM initialization arguments */
	JavaVMOption options[2];
	options[0].optionString = "-Djava.class.path=/usr/lib64/java";
	options[1].optionString = "-Xcheck:jni";
	vm_args.version = JNI_VERSION_10;
	vm_args.nOptions = 1;
	vm_args.options = options;
	vm_args.ignoreUnrecognized = false;
	/* load and initialize a Java VM, return a JNI interface
	* pointer in env */
	JNI_CreateJavaVM(&jvm, (void**)&env, &vm_args);
	/* get stdout PrintStream */
	jclass system = (*env)->FindClass(env, "java/lang/System");
	jfieldID jstdout_id = (*env)->GetStaticFieldID(env, system, "out", "Ljava/io/PrintStream;");
	jobject jstdout = (*env)->GetStaticObjectField(env, system, jstdout_id);
	/* invoke println method of PrintStream */
	jclass print_stream = (*env)->FindClass(env, "java/io/PrintStream");
	jmethodID mid = (*env)->GetMethodID(env, print_stream, "println", "(Ljava/lang/String;)V");
	jstring to_print = (*env)->NewStringUTF(env, "Hello World from C");
	(*env)->CallVoidMethod(env, jstdout, mid, to_print);
	/* We are done. */
	(*jvm)->DestroyJavaVM(jvm);
}
```

```meson
project('mjvmtest', 'c',
	version : '0.1',
	default_options : ['warning_level=3', 'c_std=gnu2x'])

app = executable('mjvmtest', [
		'jvm.c'
	],
	dependencies: [
		#dependency('jdk', version: ['>=11', '<12'])
		dependency('jdk', version: '>=11')
	],
	install : true
)
```

**Expected behavior**
I expect it to link against libjvm.so.

Adding ` self.link_args = [f'{self.java_home}/lib/server/libjvm.so']`to the JDKSystemDependency __init__ method in `mesonbuild/depenencies/dev.py` makes it work.

What needs to be done is to extend it that it uses the correct file extension for each OS and maybe link it in a way that libjvm.so does not have to be in the library search path.

**system parameters**
* OS: openSUSE Tumbleweed 20211117
* Python 3.8.12
* Meson 0.59.4 & cc80187
* Ninja 1.10.2

**Comment by eli-schwartz** [comment]
> extend it that it uses the correct file extension for each OS

Use `self.clib_compiler.find_library('jvm', environment, [f'{self.java_home}/lib/server/'])`

**Comment by eli-schwartz** [comment]
> maybe link it in a way that libjvm.so does not have to be in the library search path.

You can do this from meson.build using the install_rpath kwarg, which has no effect on Windows (where there is no such concept).  meson translates install_rpath kwargs via mesonbuild/linkers/linkers.py in `GnuLikeDynamicLinkerMixin.build_rpath_args()`, there are a couple of special behaviors that meson has but I guess it should be irrelevant if you don't need to cope with `$ORIGIN` support. The more troubling concern is that this behavior is GNU-like, not something that works with generic POSIX linkers -- see how the other linker classes in that file define the `build_rpath_args()` function.

I think meson just passes `-Wl,-rpath` args that come from a pkg-config dependency as is, and assumes they work entirely as expected, but in that case we sort of assume that the installed pkg-config files contain the arguments relevant to the platform default linker.

**Comment by tristan957** [comment]
I was literally just thinking about this since I was reading https://cmake.org/cmake/help/latest/module/FindJNI.html. I was thinking about a way to do this, but I didn't know what libraries are actually meant for linking against in the JDK. Seems like CMake supports `libjvm.so` and `libjawt.so`. Are the others implementation details or something?

**Comment by tristan957** [comment]
Looking at the include files. It seems like `jawt` and `jvm` are the only important ones.

**Comment by sp1ritCS** [comment]
huh, I never used libjawt and so far I didn't feel the need to link against it, since AWT is pretty dead AFAIK :)

it should definitively be optional

**Comment by tristan957** [comment]
@eli-schwartz thoughts?

**Comment by tristan957** [comment]
you can probably ping me in the future with any jdk/java concerns pertaining to this dependency or the Java module fyi

**Comment by eli-schwartz** [comment]
The traditional interface for dependency-specific handling of additional components within a dependency is the `modules: ` kwarg.

So by default behavior would be preserved, don't link to anything. Is there a valid use case for this BTW? Do people always want to link to jvm itself?

Users who want AWT would use `modules: ['awt']`. Users who want the JVM might pass that as a modules kwarg, depending on what we decide the default should be.

**Comment by tristan957** [comment]
I would assume one use case for this is embedding a JVM in another application. Thanks. I will switch to `modules`.

**Comment by eli-schwartz** [comment]
Makes sense. So both jvm and awt should be opt-in modules.

**Comment by tristan957** [comment]
Right. Information around this is pretty hard to come by to be honest. Will have a PR up in a bit
