### ISSUE TITLE
Use consistent formatting and colouring for warnings (needs an internal helper)

### ISSUE THREAD

**Issue by bagage** [mesonbuild/meson#961]
Currently warnings are white bold, making them easy to miss. 
I would expect them to be more visible (orange? yellow?) since they are signs of something going wrong. Plus, white is already used to show environment values, making them even more harmless:

![capture d ecran de 2016-10-27 15-30-00](https://cloud.githubusercontent.com/assets/1451988/19769094/54a7b632-9c5a-11e6-8494-6ffca62b2e3c.png)

Here the issue what about an invalid parameter name (`vala` vs `vala_args`) in `static_library` function invocation:

> **Warning:** Unknown keyword argument(s) in target geary-static: vala.

**Comment by nirbheek** [comment]
The main issue is that right now we don't have an internal helper for printing warnings, so each place that outputs warnings uses its own formatting.
