### ISSUE TITLE
Python configuration via pkg-config may differ from that of found Python on path.

### ISSUE THREAD

**Issue by matthew-brett** [mesonbuild/meson#9612]
It is fairly easy to have two Python installations on a system, only one of which reports to `pkg-config`.  If another Python is earlier on the path, then `mod = import('python')` will find one Python, but `mod.find_installation().dependency()` will find another, because it first uses `pkg_config`, regardless of whether that matches the found Python.

The consequence is that the code then compiles and links against a different Python to the one found.

**To Reproduce**

Install Python.org Python on Windows (no pkg-config files), to `c:\Python39` (e.g. with `choco install python --version=3.9`).  Install Msys2 gcc, that comes, by default, with a version of Python, along with `pkg-config` binary, and a `python3.pc` pkg-config configuration.   Make sure `c:\Python3.9` is earlier in the PATH.

In that case, with this in `meson.build`:

```
py_mod = import('python')
py_inst = py_mod.find_installation()
py_dep = py_inst.dependency()
```

the `py_inst` will be the `c:\Python39\Python.exe` Python, but the `py_dep` variables will refer to the Msys2 Python.

**Expected behavior**

I think what should happen is that the `dependency()` call should confirm that the `pkg-config` variables do in fact refer to the `py_inst` Python, and if not, then `dependency` should use the `system` method to get dependency information.

**system parameters**
* Native build
* Windows 10
* Python 3.9
* `meson --version` : 0.60.99
* `ninja --version` : 1.10.2.git.kitware.jobserver-1

**Comment by eli-schwartz** [comment]
We actually do try to find the pkg-config file from that python installation's `sysconfig.get_config_var('LIBPC')`, by overriding PKG_CONFIG_LIBDIR.

As far as I can tell, this means that even if you have a pkg-config install of python somewhere else, it will not ever actually be detected... it can only be detected if your default found python executable does not have a pkg-config file, AND it does have a `LIBPC` var that points to some other python install's pkg-config file.

If that is the case, I'd be very curious to know how we could distinguish the two...

**Comment by matthew-brett** [comment]
The Python on the PATH returns None from `sysconfig.get_config_var('LIBPC')`.

**Comment by eli-schwartz** [comment]
Aha! That does seem like a trivially solvable problem.
