### ISSUE TITLE
Meson gives me an error telling me to do something, and once I do it it gives me an error saying NOT to do it

### ISSUE THREAD

**Issue by Veinhelm** [mesonbuild/meson#9616]
**Describe the bug**
It keeps giving me an error saying to not use an absolute path (this is for the projectpath and fmod variable), and use a relative path instead. When I use a relative path, it tells me to use an absolute path.

**To Reproduce**
```
projectpath = '/home/veinhelm/dev/AVDSDLT'

if cpp.get_id() == 'gcc'
	
	SDL2 = dependency('SDL2', method : 'pkg-config')
	SDL2_image = dependency('SDL2_image', method : 'pkg-config')
	FMOD = cpp.find_library('fmod', dirs: projectpath / 'fmod/gcc/api/core/lib/x86_64')
	
	deps = [SDL2, SDL2_image, FMOD]
	
	executable('bin/AVDSDLT', sources : src, include_directories : include_directories(projectpath / 'fmod/gcc/api/core/inc'), dependencies : deps, gui_app : true)
	
endif
```

**Expected behavior**
For it to not keep contradicting itself, and to work if I do one of them or the other one.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?: Yes, trying to cross compile on Ubuntu on a VM running on Windows 10
* what operating system: Ubuntu 20.04.3
* what Python version are you using: 3.8.10
* what `meson --version`: 0.60.0

I don't know if I'm just stupid, but this looks like a bug to me.

**Comment by eli-schwartz** [comment]
> It keeps giving me an error saying to not use an absolute path (this is for the projectpath and fmod variable), and use a relative path instead.

The error has a line number and tells you to not use an absolute path for the projectpath and include_directories kwarg.

Specifically, it will show something like:
```
meson.build:15:1: ERROR: Tried to form an absolute path to a source dir.
You should not do that but use relative paths instead.

To get include path to any directory relative to the current dir do

incdir = include_directories(dirname)

After this incdir will contain both the current source dir as well as the
corresponding build dir. It can then be used in any subdirectory and
Meson will take care of all the busywork to make paths work.

Dirname can even be '.' to mark the current directory. Though you should
remember that the current source and build directories are always
put in the include directories by default so you only need to do
include_directories('.') if you intend to use the result in a
different subdirectory.
```

> When I use a relative path, it tells me to use an absolute path.

This error, on the other hand, happens when you switch *both* the include_directories, and the find_library, to use relative paths at the same time. In this case, the line number in the error message tells you to use an absolute path for the find_library call.

Specifically, it will show something like:

```
meson.build:12:1: ERROR: Search directory fmod/gcc/api/core/lib/x86_64 is not an absolute path.
```

Note: posting exact error messages is important.

**Comment by eli-schwartz** [comment]
The difference between one taking relative paths and one taking absolute paths, does seem a bit inconsistent, but it should be noted that find_library is typically meant to find system libraries, while include_directories is typically meant to add project internal paths.

Although actually I wonder why the former doesn't accept relative paths too, huh...


An example of what I think you're trying to do, is given here: https://mesonbuild.com/Shipping-prebuilt-binaries-as-wraps.html
