### ISSUE TITLE
The assets in https://github.com/mesonbuild/meson/releases/tag/0.60.1 looks weird

### ISSUE THREAD

**Issue by lygstate** [mesonbuild/meson#9633]
**Describe the bug**
Have two msi:
```
 meson-0.60.1-64.msi
 meson-0.60.1.1-64.msi
```
maybe upload inproper or other reason?

The assets in 0.60.0 is
```
meson-0.60.0-64.msi
 meson-0.60.0.pkg
 meson-0.60.0.tar.gz
 meson-0.60.0.tar.gz.asc
```

**Comment by eli-schwartz** [comment]
Nowhere in your issue description did you explain what you mean by the issue title.

**Comment by Tachi107** [comment]
0.60.1 is an old release, and assets look fine now. This issue can be closed
