### ISSUE TITLE
GitHub seems to think that "jsoref/meson" is the official meson repository

### ISSUE THREAD

**Issue by evverx** [mesonbuild/meson#9634]
I'm not sure whether anyone cares about this but looking at https://github.com/mesonbuild/meson/network/dependents and https://github.com/jsoref/meson/network/dependents it seems GitHub somehow thinks that https://github.com/jsoref/meson is the official meson repository. I don't know what exactly it affects but it could be that at least "security updates" repositories subscribe to via the security Dependabot described at https://docs.github.com/en/code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies/configuring-dependabot-security-updates could be broken. Then again, I have no idea whether anyone cares about that. Just wanted to let you know.

**Comment by jpakkane** [comment]
Even weirder is that if you go to that page it says `forked from mesonbuild/meson`. This seems like a Github problem to me.

**Comment by evverx** [comment]
I think it is but I guess to somehow fix it one of the owners of the mesonbuild organization should probably contact GitHub to ask them to point the dependency graphs to the official repository. Though I have to admit that's just an assumption that isn't based on anything.

**Comment by evverx** [comment]
I opened GH ticket #1407671. Let's see how it goes

**Comment by jpakkane** [comment]
Thanks.

**Comment by evverx** [comment]
The dependency graph was fixed. Closing
