### ISSUE TITLE
Better CI

### ISSUE THREAD

**Issue by jpakkane** [mesonbuild/meson#966]
Our current CI system is good but there are a lot of things missing:
- clang on Linux
- VS project builds
- XCode project builds (once someone actually fixes it)
- MinGW builds
- cross compilation, with and without exe wrappers
- unity builds, flat vs mirror layout
- and so on

The question is how could we have this? It probably requires self hosted hardware or paying money for Travis & co. Anyone with experience or suggestions for this?

**Comment by QuLogic** [comment]
Just add more builds to the matrix; don't see why it needs a different hosting solution?

**Comment by nirbheek** [comment]
We want it to not be unreasonably slow.

```
<jpakkane> Travis is free for one instance with one processor. I think.
<nirbheek> Do we care how much time it takes for the tests to run?
<jpakkane> For MRs yes, definitely.
<jpakkane> 5 min turnaround should be the maximum.
```

**Comment by QuLogic** [comment]
Separate builds in the matrix are run in parallel; at least 4 or 5 at a time. It depends on the overall load, but I don't recall ever seeing it only be one at a time. OSX is usually more loaded though, so maybe only 2 at a time, and it might take a little while to start.

AppVeyor on the other hand, is definitely one at a time.

**Comment by nirbheek** [comment]
Let's just add more Travis builds for now and see how it goes. If we run into problems, we can look into other options.

**Comment by jpakkane** [comment]
The simplest solution would be to run merge requests as currently but all the other ones in a separate CI system once a day.

**Comment by QuLogic** [comment]
I'm pretty sure the _simplest_ solution is adding everything to Travis instead of adding another CI.

**Comment by jpakkane** [comment]
Currently there is a MR that has been stuck waiting for Travis to start for an hour.

**Comment by QuLogic** [comment]
OSX is always backlogged; adding more Linux environments should not impact much unless there are like 10 of them.

**Comment by nirbheek** [comment]
Current status:

* ~~clang on Linux~~
* ~~VS project builds~~
* XCode project builds (once someone actually fixes it)
* MinGW builds
* cross compilation, with and without exe wrappers
* ~~unity builds~~, flat vs mirror layout

Next on my list is MinGW builds. Appveyor provides a MinGW environment, so we can do it.

**Comment by nirbheek** [comment]
Also needs: `Xvfb`-based X environment on Travis/Linux for tests that run GUIs, such as GTK+. This was needed in #1194, but I had to disable it.

**Comment by jpakkane** [comment]
We should not depend on a graphical interface being available because some build environments probably do not allow it (deb? rpm? other?)

**Comment by nirbheek** [comment]
That sounds wrong because several project test suites have at least some components that require X which are disabled when `DISPLAY` is not set. Even in Gentoo we had the ability to run `Xvfb` and set `DISPLAY` automatically for an ebuild that needed X for tests.

But if that's the case for deb or rpm, then we could add a way to skip tests that need some display server (X/Wayland/macOS/Windows) if a display server is not available.

**Comment by QuLogic** [comment]
Fedora would [use `Xvfb` if needed](https://fedoraproject.org/wiki/PackageMaintainers/GraphicalTests).

**Comment by nirbheek** [comment]
Current status:

* ~~clang on Linux~~
* ~~VS project builds~~
* XCode project builds (once someone actually fixes it)
* MinGW builds (#1346)
* ~~cross compilation~~, with and ~~without exe wrappers~~
* ~~unity builds~~

**Comment by nirbheek** [comment]
This issue has outlived its usefulness. Closing.

**Comment by sarum9in** [comment]
@nirbheek you did not close it for some reason. It looks obsolete to me, closing.
