### ISSUE TITLE
Error finding version of arm gcc 

### ISSUE THREAD

**Issue by MadsBerre** [mesonbuild/meson#967]
When meson tries to recognize the  version of arm-none-linux-gnueabi-gcc  it finds the wrong version. 

the output of arm-none-linux-gnueabi-gcc --version is: 

```
arm-none-linux-gnueabi-gcc (Sourcery CodeBench Lite 2014.05-29) 4.8.3 20140320 (prerelease)
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

printing the version within meson outputs: 
`2014.05-29`

**Comment by jpakkane** [comment]
Can you test #968 to see if it works for you?
