### ISSUE TITLE
Unknown CPU family ft32

### ISSUE THREAD

**Issue by perigoso** [mesonbuild/meson#9670]
I'm currently compiling a project for an embedded device usint a bridgetek FT902 (FT32 architecture in GCC), as I expected this is not a supported target on meson, I'm not sure what this target variable implies, but compiling with the unsupported
```
cpu_family = 'ft32'
cpu = 'ft900'
```
doesnt seem to produce any issues for me.

If there is something I can do about this let me know I'm open to contribute.

**Comment by eli-schwartz** [comment]
https://github.com/mesonbuild/meson/blob/bea735dd76db32f6ea34ab66fee496d4be2f7eb1/mesonbuild/environment.py#L297-L362

I assume you got the message from the end of that function.

If you'd like to submit a PR adding the new information then that would be great. ;)
