### ISSUE TITLE
"File name too long" error when use CMake subproject

### ISSUE THREAD

**Issue by smarttowel** [mesonbuild/meson#9676]
I want to use [libappimageupdate](https://github.com/AppImage/AppImageUpdate) as CMake subproject, so I add next lines to my `meson.build`:
```
cmake = import('cmake')
appimage_dep = cmake.subproject('appimageupdate').dependency('libappimageupdate')
```
Wrap file:
```
[wrap-git]
revision = main
url = https://github.com/AppImage/AppImageUpdate.git
clone-recursive=true
depth=1
```
But in configuration stage next error occurred:
```
OSError: [Errno 36] File name too long: '/home/pavel/myproject/client/build/subprojects/appimageupdate/__CMake_build/lib/libappimage/libarchive-EXTERNAL-prefix/src/libarchive-EXTERNAL/configure --with-pic --disable-shared --enable-static --disable-bsdtar --disable-bsdcat --disable-bsdcpio --with-zlib --without-bz2lib --without-iconv --without-lz4 --without-lzma --without-lzo2 --without-nettle --without-openssl --without-xml2 --without-expat'
```

[full.log](https://github.com/mesonbuild/meson/files/7626096/full.log)

Meson 0.60.2

**Comment by eli-schwartz** [comment]
@mensinda

But I'm going to predict this is irreparably broken. That project is attempting to download, configure, and build a ton of projects, in this case libarchive, which is a problem even without mangling the command from a cmake string into a real programming language array.

**Comment by mensinda** [comment]
Please try again with a newer CMake version. The `_guess_files` code path is only relevant for old CMake (<3.17) versions where we have to do some fancy guesswork regarding spaces in file paths.

**Comment by smarttowel** [comment]
Works with CMake 3.21.1, thanks.
