### ISSUE TITLE
Make Meson recover from bad download

### ISSUE THREAD

**Issue by nazar-pc** [mesonbuild/meson#9688]
**Describe the bug**
When meson encounters an error while downloading a dependency, it might get into inconsistent state with following error:
```
meson.build:147:0: ERROR: Subproject exists but has no meson.build file
```

**To Reproduce**
```meson
# meson.build
project('test', 'c')

executable('main', 'main.c',
  dependencies: [
    subproject('libuv').get_variable('libuv_dep')
  ]
)
```
```c
// main.c
int main(int argc, char **argv) {
    return 0;
}
```
```ini
# subprojects/libuv.wrap
[wrap-file]
directory = libuv-v1.42.0
source_url = https://dist.libuv.org/dist/v1.42.0/libuv-v1.42.0.tar.gz
source_filename = libuv-v1.42.0.tar.gz
source_hash = 43129625155a8aed796ebe90b8d4c990a73985ec717de2b2d5d3a23cfe4deb72
patch_filename = libuv_1.42.0-1_patch.zip
patch_url = https://bad-wrapdb.mesonbuild.com/v2/libuv_1.42.0-1/get_patch
patch_hash = 891698d781bc68379b799e47bc7e100698f03985b6db5d1ddc4eaa9be42a8f35

[provide]
libuv = libuv_dep
```

`bad-wrapdb` above will simulate a network error (in practice error might be caused by network timeout, temporary DNS resolution issue, etc.).

Now do usual `meson setup build` and you'll get an obvious error.

If you replace `bad-wrapdb` with `wrapdb` to simulate the end of intermittent network issues you'll get:
```
meson.build:3:0: ERROR: Subproject exists but has no meson.build file
```

**Expected behavior**
Meson shoudn't keep subprojects in inconsistent state when such issues happen and thus should be able to recover without requiring user to go and manually remove directories under `subprojects`.

Retries would also be nice to have I think, like 3 attempts with exponential backoff.

**system parameters**
* Plain native build
* Ubuntu 21.04
* Python 3.9.5
* Meson 0.60.2
* Ninja 1.10.2.git.kitware.jobserver-1

**Comment by eli-schwartz** [comment]
You can restore that with `meson subprojects update --reset`.

I guess deleting it makes sense, for cases where we know we just created it and therefore it cannot have pre-existing user content, potentially modified.

**Comment by nazar-pc** [comment]
Yes, I'm just concerned with simple cases like described where Meson knows that things will definitely break.

**Comment by nazar-pc** [comment]
We have a bit of funding available for this issue at mediasoup thanks to the donations project receives.

Requirements:
* [ ] make meson remove incomplete subproject files in case of network error to avoid "Subproject exists but has no meson.build file" error as described above
* [ ] add support for retries in case network connection has issues (3-5 attempts with exponential backoff would be ideal)
* [ ] submit as PR to meson
* [ ] get PR merged by meson maintainers

After that go to https://opencollective.com/mediasoup and send **$100 USD** expense to get paid for your work.

**Comment by eli-schwartz** [comment]
I kinda forgot about this issue, it turned out to be fairly simple to implement. Can you try the linked PR?
