### ISSUE TITLE
include_directories triggering missing-include-dirs warnings

### ISSUE THREAD

**Issue by TingPing** [mesonbuild/meson#974]
If you do `include_directories('something')` you get the both the build and source directory included. The problem with this is the build directory may not exist which triggers this warning if built with `-Wmissing-include-dirs`.

The simple solution is probably to create all included directories in the build dir?

**Comment by nirbheek** [comment]
> The simple solution is probably to create all included directories in the build dir?

Yeah, that makes sense.

**Comment by jpakkane** [comment]
That is what it should already be doing, but apparently there is a bug somewhere.

**Comment by TingPing** [comment]
Fixed by b01d2c35b7003071fc64c6d2e7d07b7652a8b386
