### ISSUE TITLE
Some compiler checks (has_header_symbol, has_type) fail when -Wall -Werror flags are used

### ISSUE THREAD

**Issue by igrr** [mesonbuild/meson#9741]
**Describe the bug**

I am trying to build [QEMU](https://gitlab.com/qemu-project/qemu) project with `-Werror` compiler option using clang compiler.

Some checks which QEMU does in its meson.build behave differently depending on whether `-Werror` compiler option is present:

```
cc.has_header_symbol('getopt.h', 'optreset')
cc.has_type('struct iovec', prefix: '#include <sys/uio.h>')
cc.has_type('struct utmpx', prefix: '#include <utmpx.h>')
```

The reason is that the test program generated by meson fails to compile. It triggers `-Wunused-value` warning (enabled by `-Wall`) which is being turned into an error by `-Werror`.

<details>
<summary>(relevant part of meson.log)</summary>

```
Running compile:
Working directory:  /Users/ivan/e/qemu/qemu/build/meson-private/tmp08h1tthv
Command line:  cc -m64 -mcx16 /Users/ivan/e/qemu/qemu/build/meson-private/tmp08h1tthv/testfile.c -o /Users/ivan/e/qemu/qemu/build/meson-private/tmp08h1tthv/output.obj -c -Werror -O0 -Werror=implicit-function-declaration -Werror=unknown-warning-option -Werror=unused-command-line-argument -Werror=ignored-optimization-argument -std=gnu11 

Code:
 #include <sys/uio.h>
        void bar(void) {
            sizeof(struct iovec);
        };
Compiler stdout:
 
Compiler stderr:
 /Users/ivan/e/qemu/qemu/build/meson-private/tmp08h1tthv/testfile.c:3:13: error: expression result unused [-Werror,-Wunused-value]
            sizeof(struct iovec);
            ^~~~~~~~~~~~~~~~~~~~
1 error generated.

Checking for type "struct iovec" : NO 
```
</details>

**To Reproduce**
Minimal reproducer: 
[meson.build.zip](https://github.com/mesonbuild/meson/files/7737188/meson.build.zip)

**Expected behavior**

Ideally compilation tests such as `has_type`, `has_header_symbol` shouldn't depend on the presence of -Werror flag in the default `c_args` or `cpp_args`.

**system parameters**
```
The Meson build system
Version: 0.60.99
Build type: native build
C compiler for the host machine: ccache cc (clang 13.0.0 "Apple clang version 13.0.0 (clang-1300.0.29.3)")
C++ compiler for the host machine: ccache c++ (clang 13.0.0 "Apple clang version 13.0.0 (clang-1300.0.29.3)")
Host machine cpu family: x86_64
OS: macOS 12.0.1
```

Also reproduced with GCC:
```
C compiler for the host machine: gcc-11 (gcc 11.2.0 "gcc-11 (Homebrew GCC 11.2.0) 11.2.0")
C++ compiler for the host machine: g++-11 (gcc 11.2.0 "g++-11 (Homebrew GCC 11.2.0) 11.2.0")
```

**Suggested fix**

* I have fixed the issue locally by adding a `(void)` cast in the code templates passed to the compiler. I.e. `(void) {symbol}` instead of `{symbol}`, `(void) sizeof({typename})` instead of `sizeof({typename});`.
* Another option I have considered is to add `-Wno-error=unused-value` in ClangCompiler and GnuLikeCompiler `get_compiler_check_args`, but this seems less reliable as other compilers may start warning about unused values as well.

I am happy to submit a PR with either of these options.

**Comment by QuLogic** [comment]
You should use the [builtin `werror` option](https://mesonbuild.com/Builtin-options.html#core-options) instead of passing `-Werror` in flags; I thought Meson warned about this already.

**Comment by igrr** [comment]
I see, thank you!
