### ISSUE TITLE
tools/ac_converter: failed to convert `HAVE_SANITIZER_LSAN_INTERFACE_H`

### ISSUE THREAD

**Issue by declanqian** [mesonbuild/meson#9747]
**Describe the bug**
tools/ac_converter failed to convert `HAVE_SANITIZER_LSAN_INTERFACE_H`

**To Reproduce**
- Create a minimal `config.h.meson` with content
```
#mesondefine HAVE_SANITIZER_LSAN_INTERFACE_H
```
- `ac_converter config.h.meson`
```
check_headers = [
  ['HAVE_SANITIZER_LSAN_INTERFACE_H', 'sanitizer/lsan/interface.h'],
]
```

**Expected behavior**
```
check_headers = [
  ['HAVE_SANITIZER_LSAN_INTERFACE_H', ''sanitizer/lsan_interface.h'],
]
```

**Comment by eli-schwartz** [comment]
So if I understand correctly, your issue is solely because meson doesn't know how to tell the difference between an underscore in a define being a literal underscore, or a transliterated directory slash?

I don't see what meson could do about this though. And FWIW, I think the script is wrong in its implementation:

```meson
check_headers = [
    'sanitizer/lsan_interface.h',
    'bar.h'
]

foreach h: check_headers
    if cc.has_header(h)
        cdata.set('HAVE_' + h.underscorify().to_upper(), 1)
    endif
endforeach
```

This makes it a lot easier to update the array of headers.

**Comment by declanqian** [comment]
> your issue is solely because meson doesn't know how to tell the difference
between an underscore in ...

Yeah, you are right. I reported for this exact reason. It's a minor issue which can cause surprise for new user
like me.

> I don't see what meson could do about this though

If `ac_converter.py` can't handle case like this, left it out should be an option? Blindly converting
seems to be an bug, IMO.

> `cdata.set('HAVE_' + h.underscorify().to_upper(), 1)`

I saw similar code in [gtk](https://gitlab.gnome.org/GNOME/gtk/-/blob/main/meson.build#L181) source. I'd prefer this too.

**Comment by eli-schwartz** [comment]
> If `ac_converter.py` can't handle case like this, left it out should be an option? Blindly converting seems to be an bug, IMO.

But no matter what it sees, it blindly converts it!

HAVE_FOO_BAR_H? Blindly converted to foo/bar.h

HAVE_FOO_BAR_BAZ_H? Blindly converted to foo/bar/baz.h

HAVE_SYS_TYPES_H? Blindly converted to sys/types.h

HAVE_PG_CONFIG_H? Converted to pg/config.h

It's usually correct, but the alternative is basically to ignore most everything. One could as easily delete the script. :)

On the other hand, it's fairly easy to use the script to stub out your code, then manually correct it. Could be easier, and will be if I modify it to use modern stuff like underscorify...

**Comment by declanqian** [comment]
> to use the script to stub out your code, then manually correct it.

Thanks for clarifying for me. This seems the right way to use this script.
I'll just close this.

> will be if I modify it to use modern stuff like underscorify

You may want to reopen it if you want to to track this. @eli-schwartz
