### ISSUE TITLE
Should not error out fallback subproject() for non-required dependency() fails to configure

### ISSUE THREAD

**Issue by tp-m** [mesonbuild/meson#975]
If a subproject() is used as fallback for an optional dependency that has not been found, Meson should not error out if the fallback subproject errors out. Instead it should note that the dependency was non-essential to start with and simply mark the dependency as not found and continue without using the fallback subproject.

**Comment by nirbheek** [comment]
Isn't this already fixed?

commit e411c0b9306601d1471eb98d431eedcb1fa37189
Author: Saunier Thibault <saunierthibault@gmail.com>
Date:   Mon Aug 29 16:31:10 2016 -0300

    Honor dependency `fallback` argument even if the dependency is not required (#735)
    
    You can potentially have a fallback subproject and if that subproject
    fails, you can continue without that dependency

**Comment by tp-m** [comment]
Ah, hrm, maybe.

I can't currently test this properly in my live setup because it is masked by issue #964 :)

Guess I should make a test case for it if there isn't one yet. I don't remember if I tested it with git master or not.

**Comment by nirbheek** [comment]
This does indeed work fine, but there was no test for it so I've added one: #1008.

**Comment by tp-m** [comment]
I'm not sure this works fine, unless the issue I'm running into is something else. With gst-build and no libxml2-dev installed:
```
...
Executing subproject gst-editing-services.
Project name: gst-editing-services
...
Dependency gst-validate-1.0 found: NO

Executing subproject gst-devtools.
Project name: gst-devtools
...
Library m found: YES
Also couldn't find a fallback subproject in subprojects/json-glib for the dependency json-glib-1.0
Also couldn't find a fallback subproject in subprojects/gst-devtools for the dependency gst-validate-1.0

Meson encountered an error in file subprojects/gst-editing-services/meson.build, line 66, column 0:
Native dependency libxml-2.0 not found.

tpm@beelink:~/gst-build/build$ grep -A2 gst-validate-1.0 ../subprojects/gst-editing-services/meson.build 
gstvalidate_dep = dependency('gst-validate-1.0', version : gst_req, required : false,
  fallback : ['gst-devtools', 'validate_dep'])
```

If this worked, shouldn't it simply mark `gstvalidate_dep` in `gst-editing-services` as not found and continue?

**Comment by nirbheek** [comment]
gst-editing-services required libxml2:

```
gstvalidate_dep = dependency('gst-validate-1.0', version : gst_req, required : false,
  fallback : ['gst-devtools', 'validate_dep'])

gio_dep = dependency('gio-2.0', version : glib_req)
libxml_dep = dependency('libxml-2.0')
```
