### ISSUE TITLE
Unable to add a CMake Subproject (ERROR: Assignment target must be an id.)

### ISSUE THREAD

**Issue by Tanishq-Banyal** [mesonbuild/meson#9754]
***PROBLEM :-***
I am unable to add cmake subprojects, getting some sort of syntax error ? And I am not sure what am i doing wrong. google was also of no help. can anybody please guide me on this ?

**Build command (from /home/CamPlay Directory) :-**
```
meson setup build/
```
**Error Message :-**
```
The Meson build system
Version: 0.60.2
Source dir: /home/CamPlay
Build dir: /home/CamPlay/build
Build type: native build

meson.build:3:0: ERROR: Assignment target must be an id.
openpnp-capture_proj = cmake.subproject('libs/openpnp-capture')
^
```

**My meson.build :-**
```py
cmake = import('cmake')

openpnp-capture_proj = cmake.subproject('libs/openpnp-capture')
tensorflow-lite_proj = cmake.subproject('libs/tensorflow-lite')

project('CamPlay', 'cpp')

deps = [
	 openpnp-capture_proj.dependency('openpnp-capture'),
	 tensorflow-lite_proj.dependency('tensorflow-lite'),
]

executable('CamPlay', 'src/main.cpp', dependencies: deps, override_options: ['cpp_std=c++20'])
```

**Project structure :-**
```
CamPlay
│
├── libs
│   ├── openpnp-capture
│   │   ├── ...
│   │   └── CMakeLists.txt
│   │
│   └── tensorflow-lite
│       ├── ...
│       └── CMakeLists.txt
│
├── meson.build
└── src
    ├── ...
    └── main.cpp
```

**Comment by eli-schwartz** [comment]
The error message states that this line is the problem:

```meson
openpnp-capture_proj = cmake.subproject('libs/openpnp-capture')
```

Specifically, the problem is that you cannot use a hyphen in a variable name, use underscores instead.

**Comment by Tanishq-Banyal** [comment]
![blank stare](https://c.tenor.com/s1XrMQU5md0AAAAM/steve-carell-blank-stare.gif)

**Maybe you guys should make the error message more clearer**

**Comment by mid-kid** [comment]
I just got this error when trying to do `dict[key] = executable(...`. I wasn't aware you couldn't assign non-existing keys to create them.
