### ISSUE TITLE
RFC: delete the rpm module

### ISSUE THREAD

**Issue by eli-schwartz** [mesonbuild/meson#9764]
Quite some time ago, @ignatenkobrain added an RPM module. This is no longer actively supported, doesn't seem to be tested, and on at least one occasion has broken for 3 years straight ***and no one even noticed***.

From taking a quick look at it, it does a lot of fragile sorcery by poking at internal coredata details, so it will inevitably break, be broken, and keep breaking if it isn't actively maintained.

I propose that no one uses it, no one should be using it, and we shouldn't commit to providing it.

For context, the purpose of this module is apparently *NOT* that your meson.build should actually use this module... The purpose of it is to temporarily add this module to meson.build, configure meson ***once*** in order to generate an RPM spec file, and then delete it from meson.build again. The developer can then manually edit the spec file (some things are missing from it), commit it to git, and maintain it purely manually from then on.

This dramatically decreases its value, because it is never actively used.

@dcbaker suggested on IRC that this would be better off as an independent script that reads the introspection data and creates a spec file based on that.

Opinions?

**Comment by eli-schwartz** [comment]
Previous issues:
#955
#1409
#2202
#6384

Current issue, which is known to be broken and the proposed fix is also broken: #9763

The common denominator here is that outright python syntax errors, as well as fundamental incompatibilities with various code refactorings, lead to meson just... crashing.

**Comment by dcbaker** [comment]
I'm in favor of deleting it, and someone (not me) writing a script. If someone wanted to step up and be maintainer that would be okay as well, but I'd prefer it become an external script.

**Comment by nirbheek** [comment]
Nuke it!
