### ISSUE TITLE
wrapdb.mesonbuild.com SSL issue on Windows

### ISSUE THREAD

**Issue by elmarco** [mesonbuild/meson#9768]
**Describe the bug**

When building glib from Windows docker:

meson.build:2002:2: ERROR: WrapDB connection failed to https://wrapdb.mesonbuild.com/v2/pcre_8.37-2/get_patch with error <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>

**To Reproduce**

The dockerfile where I tried various workarounds without success:
https://gitlab.freedesktop.org/elmarco/dbus/-/blob/win-ci2/ci/docker/windows/Dockerfile

**Expected behavior**
Download and compilation to succeed

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
* native

* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
* Windows

* what Python version are you using e.g. 3.8.0
* mingw-w64-ucrt-x86_64-python-3.9.7-4

* what `meson --version`
* meson-0.60.3-py3-none-any.whl

**Comment by tp-m** [comment]
This is probably related to https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/ and means something in your stack needs their certificates to be updated, or you need to switch to a newer windows image.

You could try if something like [this](https://gitlab.freedesktop.org/cairo/cairo/-/blob/master/.gitlab-ci.yml#L343-349) helps (but this is just cargo culting really).

Anyway, likely not a meson bug.
`

**Comment by elmarco** [comment]
Thanks Tim

certifi-win32 sems to work, as long as I fetch URL manually before:
```
RUN pip3 install python-certifi-win32
RUN (New-Object System.Net.WebClient).DownloadString('https://sourceforge.net') >$null
RUN (New-Object System.Net.WebClient).DownloadString('https://wrapdb.mesonbuild.com/v2/pcre_8.37-2/get_patch') >$null
RUN (New-Object System.Net.WebClient).DownloadString('https://zlib.net/fossils/') >$null
```

Upstream issue seems to be https://bugs.python.org/issue36011 (surprisingly not very active)

**Comment by xclaesse** [comment]
GStreamer does that same trick: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/blob/main/ci/docker/windows/prepare_gst_env.ps1#L6
