### ISSUE TITLE
DESTDIR not working correctly if prefix is defined

### ISSUE THREAD

**Issue by rhd** [mesonbuild/meson#977]
I would expect `DESTDIR` env varible to override the setting in `prefix`

In my `meson.build` file, I have:
```
    default_options : ['buildtype=debugoptimized',
                       'cpp_std=c++11',
                       'errorlogs=true',
                       'prefix=@0@/dist'.format(meson.current_source_dir())]
```

If I type `DESTDIR=/foo ninja -C build install`, meson concats `/foo` and the prefix like this ` /foo/path/to/project/dist/bin/Exe`

Is this expected?

Thanks!

**Comment by TingPing** [comment]
That is correct. DESTDIR is the directory the install goes into and it does not override the prefix at all. The use case for this is packaging so you can install into a directory then package that up where it will be extracted into the normal prefix.

**Comment by nirbheek** [comment]
`DESTDIR` never overrides `prefix`; it simply prepends to it. What exactly are you trying to do with that default value of `prefix`? Are you trying to create a dist target?

**Comment by rhd** [comment]
Basically, what I'm trying to do is:

1. Set the default destination directory for 'ninja install' (I don't want the default to be a system install) and
1. Allow our CI to change the install directory without gymnastics.

It looks like using DESTDIR (and not prefix) is the way to go? It doesn't look like there is a way to set the default destdir (it's env only).

```python
def do_install(datafilename):
    with open(datafilename, 'rb') as ifile:
        d = pickle.load(ifile)
    d.destdir = os.environ.get('DESTDIR', '')
    d.fullprefix = destdir_join(d.destdir, d.prefix)
```

I have a couple people using meson with me and I'd like `ninja install` to put the installed files in the root of their source directory. This way we don't clobber each other if we're working on the same machine. I'm currently using `prefix`, maybe using `DESTDIR` and a makefile would be better.

**Comment by jpakkane** [comment]
> I'd like ninja install to put the installed files in the root of their source directory

I don't really grasp what you are trying to do but this is almost certainly not the way you want to do it. There is the source, build and install directories and you should always keep them separate. Mixing them can lead to extremely weird issues.

The common approach is to install your stuff to a directory in your home dir during development. That means roughly the following:

    meson -Dprefix=/home/username/devroot <other args>
    ninja
    ninja install

Now you can run your installed executable from `~devroot/bin/yourexe`. If your program uses shared libraries you may need to set ´LD_LIBRARY_PATH=/home/yourname/devroot/lib` or equivalent.

**Comment by TingPing** [comment]
If it is for a CI it might be easier to do `--prefix=~/.local` as that is configured to be in most paths and should generally "just work".

**Comment by rhd** [comment]
Thanks everyone. @jpakkane `-Dprefix` didn't work, I needed to do `--prefix`.

What I ended up doing was passing in a different `prefix` on the meson command line if the CI was building the code.

Although, I'm still not sure how `DESTDIR` is useful if you sent the prefix to something like `/home/username/devroot`.

**Comment by nirbheek** [comment]
`DESTDIR` is not useful for an installation that will be directly used. It is used only for two purposes AFAIK, and this is universal across all build systems including Autotools:

1. Packaging. You install everything into a destination directory and then create a `.deb` or `.tar.gz`, etc package from it.

2. Testing. You can test that the installation will proceed as expected without clobbering your existing prefix.

I will close this issue now since it's been resolved on your end. Cheers!
