### ISSUE TITLE
Fail to find ninja when `meson install` with VS15 environment

### ISSUE THREAD

**Issue by elmarco** [mesonbuild/meson#9774]
**Describe the bug**
`meson install` doesn't find ninja (but `meson build` does)

**To Reproduce**
Run meson with VS15
```
Found ninja-1.8.2 at C:\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.EXE
Visual Studio environment is needed to run Ninja. It is recommended to use Meson wrapper:
C:\Python310\Scripts\meson compile -C builddir
```

meson build works
meson install fails with: Can't find ninja, can't rebuild test.

(I suspect the environment is modified with coredata or build.dat loading, so meson `build` works)

**Comment by nirbheek** [comment]
I am not sure how to reproduce this. Could you paste / attach `builddir/meson-logs/meson-log.txt`?

**Comment by nirbheek** [comment]
Okay, I can reproduce it.

**Comment by elmarco** [comment]
thanks! sorry for the bad bug report ;)
