### ISSUE TITLE
`meson wrap status` with non-wrapdb wrap should have better message

### ISSUE THREAD

**Issue by sielicki** [mesonbuild/meson#9787]
**Describe the bug**
When you call `meson wrap status` and you have one or more wrap files which are not from wrapdb, the following line will print

`Wrap file not from wrapdb`

It would be better if it described which wrap file it is referring to.

**To Reproduce**
Omitting because it's obvious

**Expected behavior**
Print something akin to `Wrap file 'userwrap.wrap' is not from wrapdb`

**Comment by eli-schwartz** [comment]
Fixed in #9984
