### ISSUE TITLE
Unknown CPU Family arm64

### ISSUE THREAD

**Issue by imustbebored** [mesonbuild/meson#9801]
While attempting to use the kiwix-build command, I receive the following error:

gitupdate libkiwix : WARNING : Cannot update, please check log for information
prepare sources _ios_fat_lib :

When checking the log, I found the following info:

WARNING: Unknown CPU family arm64, please report this at https://github.com/mesonbuild/meson/issues/new

**Comment by dcbaker** [comment]
Out of curiosity, what platform are you on that you're getting `arm64`?

**Comment by imustbebored** [comment]
I am on a MacBook pro, but the tool that I am using (kiwix-build) is running to generate a framework for multiple iOS devices (both iOS_x86_64 and iOS_arm64).

 I need this framework in order to run my iOS app on physical iOS devices, but unfortunately when I run it with --make-release flag, it errors out with the above.

**Comment by dcbaker** [comment]
The arm64 issue is just a warning, we try to normalize system and architecture names. It's just warning you that users are expecting `aarch64` and not `arm64`.

**Comment by dcbaker** [comment]
It even looks like the arm64 may have been fixed in a more recent version
