### ISSUE TITLE
WrapDB: expired certificate?

### ISSUE THREAD

**Issue by lemzwerg** [mesonbuild/meson#9805]
Recently, the gitlab instance on freedesktop.org produces fails as follows while building [FreeType on the Windows platform](https://gitlab.freedesktop.org/freetype/freetype/-/jobs/17434697):

```
Downloading zlib patch from
  https://wrapdb.mesonbuild.com/v1/projects/zlib/1.2.11/5/get_zip
A fallback URL could be specified using patch_fallback_url key in the wrap file
WrapDB connection failed to
  https://wrapdb.mesonbuild.com/v1/projects/zlib/1.2.11/5/get_zip
with error
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED]
  certificate verify failed: certificate has expired (_ssl.c:1122)>```

Is the certificate really expired, or this is a problem on our side?

**Comment by xclaesse** [comment]
That URL works for me, maybe just a hiccup on your CI?

Note that it uses an old version of the zlib wrap, you can update it with `meson wrap update zlib`.

**Comment by lemzwerg** [comment]
OK, thanks.

Note that I've just tried to update the zlib wrap with this command, and it says that it is up to date.  Why do you think it is an old version?

**Comment by lemzwerg** [comment]
Ah, ok.  Will the new file be backward compatible with older meson versions?

**Comment by eli-schwartz** [comment]
It will. The wrap file once added contains the exact urls to retrieve files from (v2 API urls) and any version of meson will treat those as files to download.

It is just the search API that meson needs to be version-aware for.

**Comment by lemzwerg** [comment]
Thanks for the info.  Now closing.
