### ISSUE TITLE
gnome.generate_gir() includes extraneous libraries in the gir file

### ISSUE THREAD

**Issue by TingPing** [mesonbuild/meson#981]
Currently when you pass a library to `gnome.generate_gir()` we extract every dependency from that and pass it along to `g-ir-scanner` as `LDFLAGS`. What happens after that is to be investigated but I can say the end result is incorrect:

Meson:
```xml
<namespace name="Ide"
           version="1.0"
           shared-library="libegg-private.so.0,libtemplate-glib-1.0.so.0,libcairo.so.2,libjavascriptcoregtk-4.0.so.18,libgdk_pixbuf-2.0.so.0,libatk-1.0.so.0,libwebkit2gtk-4.0.so.37,libcairo-gobject.so.2,libxml2.so.2,libgirepository-1.0.so.1,libgdk-3.so.0,libgtksourceview-3.0.so.1,libsoup-2.4.so.1,libgio-2.0.so.0,libgmodule-2.0.so.0,libgobject-2.0.so.0,libpangocairo-1.0.so.0,libglib-2.0.so.0,libfreetype.so.6,libgtk-3.so.0,libpango-1.0.so.0,libfontconfig.so.1,libpangoft2-1.0.so.0,libpeas-1.0.so.0,libide-1.0.so"
           c:identifier-prefixes="Ide"
           c:symbol-prefixes="ide">
```

Autotools:
```xml
<namespace name="Ide"
           version="1.0"
            shared-library="libide-1.0.so,libegg-private.so.0,libtemplate-glib-1.0.so.0"
           c:identifier-prefixes="Ide"
           c:symbol-prefixes="ide">
```

The Autotools version is correct and are explicitly passed dependencies by the user (effectively equal to `link_with` in Meson). The problem is the automatic dependencies only needed for building also get shoved there.

As a naive approach I just stopped passing the flags as they didn't seem to matter for my project but it is correct to be passed as #947 indicates. We just need to figure out why us passing them has the incorrect result and in autotools it has the correct one.

**Comment by ebassi** [comment]
This kind of broke the GTK-Doc functionality of the gnome module, because now it's getting `--extra-library` in the linker flags.
