### ISSUE TITLE
reconfigure shows option has been changed, configure output shows option has not been changed

### ISSUE THREAD

**Issue by andy5995** [mesonbuild/meson#9813]
**Describe the bug**
When using `meson --reconfigure`, meson reports option has been changed, but afterward, running `meson configure` shows the old option is still active.

**To Reproduce**
1. `meson configure' outputs 

```
...
`warning_level      3                    [0, 1, 2, 3]         Compiler warning level to use`
...
```

2. `meson --reconfigure -Dwarning_level=2` outputs

```
...
  User defined options
    backend       : ninja
    prefix        : /home/andy/.local
    warning_level : 2
    c_args        : -shared
    c_link_args   : -disable-shared
    without-curses: false

Found ninja-1.10.2 at /usr/bin/ninja
Generating targets:   0%|                                                    | 0/25 [00:00                                                                                          Writing build.ninja:   0%|                                                   | 0/77 [00:00                                                                                          Cleaning... 0 files.
```

3. `meson configure` then outputs

```
warning_level      3                    [0, 1, 2, 3]         Compiler warning level
```

**system parameters**
* native
* Manjaro 21.2.1
* Python 3.10.1
* meson 0.60.3
* ninja 1.10.2

**Comment by andy5995** [comment]
Some extra detail about this

After doing the 3 steps above, running `meson --reconfigure` (with no flags) will still show the warning level is set to 2. `meson configure` will show the warning level is at 3.

The same thing happens when trying

`meson --reconfigure -Dc_args=-Wall`

The output will show 'c_args       : -Wall'

Running `meson --reconfigure` again (with no flags) will show that '-Wall' is still set. `meson configure` will show that it is *not* set.

**Comment by eli-schwartz** [comment]
This, too, works for me.

**Comment by andy5995** [comment]
We cleared it up in https://github.com/mesonbuild/meson/issues/9814#issuecomment-1015098210 where I explained the error of my ways.

Closing...
