### ISSUE TITLE
[suggestion] 'meson configure' should show warning or error message when option has not been changed

### ISSUE THREAD

**Issue by andy5995** [mesonbuild/meson#9814]
**Describe the bug**
`meson configure` should show warning or error when option has not been changed

**To Reproduce**

If warning level is set to 3, `meson configure -Dwarning_level=2` returns the user back to the prompt, returning an exit code of 0.

`meson configure` shows the option has not been changed. If I understand how meson is intended to behave, that option can't be changed using `configure`, but can if using `--reconfigure` (see also possibly related https://github.com/mesonbuild/meson/issues/9813)

**system parameters**

* native build
* Manjaro 21.2.1
* Python 3.10.1
* meson 0.60.3
* ninja 1.10.2

**Comment by eli-schwartz** [comment]
I don't think it makes any sense to emit a warning when meson fails to do what it says it is going to do, we should just do it (or error out).

But as far as I know, this does work fine. Options are changed, the next run of `ninja` causes a reconfigure with the new options. (It is possible to run `meson configure` multiple times.)

**Comment by andy5995** [comment]
> But as far as I know, this does work fine. Options are changed, the next run of `ninja` causes a reconfigure with the new options. (It is possible to run `meson configure` multiple times.)

Ah.. just tried that and it works. Imo, that's a bit confusing though... but I'm a small guy in a big project so I won't say anymore about it unless someone else chimes in to agree with me. ;) In either case, thanks for the follow-up and explanation @eli-schwartz

**Comment by eli-schwartz** [comment]
For me, even `meson configure` shows the option has changed. I simply cannot get it to report the old version of the value.

**Comment by andy5995** [comment]
Ok, now I see my error, partly caused by the fact I am not used to working with subprojects yet. I was seeing the warning_level as 3 at the tail end of the output, which was for the subproject. When I scroll up, I see indeed the warning level for the superproject matches what I just used for `meson configure -Dwarning_level=...`

I guess again, I'll have to work earlier in the day. ;) I apologize for the false report, and I thank you for being thorough in your follow-up.

**Comment by eli-schwartz** [comment]
Alright, great. Happy to help resolve that.

It's an understandable error to make...
