### ISSUE TITLE
Meson complaining about use of -fsanitize-recover=alignment

### ISSUE THREAD

**Issue by tristan957** [mesonbuild/meson#9822]
**Describe the bug**
When using `-fsanitize-recover=alignment`, Meson thinks I am using the `-fsanitize` argument I supposed, so it gives the following warning:

```
meson.build:64: WARNING: Consider using the built-in option for sanitizers instead of using "-fsanitize-recover=alignment".
```

**To Reproduce**
Add the argument to your project.

**Expected behavior**
Not warn, since this flag is about adjusting behavior of the sanitizer instead of enabling it.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? No
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) Fedora 35
* what Python version are you using e.g. 3.8.0 3.10.1
* what `meson --version` 0.59,.5
* what `ninja --version` if it's a Ninja build 1.10.2

Something tells me the fix is probably just fixing the `-fsanitize` detection logic.

**Comment by kcgen** [comment]
Still hitting this in 1.1.0

**Comment by tristan957** [comment]
See the linked PR. I am sure it'll get picked up again in the future.

**Comment by kcgen** [comment]
> See the linked PR. I am sure it'll get picked up again in the future.

Indeed! Thanks for the heads up,  @tristan957.
