### ISSUE TITLE
In some cases, behavior of 'meson dist' and 'ninja dist' is different

### ISSUE THREAD

**Issue by andy5995** [mesonbuild/meson#9823]
**Describe the bug**

Maybe it's a `ninja` bug?

If the meson.build is changed but not not committed, `ninja dist` will name the distribution archive using the version number that is currently in the meson.build, instead of the intended behavior of using the version from the state of the last commit.

`meson dist` operates as intended (the resulting file is named using the version number from the meson.build in the latest commit).

https://mesonbuild.com/Creating-releases.html#autotools-dist-vs-meson-dist

>Meson behaviour is different from Autotools. The Autotools "dist" target packages up the current source tree. Meson packages the latest revision control commit. The reason for this is that it prevents developers from doing accidental releases where the distributed archive does not match any commit in revision control (especially the one tagged for the release).

**system parameters**
* native build
* Manjaro 21.2.1
* Python 3.10.1
* meson 0.60.3
* ninja 1.10.2

I discovered this bug the hard way. I used 'ninja dist' for my first couple releases after switching to meson. I hadn't read the docs and didn't know it was going to package files based on the last commit. Before a release, I usually make any last minute changes, run `make dist` (in this case, `ninja dist`), then if all is well, I do the commit and push. 

The distribution package name matched the release version in the changed meson.build, even though the meson.build inside the archive didn't have my latest changes (since I hadn't committed yet).

**Comment by eli-schwartz** [comment]
ninja dist does two things:
- perform the normal check, first thing, to see if `build.ninja` is up to date, and if not, perform a meson reconfigure
- run the command `meson dist`

In this case, it seems you did something like:
- build the project, check that it works etc.
- edit meson.build to update the version number
  - missing step, did not happen: try to build the project using the change
- run `meson dist`

meson dist then loads the configured build system, uses the old version number, and archives the project for dist.

Instead, running `ninja dist` will notice that the configured build system is out of date, reconfigure, update the version number that meson dist sees, and then run meson dist. Hence, different behavior.

> The Autotools "dist" target packages up the current source tree. Meson packages the latest revision control commit.

That is, generally, true. But that does not mean meson completely ignores the current source tree. It does use a couple inputs:
- the project version
- `meson.add_dist_script()`

Those do not necessarily match what is committed to git.

On the other hand, you might commit the version number to git, then run `meson dist` using an out of date builddir/ with the wrong version number.

**Comment by andy5995** [comment]
>       * missing step, did not happen: try to build the project using the change
 
Ok, so tested again and that works for me.
