### ISSUE TITLE
emit error message and exit if the repo has uncommitted changes

### ISSUE THREAD

**Issue by andy5995** [mesonbuild/meson#9824]
I just wanted to suggest putting this warning at the bottom of the `meson dist` output

>WARNING: Repository has uncommitted changes that will not be included in the dist tarball

I had a bit of trouble because I hadn't read the paragraph in the docs about [how `meson dist` works](https://mesonbuild.com/Creating-releases.html#autotools-dist-vs-meson-dist), and I feel that it's an important warning that could be easily missed (especially by nubs like myself) after it's scrolled away.

**Comment by andy5995** [comment]
I wanted to suggest a couple other options on how to implement this

Maybe meson should stop immediately after warning, and request confirmation with a flag. For example, this is what happens when using `cargo publish`

```
error: 1 files in the working directory contain changes that were not yet committed into git:

Cargo.toml

to proceed despite this and include the uncommitted changes, pass the `--allow-dirty` flag
```

At this point, I kind of prefer doing it that way, because I think that in most cases, if the developer is using `meson dist`, most likely he or she forgot they had uncommitted changes and therefore there isn't any use of meson performing a 'dist'.

> I just wanted to suggest putting this warning at the bottom of the `meson dist` output
> 
> > WARNING: Repository has uncommitted changes that will not be included in the dist tarball

My other suggestion would be to *not* move the warning, but instead show a warning counter at the tail end of the output (which might be useful for other situations as well, when the warnings scroll off the screen).

Example:

>Warnings: 2

**Comment by eli-schwartz** [comment]
I'd be interested in a PR to add an --allow-dirty flag and otherwise error out. Would you like to submit one?

**Comment by andy5995** [comment]
@eli-schwartz I started on a draft in #9839

I have extremely limited python experience and may already have questions, but I'm quitting for the night.

Cheers!

**Comment by eli-schwartz** [comment]
Cool, sounds great.

The best way to learn is by trying, after all -- feel free to ask any questions whatsoever. (Probably the best place to ask questions is in a real-time chat, i.e. IRC/Matrix.)
