### ISSUE TITLE
Cannot avoid 'more than one output' warning from generator depends

### ISSUE THREAD

**Issue by matthew-brett** [mesonbuild/meson#9837]
Consider the reproducer below.   A generator depends on a `custom_target` that has two outputs:

```
make_empty = custom_target(
  'make_empty_files',
  output: [ 'file1', 'file2' ],
  command: [ touch, '@OUTPUT@' ],
  )

gen_empty = generator(cp,
  arguments : ['@INPUT@', '@OUTPUT@'],
  output : '@BASENAME@.c',
  depends : make_empty)
```

When using the generator,

```
executable('bar', gen_empty.process(make_empty[0]))
```

I believe it is not possible to avoid the following warning:

```
WARNING: custom_target 'make_empty_files' has more than one output! Using the first one.
```

In fact, in my case, I want the generator to depend on _all_ outputs, but I am happy to specify one, if that would silence the warning.  However, I do not believe there is any way to specify all outputs, and specifying one gives an error. For example:

```
gen_empty = generator(cp,
  arguments : ['@INPUT@', '@OUTPUT@'],
  output : '@BASENAME@.c',
  depends : make_empty[0])
```

gives:

```
ERROR: generator keyword argument "depends" contained a value of type "CustomTargetIndex" but should have been one of: "BuildTarget", "CustomTarget"
```

See [this comment and following](https://github.com/scipy/scipy/pull/15407#issuecomment-1013720363) for a little more discussion.

**To Reproduce**

```
project('reproduce', ['c'])

touch = find_program('touch')
cp = find_program('cp')

make_empty = custom_target(
  'make_empty_files',
  output: [ 'file1', 'file2' ],
  command: [ touch, '@OUTPUT@' ],
  )

gen_empty = generator(cp,
  arguments : ['@INPUT@', '@OUTPUT@'],
  output : '@BASENAME@.c',
  depends : make_empty)

executable('bar', gen_empty.process(make_empty[0]))
```

**Expected behavior**

I would like to be able to specify `depends` depends on _all_ outputs, or specify outputs.   Alternatively, I would like some way to silence the warning, on the basis that I have reviewed the code and considered the consequences.

**system parameters**

Not cross-build.

macOS 12.1

Python 3.9

```
$ meson --version                                          
0.61.1
```

**Comment by rgommers** [comment]
This was first reported in gh-7466, which is closed as fixed (but it's not). There is also gh-7891, which is still open and provides a very similar example to the one in this issue.

Given that this issue has incoming links to it, I propose to close gh-7891 as a duplicate.

**Comment by rgommers** [comment]
This works now 🎉. Fixed in 1.5.0, by gh-12956

**Comment by eli-schwartz** [comment]
Does that mean there's nothing left to do here?

**Comment by rgommers** [comment]
@eli-schwartz there is, but the most annoying problem is solved and what remains is captured also in gh-7891, so I propose to close this.

For the above example:
1. `gen_empty.process(make_empty[0])` works and is tested
2. `gen_empty.process(make_empty)` works but emits an annoying warning:

```
WARNING: custom_target 'make_empty' has more than one output! Using the first one. Consider using `make_empty[0]`.
```

That warning is what gh-7891 is about though, so I think we should close this issue.

**Comment by eli-schwartz** [comment]
Sounds good to me.
