### ISSUE TITLE
Which environment does meson inherit from the launching shell on windows?

### ISSUE THREAD

**Issue by Makogan** [mesonbuild/meson#9843]
I am porting a linux library to windows and I am trying to compile it within wingwin using msvc isntead of gcc (for a variety of reasons).

To that effect I am aliasing the cl command within the bash terminal if I run `cl` I see:

```
Makogan@DESKTOP-4FMS6J2 MINGW64 ~/Documents/neverengine (CompileOnWindows)
$ cl
Microsoft (R) C/C++ Optimizing Compiler Version 19.13.26131.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

usage: cl [ option... ] filename... [ /link linkoption... ]
```

Which is correct, but if I try to set the meson compiler I get an error:

```
$ env CXX=cl meson build_cl
The Meson build system
Version: 0.60.3
Source dir: C:\Users\Makogan\Documents\neverengine
Build dir: C:\Users\Makogan\Documents\neverengine\build_cl
Build type: native build
Project name: NeverEngine
Project version: 0.0.1

meson.build:1:0: ERROR: Unknown compiler(s): [['cl']]
The following exception(s) were encountered:
Running "cl /?" gave "[WinError 2] The system cannot find the file specified"

A full log can be found at C:\Users\Makogan\Documents\neverengine\build_cl\meson-logs\meson-log.txt
```

Why can't meson find the cl command even though it's launched by the same shell?

**Comment by eli-schwartz** [comment]
The bash shell doesn't export aliases to subprocesses, only environment variables. Even if it did, meson doesn't implement a unix shell and wouldn't know what to do with an alias if it saw one. So as far as meson is concerned, it tried to find the text string command `cl` and it could not be found on the PATH or run via CreateProcess.
