### ISSUE TITLE
Allow list of dependency names

### ISSUE THREAD

**Issue by Jan200101** [mesonbuild/meson#9856]
at the moment you would fetch a dependency by doing
```meson
freetype_dep = dependency('freetype2')
```
which works for most libraries, but projects like Lua are a bit iffy with that.

There is not one single lua pkg-config file, collective I've found there are (taking lua5.4 as an example):
- lua5.4.pc (Debian)
- lua.pc (Fedora)
- lua-5.4.pc (FreeBSD)

any maybe even more

at the moment you would naively solve it like this (or through a list that you iterate through with a for loop and then set a variable)
```meson
lua_dep = dependency('lua5.4', required : false)
if not lua_dep.found()
    lua_dep = dependency('lua-5.4', required : false)
    if not lua_dep.found()
        lua_dep = dependency('lua')
    endif()
endif
```
But this is quite messy, doesn't scale well and doesn't play nice with forced fallbacks.

Instead I propose allowing a list of names to be passed instead
```meson
lua_dep = dependency(['lua5.4', 'lua-5.4', 'lua'])
```

It would iterate through the list of names and use the first one it can find, otherwise act as normal

**Comment by eli-schwartz** [comment]
This exact functionality was added in meson 0.60.0

**Comment by Jan200101** [comment]
Is it? I hadn't seen any documentation that reflects this or any use of it like that.
I'll install from git and check later

**Comment by eli-schwartz** [comment]
https://mesonbuild.com/Release-notes-for-0-60-0.html#dependencies-with-multiple-names

https://mesonbuild.com/Reference-manual_functions.html#dependency
> Since 0.60.0 more than one name can be provided, they will be tried in order and the first name to be found will be used. The fallback subproject will be used only if none of the names are found on the system. Once one of the name has been found, all other names are added into the cache so subsequent calls for any of those name will return the same value. This is useful in case a dependency could have different names, such as png and libpng.
