### ISSUE TITLE
Emscripten

### ISSUE THREAD

**Issue by felipellrocha** [mesonbuild/meson#986]
Hey guys!

What would be the steps to get a c++ project compiled for emscripten?

Thanks!

**Comment by jpakkane** [comment]
First you need to set up a cross file and try to compile your app with it. After that you might need to write a compiler definition file (in `compilers.py`) for Emscripten. If no weird surprises pop up, that should be it.

**Comment by nirbheek** [comment]
Closing this support issue because of inactivity.

**Comment by Type1J** [comment]
I'd like to see this issue reopened and support added for compiling using Emscripten with a command-line switch.

Support for Emscripten out-of-the-box would attract attention to Meson because it's something that most other build systems require a great deal of setup to accomplish, yet it's a very desirable feature.

**Comment by nirbheek** [comment]
It would be great to have support for compiling using Emscripten, would you be interested in working on that? We would happily help you come up with the best way for implementing it, and help you with your pull request.

**Comment by Type1J** [comment]
I'll do some code dives when I have some time.

**Comment by lieff** [comment]
I need this too.

**Comment by Type1J** [comment]
It doesn't look like I'm going to have any time for this feature because we dropped it. I know that there's an `emconfigure` and `emcmake` that are supposed to be used as prefixes to your `./configure` or `cmake` commands for those build systems. Toolchain setup should be simple, as @jpakkane said.
