### ISSUE TITLE
Invalid XML generated in testlog.junit.xml with \x07 in test output

### ISSUE THREAD

**Issue by samay-sharma** [mesonbuild/meson#9894]
**Describe the bug**

I was running tests with meson and the output of one of my tests contains special character `\x07`. When I run testlog.junit.xml through xmllint, I get an error saying:

`testlog.junit.xml:11045: parser error : PCDATA invalid Char value 7`

I think we should use the right escape characters so that the output is valid XML.

**To Reproduce**

I wrote a simple meson.build file to reproduce this issue. The code in the file is:

```
project('tutorial', 'c')
test('mytest',find_program('python'), args: ['-c','print(u"Test\x07")'])
```

I then ran `meson setup`, followed by `ninja test` to run it and generate the `testlog.junit.xml` file. Then, running:

`xmllint builddir/meson-logs/testlog.junit.xml`  outputs an error message:

```
builddir/meson-logs/testlog.junit.xml:2: parser error : PCDATA invalid Char value 7
e name="mytest" classname="tutorial" time="0.06694579124450684"><system-out>Test
```

**Expected behavior**

I think the character should be correctly escaped so that the output is valid XML.

**system parameters**

OS: MacOS Monterey (12.1)

meson --version
0.61.1
ninja --version
1.10.2

**Comment by eli-schwartz** [comment]
Currently we just stuff the stdout into an `xml.etree.ElementTree.SubElement(suite, 'system-out').text`. This already escapes common markup characters.

What would be the correct way to escape ASCII character 07 "terminal bell"? Not an HTML entity... does CDATA work for this?

**Comment by dcbaker** [comment]
we might need to call `str.encode('ascii', 'xmlcharrefreplace')` here

**Comment by eli-schwartz** [comment]
That won't do anything, it produces identical results to `str.encode('utf-8')` in this case. That codec may not be intended to produce valid XML, just XML that has had XML *markup* encoded? i.e. does it actually do anything that ElementTree doesn't do already?

**Comment by anarazel** [comment]
In xml 1.0, what the files claims to be, there is no valid encoding for a few control characters, including \x07. And even in XML 1.1, which corrected that \a, the null byte is still not encodeable. But could be part of test output, I think? Perhaps the easiest would be to just to intentionally double-encode such characters? Arguably that'd be better anyway, since they can't be seen, but could very well be the cause for a test failure.

**Comment by ePirat** [comment]
I ran into the same issue for `\r` (Carriage return).

**Comment by nbyavuz** [comment]
I have started working on that issue and came up with this solution:

```python
def double_encode_no_valid_chars(stream: [bytes]) -> [bytes]:
    no_valid_encoding_chars = [b'\x07']
    for char in no_valid_encoding_chars:
        stream = stream.replace(char, \
            char.decode('utf-8').encode('unicode_escape'))
    return stream

def decode(stream: T.Union[None, bytes]) -> str:
    if stream is None:
        return ''
    stream = double_encode_no_valid_chars(stream)
    try:
        return stream.decode('utf-8')
    except UnicodeDecodeError:
        return stream.decode('iso-8859-1', errors='ignore')
```

Does this solution sound correct to you or should I try something else?

**Comment by anarazel** [comment]
An alternative to double-encoding could be to invent a fake xml namespace for encoding of non-encodable bytes, like:
```xml
<?xml version='1.0' encoding='utf-8'?>
<testsuite xmlns:b="https://mesonbuild.com/byte">
	Unencodable byte follows: <b:b>07</b:b>
</testsuite>
```
But I'm not sure that's really an improvement over double encoding.

**Comment by jpakkane** [comment]
return stream.decode('iso-8859-1', errors='ignore')

This loses information silently. One possible option would be to use `replace` and store the original data in a separate tag as uuencoded data.

**Comment by anarazel** [comment]
I don't think information loss is a huge issue here - it'd just be removed from testlog.junit.xml, not everywhere else. It'd be good to make it apparent that data has been replaced though. To that, it seems using � / `\ufffd` would make it clear enough?

**Comment by 3v1n0** [comment]
We got a similar problem in GLib too for jobs compiled in `msvc` (and so running in windows):
 - Error: `XML Parsing Error: not well-formed`
 - CI job: https://gitlab.gnome.org/GNOME/glib/-/jobs/2345921
 - Affected artifact: https://gnome.pages.gitlab.gnome.org/-/glib/-/jobs/2345921/artifacts/_build/meson-logs/testlog.junit.xml (line 17545)

Problematic contents:

```
***** C:\_R\_BUILDS\K3_3MUAB\0\GNOME\GLIB\SUBPROJECTS\PCRE2-10.40\TESTDATA\grepoutput
  607:  [0mRC=0
  608:  1:[1;31mtriple:        t1_txt  s1_tag  s_txt   p_tag   p_txt   o_tag   o_txt
  609:  
  610:  [0m6:[1;31mtriple:    t3_txt  s2_tag  s_txt   p_tag   p_txt   o_tag   o_txt
  611:  
  612:  [0m8:[1;31mtriple:    t4_txt  s1_tag  s_txt   p_tag   p_txt   o_tag   o_txt
  613:  
  614:  [0m13:[1;31mtriple:   t6_txt  s2_tag  s_txt   p_tag   p_txt   o_tag   o_txt
  615:  
  616:  [0mRC=0
  617:  triple: t1_txt  s1_tag  s_txt   p_tag   p_txt   o_tag   o_txt
  618:  
  619:  triple: t3_txt  s2_tag  s_txt   p_tag   p_txt   o_tag   o_txt
  620:  
  621:  triple: t4_txt  s1_tag  s_txt   p_tag   p_txt   o_tag   o_txt
  622:  
  623:  triple: t6_txt  s2_tag  s_txt   p_tag   p_txt   o_tag   o_txt
  624:  
  625:  RC=0
  626:  1:triple:       t1_txt  s1_tag  s_txt   p_tag   p_txt   o_tag   o_txt
  627:  
  628:  6:triple:       t3_txt  s2_tag  s_txt   p_tag   p_txt   o_tag   o_txt
  629:  
  630:  8:triple:       t4_txt  s1_tag  s_txt   p_tag   p_txt   o_tag   o_txt
  631:  
  632:  13:triple:      t6_txt  s2_tag  s_txt   p_tag   p_txt   o_tag   o_txt
  633:  
  634:  RC=0
  635:  ---------------------------- Test 71 -----------------------------
***** TESTTRYGREP
  608:  [0mRC=0
  609:  ---------------------------- Test 71 -----------------------------
*****

```
