### ISSUE TITLE
Proposed wayland module

### ISSUE THREAD

**Issue by markbolhuis** [mesonbuild/meson#9895]
## Summary
I'm proposing a wayland module that can invoke wayland-scanner and generate .c and .h files from xml definitions.
It would look for xml files in `pkgdatadir` from `wayland-protocols.pc` and could look for local files in the project repo.

## Proposed API
```meson
list[custom_target] = scan(
    str | file           xml_files...           # list of xml files - relative file path strings point locally or in wayland-protocols data dir

    # kwargs
    scope                str                    # Either 'public' or 'private' for .c generation - 'private' is the default
    client               bool                   # Generate client .h file
    server               bool                   # Generate server .h file
    search_dir           str                    # Additional search directory for xml files
)
```
`client` or `server` kwarg is required

## Example
```meson
project('hellowayland', 'c')

wl_dep = dependency('wayland-client')
wl_mod = import('wayland')

xdg_shell = wl_mod.scan('stable/xdg-shell/xdg-shell.xml', client : true)

executable('hw', 'main.c', xdg_shell, dependencies : wl_dep)
```
------------------
I'm happy to code this up, so let me know if this is something that would be accepted

**Comment by eli-schwartz** [comment]
In principle this sounds okay... is there any other function you think might be useful in such a module?

Also /cc @emersion for wayland interest

**Comment by dcbaker** [comment]
We could use this in mesa. One suggestion I have is to replace the two bools with a single string enum value, since it creates fewer error states (ie, you can’t set both to true or to false)

**Comment by emersion** [comment]
> relative file path strings point locally or in wayland-protocols data dir

Hm, how would Meson decide between these two? `staging/asdf.xml` could be in wayland-protocols or a local protocol, there's no good way to know. I'd rather not try to be too clever with implicit behavior.

Other potential questions:

- How would one go about overriding wayland-scanner or wayland-protocols with a subproject? Will it Just Work™?
- Non-C languages: upstream wayland-scanner should def be used for C, but it's unclear what to use for other languages. Do we need to care about Rust, Zig or C++?

**Comment by emersion** [comment]
> Hm, how would Meson decide between these two?

Maybe we can force users to set `search_dir: "."` to pick a local protocol.

Another question: how would one go about providing a wayland-scanner or wayland-protocols version constraint?

**Comment by eli-schwartz** [comment]
> * How would one go about overriding wayland-scanner or wayland-protocols with a subproject? Will it Just Work™?

`override_find_program()` from the subproject, I assume. The gnome module already does this (if it isn't overridden, it should look up the dependency and retrieve the relevant variables e.g. `g_ir_scanner`, `g_ir_compiler`...)

> Another question: how would one go about providing a wayland-scanner or wayland-protocols version constraint?

If it's not a kwarg on the module method, users could look up the dependency first, with the required version.

**Comment by markbolhuis** [comment]
> We could use this in mesa. One suggestion I have is to replace the two bools with a single string enum value, since it creates fewer error states (ie, you can’t set both to true or to false)

The bools aren't mutually exclusive. I chose that for those who wanted to generate both client and server code together.
However that is probably a very niche use-case, so it's might be better not to do that.

-------------------------------------------

Anyway here's a revised proposal:

### find
Finds the xml file in the wayland-protocols pkgdatadir only, this will not search locally
This returns a file object referencing the xml file
```
file = find(
    str                 name          # name of the protocol. e.g. 'xdg-shell' or 'xdg-decoration'

    #kwargs
    stage               str           # Either 'stable', 'staging', or 'unstable' - default to 'stable'
    version             int           # Backwards incompatible version number (the 'v{n}' suffix) (no effect with stable)
)
```
## scan
This will scan the file(s) supplied and return the generated .c and .h files
```
list[custom_target] = scan(
    str|file..         xml            # Points to the xml file(s) either found with 'find' or supplied manually in the case of local xmls

    # kwargs
    scope              str            # Either 'public' or 'private' for .c generation - default to 'private' 
    type               str            # Either 'client' or 'server' for .h generation - default to 'client' 
)
```

## Example

```meson
project('hellowayland', 'c')

wl_mod = import('wayland')
wl_dep = dependency('wayland-client')

xdg_shell_xml = wl_mod.find('xdg-shell') 
xdg_decoration_xml = wl_mod.find('xdg-decoration', state : 'unstable', version : 1)
xdg_activation_xml = wl_mod.find('xdg-activation', state : 'staging', version : 1)

generated = wl_mod.scan(
    xdg_shell_xml, 
    xdg_decoration_xml, 
    xdg_activation_xml
    'protocol/my-protocol.xml'
)

executable('hw', 'main.c', generated, dependencies : wl_dep)
```
