### ISSUE TITLE
pkgconfig: `dataonly` files should be installed in `datadir`/pkgconfig

### ISSUE THREAD

**Issue by Tachi107** [mesonbuild/meson#9902]
**Describe the bug**
Since `dataonly` pkg-config files are architecture-independent they [should](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s11.html) get installed in `datadir`/pkgconfig, and not `libdir`/pkgconfig

**To Reproduce**

```meson
project('dataonly.pc')

import('pkgconfig').generate(
	name: 'dataonly',
	dataonly: true,
	description: 'Should be in $prefix/share/pkgconfig'
)
```

```sh
$ tree install_prefix
install_prefix
└── lib
   └── x86_64-linux-gnu
      └── pkgconfig
         └── dataonly.pc
```

**Expected behavior**
The .pc file should get installed in $prefix/share/pkgconfig

**system parameters**
* Build type: native
* OS: Debian Testing
* Python version: 3.9.10
* Meson version: 0.61.1
* Ninja version: 1.10.1

**Comment by eli-schwartz** [comment]
It probably should, but no one thought to mention that when #5775 was reviewed.

**Comment by Tachi107** [comment]
Maybe nobody noticed, but I don't think that installing the header to the library dir would ever be correct
