### ISSUE TITLE
Documentation: meson object documentation gone?

### ISSUE THREAD

**Issue by phillipjohnston** [mesonbuild/meson#9922]
The meson object used to be documented in the reference manual, but now I cannot see what's available through it. All it says is:

> The meson object allows you to introspect various properties of the system. This object is always mapped in the meson variable.

https://mesonbuild.com/Reference-manual_builtin_meson.html

**Comment by eli-schwartz** [comment]
https://github.com/mesonbuild/mesonbuild.github.io/commit/6bf1ff5df33e5235a62fc4a5a52ad97070d84858

> Showing 1,532 changed files with 871 additions and 10,596 deletions. 

This seems wrong... likely caused (both due to the nature of the change, and due to the timing) by #9800

**Comment by eli-schwartz** [comment]
It's back!

**Comment by phillipjohnston** [comment]
Thanks!
