### ISSUE TITLE
[Java/JAR] Cannot bundle resources files

### ISSUE THREAD

**Issue by sardemff7** [mesonbuild/meson#9945]
**Describe the bug**
One cannot bundle resources files (images, audio, properties or other arbitrary files) in a JAR via Meson’s `jar()` function

**To Reproduce**
```meson
project('java-project', 'java', version : '0.1')
jar('project', 'com.example.Main.java', 'com.example.icon.png')
```

**Expected behavior**
Any resource file would be included in the JAR file as-is

**system parameters**
* Native build
* CentOS 7
* Python 3.6.8
* Meson 0.55.1
* Ninja 1.10.2

Ping @tristan957 as asked :-)

**Comment by tristan957** [comment]
Can you leave a link to website which documents the jar command and adding resources?

**Comment by sardemff7** [comment]
Here is [the jar manual](https://docs.oracle.com/javase/7/docs/technotes/tools/windows/jar.html) though basically it’s a fancy `zip` wrapper and it actually accepts any file, AFAICT

**Comment by dcbaker** [comment]
@tristan957  there is a resources keyword argument used by c#, not sure if the idea of resources is equivalent though

**Comment by tristan957** [comment]
@dcbaker I want to pick your brain a bit. Maven uses the well-known `src/main/resources` folder as the root for all resources which are to be included in the JAR. Right now I am working on adding `java_resources` to `jar()` where `java_resources` is a `T.List[mesonlib.FileOrString]`.

My current tree structure in the test I am adding:

```
.
├── meson.build
└── src
    ├── com
    │   └── mesonbuild
    │       └── Resources.java
    ├── meson.build
    └── resources
        ├── resource1.txt
        └── subdir
            └── resource2.txt
```

`src/meson.build`
```meson
sources = files('com/mesonbuild/Resources.java')

resources = jar(
  meson.project_name(),
  sources,
  main_class: 'com.mesonbuild.Resources',
  java_resources: files(
    'resources/resource1.txt',
    'resources/subdir/resource2.txt'
  )
)
```

Contents of zip

```
$ unzip -l build/src/resources.jar
Archive:  build/src/resources.jar
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  02-25-2022 01:02   META-INF/
      102  02-25-2022 01:02   META-INF/MANIFEST.MF
        0  02-25-2022 01:02   com/
        0  02-25-2022 01:02   com/mesonbuild/
      552  02-25-2022 01:02   com/mesonbuild/Resources.class
       28  02-25-2022 01:02   src/resources/resource1.txt
       33  02-25-2022 00:53   src/resources/subdir/resource2.txt
---------                     -------
      715                     7 files
```

Ideally this becomes:

```
$ unzip -l build/src/resources.jar
Archive:  build/src/resources.jar
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  02-25-2022 01:02   META-INF/
      102  02-25-2022 01:02   META-INF/MANIFEST.MF
        0  02-25-2022 01:02   com/
        0  02-25-2022 01:02   com/mesonbuild/
      552  02-25-2022 01:02   com/mesonbuild/Resources.class
       28  02-25-2022 01:02   resource1.txt ***************
       33  02-25-2022 00:53   subdir/resource2.txt ******************
---------                     -------
      715                     7 files
```

What are your thoughts here on the best way to solve this? Seems like it would be useful to just take a directory similar to Maven, but then you can't enumerate the files that would trigger a rebuild of the JAR. Almost thinking this could benefit from your `structured_sources()` PR where Meson copies the resources into the build tree. Not sure. Let me know what you think :).

**Comment by tristan957** [comment]
Side note. There seems to be a bug in meson if you move the contents of that meson.build file into the root meson.build file where the class file gets generated in `$PRIVATE_DIR/com/mesonbuild/Resources.class`, but meson writes `$PRIVATE_DIR/src/com/mesonbuild/Resources.class` to the build.ninja file. This leads an always dirty build.

```ninja
build resources.jar.p/src/com/mesonbuild/Resources.class: java_COMPILER ../src/com/mesonbuild/Resources.java
 ARGS = -g -d resources.jar.p -s resources.jar.p -sourcepath '/home/tristan957/Projects/meson/test$ cases/java/10$ resources:/home/tristan957/Projects/meson/test$ cases/java/10$ resources/build:/home/tristan957/Projects/meson/test$ cases/java/10$ resources/build'
```

```
$ ninja -C build/ -d explain
ninja: Entering directory `build/'
ninja explain: output resources.jar.p/src/com/mesonbuild/Resources.class doesn't exist
ninja explain: resources.jar.p/src/com/mesonbuild/Resources.class is dirty
ninja explain: resources.jar is dirty
[2/2] Creating JAR resources.jar
```

**Comment by dcbaker** [comment]
@tristan957 you could do something like a `java_resource_root` keyword I guess. Something like:
```meson
resources = jar(
  meson.project_name(),
  sources,
  main_class: 'com.mesonbuild.Resources',
  java_resources: files(
    'resources/resource1.txt',
    'resources/subdir/resource2.txt'
  ),
  java_resource_root : 'resources',
)
```

**Comment by tristan957** [comment]
That could work. Do you think structured_sources() would make this a little bit cleaner however?
