### ISSUE TITLE
`meson wrap install range-v3` doesn't provide range-v3 dependency

### ISSUE THREAD

**Issue by B4mbus** [mesonbuild/meson#9951]
I declare dependencies as follows:
```meson
dependencies = [
  dependency('threads'),

  dpp_sub.dependency('dpp'),

  dependency('fmt'),
  dependency('spdlog'),
  dependency('range-v3')
]
```
and all of them work, it either searches for system ones or fallbacks for subprojects that I install with `meson wrap install dep` (specifically - fmt, spdlog and range-v3).

When setting up the build directory I get the following error:
```
WARNING: Subproject 'range-v3' did not override 'range-v3' dependency and no variable name specified
Dependency range-v3 from subproject subprojects/range-v3-0.10.0 found: NO

meson.build:27:0: ERROR: Dependency 'range-v3' is required but not found.
```
it's only for range-v3.

I looked into the wrap files and all files have the `provide` section, e.g. fmt:
```ini
[wrap-file]
directory = fmt-8.0.1
source_url = https://github.com/fmtlib/fmt/archive/8.0.1.tar.gz
source_filename = fmt-8.0.1.tar.gz
source_hash = b06ca3130158c625848f3fb7418f235155a4d389b2abc3a6245fb01cb0eb1e01
patch_filename = fmt_8.0.1-1_patch.zip
patch_url = https://wrapdb.mesonbuild.com/v2/fmt_8.0.1-1/get_patch
patch_hash = 8fab9a5d4d0971770262fef3149ef8764e5c7ba717f59afef119731197ec4ec4

[provide]
fmt = fmt_dep
```

but `range-v3` does not do that. I can add that myself, but it's not desired for the wrap system to *not* provide dependencies names correctly. Could this be my mistake or is it a meson's bug?

Info:
meson's version - 0.61.1
range-v3 version - 0.10.0

**Comment by jpakkane** [comment]
The `[provide]` entry is a fairly recent addition. Many of the wraps in WrapDB thus do not have provide entries because they have not been updated since (nowadays we have CI tests that validates that all new wraps have a `provide` entry). Please file a PR against the WrapDB repo that adds the missing entry (and updates the releases json file to create a new release) to get that properly added.

Thanks.
