### ISSUE TITLE
System Lockup When Passing /dev/zero as cross_file

### ISSUE THREAD

**Issue by gilmorem560** [mesonbuild/meson#9954]
This is a very minor issue but one I figured was worth mentioning as I haven't seen it mentioned in the issue tracker. When passing /dev/zero as --cross_file, I've found that this just about immediately locks up the system. Understandably so, probably overflows the reader almost instantly.

If you want more specifics, I was building https://github.com/ksh2020/ksh with

```
CC=aarch64-linux-musl-cc meson --prefix /usr --cross_file /dev/zero
```

I was able to pull off what I wanted with /dev/null instead. I could do cross_file right or I could just be extremely lazy...anywho, if nothing else, hopes this saves someone else from an annoying lock.

**Comment by eli-schwartz** [comment]
I think there is probably nothing to do about this. In general, there's not many good uses for /dev/zero although /dev/null is a popular file with many, many uses.

**Comment by gilmorem560** [comment]
I mean, if nothing else, might I suggest an escape that prevents using /dev/zero as a cross_file? Unless there is a specific use case in which this is valid, a simple "that isn't allowed" could save someone a major headache if they inadvertently (or adventurously) try this and suddenly their entire machine locks up without explanation. Figured the suggestion was worth posing.

**Comment by eli-schwartz** [comment]
You'd get the same problem with several other special files in /dev, such as "full", "random", or "urandom", and any block device would also be pretty bad news except they will *probably* fail with permission denied.

What should meson do -- hardcode those filenames in a highly specific function and abort early? What happens if someone uses mknod to create one of these special files in another location? What happens if someone symlinks ./meson.build to the special file instead of passing it as the --cross-file option?

Use of /dev/zero in any program at all has been known to lock up the machines of adventurous individuals. So has /dev/random. It's generally best to only use it, ever, as a data source with a program like `dd` or `head with options to limit the number of bytes to read, or alternatively, use it as a disposable data sink.

**Comment by gilmorem560** [comment]
Look I'm just communicating an issue I saw, as well as a succinct solution that would prevent a real world issue. If you really deem it someone else's problem, it's not my software, but this trend of leaving mystery issues to pop up in software with no warning, error messaging, or any other communications to end users contributes heavily to the high barriers to entry in technical fields. Expect everyone in the world to know that a read from /dev/zero is a problem? I know that, you know that, but not every person consuming the Meson software should have to be a Unix expert to use it. If I go and code this myself and raise a PR, would anyone actually bother to look at it? Or are deadlocks of someone's entire operating system perfectly acceptable?

**Comment by jpakkane** [comment]
Let's look at this from a different angle instead. Why are you passing that file as a cross file? There is no possible way it could work. An empty file is not a valid cross file (or should not be, if it is then that is a bug) because you must always define at least the cross platform and a compiler.

**Comment by gilmorem560** [comment]
Well if we want to ask that, then my question would be why is passing --cross_file <xyz> necessary to cross compile? I ran the command simply with CC set to my cross-compiler and the build fails saying that it's not in cross-compile mode, prompting me for a cross_file that obviously wasn't needed as passing --cross_file /dev/null with CC=aarch64-linux-musl-cc leads to a cross build using that compiler.

See what I mean about this being convoluted, how does anyone expect someone that *doesn't* know what we know to be able to use this? This is completely inaccessible to the average person, there shouldn't be this high of a technical barrier to entry, so how about we treat this like what it is:

We have the privilege of knowing the nitty gritties to navigate this issue. Most people don't. I'm making a suggestion that might actually make this more approachable to the average person that doesn't know the intimate particulars of /dev/zero being an endless stream with no EOF or that passing a dummy argument to this inexplicably required cross_file argument satisfies whatever it is that then allows an already provided cross-compiler to work. Think about people that haven't had the opportunities you've had to learn for a change, you can go on all day and night about what people should know, but the fact of the matter is, that doesn't get knowledge or capability into peoples' hands, recognizing the power you have to work towards more equitable and accessible software does. Again, if I stage a pull request that prevents /dev/zero from being passed as a cross_file, would it actually be considered? As much as folks benefit from free software, they sure are quick to turn around and not then pay it forward to people who know less than them or may not have the opportunities to learn every angle of every single component of their operating environment just to use a build system.

**Comment by jpakkane** [comment]
> Well if we want to ask that, then my question would be why is passing --cross_file necessary to cross compile?

That is a good question. And for that reason [we have documentation explaining what it is and why it's needed](https://mesonbuild.com/Cross-compilation.html). 

> passing --cross_file /dev/null with CC=aarch64-linux-musl-cc leads to a cross build using that compiler

This is a bug. The cross compiler must never be inferred from envvars, only the cross file. This needs to be fixed.

> the average person that doesn't know the intimate particulars of /dev/zero being an endless stream with no EOF

The average person does not even know what `/dev/zero` is. It would only ever be used by people who have a pretty good understanding of Unix special files and earlier experience with (typically) Make-based build systems.

**Comment by gilmorem560** [comment]
That still doesn't address passing a variable to an optional endpoint causing a hard-lock that most people wouldn't be able to diagnose or even explain. I repeat, I know that, you know that, but the general person doesn't, and they're the ones that suffer when the software does something weird. I only lucked out in that I immediately caught my mistake of using an EOF-less file, want to wager how many people sit down at a computer and actually know that? I don't know what else I can say about software accessibility, but nobody should be expected to maintain a holistic understanding of everything around them to use a software tool without this sort of error. I wouldn't even care if it was that the command failed, or it timed out, or something else, but I don't see any realm in which a client application literally hard-locking someone's machine without any attempt at a solution as acceptable. Again, if I stage a pull request that prevents /dev/zero from being passed as a cross_file, would it actually be considered?

**Comment by jpakkane** [comment]
> Again, if I stage a pull request that prevents /dev/zero from being passed as a cross_file, would it actually be considered?

Sure, assuming that the check is for whether the file in question is any Unix special file rather than hardcoding the path.

**Comment by gilmorem560** [comment]
Is that what I asked? If I stage a pull request that prevents /dev/zero from being passed as a cross_file, would it actually be considered? I didn't ask to be assigned what you know needs to be done, if you know it needs to be done, then my attempt would only get in the way. I'm proposing actual action I'm willing to take, you're suggesting something that might be better but you're willing to put no work behind. Do people expect things to get done or for their personal vision to come to fruition? If the latter, sounds like you know what needs to be done to prevent this completely unacceptable hard-lock, so why not do it then? At least I'm proposing actually getting my fingers moving, you're just trying to decree what needs to be done while absolving your actual team of any responsibility. I'd gladly raise a PR for what I would do here, but I'm not going to do your work for you.

**Comment by gilmorem560** [comment]
Look, long story short, either you recognize this as a problem and engage with a solution, mine or yours, or you're letting a hard-lock persist. I can't tell you how to run your software, but I find it hard that you actually believe this is acceptable. It's not acceptable to the budding programmer it stops in their tracks while trying to learn this stuff for the first time.

**Comment by eli-schwartz** [comment]
Just checking for Unix special files doesn't really solve the problem, e.g. specifying a perfectly normal 2GB file will read 2GB of data into memory and possibly freeze your system anyway, and definitely be pretty slow. It isn't unbounded size, but large bounded sizes are not actually more than marginally better.

(Also I'm quite okay to have /dev/null work in cases where everything can be dynamically detected from the compiler...)

If we assume that "the common case is someone passing a specific path to the --cross-file argument" then I guess we could hardcode that for exclusion, but that would be "enumerating badness" and it doesn't really seem like the appealing option.

**Comment by gilmorem560** [comment]
Well whatever the case, I've raised that this is a problem, hopefully some poor kid trying to learn a thing or two finds this thread and can proceed, but I do find it incredibly disconcerting that a hard-lock like this that could be mitigated is acceptable in any way, shape, or form.
