### ISSUE TITLE
Build is failing with MSVC on GitHub Actions

### ISSUE THREAD

**Issue by khaledhosny** [mesonbuild/meson#9955]
**Describe the bug**
After GitHub Actions recently updated their Windows virtual environment, builds starts failing when using MSVC as the `.symbols` generation step with error messages like the following that does not provide much details:
```
FAILED: subprojects/freetype/freetype-6.dll.p/freetype-6.dll.symbols 
"C:\hostedtoolcache\windows\Python\3.10.1\x64\Scripts\meson" "--internal" "symbolextractor" "D:\a\libraqm\libraqm\build" subprojects/freetype/freetype-6.dll "subprojects\freetype\freetype.lib" subprojects/freetype/freetype-6.dll.p/freetype-6.dll.symbols 
```

**To Reproduce**
Does not seem to be specific to a given project, I have at least two projects that now fail to build on GitHub Actions with MSVC, examples of failing builds:
https://github.com/harfbuzz/harfbuzz/runs/5083756125?check_suite_focus=true#step:6:1040
https://github.com/HOST-Oman/libraqm/runs/5083822595?check_suite_focus=true#step:10:101

**Expected behavior**
Builds to pass (which was the case before the GitHub Actions update).

**system parameters**
Ninja and meson versions do not seem to play a factor, I have seen it failing with various versions. The details CI setup can be seen in the links above.

**Comment by khaledhosny** [comment]
This might very well not be a meson bug, but it should at least give some useful error message, the failing `symbolextractor` does not seem to output any error messages.

**Comment by eli-schwartz** [comment]
This is a bug in pip. https://github.com/pypa/pip/issues/10875

Downgrade and pin pip and it will work.

**Comment by khaledhosny** [comment]
Wow, thanks! I’ve been banging my head against the wall for days!

**Comment by eli-schwartz** [comment]
It is indeed a wonderfully non-obvious problem, yeah. Fingers crossed that pip can fix it soon...
