### ISSUE TITLE
Missing backward compat warning when passing declare_dependency() to compiler

### ISSUE THREAD

**Issue by anarazel** [mesonbuild/meson#9957]
Hi,

Starting in 0.57 one can pass declare_dependency() to compiler.has_function() etc:
```
[](https://mesonbuild.com/Release-notes-for-0-57-0.html#passing-internal-dependencies-to-the-compiler-object)Passing internal dependencies to the compiler object

Methods on the compiler object (such as compiles, links, has_header) can be passed dependencies returned by declare_dependency, as long as they only specify compiler/linker arguments or other dependencies that satisfy the same requirements.
```
Which is great!

However, there is no warning about doing so even when `meson_version: '>=0.54',` or such. It's pretty easy to accidentally break even just slightly older operating systems like Debian Bullseye. 

Regards,

Andres

**Comment by eli-schwartz** [comment]
You are absolutely correct that this should be tagged with a FeatureNew, which unfortunately may in some cases get forgotten.

I'll look into this tonight if no one beats me to it.
