### ISSUE TITLE
vala: Building with flat layout does not work

### ISSUE THREAD

**Issue by arteymix** [mesonbuild/meson#996]
It does not seem to resolve the generated header path properly:

```
[5/7] Compiling c object 'meson-out/valaprog@exe/meson-out_valaprog@exe_prog.c.o'
FAILED: meson-out/valaprog@exe/meson-out_valaprog@exe_prog.c.o 
cc  '-Imeson-out/valaprog@exe' '-fdiagnostics-color=always' '-I../prog' '-Iprog' '-Ilib' '-I../lib' '-pipe' '-w' '-O0' '-g' '-I/usr/include/glib-2.0' '-I/usr/lib64/glib-2.0/include' '-MMD' '-MQ' 'meson-out/valaprog@exe/meson-out_valaprog@exe_prog.c.o' '-MF' 'meson-out/valaprog@exe/meson-out_valaprog@exe_prog.c.o.d' -o 'meson-out/valaprog@exe/meson-out_valaprog@exe_prog.c.o' -c 'meson-out/valaprog@exe/prog.c'
meson-out/valaprog@exe/prog.c:9:21: erreur fatale : valalib.h : No such file or directory
 #include "valalib.h"
                     ^
compilation terminée.
[6/7] Generating symbol file 'meson-out/valalib@sha/meson-out/libvalalib.so.symbols'.
ninja: build stopped: subcommand failed.
```

Also, there should be some CI support to run all the test cases using the flat layout.

I'll probably look into this.

**Comment by nirbheek** [comment]
I had an opportunity to look into this in #994, but I didn't bother trying to enable the flat layout in the tests because I don't know if it's actually useful. I also expected it to be very broken. 

What's the use-case for flat layouts?

**Comment by jpakkane** [comment]
The biggest is Windows, which does not have rpath. Putting all outputs in a single dir makes dll symbol resolution work without any fiddling.

**Comment by nirbheek** [comment]
About Windows and rpath: I had a thought that instead of spending a huge amount of time making flat layouts work (which is ironically impossible on Windows because of `pdb` file naming), we could add a `mesonrun` command which sets up `PATH` as necessary for running a specific executable.

We already have a wrapper script that does this for tests; it would just be a matter of hooking into that.
