### ISSUE TITLE
meson.add_dist_script() in a subproject has MESON_PROJECT_DIST_ROOT == MESON_DIST_ROOT

### ISSUE THREAD

**Issue by kjellahl** [mesonbuild/meson#9964]
When project https://gitlab.gnome.org/GNOME/mm-common.git is a subproject,
and meson.add_dist_script() calls a Python script, and that script reads
the environment variable MESON_PROJECT_DIST_ROOT, it's equal to 
MESON_DIST_ROOT, except for the trailing slash.
For instance it's <builddir>/meson-dist/libsigc++-3.0.7/.
Should be <builddir>/meson-dist/libsigc++-3.0.7/subprojects/mm-common.

I haven't seen this behaviour with other projects as subprojects.

To reproduce the error:
```
git clone https://github.com/libsigcplusplus/libsigcplusplus.git
cd libsigcplusplus
meson --wrap-mode=forcefallback _build .
cd _build
meson configure -Dmm-common:use-network=true
ninja
meson dist --include-subprojects --no-tests
```
The dist script subprojects/mm-common/util/meson_aux/extra-dist-cmd.py
does not do what it's supposed to do because MESON_PROJECT_DIST_ROOT points to
the main project instead of subprojects/mm-common.
In the tarball, subprojects/mm-common/ChangeLog should show the latest git commit,
and there should be a subprojects/mm-common/doctags/libstdc++.tag file.

meson.is_subproject() in mm-common's meson.build shows that mm-common is a subproject.

I added some calls to print() in run_dist_scripts() in meson/mesonbuild/mdist.py.
subprojects= {'mm-common': 'subprojects/mm-common'}. All dist scripts have
d.subproject='',  subdir='', even the one that belongs to subprojects/mm-common.

I've tested with meson 0.60.3 and 0.61.99.

**Comment by eli-schwartz** [comment]
It is a bug in dist scripts that are built executables or the result of find_program(), however if the dist script was specified as a string the attribute got correctly set. After the linked PR, your project seems to run correctly.

As far as I can tell, this has literally never worked.

**Comment by kjellahl** [comment]
Yes, with the patch in PR #9965 it works correctly.

I suppose my other projects worked correctly as subprojects because they
still contain the deprecated meson.add_dist_script(python3.path(), ...)
instead of meson.add_dist_script(python3, ...).
