### ISSUE TITLE
no include directories with precompiled headers ?

### ISSUE THREAD

**Issue by trashuj** [mesonbuild/meson#999]
Hi,

i have a project structure tree that looks like:
lib/
&nbsp;&nbsp;&nbsp;&nbsp;inc
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;lib
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;lib.h
&nbsp;&nbsp;&nbsp;&nbsp;src
&nbsp;&nbsp;&nbsp;&nbsp;pch
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;stdafx.h
app/
&nbsp;&nbsp;&nbsp;&nbsp;inc
&nbsp;&nbsp;&nbsp;&nbsp;src
&nbsp;&nbsp;&nbsp;&nbsp;pch
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;stdafx.h

what i do (maybe it's a bad idead?), is that I include all the headers in my lib inside lib.h.
that way, any app using that needs lib can just include lib/lib.h.
i'm trying to use precompiled headers so that
lib/pch/stdafx.h contains lib.h
app/pch/stdafx.h also contains lib.h

meson.build for the app is setup like this:
executable( 'app'
            , src
            , include_directories : [lib_inc]
            , link_with : lib_lib
            , cpp_pch : ['pch/stdafx.h', 'pch/stdafx.cpp'])

problem is when i'm compiling, i have this error:
Precompiling header ../app/pch/stdafx.h
FAILED: app/app@exe/stdafx.h.pch 
clang++  "-Wall" "-Winvalid-pch" "-Wnon-virtual-dtor" "-std=c++11" "-DWINDOWS" "-DIX_DEBUG" "-O0" "-g" "-MMD" "-MQ" app/app@exe/stdafx.h.pch "-MF" "app\\app@exe\\stdafx.h.pch.d" -o app/app@exe/stdafx.h.pch -c ../app/pch/stdafx.h
clang++.exe: warning: treating 'c-header' input as 'c++-header' when in C++ mode, this behavior is deprecated
../app/pch/stdafx.h:5:10: fatal error: 'lib/lib.h' file not found
#include <lib/lib.h>

seems to me that the include_directories doesnt apply to precompiled headers. is it expected?
bonus: how can i get rid of the warning?
note that i'm running a meson.build script from the root directory, with subdir for lib and app.

thanks a lot in advance,
best regards,
Uj

**Comment by jpakkane** [comment]
The fact that includes are not used may be a bug. However it is strongly recommended that you don't include your own headers in pch, only those that come from "the system". If you change any header, it will trigger a recompilation of every source in your target, not just those that manually include just that one target.

**Comment by trashuj** [comment]
thanks for your fast reply :-)

I know, but it's worth it considering I don't modify my libs so often.

**Comment by trashuj** [comment]
Hi again,

i moved all "systems include" inside the stdafx and use my includes outside, but now i ran into another issue.
I have several libs and exes, like core (types and containers), display(openGL), sound, some apps, some tools..
How can i use more than 1 pch file?
as far as i understand pch have to be specified in each target, and we can't specify more than 2 pch files in the static_library() and executable() functions (in which i already specify the stdafx.h and stdafx.cpp for visual studio compliance)

for example, depending on the exes, some will need openGL, some dont.
Ideally i would use a separate pch for my core and display libs. Also note that the display lib depends on the core lib and would need to be aware of its pch.
Ideally pch files would be inherited when I link with a lib, so i dont have to specify it again per target.

what do you think?
thanks a lot in advance.

**Comment by jpakkane** [comment]
The problem with PCH is that every compiler does it differently. Trying to come up with a scheme that does inheritance and all that is very difficult (possibly impossible). This means that you have to manually write a pch file per each target. Fortunately this is not such a big issue because you don't need to change PCH files often and this allows you to tailor each target's PCH includes to match what they need.

**Comment by nioncode** [comment]
Should we close this, because the recommendation is to write a separate PCH for each target?

**Comment by jpakkane** [comment]
The actual bug in this is that we don't set up dependency paths in pch compiles to be identical to ones in regular builds.
